define([], function () {
  return {
    Designer_Color_Blue: "أزرق",
    Designer_Color_Teal: "أزرق مخضر",
    Designer_Color_Green: "أخضر",
    Designer_Color_Purple: "أرجواني",
    Designer_Color_Magenta: "أرجواني فاتح",
    Designer_Color_Red: "أحمر",
    Designer_Color_Orange: "برتقالي",
    Designer_Color_Gray: "رمادي",
    Designer_Settings_LayoutSinglePage: "جميع الأسئلة في صفحة واحدة",
    Designer_Settings_LayoutWizard: "قسم واحد لكل خطوة (معالج)",
    Designer_Settings_Title: "إعدادات النموذج",
    Designer_Common_Apply: "تطبيق",
    Designer_Common_Cancel: "إلغاء",
    Designer_Settings_TabBasics: "الأساسيات",
    Designer_Settings_FormTitle: "عنوان النموذج",
    Designer_Settings_Description: "الوصف",
    Designer_Settings_Layout: "التخطيط",
    Designer_Settings_NumberQuestions: "ترقيم الأسئلة",
    Designer_Settings_ShuffleQuestions: "ترتيب الأسئلة عشوائيًا لكل مستجيب",
    Designer_Settings_ShowProgressBar: "إظهار شريط التقدم",
    Designer_Settings_TabAppearance: "المظهر",
    Designer_Settings_AccentColor: "لون التمييز",
    Designer_Settings_CustomColorTitle: "لون مخصص",
    Designer_Settings_CustomColorAria: "لون تمييز مخصص",
    Designer_Settings_AccentHint: "تُضبط ألوان التمييز تلقائيًا لتحقيق التباين على المواقع الداكنة، بحيث يظل النموذج مقروءًا مهما كان نسق الصفحة.",
    Designer_Settings_ShowHeader: "إظهار رأس النموذج",
    Designer_Settings_HeaderIcon: "أيقونة الرأس",
    Designer_Settings_TabAfterSubmit: "بعد الإرسال",
    Designer_Settings_SubmitButtonText: "نص زر الإرسال",
    Designer_Settings_SubmitPlaceholder: "إرسال",
    Designer_Settings_ThankYouTitle: "عنوان رسالة الشكر",
    Designer_Settings_ThankYouPlaceholder: "شكرًا لك!",
    Designer_Settings_ThankYouMessage: "رسالة الشكر",
    Designer_Settings_ShowSubmitAnother: "إظهار زر \"إرسال استجابة أخرى\"",
    Designer_Settings_TabNotifications: "الإشعارات",
    Designer_Settings_EmailEachResponseTo: "إرسال كل استجابة بالبريد الإلكتروني إلى",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "يتلقى الأشخاص في مؤسستك كل استجابة عبر البريد الإلكتروني مع رابط إلى عنصر القائمة",
    Designer_Settings_RespondentReceipt: "إرسال نسخة من إجابات المستجيبين إليهم بالبريد الإلكتروني",
    Designer_Settings_NotificationsInfo: "تستخدم الإشعارات خدمة البريد الخاصة بـ SharePoint، لذا يجب أن يكون المستلمون مستخدمين في مؤسستك. تُتجاهل العناوين الخارجية بصمت.",
    Designer_Settings_TabAccess: "الوصول",
    Designer_Settings_OpenFrom: "الفتح اعتبارًا من",
    Designer_Settings_OpenImmediately: "الفتح فورًا",
    Designer_Settings_CloseAfter: "الإغلاق بعد",
    Designer_Settings_NeverClose: "عدم الإغلاق أبدًا",
    Designer_Settings_ClearDates: "مسح التواريخ",
    Designer_Settings_DatesInverted: "تاريخ الإغلاق يسبق تاريخ الفتح أو يساويه، لذا لن يقبل النموذج أي استجابات.",
    Designer_Settings_MaxResponses: "التوقف بعد هذا العدد من الاستجابات",
    Designer_Settings_NoLimit: "بلا حد",
    Designer_Settings_OneResponsePerPerson: "السماح باستجابة واحدة فقط لكل شخص",
    Designer_Settings_AllowSaveDraft: "السماح للمستجيبين بحفظ مسودة والإكمال لاحقًا",
    Designer_Settings_ClosedMessage: "الرسالة المعروضة عند إغلاق النموذج",
    Designer_Settings_ClosedMessagePlaceholder: "لم يعد هذا النموذج يقبل استجابات.",
    Designer_Settings_AccessInfo: "يفرض النموذج هذه الحدود، وليس SharePoint. يمكن لأي شخص لديه إذن بإضافة عناصر إلى قائمة الاستجابات أن يضيف عنصرًا مباشرة عبر القائمة.",
    Designer_Field_StyleInfo: "معلومات (لون التمييز)",
    Designer_Field_StyleSuccess: "نجاح (أخضر)",
    Designer_Field_StyleWarning: "تحذير (كهرماني)",
    Designer_Field_StylePlain: "نص عادي",
    Designer_Field_StyleDivider: "خط فاصل",
    Designer_Field_IconStars: "نجوم",
    Designer_Field_IconHearts: "قلوب",
    Designer_Field_IconThumbs: "إعجاب",
    Designer_Field_FormatPlain: "رقم عادي",
    Designer_Field_FormatCurrency: "عملة",
    Designer_Field_FormatPercent: "نسبة مئوية",
    Designer_Field_UntitledQuestion: "سؤال بلا عنوان",
    Designer_Field_DeletedQuestion: "سؤال محذوف",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} و{value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "أو",
    Designer_Rule_JoinAll: "و",
    Designer_Rule_Preview: "يظهر عندما {conditions}.",
    Designer_Field_Yes: "نعم",
    Designer_Field_No: "لا",
    Designer_Field_When: "عندما",
    Designer_Field_SelectValue: "حدد قيمة",
    Designer_Field_DateValuePlaceholder: "YYYY-MM-DD أو \"today\"",
    Designer_Field_ValuePlaceholder: "القيمة",
    Designer_Field_UpperBound: "الحد الأعلى",
    Designer_Field_RemoveCondition: "إزالة هذا الشرط",
    Designer_Field_FormulaInvalid: "تعذر حساب هذه الصيغة. تحقق من الأقواس والعوامل.",
    Designer_Field_FormulaMissing: "هذه الأسئلة غير موجودة: {names}.",
    Designer_Field_FormulaPreview: "عندما تكون كل المدخلات 10، تعرض هذه الصيغة {value}.",
    Designer_Field_HintYesNo: "استخدم \"yes\" أو \"no\"",
    Designer_Field_HintMultiDefault: "افصل بين القيم الافتراضية المتعددة باستخدام ;",
    Designer_Field_HintSingleDefault: "يجب أن تطابق أحد الخيارات",
    Designer_Field_HintDate: "استخدم \"today\" أو تاريخًا مثل 2026-03-01",
    Designer_Field_HintTime: "استخدم \"now\" أو وقتًا مثل 09:30",
    Designer_Field_QuestionSettings: "إعدادات السؤال",
    Designer_Field_Appearance: "المظهر",
    Designer_Field_Style: "النمط",
    Designer_Field_ImageUrl: "عنوان URL للصورة (اختياري)",
    Designer_Field_Content: "المحتوى",
    Designer_Field_BasicFormatting: "التنسيق الأساسي مسموح: غامق، مائل، قوائم وروابط.",
    Designer_Field_TabOptions: "الخيارات",
    Designer_Field_TabBranching: "التفرع",
    Designer_Field_BranchingNeedsQuestion: "أضف سؤالًا آخر أولًا — يحتاج التفرع إلى ما يعتمد عليه.",
    Designer_Field_BranchingToggle: "إظهار هذا السؤال فقط عند تطابق إجابات أخرى",
    Designer_Field_Match: "مطابقة",
    Designer_Field_MatchAll: "كل هذه",
    Designer_Field_MatchAny: "أي من هذه",
    Designer_Field_AddCondition: "إضافة شرط",
    Designer_Field_TabValidation: "التحقق",
    Designer_Field_HelpText: "نص المساعدة",
    Designer_Field_HelpTextPlaceholder: "يظهر أسفل تسمية السؤال",
    Designer_Field_CheckboxLabel: "تسمية خانة الاختيار",
    Designer_Field_Placeholder: "نص العنصر النائب",
    Designer_Field_DefaultAnswer: "الإجابة الافتراضية",
    Designer_Field_RequiredMessage: "رسالة مخصصة للحقل المطلوب",
    Designer_Field_RequiredMessagePlaceholder: "{title} مطلوب",
    Designer_Field_ThisQuestion: "هذا السؤال",
    Designer_Field_RequiredMessageDescription: "تظهر بدلًا من الرسالة القياسية عند ترك هذا السؤال فارغًا",
    Designer_Field_ReadOnly: "للقراءة فقط (يمكن أن تأتي الإجابة من رابط معبأ مسبقًا فقط)",
    Designer_Field_ValidationRules: "قواعد التحقق",
    Designer_Field_MaxLength: "الحد الأقصى للطول",
    Designer_Field_Pattern: "يجب أن يطابق هذا النمط",
    Designer_Field_PatternDescription: "تعبير نمطي. اتركه فارغًا لعدم التحقق من النمط.",
    Designer_Field_PatternMessage: "الرسالة عند عدم تطابق النمط",
    Designer_Field_PatternMessagePlaceholder: "هذه الإجابة ليست بالتنسيق المتوقع",
    Designer_Field_Format: "التنسيق",
    Designer_Field_UnitSuffix: "الوحدة المعروضة بعد القيمة",
    Designer_Field_UnitSuffixPlaceholder: "كجم، ساعات، عناصر…",
    Designer_Field_Minimum: "الحد الأدنى",
    Designer_Field_Maximum: "الحد الأقصى",
    Designer_Field_Decimals: "المنازل العشرية",
    Designer_Field_Formula: "الصيغة",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "أشر إلى الأسئلة الأخرى بنصها بين أقواس معقوفة. تدعم + - * / ( ) وround وmin وmax وsum وavg.",
    Designer_Field_AvailableQuestions: "الأسئلة المتاحة: {questions}",
    Designer_Field_NoneYet: "لا شيء بعد",
    Designer_Field_Step: "الخطوة",
    Designer_Field_From: "من",
    Designer_Field_To: "إلى",
    Designer_Field_LowLabel: "تسمية الطرف الأدنى",
    Designer_Field_LowLabelPlaceholder: "غير محتمل إطلاقًا",
    Designer_Field_HighLabel: "تسمية الطرف الأعلى",
    Designer_Field_HighLabelPlaceholder: "محتمل للغاية",
    Designer_Field_SummarizeAs: "تلخيص على شكل",
    Designer_Field_SummarizeAverage: "المتوسط والتوزيع",
    Designer_Field_SummarizeNps: "مؤشر صافي المروّجين (يتطلب مقياسًا من 0 إلى 10)",
    Designer_Field_NpsWarning: "لا يكون مؤشر صافي المروّجين ذا معنى إلا على مقياس من 0 إلى 10. عيّن \"من\" إلى 0 و\"إلى\" إلى 10.",
    Designer_Field_NumberOfIcons: "عدد الأيقونات",
    Designer_Field_Icon: "الأيقونة",
    Designer_Field_AllowHalf: "السماح بنصف القيم",
    Designer_Field_ShowOptionsAs: "عرض الخيارات على شكل",
    Designer_Field_DisplayButtons: "أزرار مضمّنة",
    Designer_Field_DisplayDropdown: "قائمة منسدلة",
    Designer_Field_DisplayAutomatic: "تلقائي (مضمّن حتى 6 خيارات)",
    Designer_Field_AllowOther: "إضافة خيار \"أخرى\" للكتابة الحرة",
    Designer_Field_OtherLabel: "تسمية الخيار \"أخرى\"",
    Designer_Field_OtherPlaceholder: "أخرى",
    Designer_Field_ShuffleOptions: "ترتيب الخيارات عشوائيًا لكل مستجيب",
    Designer_Field_MinSelections: "الحد الأدنى للتحديدات",
    Designer_Field_MaxSelections: "الحد الأقصى للتحديدات",
    Designer_Field_SourceList: "القائمة المصدر",
    Designer_Field_ChooseList: "اختر قائمة",
    Designer_Field_LookupColumn: "العمود المراد قراءة الخيارات منه",
    Designer_Field_ChooseColumn: "اختر عمودًا",
    Designer_Field_ChooseListFirst: "اختر قائمة أولًا",
    Designer_Field_LookupFilter: "عامل التصفية (اختياري)",
    Designer_Field_LookupFilterDescription: "عامل تصفية OData يحدد عناصر المصدر التي تصبح خيارات",
    Designer_Field_LookupInfo: "تخزّن الإجابات نص الخيار وليس رابطًا إلى عنصر المصدر، لذا تبقى الاستجابات مقروءة حتى لو تغيّرت القائمة المصدر لاحقًا.",
    Designer_Field_ConsentText: "الشروط المعروضة أعلى خانة الاختيار",
    Designer_Field_AllowMultiplePeople: "السماح بعدة أشخاص",
    Designer_Field_AllowGroups: "السماح بالمجموعات أيضًا",
    Designer_Field_IncludeTime: "تضمين وقت من اليوم",
    Designer_Field_TimeStep: "خطوة الوقت (بالدقائق)",
    Designer_Field_MaxFiles: "الحد الأقصى للملفات",
    Designer_Field_MaxFileSize: "الحد الأقصى لحجم كل ملف (ميغابايت)",
    Designer_Field_AcceptedTypes: "أنواع الملفات المقبولة",
    Designer_Field_AcceptedTypesDescription: "امتدادات مفصولة بفواصل. اتركه فارغًا لقبول كل ما يسمح به SharePoint.",
    Designer_Field_FilesInfo: "تُحفظ الملفات كمرفقات على عنصر الاستجابة. يحظر SharePoint بعض الامتدادات (مثل .exe) بغض النظر عما تسمح به هنا.",
    Designer_Field_Rows: "الصفوف",
    Designer_Field_ProvisionedNote: "لهذا السؤال عمود قائمة موجود بالفعل ({name}). الإعدادات التي تغيّر نوع العمود مقفلة — كرّر السؤال إذا احتجت إلى نوع مختلف.",
    Designer_Category_Text: "نص",
    Designer_Category_Choice: "اختيار",
    Designer_Category_Scales: "مقاييس",
    Designer_Category_Date: "تاريخ",
    Designer_Category_People: "أشخاص",
    Designer_Category_Advanced: "متقدم",
    Designer_Category_Layout: "التخطيط",
    Designer_Menu_CommonPresets: "إعدادات مسبقة شائعة",
    Designer_Menu_AllTypes: "جميع أنواع الأسئلة",
    Designer_Menu_ChangeType: "تغيير النوع",
    Designer_Menu_TypeLockedTitle: "عمود القائمة موجود بالفعل، لذا النوع مقفل. كرّر السؤال لتغييره.",
    Designer_Menu_MoreSettings: "التفرع والتحقق والمزيد",
    Designer_Menu_InsertBelow: "إدراج سؤال أدناه",
    Designer_Card_Duplicate: "تكرار",
    Designer_Card_DeleteQuestion: "حذف السؤال",
    Designer_Outline_Aria: "مخطط الأسئلة",
    Designer_Outline_QuestionCountOne: "{count} سؤال",
    Designer_Outline_QuestionCountOther: "{count} أسئلة",
    Designer_Outline_IssuesTitle: "{count} مشكلة (مشكلات) للمراجعة",
    Designer_Outline_Find: "بحث عن سؤال",
    Designer_Outline_Empty: "لا توجد أسئلة بعد.",
    Designer_Section_DefaultTitle: "القسم {number}",
    Designer_Card_Question: "سؤال",
    Designer_Card_BranchingTitle: "يظهر هذا السؤال فقط عند تطابق قاعدة تفرع",
    Designer_Card_BranchingChip: "التفرع",
    Designer_Card_LiveTitle: "عمود القائمة موجود، لذا النوع مقفل",
    Designer_Card_LiveChip: "مباشر",
    Designer_Card_CheckChip: "تحقق",
    Designer_Option_Placeholder: "الخيار {number}",
    Designer_Option_LabelAria: "تسمية الخيار {number}",
    Designer_Option_ImageUrl: "عنوان URL للصورة",
    Designer_Option_ImageUrlAria: "عنوان URL لصورة الخيار {number}",
    Designer_Option_Remove: "إزالة الخيار",
    Designer_Option_RemoveAria: "إزالة الخيار {number}",
    Designer_Option_Add: "إضافة خيار",
    Designer_Option_OtherHint: "يمكن للمستجيبين أيضًا كتابة إجابة تحمل التسمية “{label}”.",
    Designer_Option_OtherFallback: "أخرى",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "إزالة",
    Designer_Grid_RemoveAria: "إزالة {label} {number}",
    Designer_Grid_Statements: "العبارات",
    Designer_Grid_Scale: "المقياس",
    Designer_Grid_AddStatement: "إضافة عبارة",
    Designer_Grid_AddScale: "إضافة مقياس",
    Designer_Width_Full: "العرض الكامل",
    Designer_Width_Half: "نصف العرض",
    Designer_Width_Third: "ثلث العرض",
    Designer_Width_Aria: "عرض السؤال",
    Designer_Card_BlockLabelPlaceholder: "تسمية الكتلة (لا تظهر للمستجيبين)",
    Designer_Card_QuestionText: "نص السؤال",
    Designer_Card_MoveUp: "نقل لأعلى",
    Designer_Card_MoveQuestionUp: "نقل السؤال لأعلى",
    Designer_Card_MoveDown: "نقل لأسفل",
    Designer_Card_MoveQuestionDown: "نقل السؤال لأسفل",
    Designer_Card_DuplicateQuestion: "تكرار السؤال",
    Designer_Card_MultipleAnswers: "إجابات متعددة",
    Designer_Card_Required: "مطلوب",
    Designer_Card_MoreOptions: "خيارات إضافية",
    Designer_Card_MoreOptionsAria: "خيارات إضافية لهذا السؤال",
    Designer_Canvas_FormTitle: "عنوان النموذج",
    Designer_Canvas_DescriptionPlaceholder: "أضف وصفًا (اختياري)",
    Designer_Canvas_DescriptionAria: "وصف النموذج",
    Designer_Canvas_EmptyTitle: "أضف سؤالك الأول",
    Designer_Canvas_EmptyBody: "اختر نوع سؤال للبدء. يمكنك إعادة ترتيب الأسئلة بسحبها، وإضافة التفرع حتى لا يرى الأشخاص إلا ما ينطبق عليهم.",
    Designer_Section_Chip: "القسم {number} من {total}",
    Designer_Section_TitlePlaceholder: "عنوان القسم",
    Designer_Section_TitleAria: "عنوان القسم {number}",
    Designer_Section_DescriptionPlaceholder: "الوصف (اختياري)",
    Designer_Section_DescriptionAria: "وصف القسم {number}",
    Designer_Section_MoveUp: "نقل القسم لأعلى",
    Designer_Section_MoveDown: "نقل القسم لأسفل",
    Designer_Section_Delete: "حذف القسم",
    Designer_Card_DragToReorder: "اسحب لإعادة الترتيب",
    Designer_Card_ReorderAria: "إعادة ترتيب {title}",
    Designer_Card_ReorderFallback: "سؤال",
    Designer_Canvas_AddNew: "إضافة جديد",
    Designer_Canvas_AddSection: "إضافة قسم",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "عنوان الشارع",
    Form_Address_Street2Placeholder: "شقة، جناح، إلخ (اختياري)",
    Form_Address_CityPlaceholder: "المدينة",
    Form_Address_StatePlaceholder: "المنطقة / المحافظة",
    Form_Address_PostalCodePlaceholder: "الرمز البريدي",
    Form_Address_CountryPlaceholder: "الدولة",
    Form_Address_StreetAria: "عنوان الشارع",
    Form_Address_Street2Aria: "سطر العنوان 2",
    Form_Address_CityAria: "المدينة",
    Form_Address_StateAria: "المنطقة أو المحافظة",
    Form_Address_PostalCodeAria: "الرمز البريدي",
    Form_Address_CountryAria: "الدولة",
    Form_Consent_DefaultLabel: "أوافق",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "تمت الإجابة عن {answered} من {total} صفوف",
    Form_Lookup_LoadError: "تعذر تحميل خيارات هذا السؤال.",
    Form_Lookup_Loading: "جارٍ تحميل الخيارات…",
    Form_Lookup_SelectOptionsPlaceholder: "حدد الخيارات",
    Form_Lookup_SelectOptionPlaceholder: "حدد خيارًا",
    Form_Person_Placeholder: "ابدأ بكتابة اسم…",
    Form_Person_SuggestedPeopleAndGroups: "الأشخاص والمجموعات المقترحون",
    Form_Person_SuggestedPeople: "الأشخاص المقترحون",
    Form_Person_NoPeopleOrGroups: "لم يتم العثور على أشخاص أو مجموعات",
    Form_Person_NoPeople: "لم يتم العثور على أشخاص",
    Form_Person_Searching: "جارٍ البحث…",
    Form_Ranking_Moved: "تم نقل {item} إلى الموضع {position} من {total}",
    Form_Ranking_MoveUp: "نقل لأعلى",
    Form_Ranking_MoveDown: "نقل لأسفل",
    Form_Ranking_MoveItemUpAria: "نقل {item} لأعلى",
    Form_Ranking_MoveItemDownAria: "نقل {item} لأسفل",
    Form_Rating_ValueText: "{value} من {max}",
    Form_Rating_NotRated: "بدون تقييم",
    Form_Rating_Clear: "مسح التقييم",
    Form_RichText_Bold: "غامق",
    Form_RichText_Italic: "مائل",
    Form_RichText_Underline: "تسطير",
    Form_RichText_BulletedList: "قائمة نقطية",
    Form_RichText_NumberedList: "قائمة مرقمة",
    Form_RichText_ClearFormatting: "مسح التنسيق",
    Form_RichText_ToolbarAria: "تنسيق النص",
    Form_File_SizeBytes: "{size} بايت",
    Form_File_SizeKb: "{size} كيلوبايت",
    Form_File_SizeMb: "{size} ميغابايت",
    Form_File_SkippedLimit: "تم تخطي \"{name}\" — الحد هو {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" ليس نوعًا مقبولًا.",
    Form_File_TooLarge: "\"{name}\" أكبر من {size} ميغابايت.",
    Form_File_AlreadyAttached: "\"{name}\" مرفق بالفعل.",
    Form_File_ReadError: "تعذرت قراءة أحد الملفات. حاول إرفاقه مرة أخرى.",
    Form_File_HintMaxSize: "حتى {size} ميغابايت لكل ملف",
    Form_File_HintOneFile: "ملف واحد",
    Form_File_HintMaxFiles: "بحد أقصى {count} ملفات",
    Form_File_Reading: "جارٍ قراءة الملفات…",
    Form_File_DropPrompt: "أفلت الملفات هنا، أو انقر للاستعراض",
    Form_File_Remove: "إزالة {name}",
    Form_Signature_Alt: "التوقيع",
    Form_Signature_AriaSigned: "{label} — تم التوقيع",
    Form_Signature_AriaEmpty: "{label} — فارغ",
    Form_Signature_Clear: "مسح",
    Form_Signature_Signed: "تم التوقيع",
    Form_Signature_Prompt: "وقّع أعلاه باستخدام الماوس أو القلم أو الإصبع",
    Form_Time_Placeholder: "حدد وقتًا",
    Form_Field_DatePlaceholder: "حدد تاريخًا",
    Form_Field_TimeAriaWithLabel: "{label} — الوقت",
    Form_Field_TimeAria: "الوقت",
    Form_Field_OtherDefault: "أخرى",
    Form_Field_SelectOptionsPlaceholder: "حدد الخيارات",
    Form_Field_PleaseSpecify: "يرجى التحديد",
    Form_Field_OtherSpecifyAria: "{label} — يرجى التحديد",
    Form_Field_SelectOptionPlaceholder: "حدد خيارًا",
    Form_Field_Yes: "نعم",
    Form_Field_No: "لا",
    Form_Field_SliderHint: "اسحب شريط التمرير للإجابة",
    Form_Field_WebAddressAriaWithLabel: "{label} — عنوان الويب",
    Form_Field_WebAddressAria: "عنوان الويب",
    Form_Field_DisplayTextPlaceholder: "نص العرض (اختياري)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — نص العرض",
    Form_Field_DisplayTextAria: "نص العرض",
    Form_Field_ChooseBetween: "اختر بين {min} و{max}",
    Form_Field_ChooseAtLeast: "اختر {min} على الأقل",
    Form_Field_ChooseUpTo: "اختر حتى {max}",
    Form_Field_SelectedCount: "تم تحديد {count}",
    Form_Field_RequiredAria: "(مطلوب)",
    Form_Submit_SaveError: "تعذر حفظ استجابتك. تأكد من نشر النموذج من المصمم ومن أن لديك إذنًا بإضافة عناصر إلى قائمة الاستجابات.",
    Form_Empty_Message: "لا يحتوي هذا النموذج على أي أسئلة بعد. يمكن لمالك النموذج إضافتها في علامة التبويب الأسئلة.",
    Form_Checking: "جارٍ التحقق من النموذج…",
    Form_Closed_NotYetOpen: "لم يُفتح بعد",
    Form_Closed_AlreadyAnswered: "تمت الإجابة بالفعل",
    Form_Closed_Title: "النموذج مغلق",
    Form_Confirmation_PreviewNotice: "كانت هذه معاينة — لم يتم حفظ أي شيء في قائمة الاستجابات.",
    Form_Confirmation_PreviewAgain: "معاينة مرة أخرى",
    Form_Confirmation_SubmitAnother: "إرسال استجابة أخرى",
    Form_Wizard_StepFallback: "الخطوة {step}",
    Form_Wizard_StepsAria: "خطوات النموذج",
    Form_Wizard_StepOf: "الخطوة {step} من {total}",
    Form_ErrorSummary_Title: "يرجى التحقق من {count} إجابات:",
    Form_ErrorSummary_UntitledQuestion: "سؤال بلا عنوان",
    Form_ErrorSummary_Question: "سؤال",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "رجوع",
    Form_Nav_Next: "التالي",
    Form_Draft_Saving: "جارٍ الحفظ…",
    Form_Draft_Saved: "تم حفظ المسودة",
    Form_Draft_SaveAndFinishLater: "حفظ والإكمال لاحقًا",
    Form_Draft_NotSaved: "لم يتم حفظ المسودة",
    Form_Submit_Preview: "إرسال (معاينة)",
    Form_Submit_Button: "إرسال",
    Form_Response_NoAnswer: "لا توجد إجابة",
    Form_Signature_TypeLabel: "اكتب اسمك الكامل",
    Form_Signature_TypeInstead: "اكتب اسمك بدلاً من ذلك",
    Form_Signature_DrawInstead: "ارسم بدلاً من ذلك",
    Form_Edit_Button: "تعديل استجابتك السابقة",
    Form_Edit_Available: "لقد أرسلت استجابة بالفعل. يمكنك تعديلها بدلاً من إرسال استجابة جديدة.",
    Form_Edit_Banner: "أنت تعدّل استجابتك السابقة.",
    Form_Edit_Save: "تحديث الاستجابة",
    Form_Edit_UpdatedTitle: "تم تحديث الاستجابة",
    Form_Edit_UpdatedMessage: "تم حفظ تغييراتك.",
    Form_Edit_LoadError: "تعذر تحميل استجابتك السابقة. يُرجى المحاولة مرة أخرى.",
    Form_Draft_MissingFiles: "يُرجى إرفاق الملفات مرة أخرى: {names}. تعذرت استعادة هذه الملفات.",
    Form_Attachments_Failed: "تم حفظ إجاباتك، لكن تعذر تحميل هذه المرفقات: {names}. يُرجى المحاولة مرة أخرى أو الاتصال بمالك النموذج.",
    Logic_ThisQuestion: "هذا السؤال",
    Logic_Required: "{label} مطلوب",
    Logic_RequiredConsent: "يُرجى تحديد المربع للمتابعة",
    Logic_RequiredFile: "يُرجى إرفاق ملف واحد على الأقل",
    Logic_RequiredSignature: "يُرجى إضافة توقيعك",
    Logic_RequiredLikert: "يُرجى الإجابة عن كل صف",
    Logic_InvalidEmail: "أدخل عنوان بريد إلكتروني صالحًا",
    Logic_InvalidPhone: "أدخل رقم هاتف صالحًا",
    Logic_InvalidUrl: "أدخل عنوان ويب صالحًا يبدأ بـ http:// أو https://",
    Logic_MinValue: "يجب ألا تقل القيمة عن {value}",
    Logic_MaxValue: "يجب ألا تزيد القيمة عن {value}",
    Logic_MaxLength: "الحد الأقصى للطول هو {max} حرفًا",
    Logic_ChooseAtLeastOne: "اختر {count} خيارًا على الأقل",
    Logic_ChooseAtLeastMany: "اختر {count} خيارات على الأقل",
    Logic_ChooseAtMostOne: "اختر {count} خيارًا كحد أقصى",
    Logic_ChooseAtMostMany: "اختر {count} خيارات كحد أقصى",
    Logic_LikertRemaining: "يُرجى الإجابة عن كل صف (المتبقي {count})",
    Logic_MaxFilesOne: "أرفق {count} ملفًا كحد أقصى",
    Logic_MaxFilesMany: "أرفق {count} ملفات كحد أقصى",
    Logic_FileTooLarge: "\"{name}\" أكبر من {size} ميغابايت",
    Logic_FileTypeNotAccepted: "\"{name}\" ليس نوع ملف مقبولًا ({types})",
    Logic_AddressRequired: "أدخل الشارع والمدينة على الأقل",
    Logic_PatternDefault: "هذه الإجابة ليست بالتنسيق المتوقع",
    Logic_Yes: "نعم",
    Logic_No: "لا",
    Logic_Agreed: "تمت الموافقة",
    Logic_NotAgreed: "لم تتم الموافقة",
    Logic_Signed: "تم التوقيع",
    Logic_NoAnswer: "(لا توجد إجابة)",
    Logic_Unknown: "(غير معروف)",
    Logic_OtherSlice: "أخرى ({count})",
    Logic_CsvResponseId: "معرّف الاستجابة",
    Logic_CsvSubmitted: "تاريخ الإرسال",
    Logic_CsvSubmittedBy: "أرسلها",
    Logic_EmailQuestion: "السؤال",
    Logic_EmailViewItem: "العرض في Microsoft Lists",
    Logic_EmailFooter: "أُرسلت تلقائيًا بواسطة Smart Forms.",
    Logic_ClosedDefault: "لم يعد هذا النموذج يقبل استجابات.",
    Logic_NotYetOpen: "يُفتح هذا النموذج في {date}.",
    Logic_AlreadyResponded: "لقد استجبت لهذا النموذج بالفعل. شكرًا لك!",
    Logic_UntitledQuestion: "سؤال بلا عنوان",
    Logic_Issue_NoQuestions: "أضف سؤالًا واحدًا على الأقل قبل جمع الاستجابات.",
    Logic_Issue_NoTitle: "أحد الأسئلة بلا نص — ستتم تسميته تلقائيًا عند النشر.",
    Logic_Issue_DuplicateTitle: "{label} يشترك في نصه مع سؤال آخر، مما يجعل النتائج أصعب في القراءة.",
    Logic_Issue_NeedTwoOptions: "{label} يتطلب خيارين على الأقل.",
    Logic_Issue_ImageNoImage: "{label} يحتوي على خيارات بلا صورة — ستظهر كبطاقات نصية.",
    Logic_Issue_LikertNeedRow: "{label} يتطلب صفًا واحدًا على الأقل.",
    Logic_Issue_LikertNeedColumns: "{label} يتطلب عمودين على الأقل للمقياس.",
    Logic_Issue_NoLookupList: "لم يتم تحديد قائمة مصدر لـ {label}.",
    Logic_Issue_NoFormula: "{label} ليس له صيغة.",
    Logic_Issue_BadFormula: "{label} له صيغة لا يمكن حسابها. تحقق من الأقواس والعوامل.",
    Logic_Issue_MissingRefs: "{label} يشير إلى أسئلة غير موجودة: {names}.",
    Logic_Issue_BadPattern: "{label} له نمط تحقق غير صالح.",
    Logic_Issue_BrokenRule: "{label} له قاعدة تفرّع تشير إلى سؤال محذوف.",
    Logic_Issue_SelfRule: "{label} له قاعدة تفرّع تشير إلى نفسه.",
    Logic_Issue_RuleMismatch: "{label} له قاعدة تفرّع لم تعد تناسب السؤال الذي تعتمد عليه.",
    Logic_Issue_RequiredReadOnly: "{label} مطلوب وللقراءة فقط في الوقت نفسه، لذا لا يمكن الإجابة عنه إلا عبر رابط معبأ مسبقًا.",
    Logic_Issue_EmptySection: "قسم بلا أسئلة وسيتم تخطيه.",
    Logic_Issue_CloseBeforeOpen: "تاريخ الإغلاق يسبق تاريخ الفتح أو يساويه، لذلك لن يقبل النموذج أي استجابات.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "رسائل الموافقة البريدية مفعّلة لكن خطوة الموافقة متوقفة.",
    Logic_Op_equals: "هو",
    Logic_Op_notEquals: "ليس",
    Logic_Op_contains: "يحتوي على",
    Logic_Op_notContains: "لا يحتوي على",
    Logic_Op_notEmpty: "تمت الإجابة عنه",
    Logic_Op_empty: "لم تتم الإجابة عنه",
    Logic_Op_greaterThan: "أكبر من",
    Logic_Op_greaterOrEqual: "لا يقل عن",
    Logic_Op_lessThan: "أقل من",
    Logic_Op_lessOrEqual: "لا يزيد عن",
    Logic_Op_between: "بين",
    Logic_Op_before: "قبل",
    Logic_Op_after: "بعد",
    Logic_Type_Text: "إجابة قصيرة",
    Logic_TypeDesc_Text: "سطر واحد من النص",
    Logic_Category_Text: "نص",
    Logic_Type_MultilineText: "إجابة طويلة",
    Logic_TypeDesc_MultilineText: "عدة أسطر من النص العادي",
    Logic_Type_RichText: "نص منسق",
    Logic_TypeDesc_RichText: "غامق وقوائم وروابط",
    Logic_Type_Choice: "اختيار",
    Logic_TypeDesc_Choice: "اختر من قائمة خيارات",
    Logic_Category_Choice: "اختيار",
    Logic_Type_ImageChoice: "اختيار بالصور",
    Logic_TypeDesc_ImageChoice: "اختر من بطاقات الصور",
    Logic_Type_Lookup: "بحث من قائمة",
    Logic_TypeDesc_Lookup: "خيارات تُقرأ مباشرةً من قائمة SharePoint أخرى",
    Logic_Type_YesNo: "نعم / لا",
    Logic_TypeDesc_YesNo: "مفتاح تبديل بسيط للتشغيل/الإيقاف",
    Logic_Type_Consent: "موافقة",
    Logic_TypeDesc_Consent: "مربع اختيار يجب على المستجيب تحديده للمتابعة",
    Logic_Type_Ranking: "ترتيب",
    Logic_TypeDesc_Ranking: "اسحب الخيارات لترتيبها حسب التفضيل",
    Logic_Type_Rating: "تقييم",
    Logic_TypeDesc_Rating: "نجوم أو قلوب أو إبهام",
    Logic_Category_Scales: "المقاييس",
    Logic_Type_Scale: "مقياس الرأي",
    Logic_TypeDesc_Scale: "مقياس مرقّم بنهايتين مسمّاتين",
    Logic_Type_Slider: "شريط تمرير",
    Logic_TypeDesc_Slider: "قيمة على مقياس منزلق",
    Logic_Type_Likert: "شبكة ليكرت",
    Logic_TypeDesc_Likert: "قيّم عدة عبارات على مقياس واحد مشترك",
    Logic_Type_Number: "رقم",
    Logic_TypeDesc_Number: "عادي أو عملة أو نسبة مئوية",
    Logic_Category_Advanced: "متقدم",
    Logic_Type_Calculated: "محسوب",
    Logic_TypeDesc_Calculated: "إجمالي للقراءة فقط يُحسب من إجابات أخرى",
    Logic_Type_Date: "تاريخ",
    Logic_TypeDesc_Date: "تاريخ تقويمي، مع وقت اختياريًا",
    Logic_Category_Date: "تاريخ",
    Logic_Type_Time: "وقت",
    Logic_TypeDesc_Time: "وقت من اليوم بمفرده",
    Logic_Type_Person: "شخص",
    Logic_TypeDesc_Person: "اختر شخصًا من المؤسسة",
    Logic_Category_People: "الأشخاص",
    Logic_Type_Email: "البريد الإلكتروني",
    Logic_TypeDesc_Email: "عنوان بريد إلكتروني مع التحقق منه",
    Logic_Type_Phone: "الهاتف",
    Logic_TypeDesc_Phone: "رقم هاتف مع التحقق منه",
    Logic_Type_Address: "العنوان",
    Logic_TypeDesc_Address: "الشارع والمدينة والرمز البريدي والبلد",
    Logic_Type_Hyperlink: "رابط",
    Logic_TypeDesc_Hyperlink: "عنوان ويب",
    Logic_Type_FileUpload: "تحميل ملف",
    Logic_TypeDesc_FileUpload: "أرفق ملفًا واحدًا أو أكثر بالاستجابة",
    Logic_Type_Signature: "التوقيع",
    Logic_TypeDesc_Signature: "وقّع باستخدام الماوس أو القلم أو الإصبع",
    Logic_Type_Content: "كتلة نص",
    Logic_TypeDesc_Content: "تعليمات أو صورة — لا تجمع أي إجابة",
    Logic_Category_Layout: "التخطيط",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "ما مدى احتمال أن توصي بـ…",
    Logic_Preset_satisfaction: "الرضا (1–5)",
    Logic_PresetDesc_satisfaction: "من غير راضٍ إطلاقًا إلى راضٍ جدًا",
    Logic_Preset_currency: "العملة",
    Logic_PresetDesc_currency: "مبلغ مالي",
    Logic_Preset_percent: "النسبة المئوية",
    Logic_PresetDesc_percent: "قيمة نسبة مئوية",
    Logic_Template_blank_Name: "نموذج فارغ",
    Logic_Template_blank_Description: "ابدأ من الصفر",
    Logic_Template_feedback_Name: "ملاحظات العملاء",
    Logic_Template_feedback_Description: "NPS وتقييمات وتعليقات مفتوحة",
    Logic_Template_event_Name: "التسجيل في فعالية",
    Logic_Template_event_Description: "تفاصيل الحضور والجلسات والاحتياجات الغذائية",
    Logic_Template_itrequest_Name: "طلب خدمة تقنية المعلومات",
    Logic_Template_itrequest_Description: "طلبات مصنفة مع الأولوية والمرفقات",
    Logic_Template_expense_Name: "مطالبة مصروفات",
    Logic_Template_expense_Description: "بنود وإيصالات وإجمالي محسوب",
    Logic_Template_pulse_Name: "استطلاع نبض الموظفين",
    Logic_Template_pulse_Description: "شبكة ليكرت ومقياس المشاركة وملاحظة عدم الكشف عن الهوية",
    Logic_Template_safety_Name: "فحص السلامة",
    Logic_Template_safety_Description: "قائمة تحقق وصور وتوقيع",
    Logic_Template_booking_Name: "حجز غرفة أو مورد",
    Logic_Template_booking_Description: "منتقي موارد قائم على البحث مع فترة زمنية",
    Charts_ColumnChartAria: "مخطط أعمدة يضم {count} فئات",
    Charts_DonutChartAria: "مخطط دائري مجوف لـ {count} فئات",
    Charts_NoAnswers: "لا توجد إجابات بعد.",
    Charts_NoResponses: "لا توجد استجابات بعد.",
    Charts_Responses: "الاستجابات",
    Charts_ResponsesOverTime: "الاستجابات عبر الزمن",
    Responses_Chart_Answer: "الإجابة",
    Responses_Chart_Average: "المتوسط",
    Responses_Chart_AverageOf: "متوسط {count}",
    Responses_Chart_AveragePosition: "متوسط الترتيب",
    Responses_Chart_AverageRange: "المتوسط (1–{max})",
    Responses_Chart_AvgValue: "المتوسط {value}",
    Responses_Chart_Detractors: "المنتقدون (0–6)",
    Responses_Chart_Max: "الأقصى",
    Responses_Chart_Maximum: "الحد الأقصى",
    Responses_Chart_Median: "الوسيط",
    Responses_Chart_MentionOne: "{count} إشارة",
    Responses_Chart_MentionOther: "{count} إشارات",
    Responses_Chart_Min: "الأدنى",
    Responses_Chart_Minimum: "الحد الأدنى",
    Responses_Chart_NoAnswers: "لا توجد إجابات بعد.",
    Responses_Chart_NoNumeric: "لا توجد إجابات رقمية بعد.",
    Responses_Chart_NoRankings: "لا توجد ترتيبات بعد.",
    Responses_Chart_NoScores: "لا توجد درجات بعد.",
    Responses_Chart_NotEnoughText: "لا يوجد نص كافٍ للتلخيص بعد.",
    Responses_Chart_NpsScore: "درجة NPS",
    Responses_Chart_Option: "الخيار",
    Responses_Chart_Passives: "المحايدون (7–8)",
    Responses_Chart_Promoters: "المروّجون (9–10)",
    Responses_Chart_ResponseOne: "استجابة",
    Responses_Chart_ResponseOther: "استجابات",
    Responses_Chart_Responses: "الاستجابات",
    Responses_Chart_ShowingAnswers: "عرض {shown} من {total} إجابات.",
    Responses_Chart_Statement: "العبارة",
    Responses_Chart_Statistic: "الإحصائية",
    Responses_Chart_StdDev: "الانحراف المعياري",
    Responses_Chart_StdDeviation: "الانحراف المعياري",
    Responses_Chart_Total: "الإجمالي",
    Responses_Chart_Value: "القيمة",
    Responses_Dashboard_AllHidden: "جميع الأسئلة مخفية من لوحة المعلومات. استخدم “إظهار الأسئلة المخفية” لإعادتها.",
    Responses_Dashboard_AnsweredOf: "تمت الإجابة عن {answered} من {total}",
    Responses_Dashboard_AnsweredOfPinned: "تمت الإجابة عن {answered} من {total} · مثبّت",
    Responses_Dashboard_AveragedAcrossResponses: "متوسط عبر الاستجابات",
    Responses_Dashboard_ByDay: "حسب اليوم",
    Responses_Dashboard_ByMonth: "حسب الشهر",
    Responses_Dashboard_ByWeek: "حسب الأسبوع",
    Responses_Dashboard_ChartAuto: "تلقائي",
    Responses_Dashboard_ChartBars: "أشرطة",
    Responses_Dashboard_ChartColumns: "أعمدة",
    Responses_Dashboard_ChartDonut: "دائري مجوف",
    Responses_Dashboard_ChartGauge: "مقياس",
    Responses_Dashboard_ChartHistogram: "مخطط تكراري",
    Responses_Dashboard_ChartOptions: "خيارات المخطط",
    Responses_Dashboard_ChartOptionsFor: "خيارات المخطط لـ {title}",
    Responses_Dashboard_ChartStatistics: "الإحصائيات",
    Responses_Dashboard_ChartTable: "جدول",
    Responses_Dashboard_ChartWordFrequency: "تكرار الكلمات",
    Responses_Dashboard_EmptyBody: "بمجرد أن يبدأ الأشخاص بالإجابة، تمتلئ لوحة المعلومات هذه تلقائيًا — بأرقام رئيسية وجدول زمني للاستجابات ومخطط للأسئلة التي تستحق المتابعة.",
    Responses_Dashboard_EmptyTitle: "لا توجد استجابات بعد",
    Responses_Dashboard_Hide: "إخفاء من لوحة المعلومات",
    Responses_Dashboard_Highlights: "أبرز النقاط",
    Responses_Dashboard_Last7Days: "آخر 7 أيام",
    Responses_Dashboard_LatestDate: "الأحدث {date}",
    Responses_Dashboard_MedianTimeToComplete: "الوسيط الزمني للإكمال",
    Responses_Dashboard_NoPriorWeek: "لا يوجد أسبوع سابق للمقارنة",
    Responses_Dashboard_OneEach: "واحدة لكل منهم",
    Responses_Dashboard_Pin: "تثبيت في لوحة المعلومات",
    Responses_Dashboard_QuestionFallback: "سؤال",
    Responses_Dashboard_QuestionsAnswered: "الأسئلة المُجاب عنها",
    Responses_Dashboard_RecordedOnSubmit: "تُسجَّل عند الإرسال",
    Responses_Dashboard_RepeatResponses: "{count} استجابات متكررة",
    Responses_Dashboard_ResponsesOverTime: "الاستجابات عبر الزمن",
    Responses_Dashboard_ShowHidden: "إظهار الأسئلة المخفية",
    Responses_Dashboard_SinceMidnight: "منذ منتصف الليل",
    Responses_Dashboard_Today: "اليوم",
    Responses_Dashboard_TotalResponses: "إجمالي الاستجابات",
    Responses_Dashboard_UniqueRespondents: "المستجيبون الفريدون",
    Responses_Dashboard_Unpin: "إلغاء التثبيت من لوحة المعلومات",
    Responses_Dashboard_UntitledQuestion: "سؤال بلا عنوان",
    Responses_Dashboard_VsPrevious7Days: "مقابل الأيام السبعة السابقة",
    Responses_Detail_Answers: "الإجابات",
    Responses_Detail_AsTheForm: "كما في النموذج",
    Responses_Detail_Cancel: "إلغاء",
    Responses_Detail_Delete: "حذف",
    Responses_Detail_DeleteBody: "ينتقل عنصر القائمة إلى سلة المحذوفات في الموقع، لذا يمكن استعادته من هناك.",
    Responses_Detail_DeleteTitle: "حذف هذه الاستجابة؟",
    Responses_Detail_Deleting: "جارٍ الحذف…",
    Responses_Detail_Draft: "مسودة",
    Responses_Detail_Header: "الاستجابة {index} من {total}",
    Responses_Detail_LoadingAttachments: "جارٍ تحميل المرفقات…",
    Responses_Detail_Next: "الاستجابة التالية",
    Responses_Detail_NoAnswer: "لا توجد إجابة",
    Responses_Detail_Previous: "الاستجابة السابقة",
    Responses_Detail_Print: "طباعة",
    Responses_Detail_Signature: "التوقيع",
    Responses_Detail_Signed: "تم التوقيع",
    Responses_Detail_Took: "استغرق {duration}",
    Responses_Summary_AnsweredOfType: "تمت الإجابة عن {answered} من {total} · {type}",
    Responses_Summary_ByField: "حسب {title}",
    Responses_Summary_CompareBy: "مقارنة حسب…",
    Responses_Summary_EmptyBody: "سيحصل كل سؤال على ملخص خاص به هنا.",
    Responses_Summary_NoComparison: "بلا مقارنة",
    Responses_Summary_NothingToCompare: "لم تُجب أي استجابة عن “{title}”، لذا لا يوجد ما يمكن مقارنته.",
    Responses_Summary_OtherNote: "تجمع المخططات التي تضم أكثر من {max} فئات أصغر الفئات في “أخرى” — بدّل البطاقة إلى جدول لرؤية كل قيمة.",
    Responses_Summary_ResponseCountOne: "{count} استجابة",
    Responses_Summary_ResponseCountOther: "{count} استجابات",
    Responses_Summary_SeeAllAnswers: "عرض جميع الإجابات في الجدول",
    Responses_Summary_SegmentNote: "عرض أكبر {groups} مجموعات. تظهر الاستجابة التي حددت عدة إجابات في كل مجموعة مطابقة، لذا قد تتجاوز إجماليات المجموعات {total}.",
    Responses_Summary_SplitBy: "تقسيم حسب {title}",
    Responses_Summary_Untitled: "بلا عنوان",
    Responses_Table_Apply: "تطبيق",
    Responses_Table_Cancel: "إلغاء",
    Responses_Table_ClearSelection: "مسح التحديد",
    Responses_Table_ColumnOrder: "ترتيب الأعمدة",
    Responses_Table_ColumnsCount: "الأعمدة ({shown}/{total})",
    Responses_Table_Delete: "حذف",
    Responses_Table_DeleteBody: "تنتقل عناصر القائمة إلى سلة المحذوفات في الموقع، لذا يمكن استعادتها من هناك.",
    Responses_Table_DeleteSelected: "حذف المحدد",
    Responses_Table_DeleteTitleOne: "حذف {count} استجابة؟",
    Responses_Table_DeleteTitleOther: "حذف {count} استجابات؟",
    Responses_Table_Deleting: "جارٍ الحذف…",
    Responses_Table_MoveDown: "نقل لأسفل",
    Responses_Table_MoveDownFor: "نقل {title} لأسفل",
    Responses_Table_MoveUp: "نقل لأعلى",
    Responses_Table_MoveUpFor: "نقل {title} لأعلى",
    Responses_Table_NoColumns: "لا توجد أعمدة أسئلة مرئية بعد.",
    Responses_Table_NoMatch: "لا توجد استجابات تطابق عوامل التصفية الحالية.",
    Responses_Table_NothingToShow: "لا يوجد ما يُعرض",
    Responses_Table_OpenResponse: "فتح هذه الاستجابة",
    Responses_Table_OrderNote: "يأتي \"تاريخ الإرسال\" و\"أرسلها\" دائمًا أولًا. ينطبق ترتيب السحب على أعمدة الأسئلة.",
    Responses_Table_Reorder: "إعادة الترتيب",
    Responses_Table_ResetColumns: "إعادة تعيين الأعمدة",
    Responses_Table_SelectResponse: "تحديد هذه الاستجابة",
    Responses_Table_SelectedOne: "تم تحديد {count} استجابة",
    Responses_Table_SelectedOther: "تم تحديد {count} استجابات",
    Responses_Table_ShowAll: "إظهار الكل",
    Responses_Table_ShowTheseQuestions: "إظهار هذه الأسئلة",
    Responses_Table_Submitted: "تاريخ الإرسال",
    Responses_Table_SubmittedBy: "أرسلها",
    Responses_Table_ToggleSelection: "تبديل التحديد",
    Responses_Table_Unknown: "غير معروف",
    Responses_Table_Untitled: "بلا عنوان",
    Responses_View_AllTime: "كل الأوقات",
    Responses_View_AnyAnswer: "أي إجابة",
    Responses_View_Clear: "مسح",
    Responses_View_CopyShareLink: "نسخ رابط المشاركة",
    Responses_View_CountFiltered: "{shown} من {total} استجابات",
    Responses_View_CountOne: "{count} استجابة",
    Responses_View_CountOther: "{count} استجابات",
    Responses_View_Dashboard: "لوحة المعلومات",
    Responses_View_DateRange: "النطاق الزمني",
    Responses_View_EmptyBody: "شارك النموذج لبدء الجمع. تُحفظ الإجابات في “{list}” وتظهر هنا فورًا.",
    Responses_View_EmptyTitle: "لا توجد استجابات بعد",
    Responses_View_ExportCsv: "تصدير CSV",
    Responses_View_FilterByAnswer: "تصفية حسب الإجابة",
    Responses_View_FilterByQuestion: "تصفية حسب السؤال",
    Responses_View_FilterValue: "قيمة التصفية",
    Responses_View_Last30Days: "آخر 30 يومًا",
    Responses_View_Last7Days: "آخر 7 أيام",
    Responses_View_Last90Days: "آخر 90 يومًا",
    Responses_View_LoadError: "تعذر تحميل الاستجابات. انشر النموذج مرة واحدة حتى توجد أعمدة القائمة، ثم حاول مرة أخرى.",
    Responses_View_Loading: "جارٍ تحميل الاستجابات…",
    Responses_View_MoreActions: "إجراءات إضافية للاستجابة",
    Responses_View_PreviewForm: "معاينة النموذج",
    Responses_View_Refresh: "تحديث",
    Responses_View_ResponsesTab: "الاستجابات ({count})",
    Responses_View_SearchPlaceholder: "البحث في جميع الإجابات",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "حدد قيمة",
    Responses_View_Summary: "الملخص",
    Responses_View_Today: "اليوم",
    Responses_View_Truncated: "تحتوي هذه القائمة على استجابات أكثر مما يحمّله Smart Forms دفعة واحدة. يتم عرض أحدث {count} — افتح القائمة في Microsoft Lists للاطلاع على المجموعة الكاملة.",
    Responses_View_TryAgain: "حاول مرة أخرى",
    Responses_View_Untitled: "بلا عنوان",
    Responses_Approval_Column: "الموافقة",
    Responses_Approval_ReviewerColumn: "تمت المراجعة بواسطة",
    Responses_Approval_CommentColumn: "تعليق المراجع",
    Responses_Approval_Pending: "قيد الانتظار",
    Responses_Approval_Approved: "تمت الموافقة",
    Responses_Approval_Rejected: "مرفوضة",
    Responses_Approval_AnyStatus: "أي حالة موافقة",
    Responses_Approval_FilterLabel: "التصفية حسب حالة الموافقة",
    Responses_Approval_ApproveSelected: "الموافقة على المحدد",
    Responses_Approval_RejectSelected: "رفض المحدد",
    Responses_Approval_BulkFailed: "تعذر تحديث {count} من الاستجابات. حاول مرة أخرى.",
    Responses_Approval_Approve: "موافقة",
    Responses_Approval_Reject: "رفض",
    Responses_Approval_Reset: "إعادة التعيين إلى قيد الانتظار",
    Responses_Approval_CommentLabel: "تعليق (اختياري)",
    Responses_Approval_ReviewedBy: "تمت المراجعة بواسطة {name}",
    Responses_Approval_Error: "تعذر حفظ القرار. حاول مرة أخرى.",
    Responses_Dashboard_ApprovalStatus: "بانتظار المراجعة",
    Responses_Dashboard_ApprovalBreakdown: "{pending} قيد الانتظار، {approved} تمت الموافقة عليها، {rejected} مرفوضة",
    Responses_Dashboard_TimelineCoarsened: "النطاق الزمني طويل، لذلك تم تجميع الخط الزمني بشكل أقل تفصيلًا ({grain}).",
    Responses_Dashboard_TimelineTruncated: "النطاق الزمني طويل جدًا، لذلك تُعرض أحدث {count} فترات فقط.",
    Service_Item_DefaultTitle: "استجابة — {date}",
    Service_Email_ApprovalSubject: "حالة استجابتك: {status} — {title}",
    Service_Email_ApprovalHeading: "حالة استجابتك: {status}",
    Service_Email_ApprovalIntro: "قام مراجع بتغيير حالة استجابتك على \"{title}\" إلى: {status}.",
    Service_Email_ApprovalCommentLabel: "تعليق المراجع",
    Service_Approval_Approved: "تمت الموافقة عليها",
    Service_Approval_Rejected: "تم رفضها",
    Service_Approval_Pending: "قيد الانتظار",
    Service_Lookup_InvalidFilter: "عامل تصفية البحث غير صالح.",
    Service_Edit_NotAllowed: "لا يسمح هذا النموذج بتعديل استجابة تم إرسالها.",
    Service_Edit_NotYours: "يمكنك تعديل استجابتك أنت فقط.",
    Service_Signature_AttachmentLabel: "التوقيع",
    PropertyPane_ListsLoadFailed: "تعذر تحميل القوائم في هذا الموقع.",
    PropertyPane_EnterListName: "أدخل اسمًا للقائمة الجديدة أولًا.",
    PropertyPane_CreatingList: "جارٍ إنشاء \"{name}\"…",
    PropertyPane_ListCreated: "تم إنشاء القائمة \"{title}\" وتحديدها.",
    PropertyPane_ListAlreadyExists: "توجد قائمة باسم \"{name}\" بالفعل — حددها من القائمة المنسدلة أعلاه.",
    PropertyPane_CreateListFailed: "تعذر إنشاء القائمة. تحقق من أن لديك إذنًا بإنشاء القوائم في هذا الموقع.",
    PropertyPane_Description: "اختر قائمة SharePoint التي تخزن استجابات النموذج، أو أنشئ قائمة جديدة. كل ما عدا ذلك — الأسئلة والمظهر والإشعارات — يُحرَّر مباشرة على الصفحة.",
    PropertyPane_ResponseList_GroupName: "قائمة الاستجابات",
    PropertyPane_ListDropdown_Label: "حفظ الاستجابات في هذه القائمة",
    PropertyPane_ResponsesGoTo: "تُحفظ الاستجابات في \"{name}\".",
    PropertyPane_PickList: "اختر قائمة، أو أنشئ واحدة أدناه.",
    PropertyPane_LoadingLists: "جارٍ تحميل القوائم…",
    PropertyPane_NewListName_Label: "أو أنشئ قائمة جديدة",
    PropertyPane_NewListName_Placeholder: "اسم القائمة الجديدة",
    PropertyPane_CreateList_Button: "إنشاء قائمة",
    PropertyPane_Tips_GroupName: "نصائح",
    PropertyPane_Tip_AutoSave: "تُحفظ الأسئلة والإعدادات تلقائيًا أثناء تحريرها — لا حاجة لحفظ الصفحة أو نشرها.",
    PropertyPane_Tip_Permissions: "يحتاج المستجيبون إلى إذن بإضافة عناصر إلى قائمة الاستجابات. تحقق من أذونات القائمة إذا أبلغ أحد عن خطأ عند الإرسال.",
    PropertyPane_Tip_Share: "استخدم \"جمع الاستجابات\" في الصفحة لإنشاء أعمدة القائمة والحصول على رابط تعبئة قابل للمشاركة.",
    App_ErrorBoundary_Title: "Smart Forms — خطأ في العرض",
    App_ErrorBoundary_Message: "الرسالة:",
    App_ErrorBoundary_Stack: "تتبع المكدس:",
    App_ErrorBoundary_NoStack: "(لا يتوفر تتبع للمكدس)",
    App_ErrorBoundary_ConsoleNote: "كُتبت التفاصيل الكاملة أيضًا في وحدة تحكم المتصفح.",
    App_DefaultQuestionTitle: "السؤال {number}",
    App_Error_ListMissing: "القائمة المكوّنة لهذا النموذج لم تعد موجودة. اختر قائمة أخرى في إعدادات جزء الويب.",
    App_Error_LoadConfig: "حدث خطأ أثناء تحميل تكوين النموذج.",
    App_Error_Unable: "تعذر تحميل النموذج.",
    App_Publish_ConflictNotice: "لدى \"{title}\" بالفعل عمود قائمة من نوع مختلف ({type}). أعد تسمية السؤال ليتم إنشاء عمود جديد، أو أعد نوعه كما كان.",
    App_Publish_ConflictUnnamedQuestion: "سؤال",
    App_Publish_ColumnsAddedOne: "تمت إضافة {count} عمود إلى \"{list}\".",
    App_Publish_ColumnsAddedOther: "تمت إضافة {count} أعمدة إلى \"{list}\".",
    App_Publish_TheList: "القائمة",
    App_Publish_UpToDate: "قائمة الاستجابات محدّثة بالفعل.",
    App_Publish_Error: "تعذر إنشاء أعمدة القائمة. يعني هذا عادةً أنه ليس لديك إذن إدارة القوائم على قائمة الاستجابات، لكنه قد يحدث أيضًا في المواقع التي عُطّل فيها البرمجة النصية المخصصة. تحقق من وحدة تحكم المتصفح لمعرفة الخطأ الأساسي، أو حاول مرة أخرى.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "أنشئ نموذجًا أنيقًا فوق قائمة SharePoint — {count} نوعًا من الأسئلة، ومنطق التفرع، وتحميل الملفات، وروابط تعبئة قابلة للمشاركة، ولوحة معلومات للنتائج.",
    App_Placeholder_ChooseList: "اختر قائمة أو أنشئ واحدة",
    App_Placeholder_Hint: "حرّر الصفحة وقم بتكوين جزء الويب هذا للبدء.",
    App_Loading: "جارٍ تحميل النموذج…",
    App_OpenSettings: "فتح الإعدادات",
    App_Tab_Questions: "الأسئلة",
    App_Tab_QuestionsWithCount: "الأسئلة ({count})",
    App_Tab_Responses: "الاستجابات",
    App_Tab_Responses_Title: "تُحفظ الاستجابات في \"{list}\"",
    App_Templates_Start: "البدء من قالب",
    App_Settings_Title: "إعدادات النموذج — المظهر والإشعارات والوصول",
    App_Settings_AriaLabel: "إعدادات النموذج",
    App_Preview: "معاينة",
    App_Preview_Close: "إغلاق المعاينة",
    App_Preview_Hint: "معاينة — لا يُحفظ أي شيء ترسله هنا. يعمل التحقق والتفرع تمامًا كما سيعملان للمستجيبين.",
    App_Publish_GettingReady: "جارٍ التجهيز…",
    App_Publish_CollectResponses: "جمع الاستجابات",
    App_Publish_Share: "مشاركة",
    App_Retry: "إعادة المحاولة",
    App_SaveError_Banner: "تعذر حفظ آخر تغيير. تحقق من اتصالك ثم حاول مرة أخرى.",
    App_Preflight_BlockingTitle: "أصلح هذه المشكلات قبل الجمع",
    App_Preflight_WarningTitle: "يستحق النظر أولًا",
    App_Preflight_BlockingText: "ستمنع هذه المشكلات النموذج المنشور من العمل بشكل صحيح.",
    App_Preflight_WarningText: "لا شيء معطّل، لكن يستحق إصلاح هذه الأمور عادةً قبل مشاركة الرابط.",
    App_Preflight_GoTo: "انتقال إلى",
    App_Preflight_CollectAnyway: "جمع الاستجابات على أي حال",
    App_Preflight_Back: "العودة إلى النموذج",
    App_Cancel: "إلغاء",
    App_Done: "تم",
    App_Share_Title: "نموذجك جاهز للمشاركة",
    App_Share_SubText: "أرسل هذا الرابط إلى كل من يجب أن يملأ النموذج.",
    App_Share_LinkAriaLabel: "رابط المشاركة",
    App_Share_Copy: "نسخ",
    App_Share_Copied: "تم النسخ",
    App_Share_AddItemsEmphasis: "إضافة عناصر",
    App_Share_PermissionNote: "يحتاج المستجيبون إلى إذن {addItems} إلى “{title}” وإلى الوصول إلى هذه الصفحة. إذا ظهر خطأ لأحدهم عند الإرسال، فهذا هو السبب غالبًا.",
    App_Share_PrefillNote: "يمكنك الإجابة مسبقًا عن الأسئلة في الرابط بإضافة اسم العمود، على سبيل المثال {example}.",
    App_Templates_ReplaceWarning: "اختيار قالب يستبدل الأسئلة الموجودة لديك حاليًا.",
    App_Templates_PickStart: "اختر نقطة بداية — يمكنك تغيير أي شيء لاحقًا.",
    App_Templates_Empty: "فارغ",
    App_Templates_QuestionCount: "{count} أسئلة",
    App_SaveChip_SavingTitle: "جارٍ حفظ آخر تعديل",
    App_SaveChip_Saving: "جارٍ الحفظ…",
    App_SaveChip_FailedTitle: "تعذر حفظ آخر تعديل. تحقق من اتصالك وحاول مرة أخرى.",
    App_SaveChip_Failed: "فشل الحفظ",
    App_SaveChip_SavedTitle: "تم حفظ جميع التغييرات",
    App_SaveChip_Saved: "تم الحفظ",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "استجابة جديدة — {title}",
    Service_Email_NewResponseHeading: "استجابة جديدة: {title}",
    Service_Email_NewResponseIntro: "أرسل شخص ما استجابة للتو — {date}.",
    Service_Email_ReceiptSubject: "استجابتك — {title}",
    Service_Email_ReceiptHeading: "شكرًا على استجابتك!",
    Service_Email_ReceiptIntro: "هذه نسخة مما أرسلته إلى \"{title}\".",
    App_History_Title: "سجل الإصدارات",
    App_History_RestoredNotice: "تمت استعادة الإصدار المحفوظ في {date}. راجعه، ثم استخدم \"جمع الاستجابات\" لنشر أي أسئلة جديدة.",
    App_History_Undo: "التراجع عن الاستعادة",
    App_Share_CopyManual: "حظر المتصفح النسخ. حدد الرابط أعلاه واضغط Ctrl+C (Cmd+C على جهاز Mac) لنسخه.",
    App_Share_TeamsNote: "أنت في Microsoft Teams. يفتح هذا الرابط صفحة SharePoint مباشرةً، لذلك يحتاج المستلمون إلى صلاحية الوصول إلى الموقع.",
    App_Share_PrefillNotSecure: "الإجابات المعبأة مسبقًا للتسهيل فقط: يمكن لأي شخص لديه الرابط تغييرها، لذا لا تعتبرها حدًا أمنيًا أبدًا.",
    Designer_Section_DropHere: "أفلت سؤالًا هنا",
    Designer_Section_DropEnd: "أفلت هنا للنقل إلى نهاية هذا القسم",
    Designer_Rules_RemovedOne: "تمت إزالة قاعدة تفرّع واحدة لم تعد مناسبة.",
    Designer_Rules_RemovedOther: "تمت إزالة {count} من قواعد التفرّع التي لم تعد مناسبة.",
    Designer_Settings_AllowEdit: "السماح للمستجيبين بتعديل استجاباتهم",
    Designer_Settings_AllowEditHint: "يمكن للمستجيبين إعادة فتح ما أرسلوه وتحديثه. يمكن لكل شخص تعديل استجابته فقط.",
    Designer_Settings_EnableApproval: "تمكين سير عمل الموافقة",
    Designer_Settings_ApprovalNotify: "إرسال بريد إلى المستجيب عند اتخاذ القرار",
    Designer_Settings_ApprovalHint: "يضيف أعمدة الموافقة إلى قائمة الاستجابات عند النشر في المرة التالية. يوافق المالكون على الاستجابات أو يرفضونها من علامة التبويب \"الاستجابات\".",
    Designer_History_Title: "سجل الإصدارات",
    Designer_History_Intro: "الإصدارات المحفوظة السابقة لأسئلة هذا النموذج وإعداداته. تؤدي الاستعادة إلى تحميل إصدار في المصمم؛ ويمكنك التراجع عنها، ولا تُنشأ الأسئلة الجديدة إلا عند النشر.",
    Designer_History_Loading: "جارٍ تحميل الإصدارات...",
    Designer_History_Empty: "لم يتم العثور على إصدارات سابقة. يتطلب سجل الإصدارات تشغيل إصدار الإصدارات للقائمة \"Smart Forms Config\" ووجود تعديل محفوظ واحد على الأقل.",
    Designer_History_Latest: "الأحدث",
    Designer_History_LatestTitle: "هذا هو الإصدار المستخدم حاليًا",
    Designer_History_By: "بواسطة {name}",
    Designer_History_UnknownAuthor: "مؤلف غير معروف",
    Designer_History_VersionLabel: "الإصدار {label}",
    Designer_History_Preview: "معاينة",
    Designer_History_Restore: "استعادة",
    Designer_History_QuestionsOne: "سؤال واحد",
    Designer_History_QuestionsOther: "{count} من الأسئلة",
    Designer_History_LoadFailed: "تعذر تحميل هذا الإصدار.",
    Designer_History_ConfirmTitle: "استعادة هذا الإصدار؟",
    Designer_History_ConfirmText: "سيتم استبدال النموذج بالإصدار المحفوظ في {date} ({count} من الأسئلة). يمكنك التراجع عن ذلك مباشرةً بعد ذلك."
  };
});
