define([], function () {
  return {
    Designer_Color_Blue: "Modrá",
    Designer_Color_Teal: "Modrozelená",
    Designer_Color_Green: "Zelená",
    Designer_Color_Purple: "Fialová",
    Designer_Color_Magenta: "Purpurová",
    Designer_Color_Red: "Červená",
    Designer_Color_Orange: "Oranžová",
    Designer_Color_Gray: "Šedá",
    Designer_Settings_LayoutSinglePage: "Všechny otázky na jedné stránce",
    Designer_Settings_LayoutWizard: "Jedna sekce na krok (průvodce)",
    Designer_Settings_Title: "Nastavení formuláře",
    Designer_Common_Apply: "Použít",
    Designer_Common_Cancel: "Zrušit",
    Designer_Settings_TabBasics: "Základní",
    Designer_Settings_FormTitle: "Název formuláře",
    Designer_Settings_Description: "Popis",
    Designer_Settings_Layout: "Rozložení",
    Designer_Settings_NumberQuestions: "Očíslovat otázky",
    Designer_Settings_ShuffleQuestions: "Náhodné pořadí otázek pro každého respondenta",
    Designer_Settings_ShowProgressBar: "Zobrazit indikátor průběhu",
    Designer_Settings_TabAppearance: "Vzhled",
    Designer_Settings_AccentColor: "Barva zvýraznění",
    Designer_Settings_CustomColorTitle: "Vlastní barva",
    Designer_Settings_CustomColorAria: "Vlastní barva zvýraznění",
    Designer_Settings_AccentHint: "Barvy zvýraznění se automaticky upravují pro kontrast na tmavých webech, takže formulář zůstane čitelný bez ohledu na motiv stránky.",
    Designer_Settings_ShowHeader: "Zobrazit záhlaví formuláře",
    Designer_Settings_HeaderIcon: "Ikona záhlaví",
    Designer_Settings_TabAfterSubmit: "Po odeslání",
    Designer_Settings_SubmitButtonText: "Text tlačítka Odeslat",
    Designer_Settings_SubmitPlaceholder: "Odeslat",
    Designer_Settings_ThankYouTitle: "Nadpis poděkování",
    Designer_Settings_ThankYouPlaceholder: "Děkujeme!",
    Designer_Settings_ThankYouMessage: "Zpráva s poděkováním",
    Designer_Settings_ShowSubmitAnother: "Zobrazit tlačítko „Odeslat další odpověď“",
    Designer_Settings_TabNotifications: "Oznámení",
    Designer_Settings_EmailEachResponseTo: "Posílat každou odpověď e-mailem na",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "Lidé ve vaší organizaci dostanou každou odpověď e-mailem s odkazem na položku seznamu",
    Designer_Settings_RespondentReceipt: "Poslat respondentům e-mailem kopii jejich odpovědí",
    Designer_Settings_NotificationsInfo: "Oznámení používají vlastní poštovní službu SharePointu, takže příjemci musí být uživateli ve vaší organizaci. Externí adresy se tiše zahodí.",
    Designer_Settings_TabAccess: "Přístup",
    Designer_Settings_OpenFrom: "Otevřít od",
    Designer_Settings_OpenImmediately: "Otevřít okamžitě",
    Designer_Settings_CloseAfter: "Zavřít po",
    Designer_Settings_NeverClose: "Nikdy nezavírat",
    Designer_Settings_ClearDates: "Vymazat data",
    Designer_Settings_DatesInverted: "Datum uzavření je shodné s datem otevření nebo mu předchází, takže by formulář nikdy nepřijal žádné odpovědi.",
    Designer_Settings_MaxResponses: "Zastavit po tomto počtu odpovědí",
    Designer_Settings_NoLimit: "Bez omezení",
    Designer_Settings_OneResponsePerPerson: "Povolit pouze jednu odpověď na osobu",
    Designer_Settings_AllowSaveDraft: "Umožnit respondentům uložit koncept a dokončit později",
    Designer_Settings_ClosedMessage: "Zpráva zobrazená po uzavření formuláře",
    Designer_Settings_ClosedMessagePlaceholder: "Tento formulář již nepřijímá odpovědi.",
    Designer_Settings_AccessInfo: "Tato omezení vynucuje formulář, nikoli SharePoint. Kdokoli s oprávněním přidávat položky do seznamu odpovědí by mohl přidat odpověď přímo přes seznam.",
    Designer_Field_StyleInfo: "Informace (zvýraznění)",
    Designer_Field_StyleSuccess: "Úspěch (zelená)",
    Designer_Field_StyleWarning: "Upozornění (jantarová)",
    Designer_Field_StylePlain: "Prostý text",
    Designer_Field_StyleDivider: "Dělicí čára",
    Designer_Field_IconStars: "Hvězdičky",
    Designer_Field_IconHearts: "Srdce",
    Designer_Field_IconThumbs: "Palec nahoru",
    Designer_Field_FormatPlain: "Prosté číslo",
    Designer_Field_FormatCurrency: "Měna",
    Designer_Field_FormatPercent: "Procento",
    Designer_Field_UntitledQuestion: "Otázka bez názvu",
    Designer_Field_DeletedQuestion: "odstraněná otázka",
    Designer_Rule_Unary: "„{name}“ {operator}",
    Designer_Rule_Between: "„{name}“ {operator} {value} a {value2}",
    Designer_Rule_Binary: "„{name}“ {operator} „{value}“",
    Designer_Rule_JoinAny: "NEBO",
    Designer_Rule_JoinAll: "A",
    Designer_Rule_Preview: "Zobrazí se, když {conditions}.",
    Designer_Field_Yes: "Ano",
    Designer_Field_No: "Ne",
    Designer_Field_When: "Když",
    Designer_Field_SelectValue: "Vyberte hodnotu",
    Designer_Field_DateValuePlaceholder: "RRRR-MM-DD nebo „today“",
    Designer_Field_ValuePlaceholder: "Hodnota",
    Designer_Field_UpperBound: "Horní mez",
    Designer_Field_RemoveCondition: "Odebrat tuto podmínku",
    Designer_Field_FormulaInvalid: "Tento vzorec nelze vyhodnotit. Zkontrolujte závorky a operátory.",
    Designer_Field_FormulaMissing: "Tyto otázky neexistují: {names}.",
    Designer_Field_FormulaPreview: "Když jsou všechny vstupy 10, zobrazí se {value}.",
    Designer_Field_HintYesNo: "Použijte „yes“ nebo „no“",
    Designer_Field_HintMultiDefault: "Více výchozích hodnot oddělte znakem ;",
    Designer_Field_HintSingleDefault: "Musí odpovídat jedné z možností",
    Designer_Field_HintDate: "Použijte „today“ nebo datum, například 2026-03-01",
    Designer_Field_HintTime: "Použijte „now“ nebo čas, například 09:30",
    Designer_Field_QuestionSettings: "Nastavení otázky",
    Designer_Field_Appearance: "Vzhled",
    Designer_Field_Style: "Styl",
    Designer_Field_ImageUrl: "Adresa URL obrázku (volitelné)",
    Designer_Field_Content: "Obsah",
    Designer_Field_BasicFormatting: "Je povoleno základní formátování: tučné písmo, kurzíva, seznamy a odkazy.",
    Designer_Field_TabOptions: "Možnosti",
    Designer_Field_TabBranching: "Větvení",
    Designer_Field_BranchingNeedsQuestion: "Nejprve přidejte další otázku — větvení potřebuje něco, na čem bude záviset.",
    Designer_Field_BranchingToggle: "Zobrazit tuto otázku, pouze když odpovídají jiné odpovědi",
    Designer_Field_Match: "Shoda",
    Designer_Field_MatchAll: "všech těchto",
    Designer_Field_MatchAny: "kterékoli z těchto",
    Designer_Field_AddCondition: "Přidat podmínku",
    Designer_Field_TabValidation: "Ověření",
    Designer_Field_HelpText: "Nápověda",
    Designer_Field_HelpTextPlaceholder: "Zobrazí se pod popiskem otázky",
    Designer_Field_CheckboxLabel: "Popisek zaškrtávacího políčka",
    Designer_Field_Placeholder: "Zástupný text",
    Designer_Field_DefaultAnswer: "Výchozí odpověď",
    Designer_Field_RequiredMessage: "Vlastní zpráva o povinném poli",
    Designer_Field_RequiredMessagePlaceholder: "{title} je povinné",
    Designer_Field_ThisQuestion: "Tato otázka",
    Designer_Field_RequiredMessageDescription: "Zobrazí se místo standardní zprávy, pokud tato otázka zůstane nevyplněná",
    Designer_Field_ReadOnly: "Jen pro čtení (odpověď může pocházet pouze z předvyplněného odkazu)",
    Designer_Field_ValidationRules: "Pravidla ověření",
    Designer_Field_MaxLength: "Maximální délka",
    Designer_Field_Pattern: "Musí odpovídat tomuto vzoru",
    Designer_Field_PatternDescription: "Regulární výraz. Nechte prázdné, pokud se vzor nemá kontrolovat.",
    Designer_Field_PatternMessage: "Zpráva při neshodě se vzorem",
    Designer_Field_PatternMessagePlaceholder: "Tato odpověď není v očekávaném formátu",
    Designer_Field_Format: "Formát",
    Designer_Field_UnitSuffix: "Jednotka zobrazená za hodnotou",
    Designer_Field_UnitSuffixPlaceholder: "kg, hod., položek…",
    Designer_Field_Minimum: "Minimum",
    Designer_Field_Maximum: "Maximum",
    Designer_Field_Decimals: "Desetinná místa",
    Designer_Field_Formula: "Vzorec",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Na jiné otázky odkazujte jejich textem ve složených závorkách. Podporuje + - * / ( ) a round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Dostupné otázky: {questions}",
    Designer_Field_NoneYet: "zatím žádné",
    Designer_Field_Step: "Krok",
    Designer_Field_From: "Od",
    Designer_Field_To: "Do",
    Designer_Field_LowLabel: "Popisek dolního konce",
    Designer_Field_LowLabelPlaceholder: "Vůbec ne pravděpodobné",
    Designer_Field_HighLabel: "Popisek horního konce",
    Designer_Field_HighLabelPlaceholder: "Nanejvýš pravděpodobné",
    Designer_Field_SummarizeAs: "Shrnout jako",
    Designer_Field_SummarizeAverage: "Průměr a rozdělení",
    Designer_Field_SummarizeNps: "Net Promoter Score (vyžaduje škálu 0–10)",
    Designer_Field_NpsWarning: "Net Promoter Score má smysl pouze na škále 0–10. Nastavte Od na 0 a Do na 10.",
    Designer_Field_NumberOfIcons: "Počet ikon",
    Designer_Field_Icon: "Ikona",
    Designer_Field_AllowHalf: "Povolit poloviční hodnoty",
    Designer_Field_ShowOptionsAs: "Zobrazit možnosti jako",
    Designer_Field_DisplayButtons: "Vložená tlačítka",
    Designer_Field_DisplayDropdown: "Rozevírací seznam",
    Designer_Field_DisplayAutomatic: "Automaticky (vložená až do 6 možností)",
    Designer_Field_AllowOther: "Přidat možnost „Jiné“ s volným zadáním",
    Designer_Field_OtherLabel: "Popisek možnosti „Jiné“",
    Designer_Field_OtherPlaceholder: "Jiné",
    Designer_Field_ShuffleOptions: "Náhodné pořadí možností pro každého respondenta",
    Designer_Field_MinSelections: "Minimální počet výběrů",
    Designer_Field_MaxSelections: "Maximální počet výběrů",
    Designer_Field_SourceList: "Zdrojový seznam",
    Designer_Field_ChooseList: "Vyberte seznam",
    Designer_Field_LookupColumn: "Sloupec, ze kterého se načtou možnosti",
    Designer_Field_ChooseColumn: "Vyberte sloupec",
    Designer_Field_ChooseListFirst: "Nejprve vyberte seznam",
    Designer_Field_LookupFilter: "Filtr (volitelné)",
    Designer_Field_LookupFilterDescription: "Filtr OData, který zúží, které zdrojové položky se stanou možnostmi",
    Designer_Field_LookupInfo: "Odpovědi ukládají text možnosti, nikoli odkaz na zdrojovou položku, takže odpovědi zůstanou čitelné, i když se zdrojový seznam později změní.",
    Designer_Field_ConsentText: "Podmínky zobrazené nad zaškrtávacím políčkem",
    Designer_Field_AllowMultiplePeople: "Povolit více osob",
    Designer_Field_AllowGroups: "Povolit také skupiny",
    Designer_Field_IncludeTime: "Zahrnout denní dobu",
    Designer_Field_TimeStep: "Časový krok (minuty)",
    Designer_Field_MaxFiles: "Maximální počet souborů",
    Designer_Field_MaxFileSize: "Max. velikost každého (MB)",
    Designer_Field_AcceptedTypes: "Přijímané typy souborů",
    Designer_Field_AcceptedTypesDescription: "Přípony oddělené čárkami. Nechte prázdné pro přijetí všeho, co SharePoint povoluje.",
    Designer_Field_FilesInfo: "Soubory se ukládají jako přílohy položky odpovědi. SharePoint blokuje některé přípony (například .exe) bez ohledu na to, co zde povolíte.",
    Designer_Field_Rows: "Řádky",
    Designer_Field_ProvisionedNote: "Tato otázka již má sloupec seznamu ({name}). Nastavení, která mění typ sloupce, jsou zamčena — pokud potřebujete jiný typ, otázku duplikujte.",
    Designer_Category_Text: "Text",
    Designer_Category_Choice: "Výběr",
    Designer_Category_Scales: "Škály",
    Designer_Category_Date: "Datum",
    Designer_Category_People: "Osoby",
    Designer_Category_Advanced: "Upřesnit",
    Designer_Category_Layout: "Rozložení",
    Designer_Menu_CommonPresets: "Běžné předvolby",
    Designer_Menu_AllTypes: "Všechny typy otázek",
    Designer_Menu_ChangeType: "Změnit typ",
    Designer_Menu_TypeLockedTitle: "Sloupec seznamu již existuje, takže typ je zamčen. Chcete-li jej změnit, otázku duplikujte.",
    Designer_Menu_MoreSettings: "Větvení, ověření a další",
    Designer_Menu_InsertBelow: "Vložit otázku pod",
    Designer_Card_Duplicate: "Duplikovat",
    Designer_Card_DeleteQuestion: "Odstranit otázku",
    Designer_Outline_Aria: "Osnova otázek",
    Designer_Outline_QuestionCountOne: "{count} otázka",
    Designer_Outline_QuestionCountOther: "{count} otázek",
    Designer_Outline_IssuesTitle: "Položky ke kontrole: {count}",
    Designer_Outline_Find: "Najít otázku",
    Designer_Outline_Empty: "Zatím žádné otázky.",
    Designer_Section_DefaultTitle: "Sekce {number}",
    Designer_Card_Question: "Otázka",
    Designer_Card_BranchingTitle: "Tato otázka se zobrazí, jen když odpovídá pravidlo větvení",
    Designer_Card_BranchingChip: "Větvení",
    Designer_Card_LiveTitle: "Sloupec seznamu existuje, takže typ je zamčen",
    Designer_Card_LiveChip: "Živá",
    Designer_Card_CheckChip: "Zkontrolovat",
    Designer_Option_Placeholder: "Možnost {number}",
    Designer_Option_LabelAria: "Popisek možnosti {number}",
    Designer_Option_ImageUrl: "Adresa URL obrázku",
    Designer_Option_ImageUrlAria: "Adresa URL obrázku možnosti {number}",
    Designer_Option_Remove: "Odebrat možnost",
    Designer_Option_RemoveAria: "Odebrat možnost {number}",
    Designer_Option_Add: "Přidat možnost",
    Designer_Option_OtherHint: "Respondenti mohou také napsat vlastní odpověď s popiskem „{label}“.",
    Designer_Option_OtherFallback: "Jiné",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Odebrat",
    Designer_Grid_RemoveAria: "Odebrat {label} {number}",
    Designer_Grid_Statements: "Tvrzení",
    Designer_Grid_Scale: "Škála",
    Designer_Grid_AddStatement: "Přidat tvrzení",
    Designer_Grid_AddScale: "Přidat škálu",
    Designer_Width_Full: "Plná šířka",
    Designer_Width_Half: "Poloviční šířka",
    Designer_Width_Third: "Třetinová šířka",
    Designer_Width_Aria: "Šířka otázky",
    Designer_Card_BlockLabelPlaceholder: "Popisek bloku (respondentům se nezobrazí)",
    Designer_Card_QuestionText: "Text otázky",
    Designer_Card_MoveUp: "Posunout nahoru",
    Designer_Card_MoveQuestionUp: "Posunout otázku nahoru",
    Designer_Card_MoveDown: "Posunout dolů",
    Designer_Card_MoveQuestionDown: "Posunout otázku dolů",
    Designer_Card_DuplicateQuestion: "Duplikovat otázku",
    Designer_Card_MultipleAnswers: "Více odpovědí",
    Designer_Card_Required: "Povinné",
    Designer_Card_MoreOptions: "Další možnosti",
    Designer_Card_MoreOptionsAria: "Další možnosti pro tuto otázku",
    Designer_Canvas_FormTitle: "Název formuláře",
    Designer_Canvas_DescriptionPlaceholder: "Přidejte popis (volitelné)",
    Designer_Canvas_DescriptionAria: "Popis formuláře",
    Designer_Canvas_EmptyTitle: "Přidejte první otázku",
    Designer_Canvas_EmptyBody: "Začněte výběrem typu otázky. Otázky můžete přeuspořádat přetažením a přidat větvení, aby lidé viděli jen to, co se jich týká.",
    Designer_Section_Chip: "Sekce {number} z {total}",
    Designer_Section_TitlePlaceholder: "Název sekce",
    Designer_Section_TitleAria: "Název sekce {number}",
    Designer_Section_DescriptionPlaceholder: "Popis (volitelné)",
    Designer_Section_DescriptionAria: "Popis sekce {number}",
    Designer_Section_MoveUp: "Posunout sekci nahoru",
    Designer_Section_MoveDown: "Posunout sekci dolů",
    Designer_Section_Delete: "Odstranit sekci",
    Designer_Card_DragToReorder: "Přetažením změníte pořadí",
    Designer_Card_ReorderAria: "Změnit pořadí: {title}",
    Designer_Card_ReorderFallback: "otázka",
    Designer_Canvas_AddNew: "Přidat nové",
    Designer_Canvas_AddSection: "Přidat sekci",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Ulice a číslo",
    Form_Address_Street2Placeholder: "Byt, patro apod. (volitelné)",
    Form_Address_CityPlaceholder: "Město",
    Form_Address_StatePlaceholder: "Kraj / okres",
    Form_Address_PostalCodePlaceholder: "PSČ",
    Form_Address_CountryPlaceholder: "Země",
    Form_Address_StreetAria: "ulice a číslo",
    Form_Address_Street2Aria: "druhý řádek adresy",
    Form_Address_CityAria: "město",
    Form_Address_StateAria: "kraj nebo okres",
    Form_Address_PostalCodeAria: "PSČ",
    Form_Address_CountryAria: "země",
    Form_Consent_DefaultLabel: "Souhlasím",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "Zodpovězeno řádků: {answered} z {total}",
    Form_Lookup_LoadError: "Možnosti pro tuto otázku se nepodařilo načíst.",
    Form_Lookup_Loading: "Načítání možností…",
    Form_Lookup_SelectOptionsPlaceholder: "Vyberte možnosti",
    Form_Lookup_SelectOptionPlaceholder: "Vyberte možnost",
    Form_Person_Placeholder: "Začněte psát jméno…",
    Form_Person_SuggestedPeopleAndGroups: "Navrhované osoby a skupiny",
    Form_Person_SuggestedPeople: "Navrhované osoby",
    Form_Person_NoPeopleOrGroups: "Nebyly nalezeny žádné osoby ani skupiny",
    Form_Person_NoPeople: "Nebyly nalezeny žádné osoby",
    Form_Person_Searching: "Hledání…",
    Form_Ranking_Moved: "Položka {item} byla přesunuta na pozici {position} z {total}",
    Form_Ranking_MoveUp: "Posunout nahoru",
    Form_Ranking_MoveDown: "Posunout dolů",
    Form_Ranking_MoveItemUpAria: "Posunout {item} nahoru",
    Form_Ranking_MoveItemDownAria: "Posunout {item} dolů",
    Form_Rating_ValueText: "{value} z {max}",
    Form_Rating_NotRated: "Nehodnoceno",
    Form_Rating_Clear: "Vymazat hodnocení",
    Form_RichText_Bold: "Tučné",
    Form_RichText_Italic: "Kurzíva",
    Form_RichText_Underline: "Podtržené",
    Form_RichText_BulletedList: "Odrážkový seznam",
    Form_RichText_NumberedList: "Číslovaný seznam",
    Form_RichText_ClearFormatting: "Vymazat formátování",
    Form_RichText_ToolbarAria: "Formátování textu",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} kB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "Soubor „{name}“ byl vynechán — limit je {limit}.",
    Form_File_TypeNotAccepted: "Soubor „{name}“ není přijímaného typu.",
    Form_File_TooLarge: "Soubor „{name}“ je větší než {size} MB.",
    Form_File_AlreadyAttached: "Soubor „{name}“ je již připojen.",
    Form_File_ReadError: "Jeden ze souborů se nepodařilo přečíst. Zkuste jej připojit znovu.",
    Form_File_HintMaxSize: "až {size} MB každý",
    Form_File_HintOneFile: "1 soubor",
    Form_File_HintMaxFiles: "max. {count} souborů",
    Form_File_Reading: "Čtení souborů…",
    Form_File_DropPrompt: "Přetáhněte soubory sem nebo klikněte a procházejte",
    Form_File_Remove: "Odebrat {name}",
    Form_Signature_Alt: "Podpis",
    Form_Signature_AriaSigned: "{label} — podepsáno",
    Form_Signature_AriaEmpty: "{label} — prázdné",
    Form_Signature_Clear: "Vymazat",
    Form_Signature_Signed: "Podepsáno",
    Form_Signature_Prompt: "Podepište se výše myší, perem nebo prstem",
    Form_Time_Placeholder: "Vyberte čas",
    Form_Field_DatePlaceholder: "Vyberte datum",
    Form_Field_TimeAriaWithLabel: "{label} — čas",
    Form_Field_TimeAria: "Čas",
    Form_Field_OtherDefault: "Jiné",
    Form_Field_SelectOptionsPlaceholder: "Vyberte možnosti",
    Form_Field_PleaseSpecify: "Upřesněte prosím",
    Form_Field_OtherSpecifyAria: "{label} — upřesněte prosím",
    Form_Field_SelectOptionPlaceholder: "Vyberte možnost",
    Form_Field_Yes: "Ano",
    Form_Field_No: "Ne",
    Form_Field_SliderHint: "Odpovězte přetažením posuvníku",
    Form_Field_WebAddressAriaWithLabel: "{label} — webová adresa",
    Form_Field_WebAddressAria: "Webová adresa",
    Form_Field_DisplayTextPlaceholder: "Zobrazovaný text (volitelné)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — zobrazovaný text",
    Form_Field_DisplayTextAria: "Zobrazovaný text",
    Form_Field_ChooseBetween: "Vyberte mezi {min} a {max}",
    Form_Field_ChooseAtLeast: "Vyberte alespoň {min}",
    Form_Field_ChooseUpTo: "Vyberte nejvýše {max}",
    Form_Field_SelectedCount: "Vybráno: {count}",
    Form_Field_RequiredAria: "(povinné)",
    Form_Submit_SaveError: "Vaši odpověď se nepodařilo uložit. Ujistěte se, že formulář byl publikován z návrháře a že máte oprávnění přidávat položky do seznamu odpovědí.",
    Form_Empty_Message: "Tento formulář zatím neobsahuje žádné otázky. Vlastník formuláře je může přidat na kartě Otázky.",
    Form_Checking: "Kontrola formuláře…",
    Form_Closed_NotYetOpen: "Zatím neotevřeno",
    Form_Closed_AlreadyAnswered: "Již zodpovězeno",
    Form_Closed_Title: "Formulář je uzavřen",
    Form_Confirmation_PreviewNotice: "Šlo o náhled — do seznamu odpovědí nebylo nic uloženo.",
    Form_Confirmation_PreviewAgain: "Zobrazit náhled znovu",
    Form_Confirmation_SubmitAnother: "Odeslat další odpověď",
    Form_Wizard_StepFallback: "Krok {step}",
    Form_Wizard_StepsAria: "Kroky formuláře",
    Form_Wizard_StepOf: "Krok {step} z {total}",
    Form_ErrorSummary_Title: "Zkontrolujte prosím odpovědi ({count}):",
    Form_ErrorSummary_UntitledQuestion: "Otázka bez názvu",
    Form_ErrorSummary_Question: "Otázka",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Zpět",
    Form_Nav_Next: "Další",
    Form_Draft_Saving: "Ukládání…",
    Form_Draft_Saved: "Koncept uložen",
    Form_Draft_SaveAndFinishLater: "Uložit a dokončit později",
    Form_Draft_NotSaved: "Koncept nebyl uložen",
    Form_Submit_Preview: "Odeslat (náhled)",
    Form_Submit_Button: "Odeslat",
    Form_Response_NoAnswer: "Bez odpovědi",
    Form_Signature_TypeLabel: "Napište své celé jméno",
    Form_Signature_TypeInstead: "Místo toho napsat jméno",
    Form_Signature_DrawInstead: "Místo toho nakreslit",
    Form_Edit_Button: "Upravit předchozí odpověď",
    Form_Edit_Available: "Odpověď jste již odeslali. Můžete ji upravit místo odeslání nové.",
    Form_Edit_Banner: "Upravujete svou předchozí odpověď.",
    Form_Edit_Save: "Aktualizovat odpověď",
    Form_Edit_UpdatedTitle: "Odpověď byla aktualizována",
    Form_Edit_UpdatedMessage: "Vaše změny byly uloženy.",
    Form_Edit_LoadError: "Vaši předchozí odpověď se nepodařilo načíst. Zkuste to prosím znovu.",
    Form_Draft_MissingFiles: "Připojte prosím znovu: {names}. Tyto soubory se nepodařilo obnovit.",
    Form_Attachments_Failed: "Vaše odpovědi byly uloženy, ale tyto přílohy se nepodařilo nahrát: {names}. Zkuste to prosím znovu nebo kontaktujte vlastníka formuláře.",
    Logic_ThisQuestion: "Tato otázka",
    Logic_Required: "Pole {label} je povinné",
    Logic_RequiredConsent: "Pokračujte zaškrtnutím políčka",
    Logic_RequiredFile: "Připojte alespoň jeden soubor",
    Logic_RequiredSignature: "Přidejte svůj podpis",
    Logic_RequiredLikert: "Odpovězte prosím na každý řádek",
    Logic_InvalidEmail: "Zadejte platnou e-mailovou adresu",
    Logic_InvalidPhone: "Zadejte platné telefonní číslo",
    Logic_InvalidUrl: "Zadejte platnou webovou adresu začínající http:// nebo https://",
    Logic_MinValue: "Hodnota musí být alespoň {value}",
    Logic_MaxValue: "Hodnota může být nejvýše {value}",
    Logic_MaxLength: "Maximální délka je {max} znaků",
    Logic_ChooseAtLeastOne: "Vyberte alespoň {count} možnost",
    Logic_ChooseAtLeastMany: "Vyberte alespoň {count} možnosti",
    Logic_ChooseAtMostOne: "Vyberte nejvýše {count} možnost",
    Logic_ChooseAtMostMany: "Vyberte nejvýše {count} možností",
    Logic_LikertRemaining: "Odpovězte prosím na každý řádek (zbývá {count})",
    Logic_MaxFilesOne: "Připojte nejvýše {count} soubor",
    Logic_MaxFilesMany: "Připojte nejvýše {count} souborů",
    Logic_FileTooLarge: "Soubor „{name}“ je větší než {size} MB",
    Logic_FileTypeNotAccepted: "Soubor „{name}“ není přijatelného typu ({types})",
    Logic_AddressRequired: "Zadejte alespoň ulici a město",
    Logic_PatternDefault: "Tato odpověď nemá očekávaný formát",
    Logic_Yes: "Ano",
    Logic_No: "Ne",
    Logic_Agreed: "Souhlasí",
    Logic_NotAgreed: "Nesouhlasí",
    Logic_Signed: "Podepsáno",
    Logic_NoAnswer: "(bez odpovědi)",
    Logic_Unknown: "(neznámé)",
    Logic_OtherSlice: "Ostatní ({count})",
    Logic_CsvResponseId: "ID odpovědi",
    Logic_CsvSubmitted: "Odesláno",
    Logic_CsvSubmittedBy: "Odeslal(a)",
    Logic_EmailQuestion: "Otázka",
    Logic_EmailViewItem: "Zobrazit v Microsoft Lists",
    Logic_EmailFooter: "Odesláno automaticky aplikací Smart Forms.",
    Logic_ClosedDefault: "Tento formulář již nepřijímá odpovědi.",
    Logic_NotYetOpen: "Tento formulář se otevře {date}.",
    Logic_AlreadyResponded: "Na tento formulář jste již odpověděli. Děkujeme!",
    Logic_UntitledQuestion: "Otázka bez názvu",
    Logic_Issue_NoQuestions: "Před shromažďováním odpovědí přidejte alespoň jednu otázku.",
    Logic_Issue_NoTitle: "Jedna otázka nemá text – při publikování bude pojmenována automaticky.",
    Logic_Issue_DuplicateTitle: "Otázka {label} má stejný text jako jiná otázka, takže se výsledky hůře čtou.",
    Logic_Issue_NeedTwoOptions: "Otázka {label} vyžaduje alespoň dvě možnosti.",
    Logic_Issue_ImageNoImage: "Otázka {label} má možnosti bez obrázku – zobrazí se jako textové dlaždice.",
    Logic_Issue_LikertNeedRow: "Otázka {label} vyžaduje alespoň jeden řádek.",
    Logic_Issue_LikertNeedColumns: "Otázka {label} vyžaduje alespoň dva sloupce stupnice.",
    Logic_Issue_NoLookupList: "Pro otázku {label} není vybrán zdrojový seznam.",
    Logic_Issue_NoFormula: "Otázka {label} nemá vzorec.",
    Logic_Issue_BadFormula: "Otázka {label} má vzorec, který nelze vypočítat. Zkontrolujte závorky a operátory.",
    Logic_Issue_MissingRefs: "Otázka {label} odkazuje na neexistující otázky: {names}.",
    Logic_Issue_BadPattern: "Otázka {label} má neplatný vzor ověření.",
    Logic_Issue_BrokenRule: "Otázka {label} má pravidlo větvení odkazující na odstraněnou otázku.",
    Logic_Issue_SelfRule: "Otázka {label} má pravidlo větvení, které odkazuje samo na sebe.",
    Logic_Issue_RuleMismatch: "Otázka {label} má pravidlo větvení, které již neodpovídá otázce, na níž závisí.",
    Logic_Issue_RequiredReadOnly: "Otázka {label} je povinná a zároveň jen pro čtení, takže na ni lze odpovědět jen pomocí předvyplněného odkazu.",
    Logic_Issue_EmptySection: "Sekce nemá žádné otázky a bude přeskočena.",
    Logic_Issue_CloseBeforeOpen: "Datum uzavření je stejné jako datum otevření nebo dřívější, takže formulář nikdy nepřijme žádné odpovědi.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "E-maily o schválení jsou zapnuté, ale krok schválení je vypnutý.",
    Logic_Op_equals: "je",
    Logic_Op_notEquals: "není",
    Logic_Op_contains: "obsahuje",
    Logic_Op_notContains: "neobsahuje",
    Logic_Op_notEmpty: "je zodpovězeno",
    Logic_Op_empty: "není zodpovězeno",
    Logic_Op_greaterThan: "je větší než",
    Logic_Op_greaterOrEqual: "je alespoň",
    Logic_Op_lessThan: "je menší než",
    Logic_Op_lessOrEqual: "je nejvýše",
    Logic_Op_between: "je mezi",
    Logic_Op_before: "je před",
    Logic_Op_after: "je po",
    Logic_Type_Text: "Krátká odpověď",
    Logic_TypeDesc_Text: "Jeden řádek textu",
    Logic_Category_Text: "Text",
    Logic_Type_MultilineText: "Dlouhá odpověď",
    Logic_TypeDesc_MultilineText: "Několik řádků prostého textu",
    Logic_Type_RichText: "Formátovaný text",
    Logic_TypeDesc_RichText: "Tučné písmo, seznamy a odkazy",
    Logic_Type_Choice: "Výběr",
    Logic_TypeDesc_Choice: "Výběr ze seznamu možností",
    Logic_Category_Choice: "Výběr",
    Logic_Type_ImageChoice: "Výběr obrázku",
    Logic_TypeDesc_ImageChoice: "Výběr z obrazových dlaždic",
    Logic_Type_Lookup: "Vyhledávání ze seznamu",
    Logic_TypeDesc_Lookup: "Možnosti načítané živě z jiného seznamu SharePointu",
    Logic_Type_YesNo: "Ano / Ne",
    Logic_TypeDesc_YesNo: "Jednoduchý přepínač zapnuto/vypnuto",
    Logic_Type_Consent: "Souhlas",
    Logic_TypeDesc_Consent: "Zaškrtávací políčko, které musí respondent zaškrtnout, aby mohl pokračovat",
    Logic_Type_Ranking: "Řazení",
    Logic_TypeDesc_Ranking: "Přetažením seřaďte možnosti podle preference",
    Logic_Type_Rating: "Hodnocení",
    Logic_TypeDesc_Rating: "Hvězdičky, srdce nebo palce",
    Logic_Category_Scales: "Stupnice",
    Logic_Type_Scale: "Škála názoru",
    Logic_TypeDesc_Scale: "Číselná škála s popsanými konci",
    Logic_Type_Slider: "Posuvník",
    Logic_TypeDesc_Slider: "Hodnota na posuvné stupnici",
    Logic_Type_Likert: "Likertova mřížka",
    Logic_TypeDesc_Likert: "Ohodnoťte několik tvrzení na jedné společné stupnici",
    Logic_Type_Number: "Číslo",
    Logic_TypeDesc_Number: "Prosté číslo, měna nebo procento",
    Logic_Category_Advanced: "Upřesnění",
    Logic_Type_Calculated: "Vypočítané",
    Logic_TypeDesc_Calculated: "Celkový součet jen pro čtení vypočítaný z jiných odpovědí",
    Logic_Type_Date: "Datum",
    Logic_TypeDesc_Date: "Kalendářní datum, volitelně s časem",
    Logic_Category_Date: "Datum",
    Logic_Type_Time: "Čas",
    Logic_TypeDesc_Time: "Samostatný čas během dne",
    Logic_Type_Person: "Osoba",
    Logic_TypeDesc_Person: "Výběr osoby z organizace",
    Logic_Category_People: "Lidé",
    Logic_Type_Email: "E-mail",
    Logic_TypeDesc_Email: "E-mailová adresa s ověřením",
    Logic_Type_Phone: "Telefon",
    Logic_TypeDesc_Phone: "Telefonní číslo s ověřením",
    Logic_Type_Address: "Adresa",
    Logic_TypeDesc_Address: "Ulice, město, PSČ a země",
    Logic_Type_Hyperlink: "Odkaz",
    Logic_TypeDesc_Hyperlink: "Webová adresa",
    Logic_Type_FileUpload: "Nahrání souboru",
    Logic_TypeDesc_FileUpload: "Připojte k odpovědi jeden nebo více souborů",
    Logic_Type_Signature: "Podpis",
    Logic_TypeDesc_Signature: "Podepište se myší, perem nebo prstem",
    Logic_Type_Content: "Textový blok",
    Logic_TypeDesc_Content: "Pokyny nebo obrázek – neshromažďuje žádnou odpověď",
    Logic_Category_Layout: "Rozložení",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Jak pravděpodobné je, že doporučíte…",
    Logic_Preset_satisfaction: "Spokojenost (1–5)",
    Logic_PresetDesc_satisfaction: "Od velmi nespokojen(a) po velmi spokojen(a)",
    Logic_Preset_currency: "Měna",
    Logic_PresetDesc_currency: "Peněžní částka",
    Logic_Preset_percent: "Procento",
    Logic_PresetDesc_percent: "Procentuální hodnota",
    Logic_Template_blank_Name: "Prázdný formulář",
    Logic_Template_blank_Description: "Začněte od nuly",
    Logic_Template_feedback_Name: "Zpětná vazba zákazníků",
    Logic_Template_feedback_Description: "NPS, hodnocení a otevřené komentáře",
    Logic_Template_event_Name: "Registrace na událost",
    Logic_Template_event_Description: "Údaje o účastnících, sezení a stravovací požadavky",
    Logic_Template_itrequest_Name: "Požadavek na IT službu",
    Logic_Template_itrequest_Description: "Kategorizované požadavky s prioritou a přílohami",
    Logic_Template_expense_Name: "Vyúčtování výdajů",
    Logic_Template_expense_Description: "Položky, účtenky a vypočtený součet",
    Logic_Template_pulse_Name: "Pulzní průzkum zaměstnanců",
    Logic_Template_pulse_Description: "Likertova mřížka, škála zapojení a poznámka o anonymitě",
    Logic_Template_safety_Name: "Bezpečnostní kontrola",
    Logic_Template_safety_Description: "Kontrolní seznam, fotografie a podpis",
    Logic_Template_booking_Name: "Rezervace místnosti nebo zdroje",
    Logic_Template_booking_Description: "Výběr zdroje na základě vyhledávání s časovým úsekem",
    Charts_ColumnChartAria: "Sloupcový graf s kategoriemi: {count}",
    Charts_DonutChartAria: "Prstencový graf s kategoriemi: {count}",
    Charts_NoAnswers: "Zatím žádné odpovědi.",
    Charts_NoResponses: "Zatím žádné odpovědi.",
    Charts_Responses: "Odpovědi",
    Charts_ResponsesOverTime: "Odpovědi v čase",
    Responses_Chart_Answer: "Odpověď",
    Responses_Chart_Average: "Průměr",
    Responses_Chart_AverageOf: "Průměr z {count}",
    Responses_Chart_AveragePosition: "Průměrná pozice",
    Responses_Chart_AverageRange: "Průměr (1–{max})",
    Responses_Chart_AvgValue: "prům. {value}",
    Responses_Chart_Detractors: "Kritici (0–6)",
    Responses_Chart_Max: "Max.",
    Responses_Chart_Maximum: "Maximum",
    Responses_Chart_Median: "Medián",
    Responses_Chart_MentionOne: "{count} zmínka",
    Responses_Chart_MentionOther: "{count} zmínek",
    Responses_Chart_Min: "Min.",
    Responses_Chart_Minimum: "Minimum",
    Responses_Chart_NoAnswers: "Zatím žádné odpovědi.",
    Responses_Chart_NoNumeric: "Zatím žádné číselné odpovědi.",
    Responses_Chart_NoRankings: "Zatím žádná pořadí.",
    Responses_Chart_NoScores: "Zatím žádné skóre.",
    Responses_Chart_NotEnoughText: "Zatím není dost textu ke shrnutí.",
    Responses_Chart_NpsScore: "Skóre NPS",
    Responses_Chart_Option: "Možnost",
    Responses_Chart_Passives: "Pasivní (7–8)",
    Responses_Chart_Promoters: "Propagátoři (9–10)",
    Responses_Chart_ResponseOne: "odpověď",
    Responses_Chart_ResponseOther: "odpovědí",
    Responses_Chart_Responses: "Odpovědi",
    Responses_Chart_ShowingAnswers: "Zobrazeno {shown} z {total} odpovědí.",
    Responses_Chart_Statement: "Tvrzení",
    Responses_Chart_Statistic: "Statistika",
    Responses_Chart_StdDev: "Směrodatná odch.",
    Responses_Chart_StdDeviation: "Směrodatná odchylka",
    Responses_Chart_Total: "Celkem",
    Responses_Chart_Value: "Hodnota",
    Responses_Dashboard_AllHidden: "Všechny otázky jsou na řídicím panelu skryté. Pomocí možnosti „Zobrazit skryté otázky“ je vrátíte zpět.",
    Responses_Dashboard_AnsweredOf: "Zodpovězeno {answered} z {total}",
    Responses_Dashboard_AnsweredOfPinned: "Zodpovězeno {answered} z {total} · připnuto",
    Responses_Dashboard_AveragedAcrossResponses: "Průměr napříč odpověďmi",
    Responses_Dashboard_ByDay: "Po dnech",
    Responses_Dashboard_ByMonth: "Po měsících",
    Responses_Dashboard_ByWeek: "Po týdnech",
    Responses_Dashboard_ChartAuto: "Automaticky",
    Responses_Dashboard_ChartBars: "Pruhy",
    Responses_Dashboard_ChartColumns: "Sloupce",
    Responses_Dashboard_ChartDonut: "Prstenec",
    Responses_Dashboard_ChartGauge: "Ukazatel",
    Responses_Dashboard_ChartHistogram: "Histogram",
    Responses_Dashboard_ChartOptions: "Možnosti grafu",
    Responses_Dashboard_ChartOptionsFor: "Možnosti grafu pro {title}",
    Responses_Dashboard_ChartStatistics: "Statistiky",
    Responses_Dashboard_ChartTable: "Tabulka",
    Responses_Dashboard_ChartWordFrequency: "Četnost slov",
    Responses_Dashboard_EmptyBody: "Jakmile lidé začnou odpovídat, tento řídicí panel se automaticky naplní — hlavními čísly, časovou osou odpovědí a grafem pro otázky, které stojí za sledování.",
    Responses_Dashboard_EmptyTitle: "Zatím žádné odpovědi",
    Responses_Dashboard_Hide: "Skrýt na řídicím panelu",
    Responses_Dashboard_Highlights: "Přehled",
    Responses_Dashboard_Last7Days: "Posledních 7 dní",
    Responses_Dashboard_LatestDate: "Poslední {date}",
    Responses_Dashboard_MedianTimeToComplete: "Medián doby vyplnění",
    Responses_Dashboard_NoPriorWeek: "Není předchozí týden k porovnání",
    Responses_Dashboard_OneEach: "Po jedné",
    Responses_Dashboard_Pin: "Připnout na řídicí panel",
    Responses_Dashboard_QuestionFallback: "otázka",
    Responses_Dashboard_QuestionsAnswered: "Zodpovězené otázky",
    Responses_Dashboard_RecordedOnSubmit: "Zaznamenáno při odeslání",
    Responses_Dashboard_RepeatResponses: "Opakované odpovědi: {count}",
    Responses_Dashboard_ResponsesOverTime: "Odpovědi v čase",
    Responses_Dashboard_ShowHidden: "Zobrazit skryté otázky",
    Responses_Dashboard_SinceMidnight: "Od půlnoci",
    Responses_Dashboard_Today: "Dnes",
    Responses_Dashboard_TotalResponses: "Celkem odpovědí",
    Responses_Dashboard_UniqueRespondents: "Jedineční respondenti",
    Responses_Dashboard_Unpin: "Odepnout z řídicího panelu",
    Responses_Dashboard_UntitledQuestion: "Otázka bez názvu",
    Responses_Dashboard_VsPrevious7Days: "oproti předchozím 7 dnům",
    Responses_Detail_Answers: "Odpovědi",
    Responses_Detail_AsTheForm: "Jako ve formuláři",
    Responses_Detail_Cancel: "Zrušit",
    Responses_Detail_Delete: "Odstranit",
    Responses_Detail_DeleteBody: "Položka seznamu se přesune do koše webu, takže ji odtud lze obnovit.",
    Responses_Detail_DeleteTitle: "Odstranit tuto odpověď?",
    Responses_Detail_Deleting: "Odstraňování…",
    Responses_Detail_Draft: "Koncept",
    Responses_Detail_Header: "Odpověď {index} z {total}",
    Responses_Detail_LoadingAttachments: "Načítání příloh…",
    Responses_Detail_Next: "Další odpověď",
    Responses_Detail_NoAnswer: "Bez odpovědi",
    Responses_Detail_Previous: "Předchozí odpověď",
    Responses_Detail_Print: "Tisk",
    Responses_Detail_Signature: "Podpis",
    Responses_Detail_Signed: "Podepsáno",
    Responses_Detail_Took: "trvalo {duration}",
    Responses_Summary_AnsweredOfType: "Zodpovězeno {answered} z {total} · {type}",
    Responses_Summary_ByField: "Podle: {title}",
    Responses_Summary_CompareBy: "Porovnat podle…",
    Responses_Summary_EmptyBody: "Každá otázka zde dostane vlastní souhrn.",
    Responses_Summary_NoComparison: "Bez porovnání",
    Responses_Summary_NothingToCompare: "Na otázku „{title}“ nikdo neodpověděl, takže není co porovnávat.",
    Responses_Summary_OtherNote: "Grafy s více než {max} kategoriemi seskupí nejmenší do kategorie „Jiné“ — přepnutím karty na Tabulku zobrazíte všechny hodnoty.",
    Responses_Summary_ResponseCountOne: "{count} odpověď",
    Responses_Summary_ResponseCountOther: "{count} odpovědí",
    Responses_Summary_SeeAllAnswers: "Zobrazit všechny odpovědi v tabulce",
    Responses_Summary_SegmentNote: "Zobrazeno {groups} největších skupin. Odpověď s více vybranými možnostmi se zobrazí v každé odpovídající skupině, takže součty skupin mohou přesáhnout {total}.",
    Responses_Summary_SplitBy: "Rozdělit podle: {title}",
    Responses_Summary_Untitled: "bez názvu",
    Responses_Table_Apply: "Použít",
    Responses_Table_Cancel: "Zrušit",
    Responses_Table_ClearSelection: "Zrušit výběr",
    Responses_Table_ColumnOrder: "Pořadí sloupců",
    Responses_Table_ColumnsCount: "Sloupce ({shown}/{total})",
    Responses_Table_Delete: "Odstranit",
    Responses_Table_DeleteBody: "Položky seznamu se přesunou do koše webu, takže je odtud lze obnovit.",
    Responses_Table_DeleteSelected: "Odstranit vybrané",
    Responses_Table_DeleteTitleOne: "Odstranit {count} odpověď?",
    Responses_Table_DeleteTitleOther: "Odstranit odpovědi ({count})?",
    Responses_Table_Deleting: "Odstraňování…",
    Responses_Table_MoveDown: "Posunout dolů",
    Responses_Table_MoveDownFor: "Posunout {title} dolů",
    Responses_Table_MoveUp: "Posunout nahoru",
    Responses_Table_MoveUpFor: "Posunout {title} nahoru",
    Responses_Table_NoColumns: "Zatím nejsou viditelné žádné sloupce s otázkami.",
    Responses_Table_NoMatch: "Aktuálním filtrům neodpovídají žádné odpovědi.",
    Responses_Table_NothingToShow: "Není co zobrazit",
    Responses_Table_OpenResponse: "Otevřít tuto odpověď",
    Responses_Table_OrderNote: "Sloupce Odesláno a Odeslal(a) jsou vždy první. Pořadí přetažením platí pro sloupce s otázkami.",
    Responses_Table_Reorder: "Změnit pořadí",
    Responses_Table_ResetColumns: "Obnovit sloupce",
    Responses_Table_SelectResponse: "Vybrat tuto odpověď",
    Responses_Table_SelectedOne: "Vybrána {count} odpověď",
    Responses_Table_SelectedOther: "Vybrané odpovědi: {count}",
    Responses_Table_ShowAll: "Zobrazit vše",
    Responses_Table_ShowTheseQuestions: "Zobrazit tyto otázky",
    Responses_Table_Submitted: "Odesláno",
    Responses_Table_SubmittedBy: "Odeslal(a)",
    Responses_Table_ToggleSelection: "Přepnout výběr",
    Responses_Table_Unknown: "Neznámé",
    Responses_Table_Untitled: "Bez názvu",
    Responses_View_AllTime: "Za celou dobu",
    Responses_View_AnyAnswer: "Jakákoli odpověď",
    Responses_View_Clear: "Vymazat",
    Responses_View_CopyShareLink: "Kopírovat odkaz pro sdílení",
    Responses_View_CountFiltered: "{shown} z {total} odpovědí",
    Responses_View_CountOne: "{count} odpověď",
    Responses_View_CountOther: "{count} odpovědí",
    Responses_View_Dashboard: "Řídicí panel",
    Responses_View_DateRange: "Časové období",
    Responses_View_EmptyBody: "Sdílejte formulář a začněte sbírat odpovědi. Odpovědi se ukládají do seznamu „{list}“ a hned se zde zobrazí.",
    Responses_View_EmptyTitle: "Zatím žádné odpovědi",
    Responses_View_ExportCsv: "Exportovat do CSV",
    Responses_View_FilterByAnswer: "Filtrovat podle odpovědi",
    Responses_View_FilterByQuestion: "Filtrovat podle otázky",
    Responses_View_FilterValue: "Hodnota filtru",
    Responses_View_Last30Days: "Posledních 30 dní",
    Responses_View_Last7Days: "Posledních 7 dní",
    Responses_View_Last90Days: "Posledních 90 dní",
    Responses_View_LoadError: "Odpovědi se nepodařilo načíst. Jednou formulář publikujte, aby existovaly sloupce seznamu, a zkuste to znovu.",
    Responses_View_Loading: "Načítání odpovědí…",
    Responses_View_MoreActions: "Další akce s odpovědí",
    Responses_View_PreviewForm: "Zobrazit náhled formuláře",
    Responses_View_Refresh: "Aktualizovat",
    Responses_View_ResponsesTab: "Odpovědi ({count})",
    Responses_View_SearchPlaceholder: "Hledat ve všech odpovědích",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Vyberte hodnotu",
    Responses_View_Summary: "Souhrn",
    Responses_View_Today: "Dnes",
    Responses_View_Truncated: "Tento seznam obsahuje více odpovědí, než kolik Smart Forms načte najednou. Zobrazuje se nejnovějších {count} — úplnou sadu otevřete v Microsoft Lists.",
    Responses_View_TryAgain: "Zkusit znovu",
    Responses_View_Untitled: "Bez názvu",
    Responses_Approval_Column: "Schválení",
    Responses_Approval_ReviewerColumn: "Zkontroloval(a)",
    Responses_Approval_CommentColumn: "Komentář recenzenta",
    Responses_Approval_Pending: "Čeká na vyřízení",
    Responses_Approval_Approved: "Schváleno",
    Responses_Approval_Rejected: "Zamítnuto",
    Responses_Approval_AnyStatus: "Libovolný stav schválení",
    Responses_Approval_FilterLabel: "Filtrovat podle stavu schválení",
    Responses_Approval_ApproveSelected: "Schválit vybrané",
    Responses_Approval_RejectSelected: "Zamítnout vybrané",
    Responses_Approval_BulkFailed: "Nepodařilo se aktualizovat odpovědi: {count}. Zkuste to znovu.",
    Responses_Approval_Approve: "Schválit",
    Responses_Approval_Reject: "Zamítnout",
    Responses_Approval_Reset: "Obnovit na čekající",
    Responses_Approval_CommentLabel: "Komentář (volitelné)",
    Responses_Approval_ReviewedBy: "Zkontroloval(a) {name}",
    Responses_Approval_Error: "Rozhodnutí se nepodařilo uložit. Zkuste to znovu.",
    Responses_Dashboard_ApprovalStatus: "Čeká na kontrolu",
    Responses_Dashboard_ApprovalBreakdown: "{pending} čeká, {approved} schváleno, {rejected} zamítnuto",
    Responses_Dashboard_TimelineCoarsened: "Časové rozmezí je dlouhé, proto byla časová osa seskupena hruběji ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Časové rozmezí je velmi dlouhé, proto se zobrazuje jen posledních {count} období.",
    Service_Item_DefaultTitle: "Odpověď – {date}",
    Service_Email_ApprovalSubject: "Stav vaší odpovědi: {status} – {title}",
    Service_Email_ApprovalHeading: "Stav vaší odpovědi: {status}",
    Service_Email_ApprovalIntro: "Recenzent označil vaši odpověď na „{title}“ stavem: {status}.",
    Service_Email_ApprovalCommentLabel: "Komentář recenzenta",
    Service_Approval_Approved: "schválena",
    Service_Approval_Rejected: "zamítnuta",
    Service_Approval_Pending: "čekající",
    Service_Lookup_InvalidFilter: "Filtr vyhledávání není platný.",
    Service_Edit_NotAllowed: "Tento formulář nepovoluje úpravy odeslané odpovědi.",
    Service_Edit_NotYours: "Upravovat můžete pouze vlastní odpověď.",
    Service_Signature_AttachmentLabel: "Podpis",
    PropertyPane_ListsLoadFailed: "Seznamy na tomto webu se nepodařilo načíst.",
    PropertyPane_EnterListName: "Nejprve zadejte název nového seznamu.",
    PropertyPane_CreatingList: "Vytváří se „{name}“…",
    PropertyPane_ListCreated: "Seznam „{title}“ byl vytvořen a vybrán.",
    PropertyPane_ListAlreadyExists: "Seznam s názvem „{name}“ již existuje — vyberte jej v rozevíracím seznamu výše.",
    PropertyPane_CreateListFailed: "Seznam se nepodařilo vytvořit. Zkontrolujte, zda máte oprávnění vytvářet seznamy na tomto webu.",
    PropertyPane_Description: "Vyberte seznam SharePointu, do kterého se ukládají odpovědi formuláře, nebo vytvořte nový. Vše ostatní — otázky, vzhled, oznámení — se upravuje přímo na stránce.",
    PropertyPane_ResponseList_GroupName: "Seznam odpovědí",
    PropertyPane_ListDropdown_Label: "Ukládat odpovědi do tohoto seznamu",
    PropertyPane_ResponsesGoTo: "Odpovědi se ukládají do „{name}“.",
    PropertyPane_PickList: "Vyberte seznam nebo níže vytvořte nový.",
    PropertyPane_LoadingLists: "Načítání seznamů…",
    PropertyPane_NewListName_Label: "Nebo vytvořte nový seznam",
    PropertyPane_NewListName_Placeholder: "Název nového seznamu",
    PropertyPane_CreateList_Button: "Vytvořit seznam",
    PropertyPane_Tips_GroupName: "Tipy",
    PropertyPane_Tip_AutoSave: "Otázky a nastavení se ukládají automaticky při úpravách — stránku není třeba ukládat ani publikovat.",
    PropertyPane_Tip_Permissions: "Respondenti potřebují oprávnění přidávat položky do seznamu odpovědí. Pokud někdo hlásí chybu při odeslání, zkontrolujte oprávnění seznamu.",
    PropertyPane_Tip_Share: "Pomocí tlačítka „Sbírat odpovědi“ na stránce vytvoříte sloupce seznamu a získáte odkaz k vyplnění, který lze sdílet.",
    App_ErrorBoundary_Title: "Smart Forms — chyba vykreslení",
    App_ErrorBoundary_Message: "Zpráva:",
    App_ErrorBoundary_Stack: "Zásobník:",
    App_ErrorBoundary_NoStack: "(zásobník není k dispozici)",
    App_ErrorBoundary_ConsoleNote: "Úplné podrobnosti byly také zapsány do konzoly prohlížeče.",
    App_DefaultQuestionTitle: "Otázka {number}",
    App_Error_ListMissing: "Seznam nakonfigurovaný pro tento formulář již neexistuje. Vyberte jiný seznam v nastavení webové části.",
    App_Error_LoadConfig: "Při načítání konfigurace formuláře se něco pokazilo.",
    App_Error_Unable: "Formulář se nepodařilo načíst.",
    App_Publish_ConflictNotice: "„{title}“ již má sloupec seznamu jiného typu ({type}). Přejmenujte otázku, aby bylo možné vytvořit nový sloupec, nebo vraťte její typ zpět.",
    App_Publish_ConflictUnnamedQuestion: "otázka",
    App_Publish_ColumnsAddedOne: "Do seznamu „{list}“ byl přidán {count} sloupec.",
    App_Publish_ColumnsAddedOther: "Do seznamu „{list}“ byl přidán počet sloupců: {count}.",
    App_Publish_TheList: "seznam",
    App_Publish_UpToDate: "Seznam odpovědí je již aktuální.",
    App_Publish_Error: "Sloupce seznamu se nepodařilo vytvořit. Obvykle to znamená, že nemáte oprávnění Správa seznamů pro seznam odpovědí, může se to ale stát i na webech s vypnutými vlastními skripty. Podívejte se do konzoly prohlížeče na podrobnosti chyby nebo to zkuste znovu.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Vytvořte dokonalý formulář nad seznamem SharePointu — typů otázek: {count}, logika větvení, nahrávání souborů, sdílitelné odkazy k vyplnění a řídicí panel s výsledky.",
    App_Placeholder_ChooseList: "Vyberte nebo vytvořte seznam",
    App_Placeholder_Hint: "Chcete-li začít, upravte stránku a nakonfigurujte tuto webovou část.",
    App_Loading: "Načítání formuláře…",
    App_OpenSettings: "Otevřít nastavení",
    App_Tab_Questions: "Otázky",
    App_Tab_QuestionsWithCount: "Otázky ({count})",
    App_Tab_Responses: "Odpovědi",
    App_Tab_Responses_Title: "Odpovědi se ukládají do „{list}“",
    App_Templates_Start: "Začít ze šablony",
    App_Settings_Title: "Nastavení formuláře — vzhled, oznámení, přístup",
    App_Settings_AriaLabel: "Nastavení formuláře",
    App_Preview: "Náhled",
    App_Preview_Close: "Zavřít náhled",
    App_Preview_Hint: "Náhled — nic, co zde odešlete, se neuloží. Ověření a větvení se chovají přesně tak, jak se budou chovat pro respondenty.",
    App_Publish_GettingReady: "Příprava…",
    App_Publish_CollectResponses: "Sbírat odpovědi",
    App_Publish_Share: "Sdílet",
    App_Retry: "Zkusit znovu",
    App_SaveError_Banner: "Poslední změnu se nepodařilo uložit. Zkontrolujte připojení a zkuste to znovu.",
    App_Preflight_BlockingTitle: "Před sběrem odpovědí opravte",
    App_Preflight_WarningTitle: "Nejdřív se na to podívejte",
    App_Preflight_BlockingText: "Tyto problémy by zabránily správné funkci publikovaného formuláře.",
    App_Preflight_WarningText: "Nic není rozbité, ale před sdílením odkazu je obvykle vhodné to opravit.",
    App_Preflight_GoTo: "Přejít na",
    App_Preflight_CollectAnyway: "Přesto sbírat odpovědi",
    App_Preflight_Back: "Zpět na formulář",
    App_Cancel: "Zrušit",
    App_Done: "Hotovo",
    App_Share_Title: "Váš formulář je připraven ke sdílení",
    App_Share_SubText: "Pošlete tento odkaz každému, kdo má formulář vyplnit.",
    App_Share_LinkAriaLabel: "Odkaz pro sdílení",
    App_Share_Copy: "Kopírovat",
    App_Share_Copied: "Zkopírováno",
    App_Share_AddItemsEmphasis: "přidávat položky",
    App_Share_PermissionNote: "Respondenti potřebují oprávnění {addItems} do „{title}“ a přístup k této stránce. Pokud někdo při odeslání dostane chybu, je to téměř vždy tím.",
    App_Share_PrefillNote: "Otázky můžete v odkazu předvyplnit přidáním názvu sloupce, například {example}.",
    App_Templates_ReplaceWarning: "Výběrem šablony nahradíte aktuální otázky.",
    App_Templates_PickStart: "Vyberte výchozí bod — cokoli můžete později změnit.",
    App_Templates_Empty: "Prázdný",
    App_Templates_QuestionCount: "Otázky: {count}",
    App_SaveChip_SavingTitle: "Ukládání poslední úpravy",
    App_SaveChip_Saving: "Ukládání…",
    App_SaveChip_FailedTitle: "Poslední úpravu se nepodařilo uložit. Zkontrolujte připojení a zkuste to znovu.",
    App_SaveChip_Failed: "Uložení se nezdařilo",
    App_SaveChip_SavedTitle: "Všechny změny jsou uloženy",
    App_SaveChip_Saved: "Uloženo",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Nová odpověď — {title}",
    Service_Email_NewResponseHeading: "Nová odpověď: {title}",
    Service_Email_NewResponseIntro: "Někdo právě odeslal odpověď — {date}.",
    Service_Email_ReceiptSubject: "Vaše odpověď — {title}",
    Service_Email_ReceiptHeading: "Děkujeme za vaši odpověď!",
    Service_Email_ReceiptIntro: "Zde je kopie toho, co jste odeslali do formuláře „{title}“.",
    App_History_Title: "Historie verzí",
    App_History_RestoredNotice: "Byla obnovena verze uložená {date}. Zkontrolujte ji a poté pomocí Shromažďovat odpovědi publikujte případné nové otázky.",
    App_History_Undo: "Vrátit obnovení zpět",
    App_Share_CopyManual: "Prohlížeč zablokoval kopírování. Vyberte odkaz výše a zkopírujte ho stisknutím Ctrl+C (na Macu Cmd+C).",
    App_Share_TeamsNote: "Jste v Microsoft Teams. Tento odkaz otevře přímo stránku SharePointu, takže příjemci potřebují přístup k webu.",
    App_Share_PrefillNotSecure: "Předvyplněné odpovědi slouží jen pro pohodlí: kdokoli s odkazem je může změnit, proto je nikdy nepovažujte za bezpečnostní hranici.",
    Designer_Section_DropHere: "Přetáhněte sem otázku",
    Designer_Section_DropEnd: "Pusťte zde a přesunete na konec této sekce",
    Designer_Rules_RemovedOne: "Bylo odebráno 1 pravidlo větvení, které už nevyhovovalo.",
    Designer_Rules_RemovedOther: "Počet odebraných pravidel větvení, která už nevyhovovala: {count}.",
    Designer_Settings_AllowEdit: "Povolit respondentům upravovat své odpovědi",
    Designer_Settings_AllowEditHint: "Respondenti mohou znovu otevřít a aktualizovat to, co odeslali. Každý může upravovat jen svou vlastní odpověď.",
    Designer_Settings_EnableApproval: "Povolit pracovní postup schvalování",
    Designer_Settings_ApprovalNotify: "Poslat respondentovi e-mail o rozhodnutí",
    Designer_Settings_ApprovalHint: "Při dalším publikování přidá do seznamu odpovědí sloupce schvalování. Vlastníci odpovědi schvalují nebo zamítají na kartě Odpovědi.",
    Designer_History_Title: "Historie verzí",
    Designer_History_Intro: "Dříve uložené verze otázek a nastavení tohoto formuláře. Obnovením se verze načte do návrháře; můžete ji vrátit zpět a nové otázky se vytvoří až při publikování.",
    Designer_History_Loading: "Načítání verzí...",
    Designer_History_Empty: "Nebyly nalezeny žádné dřívější verze. Historie verzí vyžaduje zapnuté verzování seznamu „Smart Forms Config“ a alespoň jednu uloženou úpravu.",
    Designer_History_Latest: "Nejnovější",
    Designer_History_LatestTitle: "Toto je aktuálně používaná verze",
    Designer_History_By: "od {name}",
    Designer_History_UnknownAuthor: "Neznámý autor",
    Designer_History_VersionLabel: "verze {label}",
    Designer_History_Preview: "Náhled",
    Designer_History_Restore: "Obnovit",
    Designer_History_QuestionsOne: "1 otázka",
    Designer_History_QuestionsOther: "Otázek: {count}",
    Designer_History_LoadFailed: "Tuto verzi se nepodařilo načíst.",
    Designer_History_ConfirmTitle: "Obnovit tuto verzi?",
    Designer_History_ConfirmText: "Formulář bude nahrazen verzí uloženou {date} (otázek: {count}). Hned poté to můžete vrátit zpět."
  };
});
