define([], function () {
  return {
    Designer_Color_Blue: "Blå",
    Designer_Color_Teal: "Blågrøn",
    Designer_Color_Green: "Grøn",
    Designer_Color_Purple: "Lilla",
    Designer_Color_Magenta: "Magenta",
    Designer_Color_Red: "Rød",
    Designer_Color_Orange: "Orange",
    Designer_Color_Gray: "Grå",
    Designer_Settings_LayoutSinglePage: "Alle spørgsmål på én side",
    Designer_Settings_LayoutWizard: "Ét afsnit pr. trin (guide)",
    Designer_Settings_Title: "Formularindstillinger",
    Designer_Common_Apply: "Anvend",
    Designer_Common_Cancel: "Annuller",
    Designer_Settings_TabBasics: "Grundlæggende",
    Designer_Settings_FormTitle: "Formulartitel",
    Designer_Settings_Description: "Beskrivelse",
    Designer_Settings_Layout: "Layout",
    Designer_Settings_NumberQuestions: "Nummerer spørgsmålene",
    Designer_Settings_ShuffleQuestions: "Bland rækkefølgen af spørgsmål for hver respondent",
    Designer_Settings_ShowProgressBar: "Vis en statuslinje",
    Designer_Settings_TabAppearance: "Udseende",
    Designer_Settings_AccentColor: "Accentfarve",
    Designer_Settings_CustomColorTitle: "Brugerdefineret farve",
    Designer_Settings_CustomColorAria: "Brugerdefineret accentfarve",
    Designer_Settings_AccentHint: "Accentfarver justeres automatisk for kontrast på mørke websteder, så formularen forbliver læsbar uanset sidens tema.",
    Designer_Settings_ShowHeader: "Vis formularens sidehoved",
    Designer_Settings_HeaderIcon: "Ikon i sidehoved",
    Designer_Settings_TabAfterSubmit: "Efter afsendelse",
    Designer_Settings_SubmitButtonText: "Tekst på knappen Send",
    Designer_Settings_SubmitPlaceholder: "Send",
    Designer_Settings_ThankYouTitle: "Titel på tak-besked",
    Designer_Settings_ThankYouPlaceholder: "Tak!",
    Designer_Settings_ThankYouMessage: "Tak-besked",
    Designer_Settings_ShowSubmitAnother: "Vis knappen \"Send endnu et svar\"",
    Designer_Settings_TabNotifications: "Meddelelser",
    Designer_Settings_EmailEachResponseTo: "Send hvert svar pr. mail til",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "Personer i din organisation får hvert svar pr. mail med et link til listeelementet",
    Designer_Settings_RespondentReceipt: "Send respondenterne en kopi af deres svar pr. mail",
    Designer_Settings_NotificationsInfo: "Meddelelser bruger SharePoints egen mailtjeneste, så modtagerne skal være brugere i din organisation. Eksterne adresser fjernes uden besked.",
    Designer_Settings_TabAccess: "Adgang",
    Designer_Settings_OpenFrom: "Åbn fra",
    Designer_Settings_OpenImmediately: "Åbn med det samme",
    Designer_Settings_CloseAfter: "Luk efter",
    Designer_Settings_NeverClose: "Luk aldrig",
    Designer_Settings_ClearDates: "Ryd datoer",
    Designer_Settings_DatesInverted: "Lukkedatoen er den samme som eller ligger før åbningsdatoen, så formularen ville aldrig acceptere svar.",
    Designer_Settings_MaxResponses: "Stop efter dette antal svar",
    Designer_Settings_NoLimit: "Ingen grænse",
    Designer_Settings_OneResponsePerPerson: "Tillad kun ét svar pr. person",
    Designer_Settings_AllowSaveDraft: "Lad respondenter gemme en kladde og gøre den færdig senere",
    Designer_Settings_ClosedMessage: "Besked, der vises, når formularen er lukket",
    Designer_Settings_ClosedMessagePlaceholder: "Denne formular accepterer ikke længere svar.",
    Designer_Settings_AccessInfo: "Disse grænser håndhæves af formularen, ikke af SharePoint. Alle med tilladelse til at tilføje elementer til svarlisten kan stadig tilføje et direkte via listen.",
    Designer_Field_StyleInfo: "Info (accent)",
    Designer_Field_StyleSuccess: "Succes (grøn)",
    Designer_Field_StyleWarning: "Advarsel (rav)",
    Designer_Field_StylePlain: "Almindelig tekst",
    Designer_Field_StyleDivider: "Skillelinje",
    Designer_Field_IconStars: "Stjerner",
    Designer_Field_IconHearts: "Hjerter",
    Designer_Field_IconThumbs: "Tommelfinger op",
    Designer_Field_FormatPlain: "Almindeligt tal",
    Designer_Field_FormatCurrency: "Valuta",
    Designer_Field_FormatPercent: "Procent",
    Designer_Field_UntitledQuestion: "Unavngivet spørgsmål",
    Designer_Field_DeletedQuestion: "et slettet spørgsmål",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} og {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "ELLER",
    Designer_Rule_JoinAll: "OG",
    Designer_Rule_Preview: "Vises, når {conditions}.",
    Designer_Field_Yes: "Ja",
    Designer_Field_No: "Nej",
    Designer_Field_When: "Når",
    Designer_Field_SelectValue: "Vælg en værdi",
    Designer_Field_DateValuePlaceholder: "ÅÅÅÅ-MM-DD eller \"today\"",
    Designer_Field_ValuePlaceholder: "Værdi",
    Designer_Field_UpperBound: "Øvre grænse",
    Designer_Field_RemoveCondition: "Fjern denne betingelse",
    Designer_Field_FormulaInvalid: "Denne formel kan ikke beregnes. Kontroller parenteser og operatorer.",
    Designer_Field_FormulaMissing: "Disse spørgsmål findes ikke: {names}.",
    Designer_Field_FormulaPreview: "Når alle input er 10, viser dette {value}.",
    Designer_Field_HintYesNo: "Brug \"yes\" eller \"no\"",
    Designer_Field_HintMultiDefault: "Adskil flere standardværdier med ;",
    Designer_Field_HintSingleDefault: "Skal matche en af indstillingerne",
    Designer_Field_HintDate: "Brug \"today\" eller en dato som 2026-03-01",
    Designer_Field_HintTime: "Brug \"now\" eller et klokkeslæt som 09:30",
    Designer_Field_QuestionSettings: "Spørgsmålsindstillinger",
    Designer_Field_Appearance: "Udseende",
    Designer_Field_Style: "Typografi",
    Designer_Field_ImageUrl: "Billed-URL (valgfrit)",
    Designer_Field_Content: "Indhold",
    Designer_Field_BasicFormatting: "Grundlæggende formatering er tilladt: fed, kursiv, lister og links.",
    Designer_Field_TabOptions: "Indstillinger",
    Designer_Field_TabBranching: "Forgrening",
    Designer_Field_BranchingNeedsQuestion: "Tilføj først et andet spørgsmål — forgrening har brug for noget at afhænge af.",
    Designer_Field_BranchingToggle: "Vis kun dette spørgsmål, når andre svar matcher",
    Designer_Field_Match: "Match",
    Designer_Field_MatchAll: "alle disse",
    Designer_Field_MatchAny: "en af disse",
    Designer_Field_AddCondition: "Tilføj betingelse",
    Designer_Field_TabValidation: "Validering",
    Designer_Field_HelpText: "Hjælpetekst",
    Designer_Field_HelpTextPlaceholder: "Vises under spørgsmålsetiketten",
    Designer_Field_CheckboxLabel: "Etiket til afkrydsningsfelt",
    Designer_Field_Placeholder: "Pladsholder",
    Designer_Field_DefaultAnswer: "Standardsvar",
    Designer_Field_RequiredMessage: "Brugerdefineret besked om obligatorisk felt",
    Designer_Field_RequiredMessagePlaceholder: "{title} er påkrævet",
    Designer_Field_ThisQuestion: "Dette spørgsmål",
    Designer_Field_RequiredMessageDescription: "Vises i stedet for standardbeskeden, når dette spørgsmål efterlades tomt",
    Designer_Field_ReadOnly: "Skrivebeskyttet (svaret kan kun komme fra et forudfyldt link)",
    Designer_Field_ValidationRules: "Valideringsregler",
    Designer_Field_MaxLength: "Maksimal længde",
    Designer_Field_Pattern: "Skal matche dette mønster",
    Designer_Field_PatternDescription: "Et regulært udtryk. Lad feltet være tomt for ingen mønsterkontrol.",
    Designer_Field_PatternMessage: "Besked, når mønsteret ikke matcher",
    Designer_Field_PatternMessagePlaceholder: "Dette svar har ikke det forventede format",
    Designer_Field_Format: "Format",
    Designer_Field_UnitSuffix: "Enhed vist efter værdien",
    Designer_Field_UnitSuffixPlaceholder: "kg, timer, stk…",
    Designer_Field_Minimum: "Minimum",
    Designer_Field_Maximum: "Maksimum",
    Designer_Field_Decimals: "Decimaler",
    Designer_Field_Formula: "Formel",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Henvis til andre spørgsmål med deres tekst i tuborgparenteser. Understøtter + - * / ( ) samt round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Tilgængelige spørgsmål: {questions}",
    Designer_Field_NoneYet: "ingen endnu",
    Designer_Field_Step: "Trin",
    Designer_Field_From: "Fra",
    Designer_Field_To: "Til",
    Designer_Field_LowLabel: "Etiket i den lave ende",
    Designer_Field_LowLabelPlaceholder: "Slet ikke sandsynligt",
    Designer_Field_HighLabel: "Etiket i den høje ende",
    Designer_Field_HighLabelPlaceholder: "Yderst sandsynligt",
    Designer_Field_SummarizeAs: "Opsummer som",
    Designer_Field_SummarizeAverage: "Gennemsnit og fordeling",
    Designer_Field_SummarizeNps: "Net Promoter Score (kræver en skala fra 0–10)",
    Designer_Field_NpsWarning: "Net Promoter Score giver kun mening på en skala fra 0–10. Sæt Fra til 0 og Til til 10.",
    Designer_Field_NumberOfIcons: "Antal ikoner",
    Designer_Field_Icon: "Ikon",
    Designer_Field_AllowHalf: "Tillad halve værdier",
    Designer_Field_ShowOptionsAs: "Vis indstillinger som",
    Designer_Field_DisplayButtons: "Indlejrede knapper",
    Designer_Field_DisplayDropdown: "Rullemenu",
    Designer_Field_DisplayAutomatic: "Automatisk (indlejret op til 6 indstillinger)",
    Designer_Field_AllowOther: "Tilføj en fritekstindstilling \"Andet\"",
    Designer_Field_OtherLabel: "Etiket til indstillingen \"Andet\"",
    Designer_Field_OtherPlaceholder: "Andet",
    Designer_Field_ShuffleOptions: "Bland rækkefølgen af indstillinger for hver respondent",
    Designer_Field_MinSelections: "Minimum antal valg",
    Designer_Field_MaxSelections: "Maksimum antal valg",
    Designer_Field_SourceList: "Kildeliste",
    Designer_Field_ChooseList: "Vælg en liste",
    Designer_Field_LookupColumn: "Kolonne, som indstillinger læses fra",
    Designer_Field_ChooseColumn: "Vælg en kolonne",
    Designer_Field_ChooseListFirst: "Vælg først en liste",
    Designer_Field_LookupFilter: "Filter (valgfrit)",
    Designer_Field_LookupFilterDescription: "Et OData-filter, der afgrænser, hvilke kildeelementer der bliver til indstillinger",
    Designer_Field_LookupInfo: "Svar gemmer indstillingens tekst, ikke et link til kildeelementet, så svarene forbliver læsbare, selvom kildelisten ændres senere.",
    Designer_Field_ConsentText: "Vilkår vist over afkrydsningsfeltet",
    Designer_Field_AllowMultiplePeople: "Tillad flere personer",
    Designer_Field_AllowGroups: "Tillad også grupper",
    Designer_Field_IncludeTime: "Medtag et klokkeslæt",
    Designer_Field_TimeStep: "Tidstrin (minutter)",
    Designer_Field_MaxFiles: "Maksimum antal filer",
    Designer_Field_MaxFileSize: "Maks. størrelse pr. fil (MB)",
    Designer_Field_AcceptedTypes: "Accepterede filtyper",
    Designer_Field_AcceptedTypesDescription: "Filtypenavne adskilt af kommaer. Lad feltet være tomt for at acceptere alt, hvad SharePoint tillader.",
    Designer_Field_FilesInfo: "Filer gemmes som vedhæftede filer på svarelementet. SharePoint blokerer visse filtypenavne (f.eks. .exe) uanset, hvad du tillader her.",
    Designer_Field_Rows: "Rækker",
    Designer_Field_ProvisionedNote: "Dette spørgsmål har allerede en listekolonne ({name}). Indstillinger, der ændrer kolonnens type, er låst — dupliker spørgsmålet, hvis du har brug for en anden type.",
    Designer_Category_Text: "Tekst",
    Designer_Category_Choice: "Valg",
    Designer_Category_Scales: "Skalaer",
    Designer_Category_Date: "Dato",
    Designer_Category_People: "Personer",
    Designer_Category_Advanced: "Avanceret",
    Designer_Category_Layout: "Layout",
    Designer_Menu_CommonPresets: "Almindelige forudindstillinger",
    Designer_Menu_AllTypes: "Alle spørgsmålstyper",
    Designer_Menu_ChangeType: "Skift type",
    Designer_Menu_TypeLockedTitle: "Listekolonnen findes allerede, så typen er låst. Dupliker spørgsmålet for at ændre den.",
    Designer_Menu_MoreSettings: "Forgrening, validering m.m.",
    Designer_Menu_InsertBelow: "Indsæt spørgsmål nedenfor",
    Designer_Card_Duplicate: "Dupliker",
    Designer_Card_DeleteQuestion: "Slet spørgsmål",
    Designer_Outline_Aria: "Spørgsmålsoversigt",
    Designer_Outline_QuestionCountOne: "{count} spørgsmål",
    Designer_Outline_QuestionCountOther: "{count} spørgsmål",
    Designer_Outline_IssuesTitle: "{count} problem(er) at gennemgå",
    Designer_Outline_Find: "Find et spørgsmål",
    Designer_Outline_Empty: "Ingen spørgsmål endnu.",
    Designer_Section_DefaultTitle: "Afsnit {number}",
    Designer_Card_Question: "Spørgsmål",
    Designer_Card_BranchingTitle: "Dette spørgsmål vises kun, når en forgreningsregel matcher",
    Designer_Card_BranchingChip: "Forgrening",
    Designer_Card_LiveTitle: "Listekolonnen findes, så typen er låst",
    Designer_Card_LiveChip: "Aktiv",
    Designer_Card_CheckChip: "Kontroller",
    Designer_Option_Placeholder: "Indstilling {number}",
    Designer_Option_LabelAria: "Etiket for indstilling {number}",
    Designer_Option_ImageUrl: "Billed-URL",
    Designer_Option_ImageUrlAria: "Billed-URL for indstilling {number}",
    Designer_Option_Remove: "Fjern indstilling",
    Designer_Option_RemoveAria: "Fjern indstilling {number}",
    Designer_Option_Add: "Tilføj indstilling",
    Designer_Option_OtherHint: "Respondenter kan også skrive et svar med etiketten “{label}”.",
    Designer_Option_OtherFallback: "Andet",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Fjern",
    Designer_Grid_RemoveAria: "Fjern {label} {number}",
    Designer_Grid_Statements: "Udsagn",
    Designer_Grid_Scale: "Skala",
    Designer_Grid_AddStatement: "Tilføj udsagn",
    Designer_Grid_AddScale: "Tilføj skala",
    Designer_Width_Full: "Fuld bredde",
    Designer_Width_Half: "Halv bredde",
    Designer_Width_Third: "En tredjedel bredde",
    Designer_Width_Aria: "Spørgsmålets bredde",
    Designer_Card_BlockLabelPlaceholder: "Bloketiket (vises ikke for respondenter)",
    Designer_Card_QuestionText: "Spørgsmålstekst",
    Designer_Card_MoveUp: "Flyt op",
    Designer_Card_MoveQuestionUp: "Flyt spørgsmål op",
    Designer_Card_MoveDown: "Flyt ned",
    Designer_Card_MoveQuestionDown: "Flyt spørgsmål ned",
    Designer_Card_DuplicateQuestion: "Dupliker spørgsmål",
    Designer_Card_MultipleAnswers: "Flere svar",
    Designer_Card_Required: "Påkrævet",
    Designer_Card_MoreOptions: "Flere indstillinger",
    Designer_Card_MoreOptionsAria: "Flere indstillinger for dette spørgsmål",
    Designer_Canvas_FormTitle: "Formulartitel",
    Designer_Canvas_DescriptionPlaceholder: "Tilføj en beskrivelse (valgfrit)",
    Designer_Canvas_DescriptionAria: "Formularbeskrivelse",
    Designer_Canvas_EmptyTitle: "Tilføj dit første spørgsmål",
    Designer_Canvas_EmptyBody: "Vælg en spørgsmålstype for at komme i gang. Du kan omarrangere spørgsmål ved at trække dem og tilføje forgrening, så folk kun ser det, der gælder for dem.",
    Designer_Section_Chip: "Afsnit {number} af {total}",
    Designer_Section_TitlePlaceholder: "Afsnitstitel",
    Designer_Section_TitleAria: "Titel på afsnit {number}",
    Designer_Section_DescriptionPlaceholder: "Beskrivelse (valgfrit)",
    Designer_Section_DescriptionAria: "Beskrivelse af afsnit {number}",
    Designer_Section_MoveUp: "Flyt afsnit op",
    Designer_Section_MoveDown: "Flyt afsnit ned",
    Designer_Section_Delete: "Slet afsnit",
    Designer_Card_DragToReorder: "Træk for at omarrangere",
    Designer_Card_ReorderAria: "Omarranger {title}",
    Designer_Card_ReorderFallback: "spørgsmål",
    Designer_Canvas_AddNew: "Tilføj ny",
    Designer_Canvas_AddSection: "Tilføj afsnit",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Vejnavn og husnummer",
    Form_Address_Street2Placeholder: "Etage, side osv. (valgfrit)",
    Form_Address_CityPlaceholder: "By",
    Form_Address_StatePlaceholder: "Region / kommune",
    Form_Address_PostalCodePlaceholder: "Postnummer",
    Form_Address_CountryPlaceholder: "Land",
    Form_Address_StreetAria: "vejnavn og husnummer",
    Form_Address_Street2Aria: "adresselinje 2",
    Form_Address_CityAria: "by",
    Form_Address_StateAria: "region eller kommune",
    Form_Address_PostalCodeAria: "postnummer",
    Form_Address_CountryAria: "land",
    Form_Consent_DefaultLabel: "Jeg accepterer",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered} af {total} rækker besvaret",
    Form_Lookup_LoadError: "Indstillingerne til dette spørgsmål kunne ikke indlæses.",
    Form_Lookup_Loading: "Indlæser indstillinger…",
    Form_Lookup_SelectOptionsPlaceholder: "Vælg indstillinger",
    Form_Lookup_SelectOptionPlaceholder: "Vælg en indstilling",
    Form_Person_Placeholder: "Begynd at skrive et navn…",
    Form_Person_SuggestedPeopleAndGroups: "Foreslåede personer og grupper",
    Form_Person_SuggestedPeople: "Foreslåede personer",
    Form_Person_NoPeopleOrGroups: "Ingen personer eller grupper fundet",
    Form_Person_NoPeople: "Ingen personer fundet",
    Form_Person_Searching: "Søger…",
    Form_Ranking_Moved: "{item} er flyttet til position {position} af {total}",
    Form_Ranking_MoveUp: "Flyt op",
    Form_Ranking_MoveDown: "Flyt ned",
    Form_Ranking_MoveItemUpAria: "Flyt {item} op",
    Form_Ranking_MoveItemDownAria: "Flyt {item} ned",
    Form_Rating_ValueText: "{value} af {max}",
    Form_Rating_NotRated: "Ikke bedømt",
    Form_Rating_Clear: "Ryd bedømmelse",
    Form_RichText_Bold: "Fed",
    Form_RichText_Italic: "Kursiv",
    Form_RichText_Underline: "Understreget",
    Form_RichText_BulletedList: "Punktopstilling",
    Form_RichText_NumberedList: "Nummereret liste",
    Form_RichText_ClearFormatting: "Ryd formatering",
    Form_RichText_ToolbarAria: "Tekstformatering",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\" blev sprunget over — grænsen er {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" er ikke en accepteret type.",
    Form_File_TooLarge: "\"{name}\" er større end {size} MB.",
    Form_File_AlreadyAttached: "\"{name}\" er allerede vedhæftet.",
    Form_File_ReadError: "En af filerne kunne ikke læses. Prøv at vedhæfte den igen.",
    Form_File_HintMaxSize: "op til {size} MB pr. fil",
    Form_File_HintOneFile: "1 fil",
    Form_File_HintMaxFiles: "maks. {count} filer",
    Form_File_Reading: "Læser filer…",
    Form_File_DropPrompt: "Slip filer her, eller klik for at gennemse",
    Form_File_Remove: "Fjern {name}",
    Form_Signature_Alt: "Underskrift",
    Form_Signature_AriaSigned: "{label} — underskrevet",
    Form_Signature_AriaEmpty: "{label} — tom",
    Form_Signature_Clear: "Ryd",
    Form_Signature_Signed: "Underskrevet",
    Form_Signature_Prompt: "Underskriv ovenfor med mus, pen eller finger",
    Form_Time_Placeholder: "Vælg et klokkeslæt",
    Form_Field_DatePlaceholder: "Vælg en dato",
    Form_Field_TimeAriaWithLabel: "{label} — klokkeslæt",
    Form_Field_TimeAria: "Klokkeslæt",
    Form_Field_OtherDefault: "Andet",
    Form_Field_SelectOptionsPlaceholder: "Vælg indstillinger",
    Form_Field_PleaseSpecify: "Angiv venligst",
    Form_Field_OtherSpecifyAria: "{label} — angiv venligst",
    Form_Field_SelectOptionPlaceholder: "Vælg en indstilling",
    Form_Field_Yes: "Ja",
    Form_Field_No: "Nej",
    Form_Field_SliderHint: "Træk i skyderen for at svare",
    Form_Field_WebAddressAriaWithLabel: "{label} — webadresse",
    Form_Field_WebAddressAria: "Webadresse",
    Form_Field_DisplayTextPlaceholder: "Visningstekst (valgfrit)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — visningstekst",
    Form_Field_DisplayTextAria: "Visningstekst",
    Form_Field_ChooseBetween: "Vælg mellem {min} og {max}",
    Form_Field_ChooseAtLeast: "Vælg mindst {min}",
    Form_Field_ChooseUpTo: "Vælg op til {max}",
    Form_Field_SelectedCount: "{count} valgt",
    Form_Field_RequiredAria: "(påkrævet)",
    Form_Submit_SaveError: "Dit svar kunne ikke gemmes. Kontroller, at formularen er udgivet fra designeren, og at du har tilladelse til at tilføje elementer til svarlisten.",
    Form_Empty_Message: "Denne formular har endnu ingen spørgsmål. Formularens ejer kan tilføje dem under fanen Spørgsmål.",
    Form_Checking: "Kontrollerer formularen…",
    Form_Closed_NotYetOpen: "Ikke åben endnu",
    Form_Closed_AlreadyAnswered: "Allerede besvaret",
    Form_Closed_Title: "Formularen er lukket",
    Form_Confirmation_PreviewNotice: "Dette var et eksempel — der blev ikke gemt noget på svarlisten.",
    Form_Confirmation_PreviewAgain: "Vis eksempel igen",
    Form_Confirmation_SubmitAnother: "Send endnu et svar",
    Form_Wizard_StepFallback: "Trin {step}",
    Form_Wizard_StepsAria: "Formulartrin",
    Form_Wizard_StepOf: "Trin {step} af {total}",
    Form_ErrorSummary_Title: "Kontroller {count} svar:",
    Form_ErrorSummary_UntitledQuestion: "Unavngivet spørgsmål",
    Form_ErrorSummary_Question: "Spørgsmål",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Tilbage",
    Form_Nav_Next: "Næste",
    Form_Draft_Saving: "Gemmer…",
    Form_Draft_Saved: "Kladde gemt",
    Form_Draft_SaveAndFinishLater: "Gem og afslut senere",
    Form_Draft_NotSaved: "Kladde ikke gemt",
    Form_Submit_Preview: "Send (eksempel)",
    Form_Submit_Button: "Send",
    Form_Response_NoAnswer: "Intet svar",
    Form_Signature_TypeLabel: "Skriv dit fulde navn",
    Form_Signature_TypeInstead: "Skriv dit navn i stedet",
    Form_Signature_DrawInstead: "Tegn i stedet",
    Form_Edit_Button: "Rediger dit tidligere svar",
    Form_Edit_Available: "Du har allerede sendt et svar. Du kan redigere det i stedet for at sende et nyt.",
    Form_Edit_Banner: "Du redigerer dit tidligere svar.",
    Form_Edit_Save: "Opdater svar",
    Form_Edit_UpdatedTitle: "Svaret er opdateret",
    Form_Edit_UpdatedMessage: "Dine ændringer er gemt.",
    Form_Edit_LoadError: "Dit tidligere svar kunne ikke indlæses. Prøv igen.",
    Form_Draft_MissingFiles: "Vedhæft venligst igen: {names}. Disse filer kunne ikke gendannes.",
    Form_Attachments_Failed: "Dine svar blev gemt, men disse vedhæftede filer kunne ikke uploades: {names}. Prøv igen, eller kontakt formularens ejer.",
    Logic_ThisQuestion: "Dette spørgsmål",
    Logic_Required: "{label} skal udfyldes",
    Logic_RequiredConsent: "Markér feltet for at fortsætte",
    Logic_RequiredFile: "Vedhæft mindst én fil",
    Logic_RequiredSignature: "Tilføj din signatur",
    Logic_RequiredLikert: "Besvar hver række",
    Logic_InvalidEmail: "Angiv en gyldig mailadresse",
    Logic_InvalidPhone: "Angiv et gyldigt telefonnummer",
    Logic_InvalidUrl: "Angiv en gyldig webadresse, der starter med http:// eller https://",
    Logic_MinValue: "Værdien skal være mindst {value}",
    Logic_MaxValue: "Værdien må højst være {value}",
    Logic_MaxLength: "Maksimal længde er {max} tegn",
    Logic_ChooseAtLeastOne: "Vælg mindst {count} valgmulighed",
    Logic_ChooseAtLeastMany: "Vælg mindst {count} valgmuligheder",
    Logic_ChooseAtMostOne: "Vælg højst {count} valgmulighed",
    Logic_ChooseAtMostMany: "Vælg højst {count} valgmuligheder",
    Logic_LikertRemaining: "Besvar hver række ({count} tilbage)",
    Logic_MaxFilesOne: "Vedhæft højst {count} fil",
    Logic_MaxFilesMany: "Vedhæft højst {count} filer",
    Logic_FileTooLarge: "\"{name}\" er større end {size} MB",
    Logic_FileTypeNotAccepted: "\"{name}\" er ikke en accepteret filtype ({types})",
    Logic_AddressRequired: "Angiv som minimum en gade og en by",
    Logic_PatternDefault: "Dette svar har ikke det forventede format",
    Logic_Yes: "Ja",
    Logic_No: "Nej",
    Logic_Agreed: "Accepteret",
    Logic_NotAgreed: "Ikke accepteret",
    Logic_Signed: "Underskrevet",
    Logic_NoAnswer: "(intet svar)",
    Logic_Unknown: "(ukendt)",
    Logic_OtherSlice: "Andre ({count})",
    Logic_CsvResponseId: "Svar-id",
    Logic_CsvSubmitted: "Sendt",
    Logic_CsvSubmittedBy: "Sendt af",
    Logic_EmailQuestion: "Spørgsmål",
    Logic_EmailViewItem: "Vis i Microsoft Lists",
    Logic_EmailFooter: "Sendt automatisk af Smart Forms.",
    Logic_ClosedDefault: "Denne formular modtager ikke længere svar.",
    Logic_NotYetOpen: "Denne formular åbner {date}.",
    Logic_AlreadyResponded: "Du har allerede besvaret denne formular. Tak!",
    Logic_UntitledQuestion: "Et spørgsmål uden titel",
    Logic_Issue_NoQuestions: "Tilføj mindst ét spørgsmål, før du indsamler svar.",
    Logic_Issue_NoTitle: "Et spørgsmål har ingen tekst – det navngives automatisk, når du udgiver.",
    Logic_Issue_DuplicateTitle: "{label} har samme tekst som et andet spørgsmål, hvilket gør resultaterne sværere at læse.",
    Logic_Issue_NeedTwoOptions: "{label} kræver mindst to valgmuligheder.",
    Logic_Issue_ImageNoImage: "{label} har valgmuligheder uden billede – de vises som tekstfliser.",
    Logic_Issue_LikertNeedRow: "{label} kræver mindst én række.",
    Logic_Issue_LikertNeedColumns: "{label} kræver mindst to skalakolonner.",
    Logic_Issue_NoLookupList: "{label} har ingen valgt kildeliste.",
    Logic_Issue_NoFormula: "{label} har ingen formel.",
    Logic_Issue_BadFormula: "{label} har en formel, der ikke kan beregnes. Kontroller parenteser og operatorer.",
    Logic_Issue_MissingRefs: "{label} refererer til spørgsmål, der ikke findes: {names}.",
    Logic_Issue_BadPattern: "{label} har et ugyldigt valideringsmønster.",
    Logic_Issue_BrokenRule: "{label} har en forgreningsregel, der peger på et slettet spørgsmål.",
    Logic_Issue_SelfRule: "{label} har en forgreningsregel, der refererer til sig selv.",
    Logic_Issue_RuleMismatch: "{label} har en forgreningsregel, der ikke længere passer til det spørgsmål, den afhænger af.",
    Logic_Issue_RequiredReadOnly: "{label} er både obligatorisk og skrivebeskyttet, så det kan kun besvares via et forududfyldt link.",
    Logic_Issue_EmptySection: "En sektion har ingen spørgsmål og springes over.",
    Logic_Issue_CloseBeforeOpen: "Lukkedatoen er på eller før åbningsdatoen, så formularen vil aldrig modtage svar.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Godkendelsesmails er slået til, men godkendelsestrinnet er slået fra.",
    Logic_Op_equals: "er",
    Logic_Op_notEquals: "er ikke",
    Logic_Op_contains: "indeholder",
    Logic_Op_notContains: "indeholder ikke",
    Logic_Op_notEmpty: "er besvaret",
    Logic_Op_empty: "er ikke besvaret",
    Logic_Op_greaterThan: "er større end",
    Logic_Op_greaterOrEqual: "er mindst",
    Logic_Op_lessThan: "er mindre end",
    Logic_Op_lessOrEqual: "er højst",
    Logic_Op_between: "er mellem",
    Logic_Op_before: "er før",
    Logic_Op_after: "er efter",
    Logic_Type_Text: "Kort svar",
    Logic_TypeDesc_Text: "Én linje tekst",
    Logic_Category_Text: "Tekst",
    Logic_Type_MultilineText: "Langt svar",
    Logic_TypeDesc_MultilineText: "Flere linjer almindelig tekst",
    Logic_Type_RichText: "Formateret tekst",
    Logic_TypeDesc_RichText: "Fed, lister og links",
    Logic_Type_Choice: "Valg",
    Logic_TypeDesc_Choice: "Vælg fra en liste med valgmuligheder",
    Logic_Category_Choice: "Valg",
    Logic_Type_ImageChoice: "Billedvalg",
    Logic_TypeDesc_ImageChoice: "Vælg fra billedfliser",
    Logic_Type_Lookup: "Opslag fra en liste",
    Logic_TypeDesc_Lookup: "Valgmuligheder læses live fra en anden SharePoint-liste",
    Logic_Type_YesNo: "Ja / Nej",
    Logic_TypeDesc_YesNo: "En enkel til/fra-kontakt",
    Logic_Type_Consent: "Samtykke",
    Logic_TypeDesc_Consent: "Et afkrydsningsfelt, som respondenten skal markere for at fortsætte",
    Logic_Type_Ranking: "Rangordning",
    Logic_TypeDesc_Ranking: "Træk valgmuligheder i rækkefølge efter præference",
    Logic_Type_Rating: "Vurdering",
    Logic_TypeDesc_Rating: "Stjerner, hjerter eller tommelfingre",
    Logic_Category_Scales: "Skalaer",
    Logic_Type_Scale: "Meningsskala",
    Logic_TypeDesc_Scale: "En nummereret skala med mærkede ender",
    Logic_Type_Slider: "Skyder",
    Logic_TypeDesc_Slider: "En værdi på en glidende skala",
    Logic_Type_Likert: "Likert-gitter",
    Logic_TypeDesc_Likert: "Vurder flere udsagn på én fælles skala",
    Logic_Type_Number: "Tal",
    Logic_TypeDesc_Number: "Almindeligt tal, valuta eller procent",
    Logic_Category_Advanced: "Avanceret",
    Logic_Type_Calculated: "Beregnet",
    Logic_TypeDesc_Calculated: "En skrivebeskyttet sum beregnet ud fra andre svar",
    Logic_Type_Date: "Dato",
    Logic_TypeDesc_Date: "En kalenderdato, eventuelt med et klokkeslæt",
    Logic_Category_Date: "Dato",
    Logic_Type_Time: "Klokkeslæt",
    Logic_TypeDesc_Time: "Et klokkeslæt alene",
    Logic_Type_Person: "Person",
    Logic_TypeDesc_Person: "Vælg en person fra organisationen",
    Logic_Category_People: "Personer",
    Logic_Type_Email: "Mail",
    Logic_TypeDesc_Email: "En mailadresse, valideret",
    Logic_Type_Phone: "Telefon",
    Logic_TypeDesc_Phone: "Et telefonnummer, valideret",
    Logic_Type_Address: "Adresse",
    Logic_TypeDesc_Address: "Gade, by, postnummer og land",
    Logic_Type_Hyperlink: "Link",
    Logic_TypeDesc_Hyperlink: "En webadresse",
    Logic_Type_FileUpload: "Filupload",
    Logic_TypeDesc_FileUpload: "Vedhæft en eller flere filer til svaret",
    Logic_Type_Signature: "Signatur",
    Logic_TypeDesc_Signature: "Underskriv med mus, pen eller finger",
    Logic_Type_Content: "Tekstblok",
    Logic_TypeDesc_Content: "Instruktioner eller et billede – indsamler intet svar",
    Logic_Category_Layout: "Layout",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Hvor sandsynligt er det, at du vil anbefale…",
    Logic_Preset_satisfaction: "Tilfredshed (1–5)",
    Logic_PresetDesc_satisfaction: "Fra meget utilfreds til meget tilfreds",
    Logic_Preset_currency: "Valuta",
    Logic_PresetDesc_currency: "Et pengebeløb",
    Logic_Preset_percent: "Procent",
    Logic_PresetDesc_percent: "En procentværdi",
    Logic_Template_blank_Name: "Tom formular",
    Logic_Template_blank_Description: "Start fra bunden",
    Logic_Template_feedback_Name: "Kundefeedback",
    Logic_Template_feedback_Description: "NPS, vurderinger og åbne kommentarer",
    Logic_Template_event_Name: "Tilmelding til begivenhed",
    Logic_Template_event_Description: "Deltageroplysninger, sessioner og kostbehov",
    Logic_Template_itrequest_Name: "IT-serviceanmodning",
    Logic_Template_itrequest_Description: "Kategoriserede anmodninger med prioritet og vedhæftede filer",
    Logic_Template_expense_Name: "Udgiftsrefusion",
    Logic_Template_expense_Description: "Linjer, kvitteringer og en beregnet total",
    Logic_Template_pulse_Name: "Medarbejderpulsundersøgelse",
    Logic_Template_pulse_Description: "Likert-gitter, engagementskala og anonymitetsnote",
    Logic_Template_safety_Name: "Sikkerhedsinspektion",
    Logic_Template_safety_Description: "Tjekliste, fotos og en signatur",
    Logic_Template_booking_Name: "Booking af rum eller ressource",
    Logic_Template_booking_Description: "Ressourcevælger baseret på opslag med tidsrum",
    Charts_ColumnChartAria: "Søjlediagram med {count} kategorier",
    Charts_DonutChartAria: "Ringdiagram med {count} kategorier",
    Charts_NoAnswers: "Ingen svar endnu.",
    Charts_NoResponses: "Ingen svar endnu.",
    Charts_Responses: "Svar",
    Charts_ResponsesOverTime: "Svar over tid",
    Responses_Chart_Answer: "Svar",
    Responses_Chart_Average: "Gennemsnit",
    Responses_Chart_AverageOf: "Gennemsnit af {count}",
    Responses_Chart_AveragePosition: "Gennemsnitlig placering",
    Responses_Chart_AverageRange: "Gennemsnit (1–{max})",
    Responses_Chart_AvgValue: "gns. {value}",
    Responses_Chart_Detractors: "Kritikere (0–6)",
    Responses_Chart_Max: "Maks.",
    Responses_Chart_Maximum: "Maksimum",
    Responses_Chart_Median: "Median",
    Responses_Chart_MentionOne: "{count} omtale",
    Responses_Chart_MentionOther: "{count} omtaler",
    Responses_Chart_Min: "Min.",
    Responses_Chart_Minimum: "Minimum",
    Responses_Chart_NoAnswers: "Ingen svar endnu.",
    Responses_Chart_NoNumeric: "Ingen numeriske svar endnu.",
    Responses_Chart_NoRankings: "Ingen rangeringer endnu.",
    Responses_Chart_NoScores: "Ingen scorer endnu.",
    Responses_Chart_NotEnoughText: "Ikke nok tekst til at opsummere endnu.",
    Responses_Chart_NpsScore: "NPS-score",
    Responses_Chart_Option: "Indstilling",
    Responses_Chart_Passives: "Passive (7–8)",
    Responses_Chart_Promoters: "Ambassadører (9–10)",
    Responses_Chart_ResponseOne: "svar",
    Responses_Chart_ResponseOther: "svar",
    Responses_Chart_Responses: "Svar",
    Responses_Chart_ShowingAnswers: "Viser {shown} af {total} svar.",
    Responses_Chart_Statement: "Udsagn",
    Responses_Chart_Statistic: "Statistik",
    Responses_Chart_StdDev: "Std.afv.",
    Responses_Chart_StdDeviation: "Standardafvigelse",
    Responses_Chart_Total: "I alt",
    Responses_Chart_Value: "Værdi",
    Responses_Dashboard_AllHidden: "Alle spørgsmål er skjult fra dashboardet. Brug “Vis skjulte spørgsmål” for at få dem tilbage.",
    Responses_Dashboard_AnsweredOf: "{answered} af {total} besvaret",
    Responses_Dashboard_AnsweredOfPinned: "{answered} af {total} besvaret · fastgjort",
    Responses_Dashboard_AveragedAcrossResponses: "Gennemsnit på tværs af svar",
    Responses_Dashboard_ByDay: "Efter dag",
    Responses_Dashboard_ByMonth: "Efter måned",
    Responses_Dashboard_ByWeek: "Efter uge",
    Responses_Dashboard_ChartAuto: "Automatisk",
    Responses_Dashboard_ChartBars: "Bjælker",
    Responses_Dashboard_ChartColumns: "Søjler",
    Responses_Dashboard_ChartDonut: "Ring",
    Responses_Dashboard_ChartGauge: "Måler",
    Responses_Dashboard_ChartHistogram: "Histogram",
    Responses_Dashboard_ChartOptions: "Diagramindstillinger",
    Responses_Dashboard_ChartOptionsFor: "Diagramindstillinger for {title}",
    Responses_Dashboard_ChartStatistics: "Statistik",
    Responses_Dashboard_ChartTable: "Tabel",
    Responses_Dashboard_ChartWordFrequency: "Ordhyppighed",
    Responses_Dashboard_EmptyBody: "Så snart folk begynder at svare, udfyldes dette dashboard automatisk — med nøgletal, en tidslinje for svar og et diagram for de spørgsmål, der er værd at følge.",
    Responses_Dashboard_EmptyTitle: "Ingen svar endnu",
    Responses_Dashboard_Hide: "Skjul fra dashboard",
    Responses_Dashboard_Highlights: "Højdepunkter",
    Responses_Dashboard_Last7Days: "Seneste 7 dage",
    Responses_Dashboard_LatestDate: "Seneste {date}",
    Responses_Dashboard_MedianTimeToComplete: "Mediantid til udfyldelse",
    Responses_Dashboard_NoPriorWeek: "Ingen foregående uge at sammenligne med",
    Responses_Dashboard_OneEach: "Én af hver",
    Responses_Dashboard_Pin: "Fastgør til dashboard",
    Responses_Dashboard_QuestionFallback: "spørgsmål",
    Responses_Dashboard_QuestionsAnswered: "Besvarede spørgsmål",
    Responses_Dashboard_RecordedOnSubmit: "Registreres ved afsendelse",
    Responses_Dashboard_RepeatResponses: "{count} gentagne svar",
    Responses_Dashboard_ResponsesOverTime: "Svar over tid",
    Responses_Dashboard_ShowHidden: "Vis skjulte spørgsmål",
    Responses_Dashboard_SinceMidnight: "Siden midnat",
    Responses_Dashboard_Today: "I dag",
    Responses_Dashboard_TotalResponses: "Svar i alt",
    Responses_Dashboard_UniqueRespondents: "Unikke respondenter",
    Responses_Dashboard_Unpin: "Frigør fra dashboard",
    Responses_Dashboard_UntitledQuestion: "Unavngivet spørgsmål",
    Responses_Dashboard_VsPrevious7Days: "mod de foregående 7 dage",
    Responses_Detail_Answers: "Svar",
    Responses_Detail_AsTheForm: "Som formularen",
    Responses_Detail_Cancel: "Annuller",
    Responses_Detail_Delete: "Slet",
    Responses_Detail_DeleteBody: "Listeelementet flyttes til webstedets papirkurv, så det kan gendannes derfra.",
    Responses_Detail_DeleteTitle: "Vil du slette dette svar?",
    Responses_Detail_Deleting: "Sletter…",
    Responses_Detail_Draft: "Kladde",
    Responses_Detail_Header: "Svar {index} af {total}",
    Responses_Detail_LoadingAttachments: "Indlæser vedhæftede filer…",
    Responses_Detail_Next: "Næste svar",
    Responses_Detail_NoAnswer: "Intet svar",
    Responses_Detail_Previous: "Forrige svar",
    Responses_Detail_Print: "Udskriv",
    Responses_Detail_Signature: "Underskrift",
    Responses_Detail_Signed: "Underskrevet",
    Responses_Detail_Took: "tog {duration}",
    Responses_Summary_AnsweredOfType: "{answered} af {total} besvaret · {type}",
    Responses_Summary_ByField: "Efter {title}",
    Responses_Summary_CompareBy: "Sammenlign efter…",
    Responses_Summary_EmptyBody: "Hvert spørgsmål får sin egen oversigt her.",
    Responses_Summary_NoComparison: "Ingen sammenligning",
    Responses_Summary_NothingToCompare: "Ingen svar besvarede “{title}”, så der er intet at sammenligne.",
    Responses_Summary_OtherNote: "Diagrammer med mere end {max} kategorier samler de mindste under “Andet” — skift et kort til Tabel for at se alle værdier.",
    Responses_Summary_ResponseCountOne: "{count} svar",
    Responses_Summary_ResponseCountOther: "{count} svar",
    Responses_Summary_SeeAllAnswers: "Se alle svar i tabellen",
    Responses_Summary_SegmentNote: "Viser de {groups} største grupper. Et svar med flere valgte svarmuligheder vises i hver matchende gruppe, så gruppesummer kan give mere end {total}.",
    Responses_Summary_SplitBy: "Opdel efter {title}",
    Responses_Summary_Untitled: "uden titel",
    Responses_Table_Apply: "Anvend",
    Responses_Table_Cancel: "Annuller",
    Responses_Table_ClearSelection: "Ryd markering",
    Responses_Table_ColumnOrder: "Kolonnerækkefølge",
    Responses_Table_ColumnsCount: "Kolonner ({shown}/{total})",
    Responses_Table_Delete: "Slet",
    Responses_Table_DeleteBody: "Listeelementerne flyttes til webstedets papirkurv, så de kan gendannes derfra.",
    Responses_Table_DeleteSelected: "Slet markerede",
    Responses_Table_DeleteTitleOne: "Vil du slette {count} svar?",
    Responses_Table_DeleteTitleOther: "Vil du slette {count} svar?",
    Responses_Table_Deleting: "Sletter…",
    Responses_Table_MoveDown: "Flyt ned",
    Responses_Table_MoveDownFor: "Flyt {title} ned",
    Responses_Table_MoveUp: "Flyt op",
    Responses_Table_MoveUpFor: "Flyt {title} op",
    Responses_Table_NoColumns: "Ingen spørgsmålskolonner er synlige endnu.",
    Responses_Table_NoMatch: "Ingen svar matcher de aktuelle filtre.",
    Responses_Table_NothingToShow: "Intet at vise",
    Responses_Table_OpenResponse: "Åbn dette svar",
    Responses_Table_OrderNote: "Sendt og Sendt af står altid først. Rækkefølgen ved træk gælder for spørgsmålskolonnerne.",
    Responses_Table_Reorder: "Omarranger",
    Responses_Table_ResetColumns: "Nulstil kolonner",
    Responses_Table_SelectResponse: "Markér dette svar",
    Responses_Table_SelectedOne: "{count} svar markeret",
    Responses_Table_SelectedOther: "{count} svar markeret",
    Responses_Table_ShowAll: "Vis alle",
    Responses_Table_ShowTheseQuestions: "Vis disse spørgsmål",
    Responses_Table_Submitted: "Sendt",
    Responses_Table_SubmittedBy: "Sendt af",
    Responses_Table_ToggleSelection: "Skift markering",
    Responses_Table_Unknown: "Ukendt",
    Responses_Table_Untitled: "Uden titel",
    Responses_View_AllTime: "Alle tidspunkter",
    Responses_View_AnyAnswer: "Alle svar",
    Responses_View_Clear: "Ryd",
    Responses_View_CopyShareLink: "Kopiér delingslink",
    Responses_View_CountFiltered: "{shown} af {total} svar",
    Responses_View_CountOne: "{count} svar",
    Responses_View_CountOther: "{count} svar",
    Responses_View_Dashboard: "Dashboard",
    Responses_View_DateRange: "Datointerval",
    Responses_View_EmptyBody: "Del formularen for at begynde at indsamle svar. Svar gemmes i “{list}” og vises her med det samme.",
    Responses_View_EmptyTitle: "Ingen svar endnu",
    Responses_View_ExportCsv: "Eksportér CSV",
    Responses_View_FilterByAnswer: "Filtrer efter svar",
    Responses_View_FilterByQuestion: "Filtrer efter spørgsmål",
    Responses_View_FilterValue: "Filterværdi",
    Responses_View_Last30Days: "Seneste 30 dage",
    Responses_View_Last7Days: "Seneste 7 dage",
    Responses_View_Last90Days: "Seneste 90 dage",
    Responses_View_LoadError: "Svarene kunne ikke indlæses. Udgiv formularen én gang, så listekolonnerne findes, og prøv igen.",
    Responses_View_Loading: "Indlæser svar…",
    Responses_View_MoreActions: "Flere handlinger for svar",
    Responses_View_PreviewForm: "Vis eksempel på formularen",
    Responses_View_Refresh: "Opdater",
    Responses_View_ResponsesTab: "Svar ({count})",
    Responses_View_SearchPlaceholder: "Søg i alle svar",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Vælg en værdi",
    Responses_View_Summary: "Oversigt",
    Responses_View_Today: "I dag",
    Responses_View_Truncated: "Denne liste har flere svar, end Smart Forms indlæser ad gangen. De nyeste {count} vises — åbn listen i Microsoft Lists for at se hele sættet.",
    Responses_View_TryAgain: "Prøv igen",
    Responses_View_Untitled: "Uden titel",
    Responses_Approval_Column: "Godkendelse",
    Responses_Approval_ReviewerColumn: "Gennemgået af",
    Responses_Approval_CommentColumn: "Anmelderens kommentar",
    Responses_Approval_Pending: "Afventer",
    Responses_Approval_Approved: "Godkendt",
    Responses_Approval_Rejected: "Afvist",
    Responses_Approval_AnyStatus: "Enhver godkendelsesstatus",
    Responses_Approval_FilterLabel: "Filtrer efter godkendelsesstatus",
    Responses_Approval_ApproveSelected: "Godkend valgte",
    Responses_Approval_RejectSelected: "Afvis valgte",
    Responses_Approval_BulkFailed: "{count} svar kunne ikke opdateres. Prøv igen.",
    Responses_Approval_Approve: "Godkend",
    Responses_Approval_Reject: "Afvis",
    Responses_Approval_Reset: "Nulstil til afventer",
    Responses_Approval_CommentLabel: "Kommentar (valgfrit)",
    Responses_Approval_ReviewedBy: "Gennemgået af {name}",
    Responses_Approval_Error: "Beslutningen kunne ikke gemmes. Prøv igen.",
    Responses_Dashboard_ApprovalStatus: "Afventer gennemgang",
    Responses_Dashboard_ApprovalBreakdown: "{pending} afventer, {approved} godkendt, {rejected} afvist",
    Responses_Dashboard_TimelineCoarsened: "Datointervallet er langt, så tidslinjen blev grupperet mere groft ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Datointervallet er meget langt, så kun de seneste {count} perioder vises.",
    Service_Item_DefaultTitle: "Svar – {date}",
    Service_Email_ApprovalSubject: "Dit svar er {status} – {title}",
    Service_Email_ApprovalHeading: "Dit svar er {status}",
    Service_Email_ApprovalIntro: "En anmelder har markeret dit svar på \"{title}\" som {status}.",
    Service_Email_ApprovalCommentLabel: "Anmelderens kommentar",
    Service_Approval_Approved: "godkendt",
    Service_Approval_Rejected: "afvist",
    Service_Approval_Pending: "afventende",
    Service_Lookup_InvalidFilter: "Opslagsfilteret er ikke gyldigt.",
    Service_Edit_NotAllowed: "Denne formular tillader ikke redigering af et sendt svar.",
    Service_Edit_NotYours: "Du kan kun redigere dit eget svar.",
    Service_Signature_AttachmentLabel: "Signatur",
    PropertyPane_ListsLoadFailed: "Listerne på dette websted kunne ikke indlæses.",
    PropertyPane_EnterListName: "Angiv først et navn til den nye liste.",
    PropertyPane_CreatingList: "Opretter \"{name}\"…",
    PropertyPane_ListCreated: "Listen \"{title}\" er oprettet og valgt.",
    PropertyPane_ListAlreadyExists: "En liste med navnet \"{name}\" findes allerede — vælg den i rullemenuen ovenfor.",
    PropertyPane_CreateListFailed: "Listen kunne ikke oprettes. Kontroller, at du har tilladelse til at oprette lister på dette websted.",
    PropertyPane_Description: "Vælg den SharePoint-liste, der gemmer formularsvar, eller opret en ny. Alt andet — spørgsmål, udseende, meddelelser — redigeres direkte på siden.",
    PropertyPane_ResponseList_GroupName: "Svarliste",
    PropertyPane_ListDropdown_Label: "Gem svar på denne liste",
    PropertyPane_ResponsesGoTo: "Svar gemmes i \"{name}\".",
    PropertyPane_PickList: "Vælg en liste, eller opret en nedenfor.",
    PropertyPane_LoadingLists: "Indlæser lister…",
    PropertyPane_NewListName_Label: "Eller opret en ny liste",
    PropertyPane_NewListName_Placeholder: "Navn på ny liste",
    PropertyPane_CreateList_Button: "Opret liste",
    PropertyPane_Tips_GroupName: "Tip",
    PropertyPane_Tip_AutoSave: "Spørgsmål og indstillinger gemmes automatisk, mens du redigerer — du behøver ikke gemme eller udgive siden.",
    PropertyPane_Tip_Permissions: "Respondenter skal have tilladelse til at tilføje elementer til svarlisten. Kontroller listens tilladelser, hvis nogen rapporterer en fejl ved afsendelse.",
    PropertyPane_Tip_Share: "Brug \"Indsaml svar\" på siden til at oprette listekolonnerne og få et delbart link til udfyldelse.",
    App_ErrorBoundary_Title: "Smart Forms — gengivelsesfejl",
    App_ErrorBoundary_Message: "Meddelelse:",
    App_ErrorBoundary_Stack: "Stak:",
    App_ErrorBoundary_NoStack: "(ingen stak tilgængelig)",
    App_ErrorBoundary_ConsoleNote: "Alle detaljer blev også skrevet til browserkonsollen.",
    App_DefaultQuestionTitle: "Spørgsmål {number}",
    App_Error_ListMissing: "Listen, der er konfigureret til denne formular, findes ikke længere. Vælg en anden liste i webdelens indstillinger.",
    App_Error_LoadConfig: "Noget gik galt under indlæsning af formularkonfigurationen.",
    App_Error_Unable: "Formularen kunne ikke indlæses.",
    App_Publish_ConflictNotice: "\"{title}\" har allerede en listekolonne af en anden type ({type}). Omdøb spørgsmålet, så der kan oprettes en ny kolonne, eller skift typen tilbage.",
    App_Publish_ConflictUnnamedQuestion: "et spørgsmål",
    App_Publish_ColumnsAddedOne: "{count} kolonne blev tilføjet til \"{list}\".",
    App_Publish_ColumnsAddedOther: "{count} kolonner blev tilføjet til \"{list}\".",
    App_Publish_TheList: "listen",
    App_Publish_UpToDate: "Svarlisten er allerede opdateret.",
    App_Publish_Error: "Listekolonnerne kunne ikke oprettes. Det betyder som regel, at du ikke har tilladelsen Administrer lister på svarlisten, men det kan også ske på websteder, hvor brugerdefinerede scripts er deaktiveret. Kontroller browserkonsollen for den underliggende fejl, eller prøv igen.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Byg en flot formular oven på en SharePoint-liste — {count} spørgsmålstyper, forgreningslogik, filoverførsler, delbare links til udfyldelse og et resultatdashboard.",
    App_Placeholder_ChooseList: "Vælg eller opret en liste",
    App_Placeholder_Hint: "Rediger siden, og konfigurer denne webdel for at komme i gang.",
    App_Loading: "Indlæser formular…",
    App_OpenSettings: "Åbn indstillinger",
    App_Tab_Questions: "Spørgsmål",
    App_Tab_QuestionsWithCount: "Spørgsmål ({count})",
    App_Tab_Responses: "Svar",
    App_Tab_Responses_Title: "Svar gemmes i \"{list}\"",
    App_Templates_Start: "Start fra en skabelon",
    App_Settings_Title: "Formularindstillinger — udseende, meddelelser, adgang",
    App_Settings_AriaLabel: "Formularindstillinger",
    App_Preview: "Eksempel",
    App_Preview_Close: "Luk eksempel",
    App_Preview_Hint: "Eksempel — intet, du sender her, bliver gemt. Validering og forgrening fungerer præcis, som de vil gøre for respondenterne.",
    App_Publish_GettingReady: "Gør klar…",
    App_Publish_CollectResponses: "Indsaml svar",
    App_Publish_Share: "Del",
    App_Retry: "Prøv igen",
    App_SaveError_Banner: "Din seneste ændring kunne ikke gemmes. Kontroller din forbindelse, og prøv igen.",
    App_Preflight_BlockingTitle: "Ret disse, før du indsamler svar",
    App_Preflight_WarningTitle: "Værd at se på først",
    App_Preflight_BlockingText: "Disse ting ville forhindre den udgivne formular i at fungere korrekt.",
    App_Preflight_WarningText: "Intet er i stykker, men det er som regel en god idé at rette disse ting, før du deler linket.",
    App_Preflight_GoTo: "Gå til",
    App_Preflight_CollectAnyway: "Indsaml svar alligevel",
    App_Preflight_Back: "Tilbage til formularen",
    App_Cancel: "Annuller",
    App_Done: "Udført",
    App_Share_Title: "Din formular er klar til deling",
    App_Share_SubText: "Send dette link til alle, der skal udfylde formularen.",
    App_Share_LinkAriaLabel: "Delingslink",
    App_Share_Copy: "Kopiér",
    App_Share_Copied: "Kopieret",
    App_Share_AddItemsEmphasis: "tilføje elementer",
    App_Share_PermissionNote: "Respondenter skal have tilladelse til at {addItems} til “{title}” samt adgang til denne side. Hvis nogen får en fejl ved afsendelse, er det næsten altid derfor.",
    App_Share_PrefillNote: "Du kan forudbesvare spørgsmål i linket ved at tilføje kolonnenavnet, f.eks. {example}.",
    App_Templates_ReplaceWarning: "Hvis du vælger en skabelon, erstattes de spørgsmål, du har nu.",
    App_Templates_PickStart: "Vælg et udgangspunkt — du kan ændre alt bagefter.",
    App_Templates_Empty: "Tom",
    App_Templates_QuestionCount: "{count} spørgsmål",
    App_SaveChip_SavingTitle: "Gemmer din seneste redigering",
    App_SaveChip_Saving: "Gemmer…",
    App_SaveChip_FailedTitle: "Din seneste redigering kunne ikke gemmes. Kontroller din forbindelse, og prøv igen.",
    App_SaveChip_Failed: "Kunne ikke gemme",
    App_SaveChip_SavedTitle: "Alle ændringer er gemt",
    App_SaveChip_Saved: "Gemt",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Nyt svar — {title}",
    Service_Email_NewResponseHeading: "Nyt svar: {title}",
    Service_Email_NewResponseIntro: "Nogen har netop sendt et svar — {date}.",
    Service_Email_ReceiptSubject: "Dit svar — {title}",
    Service_Email_ReceiptHeading: "Tak for dit svar!",
    Service_Email_ReceiptIntro: "Her er en kopi af det, du sendte til \"{title}\".",
    App_History_Title: "Versionshistorik",
    App_History_RestoredNotice: "Versionen gemt {date} er gendannet. Gennemgå den, og brug derefter Indsaml svar til at udgive eventuelle nye spørgsmål.",
    App_History_Undo: "Fortryd gendannelse",
    App_Share_CopyManual: "Din browser blokerede kopiering. Markér linket ovenfor, og tryk på Ctrl+C (Cmd+C på en Mac) for at kopiere det.",
    App_Share_TeamsNote: "Du er i Microsoft Teams. Dette link åbner SharePoint-siden direkte, så modtagerne skal have adgang til webstedet.",
    App_Share_PrefillNotSecure: "Forududfyldte svar er kun en bekvemmelighed: alle med linket kan ændre dem, så betragt dem aldrig som en sikkerhedsgrænse.",
    Designer_Section_DropHere: "Slip et spørgsmål her",
    Designer_Section_DropEnd: "Slip her for at flytte til slutningen af denne sektion",
    Designer_Rules_RemovedOne: "1 forgreningsregel, der ikke længere passede, blev fjernet.",
    Designer_Rules_RemovedOther: "{count} forgreningsregler, der ikke længere passede, blev fjernet.",
    Designer_Settings_AllowEdit: "Tillad respondenter at redigere deres svar",
    Designer_Settings_AllowEditHint: "Respondenter kan genåbne og opdatere det, de har sendt. Hver person kan kun redigere sit eget svar.",
    Designer_Settings_EnableApproval: "Aktivér godkendelsesworkflow",
    Designer_Settings_ApprovalNotify: "Send mail til respondenten ved afgørelse",
    Designer_Settings_ApprovalHint: "Tilføjer godkendelseskolonner til svarlisten, næste gang du udgiver. Ejere godkender eller afviser svar på fanen Svar.",
    Designer_History_Title: "Versionshistorik",
    Designer_History_Intro: "Tidligere gemte versioner af dette formulars spørgsmål og indstillinger. Gendannelse indlæser en version i designeren; du kan fortryde det, og nye spørgsmål oprettes først, når du udgiver.",
    Designer_History_Loading: "Indlæser versioner...",
    Designer_History_Empty: "Der blev ikke fundet nogen tidligere versioner. Versionshistorik kræver, at versionsstyring er slået til for listen \"Smart Forms Config\", og mindst én gemt redigering.",
    Designer_History_Latest: "Seneste",
    Designer_History_LatestTitle: "Dette er den version, der bruges i øjeblikket",
    Designer_History_By: "af {name}",
    Designer_History_UnknownAuthor: "Ukendt forfatter",
    Designer_History_VersionLabel: "version {label}",
    Designer_History_Preview: "Vis eksempel",
    Designer_History_Restore: "Gendan",
    Designer_History_QuestionsOne: "1 spørgsmål",
    Designer_History_QuestionsOther: "{count} spørgsmål",
    Designer_History_LoadFailed: "Denne version kunne ikke indlæses.",
    Designer_History_ConfirmTitle: "Gendan denne version?",
    Designer_History_ConfirmText: "Formularen erstattes med versionen gemt {date} ({count} spørgsmål). Du kan fortryde det lige bagefter."
  };
});
