define([], function () {
  return {
    Designer_Color_Blue: "Μπλε",
    Designer_Color_Teal: "Τιρκουάζ",
    Designer_Color_Green: "Πράσινο",
    Designer_Color_Purple: "Μωβ",
    Designer_Color_Magenta: "Ματζέντα",
    Designer_Color_Red: "Κόκκινο",
    Designer_Color_Orange: "Πορτοκαλί",
    Designer_Color_Gray: "Γκρι",
    Designer_Settings_LayoutSinglePage: "Όλες οι ερωτήσεις σε μία σελίδα",
    Designer_Settings_LayoutWizard: "Μία ενότητα ανά βήμα (οδηγός)",
    Designer_Settings_Title: "Ρυθμίσεις φόρμας",
    Designer_Common_Apply: "Εφαρμογή",
    Designer_Common_Cancel: "Ακύρωση",
    Designer_Settings_TabBasics: "Βασικά",
    Designer_Settings_FormTitle: "Τίτλος φόρμας",
    Designer_Settings_Description: "Περιγραφή",
    Designer_Settings_Layout: "Διάταξη",
    Designer_Settings_NumberQuestions: "Αρίθμηση των ερωτήσεων",
    Designer_Settings_ShuffleQuestions: "Τυχαία σειρά ερωτήσεων για κάθε συμμετέχοντα",
    Designer_Settings_ShowProgressBar: "Εμφάνιση γραμμής προόδου",
    Designer_Settings_TabAppearance: "Εμφάνιση",
    Designer_Settings_AccentColor: "Χρώμα έμφασης",
    Designer_Settings_CustomColorTitle: "Προσαρμοσμένο χρώμα",
    Designer_Settings_CustomColorAria: "Προσαρμοσμένο χρώμα έμφασης",
    Designer_Settings_AccentHint: "Τα χρώματα έμφασης προσαρμόζονται αυτόματα για αντίθεση σε σκουρόχρωμους ιστότοπους, ώστε η φόρμα να παραμένει ευανάγνωστη ανεξάρτητα από το θέμα της σελίδας.",
    Designer_Settings_ShowHeader: "Εμφάνιση κεφαλίδας φόρμας",
    Designer_Settings_HeaderIcon: "Εικονίδιο κεφαλίδας",
    Designer_Settings_TabAfterSubmit: "Μετά την υποβολή",
    Designer_Settings_SubmitButtonText: "Κείμενο κουμπιού υποβολής",
    Designer_Settings_SubmitPlaceholder: "Υποβολή",
    Designer_Settings_ThankYouTitle: "Τίτλος ευχαριστίας",
    Designer_Settings_ThankYouPlaceholder: "Ευχαριστούμε!",
    Designer_Settings_ThankYouMessage: "Μήνυμα ευχαριστίας",
    Designer_Settings_ShowSubmitAnother: "Εμφάνιση κουμπιού «Υποβολή άλλης απάντησης»",
    Designer_Settings_TabNotifications: "Ειδοποιήσεις",
    Designer_Settings_EmailEachResponseTo: "Αποστολή κάθε απάντησης με email στους",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "Τα άτομα του οργανισμού σας λαμβάνουν κάθε απάντηση με email, με σύνδεσμο προς το στοιχείο της λίστας",
    Designer_Settings_RespondentReceipt: "Αποστολή αντιγράφου των απαντήσεων με email στους συμμετέχοντες",
    Designer_Settings_NotificationsInfo: "Οι ειδοποιήσεις χρησιμοποιούν την υπηρεσία αλληλογραφίας του SharePoint, επομένως οι παραλήπτες πρέπει να είναι χρήστες του οργανισμού σας. Οι εξωτερικές διευθύνσεις απορρίπτονται αθόρυβα.",
    Designer_Settings_TabAccess: "Πρόσβαση",
    Designer_Settings_OpenFrom: "Άνοιγμα από",
    Designer_Settings_OpenImmediately: "Άμεσο άνοιγμα",
    Designer_Settings_CloseAfter: "Κλείσιμο μετά από",
    Designer_Settings_NeverClose: "Να μην κλείνει ποτέ",
    Designer_Settings_ClearDates: "Απαλοιφή ημερομηνιών",
    Designer_Settings_DatesInverted: "Η ημερομηνία κλεισίματος είναι ίδια ή προγενέστερη της ημερομηνίας ανοίγματος, οπότε η φόρμα δεν θα δεχόταν ποτέ απαντήσεις.",
    Designer_Settings_MaxResponses: "Διακοπή μετά από αυτόν τον αριθμό απαντήσεων",
    Designer_Settings_NoLimit: "Χωρίς όριο",
    Designer_Settings_OneResponsePerPerson: "Να επιτρέπεται μόνο μία απάντηση ανά άτομο",
    Designer_Settings_AllowSaveDraft: "Να επιτρέπεται στους συμμετέχοντες να αποθηκεύουν πρόχειρο και να συνεχίζουν αργότερα",
    Designer_Settings_ClosedMessage: "Μήνυμα που εμφανίζεται όταν η φόρμα είναι κλειστή",
    Designer_Settings_ClosedMessagePlaceholder: "Αυτή η φόρμα δεν δέχεται πλέον απαντήσεις.",
    Designer_Settings_AccessInfo: "Αυτά τα όρια επιβάλλονται από τη φόρμα και όχι από το SharePoint. Όποιος έχει άδεια προσθήκης στοιχείων στη λίστα απαντήσεων θα μπορούσε και πάλι να προσθέσει ένα απευθείας μέσω της λίστας.",
    Designer_Field_StyleInfo: "Πληροφορία (έμφαση)",
    Designer_Field_StyleSuccess: "Επιτυχία (πράσινο)",
    Designer_Field_StyleWarning: "Προειδοποίηση (κεχριμπαρί)",
    Designer_Field_StylePlain: "Απλό κείμενο",
    Designer_Field_StyleDivider: "Γραμμή διαχωρισμού",
    Designer_Field_IconStars: "Αστέρια",
    Designer_Field_IconHearts: "Καρδιές",
    Designer_Field_IconThumbs: "Μπράβο",
    Designer_Field_FormatPlain: "Απλός αριθμός",
    Designer_Field_FormatCurrency: "Νόμισμα",
    Designer_Field_FormatPercent: "Ποσοστό",
    Designer_Field_UntitledQuestion: "Ερώτηση χωρίς τίτλο",
    Designer_Field_DeletedQuestion: "μια διαγραμμένη ερώτηση",
    Designer_Rule_Unary: "«{name}» {operator}",
    Designer_Rule_Between: "«{name}» {operator} {value} και {value2}",
    Designer_Rule_Binary: "«{name}» {operator} «{value}»",
    Designer_Rule_JoinAny: "Ή",
    Designer_Rule_JoinAll: "ΚΑΙ",
    Designer_Rule_Preview: "Εμφανίζεται όταν {conditions}.",
    Designer_Field_Yes: "Ναι",
    Designer_Field_No: "Όχι",
    Designer_Field_When: "Όταν",
    Designer_Field_SelectValue: "Επιλέξτε τιμή",
    Designer_Field_DateValuePlaceholder: "ΕΕΕΕ-ΜΜ-ΗΗ ή \"today\"",
    Designer_Field_ValuePlaceholder: "Τιμή",
    Designer_Field_UpperBound: "Άνω όριο",
    Designer_Field_RemoveCondition: "Κατάργηση αυτής της συνθήκης",
    Designer_Field_FormulaInvalid: "Δεν είναι δυνατός ο υπολογισμός αυτού του τύπου. Ελέγξτε τις παρενθέσεις και τους τελεστές.",
    Designer_Field_FormulaMissing: "Αυτές οι ερωτήσεις δεν υπάρχουν: {names}.",
    Designer_Field_FormulaPreview: "Με κάθε είσοδο ίση με 10, εμφανίζεται {value}.",
    Designer_Field_HintYesNo: "Χρησιμοποιήστε \"yes\" ή \"no\"",
    Designer_Field_HintMultiDefault: "Διαχωρίστε πολλές προεπιλογές με ;",
    Designer_Field_HintSingleDefault: "Πρέπει να ταιριάζει με μία από τις επιλογές",
    Designer_Field_HintDate: "Χρησιμοποιήστε \"today\" ή μια ημερομηνία όπως 2026-03-01",
    Designer_Field_HintTime: "Χρησιμοποιήστε \"now\" ή μια ώρα όπως 09:30",
    Designer_Field_QuestionSettings: "Ρυθμίσεις ερώτησης",
    Designer_Field_Appearance: "Εμφάνιση",
    Designer_Field_Style: "Στυλ",
    Designer_Field_ImageUrl: "Διεύθυνση URL εικόνας (προαιρετικό)",
    Designer_Field_Content: "Περιεχόμενο",
    Designer_Field_BasicFormatting: "Επιτρέπεται βασική μορφοποίηση: έντονα, πλάγια, λίστες και σύνδεσμοι.",
    Designer_Field_TabOptions: "Επιλογές",
    Designer_Field_TabBranching: "Διακλάδωση",
    Designer_Field_BranchingNeedsQuestion: "Προσθέστε πρώτα μια άλλη ερώτηση — η διακλάδωση χρειάζεται κάτι από το οποίο να εξαρτάται.",
    Designer_Field_BranchingToggle: "Εμφάνιση αυτής της ερώτησης μόνο όταν ταιριάζουν άλλες απαντήσεις",
    Designer_Field_Match: "Αντιστοίχιση",
    Designer_Field_MatchAll: "όλων αυτών",
    Designer_Field_MatchAny: "οποιουδήποτε από αυτά",
    Designer_Field_AddCondition: "Προσθήκη συνθήκης",
    Designer_Field_TabValidation: "Επικύρωση",
    Designer_Field_HelpText: "Κείμενο βοήθειας",
    Designer_Field_HelpTextPlaceholder: "Εμφανίζεται κάτω από την ετικέτα της ερώτησης",
    Designer_Field_CheckboxLabel: "Ετικέτα πλαισίου ελέγχου",
    Designer_Field_Placeholder: "Κείμενο υποκατάστασης",
    Designer_Field_DefaultAnswer: "Προεπιλεγμένη απάντηση",
    Designer_Field_RequiredMessage: "Προσαρμοσμένο μήνυμα υποχρεωτικού πεδίου",
    Designer_Field_RequiredMessagePlaceholder: "Το πεδίο {title} είναι υποχρεωτικό",
    Designer_Field_ThisQuestion: "Αυτή η ερώτηση",
    Designer_Field_RequiredMessageDescription: "Εμφανίζεται αντί για το τυπικό μήνυμα όταν αυτή η ερώτηση μείνει κενή",
    Designer_Field_ReadOnly: "Μόνο για ανάγνωση (η απάντηση μπορεί να προέλθει μόνο από προσυμπληρωμένο σύνδεσμο)",
    Designer_Field_ValidationRules: "Κανόνες επικύρωσης",
    Designer_Field_MaxLength: "Μέγιστο μήκος",
    Designer_Field_Pattern: "Πρέπει να ταιριάζει με αυτό το μοτίβο",
    Designer_Field_PatternDescription: "Μια κανονική έκφραση. Αφήστε κενό για να μην γίνεται έλεγχος μοτίβου.",
    Designer_Field_PatternMessage: "Μήνυμα όταν το μοτίβο δεν ταιριάζει",
    Designer_Field_PatternMessagePlaceholder: "Αυτή η απάντηση δεν έχει την αναμενόμενη μορφή",
    Designer_Field_Format: "Μορφή",
    Designer_Field_UnitSuffix: "Μονάδα που εμφανίζεται μετά την τιμή",
    Designer_Field_UnitSuffixPlaceholder: "kg, ώρες, τεμάχια…",
    Designer_Field_Minimum: "Ελάχιστο",
    Designer_Field_Maximum: "Μέγιστο",
    Designer_Field_Decimals: "Δεκαδικά ψηφία",
    Designer_Field_Formula: "Τύπος",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Αναφερθείτε σε άλλες ερωτήσεις με το κείμενό τους μέσα σε άγκιστρα. Υποστηρίζονται τα + - * / ( ) και τα round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Διαθέσιμες ερωτήσεις: {questions}",
    Designer_Field_NoneYet: "καμία ακόμη",
    Designer_Field_Step: "Βήμα",
    Designer_Field_From: "Από",
    Designer_Field_To: "Έως",
    Designer_Field_LowLabel: "Ετικέτα στο χαμηλό άκρο",
    Designer_Field_LowLabelPlaceholder: "Καθόλου πιθανό",
    Designer_Field_HighLabel: "Ετικέτα στο υψηλό άκρο",
    Designer_Field_HighLabelPlaceholder: "Εξαιρετικά πιθανό",
    Designer_Field_SummarizeAs: "Σύνοψη ως",
    Designer_Field_SummarizeAverage: "Μέσος όρος και κατανομή",
    Designer_Field_SummarizeNps: "Net Promoter Score (απαιτεί κλίμακα 0–10)",
    Designer_Field_NpsWarning: "Το Net Promoter Score έχει νόημα μόνο σε κλίμακα 0–10. Ορίστε το Από σε 0 και το Έως σε 10.",
    Designer_Field_NumberOfIcons: "Αριθμός εικονιδίων",
    Designer_Field_Icon: "Εικονίδιο",
    Designer_Field_AllowHalf: "Να επιτρέπονται μισές τιμές",
    Designer_Field_ShowOptionsAs: "Εμφάνιση επιλογών ως",
    Designer_Field_DisplayButtons: "Ενσωματωμένα κουμπιά",
    Designer_Field_DisplayDropdown: "Αναπτυσσόμενη λίστα",
    Designer_Field_DisplayAutomatic: "Αυτόματα (ενσωματωμένα έως 6 επιλογές)",
    Designer_Field_AllowOther: "Προσθήκη επιλογής «Άλλο» με ελεύθερη καταχώριση",
    Designer_Field_OtherLabel: "Ετικέτα για την επιλογή «Άλλο»",
    Designer_Field_OtherPlaceholder: "Άλλο",
    Designer_Field_ShuffleOptions: "Τυχαία σειρά επιλογών για κάθε συμμετέχοντα",
    Designer_Field_MinSelections: "Ελάχιστες επιλογές",
    Designer_Field_MaxSelections: "Μέγιστες επιλογές",
    Designer_Field_SourceList: "Λίστα προέλευσης",
    Designer_Field_ChooseList: "Επιλέξτε λίστα",
    Designer_Field_LookupColumn: "Στήλη από την οποία θα διαβάζονται οι επιλογές",
    Designer_Field_ChooseColumn: "Επιλέξτε στήλη",
    Designer_Field_ChooseListFirst: "Επιλέξτε πρώτα μια λίστα",
    Designer_Field_LookupFilter: "Φίλτρο (προαιρετικό)",
    Designer_Field_LookupFilterDescription: "Ένα φίλτρο OData που περιορίζει ποια στοιχεία προέλευσης γίνονται επιλογές",
    Designer_Field_LookupInfo: "Οι απαντήσεις αποθηκεύουν το κείμενο της επιλογής και όχι σύνδεσμο προς το στοιχείο προέλευσης, ώστε οι απαντήσεις να παραμένουν ευανάγνωστες ακόμη και αν η λίστα προέλευσης αλλάξει αργότερα.",
    Designer_Field_ConsentText: "Όροι που εμφανίζονται πάνω από το πλαίσιο ελέγχου",
    Designer_Field_AllowMultiplePeople: "Να επιτρέπονται πολλά άτομα",
    Designer_Field_AllowGroups: "Να επιτρέπονται και ομάδες",
    Designer_Field_IncludeTime: "Συμπερίληψη ώρας της ημέρας",
    Designer_Field_TimeStep: "Βήμα ώρας (λεπτά)",
    Designer_Field_MaxFiles: "Μέγιστος αριθμός αρχείων",
    Designer_Field_MaxFileSize: "Μέγ. μέγεθος ανά αρχείο (MB)",
    Designer_Field_AcceptedTypes: "Αποδεκτοί τύποι αρχείων",
    Designer_Field_AcceptedTypesDescription: "Επεκτάσεις χωρισμένες με κόμμα. Αφήστε κενό για να γίνεται αποδεκτό ό,τι επιτρέπει το SharePoint.",
    Designer_Field_FilesInfo: "Τα αρχεία αποθηκεύονται ως συνημμένα στο στοιχείο της απάντησης. Το SharePoint αποκλείει ορισμένες επεκτάσεις (όπως .exe) ανεξάρτητα από το τι επιτρέπετε εδώ.",
    Designer_Field_Rows: "Γραμμές",
    Designer_Field_ProvisionedNote: "Αυτή η ερώτηση έχει ήδη στήλη λίστας ({name}). Οι ρυθμίσεις που αλλάζουν τον τύπο της στήλης είναι κλειδωμένες — αντιγράψτε την ερώτηση αν χρειάζεστε διαφορετικό τύπο.",
    Designer_Category_Text: "Κείμενο",
    Designer_Category_Choice: "Επιλογή",
    Designer_Category_Scales: "Κλίμακες",
    Designer_Category_Date: "Ημερομηνία",
    Designer_Category_People: "Άτομα",
    Designer_Category_Advanced: "Για προχωρημένους",
    Designer_Category_Layout: "Διάταξη",
    Designer_Menu_CommonPresets: "Συνήθεις προεπιλογές",
    Designer_Menu_AllTypes: "Όλοι οι τύποι ερωτήσεων",
    Designer_Menu_ChangeType: "Αλλαγή τύπου",
    Designer_Menu_TypeLockedTitle: "Η στήλη της λίστας υπάρχει ήδη, οπότε ο τύπος είναι κλειδωμένος. Αντιγράψτε την ερώτηση για να τον αλλάξετε.",
    Designer_Menu_MoreSettings: "Διακλάδωση, επικύρωση και άλλα",
    Designer_Menu_InsertBelow: "Εισαγωγή ερώτησης από κάτω",
    Designer_Card_Duplicate: "Αντιγραφή",
    Designer_Card_DeleteQuestion: "Διαγραφή ερώτησης",
    Designer_Outline_Aria: "Διάρθρωση ερωτήσεων",
    Designer_Outline_QuestionCountOne: "{count} ερώτηση",
    Designer_Outline_QuestionCountOther: "{count} ερωτήσεις",
    Designer_Outline_IssuesTitle: "{count} πρόβλημα(τα) προς έλεγχο",
    Designer_Outline_Find: "Εύρεση ερώτησης",
    Designer_Outline_Empty: "Δεν υπάρχουν ερωτήσεις ακόμη.",
    Designer_Section_DefaultTitle: "Ενότητα {number}",
    Designer_Card_Question: "Ερώτηση",
    Designer_Card_BranchingTitle: "Αυτή η ερώτηση εμφανίζεται μόνο όταν ταιριάζει ένας κανόνας διακλάδωσης",
    Designer_Card_BranchingChip: "Διακλάδωση",
    Designer_Card_LiveTitle: "Η στήλη της λίστας υπάρχει, οπότε ο τύπος είναι κλειδωμένος",
    Designer_Card_LiveChip: "Ενεργή",
    Designer_Card_CheckChip: "Έλεγχος",
    Designer_Option_Placeholder: "Επιλογή {number}",
    Designer_Option_LabelAria: "Ετικέτα επιλογής {number}",
    Designer_Option_ImageUrl: "Διεύθυνση URL εικόνας",
    Designer_Option_ImageUrlAria: "Διεύθυνση URL εικόνας επιλογής {number}",
    Designer_Option_Remove: "Κατάργηση επιλογής",
    Designer_Option_RemoveAria: "Κατάργηση επιλογής {number}",
    Designer_Option_Add: "Προσθήκη επιλογής",
    Designer_Option_OtherHint: "Οι συμμετέχοντες μπορούν επίσης να γράψουν μια απάντηση με ετικέτα «{label}».",
    Designer_Option_OtherFallback: "Άλλο",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Κατάργηση",
    Designer_Grid_RemoveAria: "Κατάργηση {label} {number}",
    Designer_Grid_Statements: "Δηλώσεις",
    Designer_Grid_Scale: "Κλίμακα",
    Designer_Grid_AddStatement: "Προσθήκη δήλωσης",
    Designer_Grid_AddScale: "Προσθήκη κλίμακας",
    Designer_Width_Full: "Πλήρες πλάτος",
    Designer_Width_Half: "Μισό πλάτος",
    Designer_Width_Third: "Ένα τρίτο του πλάτους",
    Designer_Width_Aria: "Πλάτος ερώτησης",
    Designer_Card_BlockLabelPlaceholder: "Ετικέτα μπλοκ (δεν εμφανίζεται στους συμμετέχοντες)",
    Designer_Card_QuestionText: "Κείμενο ερώτησης",
    Designer_Card_MoveUp: "Μετακίνηση προς τα πάνω",
    Designer_Card_MoveQuestionUp: "Μετακίνηση ερώτησης προς τα πάνω",
    Designer_Card_MoveDown: "Μετακίνηση προς τα κάτω",
    Designer_Card_MoveQuestionDown: "Μετακίνηση ερώτησης προς τα κάτω",
    Designer_Card_DuplicateQuestion: "Αντιγραφή ερώτησης",
    Designer_Card_MultipleAnswers: "Πολλαπλές απαντήσεις",
    Designer_Card_Required: "Υποχρεωτική",
    Designer_Card_MoreOptions: "Περισσότερες επιλογές",
    Designer_Card_MoreOptionsAria: "Περισσότερες επιλογές για αυτή την ερώτηση",
    Designer_Canvas_FormTitle: "Τίτλος φόρμας",
    Designer_Canvas_DescriptionPlaceholder: "Προσθήκη περιγραφής (προαιρετικό)",
    Designer_Canvas_DescriptionAria: "Περιγραφή φόρμας",
    Designer_Canvas_EmptyTitle: "Προσθέστε την πρώτη σας ερώτηση",
    Designer_Canvas_EmptyBody: "Επιλέξτε έναν τύπο ερώτησης για να ξεκινήσετε. Μπορείτε να αναδιατάξετε τις ερωτήσεις σύροντάς τες και να προσθέσετε διακλάδωση, ώστε οι χρήστες να βλέπουν μόνο ό,τι τους αφορά.",
    Designer_Section_Chip: "Ενότητα {number} από {total}",
    Designer_Section_TitlePlaceholder: "Τίτλος ενότητας",
    Designer_Section_TitleAria: "Τίτλος ενότητας {number}",
    Designer_Section_DescriptionPlaceholder: "Περιγραφή (προαιρετικό)",
    Designer_Section_DescriptionAria: "Περιγραφή ενότητας {number}",
    Designer_Section_MoveUp: "Μετακίνηση ενότητας προς τα πάνω",
    Designer_Section_MoveDown: "Μετακίνηση ενότητας προς τα κάτω",
    Designer_Section_Delete: "Διαγραφή ενότητας",
    Designer_Card_DragToReorder: "Σύρετε για αναδιάταξη",
    Designer_Card_ReorderAria: "Αναδιάταξη {title}",
    Designer_Card_ReorderFallback: "ερώτηση",
    Designer_Canvas_AddNew: "Προσθήκη νέου",
    Designer_Canvas_AddSection: "Προσθήκη ενότητας",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Διεύθυνση (οδός και αριθμός)",
    Form_Address_Street2Placeholder: "Διαμέρισμα, όροφος κ.λπ. (προαιρετικό)",
    Form_Address_CityPlaceholder: "Πόλη",
    Form_Address_StatePlaceholder: "Νομός / περιφέρεια",
    Form_Address_PostalCodePlaceholder: "Ταχυδρομικός κώδικας",
    Form_Address_CountryPlaceholder: "Χώρα",
    Form_Address_StreetAria: "διεύθυνση",
    Form_Address_Street2Aria: "γραμμή διεύθυνσης 2",
    Form_Address_CityAria: "πόλη",
    Form_Address_StateAria: "νομός ή περιφέρεια",
    Form_Address_PostalCodeAria: "ταχυδρομικός κώδικας",
    Form_Address_CountryAria: "χώρα",
    Form_Consent_DefaultLabel: "Συμφωνώ",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered} από {total} γραμμές απαντήθηκαν",
    Form_Lookup_LoadError: "Δεν ήταν δυνατή η φόρτωση των επιλογών για αυτή την ερώτηση.",
    Form_Lookup_Loading: "Φόρτωση επιλογών…",
    Form_Lookup_SelectOptionsPlaceholder: "Επιλέξτε επιλογές",
    Form_Lookup_SelectOptionPlaceholder: "Επιλέξτε μια επιλογή",
    Form_Person_Placeholder: "Ξεκινήστε να πληκτρολογείτε ένα όνομα…",
    Form_Person_SuggestedPeopleAndGroups: "Προτεινόμενα άτομα και ομάδες",
    Form_Person_SuggestedPeople: "Προτεινόμενα άτομα",
    Form_Person_NoPeopleOrGroups: "Δεν βρέθηκαν άτομα ή ομάδες",
    Form_Person_NoPeople: "Δεν βρέθηκαν άτομα",
    Form_Person_Searching: "Γίνεται αναζήτηση…",
    Form_Ranking_Moved: "Το στοιχείο {item} μετακινήθηκε στη θέση {position} από {total}",
    Form_Ranking_MoveUp: "Μετακίνηση προς τα πάνω",
    Form_Ranking_MoveDown: "Μετακίνηση προς τα κάτω",
    Form_Ranking_MoveItemUpAria: "Μετακίνηση του {item} προς τα πάνω",
    Form_Ranking_MoveItemDownAria: "Μετακίνηση του {item} προς τα κάτω",
    Form_Rating_ValueText: "{value} από {max}",
    Form_Rating_NotRated: "Χωρίς βαθμολογία",
    Form_Rating_Clear: "Απαλοιφή βαθμολογίας",
    Form_RichText_Bold: "Έντονα",
    Form_RichText_Italic: "Πλάγια",
    Form_RichText_Underline: "Υπογράμμιση",
    Form_RichText_BulletedList: "Λίστα με κουκκίδες",
    Form_RichText_NumberedList: "Αριθμημένη λίστα",
    Form_RichText_ClearFormatting: "Απαλοιφή μορφοποίησης",
    Form_RichText_ToolbarAria: "Μορφοποίηση κειμένου",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "Το «{name}» παραλείφθηκε — το όριο είναι {limit}.",
    Form_File_TypeNotAccepted: "Το «{name}» δεν είναι αποδεκτός τύπος.",
    Form_File_TooLarge: "Το «{name}» είναι μεγαλύτερο από {size} MB.",
    Form_File_AlreadyAttached: "Το «{name}» έχει ήδη επισυναφθεί.",
    Form_File_ReadError: "Δεν ήταν δυνατή η ανάγνωση ενός από τα αρχεία. Δοκιμάστε να το επισυνάψετε ξανά.",
    Form_File_HintMaxSize: "έως {size} MB το καθένα",
    Form_File_HintOneFile: "1 αρχείο",
    Form_File_HintMaxFiles: "έως {count} αρχεία",
    Form_File_Reading: "Ανάγνωση αρχείων…",
    Form_File_DropPrompt: "Αποθέστε αρχεία εδώ ή κάντε κλικ για περιήγηση",
    Form_File_Remove: "Κατάργηση {name}",
    Form_Signature_Alt: "Υπογραφή",
    Form_Signature_AriaSigned: "{label} — υπογεγραμμένο",
    Form_Signature_AriaEmpty: "{label} — κενό",
    Form_Signature_Clear: "Απαλοιφή",
    Form_Signature_Signed: "Υπογεγραμμένο",
    Form_Signature_Prompt: "Υπογράψτε παραπάνω με ποντίκι, στυλό ή δάχτυλο",
    Form_Time_Placeholder: "Επιλέξτε ώρα",
    Form_Field_DatePlaceholder: "Επιλέξτε ημερομηνία",
    Form_Field_TimeAriaWithLabel: "{label} — ώρα",
    Form_Field_TimeAria: "Ώρα",
    Form_Field_OtherDefault: "Άλλο",
    Form_Field_SelectOptionsPlaceholder: "Επιλέξτε επιλογές",
    Form_Field_PleaseSpecify: "Παρακαλούμε διευκρινίστε",
    Form_Field_OtherSpecifyAria: "{label} — παρακαλούμε διευκρινίστε",
    Form_Field_SelectOptionPlaceholder: "Επιλέξτε μια επιλογή",
    Form_Field_Yes: "Ναι",
    Form_Field_No: "Όχι",
    Form_Field_SliderHint: "Σύρετε το ρυθμιστικό για να απαντήσετε",
    Form_Field_WebAddressAriaWithLabel: "{label} — διεύθυνση web",
    Form_Field_WebAddressAria: "Διεύθυνση web",
    Form_Field_DisplayTextPlaceholder: "Κείμενο εμφάνισης (προαιρετικό)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — κείμενο εμφάνισης",
    Form_Field_DisplayTextAria: "Κείμενο εμφάνισης",
    Form_Field_ChooseBetween: "Επιλέξτε από {min} έως {max}",
    Form_Field_ChooseAtLeast: "Επιλέξτε τουλάχιστον {min}",
    Form_Field_ChooseUpTo: "Επιλέξτε έως {max}",
    Form_Field_SelectedCount: "{count} επιλεγμένα",
    Form_Field_RequiredAria: "(υποχρεωτικό)",
    Form_Submit_SaveError: "Δεν ήταν δυνατή η αποθήκευση της απάντησής σας. Βεβαιωθείτε ότι η φόρμα έχει δημοσιευθεί από τον σχεδιαστή και ότι έχετε άδεια προσθήκης στοιχείων στη λίστα απαντήσεων.",
    Form_Empty_Message: "Αυτή η φόρμα δεν έχει ακόμη ερωτήσεις. Ο κάτοχος της φόρμας μπορεί να τις προσθέσει στην καρτέλα Ερωτήσεις.",
    Form_Checking: "Έλεγχος της φόρμας…",
    Form_Closed_NotYetOpen: "Δεν έχει ανοίξει ακόμη",
    Form_Closed_AlreadyAnswered: "Έχει ήδη απαντηθεί",
    Form_Closed_Title: "Η φόρμα έκλεισε",
    Form_Confirmation_PreviewNotice: "Αυτή ήταν προεπισκόπηση — δεν αποθηκεύτηκε τίποτα στη λίστα απαντήσεων.",
    Form_Confirmation_PreviewAgain: "Νέα προεπισκόπηση",
    Form_Confirmation_SubmitAnother: "Υποβολή άλλης απάντησης",
    Form_Wizard_StepFallback: "Βήμα {step}",
    Form_Wizard_StepsAria: "Βήματα φόρμας",
    Form_Wizard_StepOf: "Βήμα {step} από {total}",
    Form_ErrorSummary_Title: "Ελέγξτε {count} απαντήσεις:",
    Form_ErrorSummary_UntitledQuestion: "Ερώτηση χωρίς τίτλο",
    Form_ErrorSummary_Question: "Ερώτηση",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Πίσω",
    Form_Nav_Next: "Επόμενο",
    Form_Draft_Saving: "Γίνεται αποθήκευση…",
    Form_Draft_Saved: "Το πρόχειρο αποθηκεύτηκε",
    Form_Draft_SaveAndFinishLater: "Αποθήκευση και συνέχεια αργότερα",
    Form_Draft_NotSaved: "Το πρόχειρο δεν αποθηκεύτηκε",
    Form_Submit_Preview: "Υποβολή (προεπισκόπηση)",
    Form_Submit_Button: "Υποβολή",
    Form_Response_NoAnswer: "Καμία απάντηση",
    Form_Signature_TypeLabel: "Πληκτρολογήστε το πλήρες όνομά σας",
    Form_Signature_TypeInstead: "Πληκτρολόγηση ονόματος",
    Form_Signature_DrawInstead: "Σχεδίαση",
    Form_Edit_Button: "Επεξεργασία της προηγούμενης απάντησής σας",
    Form_Edit_Available: "Έχετε ήδη υποβάλει απάντηση. Μπορείτε να την επεξεργαστείτε αντί να υποβάλετε νέα.",
    Form_Edit_Banner: "Επεξεργάζεστε την προηγούμενη απάντησή σας.",
    Form_Edit_Save: "Ενημέρωση απάντησης",
    Form_Edit_UpdatedTitle: "Η απάντηση ενημερώθηκε",
    Form_Edit_UpdatedMessage: "Οι αλλαγές σας αποθηκεύτηκαν.",
    Form_Edit_LoadError: "Δεν ήταν δυνατή η φόρτωση της προηγούμενης απάντησής σας. Δοκιμάστε ξανά.",
    Form_Draft_MissingFiles: "Επισυνάψτε ξανά: {names}. Δεν ήταν δυνατή η επαναφορά αυτών των αρχείων.",
    Form_Attachments_Failed: "Οι απαντήσεις σας αποθηκεύτηκαν, αλλά δεν ήταν δυνατή η μεταφόρτωση αυτών των συνημμένων: {names}. Δοκιμάστε ξανά ή επικοινωνήστε με τον κάτοχο της φόρμας.",
    Logic_ThisQuestion: "Αυτή η ερώτηση",
    Logic_Required: "Το πεδίο {label} είναι υποχρεωτικό",
    Logic_RequiredConsent: "Επιλέξτε το πλαίσιο για να συνεχίσετε",
    Logic_RequiredFile: "Επισυνάψτε τουλάχιστον ένα αρχείο",
    Logic_RequiredSignature: "Προσθέστε την υπογραφή σας",
    Logic_RequiredLikert: "Απαντήστε σε κάθε γραμμή",
    Logic_InvalidEmail: "Εισαγάγετε μια έγκυρη διεύθυνση email",
    Logic_InvalidPhone: "Εισαγάγετε έναν έγκυρο αριθμό τηλεφώνου",
    Logic_InvalidUrl: "Εισαγάγετε μια έγκυρη διεύθυνση ιστού που αρχίζει με http:// ή https://",
    Logic_MinValue: "Η τιμή πρέπει να είναι τουλάχιστον {value}",
    Logic_MaxValue: "Η τιμή πρέπει να είναι το πολύ {value}",
    Logic_MaxLength: "Το μέγιστο μήκος είναι {max} χαρακτήρες",
    Logic_ChooseAtLeastOne: "Επιλέξτε τουλάχιστον {count} επιλογή",
    Logic_ChooseAtLeastMany: "Επιλέξτε τουλάχιστον {count} επιλογές",
    Logic_ChooseAtMostOne: "Επιλέξτε το πολύ {count} επιλογή",
    Logic_ChooseAtMostMany: "Επιλέξτε το πολύ {count} επιλογές",
    Logic_LikertRemaining: "Απαντήστε σε κάθε γραμμή (απομένουν {count})",
    Logic_MaxFilesOne: "Επισυνάψτε το πολύ {count} αρχείο",
    Logic_MaxFilesMany: "Επισυνάψτε το πολύ {count} αρχεία",
    Logic_FileTooLarge: "Το \"{name}\" είναι μεγαλύτερο από {size} MB",
    Logic_FileTypeNotAccepted: "Το \"{name}\" δεν είναι αποδεκτός τύπος αρχείου ({types})",
    Logic_AddressRequired: "Εισαγάγετε τουλάχιστον οδό και πόλη",
    Logic_PatternDefault: "Αυτή η απάντηση δεν έχει την αναμενόμενη μορφή",
    Logic_Yes: "Ναι",
    Logic_No: "Όχι",
    Logic_Agreed: "Συμφωνώ",
    Logic_NotAgreed: "Δεν συμφωνώ",
    Logic_Signed: "Υπογράφηκε",
    Logic_NoAnswer: "(καμία απάντηση)",
    Logic_Unknown: "(άγνωστο)",
    Logic_OtherSlice: "Άλλα ({count})",
    Logic_CsvResponseId: "Αναγνωριστικό απάντησης",
    Logic_CsvSubmitted: "Υποβλήθηκε",
    Logic_CsvSubmittedBy: "Υποβλήθηκε από",
    Logic_EmailQuestion: "Ερώτηση",
    Logic_EmailViewItem: "Προβολή στο Microsoft Lists",
    Logic_EmailFooter: "Στάλθηκε αυτόματα από το Smart Forms.",
    Logic_ClosedDefault: "Αυτή η φόρμα δεν δέχεται πλέον απαντήσεις.",
    Logic_NotYetOpen: "Αυτή η φόρμα ανοίγει στις {date}.",
    Logic_AlreadyResponded: "Έχετε ήδη απαντήσει σε αυτή τη φόρμα. Ευχαριστούμε!",
    Logic_UntitledQuestion: "Μια ερώτηση χωρίς τίτλο",
    Logic_Issue_NoQuestions: "Προσθέστε τουλάχιστον μία ερώτηση πριν από τη συλλογή απαντήσεων.",
    Logic_Issue_NoTitle: "Μια ερώτηση δεν έχει κείμενο — θα ονομαστεί αυτόματα κατά τη δημοσίευση.",
    Logic_Issue_DuplicateTitle: "Το πεδίο {label} έχει το ίδιο κείμενο με άλλη ερώτηση, γεγονός που δυσκολεύει την ανάγνωση των αποτελεσμάτων.",
    Logic_Issue_NeedTwoOptions: "Το πεδίο {label} χρειάζεται τουλάχιστον δύο επιλογές.",
    Logic_Issue_ImageNoImage: "Το πεδίο {label} έχει επιλογές χωρίς εικόνα — θα εμφανιστούν ως πλακίδια κειμένου.",
    Logic_Issue_LikertNeedRow: "Το πεδίο {label} χρειάζεται τουλάχιστον μία γραμμή.",
    Logic_Issue_LikertNeedColumns: "Το πεδίο {label} χρειάζεται τουλάχιστον δύο στήλες κλίμακας.",
    Logic_Issue_NoLookupList: "Το πεδίο {label} δεν έχει επιλεγμένη λίστα προέλευσης.",
    Logic_Issue_NoFormula: "Το πεδίο {label} δεν έχει τύπο.",
    Logic_Issue_BadFormula: "Το πεδίο {label} έχει τύπο που δεν μπορεί να υπολογιστεί. Ελέγξτε τις παρενθέσεις και τους τελεστές.",
    Logic_Issue_MissingRefs: "Το πεδίο {label} αναφέρεται σε ερωτήσεις που δεν υπάρχουν: {names}.",
    Logic_Issue_BadPattern: "Το πεδίο {label} έχει μη έγκυρο μοτίβο επικύρωσης.",
    Logic_Issue_BrokenRule: "Το πεδίο {label} έχει κανόνα διακλάδωσης που δείχνει σε διαγραμμένη ερώτηση.",
    Logic_Issue_SelfRule: "Το πεδίο {label} έχει κανόνα διακλάδωσης που αναφέρεται στον εαυτό του.",
    Logic_Issue_RuleMismatch: "Το πεδίο {label} έχει κανόνα διακλάδωσης που δεν ταιριάζει πλέον με την ερώτηση από την οποία εξαρτάται.",
    Logic_Issue_RequiredReadOnly: "Το πεδίο {label} είναι ταυτόχρονα υποχρεωτικό και μόνο για ανάγνωση, επομένως μπορεί να απαντηθεί μόνο μέσω προσυμπληρωμένου συνδέσμου.",
    Logic_Issue_EmptySection: "Μια ενότητα δεν έχει ερωτήσεις και θα παραλειφθεί.",
    Logic_Issue_CloseBeforeOpen: "Η ημερομηνία λήξης είναι ίδια ή προγενέστερη της ημερομηνίας έναρξης, επομένως η φόρμα δεν θα δεχτεί ποτέ απαντήσεις.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Τα email έγκρισης είναι ενεργοποιημένα, αλλά το βήμα έγκρισης είναι απενεργοποιημένο.",
    Logic_Op_equals: "είναι",
    Logic_Op_notEquals: "δεν είναι",
    Logic_Op_contains: "περιέχει",
    Logic_Op_notContains: "δεν περιέχει",
    Logic_Op_notEmpty: "έχει απαντηθεί",
    Logic_Op_empty: "δεν έχει απαντηθεί",
    Logic_Op_greaterThan: "είναι μεγαλύτερο από",
    Logic_Op_greaterOrEqual: "είναι τουλάχιστον",
    Logic_Op_lessThan: "είναι μικρότερο από",
    Logic_Op_lessOrEqual: "είναι το πολύ",
    Logic_Op_between: "είναι μεταξύ",
    Logic_Op_before: "είναι πριν από",
    Logic_Op_after: "είναι μετά από",
    Logic_Type_Text: "Σύντομη απάντηση",
    Logic_TypeDesc_Text: "Μία γραμμή κειμένου",
    Logic_Category_Text: "Κείμενο",
    Logic_Type_MultilineText: "Μεγάλη απάντηση",
    Logic_TypeDesc_MultilineText: "Πολλές γραμμές απλού κειμένου",
    Logic_Type_RichText: "Μορφοποιημένο κείμενο",
    Logic_TypeDesc_RichText: "Έντονη γραφή, λίστες και σύνδεσμοι",
    Logic_Type_Choice: "Επιλογή",
    Logic_TypeDesc_Choice: "Επιλογή από λίστα επιλογών",
    Logic_Category_Choice: "Επιλογή",
    Logic_Type_ImageChoice: "Επιλογή εικόνας",
    Logic_TypeDesc_ImageChoice: "Επιλογή από πλακίδια εικόνων",
    Logic_Type_Lookup: "Αναζήτηση από λίστα",
    Logic_TypeDesc_Lookup: "Οι επιλογές διαβάζονται ζωντανά από άλλη λίστα του SharePoint",
    Logic_Type_YesNo: "Ναι / Όχι",
    Logic_TypeDesc_YesNo: "Ένας απλός διακόπτης ενεργοποίησης/απενεργοποίησης",
    Logic_Type_Consent: "Συναίνεση",
    Logic_TypeDesc_Consent: "Ένα πλαίσιο ελέγχου που πρέπει να επιλέξει ο συμμετέχων για να συνεχίσει",
    Logic_Type_Ranking: "Κατάταξη",
    Logic_TypeDesc_Ranking: "Σύρετε τις επιλογές για να τις ταξινομήσετε ανά προτίμηση",
    Logic_Type_Rating: "Βαθμολογία",
    Logic_TypeDesc_Rating: "Αστέρια, καρδιές ή αντίχειρες",
    Logic_Category_Scales: "Κλίμακες",
    Logic_Type_Scale: "Κλίμακα άποψης",
    Logic_TypeDesc_Scale: "Αριθμημένη κλίμακα με ετικέτες στα άκρα",
    Logic_Type_Slider: "Ρυθμιστικό",
    Logic_TypeDesc_Slider: "Μια τιμή σε κλίμακα ολίσθησης",
    Logic_Type_Likert: "Πλέγμα Likert",
    Logic_TypeDesc_Likert: "Βαθμολόγηση πολλών δηλώσεων σε μία κοινή κλίμακα",
    Logic_Type_Number: "Αριθμός",
    Logic_TypeDesc_Number: "Απλός, νόμισμα ή ποσοστό",
    Logic_Category_Advanced: "Για προχωρημένους",
    Logic_Type_Calculated: "Υπολογιζόμενο",
    Logic_TypeDesc_Calculated: "Ένα σύνολο μόνο για ανάγνωση που υπολογίζεται από άλλες απαντήσεις",
    Logic_Type_Date: "Ημερομηνία",
    Logic_TypeDesc_Date: "Μια ημερομηνία ημερολογίου, προαιρετικά με ώρα",
    Logic_Category_Date: "Ημερομηνία",
    Logic_Type_Time: "Ώρα",
    Logic_TypeDesc_Time: "Μια ώρα της ημέρας μόνη της",
    Logic_Type_Person: "Άτομο",
    Logic_TypeDesc_Person: "Επιλογή ατόμου από τον οργανισμό",
    Logic_Category_People: "Άτομα",
    Logic_Type_Email: "Email",
    Logic_TypeDesc_Email: "Μια διεύθυνση email, με επικύρωση",
    Logic_Type_Phone: "Τηλέφωνο",
    Logic_TypeDesc_Phone: "Ένας αριθμός τηλεφώνου, με επικύρωση",
    Logic_Type_Address: "Διεύθυνση",
    Logic_TypeDesc_Address: "Οδός, πόλη, ταχυδρομικός κώδικας και χώρα",
    Logic_Type_Hyperlink: "Σύνδεσμος",
    Logic_TypeDesc_Hyperlink: "Μια διεύθυνση ιστού",
    Logic_Type_FileUpload: "Μεταφόρτωση αρχείου",
    Logic_TypeDesc_FileUpload: "Επισύναψη ενός ή περισσότερων αρχείων στην απάντηση",
    Logic_Type_Signature: "Υπογραφή",
    Logic_TypeDesc_Signature: "Υπογραφή με ποντίκι, στυλό ή δάχτυλο",
    Logic_Type_Content: "Μπλοκ κειμένου",
    Logic_TypeDesc_Content: "Οδηγίες ή εικόνα — δεν συλλέγει απάντηση",
    Logic_Category_Layout: "Διάταξη",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Πόσο πιθανό είναι να προτείνετε…",
    Logic_Preset_satisfaction: "Ικανοποίηση (1–5)",
    Logic_PresetDesc_satisfaction: "Από πολύ δυσαρεστημένος έως πολύ ικανοποιημένος",
    Logic_Preset_currency: "Νόμισμα",
    Logic_PresetDesc_currency: "Ένα χρηματικό ποσό",
    Logic_Preset_percent: "Ποσοστό",
    Logic_PresetDesc_percent: "Μια ποσοστιαία τιμή",
    Logic_Template_blank_Name: "Κενή φόρμα",
    Logic_Template_blank_Description: "Έναρξη από το μηδέν",
    Logic_Template_feedback_Name: "Σχόλια πελατών",
    Logic_Template_feedback_Description: "NPS, βαθμολογίες και ανοιχτά σχόλια",
    Logic_Template_event_Name: "Εγγραφή σε εκδήλωση",
    Logic_Template_event_Description: "Στοιχεία συμμετεχόντων, συνεδρίες και διατροφικές ανάγκες",
    Logic_Template_itrequest_Name: "Αίτημα υπηρεσίας IT",
    Logic_Template_itrequest_Description: "Αιτήματα ανά κατηγορία με προτεραιότητα και συνημμένα",
    Logic_Template_expense_Name: "Απαίτηση εξόδων",
    Logic_Template_expense_Description: "Γραμμές στοιχείων, αποδείξεις και υπολογιζόμενο σύνολο",
    Logic_Template_pulse_Name: "Έρευνα σφυγμού εργαζομένων",
    Logic_Template_pulse_Description: "Πλέγμα Likert, κλίμακα εμπλοκής και σημείωση ανωνυμίας",
    Logic_Template_safety_Name: "Επιθεώρηση ασφάλειας",
    Logic_Template_safety_Description: "Λίστα ελέγχου, φωτογραφίες και υπογραφή",
    Logic_Template_booking_Name: "Κράτηση αίθουσας ή πόρου",
    Logic_Template_booking_Description: "Επιλογέας πόρων με αναζήτηση και χρονικό διάστημα",
    Charts_ColumnChartAria: "Γράφημα στηλών με {count} κατηγορίες",
    Charts_DonutChartAria: "Γράφημα δακτυλίου με {count} κατηγορίες",
    Charts_NoAnswers: "Δεν υπάρχουν απαντήσεις ακόμη.",
    Charts_NoResponses: "Δεν υπάρχουν απαντήσεις ακόμη.",
    Charts_Responses: "Απαντήσεις",
    Charts_ResponsesOverTime: "Απαντήσεις με την πάροδο του χρόνου",
    Responses_Chart_Answer: "Απάντηση",
    Responses_Chart_Average: "Μέσος όρος",
    Responses_Chart_AverageOf: "Μέσος όρος από {count}",
    Responses_Chart_AveragePosition: "Μέση θέση",
    Responses_Chart_AverageRange: "Μέσος όρος (1–{max})",
    Responses_Chart_AvgValue: "μ.ό. {value}",
    Responses_Chart_Detractors: "Επικριτές (0–6)",
    Responses_Chart_Max: "Μέγ.",
    Responses_Chart_Maximum: "Μέγιστο",
    Responses_Chart_Median: "Διάμεσος",
    Responses_Chart_MentionOne: "{count} αναφορά",
    Responses_Chart_MentionOther: "{count} αναφορές",
    Responses_Chart_Min: "Ελάχ.",
    Responses_Chart_Minimum: "Ελάχιστο",
    Responses_Chart_NoAnswers: "Δεν υπάρχουν απαντήσεις ακόμη.",
    Responses_Chart_NoNumeric: "Δεν υπάρχουν αριθμητικές απαντήσεις ακόμη.",
    Responses_Chart_NoRankings: "Δεν υπάρχουν ακόμη κατατάξεις.",
    Responses_Chart_NoScores: "Δεν υπάρχουν ακόμη βαθμολογίες.",
    Responses_Chart_NotEnoughText: "Δεν υπάρχει ακόμη αρκετό κείμενο για σύνοψη.",
    Responses_Chart_NpsScore: "Βαθμολογία NPS",
    Responses_Chart_Option: "Επιλογή",
    Responses_Chart_Passives: "Παθητικοί (7–8)",
    Responses_Chart_Promoters: "Υποστηρικτές (9–10)",
    Responses_Chart_ResponseOne: "απάντηση",
    Responses_Chart_ResponseOther: "απαντήσεις",
    Responses_Chart_Responses: "Απαντήσεις",
    Responses_Chart_ShowingAnswers: "Εμφάνιση {shown} από {total} απαντήσεις.",
    Responses_Chart_Statement: "Δήλωση",
    Responses_Chart_Statistic: "Στατιστικό",
    Responses_Chart_StdDev: "Τυπ. απόκλ.",
    Responses_Chart_StdDeviation: "Τυπική απόκλιση",
    Responses_Chart_Total: "Σύνολο",
    Responses_Chart_Value: "Τιμή",
    Responses_Dashboard_AllHidden: "Όλες οι ερωτήσεις είναι κρυμμένες από τον πίνακα εργαλείων. Χρησιμοποιήστε το «Εμφάνιση κρυμμένων ερωτήσεων» για να τις επαναφέρετε.",
    Responses_Dashboard_AnsweredOf: "{answered} από {total} απαντήθηκαν",
    Responses_Dashboard_AnsweredOfPinned: "{answered} από {total} απαντήθηκαν · καρφιτσωμένη",
    Responses_Dashboard_AveragedAcrossResponses: "Μέσος όρος όλων των απαντήσεων",
    Responses_Dashboard_ByDay: "Ανά ημέρα",
    Responses_Dashboard_ByMonth: "Ανά μήνα",
    Responses_Dashboard_ByWeek: "Ανά εβδομάδα",
    Responses_Dashboard_ChartAuto: "Αυτόματα",
    Responses_Dashboard_ChartBars: "Ράβδοι",
    Responses_Dashboard_ChartColumns: "Στήλες",
    Responses_Dashboard_ChartDonut: "Δακτύλιος",
    Responses_Dashboard_ChartGauge: "Δείκτης",
    Responses_Dashboard_ChartHistogram: "Ιστόγραμμα",
    Responses_Dashboard_ChartOptions: "Επιλογές γραφήματος",
    Responses_Dashboard_ChartOptionsFor: "Επιλογές γραφήματος για {title}",
    Responses_Dashboard_ChartStatistics: "Στατιστικά",
    Responses_Dashboard_ChartTable: "Πίνακας",
    Responses_Dashboard_ChartWordFrequency: "Συχνότητα λέξεων",
    Responses_Dashboard_EmptyBody: "Μόλις οι χρήστες αρχίσουν να απαντούν, αυτός ο πίνακας εργαλείων συμπληρώνεται αυτόματα — βασικοί αριθμοί, χρονολόγιο απαντήσεων και ένα γράφημα για τις ερωτήσεις που αξίζει να παρακολουθείτε.",
    Responses_Dashboard_EmptyTitle: "Δεν υπάρχουν απαντήσεις ακόμη",
    Responses_Dashboard_Hide: "Απόκρυψη από τον πίνακα εργαλείων",
    Responses_Dashboard_Highlights: "Κυριότερα σημεία",
    Responses_Dashboard_Last7Days: "Τελευταίες 7 ημέρες",
    Responses_Dashboard_LatestDate: "Τελευταία {date}",
    Responses_Dashboard_MedianTimeToComplete: "Διάμεσος χρόνος συμπλήρωσης",
    Responses_Dashboard_NoPriorWeek: "Δεν υπάρχει προηγούμενη εβδομάδα για σύγκριση",
    Responses_Dashboard_OneEach: "Μία από την καθεμία",
    Responses_Dashboard_Pin: "Καρφίτσωμα στον πίνακα εργαλείων",
    Responses_Dashboard_QuestionFallback: "ερώτηση",
    Responses_Dashboard_QuestionsAnswered: "Ερωτήσεις που απαντήθηκαν",
    Responses_Dashboard_RecordedOnSubmit: "Καταγράφεται κατά την υποβολή",
    Responses_Dashboard_RepeatResponses: "{count} επαναλαμβανόμενες απαντήσεις",
    Responses_Dashboard_ResponsesOverTime: "Απαντήσεις με την πάροδο του χρόνου",
    Responses_Dashboard_ShowHidden: "Εμφάνιση κρυμμένων ερωτήσεων",
    Responses_Dashboard_SinceMidnight: "Από τα μεσάνυχτα",
    Responses_Dashboard_Today: "Σήμερα",
    Responses_Dashboard_TotalResponses: "Σύνολο απαντήσεων",
    Responses_Dashboard_UniqueRespondents: "Μοναδικοί συμμετέχοντες",
    Responses_Dashboard_Unpin: "Ξεκαρφίτσωμα από τον πίνακα εργαλείων",
    Responses_Dashboard_UntitledQuestion: "Ερώτηση χωρίς τίτλο",
    Responses_Dashboard_VsPrevious7Days: "σε σχέση με τις προηγούμενες 7 ημέρες",
    Responses_Detail_Answers: "Απαντήσεις",
    Responses_Detail_AsTheForm: "Όπως στη φόρμα",
    Responses_Detail_Cancel: "Ακύρωση",
    Responses_Detail_Delete: "Διαγραφή",
    Responses_Detail_DeleteBody: "Το στοιχείο της λίστας μετακινείται στον κάδο ανακύκλωσης του ιστότοπου, από όπου μπορεί να επαναφερθεί.",
    Responses_Detail_DeleteTitle: "Διαγραφή αυτής της απάντησης;",
    Responses_Detail_Deleting: "Γίνεται διαγραφή…",
    Responses_Detail_Draft: "Πρόχειρο",
    Responses_Detail_Header: "Απάντηση {index} από {total}",
    Responses_Detail_LoadingAttachments: "Φόρτωση συνημμένων…",
    Responses_Detail_Next: "Επόμενη απάντηση",
    Responses_Detail_NoAnswer: "Καμία απάντηση",
    Responses_Detail_Previous: "Προηγούμενη απάντηση",
    Responses_Detail_Print: "Εκτύπωση",
    Responses_Detail_Signature: "Υπογραφή",
    Responses_Detail_Signed: "Υπογεγραμμένο",
    Responses_Detail_Took: "διήρκεσε {duration}",
    Responses_Summary_AnsweredOfType: "{answered} από {total} απαντήθηκαν · {type}",
    Responses_Summary_ByField: "Ανά {title}",
    Responses_Summary_CompareBy: "Σύγκριση ανά…",
    Responses_Summary_EmptyBody: "Κάθε ερώτηση θα έχει εδώ τη δική της σύνοψη.",
    Responses_Summary_NoComparison: "Χωρίς σύγκριση",
    Responses_Summary_NothingToCompare: "Καμία απάντηση δεν περιέχει «{title}», επομένως δεν υπάρχει τίποτα για σύγκριση.",
    Responses_Summary_OtherNote: "Τα γραφήματα με περισσότερες από {max} κατηγορίες ομαδοποιούν τις μικρότερες στο «Άλλο» — αλλάξτε μια κάρτα σε Πίνακα για να δείτε όλες τις τιμές.",
    Responses_Summary_ResponseCountOne: "{count} απάντηση",
    Responses_Summary_ResponseCountOther: "{count} απαντήσεις",
    Responses_Summary_SeeAllAnswers: "Προβολή όλων των απαντήσεων στον πίνακα",
    Responses_Summary_SegmentNote: "Εμφανίζονται οι {groups} μεγαλύτερες ομάδες. Μια απάντηση που επέλεξε πολλές απαντήσεις εμφανίζεται σε κάθε ομάδα που ταιριάζει, οπότε τα σύνολα των ομάδων μπορεί να αθροίζονται σε περισσότερα από {total}.",
    Responses_Summary_SplitBy: "Διαχωρισμός ανά {title}",
    Responses_Summary_Untitled: "χωρίς τίτλο",
    Responses_Table_Apply: "Εφαρμογή",
    Responses_Table_Cancel: "Ακύρωση",
    Responses_Table_ClearSelection: "Απαλοιφή επιλογής",
    Responses_Table_ColumnOrder: "Σειρά στηλών",
    Responses_Table_ColumnsCount: "Στήλες ({shown}/{total})",
    Responses_Table_Delete: "Διαγραφή",
    Responses_Table_DeleteBody: "Τα στοιχεία της λίστας μετακινούνται στον κάδο ανακύκλωσης του ιστότοπου, από όπου μπορούν να επαναφερθούν.",
    Responses_Table_DeleteSelected: "Διαγραφή επιλεγμένων",
    Responses_Table_DeleteTitleOne: "Διαγραφή {count} απάντησης;",
    Responses_Table_DeleteTitleOther: "Διαγραφή {count} απαντήσεων;",
    Responses_Table_Deleting: "Γίνεται διαγραφή…",
    Responses_Table_MoveDown: "Μετακίνηση προς τα κάτω",
    Responses_Table_MoveDownFor: "Μετακίνηση του {title} προς τα κάτω",
    Responses_Table_MoveUp: "Μετακίνηση προς τα πάνω",
    Responses_Table_MoveUpFor: "Μετακίνηση του {title} προς τα πάνω",
    Responses_Table_NoColumns: "Δεν είναι ακόμη ορατές στήλες ερωτήσεων.",
    Responses_Table_NoMatch: "Καμία απάντηση δεν ταιριάζει με τα τρέχοντα φίλτρα.",
    Responses_Table_NothingToShow: "Δεν υπάρχει τίποτα για εμφάνιση",
    Responses_Table_OpenResponse: "Άνοιγμα αυτής της απάντησης",
    Responses_Table_OrderNote: "Οι στήλες «Υποβλήθηκε» και «Υποβλήθηκε από» εμφανίζονται πάντα πρώτες. Η σειρά μεταφοράς ισχύει για τις στήλες των ερωτήσεων.",
    Responses_Table_Reorder: "Αναδιάταξη",
    Responses_Table_ResetColumns: "Επαναφορά στηλών",
    Responses_Table_SelectResponse: "Επιλογή αυτής της απάντησης",
    Responses_Table_SelectedOne: "{count} απάντηση επιλέχθηκε",
    Responses_Table_SelectedOther: "{count} απαντήσεις επιλέχθηκαν",
    Responses_Table_ShowAll: "Εμφάνιση όλων",
    Responses_Table_ShowTheseQuestions: "Εμφάνιση αυτών των ερωτήσεων",
    Responses_Table_Submitted: "Υποβλήθηκε",
    Responses_Table_SubmittedBy: "Υποβλήθηκε από",
    Responses_Table_ToggleSelection: "Εναλλαγή επιλογής",
    Responses_Table_Unknown: "Άγνωστο",
    Responses_Table_Untitled: "Χωρίς τίτλο",
    Responses_View_AllTime: "Όλο το διάστημα",
    Responses_View_AnyAnswer: "Οποιαδήποτε απάντηση",
    Responses_View_Clear: "Απαλοιφή",
    Responses_View_CopyShareLink: "Αντιγραφή συνδέσμου κοινής χρήσης",
    Responses_View_CountFiltered: "{shown} από {total} απαντήσεις",
    Responses_View_CountOne: "{count} απάντηση",
    Responses_View_CountOther: "{count} απαντήσεις",
    Responses_View_Dashboard: "Πίνακας εργαλείων",
    Responses_View_DateRange: "Εύρος ημερομηνιών",
    Responses_View_EmptyBody: "Μοιραστείτε τη φόρμα για να αρχίσετε τη συλλογή. Οι απαντήσεις αποθηκεύονται στη λίστα «{list}» και εμφανίζονται εδώ αμέσως.",
    Responses_View_EmptyTitle: "Δεν υπάρχουν απαντήσεις ακόμη",
    Responses_View_ExportCsv: "Εξαγωγή CSV",
    Responses_View_FilterByAnswer: "Φιλτράρισμα ανά απάντηση",
    Responses_View_FilterByQuestion: "Φιλτράρισμα ανά ερώτηση",
    Responses_View_FilterValue: "Τιμή φίλτρου",
    Responses_View_Last30Days: "Τελευταίες 30 ημέρες",
    Responses_View_Last7Days: "Τελευταίες 7 ημέρες",
    Responses_View_Last90Days: "Τελευταίες 90 ημέρες",
    Responses_View_LoadError: "Δεν ήταν δυνατή η φόρτωση των απαντήσεων. Δημοσιεύστε τη φόρμα μία φορά ώστε να υπάρχουν οι στήλες της λίστας και δοκιμάστε ξανά.",
    Responses_View_Loading: "Φόρτωση απαντήσεων…",
    Responses_View_MoreActions: "Περισσότερες ενέργειες απαντήσεων",
    Responses_View_PreviewForm: "Προεπισκόπηση της φόρμας",
    Responses_View_Refresh: "Ανανέωση",
    Responses_View_ResponsesTab: "Απαντήσεις ({count})",
    Responses_View_SearchPlaceholder: "Αναζήτηση σε όλες τις απαντήσεις",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Επιλέξτε τιμή",
    Responses_View_Summary: "Σύνοψη",
    Responses_View_Today: "Σήμερα",
    Responses_View_Truncated: "Αυτή η λίστα έχει περισσότερες απαντήσεις από όσες φορτώνει ταυτόχρονα το Smart Forms. Εμφανίζονται οι {count} νεότερες — ανοίξτε τη λίστα στο Microsoft Lists για το πλήρες σύνολο.",
    Responses_View_TryAgain: "Δοκιμή ξανά",
    Responses_View_Untitled: "Χωρίς τίτλο",
    Responses_Approval_Column: "Έγκριση",
    Responses_Approval_ReviewerColumn: "Ελέγχθηκε από",
    Responses_Approval_CommentColumn: "Σχόλιο εξεταστή",
    Responses_Approval_Pending: "Σε εκκρεμότητα",
    Responses_Approval_Approved: "Εγκρίθηκε",
    Responses_Approval_Rejected: "Απορρίφθηκε",
    Responses_Approval_AnyStatus: "Οποιαδήποτε κατάσταση έγκρισης",
    Responses_Approval_FilterLabel: "Φιλτράρισμα ανά κατάσταση έγκρισης",
    Responses_Approval_ApproveSelected: "Έγκριση επιλεγμένων",
    Responses_Approval_RejectSelected: "Απόρριψη επιλεγμένων",
    Responses_Approval_BulkFailed: "Δεν ήταν δυνατή η ενημέρωση {count} απαντήσεων. Δοκιμάστε ξανά.",
    Responses_Approval_Approve: "Έγκριση",
    Responses_Approval_Reject: "Απόρριψη",
    Responses_Approval_Reset: "Επαναφορά σε εκκρεμότητα",
    Responses_Approval_CommentLabel: "Σχόλιο (προαιρετικό)",
    Responses_Approval_ReviewedBy: "Ελέγχθηκε από {name}",
    Responses_Approval_Error: "Δεν ήταν δυνατή η αποθήκευση της απόφασης. Δοκιμάστε ξανά.",
    Responses_Dashboard_ApprovalStatus: "Αναμένεται έλεγχος",
    Responses_Dashboard_ApprovalBreakdown: "{pending} σε εκκρεμότητα, {approved} εγκεκριμένες, {rejected} απορριφθείσες",
    Responses_Dashboard_TimelineCoarsened: "Το εύρος ημερομηνιών είναι μεγάλο, γι' αυτό το χρονολόγιο ομαδοποιήθηκε πιο αδρά ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Το εύρος ημερομηνιών είναι πολύ μεγάλο, γι' αυτό εμφανίζονται μόνο οι πιο πρόσφατες {count} περίοδοι.",
    Service_Item_DefaultTitle: "Απάντηση — {date}",
    Service_Email_ApprovalSubject: "Η απάντησή σας {status} — {title}",
    Service_Email_ApprovalHeading: "Η απάντησή σας {status}",
    Service_Email_ApprovalIntro: "Ένας εξεταστής χαρακτήρισε την απάντησή σας στο \"{title}\" ως {status}.",
    Service_Email_ApprovalCommentLabel: "Σχόλιο εξεταστή",
    Service_Approval_Approved: "εγκρίθηκε",
    Service_Approval_Rejected: "απορρίφθηκε",
    Service_Approval_Pending: "βρίσκεται σε εκκρεμότητα",
    Service_Lookup_InvalidFilter: "Το φίλτρο αναζήτησης δεν είναι έγκυρο.",
    Service_Edit_NotAllowed: "Αυτή η φόρμα δεν επιτρέπει την επεξεργασία υποβληθείσας απάντησης.",
    Service_Edit_NotYours: "Μπορείτε να επεξεργαστείτε μόνο τη δική σας απάντηση.",
    Service_Signature_AttachmentLabel: "Υπογραφή",
    PropertyPane_ListsLoadFailed: "Δεν ήταν δυνατή η φόρτωση των λιστών αυτού του ιστότοπου.",
    PropertyPane_EnterListName: "Πρώτα εισαγάγετε ένα όνομα για τη νέα λίστα.",
    PropertyPane_CreatingList: "Δημιουργία της «{name}»…",
    PropertyPane_ListCreated: "Η λίστα «{title}» δημιουργήθηκε και επιλέχθηκε.",
    PropertyPane_ListAlreadyExists: "Υπάρχει ήδη λίστα με όνομα «{name}» — επιλέξτε την από την αναπτυσσόμενη λίστα παραπάνω.",
    PropertyPane_CreateListFailed: "Δεν ήταν δυνατή η δημιουργία της λίστας. Ελέγξτε ότι έχετε άδεια δημιουργίας λιστών σε αυτόν τον ιστότοπο.",
    PropertyPane_Description: "Επιλέξτε τη λίστα του SharePoint που αποθηκεύει τις απαντήσεις της φόρμας ή δημιουργήστε μια νέα. Όλα τα υπόλοιπα — ερωτήσεις, εμφάνιση, ειδοποιήσεις — επεξεργάζονται απευθείας στη σελίδα.",
    PropertyPane_ResponseList_GroupName: "Λίστα απαντήσεων",
    PropertyPane_ListDropdown_Label: "Αποθήκευση απαντήσεων σε αυτή τη λίστα",
    PropertyPane_ResponsesGoTo: "Οι απαντήσεις αποθηκεύονται στη λίστα «{name}».",
    PropertyPane_PickList: "Επιλέξτε μια λίστα ή δημιουργήστε μία παρακάτω.",
    PropertyPane_LoadingLists: "Φόρτωση λιστών…",
    PropertyPane_NewListName_Label: "Ή δημιουργήστε νέα λίστα",
    PropertyPane_NewListName_Placeholder: "Όνομα νέας λίστας",
    PropertyPane_CreateList_Button: "Δημιουργία λίστας",
    PropertyPane_Tips_GroupName: "Συμβουλές",
    PropertyPane_Tip_AutoSave: "Οι ερωτήσεις και οι ρυθμίσεις αποθηκεύονται αυτόματα καθώς τις επεξεργάζεστε — δεν χρειάζεται να αποθηκεύσετε ή να δημοσιεύσετε τη σελίδα.",
    PropertyPane_Tip_Permissions: "Οι συμμετέχοντες χρειάζονται άδεια προσθήκης στοιχείων στη λίστα απαντήσεων. Ελέγξτε τα δικαιώματα της λίστας αν κάποιος αναφέρει σφάλμα κατά την υποβολή.",
    PropertyPane_Tip_Share: "Χρησιμοποιήστε το «Συλλογή απαντήσεων» στη σελίδα για να δημιουργήσετε τις στήλες της λίστας και να λάβετε έναν σύνδεσμο συμπλήρωσης που μπορείτε να μοιραστείτε.",
    App_ErrorBoundary_Title: "Smart Forms — Σφάλμα απόδοσης",
    App_ErrorBoundary_Message: "Μήνυμα:",
    App_ErrorBoundary_Stack: "Στοίβα:",
    App_ErrorBoundary_NoStack: "(δεν υπάρχει διαθέσιμη στοίβα)",
    App_ErrorBoundary_ConsoleNote: "Όλες οι λεπτομέρειες εγγράφηκαν επίσης στην κονσόλα του προγράμματος περιήγησης.",
    App_DefaultQuestionTitle: "Ερώτηση {number}",
    App_Error_ListMissing: "Η λίστα που έχει διαμορφωθεί για αυτή τη φόρμα δεν υπάρχει πλέον. Επιλέξτε άλλη λίστα στις ρυθμίσεις του τμήματος Web.",
    App_Error_LoadConfig: "Παρουσιάστηκε πρόβλημα κατά τη φόρτωση της διαμόρφωσης της φόρμας.",
    App_Error_Unable: "Δεν είναι δυνατή η φόρτωση της φόρμας.",
    App_Publish_ConflictNotice: "Το «{title}» έχει ήδη στήλη λίστας διαφορετικού τύπου ({type}). Μετονομάστε την ερώτηση ώστε να δημιουργηθεί νέα στήλη ή αλλάξτε ξανά τον τύπο της.",
    App_Publish_ConflictUnnamedQuestion: "μια ερώτηση",
    App_Publish_ColumnsAddedOne: "Προστέθηκε {count} στήλη στη λίστα «{list}».",
    App_Publish_ColumnsAddedOther: "Προστέθηκαν {count} στήλες στη λίστα «{list}».",
    App_Publish_TheList: "η λίστα",
    App_Publish_UpToDate: "Η λίστα απαντήσεων είναι ήδη ενημερωμένη.",
    App_Publish_Error: "Δεν ήταν δυνατή η δημιουργία των στηλών της λίστας. Αυτό συνήθως σημαίνει ότι δεν έχετε άδεια διαχείρισης λιστών στη λίστα απαντήσεων, αλλά μπορεί να συμβεί και σε ιστότοπους με απενεργοποιημένη την προσαρμοσμένη δέσμη ενεργειών. Ελέγξτε την κονσόλα του προγράμματος περιήγησης για το υποκείμενο σφάλμα ή δοκιμάστε ξανά.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Δημιουργήστε μια εντυπωσιακή φόρμα πάνω σε μια λίστα του SharePoint — {count} τύποι ερωτήσεων, λογική διακλάδωσης, μεταφορτώσεις αρχείων, σύνδεσμοι συμπλήρωσης προς κοινή χρήση και πίνακας εργαλείων αποτελεσμάτων.",
    App_Placeholder_ChooseList: "Επιλογή ή δημιουργία λίστας",
    App_Placeholder_Hint: "Επεξεργαστείτε τη σελίδα και διαμορφώστε αυτό το τμήμα Web για να ξεκινήσετε.",
    App_Loading: "Φόρτωση φόρμας…",
    App_OpenSettings: "Άνοιγμα ρυθμίσεων",
    App_Tab_Questions: "Ερωτήσεις",
    App_Tab_QuestionsWithCount: "Ερωτήσεις ({count})",
    App_Tab_Responses: "Απαντήσεις",
    App_Tab_Responses_Title: "Οι απαντήσεις αποθηκεύονται στη λίστα «{list}»",
    App_Templates_Start: "Έναρξη από πρότυπο",
    App_Settings_Title: "Ρυθμίσεις φόρμας — εμφάνιση, ειδοποιήσεις, πρόσβαση",
    App_Settings_AriaLabel: "Ρυθμίσεις φόρμας",
    App_Preview: "Προεπισκόπηση",
    App_Preview_Close: "Κλείσιμο προεπισκόπησης",
    App_Preview_Hint: "Προεπισκόπηση — ό,τι υποβάλλετε εδώ δεν αποθηκεύεται. Η επικύρωση και η διακλάδωση συμπεριφέρονται ακριβώς όπως θα συμπεριφέρονται για τους συμμετέχοντες.",
    App_Publish_GettingReady: "Προετοιμασία…",
    App_Publish_CollectResponses: "Συλλογή απαντήσεων",
    App_Publish_Share: "Κοινή χρήση",
    App_Retry: "Επανάληψη",
    App_SaveError_Banner: "Η τελευταία σας αλλαγή δεν αποθηκεύτηκε. Ελέγξτε τη σύνδεσή σας και δοκιμάστε ξανά.",
    App_Preflight_BlockingTitle: "Διορθώστε τα παρακάτω πριν από τη συλλογή",
    App_Preflight_WarningTitle: "Αξίζει να τα δείτε πρώτα",
    App_Preflight_BlockingText: "Αυτά θα εμπόδιζαν τη σωστή λειτουργία της δημοσιευμένης φόρμας.",
    App_Preflight_WarningText: "Δεν υπάρχει κάποια βλάβη, αλλά συνήθως αξίζει να διορθωθούν πριν μοιραστείτε τον σύνδεσμο.",
    App_Preflight_GoTo: "Μετάβαση σε",
    App_Preflight_CollectAnyway: "Συλλογή απαντήσεων ούτως ή άλλως",
    App_Preflight_Back: "Πίσω στη φόρμα",
    App_Cancel: "Ακύρωση",
    App_Done: "Τέλος",
    App_Share_Title: "Η φόρμα σας είναι έτοιμη για κοινή χρήση",
    App_Share_SubText: "Στείλτε αυτόν τον σύνδεσμο σε όποιον πρέπει να συμπληρώσει τη φόρμα.",
    App_Share_LinkAriaLabel: "Σύνδεσμος κοινής χρήσης",
    App_Share_Copy: "Αντιγραφή",
    App_Share_Copied: "Αντιγράφηκε",
    App_Share_AddItemsEmphasis: "προσθήκης στοιχείων",
    App_Share_PermissionNote: "Οι συμμετέχοντες χρειάζονται άδεια {addItems} στη λίστα «{title}» και πρόσβαση σε αυτή τη σελίδα. Αν κάποιος λάβει σφάλμα κατά την υποβολή, σχεδόν πάντα αυτός είναι ο λόγος.",
    App_Share_PrefillNote: "Μπορείτε να απαντήσετε εκ των προτέρων σε ερωτήσεις μέσω του συνδέσμου προσθέτοντας το όνομα της στήλης, για παράδειγμα {example}.",
    App_Templates_ReplaceWarning: "Η επιλογή προτύπου αντικαθιστά τις ερωτήσεις που έχετε τώρα.",
    App_Templates_PickStart: "Επιλέξτε ένα σημείο εκκίνησης — μπορείτε να αλλάξετε οτιδήποτε στη συνέχεια.",
    App_Templates_Empty: "Κενό",
    App_Templates_QuestionCount: "{count} ερωτήσεις",
    App_SaveChip_SavingTitle: "Αποθήκευση της τελευταίας σας επεξεργασίας",
    App_SaveChip_Saving: "Γίνεται αποθήκευση…",
    App_SaveChip_FailedTitle: "Η τελευταία σας επεξεργασία δεν αποθηκεύτηκε. Ελέγξτε τη σύνδεσή σας και δοκιμάστε ξανά.",
    App_SaveChip_Failed: "Η αποθήκευση απέτυχε",
    App_SaveChip_SavedTitle: "Όλες οι αλλαγές έχουν αποθηκευτεί",
    App_SaveChip_Saved: "Αποθηκεύτηκε",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Νέα απάντηση — {title}",
    Service_Email_NewResponseHeading: "Νέα απάντηση: {title}",
    Service_Email_NewResponseIntro: "Κάποιος μόλις υπέβαλε μια απάντηση — {date}.",
    Service_Email_ReceiptSubject: "Η απάντησή σας — {title}",
    Service_Email_ReceiptHeading: "Ευχαριστούμε για την απάντησή σας!",
    Service_Email_ReceiptIntro: "Ακολουθεί αντίγραφο όσων υποβάλατε στη φόρμα «{title}».",
    App_History_Title: "Ιστορικό εκδόσεων",
    App_History_RestoredNotice: "Έγινε επαναφορά της έκδοσης που αποθηκεύτηκε στις {date}. Ελέγξτε την και, στη συνέχεια, χρησιμοποιήστε τη Συλλογή απαντήσεων για να δημοσιεύσετε νέες ερωτήσεις.",
    App_History_Undo: "Αναίρεση επαναφοράς",
    App_Share_CopyManual: "Το πρόγραμμα περιήγησης απέκλεισε την αντιγραφή. Επιλέξτε τον παραπάνω σύνδεσμο και πατήστε Ctrl+C (Cmd+C σε Mac) για να τον αντιγράψετε.",
    App_Share_TeamsNote: "Βρίσκεστε στο Microsoft Teams. Αυτός ο σύνδεσμος ανοίγει απευθείας τη σελίδα του SharePoint, επομένως οι παραλήπτες χρειάζονται πρόσβαση στον ιστότοπο.",
    App_Share_PrefillNotSecure: "Οι προσυμπληρωμένες απαντήσεις είναι απλώς διευκόλυνση: όποιος έχει τον σύνδεσμο μπορεί να τις αλλάξει, γι' αυτό μην τις θεωρείτε ποτέ όριο ασφαλείας.",
    Designer_Section_DropHere: "Αποθέστε μια ερώτηση εδώ",
    Designer_Section_DropEnd: "Αποθέστε εδώ για μετακίνηση στο τέλος αυτής της ενότητας",
    Designer_Rules_RemovedOne: "Καταργήθηκε 1 κανόνας διακλάδωσης που δεν ταίριαζε πλέον.",
    Designer_Rules_RemovedOther: "Καταργήθηκαν {count} κανόνες διακλάδωσης που δεν ταίριαζαν πλέον.",
    Designer_Settings_AllowEdit: "Να επιτρέπεται στους συμμετέχοντες να επεξεργάζονται την απάντησή τους",
    Designer_Settings_AllowEditHint: "Οι συμμετέχοντες μπορούν να ανοίξουν ξανά και να ενημερώσουν όσα υπέβαλαν. Κάθε άτομο μπορεί να επεξεργαστεί μόνο τη δική του απάντηση.",
    Designer_Settings_EnableApproval: "Ενεργοποίηση ροής εργασίας έγκρισης",
    Designer_Settings_ApprovalNotify: "Αποστολή email στον συμμετέχοντα με την απόφαση",
    Designer_Settings_ApprovalHint: "Προσθέτει στήλες έγκρισης στη λίστα απαντήσεων την επόμενη φορά που θα δημοσιεύσετε. Οι κάτοχοι εγκρίνουν ή απορρίπτουν απαντήσεις από την καρτέλα Απαντήσεις.",
    Designer_History_Title: "Ιστορικό εκδόσεων",
    Designer_History_Intro: "Προηγούμενες αποθηκευμένες εκδόσεις των ερωτήσεων και των ρυθμίσεων αυτής της φόρμας. Η επαναφορά φορτώνει μια έκδοση στον σχεδιαστή· μπορείτε να την αναιρέσετε και οι νέες ερωτήσεις δημιουργούνται μόνο κατά τη δημοσίευση.",
    Designer_History_Loading: "Φόρτωση εκδόσεων...",
    Designer_History_Empty: "Δεν βρέθηκαν προηγούμενες εκδόσεις. Το ιστορικό εκδόσεων απαιτεί ενεργοποιημένη τη δημιουργία εκδόσεων στη λίστα \"Smart Forms Config\" και τουλάχιστον μία αποθηκευμένη επεξεργασία.",
    Designer_History_Latest: "Τελευταία",
    Designer_History_LatestTitle: "Αυτή είναι η έκδοση που χρησιμοποιείται αυτήν τη στιγμή",
    Designer_History_By: "από {name}",
    Designer_History_UnknownAuthor: "Άγνωστος συντάκτης",
    Designer_History_VersionLabel: "έκδοση {label}",
    Designer_History_Preview: "Προεπισκόπηση",
    Designer_History_Restore: "Επαναφορά",
    Designer_History_QuestionsOne: "1 ερώτηση",
    Designer_History_QuestionsOther: "{count} ερωτήσεις",
    Designer_History_LoadFailed: "Δεν ήταν δυνατή η φόρτωση αυτής της έκδοσης.",
    Designer_History_ConfirmTitle: "Επαναφορά αυτής της έκδοσης;",
    Designer_History_ConfirmText: "Η φόρμα θα αντικατασταθεί από την έκδοση που αποθηκεύτηκε στις {date} ({count} ερωτήσεις). Μπορείτε να το αναιρέσετε αμέσως μετά."
  };
});
