define([], function () {
  return {
    Designer_Color_Blue: "Blue",
    Designer_Color_Teal: "Teal",
    Designer_Color_Green: "Green",
    Designer_Color_Purple: "Purple",
    Designer_Color_Magenta: "Magenta",
    Designer_Color_Red: "Red",
    Designer_Color_Orange: "Orange",
    Designer_Color_Gray: "Gray",
    Designer_Settings_LayoutSinglePage: "All questions on one page",
    Designer_Settings_LayoutWizard: "One section per step (wizard)",
    Designer_Settings_Title: "Form settings",
    Designer_Common_Apply: "Apply",
    Designer_Common_Cancel: "Cancel",
    Designer_Settings_TabBasics: "Basics",
    Designer_Settings_FormTitle: "Form title",
    Designer_Settings_Description: "Description",
    Designer_Settings_Layout: "Layout",
    Designer_Settings_NumberQuestions: "Number the questions",
    Designer_Settings_ShuffleQuestions: "Shuffle question order for each respondent",
    Designer_Settings_ShowProgressBar: "Show a progress bar",
    Designer_Settings_TabAppearance: "Appearance",
    Designer_Settings_AccentColor: "Accent color",
    Designer_Settings_CustomColorTitle: "Custom color",
    Designer_Settings_CustomColorAria: "Custom accent color",
    Designer_Settings_AccentHint: "Accent colors are automatically adjusted for contrast on dark sites, so the form stays readable whichever theme the page uses.",
    Designer_Settings_ShowHeader: "Show the form header",
    Designer_Settings_HeaderIcon: "Header icon",
    Designer_Settings_TabAfterSubmit: "After submit",
    Designer_Settings_SubmitButtonText: "Submit button text",
    Designer_Settings_SubmitPlaceholder: "Submit",
    Designer_Settings_ThankYouTitle: "Thank-you title",
    Designer_Settings_ThankYouPlaceholder: "Thank you!",
    Designer_Settings_ThankYouMessage: "Thank-you message",
    Designer_Settings_ShowSubmitAnother: "Show a \"Submit another response\" button",
    Designer_Settings_TabNotifications: "Notifications",
    Designer_Settings_EmailEachResponseTo: "Email each response to",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "People in your organization get every response by email, with a link to the list item",
    Designer_Settings_RespondentReceipt: "Email respondents a copy of their answers",
    Designer_Settings_NotificationsInfo: "Notifications use SharePoint's own mail service, so recipients must be users in your organization. External addresses are silently dropped.",
    Designer_Settings_TabAccess: "Access",
    Designer_Settings_OpenFrom: "Open from",
    Designer_Settings_OpenImmediately: "Open immediately",
    Designer_Settings_CloseAfter: "Close after",
    Designer_Settings_NeverClose: "Never close",
    Designer_Settings_ClearDates: "Clear dates",
    Designer_Settings_DatesInverted: "The close date is on or before the open date, so the form would never accept responses.",
    Designer_Settings_MaxResponses: "Stop after this many responses",
    Designer_Settings_NoLimit: "No limit",
    Designer_Settings_OneResponsePerPerson: "Only allow one response per person",
    Designer_Settings_AllowSaveDraft: "Let respondents save a draft and finish later",
    Designer_Settings_ClosedMessage: "Message shown when the form is closed",
    Designer_Settings_ClosedMessagePlaceholder: "This form is no longer accepting responses.",
    Designer_Settings_AccessInfo: "These limits are enforced by the form, not by SharePoint. Anyone with permission to add items to the response list could still add one directly through the list.",
    Designer_Field_StyleInfo: "Info (accent)",
    Designer_Field_StyleSuccess: "Success (green)",
    Designer_Field_StyleWarning: "Warning (amber)",
    Designer_Field_StylePlain: "Plain text",
    Designer_Field_StyleDivider: "Divider line",
    Designer_Field_IconStars: "Stars",
    Designer_Field_IconHearts: "Hearts",
    Designer_Field_IconThumbs: "Thumbs up",
    Designer_Field_FormatPlain: "Plain number",
    Designer_Field_FormatCurrency: "Currency",
    Designer_Field_FormatPercent: "Percentage",
    Designer_Field_UntitledQuestion: "Untitled question",
    Designer_Field_DeletedQuestion: "a deleted question",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} and {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "OR",
    Designer_Rule_JoinAll: "AND",
    Designer_Rule_Preview: "Shown when {conditions}.",
    Designer_Field_Yes: "Yes",
    Designer_Field_No: "No",
    Designer_Field_When: "When",
    Designer_Field_SelectValue: "Select a value",
    Designer_Field_DateValuePlaceholder: "YYYY-MM-DD or \"today\"",
    Designer_Field_ValuePlaceholder: "Value",
    Designer_Field_UpperBound: "Upper bound",
    Designer_Field_RemoveCondition: "Remove this condition",
    Designer_Field_FormulaInvalid: "This formula cannot be worked out. Check the brackets and operators.",
    Designer_Field_FormulaMissing: "These questions do not exist: {names}.",
    Designer_Field_FormulaPreview: "With every input at 10, this shows {value}.",
    Designer_Field_HintYesNo: "Use \"yes\" or \"no\"",
    Designer_Field_HintMultiDefault: "Separate multiple defaults with ;",
    Designer_Field_HintSingleDefault: "Must match one of the options",
    Designer_Field_HintDate: "Use \"today\", or a date like 2026-03-01",
    Designer_Field_HintTime: "Use \"now\", or a time like 09:30",
    Designer_Field_QuestionSettings: "Question settings",
    Designer_Field_Appearance: "Appearance",
    Designer_Field_Style: "Style",
    Designer_Field_ImageUrl: "Image URL (optional)",
    Designer_Field_Content: "Content",
    Designer_Field_BasicFormatting: "Basic formatting is allowed: bold, italic, lists and links.",
    Designer_Field_TabOptions: "Options",
    Designer_Field_TabBranching: "Branching",
    Designer_Field_BranchingNeedsQuestion: "Add another question first — branching needs something to depend on.",
    Designer_Field_BranchingToggle: "Only show this question when other answers match",
    Designer_Field_Match: "Match",
    Designer_Field_MatchAll: "all of these",
    Designer_Field_MatchAny: "any of these",
    Designer_Field_AddCondition: "Add condition",
    Designer_Field_TabValidation: "Validation",
    Designer_Field_HelpText: "Help text",
    Designer_Field_HelpTextPlaceholder: "Shown under the question label",
    Designer_Field_CheckboxLabel: "Checkbox label",
    Designer_Field_Placeholder: "Placeholder",
    Designer_Field_DefaultAnswer: "Default answer",
    Designer_Field_RequiredMessage: "Custom required message",
    Designer_Field_RequiredMessagePlaceholder: "{title} is required",
    Designer_Field_ThisQuestion: "This question",
    Designer_Field_RequiredMessageDescription: "Shown instead of the standard message when this question is left blank",
    Designer_Field_ReadOnly: "Read-only (answer can only come from a prefilled link)",
    Designer_Field_ValidationRules: "Validation rules",
    Designer_Field_MaxLength: "Maximum length",
    Designer_Field_Pattern: "Must match this pattern",
    Designer_Field_PatternDescription: "A regular expression. Leave blank for no pattern check.",
    Designer_Field_PatternMessage: "Message when the pattern doesn't match",
    Designer_Field_PatternMessagePlaceholder: "This answer is not in the expected format",
    Designer_Field_Format: "Format",
    Designer_Field_UnitSuffix: "Unit shown after the value",
    Designer_Field_UnitSuffixPlaceholder: "kg, hrs, items…",
    Designer_Field_Minimum: "Minimum",
    Designer_Field_Maximum: "Maximum",
    Designer_Field_Decimals: "Decimals",
    Designer_Field_Formula: "Formula",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Reference other questions by their text in braces. Supports + - * / ( ) and round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Available questions: {questions}",
    Designer_Field_NoneYet: "none yet",
    Designer_Field_Step: "Step",
    Designer_Field_From: "From",
    Designer_Field_To: "To",
    Designer_Field_LowLabel: "Label at the low end",
    Designer_Field_LowLabelPlaceholder: "Not at all likely",
    Designer_Field_HighLabel: "Label at the high end",
    Designer_Field_HighLabelPlaceholder: "Extremely likely",
    Designer_Field_SummarizeAs: "Summarize as",
    Designer_Field_SummarizeAverage: "Average and distribution",
    Designer_Field_SummarizeNps: "Net Promoter Score (needs a 0–10 scale)",
    Designer_Field_NpsWarning: "Net Promoter Score is only meaningful on a 0–10 scale. Set From to 0 and To to 10.",
    Designer_Field_NumberOfIcons: "Number of icons",
    Designer_Field_Icon: "Icon",
    Designer_Field_AllowHalf: "Allow half values",
    Designer_Field_ShowOptionsAs: "Show options as",
    Designer_Field_DisplayButtons: "Inline buttons",
    Designer_Field_DisplayDropdown: "Dropdown",
    Designer_Field_DisplayAutomatic: "Automatic (inline up to 6 options)",
    Designer_Field_AllowOther: "Add a write-in \"Other\" option",
    Designer_Field_OtherLabel: "Label for the \"Other\" option",
    Designer_Field_OtherPlaceholder: "Other",
    Designer_Field_ShuffleOptions: "Shuffle the option order for each respondent",
    Designer_Field_MinSelections: "Minimum selections",
    Designer_Field_MaxSelections: "Maximum selections",
    Designer_Field_SourceList: "Source list",
    Designer_Field_ChooseList: "Choose a list",
    Designer_Field_LookupColumn: "Column to read options from",
    Designer_Field_ChooseColumn: "Choose a column",
    Designer_Field_ChooseListFirst: "Choose a list first",
    Designer_Field_LookupFilter: "Filter (optional)",
    Designer_Field_LookupFilterDescription: "An OData filter narrowing which source items become options",
    Designer_Field_LookupInfo: "Answers store the option text, not a link to the source item, so responses stay readable even if the source list changes later.",
    Designer_Field_ConsentText: "Terms shown above the checkbox",
    Designer_Field_AllowMultiplePeople: "Allow multiple people",
    Designer_Field_AllowGroups: "Also allow groups",
    Designer_Field_IncludeTime: "Include a time of day",
    Designer_Field_TimeStep: "Time step (minutes)",
    Designer_Field_MaxFiles: "Maximum files",
    Designer_Field_MaxFileSize: "Max size each (MB)",
    Designer_Field_AcceptedTypes: "Accepted file types",
    Designer_Field_AcceptedTypesDescription: "Comma-separated extensions. Leave blank to accept anything SharePoint allows.",
    Designer_Field_FilesInfo: "Files are saved as attachments on the response item. SharePoint blocks some extensions (such as .exe) regardless of what you allow here.",
    Designer_Field_Rows: "Rows",
    Designer_Field_ProvisionedNote: "This question already has a list column ({name}). Settings that change the column's type are locked — duplicate the question if you need a different type.",
    Designer_Category_Text: "Text",
    Designer_Category_Choice: "Choice",
    Designer_Category_Scales: "Scales",
    Designer_Category_Date: "Date",
    Designer_Category_People: "People",
    Designer_Category_Advanced: "Advanced",
    Designer_Category_Layout: "Layout",
    Designer_Menu_CommonPresets: "Common presets",
    Designer_Menu_AllTypes: "All question types",
    Designer_Menu_ChangeType: "Change type",
    Designer_Menu_TypeLockedTitle: "The list column already exists, so the type is locked. Duplicate the question to change it.",
    Designer_Menu_MoreSettings: "Branching, validation & more",
    Designer_Menu_InsertBelow: "Insert question below",
    Designer_Card_Duplicate: "Duplicate",
    Designer_Card_DeleteQuestion: "Delete question",
    Designer_Outline_Aria: "Question outline",
    Designer_Outline_QuestionCountOne: "{count} question",
    Designer_Outline_QuestionCountOther: "{count} questions",
    Designer_Outline_IssuesTitle: "{count} issue(s) to review",
    Designer_Outline_Find: "Find a question",
    Designer_Outline_Empty: "No questions yet.",
    Designer_Section_DefaultTitle: "Section {number}",
    Designer_Card_Question: "Question",
    Designer_Card_BranchingTitle: "This question only appears when a branching rule matches",
    Designer_Card_BranchingChip: "Branching",
    Designer_Card_LiveTitle: "The list column exists, so the type is locked",
    Designer_Card_LiveChip: "Live",
    Designer_Card_CheckChip: "Check",
    Designer_Option_Placeholder: "Option {number}",
    Designer_Option_LabelAria: "Option {number} label",
    Designer_Option_ImageUrl: "Image URL",
    Designer_Option_ImageUrlAria: "Option {number} image URL",
    Designer_Option_Remove: "Remove option",
    Designer_Option_RemoveAria: "Remove option {number}",
    Designer_Option_Add: "Add option",
    Designer_Option_OtherHint: "Respondents can also write in an answer labeled “{label}”.",
    Designer_Option_OtherFallback: "Other",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Remove",
    Designer_Grid_RemoveAria: "Remove {label} {number}",
    Designer_Grid_Statements: "Statements",
    Designer_Grid_Scale: "Scale",
    Designer_Grid_AddStatement: "Add statement",
    Designer_Grid_AddScale: "Add scale",
    Designer_Width_Full: "Full width",
    Designer_Width_Half: "Half width",
    Designer_Width_Third: "One third width",
    Designer_Width_Aria: "Question width",
    Designer_Card_BlockLabelPlaceholder: "Block label (not shown to respondents)",
    Designer_Card_QuestionText: "Question text",
    Designer_Card_MoveUp: "Move up",
    Designer_Card_MoveQuestionUp: "Move question up",
    Designer_Card_MoveDown: "Move down",
    Designer_Card_MoveQuestionDown: "Move question down",
    Designer_Card_DuplicateQuestion: "Duplicate question",
    Designer_Card_MultipleAnswers: "Multiple answers",
    Designer_Card_Required: "Required",
    Designer_Card_MoreOptions: "More options",
    Designer_Card_MoreOptionsAria: "More options for this question",
    Designer_Canvas_FormTitle: "Form title",
    Designer_Canvas_DescriptionPlaceholder: "Add a description (optional)",
    Designer_Canvas_DescriptionAria: "Form description",
    Designer_Canvas_EmptyTitle: "Add your first question",
    Designer_Canvas_EmptyBody: "Pick a question type to get started. You can reorder questions by dragging them, and add branching so people only see what applies to them.",
    Designer_Section_Chip: "Section {number} of {total}",
    Designer_Section_TitlePlaceholder: "Section title",
    Designer_Section_TitleAria: "Section {number} title",
    Designer_Section_DescriptionPlaceholder: "Description (optional)",
    Designer_Section_DescriptionAria: "Section {number} description",
    Designer_Section_MoveUp: "Move section up",
    Designer_Section_MoveDown: "Move section down",
    Designer_Section_Delete: "Delete section",
    Designer_Card_DragToReorder: "Drag to reorder",
    Designer_Card_ReorderAria: "Reorder {title}",
    Designer_Card_ReorderFallback: "question",
    Designer_Canvas_AddNew: "Add new",
    Designer_Canvas_AddSection: "Add section",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Street address",
    Form_Address_Street2Placeholder: "Apartment, suite, etc. (optional)",
    Form_Address_CityPlaceholder: "City",
    Form_Address_StatePlaceholder: "State / county",
    Form_Address_PostalCodePlaceholder: "Postcode / ZIP",
    Form_Address_CountryPlaceholder: "Country",
    Form_Address_StreetAria: "street address",
    Form_Address_Street2Aria: "address line 2",
    Form_Address_CityAria: "city",
    Form_Address_StateAria: "state or county",
    Form_Address_PostalCodeAria: "postcode",
    Form_Address_CountryAria: "country",
    Form_Consent_DefaultLabel: "I agree",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered} of {total} rows answered",
    Form_Lookup_LoadError: "The options for this question could not be loaded.",
    Form_Lookup_Loading: "Loading options…",
    Form_Lookup_SelectOptionsPlaceholder: "Select options",
    Form_Lookup_SelectOptionPlaceholder: "Select an option",
    Form_Person_Placeholder: "Start typing a name…",
    Form_Person_SuggestedPeopleAndGroups: "Suggested people and groups",
    Form_Person_SuggestedPeople: "Suggested people",
    Form_Person_NoPeopleOrGroups: "No people or groups found",
    Form_Person_NoPeople: "No people found",
    Form_Person_Searching: "Searching…",
    Form_Ranking_Moved: "{item} moved to position {position} of {total}",
    Form_Ranking_MoveUp: "Move up",
    Form_Ranking_MoveDown: "Move down",
    Form_Ranking_MoveItemUpAria: "Move {item} up",
    Form_Ranking_MoveItemDownAria: "Move {item} down",
    Form_Rating_ValueText: "{value} of {max}",
    Form_Rating_NotRated: "Not rated",
    Form_Rating_Clear: "Clear rating",
    Form_RichText_Bold: "Bold",
    Form_RichText_Italic: "Italic",
    Form_RichText_Underline: "Underline",
    Form_RichText_BulletedList: "Bulleted list",
    Form_RichText_NumberedList: "Numbered list",
    Form_RichText_ClearFormatting: "Clear formatting",
    Form_RichText_ToolbarAria: "Text formatting",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\" was skipped — the limit is {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" is not an accepted type.",
    Form_File_TooLarge: "\"{name}\" is larger than {size} MB.",
    Form_File_AlreadyAttached: "\"{name}\" is already attached.",
    Form_File_ReadError: "One of the files could not be read. Try attaching it again.",
    Form_File_HintMaxSize: "up to {size} MB each",
    Form_File_HintOneFile: "1 file",
    Form_File_HintMaxFiles: "max {count} files",
    Form_File_Reading: "Reading files…",
    Form_File_DropPrompt: "Drop files here, or click to browse",
    Form_File_Remove: "Remove {name}",
    Form_Signature_Alt: "Signature",
    Form_Signature_AriaSigned: "{label} — signed",
    Form_Signature_AriaEmpty: "{label} — empty",
    Form_Signature_Clear: "Clear",
    Form_Signature_Signed: "Signed",
    Form_Signature_Prompt: "Sign above using a mouse, pen or finger",
    Form_Time_Placeholder: "Select a time",
    Form_Field_DatePlaceholder: "Select a date",
    Form_Field_TimeAriaWithLabel: "{label} — time",
    Form_Field_TimeAria: "Time",
    Form_Field_OtherDefault: "Other",
    Form_Field_SelectOptionsPlaceholder: "Select options",
    Form_Field_PleaseSpecify: "Please specify",
    Form_Field_OtherSpecifyAria: "{label} — please specify",
    Form_Field_SelectOptionPlaceholder: "Select an option",
    Form_Field_Yes: "Yes",
    Form_Field_No: "No",
    Form_Field_SliderHint: "Drag the slider to answer",
    Form_Field_WebAddressAriaWithLabel: "{label} — web address",
    Form_Field_WebAddressAria: "Web address",
    Form_Field_DisplayTextPlaceholder: "Display text (optional)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — display text",
    Form_Field_DisplayTextAria: "Display text",
    Form_Field_ChooseBetween: "Choose between {min} and {max}",
    Form_Field_ChooseAtLeast: "Choose at least {min}",
    Form_Field_ChooseUpTo: "Choose up to {max}",
    Form_Field_SelectedCount: "{count} selected",
    Form_Field_RequiredAria: "(required)",
    Form_Submit_SaveError: "Your response could not be saved. Make sure the form has been published from the designer and that you have permission to add items to the response list.",
    Form_Empty_Message: "This form doesn't have any questions yet. The form owner can add them in the Questions tab.",
    Form_Checking: "Checking the form…",
    Form_Closed_NotYetOpen: "Not open yet",
    Form_Closed_AlreadyAnswered: "Already answered",
    Form_Closed_Title: "Form closed",
    Form_Confirmation_PreviewNotice: "This was a preview — nothing was saved to the response list.",
    Form_Confirmation_PreviewAgain: "Preview again",
    Form_Confirmation_SubmitAnother: "Submit another response",
    Form_Wizard_StepFallback: "Step {step}",
    Form_Wizard_StepsAria: "Form steps",
    Form_Wizard_StepOf: "Step {step} of {total}",
    Form_ErrorSummary_Title: "Please check {count} answers:",
    Form_ErrorSummary_UntitledQuestion: "Untitled question",
    Form_ErrorSummary_Question: "Question",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Back",
    Form_Nav_Next: "Next",
    Form_Draft_Saving: "Saving…",
    Form_Draft_Saved: "Draft saved",
    Form_Draft_SaveAndFinishLater: "Save and finish later",
    Form_Draft_NotSaved: "Draft not saved",
    Form_Submit_Preview: "Submit (preview)",
    Form_Submit_Button: "Submit",
    Form_Response_NoAnswer: "No answer",
    Form_Signature_TypeLabel: "Type your full name",
    Form_Signature_TypeInstead: "Type your name instead",
    Form_Signature_DrawInstead: "Draw instead",
    Form_Edit_Button: "Edit your previous response",
    Form_Edit_Available: "You have already submitted a response. You can edit it instead of submitting a new one.",
    Form_Edit_Banner: "You are editing your previous response.",
    Form_Edit_Save: "Update response",
    Form_Edit_UpdatedTitle: "Response updated",
    Form_Edit_UpdatedMessage: "Your changes have been saved.",
    Form_Edit_LoadError: "Your previous response could not be loaded. Please try again.",
    Form_Draft_MissingFiles: "Please re-attach: {names}. These files could not be restored.",
    Form_Attachments_Failed: "Your answers were saved, but these attachments could not be uploaded: {names}. Please try again or contact the form owner.",
    Logic_ThisQuestion: "This question",
    Logic_Required: "{label} is required",
    Logic_RequiredConsent: "Please tick the box to continue",
    Logic_RequiredFile: "Please attach at least one file",
    Logic_RequiredSignature: "Please add your signature",
    Logic_RequiredLikert: "Please answer every row",
    Logic_InvalidEmail: "Enter a valid email address",
    Logic_InvalidPhone: "Enter a valid phone number",
    Logic_InvalidUrl: "Enter a valid web address starting with http:// or https://",
    Logic_MinValue: "Value must be at least {value}",
    Logic_MaxValue: "Value must be at most {value}",
    Logic_MaxLength: "Maximum length is {max} characters",
    Logic_ChooseAtLeastOne: "Choose at least {count} option",
    Logic_ChooseAtLeastMany: "Choose at least {count} options",
    Logic_ChooseAtMostOne: "Choose no more than {count} option",
    Logic_ChooseAtMostMany: "Choose no more than {count} options",
    Logic_LikertRemaining: "Please answer every row ({count} remaining)",
    Logic_MaxFilesOne: "Attach no more than {count} file",
    Logic_MaxFilesMany: "Attach no more than {count} files",
    Logic_FileTooLarge: "\"{name}\" is larger than {size} MB",
    Logic_FileTypeNotAccepted: "\"{name}\" is not an accepted file type ({types})",
    Logic_AddressRequired: "Enter at least a street and a city",
    Logic_PatternDefault: "This answer is not in the expected format",
    Logic_Yes: "Yes",
    Logic_No: "No",
    Logic_Agreed: "Agreed",
    Logic_NotAgreed: "Not agreed",
    Logic_Signed: "Signed",
    Logic_NoAnswer: "(no answer)",
    Logic_Unknown: "(unknown)",
    Logic_OtherSlice: "Other ({count})",
    Logic_CsvResponseId: "Response ID",
    Logic_CsvSubmitted: "Submitted",
    Logic_CsvSubmittedBy: "Submitted by",
    Logic_EmailQuestion: "Question",
    Logic_EmailViewItem: "View in Microsoft Lists",
    Logic_EmailFooter: "Sent automatically by Smart Forms.",
    Logic_ClosedDefault: "This form is no longer accepting responses.",
    Logic_NotYetOpen: "This form opens on {date}.",
    Logic_AlreadyResponded: "You have already responded to this form. Thank you!",
    Logic_UntitledQuestion: "An untitled question",
    Logic_Issue_NoQuestions: "Add at least one question before collecting responses.",
    Logic_Issue_NoTitle: "A question has no text — it will be named automatically when you publish.",
    Logic_Issue_DuplicateTitle: "{label} shares its text with another question, which makes results harder to read.",
    Logic_Issue_NeedTwoOptions: "{label} needs at least two options.",
    Logic_Issue_ImageNoImage: "{label} has options with no image — they will show as text tiles.",
    Logic_Issue_LikertNeedRow: "{label} needs at least one row.",
    Logic_Issue_LikertNeedColumns: "{label} needs at least two scale columns.",
    Logic_Issue_NoLookupList: "{label} has no source list selected.",
    Logic_Issue_NoFormula: "{label} has no formula.",
    Logic_Issue_BadFormula: "{label} has a formula that cannot be worked out. Check the brackets and operators.",
    Logic_Issue_MissingRefs: "{label} refers to questions that do not exist: {names}.",
    Logic_Issue_BadPattern: "{label} has an invalid validation pattern.",
    Logic_Issue_BrokenRule: "{label} has a branching rule pointing at a deleted question.",
    Logic_Issue_SelfRule: "{label} has a branching rule that refers to itself.",
    Logic_Issue_RuleMismatch: "{label} has a branching rule that no longer fits the question it depends on.",
    Logic_Issue_RequiredReadOnly: "{label} is both required and read-only, so it can only be answered by a prefilled link.",
    Logic_Issue_EmptySection: "A section has no questions and will be skipped.",
    Logic_Issue_CloseBeforeOpen: "The close date is on or before the open date, so the form will never accept responses.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Approval emails are switched on but the approval step is off.",
    Logic_Op_equals: "is",
    Logic_Op_notEquals: "is not",
    Logic_Op_contains: "contains",
    Logic_Op_notContains: "does not contain",
    Logic_Op_notEmpty: "is answered",
    Logic_Op_empty: "is not answered",
    Logic_Op_greaterThan: "is greater than",
    Logic_Op_greaterOrEqual: "is at least",
    Logic_Op_lessThan: "is less than",
    Logic_Op_lessOrEqual: "is at most",
    Logic_Op_between: "is between",
    Logic_Op_before: "is before",
    Logic_Op_after: "is after",
    Logic_Type_Text: "Short answer",
    Logic_TypeDesc_Text: "A single line of text",
    Logic_Category_Text: "Text",
    Logic_Type_MultilineText: "Long answer",
    Logic_TypeDesc_MultilineText: "Several lines of plain text",
    Logic_Type_RichText: "Formatted text",
    Logic_TypeDesc_RichText: "Bold, lists and links",
    Logic_Type_Choice: "Choice",
    Logic_TypeDesc_Choice: "Pick from a list of options",
    Logic_Category_Choice: "Choice",
    Logic_Type_ImageChoice: "Image choice",
    Logic_TypeDesc_ImageChoice: "Pick from picture tiles",
    Logic_Type_Lookup: "Lookup from a list",
    Logic_TypeDesc_Lookup: "Options read live from another SharePoint list",
    Logic_Type_YesNo: "Yes / No",
    Logic_TypeDesc_YesNo: "A simple on/off toggle",
    Logic_Type_Consent: "Consent",
    Logic_TypeDesc_Consent: "A checkbox the respondent must tick to continue",
    Logic_Type_Ranking: "Ranking",
    Logic_TypeDesc_Ranking: "Drag options into order of preference",
    Logic_Type_Rating: "Rating",
    Logic_TypeDesc_Rating: "Stars, hearts or thumbs",
    Logic_Category_Scales: "Scales",
    Logic_Type_Scale: "Opinion scale",
    Logic_TypeDesc_Scale: "A numbered scale with labelled ends",
    Logic_Type_Slider: "Slider",
    Logic_TypeDesc_Slider: "A value on a sliding scale",
    Logic_Type_Likert: "Likert grid",
    Logic_TypeDesc_Likert: "Rate several statements on one shared scale",
    Logic_Type_Number: "Number",
    Logic_TypeDesc_Number: "Plain, currency or percentage",
    Logic_Category_Advanced: "Advanced",
    Logic_Type_Calculated: "Calculated",
    Logic_TypeDesc_Calculated: "A read-only total worked out from other answers",
    Logic_Type_Date: "Date",
    Logic_TypeDesc_Date: "A calendar date, optionally with a time",
    Logic_Category_Date: "Date",
    Logic_Type_Time: "Time",
    Logic_TypeDesc_Time: "A time of day on its own",
    Logic_Type_Person: "Person",
    Logic_TypeDesc_Person: "Pick someone from the organization",
    Logic_Category_People: "People",
    Logic_Type_Email: "Email",
    Logic_TypeDesc_Email: "An email address, validated",
    Logic_Type_Phone: "Phone",
    Logic_TypeDesc_Phone: "A phone number, validated",
    Logic_Type_Address: "Address",
    Logic_TypeDesc_Address: "Street, city, postcode and country",
    Logic_Type_Hyperlink: "Link",
    Logic_TypeDesc_Hyperlink: "A web address",
    Logic_Type_FileUpload: "File upload",
    Logic_TypeDesc_FileUpload: "Attach one or more files to the response",
    Logic_Type_Signature: "Signature",
    Logic_TypeDesc_Signature: "Sign with a mouse, pen or finger",
    Logic_Type_Content: "Text block",
    Logic_TypeDesc_Content: "Instructions or an image — collects no answer",
    Logic_Category_Layout: "Layout",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "How likely are you to recommend…",
    Logic_Preset_satisfaction: "Satisfaction (1–5)",
    Logic_PresetDesc_satisfaction: "Very dissatisfied to very satisfied",
    Logic_Preset_currency: "Currency",
    Logic_PresetDesc_currency: "A money amount",
    Logic_Preset_percent: "Percentage",
    Logic_PresetDesc_percent: "A percentage value",
    Logic_Template_blank_Name: "Blank form",
    Logic_Template_blank_Description: "Start from nothing",
    Logic_Template_feedback_Name: "Customer feedback",
    Logic_Template_feedback_Description: "NPS, ratings and open comments",
    Logic_Template_event_Name: "Event registration",
    Logic_Template_event_Description: "Attendee details, sessions and dietary needs",
    Logic_Template_itrequest_Name: "IT service request",
    Logic_Template_itrequest_Description: "Categorized requests with priority and attachments",
    Logic_Template_expense_Name: "Expense claim",
    Logic_Template_expense_Description: "Line items, receipts and a calculated total",
    Logic_Template_pulse_Name: "Employee pulse survey",
    Logic_Template_pulse_Description: "Likert grid, engagement scale and anonymity note",
    Logic_Template_safety_Name: "Safety inspection",
    Logic_Template_safety_Description: "Checklist, photos and a signature",
    Logic_Template_booking_Name: "Room or resource booking",
    Logic_Template_booking_Description: "Lookup-driven resource picker with a time slot",
    Charts_ColumnChartAria: "Column chart with {count} categories",
    Charts_DonutChartAria: "Donut chart of {count} categories",
    Charts_NoAnswers: "No answers yet.",
    Charts_NoResponses: "No responses yet.",
    Charts_Responses: "Responses",
    Charts_ResponsesOverTime: "Responses over time",
    Responses_Chart_Answer: "Answer",
    Responses_Chart_Average: "Average",
    Responses_Chart_AverageOf: "Average of {count}",
    Responses_Chart_AveragePosition: "Average position",
    Responses_Chart_AverageRange: "Average (1–{max})",
    Responses_Chart_AvgValue: "avg {value}",
    Responses_Chart_Detractors: "Detractors (0–6)",
    Responses_Chart_Max: "Max",
    Responses_Chart_Maximum: "Maximum",
    Responses_Chart_Median: "Median",
    Responses_Chart_MentionOne: "{count} mention",
    Responses_Chart_MentionOther: "{count} mentions",
    Responses_Chart_Min: "Min",
    Responses_Chart_Minimum: "Minimum",
    Responses_Chart_NoAnswers: "No answers yet.",
    Responses_Chart_NoNumeric: "No numeric answers yet.",
    Responses_Chart_NoRankings: "No rankings yet.",
    Responses_Chart_NoScores: "No scores yet.",
    Responses_Chart_NotEnoughText: "Not enough text to summarize yet.",
    Responses_Chart_NpsScore: "NPS score",
    Responses_Chart_Option: "Option",
    Responses_Chart_Passives: "Passives (7–8)",
    Responses_Chart_Promoters: "Promoters (9–10)",
    Responses_Chart_ResponseOne: "response",
    Responses_Chart_ResponseOther: "responses",
    Responses_Chart_Responses: "Responses",
    Responses_Chart_ShowingAnswers: "Showing {shown} of {total} answers.",
    Responses_Chart_Statement: "Statement",
    Responses_Chart_Statistic: "Statistic",
    Responses_Chart_StdDev: "Std dev",
    Responses_Chart_StdDeviation: "Std deviation",
    Responses_Chart_Total: "Total",
    Responses_Chart_Value: "Value",
    Responses_Dashboard_AllHidden: "Every question is hidden from the dashboard. Use “Show hidden questions” to bring them back.",
    Responses_Dashboard_AnsweredOf: "{answered} of {total} answered",
    Responses_Dashboard_AnsweredOfPinned: "{answered} of {total} answered · pinned",
    Responses_Dashboard_AveragedAcrossResponses: "Averaged across responses",
    Responses_Dashboard_ByDay: "By day",
    Responses_Dashboard_ByMonth: "By month",
    Responses_Dashboard_ByWeek: "By week",
    Responses_Dashboard_ChartAuto: "Automatic",
    Responses_Dashboard_ChartBars: "Bars",
    Responses_Dashboard_ChartColumns: "Columns",
    Responses_Dashboard_ChartDonut: "Donut",
    Responses_Dashboard_ChartGauge: "Gauge",
    Responses_Dashboard_ChartHistogram: "Histogram",
    Responses_Dashboard_ChartOptions: "Chart options",
    Responses_Dashboard_ChartOptionsFor: "Chart options for {title}",
    Responses_Dashboard_ChartStatistics: "Statistics",
    Responses_Dashboard_ChartTable: "Table",
    Responses_Dashboard_ChartWordFrequency: "Word frequency",
    Responses_Dashboard_EmptyBody: "Once people start answering, this dashboard fills in automatically — headline numbers, a response timeline, and a chart for the questions worth watching.",
    Responses_Dashboard_EmptyTitle: "No responses yet",
    Responses_Dashboard_Hide: "Hide from dashboard",
    Responses_Dashboard_Highlights: "Highlights",
    Responses_Dashboard_Last7Days: "Last 7 days",
    Responses_Dashboard_LatestDate: "Latest {date}",
    Responses_Dashboard_MedianTimeToComplete: "Median time to complete",
    Responses_Dashboard_NoPriorWeek: "No prior week to compare",
    Responses_Dashboard_OneEach: "One each",
    Responses_Dashboard_Pin: "Pin to dashboard",
    Responses_Dashboard_QuestionFallback: "question",
    Responses_Dashboard_QuestionsAnswered: "Questions answered",
    Responses_Dashboard_RecordedOnSubmit: "Recorded on submit",
    Responses_Dashboard_RepeatResponses: "{count} repeat responses",
    Responses_Dashboard_ResponsesOverTime: "Responses over time",
    Responses_Dashboard_ShowHidden: "Show hidden questions",
    Responses_Dashboard_SinceMidnight: "Since midnight",
    Responses_Dashboard_Today: "Today",
    Responses_Dashboard_TotalResponses: "Total responses",
    Responses_Dashboard_UniqueRespondents: "Unique respondents",
    Responses_Dashboard_Unpin: "Unpin from dashboard",
    Responses_Dashboard_UntitledQuestion: "Untitled question",
    Responses_Dashboard_VsPrevious7Days: "vs previous 7 days",
    Responses_Detail_Answers: "Answers",
    Responses_Detail_AsTheForm: "As the form",
    Responses_Detail_Cancel: "Cancel",
    Responses_Detail_Delete: "Delete",
    Responses_Detail_DeleteBody: "The list item moves to the site recycle bin, so it can be restored from there.",
    Responses_Detail_DeleteTitle: "Delete this response?",
    Responses_Detail_Deleting: "Deleting…",
    Responses_Detail_Draft: "Draft",
    Responses_Detail_Header: "Response {index} of {total}",
    Responses_Detail_LoadingAttachments: "Loading attachments…",
    Responses_Detail_Next: "Next response",
    Responses_Detail_NoAnswer: "No answer",
    Responses_Detail_Previous: "Previous response",
    Responses_Detail_Print: "Print",
    Responses_Detail_Signature: "Signature",
    Responses_Detail_Signed: "Signed",
    Responses_Detail_Took: "took {duration}",
    Responses_Summary_AnsweredOfType: "{answered} of {total} answered · {type}",
    Responses_Summary_ByField: "By {title}",
    Responses_Summary_CompareBy: "Compare by…",
    Responses_Summary_EmptyBody: "Every question will get its own summary here.",
    Responses_Summary_NoComparison: "No comparison",
    Responses_Summary_NothingToCompare: "No responses answered “{title}”, so there is nothing to compare.",
    Responses_Summary_OtherNote: "Charts with more than {max} categories group the smallest into “Other” — switch a card to Table to see every value.",
    Responses_Summary_ResponseCountOne: "{count} response",
    Responses_Summary_ResponseCountOther: "{count} responses",
    Responses_Summary_SeeAllAnswers: "See all answers in the table",
    Responses_Summary_SegmentNote: "Showing the {groups} largest groups. A response that selected several answers appears in every matching group, so group totals can add up to more than {total}.",
    Responses_Summary_SplitBy: "Split by {title}",
    Responses_Summary_Untitled: "untitled",
    Responses_Table_Apply: "Apply",
    Responses_Table_Cancel: "Cancel",
    Responses_Table_ClearSelection: "Clear selection",
    Responses_Table_ColumnOrder: "Column order",
    Responses_Table_ColumnsCount: "Columns ({shown}/{total})",
    Responses_Table_Delete: "Delete",
    Responses_Table_DeleteBody: "The list items move to the site recycle bin, so they can be restored from there.",
    Responses_Table_DeleteSelected: "Delete selected",
    Responses_Table_DeleteTitleOne: "Delete {count} response?",
    Responses_Table_DeleteTitleOther: "Delete {count} responses?",
    Responses_Table_Deleting: "Deleting…",
    Responses_Table_MoveDown: "Move down",
    Responses_Table_MoveDownFor: "Move {title} down",
    Responses_Table_MoveUp: "Move up",
    Responses_Table_MoveUpFor: "Move {title} up",
    Responses_Table_NoColumns: "No question columns are visible yet.",
    Responses_Table_NoMatch: "No responses match the current filters.",
    Responses_Table_NothingToShow: "Nothing to show",
    Responses_Table_OpenResponse: "Open this response",
    Responses_Table_OrderNote: "Submitted and Submitted by always come first. Drag order applies to the question columns.",
    Responses_Table_Reorder: "Reorder",
    Responses_Table_ResetColumns: "Reset columns",
    Responses_Table_SelectResponse: "Select this response",
    Responses_Table_SelectedOne: "{count} response selected",
    Responses_Table_SelectedOther: "{count} responses selected",
    Responses_Table_ShowAll: "Show all",
    Responses_Table_ShowTheseQuestions: "Show these questions",
    Responses_Table_Submitted: "Submitted",
    Responses_Table_SubmittedBy: "Submitted by",
    Responses_Table_ToggleSelection: "Toggle selection",
    Responses_Table_Unknown: "Unknown",
    Responses_Table_Untitled: "Untitled",
    Responses_View_AllTime: "All time",
    Responses_View_AnyAnswer: "Any answer",
    Responses_View_Clear: "Clear",
    Responses_View_CopyShareLink: "Copy share link",
    Responses_View_CountFiltered: "{shown} of {total} responses",
    Responses_View_CountOne: "{count} response",
    Responses_View_CountOther: "{count} responses",
    Responses_View_Dashboard: "Dashboard",
    Responses_View_DateRange: "Date range",
    Responses_View_EmptyBody: "Share the form to start collecting. Answers are saved to “{list}” and appear here straight away.",
    Responses_View_EmptyTitle: "No responses yet",
    Responses_View_ExportCsv: "Export CSV",
    Responses_View_FilterByAnswer: "Filter by answer",
    Responses_View_FilterByQuestion: "Filter by question",
    Responses_View_FilterValue: "Filter value",
    Responses_View_Last30Days: "Last 30 days",
    Responses_View_Last7Days: "Last 7 days",
    Responses_View_Last90Days: "Last 90 days",
    Responses_View_LoadError: "Responses could not be loaded. Publish the form once so the list columns exist, then try again.",
    Responses_View_Loading: "Loading responses…",
    Responses_View_MoreActions: "More response actions",
    Responses_View_PreviewForm: "Preview the form",
    Responses_View_Refresh: "Refresh",
    Responses_View_ResponsesTab: "Responses ({count})",
    Responses_View_SearchPlaceholder: "Search all answers",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Select a value",
    Responses_View_Summary: "Summary",
    Responses_View_Today: "Today",
    Responses_View_Truncated: "This list has more responses than Smart Forms loads at once. The newest {count} are shown — open the list in Microsoft Lists for the complete set.",
    Responses_View_TryAgain: "Try again",
    Responses_View_Untitled: "Untitled",
    Responses_Approval_Column: "Approval",
    Responses_Approval_ReviewerColumn: "Reviewed by",
    Responses_Approval_CommentColumn: "Reviewer comment",
    Responses_Approval_Pending: "Pending",
    Responses_Approval_Approved: "Approved",
    Responses_Approval_Rejected: "Rejected",
    Responses_Approval_AnyStatus: "Any approval status",
    Responses_Approval_FilterLabel: "Filter by approval status",
    Responses_Approval_ApproveSelected: "Approve selected",
    Responses_Approval_RejectSelected: "Reject selected",
    Responses_Approval_BulkFailed: "{count} responses could not be updated. Try again.",
    Responses_Approval_Approve: "Approve",
    Responses_Approval_Reject: "Reject",
    Responses_Approval_Reset: "Reset to pending",
    Responses_Approval_CommentLabel: "Comment (optional)",
    Responses_Approval_ReviewedBy: "Reviewed by {name}",
    Responses_Approval_Error: "The decision could not be saved. Try again.",
    Responses_Dashboard_ApprovalStatus: "Awaiting review",
    Responses_Dashboard_ApprovalBreakdown: "{pending} pending, {approved} approved, {rejected} rejected",
    Responses_Dashboard_TimelineCoarsened: "The date range is long, so the timeline was grouped more coarsely ({grain}).",
    Responses_Dashboard_TimelineTruncated: "The date range is very long, so only the most recent {count} periods are shown.",
    Service_Item_DefaultTitle: "Response — {date}",
    Service_Email_ApprovalSubject: "Your response was {status} — {title}",
    Service_Email_ApprovalHeading: "Your response was {status}",
    Service_Email_ApprovalIntro: "A reviewer marked your response to \"{title}\" as {status}.",
    Service_Email_ApprovalCommentLabel: "Reviewer comment",
    Service_Approval_Approved: "approved",
    Service_Approval_Rejected: "rejected",
    Service_Approval_Pending: "pending",
    Service_Lookup_InvalidFilter: "The lookup filter is not valid.",
    Service_Edit_NotAllowed: "This form does not allow editing a submitted response.",
    Service_Edit_NotYours: "You can only edit your own response.",
    Service_Signature_AttachmentLabel: "Signature",
    PropertyPane_ListsLoadFailed: "The lists on this site could not be loaded.",
    PropertyPane_EnterListName: "Enter a name for the new list first.",
    PropertyPane_CreatingList: "Creating \"{name}\"…",
    PropertyPane_ListCreated: "List \"{title}\" created and selected.",
    PropertyPane_ListAlreadyExists: "A list named \"{name}\" already exists — select it from the dropdown above.",
    PropertyPane_CreateListFailed: "Could not create the list. Check that you have permission to create lists on this site.",
    PropertyPane_Description: "Choose the SharePoint list that stores form responses, or create a new one. Everything else — questions, appearance, notifications — is edited directly on the page.",
    PropertyPane_ResponseList_GroupName: "Response list",
    PropertyPane_ListDropdown_Label: "Save responses to this list",
    PropertyPane_ResponsesGoTo: "Responses go to \"{name}\".",
    PropertyPane_PickList: "Pick a list, or create one below.",
    PropertyPane_LoadingLists: "Loading lists…",
    PropertyPane_NewListName_Label: "Or create a new list",
    PropertyPane_NewListName_Placeholder: "New list name",
    PropertyPane_CreateList_Button: "Create list",
    PropertyPane_Tips_GroupName: "Tips",
    PropertyPane_Tip_AutoSave: "Questions and settings save automatically as you edit them — no need to save or publish the page.",
    PropertyPane_Tip_Permissions: "Respondents need permission to add items to the response list. Check the list permissions if someone reports an error when submitting.",
    PropertyPane_Tip_Share: "Use \"Collect responses\" on the page to create the list columns and get a shareable fill-in link.",
    App_ErrorBoundary_Title: "Smart Forms — Render Error",
    App_ErrorBoundary_Message: "Message:",
    App_ErrorBoundary_Stack: "Stack:",
    App_ErrorBoundary_NoStack: "(no stack available)",
    App_ErrorBoundary_ConsoleNote: "Full details were also written to the browser console.",
    App_DefaultQuestionTitle: "Question {number}",
    App_Error_ListMissing: "The list configured for this form no longer exists. Pick another list in the web part settings.",
    App_Error_LoadConfig: "Something went wrong loading the form configuration.",
    App_Error_Unable: "Unable to load the form.",
    App_Publish_ConflictNotice: "\"{title}\" already has a list column of a different type ({type}). Rename the question so a new column can be created, or change its type back.",
    App_Publish_ConflictUnnamedQuestion: "a question",
    App_Publish_ColumnsAddedOne: "{count} column was added to \"{list}\".",
    App_Publish_ColumnsAddedOther: "{count} columns were added to \"{list}\".",
    App_Publish_TheList: "the list",
    App_Publish_UpToDate: "The response list is already up to date.",
    App_Publish_Error: "The list columns could not be created. This usually means you don't have Manage Lists permission on the response list, but it can also happen on sites with custom scripting disabled. Check the browser console for the underlying error, or try again.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Build a polished form on top of a SharePoint list — {count} question types, branching logic, file uploads, shareable fill-in links, and a results dashboard.",
    App_Placeholder_ChooseList: "Choose or create a list",
    App_Placeholder_Hint: "Edit the page and configure this web part to get started.",
    App_Loading: "Loading form…",
    App_OpenSettings: "Open settings",
    App_Tab_Questions: "Questions",
    App_Tab_QuestionsWithCount: "Questions ({count})",
    App_Tab_Responses: "Responses",
    App_Tab_Responses_Title: "Responses are saved to \"{list}\"",
    App_Templates_Start: "Start from a template",
    App_Settings_Title: "Form settings — appearance, notifications, access",
    App_Settings_AriaLabel: "Form settings",
    App_Preview: "Preview",
    App_Preview_Close: "Close preview",
    App_Preview_Hint: "Preview — nothing you submit here is saved. Validation and branching behave exactly as they will for respondents.",
    App_Publish_GettingReady: "Getting ready…",
    App_Publish_CollectResponses: "Collect responses",
    App_Publish_Share: "Share",
    App_Retry: "Retry",
    App_SaveError_Banner: "Your last change could not be saved. Check your connection, then try again.",
    App_Preflight_BlockingTitle: "Fix these before collecting",
    App_Preflight_WarningTitle: "Worth a look first",
    App_Preflight_BlockingText: "These would stop the published form working properly.",
    App_Preflight_WarningText: "Nothing is broken, but these are usually worth fixing before you share the link.",
    App_Preflight_GoTo: "Go to",
    App_Preflight_CollectAnyway: "Collect responses anyway",
    App_Preflight_Back: "Back to the form",
    App_Cancel: "Cancel",
    App_Done: "Done",
    App_Share_Title: "Your form is ready to share",
    App_Share_SubText: "Send this link to anyone who should fill in the form.",
    App_Share_LinkAriaLabel: "Share link",
    App_Share_Copy: "Copy",
    App_Share_Copied: "Copied",
    App_Share_AddItemsEmphasis: "add items",
    App_Share_PermissionNote: "Respondents need permission to {addItems} to “{title}”, and access to this page. If someone gets an error on submit, that is almost always why.",
    App_Share_PrefillNote: "You can pre-answer questions in the link by adding the column name, for example {example}.",
    App_Templates_ReplaceWarning: "Choosing a template replaces the questions you have now.",
    App_Templates_PickStart: "Pick a starting point — you can change anything afterwards.",
    App_Templates_Empty: "Empty",
    App_Templates_QuestionCount: "{count} questions",
    App_SaveChip_SavingTitle: "Saving your latest edit",
    App_SaveChip_Saving: "Saving…",
    App_SaveChip_FailedTitle: "Your last edit could not be saved. Check your connection and try again.",
    App_SaveChip_Failed: "Save failed",
    App_SaveChip_SavedTitle: "All changes are saved",
    App_SaveChip_Saved: "Saved",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "New response — {title}",
    Service_Email_NewResponseHeading: "New response: {title}",
    Service_Email_NewResponseIntro: "Someone just submitted a response — {date}.",
    Service_Email_ReceiptSubject: "Your response — {title}",
    Service_Email_ReceiptHeading: "Thanks for your response!",
    Service_Email_ReceiptIntro: "Here is a copy of what you submitted to \"{title}\".",
    App_History_Title: "Version history",
    App_History_RestoredNotice: "Restored the version saved {date}. Review it, then use Collect responses to publish any new questions.",
    App_History_Undo: "Undo restore",
    App_Share_CopyManual: "Your browser blocked copying. Select the link above and press Ctrl+C (Cmd+C on a Mac) to copy it.",
    App_Share_TeamsNote: "You are in Microsoft Teams. This link opens the SharePoint page directly, so recipients need access to the site.",
    App_Share_PrefillNotSecure: "Prefilled answers are a convenience only: anyone with the link can change them, so never treat them as a security boundary.",
    Designer_Section_DropHere: "Drop a question here",
    Designer_Section_DropEnd: "Drop here to move to the end of this section",
    Designer_Rules_RemovedOne: "1 branching rule that no longer fit was removed.",
    Designer_Rules_RemovedOther: "{count} branching rules that no longer fit were removed.",
    Designer_Settings_AllowEdit: "Allow respondents to edit their response",
    Designer_Settings_AllowEditHint: "Respondents can reopen and update what they submitted. Each person can edit only their own response.",
    Designer_Settings_EnableApproval: "Enable approval workflow",
    Designer_Settings_ApprovalNotify: "Email respondent on decision",
    Designer_Settings_ApprovalHint: "Adds approval columns to the response list the next time you publish. Owners approve or reject responses from the Responses tab.",
    Designer_History_Title: "Version history",
    Designer_History_Intro: "Earlier saved versions of this form's questions and settings. Restoring loads a version into the designer; you can undo it, and new questions are only created when you publish.",
    Designer_History_Loading: "Loading versions...",
    Designer_History_Empty: "No earlier versions were found. Version history needs versioning turned on for the \"Smart Forms Config\" list and at least one saved edit.",
    Designer_History_Latest: "Latest",
    Designer_History_LatestTitle: "This is the version currently in use",
    Designer_History_By: "by {name}",
    Designer_History_UnknownAuthor: "Unknown author",
    Designer_History_VersionLabel: "version {label}",
    Designer_History_Preview: "Preview",
    Designer_History_Restore: "Restore",
    Designer_History_QuestionsOne: "1 question",
    Designer_History_QuestionsOther: "{count} questions",
    Designer_History_LoadFailed: "This version could not be loaded.",
    Designer_History_ConfirmTitle: "Restore this version?",
    Designer_History_ConfirmText: "The form will be replaced with the version saved {date} ({count} questions). You can undo this right after."
  };
});
