define([], function () {
  return {
    Designer_Color_Blue: "Azul",
    Designer_Color_Teal: "Verde azulado",
    Designer_Color_Green: "Verde",
    Designer_Color_Purple: "Morado",
    Designer_Color_Magenta: "Magenta",
    Designer_Color_Red: "Rojo",
    Designer_Color_Orange: "Naranja",
    Designer_Color_Gray: "Gris",
    Designer_Settings_LayoutSinglePage: "Todas las preguntas en una página",
    Designer_Settings_LayoutWizard: "Una sección por paso (asistente)",
    Designer_Settings_Title: "Configuración del formulario",
    Designer_Common_Apply: "Aplicar",
    Designer_Common_Cancel: "Cancelar",
    Designer_Settings_TabBasics: "Básico",
    Designer_Settings_FormTitle: "Título del formulario",
    Designer_Settings_Description: "Descripción",
    Designer_Settings_Layout: "Diseño",
    Designer_Settings_NumberQuestions: "Numerar las preguntas",
    Designer_Settings_ShuffleQuestions: "Mezclar el orden de las preguntas para cada encuestado",
    Designer_Settings_ShowProgressBar: "Mostrar una barra de progreso",
    Designer_Settings_TabAppearance: "Apariencia",
    Designer_Settings_AccentColor: "Color de énfasis",
    Designer_Settings_CustomColorTitle: "Color personalizado",
    Designer_Settings_CustomColorAria: "Color de énfasis personalizado",
    Designer_Settings_AccentHint: "Los colores de énfasis se ajustan automáticamente para lograr contraste en sitios oscuros, de modo que el formulario siga siendo legible con cualquier tema de la página.",
    Designer_Settings_ShowHeader: "Mostrar el encabezado del formulario",
    Designer_Settings_HeaderIcon: "Icono del encabezado",
    Designer_Settings_TabAfterSubmit: "Después del envío",
    Designer_Settings_SubmitButtonText: "Texto del botón Enviar",
    Designer_Settings_SubmitPlaceholder: "Enviar",
    Designer_Settings_ThankYouTitle: "Título del agradecimiento",
    Designer_Settings_ThankYouPlaceholder: "¡Gracias!",
    Designer_Settings_ThankYouMessage: "Mensaje de agradecimiento",
    Designer_Settings_ShowSubmitAnother: "Mostrar un botón \"Enviar otra respuesta\"",
    Designer_Settings_TabNotifications: "Notificaciones",
    Designer_Settings_EmailEachResponseTo: "Enviar cada respuesta por correo a",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "Las personas de su organización reciben cada respuesta por correo, con un vínculo al elemento de la lista",
    Designer_Settings_RespondentReceipt: "Enviar a los encuestados una copia de sus respuestas por correo",
    Designer_Settings_NotificationsInfo: "Las notificaciones usan el servicio de correo propio de SharePoint, por lo que los destinatarios deben ser usuarios de su organización. Las direcciones externas se descartan sin aviso.",
    Designer_Settings_TabAccess: "Acceso",
    Designer_Settings_OpenFrom: "Abrir desde",
    Designer_Settings_OpenImmediately: "Abrir inmediatamente",
    Designer_Settings_CloseAfter: "Cerrar después de",
    Designer_Settings_NeverClose: "No cerrar nunca",
    Designer_Settings_ClearDates: "Borrar fechas",
    Designer_Settings_DatesInverted: "La fecha de cierre es igual o anterior a la fecha de apertura, por lo que el formulario nunca aceptaría respuestas.",
    Designer_Settings_MaxResponses: "Detener después de este número de respuestas",
    Designer_Settings_NoLimit: "Sin límite",
    Designer_Settings_OneResponsePerPerson: "Permitir solo una respuesta por persona",
    Designer_Settings_AllowSaveDraft: "Permitir a los encuestados guardar un borrador y terminar más tarde",
    Designer_Settings_ClosedMessage: "Mensaje que se muestra cuando el formulario está cerrado",
    Designer_Settings_ClosedMessagePlaceholder: "Este formulario ya no acepta respuestas.",
    Designer_Settings_AccessInfo: "Estos límites los aplica el formulario, no SharePoint. Cualquier persona con permiso para agregar elementos a la lista de respuestas podría seguir agregando uno directamente desde la lista.",
    Designer_Field_StyleInfo: "Información (énfasis)",
    Designer_Field_StyleSuccess: "Correcto (verde)",
    Designer_Field_StyleWarning: "Advertencia (ámbar)",
    Designer_Field_StylePlain: "Texto sin formato",
    Designer_Field_StyleDivider: "Línea divisoria",
    Designer_Field_IconStars: "Estrellas",
    Designer_Field_IconHearts: "Corazones",
    Designer_Field_IconThumbs: "Pulgar hacia arriba",
    Designer_Field_FormatPlain: "Número sin formato",
    Designer_Field_FormatCurrency: "Moneda",
    Designer_Field_FormatPercent: "Porcentaje",
    Designer_Field_UntitledQuestion: "Pregunta sin título",
    Designer_Field_DeletedQuestion: "una pregunta eliminada",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} y {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "O",
    Designer_Rule_JoinAll: "Y",
    Designer_Rule_Preview: "Se muestra cuando {conditions}.",
    Designer_Field_Yes: "Sí",
    Designer_Field_No: "No",
    Designer_Field_When: "Cuando",
    Designer_Field_SelectValue: "Seleccione un valor",
    Designer_Field_DateValuePlaceholder: "AAAA-MM-DD o \"today\"",
    Designer_Field_ValuePlaceholder: "Valor",
    Designer_Field_UpperBound: "Límite superior",
    Designer_Field_RemoveCondition: "Quitar esta condición",
    Designer_Field_FormulaInvalid: "No se puede calcular esta fórmula. Compruebe los paréntesis y los operadores.",
    Designer_Field_FormulaMissing: "Estas preguntas no existen: {names}.",
    Designer_Field_FormulaPreview: "Con todas las entradas en 10, se muestra {value}.",
    Designer_Field_HintYesNo: "Use \"yes\" o \"no\"",
    Designer_Field_HintMultiDefault: "Separe varios valores predeterminados con ;",
    Designer_Field_HintSingleDefault: "Debe coincidir con una de las opciones",
    Designer_Field_HintDate: "Use \"today\" o una fecha como 2026-03-01",
    Designer_Field_HintTime: "Use \"now\" o una hora como 09:30",
    Designer_Field_QuestionSettings: "Configuración de la pregunta",
    Designer_Field_Appearance: "Apariencia",
    Designer_Field_Style: "Estilo",
    Designer_Field_ImageUrl: "URL de la imagen (opcional)",
    Designer_Field_Content: "Contenido",
    Designer_Field_BasicFormatting: "Se permite el formato básico: negrita, cursiva, listas y vínculos.",
    Designer_Field_TabOptions: "Opciones",
    Designer_Field_TabBranching: "Ramificación",
    Designer_Field_BranchingNeedsQuestion: "Agregue primero otra pregunta: la ramificación necesita algo de lo que depender.",
    Designer_Field_BranchingToggle: "Mostrar esta pregunta solo cuando otras respuestas coincidan",
    Designer_Field_Match: "Coincidir con",
    Designer_Field_MatchAll: "todas estas",
    Designer_Field_MatchAny: "cualquiera de estas",
    Designer_Field_AddCondition: "Agregar condición",
    Designer_Field_TabValidation: "Validación",
    Designer_Field_HelpText: "Texto de ayuda",
    Designer_Field_HelpTextPlaceholder: "Se muestra debajo de la etiqueta de la pregunta",
    Designer_Field_CheckboxLabel: "Etiqueta de la casilla",
    Designer_Field_Placeholder: "Marcador de posición",
    Designer_Field_DefaultAnswer: "Respuesta predeterminada",
    Designer_Field_RequiredMessage: "Mensaje de obligatoriedad personalizado",
    Designer_Field_RequiredMessagePlaceholder: "{title} es obligatorio",
    Designer_Field_ThisQuestion: "Esta pregunta",
    Designer_Field_RequiredMessageDescription: "Se muestra en lugar del mensaje estándar cuando esta pregunta se deja en blanco",
    Designer_Field_ReadOnly: "Solo lectura (la respuesta solo puede proceder de un vínculo rellenado previamente)",
    Designer_Field_ValidationRules: "Reglas de validación",
    Designer_Field_MaxLength: "Longitud máxima",
    Designer_Field_Pattern: "Debe coincidir con este patrón",
    Designer_Field_PatternDescription: "Una expresión regular. Déjelo en blanco para no comprobar ningún patrón.",
    Designer_Field_PatternMessage: "Mensaje cuando el patrón no coincide",
    Designer_Field_PatternMessagePlaceholder: "Esta respuesta no tiene el formato esperado",
    Designer_Field_Format: "Formato",
    Designer_Field_UnitSuffix: "Unidad que se muestra después del valor",
    Designer_Field_UnitSuffixPlaceholder: "kg, h, artículos…",
    Designer_Field_Minimum: "Mínimo",
    Designer_Field_Maximum: "Máximo",
    Designer_Field_Decimals: "Decimales",
    Designer_Field_Formula: "Fórmula",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Haga referencia a otras preguntas por su texto entre llaves. Admite + - * / ( ) y round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Preguntas disponibles: {questions}",
    Designer_Field_NoneYet: "ninguna todavía",
    Designer_Field_Step: "Paso",
    Designer_Field_From: "Desde",
    Designer_Field_To: "Hasta",
    Designer_Field_LowLabel: "Etiqueta del extremo inferior",
    Designer_Field_LowLabelPlaceholder: "Nada probable",
    Designer_Field_HighLabel: "Etiqueta del extremo superior",
    Designer_Field_HighLabelPlaceholder: "Extremadamente probable",
    Designer_Field_SummarizeAs: "Resumir como",
    Designer_Field_SummarizeAverage: "Promedio y distribución",
    Designer_Field_SummarizeNps: "Net Promoter Score (requiere una escala de 0–10)",
    Designer_Field_NpsWarning: "El Net Promoter Score solo es significativo en una escala de 0–10. Establezca Desde en 0 y Hasta en 10.",
    Designer_Field_NumberOfIcons: "Número de iconos",
    Designer_Field_Icon: "Icono",
    Designer_Field_AllowHalf: "Permitir valores intermedios",
    Designer_Field_ShowOptionsAs: "Mostrar las opciones como",
    Designer_Field_DisplayButtons: "Botones en línea",
    Designer_Field_DisplayDropdown: "Lista desplegable",
    Designer_Field_DisplayAutomatic: "Automático (en línea hasta 6 opciones)",
    Designer_Field_AllowOther: "Agregar una opción \"Otro\" de texto libre",
    Designer_Field_OtherLabel: "Etiqueta de la opción \"Otro\"",
    Designer_Field_OtherPlaceholder: "Otro",
    Designer_Field_ShuffleOptions: "Mezclar el orden de las opciones para cada encuestado",
    Designer_Field_MinSelections: "Selecciones mínimas",
    Designer_Field_MaxSelections: "Selecciones máximas",
    Designer_Field_SourceList: "Lista de origen",
    Designer_Field_ChooseList: "Elija una lista",
    Designer_Field_LookupColumn: "Columna de la que leer las opciones",
    Designer_Field_ChooseColumn: "Elija una columna",
    Designer_Field_ChooseListFirst: "Elija primero una lista",
    Designer_Field_LookupFilter: "Filtro (opcional)",
    Designer_Field_LookupFilterDescription: "Un filtro OData que limita qué elementos de origen se convierten en opciones",
    Designer_Field_LookupInfo: "Las respuestas almacenan el texto de la opción, no un vínculo al elemento de origen, por lo que siguen siendo legibles aunque la lista de origen cambie más adelante.",
    Designer_Field_ConsentText: "Términos que se muestran sobre la casilla",
    Designer_Field_AllowMultiplePeople: "Permitir varias personas",
    Designer_Field_AllowGroups: "Permitir también grupos",
    Designer_Field_IncludeTime: "Incluir una hora del día",
    Designer_Field_TimeStep: "Intervalo de tiempo (minutos)",
    Designer_Field_MaxFiles: "Máximo de archivos",
    Designer_Field_MaxFileSize: "Tamaño máx. de cada uno (MB)",
    Designer_Field_AcceptedTypes: "Tipos de archivo aceptados",
    Designer_Field_AcceptedTypesDescription: "Extensiones separadas por comas. Déjelo en blanco para aceptar todo lo que SharePoint permita.",
    Designer_Field_FilesInfo: "Los archivos se guardan como datos adjuntos del elemento de respuesta. SharePoint bloquea algunas extensiones (como .exe) independientemente de lo que permita aquí.",
    Designer_Field_Rows: "Filas",
    Designer_Field_ProvisionedNote: "Esta pregunta ya tiene una columna de lista ({name}). La configuración que cambia el tipo de la columna está bloqueada; duplique la pregunta si necesita un tipo diferente.",
    Designer_Category_Text: "Texto",
    Designer_Category_Choice: "Elección",
    Designer_Category_Scales: "Escalas",
    Designer_Category_Date: "Fecha",
    Designer_Category_People: "Personas",
    Designer_Category_Advanced: "Avanzado",
    Designer_Category_Layout: "Diseño",
    Designer_Menu_CommonPresets: "Valores preestablecidos comunes",
    Designer_Menu_AllTypes: "Todos los tipos de pregunta",
    Designer_Menu_ChangeType: "Cambiar tipo",
    Designer_Menu_TypeLockedTitle: "La columna de la lista ya existe, por lo que el tipo está bloqueado. Duplique la pregunta para cambiarlo.",
    Designer_Menu_MoreSettings: "Ramificación, validación y más",
    Designer_Menu_InsertBelow: "Insertar pregunta debajo",
    Designer_Card_Duplicate: "Duplicar",
    Designer_Card_DeleteQuestion: "Eliminar pregunta",
    Designer_Outline_Aria: "Esquema de preguntas",
    Designer_Outline_QuestionCountOne: "{count} pregunta",
    Designer_Outline_QuestionCountOther: "{count} preguntas",
    Designer_Outline_IssuesTitle: "{count} problema(s) por revisar",
    Designer_Outline_Find: "Buscar una pregunta",
    Designer_Outline_Empty: "Aún no hay preguntas.",
    Designer_Section_DefaultTitle: "Sección {number}",
    Designer_Card_Question: "Pregunta",
    Designer_Card_BranchingTitle: "Esta pregunta solo aparece cuando coincide una regla de ramificación",
    Designer_Card_BranchingChip: "Ramificación",
    Designer_Card_LiveTitle: "La columna de la lista existe, por lo que el tipo está bloqueado",
    Designer_Card_LiveChip: "Activa",
    Designer_Card_CheckChip: "Revisar",
    Designer_Option_Placeholder: "Opción {number}",
    Designer_Option_LabelAria: "Etiqueta de la opción {number}",
    Designer_Option_ImageUrl: "URL de la imagen",
    Designer_Option_ImageUrlAria: "URL de la imagen de la opción {number}",
    Designer_Option_Remove: "Quitar opción",
    Designer_Option_RemoveAria: "Quitar la opción {number}",
    Designer_Option_Add: "Agregar opción",
    Designer_Option_OtherHint: "Los encuestados también pueden escribir una respuesta con la etiqueta “{label}”.",
    Designer_Option_OtherFallback: "Otro",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Quitar",
    Designer_Grid_RemoveAria: "Quitar {label} {number}",
    Designer_Grid_Statements: "Afirmaciones",
    Designer_Grid_Scale: "Escala",
    Designer_Grid_AddStatement: "Agregar afirmación",
    Designer_Grid_AddScale: "Agregar escala",
    Designer_Width_Full: "Ancho completo",
    Designer_Width_Half: "Medio ancho",
    Designer_Width_Third: "Un tercio del ancho",
    Designer_Width_Aria: "Ancho de la pregunta",
    Designer_Card_BlockLabelPlaceholder: "Etiqueta del bloque (no se muestra a los encuestados)",
    Designer_Card_QuestionText: "Texto de la pregunta",
    Designer_Card_MoveUp: "Subir",
    Designer_Card_MoveQuestionUp: "Subir pregunta",
    Designer_Card_MoveDown: "Bajar",
    Designer_Card_MoveQuestionDown: "Bajar pregunta",
    Designer_Card_DuplicateQuestion: "Duplicar pregunta",
    Designer_Card_MultipleAnswers: "Varias respuestas",
    Designer_Card_Required: "Obligatoria",
    Designer_Card_MoreOptions: "Más opciones",
    Designer_Card_MoreOptionsAria: "Más opciones para esta pregunta",
    Designer_Canvas_FormTitle: "Título del formulario",
    Designer_Canvas_DescriptionPlaceholder: "Agregar una descripción (opcional)",
    Designer_Canvas_DescriptionAria: "Descripción del formulario",
    Designer_Canvas_EmptyTitle: "Agregue su primera pregunta",
    Designer_Canvas_EmptyBody: "Elija un tipo de pregunta para empezar. Puede reordenar las preguntas arrastrándolas y agregar ramificación para que cada persona vea solo lo que le corresponde.",
    Designer_Section_Chip: "Sección {number} de {total}",
    Designer_Section_TitlePlaceholder: "Título de la sección",
    Designer_Section_TitleAria: "Título de la sección {number}",
    Designer_Section_DescriptionPlaceholder: "Descripción (opcional)",
    Designer_Section_DescriptionAria: "Descripción de la sección {number}",
    Designer_Section_MoveUp: "Subir sección",
    Designer_Section_MoveDown: "Bajar sección",
    Designer_Section_Delete: "Eliminar sección",
    Designer_Card_DragToReorder: "Arrastre para reordenar",
    Designer_Card_ReorderAria: "Reordenar {title}",
    Designer_Card_ReorderFallback: "pregunta",
    Designer_Canvas_AddNew: "Agregar nuevo",
    Designer_Canvas_AddSection: "Agregar sección",
    Form_Address_AriaWithLabel: "{label}: {part}",
    Form_Address_StreetPlaceholder: "Dirección",
    Form_Address_Street2Placeholder: "Apartamento, piso, etc. (opcional)",
    Form_Address_CityPlaceholder: "Ciudad",
    Form_Address_StatePlaceholder: "Provincia / región",
    Form_Address_PostalCodePlaceholder: "Código postal",
    Form_Address_CountryPlaceholder: "País",
    Form_Address_StreetAria: "dirección",
    Form_Address_Street2Aria: "línea de dirección 2",
    Form_Address_CityAria: "ciudad",
    Form_Address_StateAria: "provincia o región",
    Form_Address_PostalCodeAria: "código postal",
    Form_Address_CountryAria: "país",
    Form_Consent_DefaultLabel: "Acepto",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered} de {total} filas respondidas",
    Form_Lookup_LoadError: "No se pudieron cargar las opciones de esta pregunta.",
    Form_Lookup_Loading: "Cargando opciones…",
    Form_Lookup_SelectOptionsPlaceholder: "Seleccione opciones",
    Form_Lookup_SelectOptionPlaceholder: "Seleccione una opción",
    Form_Person_Placeholder: "Empiece a escribir un nombre…",
    Form_Person_SuggestedPeopleAndGroups: "Personas y grupos sugeridos",
    Form_Person_SuggestedPeople: "Personas sugeridas",
    Form_Person_NoPeopleOrGroups: "No se encontraron personas ni grupos",
    Form_Person_NoPeople: "No se encontraron personas",
    Form_Person_Searching: "Buscando…",
    Form_Ranking_Moved: "{item} movido a la posición {position} de {total}",
    Form_Ranking_MoveUp: "Subir",
    Form_Ranking_MoveDown: "Bajar",
    Form_Ranking_MoveItemUpAria: "Subir {item}",
    Form_Ranking_MoveItemDownAria: "Bajar {item}",
    Form_Rating_ValueText: "{value} de {max}",
    Form_Rating_NotRated: "Sin valorar",
    Form_Rating_Clear: "Borrar valoración",
    Form_RichText_Bold: "Negrita",
    Form_RichText_Italic: "Cursiva",
    Form_RichText_Underline: "Subrayado",
    Form_RichText_BulletedList: "Lista con viñetas",
    Form_RichText_NumberedList: "Lista numerada",
    Form_RichText_ClearFormatting: "Borrar formato",
    Form_RichText_ToolbarAria: "Formato de texto",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "Se omitió \"{name}\": el límite es {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" no es un tipo aceptado.",
    Form_File_TooLarge: "\"{name}\" supera los {size} MB.",
    Form_File_AlreadyAttached: "\"{name}\" ya está adjunto.",
    Form_File_ReadError: "No se pudo leer uno de los archivos. Intente adjuntarlo de nuevo.",
    Form_File_HintMaxSize: "hasta {size} MB cada uno",
    Form_File_HintOneFile: "1 archivo",
    Form_File_HintMaxFiles: "máx. {count} archivos",
    Form_File_Reading: "Leyendo archivos…",
    Form_File_DropPrompt: "Suelte los archivos aquí o haga clic para examinar",
    Form_File_Remove: "Quitar {name}",
    Form_Signature_Alt: "Firma",
    Form_Signature_AriaSigned: "{label}: firmado",
    Form_Signature_AriaEmpty: "{label}: vacío",
    Form_Signature_Clear: "Borrar",
    Form_Signature_Signed: "Firmado",
    Form_Signature_Prompt: "Firme arriba con el mouse, un lápiz o el dedo",
    Form_Time_Placeholder: "Seleccione una hora",
    Form_Field_DatePlaceholder: "Seleccione una fecha",
    Form_Field_TimeAriaWithLabel: "{label}: hora",
    Form_Field_TimeAria: "Hora",
    Form_Field_OtherDefault: "Otro",
    Form_Field_SelectOptionsPlaceholder: "Seleccione opciones",
    Form_Field_PleaseSpecify: "Especifique",
    Form_Field_OtherSpecifyAria: "{label}: especifique",
    Form_Field_SelectOptionPlaceholder: "Seleccione una opción",
    Form_Field_Yes: "Sí",
    Form_Field_No: "No",
    Form_Field_SliderHint: "Arrastre el control deslizante para responder",
    Form_Field_WebAddressAriaWithLabel: "{label}: dirección web",
    Form_Field_WebAddressAria: "Dirección web",
    Form_Field_DisplayTextPlaceholder: "Texto para mostrar (opcional)",
    Form_Field_DisplayTextAriaWithLabel: "{label}: texto para mostrar",
    Form_Field_DisplayTextAria: "Texto para mostrar",
    Form_Field_ChooseBetween: "Elija entre {min} y {max}",
    Form_Field_ChooseAtLeast: "Elija al menos {min}",
    Form_Field_ChooseUpTo: "Elija hasta {max}",
    Form_Field_SelectedCount: "{count} seleccionados",
    Form_Field_RequiredAria: "(obligatorio)",
    Form_Submit_SaveError: "No se pudo guardar su respuesta. Asegúrese de que el formulario se haya publicado desde el diseñador y de que tenga permiso para agregar elementos a la lista de respuestas.",
    Form_Empty_Message: "Este formulario aún no tiene preguntas. El propietario del formulario puede agregarlas en la pestaña Preguntas.",
    Form_Checking: "Comprobando el formulario…",
    Form_Closed_NotYetOpen: "Aún no está abierto",
    Form_Closed_AlreadyAnswered: "Ya respondido",
    Form_Closed_Title: "Formulario cerrado",
    Form_Confirmation_PreviewNotice: "Esto era una vista previa: no se guardó nada en la lista de respuestas.",
    Form_Confirmation_PreviewAgain: "Volver a previsualizar",
    Form_Confirmation_SubmitAnother: "Enviar otra respuesta",
    Form_Wizard_StepFallback: "Paso {step}",
    Form_Wizard_StepsAria: "Pasos del formulario",
    Form_Wizard_StepOf: "Paso {step} de {total}",
    Form_ErrorSummary_Title: "Revise {count} respuestas:",
    Form_ErrorSummary_UntitledQuestion: "Pregunta sin título",
    Form_ErrorSummary_Question: "Pregunta",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Atrás",
    Form_Nav_Next: "Siguiente",
    Form_Draft_Saving: "Guardando…",
    Form_Draft_Saved: "Borrador guardado",
    Form_Draft_SaveAndFinishLater: "Guardar y terminar más tarde",
    Form_Draft_NotSaved: "Borrador sin guardar",
    Form_Submit_Preview: "Enviar (vista previa)",
    Form_Submit_Button: "Enviar",
    Form_Response_NoAnswer: "Sin respuesta",
    Form_Signature_TypeLabel: "Escriba su nombre completo",
    Form_Signature_TypeInstead: "Escribir el nombre en su lugar",
    Form_Signature_DrawInstead: "Dibujar en su lugar",
    Form_Edit_Button: "Editar su respuesta anterior",
    Form_Edit_Available: "Ya ha enviado una respuesta. Puede editarla en lugar de enviar una nueva.",
    Form_Edit_Banner: "Está editando su respuesta anterior.",
    Form_Edit_Save: "Actualizar respuesta",
    Form_Edit_UpdatedTitle: "Respuesta actualizada",
    Form_Edit_UpdatedMessage: "Se han guardado los cambios.",
    Form_Edit_LoadError: "No se pudo cargar su respuesta anterior. Inténtelo de nuevo.",
    Form_Draft_MissingFiles: "Vuelva a adjuntar: {names}. No se pudieron restaurar estos archivos.",
    Form_Attachments_Failed: "Sus respuestas se guardaron, pero no se pudieron cargar estos datos adjuntos: {names}. Inténtelo de nuevo o póngase en contacto con el propietario del formulario.",
    Logic_ThisQuestion: "Esta pregunta",
    Logic_Required: "{label} es obligatorio",
    Logic_RequiredConsent: "Marque la casilla para continuar",
    Logic_RequiredFile: "Adjunte al menos un archivo",
    Logic_RequiredSignature: "Agregue su firma",
    Logic_RequiredLikert: "Responda a todas las filas",
    Logic_InvalidEmail: "Escriba una dirección de correo electrónico válida",
    Logic_InvalidPhone: "Escriba un número de teléfono válido",
    Logic_InvalidUrl: "Escriba una dirección web válida que empiece por http:// o https://",
    Logic_MinValue: "El valor debe ser como mínimo {value}",
    Logic_MaxValue: "El valor debe ser como máximo {value}",
    Logic_MaxLength: "La longitud máxima es de {max} caracteres",
    Logic_ChooseAtLeastOne: "Elija al menos {count} opción",
    Logic_ChooseAtLeastMany: "Elija al menos {count} opciones",
    Logic_ChooseAtMostOne: "No elija más de {count} opción",
    Logic_ChooseAtMostMany: "No elija más de {count} opciones",
    Logic_LikertRemaining: "Responda a todas las filas (faltan {count})",
    Logic_MaxFilesOne: "No adjunte más de {count} archivo",
    Logic_MaxFilesMany: "No adjunte más de {count} archivos",
    Logic_FileTooLarge: "\"{name}\" supera los {size} MB",
    Logic_FileTypeNotAccepted: "\"{name}\" no es un tipo de archivo admitido ({types})",
    Logic_AddressRequired: "Escriba al menos una calle y una ciudad",
    Logic_PatternDefault: "Esta respuesta no tiene el formato esperado",
    Logic_Yes: "Sí",
    Logic_No: "No",
    Logic_Agreed: "Aceptado",
    Logic_NotAgreed: "No aceptado",
    Logic_Signed: "Firmado",
    Logic_NoAnswer: "(sin respuesta)",
    Logic_Unknown: "(desconocido)",
    Logic_OtherSlice: "Otros ({count})",
    Logic_CsvResponseId: "Id. de respuesta",
    Logic_CsvSubmitted: "Enviado",
    Logic_CsvSubmittedBy: "Enviado por",
    Logic_EmailQuestion: "Pregunta",
    Logic_EmailViewItem: "Ver en Microsoft Lists",
    Logic_EmailFooter: "Enviado automáticamente por Smart Forms.",
    Logic_ClosedDefault: "Este formulario ya no acepta respuestas.",
    Logic_NotYetOpen: "Este formulario se abre el {date}.",
    Logic_AlreadyResponded: "Ya ha respondido a este formulario. ¡Gracias!",
    Logic_UntitledQuestion: "Una pregunta sin título",
    Logic_Issue_NoQuestions: "Agregue al menos una pregunta antes de recopilar respuestas.",
    Logic_Issue_NoTitle: "Una pregunta no tiene texto: se le asignará un nombre automáticamente al publicar.",
    Logic_Issue_DuplicateTitle: "{label} tiene el mismo texto que otra pregunta, lo que dificulta la lectura de los resultados.",
    Logic_Issue_NeedTwoOptions: "{label} necesita al menos dos opciones.",
    Logic_Issue_ImageNoImage: "{label} tiene opciones sin imagen: se mostrarán como mosaicos de texto.",
    Logic_Issue_LikertNeedRow: "{label} necesita al menos una fila.",
    Logic_Issue_LikertNeedColumns: "{label} necesita al menos dos columnas de escala.",
    Logic_Issue_NoLookupList: "{label} no tiene ninguna lista de origen seleccionada.",
    Logic_Issue_NoFormula: "{label} no tiene fórmula.",
    Logic_Issue_BadFormula: "{label} tiene una fórmula que no se puede calcular. Compruebe los paréntesis y los operadores.",
    Logic_Issue_MissingRefs: "{label} hace referencia a preguntas que no existen: {names}.",
    Logic_Issue_BadPattern: "{label} tiene un patrón de validación no válido.",
    Logic_Issue_BrokenRule: "{label} tiene una regla de bifurcación que apunta a una pregunta eliminada.",
    Logic_Issue_SelfRule: "{label} tiene una regla de bifurcación que hace referencia a sí misma.",
    Logic_Issue_RuleMismatch: "{label} tiene una regla de bifurcación que ya no se ajusta a la pregunta de la que depende.",
    Logic_Issue_RequiredReadOnly: "{label} es obligatorio y de solo lectura a la vez, por lo que solo se puede responder mediante un vínculo rellenado previamente.",
    Logic_Issue_EmptySection: "Una sección no tiene preguntas y se omitirá.",
    Logic_Issue_CloseBeforeOpen: "La fecha de cierre es igual o anterior a la de apertura, por lo que el formulario nunca aceptará respuestas.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Los correos de aprobación están activados, pero el paso de aprobación está desactivado.",
    Logic_Op_equals: "es",
    Logic_Op_notEquals: "no es",
    Logic_Op_contains: "contiene",
    Logic_Op_notContains: "no contiene",
    Logic_Op_notEmpty: "está respondido",
    Logic_Op_empty: "no está respondido",
    Logic_Op_greaterThan: "es mayor que",
    Logic_Op_greaterOrEqual: "es como mínimo",
    Logic_Op_lessThan: "es menor que",
    Logic_Op_lessOrEqual: "es como máximo",
    Logic_Op_between: "está entre",
    Logic_Op_before: "es anterior a",
    Logic_Op_after: "es posterior a",
    Logic_Type_Text: "Respuesta corta",
    Logic_TypeDesc_Text: "Una sola línea de texto",
    Logic_Category_Text: "Texto",
    Logic_Type_MultilineText: "Respuesta larga",
    Logic_TypeDesc_MultilineText: "Varias líneas de texto sin formato",
    Logic_Type_RichText: "Texto con formato",
    Logic_TypeDesc_RichText: "Negrita, listas y vínculos",
    Logic_Type_Choice: "Opción",
    Logic_TypeDesc_Choice: "Elegir entre una lista de opciones",
    Logic_Category_Choice: "Opción",
    Logic_Type_ImageChoice: "Opción de imagen",
    Logic_TypeDesc_ImageChoice: "Elegir entre mosaicos de imágenes",
    Logic_Type_Lookup: "Búsqueda en una lista",
    Logic_TypeDesc_Lookup: "Las opciones se leen en tiempo real de otra lista de SharePoint",
    Logic_Type_YesNo: "Sí / No",
    Logic_TypeDesc_YesNo: "Un interruptor sencillo de activado/desactivado",
    Logic_Type_Consent: "Consentimiento",
    Logic_TypeDesc_Consent: "Una casilla que el encuestado debe marcar para continuar",
    Logic_Type_Ranking: "Clasificación",
    Logic_TypeDesc_Ranking: "Arrastrar las opciones para ordenarlas por preferencia",
    Logic_Type_Rating: "Valoración",
    Logic_TypeDesc_Rating: "Estrellas, corazones o pulgares",
    Logic_Category_Scales: "Escalas",
    Logic_Type_Scale: "Escala de opinión",
    Logic_TypeDesc_Scale: "Una escala numerada con extremos etiquetados",
    Logic_Type_Slider: "Control deslizante",
    Logic_TypeDesc_Slider: "Un valor en una escala deslizante",
    Logic_Type_Likert: "Cuadrícula Likert",
    Logic_TypeDesc_Likert: "Valorar varias afirmaciones en una misma escala",
    Logic_Type_Number: "Número",
    Logic_TypeDesc_Number: "Simple, moneda o porcentaje",
    Logic_Category_Advanced: "Avanzado",
    Logic_Type_Calculated: "Calculado",
    Logic_TypeDesc_Calculated: "Un total de solo lectura calculado a partir de otras respuestas",
    Logic_Type_Date: "Fecha",
    Logic_TypeDesc_Date: "Una fecha del calendario, opcionalmente con hora",
    Logic_Category_Date: "Fecha",
    Logic_Type_Time: "Hora",
    Logic_TypeDesc_Time: "Una hora del día por sí sola",
    Logic_Type_Person: "Persona",
    Logic_TypeDesc_Person: "Elegir a alguien de la organización",
    Logic_Category_People: "Personas",
    Logic_Type_Email: "Correo electrónico",
    Logic_TypeDesc_Email: "Una dirección de correo electrónico, validada",
    Logic_Type_Phone: "Teléfono",
    Logic_TypeDesc_Phone: "Un número de teléfono, validado",
    Logic_Type_Address: "Dirección",
    Logic_TypeDesc_Address: "Calle, ciudad, código postal y país",
    Logic_Type_Hyperlink: "Vínculo",
    Logic_TypeDesc_Hyperlink: "Una dirección web",
    Logic_Type_FileUpload: "Carga de archivos",
    Logic_TypeDesc_FileUpload: "Adjuntar uno o varios archivos a la respuesta",
    Logic_Type_Signature: "Firma",
    Logic_TypeDesc_Signature: "Firmar con el mouse, un lápiz o el dedo",
    Logic_Type_Content: "Bloque de texto",
    Logic_TypeDesc_Content: "Instrucciones o una imagen: no recopila ninguna respuesta",
    Logic_Category_Layout: "Diseño",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "¿Con qué probabilidad nos recomendaría…?",
    Logic_Preset_satisfaction: "Satisfacción (1–5)",
    Logic_PresetDesc_satisfaction: "De muy insatisfecho a muy satisfecho",
    Logic_Preset_currency: "Moneda",
    Logic_PresetDesc_currency: "Una cantidad de dinero",
    Logic_Preset_percent: "Porcentaje",
    Logic_PresetDesc_percent: "Un valor porcentual",
    Logic_Template_blank_Name: "Formulario en blanco",
    Logic_Template_blank_Description: "Empezar desde cero",
    Logic_Template_feedback_Name: "Opiniones de clientes",
    Logic_Template_feedback_Description: "NPS, valoraciones y comentarios abiertos",
    Logic_Template_event_Name: "Inscripción a un evento",
    Logic_Template_event_Description: "Datos de los asistentes, sesiones y necesidades dietéticas",
    Logic_Template_itrequest_Name: "Solicitud de servicio de TI",
    Logic_Template_itrequest_Description: "Solicitudes categorizadas con prioridad y datos adjuntos",
    Logic_Template_expense_Name: "Solicitud de gastos",
    Logic_Template_expense_Description: "Partidas, recibos y un total calculado",
    Logic_Template_pulse_Name: "Encuesta de clima laboral",
    Logic_Template_pulse_Description: "Cuadrícula Likert, escala de compromiso y nota de anonimato",
    Logic_Template_safety_Name: "Inspección de seguridad",
    Logic_Template_safety_Description: "Lista de comprobación, fotos y una firma",
    Logic_Template_booking_Name: "Reserva de sala o recurso",
    Logic_Template_booking_Description: "Selector de recursos basado en búsqueda con franja horaria",
    Charts_ColumnChartAria: "Gráfico de columnas con {count} categorías",
    Charts_DonutChartAria: "Gráfico de anillos de {count} categorías",
    Charts_NoAnswers: "Aún no hay respuestas.",
    Charts_NoResponses: "Aún no hay respuestas.",
    Charts_Responses: "Respuestas",
    Charts_ResponsesOverTime: "Respuestas a lo largo del tiempo",
    Responses_Chart_Answer: "Respuesta",
    Responses_Chart_Average: "Promedio",
    Responses_Chart_AverageOf: "Promedio de {count}",
    Responses_Chart_AveragePosition: "Posición promedio",
    Responses_Chart_AverageRange: "Promedio (1–{max})",
    Responses_Chart_AvgValue: "prom. {value}",
    Responses_Chart_Detractors: "Detractores (0–6)",
    Responses_Chart_Max: "Máx.",
    Responses_Chart_Maximum: "Máximo",
    Responses_Chart_Median: "Mediana",
    Responses_Chart_MentionOne: "{count} mención",
    Responses_Chart_MentionOther: "{count} menciones",
    Responses_Chart_Min: "Mín.",
    Responses_Chart_Minimum: "Mínimo",
    Responses_Chart_NoAnswers: "Aún no hay respuestas.",
    Responses_Chart_NoNumeric: "Aún no hay respuestas numéricas.",
    Responses_Chart_NoRankings: "Aún no hay clasificaciones.",
    Responses_Chart_NoScores: "Aún no hay puntuaciones.",
    Responses_Chart_NotEnoughText: "Todavía no hay suficiente texto para resumir.",
    Responses_Chart_NpsScore: "Puntuación NPS",
    Responses_Chart_Option: "Opción",
    Responses_Chart_Passives: "Pasivos (7–8)",
    Responses_Chart_Promoters: "Promotores (9–10)",
    Responses_Chart_ResponseOne: "respuesta",
    Responses_Chart_ResponseOther: "respuestas",
    Responses_Chart_Responses: "Respuestas",
    Responses_Chart_ShowingAnswers: "Mostrando {shown} de {total} respuestas.",
    Responses_Chart_Statement: "Afirmación",
    Responses_Chart_Statistic: "Estadística",
    Responses_Chart_StdDev: "Desv. est.",
    Responses_Chart_StdDeviation: "Desviación estándar",
    Responses_Chart_Total: "Total",
    Responses_Chart_Value: "Valor",
    Responses_Dashboard_AllHidden: "Todas las preguntas están ocultas en el panel. Use “Mostrar preguntas ocultas” para recuperarlas.",
    Responses_Dashboard_AnsweredOf: "{answered} de {total} respondidas",
    Responses_Dashboard_AnsweredOfPinned: "{answered} de {total} respondidas · anclada",
    Responses_Dashboard_AveragedAcrossResponses: "Promedio de todas las respuestas",
    Responses_Dashboard_ByDay: "Por día",
    Responses_Dashboard_ByMonth: "Por mes",
    Responses_Dashboard_ByWeek: "Por semana",
    Responses_Dashboard_ChartAuto: "Automático",
    Responses_Dashboard_ChartBars: "Barras",
    Responses_Dashboard_ChartColumns: "Columnas",
    Responses_Dashboard_ChartDonut: "Anillo",
    Responses_Dashboard_ChartGauge: "Indicador",
    Responses_Dashboard_ChartHistogram: "Histograma",
    Responses_Dashboard_ChartOptions: "Opciones del gráfico",
    Responses_Dashboard_ChartOptionsFor: "Opciones del gráfico para {title}",
    Responses_Dashboard_ChartStatistics: "Estadísticas",
    Responses_Dashboard_ChartTable: "Tabla",
    Responses_Dashboard_ChartWordFrequency: "Frecuencia de palabras",
    Responses_Dashboard_EmptyBody: "En cuanto la gente empiece a responder, este panel se rellena automáticamente: cifras destacadas, una cronología de respuestas y un gráfico para las preguntas que merece la pena vigilar.",
    Responses_Dashboard_EmptyTitle: "Aún no hay respuestas",
    Responses_Dashboard_Hide: "Ocultar del panel",
    Responses_Dashboard_Highlights: "Aspectos destacados",
    Responses_Dashboard_Last7Days: "Últimos 7 días",
    Responses_Dashboard_LatestDate: "Última: {date}",
    Responses_Dashboard_MedianTimeToComplete: "Tiempo mediano de finalización",
    Responses_Dashboard_NoPriorWeek: "No hay semana anterior con la que comparar",
    Responses_Dashboard_OneEach: "Una de cada",
    Responses_Dashboard_Pin: "Anclar al panel",
    Responses_Dashboard_QuestionFallback: "pregunta",
    Responses_Dashboard_QuestionsAnswered: "Preguntas respondidas",
    Responses_Dashboard_RecordedOnSubmit: "Registrado al enviar",
    Responses_Dashboard_RepeatResponses: "{count} respuestas repetidas",
    Responses_Dashboard_ResponsesOverTime: "Respuestas a lo largo del tiempo",
    Responses_Dashboard_ShowHidden: "Mostrar preguntas ocultas",
    Responses_Dashboard_SinceMidnight: "Desde la medianoche",
    Responses_Dashboard_Today: "Hoy",
    Responses_Dashboard_TotalResponses: "Total de respuestas",
    Responses_Dashboard_UniqueRespondents: "Encuestados únicos",
    Responses_Dashboard_Unpin: "Desanclar del panel",
    Responses_Dashboard_UntitledQuestion: "Pregunta sin título",
    Responses_Dashboard_VsPrevious7Days: "frente a los 7 días anteriores",
    Responses_Detail_Answers: "Respuestas",
    Responses_Detail_AsTheForm: "Como en el formulario",
    Responses_Detail_Cancel: "Cancelar",
    Responses_Detail_Delete: "Eliminar",
    Responses_Detail_DeleteBody: "El elemento de la lista se mueve a la papelera de reciclaje del sitio, desde donde se puede restaurar.",
    Responses_Detail_DeleteTitle: "¿Eliminar esta respuesta?",
    Responses_Detail_Deleting: "Eliminando…",
    Responses_Detail_Draft: "Borrador",
    Responses_Detail_Header: "Respuesta {index} de {total}",
    Responses_Detail_LoadingAttachments: "Cargando datos adjuntos…",
    Responses_Detail_Next: "Respuesta siguiente",
    Responses_Detail_NoAnswer: "Sin respuesta",
    Responses_Detail_Previous: "Respuesta anterior",
    Responses_Detail_Print: "Imprimir",
    Responses_Detail_Signature: "Firma",
    Responses_Detail_Signed: "Firmado",
    Responses_Detail_Took: "tardó {duration}",
    Responses_Summary_AnsweredOfType: "{answered} de {total} respondidas · {type}",
    Responses_Summary_ByField: "Por {title}",
    Responses_Summary_CompareBy: "Comparar por…",
    Responses_Summary_EmptyBody: "Cada pregunta tendrá aquí su propio resumen.",
    Responses_Summary_NoComparison: "Sin comparación",
    Responses_Summary_NothingToCompare: "Ninguna respuesta contestó “{title}”, así que no hay nada que comparar.",
    Responses_Summary_OtherNote: "Los gráficos con más de {max} categorías agrupan las más pequeñas en “Otros”; cambie una tarjeta a Tabla para ver todos los valores.",
    Responses_Summary_ResponseCountOne: "{count} respuesta",
    Responses_Summary_ResponseCountOther: "{count} respuestas",
    Responses_Summary_SeeAllAnswers: "Ver todas las respuestas en la tabla",
    Responses_Summary_SegmentNote: "Se muestran los {groups} grupos más grandes. Una respuesta que seleccionó varias opciones aparece en cada grupo coincidente, por lo que los totales de los grupos pueden sumar más de {total}.",
    Responses_Summary_SplitBy: "Dividir por {title}",
    Responses_Summary_Untitled: "sin título",
    Responses_Table_Apply: "Aplicar",
    Responses_Table_Cancel: "Cancelar",
    Responses_Table_ClearSelection: "Borrar selección",
    Responses_Table_ColumnOrder: "Orden de las columnas",
    Responses_Table_ColumnsCount: "Columnas ({shown}/{total})",
    Responses_Table_Delete: "Eliminar",
    Responses_Table_DeleteBody: "Los elementos de la lista se mueven a la papelera de reciclaje del sitio, desde donde se pueden restaurar.",
    Responses_Table_DeleteSelected: "Eliminar seleccionadas",
    Responses_Table_DeleteTitleOne: "¿Eliminar {count} respuesta?",
    Responses_Table_DeleteTitleOther: "¿Eliminar {count} respuestas?",
    Responses_Table_Deleting: "Eliminando…",
    Responses_Table_MoveDown: "Bajar",
    Responses_Table_MoveDownFor: "Bajar {title}",
    Responses_Table_MoveUp: "Subir",
    Responses_Table_MoveUpFor: "Subir {title}",
    Responses_Table_NoColumns: "Aún no hay columnas de preguntas visibles.",
    Responses_Table_NoMatch: "Ninguna respuesta coincide con los filtros actuales.",
    Responses_Table_NothingToShow: "Nada que mostrar",
    Responses_Table_OpenResponse: "Abrir esta respuesta",
    Responses_Table_OrderNote: "Enviado y Enviado por siempre van primero. El orden de arrastre se aplica a las columnas de preguntas.",
    Responses_Table_Reorder: "Reordenar",
    Responses_Table_ResetColumns: "Restablecer columnas",
    Responses_Table_SelectResponse: "Seleccionar esta respuesta",
    Responses_Table_SelectedOne: "{count} respuesta seleccionada",
    Responses_Table_SelectedOther: "{count} respuestas seleccionadas",
    Responses_Table_ShowAll: "Mostrar todo",
    Responses_Table_ShowTheseQuestions: "Mostrar estas preguntas",
    Responses_Table_Submitted: "Enviado",
    Responses_Table_SubmittedBy: "Enviado por",
    Responses_Table_ToggleSelection: "Alternar selección",
    Responses_Table_Unknown: "Desconocido",
    Responses_Table_Untitled: "Sin título",
    Responses_View_AllTime: "Todo el tiempo",
    Responses_View_AnyAnswer: "Cualquier respuesta",
    Responses_View_Clear: "Borrar",
    Responses_View_CopyShareLink: "Copiar vínculo para compartir",
    Responses_View_CountFiltered: "{shown} de {total} respuestas",
    Responses_View_CountOne: "{count} respuesta",
    Responses_View_CountOther: "{count} respuestas",
    Responses_View_Dashboard: "Panel",
    Responses_View_DateRange: "Intervalo de fechas",
    Responses_View_EmptyBody: "Comparta el formulario para empezar a recopilar respuestas. Las respuestas se guardan en “{list}” y aparecen aquí de inmediato.",
    Responses_View_EmptyTitle: "Aún no hay respuestas",
    Responses_View_ExportCsv: "Exportar CSV",
    Responses_View_FilterByAnswer: "Filtrar por respuesta",
    Responses_View_FilterByQuestion: "Filtrar por pregunta",
    Responses_View_FilterValue: "Valor del filtro",
    Responses_View_Last30Days: "Últimos 30 días",
    Responses_View_Last7Days: "Últimos 7 días",
    Responses_View_Last90Days: "Últimos 90 días",
    Responses_View_LoadError: "No se pudieron cargar las respuestas. Publique el formulario una vez para que existan las columnas de la lista y vuelva a intentarlo.",
    Responses_View_Loading: "Cargando respuestas…",
    Responses_View_MoreActions: "Más acciones de respuesta",
    Responses_View_PreviewForm: "Vista previa del formulario",
    Responses_View_Refresh: "Actualizar",
    Responses_View_ResponsesTab: "Respuestas ({count})",
    Responses_View_SearchPlaceholder: "Buscar en todas las respuestas",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Seleccione un valor",
    Responses_View_Summary: "Resumen",
    Responses_View_Today: "Hoy",
    Responses_View_Truncated: "Esta lista tiene más respuestas de las que Smart Forms carga a la vez. Se muestran las {count} más recientes; abra la lista en Microsoft Lists para ver el conjunto completo.",
    Responses_View_TryAgain: "Intentar de nuevo",
    Responses_View_Untitled: "Sin título",
    Responses_Approval_Column: "Aprobación",
    Responses_Approval_ReviewerColumn: "Revisado por",
    Responses_Approval_CommentColumn: "Comentario del revisor",
    Responses_Approval_Pending: "Pendiente",
    Responses_Approval_Approved: "Aprobada",
    Responses_Approval_Rejected: "Rechazada",
    Responses_Approval_AnyStatus: "Cualquier estado de aprobación",
    Responses_Approval_FilterLabel: "Filtrar por estado de aprobación",
    Responses_Approval_ApproveSelected: "Aprobar seleccionadas",
    Responses_Approval_RejectSelected: "Rechazar seleccionadas",
    Responses_Approval_BulkFailed: "No se pudieron actualizar {count} respuestas. Inténtelo de nuevo.",
    Responses_Approval_Approve: "Aprobar",
    Responses_Approval_Reject: "Rechazar",
    Responses_Approval_Reset: "Restablecer a pendiente",
    Responses_Approval_CommentLabel: "Comentario (opcional)",
    Responses_Approval_ReviewedBy: "Revisado por {name}",
    Responses_Approval_Error: "No se pudo guardar la decisión. Inténtelo de nuevo.",
    Responses_Dashboard_ApprovalStatus: "Pendiente de revisión",
    Responses_Dashboard_ApprovalBreakdown: "{pending} pendientes, {approved} aprobadas, {rejected} rechazadas",
    Responses_Dashboard_TimelineCoarsened: "El intervalo de fechas es largo, por lo que la escala de tiempo se agrupó de forma más general ({grain}).",
    Responses_Dashboard_TimelineTruncated: "El intervalo de fechas es muy largo, por lo que solo se muestran los últimos {count} períodos.",
    Service_Item_DefaultTitle: "Respuesta — {date}",
    Service_Email_ApprovalSubject: "Su respuesta fue {status} — {title}",
    Service_Email_ApprovalHeading: "Su respuesta fue {status}",
    Service_Email_ApprovalIntro: "Un revisor marcó su respuesta a \"{title}\" como {status}.",
    Service_Email_ApprovalCommentLabel: "Comentario del revisor",
    Service_Approval_Approved: "aprobada",
    Service_Approval_Rejected: "rechazada",
    Service_Approval_Pending: "pendiente",
    Service_Lookup_InvalidFilter: "El filtro de búsqueda no es válido.",
    Service_Edit_NotAllowed: "Este formulario no permite editar una respuesta enviada.",
    Service_Edit_NotYours: "Solo puede editar su propia respuesta.",
    Service_Signature_AttachmentLabel: "Firma",
    PropertyPane_ListsLoadFailed: "No se pudieron cargar las listas de este sitio.",
    PropertyPane_EnterListName: "Primero escriba un nombre para la nueva lista.",
    PropertyPane_CreatingList: "Creando \"{name}\"…",
    PropertyPane_ListCreated: "Lista \"{title}\" creada y seleccionada.",
    PropertyPane_ListAlreadyExists: "Ya existe una lista llamada \"{name}\": selecciónela en la lista desplegable de arriba.",
    PropertyPane_CreateListFailed: "No se pudo crear la lista. Compruebe que tiene permiso para crear listas en este sitio.",
    PropertyPane_Description: "Elija la lista de SharePoint que almacena las respuestas del formulario o cree una nueva. Todo lo demás (preguntas, apariencia, notificaciones) se edita directamente en la página.",
    PropertyPane_ResponseList_GroupName: "Lista de respuestas",
    PropertyPane_ListDropdown_Label: "Guardar las respuestas en esta lista",
    PropertyPane_ResponsesGoTo: "Las respuestas se guardan en \"{name}\".",
    PropertyPane_PickList: "Elija una lista o cree una a continuación.",
    PropertyPane_LoadingLists: "Cargando listas…",
    PropertyPane_NewListName_Label: "O cree una nueva lista",
    PropertyPane_NewListName_Placeholder: "Nombre de la nueva lista",
    PropertyPane_CreateList_Button: "Crear lista",
    PropertyPane_Tips_GroupName: "Sugerencias",
    PropertyPane_Tip_AutoSave: "Las preguntas y la configuración se guardan automáticamente a medida que las edita; no es necesario guardar ni publicar la página.",
    PropertyPane_Tip_Permissions: "Los encuestados necesitan permiso para agregar elementos a la lista de respuestas. Revise los permisos de la lista si alguien informa de un error al enviar.",
    PropertyPane_Tip_Share: "Use \"Recopilar respuestas\" en la página para crear las columnas de la lista y obtener un vínculo para compartir y rellenar el formulario.",
    App_ErrorBoundary_Title: "Smart Forms: error de representación",
    App_ErrorBoundary_Message: "Mensaje:",
    App_ErrorBoundary_Stack: "Pila:",
    App_ErrorBoundary_NoStack: "(no hay pila disponible)",
    App_ErrorBoundary_ConsoleNote: "Todos los detalles también se escribieron en la consola del explorador.",
    App_DefaultQuestionTitle: "Pregunta {number}",
    App_Error_ListMissing: "La lista configurada para este formulario ya no existe. Elija otra lista en la configuración del elemento web.",
    App_Error_LoadConfig: "Se produjo un error al cargar la configuración del formulario.",
    App_Error_Unable: "No se puede cargar el formulario.",
    App_Publish_ConflictNotice: "\"{title}\" ya tiene una columna de lista de otro tipo ({type}). Cambie el nombre de la pregunta para que se pueda crear una columna nueva o vuelva a cambiar su tipo.",
    App_Publish_ConflictUnnamedQuestion: "una pregunta",
    App_Publish_ColumnsAddedOne: "Se agregó {count} columna a \"{list}\".",
    App_Publish_ColumnsAddedOther: "Se agregaron {count} columnas a \"{list}\".",
    App_Publish_TheList: "la lista",
    App_Publish_UpToDate: "La lista de respuestas ya está actualizada.",
    App_Publish_Error: "No se pudieron crear las columnas de la lista. Normalmente significa que no tiene el permiso Administrar listas en la lista de respuestas, pero también puede ocurrir en sitios con los scripts personalizados deshabilitados. Compruebe la consola del explorador para ver el error subyacente o inténtelo de nuevo.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Cree un formulario atractivo sobre una lista de SharePoint: {count} tipos de pregunta, lógica de ramificación, carga de archivos, vínculos para rellenar y compartir, y un panel de resultados.",
    App_Placeholder_ChooseList: "Elegir o crear una lista",
    App_Placeholder_Hint: "Edite la página y configure este elemento web para empezar.",
    App_Loading: "Cargando formulario…",
    App_OpenSettings: "Abrir configuración",
    App_Tab_Questions: "Preguntas",
    App_Tab_QuestionsWithCount: "Preguntas ({count})",
    App_Tab_Responses: "Respuestas",
    App_Tab_Responses_Title: "Las respuestas se guardan en \"{list}\"",
    App_Templates_Start: "Empezar desde una plantilla",
    App_Settings_Title: "Configuración del formulario: apariencia, notificaciones, acceso",
    App_Settings_AriaLabel: "Configuración del formulario",
    App_Preview: "Vista previa",
    App_Preview_Close: "Cerrar vista previa",
    App_Preview_Hint: "Vista previa: nada de lo que envíe aquí se guarda. La validación y la ramificación se comportan exactamente como lo harán para los encuestados.",
    App_Publish_GettingReady: "Preparando…",
    App_Publish_CollectResponses: "Recopilar respuestas",
    App_Publish_Share: "Compartir",
    App_Retry: "Reintentar",
    App_SaveError_Banner: "No se pudo guardar su último cambio. Compruebe la conexión y vuelva a intentarlo.",
    App_Preflight_BlockingTitle: "Corrija esto antes de recopilar",
    App_Preflight_WarningTitle: "Conviene revisarlo antes",
    App_Preflight_BlockingText: "Esto impediría que el formulario publicado funcione correctamente.",
    App_Preflight_WarningText: "No hay nada roto, pero normalmente conviene corregir esto antes de compartir el vínculo.",
    App_Preflight_GoTo: "Ir a",
    App_Preflight_CollectAnyway: "Recopilar respuestas de todos modos",
    App_Preflight_Back: "Volver al formulario",
    App_Cancel: "Cancelar",
    App_Done: "Listo",
    App_Share_Title: "Su formulario está listo para compartir",
    App_Share_SubText: "Envíe este vínculo a quien deba rellenar el formulario.",
    App_Share_LinkAriaLabel: "Vínculo para compartir",
    App_Share_Copy: "Copiar",
    App_Share_Copied: "Copiado",
    App_Share_AddItemsEmphasis: "agregar elementos",
    App_Share_PermissionNote: "Los encuestados necesitan permiso para {addItems} a “{title}” y acceso a esta página. Si alguien recibe un error al enviar, casi siempre se debe a esto.",
    App_Share_PrefillNote: "Puede responder preguntas de antemano en el vínculo agregando el nombre de la columna, por ejemplo {example}.",
    App_Templates_ReplaceWarning: "Al elegir una plantilla se reemplazan las preguntas actuales.",
    App_Templates_PickStart: "Elija un punto de partida; después podrá cambiar lo que quiera.",
    App_Templates_Empty: "Vacío",
    App_Templates_QuestionCount: "{count} preguntas",
    App_SaveChip_SavingTitle: "Guardando su última edición",
    App_SaveChip_Saving: "Guardando…",
    App_SaveChip_FailedTitle: "No se pudo guardar su última edición. Compruebe la conexión y vuelva a intentarlo.",
    App_SaveChip_Failed: "Error al guardar",
    App_SaveChip_SavedTitle: "Todos los cambios están guardados",
    App_SaveChip_Saved: "Guardado",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Nueva respuesta: {title}",
    Service_Email_NewResponseHeading: "Nueva respuesta: {title}",
    Service_Email_NewResponseIntro: "Alguien acaba de enviar una respuesta: {date}.",
    Service_Email_ReceiptSubject: "Su respuesta: {title}",
    Service_Email_ReceiptHeading: "¡Gracias por su respuesta!",
    Service_Email_ReceiptIntro: "Esta es una copia de lo que envió a \"{title}\".",
    App_History_Title: "Historial de versiones",
    App_History_RestoredNotice: "Se restauró la versión guardada el {date}. Revísela y, después, use Recopilar respuestas para publicar las preguntas nuevas.",
    App_History_Undo: "Deshacer restauración",
    App_Share_CopyManual: "El explorador bloqueó la copia. Seleccione el vínculo anterior y presione Ctrl+C (Cmd+C en Mac) para copiarlo.",
    App_Share_TeamsNote: "Está en Microsoft Teams. Este vínculo abre directamente la página de SharePoint, por lo que los destinatarios necesitan acceso al sitio.",
    App_Share_PrefillNotSecure: "Las respuestas rellenadas previamente son solo una comodidad: cualquier persona con el vínculo puede cambiarlas, así que nunca las considere un límite de seguridad.",
    Designer_Section_DropHere: "Suelte aquí una pregunta",
    Designer_Section_DropEnd: "Suelte aquí para mover al final de esta sección",
    Designer_Rules_RemovedOne: "Se quitó 1 regla de bifurcación que ya no se ajustaba.",
    Designer_Rules_RemovedOther: "Se quitaron {count} reglas de bifurcación que ya no se ajustaban.",
    Designer_Settings_AllowEdit: "Permitir a los encuestados editar su respuesta",
    Designer_Settings_AllowEditHint: "Los encuestados pueden volver a abrir y actualizar lo que enviaron. Cada persona solo puede editar su propia respuesta.",
    Designer_Settings_EnableApproval: "Habilitar flujo de trabajo de aprobación",
    Designer_Settings_ApprovalNotify: "Enviar correo al encuestado con la decisión",
    Designer_Settings_ApprovalHint: "Agrega columnas de aprobación a la lista de respuestas la próxima vez que publique. Los propietarios aprueban o rechazan las respuestas desde la pestaña Respuestas.",
    Designer_History_Title: "Historial de versiones",
    Designer_History_Intro: "Versiones guardadas anteriormente de las preguntas y la configuración de este formulario. Al restaurar, se carga una versión en el diseñador; puede deshacerlo, y las preguntas nuevas solo se crean al publicar.",
    Designer_History_Loading: "Cargando versiones...",
    Designer_History_Empty: "No se encontraron versiones anteriores. El historial de versiones requiere que el control de versiones esté activado en la lista \"Smart Forms Config\" y al menos una edición guardada.",
    Designer_History_Latest: "Última",
    Designer_History_LatestTitle: "Esta es la versión que se usa actualmente",
    Designer_History_By: "por {name}",
    Designer_History_UnknownAuthor: "Autor desconocido",
    Designer_History_VersionLabel: "versión {label}",
    Designer_History_Preview: "Vista previa",
    Designer_History_Restore: "Restaurar",
    Designer_History_QuestionsOne: "1 pregunta",
    Designer_History_QuestionsOther: "{count} preguntas",
    Designer_History_LoadFailed: "No se pudo cargar esta versión.",
    Designer_History_ConfirmTitle: "¿Restaurar esta versión?",
    Designer_History_ConfirmText: "El formulario se reemplazará por la versión guardada el {date} ({count} preguntas). Puede deshacerlo justo después."
  };
});
