define([], function () {
  return {
    Designer_Color_Blue: "Sininen",
    Designer_Color_Teal: "Sinivihreä",
    Designer_Color_Green: "Vihreä",
    Designer_Color_Purple: "Violetti",
    Designer_Color_Magenta: "Magenta",
    Designer_Color_Red: "Punainen",
    Designer_Color_Orange: "Oranssi",
    Designer_Color_Gray: "Harmaa",
    Designer_Settings_LayoutSinglePage: "Kaikki kysymykset yhdellä sivulla",
    Designer_Settings_LayoutWizard: "Yksi osio per vaihe (ohjattu toiminto)",
    Designer_Settings_Title: "Lomakkeen asetukset",
    Designer_Common_Apply: "Käytä",
    Designer_Common_Cancel: "Peruuta",
    Designer_Settings_TabBasics: "Perusasetukset",
    Designer_Settings_FormTitle: "Lomakkeen otsikko",
    Designer_Settings_Description: "Kuvaus",
    Designer_Settings_Layout: "Asettelu",
    Designer_Settings_NumberQuestions: "Numeroi kysymykset",
    Designer_Settings_ShuffleQuestions: "Sekoita kysymysten järjestys jokaiselle vastaajalle",
    Designer_Settings_ShowProgressBar: "Näytä edistymispalkki",
    Designer_Settings_TabAppearance: "Ulkoasu",
    Designer_Settings_AccentColor: "Korostusväri",
    Designer_Settings_CustomColorTitle: "Mukautettu väri",
    Designer_Settings_CustomColorAria: "Mukautettu korostusväri",
    Designer_Settings_AccentHint: "Korostusvärit mukautetaan automaattisesti kontrastin vuoksi tummilla sivustoilla, jolloin lomake pysyy luettavana sivun teemasta riippumatta.",
    Designer_Settings_ShowHeader: "Näytä lomakkeen ylätunniste",
    Designer_Settings_HeaderIcon: "Ylätunnisteen kuvake",
    Designer_Settings_TabAfterSubmit: "Lähetyksen jälkeen",
    Designer_Settings_SubmitButtonText: "Lähetä-painikkeen teksti",
    Designer_Settings_SubmitPlaceholder: "Lähetä",
    Designer_Settings_ThankYouTitle: "Kiitosviestin otsikko",
    Designer_Settings_ThankYouPlaceholder: "Kiitos!",
    Designer_Settings_ThankYouMessage: "Kiitosviesti",
    Designer_Settings_ShowSubmitAnother: "Näytä ”Lähetä uusi vastaus” -painike",
    Designer_Settings_TabNotifications: "Ilmoitukset",
    Designer_Settings_EmailEachResponseTo: "Lähetä jokainen vastaus sähköpostilla osoitteeseen",
    Designer_Settings_EmailPlaceholder: "nimi@yritys.fi; tiimi@yritys.fi",
    Designer_Settings_EmailDescription: "Organisaatiosi jäsenet saavat jokaisen vastauksen sähköpostitse sekä linkin luettelon kohteeseen",
    Designer_Settings_RespondentReceipt: "Lähetä vastaajille kopio heidän vastauksistaan sähköpostilla",
    Designer_Settings_NotificationsInfo: "Ilmoitukset käyttävät SharePointin omaa sähköpostipalvelua, joten vastaanottajien on oltava organisaatiosi käyttäjiä. Ulkoiset osoitteet ohitetaan ilman ilmoitusta.",
    Designer_Settings_TabAccess: "Käyttöoikeudet",
    Designer_Settings_OpenFrom: "Avataan alkaen",
    Designer_Settings_OpenImmediately: "Avaa heti",
    Designer_Settings_CloseAfter: "Suljetaan",
    Designer_Settings_NeverClose: "Älä koskaan sulje",
    Designer_Settings_ClearDates: "Tyhjennä päivämäärät",
    Designer_Settings_DatesInverted: "Sulkeutumispäivä on avautumispäivän kanssa sama tai sitä aiempi, joten lomake ei ottaisi koskaan vastaan vastauksia.",
    Designer_Settings_MaxResponses: "Lopeta tämän vastausmäärän jälkeen",
    Designer_Settings_NoLimit: "Ei rajoitusta",
    Designer_Settings_OneResponsePerPerson: "Salli vain yksi vastaus henkilöä kohden",
    Designer_Settings_AllowSaveDraft: "Salli vastaajien tallentaa luonnos ja jatkaa myöhemmin",
    Designer_Settings_ClosedMessage: "Viesti, joka näytetään lomakkeen ollessa suljettu",
    Designer_Settings_ClosedMessagePlaceholder: "Tämä lomake ei enää ota vastaan vastauksia.",
    Designer_Settings_AccessInfo: "Nämä rajoitukset toteutetaan lomakkeessa, ei SharePointissa. Jokainen, jolla on oikeus lisätä kohteita vastausluetteloon, voi silti lisätä sellaisen suoraan luettelon kautta.",
    Designer_Field_StyleInfo: "Tieto (korostus)",
    Designer_Field_StyleSuccess: "Onnistuminen (vihreä)",
    Designer_Field_StyleWarning: "Varoitus (keltainen)",
    Designer_Field_StylePlain: "Pelkkä teksti",
    Designer_Field_StyleDivider: "Erotinviiva",
    Designer_Field_IconStars: "Tähdet",
    Designer_Field_IconHearts: "Sydämet",
    Designer_Field_IconThumbs: "Peukut ylös",
    Designer_Field_FormatPlain: "Pelkkä luku",
    Designer_Field_FormatCurrency: "Valuutta",
    Designer_Field_FormatPercent: "Prosentti",
    Designer_Field_UntitledQuestion: "Nimetön kysymys",
    Designer_Field_DeletedQuestion: "poistettu kysymys",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} ja {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "TAI",
    Designer_Rule_JoinAll: "JA",
    Designer_Rule_Preview: "Näytetään, kun {conditions}.",
    Designer_Field_Yes: "Kyllä",
    Designer_Field_No: "Ei",
    Designer_Field_When: "Kun",
    Designer_Field_SelectValue: "Valitse arvo",
    Designer_Field_DateValuePlaceholder: "VVVV-KK-PP tai \"today\"",
    Designer_Field_ValuePlaceholder: "Arvo",
    Designer_Field_UpperBound: "Yläraja",
    Designer_Field_RemoveCondition: "Poista tämä ehto",
    Designer_Field_FormulaInvalid: "Tätä kaavaa ei voi laskea. Tarkista sulut ja operaattorit.",
    Designer_Field_FormulaMissing: "Näitä kysymyksiä ei ole olemassa: {names}.",
    Designer_Field_FormulaPreview: "Kun jokainen syöte on 10, tulokseksi tulee {value}.",
    Designer_Field_HintYesNo: "Käytä arvoa \"yes\" tai \"no\"",
    Designer_Field_HintMultiDefault: "Erota useat oletusarvot merkillä ;",
    Designer_Field_HintSingleDefault: "Arvon on vastattava jotakin vaihtoehtoa",
    Designer_Field_HintDate: "Käytä arvoa \"today\" tai päivämäärää, esimerkiksi 2026-03-01",
    Designer_Field_HintTime: "Käytä arvoa \"now\" tai kellonaikaa, esimerkiksi 09:30",
    Designer_Field_QuestionSettings: "Kysymyksen asetukset",
    Designer_Field_Appearance: "Ulkoasu",
    Designer_Field_Style: "Tyyli",
    Designer_Field_ImageUrl: "Kuvan URL-osoite (valinnainen)",
    Designer_Field_Content: "Sisältö",
    Designer_Field_BasicFormatting: "Perusmuotoilu on sallittu: lihavointi, kursivointi, luettelot ja linkit.",
    Designer_Field_TabOptions: "Vaihtoehdot",
    Designer_Field_TabBranching: "Haarautuminen",
    Designer_Field_BranchingNeedsQuestion: "Lisää ensin toinen kysymys – haarautuminen tarvitsee jotain, mihin se perustuu.",
    Designer_Field_BranchingToggle: "Näytä tämä kysymys vain, kun muut vastaukset täsmäävät",
    Designer_Field_Match: "Täsmää",
    Designer_Field_MatchAll: "kaikkiin näistä",
    Designer_Field_MatchAny: "johonkin näistä",
    Designer_Field_AddCondition: "Lisää ehto",
    Designer_Field_TabValidation: "Vahvistus",
    Designer_Field_HelpText: "Ohjeteksti",
    Designer_Field_HelpTextPlaceholder: "Näytetään kysymyksen otsikon alla",
    Designer_Field_CheckboxLabel: "Valintaruudun otsikko",
    Designer_Field_Placeholder: "Paikkamerkki",
    Designer_Field_DefaultAnswer: "Oletusvastaus",
    Designer_Field_RequiredMessage: "Mukautettu pakollisuusviesti",
    Designer_Field_RequiredMessagePlaceholder: "{title} on pakollinen",
    Designer_Field_ThisQuestion: "Tämä kysymys",
    Designer_Field_RequiredMessageDescription: "Näytetään vakioviestin sijaan, kun tähän kysymykseen ei ole vastattu",
    Designer_Field_ReadOnly: "Vain luku (vastaus voi tulla vain esitäytetystä linkistä)",
    Designer_Field_ValidationRules: "Vahvistussäännöt",
    Designer_Field_MaxLength: "Enimmäispituus",
    Designer_Field_Pattern: "On täsmättävä tähän kaavaan",
    Designer_Field_PatternDescription: "Säännöllinen lauseke. Jätä tyhjäksi, jos kaavaa ei tarkisteta.",
    Designer_Field_PatternMessage: "Viesti, kun kaava ei täsmää",
    Designer_Field_PatternMessagePlaceholder: "Vastaus ei ole odotetussa muodossa",
    Designer_Field_Format: "Muoto",
    Designer_Field_UnitSuffix: "Arvon jälkeen näytettävä yksikkö",
    Designer_Field_UnitSuffixPlaceholder: "kg, h, kpl…",
    Designer_Field_Minimum: "Vähimmäisarvo",
    Designer_Field_Maximum: "Enimmäisarvo",
    Designer_Field_Decimals: "Desimaalit",
    Designer_Field_Formula: "Kaava",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Viittaa muihin kysymyksiin niiden tekstillä aaltosulkeissa. Tukee merkintöjä + - * / ( ) sekä funktioita round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Käytettävissä olevat kysymykset: {questions}",
    Designer_Field_NoneYet: "ei vielä yhtään",
    Designer_Field_Step: "Askel",
    Designer_Field_From: "Alkaen",
    Designer_Field_To: "Asti",
    Designer_Field_LowLabel: "Alarajan otsikko",
    Designer_Field_LowLabelPlaceholder: "Erittäin epätodennäköistä",
    Designer_Field_HighLabel: "Ylärajan otsikko",
    Designer_Field_HighLabelPlaceholder: "Erittäin todennäköistä",
    Designer_Field_SummarizeAs: "Tiivistä muodossa",
    Designer_Field_SummarizeAverage: "Keskiarvo ja jakauma",
    Designer_Field_SummarizeNps: "Net Promoter Score (vaatii asteikon 0–10)",
    Designer_Field_NpsWarning: "Net Promoter Score on mielekäs vain asteikolla 0–10. Aseta Alkaen-arvoksi 0 ja Asti-arvoksi 10.",
    Designer_Field_NumberOfIcons: "Kuvakkeiden määrä",
    Designer_Field_Icon: "Kuvake",
    Designer_Field_AllowHalf: "Salli puoliarvot",
    Designer_Field_ShowOptionsAs: "Näytä vaihtoehdot muodossa",
    Designer_Field_DisplayButtons: "Rivinsisäiset painikkeet",
    Designer_Field_DisplayDropdown: "Avattava luettelo",
    Designer_Field_DisplayAutomatic: "Automaattinen (rivinsisäinen enintään 6 vaihtoehtoon asti)",
    Designer_Field_AllowOther: "Lisää vapaasti täytettävä ”Muu”-vaihtoehto",
    Designer_Field_OtherLabel: "”Muu”-vaihtoehdon otsikko",
    Designer_Field_OtherPlaceholder: "Muu",
    Designer_Field_ShuffleOptions: "Sekoita vaihtoehtojen järjestys jokaiselle vastaajalle",
    Designer_Field_MinSelections: "Valintojen vähimmäismäärä",
    Designer_Field_MaxSelections: "Valintojen enimmäismäärä",
    Designer_Field_SourceList: "Lähdeluettelo",
    Designer_Field_ChooseList: "Valitse luettelo",
    Designer_Field_LookupColumn: "Sarake, josta vaihtoehdot luetaan",
    Designer_Field_ChooseColumn: "Valitse sarake",
    Designer_Field_ChooseListFirst: "Valitse ensin luettelo",
    Designer_Field_LookupFilter: "Suodatin (valinnainen)",
    Designer_Field_LookupFilterDescription: "OData-suodatin, joka rajaa, mistä lähdekohteista tulee vaihtoehtoja",
    Designer_Field_LookupInfo: "Vastaukset tallentavat vaihtoehdon tekstin eivätkä linkkiä lähdekohteeseen, joten vastaukset pysyvät luettavina, vaikka lähdeluettelo muuttuisi myöhemmin.",
    Designer_Field_ConsentText: "Valintaruudun yläpuolella näytettävät ehdot",
    Designer_Field_AllowMultiplePeople: "Salli useita henkilöitä",
    Designer_Field_AllowGroups: "Salli myös ryhmät",
    Designer_Field_IncludeTime: "Sisällytä kellonaika",
    Designer_Field_TimeStep: "Aika-askel (minuuttia)",
    Designer_Field_MaxFiles: "Tiedostojen enimmäismäärä",
    Designer_Field_MaxFileSize: "Enimmäiskoko per tiedosto (Mt)",
    Designer_Field_AcceptedTypes: "Hyväksytyt tiedostotyypit",
    Designer_Field_AcceptedTypesDescription: "Pilkuilla erotetut tunnisteet. Jätä tyhjäksi, jos hyväksytään kaikki, mitä SharePoint sallii.",
    Designer_Field_FilesInfo: "Tiedostot tallennetaan vastauskohteen liitteiksi. SharePoint estää tietyt tunnisteet (kuten .exe) riippumatta siitä, mitä sallit tässä.",
    Designer_Field_Rows: "Rivit",
    Designer_Field_ProvisionedNote: "Tälle kysymykselle on jo luettelosarake ({name}). Sarakkeen tyyppiä muuttavat asetukset on lukittu – monista kysymys, jos tarvitset eri tyypin.",
    Designer_Category_Text: "Teksti",
    Designer_Category_Choice: "Valinta",
    Designer_Category_Scales: "Asteikot",
    Designer_Category_Date: "Päivämäärä",
    Designer_Category_People: "Henkilöt",
    Designer_Category_Advanced: "Lisäasetukset",
    Designer_Category_Layout: "Asettelu",
    Designer_Menu_CommonPresets: "Yleiset esiasetukset",
    Designer_Menu_AllTypes: "Kaikki kysymystyypit",
    Designer_Menu_ChangeType: "Vaihda tyyppi",
    Designer_Menu_TypeLockedTitle: "Luettelosarake on jo olemassa, joten tyyppi on lukittu. Vaihda tyyppi monistamalla kysymys.",
    Designer_Menu_MoreSettings: "Haarautuminen, vahvistus ym.",
    Designer_Menu_InsertBelow: "Lisää kysymys alapuolelle",
    Designer_Card_Duplicate: "Monista",
    Designer_Card_DeleteQuestion: "Poista kysymys",
    Designer_Outline_Aria: "Kysymysten jäsennys",
    Designer_Outline_QuestionCountOne: "{count} kysymys",
    Designer_Outline_QuestionCountOther: "{count} kysymystä",
    Designer_Outline_IssuesTitle: "{count} tarkistettavaa asiaa",
    Designer_Outline_Find: "Etsi kysymys",
    Designer_Outline_Empty: "Ei vielä kysymyksiä.",
    Designer_Section_DefaultTitle: "Osio {number}",
    Designer_Card_Question: "Kysymys",
    Designer_Card_BranchingTitle: "Tämä kysymys näkyy vain, kun haarautumissääntö täsmää",
    Designer_Card_BranchingChip: "Haarautuminen",
    Designer_Card_LiveTitle: "Luettelosarake on olemassa, joten tyyppi on lukittu",
    Designer_Card_LiveChip: "Käytössä",
    Designer_Card_CheckChip: "Tarkista",
    Designer_Option_Placeholder: "Vaihtoehto {number}",
    Designer_Option_LabelAria: "Vaihtoehdon {number} otsikko",
    Designer_Option_ImageUrl: "Kuvan URL-osoite",
    Designer_Option_ImageUrlAria: "Vaihtoehdon {number} kuvan URL-osoite",
    Designer_Option_Remove: "Poista vaihtoehto",
    Designer_Option_RemoveAria: "Poista vaihtoehto {number}",
    Designer_Option_Add: "Lisää vaihtoehto",
    Designer_Option_OtherHint: "Vastaajat voivat myös kirjoittaa oman vastauksen nimellä ”{label}”.",
    Designer_Option_OtherFallback: "Muu",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Poista",
    Designer_Grid_RemoveAria: "Poista {label} {number}",
    Designer_Grid_Statements: "Väittämät",
    Designer_Grid_Scale: "Asteikko",
    Designer_Grid_AddStatement: "Lisää väittämä",
    Designer_Grid_AddScale: "Lisää asteikko",
    Designer_Width_Full: "Koko leveys",
    Designer_Width_Half: "Puolet leveydestä",
    Designer_Width_Third: "Kolmasosa leveydestä",
    Designer_Width_Aria: "Kysymyksen leveys",
    Designer_Card_BlockLabelPlaceholder: "Lohkon otsikko (ei näytetä vastaajille)",
    Designer_Card_QuestionText: "Kysymysteksti",
    Designer_Card_MoveUp: "Siirrä ylös",
    Designer_Card_MoveQuestionUp: "Siirrä kysymystä ylös",
    Designer_Card_MoveDown: "Siirrä alas",
    Designer_Card_MoveQuestionDown: "Siirrä kysymystä alas",
    Designer_Card_DuplicateQuestion: "Monista kysymys",
    Designer_Card_MultipleAnswers: "Useita vastauksia",
    Designer_Card_Required: "Pakollinen",
    Designer_Card_MoreOptions: "Lisää asetuksia",
    Designer_Card_MoreOptionsAria: "Tämän kysymyksen lisäasetukset",
    Designer_Canvas_FormTitle: "Lomakkeen otsikko",
    Designer_Canvas_DescriptionPlaceholder: "Lisää kuvaus (valinnainen)",
    Designer_Canvas_DescriptionAria: "Lomakkeen kuvaus",
    Designer_Canvas_EmptyTitle: "Lisää ensimmäinen kysymyksesi",
    Designer_Canvas_EmptyBody: "Aloita valitsemalla kysymystyyppi. Voit järjestää kysymyksiä uudelleen vetämällä ja lisätä haarautumisen, jotta ihmiset näkevät vain heitä koskevat kysymykset.",
    Designer_Section_Chip: "Osio {number}/{total}",
    Designer_Section_TitlePlaceholder: "Osion otsikko",
    Designer_Section_TitleAria: "Osion {number} otsikko",
    Designer_Section_DescriptionPlaceholder: "Kuvaus (valinnainen)",
    Designer_Section_DescriptionAria: "Osion {number} kuvaus",
    Designer_Section_MoveUp: "Siirrä osiota ylös",
    Designer_Section_MoveDown: "Siirrä osiota alas",
    Designer_Section_Delete: "Poista osio",
    Designer_Card_DragToReorder: "Järjestä vetämällä",
    Designer_Card_ReorderAria: "Järjestä uudelleen: {title}",
    Designer_Card_ReorderFallback: "kysymys",
    Designer_Canvas_AddNew: "Lisää uusi",
    Designer_Canvas_AddSection: "Lisää osio",
    Form_Address_AriaWithLabel: "{label} – {part}",
    Form_Address_StreetPlaceholder: "Katuosoite",
    Form_Address_Street2Placeholder: "Huoneisto tms. (valinnainen)",
    Form_Address_CityPlaceholder: "Kaupunki",
    Form_Address_StatePlaceholder: "Osavaltio / maakunta",
    Form_Address_PostalCodePlaceholder: "Postinumero",
    Form_Address_CountryPlaceholder: "Maa",
    Form_Address_StreetAria: "katuosoite",
    Form_Address_Street2Aria: "osoiterivi 2",
    Form_Address_CityAria: "kaupunki",
    Form_Address_StateAria: "osavaltio tai maakunta",
    Form_Address_PostalCodeAria: "postinumero",
    Form_Address_CountryAria: "maa",
    Form_Consent_DefaultLabel: "Hyväksyn",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered}/{total} riviä vastattu",
    Form_Lookup_LoadError: "Tämän kysymyksen vaihtoehtoja ei voitu ladata.",
    Form_Lookup_Loading: "Ladataan vaihtoehtoja…",
    Form_Lookup_SelectOptionsPlaceholder: "Valitse vaihtoehdot",
    Form_Lookup_SelectOptionPlaceholder: "Valitse vaihtoehto",
    Form_Person_Placeholder: "Aloita nimen kirjoittaminen…",
    Form_Person_SuggestedPeopleAndGroups: "Ehdotetut henkilöt ja ryhmät",
    Form_Person_SuggestedPeople: "Ehdotetut henkilöt",
    Form_Person_NoPeopleOrGroups: "Henkilöitä tai ryhmiä ei löytynyt",
    Form_Person_NoPeople: "Henkilöitä ei löytynyt",
    Form_Person_Searching: "Haetaan…",
    Form_Ranking_Moved: "{item} siirrettiin sijalle {position}/{total}",
    Form_Ranking_MoveUp: "Siirrä ylös",
    Form_Ranking_MoveDown: "Siirrä alas",
    Form_Ranking_MoveItemUpAria: "Siirrä {item} ylös",
    Form_Ranking_MoveItemDownAria: "Siirrä {item} alas",
    Form_Rating_ValueText: "{value}/{max}",
    Form_Rating_NotRated: "Ei arvosteltu",
    Form_Rating_Clear: "Tyhjennä arvostelu",
    Form_RichText_Bold: "Lihavointi",
    Form_RichText_Italic: "Kursivointi",
    Form_RichText_Underline: "Alleviivaus",
    Form_RichText_BulletedList: "Luettelomerkit",
    Form_RichText_NumberedList: "Numerointi",
    Form_RichText_ClearFormatting: "Poista muotoilu",
    Form_RichText_ToolbarAria: "Tekstin muotoilu",
    Form_File_SizeBytes: "{size} t",
    Form_File_SizeKb: "{size} kt",
    Form_File_SizeMb: "{size} Mt",
    Form_File_SkippedLimit: "\"{name}\" ohitettiin – enimmäismäärä on {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" ei ole hyväksytty tyyppi.",
    Form_File_TooLarge: "\"{name}\" on suurempi kuin {size} Mt.",
    Form_File_AlreadyAttached: "\"{name}\" on jo liitetty.",
    Form_File_ReadError: "Yhtä tiedostoista ei voitu lukea. Yritä liittää se uudelleen.",
    Form_File_HintMaxSize: "enintään {size} Mt per tiedosto",
    Form_File_HintOneFile: "1 tiedosto",
    Form_File_HintMaxFiles: "enintään {count} tiedostoa",
    Form_File_Reading: "Luetaan tiedostoja…",
    Form_File_DropPrompt: "Pudota tiedostot tähän tai selaa napsauttamalla",
    Form_File_Remove: "Poista {name}",
    Form_Signature_Alt: "Allekirjoitus",
    Form_Signature_AriaSigned: "{label} – allekirjoitettu",
    Form_Signature_AriaEmpty: "{label} – tyhjä",
    Form_Signature_Clear: "Tyhjennä",
    Form_Signature_Signed: "Allekirjoitettu",
    Form_Signature_Prompt: "Allekirjoita yllä hiirellä, kynällä tai sormella",
    Form_Time_Placeholder: "Valitse kellonaika",
    Form_Field_DatePlaceholder: "Valitse päivämäärä",
    Form_Field_TimeAriaWithLabel: "{label} – kellonaika",
    Form_Field_TimeAria: "Kellonaika",
    Form_Field_OtherDefault: "Muu",
    Form_Field_SelectOptionsPlaceholder: "Valitse vaihtoehdot",
    Form_Field_PleaseSpecify: "Täsmennä",
    Form_Field_OtherSpecifyAria: "{label} – täsmennä",
    Form_Field_SelectOptionPlaceholder: "Valitse vaihtoehto",
    Form_Field_Yes: "Kyllä",
    Form_Field_No: "Ei",
    Form_Field_SliderHint: "Vastaa vetämällä liukusäädintä",
    Form_Field_WebAddressAriaWithLabel: "{label} – verkko-osoite",
    Form_Field_WebAddressAria: "Verkko-osoite",
    Form_Field_DisplayTextPlaceholder: "Näyttöteksti (valinnainen)",
    Form_Field_DisplayTextAriaWithLabel: "{label} – näyttöteksti",
    Form_Field_DisplayTextAria: "Näyttöteksti",
    Form_Field_ChooseBetween: "Valitse {min}–{max}",
    Form_Field_ChooseAtLeast: "Valitse vähintään {min}",
    Form_Field_ChooseUpTo: "Valitse enintään {max}",
    Form_Field_SelectedCount: "{count} valittu",
    Form_Field_RequiredAria: "(pakollinen)",
    Form_Submit_SaveError: "Vastaustasi ei voitu tallentaa. Varmista, että lomake on julkaistu suunnittelusta ja että sinulla on oikeus lisätä kohteita vastausluetteloon.",
    Form_Empty_Message: "Tässä lomakkeessa ei ole vielä kysymyksiä. Lomakkeen omistaja voi lisätä niitä Kysymykset-välilehdellä.",
    Form_Checking: "Tarkistetaan lomaketta…",
    Form_Closed_NotYetOpen: "Ei vielä avoinna",
    Form_Closed_AlreadyAnswered: "Jo vastattu",
    Form_Closed_Title: "Lomake suljettu",
    Form_Confirmation_PreviewNotice: "Tämä oli esikatselu – mitään ei tallennettu vastausluetteloon.",
    Form_Confirmation_PreviewAgain: "Esikatsele uudelleen",
    Form_Confirmation_SubmitAnother: "Lähetä uusi vastaus",
    Form_Wizard_StepFallback: "Vaihe {step}",
    Form_Wizard_StepsAria: "Lomakkeen vaiheet",
    Form_Wizard_StepOf: "Vaihe {step}/{total}",
    Form_ErrorSummary_Title: "Tarkista {count} vastausta:",
    Form_ErrorSummary_UntitledQuestion: "Nimetön kysymys",
    Form_ErrorSummary_Question: "Kysymys",
    Form_ErrorSummary_Detail: " – {message}",
    Form_Nav_Back: "Edellinen",
    Form_Nav_Next: "Seuraava",
    Form_Draft_Saving: "Tallennetaan…",
    Form_Draft_Saved: "Luonnos tallennettu",
    Form_Draft_SaveAndFinishLater: "Tallenna ja jatka myöhemmin",
    Form_Draft_NotSaved: "Luonnosta ei tallennettu",
    Form_Submit_Preview: "Lähetä (esikatselu)",
    Form_Submit_Button: "Lähetä",
    Form_Response_NoAnswer: "Ei vastausta",
    Form_Signature_TypeLabel: "Kirjoita koko nimesi",
    Form_Signature_TypeInstead: "Kirjoita nimesi sen sijaan",
    Form_Signature_DrawInstead: "Piirrä sen sijaan",
    Form_Edit_Button: "Muokkaa aiempaa vastaustasi",
    Form_Edit_Available: "Olet jo lähettänyt vastauksen. Voit muokata sitä uuden lähettämisen sijaan.",
    Form_Edit_Banner: "Muokkaat aiempaa vastaustasi.",
    Form_Edit_Save: "Päivitä vastaus",
    Form_Edit_UpdatedTitle: "Vastaus päivitetty",
    Form_Edit_UpdatedMessage: "Muutokset on tallennettu.",
    Form_Edit_LoadError: "Aiempaa vastaustasi ei voitu ladata. Yritä uudelleen.",
    Form_Draft_MissingFiles: "Liitä uudelleen: {names}. Näitä tiedostoja ei voitu palauttaa.",
    Form_Attachments_Failed: "Vastauksesi tallennettiin, mutta näitä liitteitä ei voitu ladata: {names}. Yritä uudelleen tai ota yhteyttä lomakkeen omistajaan.",
    Logic_ThisQuestion: "Tämä kysymys",
    Logic_Required: "{label} on pakollinen",
    Logic_RequiredConsent: "Jatka valitsemalla valintaruutu",
    Logic_RequiredFile: "Liitä vähintään yksi tiedosto",
    Logic_RequiredSignature: "Lisää allekirjoituksesi",
    Logic_RequiredLikert: "Vastaa jokaiseen riviin",
    Logic_InvalidEmail: "Anna kelvollinen sähköpostiosoite",
    Logic_InvalidPhone: "Anna kelvollinen puhelinnumero",
    Logic_InvalidUrl: "Anna kelvollinen verkko-osoite, joka alkaa merkinnällä http:// tai https://",
    Logic_MinValue: "Arvon on oltava vähintään {value}",
    Logic_MaxValue: "Arvo saa olla enintään {value}",
    Logic_MaxLength: "Enimmäispituus on {max} merkkiä",
    Logic_ChooseAtLeastOne: "Valitse vähintään {count} vaihtoehto",
    Logic_ChooseAtLeastMany: "Valitse vähintään {count} vaihtoehtoa",
    Logic_ChooseAtMostOne: "Valitse enintään {count} vaihtoehto",
    Logic_ChooseAtMostMany: "Valitse enintään {count} vaihtoehtoa",
    Logic_LikertRemaining: "Vastaa jokaiseen riviin ({count} jäljellä)",
    Logic_MaxFilesOne: "Liitä enintään {count} tiedosto",
    Logic_MaxFilesMany: "Liitä enintään {count} tiedostoa",
    Logic_FileTooLarge: "\"{name}\" on suurempi kuin {size} Mt",
    Logic_FileTypeNotAccepted: "\"{name}\" ei ole hyväksytty tiedostotyyppi ({types})",
    Logic_AddressRequired: "Anna vähintään katuosoite ja kaupunki",
    Logic_PatternDefault: "Vastaus ei ole odotetussa muodossa",
    Logic_Yes: "Kyllä",
    Logic_No: "Ei",
    Logic_Agreed: "Hyväksytty",
    Logic_NotAgreed: "Ei hyväksytty",
    Logic_Signed: "Allekirjoitettu",
    Logic_NoAnswer: "(ei vastausta)",
    Logic_Unknown: "(tuntematon)",
    Logic_OtherSlice: "Muut ({count})",
    Logic_CsvResponseId: "Vastauksen tunnus",
    Logic_CsvSubmitted: "Lähetetty",
    Logic_CsvSubmittedBy: "Lähettäjä",
    Logic_EmailQuestion: "Kysymys",
    Logic_EmailViewItem: "Näytä Microsoft Listsissä",
    Logic_EmailFooter: "Smart Forms lähetti tämän automaattisesti.",
    Logic_ClosedDefault: "Tämä lomake ei enää vastaanota vastauksia.",
    Logic_NotYetOpen: "Tämä lomake avautuu {date}.",
    Logic_AlreadyResponded: "Olet jo vastannut tähän lomakkeeseen. Kiitos!",
    Logic_UntitledQuestion: "Nimetön kysymys",
    Logic_Issue_NoQuestions: "Lisää vähintään yksi kysymys ennen vastausten keräämistä.",
    Logic_Issue_NoTitle: "Kysymyksellä ei ole tekstiä – se nimetään automaattisesti julkaisun yhteydessä.",
    Logic_Issue_DuplicateTitle: "{label} on samanniminen kuin toinen kysymys, mikä vaikeuttaa tulosten lukemista.",
    Logic_Issue_NeedTwoOptions: "{label} tarvitsee vähintään kaksi vaihtoehtoa.",
    Logic_Issue_ImageNoImage: "{label} sisältää vaihtoehtoja ilman kuvaa – ne näytetään tekstiruutuina.",
    Logic_Issue_LikertNeedRow: "{label} tarvitsee vähintään yhden rivin.",
    Logic_Issue_LikertNeedColumns: "{label} tarvitsee vähintään kaksi asteikkosaraketta.",
    Logic_Issue_NoLookupList: "{label}: lähdeluetteloa ei ole valittu.",
    Logic_Issue_NoFormula: "{label}: kaavaa ei ole määritetty.",
    Logic_Issue_BadFormula: "{label}: kaavaa ei voida laskea. Tarkista sulkeet ja operaattorit.",
    Logic_Issue_MissingRefs: "{label} viittaa kysymyksiin, joita ei ole: {names}.",
    Logic_Issue_BadPattern: "{label}: vahvistusmalli on virheellinen.",
    Logic_Issue_BrokenRule: "{label}: haarautumissääntö viittaa poistettuun kysymykseen.",
    Logic_Issue_SelfRule: "{label}: haarautumissääntö viittaa itseensä.",
    Logic_Issue_RuleMismatch: "{label}: haarautumissääntö ei enää sovi kysymykseen, josta se riippuu.",
    Logic_Issue_RequiredReadOnly: "{label} on sekä pakollinen että vain luku -tilassa, joten siihen voi vastata vain esitäytetyn linkin kautta.",
    Logic_Issue_EmptySection: "Osiossa ei ole kysymyksiä, ja se ohitetaan.",
    Logic_Issue_CloseBeforeOpen: "Sulkeutumispäivä on avautumispäivä tai sitä ennen, joten lomake ei koskaan ota vastaan vastauksia.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Hyväksyntäsähköpostit on otettu käyttöön, mutta hyväksyntävaihe ei ole päällä.",
    Logic_Op_equals: "on",
    Logic_Op_notEquals: "ei ole",
    Logic_Op_contains: "sisältää",
    Logic_Op_notContains: "ei sisällä",
    Logic_Op_notEmpty: "on vastattu",
    Logic_Op_empty: "ei ole vastattu",
    Logic_Op_greaterThan: "on suurempi kuin",
    Logic_Op_greaterOrEqual: "on vähintään",
    Logic_Op_lessThan: "on pienempi kuin",
    Logic_Op_lessOrEqual: "on enintään",
    Logic_Op_between: "on välillä",
    Logic_Op_before: "on ennen",
    Logic_Op_after: "on jälkeen",
    Logic_Type_Text: "Lyhyt vastaus",
    Logic_TypeDesc_Text: "Yksi tekstirivi",
    Logic_Category_Text: "Teksti",
    Logic_Type_MultilineText: "Pitkä vastaus",
    Logic_TypeDesc_MultilineText: "Useita rivejä pelkkää tekstiä",
    Logic_Type_RichText: "Muotoiltu teksti",
    Logic_TypeDesc_RichText: "Lihavointi, luettelot ja linkit",
    Logic_Type_Choice: "Valinta",
    Logic_TypeDesc_Choice: "Valitse vaihtoehtoluettelosta",
    Logic_Category_Choice: "Valinta",
    Logic_Type_ImageChoice: "Kuvavalinta",
    Logic_TypeDesc_ImageChoice: "Valitse kuvaruuduista",
    Logic_Type_Lookup: "Haku luettelosta",
    Logic_TypeDesc_Lookup: "Vaihtoehdot luetaan reaaliaikaisesti toisesta SharePoint-luettelosta",
    Logic_Type_YesNo: "Kyllä / Ei",
    Logic_TypeDesc_YesNo: "Yksinkertainen päälle/pois-kytkin",
    Logic_Type_Consent: "Suostumus",
    Logic_TypeDesc_Consent: "Valintaruutu, joka vastaajan on valittava jatkaakseen",
    Logic_Type_Ranking: "Asettaminen järjestykseen",
    Logic_TypeDesc_Ranking: "Vedä vaihtoehdot paremmuusjärjestykseen",
    Logic_Type_Rating: "Arvostelu",
    Logic_TypeDesc_Rating: "Tähtiä, sydämiä tai peukkuja",
    Logic_Category_Scales: "Asteikot",
    Logic_Type_Scale: "Mielipideasteikko",
    Logic_TypeDesc_Scale: "Numeroitu asteikko nimetyin ääripäin",
    Logic_Type_Slider: "Liukusäädin",
    Logic_TypeDesc_Slider: "Arvo liukuasteikolla",
    Logic_Type_Likert: "Likert-ruudukko",
    Logic_TypeDesc_Likert: "Arvioi useita väittämiä yhdellä jaetulla asteikolla",
    Logic_Type_Number: "Numero",
    Logic_TypeDesc_Number: "Tavallinen luku, valuutta tai prosentti",
    Logic_Category_Advanced: "Lisäasetukset",
    Logic_Type_Calculated: "Laskettu",
    Logic_TypeDesc_Calculated: "Vain luku -summa, joka lasketaan muista vastauksista",
    Logic_Type_Date: "Päivämäärä",
    Logic_TypeDesc_Date: "Kalenteripäivä, valinnaisesti kellonajalla",
    Logic_Category_Date: "Päivämäärä",
    Logic_Type_Time: "Aika",
    Logic_TypeDesc_Time: "Pelkkä kellonaika",
    Logic_Type_Person: "Henkilö",
    Logic_TypeDesc_Person: "Valitse joku organisaatiosta",
    Logic_Category_People: "Henkilöt",
    Logic_Type_Email: "Sähköposti",
    Logic_TypeDesc_Email: "Sähköpostiosoite, jonka oikeellisuus tarkistetaan",
    Logic_Type_Phone: "Puhelin",
    Logic_TypeDesc_Phone: "Puhelinnumero, jonka oikeellisuus tarkistetaan",
    Logic_Type_Address: "Osoite",
    Logic_TypeDesc_Address: "Katu, kaupunki, postinumero ja maa",
    Logic_Type_Hyperlink: "Linkki",
    Logic_TypeDesc_Hyperlink: "Verkko-osoite",
    Logic_Type_FileUpload: "Tiedoston lataus",
    Logic_TypeDesc_FileUpload: "Liitä vastaukseen yksi tai useampi tiedosto",
    Logic_Type_Signature: "Allekirjoitus",
    Logic_TypeDesc_Signature: "Allekirjoita hiirellä, kynällä tai sormella",
    Logic_Type_Content: "Tekstilohko",
    Logic_TypeDesc_Content: "Ohjeita tai kuva – ei kerää vastausta",
    Logic_Category_Layout: "Asettelu",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Kuinka todennäköisesti suosittelisit…",
    Logic_Preset_satisfaction: "Tyytyväisyys (1–5)",
    Logic_PresetDesc_satisfaction: "Erittäin tyytymätön – erittäin tyytyväinen",
    Logic_Preset_currency: "Valuutta",
    Logic_PresetDesc_currency: "Rahamäärä",
    Logic_Preset_percent: "Prosentti",
    Logic_PresetDesc_percent: "Prosenttiarvo",
    Logic_Template_blank_Name: "Tyhjä lomake",
    Logic_Template_blank_Description: "Aloita tyhjästä",
    Logic_Template_feedback_Name: "Asiakaspalaute",
    Logic_Template_feedback_Description: "NPS, arvostelut ja avoimet kommentit",
    Logic_Template_event_Name: "Tapahtumailmoittautuminen",
    Logic_Template_event_Description: "Osallistujatiedot, istunnot ja ruokavaliotarpeet",
    Logic_Template_itrequest_Name: "IT-palvelupyyntö",
    Logic_Template_itrequest_Description: "Luokitellut pyynnöt, prioriteetti ja liitteet",
    Logic_Template_expense_Name: "Kulukorvaus",
    Logic_Template_expense_Description: "Rivikohdat, kuitit ja laskettu loppusumma",
    Logic_Template_pulse_Name: "Henkilöstön pulssikysely",
    Logic_Template_pulse_Description: "Likert-ruudukko, sitoutumisasteikko ja anonymiteettihuomautus",
    Logic_Template_safety_Name: "Turvallisuustarkastus",
    Logic_Template_safety_Description: "Tarkistuslista, valokuvat ja allekirjoitus",
    Logic_Template_booking_Name: "Huoneen tai resurssin varaus",
    Logic_Template_booking_Description: "Hakuun perustuva resurssinvalitsin ja aikaväli",
    Charts_ColumnChartAria: "Pylväskaavio, jossa on {count} luokkaa",
    Charts_DonutChartAria: "Rengaskaavio, jossa on {count} luokkaa",
    Charts_NoAnswers: "Ei vielä vastauksia.",
    Charts_NoResponses: "Ei vielä vastauksia.",
    Charts_Responses: "Vastaukset",
    Charts_ResponsesOverTime: "Vastaukset ajan mittaan",
    Responses_Chart_Answer: "Vastaus",
    Responses_Chart_Average: "Keskiarvo",
    Responses_Chart_AverageOf: "Keskiarvo ({count})",
    Responses_Chart_AveragePosition: "Keskimääräinen sijoitus",
    Responses_Chart_AverageRange: "Keskiarvo (1–{max})",
    Responses_Chart_AvgValue: "ka. {value}",
    Responses_Chart_Detractors: "Arvostelijat (0–6)",
    Responses_Chart_Max: "Maks.",
    Responses_Chart_Maximum: "Enimmäisarvo",
    Responses_Chart_Median: "Mediaani",
    Responses_Chart_MentionOne: "{count} maininta",
    Responses_Chart_MentionOther: "{count} mainintaa",
    Responses_Chart_Min: "Min.",
    Responses_Chart_Minimum: "Vähimmäisarvo",
    Responses_Chart_NoAnswers: "Ei vielä vastauksia.",
    Responses_Chart_NoNumeric: "Ei vielä numeerisia vastauksia.",
    Responses_Chart_NoRankings: "Ei vielä sijoituksia.",
    Responses_Chart_NoScores: "Ei vielä pisteitä.",
    Responses_Chart_NotEnoughText: "Tekstiä ei vielä ole tarpeeksi tiivistettäväksi.",
    Responses_Chart_NpsScore: "NPS-pistemäärä",
    Responses_Chart_Option: "Vaihtoehto",
    Responses_Chart_Passives: "Passiiviset (7–8)",
    Responses_Chart_Promoters: "Suosittelijat (9–10)",
    Responses_Chart_ResponseOne: "vastaus",
    Responses_Chart_ResponseOther: "vastausta",
    Responses_Chart_Responses: "Vastaukset",
    Responses_Chart_ShowingAnswers: "Näytetään {shown}/{total} vastausta.",
    Responses_Chart_Statement: "Väittämä",
    Responses_Chart_Statistic: "Tunnusluku",
    Responses_Chart_StdDev: "Keskihajonta",
    Responses_Chart_StdDeviation: "Keskihajonta",
    Responses_Chart_Total: "Yhteensä",
    Responses_Chart_Value: "Arvo",
    Responses_Dashboard_AllHidden: "Kaikki kysymykset on piilotettu koontinäkymästä. Palauta ne valitsemalla ”Näytä piilotetut kysymykset”.",
    Responses_Dashboard_AnsweredOf: "{answered}/{total} vastattu",
    Responses_Dashboard_AnsweredOfPinned: "{answered}/{total} vastattu · kiinnitetty",
    Responses_Dashboard_AveragedAcrossResponses: "Vastausten keskiarvo",
    Responses_Dashboard_ByDay: "Päivittäin",
    Responses_Dashboard_ByMonth: "Kuukausittain",
    Responses_Dashboard_ByWeek: "Viikoittain",
    Responses_Dashboard_ChartAuto: "Automaattinen",
    Responses_Dashboard_ChartBars: "Palkit",
    Responses_Dashboard_ChartColumns: "Pylväät",
    Responses_Dashboard_ChartDonut: "Rengas",
    Responses_Dashboard_ChartGauge: "Mittari",
    Responses_Dashboard_ChartHistogram: "Histogrammi",
    Responses_Dashboard_ChartOptions: "Kaavion asetukset",
    Responses_Dashboard_ChartOptionsFor: "Kaavion asetukset: {title}",
    Responses_Dashboard_ChartStatistics: "Tilastot",
    Responses_Dashboard_ChartTable: "Taulukko",
    Responses_Dashboard_ChartWordFrequency: "Sanojen esiintymistiheys",
    Responses_Dashboard_EmptyBody: "Kun ihmiset alkavat vastata, tämä koontinäkymä täyttyy automaattisesti – pääluvut, vastausten aikajana ja kaavio seuraamisen arvoisista kysymyksistä.",
    Responses_Dashboard_EmptyTitle: "Ei vielä vastauksia",
    Responses_Dashboard_Hide: "Piilota koontinäkymästä",
    Responses_Dashboard_Highlights: "Kohokohdat",
    Responses_Dashboard_Last7Days: "Viimeiset 7 päivää",
    Responses_Dashboard_LatestDate: "Viimeisin {date}",
    Responses_Dashboard_MedianTimeToComplete: "Täyttöajan mediaani",
    Responses_Dashboard_NoPriorWeek: "Ei edellistä viikkoa vertailtavaksi",
    Responses_Dashboard_OneEach: "Yksi kutakin",
    Responses_Dashboard_Pin: "Kiinnitä koontinäkymään",
    Responses_Dashboard_QuestionFallback: "kysymys",
    Responses_Dashboard_QuestionsAnswered: "Vastatut kysymykset",
    Responses_Dashboard_RecordedOnSubmit: "Tallennetaan lähetettäessä",
    Responses_Dashboard_RepeatResponses: "{count} toistuvaa vastausta",
    Responses_Dashboard_ResponsesOverTime: "Vastaukset ajan mittaan",
    Responses_Dashboard_ShowHidden: "Näytä piilotetut kysymykset",
    Responses_Dashboard_SinceMidnight: "Keskiyöstä lähtien",
    Responses_Dashboard_Today: "Tänään",
    Responses_Dashboard_TotalResponses: "Vastauksia yhteensä",
    Responses_Dashboard_UniqueRespondents: "Yksilölliset vastaajat",
    Responses_Dashboard_Unpin: "Poista kiinnitys koontinäkymästä",
    Responses_Dashboard_UntitledQuestion: "Nimetön kysymys",
    Responses_Dashboard_VsPrevious7Days: "verrattuna edellisiin 7 päivään",
    Responses_Detail_Answers: "Vastaukset",
    Responses_Detail_AsTheForm: "Lomakkeen mukaan",
    Responses_Detail_Cancel: "Peruuta",
    Responses_Detail_Delete: "Poista",
    Responses_Detail_DeleteBody: "Luettelokohde siirretään sivuston roskakoriin, josta se voidaan palauttaa.",
    Responses_Detail_DeleteTitle: "Poistetaanko tämä vastaus?",
    Responses_Detail_Deleting: "Poistetaan…",
    Responses_Detail_Draft: "Luonnos",
    Responses_Detail_Header: "Vastaus {index}/{total}",
    Responses_Detail_LoadingAttachments: "Ladataan liitteitä…",
    Responses_Detail_Next: "Seuraava vastaus",
    Responses_Detail_NoAnswer: "Ei vastausta",
    Responses_Detail_Previous: "Edellinen vastaus",
    Responses_Detail_Print: "Tulosta",
    Responses_Detail_Signature: "Allekirjoitus",
    Responses_Detail_Signed: "Allekirjoitettu",
    Responses_Detail_Took: "kesti {duration}",
    Responses_Summary_AnsweredOfType: "{answered}/{total} vastattu · {type}",
    Responses_Summary_ByField: "Kentän {title} mukaan",
    Responses_Summary_CompareBy: "Vertaile…",
    Responses_Summary_EmptyBody: "Jokaiselle kysymykselle tulee tähän oma yhteenvetonsa.",
    Responses_Summary_NoComparison: "Ei vertailua",
    Responses_Summary_NothingToCompare: "Kukaan ei vastannut kysymykseen ”{title}”, joten vertailtavaa ei ole.",
    Responses_Summary_OtherNote: "Kaavioissa, joissa on yli {max} luokkaa, pienimmät ryhmitellään luokkaan ”Muu” – näet kaikki arvot vaihtamalla kortin Taulukko-näkymään.",
    Responses_Summary_ResponseCountOne: "{count} vastaus",
    Responses_Summary_ResponseCountOther: "{count} vastausta",
    Responses_Summary_SeeAllAnswers: "Näytä kaikki vastaukset taulukossa",
    Responses_Summary_SegmentNote: "Näytetään {groups} suurinta ryhmää. Vastaus, jossa on valittu useita vaihtoehtoja, näkyy jokaisessa vastaavassa ryhmässä, joten ryhmien summat voivat olla suurempia kuin {total}.",
    Responses_Summary_SplitBy: "Jaottelu: {title}",
    Responses_Summary_Untitled: "nimetön",
    Responses_Table_Apply: "Käytä",
    Responses_Table_Cancel: "Peruuta",
    Responses_Table_ClearSelection: "Tyhjennä valinta",
    Responses_Table_ColumnOrder: "Sarakkeiden järjestys",
    Responses_Table_ColumnsCount: "Sarakkeet ({shown}/{total})",
    Responses_Table_Delete: "Poista",
    Responses_Table_DeleteBody: "Luettelokohteet siirretään sivuston roskakoriin, josta ne voidaan palauttaa.",
    Responses_Table_DeleteSelected: "Poista valitut",
    Responses_Table_DeleteTitleOne: "Poistetaanko {count} vastaus?",
    Responses_Table_DeleteTitleOther: "Poistetaanko {count} vastausta?",
    Responses_Table_Deleting: "Poistetaan…",
    Responses_Table_MoveDown: "Siirrä alas",
    Responses_Table_MoveDownFor: "Siirrä {title} alas",
    Responses_Table_MoveUp: "Siirrä ylös",
    Responses_Table_MoveUpFor: "Siirrä {title} ylös",
    Responses_Table_NoColumns: "Kysymyssarakkeita ei ole vielä näkyvissä.",
    Responses_Table_NoMatch: "Mikään vastaus ei vastaa nykyisiä suodattimia.",
    Responses_Table_NothingToShow: "Ei näytettävää",
    Responses_Table_OpenResponse: "Avaa tämä vastaus",
    Responses_Table_OrderNote: "Lähetetty ja Lähettäjä ovat aina ensin. Vetojärjestys koskee kysymyssarakkeita.",
    Responses_Table_Reorder: "Järjestä uudelleen",
    Responses_Table_ResetColumns: "Palauta sarakkeet",
    Responses_Table_SelectResponse: "Valitse tämä vastaus",
    Responses_Table_SelectedOne: "{count} vastaus valittu",
    Responses_Table_SelectedOther: "{count} vastausta valittu",
    Responses_Table_ShowAll: "Näytä kaikki",
    Responses_Table_ShowTheseQuestions: "Näytä nämä kysymykset",
    Responses_Table_Submitted: "Lähetetty",
    Responses_Table_SubmittedBy: "Lähettäjä",
    Responses_Table_ToggleSelection: "Vaihda valinta",
    Responses_Table_Unknown: "Tuntematon",
    Responses_Table_Untitled: "Nimetön",
    Responses_View_AllTime: "Koko ajalta",
    Responses_View_AnyAnswer: "Mikä tahansa vastaus",
    Responses_View_Clear: "Tyhjennä",
    Responses_View_CopyShareLink: "Kopioi jakolinkki",
    Responses_View_CountFiltered: "{shown}/{total} vastausta",
    Responses_View_CountOne: "{count} vastaus",
    Responses_View_CountOther: "{count} vastausta",
    Responses_View_Dashboard: "Koontinäkymä",
    Responses_View_DateRange: "Aikaväli",
    Responses_View_EmptyBody: "Jaa lomake aloittaaksesi vastausten keräämisen. Vastaukset tallennetaan luetteloon ”{list}” ja näkyvät täällä heti.",
    Responses_View_EmptyTitle: "Ei vielä vastauksia",
    Responses_View_ExportCsv: "Vie CSV-tiedostoon",
    Responses_View_FilterByAnswer: "Suodata vastauksen mukaan",
    Responses_View_FilterByQuestion: "Suodata kysymyksen mukaan",
    Responses_View_FilterValue: "Suodattimen arvo",
    Responses_View_Last30Days: "Viimeiset 30 päivää",
    Responses_View_Last7Days: "Viimeiset 7 päivää",
    Responses_View_Last90Days: "Viimeiset 90 päivää",
    Responses_View_LoadError: "Vastauksia ei voitu ladata. Julkaise lomake kerran, jotta luettelosarakkeet ovat olemassa, ja yritä sitten uudelleen.",
    Responses_View_Loading: "Ladataan vastauksia…",
    Responses_View_MoreActions: "Lisää vastaustoimintoja",
    Responses_View_PreviewForm: "Esikatsele lomaketta",
    Responses_View_Refresh: "Päivitä",
    Responses_View_ResponsesTab: "Vastaukset ({count})",
    Responses_View_SearchPlaceholder: "Hae kaikista vastauksista",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Valitse arvo",
    Responses_View_Summary: "Yhteenveto",
    Responses_View_Today: "Tänään",
    Responses_View_Truncated: "Tässä luettelossa on enemmän vastauksia kuin Smart Forms lataa kerralla. Näytetään uusimmat {count} – avaa luettelo Microsoft Listsissä nähdäksesi kaikki.",
    Responses_View_TryAgain: "Yritä uudelleen",
    Responses_View_Untitled: "Nimetön",
    Responses_Approval_Column: "Hyväksyntä",
    Responses_Approval_ReviewerColumn: "Tarkastaja",
    Responses_Approval_CommentColumn: "Tarkastajan kommentti",
    Responses_Approval_Pending: "Odottaa",
    Responses_Approval_Approved: "Hyväksytty",
    Responses_Approval_Rejected: "Hylätty",
    Responses_Approval_AnyStatus: "Mikä tahansa hyväksyntätila",
    Responses_Approval_FilterLabel: "Suodata hyväksyntätilan mukaan",
    Responses_Approval_ApproveSelected: "Hyväksy valitut",
    Responses_Approval_RejectSelected: "Hylkää valitut",
    Responses_Approval_BulkFailed: "{count} vastauksen päivitys epäonnistui. Yritä uudelleen.",
    Responses_Approval_Approve: "Hyväksy",
    Responses_Approval_Reject: "Hylkää",
    Responses_Approval_Reset: "Palauta odottavaksi",
    Responses_Approval_CommentLabel: "Kommentti (valinnainen)",
    Responses_Approval_ReviewedBy: "Tarkastaja: {name}",
    Responses_Approval_Error: "Päätöstä ei voitu tallentaa. Yritä uudelleen.",
    Responses_Dashboard_ApprovalStatus: "Odottaa tarkastusta",
    Responses_Dashboard_ApprovalBreakdown: "{pending} odottaa, {approved} hyväksytty, {rejected} hylätty",
    Responses_Dashboard_TimelineCoarsened: "Ajanjakso on pitkä, joten aikajana ryhmiteltiin karkeammin ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Ajanjakso on hyvin pitkä, joten vain viimeisimmät {count} jaksoa näytetään.",
    Service_Item_DefaultTitle: "Vastaus – {date}",
    Service_Email_ApprovalSubject: "Vastauksesi tila: {status} — {title}",
    Service_Email_ApprovalHeading: "Vastauksesi tila: {status}",
    Service_Email_ApprovalIntro: "Tarkastaja merkitsi vastauksesi lomakkeeseen \"{title}\" tilaan: {status}.",
    Service_Email_ApprovalCommentLabel: "Tarkastajan kommentti",
    Service_Approval_Approved: "hyväksytty",
    Service_Approval_Rejected: "hylätty",
    Service_Approval_Pending: "odottaa",
    Service_Lookup_InvalidFilter: "Hakusuodatin ei kelpaa.",
    Service_Edit_NotAllowed: "Tämä lomake ei salli lähetetyn vastauksen muokkaamista.",
    Service_Edit_NotYours: "Voit muokata vain omaa vastaustasi.",
    Service_Signature_AttachmentLabel: "Allekirjoitus",
    PropertyPane_ListsLoadFailed: "Tämän sivuston luetteloita ei voitu ladata.",
    PropertyPane_EnterListName: "Anna ensin uuden luettelon nimi.",
    PropertyPane_CreatingList: "Luodaan luetteloa \"{name}\"…",
    PropertyPane_ListCreated: "Luettelo \"{title}\" luotu ja valittu.",
    PropertyPane_ListAlreadyExists: "Luettelo nimeltä \"{name}\" on jo olemassa – valitse se yllä olevasta avattavasta luettelosta.",
    PropertyPane_CreateListFailed: "Luetteloa ei voitu luoda. Tarkista, että sinulla on oikeus luoda luetteloita tällä sivustolla.",
    PropertyPane_Description: "Valitse SharePoint-luettelo, johon lomakkeen vastaukset tallennetaan, tai luo uusi. Kaikkea muuta – kysymyksiä, ulkoasua ja ilmoituksia – muokataan suoraan sivulla.",
    PropertyPane_ResponseList_GroupName: "Vastausluettelo",
    PropertyPane_ListDropdown_Label: "Tallenna vastaukset tähän luetteloon",
    PropertyPane_ResponsesGoTo: "Vastaukset tallennetaan luetteloon \"{name}\".",
    PropertyPane_PickList: "Valitse luettelo tai luo sellainen alla.",
    PropertyPane_LoadingLists: "Ladataan luetteloita…",
    PropertyPane_NewListName_Label: "Tai luo uusi luettelo",
    PropertyPane_NewListName_Placeholder: "Uuden luettelon nimi",
    PropertyPane_CreateList_Button: "Luo luettelo",
    PropertyPane_Tips_GroupName: "Vinkit",
    PropertyPane_Tip_AutoSave: "Kysymykset ja asetukset tallentuvat automaattisesti muokatessasi – sivua ei tarvitse tallentaa tai julkaista.",
    PropertyPane_Tip_Permissions: "Vastaajilla on oltava oikeus lisätä kohteita vastausluetteloon. Tarkista luettelon käyttöoikeudet, jos joku ilmoittaa virheestä lähetettäessä.",
    PropertyPane_Tip_Share: "Valitse sivulla ”Kerää vastauksia” luodaksesi luettelosarakkeet ja saadaksesi jaettavan täyttölinkin.",
    App_ErrorBoundary_Title: "Smart Forms – Renderöintivirhe",
    App_ErrorBoundary_Message: "Viesti:",
    App_ErrorBoundary_Stack: "Pino:",
    App_ErrorBoundary_NoStack: "(pinoa ei saatavilla)",
    App_ErrorBoundary_ConsoleNote: "Kaikki tiedot kirjoitettiin myös selaimen konsoliin.",
    App_DefaultQuestionTitle: "Kysymys {number}",
    App_Error_ListMissing: "Tälle lomakkeelle määritettyä luetteloa ei enää ole. Valitse toinen luettelo verkkopalan asetuksista.",
    App_Error_LoadConfig: "Lomakkeen määritysten lataamisessa tapahtui virhe.",
    App_Error_Unable: "Lomaketta ei voi ladata.",
    App_Publish_ConflictNotice: "Kysymyksellä \"{title}\" on jo eri tyyppinen luettelosarake ({type}). Nimeä kysymys uudelleen, jotta uusi sarake voidaan luoda, tai vaihda sen tyyppi takaisin.",
    App_Publish_ConflictUnnamedQuestion: "kysymys",
    App_Publish_ColumnsAddedOne: "{count} sarake lisättiin luetteloon \"{list}\".",
    App_Publish_ColumnsAddedOther: "{count} saraketta lisättiin luetteloon \"{list}\".",
    App_Publish_TheList: "luettelo",
    App_Publish_UpToDate: "Vastausluettelo on jo ajan tasalla.",
    App_Publish_Error: "Luettelosarakkeita ei voitu luoda. Yleensä syynä on, ettei sinulla ole Hallitse luetteloita -oikeutta vastausluetteloon, mutta virhe voi ilmetä myös sivustoilla, joilla mukautettu komentosarjojen käyttö on poistettu käytöstä. Tarkista taustalla oleva virhe selaimen konsolista tai yritä uudelleen.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Rakenna viimeistelty lomake SharePoint-luettelon päälle – {count} kysymystyyppiä, haarautumislogiikka, tiedostojen lataukset, jaettavat täyttölinkit ja tulosten koontinäkymä.",
    App_Placeholder_ChooseList: "Valitse tai luo luettelo",
    App_Placeholder_Hint: "Aloita muokkaamalla sivua ja määrittämällä tämä verkkopala.",
    App_Loading: "Ladataan lomaketta…",
    App_OpenSettings: "Avaa asetukset",
    App_Tab_Questions: "Kysymykset",
    App_Tab_QuestionsWithCount: "Kysymykset ({count})",
    App_Tab_Responses: "Vastaukset",
    App_Tab_Responses_Title: "Vastaukset tallennetaan luetteloon \"{list}\"",
    App_Templates_Start: "Aloita mallista",
    App_Settings_Title: "Lomakkeen asetukset – ulkoasu, ilmoitukset, käyttöoikeudet",
    App_Settings_AriaLabel: "Lomakkeen asetukset",
    App_Preview: "Esikatselu",
    App_Preview_Close: "Sulje esikatselu",
    App_Preview_Hint: "Esikatselu – mitään tässä lähettämääsi ei tallenneta. Vahvistus ja haarautuminen toimivat täsmälleen samoin kuin vastaajille.",
    App_Publish_GettingReady: "Valmistellaan…",
    App_Publish_CollectResponses: "Kerää vastauksia",
    App_Publish_Share: "Jaa",
    App_Retry: "Yritä uudelleen",
    App_SaveError_Banner: "Viimeisintä muutosta ei voitu tallentaa. Tarkista yhteytesi ja yritä uudelleen.",
    App_Preflight_BlockingTitle: "Korjaa nämä ennen keräämistä",
    App_Preflight_WarningTitle: "Kannattaa tarkistaa ensin",
    App_Preflight_BlockingText: "Nämä estäisivät julkaistun lomakkeen toimimisen kunnolla.",
    App_Preflight_WarningText: "Mikään ei ole rikki, mutta nämä kannattaa yleensä korjata ennen linkin jakamista.",
    App_Preflight_GoTo: "Siirry",
    App_Preflight_CollectAnyway: "Kerää vastauksia silti",
    App_Preflight_Back: "Takaisin lomakkeeseen",
    App_Cancel: "Peruuta",
    App_Done: "Valmis",
    App_Share_Title: "Lomake on valmis jaettavaksi",
    App_Share_SubText: "Lähetä tämä linkki kaikille, joiden pitäisi täyttää lomake.",
    App_Share_LinkAriaLabel: "Jakolinkki",
    App_Share_Copy: "Kopioi",
    App_Share_Copied: "Kopioitu",
    App_Share_AddItemsEmphasis: "lisätä kohteita",
    App_Share_PermissionNote: "Vastaajilla on oltava oikeus {addItems} luetteloon ”{title}” sekä pääsy tälle sivulle. Jos joku saa virheen lähettäessään, syy on lähes aina tämä.",
    App_Share_PrefillNote: "Voit esitäyttää kysymyksiä linkissä lisäämällä sarakkeen nimen, esimerkiksi {example}.",
    App_Templates_ReplaceWarning: "Mallin valitseminen korvaa nykyiset kysymyksesi.",
    App_Templates_PickStart: "Valitse lähtökohta – voit muuttaa kaikkea jälkeenpäin.",
    App_Templates_Empty: "Tyhjä",
    App_Templates_QuestionCount: "{count} kysymystä",
    App_SaveChip_SavingTitle: "Tallennetaan viimeisintä muokkausta",
    App_SaveChip_Saving: "Tallennetaan…",
    App_SaveChip_FailedTitle: "Viimeisintä muokkausta ei voitu tallentaa. Tarkista yhteytesi ja yritä uudelleen.",
    App_SaveChip_Failed: "Tallennus epäonnistui",
    App_SaveChip_SavedTitle: "Kaikki muutokset on tallennettu",
    App_SaveChip_Saved: "Tallennettu",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Uusi vastaus – {title}",
    Service_Email_NewResponseHeading: "Uusi vastaus: {title}",
    Service_Email_NewResponseIntro: "Joku lähetti juuri vastauksen – {date}.",
    Service_Email_ReceiptSubject: "Vastauksesi – {title}",
    Service_Email_ReceiptHeading: "Kiitos vastauksestasi!",
    Service_Email_ReceiptIntro: "Tässä on kopio lomakkeeseen \"{title}\" lähettämästäsi vastauksesta.",
    App_History_Title: "Versiohistoria",
    App_History_RestoredNotice: "Tallennettu versio {date} palautettiin. Tarkista se ja julkaise mahdolliset uudet kysymykset Kerää vastauksia -toiminnolla.",
    App_History_Undo: "Kumoa palautus",
    App_Share_CopyManual: "Selain esti kopioinnin. Valitse yllä oleva linkki ja kopioi se painamalla Ctrl+C (Macissa Cmd+C).",
    App_Share_TeamsNote: "Käytät Microsoft Teamsia. Tämä linkki avaa SharePoint-sivun suoraan, joten vastaanottajilla on oltava käyttöoikeus sivustoon.",
    App_Share_PrefillNotSecure: "Esitäytetyt vastaukset ovat vain mukavuustoiminto: kuka tahansa linkin saanut voi muuttaa niitä, joten älä koskaan pidä niitä suojausrajana.",
    Designer_Section_DropHere: "Pudota kysymys tähän",
    Designer_Section_DropEnd: "Pudota tähän siirtääksesi osion loppuun",
    Designer_Rules_RemovedOne: "1 haarautumissääntö, joka ei enää sopinut, poistettiin.",
    Designer_Rules_RemovedOther: "{count} haarautumissääntöä, jotka eivät enää sopineet, poistettiin.",
    Designer_Settings_AllowEdit: "Salli vastaajien muokata vastaustaan",
    Designer_Settings_AllowEditHint: "Vastaajat voivat avata lähettämänsä vastauksen uudelleen ja päivittää sen. Jokainen voi muokata vain omaa vastaustaan.",
    Designer_Settings_EnableApproval: "Ota käyttöön hyväksyntätyönkulku",
    Designer_Settings_ApprovalNotify: "Lähetä vastaajalle sähköposti päätöksestä",
    Designer_Settings_ApprovalHint: "Lisää hyväksyntäsarakkeet vastausluetteloon seuraavan julkaisun yhteydessä. Omistajat hyväksyvät tai hylkäävät vastauksia Vastaukset-välilehdellä.",
    Designer_History_Title: "Versiohistoria",
    Designer_History_Intro: "Tämän lomakkeen kysymysten ja asetusten aiemmin tallennetut versiot. Palautus lataa version suunnittelijaan; sen voi kumota, ja uudet kysymykset luodaan vasta julkaistaessa.",
    Designer_History_Loading: "Ladataan versioita...",
    Designer_History_Empty: "Aiempia versioita ei löytynyt. Versiohistoria edellyttää, että \"Smart Forms Config\" -luettelossa on versiointi käytössä ja vähintään yksi tallennettu muokkaus.",
    Designer_History_Latest: "Uusin",
    Designer_History_LatestTitle: "Tämä on tällä hetkellä käytössä oleva versio",
    Designer_History_By: "tekijä: {name}",
    Designer_History_UnknownAuthor: "Tuntematon tekijä",
    Designer_History_VersionLabel: "versio {label}",
    Designer_History_Preview: "Esikatsele",
    Designer_History_Restore: "Palauta",
    Designer_History_QuestionsOne: "1 kysymys",
    Designer_History_QuestionsOther: "{count} kysymystä",
    Designer_History_LoadFailed: "Tätä versiota ei voitu ladata.",
    Designer_History_ConfirmTitle: "Palautetaanko tämä versio?",
    Designer_History_ConfirmText: "Lomake korvataan versiolla, joka tallennettiin {date} ({count} kysymystä). Voit kumota tämän heti."
  };
});
