define([], function () {
  return {
    Designer_Color_Blue: "Bleu",
    Designer_Color_Teal: "Sarcelle",
    Designer_Color_Green: "Vert",
    Designer_Color_Purple: "Violet",
    Designer_Color_Magenta: "Magenta",
    Designer_Color_Red: "Rouge",
    Designer_Color_Orange: "Orange",
    Designer_Color_Gray: "Gris",
    Designer_Settings_LayoutSinglePage: "Toutes les questions sur une seule page",
    Designer_Settings_LayoutWizard: "Une section par étape (assistant)",
    Designer_Settings_Title: "Paramètres du formulaire",
    Designer_Common_Apply: "Appliquer",
    Designer_Common_Cancel: "Annuler",
    Designer_Settings_TabBasics: "Général",
    Designer_Settings_FormTitle: "Titre du formulaire",
    Designer_Settings_Description: "Description",
    Designer_Settings_Layout: "Disposition",
    Designer_Settings_NumberQuestions: "Numéroter les questions",
    Designer_Settings_ShuffleQuestions: "Mélanger l'ordre des questions pour chaque répondant",
    Designer_Settings_ShowProgressBar: "Afficher une barre de progression",
    Designer_Settings_TabAppearance: "Apparence",
    Designer_Settings_AccentColor: "Couleur d'accentuation",
    Designer_Settings_CustomColorTitle: "Couleur personnalisée",
    Designer_Settings_CustomColorAria: "Couleur d'accentuation personnalisée",
    Designer_Settings_AccentHint: "Les couleurs d'accentuation sont automatiquement ajustées pour le contraste sur les sites sombres, afin que le formulaire reste lisible quel que soit le thème de la page.",
    Designer_Settings_ShowHeader: "Afficher l'en-tête du formulaire",
    Designer_Settings_HeaderIcon: "Icône d'en-tête",
    Designer_Settings_TabAfterSubmit: "Après l'envoi",
    Designer_Settings_SubmitButtonText: "Texte du bouton d'envoi",
    Designer_Settings_SubmitPlaceholder: "Envoyer",
    Designer_Settings_ThankYouTitle: "Titre du message de remerciement",
    Designer_Settings_ThankYouPlaceholder: "Merci !",
    Designer_Settings_ThankYouMessage: "Message de remerciement",
    Designer_Settings_ShowSubmitAnother: "Afficher un bouton « Envoyer une autre réponse »",
    Designer_Settings_TabNotifications: "Notifications",
    Designer_Settings_EmailEachResponseTo: "Envoyer chaque réponse par e-mail à",
    Designer_Settings_EmailPlaceholder: "nom@societe.com; equipe@societe.com",
    Designer_Settings_EmailDescription: "Les membres de votre organisation reçoivent chaque réponse par e-mail, avec un lien vers l'élément de la liste",
    Designer_Settings_RespondentReceipt: "Envoyer aux répondants une copie de leurs réponses par e-mail",
    Designer_Settings_NotificationsInfo: "Les notifications utilisent le service de messagerie propre à SharePoint ; les destinataires doivent donc être des utilisateurs de votre organisation. Les adresses externes sont ignorées sans avertissement.",
    Designer_Settings_TabAccess: "Accès",
    Designer_Settings_OpenFrom: "Ouvrir à partir du",
    Designer_Settings_OpenImmediately: "Ouvrir immédiatement",
    Designer_Settings_CloseAfter: "Fermer après le",
    Designer_Settings_NeverClose: "Ne jamais fermer",
    Designer_Settings_ClearDates: "Effacer les dates",
    Designer_Settings_DatesInverted: "La date de fermeture est identique ou antérieure à la date d'ouverture ; le formulaire n'accepterait donc jamais de réponses.",
    Designer_Settings_MaxResponses: "Arrêter après ce nombre de réponses",
    Designer_Settings_NoLimit: "Aucune limite",
    Designer_Settings_OneResponsePerPerson: "N'autoriser qu'une seule réponse par personne",
    Designer_Settings_AllowSaveDraft: "Permettre aux répondants d'enregistrer un brouillon et de terminer plus tard",
    Designer_Settings_ClosedMessage: "Message affiché lorsque le formulaire est fermé",
    Designer_Settings_ClosedMessagePlaceholder: "Ce formulaire n'accepte plus de réponses.",
    Designer_Settings_AccessInfo: "Ces limites sont appliquées par le formulaire, et non par SharePoint. Toute personne autorisée à ajouter des éléments à la liste des réponses pourrait toujours en ajouter un directement via la liste.",
    Designer_Field_StyleInfo: "Information (accentuation)",
    Designer_Field_StyleSuccess: "Réussite (vert)",
    Designer_Field_StyleWarning: "Avertissement (ambre)",
    Designer_Field_StylePlain: "Texte brut",
    Designer_Field_StyleDivider: "Ligne de séparation",
    Designer_Field_IconStars: "Étoiles",
    Designer_Field_IconHearts: "Cœurs",
    Designer_Field_IconThumbs: "Pouces levés",
    Designer_Field_FormatPlain: "Nombre simple",
    Designer_Field_FormatCurrency: "Devise",
    Designer_Field_FormatPercent: "Pourcentage",
    Designer_Field_UntitledQuestion: "Question sans titre",
    Designer_Field_DeletedQuestion: "une question supprimée",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} et {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "OU",
    Designer_Rule_JoinAll: "ET",
    Designer_Rule_Preview: "Affichée lorsque {conditions}.",
    Designer_Field_Yes: "Oui",
    Designer_Field_No: "Non",
    Designer_Field_When: "Quand",
    Designer_Field_SelectValue: "Sélectionner une valeur",
    Designer_Field_DateValuePlaceholder: "AAAA-MM-JJ ou \"today\"",
    Designer_Field_ValuePlaceholder: "Valeur",
    Designer_Field_UpperBound: "Borne supérieure",
    Designer_Field_RemoveCondition: "Supprimer cette condition",
    Designer_Field_FormulaInvalid: "Cette formule ne peut pas être calculée. Vérifiez les parenthèses et les opérateurs.",
    Designer_Field_FormulaMissing: "Ces questions n'existent pas : {names}.",
    Designer_Field_FormulaPreview: "Avec chaque entrée à 10, le résultat affiché est {value}.",
    Designer_Field_HintYesNo: "Utilisez \"yes\" ou \"no\"",
    Designer_Field_HintMultiDefault: "Séparez plusieurs valeurs par défaut par ;",
    Designer_Field_HintSingleDefault: "Doit correspondre à l'une des options",
    Designer_Field_HintDate: "Utilisez \"today\" ou une date comme 2026-03-01",
    Designer_Field_HintTime: "Utilisez \"now\" ou une heure comme 09:30",
    Designer_Field_QuestionSettings: "Paramètres de la question",
    Designer_Field_Appearance: "Apparence",
    Designer_Field_Style: "Style",
    Designer_Field_ImageUrl: "URL de l'image (facultatif)",
    Designer_Field_Content: "Contenu",
    Designer_Field_BasicFormatting: "La mise en forme de base est autorisée : gras, italique, listes et liens.",
    Designer_Field_TabOptions: "Options",
    Designer_Field_TabBranching: "Ramification",
    Designer_Field_BranchingNeedsQuestion: "Ajoutez d'abord une autre question : la ramification a besoin d'un élément dont dépendre.",
    Designer_Field_BranchingToggle: "Afficher cette question uniquement si d'autres réponses correspondent",
    Designer_Field_Match: "Correspondre à",
    Designer_Field_MatchAll: "toutes ces conditions",
    Designer_Field_MatchAny: "l'une de ces conditions",
    Designer_Field_AddCondition: "Ajouter une condition",
    Designer_Field_TabValidation: "Validation",
    Designer_Field_HelpText: "Texte d'aide",
    Designer_Field_HelpTextPlaceholder: "Affiché sous l'intitulé de la question",
    Designer_Field_CheckboxLabel: "Libellé de la case à cocher",
    Designer_Field_Placeholder: "Texte indicatif",
    Designer_Field_DefaultAnswer: "Réponse par défaut",
    Designer_Field_RequiredMessage: "Message personnalisé de champ obligatoire",
    Designer_Field_RequiredMessagePlaceholder: "{title} est obligatoire",
    Designer_Field_ThisQuestion: "Cette question",
    Designer_Field_RequiredMessageDescription: "Affiché à la place du message standard lorsque cette question reste sans réponse",
    Designer_Field_ReadOnly: "Lecture seule (la réponse ne peut provenir que d'un lien prérempli)",
    Designer_Field_ValidationRules: "Règles de validation",
    Designer_Field_MaxLength: "Longueur maximale",
    Designer_Field_Pattern: "Doit correspondre à ce modèle",
    Designer_Field_PatternDescription: "Une expression régulière. Laissez vide pour ne pas vérifier de modèle.",
    Designer_Field_PatternMessage: "Message lorsque le modèle ne correspond pas",
    Designer_Field_PatternMessagePlaceholder: "Cette réponse n'est pas au format attendu",
    Designer_Field_Format: "Format",
    Designer_Field_UnitSuffix: "Unité affichée après la valeur",
    Designer_Field_UnitSuffixPlaceholder: "kg, h, articles…",
    Designer_Field_Minimum: "Minimum",
    Designer_Field_Maximum: "Maximum",
    Designer_Field_Decimals: "Décimales",
    Designer_Field_Formula: "Formule",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Référencez d'autres questions par leur texte entre accolades. Prend en charge + - * / ( ) ainsi que round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Questions disponibles : {questions}",
    Designer_Field_NoneYet: "aucune pour l'instant",
    Designer_Field_Step: "Pas",
    Designer_Field_From: "De",
    Designer_Field_To: "À",
    Designer_Field_LowLabel: "Libellé de la valeur basse",
    Designer_Field_LowLabelPlaceholder: "Pas du tout probable",
    Designer_Field_HighLabel: "Libellé de la valeur haute",
    Designer_Field_HighLabelPlaceholder: "Extrêmement probable",
    Designer_Field_SummarizeAs: "Résumer sous forme de",
    Designer_Field_SummarizeAverage: "Moyenne et répartition",
    Designer_Field_SummarizeNps: "Net Promoter Score (nécessite une échelle de 0 à 10)",
    Designer_Field_NpsWarning: "Le Net Promoter Score n'a de sens que sur une échelle de 0 à 10. Définissez De sur 0 et À sur 10.",
    Designer_Field_NumberOfIcons: "Nombre d'icônes",
    Designer_Field_Icon: "Icône",
    Designer_Field_AllowHalf: "Autoriser les demi-valeurs",
    Designer_Field_ShowOptionsAs: "Afficher les options sous forme de",
    Designer_Field_DisplayButtons: "Boutons en ligne",
    Designer_Field_DisplayDropdown: "Liste déroulante",
    Designer_Field_DisplayAutomatic: "Automatique (en ligne jusqu'à 6 options)",
    Designer_Field_AllowOther: "Ajouter une option « Autre » à saisir librement",
    Designer_Field_OtherLabel: "Libellé de l'option « Autre »",
    Designer_Field_OtherPlaceholder: "Autre",
    Designer_Field_ShuffleOptions: "Mélanger l'ordre des options pour chaque répondant",
    Designer_Field_MinSelections: "Nombre minimal de sélections",
    Designer_Field_MaxSelections: "Nombre maximal de sélections",
    Designer_Field_SourceList: "Liste source",
    Designer_Field_ChooseList: "Choisir une liste",
    Designer_Field_LookupColumn: "Colonne dont lire les options",
    Designer_Field_ChooseColumn: "Choisir une colonne",
    Designer_Field_ChooseListFirst: "Choisissez d'abord une liste",
    Designer_Field_LookupFilter: "Filtre (facultatif)",
    Designer_Field_LookupFilterDescription: "Un filtre OData limitant les éléments sources qui deviennent des options",
    Designer_Field_LookupInfo: "Les réponses stockent le texte de l'option, et non un lien vers l'élément source ; les réponses restent donc lisibles même si la liste source change par la suite.",
    Designer_Field_ConsentText: "Conditions affichées au-dessus de la case à cocher",
    Designer_Field_AllowMultiplePeople: "Autoriser plusieurs personnes",
    Designer_Field_AllowGroups: "Autoriser aussi les groupes",
    Designer_Field_IncludeTime: "Inclure une heure",
    Designer_Field_TimeStep: "Pas de temps (minutes)",
    Designer_Field_MaxFiles: "Nombre maximal de fichiers",
    Designer_Field_MaxFileSize: "Taille max. par fichier (Mo)",
    Designer_Field_AcceptedTypes: "Types de fichiers acceptés",
    Designer_Field_AcceptedTypesDescription: "Extensions séparées par des virgules. Laissez vide pour accepter tout ce que SharePoint autorise.",
    Designer_Field_FilesInfo: "Les fichiers sont enregistrés en tant que pièces jointes de l'élément de réponse. SharePoint bloque certaines extensions (comme .exe) quelles que soient vos autorisations ici.",
    Designer_Field_Rows: "Lignes",
    Designer_Field_ProvisionedNote: "Cette question possède déjà une colonne de liste ({name}). Les paramètres qui modifient le type de la colonne sont verrouillés : dupliquez la question si vous avez besoin d'un autre type.",
    Designer_Category_Text: "Texte",
    Designer_Category_Choice: "Choix",
    Designer_Category_Scales: "Échelles",
    Designer_Category_Date: "Date",
    Designer_Category_People: "Personnes",
    Designer_Category_Advanced: "Avancé",
    Designer_Category_Layout: "Mise en page",
    Designer_Menu_CommonPresets: "Préréglages courants",
    Designer_Menu_AllTypes: "Tous les types de questions",
    Designer_Menu_ChangeType: "Changer le type",
    Designer_Menu_TypeLockedTitle: "La colonne de liste existe déjà, le type est donc verrouillé. Dupliquez la question pour le modifier.",
    Designer_Menu_MoreSettings: "Ramification, validation et plus",
    Designer_Menu_InsertBelow: "Insérer une question en dessous",
    Designer_Card_Duplicate: "Dupliquer",
    Designer_Card_DeleteQuestion: "Supprimer la question",
    Designer_Outline_Aria: "Plan des questions",
    Designer_Outline_QuestionCountOne: "{count} question",
    Designer_Outline_QuestionCountOther: "{count} questions",
    Designer_Outline_IssuesTitle: "{count} problème(s) à examiner",
    Designer_Outline_Find: "Rechercher une question",
    Designer_Outline_Empty: "Aucune question pour l'instant.",
    Designer_Section_DefaultTitle: "Section {number}",
    Designer_Card_Question: "Question",
    Designer_Card_BranchingTitle: "Cette question n'apparaît que lorsqu'une règle de ramification correspond",
    Designer_Card_BranchingChip: "Ramification",
    Designer_Card_LiveTitle: "La colonne de liste existe, le type est donc verrouillé",
    Designer_Card_LiveChip: "Actif",
    Designer_Card_CheckChip: "À vérifier",
    Designer_Option_Placeholder: "Option {number}",
    Designer_Option_LabelAria: "Libellé de l'option {number}",
    Designer_Option_ImageUrl: "URL de l'image",
    Designer_Option_ImageUrlAria: "URL de l'image de l'option {number}",
    Designer_Option_Remove: "Supprimer l'option",
    Designer_Option_RemoveAria: "Supprimer l'option {number}",
    Designer_Option_Add: "Ajouter une option",
    Designer_Option_OtherHint: "Les répondants peuvent aussi saisir une réponse intitulée « {label} ».",
    Designer_Option_OtherFallback: "Autre",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Supprimer",
    Designer_Grid_RemoveAria: "Supprimer {label} {number}",
    Designer_Grid_Statements: "Affirmations",
    Designer_Grid_Scale: "Échelle",
    Designer_Grid_AddStatement: "Ajouter une affirmation",
    Designer_Grid_AddScale: "Ajouter une échelle",
    Designer_Width_Full: "Pleine largeur",
    Designer_Width_Half: "Demi-largeur",
    Designer_Width_Third: "Un tiers de la largeur",
    Designer_Width_Aria: "Largeur de la question",
    Designer_Card_BlockLabelPlaceholder: "Libellé du bloc (non affiché aux répondants)",
    Designer_Card_QuestionText: "Texte de la question",
    Designer_Card_MoveUp: "Monter",
    Designer_Card_MoveQuestionUp: "Monter la question",
    Designer_Card_MoveDown: "Descendre",
    Designer_Card_MoveQuestionDown: "Descendre la question",
    Designer_Card_DuplicateQuestion: "Dupliquer la question",
    Designer_Card_MultipleAnswers: "Réponses multiples",
    Designer_Card_Required: "Obligatoire",
    Designer_Card_MoreOptions: "Plus d'options",
    Designer_Card_MoreOptionsAria: "Plus d'options pour cette question",
    Designer_Canvas_FormTitle: "Titre du formulaire",
    Designer_Canvas_DescriptionPlaceholder: "Ajouter une description (facultatif)",
    Designer_Canvas_DescriptionAria: "Description du formulaire",
    Designer_Canvas_EmptyTitle: "Ajoutez votre première question",
    Designer_Canvas_EmptyBody: "Choisissez un type de question pour commencer. Vous pouvez réorganiser les questions par glisser-déposer et ajouter une ramification pour que chacun ne voie que ce qui le concerne.",
    Designer_Section_Chip: "Section {number} sur {total}",
    Designer_Section_TitlePlaceholder: "Titre de la section",
    Designer_Section_TitleAria: "Titre de la section {number}",
    Designer_Section_DescriptionPlaceholder: "Description (facultatif)",
    Designer_Section_DescriptionAria: "Description de la section {number}",
    Designer_Section_MoveUp: "Monter la section",
    Designer_Section_MoveDown: "Descendre la section",
    Designer_Section_Delete: "Supprimer la section",
    Designer_Card_DragToReorder: "Faire glisser pour réorganiser",
    Designer_Card_ReorderAria: "Réorganiser {title}",
    Designer_Card_ReorderFallback: "question",
    Designer_Canvas_AddNew: "Ajouter",
    Designer_Canvas_AddSection: "Ajouter une section",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Adresse",
    Form_Address_Street2Placeholder: "Appartement, bâtiment, etc. (facultatif)",
    Form_Address_CityPlaceholder: "Ville",
    Form_Address_StatePlaceholder: "État / région",
    Form_Address_PostalCodePlaceholder: "Code postal",
    Form_Address_CountryPlaceholder: "Pays",
    Form_Address_StreetAria: "adresse",
    Form_Address_Street2Aria: "complément d'adresse",
    Form_Address_CityAria: "ville",
    Form_Address_StateAria: "état ou région",
    Form_Address_PostalCodeAria: "code postal",
    Form_Address_CountryAria: "pays",
    Form_Consent_DefaultLabel: "J'accepte",
    Form_Likert_RadioAria: "{row} : {column}",
    Form_Likert_RowsAnswered: "{answered} ligne(s) sur {total} renseignée(s)",
    Form_Lookup_LoadError: "Les options de cette question n'ont pas pu être chargées.",
    Form_Lookup_Loading: "Chargement des options…",
    Form_Lookup_SelectOptionsPlaceholder: "Sélectionner des options",
    Form_Lookup_SelectOptionPlaceholder: "Sélectionner une option",
    Form_Person_Placeholder: "Commencez à saisir un nom…",
    Form_Person_SuggestedPeopleAndGroups: "Personnes et groupes suggérés",
    Form_Person_SuggestedPeople: "Personnes suggérées",
    Form_Person_NoPeopleOrGroups: "Aucune personne ni aucun groupe trouvé",
    Form_Person_NoPeople: "Aucune personne trouvée",
    Form_Person_Searching: "Recherche en cours…",
    Form_Ranking_Moved: "{item} déplacé en position {position} sur {total}",
    Form_Ranking_MoveUp: "Monter",
    Form_Ranking_MoveDown: "Descendre",
    Form_Ranking_MoveItemUpAria: "Monter {item}",
    Form_Ranking_MoveItemDownAria: "Descendre {item}",
    Form_Rating_ValueText: "{value} sur {max}",
    Form_Rating_NotRated: "Non noté",
    Form_Rating_Clear: "Effacer la note",
    Form_RichText_Bold: "Gras",
    Form_RichText_Italic: "Italique",
    Form_RichText_Underline: "Souligné",
    Form_RichText_BulletedList: "Liste à puces",
    Form_RichText_NumberedList: "Liste numérotée",
    Form_RichText_ClearFormatting: "Effacer la mise en forme",
    Form_RichText_ToolbarAria: "Mise en forme du texte",
    Form_File_SizeBytes: "{size} o",
    Form_File_SizeKb: "{size} Ko",
    Form_File_SizeMb: "{size} Mo",
    Form_File_SkippedLimit: "\"{name}\" a été ignoré : la limite est de {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" n'est pas un type accepté.",
    Form_File_TooLarge: "\"{name}\" dépasse {size} Mo.",
    Form_File_AlreadyAttached: "\"{name}\" est déjà joint.",
    Form_File_ReadError: "L'un des fichiers n'a pas pu être lu. Essayez de le joindre à nouveau.",
    Form_File_HintMaxSize: "jusqu'à {size} Mo chacun",
    Form_File_HintOneFile: "1 fichier",
    Form_File_HintMaxFiles: "{count} fichiers max.",
    Form_File_Reading: "Lecture des fichiers…",
    Form_File_DropPrompt: "Déposez des fichiers ici ou cliquez pour parcourir",
    Form_File_Remove: "Supprimer {name}",
    Form_Signature_Alt: "Signature",
    Form_Signature_AriaSigned: "{label} — signé",
    Form_Signature_AriaEmpty: "{label} — vide",
    Form_Signature_Clear: "Effacer",
    Form_Signature_Signed: "Signé",
    Form_Signature_Prompt: "Signez ci-dessus avec la souris, un stylet ou le doigt",
    Form_Time_Placeholder: "Sélectionner une heure",
    Form_Field_DatePlaceholder: "Sélectionner une date",
    Form_Field_TimeAriaWithLabel: "{label} — heure",
    Form_Field_TimeAria: "Heure",
    Form_Field_OtherDefault: "Autre",
    Form_Field_SelectOptionsPlaceholder: "Sélectionner des options",
    Form_Field_PleaseSpecify: "Veuillez préciser",
    Form_Field_OtherSpecifyAria: "{label} — veuillez préciser",
    Form_Field_SelectOptionPlaceholder: "Sélectionner une option",
    Form_Field_Yes: "Oui",
    Form_Field_No: "Non",
    Form_Field_SliderHint: "Faites glisser le curseur pour répondre",
    Form_Field_WebAddressAriaWithLabel: "{label} — adresse web",
    Form_Field_WebAddressAria: "Adresse web",
    Form_Field_DisplayTextPlaceholder: "Texte affiché (facultatif)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — texte affiché",
    Form_Field_DisplayTextAria: "Texte affiché",
    Form_Field_ChooseBetween: "Choisissez entre {min} et {max}",
    Form_Field_ChooseAtLeast: "Choisissez au moins {min}",
    Form_Field_ChooseUpTo: "Choisissez jusqu'à {max}",
    Form_Field_SelectedCount: "{count} sélectionné(s)",
    Form_Field_RequiredAria: "(obligatoire)",
    Form_Submit_SaveError: "Votre réponse n'a pas pu être enregistrée. Vérifiez que le formulaire a été publié depuis le concepteur et que vous êtes autorisé à ajouter des éléments à la liste des réponses.",
    Form_Empty_Message: "Ce formulaire ne contient pas encore de questions. Son propriétaire peut en ajouter dans l'onglet Questions.",
    Form_Checking: "Vérification du formulaire…",
    Form_Closed_NotYetOpen: "Pas encore ouvert",
    Form_Closed_AlreadyAnswered: "Déjà répondu",
    Form_Closed_Title: "Formulaire fermé",
    Form_Confirmation_PreviewNotice: "Il s'agissait d'un aperçu : rien n'a été enregistré dans la liste des réponses.",
    Form_Confirmation_PreviewAgain: "Afficher à nouveau l'aperçu",
    Form_Confirmation_SubmitAnother: "Envoyer une autre réponse",
    Form_Wizard_StepFallback: "Étape {step}",
    Form_Wizard_StepsAria: "Étapes du formulaire",
    Form_Wizard_StepOf: "Étape {step} sur {total}",
    Form_ErrorSummary_Title: "Veuillez vérifier {count} réponse(s) :",
    Form_ErrorSummary_UntitledQuestion: "Question sans titre",
    Form_ErrorSummary_Question: "Question",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Précédent",
    Form_Nav_Next: "Suivant",
    Form_Draft_Saving: "Enregistrement…",
    Form_Draft_Saved: "Brouillon enregistré",
    Form_Draft_SaveAndFinishLater: "Enregistrer et terminer plus tard",
    Form_Draft_NotSaved: "Brouillon non enregistré",
    Form_Submit_Preview: "Envoyer (aperçu)",
    Form_Submit_Button: "Envoyer",
    Form_Response_NoAnswer: "Aucune réponse",
    Form_Signature_TypeLabel: "Saisissez votre nom complet",
    Form_Signature_TypeInstead: "Saisir votre nom à la place",
    Form_Signature_DrawInstead: "Dessiner à la place",
    Form_Edit_Button: "Modifier votre réponse précédente",
    Form_Edit_Available: "Vous avez déjà envoyé une réponse. Vous pouvez la modifier au lieu d'en envoyer une nouvelle.",
    Form_Edit_Banner: "Vous modifiez votre réponse précédente.",
    Form_Edit_Save: "Mettre à jour la réponse",
    Form_Edit_UpdatedTitle: "Réponse mise à jour",
    Form_Edit_UpdatedMessage: "Vos modifications ont été enregistrées.",
    Form_Edit_LoadError: "Impossible de charger votre réponse précédente. Veuillez réessayer.",
    Form_Draft_MissingFiles: "Veuillez rattacher à nouveau : {names}. Ces fichiers n'ont pas pu être restaurés.",
    Form_Attachments_Failed: "Vos réponses ont été enregistrées, mais ces pièces jointes n'ont pas pu être téléchargées : {names}. Veuillez réessayer ou contacter le propriétaire du formulaire.",
    Logic_ThisQuestion: "Cette question",
    Logic_Required: "{label} est obligatoire",
    Logic_RequiredConsent: "Cochez la case pour continuer",
    Logic_RequiredFile: "Joignez au moins un fichier",
    Logic_RequiredSignature: "Veuillez ajouter votre signature",
    Logic_RequiredLikert: "Veuillez répondre à chaque ligne",
    Logic_InvalidEmail: "Saisissez une adresse e-mail valide",
    Logic_InvalidPhone: "Saisissez un numéro de téléphone valide",
    Logic_InvalidUrl: "Saisissez une adresse web valide commençant par http:// ou https://",
    Logic_MinValue: "La valeur doit être au moins {value}",
    Logic_MaxValue: "La valeur doit être au plus {value}",
    Logic_MaxLength: "La longueur maximale est de {max} caractères",
    Logic_ChooseAtLeastOne: "Choisissez au moins {count} option",
    Logic_ChooseAtLeastMany: "Choisissez au moins {count} options",
    Logic_ChooseAtMostOne: "Choisissez au plus {count} option",
    Logic_ChooseAtMostMany: "Choisissez au plus {count} options",
    Logic_LikertRemaining: "Veuillez répondre à chaque ligne ({count} restante(s))",
    Logic_MaxFilesOne: "Joignez au plus {count} fichier",
    Logic_MaxFilesMany: "Joignez au plus {count} fichiers",
    Logic_FileTooLarge: "« {name} » dépasse {size} Mo",
    Logic_FileTypeNotAccepted: "« {name} » n'est pas un type de fichier accepté ({types})",
    Logic_AddressRequired: "Saisissez au moins une rue et une ville",
    Logic_PatternDefault: "Cette réponse n'est pas au format attendu",
    Logic_Yes: "Oui",
    Logic_No: "Non",
    Logic_Agreed: "Accepté",
    Logic_NotAgreed: "Non accepté",
    Logic_Signed: "Signé",
    Logic_NoAnswer: "(aucune réponse)",
    Logic_Unknown: "(inconnu)",
    Logic_OtherSlice: "Autres ({count})",
    Logic_CsvResponseId: "ID de la réponse",
    Logic_CsvSubmitted: "Envoyé le",
    Logic_CsvSubmittedBy: "Envoyé par",
    Logic_EmailQuestion: "Question",
    Logic_EmailViewItem: "Afficher dans Microsoft Lists",
    Logic_EmailFooter: "Envoyé automatiquement par Smart Forms.",
    Logic_ClosedDefault: "Ce formulaire n'accepte plus de réponses.",
    Logic_NotYetOpen: "Ce formulaire ouvrira le {date}.",
    Logic_AlreadyResponded: "Vous avez déjà répondu à ce formulaire. Merci !",
    Logic_UntitledQuestion: "Une question sans titre",
    Logic_Issue_NoQuestions: "Ajoutez au moins une question avant de collecter des réponses.",
    Logic_Issue_NoTitle: "Une question n'a pas de texte : elle sera nommée automatiquement à la publication.",
    Logic_Issue_DuplicateTitle: "{label} a le même texte qu'une autre question, ce qui rend les résultats plus difficiles à lire.",
    Logic_Issue_NeedTwoOptions: "{label} nécessite au moins deux options.",
    Logic_Issue_ImageNoImage: "{label} contient des options sans image : elles s'afficheront sous forme de vignettes de texte.",
    Logic_Issue_LikertNeedRow: "{label} nécessite au moins une ligne.",
    Logic_Issue_LikertNeedColumns: "{label} nécessite au moins deux colonnes d'échelle.",
    Logic_Issue_NoLookupList: "Aucune liste source n'est sélectionnée pour {label}.",
    Logic_Issue_NoFormula: "{label} n'a pas de formule.",
    Logic_Issue_BadFormula: "La formule de {label} ne peut pas être calculée. Vérifiez les parenthèses et les opérateurs.",
    Logic_Issue_MissingRefs: "{label} fait référence à des questions inexistantes : {names}.",
    Logic_Issue_BadPattern: "{label} a un modèle de validation non valide.",
    Logic_Issue_BrokenRule: "{label} a une règle de branchement qui pointe vers une question supprimée.",
    Logic_Issue_SelfRule: "{label} a une règle de branchement qui fait référence à elle-même.",
    Logic_Issue_RuleMismatch: "{label} a une règle de branchement qui ne correspond plus à la question dont elle dépend.",
    Logic_Issue_RequiredReadOnly: "{label} est à la fois obligatoire et en lecture seule ; on ne peut y répondre que via un lien prérempli.",
    Logic_Issue_EmptySection: "Une section ne contient aucune question et sera ignorée.",
    Logic_Issue_CloseBeforeOpen: "La date de fermeture est antérieure ou égale à la date d'ouverture ; le formulaire n'acceptera donc jamais de réponses.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Les e-mails d'approbation sont activés, mais l'étape d'approbation est désactivée.",
    Logic_Op_equals: "est",
    Logic_Op_notEquals: "n'est pas",
    Logic_Op_contains: "contient",
    Logic_Op_notContains: "ne contient pas",
    Logic_Op_notEmpty: "est renseignée",
    Logic_Op_empty: "n'est pas renseignée",
    Logic_Op_greaterThan: "est supérieur à",
    Logic_Op_greaterOrEqual: "est au moins",
    Logic_Op_lessThan: "est inférieur à",
    Logic_Op_lessOrEqual: "est au plus",
    Logic_Op_between: "est compris entre",
    Logic_Op_before: "est avant",
    Logic_Op_after: "est après",
    Logic_Type_Text: "Réponse courte",
    Logic_TypeDesc_Text: "Une seule ligne de texte",
    Logic_Category_Text: "Texte",
    Logic_Type_MultilineText: "Réponse longue",
    Logic_TypeDesc_MultilineText: "Plusieurs lignes de texte brut",
    Logic_Type_RichText: "Texte mis en forme",
    Logic_TypeDesc_RichText: "Gras, listes et liens",
    Logic_Type_Choice: "Choix",
    Logic_TypeDesc_Choice: "Sélection dans une liste d'options",
    Logic_Category_Choice: "Choix",
    Logic_Type_ImageChoice: "Choix d'image",
    Logic_TypeDesc_ImageChoice: "Sélection parmi des vignettes d'images",
    Logic_Type_Lookup: "Liste de choix depuis une liste",
    Logic_TypeDesc_Lookup: "Options lues en direct depuis une autre liste SharePoint",
    Logic_Type_YesNo: "Oui / Non",
    Logic_TypeDesc_YesNo: "Un simple bouton bascule activé/désactivé",
    Logic_Type_Consent: "Consentement",
    Logic_TypeDesc_Consent: "Une case que le répondant doit cocher pour continuer",
    Logic_Type_Ranking: "Classement",
    Logic_TypeDesc_Ranking: "Faites glisser les options par ordre de préférence",
    Logic_Type_Rating: "Évaluation",
    Logic_TypeDesc_Rating: "Étoiles, cœurs ou pouces",
    Logic_Category_Scales: "Échelles",
    Logic_Type_Scale: "Échelle d'opinion",
    Logic_TypeDesc_Scale: "Une échelle numérotée avec des extrémités libellées",
    Logic_Type_Slider: "Curseur",
    Logic_TypeDesc_Slider: "Une valeur sur une échelle à curseur",
    Logic_Type_Likert: "Grille de Likert",
    Logic_TypeDesc_Likert: "Évaluez plusieurs affirmations sur une même échelle",
    Logic_Type_Number: "Nombre",
    Logic_TypeDesc_Number: "Nombre simple, devise ou pourcentage",
    Logic_Category_Advanced: "Avancé",
    Logic_Type_Calculated: "Calculé",
    Logic_TypeDesc_Calculated: "Un total en lecture seule calculé à partir d'autres réponses",
    Logic_Type_Date: "Date",
    Logic_TypeDesc_Date: "Une date du calendrier, avec heure en option",
    Logic_Category_Date: "Date",
    Logic_Type_Time: "Heure",
    Logic_TypeDesc_Time: "Une heure de la journée seule",
    Logic_Type_Person: "Personne",
    Logic_TypeDesc_Person: "Sélectionnez une personne de l'organisation",
    Logic_Category_People: "Personnes",
    Logic_Type_Email: "E-mail",
    Logic_TypeDesc_Email: "Une adresse e-mail, validée",
    Logic_Type_Phone: "Téléphone",
    Logic_TypeDesc_Phone: "Un numéro de téléphone, validé",
    Logic_Type_Address: "Adresse",
    Logic_TypeDesc_Address: "Rue, ville, code postal et pays",
    Logic_Type_Hyperlink: "Lien",
    Logic_TypeDesc_Hyperlink: "Une adresse web",
    Logic_Type_FileUpload: "Téléchargement de fichier",
    Logic_TypeDesc_FileUpload: "Joignez un ou plusieurs fichiers à la réponse",
    Logic_Type_Signature: "Signature",
    Logic_TypeDesc_Signature: "Signez avec une souris, un stylet ou le doigt",
    Logic_Type_Content: "Bloc de texte",
    Logic_TypeDesc_Content: "Instructions ou image : ne collecte aucune réponse",
    Logic_Category_Layout: "Mise en page",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Dans quelle mesure recommanderiez-vous…",
    Logic_Preset_satisfaction: "Satisfaction (1–5)",
    Logic_PresetDesc_satisfaction: "De très insatisfait à très satisfait",
    Logic_Preset_currency: "Devise",
    Logic_PresetDesc_currency: "Un montant monétaire",
    Logic_Preset_percent: "Pourcentage",
    Logic_PresetDesc_percent: "Une valeur en pourcentage",
    Logic_Template_blank_Name: "Formulaire vierge",
    Logic_Template_blank_Description: "Partir de zéro",
    Logic_Template_feedback_Name: "Retour client",
    Logic_Template_feedback_Description: "NPS, évaluations et commentaires libres",
    Logic_Template_event_Name: "Inscription à un événement",
    Logic_Template_event_Description: "Coordonnées des participants, sessions et besoins alimentaires",
    Logic_Template_itrequest_Name: "Demande de service informatique",
    Logic_Template_itrequest_Description: "Demandes classées avec priorité et pièces jointes",
    Logic_Template_expense_Name: "Note de frais",
    Logic_Template_expense_Description: "Lignes de frais, reçus et total calculé",
    Logic_Template_pulse_Name: "Sondage flash auprès des employés",
    Logic_Template_pulse_Description: "Grille de Likert, échelle d'engagement et note d'anonymat",
    Logic_Template_safety_Name: "Inspection de sécurité",
    Logic_Template_safety_Description: "Liste de contrôle, photos et signature",
    Logic_Template_booking_Name: "Réservation de salle ou de ressource",
    Logic_Template_booking_Description: "Sélecteur de ressource basé sur une liste, avec créneau horaire",
    Charts_ColumnChartAria: "Histogramme de {count} catégories",
    Charts_DonutChartAria: "Graphique en anneau de {count} catégories",
    Charts_NoAnswers: "Aucune réponse pour l'instant.",
    Charts_NoResponses: "Aucune réponse pour l'instant.",
    Charts_Responses: "Réponses",
    Charts_ResponsesOverTime: "Réponses au fil du temps",
    Responses_Chart_Answer: "Réponse",
    Responses_Chart_Average: "Moyenne",
    Responses_Chart_AverageOf: "Moyenne de {count}",
    Responses_Chart_AveragePosition: "Position moyenne",
    Responses_Chart_AverageRange: "Moyenne (1–{max})",
    Responses_Chart_AvgValue: "moy. {value}",
    Responses_Chart_Detractors: "Détracteurs (0–6)",
    Responses_Chart_Max: "Max",
    Responses_Chart_Maximum: "Maximum",
    Responses_Chart_Median: "Médiane",
    Responses_Chart_MentionOne: "{count} mention",
    Responses_Chart_MentionOther: "{count} mentions",
    Responses_Chart_Min: "Min",
    Responses_Chart_Minimum: "Minimum",
    Responses_Chart_NoAnswers: "Aucune réponse pour l'instant.",
    Responses_Chart_NoNumeric: "Aucune réponse numérique pour l'instant.",
    Responses_Chart_NoRankings: "Aucun classement pour l'instant.",
    Responses_Chart_NoScores: "Aucun score pour l'instant.",
    Responses_Chart_NotEnoughText: "Pas encore assez de texte à résumer.",
    Responses_Chart_NpsScore: "Score NPS",
    Responses_Chart_Option: "Option",
    Responses_Chart_Passives: "Passifs (7–8)",
    Responses_Chart_Promoters: "Promoteurs (9–10)",
    Responses_Chart_ResponseOne: "réponse",
    Responses_Chart_ResponseOther: "réponses",
    Responses_Chart_Responses: "Réponses",
    Responses_Chart_ShowingAnswers: "Affichage de {shown} réponses sur {total}.",
    Responses_Chart_Statement: "Affirmation",
    Responses_Chart_Statistic: "Statistique",
    Responses_Chart_StdDev: "Écart-type",
    Responses_Chart_StdDeviation: "Écart-type",
    Responses_Chart_Total: "Total",
    Responses_Chart_Value: "Valeur",
    Responses_Dashboard_AllHidden: "Toutes les questions sont masquées du tableau de bord. Utilisez « Afficher les questions masquées » pour les rétablir.",
    Responses_Dashboard_AnsweredOf: "{answered} sur {total} répondu(s)",
    Responses_Dashboard_AnsweredOfPinned: "{answered} sur {total} répondu(s) · épinglé",
    Responses_Dashboard_AveragedAcrossResponses: "Moyenne sur l'ensemble des réponses",
    Responses_Dashboard_ByDay: "Par jour",
    Responses_Dashboard_ByMonth: "Par mois",
    Responses_Dashboard_ByWeek: "Par semaine",
    Responses_Dashboard_ChartAuto: "Automatique",
    Responses_Dashboard_ChartBars: "Barres",
    Responses_Dashboard_ChartColumns: "Colonnes",
    Responses_Dashboard_ChartDonut: "Anneau",
    Responses_Dashboard_ChartGauge: "Jauge",
    Responses_Dashboard_ChartHistogram: "Histogramme",
    Responses_Dashboard_ChartOptions: "Options du graphique",
    Responses_Dashboard_ChartOptionsFor: "Options du graphique pour {title}",
    Responses_Dashboard_ChartStatistics: "Statistiques",
    Responses_Dashboard_ChartTable: "Tableau",
    Responses_Dashboard_ChartWordFrequency: "Fréquence des mots",
    Responses_Dashboard_EmptyBody: "Dès que les gens commenceront à répondre, ce tableau de bord se remplira automatiquement : chiffres clés, chronologie des réponses et graphique pour les questions à suivre.",
    Responses_Dashboard_EmptyTitle: "Aucune réponse pour l'instant",
    Responses_Dashboard_Hide: "Masquer du tableau de bord",
    Responses_Dashboard_Highlights: "Points clés",
    Responses_Dashboard_Last7Days: "7 derniers jours",
    Responses_Dashboard_LatestDate: "Dernière : {date}",
    Responses_Dashboard_MedianTimeToComplete: "Temps médian de réponse",
    Responses_Dashboard_NoPriorWeek: "Aucune semaine précédente à comparer",
    Responses_Dashboard_OneEach: "Une chacun",
    Responses_Dashboard_Pin: "Épingler au tableau de bord",
    Responses_Dashboard_QuestionFallback: "question",
    Responses_Dashboard_QuestionsAnswered: "Questions répondues",
    Responses_Dashboard_RecordedOnSubmit: "Enregistré à l'envoi",
    Responses_Dashboard_RepeatResponses: "{count} réponses répétées",
    Responses_Dashboard_ResponsesOverTime: "Réponses au fil du temps",
    Responses_Dashboard_ShowHidden: "Afficher les questions masquées",
    Responses_Dashboard_SinceMidnight: "Depuis minuit",
    Responses_Dashboard_Today: "Aujourd'hui",
    Responses_Dashboard_TotalResponses: "Total des réponses",
    Responses_Dashboard_UniqueRespondents: "Répondants uniques",
    Responses_Dashboard_Unpin: "Désépingler du tableau de bord",
    Responses_Dashboard_UntitledQuestion: "Question sans titre",
    Responses_Dashboard_VsPrevious7Days: "par rapport aux 7 jours précédents",
    Responses_Detail_Answers: "Réponses",
    Responses_Detail_AsTheForm: "Comme dans le formulaire",
    Responses_Detail_Cancel: "Annuler",
    Responses_Detail_Delete: "Supprimer",
    Responses_Detail_DeleteBody: "L'élément de liste est déplacé dans la corbeille du site, d'où il peut être restauré.",
    Responses_Detail_DeleteTitle: "Supprimer cette réponse ?",
    Responses_Detail_Deleting: "Suppression…",
    Responses_Detail_Draft: "Brouillon",
    Responses_Detail_Header: "Réponse {index} sur {total}",
    Responses_Detail_LoadingAttachments: "Chargement des pièces jointes…",
    Responses_Detail_Next: "Réponse suivante",
    Responses_Detail_NoAnswer: "Aucune réponse",
    Responses_Detail_Previous: "Réponse précédente",
    Responses_Detail_Print: "Imprimer",
    Responses_Detail_Signature: "Signature",
    Responses_Detail_Signed: "Signé",
    Responses_Detail_Took: "a pris {duration}",
    Responses_Summary_AnsweredOfType: "{answered} sur {total} répondu(s) · {type}",
    Responses_Summary_ByField: "Par {title}",
    Responses_Summary_CompareBy: "Comparer par…",
    Responses_Summary_EmptyBody: "Chaque question aura ici son propre résumé.",
    Responses_Summary_NoComparison: "Aucune comparaison",
    Responses_Summary_NothingToCompare: "Aucune réponse à « {title} » : il n'y a donc rien à comparer.",
    Responses_Summary_OtherNote: "Les graphiques de plus de {max} catégories regroupent les plus petites sous « Autre » ; passez une carte en Tableau pour voir toutes les valeurs.",
    Responses_Summary_ResponseCountOne: "{count} réponse",
    Responses_Summary_ResponseCountOther: "{count} réponses",
    Responses_Summary_SeeAllAnswers: "Voir toutes les réponses dans le tableau",
    Responses_Summary_SegmentNote: "Affichage des {groups} plus grands groupes. Une réponse ayant sélectionné plusieurs choix apparaît dans chaque groupe correspondant ; les totaux des groupes peuvent donc dépasser {total}.",
    Responses_Summary_SplitBy: "Répartir par {title}",
    Responses_Summary_Untitled: "sans titre",
    Responses_Table_Apply: "Appliquer",
    Responses_Table_Cancel: "Annuler",
    Responses_Table_ClearSelection: "Effacer la sélection",
    Responses_Table_ColumnOrder: "Ordre des colonnes",
    Responses_Table_ColumnsCount: "Colonnes ({shown}/{total})",
    Responses_Table_Delete: "Supprimer",
    Responses_Table_DeleteBody: "Les éléments de liste sont déplacés dans la corbeille du site, d'où ils peuvent être restaurés.",
    Responses_Table_DeleteSelected: "Supprimer la sélection",
    Responses_Table_DeleteTitleOne: "Supprimer {count} réponse ?",
    Responses_Table_DeleteTitleOther: "Supprimer {count} réponses ?",
    Responses_Table_Deleting: "Suppression…",
    Responses_Table_MoveDown: "Descendre",
    Responses_Table_MoveDownFor: "Descendre {title}",
    Responses_Table_MoveUp: "Monter",
    Responses_Table_MoveUpFor: "Monter {title}",
    Responses_Table_NoColumns: "Aucune colonne de question n'est visible pour l'instant.",
    Responses_Table_NoMatch: "Aucune réponse ne correspond aux filtres actuels.",
    Responses_Table_NothingToShow: "Rien à afficher",
    Responses_Table_OpenResponse: "Ouvrir cette réponse",
    Responses_Table_OrderNote: "Envoyé le et Envoyé par restent toujours en premier. L'ordre par glisser-déposer s'applique aux colonnes de questions.",
    Responses_Table_Reorder: "Réorganiser",
    Responses_Table_ResetColumns: "Réinitialiser les colonnes",
    Responses_Table_SelectResponse: "Sélectionner cette réponse",
    Responses_Table_SelectedOne: "{count} réponse sélectionnée",
    Responses_Table_SelectedOther: "{count} réponses sélectionnées",
    Responses_Table_ShowAll: "Tout afficher",
    Responses_Table_ShowTheseQuestions: "Afficher ces questions",
    Responses_Table_Submitted: "Envoyé le",
    Responses_Table_SubmittedBy: "Envoyé par",
    Responses_Table_ToggleSelection: "Basculer la sélection",
    Responses_Table_Unknown: "Inconnu",
    Responses_Table_Untitled: "Sans titre",
    Responses_View_AllTime: "Tout l'historique",
    Responses_View_AnyAnswer: "Toute réponse",
    Responses_View_Clear: "Effacer",
    Responses_View_CopyShareLink: "Copier le lien de partage",
    Responses_View_CountFiltered: "{shown} réponses sur {total}",
    Responses_View_CountOne: "{count} réponse",
    Responses_View_CountOther: "{count} réponses",
    Responses_View_Dashboard: "Tableau de bord",
    Responses_View_DateRange: "Plage de dates",
    Responses_View_EmptyBody: "Partagez le formulaire pour commencer à collecter des réponses. Elles sont enregistrées dans « {list} » et apparaissent ici immédiatement.",
    Responses_View_EmptyTitle: "Aucune réponse pour l'instant",
    Responses_View_ExportCsv: "Exporter en CSV",
    Responses_View_FilterByAnswer: "Filtrer par réponse",
    Responses_View_FilterByQuestion: "Filtrer par question",
    Responses_View_FilterValue: "Valeur du filtre",
    Responses_View_Last30Days: "30 derniers jours",
    Responses_View_Last7Days: "7 derniers jours",
    Responses_View_Last90Days: "90 derniers jours",
    Responses_View_LoadError: "Les réponses n'ont pas pu être chargées. Publiez le formulaire une fois pour que les colonnes de la liste existent, puis réessayez.",
    Responses_View_Loading: "Chargement des réponses…",
    Responses_View_MoreActions: "Autres actions sur les réponses",
    Responses_View_PreviewForm: "Afficher l'aperçu du formulaire",
    Responses_View_Refresh: "Actualiser",
    Responses_View_ResponsesTab: "Réponses ({count})",
    Responses_View_SearchPlaceholder: "Rechercher dans toutes les réponses",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Sélectionner une valeur",
    Responses_View_Summary: "Résumé",
    Responses_View_Today: "Aujourd'hui",
    Responses_View_Truncated: "Cette liste contient plus de réponses que Smart Forms n'en charge à la fois. Les {count} plus récentes sont affichées ; ouvrez la liste dans Microsoft Lists pour obtenir l'ensemble.",
    Responses_View_TryAgain: "Réessayer",
    Responses_View_Untitled: "Sans titre",
    Responses_Approval_Column: "Approbation",
    Responses_Approval_ReviewerColumn: "Examiné par",
    Responses_Approval_CommentColumn: "Commentaire du réviseur",
    Responses_Approval_Pending: "En attente",
    Responses_Approval_Approved: "Approuvé",
    Responses_Approval_Rejected: "Rejeté",
    Responses_Approval_AnyStatus: "Tout état d'approbation",
    Responses_Approval_FilterLabel: "Filtrer par état d'approbation",
    Responses_Approval_ApproveSelected: "Approuver la sélection",
    Responses_Approval_RejectSelected: "Rejeter la sélection",
    Responses_Approval_BulkFailed: "{count} réponses n'ont pas pu être mises à jour. Réessayez.",
    Responses_Approval_Approve: "Approuver",
    Responses_Approval_Reject: "Rejeter",
    Responses_Approval_Reset: "Remettre en attente",
    Responses_Approval_CommentLabel: "Commentaire (facultatif)",
    Responses_Approval_ReviewedBy: "Examiné par {name}",
    Responses_Approval_Error: "La décision n'a pas pu être enregistrée. Réessayez.",
    Responses_Dashboard_ApprovalStatus: "En attente d'examen",
    Responses_Dashboard_ApprovalBreakdown: "{pending} en attente, {approved} approuvées, {rejected} rejetées",
    Responses_Dashboard_TimelineCoarsened: "La plage de dates est longue ; la chronologie a donc été regroupée plus grossièrement ({grain}).",
    Responses_Dashboard_TimelineTruncated: "La plage de dates est très longue ; seules les {count} périodes les plus récentes sont affichées.",
    Service_Item_DefaultTitle: "Réponse — {date}",
    Service_Email_ApprovalSubject: "Votre réponse a été {status} — {title}",
    Service_Email_ApprovalHeading: "Votre réponse a été {status}",
    Service_Email_ApprovalIntro: "Un réviseur a marqué votre réponse à « {title} » comme {status}.",
    Service_Email_ApprovalCommentLabel: "Commentaire du réviseur",
    Service_Approval_Approved: "approuvée",
    Service_Approval_Rejected: "rejetée",
    Service_Approval_Pending: "en attente",
    Service_Lookup_InvalidFilter: "Le filtre de la liste de choix n'est pas valide.",
    Service_Edit_NotAllowed: "Ce formulaire ne permet pas de modifier une réponse envoyée.",
    Service_Edit_NotYours: "Vous ne pouvez modifier que votre propre réponse.",
    Service_Signature_AttachmentLabel: "Signature",
    PropertyPane_ListsLoadFailed: "Les listes de ce site n'ont pas pu être chargées.",
    PropertyPane_EnterListName: "Saisissez d'abord un nom pour la nouvelle liste.",
    PropertyPane_CreatingList: "Création de \"{name}\"…",
    PropertyPane_ListCreated: "Liste \"{title}\" créée et sélectionnée.",
    PropertyPane_ListAlreadyExists: "Une liste nommée \"{name}\" existe déjà : sélectionnez-la dans la liste déroulante ci-dessus.",
    PropertyPane_CreateListFailed: "Impossible de créer la liste. Vérifiez que vous êtes autorisé à créer des listes sur ce site.",
    PropertyPane_Description: "Choisissez la liste SharePoint qui stocke les réponses du formulaire, ou créez-en une. Tout le reste (questions, apparence, notifications) se modifie directement sur la page.",
    PropertyPane_ResponseList_GroupName: "Liste des réponses",
    PropertyPane_ListDropdown_Label: "Enregistrer les réponses dans cette liste",
    PropertyPane_ResponsesGoTo: "Les réponses sont envoyées dans \"{name}\".",
    PropertyPane_PickList: "Choisissez une liste ou créez-en une ci-dessous.",
    PropertyPane_LoadingLists: "Chargement des listes…",
    PropertyPane_NewListName_Label: "Ou créer une nouvelle liste",
    PropertyPane_NewListName_Placeholder: "Nom de la nouvelle liste",
    PropertyPane_CreateList_Button: "Créer la liste",
    PropertyPane_Tips_GroupName: "Conseils",
    PropertyPane_Tip_AutoSave: "Les questions et paramètres sont enregistrés automatiquement pendant vos modifications : inutile d'enregistrer ou de publier la page.",
    PropertyPane_Tip_Permissions: "Les répondants doivent être autorisés à ajouter des éléments à la liste des réponses. Vérifiez les autorisations de la liste si quelqu'un signale une erreur à l'envoi.",
    PropertyPane_Tip_Share: "Utilisez « Collecter des réponses » sur la page pour créer les colonnes de la liste et obtenir un lien de réponse partageable.",
    App_ErrorBoundary_Title: "Smart Forms — Erreur de rendu",
    App_ErrorBoundary_Message: "Message :",
    App_ErrorBoundary_Stack: "Pile :",
    App_ErrorBoundary_NoStack: "(aucune pile disponible)",
    App_ErrorBoundary_ConsoleNote: "Tous les détails ont aussi été écrits dans la console du navigateur.",
    App_DefaultQuestionTitle: "Question {number}",
    App_Error_ListMissing: "La liste configurée pour ce formulaire n'existe plus. Choisissez une autre liste dans les paramètres du composant WebPart.",
    App_Error_LoadConfig: "Une erreur s'est produite lors du chargement de la configuration du formulaire.",
    App_Error_Unable: "Impossible de charger le formulaire.",
    App_Publish_ConflictNotice: "\"{title}\" possède déjà une colonne de liste d'un autre type ({type}). Renommez la question pour qu'une nouvelle colonne puisse être créée, ou rétablissez son type.",
    App_Publish_ConflictUnnamedQuestion: "une question",
    App_Publish_ColumnsAddedOne: "{count} colonne a été ajoutée à \"{list}\".",
    App_Publish_ColumnsAddedOther: "{count} colonnes ont été ajoutées à \"{list}\".",
    App_Publish_TheList: "la liste",
    App_Publish_UpToDate: "La liste des réponses est déjà à jour.",
    App_Publish_Error: "Les colonnes de la liste n'ont pas pu être créées. Cela signifie généralement que vous n'avez pas l'autorisation Gérer les listes sur la liste des réponses, mais cela peut aussi se produire sur les sites où les scripts personnalisés sont désactivés. Consultez la console du navigateur pour connaître l'erreur sous-jacente, ou réessayez.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Créez un formulaire soigné à partir d'une liste SharePoint : {count} types de questions, logique de ramification, chargement de fichiers, liens de réponse partageables et tableau de bord des résultats.",
    App_Placeholder_ChooseList: "Choisir ou créer une liste",
    App_Placeholder_Hint: "Modifiez la page et configurez ce composant WebPart pour commencer.",
    App_Loading: "Chargement du formulaire…",
    App_OpenSettings: "Ouvrir les paramètres",
    App_Tab_Questions: "Questions",
    App_Tab_QuestionsWithCount: "Questions ({count})",
    App_Tab_Responses: "Réponses",
    App_Tab_Responses_Title: "Les réponses sont enregistrées dans \"{list}\"",
    App_Templates_Start: "Partir d'un modèle",
    App_Settings_Title: "Paramètres du formulaire : apparence, notifications, accès",
    App_Settings_AriaLabel: "Paramètres du formulaire",
    App_Preview: "Aperçu",
    App_Preview_Close: "Fermer l'aperçu",
    App_Preview_Hint: "Aperçu : rien de ce que vous envoyez ici n'est enregistré. La validation et la ramification se comportent exactement comme pour les répondants.",
    App_Publish_GettingReady: "Préparation…",
    App_Publish_CollectResponses: "Collecter des réponses",
    App_Publish_Share: "Partager",
    App_Retry: "Réessayer",
    App_SaveError_Banner: "Votre dernière modification n'a pas pu être enregistrée. Vérifiez votre connexion, puis réessayez.",
    App_Preflight_BlockingTitle: "À corriger avant de collecter",
    App_Preflight_WarningTitle: "À vérifier d'abord",
    App_Preflight_BlockingText: "Ces éléments empêcheraient le formulaire publié de fonctionner correctement.",
    App_Preflight_WarningText: "Rien n'est cassé, mais il vaut généralement mieux corriger ces points avant de partager le lien.",
    App_Preflight_GoTo: "Aller à",
    App_Preflight_CollectAnyway: "Collecter quand même",
    App_Preflight_Back: "Retour au formulaire",
    App_Cancel: "Annuler",
    App_Done: "Terminé",
    App_Share_Title: "Votre formulaire est prêt à être partagé",
    App_Share_SubText: "Envoyez ce lien à toutes les personnes qui doivent remplir le formulaire.",
    App_Share_LinkAriaLabel: "Lien de partage",
    App_Share_Copy: "Copier",
    App_Share_Copied: "Copié",
    App_Share_AddItemsEmphasis: "ajouter des éléments",
    App_Share_PermissionNote: "Les répondants doivent être autorisés à {addItems} à « {title} » et avoir accès à cette page. Si quelqu'un obtient une erreur à l'envoi, c'est presque toujours pour cette raison.",
    App_Share_PrefillNote: "Vous pouvez préremplir des questions dans le lien en ajoutant le nom de la colonne, par exemple {example}.",
    App_Templates_ReplaceWarning: "Choisir un modèle remplace les questions actuelles.",
    App_Templates_PickStart: "Choisissez un point de départ : vous pourrez tout modifier ensuite.",
    App_Templates_Empty: "Vide",
    App_Templates_QuestionCount: "{count} questions",
    App_SaveChip_SavingTitle: "Enregistrement de votre dernière modification",
    App_SaveChip_Saving: "Enregistrement…",
    App_SaveChip_FailedTitle: "Votre dernière modification n'a pas pu être enregistrée. Vérifiez votre connexion et réessayez.",
    App_SaveChip_Failed: "Échec de l'enregistrement",
    App_SaveChip_SavedTitle: "Toutes les modifications sont enregistrées",
    App_SaveChip_Saved: "Enregistré",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Nouvelle réponse — {title}",
    Service_Email_NewResponseHeading: "Nouvelle réponse : {title}",
    Service_Email_NewResponseIntro: "Quelqu'un vient d'envoyer une réponse — {date}.",
    Service_Email_ReceiptSubject: "Votre réponse — {title}",
    Service_Email_ReceiptHeading: "Merci pour votre réponse !",
    Service_Email_ReceiptIntro: "Voici une copie de ce que vous avez envoyé à \"{title}\".",
    App_History_Title: "Historique des versions",
    App_History_RestoredNotice: "Version enregistrée le {date} restaurée. Vérifiez-la, puis utilisez Collecter les réponses pour publier les nouvelles questions.",
    App_History_Undo: "Annuler la restauration",
    App_Share_CopyManual: "Votre navigateur a bloqué la copie. Sélectionnez le lien ci-dessus et appuyez sur Ctrl+C (Cmd+C sur Mac) pour le copier.",
    App_Share_TeamsNote: "Vous êtes dans Microsoft Teams. Ce lien ouvre directement la page SharePoint ; les destinataires doivent donc avoir accès au site.",
    App_Share_PrefillNotSecure: "Les réponses préremplies ne sont qu'un confort : toute personne disposant du lien peut les modifier ; ne les considérez donc jamais comme une limite de sécurité.",
    Designer_Section_DropHere: "Déposez une question ici",
    Designer_Section_DropEnd: "Déposez ici pour déplacer à la fin de cette section",
    Designer_Rules_RemovedOne: "1 règle de branchement qui ne convenait plus a été supprimée.",
    Designer_Rules_RemovedOther: "{count} règles de branchement qui ne convenaient plus ont été supprimées.",
    Designer_Settings_AllowEdit: "Autoriser les répondants à modifier leur réponse",
    Designer_Settings_AllowEditHint: "Les répondants peuvent rouvrir et mettre à jour ce qu'ils ont envoyé. Chacun ne peut modifier que sa propre réponse.",
    Designer_Settings_EnableApproval: "Activer le flux d'approbation",
    Designer_Settings_ApprovalNotify: "Envoyer un e-mail au répondant après la décision",
    Designer_Settings_ApprovalHint: "Ajoute des colonnes d'approbation à la liste des réponses lors de la prochaine publication. Les propriétaires approuvent ou rejettent les réponses depuis l'onglet Réponses.",
    Designer_History_Title: "Historique des versions",
    Designer_History_Intro: "Versions précédemment enregistrées des questions et des paramètres de ce formulaire. La restauration charge une version dans le concepteur ; vous pouvez l'annuler, et les nouvelles questions ne sont créées qu'à la publication.",
    Designer_History_Loading: "Chargement des versions...",
    Designer_History_Empty: "Aucune version antérieure trouvée. L'historique des versions nécessite que le suivi des versions soit activé pour la liste « Smart Forms Config » et qu'au moins une modification ait été enregistrée.",
    Designer_History_Latest: "Dernière",
    Designer_History_LatestTitle: "Il s'agit de la version actuellement utilisée",
    Designer_History_By: "par {name}",
    Designer_History_UnknownAuthor: "Auteur inconnu",
    Designer_History_VersionLabel: "version {label}",
    Designer_History_Preview: "Aperçu",
    Designer_History_Restore: "Restaurer",
    Designer_History_QuestionsOne: "1 question",
    Designer_History_QuestionsOther: "{count} questions",
    Designer_History_LoadFailed: "Cette version n'a pas pu être chargée.",
    Designer_History_ConfirmTitle: "Restaurer cette version ?",
    Designer_History_ConfirmText: "Le formulaire sera remplacé par la version enregistrée le {date} ({count} questions). Vous pourrez l'annuler juste après."
  };
});
