define([], function () {
  return {
    Designer_Color_Blue: "כחול",
    Designer_Color_Teal: "טורקיז",
    Designer_Color_Green: "ירוק",
    Designer_Color_Purple: "סגול",
    Designer_Color_Magenta: "מג'נטה",
    Designer_Color_Red: "אדום",
    Designer_Color_Orange: "כתום",
    Designer_Color_Gray: "אפור",
    Designer_Settings_LayoutSinglePage: "כל השאלות בעמוד אחד",
    Designer_Settings_LayoutWizard: "מקטע אחד בכל שלב (אשף)",
    Designer_Settings_Title: "הגדרות טופס",
    Designer_Common_Apply: "החל",
    Designer_Common_Cancel: "ביטול",
    Designer_Settings_TabBasics: "בסיסי",
    Designer_Settings_FormTitle: "כותרת הטופס",
    Designer_Settings_Description: "תיאור",
    Designer_Settings_Layout: "פריסה",
    Designer_Settings_NumberQuestions: "מספור השאלות",
    Designer_Settings_ShuffleQuestions: "ערבוב סדר השאלות עבור כל משיב",
    Designer_Settings_ShowProgressBar: "הצגת סרגל התקדמות",
    Designer_Settings_TabAppearance: "מראה",
    Designer_Settings_AccentColor: "צבע הדגשה",
    Designer_Settings_CustomColorTitle: "צבע מותאם אישית",
    Designer_Settings_CustomColorAria: "צבע הדגשה מותאם אישית",
    Designer_Settings_AccentHint: "צבעי ההדגשה מותאמים אוטומטית לניגודיות באתרים כהים, כך שהטופס נשאר קריא בכל ערכת נושא של הדף.",
    Designer_Settings_ShowHeader: "הצגת כותרת הטופס",
    Designer_Settings_HeaderIcon: "סמל בכותרת",
    Designer_Settings_TabAfterSubmit: "לאחר השליחה",
    Designer_Settings_SubmitButtonText: "טקסט לחצן השליחה",
    Designer_Settings_SubmitPlaceholder: "שליחה",
    Designer_Settings_ThankYouTitle: "כותרת הודעת התודה",
    Designer_Settings_ThankYouPlaceholder: "תודה!",
    Designer_Settings_ThankYouMessage: "הודעת תודה",
    Designer_Settings_ShowSubmitAnother: "הצגת לחצן \"שליחת תשובה נוספת\"",
    Designer_Settings_TabNotifications: "התראות",
    Designer_Settings_EmailEachResponseTo: "שליחת כל תשובה בדואר אלקטרוני אל",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "אנשים בארגון שלך יקבלו כל תשובה בדואר אלקטרוני, עם קישור לפריט ברשימה",
    Designer_Settings_RespondentReceipt: "שליחת עותק של התשובות למשיבים בדואר אלקטרוני",
    Designer_Settings_NotificationsInfo: "ההתראות משתמשות בשירות הדואר של SharePoint, ולכן הנמענים חייבים להיות משתמשים בארגון שלך. כתובות חיצוניות מושמטות ללא הודעה.",
    Designer_Settings_TabAccess: "גישה",
    Designer_Settings_OpenFrom: "פתיחה החל מ-",
    Designer_Settings_OpenImmediately: "פתיחה מיידית",
    Designer_Settings_CloseAfter: "סגירה לאחר",
    Designer_Settings_NeverClose: "לעולם לא לסגור",
    Designer_Settings_ClearDates: "ניקוי תאריכים",
    Designer_Settings_DatesInverted: "תאריך הסגירה זהה לתאריך הפתיחה או קודם לו, ולכן הטופס לא יקבל תשובות לעולם.",
    Designer_Settings_MaxResponses: "הפסקה לאחר מספר תשובות זה",
    Designer_Settings_NoLimit: "ללא הגבלה",
    Designer_Settings_OneResponsePerPerson: "אפשר תשובה אחת בלבד לכל אדם",
    Designer_Settings_AllowSaveDraft: "אפשר למשיבים לשמור טיוטה ולסיים מאוחר יותר",
    Designer_Settings_ClosedMessage: "הודעה שתוצג כשהטופס סגור",
    Designer_Settings_ClosedMessagePlaceholder: "טופס זה אינו מקבל עוד תשובות.",
    Designer_Settings_AccessInfo: "מגבלות אלו נאכפות על ידי הטופס ולא על ידי SharePoint. כל מי שיש לו הרשאה להוסיף פריטים לרשימת התשובות עדיין יכול להוסיף פריט ישירות דרך הרשימה.",
    Designer_Field_StyleInfo: "מידע (הדגשה)",
    Designer_Field_StyleSuccess: "הצלחה (ירוק)",
    Designer_Field_StyleWarning: "אזהרה (ענבר)",
    Designer_Field_StylePlain: "טקסט רגיל",
    Designer_Field_StyleDivider: "קו מפריד",
    Designer_Field_IconStars: "כוכבים",
    Designer_Field_IconHearts: "לבבות",
    Designer_Field_IconThumbs: "אגודלים למעלה",
    Designer_Field_FormatPlain: "מספר רגיל",
    Designer_Field_FormatCurrency: "מטבע",
    Designer_Field_FormatPercent: "אחוז",
    Designer_Field_UntitledQuestion: "שאלה ללא כותרת",
    Designer_Field_DeletedQuestion: "שאלה שנמחקה",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} ו-{value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "או",
    Designer_Rule_JoinAll: "וגם",
    Designer_Rule_Preview: "מוצג כאשר {conditions}.",
    Designer_Field_Yes: "כן",
    Designer_Field_No: "לא",
    Designer_Field_When: "כאשר",
    Designer_Field_SelectValue: "בחירת ערך",
    Designer_Field_DateValuePlaceholder: "YYYY-MM-DD או \"today\"",
    Designer_Field_ValuePlaceholder: "ערך",
    Designer_Field_UpperBound: "גבול עליון",
    Designer_Field_RemoveCondition: "הסרת תנאי זה",
    Designer_Field_FormulaInvalid: "לא ניתן לחשב נוסחה זו. בדוק את הסוגריים והאופרטורים.",
    Designer_Field_FormulaMissing: "השאלות האלה אינן קיימות: {names}.",
    Designer_Field_FormulaPreview: "כאשר כל קלט הוא 10, מוצג {value}.",
    Designer_Field_HintYesNo: "השתמש ב-\"yes\" או ב-\"no\"",
    Designer_Field_HintMultiDefault: "הפרד בין ערכי ברירת מחדל מרובים באמצעות ;",
    Designer_Field_HintSingleDefault: "חייב להתאים לאחת האפשרויות",
    Designer_Field_HintDate: "השתמש ב-\"today\" או בתאריך כמו 2026-03-01",
    Designer_Field_HintTime: "השתמש ב-\"now\" או בשעה כמו 09:30",
    Designer_Field_QuestionSettings: "הגדרות שאלה",
    Designer_Field_Appearance: "מראה",
    Designer_Field_Style: "סגנון",
    Designer_Field_ImageUrl: "כתובת URL של תמונה (אופציונלי)",
    Designer_Field_Content: "תוכן",
    Designer_Field_BasicFormatting: "עיצוב בסיסי מותר: מודגש, נטוי, רשימות וקישורים.",
    Designer_Field_TabOptions: "אפשרויות",
    Designer_Field_TabBranching: "הסתעפות",
    Designer_Field_BranchingNeedsQuestion: "הוסף תחילה שאלה נוספת – הסתעפות זקוקה למשהו שעליו היא תלויה.",
    Designer_Field_BranchingToggle: "הצג שאלה זו רק כאשר תשובות אחרות תואמות",
    Designer_Field_Match: "התאמה",
    Designer_Field_MatchAll: "לכל אלה",
    Designer_Field_MatchAny: "לאחד מאלה",
    Designer_Field_AddCondition: "הוספת תנאי",
    Designer_Field_TabValidation: "אימות",
    Designer_Field_HelpText: "טקסט עזרה",
    Designer_Field_HelpTextPlaceholder: "מוצג מתחת לתווית השאלה",
    Designer_Field_CheckboxLabel: "תווית תיבת הסימון",
    Designer_Field_Placeholder: "טקסט מציין מיקום",
    Designer_Field_DefaultAnswer: "תשובת ברירת מחדל",
    Designer_Field_RequiredMessage: "הודעת חובה מותאמת אישית",
    Designer_Field_RequiredMessagePlaceholder: "{title} הוא שדה חובה",
    Designer_Field_ThisQuestion: "שאלה זו",
    Designer_Field_RequiredMessageDescription: "מוצגת במקום ההודעה הרגילה כאשר שאלה זו נשארת ריקה",
    Designer_Field_ReadOnly: "לקריאה בלבד (התשובה יכולה להגיע רק מקישור ממולא מראש)",
    Designer_Field_ValidationRules: "כללי אימות",
    Designer_Field_MaxLength: "אורך מרבי",
    Designer_Field_Pattern: "חייב להתאים לתבנית זו",
    Designer_Field_PatternDescription: "ביטוי רגולרי. השאר ריק כדי לא לבדוק תבנית.",
    Designer_Field_PatternMessage: "הודעה כאשר התבנית אינה תואמת",
    Designer_Field_PatternMessagePlaceholder: "תשובה זו אינה בפורמט הצפוי",
    Designer_Field_Format: "פורמט",
    Designer_Field_UnitSuffix: "יחידה שתוצג אחרי הערך",
    Designer_Field_UnitSuffixPlaceholder: "ק\"ג, שעות, פריטים…",
    Designer_Field_Minimum: "מינימום",
    Designer_Field_Maximum: "מקסימום",
    Designer_Field_Decimals: "ספרות עשרוניות",
    Designer_Field_Formula: "נוסחה",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "הפנה לשאלות אחרות לפי הטקסט שלהן בתוך סוגריים מסולסלים. נתמכים + - * / ( ) וכן round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "שאלות זמינות: {questions}",
    Designer_Field_NoneYet: "עדיין אין",
    Designer_Field_Step: "צעד",
    Designer_Field_From: "מ-",
    Designer_Field_To: "עד",
    Designer_Field_LowLabel: "תווית בקצה התחתון",
    Designer_Field_LowLabelPlaceholder: "כלל לא סביר",
    Designer_Field_HighLabel: "תווית בקצה העליון",
    Designer_Field_HighLabelPlaceholder: "סביר ביותר",
    Designer_Field_SummarizeAs: "סיכום בתור",
    Designer_Field_SummarizeAverage: "ממוצע והתפלגות",
    Designer_Field_SummarizeNps: "Net Promoter Score (דורש סולם 0–10)",
    Designer_Field_NpsWarning: "Net Promoter Score משמעותי רק בסולם 0–10. הגדר את \"מ-\" ל-0 ואת \"עד\" ל-10.",
    Designer_Field_NumberOfIcons: "מספר הסמלים",
    Designer_Field_Icon: "סמל",
    Designer_Field_AllowHalf: "אפשר חצאי ערכים",
    Designer_Field_ShowOptionsAs: "הצגת האפשרויות כ-",
    Designer_Field_DisplayButtons: "לחצנים בשורה",
    Designer_Field_DisplayDropdown: "רשימה נפתחת",
    Designer_Field_DisplayAutomatic: "אוטומטי (בשורה עד 6 אפשרויות)",
    Designer_Field_AllowOther: "הוספת אפשרות \"אחר\" להקלדה חופשית",
    Designer_Field_OtherLabel: "תווית לאפשרות \"אחר\"",
    Designer_Field_OtherPlaceholder: "אחר",
    Designer_Field_ShuffleOptions: "ערבוב סדר האפשרויות עבור כל משיב",
    Designer_Field_MinSelections: "מספר בחירות מינימלי",
    Designer_Field_MaxSelections: "מספר בחירות מרבי",
    Designer_Field_SourceList: "רשימת מקור",
    Designer_Field_ChooseList: "בחירת רשימה",
    Designer_Field_LookupColumn: "עמודה שממנה יקראו האפשרויות",
    Designer_Field_ChooseColumn: "בחירת עמודה",
    Designer_Field_ChooseListFirst: "בחר תחילה רשימה",
    Designer_Field_LookupFilter: "מסנן (אופציונלי)",
    Designer_Field_LookupFilterDescription: "מסנן OData המצמצם אילו פריטי מקור יהפכו לאפשרויות",
    Designer_Field_LookupInfo: "התשובות שומרות את טקסט האפשרות ולא קישור לפריט המקור, כך שהתשובות נשארות קריאות גם אם רשימת המקור תשתנה בהמשך.",
    Designer_Field_ConsentText: "תנאים שיוצגו מעל תיבת הסימון",
    Designer_Field_AllowMultiplePeople: "אפשר מספר אנשים",
    Designer_Field_AllowGroups: "אפשר גם קבוצות",
    Designer_Field_IncludeTime: "כלול שעה ביום",
    Designer_Field_TimeStep: "צעד זמן (דקות)",
    Designer_Field_MaxFiles: "מספר קבצים מרבי",
    Designer_Field_MaxFileSize: "גודל מרבי לכל קובץ (MB)",
    Designer_Field_AcceptedTypes: "סוגי קבצים מותרים",
    Designer_Field_AcceptedTypesDescription: "סיומות מופרדות בפסיקים. השאר ריק כדי לקבל כל מה ש-SharePoint מאפשר.",
    Designer_Field_FilesInfo: "הקבצים נשמרים כקבצים מצורפים לפריט התשובה. SharePoint חוסם סיומות מסוימות (כגון .exe) ללא קשר למה שתאפשר כאן.",
    Designer_Field_Rows: "שורות",
    Designer_Field_ProvisionedNote: "לשאלה זו כבר יש עמודת רשימה ({name}). הגדרות המשנות את סוג העמודה נעולות – שכפל את השאלה אם דרוש סוג אחר.",
    Designer_Category_Text: "טקסט",
    Designer_Category_Choice: "בחירה",
    Designer_Category_Scales: "סולמות",
    Designer_Category_Date: "תאריך",
    Designer_Category_People: "אנשים",
    Designer_Category_Advanced: "מתקדם",
    Designer_Category_Layout: "פריסה",
    Designer_Menu_CommonPresets: "הגדרות מוכנות נפוצות",
    Designer_Menu_AllTypes: "כל סוגי השאלות",
    Designer_Menu_ChangeType: "שינוי סוג",
    Designer_Menu_TypeLockedTitle: "עמודת הרשימה כבר קיימת, ולכן הסוג נעול. שכפל את השאלה כדי לשנות אותו.",
    Designer_Menu_MoreSettings: "הסתעפות, אימות ועוד",
    Designer_Menu_InsertBelow: "הוספת שאלה מתחת",
    Designer_Card_Duplicate: "שכפול",
    Designer_Card_DeleteQuestion: "מחיקת שאלה",
    Designer_Outline_Aria: "מתאר השאלות",
    Designer_Outline_QuestionCountOne: "שאלה {count}",
    Designer_Outline_QuestionCountOther: "{count} שאלות",
    Designer_Outline_IssuesTitle: "{count} בעיות לבדיקה",
    Designer_Outline_Find: "חיפוש שאלה",
    Designer_Outline_Empty: "עדיין אין שאלות.",
    Designer_Section_DefaultTitle: "מקטע {number}",
    Designer_Card_Question: "שאלה",
    Designer_Card_BranchingTitle: "שאלה זו מופיעה רק כאשר כלל הסתעפות מתאים",
    Designer_Card_BranchingChip: "הסתעפות",
    Designer_Card_LiveTitle: "עמודת הרשימה קיימת, ולכן הסוג נעול",
    Designer_Card_LiveChip: "פעיל",
    Designer_Card_CheckChip: "לבדיקה",
    Designer_Option_Placeholder: "אפשרות {number}",
    Designer_Option_LabelAria: "תווית אפשרות {number}",
    Designer_Option_ImageUrl: "כתובת URL של תמונה",
    Designer_Option_ImageUrlAria: "כתובת URL של תמונה לאפשרות {number}",
    Designer_Option_Remove: "הסרת אפשרות",
    Designer_Option_RemoveAria: "הסרת אפשרות {number}",
    Designer_Option_Add: "הוספת אפשרות",
    Designer_Option_OtherHint: "משיבים יכולים גם להקליד תשובה בשם “{label}”.",
    Designer_Option_OtherFallback: "אחר",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "הסרה",
    Designer_Grid_RemoveAria: "הסרת {label} {number}",
    Designer_Grid_Statements: "היגדים",
    Designer_Grid_Scale: "סולם",
    Designer_Grid_AddStatement: "הוספת היגד",
    Designer_Grid_AddScale: "הוספת סולם",
    Designer_Width_Full: "רוחב מלא",
    Designer_Width_Half: "חצי רוחב",
    Designer_Width_Third: "שליש רוחב",
    Designer_Width_Aria: "רוחב השאלה",
    Designer_Card_BlockLabelPlaceholder: "תווית בלוק (לא מוצגת למשיבים)",
    Designer_Card_QuestionText: "טקסט השאלה",
    Designer_Card_MoveUp: "הזזה למעלה",
    Designer_Card_MoveQuestionUp: "הזזת השאלה למעלה",
    Designer_Card_MoveDown: "הזזה למטה",
    Designer_Card_MoveQuestionDown: "הזזת השאלה למטה",
    Designer_Card_DuplicateQuestion: "שכפול שאלה",
    Designer_Card_MultipleAnswers: "תשובות מרובות",
    Designer_Card_Required: "חובה",
    Designer_Card_MoreOptions: "אפשרויות נוספות",
    Designer_Card_MoreOptionsAria: "אפשרויות נוספות לשאלה זו",
    Designer_Canvas_FormTitle: "כותרת הטופס",
    Designer_Canvas_DescriptionPlaceholder: "הוספת תיאור (אופציונלי)",
    Designer_Canvas_DescriptionAria: "תיאור הטופס",
    Designer_Canvas_EmptyTitle: "הוסף את השאלה הראשונה שלך",
    Designer_Canvas_EmptyBody: "בחר סוג שאלה כדי להתחיל. אפשר לסדר מחדש את השאלות בגרירה, ולהוסיף הסתעפות כדי שאנשים יראו רק את מה שרלוונטי להם.",
    Designer_Section_Chip: "מקטע {number} מתוך {total}",
    Designer_Section_TitlePlaceholder: "כותרת המקטע",
    Designer_Section_TitleAria: "כותרת מקטע {number}",
    Designer_Section_DescriptionPlaceholder: "תיאור (אופציונלי)",
    Designer_Section_DescriptionAria: "תיאור מקטע {number}",
    Designer_Section_MoveUp: "הזזת המקטע למעלה",
    Designer_Section_MoveDown: "הזזת המקטע למטה",
    Designer_Section_Delete: "מחיקת מקטע",
    Designer_Card_DragToReorder: "גרור כדי לסדר מחדש",
    Designer_Card_ReorderAria: "סידור מחדש של {title}",
    Designer_Card_ReorderFallback: "שאלה",
    Designer_Canvas_AddNew: "הוספה",
    Designer_Canvas_AddSection: "הוספת מקטע",
    Form_Address_AriaWithLabel: "{label} – {part}",
    Form_Address_StreetPlaceholder: "רחוב ומספר",
    Form_Address_Street2Placeholder: "דירה, כניסה וכו' (אופציונלי)",
    Form_Address_CityPlaceholder: "עיר",
    Form_Address_StatePlaceholder: "מדינה / מחוז",
    Form_Address_PostalCodePlaceholder: "מיקוד",
    Form_Address_CountryPlaceholder: "מדינה",
    Form_Address_StreetAria: "רחוב ומספר",
    Form_Address_Street2Aria: "שורת כתובת 2",
    Form_Address_CityAria: "עיר",
    Form_Address_StateAria: "מדינה או מחוז",
    Form_Address_PostalCodeAria: "מיקוד",
    Form_Address_CountryAria: "מדינה",
    Form_Consent_DefaultLabel: "אני מסכים/ה",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "נענו {answered} מתוך {total} שורות",
    Form_Lookup_LoadError: "לא ניתן היה לטעון את האפשרויות של שאלה זו.",
    Form_Lookup_Loading: "טוען אפשרויות…",
    Form_Lookup_SelectOptionsPlaceholder: "בחירת אפשרויות",
    Form_Lookup_SelectOptionPlaceholder: "בחירת אפשרות",
    Form_Person_Placeholder: "התחל להקליד שם…",
    Form_Person_SuggestedPeopleAndGroups: "אנשים וקבוצות מוצעים",
    Form_Person_SuggestedPeople: "אנשים מוצעים",
    Form_Person_NoPeopleOrGroups: "לא נמצאו אנשים או קבוצות",
    Form_Person_NoPeople: "לא נמצאו אנשים",
    Form_Person_Searching: "מחפש…",
    Form_Ranking_Moved: "{item} הועבר למיקום {position} מתוך {total}",
    Form_Ranking_MoveUp: "הזזה למעלה",
    Form_Ranking_MoveDown: "הזזה למטה",
    Form_Ranking_MoveItemUpAria: "הזזת {item} למעלה",
    Form_Ranking_MoveItemDownAria: "הזזת {item} למטה",
    Form_Rating_ValueText: "{value} מתוך {max}",
    Form_Rating_NotRated: "לא דורג",
    Form_Rating_Clear: "ניקוי הדירוג",
    Form_RichText_Bold: "מודגש",
    Form_RichText_Italic: "נטוי",
    Form_RichText_Underline: "קו תחתון",
    Form_RichText_BulletedList: "רשימת תבליטים",
    Form_RichText_NumberedList: "רשימה ממוספרת",
    Form_RichText_ClearFormatting: "ניקוי עיצוב",
    Form_RichText_ToolbarAria: "עיצוב טקסט",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\" דולג – המגבלה היא {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" אינו סוג מותר.",
    Form_File_TooLarge: "\"{name}\" גדול מ-{size} MB.",
    Form_File_AlreadyAttached: "\"{name}\" כבר מצורף.",
    Form_File_ReadError: "לא ניתן היה לקרוא אחד הקבצים. נסה לצרף אותו שוב.",
    Form_File_HintMaxSize: "עד {size} MB לכל קובץ",
    Form_File_HintOneFile: "קובץ אחד",
    Form_File_HintMaxFiles: "עד {count} קבצים",
    Form_File_Reading: "קורא קבצים…",
    Form_File_DropPrompt: "גרור קבצים לכאן, או לחץ כדי לעיין",
    Form_File_Remove: "הסרת {name}",
    Form_Signature_Alt: "חתימה",
    Form_Signature_AriaSigned: "{label} – חתום",
    Form_Signature_AriaEmpty: "{label} – ריק",
    Form_Signature_Clear: "ניקוי",
    Form_Signature_Signed: "חתום",
    Form_Signature_Prompt: "חתום למעלה באמצעות עכבר, עט או אצבע",
    Form_Time_Placeholder: "בחירת שעה",
    Form_Field_DatePlaceholder: "בחירת תאריך",
    Form_Field_TimeAriaWithLabel: "{label} – שעה",
    Form_Field_TimeAria: "שעה",
    Form_Field_OtherDefault: "אחר",
    Form_Field_SelectOptionsPlaceholder: "בחירת אפשרויות",
    Form_Field_PleaseSpecify: "נא לפרט",
    Form_Field_OtherSpecifyAria: "{label} – נא לפרט",
    Form_Field_SelectOptionPlaceholder: "בחירת אפשרות",
    Form_Field_Yes: "כן",
    Form_Field_No: "לא",
    Form_Field_SliderHint: "גרור את המחוון כדי לענות",
    Form_Field_WebAddressAriaWithLabel: "{label} – כתובת אינטרנט",
    Form_Field_WebAddressAria: "כתובת אינטרנט",
    Form_Field_DisplayTextPlaceholder: "טקסט לתצוגה (אופציונלי)",
    Form_Field_DisplayTextAriaWithLabel: "{label} – טקסט לתצוגה",
    Form_Field_DisplayTextAria: "טקסט לתצוגה",
    Form_Field_ChooseBetween: "בחר בין {min} ל-{max}",
    Form_Field_ChooseAtLeast: "בחר לפחות {min}",
    Form_Field_ChooseUpTo: "בחר עד {max}",
    Form_Field_SelectedCount: "{count} נבחרו",
    Form_Field_RequiredAria: "(חובה)",
    Form_Submit_SaveError: "לא ניתן היה לשמור את התשובה שלך. ודא שהטופס פורסם מהמעצב ושיש לך הרשאה להוסיף פריטים לרשימת התשובות.",
    Form_Empty_Message: "בטופס זה עדיין אין שאלות. בעל הטופס יכול להוסיף אותן בכרטיסיית השאלות.",
    Form_Checking: "בודק את הטופס…",
    Form_Closed_NotYetOpen: "עדיין לא נפתח",
    Form_Closed_AlreadyAnswered: "כבר נענה",
    Form_Closed_Title: "הטופס סגור",
    Form_Confirmation_PreviewNotice: "זו הייתה תצוגה מקדימה – דבר לא נשמר ברשימת התשובות.",
    Form_Confirmation_PreviewAgain: "תצוגה מקדימה נוספת",
    Form_Confirmation_SubmitAnother: "שליחת תשובה נוספת",
    Form_Wizard_StepFallback: "שלב {step}",
    Form_Wizard_StepsAria: "שלבי הטופס",
    Form_Wizard_StepOf: "שלב {step} מתוך {total}",
    Form_ErrorSummary_Title: "נא לבדוק {count} תשובות:",
    Form_ErrorSummary_UntitledQuestion: "שאלה ללא כותרת",
    Form_ErrorSummary_Question: "שאלה",
    Form_ErrorSummary_Detail: " – {message}",
    Form_Nav_Back: "הקודם",
    Form_Nav_Next: "הבא",
    Form_Draft_Saving: "שומר…",
    Form_Draft_Saved: "הטיוטה נשמרה",
    Form_Draft_SaveAndFinishLater: "שמירה וסיום מאוחר יותר",
    Form_Draft_NotSaved: "הטיוטה לא נשמרה",
    Form_Submit_Preview: "שליחה (תצוגה מקדימה)",
    Form_Submit_Button: "שליחה",
    Form_Response_NoAnswer: "אין תשובה",
    Form_Signature_TypeLabel: "הקלד/י את שמך המלא",
    Form_Signature_TypeInstead: "הקלד/י את שמך במקום זאת",
    Form_Signature_DrawInstead: "צייר/י במקום זאת",
    Form_Edit_Button: "עריכת התשובה הקודמת שלך",
    Form_Edit_Available: "כבר שלחת תשובה. ניתן לערוך אותה במקום לשלוח תשובה חדשה.",
    Form_Edit_Banner: "את/ה עורך/ת את התשובה הקודמת שלך.",
    Form_Edit_Save: "עדכון התשובה",
    Form_Edit_UpdatedTitle: "התשובה עודכנה",
    Form_Edit_UpdatedMessage: "השינויים נשמרו.",
    Form_Edit_LoadError: "לא ניתן היה לטעון את התשובה הקודמת שלך. נסה/י שוב.",
    Form_Draft_MissingFiles: "נא לצרף מחדש: {names}. לא ניתן היה לשחזר קבצים אלה.",
    Form_Attachments_Failed: "התשובות שלך נשמרו, אך לא ניתן היה להעלות את הקבצים המצורפים הבאים: {names}. נסה/י שוב או פנה/י לבעלים של הטופס.",
    Logic_ThisQuestion: "שאלה זו",
    Logic_Required: "{label} הוא שדה חובה",
    Logic_RequiredConsent: "סמן/י את תיבת הסימון כדי להמשיך",
    Logic_RequiredFile: "צרף/י לפחות קובץ אחד",
    Logic_RequiredSignature: "הוסף/י את חתימתך",
    Logic_RequiredLikert: "נא לענות על כל שורה",
    Logic_InvalidEmail: "הזן/י כתובת דוא\"ל תקינה",
    Logic_InvalidPhone: "הזן/י מספר טלפון תקין",
    Logic_InvalidUrl: "הזן/י כתובת אינטרנט תקינה המתחילה ב-http:// או ב-https://",
    Logic_MinValue: "הערך חייב להיות לפחות {value}",
    Logic_MaxValue: "הערך יכול להיות לכל היותר {value}",
    Logic_MaxLength: "האורך המרבי הוא {max} תווים",
    Logic_ChooseAtLeastOne: "בחר/י לפחות {count} אפשרות",
    Logic_ChooseAtLeastMany: "בחר/י לפחות {count} אפשרויות",
    Logic_ChooseAtMostOne: "בחר/י לכל היותר {count} אפשרות",
    Logic_ChooseAtMostMany: "בחר/י לכל היותר {count} אפשרויות",
    Logic_LikertRemaining: "נא לענות על כל שורה (נותרו {count})",
    Logic_MaxFilesOne: "צרף/י לכל היותר {count} קובץ",
    Logic_MaxFilesMany: "צרף/י לכל היותר {count} קבצים",
    Logic_FileTooLarge: "\"{name}\" גדול מ-{size} MB",
    Logic_FileTypeNotAccepted: "\"{name}\" אינו סוג קובץ מקובל ({types})",
    Logic_AddressRequired: "הזן/י לפחות רחוב ועיר",
    Logic_PatternDefault: "התשובה אינה בפורמט הצפוי",
    Logic_Yes: "כן",
    Logic_No: "לא",
    Logic_Agreed: "הסכמה",
    Logic_NotAgreed: "ללא הסכמה",
    Logic_Signed: "חתום",
    Logic_NoAnswer: "(אין תשובה)",
    Logic_Unknown: "(לא ידוע)",
    Logic_OtherSlice: "אחר ({count})",
    Logic_CsvResponseId: "מזהה תשובה",
    Logic_CsvSubmitted: "נשלח",
    Logic_CsvSubmittedBy: "נשלח על ידי",
    Logic_EmailQuestion: "שאלה",
    Logic_EmailViewItem: "הצגה ב-Microsoft Lists",
    Logic_EmailFooter: "נשלח אוטומטית על ידי Smart Forms.",
    Logic_ClosedDefault: "טופס זה אינו מקבל עוד תשובות.",
    Logic_NotYetOpen: "טופס זה ייפתח ב-{date}.",
    Logic_AlreadyResponded: "כבר השבת על טופס זה. תודה!",
    Logic_UntitledQuestion: "שאלה ללא כותרת",
    Logic_Issue_NoQuestions: "הוסף/י לפחות שאלה אחת לפני איסוף תשובות.",
    Logic_Issue_NoTitle: "לשאלה אין טקסט – היא תקבל שם אוטומטית בעת הפרסום.",
    Logic_Issue_DuplicateTitle: "הטקסט של {label} זהה לשאלה אחרת, מה שמקשה על קריאת התוצאות.",
    Logic_Issue_NeedTwoOptions: "{label} דורש לפחות שתי אפשרויות.",
    Logic_Issue_ImageNoImage: "ל-{label} יש אפשרויות ללא תמונה – הן יוצגו כאריחי טקסט.",
    Logic_Issue_LikertNeedRow: "{label} דורש לפחות שורה אחת.",
    Logic_Issue_LikertNeedColumns: "{label} דורש לפחות שתי עמודות סולם.",
    Logic_Issue_NoLookupList: "לא נבחרה רשימת מקור עבור {label}.",
    Logic_Issue_NoFormula: "ל-{label} אין נוסחה.",
    Logic_Issue_BadFormula: "לא ניתן לחשב את הנוסחה של {label}. בדוק/י את הסוגריים והאופרטורים.",
    Logic_Issue_MissingRefs: "{label} מפנה לשאלות שאינן קיימות: {names}.",
    Logic_Issue_BadPattern: "ל-{label} יש תבנית אימות לא תקינה.",
    Logic_Issue_BrokenRule: "ל-{label} יש כלל הסתעפות המפנה לשאלה שנמחקה.",
    Logic_Issue_SelfRule: "ל-{label} יש כלל הסתעפות המפנה לעצמו.",
    Logic_Issue_RuleMismatch: "ל-{label} יש כלל הסתעפות שאינו מתאים עוד לשאלה שעליה הוא תלוי.",
    Logic_Issue_RequiredReadOnly: "{label} הוא גם שדה חובה וגם לקריאה בלבד, ולכן ניתן לענות עליו רק באמצעות קישור ממולא מראש.",
    Logic_Issue_EmptySection: "בקטע אין שאלות והוא ידולג.",
    Logic_Issue_CloseBeforeOpen: "תאריך הסגירה חל לפני תאריך הפתיחה או באותו יום, ולכן הטופס לעולם לא יקבל תשובות.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "הודעות דוא\"ל לאישור מופעלות, אך שלב האישור כבוי.",
    Logic_Op_equals: "הוא",
    Logic_Op_notEquals: "אינו",
    Logic_Op_contains: "מכיל",
    Logic_Op_notContains: "אינו מכיל",
    Logic_Op_notEmpty: "נענה",
    Logic_Op_empty: "לא נענה",
    Logic_Op_greaterThan: "גדול מ-",
    Logic_Op_greaterOrEqual: "הוא לפחות",
    Logic_Op_lessThan: "קטן מ-",
    Logic_Op_lessOrEqual: "הוא לכל היותר",
    Logic_Op_between: "נמצא בין",
    Logic_Op_before: "הוא לפני",
    Logic_Op_after: "הוא אחרי",
    Logic_Type_Text: "תשובה קצרה",
    Logic_TypeDesc_Text: "שורת טקסט אחת",
    Logic_Category_Text: "טקסט",
    Logic_Type_MultilineText: "תשובה ארוכה",
    Logic_TypeDesc_MultilineText: "מספר שורות של טקסט רגיל",
    Logic_Type_RichText: "טקסט מעוצב",
    Logic_TypeDesc_RichText: "הדגשה, רשימות וקישורים",
    Logic_Type_Choice: "בחירה",
    Logic_TypeDesc_Choice: "בחירה מתוך רשימת אפשרויות",
    Logic_Category_Choice: "בחירה",
    Logic_Type_ImageChoice: "בחירת תמונה",
    Logic_TypeDesc_ImageChoice: "בחירה מתוך אריחי תמונות",
    Logic_Type_Lookup: "בחירה מרשימה",
    Logic_TypeDesc_Lookup: "אפשרויות הנקראות בזמן אמת מרשימת SharePoint אחרת",
    Logic_Type_YesNo: "כן / לא",
    Logic_TypeDesc_YesNo: "מתג פשוט של הפעלה/כיבוי",
    Logic_Type_Consent: "הסכמה",
    Logic_TypeDesc_Consent: "תיבת סימון שהמשיב/ה חייב/ת לסמן כדי להמשיך",
    Logic_Type_Ranking: "דירוג",
    Logic_TypeDesc_Ranking: "גרור/י אפשרויות לפי סדר העדפה",
    Logic_Type_Rating: "דירוג בכוכבים",
    Logic_TypeDesc_Rating: "כוכבים, לבבות או אגודלים",
    Logic_Category_Scales: "סולמות",
    Logic_Type_Scale: "סולם דעה",
    Logic_TypeDesc_Scale: "סולם ממוספר עם תוויות בקצוות",
    Logic_Type_Slider: "מחוון",
    Logic_TypeDesc_Slider: "ערך על סולם הזזה",
    Logic_Type_Likert: "טבלת ליקרט",
    Logic_TypeDesc_Likert: "דרג/י מספר היגדים בסולם משותף אחד",
    Logic_Type_Number: "מספר",
    Logic_TypeDesc_Number: "רגיל, מטבע או אחוז",
    Logic_Category_Advanced: "מתקדם",
    Logic_Type_Calculated: "מחושב",
    Logic_TypeDesc_Calculated: "סכום לקריאה בלבד המחושב מתשובות אחרות",
    Logic_Type_Date: "תאריך",
    Logic_TypeDesc_Date: "תאריך בלוח שנה, עם שעה כאפשרות",
    Logic_Category_Date: "תאריך",
    Logic_Type_Time: "שעה",
    Logic_TypeDesc_Time: "שעה ביום בלבד",
    Logic_Type_Person: "אדם",
    Logic_TypeDesc_Person: "בחר/י אדם מתוך הארגון",
    Logic_Category_People: "אנשים",
    Logic_Type_Email: "דוא\"ל",
    Logic_TypeDesc_Email: "כתובת דוא\"ל, עם אימות",
    Logic_Type_Phone: "טלפון",
    Logic_TypeDesc_Phone: "מספר טלפון, עם אימות",
    Logic_Type_Address: "כתובת",
    Logic_TypeDesc_Address: "רחוב, עיר, מיקוד ומדינה",
    Logic_Type_Hyperlink: "קישור",
    Logic_TypeDesc_Hyperlink: "כתובת אינטרנט",
    Logic_Type_FileUpload: "העלאת קובץ",
    Logic_TypeDesc_FileUpload: "צרף/י קובץ אחד או יותר לתשובה",
    Logic_Type_Signature: "חתימה",
    Logic_TypeDesc_Signature: "חתום/י בעכבר, בעט או באצבע",
    Logic_Type_Content: "בלוק טקסט",
    Logic_TypeDesc_Content: "הוראות או תמונה – אינו אוסף תשובה",
    Logic_Category_Layout: "פריסה",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "באיזו מידה סביר שתמליץ/י על…",
    Logic_Preset_satisfaction: "שביעות רצון (1–5)",
    Logic_PresetDesc_satisfaction: "מלא חוסר שביעות רצון עד שביעות רצון מלאה",
    Logic_Preset_currency: "מטבע",
    Logic_PresetDesc_currency: "סכום כסף",
    Logic_Preset_percent: "אחוז",
    Logic_PresetDesc_percent: "ערך באחוזים",
    Logic_Template_blank_Name: "טופס ריק",
    Logic_Template_blank_Description: "התחל/י מאפס",
    Logic_Template_feedback_Name: "משוב לקוחות",
    Logic_Template_feedback_Description: "NPS, דירוגים והערות חופשיות",
    Logic_Template_event_Name: "הרשמה לאירוע",
    Logic_Template_event_Description: "פרטי משתתפים, מפגשים והעדפות תזונה",
    Logic_Template_itrequest_Name: "בקשת שירות IT",
    Logic_Template_itrequest_Description: "בקשות מסווגות עם עדיפות וקבצים מצורפים",
    Logic_Template_expense_Name: "בקשת החזר הוצאות",
    Logic_Template_expense_Description: "פריטים, קבלות וסכום כולל מחושב",
    Logic_Template_pulse_Name: "סקר דופק עובדים",
    Logic_Template_pulse_Description: "טבלת ליקרט, סולם מעורבות והערת אנונימיות",
    Logic_Template_safety_Name: "בדיקת בטיחות",
    Logic_Template_safety_Description: "רשימת בדיקה, תמונות וחתימה",
    Logic_Template_booking_Name: "הזמנת חדר או משאב",
    Logic_Template_booking_Description: "בורר משאבים מבוסס רשימה עם משבצת זמן",
    Charts_ColumnChartAria: "תרשים עמודות עם {count} קטגוריות",
    Charts_DonutChartAria: "תרשים טבעת של {count} קטגוריות",
    Charts_NoAnswers: "עדיין אין תשובות.",
    Charts_NoResponses: "עדיין אין תשובות.",
    Charts_Responses: "תשובות",
    Charts_ResponsesOverTime: "תשובות לאורך זמן",
    Responses_Chart_Answer: "תשובה",
    Responses_Chart_Average: "ממוצע",
    Responses_Chart_AverageOf: "ממוצע של {count}",
    Responses_Chart_AveragePosition: "מיקום ממוצע",
    Responses_Chart_AverageRange: "ממוצע (1–{max})",
    Responses_Chart_AvgValue: "ממוצע {value}",
    Responses_Chart_Detractors: "מבקרים (0–6)",
    Responses_Chart_Max: "מקס'",
    Responses_Chart_Maximum: "מקסימום",
    Responses_Chart_Median: "חציון",
    Responses_Chart_MentionOne: "אזכור {count}",
    Responses_Chart_MentionOther: "{count} אזכורים",
    Responses_Chart_Min: "מינ'",
    Responses_Chart_Minimum: "מינימום",
    Responses_Chart_NoAnswers: "עדיין אין תשובות.",
    Responses_Chart_NoNumeric: "עדיין אין תשובות מספריות.",
    Responses_Chart_NoRankings: "עדיין אין דירוגים.",
    Responses_Chart_NoScores: "עדיין אין ציונים.",
    Responses_Chart_NotEnoughText: "עדיין אין מספיק טקסט לסיכום.",
    Responses_Chart_NpsScore: "ציון NPS",
    Responses_Chart_Option: "אפשרות",
    Responses_Chart_Passives: "פסיביים (7–8)",
    Responses_Chart_Promoters: "מקדמים (9–10)",
    Responses_Chart_ResponseOne: "תשובה",
    Responses_Chart_ResponseOther: "תשובות",
    Responses_Chart_Responses: "תשובות",
    Responses_Chart_ShowingAnswers: "מוצגות {shown} מתוך {total} תשובות.",
    Responses_Chart_Statement: "היגד",
    Responses_Chart_Statistic: "סטטיסטיקה",
    Responses_Chart_StdDev: "סטיית תקן",
    Responses_Chart_StdDeviation: "סטיית תקן",
    Responses_Chart_Total: "סה\"כ",
    Responses_Chart_Value: "ערך",
    Responses_Dashboard_AllHidden: "כל השאלות מוסתרות מלוח המחוונים. השתמש ב“הצגת שאלות מוסתרות” כדי להחזיר אותן.",
    Responses_Dashboard_AnsweredOf: "נענו {answered} מתוך {total}",
    Responses_Dashboard_AnsweredOfPinned: "נענו {answered} מתוך {total} · מוצמד",
    Responses_Dashboard_AveragedAcrossResponses: "ממוצע בין התשובות",
    Responses_Dashboard_ByDay: "לפי יום",
    Responses_Dashboard_ByMonth: "לפי חודש",
    Responses_Dashboard_ByWeek: "לפי שבוע",
    Responses_Dashboard_ChartAuto: "אוטומטי",
    Responses_Dashboard_ChartBars: "פסים",
    Responses_Dashboard_ChartColumns: "עמודות",
    Responses_Dashboard_ChartDonut: "טבעת",
    Responses_Dashboard_ChartGauge: "מד",
    Responses_Dashboard_ChartHistogram: "היסטוגרמה",
    Responses_Dashboard_ChartOptions: "אפשרויות תרשים",
    Responses_Dashboard_ChartOptionsFor: "אפשרויות תרשים עבור {title}",
    Responses_Dashboard_ChartStatistics: "סטטיסטיקה",
    Responses_Dashboard_ChartTable: "טבלה",
    Responses_Dashboard_ChartWordFrequency: "שכיחות מילים",
    Responses_Dashboard_EmptyBody: "ברגע שאנשים יתחילו לענות, לוח המחוונים ימולא אוטומטית – מספרים עיקריים, ציר זמן של תשובות ותרשים לשאלות ששווה לעקוב אחריהן.",
    Responses_Dashboard_EmptyTitle: "עדיין אין תשובות",
    Responses_Dashboard_Hide: "הסתרה מלוח המחוונים",
    Responses_Dashboard_Highlights: "עיקרי הדברים",
    Responses_Dashboard_Last7Days: "7 הימים האחרונים",
    Responses_Dashboard_LatestDate: "אחרון: {date}",
    Responses_Dashboard_MedianTimeToComplete: "זמן חציוני להשלמה",
    Responses_Dashboard_NoPriorWeek: "אין שבוע קודם להשוואה",
    Responses_Dashboard_OneEach: "אחת לכל אחד",
    Responses_Dashboard_Pin: "הצמדה ללוח המחוונים",
    Responses_Dashboard_QuestionFallback: "שאלה",
    Responses_Dashboard_QuestionsAnswered: "שאלות שנענו",
    Responses_Dashboard_RecordedOnSubmit: "נרשם בעת השליחה",
    Responses_Dashboard_RepeatResponses: "{count} תשובות חוזרות",
    Responses_Dashboard_ResponsesOverTime: "תשובות לאורך זמן",
    Responses_Dashboard_ShowHidden: "הצגת שאלות מוסתרות",
    Responses_Dashboard_SinceMidnight: "מאז חצות",
    Responses_Dashboard_Today: "היום",
    Responses_Dashboard_TotalResponses: "סה\"כ תשובות",
    Responses_Dashboard_UniqueRespondents: "משיבים ייחודיים",
    Responses_Dashboard_Unpin: "ביטול הצמדה ללוח המחוונים",
    Responses_Dashboard_UntitledQuestion: "שאלה ללא כותרת",
    Responses_Dashboard_VsPrevious7Days: "לעומת 7 הימים הקודמים",
    Responses_Detail_Answers: "תשובות",
    Responses_Detail_AsTheForm: "כפי שבטופס",
    Responses_Detail_Cancel: "ביטול",
    Responses_Detail_Delete: "מחיקה",
    Responses_Detail_DeleteBody: "פריט הרשימה מועבר לסל המחזור של האתר, ולכן ניתן לשחזר אותו משם.",
    Responses_Detail_DeleteTitle: "למחוק תשובה זו?",
    Responses_Detail_Deleting: "מוחק…",
    Responses_Detail_Draft: "טיוטה",
    Responses_Detail_Header: "תשובה {index} מתוך {total}",
    Responses_Detail_LoadingAttachments: "טוען קבצים מצורפים…",
    Responses_Detail_Next: "התשובה הבאה",
    Responses_Detail_NoAnswer: "אין תשובה",
    Responses_Detail_Previous: "התשובה הקודמת",
    Responses_Detail_Print: "הדפסה",
    Responses_Detail_Signature: "חתימה",
    Responses_Detail_Signed: "חתום",
    Responses_Detail_Took: "נמשך {duration}",
    Responses_Summary_AnsweredOfType: "נענו {answered} מתוך {total} · {type}",
    Responses_Summary_ByField: "לפי {title}",
    Responses_Summary_CompareBy: "השוואה לפי…",
    Responses_Summary_EmptyBody: "לכל שאלה יהיה כאן סיכום משלה.",
    Responses_Summary_NoComparison: "ללא השוואה",
    Responses_Summary_NothingToCompare: "אף תשובה לא ענתה על “{title}”, ולכן אין מה להשוות.",
    Responses_Summary_OtherNote: "תרשימים עם יותר מ-{max} קטגוריות מקבצים את הקטנות ביותר תחת “אחר” – עבור לתצוגת טבלה בכרטיס כדי לראות כל ערך.",
    Responses_Summary_ResponseCountOne: "תשובה {count}",
    Responses_Summary_ResponseCountOther: "{count} תשובות",
    Responses_Summary_SeeAllAnswers: "הצגת כל התשובות בטבלה",
    Responses_Summary_SegmentNote: "מוצגות {groups} הקבוצות הגדולות ביותר. תשובה שבחרה כמה אפשרויות מופיעה בכל קבוצה תואמת, ולכן סכומי הקבוצות עשויים לעלות על {total}.",
    Responses_Summary_SplitBy: "פיצול לפי {title}",
    Responses_Summary_Untitled: "ללא כותרת",
    Responses_Table_Apply: "החל",
    Responses_Table_Cancel: "ביטול",
    Responses_Table_ClearSelection: "ניקוי הבחירה",
    Responses_Table_ColumnOrder: "סדר העמודות",
    Responses_Table_ColumnsCount: "עמודות ({shown}/{total})",
    Responses_Table_Delete: "מחיקה",
    Responses_Table_DeleteBody: "פריטי הרשימה מועברים לסל המחזור של האתר, ולכן ניתן לשחזר אותם משם.",
    Responses_Table_DeleteSelected: "מחיקת הנבחרים",
    Responses_Table_DeleteTitleOne: "למחוק תשובה {count}?",
    Responses_Table_DeleteTitleOther: "למחוק {count} תשובות?",
    Responses_Table_Deleting: "מוחק…",
    Responses_Table_MoveDown: "הזזה למטה",
    Responses_Table_MoveDownFor: "הזזת {title} למטה",
    Responses_Table_MoveUp: "הזזה למעלה",
    Responses_Table_MoveUpFor: "הזזת {title} למעלה",
    Responses_Table_NoColumns: "עדיין אין עמודות שאלות גלויות.",
    Responses_Table_NoMatch: "אין תשובות התואמות למסננים הנוכחיים.",
    Responses_Table_NothingToShow: "אין מה להציג",
    Responses_Table_OpenResponse: "פתיחת תשובה זו",
    Responses_Table_OrderNote: "העמודות \"נשלח\" ו\"נשלח על ידי\" תמיד ראשונות. סדר הגרירה חל על עמודות השאלות.",
    Responses_Table_Reorder: "סידור מחדש",
    Responses_Table_ResetColumns: "איפוס עמודות",
    Responses_Table_SelectResponse: "בחירת תשובה זו",
    Responses_Table_SelectedOne: "נבחרה תשובה {count}",
    Responses_Table_SelectedOther: "נבחרו {count} תשובות",
    Responses_Table_ShowAll: "הצג הכל",
    Responses_Table_ShowTheseQuestions: "הצגת שאלות אלה",
    Responses_Table_Submitted: "נשלח",
    Responses_Table_SubmittedBy: "נשלח על ידי",
    Responses_Table_ToggleSelection: "החלפת מצב בחירה",
    Responses_Table_Unknown: "לא ידוע",
    Responses_Table_Untitled: "ללא כותרת",
    Responses_View_AllTime: "כל הזמן",
    Responses_View_AnyAnswer: "כל תשובה",
    Responses_View_Clear: "ניקוי",
    Responses_View_CopyShareLink: "העתקת קישור לשיתוף",
    Responses_View_CountFiltered: "{shown} מתוך {total} תשובות",
    Responses_View_CountOne: "תשובה {count}",
    Responses_View_CountOther: "{count} תשובות",
    Responses_View_Dashboard: "לוח מחוונים",
    Responses_View_DateRange: "טווח תאריכים",
    Responses_View_EmptyBody: "שתף את הטופס כדי להתחיל לאסוף תשובות. התשובות נשמרות ב-“{list}” ומופיעות כאן מיד.",
    Responses_View_EmptyTitle: "עדיין אין תשובות",
    Responses_View_ExportCsv: "ייצוא ל-CSV",
    Responses_View_FilterByAnswer: "סינון לפי תשובה",
    Responses_View_FilterByQuestion: "סינון לפי שאלה",
    Responses_View_FilterValue: "ערך המסנן",
    Responses_View_Last30Days: "30 הימים האחרונים",
    Responses_View_Last7Days: "7 הימים האחרונים",
    Responses_View_Last90Days: "90 הימים האחרונים",
    Responses_View_LoadError: "לא ניתן היה לטעון את התשובות. פרסם את הטופס פעם אחת כדי שעמודות הרשימה יווצרו, ואז נסה שוב.",
    Responses_View_Loading: "טוען תשובות…",
    Responses_View_MoreActions: "פעולות נוספות בתשובות",
    Responses_View_PreviewForm: "תצוגה מקדימה של הטופס",
    Responses_View_Refresh: "רענון",
    Responses_View_ResponsesTab: "תשובות ({count})",
    Responses_View_SearchPlaceholder: "חיפוש בכל התשובות",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "בחירת ערך",
    Responses_View_Summary: "סיכום",
    Responses_View_Today: "היום",
    Responses_View_Truncated: "ברשימה זו יש יותר תשובות ממה ש-Smart Forms טוען בבת אחת. מוצגות {count} התשובות החדשות ביותר – פתח את הרשימה ב-Microsoft Lists כדי לראות את הכול.",
    Responses_View_TryAgain: "נסה שוב",
    Responses_View_Untitled: "ללא כותרת",
    Responses_Approval_Column: "אישור",
    Responses_Approval_ReviewerColumn: "נבדק על ידי",
    Responses_Approval_CommentColumn: "הערת הבודק",
    Responses_Approval_Pending: "ממתין",
    Responses_Approval_Approved: "אושר",
    Responses_Approval_Rejected: "נדחה",
    Responses_Approval_AnyStatus: "כל סטטוס אישור",
    Responses_Approval_FilterLabel: "סינון לפי סטטוס אישור",
    Responses_Approval_ApproveSelected: "אישור הנבחרים",
    Responses_Approval_RejectSelected: "דחיית הנבחרים",
    Responses_Approval_BulkFailed: "לא ניתן היה לעדכן {count} תשובות. נסה/י שוב.",
    Responses_Approval_Approve: "אישור",
    Responses_Approval_Reject: "דחייה",
    Responses_Approval_Reset: "איפוס להמתנה",
    Responses_Approval_CommentLabel: "הערה (אופציונלי)",
    Responses_Approval_ReviewedBy: "נבדק על ידי {name}",
    Responses_Approval_Error: "לא ניתן היה לשמור את ההחלטה. נסה/י שוב.",
    Responses_Dashboard_ApprovalStatus: "ממתין לבדיקה",
    Responses_Dashboard_ApprovalBreakdown: "{pending} ממתינות, {approved} אושרו, {rejected} נדחו",
    Responses_Dashboard_TimelineCoarsened: "טווח התאריכים ארוך, ולכן ציר הזמן קובץ בפירוט נמוך יותר ({grain}).",
    Responses_Dashboard_TimelineTruncated: "טווח התאריכים ארוך מאוד, ולכן מוצגות רק {count} התקופות האחרונות.",
    Service_Item_DefaultTitle: "תשובה — {date}",
    Service_Email_ApprovalSubject: "התשובה שלך {status} — {title}",
    Service_Email_ApprovalHeading: "התשובה שלך {status}",
    Service_Email_ApprovalIntro: "בודק סימן את התשובה שלך ל-\"{title}\" כ{status}.",
    Service_Email_ApprovalCommentLabel: "הערת הבודק",
    Service_Approval_Approved: "מאושרת",
    Service_Approval_Rejected: "נדחתה",
    Service_Approval_Pending: "ממתינה",
    Service_Lookup_InvalidFilter: "מסנן הבחירה אינו תקין.",
    Service_Edit_NotAllowed: "טופס זה אינו מאפשר עריכת תשובה שנשלחה.",
    Service_Edit_NotYours: "ניתן לערוך רק את התשובה שלך.",
    Service_Signature_AttachmentLabel: "חתימה",
    PropertyPane_ListsLoadFailed: "לא ניתן היה לטעון את הרשימות באתר זה.",
    PropertyPane_EnterListName: "הזן תחילה שם לרשימה החדשה.",
    PropertyPane_CreatingList: "יוצר את \"{name}\"…",
    PropertyPane_ListCreated: "הרשימה \"{title}\" נוצרה ונבחרה.",
    PropertyPane_ListAlreadyExists: "כבר קיימת רשימה בשם \"{name}\" – בחר אותה מהרשימה הנפתחת שלמעלה.",
    PropertyPane_CreateListFailed: "לא ניתן היה ליצור את הרשימה. ודא שיש לך הרשאה ליצור רשימות באתר זה.",
    PropertyPane_Description: "בחר את רשימת SharePoint שבה יאוחסנו תשובות הטופס, או צור רשימה חדשה. כל השאר – שאלות, מראה והתראות – נערך ישירות בדף.",
    PropertyPane_ResponseList_GroupName: "רשימת תשובות",
    PropertyPane_ListDropdown_Label: "שמירת התשובות ברשימה זו",
    PropertyPane_ResponsesGoTo: "התשובות נשמרות ב-\"{name}\".",
    PropertyPane_PickList: "בחר רשימה, או צור אחת למטה.",
    PropertyPane_LoadingLists: "טוען רשימות…",
    PropertyPane_NewListName_Label: "או צור רשימה חדשה",
    PropertyPane_NewListName_Placeholder: "שם הרשימה החדשה",
    PropertyPane_CreateList_Button: "יצירת רשימה",
    PropertyPane_Tips_GroupName: "טיפים",
    PropertyPane_Tip_AutoSave: "שאלות והגדרות נשמרות אוטומטית תוך כדי עריכה – אין צורך לשמור או לפרסם את הדף.",
    PropertyPane_Tip_Permissions: "משיבים זקוקים להרשאה להוסיף פריטים לרשימת התשובות. בדוק את הרשאות הרשימה אם מישהו מדווח על שגיאה בעת השליחה.",
    PropertyPane_Tip_Share: "השתמש ב-\"איסוף תשובות\" בדף כדי ליצור את עמודות הרשימה ולקבל קישור למילוי שניתן לשתף.",
    App_ErrorBoundary_Title: "Smart Forms – שגיאת עיבוד",
    App_ErrorBoundary_Message: "הודעה:",
    App_ErrorBoundary_Stack: "מחסנית:",
    App_ErrorBoundary_NoStack: "(אין מחסנית זמינה)",
    App_ErrorBoundary_ConsoleNote: "כל הפרטים נכתבו גם למסוף הדפדפן.",
    App_DefaultQuestionTitle: "שאלה {number}",
    App_Error_ListMissing: "הרשימה שהוגדרה לטופס זה כבר אינה קיימת. בחר רשימה אחרת בהגדרות רכיב האינטרנט.",
    App_Error_LoadConfig: "אירעה שגיאה בטעינת תצורת הטופס.",
    App_Error_Unable: "לא ניתן לטעון את הטופס.",
    App_Publish_ConflictNotice: "ל-\"{title}\" כבר יש עמודת רשימה מסוג אחר ({type}). שנה את שם השאלה כדי שניתן יהיה ליצור עמודה חדשה, או החזר את הסוג.",
    App_Publish_ConflictUnnamedQuestion: "שאלה",
    App_Publish_ColumnsAddedOne: "עמודה {count} נוספה ל-\"{list}\".",
    App_Publish_ColumnsAddedOther: "{count} עמודות נוספו ל-\"{list}\".",
    App_Publish_TheList: "הרשימה",
    App_Publish_UpToDate: "רשימת התשובות כבר מעודכנת.",
    App_Publish_Error: "לא ניתן היה ליצור את עמודות הרשימה. בדרך כלל פירוש הדבר שאין לך הרשאת ניהול רשימות ברשימת התשובות, אך הדבר עשוי לקרות גם באתרים שבהם סקריפטים מותאמים אישית מושבתים. בדוק את מסוף הדפדפן לקבלת השגיאה הבסיסית, או נסה שוב.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "בנה טופס מלוטש על גבי רשימת SharePoint – {count} סוגי שאלות, לוגיקת הסתעפות, העלאת קבצים, קישורי מילוי לשיתוף ולוח מחוונים לתוצאות.",
    App_Placeholder_ChooseList: "בחירה או יצירה של רשימה",
    App_Placeholder_Hint: "ערוך את הדף והגדר את רכיב האינטרנט כדי להתחיל.",
    App_Loading: "טוען את הטופס…",
    App_OpenSettings: "פתיחת הגדרות",
    App_Tab_Questions: "שאלות",
    App_Tab_QuestionsWithCount: "שאלות ({count})",
    App_Tab_Responses: "תשובות",
    App_Tab_Responses_Title: "התשובות נשמרות ב-\"{list}\"",
    App_Templates_Start: "התחלה מתבנית",
    App_Settings_Title: "הגדרות טופס – מראה, התראות, גישה",
    App_Settings_AriaLabel: "הגדרות טופס",
    App_Preview: "תצוגה מקדימה",
    App_Preview_Close: "סגירת התצוגה המקדימה",
    App_Preview_Hint: "תצוגה מקדימה – דבר ממה שתשלח כאן אינו נשמר. האימות וההסתעפות פועלים בדיוק כפי שיפעלו עבור משיבים.",
    App_Publish_GettingReady: "מתכונן…",
    App_Publish_CollectResponses: "איסוף תשובות",
    App_Publish_Share: "שיתוף",
    App_Retry: "נסה שוב",
    App_SaveError_Banner: "לא ניתן היה לשמור את השינוי האחרון שלך. בדוק את החיבור ונסה שוב.",
    App_Preflight_BlockingTitle: "תקן את אלה לפני האיסוף",
    App_Preflight_WarningTitle: "כדאי לבדוק קודם",
    App_Preflight_BlockingText: "אלה ימנעו מהטופס שפורסם לפעול כראוי.",
    App_Preflight_WarningText: "שום דבר אינו שבור, אך בדרך כלל כדאי לתקן את אלה לפני שיתוף הקישור.",
    App_Preflight_GoTo: "מעבר אל",
    App_Preflight_CollectAnyway: "איסוף תשובות בכל זאת",
    App_Preflight_Back: "חזרה לטופס",
    App_Cancel: "ביטול",
    App_Done: "סיום",
    App_Share_Title: "הטופס שלך מוכן לשיתוף",
    App_Share_SubText: "שלח קישור זה לכל מי שצריך למלא את הטופס.",
    App_Share_LinkAriaLabel: "קישור לשיתוף",
    App_Share_Copy: "העתקה",
    App_Share_Copied: "הועתק",
    App_Share_AddItemsEmphasis: "להוסיף פריטים",
    App_Share_PermissionNote: "משיבים זקוקים להרשאה {addItems} ל-“{title}” ולגישה לדף זה. אם מישהו מקבל שגיאה בעת השליחה, זו כמעט תמיד הסיבה.",
    App_Share_PrefillNote: "אפשר למלא שאלות מראש בקישור על ידי הוספת שם העמודה, לדוגמה {example}.",
    App_Templates_ReplaceWarning: "בחירת תבנית מחליפה את השאלות הקיימות.",
    App_Templates_PickStart: "בחר נקודת פתיחה – אפשר לשנות הכול לאחר מכן.",
    App_Templates_Empty: "ריק",
    App_Templates_QuestionCount: "{count} שאלות",
    App_SaveChip_SavingTitle: "שומר את העריכה האחרונה שלך",
    App_SaveChip_Saving: "שומר…",
    App_SaveChip_FailedTitle: "לא ניתן היה לשמור את העריכה האחרונה שלך. בדוק את החיבור ונסה שוב.",
    App_SaveChip_Failed: "השמירה נכשלה",
    App_SaveChip_SavedTitle: "כל השינויים נשמרו",
    App_SaveChip_Saved: "נשמר",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "תשובה חדשה – {title}",
    Service_Email_NewResponseHeading: "תשובה חדשה: {title}",
    Service_Email_NewResponseIntro: "מישהו שלח זה עתה תשובה – {date}.",
    Service_Email_ReceiptSubject: "התשובה שלך – {title}",
    Service_Email_ReceiptHeading: "תודה על תשובתך!",
    Service_Email_ReceiptIntro: "הנה עותק של מה ששלחת אל \"{title}\".",
    App_History_Title: "היסטוריית גרסאות",
    App_History_RestoredNotice: "הגרסה שנשמרה ב-{date} שוחזרה. בדוק/י אותה, ולאחר מכן השתמש/י באיסוף תשובות כדי לפרסם שאלות חדשות.",
    App_History_Undo: "ביטול השחזור",
    App_Share_CopyManual: "הדפדפן חסם את ההעתקה. בחר/י את הקישור שלמעלה ולחץ/י על Ctrl+C (Cmd+C ב-Mac) כדי להעתיק אותו.",
    App_Share_TeamsNote: "את/ה ב-Microsoft Teams. קישור זה פותח ישירות את דף SharePoint, ולכן הנמענים זקוקים לגישה לאתר.",
    App_Share_PrefillNotSecure: "תשובות ממולאות מראש נועדו לנוחות בלבד: כל מי שיש לו את הקישור יכול לשנות אותן, ולכן אין להתייחס אליהן כגבול אבטחה.",
    Designer_Section_DropHere: "גרור/י שאלה לכאן",
    Designer_Section_DropEnd: "שחרר/י כאן כדי להעביר לסוף הקטע",
    Designer_Rules_RemovedOne: "כלל הסתעפות אחד שאינו מתאים עוד הוסר.",
    Designer_Rules_RemovedOther: "{count} כללי הסתעפות שאינם מתאימים עוד הוסרו.",
    Designer_Settings_AllowEdit: "אפשר למשיבים לערוך את תשובתם",
    Designer_Settings_AllowEditHint: "משיבים יכולים לפתוח מחדש ולעדכן את מה ששלחו. כל אדם יכול לערוך רק את התשובה שלו.",
    Designer_Settings_EnableApproval: "הפעלת תהליך אישור",
    Designer_Settings_ApprovalNotify: "שליחת דוא\"ל למשיב לאחר החלטה",
    Designer_Settings_ApprovalHint: "מוסיף עמודות אישור לרשימת התשובות בפרסום הבא. בעלים מאשרים או דוחים תשובות בכרטיסייה \"תשובות\".",
    Designer_History_Title: "היסטוריית גרסאות",
    Designer_History_Intro: "גרסאות שנשמרו קודם של השאלות וההגדרות בטופס זה. שחזור טוען גרסה למעצב; ניתן לבטל אותו, ושאלות חדשות נוצרות רק בעת הפרסום.",
    Designer_History_Loading: "טוען גרסאות...",
    Designer_History_Empty: "לא נמצאו גרסאות קודמות. היסטוריית גרסאות דורשת שניהול גרסאות יהיה מופעל ברשימה \"Smart Forms Config\" ושתהיה לפחות עריכה אחת שנשמרה.",
    Designer_History_Latest: "אחרונה",
    Designer_History_LatestTitle: "זוהי הגרסה שבשימוש כעת",
    Designer_History_By: "על ידי {name}",
    Designer_History_UnknownAuthor: "מחבר לא ידוע",
    Designer_History_VersionLabel: "גרסה {label}",
    Designer_History_Preview: "תצוגה מקדימה",
    Designer_History_Restore: "שחזור",
    Designer_History_QuestionsOne: "שאלה אחת",
    Designer_History_QuestionsOther: "{count} שאלות",
    Designer_History_LoadFailed: "לא ניתן היה לטעון גרסה זו.",
    Designer_History_ConfirmTitle: "לשחזר גרסה זו?",
    Designer_History_ConfirmText: "הטופס יוחלף בגרסה שנשמרה ב-{date} ({count} שאלות). ניתן לבטל זאת מיד לאחר מכן."
  };
});
