define([], function () {
  return {
    Designer_Color_Blue: "नीला",
    Designer_Color_Teal: "टील",
    Designer_Color_Green: "हरा",
    Designer_Color_Purple: "बैंगनी",
    Designer_Color_Magenta: "मैजेंटा",
    Designer_Color_Red: "लाल",
    Designer_Color_Orange: "नारंगी",
    Designer_Color_Gray: "स्लेटी",
    Designer_Settings_LayoutSinglePage: "सभी प्रश्न एक ही पृष्ठ पर",
    Designer_Settings_LayoutWizard: "प्रति चरण एक अनुभाग (विज़ार्ड)",
    Designer_Settings_Title: "फ़ॉर्म सेटिंग",
    Designer_Common_Apply: "लागू करें",
    Designer_Common_Cancel: "रद्द करें",
    Designer_Settings_TabBasics: "मूल बातें",
    Designer_Settings_FormTitle: "फ़ॉर्म का शीर्षक",
    Designer_Settings_Description: "विवरण",
    Designer_Settings_Layout: "लेआउट",
    Designer_Settings_NumberQuestions: "प्रश्नों को क्रमांकित करें",
    Designer_Settings_ShuffleQuestions: "प्रत्येक प्रतिभागी के लिए प्रश्नों का क्रम बदलें",
    Designer_Settings_ShowProgressBar: "प्रगति पट्टी दिखाएँ",
    Designer_Settings_TabAppearance: "रूप-रंग",
    Designer_Settings_AccentColor: "एक्सेंट रंग",
    Designer_Settings_CustomColorTitle: "कस्टम रंग",
    Designer_Settings_CustomColorAria: "कस्टम एक्सेंट रंग",
    Designer_Settings_AccentHint: "डार्क साइटों पर कंट्रास्ट के लिए एक्सेंट रंग अपने-आप समायोजित हो जाते हैं, ताकि पृष्ठ का थीम कोई भी हो, फ़ॉर्म पढ़ने योग्य रहे।",
    Designer_Settings_ShowHeader: "फ़ॉर्म हेडर दिखाएँ",
    Designer_Settings_HeaderIcon: "हेडर आइकन",
    Designer_Settings_TabAfterSubmit: "सबमिट के बाद",
    Designer_Settings_SubmitButtonText: "सबमिट बटन का टेक्स्ट",
    Designer_Settings_SubmitPlaceholder: "सबमिट करें",
    Designer_Settings_ThankYouTitle: "धन्यवाद शीर्षक",
    Designer_Settings_ThankYouPlaceholder: "धन्यवाद!",
    Designer_Settings_ThankYouMessage: "धन्यवाद संदेश",
    Designer_Settings_ShowSubmitAnother: "\"दूसरी प्रतिक्रिया सबमिट करें\" बटन दिखाएँ",
    Designer_Settings_TabNotifications: "सूचनाएँ",
    Designer_Settings_EmailEachResponseTo: "प्रत्येक प्रतिक्रिया ईमेल करें",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "आपके संगठन के लोगों को हर प्रतिक्रिया ईमेल से मिलती है, साथ में सूची आइटम का लिंक भी होता है",
    Designer_Settings_RespondentReceipt: "प्रतिभागियों को उनके उत्तरों की प्रति ईमेल करें",
    Designer_Settings_NotificationsInfo: "सूचनाएँ SharePoint की अपनी मेल सेवा का उपयोग करती हैं, इसलिए प्राप्तकर्ता आपके संगठन के उपयोगकर्ता होने चाहिए। बाहरी पते चुपचाप हटा दिए जाते हैं।",
    Designer_Settings_TabAccess: "एक्सेस",
    Designer_Settings_OpenFrom: "इस समय से खोलें",
    Designer_Settings_OpenImmediately: "तुरंत खोलें",
    Designer_Settings_CloseAfter: "इसके बाद बंद करें",
    Designer_Settings_NeverClose: "कभी बंद न करें",
    Designer_Settings_ClearDates: "तिथियाँ साफ़ करें",
    Designer_Settings_DatesInverted: "बंद होने की तिथि खुलने की तिथि पर या उससे पहले है, इसलिए फ़ॉर्म कभी प्रतिक्रियाएँ स्वीकार नहीं करेगा।",
    Designer_Settings_MaxResponses: "इतनी प्रतिक्रियाओं के बाद रोकें",
    Designer_Settings_NoLimit: "कोई सीमा नहीं",
    Designer_Settings_OneResponsePerPerson: "प्रति व्यक्ति केवल एक प्रतिक्रिया की अनुमति दें",
    Designer_Settings_AllowSaveDraft: "प्रतिभागियों को ड्राफ़्ट सहेजने और बाद में पूरा करने दें",
    Designer_Settings_ClosedMessage: "फ़ॉर्म बंद होने पर दिखाया जाने वाला संदेश",
    Designer_Settings_ClosedMessagePlaceholder: "यह फ़ॉर्म अब प्रतिक्रियाएँ स्वीकार नहीं कर रहा है।",
    Designer_Settings_AccessInfo: "ये सीमाएँ फ़ॉर्म द्वारा लागू की जाती हैं, SharePoint द्वारा नहीं। प्रतिक्रिया सूची में आइटम जोड़ने की अनुमति वाला कोई भी व्यक्ति फिर भी सीधे सूची के माध्यम से आइटम जोड़ सकता है।",
    Designer_Field_StyleInfo: "जानकारी (एक्सेंट)",
    Designer_Field_StyleSuccess: "सफलता (हरा)",
    Designer_Field_StyleWarning: "चेतावनी (एम्बर)",
    Designer_Field_StylePlain: "सादा टेक्स्ट",
    Designer_Field_StyleDivider: "विभाजक रेखा",
    Designer_Field_IconStars: "सितारे",
    Designer_Field_IconHearts: "दिल",
    Designer_Field_IconThumbs: "थम्ब्स अप",
    Designer_Field_FormatPlain: "सादी संख्या",
    Designer_Field_FormatCurrency: "मुद्रा",
    Designer_Field_FormatPercent: "प्रतिशत",
    Designer_Field_UntitledQuestion: "शीर्षकरहित प्रश्न",
    Designer_Field_DeletedQuestion: "हटाया गया प्रश्न",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} और {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "या",
    Designer_Rule_JoinAll: "और",
    Designer_Rule_Preview: "{conditions} होने पर दिखाया जाता है।",
    Designer_Field_Yes: "हाँ",
    Designer_Field_No: "नहीं",
    Designer_Field_When: "जब",
    Designer_Field_SelectValue: "मान चुनें",
    Designer_Field_DateValuePlaceholder: "YYYY-MM-DD या \"today\"",
    Designer_Field_ValuePlaceholder: "मान",
    Designer_Field_UpperBound: "ऊपरी सीमा",
    Designer_Field_RemoveCondition: "यह शर्त हटाएँ",
    Designer_Field_FormulaInvalid: "इस सूत्र की गणना नहीं की जा सकती। कोष्ठक और ऑपरेटर जाँचें।",
    Designer_Field_FormulaMissing: "ये प्रश्न मौजूद नहीं हैं: {names}।",
    Designer_Field_FormulaPreview: "हर इनपुट 10 होने पर यह {value} दिखाता है।",
    Designer_Field_HintYesNo: "\"yes\" या \"no\" का उपयोग करें",
    Designer_Field_HintMultiDefault: "एकाधिक डिफ़ॉल्ट को ; से अलग करें",
    Designer_Field_HintSingleDefault: "विकल्पों में से किसी एक से मेल खाना चाहिए",
    Designer_Field_HintDate: "\"today\" या 2026-03-01 जैसी तिथि का उपयोग करें",
    Designer_Field_HintTime: "\"now\" या 09:30 जैसे समय का उपयोग करें",
    Designer_Field_QuestionSettings: "प्रश्न सेटिंग",
    Designer_Field_Appearance: "रूप-रंग",
    Designer_Field_Style: "शैली",
    Designer_Field_ImageUrl: "छवि URL (वैकल्पिक)",
    Designer_Field_Content: "सामग्री",
    Designer_Field_BasicFormatting: "बुनियादी फ़ॉर्मेटिंग की अनुमति है: बोल्ड, इटैलिक, सूचियाँ और लिंक।",
    Designer_Field_TabOptions: "विकल्प",
    Designer_Field_TabBranching: "ब्रांचिंग",
    Designer_Field_BranchingNeedsQuestion: "पहले एक और प्रश्न जोड़ें — ब्रांचिंग के लिए किसी आधार प्रश्न की आवश्यकता होती है।",
    Designer_Field_BranchingToggle: "अन्य उत्तर मेल खाने पर ही यह प्रश्न दिखाएँ",
    Designer_Field_Match: "मिलान",
    Designer_Field_MatchAll: "इनमें से सभी",
    Designer_Field_MatchAny: "इनमें से कोई भी",
    Designer_Field_AddCondition: "शर्त जोड़ें",
    Designer_Field_TabValidation: "सत्यापन",
    Designer_Field_HelpText: "सहायता टेक्स्ट",
    Designer_Field_HelpTextPlaceholder: "प्रश्न लेबल के नीचे दिखाया जाता है",
    Designer_Field_CheckboxLabel: "चेकबॉक्स लेबल",
    Designer_Field_Placeholder: "प्लेसहोल्डर",
    Designer_Field_DefaultAnswer: "डिफ़ॉल्ट उत्तर",
    Designer_Field_RequiredMessage: "कस्टम आवश्यक संदेश",
    Designer_Field_RequiredMessagePlaceholder: "{title} आवश्यक है",
    Designer_Field_ThisQuestion: "यह प्रश्न",
    Designer_Field_RequiredMessageDescription: "प्रश्न खाली छोड़े जाने पर मानक संदेश के बजाय दिखाया जाता है",
    Designer_Field_ReadOnly: "केवल-पढ़ने योग्य (उत्तर केवल पहले से भरे लिंक से आ सकता है)",
    Designer_Field_ValidationRules: "सत्यापन नियम",
    Designer_Field_MaxLength: "अधिकतम लंबाई",
    Designer_Field_Pattern: "इस पैटर्न से मेल खाना चाहिए",
    Designer_Field_PatternDescription: "एक रेगुलर एक्सप्रेशन। पैटर्न जाँच न चाहिए तो खाली छोड़ें।",
    Designer_Field_PatternMessage: "पैटर्न मेल न खाने पर संदेश",
    Designer_Field_PatternMessagePlaceholder: "यह उत्तर अपेक्षित प्रारूप में नहीं है",
    Designer_Field_Format: "प्रारूप",
    Designer_Field_UnitSuffix: "मान के बाद दिखाई जाने वाली इकाई",
    Designer_Field_UnitSuffixPlaceholder: "kg, घंटे, आइटम…",
    Designer_Field_Minimum: "न्यूनतम",
    Designer_Field_Maximum: "अधिकतम",
    Designer_Field_Decimals: "दशमलव",
    Designer_Field_Formula: "सूत्र",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "अन्य प्रश्नों को उनके टेक्स्ट से ब्रेसिज़ में संदर्भित करें। + - * / ( ) और round, min, max, sum, avg समर्थित हैं।",
    Designer_Field_AvailableQuestions: "उपलब्ध प्रश्न: {questions}",
    Designer_Field_NoneYet: "अभी कोई नहीं",
    Designer_Field_Step: "चरण",
    Designer_Field_From: "से",
    Designer_Field_To: "तक",
    Designer_Field_LowLabel: "निचले छोर का लेबल",
    Designer_Field_LowLabelPlaceholder: "बिल्कुल संभावना नहीं",
    Designer_Field_HighLabel: "ऊपरी छोर का लेबल",
    Designer_Field_HighLabelPlaceholder: "अत्यंत संभावित",
    Designer_Field_SummarizeAs: "इस रूप में सारांशित करें",
    Designer_Field_SummarizeAverage: "औसत और वितरण",
    Designer_Field_SummarizeNps: "नेट प्रमोटर स्कोर (0–10 का पैमाना आवश्यक)",
    Designer_Field_NpsWarning: "नेट प्रमोटर स्कोर केवल 0–10 के पैमाने पर सार्थक है। से को 0 और तक को 10 पर सेट करें।",
    Designer_Field_NumberOfIcons: "आइकन की संख्या",
    Designer_Field_Icon: "आइकन",
    Designer_Field_AllowHalf: "आधे मानों की अनुमति दें",
    Designer_Field_ShowOptionsAs: "विकल्प इस रूप में दिखाएँ",
    Designer_Field_DisplayButtons: "इनलाइन बटन",
    Designer_Field_DisplayDropdown: "ड्रॉपडाउन",
    Designer_Field_DisplayAutomatic: "स्वचालित (6 विकल्पों तक इनलाइन)",
    Designer_Field_AllowOther: "हाथ से लिखा \"अन्य\" विकल्प जोड़ें",
    Designer_Field_OtherLabel: "\"अन्य\" विकल्प का लेबल",
    Designer_Field_OtherPlaceholder: "अन्य",
    Designer_Field_ShuffleOptions: "प्रत्येक प्रतिभागी के लिए विकल्पों का क्रम बदलें",
    Designer_Field_MinSelections: "न्यूनतम चयन",
    Designer_Field_MaxSelections: "अधिकतम चयन",
    Designer_Field_SourceList: "स्रोत सूची",
    Designer_Field_ChooseList: "सूची चुनें",
    Designer_Field_LookupColumn: "विकल्प पढ़ने के लिए कॉलम",
    Designer_Field_ChooseColumn: "कॉलम चुनें",
    Designer_Field_ChooseListFirst: "पहले सूची चुनें",
    Designer_Field_LookupFilter: "फ़िल्टर (वैकल्पिक)",
    Designer_Field_LookupFilterDescription: "एक OData फ़िल्टर जो तय करता है कि कौन-से स्रोत आइटम विकल्प बनें",
    Designer_Field_LookupInfo: "उत्तर विकल्प का टेक्स्ट सहेजते हैं, स्रोत आइटम का लिंक नहीं, ताकि स्रोत सूची बाद में बदलने पर भी प्रतिक्रियाएँ पढ़ने योग्य रहें।",
    Designer_Field_ConsentText: "चेकबॉक्स के ऊपर दिखाई जाने वाली शर्तें",
    Designer_Field_AllowMultiplePeople: "एकाधिक लोगों की अनुमति दें",
    Designer_Field_AllowGroups: "समूहों की भी अनुमति दें",
    Designer_Field_IncludeTime: "दिन का समय शामिल करें",
    Designer_Field_TimeStep: "समय अंतराल (मिनट)",
    Designer_Field_MaxFiles: "अधिकतम फ़ाइलें",
    Designer_Field_MaxFileSize: "प्रत्येक का अधिकतम आकार (MB)",
    Designer_Field_AcceptedTypes: "स्वीकृत फ़ाइल प्रकार",
    Designer_Field_AcceptedTypesDescription: "अल्पविराम से अलग किए गए एक्सटेंशन। SharePoint जो भी अनुमति देता है उसे स्वीकार करने के लिए खाली छोड़ें।",
    Designer_Field_FilesInfo: "फ़ाइलें प्रतिक्रिया आइटम पर अनुलग्नक के रूप में सहेजी जाती हैं। आप यहाँ जो भी अनुमति दें, SharePoint कुछ एक्सटेंशन (जैसे .exe) ब्लॉक करता है।",
    Designer_Field_Rows: "पंक्तियाँ",
    Designer_Field_ProvisionedNote: "इस प्रश्न का पहले से एक सूची कॉलम ({name}) है। कॉलम का प्रकार बदलने वाली सेटिंग लॉक हैं — अलग प्रकार चाहिए तो प्रश्न की प्रतिलिपि बनाएँ।",
    Designer_Category_Text: "टेक्स्ट",
    Designer_Category_Choice: "विकल्प",
    Designer_Category_Scales: "पैमाने",
    Designer_Category_Date: "तिथि",
    Designer_Category_People: "लोग",
    Designer_Category_Advanced: "उन्नत",
    Designer_Category_Layout: "लेआउट",
    Designer_Menu_CommonPresets: "सामान्य प्रीसेट",
    Designer_Menu_AllTypes: "सभी प्रश्न प्रकार",
    Designer_Menu_ChangeType: "प्रकार बदलें",
    Designer_Menu_TypeLockedTitle: "सूची कॉलम पहले से मौजूद है, इसलिए प्रकार लॉक है। प्रकार बदलने के लिए प्रश्न की प्रतिलिपि बनाएँ।",
    Designer_Menu_MoreSettings: "ब्रांचिंग, सत्यापन और अधिक",
    Designer_Menu_InsertBelow: "नीचे प्रश्न डालें",
    Designer_Card_Duplicate: "प्रतिलिपि बनाएँ",
    Designer_Card_DeleteQuestion: "प्रश्न हटाएँ",
    Designer_Outline_Aria: "प्रश्न रूपरेखा",
    Designer_Outline_QuestionCountOne: "{count} प्रश्न",
    Designer_Outline_QuestionCountOther: "{count} प्रश्न",
    Designer_Outline_IssuesTitle: "समीक्षा के लिए {count} समस्या(एँ)",
    Designer_Outline_Find: "प्रश्न खोजें",
    Designer_Outline_Empty: "अभी कोई प्रश्न नहीं।",
    Designer_Section_DefaultTitle: "अनुभाग {number}",
    Designer_Card_Question: "प्रश्न",
    Designer_Card_BranchingTitle: "यह प्रश्न तभी दिखाई देता है जब कोई ब्रांचिंग नियम मेल खाता है",
    Designer_Card_BranchingChip: "ब्रांचिंग",
    Designer_Card_LiveTitle: "सूची कॉलम मौजूद है, इसलिए प्रकार लॉक है",
    Designer_Card_LiveChip: "लाइव",
    Designer_Card_CheckChip: "जाँचें",
    Designer_Option_Placeholder: "विकल्प {number}",
    Designer_Option_LabelAria: "विकल्प {number} का लेबल",
    Designer_Option_ImageUrl: "छवि URL",
    Designer_Option_ImageUrlAria: "विकल्प {number} की छवि URL",
    Designer_Option_Remove: "विकल्प हटाएँ",
    Designer_Option_RemoveAria: "विकल्प {number} हटाएँ",
    Designer_Option_Add: "विकल्प जोड़ें",
    Designer_Option_OtherHint: "प्रतिभागी “{label}” नाम से अपना उत्तर भी लिख सकते हैं।",
    Designer_Option_OtherFallback: "अन्य",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "हटाएँ",
    Designer_Grid_RemoveAria: "{label} {number} हटाएँ",
    Designer_Grid_Statements: "कथन",
    Designer_Grid_Scale: "पैमाना",
    Designer_Grid_AddStatement: "कथन जोड़ें",
    Designer_Grid_AddScale: "पैमाना जोड़ें",
    Designer_Width_Full: "पूरी चौड़ाई",
    Designer_Width_Half: "आधी चौड़ाई",
    Designer_Width_Third: "एक तिहाई चौड़ाई",
    Designer_Width_Aria: "प्रश्न की चौड़ाई",
    Designer_Card_BlockLabelPlaceholder: "ब्लॉक लेबल (प्रतिभागियों को नहीं दिखता)",
    Designer_Card_QuestionText: "प्रश्न का टेक्स्ट",
    Designer_Card_MoveUp: "ऊपर ले जाएँ",
    Designer_Card_MoveQuestionUp: "प्रश्न को ऊपर ले जाएँ",
    Designer_Card_MoveDown: "नीचे ले जाएँ",
    Designer_Card_MoveQuestionDown: "प्रश्न को नीचे ले जाएँ",
    Designer_Card_DuplicateQuestion: "प्रश्न की प्रतिलिपि बनाएँ",
    Designer_Card_MultipleAnswers: "एकाधिक उत्तर",
    Designer_Card_Required: "आवश्यक",
    Designer_Card_MoreOptions: "अधिक विकल्प",
    Designer_Card_MoreOptionsAria: "इस प्रश्न के लिए अधिक विकल्प",
    Designer_Canvas_FormTitle: "फ़ॉर्म का शीर्षक",
    Designer_Canvas_DescriptionPlaceholder: "विवरण जोड़ें (वैकल्पिक)",
    Designer_Canvas_DescriptionAria: "फ़ॉर्म का विवरण",
    Designer_Canvas_EmptyTitle: "अपना पहला प्रश्न जोड़ें",
    Designer_Canvas_EmptyBody: "शुरू करने के लिए प्रश्न का प्रकार चुनें। आप प्रश्नों को खींचकर उनका क्रम बदल सकते हैं, और ब्रांचिंग जोड़ सकते हैं ताकि लोगों को केवल वही दिखे जो उन पर लागू हो।",
    Designer_Section_Chip: "अनुभाग {number} / {total}",
    Designer_Section_TitlePlaceholder: "अनुभाग का शीर्षक",
    Designer_Section_TitleAria: "अनुभाग {number} का शीर्षक",
    Designer_Section_DescriptionPlaceholder: "विवरण (वैकल्पिक)",
    Designer_Section_DescriptionAria: "अनुभाग {number} का विवरण",
    Designer_Section_MoveUp: "अनुभाग को ऊपर ले जाएँ",
    Designer_Section_MoveDown: "अनुभाग को नीचे ले जाएँ",
    Designer_Section_Delete: "अनुभाग हटाएँ",
    Designer_Card_DragToReorder: "क्रम बदलने के लिए खींचें",
    Designer_Card_ReorderAria: "{title} का क्रम बदलें",
    Designer_Card_ReorderFallback: "प्रश्न",
    Designer_Canvas_AddNew: "नया जोड़ें",
    Designer_Canvas_AddSection: "अनुभाग जोड़ें",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "सड़क का पता",
    Form_Address_Street2Placeholder: "अपार्टमेंट, सुइट आदि (वैकल्पिक)",
    Form_Address_CityPlaceholder: "शहर",
    Form_Address_StatePlaceholder: "राज्य / जिला",
    Form_Address_PostalCodePlaceholder: "पिन कोड / ZIP",
    Form_Address_CountryPlaceholder: "देश",
    Form_Address_StreetAria: "सड़क का पता",
    Form_Address_Street2Aria: "पता पंक्ति 2",
    Form_Address_CityAria: "शहर",
    Form_Address_StateAria: "राज्य या जिला",
    Form_Address_PostalCodeAria: "पिन कोड",
    Form_Address_CountryAria: "देश",
    Form_Consent_DefaultLabel: "मैं सहमत हूँ",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{total} में से {answered} पंक्तियों के उत्तर दिए गए",
    Form_Lookup_LoadError: "इस प्रश्न के विकल्प लोड नहीं किए जा सके।",
    Form_Lookup_Loading: "विकल्प लोड हो रहे हैं…",
    Form_Lookup_SelectOptionsPlaceholder: "विकल्प चुनें",
    Form_Lookup_SelectOptionPlaceholder: "एक विकल्प चुनें",
    Form_Person_Placeholder: "नाम टाइप करना शुरू करें…",
    Form_Person_SuggestedPeopleAndGroups: "सुझाए गए लोग और समूह",
    Form_Person_SuggestedPeople: "सुझाए गए लोग",
    Form_Person_NoPeopleOrGroups: "कोई लोग या समूह नहीं मिले",
    Form_Person_NoPeople: "कोई लोग नहीं मिले",
    Form_Person_Searching: "खोज रहे हैं…",
    Form_Ranking_Moved: "{item} को {total} में से स्थान {position} पर ले जाया गया",
    Form_Ranking_MoveUp: "ऊपर ले जाएँ",
    Form_Ranking_MoveDown: "नीचे ले जाएँ",
    Form_Ranking_MoveItemUpAria: "{item} को ऊपर ले जाएँ",
    Form_Ranking_MoveItemDownAria: "{item} को नीचे ले जाएँ",
    Form_Rating_ValueText: "{max} में से {value}",
    Form_Rating_NotRated: "रेटिंग नहीं दी गई",
    Form_Rating_Clear: "रेटिंग साफ़ करें",
    Form_RichText_Bold: "बोल्ड",
    Form_RichText_Italic: "इटैलिक",
    Form_RichText_Underline: "अंडरलाइन",
    Form_RichText_BulletedList: "बुलेट सूची",
    Form_RichText_NumberedList: "क्रमांकित सूची",
    Form_RichText_ClearFormatting: "फ़ॉर्मेटिंग साफ़ करें",
    Form_RichText_ToolbarAria: "टेक्स्ट फ़ॉर्मेटिंग",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\" छोड़ दी गई — सीमा {limit} है।",
    Form_File_TypeNotAccepted: "\"{name}\" स्वीकृत प्रकार की नहीं है।",
    Form_File_TooLarge: "\"{name}\" {size} MB से बड़ी है।",
    Form_File_AlreadyAttached: "\"{name}\" पहले से संलग्न है।",
    Form_File_ReadError: "एक फ़ाइल पढ़ी नहीं जा सकी। उसे फिर से संलग्न करके देखें।",
    Form_File_HintMaxSize: "प्रत्येक अधिकतम {size} MB",
    Form_File_HintOneFile: "1 फ़ाइल",
    Form_File_HintMaxFiles: "अधिकतम {count} फ़ाइलें",
    Form_File_Reading: "फ़ाइलें पढ़ी जा रही हैं…",
    Form_File_DropPrompt: "फ़ाइलें यहाँ छोड़ें, या ब्राउज़ करने के लिए क्लिक करें",
    Form_File_Remove: "{name} हटाएँ",
    Form_Signature_Alt: "हस्ताक्षर",
    Form_Signature_AriaSigned: "{label} — हस्ताक्षरित",
    Form_Signature_AriaEmpty: "{label} — खाली",
    Form_Signature_Clear: "साफ़ करें",
    Form_Signature_Signed: "हस्ताक्षरित",
    Form_Signature_Prompt: "माउस, पेन या उंगली से ऊपर हस्ताक्षर करें",
    Form_Time_Placeholder: "समय चुनें",
    Form_Field_DatePlaceholder: "तिथि चुनें",
    Form_Field_TimeAriaWithLabel: "{label} — समय",
    Form_Field_TimeAria: "समय",
    Form_Field_OtherDefault: "अन्य",
    Form_Field_SelectOptionsPlaceholder: "विकल्प चुनें",
    Form_Field_PleaseSpecify: "कृपया बताएँ",
    Form_Field_OtherSpecifyAria: "{label} — कृपया बताएँ",
    Form_Field_SelectOptionPlaceholder: "एक विकल्प चुनें",
    Form_Field_Yes: "हाँ",
    Form_Field_No: "नहीं",
    Form_Field_SliderHint: "उत्तर देने के लिए स्लाइडर खींचें",
    Form_Field_WebAddressAriaWithLabel: "{label} — वेब पता",
    Form_Field_WebAddressAria: "वेब पता",
    Form_Field_DisplayTextPlaceholder: "प्रदर्शित टेक्स्ट (वैकल्पिक)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — प्रदर्शित टेक्स्ट",
    Form_Field_DisplayTextAria: "प्रदर्शित टेक्स्ट",
    Form_Field_ChooseBetween: "{min} और {max} के बीच चुनें",
    Form_Field_ChooseAtLeast: "कम से कम {min} चुनें",
    Form_Field_ChooseUpTo: "अधिकतम {max} चुनें",
    Form_Field_SelectedCount: "{count} चयनित",
    Form_Field_RequiredAria: "(आवश्यक)",
    Form_Submit_SaveError: "आपकी प्रतिक्रिया सहेजी नहीं जा सकी। सुनिश्चित करें कि फ़ॉर्म डिज़ाइनर से प्रकाशित किया गया है और आपके पास प्रतिक्रिया सूची में आइटम जोड़ने की अनुमति है।",
    Form_Empty_Message: "इस फ़ॉर्म में अभी कोई प्रश्न नहीं है। फ़ॉर्म का स्वामी उन्हें प्रश्न टैब में जोड़ सकता है।",
    Form_Checking: "फ़ॉर्म जाँचा जा रहा है…",
    Form_Closed_NotYetOpen: "अभी खुला नहीं है",
    Form_Closed_AlreadyAnswered: "पहले ही उत्तर दिया जा चुका है",
    Form_Closed_Title: "फ़ॉर्म बंद है",
    Form_Confirmation_PreviewNotice: "यह एक पूर्वावलोकन था — प्रतिक्रिया सूची में कुछ भी सहेजा नहीं गया।",
    Form_Confirmation_PreviewAgain: "फिर से पूर्वावलोकन करें",
    Form_Confirmation_SubmitAnother: "दूसरी प्रतिक्रिया सबमिट करें",
    Form_Wizard_StepFallback: "चरण {step}",
    Form_Wizard_StepsAria: "फ़ॉर्म के चरण",
    Form_Wizard_StepOf: "चरण {step} / {total}",
    Form_ErrorSummary_Title: "कृपया {count} उत्तर जाँचें:",
    Form_ErrorSummary_UntitledQuestion: "शीर्षकरहित प्रश्न",
    Form_ErrorSummary_Question: "प्रश्न",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "वापस",
    Form_Nav_Next: "आगे",
    Form_Draft_Saving: "सहेजा जा रहा है…",
    Form_Draft_Saved: "ड्राफ़्ट सहेजा गया",
    Form_Draft_SaveAndFinishLater: "सहेजें और बाद में पूरा करें",
    Form_Draft_NotSaved: "ड्राफ़्ट सहेजा नहीं गया",
    Form_Submit_Preview: "सबमिट करें (पूर्वावलोकन)",
    Form_Submit_Button: "सबमिट करें",
    Form_Response_NoAnswer: "कोई उत्तर नहीं",
    Form_Signature_TypeLabel: "अपना पूरा नाम लिखें",
    Form_Signature_TypeInstead: "इसके बजाय अपना नाम टाइप करें",
    Form_Signature_DrawInstead: "इसके बजाय हस्ताक्षर बनाएँ",
    Form_Edit_Button: "अपनी पिछली प्रतिक्रिया संपादित करें",
    Form_Edit_Available: "आप पहले ही प्रतिक्रिया सबमिट कर चुके हैं। नई प्रतिक्रिया सबमिट करने के बजाय आप उसे संपादित कर सकते हैं।",
    Form_Edit_Banner: "आप अपनी पिछली प्रतिक्रिया संपादित कर रहे हैं।",
    Form_Edit_Save: "प्रतिक्रिया अपडेट करें",
    Form_Edit_UpdatedTitle: "प्रतिक्रिया अपडेट हो गई",
    Form_Edit_UpdatedMessage: "आपके बदलाव सहेज लिए गए हैं।",
    Form_Edit_LoadError: "आपकी पिछली प्रतिक्रिया लोड नहीं हो सकी। कृपया पुनः प्रयास करें।",
    Form_Draft_MissingFiles: "कृपया दोबारा संलग्न करें: {names}। ये फ़ाइलें पुनर्स्थापित नहीं की जा सकीं।",
    Form_Attachments_Failed: "आपके उत्तर सहेज लिए गए, लेकिन ये अनुलग्नक अपलोड नहीं हो सके: {names}। कृपया पुनः प्रयास करें या फ़ॉर्म के स्वामी से संपर्क करें।",
    Logic_ThisQuestion: "यह प्रश्न",
    Logic_Required: "{label} आवश्यक है",
    Logic_RequiredConsent: "जारी रखने के लिए कृपया बॉक्स चुनें",
    Logic_RequiredFile: "कृपया कम से कम एक फ़ाइल संलग्न करें",
    Logic_RequiredSignature: "कृपया अपना हस्ताक्षर जोड़ें",
    Logic_RequiredLikert: "कृपया हर पंक्ति का उत्तर दें",
    Logic_InvalidEmail: "मान्य ईमेल पता दर्ज करें",
    Logic_InvalidPhone: "मान्य फ़ोन नंबर दर्ज करें",
    Logic_InvalidUrl: "http:// या https:// से शुरू होने वाला मान्य वेब पता दर्ज करें",
    Logic_MinValue: "मान कम से कम {value} होना चाहिए",
    Logic_MaxValue: "मान अधिकतम {value} होना चाहिए",
    Logic_MaxLength: "अधिकतम लंबाई {max} वर्ण है",
    Logic_ChooseAtLeastOne: "कम से कम {count} विकल्प चुनें",
    Logic_ChooseAtLeastMany: "कम से कम {count} विकल्प चुनें",
    Logic_ChooseAtMostOne: "{count} से अधिक विकल्प न चुनें",
    Logic_ChooseAtMostMany: "{count} से अधिक विकल्प न चुनें",
    Logic_LikertRemaining: "कृपया हर पंक्ति का उत्तर दें ({count} शेष)",
    Logic_MaxFilesOne: "{count} से अधिक फ़ाइल संलग्न न करें",
    Logic_MaxFilesMany: "{count} से अधिक फ़ाइलें संलग्न न करें",
    Logic_FileTooLarge: "\"{name}\" {size} MB से बड़ी है",
    Logic_FileTypeNotAccepted: "\"{name}\" स्वीकृत फ़ाइल प्रकार नहीं है ({types})",
    Logic_AddressRequired: "कम से कम सड़क और शहर दर्ज करें",
    Logic_PatternDefault: "यह उत्तर अपेक्षित प्रारूप में नहीं है",
    Logic_Yes: "हाँ",
    Logic_No: "नहीं",
    Logic_Agreed: "सहमत",
    Logic_NotAgreed: "असहमत",
    Logic_Signed: "हस्ताक्षरित",
    Logic_NoAnswer: "(कोई उत्तर नहीं)",
    Logic_Unknown: "(अज्ञात)",
    Logic_OtherSlice: "अन्य ({count})",
    Logic_CsvResponseId: "प्रतिक्रिया ID",
    Logic_CsvSubmitted: "सबमिट किया गया",
    Logic_CsvSubmittedBy: "सबमिट करने वाला",
    Logic_EmailQuestion: "प्रश्न",
    Logic_EmailViewItem: "Microsoft Lists में देखें",
    Logic_EmailFooter: "Smart Forms द्वारा स्वचालित रूप से भेजा गया।",
    Logic_ClosedDefault: "यह फ़ॉर्म अब प्रतिक्रियाएँ स्वीकार नहीं कर रहा है।",
    Logic_NotYetOpen: "यह फ़ॉर्म {date} को खुलेगा।",
    Logic_AlreadyResponded: "आप इस फ़ॉर्म पर पहले ही प्रतिक्रिया दे चुके हैं। धन्यवाद!",
    Logic_UntitledQuestion: "शीर्षकहीन प्रश्न",
    Logic_Issue_NoQuestions: "प्रतिक्रियाएँ एकत्र करने से पहले कम से कम एक प्रश्न जोड़ें।",
    Logic_Issue_NoTitle: "किसी प्रश्न में टेक्स्ट नहीं है — प्रकाशित करने पर उसे अपने-आप नाम दिया जाएगा।",
    Logic_Issue_DuplicateTitle: "{label} का टेक्स्ट किसी अन्य प्रश्न जैसा ही है, जिससे परिणाम पढ़ना कठिन हो जाता है।",
    Logic_Issue_NeedTwoOptions: "{label} में कम से कम दो विकल्प होने चाहिए।",
    Logic_Issue_ImageNoImage: "{label} के कुछ विकल्पों में छवि नहीं है — वे टेक्स्ट टाइल के रूप में दिखेंगे।",
    Logic_Issue_LikertNeedRow: "{label} में कम से कम एक पंक्ति होनी चाहिए।",
    Logic_Issue_LikertNeedColumns: "{label} में कम से कम दो स्केल कॉलम होने चाहिए।",
    Logic_Issue_NoLookupList: "{label} के लिए कोई स्रोत सूची नहीं चुनी गई है।",
    Logic_Issue_NoFormula: "{label} में कोई सूत्र नहीं है।",
    Logic_Issue_BadFormula: "{label} में ऐसा सूत्र है जिसकी गणना नहीं हो सकती। कोष्ठक और ऑपरेटर जाँचें।",
    Logic_Issue_MissingRefs: "{label} ऐसे प्रश्नों का संदर्भ देता है जो मौजूद नहीं हैं: {names}।",
    Logic_Issue_BadPattern: "{label} का सत्यापन पैटर्न अमान्य है।",
    Logic_Issue_BrokenRule: "{label} में ऐसा ब्रांचिंग नियम है जो हटाए गए प्रश्न की ओर इशारा करता है।",
    Logic_Issue_SelfRule: "{label} में ऐसा ब्रांचिंग नियम है जो स्वयं का संदर्भ देता है।",
    Logic_Issue_RuleMismatch: "{label} में ऐसा ब्रांचिंग नियम है जो अब उस प्रश्न से मेल नहीं खाता जिस पर वह निर्भर है।",
    Logic_Issue_RequiredReadOnly: "{label} आवश्यक और केवल-पढ़ने योग्य दोनों है, इसलिए इसका उत्तर केवल पूर्वभरे लिंक से दिया जा सकता है।",
    Logic_Issue_EmptySection: "किसी अनुभाग में कोई प्रश्न नहीं है और उसे छोड़ दिया जाएगा।",
    Logic_Issue_CloseBeforeOpen: "समाप्ति तिथि आरंभ तिथि पर या उससे पहले है, इसलिए फ़ॉर्म कभी प्रतिक्रियाएँ स्वीकार नहीं करेगा।",
    Logic_Issue_ApprovalNotifyWithoutApproval: "अनुमोदन ईमेल चालू हैं लेकिन अनुमोदन चरण बंद है।",
    Logic_Op_equals: "है",
    Logic_Op_notEquals: "नहीं है",
    Logic_Op_contains: "शामिल है",
    Logic_Op_notContains: "शामिल नहीं है",
    Logic_Op_notEmpty: "उत्तर दिया गया है",
    Logic_Op_empty: "उत्तर नहीं दिया गया है",
    Logic_Op_greaterThan: "से अधिक है",
    Logic_Op_greaterOrEqual: "कम से कम है",
    Logic_Op_lessThan: "से कम है",
    Logic_Op_lessOrEqual: "अधिकतम है",
    Logic_Op_between: "के बीच है",
    Logic_Op_before: "से पहले है",
    Logic_Op_after: "के बाद है",
    Logic_Type_Text: "संक्षिप्त उत्तर",
    Logic_TypeDesc_Text: "टेक्स्ट की एक पंक्ति",
    Logic_Category_Text: "टेक्स्ट",
    Logic_Type_MultilineText: "लंबा उत्तर",
    Logic_TypeDesc_MultilineText: "सादे टेक्स्ट की कई पंक्तियाँ",
    Logic_Type_RichText: "स्वरूपित टेक्स्ट",
    Logic_TypeDesc_RichText: "बोल्ड, सूचियाँ और लिंक",
    Logic_Type_Choice: "विकल्प",
    Logic_TypeDesc_Choice: "विकल्पों की सूची में से चुनें",
    Logic_Category_Choice: "विकल्प",
    Logic_Type_ImageChoice: "छवि विकल्प",
    Logic_TypeDesc_ImageChoice: "चित्र टाइल में से चुनें",
    Logic_Type_Lookup: "सूची से लुकअप",
    Logic_TypeDesc_Lookup: "विकल्प किसी अन्य SharePoint सूची से लाइव पढ़े जाते हैं",
    Logic_Type_YesNo: "हाँ / नहीं",
    Logic_TypeDesc_YesNo: "एक सरल चालू/बंद टॉगल",
    Logic_Type_Consent: "सहमति",
    Logic_TypeDesc_Consent: "एक चेकबॉक्स जिसे जारी रखने के लिए प्रतिभागी को चुनना होगा",
    Logic_Type_Ranking: "रैंकिंग",
    Logic_TypeDesc_Ranking: "विकल्पों को पसंद के क्रम में खींचें",
    Logic_Type_Rating: "रेटिंग",
    Logic_TypeDesc_Rating: "सितारे, दिल या थम्स-अप",
    Logic_Category_Scales: "स्केल",
    Logic_Type_Scale: "राय स्केल",
    Logic_TypeDesc_Scale: "लेबल वाले सिरों के साथ क्रमांकित स्केल",
    Logic_Type_Slider: "स्लाइडर",
    Logic_TypeDesc_Slider: "स्लाइडिंग स्केल पर एक मान",
    Logic_Type_Likert: "लिकर्ट ग्रिड",
    Logic_TypeDesc_Likert: "एक साझा स्केल पर कई कथनों को रेट करें",
    Logic_Type_Number: "संख्या",
    Logic_TypeDesc_Number: "सामान्य, मुद्रा या प्रतिशत",
    Logic_Category_Advanced: "उन्नत",
    Logic_Type_Calculated: "परिकलित",
    Logic_TypeDesc_Calculated: "अन्य उत्तरों से निकाला गया केवल-पढ़ने योग्य कुल",
    Logic_Type_Date: "तिथि",
    Logic_TypeDesc_Date: "कैलेंडर की तिथि, वैकल्पिक रूप से समय के साथ",
    Logic_Category_Date: "तिथि",
    Logic_Type_Time: "समय",
    Logic_TypeDesc_Time: "दिन का केवल समय",
    Logic_Type_Person: "व्यक्ति",
    Logic_TypeDesc_Person: "संगठन में से किसी को चुनें",
    Logic_Category_People: "लोग",
    Logic_Type_Email: "ईमेल",
    Logic_TypeDesc_Email: "सत्यापित ईमेल पता",
    Logic_Type_Phone: "फ़ोन",
    Logic_TypeDesc_Phone: "सत्यापित फ़ोन नंबर",
    Logic_Type_Address: "पता",
    Logic_TypeDesc_Address: "सड़क, शहर, पिन कोड और देश",
    Logic_Type_Hyperlink: "लिंक",
    Logic_TypeDesc_Hyperlink: "एक वेब पता",
    Logic_Type_FileUpload: "फ़ाइल अपलोड",
    Logic_TypeDesc_FileUpload: "प्रतिक्रिया के साथ एक या अधिक फ़ाइलें संलग्न करें",
    Logic_Type_Signature: "हस्ताक्षर",
    Logic_TypeDesc_Signature: "माउस, पेन या उँगली से हस्ताक्षर करें",
    Logic_Type_Content: "टेक्स्ट ब्लॉक",
    Logic_TypeDesc_Content: "निर्देश या छवि — कोई उत्तर एकत्र नहीं करता",
    Logic_Category_Layout: "लेआउट",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "आप हमारी सिफ़ारिश करने की कितनी संभावना रखते हैं…",
    Logic_Preset_satisfaction: "संतुष्टि (1–5)",
    Logic_PresetDesc_satisfaction: "बहुत असंतुष्ट से बहुत संतुष्ट तक",
    Logic_Preset_currency: "मुद्रा",
    Logic_PresetDesc_currency: "धनराशि",
    Logic_Preset_percent: "प्रतिशत",
    Logic_PresetDesc_percent: "प्रतिशत मान",
    Logic_Template_blank_Name: "खाली फ़ॉर्म",
    Logic_Template_blank_Description: "शुरू से शुरुआत करें",
    Logic_Template_feedback_Name: "ग्राहक फ़ीडबैक",
    Logic_Template_feedback_Description: "NPS, रेटिंग और खुली टिप्पणियाँ",
    Logic_Template_event_Name: "इवेंट पंजीकरण",
    Logic_Template_event_Description: "प्रतिभागी विवरण, सत्र और आहार संबंधी आवश्यकताएँ",
    Logic_Template_itrequest_Name: "IT सेवा अनुरोध",
    Logic_Template_itrequest_Description: "प्राथमिकता और अनुलग्नकों के साथ श्रेणीबद्ध अनुरोध",
    Logic_Template_expense_Name: "व्यय दावा",
    Logic_Template_expense_Description: "मदें, रसीदें और परिकलित कुल",
    Logic_Template_pulse_Name: "कर्मचारी पल्स सर्वे",
    Logic_Template_pulse_Description: "लिकर्ट ग्रिड, जुड़ाव स्केल और गोपनीयता नोट",
    Logic_Template_safety_Name: "सुरक्षा निरीक्षण",
    Logic_Template_safety_Description: "चेकलिस्ट, फ़ोटो और हस्ताक्षर",
    Logic_Template_booking_Name: "कमरा या संसाधन बुकिंग",
    Logic_Template_booking_Description: "समय स्लॉट के साथ लुकअप-आधारित संसाधन चयनकर्ता",
    Charts_ColumnChartAria: "{count} श्रेणियों वाला कॉलम चार्ट",
    Charts_DonutChartAria: "{count} श्रेणियों का डोनट चार्ट",
    Charts_NoAnswers: "अभी कोई उत्तर नहीं।",
    Charts_NoResponses: "अभी कोई प्रतिक्रिया नहीं।",
    Charts_Responses: "प्रतिक्रियाएँ",
    Charts_ResponsesOverTime: "समय के साथ प्रतिक्रियाएँ",
    Responses_Chart_Answer: "उत्तर",
    Responses_Chart_Average: "औसत",
    Responses_Chart_AverageOf: "{count} का औसत",
    Responses_Chart_AveragePosition: "औसत स्थान",
    Responses_Chart_AverageRange: "औसत (1–{max})",
    Responses_Chart_AvgValue: "औसत {value}",
    Responses_Chart_Detractors: "आलोचक (0–6)",
    Responses_Chart_Max: "अधिकतम",
    Responses_Chart_Maximum: "अधिकतम",
    Responses_Chart_Median: "माध्यिका",
    Responses_Chart_MentionOne: "{count} उल्लेख",
    Responses_Chart_MentionOther: "{count} उल्लेख",
    Responses_Chart_Min: "न्यूनतम",
    Responses_Chart_Minimum: "न्यूनतम",
    Responses_Chart_NoAnswers: "अभी कोई उत्तर नहीं।",
    Responses_Chart_NoNumeric: "अभी कोई संख्यात्मक उत्तर नहीं।",
    Responses_Chart_NoRankings: "अभी कोई रैंकिंग नहीं।",
    Responses_Chart_NoScores: "अभी कोई स्कोर नहीं।",
    Responses_Chart_NotEnoughText: "सारांश बनाने के लिए अभी पर्याप्त टेक्स्ट नहीं है।",
    Responses_Chart_NpsScore: "NPS स्कोर",
    Responses_Chart_Option: "विकल्प",
    Responses_Chart_Passives: "तटस्थ (7–8)",
    Responses_Chart_Promoters: "प्रमोटर (9–10)",
    Responses_Chart_ResponseOne: "प्रतिक्रिया",
    Responses_Chart_ResponseOther: "प्रतिक्रियाएँ",
    Responses_Chart_Responses: "प्रतिक्रियाएँ",
    Responses_Chart_ShowingAnswers: "{total} में से {shown} उत्तर दिखाए जा रहे हैं।",
    Responses_Chart_Statement: "कथन",
    Responses_Chart_Statistic: "आँकड़ा",
    Responses_Chart_StdDev: "मानक विचलन",
    Responses_Chart_StdDeviation: "मानक विचलन",
    Responses_Chart_Total: "कुल",
    Responses_Chart_Value: "मान",
    Responses_Dashboard_AllHidden: "हर प्रश्न डैशबोर्ड से छिपा है। उन्हें वापस लाने के लिए “छिपे हुए प्रश्न दिखाएँ” का उपयोग करें।",
    Responses_Dashboard_AnsweredOf: "{total} में से {answered} के उत्तर मिले",
    Responses_Dashboard_AnsweredOfPinned: "{total} में से {answered} के उत्तर मिले · पिन किया गया",
    Responses_Dashboard_AveragedAcrossResponses: "सभी प्रतिक्रियाओं का औसत",
    Responses_Dashboard_ByDay: "दिन के अनुसार",
    Responses_Dashboard_ByMonth: "महीने के अनुसार",
    Responses_Dashboard_ByWeek: "सप्ताह के अनुसार",
    Responses_Dashboard_ChartAuto: "स्वचालित",
    Responses_Dashboard_ChartBars: "बार",
    Responses_Dashboard_ChartColumns: "कॉलम",
    Responses_Dashboard_ChartDonut: "डोनट",
    Responses_Dashboard_ChartGauge: "गेज",
    Responses_Dashboard_ChartHistogram: "हिस्टोग्राम",
    Responses_Dashboard_ChartOptions: "चार्ट विकल्प",
    Responses_Dashboard_ChartOptionsFor: "{title} के लिए चार्ट विकल्प",
    Responses_Dashboard_ChartStatistics: "आँकड़े",
    Responses_Dashboard_ChartTable: "तालिका",
    Responses_Dashboard_ChartWordFrequency: "शब्द आवृत्ति",
    Responses_Dashboard_EmptyBody: "जब लोग उत्तर देना शुरू करेंगे, यह डैशबोर्ड अपने-आप भर जाएगा — मुख्य आँकड़े, प्रतिक्रियाओं की टाइमलाइन, और देखने योग्य प्रश्नों के लिए एक चार्ट।",
    Responses_Dashboard_EmptyTitle: "अभी कोई प्रतिक्रिया नहीं",
    Responses_Dashboard_Hide: "डैशबोर्ड से छिपाएँ",
    Responses_Dashboard_Highlights: "मुख्य बातें",
    Responses_Dashboard_Last7Days: "पिछले 7 दिन",
    Responses_Dashboard_LatestDate: "नवीनतम {date}",
    Responses_Dashboard_MedianTimeToComplete: "पूरा करने का माध्यिका समय",
    Responses_Dashboard_NoPriorWeek: "तुलना के लिए कोई पिछला सप्ताह नहीं",
    Responses_Dashboard_OneEach: "प्रत्येक एक",
    Responses_Dashboard_Pin: "डैशबोर्ड पर पिन करें",
    Responses_Dashboard_QuestionFallback: "प्रश्न",
    Responses_Dashboard_QuestionsAnswered: "उत्तर दिए गए प्रश्न",
    Responses_Dashboard_RecordedOnSubmit: "सबमिट के समय दर्ज",
    Responses_Dashboard_RepeatResponses: "{count} दोहराई गई प्रतिक्रियाएँ",
    Responses_Dashboard_ResponsesOverTime: "समय के साथ प्रतिक्रियाएँ",
    Responses_Dashboard_ShowHidden: "छिपे हुए प्रश्न दिखाएँ",
    Responses_Dashboard_SinceMidnight: "आधी रात से अब तक",
    Responses_Dashboard_Today: "आज",
    Responses_Dashboard_TotalResponses: "कुल प्रतिक्रियाएँ",
    Responses_Dashboard_UniqueRespondents: "अद्वितीय प्रतिभागी",
    Responses_Dashboard_Unpin: "डैशबोर्ड से अनपिन करें",
    Responses_Dashboard_UntitledQuestion: "शीर्षकरहित प्रश्न",
    Responses_Dashboard_VsPrevious7Days: "पिछले 7 दिनों की तुलना में",
    Responses_Detail_Answers: "उत्तर",
    Responses_Detail_AsTheForm: "फ़ॉर्म जैसा दिखता है",
    Responses_Detail_Cancel: "रद्द करें",
    Responses_Detail_Delete: "हटाएँ",
    Responses_Detail_DeleteBody: "सूची आइटम साइट के रीसायकल बिन में चला जाता है, इसलिए उसे वहाँ से पुनर्स्थापित किया जा सकता है।",
    Responses_Detail_DeleteTitle: "इस प्रतिक्रिया को हटाएँ?",
    Responses_Detail_Deleting: "हटाया जा रहा है…",
    Responses_Detail_Draft: "ड्राफ़्ट",
    Responses_Detail_Header: "{total} में से प्रतिक्रिया {index}",
    Responses_Detail_LoadingAttachments: "अनुलग्नक लोड हो रहे हैं…",
    Responses_Detail_Next: "अगली प्रतिक्रिया",
    Responses_Detail_NoAnswer: "कोई उत्तर नहीं",
    Responses_Detail_Previous: "पिछली प्रतिक्रिया",
    Responses_Detail_Print: "प्रिंट करें",
    Responses_Detail_Signature: "हस्ताक्षर",
    Responses_Detail_Signed: "हस्ताक्षरित",
    Responses_Detail_Took: "{duration} लगे",
    Responses_Summary_AnsweredOfType: "{total} में से {answered} के उत्तर मिले · {type}",
    Responses_Summary_ByField: "{title} के अनुसार",
    Responses_Summary_CompareBy: "इसके आधार पर तुलना करें…",
    Responses_Summary_EmptyBody: "हर प्रश्न का अपना सारांश यहाँ होगा।",
    Responses_Summary_NoComparison: "कोई तुलना नहीं",
    Responses_Summary_NothingToCompare: "किसी भी प्रतिक्रिया ने “{title}” का उत्तर नहीं दिया, इसलिए तुलना के लिए कुछ नहीं है।",
    Responses_Summary_OtherNote: "{max} से अधिक श्रेणियों वाले चार्ट सबसे छोटी श्रेणियों को “अन्य” में समूहित करते हैं — हर मान देखने के लिए कार्ड को तालिका में बदलें।",
    Responses_Summary_ResponseCountOne: "{count} प्रतिक्रिया",
    Responses_Summary_ResponseCountOther: "{count} प्रतिक्रियाएँ",
    Responses_Summary_SeeAllAnswers: "तालिका में सभी उत्तर देखें",
    Responses_Summary_SegmentNote: "सबसे बड़े {groups} समूह दिखाए जा रहे हैं। कई उत्तर चुनने वाली प्रतिक्रिया हर मेल खाते समूह में दिखाई देती है, इसलिए समूहों का कुल योग {total} से अधिक हो सकता है।",
    Responses_Summary_SplitBy: "{title} के अनुसार विभाजित करें",
    Responses_Summary_Untitled: "शीर्षकरहित",
    Responses_Table_Apply: "लागू करें",
    Responses_Table_Cancel: "रद्द करें",
    Responses_Table_ClearSelection: "चयन साफ़ करें",
    Responses_Table_ColumnOrder: "कॉलम क्रम",
    Responses_Table_ColumnsCount: "कॉलम ({shown}/{total})",
    Responses_Table_Delete: "हटाएँ",
    Responses_Table_DeleteBody: "सूची आइटम साइट के रीसायकल बिन में चले जाते हैं, इसलिए उन्हें वहाँ से पुनर्स्थापित किया जा सकता है।",
    Responses_Table_DeleteSelected: "चयनित हटाएँ",
    Responses_Table_DeleteTitleOne: "{count} प्रतिक्रिया हटाएँ?",
    Responses_Table_DeleteTitleOther: "{count} प्रतिक्रियाएँ हटाएँ?",
    Responses_Table_Deleting: "हटाया जा रहा है…",
    Responses_Table_MoveDown: "नीचे ले जाएँ",
    Responses_Table_MoveDownFor: "{title} को नीचे ले जाएँ",
    Responses_Table_MoveUp: "ऊपर ले जाएँ",
    Responses_Table_MoveUpFor: "{title} को ऊपर ले जाएँ",
    Responses_Table_NoColumns: "अभी कोई प्रश्न कॉलम दिखाई नहीं दे रहा है।",
    Responses_Table_NoMatch: "कोई प्रतिक्रिया वर्तमान फ़िल्टर से मेल नहीं खाती।",
    Responses_Table_NothingToShow: "दिखाने के लिए कुछ नहीं",
    Responses_Table_OpenResponse: "इस प्रतिक्रिया को खोलें",
    Responses_Table_OrderNote: "सबमिट किया गया और सबमिट करने वाला हमेशा पहले आते हैं। खींचकर क्रम बदलना प्रश्न कॉलमों पर लागू होता है।",
    Responses_Table_Reorder: "क्रम बदलें",
    Responses_Table_ResetColumns: "कॉलम रीसेट करें",
    Responses_Table_SelectResponse: "इस प्रतिक्रिया को चुनें",
    Responses_Table_SelectedOne: "{count} प्रतिक्रिया चयनित",
    Responses_Table_SelectedOther: "{count} प्रतिक्रियाएँ चयनित",
    Responses_Table_ShowAll: "सभी दिखाएँ",
    Responses_Table_ShowTheseQuestions: "इन प्रश्नों को दिखाएँ",
    Responses_Table_Submitted: "सबमिट किया गया",
    Responses_Table_SubmittedBy: "सबमिट करने वाला",
    Responses_Table_ToggleSelection: "चयन टॉगल करें",
    Responses_Table_Unknown: "अज्ञात",
    Responses_Table_Untitled: "शीर्षकरहित",
    Responses_View_AllTime: "सभी समय",
    Responses_View_AnyAnswer: "कोई भी उत्तर",
    Responses_View_Clear: "साफ़ करें",
    Responses_View_CopyShareLink: "शेयर लिंक कॉपी करें",
    Responses_View_CountFiltered: "{total} में से {shown} प्रतिक्रियाएँ",
    Responses_View_CountOne: "{count} प्रतिक्रिया",
    Responses_View_CountOther: "{count} प्रतिक्रियाएँ",
    Responses_View_Dashboard: "डैशबोर्ड",
    Responses_View_DateRange: "तिथि सीमा",
    Responses_View_EmptyBody: "संग्रह शुरू करने के लिए फ़ॉर्म साझा करें। उत्तर “{list}” में सहेजे जाते हैं और तुरंत यहाँ दिखाई देते हैं।",
    Responses_View_EmptyTitle: "अभी कोई प्रतिक्रिया नहीं",
    Responses_View_ExportCsv: "CSV निर्यात करें",
    Responses_View_FilterByAnswer: "उत्तर के अनुसार फ़िल्टर करें",
    Responses_View_FilterByQuestion: "प्रश्न के अनुसार फ़िल्टर करें",
    Responses_View_FilterValue: "फ़िल्टर मान",
    Responses_View_Last30Days: "पिछले 30 दिन",
    Responses_View_Last7Days: "पिछले 7 दिन",
    Responses_View_Last90Days: "पिछले 90 दिन",
    Responses_View_LoadError: "प्रतिक्रियाएँ लोड नहीं की जा सकीं। सूची कॉलम बनाने के लिए फ़ॉर्म को एक बार प्रकाशित करें, फिर दोबारा प्रयास करें।",
    Responses_View_Loading: "प्रतिक्रियाएँ लोड हो रही हैं…",
    Responses_View_MoreActions: "अधिक प्रतिक्रिया क्रियाएँ",
    Responses_View_PreviewForm: "फ़ॉर्म का पूर्वावलोकन करें",
    Responses_View_Refresh: "रीफ़्रेश करें",
    Responses_View_ResponsesTab: "प्रतिक्रियाएँ ({count})",
    Responses_View_SearchPlaceholder: "सभी उत्तरों में खोजें",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "मान चुनें",
    Responses_View_Summary: "सारांश",
    Responses_View_Today: "आज",
    Responses_View_Truncated: "इस सूची में Smart Forms द्वारा एक बार में लोड की जा सकने वाली प्रतिक्रियाओं से अधिक प्रतिक्रियाएँ हैं। सबसे नई {count} दिखाई गई हैं — पूरा सेट देखने के लिए सूची को Microsoft Lists में खोलें।",
    Responses_View_TryAgain: "फिर से प्रयास करें",
    Responses_View_Untitled: "शीर्षकरहित",
    Responses_Approval_Column: "अनुमोदन",
    Responses_Approval_ReviewerColumn: "समीक्षक",
    Responses_Approval_CommentColumn: "समीक्षक की टिप्पणी",
    Responses_Approval_Pending: "लंबित",
    Responses_Approval_Approved: "स्वीकृत",
    Responses_Approval_Rejected: "अस्वीकृत",
    Responses_Approval_AnyStatus: "कोई भी अनुमोदन स्थिति",
    Responses_Approval_FilterLabel: "अनुमोदन स्थिति के आधार पर फ़िल्टर करें",
    Responses_Approval_ApproveSelected: "चयनित स्वीकृत करें",
    Responses_Approval_RejectSelected: "चयनित अस्वीकृत करें",
    Responses_Approval_BulkFailed: "{count} प्रतिक्रियाएँ अपडेट नहीं हो सकीं। पुनः प्रयास करें।",
    Responses_Approval_Approve: "स्वीकृत करें",
    Responses_Approval_Reject: "अस्वीकृत करें",
    Responses_Approval_Reset: "लंबित पर रीसेट करें",
    Responses_Approval_CommentLabel: "टिप्पणी (वैकल्पिक)",
    Responses_Approval_ReviewedBy: "{name} द्वारा समीक्षित",
    Responses_Approval_Error: "निर्णय सहेजा नहीं जा सका। पुनः प्रयास करें।",
    Responses_Dashboard_ApprovalStatus: "समीक्षा की प्रतीक्षा में",
    Responses_Dashboard_ApprovalBreakdown: "{pending} लंबित, {approved} स्वीकृत, {rejected} अस्वीकृत",
    Responses_Dashboard_TimelineCoarsened: "तिथि सीमा लंबी है, इसलिए टाइमलाइन को मोटे अंतराल ({grain}) में समूहित किया गया।",
    Responses_Dashboard_TimelineTruncated: "तिथि सीमा बहुत लंबी है, इसलिए केवल सबसे हाल की {count} अवधियाँ दिखाई गई हैं।",
    Service_Item_DefaultTitle: "प्रतिक्रिया — {date}",
    Service_Email_ApprovalSubject: "आपकी प्रतिक्रिया {status} — {title}",
    Service_Email_ApprovalHeading: "आपकी प्रतिक्रिया {status}",
    Service_Email_ApprovalIntro: "एक समीक्षक ने \"{title}\" पर आपकी प्रतिक्रिया को {status} चिह्नित किया।",
    Service_Email_ApprovalCommentLabel: "समीक्षक की टिप्पणी",
    Service_Approval_Approved: "स्वीकृत की गई",
    Service_Approval_Rejected: "अस्वीकृत की गई",
    Service_Approval_Pending: "लंबित है",
    Service_Lookup_InvalidFilter: "लुकअप फ़िल्टर मान्य नहीं है।",
    Service_Edit_NotAllowed: "यह फ़ॉर्म सबमिट की गई प्रतिक्रिया के संपादन की अनुमति नहीं देता।",
    Service_Edit_NotYours: "आप केवल अपनी प्रतिक्रिया संपादित कर सकते हैं।",
    Service_Signature_AttachmentLabel: "हस्ताक्षर",
    PropertyPane_ListsLoadFailed: "इस साइट की सूचियाँ लोड नहीं की जा सकीं।",
    PropertyPane_EnterListName: "पहले नई सूची के लिए एक नाम दर्ज करें।",
    PropertyPane_CreatingList: "\"{name}\" बनाई जा रही है…",
    PropertyPane_ListCreated: "सूची \"{title}\" बनाई गई और चुनी गई।",
    PropertyPane_ListAlreadyExists: "\"{name}\" नाम की सूची पहले से मौजूद है — इसे ऊपर के ड्रॉपडाउन से चुनें।",
    PropertyPane_CreateListFailed: "सूची नहीं बनाई जा सकी। जाँचें कि आपके पास इस साइट पर सूचियाँ बनाने की अनुमति है।",
    PropertyPane_Description: "वह SharePoint सूची चुनें जो फ़ॉर्म प्रतिक्रियाएँ संग्रहीत करती है, या नई बनाएँ। बाकी सब कुछ — प्रश्न, रूप-रंग, सूचनाएँ — सीधे पृष्ठ पर संपादित किया जाता है।",
    PropertyPane_ResponseList_GroupName: "प्रतिक्रिया सूची",
    PropertyPane_ListDropdown_Label: "प्रतिक्रियाएँ इस सूची में सहेजें",
    PropertyPane_ResponsesGoTo: "प्रतिक्रियाएँ \"{name}\" में जाती हैं।",
    PropertyPane_PickList: "कोई सूची चुनें, या नीचे नई बनाएँ।",
    PropertyPane_LoadingLists: "सूचियाँ लोड हो रही हैं…",
    PropertyPane_NewListName_Label: "या नई सूची बनाएँ",
    PropertyPane_NewListName_Placeholder: "नई सूची का नाम",
    PropertyPane_CreateList_Button: "सूची बनाएँ",
    PropertyPane_Tips_GroupName: "सुझाव",
    PropertyPane_Tip_AutoSave: "प्रश्न और सेटिंग संपादित करते ही अपने-आप सहेज ली जाती हैं — पृष्ठ को सहेजने या प्रकाशित करने की आवश्यकता नहीं।",
    PropertyPane_Tip_Permissions: "प्रतिभागियों के पास प्रतिक्रिया सूची में आइटम जोड़ने की अनुमति होनी चाहिए। यदि कोई सबमिट करते समय त्रुटि बताए, तो सूची की अनुमतियाँ जाँचें।",
    PropertyPane_Tip_Share: "सूची कॉलम बनाने और साझा करने योग्य भरने का लिंक पाने के लिए पृष्ठ पर \"प्रतिक्रियाएँ एकत्र करें\" का उपयोग करें।",
    App_ErrorBoundary_Title: "Smart Forms — रेंडर त्रुटि",
    App_ErrorBoundary_Message: "संदेश:",
    App_ErrorBoundary_Stack: "स्टैक:",
    App_ErrorBoundary_NoStack: "(कोई स्टैक उपलब्ध नहीं)",
    App_ErrorBoundary_ConsoleNote: "पूरा विवरण ब्राउज़र कंसोल में भी लिखा गया है।",
    App_DefaultQuestionTitle: "प्रश्न {number}",
    App_Error_ListMissing: "इस फ़ॉर्म के लिए कॉन्फ़िगर की गई सूची अब मौजूद नहीं है। वेब पार्ट सेटिंग में कोई अन्य सूची चुनें।",
    App_Error_LoadConfig: "फ़ॉर्म कॉन्फ़िगरेशन लोड करते समय कुछ गड़बड़ हुई।",
    App_Error_Unable: "फ़ॉर्म लोड नहीं किया जा सका।",
    App_Publish_ConflictNotice: "\"{title}\" का सूची कॉलम पहले से एक अलग प्रकार ({type}) का है। प्रश्न का नाम बदलें ताकि नया कॉलम बन सके, या उसका प्रकार वापस बदलें।",
    App_Publish_ConflictUnnamedQuestion: "एक प्रश्न",
    App_Publish_ColumnsAddedOne: "\"{list}\" में {count} कॉलम जोड़ा गया।",
    App_Publish_ColumnsAddedOther: "\"{list}\" में {count} कॉलम जोड़े गए।",
    App_Publish_TheList: "सूची",
    App_Publish_UpToDate: "प्रतिक्रिया सूची पहले से अद्यतन है।",
    App_Publish_Error: "सूची कॉलम नहीं बनाए जा सके। आमतौर पर इसका मतलब है कि आपके पास प्रतिक्रिया सूची पर Manage Lists अनुमति नहीं है, लेकिन यह कस्टम स्क्रिप्टिंग अक्षम वाली साइटों पर भी हो सकता है। मूल त्रुटि के लिए ब्राउज़र कंसोल देखें, या दोबारा प्रयास करें।",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "SharePoint सूची पर एक बेहतरीन फ़ॉर्म बनाएँ — {count} प्रश्न प्रकार, ब्रांचिंग लॉजिक, फ़ाइल अपलोड, साझा करने योग्य भरने के लिंक, और एक परिणाम डैशबोर्ड।",
    App_Placeholder_ChooseList: "सूची चुनें या बनाएँ",
    App_Placeholder_Hint: "आरंभ करने के लिए पृष्ठ संपादित करें और इस वेब पार्ट को कॉन्फ़िगर करें।",
    App_Loading: "फ़ॉर्म लोड हो रहा है…",
    App_OpenSettings: "सेटिंग खोलें",
    App_Tab_Questions: "प्रश्न",
    App_Tab_QuestionsWithCount: "प्रश्न ({count})",
    App_Tab_Responses: "प्रतिक्रियाएँ",
    App_Tab_Responses_Title: "प्रतिक्रियाएँ \"{list}\" में सहेजी जाती हैं",
    App_Templates_Start: "टेम्पलेट से शुरू करें",
    App_Settings_Title: "फ़ॉर्म सेटिंग — रूप-रंग, सूचनाएँ, एक्सेस",
    App_Settings_AriaLabel: "फ़ॉर्म सेटिंग",
    App_Preview: "पूर्वावलोकन",
    App_Preview_Close: "पूर्वावलोकन बंद करें",
    App_Preview_Hint: "पूर्वावलोकन — यहाँ आप जो भी सबमिट करेंगे वह सहेजा नहीं जाएगा। सत्यापन और ब्रांचिंग ठीक वैसे ही काम करते हैं जैसे प्रतिभागियों के लिए करेंगे।",
    App_Publish_GettingReady: "तैयारी हो रही है…",
    App_Publish_CollectResponses: "प्रतिक्रियाएँ एकत्र करें",
    App_Publish_Share: "साझा करें",
    App_Retry: "पुनः प्रयास करें",
    App_SaveError_Banner: "आपका पिछला बदलाव सहेजा नहीं जा सका। अपना कनेक्शन जाँचें, फिर दोबारा प्रयास करें।",
    App_Preflight_BlockingTitle: "एकत्र करने से पहले इन्हें ठीक करें",
    App_Preflight_WarningTitle: "पहले एक नज़र डालने लायक",
    App_Preflight_BlockingText: "ये प्रकाशित फ़ॉर्म को ठीक से काम करने से रोकेंगे।",
    App_Preflight_WarningText: "कुछ भी टूटा नहीं है, लेकिन लिंक साझा करने से पहले इन्हें ठीक करना आमतौर पर उचित होता है।",
    App_Preflight_GoTo: "यहाँ जाएँ",
    App_Preflight_CollectAnyway: "फिर भी प्रतिक्रियाएँ एकत्र करें",
    App_Preflight_Back: "फ़ॉर्म पर वापस जाएँ",
    App_Cancel: "रद्द करें",
    App_Done: "पूर्ण",
    App_Share_Title: "आपका फ़ॉर्म साझा करने के लिए तैयार है",
    App_Share_SubText: "यह लिंक उन सभी को भेजें जिन्हें फ़ॉर्म भरना है।",
    App_Share_LinkAriaLabel: "शेयर लिंक",
    App_Share_Copy: "कॉपी करें",
    App_Share_Copied: "कॉपी किया गया",
    App_Share_AddItemsEmphasis: "आइटम जोड़ने",
    App_Share_PermissionNote: "प्रतिभागियों को “{title}” में {addItems} की अनुमति और इस पृष्ठ का एक्सेस चाहिए। यदि किसी को सबमिट करते समय त्रुटि मिले, तो लगभग हमेशा यही कारण होता है।",
    App_Share_PrefillNote: "आप लिंक में कॉलम का नाम जोड़कर प्रश्नों के उत्तर पहले से भर सकते हैं, उदाहरण के लिए {example}।",
    App_Templates_ReplaceWarning: "टेम्पलेट चुनने से आपके मौजूदा प्रश्न बदल जाएँगे।",
    App_Templates_PickStart: "शुरुआती बिंदु चुनें — आप बाद में कुछ भी बदल सकते हैं।",
    App_Templates_Empty: "खाली",
    App_Templates_QuestionCount: "{count} प्रश्न",
    App_SaveChip_SavingTitle: "आपका नवीनतम संपादन सहेजा जा रहा है",
    App_SaveChip_Saving: "सहेजा जा रहा है…",
    App_SaveChip_FailedTitle: "आपका पिछला संपादन सहेजा नहीं जा सका। अपना कनेक्शन जाँचें और दोबारा प्रयास करें।",
    App_SaveChip_Failed: "सहेजना विफल",
    App_SaveChip_SavedTitle: "सभी बदलाव सहेज लिए गए हैं",
    App_SaveChip_Saved: "सहेजा गया",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "नई प्रतिक्रिया — {title}",
    Service_Email_NewResponseHeading: "नई प्रतिक्रिया: {title}",
    Service_Email_NewResponseIntro: "किसी ने अभी एक प्रतिक्रिया सबमिट की है — {date}।",
    Service_Email_ReceiptSubject: "आपकी प्रतिक्रिया — {title}",
    Service_Email_ReceiptHeading: "आपकी प्रतिक्रिया के लिए धन्यवाद!",
    Service_Email_ReceiptIntro: "\"{title}\" पर आपके द्वारा सबमिट की गई सामग्री की प्रति यह है।",
    App_History_Title: "संस्करण इतिहास",
    App_History_RestoredNotice: "{date} को सहेजा गया संस्करण पुनर्स्थापित किया गया। उसकी समीक्षा करें, फिर नए प्रश्न प्रकाशित करने के लिए \"प्रतिक्रियाएँ एकत्र करें\" का उपयोग करें।",
    App_History_Undo: "पुनर्स्थापना पूर्ववत करें",
    App_Share_CopyManual: "आपके ब्राउज़र ने कॉपी करना रोक दिया। ऊपर दिया गया लिंक चुनें और कॉपी करने के लिए Ctrl+C (Mac पर Cmd+C) दबाएँ।",
    App_Share_TeamsNote: "आप Microsoft Teams में हैं। यह लिंक सीधे SharePoint पृष्ठ खोलता है, इसलिए प्राप्तकर्ताओं के पास साइट की पहुँच होनी चाहिए।",
    App_Share_PrefillNotSecure: "पूर्वभरे उत्तर केवल सुविधा के लिए हैं: लिंक वाला कोई भी व्यक्ति उन्हें बदल सकता है, इसलिए उन्हें कभी सुरक्षा सीमा न मानें।",
    Designer_Section_DropHere: "प्रश्न को यहाँ छोड़ें",
    Designer_Section_DropEnd: "इस अनुभाग के अंत में ले जाने के लिए यहाँ छोड़ें",
    Designer_Rules_RemovedOne: "1 ब्रांचिंग नियम जो अब मेल नहीं खाता था, हटा दिया गया।",
    Designer_Rules_RemovedOther: "{count} ब्रांचिंग नियम जो अब मेल नहीं खाते थे, हटा दिए गए।",
    Designer_Settings_AllowEdit: "प्रतिभागियों को अपनी प्रतिक्रिया संपादित करने की अनुमति दें",
    Designer_Settings_AllowEditHint: "प्रतिभागी अपनी सबमिट की गई प्रतिक्रिया दोबारा खोलकर अपडेट कर सकते हैं। हर व्यक्ति केवल अपनी प्रतिक्रिया संपादित कर सकता है।",
    Designer_Settings_EnableApproval: "अनुमोदन वर्कफ़्लो सक्षम करें",
    Designer_Settings_ApprovalNotify: "निर्णय पर प्रतिभागी को ईमेल भेजें",
    Designer_Settings_ApprovalHint: "अगली बार प्रकाशित करने पर प्रतिक्रिया सूची में अनुमोदन कॉलम जुड़ जाते हैं। स्वामी प्रतिक्रियाएँ टैब से प्रतिक्रियाओं को स्वीकृत या अस्वीकृत करते हैं।",
    Designer_History_Title: "संस्करण इतिहास",
    Designer_History_Intro: "इस फ़ॉर्म के प्रश्नों और सेटिंग के पहले सहेजे गए संस्करण। पुनर्स्थापित करने पर संस्करण डिज़ाइनर में लोड होता है; आप उसे पूर्ववत कर सकते हैं, और नए प्रश्न केवल प्रकाशित करने पर बनते हैं।",
    Designer_History_Loading: "संस्करण लोड हो रहे हैं...",
    Designer_History_Empty: "कोई पुराना संस्करण नहीं मिला। संस्करण इतिहास के लिए \"Smart Forms Config\" सूची में वर्शनिंग चालू होनी चाहिए और कम से कम एक सहेजा हुआ संपादन होना चाहिए।",
    Designer_History_Latest: "नवीनतम",
    Designer_History_LatestTitle: "यह वह संस्करण है जो अभी उपयोग में है",
    Designer_History_By: "{name} द्वारा",
    Designer_History_UnknownAuthor: "अज्ञात लेखक",
    Designer_History_VersionLabel: "संस्करण {label}",
    Designer_History_Preview: "पूर्वावलोकन",
    Designer_History_Restore: "पुनर्स्थापित करें",
    Designer_History_QuestionsOne: "1 प्रश्न",
    Designer_History_QuestionsOther: "{count} प्रश्न",
    Designer_History_LoadFailed: "यह संस्करण लोड नहीं हो सका।",
    Designer_History_ConfirmTitle: "इस संस्करण को पुनर्स्थापित करें?",
    Designer_History_ConfirmText: "फ़ॉर्म को {date} को सहेजे गए संस्करण ({count} प्रश्न) से बदल दिया जाएगा। आप इसके तुरंत बाद इसे पूर्ववत कर सकते हैं।"
  };
});
