define([], function () {
  return {
    Designer_Color_Blue: "Kék",
    Designer_Color_Teal: "Pávakék",
    Designer_Color_Green: "Zöld",
    Designer_Color_Purple: "Lila",
    Designer_Color_Magenta: "Bíbor",
    Designer_Color_Red: "Piros",
    Designer_Color_Orange: "Narancssárga",
    Designer_Color_Gray: "Szürke",
    Designer_Settings_LayoutSinglePage: "Minden kérdés egy oldalon",
    Designer_Settings_LayoutWizard: "Szakaszonként egy lépés (varázsló)",
    Designer_Settings_Title: "Űrlapbeállítások",
    Designer_Common_Apply: "Alkalmaz",
    Designer_Common_Cancel: "Mégse",
    Designer_Settings_TabBasics: "Alapok",
    Designer_Settings_FormTitle: "Űrlap címe",
    Designer_Settings_Description: "Leírás",
    Designer_Settings_Layout: "Elrendezés",
    Designer_Settings_NumberQuestions: "Kérdések számozása",
    Designer_Settings_ShuffleQuestions: "Kérdések sorrendjének keverése minden válaszadónál",
    Designer_Settings_ShowProgressBar: "Folyamatjelző sáv megjelenítése",
    Designer_Settings_TabAppearance: "Megjelenés",
    Designer_Settings_AccentColor: "Kiemelő szín",
    Designer_Settings_CustomColorTitle: "Egyéni szín",
    Designer_Settings_CustomColorAria: "Egyéni kiemelő szín",
    Designer_Settings_AccentHint: "A kiemelő színek automatikusan igazodnak a kontraszthoz sötét webhelyeken, így az űrlap az oldal témájától függetlenül olvasható marad.",
    Designer_Settings_ShowHeader: "Az űrlap fejlécének megjelenítése",
    Designer_Settings_HeaderIcon: "Fejléc ikonja",
    Designer_Settings_TabAfterSubmit: "Beküldés után",
    Designer_Settings_SubmitButtonText: "Beküldés gomb szövege",
    Designer_Settings_SubmitPlaceholder: "Beküldés",
    Designer_Settings_ThankYouTitle: "Köszönő cím",
    Designer_Settings_ThankYouPlaceholder: "Köszönjük!",
    Designer_Settings_ThankYouMessage: "Köszönő üzenet",
    Designer_Settings_ShowSubmitAnother: "„Újabb válasz beküldése” gomb megjelenítése",
    Designer_Settings_TabNotifications: "Értesítések",
    Designer_Settings_EmailEachResponseTo: "Minden válasz elküldése e-mailben ide",
    Designer_Settings_EmailPlaceholder: "név@cég.hu; csapat@cég.hu",
    Designer_Settings_EmailDescription: "A szervezet tagjai e-mailben megkapják az összes választ, a listaelemre mutató hivatkozással",
    Designer_Settings_RespondentReceipt: "A válaszadók e-mailben megkapják válaszaik másolatát",
    Designer_Settings_NotificationsInfo: "Az értesítések a SharePoint saját levelezőszolgáltatását használják, ezért a címzetteknek a szervezet felhasználóinak kell lenniük. A külső címeket a rendszer csendben elveti.",
    Designer_Settings_TabAccess: "Hozzáférés",
    Designer_Settings_OpenFrom: "Megnyitás ettől",
    Designer_Settings_OpenImmediately: "Azonnali megnyitás",
    Designer_Settings_CloseAfter: "Bezárás ennyi idő után",
    Designer_Settings_NeverClose: "Soha ne záródjon be",
    Designer_Settings_ClearDates: "Dátumok törlése",
    Designer_Settings_DatesInverted: "A zárási dátum megegyezik a megnyitási dátummal vagy korábbi annál, így az űrlap soha nem fogadna el választ.",
    Designer_Settings_MaxResponses: "Leállítás ennyi válasz után",
    Designer_Settings_NoLimit: "Nincs korlát",
    Designer_Settings_OneResponsePerPerson: "Személyenként csak egy válasz engedélyezett",
    Designer_Settings_AllowSaveDraft: "A válaszadók menthessenek piszkozatot, és később fejezhessék be",
    Designer_Settings_ClosedMessage: "Az űrlap lezárásakor megjelenő üzenet",
    Designer_Settings_ClosedMessagePlaceholder: "Ez az űrlap már nem fogad válaszokat.",
    Designer_Settings_AccessInfo: "Ezeket a korlátozásokat az űrlap érvényesíti, nem a SharePoint. Aki jogosult elemet hozzáadni a válaszlistához, az továbbra is közvetlenül a listán keresztül adhat hozzá elemet.",
    Designer_Field_StyleInfo: "Információ (kiemelő)",
    Designer_Field_StyleSuccess: "Siker (zöld)",
    Designer_Field_StyleWarning: "Figyelmeztetés (borostyán)",
    Designer_Field_StylePlain: "Egyszerű szöveg",
    Designer_Field_StyleDivider: "Elválasztó vonal",
    Designer_Field_IconStars: "Csillagok",
    Designer_Field_IconHearts: "Szívek",
    Designer_Field_IconThumbs: "Felfelé mutató hüvelykujj",
    Designer_Field_FormatPlain: "Sima szám",
    Designer_Field_FormatCurrency: "Pénznem",
    Designer_Field_FormatPercent: "Százalék",
    Designer_Field_UntitledQuestion: "Cím nélküli kérdés",
    Designer_Field_DeletedQuestion: "egy törölt kérdés",
    Designer_Rule_Unary: "„{name}” {operator}",
    Designer_Rule_Between: "„{name}” {operator} {value} és {value2}",
    Designer_Rule_Binary: "„{name}” {operator} „{value}”",
    Designer_Rule_JoinAny: "VAGY",
    Designer_Rule_JoinAll: "ÉS",
    Designer_Rule_Preview: "Akkor jelenik meg, ha {conditions}.",
    Designer_Field_Yes: "Igen",
    Designer_Field_No: "Nem",
    Designer_Field_When: "Ha",
    Designer_Field_SelectValue: "Válasszon értéket",
    Designer_Field_DateValuePlaceholder: "ÉÉÉÉ-HH-NN vagy „today”",
    Designer_Field_ValuePlaceholder: "Érték",
    Designer_Field_UpperBound: "Felső határ",
    Designer_Field_RemoveCondition: "Feltétel eltávolítása",
    Designer_Field_FormulaInvalid: "Ez a képlet nem értékelhető ki. Ellenőrizze a zárójeleket és az operátorokat.",
    Designer_Field_FormulaMissing: "Ezek a kérdések nem léteznek: {names}.",
    Designer_Field_FormulaPreview: "Ha minden bemenet 10, ez {value} értéket jelenít meg.",
    Designer_Field_HintYesNo: "Használja a „yes” vagy „no” értéket",
    Designer_Field_HintMultiDefault: "Több alapértelmezett érték elválasztása: ;",
    Designer_Field_HintSingleDefault: "Egyeznie kell az egyik lehetőséggel",
    Designer_Field_HintDate: "Használja a „today” értéket, vagy egy dátumot, például 2026-03-01",
    Designer_Field_HintTime: "Használja a „now” értéket, vagy egy időpontot, például 09:30",
    Designer_Field_QuestionSettings: "Kérdésbeállítások",
    Designer_Field_Appearance: "Megjelenés",
    Designer_Field_Style: "Stílus",
    Designer_Field_ImageUrl: "Kép URL-címe (nem kötelező)",
    Designer_Field_Content: "Tartalom",
    Designer_Field_BasicFormatting: "Az alapvető formázás engedélyezett: félkövér, dőlt, listák és hivatkozások.",
    Designer_Field_TabOptions: "Lehetőségek",
    Designer_Field_TabBranching: "Elágazás",
    Designer_Field_BranchingNeedsQuestion: "Először adjon hozzá egy másik kérdést — az elágazáshoz szükség van valamire, amitől függhet.",
    Designer_Field_BranchingToggle: "A kérdés csak akkor jelenjen meg, ha más válaszok egyeznek",
    Designer_Field_Match: "Egyezés",
    Designer_Field_MatchAll: "mindegyik ezek közül",
    Designer_Field_MatchAny: "bármelyik ezek közül",
    Designer_Field_AddCondition: "Feltétel hozzáadása",
    Designer_Field_TabValidation: "Érvényesítés",
    Designer_Field_HelpText: "Súgószöveg",
    Designer_Field_HelpTextPlaceholder: "A kérdés címkéje alatt jelenik meg",
    Designer_Field_CheckboxLabel: "Jelölőnégyzet címkéje",
    Designer_Field_Placeholder: "Helyőrző",
    Designer_Field_DefaultAnswer: "Alapértelmezett válasz",
    Designer_Field_RequiredMessage: "Egyéni kötelezőségi üzenet",
    Designer_Field_RequiredMessagePlaceholder: "{title} megadása kötelező",
    Designer_Field_ThisQuestion: "Ez a kérdés",
    Designer_Field_RequiredMessageDescription: "A szokásos üzenet helyett jelenik meg, ha a kérdés üresen marad",
    Designer_Field_ReadOnly: "Csak olvasható (a válasz csak előre kitöltött hivatkozásból érkezhet)",
    Designer_Field_ValidationRules: "Érvényesítési szabályok",
    Designer_Field_MaxLength: "Maximális hossz",
    Designer_Field_Pattern: "Egyeznie kell ezzel a mintával",
    Designer_Field_PatternDescription: "Reguláris kifejezés. Hagyja üresen, ha nincs szükség mintaellenőrzésre.",
    Designer_Field_PatternMessage: "Üzenet, ha a minta nem egyezik",
    Designer_Field_PatternMessagePlaceholder: "Ez a válasz nem a várt formátumú",
    Designer_Field_Format: "Formátum",
    Designer_Field_UnitSuffix: "Az érték után megjelenő mértékegység",
    Designer_Field_UnitSuffixPlaceholder: "kg, óra, db…",
    Designer_Field_Minimum: "Minimum",
    Designer_Field_Maximum: "Maximum",
    Designer_Field_Decimals: "Tizedesjegyek",
    Designer_Field_Formula: "Képlet",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Hivatkozzon más kérdésekre a szövegükkel, kapcsos zárójelben. Támogatott: + - * / ( ) és round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Elérhető kérdések: {questions}",
    Designer_Field_NoneYet: "még nincs",
    Designer_Field_Step: "Lépésköz",
    Designer_Field_From: "Kezdet",
    Designer_Field_To: "Vég",
    Designer_Field_LowLabel: "Az alsó végpont címkéje",
    Designer_Field_LowLabelPlaceholder: "Egyáltalán nem valószínű",
    Designer_Field_HighLabel: "A felső végpont címkéje",
    Designer_Field_HighLabelPlaceholder: "Rendkívül valószínű",
    Designer_Field_SummarizeAs: "Összegzés módja",
    Designer_Field_SummarizeAverage: "Átlag és eloszlás",
    Designer_Field_SummarizeNps: "Net Promoter Score (0–10 skála szükséges)",
    Designer_Field_NpsWarning: "A Net Promoter Score csak 0–10 skálán értelmezhető. Állítsa a Kezdet értékét 0-ra, a Vég értékét 10-re.",
    Designer_Field_NumberOfIcons: "Ikonok száma",
    Designer_Field_Icon: "Ikon",
    Designer_Field_AllowHalf: "Fél értékek engedélyezése",
    Designer_Field_ShowOptionsAs: "Lehetőségek megjelenítése",
    Designer_Field_DisplayButtons: "Beágyazott gombok",
    Designer_Field_DisplayDropdown: "Legördülő lista",
    Designer_Field_DisplayAutomatic: "Automatikus (legfeljebb 6 lehetőségnél beágyazott)",
    Designer_Field_AllowOther: "Szabadon beírható „Egyéb” lehetőség hozzáadása",
    Designer_Field_OtherLabel: "Az „Egyéb” lehetőség címkéje",
    Designer_Field_OtherPlaceholder: "Egyéb",
    Designer_Field_ShuffleOptions: "A lehetőségek sorrendjének keverése minden válaszadónál",
    Designer_Field_MinSelections: "Minimális kijelölések",
    Designer_Field_MaxSelections: "Maximális kijelölések",
    Designer_Field_SourceList: "Forráslista",
    Designer_Field_ChooseList: "Válasszon listát",
    Designer_Field_LookupColumn: "Az oszlop, amelyből a lehetőségek származnak",
    Designer_Field_ChooseColumn: "Válasszon oszlopot",
    Designer_Field_ChooseListFirst: "Először válasszon listát",
    Designer_Field_LookupFilter: "Szűrő (nem kötelező)",
    Designer_Field_LookupFilterDescription: "OData-szűrő, amely szűkíti, mely forráselemek lesznek lehetőségek",
    Designer_Field_LookupInfo: "A válaszok a lehetőség szövegét tárolják, nem a forráselemre mutató hivatkozást, így a válaszok olvashatók maradnak akkor is, ha a forráslista később megváltozik.",
    Designer_Field_ConsentText: "A jelölőnégyzet fölött megjelenő feltételek",
    Designer_Field_AllowMultiplePeople: "Több személy engedélyezése",
    Designer_Field_AllowGroups: "Csoportok engedélyezése is",
    Designer_Field_IncludeTime: "Napszak megadása",
    Designer_Field_TimeStep: "Időköz (perc)",
    Designer_Field_MaxFiles: "Fájlok maximális száma",
    Designer_Field_MaxFileSize: "Egy fájl max. mérete (MB)",
    Designer_Field_AcceptedTypes: "Elfogadott fájltípusok",
    Designer_Field_AcceptedTypesDescription: "Vesszővel elválasztott kiterjesztések. Hagyja üresen, ha a SharePoint által engedélyezett bármely fájlt elfogadja.",
    Designer_Field_FilesInfo: "A fájlok mellékletként kerülnek mentésre a válaszelemhez. A SharePoint bizonyos kiterjesztéseket (például .exe) letilt, függetlenül attól, hogy itt mit engedélyez.",
    Designer_Field_Rows: "Sorok",
    Designer_Field_ProvisionedNote: "Ehhez a kérdéshez már tartozik listaoszlop ({name}). Az oszlop típusát módosító beállítások zároltak — másik típushoz duplikálja a kérdést.",
    Designer_Category_Text: "Szöveg",
    Designer_Category_Choice: "Választás",
    Designer_Category_Scales: "Skálák",
    Designer_Category_Date: "Dátum",
    Designer_Category_People: "Személyek",
    Designer_Category_Advanced: "Speciális",
    Designer_Category_Layout: "Elrendezés",
    Designer_Menu_CommonPresets: "Gyakori előbeállítások",
    Designer_Menu_AllTypes: "Minden kérdéstípus",
    Designer_Menu_ChangeType: "Típus módosítása",
    Designer_Menu_TypeLockedTitle: "A listaoszlop már létezik, ezért a típus zárolt. A módosításhoz duplikálja a kérdést.",
    Designer_Menu_MoreSettings: "Elágazás, érvényesítés és egyebek",
    Designer_Menu_InsertBelow: "Kérdés beszúrása alá",
    Designer_Card_Duplicate: "Duplikálás",
    Designer_Card_DeleteQuestion: "Kérdés törlése",
    Designer_Outline_Aria: "Kérdésvázlat",
    Designer_Outline_QuestionCountOne: "{count} kérdés",
    Designer_Outline_QuestionCountOther: "{count} kérdés",
    Designer_Outline_IssuesTitle: "{count} áttekintendő probléma",
    Designer_Outline_Find: "Kérdés keresése",
    Designer_Outline_Empty: "Még nincsenek kérdések.",
    Designer_Section_DefaultTitle: "{number}. szakasz",
    Designer_Card_Question: "Kérdés",
    Designer_Card_BranchingTitle: "Ez a kérdés csak akkor jelenik meg, ha egy elágazási szabály teljesül",
    Designer_Card_BranchingChip: "Elágazás",
    Designer_Card_LiveTitle: "A listaoszlop létezik, ezért a típus zárolt",
    Designer_Card_LiveChip: "Éles",
    Designer_Card_CheckChip: "Ellenőrzés",
    Designer_Option_Placeholder: "{number}. lehetőség",
    Designer_Option_LabelAria: "{number}. lehetőség címkéje",
    Designer_Option_ImageUrl: "Kép URL-címe",
    Designer_Option_ImageUrlAria: "{number}. lehetőség képének URL-címe",
    Designer_Option_Remove: "Lehetőség eltávolítása",
    Designer_Option_RemoveAria: "{number}. lehetőség eltávolítása",
    Designer_Option_Add: "Lehetőség hozzáadása",
    Designer_Option_OtherHint: "A válaszadók „{label}” címkéjű saját választ is beírhatnak.",
    Designer_Option_OtherFallback: "Egyéb",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Eltávolítás",
    Designer_Grid_RemoveAria: "{label} {number} eltávolítása",
    Designer_Grid_Statements: "Állítások",
    Designer_Grid_Scale: "Skála",
    Designer_Grid_AddStatement: "Állítás hozzáadása",
    Designer_Grid_AddScale: "Skála hozzáadása",
    Designer_Width_Full: "Teljes szélesség",
    Designer_Width_Half: "Fél szélesség",
    Designer_Width_Third: "Egyharmad szélesség",
    Designer_Width_Aria: "Kérdés szélessége",
    Designer_Card_BlockLabelPlaceholder: "Blokkcímke (a válaszadók nem látják)",
    Designer_Card_QuestionText: "Kérdés szövege",
    Designer_Card_MoveUp: "Feljebb",
    Designer_Card_MoveQuestionUp: "Kérdés feljebb helyezése",
    Designer_Card_MoveDown: "Lejjebb",
    Designer_Card_MoveQuestionDown: "Kérdés lejjebb helyezése",
    Designer_Card_DuplicateQuestion: "Kérdés duplikálása",
    Designer_Card_MultipleAnswers: "Több válasz",
    Designer_Card_Required: "Kötelező",
    Designer_Card_MoreOptions: "További lehetőségek",
    Designer_Card_MoreOptionsAria: "További lehetőségek ehhez a kérdéshez",
    Designer_Canvas_FormTitle: "Űrlap címe",
    Designer_Canvas_DescriptionPlaceholder: "Leírás hozzáadása (nem kötelező)",
    Designer_Canvas_DescriptionAria: "Űrlap leírása",
    Designer_Canvas_EmptyTitle: "Adja hozzá az első kérdést",
    Designer_Canvas_EmptyBody: "A kezdéshez válasszon kérdéstípust. A kérdések sorrendjét húzással módosíthatja, és elágazást is hozzáadhat, hogy a válaszadók csak a rájuk vonatkozó kérdéseket lássák.",
    Designer_Section_Chip: "{number}. szakasz / {total}",
    Designer_Section_TitlePlaceholder: "Szakasz címe",
    Designer_Section_TitleAria: "{number}. szakasz címe",
    Designer_Section_DescriptionPlaceholder: "Leírás (nem kötelező)",
    Designer_Section_DescriptionAria: "{number}. szakasz leírása",
    Designer_Section_MoveUp: "Szakasz feljebb helyezése",
    Designer_Section_MoveDown: "Szakasz lejjebb helyezése",
    Designer_Section_Delete: "Szakasz törlése",
    Designer_Card_DragToReorder: "Húzza az átrendezéshez",
    Designer_Card_ReorderAria: "{title} átrendezése",
    Designer_Card_ReorderFallback: "kérdés",
    Designer_Canvas_AddNew: "Új hozzáadása",
    Designer_Canvas_AddSection: "Szakasz hozzáadása",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Utca, házszám",
    Form_Address_Street2Placeholder: "Emelet, ajtó stb. (nem kötelező)",
    Form_Address_CityPlaceholder: "Város",
    Form_Address_StatePlaceholder: "Megye / tartomány",
    Form_Address_PostalCodePlaceholder: "Irányítószám",
    Form_Address_CountryPlaceholder: "Ország",
    Form_Address_StreetAria: "utca, házszám",
    Form_Address_Street2Aria: "címsor 2",
    Form_Address_CityAria: "város",
    Form_Address_StateAria: "megye vagy tartomány",
    Form_Address_PostalCodeAria: "irányítószám",
    Form_Address_CountryAria: "ország",
    Form_Consent_DefaultLabel: "Elfogadom",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered} / {total} sor megválaszolva",
    Form_Lookup_LoadError: "A kérdés lehetőségeit nem sikerült betölteni.",
    Form_Lookup_Loading: "Lehetőségek betöltése…",
    Form_Lookup_SelectOptionsPlaceholder: "Válasszon lehetőségeket",
    Form_Lookup_SelectOptionPlaceholder: "Válasszon egy lehetőséget",
    Form_Person_Placeholder: "Kezdjen el nevet írni…",
    Form_Person_SuggestedPeopleAndGroups: "Javasolt személyek és csoportok",
    Form_Person_SuggestedPeople: "Javasolt személyek",
    Form_Person_NoPeopleOrGroups: "Nem található személy vagy csoport",
    Form_Person_NoPeople: "Nem található személy",
    Form_Person_Searching: "Keresés…",
    Form_Ranking_Moved: "{item} áthelyezve a(z) {position}. helyre ({total} közül)",
    Form_Ranking_MoveUp: "Feljebb",
    Form_Ranking_MoveDown: "Lejjebb",
    Form_Ranking_MoveItemUpAria: "{item} feljebb helyezése",
    Form_Ranking_MoveItemDownAria: "{item} lejjebb helyezése",
    Form_Rating_ValueText: "{value} / {max}",
    Form_Rating_NotRated: "Nincs értékelve",
    Form_Rating_Clear: "Értékelés törlése",
    Form_RichText_Bold: "Félkövér",
    Form_RichText_Italic: "Dőlt",
    Form_RichText_Underline: "Aláhúzott",
    Form_RichText_BulletedList: "Felsorolás",
    Form_RichText_NumberedList: "Számozott lista",
    Form_RichText_ClearFormatting: "Formázás törlése",
    Form_RichText_ToolbarAria: "Szövegformázás",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "„{name}” kihagyva — a korlát {limit}.",
    Form_File_TypeNotAccepted: "„{name}” nem elfogadott típus.",
    Form_File_TooLarge: "„{name}” nagyobb, mint {size} MB.",
    Form_File_AlreadyAttached: "„{name}” már csatolva van.",
    Form_File_ReadError: "Az egyik fájlt nem sikerült beolvasni. Próbálja meg újra csatolni.",
    Form_File_HintMaxSize: "egyenként legfeljebb {size} MB",
    Form_File_HintOneFile: "1 fájl",
    Form_File_HintMaxFiles: "legfeljebb {count} fájl",
    Form_File_Reading: "Fájlok beolvasása…",
    Form_File_DropPrompt: "Húzza ide a fájlokat, vagy kattintson a tallózáshoz",
    Form_File_Remove: "{name} eltávolítása",
    Form_Signature_Alt: "Aláírás",
    Form_Signature_AriaSigned: "{label} — aláírva",
    Form_Signature_AriaEmpty: "{label} — üres",
    Form_Signature_Clear: "Törlés",
    Form_Signature_Signed: "Aláírva",
    Form_Signature_Prompt: "Írjon alá fent egérrel, tollal vagy ujjal",
    Form_Time_Placeholder: "Válasszon időpontot",
    Form_Field_DatePlaceholder: "Válasszon dátumot",
    Form_Field_TimeAriaWithLabel: "{label} — időpont",
    Form_Field_TimeAria: "Időpont",
    Form_Field_OtherDefault: "Egyéb",
    Form_Field_SelectOptionsPlaceholder: "Válasszon lehetőségeket",
    Form_Field_PleaseSpecify: "Kérjük, részletezze",
    Form_Field_OtherSpecifyAria: "{label} — kérjük, részletezze",
    Form_Field_SelectOptionPlaceholder: "Válasszon egy lehetőséget",
    Form_Field_Yes: "Igen",
    Form_Field_No: "Nem",
    Form_Field_SliderHint: "A válaszadáshoz húzza a csúszkát",
    Form_Field_WebAddressAriaWithLabel: "{label} — webcím",
    Form_Field_WebAddressAria: "Webcím",
    Form_Field_DisplayTextPlaceholder: "Megjelenített szöveg (nem kötelező)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — megjelenített szöveg",
    Form_Field_DisplayTextAria: "Megjelenített szöveg",
    Form_Field_ChooseBetween: "Válasszon {min} és {max} között",
    Form_Field_ChooseAtLeast: "Válasszon legalább {min} elemet",
    Form_Field_ChooseUpTo: "Legfeljebb {max} elemet válasszon",
    Form_Field_SelectedCount: "{count} kijelölve",
    Form_Field_RequiredAria: "(kötelező)",
    Form_Submit_SaveError: "A válasz mentése nem sikerült. Győződjön meg arról, hogy az űrlap közzé lett téve a tervezőből, és hogy van jogosultsága elemeket hozzáadni a válaszlistához.",
    Form_Empty_Message: "Ez az űrlap még nem tartalmaz kérdéseket. Az űrlap tulajdonosa a Kérdések lapon adhat hozzá.",
    Form_Checking: "Az űrlap ellenőrzése…",
    Form_Closed_NotYetOpen: "Még nem nyílt meg",
    Form_Closed_AlreadyAnswered: "Már megválaszolva",
    Form_Closed_Title: "Az űrlap lezárult",
    Form_Confirmation_PreviewNotice: "Ez csak előnézet volt — semmi sem lett mentve a válaszlistába.",
    Form_Confirmation_PreviewAgain: "Újabb előnézet",
    Form_Confirmation_SubmitAnother: "Újabb válasz beküldése",
    Form_Wizard_StepFallback: "{step}. lépés",
    Form_Wizard_StepsAria: "Űrlaplépések",
    Form_Wizard_StepOf: "{step}. lépés / {total}",
    Form_ErrorSummary_Title: "Kérjük, ellenőrizze a(z) {count} választ:",
    Form_ErrorSummary_UntitledQuestion: "Cím nélküli kérdés",
    Form_ErrorSummary_Question: "Kérdés",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Vissza",
    Form_Nav_Next: "Tovább",
    Form_Draft_Saving: "Mentés…",
    Form_Draft_Saved: "Piszkozat mentve",
    Form_Draft_SaveAndFinishLater: "Mentés és befejezés később",
    Form_Draft_NotSaved: "A piszkozat nincs mentve",
    Form_Submit_Preview: "Beküldés (előnézet)",
    Form_Submit_Button: "Beküldés",
    Form_Response_NoAnswer: "Nincs válasz",
    Form_Signature_TypeLabel: "Írja be a teljes nevét",
    Form_Signature_TypeInstead: "Inkább a nevem beírása",
    Form_Signature_DrawInstead: "Inkább rajzolás",
    Form_Edit_Button: "Előző válaszom szerkesztése",
    Form_Edit_Available: "Már beküldött egy választ. Új beküldése helyett szerkesztheti a meglévőt.",
    Form_Edit_Banner: "Az előző válaszát szerkeszti.",
    Form_Edit_Save: "Válasz frissítése",
    Form_Edit_UpdatedTitle: "Válasz frissítve",
    Form_Edit_UpdatedMessage: "A módosítások mentve lettek.",
    Form_Edit_LoadError: "Az előző választ nem sikerült betölteni. Próbálja újra.",
    Form_Draft_MissingFiles: "Csatolja újra: {names}. Ezeket a fájlokat nem sikerült visszaállítani.",
    Form_Attachments_Failed: "A válaszait mentettük, de ezeket a mellékleteket nem sikerült feltölteni: {names}. Próbálja újra, vagy forduljon az űrlap tulajdonosához.",
    Logic_ThisQuestion: "Ez a kérdés",
    Logic_Required: "A(z) {label} megadása kötelező",
    Logic_RequiredConsent: "A folytatáshoz jelölje be a négyzetet",
    Logic_RequiredFile: "Csatoljon legalább egy fájlt",
    Logic_RequiredSignature: "Adja meg az aláírását",
    Logic_RequiredLikert: "Válaszoljon minden sorra",
    Logic_InvalidEmail: "Adjon meg érvényes e-mail-címet",
    Logic_InvalidPhone: "Adjon meg érvényes telefonszámot",
    Logic_InvalidUrl: "Adjon meg érvényes, http:// vagy https:// kezdetű webcímet",
    Logic_MinValue: "Az értéknek legalább {value} kell lennie",
    Logic_MaxValue: "Az érték legfeljebb {value} lehet",
    Logic_MaxLength: "A maximális hossz {max} karakter",
    Logic_ChooseAtLeastOne: "Válasszon legalább {count} lehetőséget",
    Logic_ChooseAtLeastMany: "Válasszon legalább {count} lehetőséget",
    Logic_ChooseAtMostOne: "Legfeljebb {count} lehetőséget válasszon",
    Logic_ChooseAtMostMany: "Legfeljebb {count} lehetőséget válasszon",
    Logic_LikertRemaining: "Válaszoljon minden sorra ({count} maradt)",
    Logic_MaxFilesOne: "Legfeljebb {count} fájlt csatoljon",
    Logic_MaxFilesMany: "Legfeljebb {count} fájlt csatoljon",
    Logic_FileTooLarge: "A(z) „{name}” nagyobb, mint {size} MB",
    Logic_FileTypeNotAccepted: "A(z) „{name}” nem elfogadott fájltípus ({types})",
    Logic_AddressRequired: "Adjon meg legalább utcát és várost",
    Logic_PatternDefault: "Ez a válasz nem a várt formátumú",
    Logic_Yes: "Igen",
    Logic_No: "Nem",
    Logic_Agreed: "Elfogadva",
    Logic_NotAgreed: "Nincs elfogadva",
    Logic_Signed: "Aláírva",
    Logic_NoAnswer: "(nincs válasz)",
    Logic_Unknown: "(ismeretlen)",
    Logic_OtherSlice: "Egyéb ({count})",
    Logic_CsvResponseId: "Válaszazonosító",
    Logic_CsvSubmitted: "Beküldve",
    Logic_CsvSubmittedBy: "Beküldte",
    Logic_EmailQuestion: "Kérdés",
    Logic_EmailViewItem: "Megtekintés a Microsoft Listsben",
    Logic_EmailFooter: "A Smart Forms automatikusan küldte.",
    Logic_ClosedDefault: "Ez az űrlap már nem fogad válaszokat.",
    Logic_NotYetOpen: "Ez az űrlap {date} napon nyílik meg.",
    Logic_AlreadyResponded: "Ezt az űrlapot már kitöltötte. Köszönjük!",
    Logic_UntitledQuestion: "Cím nélküli kérdés",
    Logic_Issue_NoQuestions: "A válaszok gyűjtése előtt adjon hozzá legalább egy kérdést.",
    Logic_Issue_NoTitle: "Egy kérdésnek nincs szövege – közzétételkor automatikusan nevet kap.",
    Logic_Issue_DuplicateTitle: "A(z) {label} szövege megegyezik egy másik kérdésével, ami megnehezíti az eredmények olvasását.",
    Logic_Issue_NeedTwoOptions: "A(z) {label} kérdéshez legalább két lehetőség kell.",
    Logic_Issue_ImageNoImage: "A(z) {label} egyes lehetőségeihez nincs kép – szöveges csempeként jelennek meg.",
    Logic_Issue_LikertNeedRow: "A(z) {label} kérdéshez legalább egy sor kell.",
    Logic_Issue_LikertNeedColumns: "A(z) {label} kérdéshez legalább két skálaoszlop kell.",
    Logic_Issue_NoLookupList: "A(z) {label} kérdéshez nincs forráslista kiválasztva.",
    Logic_Issue_NoFormula: "A(z) {label} kérdésnek nincs képlete.",
    Logic_Issue_BadFormula: "A(z) {label} képlete nem értékelhető ki. Ellenőrizze a zárójeleket és az operátorokat.",
    Logic_Issue_MissingRefs: "A(z) {label} nem létező kérdésekre hivatkozik: {names}.",
    Logic_Issue_BadPattern: "A(z) {label} érvényesítési mintája érvénytelen.",
    Logic_Issue_BrokenRule: "A(z) {label} elágazási szabálya egy törölt kérdésre mutat.",
    Logic_Issue_SelfRule: "A(z) {label} elágazási szabálya önmagára hivatkozik.",
    Logic_Issue_RuleMismatch: "A(z) {label} elágazási szabálya már nem illik ahhoz a kérdéshez, amelytől függ.",
    Logic_Issue_RequiredReadOnly: "A(z) {label} kötelező és csak olvasható is, ezért csak előre kitöltött hivatkozással válaszolható meg.",
    Logic_Issue_EmptySection: "Egy szakaszban nincs kérdés, ezért ki lesz hagyva.",
    Logic_Issue_CloseBeforeOpen: "A zárási dátum nem későbbi a nyitási dátumnál, ezért az űrlap soha nem fogad válaszokat.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "A jóváhagyási e-mailek be vannak kapcsolva, de a jóváhagyási lépés ki van kapcsolva.",
    Logic_Op_equals: "egyenlő",
    Logic_Op_notEquals: "nem egyenlő",
    Logic_Op_contains: "tartalmazza",
    Logic_Op_notContains: "nem tartalmazza",
    Logic_Op_notEmpty: "meg van válaszolva",
    Logic_Op_empty: "nincs megválaszolva",
    Logic_Op_greaterThan: "nagyobb, mint",
    Logic_Op_greaterOrEqual: "legalább",
    Logic_Op_lessThan: "kisebb, mint",
    Logic_Op_lessOrEqual: "legfeljebb",
    Logic_Op_between: "között van",
    Logic_Op_before: "előtt van",
    Logic_Op_after: "után van",
    Logic_Type_Text: "Rövid válasz",
    Logic_TypeDesc_Text: "Egyetlen szövegsor",
    Logic_Category_Text: "Szöveg",
    Logic_Type_MultilineText: "Hosszú válasz",
    Logic_TypeDesc_MultilineText: "Több sornyi egyszerű szöveg",
    Logic_Type_RichText: "Formázott szöveg",
    Logic_TypeDesc_RichText: "Félkövér, listák és hivatkozások",
    Logic_Type_Choice: "Választás",
    Logic_TypeDesc_Choice: "Választás a lehetőségek listájából",
    Logic_Category_Choice: "Választás",
    Logic_Type_ImageChoice: "Képes választás",
    Logic_TypeDesc_ImageChoice: "Választás képcsempék közül",
    Logic_Type_Lookup: "Keresés listából",
    Logic_TypeDesc_Lookup: "A lehetőségek élőben egy másik SharePoint-listából érkeznek",
    Logic_Type_YesNo: "Igen / Nem",
    Logic_TypeDesc_YesNo: "Egyszerű be/ki kapcsoló",
    Logic_Type_Consent: "Beleegyezés",
    Logic_TypeDesc_Consent: "Jelölőnégyzet, amelyet a válaszadónak be kell jelölnie a folytatáshoz",
    Logic_Type_Ranking: "Rangsorolás",
    Logic_TypeDesc_Ranking: "Húzza a lehetőségeket preferencia szerinti sorrendbe",
    Logic_Type_Rating: "Értékelés",
    Logic_TypeDesc_Rating: "Csillagok, szívek vagy hüvelykujjak",
    Logic_Category_Scales: "Skálák",
    Logic_Type_Scale: "Véleményskála",
    Logic_TypeDesc_Scale: "Számozott skála feliratozott végekkel",
    Logic_Type_Slider: "Csúszka",
    Logic_TypeDesc_Slider: "Érték egy csúszkás skálán",
    Logic_Type_Likert: "Likert-rács",
    Logic_TypeDesc_Likert: "Több állítás értékelése egy közös skálán",
    Logic_Type_Number: "Szám",
    Logic_TypeDesc_Number: "Egyszerű, pénznem vagy százalék",
    Logic_Category_Advanced: "Speciális",
    Logic_Type_Calculated: "Számított",
    Logic_TypeDesc_Calculated: "Más válaszokból kiszámított, csak olvasható összeg",
    Logic_Type_Date: "Dátum",
    Logic_TypeDesc_Date: "Naptári dátum, opcionálisan idővel",
    Logic_Category_Date: "Dátum",
    Logic_Type_Time: "Idő",
    Logic_TypeDesc_Time: "Csak napszak",
    Logic_Type_Person: "Személy",
    Logic_TypeDesc_Person: "Válasszon valakit a szervezetből",
    Logic_Category_People: "Személyek",
    Logic_Type_Email: "E-mail",
    Logic_TypeDesc_Email: "Érvényesített e-mail-cím",
    Logic_Type_Phone: "Telefon",
    Logic_TypeDesc_Phone: "Érvényesített telefonszám",
    Logic_Type_Address: "Cím",
    Logic_TypeDesc_Address: "Utca, város, irányítószám és ország",
    Logic_Type_Hyperlink: "Hivatkozás",
    Logic_TypeDesc_Hyperlink: "Webcím",
    Logic_Type_FileUpload: "Fájlfeltöltés",
    Logic_TypeDesc_FileUpload: "Egy vagy több fájl csatolása a válaszhoz",
    Logic_Type_Signature: "Aláírás",
    Logic_TypeDesc_Signature: "Aláírás egérrel, tollal vagy ujjal",
    Logic_Type_Content: "Szövegblokk",
    Logic_TypeDesc_Content: "Útmutatás vagy kép – nem gyűjt választ",
    Logic_Category_Layout: "Elrendezés",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Mennyire valószínű, hogy ajánlaná…",
    Logic_Preset_satisfaction: "Elégedettség (1–5)",
    Logic_PresetDesc_satisfaction: "Nagyon elégedetlentől nagyon elégedettig",
    Logic_Preset_currency: "Pénznem",
    Logic_PresetDesc_currency: "Pénzösszeg",
    Logic_Preset_percent: "Százalék",
    Logic_PresetDesc_percent: "Százalékos érték",
    Logic_Template_blank_Name: "Üres űrlap",
    Logic_Template_blank_Description: "Kezdés a nulláról",
    Logic_Template_feedback_Name: "Ügyfél-visszajelzés",
    Logic_Template_feedback_Description: "NPS, értékelések és szabad megjegyzések",
    Logic_Template_event_Name: "Rendezvényregisztráció",
    Logic_Template_event_Description: "Résztvevői adatok, előadások és étkezési igények",
    Logic_Template_itrequest_Name: "IT-szolgáltatási kérelem",
    Logic_Template_itrequest_Description: "Kategorizált kérelmek prioritással és mellékletekkel",
    Logic_Template_expense_Name: "Költségelszámolás",
    Logic_Template_expense_Description: "Tételek, nyugták és számított végösszeg",
    Logic_Template_pulse_Name: "Munkatársi pulzusfelmérés",
    Logic_Template_pulse_Description: "Likert-rács, elkötelezettségi skála és névtelenségi megjegyzés",
    Logic_Template_safety_Name: "Biztonsági ellenőrzés",
    Logic_Template_safety_Description: "Ellenőrzőlista, fényképek és aláírás",
    Logic_Template_booking_Name: "Terem- vagy erőforrás-foglalás",
    Logic_Template_booking_Description: "Lookup-alapú erőforrás-választó időponttal",
    Charts_ColumnChartAria: "Oszlopdiagram {count} kategóriával",
    Charts_DonutChartAria: "Perecdiagram {count} kategóriáról",
    Charts_NoAnswers: "Még nincsenek válaszok.",
    Charts_NoResponses: "Még nincsenek válaszok.",
    Charts_Responses: "Válaszok",
    Charts_ResponsesOverTime: "Válaszok az idő függvényében",
    Responses_Chart_Answer: "Válasz",
    Responses_Chart_Average: "Átlag",
    Responses_Chart_AverageOf: "{count} átlaga",
    Responses_Chart_AveragePosition: "Átlagos pozíció",
    Responses_Chart_AverageRange: "Átlag (1–{max})",
    Responses_Chart_AvgValue: "átl. {value}",
    Responses_Chart_Detractors: "Kritikusok (0–6)",
    Responses_Chart_Max: "Max.",
    Responses_Chart_Maximum: "Maximum",
    Responses_Chart_Median: "Medián",
    Responses_Chart_MentionOne: "{count} említés",
    Responses_Chart_MentionOther: "{count} említés",
    Responses_Chart_Min: "Min.",
    Responses_Chart_Minimum: "Minimum",
    Responses_Chart_NoAnswers: "Még nincsenek válaszok.",
    Responses_Chart_NoNumeric: "Még nincsenek numerikus válaszok.",
    Responses_Chart_NoRankings: "Még nincsenek rangsorok.",
    Responses_Chart_NoScores: "Még nincsenek pontszámok.",
    Responses_Chart_NotEnoughText: "Még nincs elég szöveg az összegzéshez.",
    Responses_Chart_NpsScore: "NPS-pontszám",
    Responses_Chart_Option: "Lehetőség",
    Responses_Chart_Passives: "Passzívak (7–8)",
    Responses_Chart_Promoters: "Támogatók (9–10)",
    Responses_Chart_ResponseOne: "válasz",
    Responses_Chart_ResponseOther: "válasz",
    Responses_Chart_Responses: "Válaszok",
    Responses_Chart_ShowingAnswers: "{total} válaszból {shown} látható.",
    Responses_Chart_Statement: "Állítás",
    Responses_Chart_Statistic: "Statisztika",
    Responses_Chart_StdDev: "Szórás",
    Responses_Chart_StdDeviation: "Szórás",
    Responses_Chart_Total: "Összesen",
    Responses_Chart_Value: "Érték",
    Responses_Dashboard_AllHidden: "Minden kérdés el van rejtve az irányítópultról. A visszaállításukhoz használja a „Rejtett kérdések megjelenítése” lehetőséget.",
    Responses_Dashboard_AnsweredOf: "{answered} / {total} megválaszolva",
    Responses_Dashboard_AnsweredOfPinned: "{answered} / {total} megválaszolva · kitűzve",
    Responses_Dashboard_AveragedAcrossResponses: "Átlag az összes válaszra",
    Responses_Dashboard_ByDay: "Naponta",
    Responses_Dashboard_ByMonth: "Havonta",
    Responses_Dashboard_ByWeek: "Hetente",
    Responses_Dashboard_ChartAuto: "Automatikus",
    Responses_Dashboard_ChartBars: "Sávok",
    Responses_Dashboard_ChartColumns: "Oszlopok",
    Responses_Dashboard_ChartDonut: "Perec",
    Responses_Dashboard_ChartGauge: "Mérőóra",
    Responses_Dashboard_ChartHistogram: "Hisztogram",
    Responses_Dashboard_ChartOptions: "Diagramlehetőségek",
    Responses_Dashboard_ChartOptionsFor: "Diagramlehetőségek: {title}",
    Responses_Dashboard_ChartStatistics: "Statisztika",
    Responses_Dashboard_ChartTable: "Táblázat",
    Responses_Dashboard_ChartWordFrequency: "Szógyakoriság",
    Responses_Dashboard_EmptyBody: "Amint az emberek elkezdenek válaszolni, ez az irányítópult automatikusan feltöltődik — kiemelt számokkal, válaszidővonallal és a figyelemre méltó kérdések diagramjaival.",
    Responses_Dashboard_EmptyTitle: "Még nincsenek válaszok",
    Responses_Dashboard_Hide: "Elrejtés az irányítópultról",
    Responses_Dashboard_Highlights: "Kiemelések",
    Responses_Dashboard_Last7Days: "Elmúlt 7 nap",
    Responses_Dashboard_LatestDate: "Legutóbbi: {date}",
    Responses_Dashboard_MedianTimeToComplete: "Kitöltés mediánideje",
    Responses_Dashboard_NoPriorWeek: "Nincs előző hét az összehasonlításhoz",
    Responses_Dashboard_OneEach: "Egyenként egy",
    Responses_Dashboard_Pin: "Kitűzés az irányítópultra",
    Responses_Dashboard_QuestionFallback: "kérdés",
    Responses_Dashboard_QuestionsAnswered: "Megválaszolt kérdések",
    Responses_Dashboard_RecordedOnSubmit: "Beküldéskor rögzítve",
    Responses_Dashboard_RepeatResponses: "{count} ismételt válasz",
    Responses_Dashboard_ResponsesOverTime: "Válaszok az idő függvényében",
    Responses_Dashboard_ShowHidden: "Rejtett kérdések megjelenítése",
    Responses_Dashboard_SinceMidnight: "Éjfél óta",
    Responses_Dashboard_Today: "Ma",
    Responses_Dashboard_TotalResponses: "Összes válasz",
    Responses_Dashboard_UniqueRespondents: "Egyedi válaszadók",
    Responses_Dashboard_Unpin: "Kitűzés megszüntetése az irányítópultról",
    Responses_Dashboard_UntitledQuestion: "Cím nélküli kérdés",
    Responses_Dashboard_VsPrevious7Days: "az előző 7 naphoz képest",
    Responses_Detail_Answers: "Válaszok",
    Responses_Detail_AsTheForm: "Az űrlap szerint",
    Responses_Detail_Cancel: "Mégse",
    Responses_Detail_Delete: "Törlés",
    Responses_Detail_DeleteBody: "A listaelem a webhely lomtárába kerül, így onnan visszaállítható.",
    Responses_Detail_DeleteTitle: "Törli ezt a választ?",
    Responses_Detail_Deleting: "Törlés…",
    Responses_Detail_Draft: "Piszkozat",
    Responses_Detail_Header: "{index}. válasz / {total}",
    Responses_Detail_LoadingAttachments: "Mellékletek betöltése…",
    Responses_Detail_Next: "Következő válasz",
    Responses_Detail_NoAnswer: "Nincs válasz",
    Responses_Detail_Previous: "Előző válasz",
    Responses_Detail_Print: "Nyomtatás",
    Responses_Detail_Signature: "Aláírás",
    Responses_Detail_Signed: "Aláírva",
    Responses_Detail_Took: "{duration} alatt töltötte ki",
    Responses_Summary_AnsweredOfType: "{answered} / {total} megválaszolva · {type}",
    Responses_Summary_ByField: "{title} szerint",
    Responses_Summary_CompareBy: "Összehasonlítás…",
    Responses_Summary_EmptyBody: "Minden kérdéshez külön összegzés jelenik meg itt.",
    Responses_Summary_NoComparison: "Nincs összehasonlítás",
    Responses_Summary_NothingToCompare: "Senki sem válaszolt a(z) „{title}” kérdésre, így nincs mit összehasonlítani.",
    Responses_Summary_OtherNote: "A(z) {max} kategóriánál többet tartalmazó diagramok a legkisebbeket az „Egyéb” csoportba vonják össze — az összes érték megtekintéséhez váltson a kártyán Táblázatra.",
    Responses_Summary_ResponseCountOne: "{count} válasz",
    Responses_Summary_ResponseCountOther: "{count} válasz",
    Responses_Summary_SeeAllAnswers: "Az összes válasz megtekintése a táblázatban",
    Responses_Summary_SegmentNote: "A(z) {groups} legnagyobb csoport látható. Az a válasz, amely több lehetőséget is kijelölt, minden egyező csoportban megjelenik, így a csoportösszegek együtt meghaladhatják a(z) {total} értéket.",
    Responses_Summary_SplitBy: "Felosztás: {title}",
    Responses_Summary_Untitled: "névtelen",
    Responses_Table_Apply: "Alkalmaz",
    Responses_Table_Cancel: "Mégse",
    Responses_Table_ClearSelection: "Kijelölés törlése",
    Responses_Table_ColumnOrder: "Oszlopsorrend",
    Responses_Table_ColumnsCount: "Oszlopok ({shown}/{total})",
    Responses_Table_Delete: "Törlés",
    Responses_Table_DeleteBody: "A listaelemek a webhely lomtárába kerülnek, így onnan visszaállíthatók.",
    Responses_Table_DeleteSelected: "Kijelöltek törlése",
    Responses_Table_DeleteTitleOne: "Töröl {count} választ?",
    Responses_Table_DeleteTitleOther: "Töröl {count} választ?",
    Responses_Table_Deleting: "Törlés…",
    Responses_Table_MoveDown: "Lejjebb",
    Responses_Table_MoveDownFor: "{title} lejjebb helyezése",
    Responses_Table_MoveUp: "Feljebb",
    Responses_Table_MoveUpFor: "{title} feljebb helyezése",
    Responses_Table_NoColumns: "Még nincs látható kérdésoszlop.",
    Responses_Table_NoMatch: "Egyetlen válasz sem felel meg a jelenlegi szűrőknek.",
    Responses_Table_NothingToShow: "Nincs megjeleníthető elem",
    Responses_Table_OpenResponse: "Válasz megnyitása",
    Responses_Table_OrderNote: "A Beküldve és a Beküldő mindig elöl áll. A húzással megadott sorrend a kérdésoszlopokra vonatkozik.",
    Responses_Table_Reorder: "Átrendezés",
    Responses_Table_ResetColumns: "Oszlopok alaphelyzetbe állítása",
    Responses_Table_SelectResponse: "Válasz kijelölése",
    Responses_Table_SelectedOne: "{count} válasz kijelölve",
    Responses_Table_SelectedOther: "{count} válasz kijelölve",
    Responses_Table_ShowAll: "Összes megjelenítése",
    Responses_Table_ShowTheseQuestions: "Ezen kérdések megjelenítése",
    Responses_Table_Submitted: "Beküldve",
    Responses_Table_SubmittedBy: "Beküldő",
    Responses_Table_ToggleSelection: "Kijelölés váltása",
    Responses_Table_Unknown: "Ismeretlen",
    Responses_Table_Untitled: "Cím nélküli",
    Responses_View_AllTime: "Bármikor",
    Responses_View_AnyAnswer: "Bármely válasz",
    Responses_View_Clear: "Törlés",
    Responses_View_CopyShareLink: "Megosztási hivatkozás másolása",
    Responses_View_CountFiltered: "{total} válaszból {shown}",
    Responses_View_CountOne: "{count} válasz",
    Responses_View_CountOther: "{count} válasz",
    Responses_View_Dashboard: "Irányítópult",
    Responses_View_DateRange: "Dátumtartomány",
    Responses_View_EmptyBody: "Osszák meg az űrlapot a gyűjtés megkezdéséhez. A válaszok a(z) „{list}” listába kerülnek, és azonnal megjelennek itt.",
    Responses_View_EmptyTitle: "Még nincsenek válaszok",
    Responses_View_ExportCsv: "Exportálás CSV-be",
    Responses_View_FilterByAnswer: "Szűrés válasz szerint",
    Responses_View_FilterByQuestion: "Szűrés kérdés szerint",
    Responses_View_FilterValue: "Szűrőérték",
    Responses_View_Last30Days: "Elmúlt 30 nap",
    Responses_View_Last7Days: "Elmúlt 7 nap",
    Responses_View_Last90Days: "Elmúlt 90 nap",
    Responses_View_LoadError: "A válaszokat nem sikerült betölteni. Tegye közzé egyszer az űrlapot, hogy létrejöjjenek a listaoszlopok, majd próbálja újra.",
    Responses_View_Loading: "Válaszok betöltése…",
    Responses_View_MoreActions: "További válaszműveletek",
    Responses_View_PreviewForm: "Űrlap előnézete",
    Responses_View_Refresh: "Frissítés",
    Responses_View_ResponsesTab: "Válaszok ({count})",
    Responses_View_SearchPlaceholder: "Keresés az összes válaszban",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Válasszon értéket",
    Responses_View_Summary: "Összegzés",
    Responses_View_Today: "Ma",
    Responses_View_Truncated: "Ez a lista több választ tartalmaz, mint amennyit a Smart Forms egyszerre be tud tölteni. A legújabb {count} látható — a teljes készlethez nyissa meg a listát a Microsoft Listsben.",
    Responses_View_TryAgain: "Próbálja újra",
    Responses_View_Untitled: "Cím nélküli",
    Responses_Approval_Column: "Jóváhagyás",
    Responses_Approval_ReviewerColumn: "Felülvizsgáló",
    Responses_Approval_CommentColumn: "Felülvizsgáló megjegyzése",
    Responses_Approval_Pending: "Függőben",
    Responses_Approval_Approved: "Jóváhagyva",
    Responses_Approval_Rejected: "Elutasítva",
    Responses_Approval_AnyStatus: "Bármely jóváhagyási állapot",
    Responses_Approval_FilterLabel: "Szűrés jóváhagyási állapot szerint",
    Responses_Approval_ApproveSelected: "Kijelöltek jóváhagyása",
    Responses_Approval_RejectSelected: "Kijelöltek elutasítása",
    Responses_Approval_BulkFailed: "{count} választ nem sikerült frissíteni. Próbálja újra.",
    Responses_Approval_Approve: "Jóváhagyás",
    Responses_Approval_Reject: "Elutasítás",
    Responses_Approval_Reset: "Visszaállítás függőre",
    Responses_Approval_CommentLabel: "Megjegyzés (nem kötelező)",
    Responses_Approval_ReviewedBy: "Felülvizsgálta: {name}",
    Responses_Approval_Error: "A döntést nem sikerült menteni. Próbálja újra.",
    Responses_Dashboard_ApprovalStatus: "Felülvizsgálatra vár",
    Responses_Dashboard_ApprovalBreakdown: "{pending} függőben, {approved} jóváhagyva, {rejected} elutasítva",
    Responses_Dashboard_TimelineCoarsened: "A dátumtartomány hosszú, ezért az idővonalat durvábban csoportosítottuk ({grain}).",
    Responses_Dashboard_TimelineTruncated: "A dátumtartomány nagyon hosszú, ezért csak a legutóbbi {count} időszak látható.",
    Service_Item_DefaultTitle: "Válasz – {date}",
    Service_Email_ApprovalSubject: "A válasza: {status} – {title}",
    Service_Email_ApprovalHeading: "A válasza: {status}",
    Service_Email_ApprovalIntro: "Egy felülvizsgáló a(z) „{title}” űrlapra adott válaszát a következőre állította: {status}.",
    Service_Email_ApprovalCommentLabel: "Felülvizsgáló megjegyzése",
    Service_Approval_Approved: "jóváhagyva",
    Service_Approval_Rejected: "elutasítva",
    Service_Approval_Pending: "függőben",
    Service_Lookup_InvalidFilter: "A keresési szűrő érvénytelen.",
    Service_Edit_NotAllowed: "Ez az űrlap nem engedi a beküldött válasz szerkesztését.",
    Service_Edit_NotYours: "Csak a saját válaszát szerkesztheti.",
    Service_Signature_AttachmentLabel: "Aláírás",
    PropertyPane_ListsLoadFailed: "A webhely listáit nem sikerült betölteni.",
    PropertyPane_EnterListName: "Először adjon nevet az új listának.",
    PropertyPane_CreatingList: "„{name}” létrehozása…",
    PropertyPane_ListCreated: "A(z) „{title}” lista létrejött, és ki lett választva.",
    PropertyPane_ListAlreadyExists: "Már létezik „{name}” nevű lista — válassza ki a fenti legördülő listából.",
    PropertyPane_CreateListFailed: "A listát nem sikerült létrehozni. Ellenőrizze, hogy van jogosultsága listákat létrehozni ezen a webhelyen.",
    PropertyPane_Description: "Válassza ki az űrlapválaszokat tároló SharePoint-listát, vagy hozzon létre újat. Minden más — kérdések, megjelenés, értesítések — közvetlenül az oldalon szerkeszthető.",
    PropertyPane_ResponseList_GroupName: "Válaszlista",
    PropertyPane_ListDropdown_Label: "Válaszok mentése ebbe a listába",
    PropertyPane_ResponsesGoTo: "A válaszok a(z) „{name}” listába kerülnek.",
    PropertyPane_PickList: "Válasszon listát, vagy hozzon létre egyet lent.",
    PropertyPane_LoadingLists: "Listák betöltése…",
    PropertyPane_NewListName_Label: "Vagy hozzon létre új listát",
    PropertyPane_NewListName_Placeholder: "Új lista neve",
    PropertyPane_CreateList_Button: "Lista létrehozása",
    PropertyPane_Tips_GroupName: "Tippek",
    PropertyPane_Tip_AutoSave: "A kérdések és a beállítások szerkesztés közben automatikusan mentődnek — az oldalt nem kell menteni vagy közzétenni.",
    PropertyPane_Tip_Permissions: "A válaszadóknak jogosultságra van szükségük elemek hozzáadásához a válaszlistán. Ha valaki hibát jelez beküldéskor, ellenőrizze a lista jogosultságait.",
    PropertyPane_Tip_Share: "Az oldalon a „Válaszok gyűjtése” gombbal hozhatja létre a listaoszlopokat, és kaphat megosztható kitöltési hivatkozást.",
    App_ErrorBoundary_Title: "Smart Forms — megjelenítési hiba",
    App_ErrorBoundary_Message: "Üzenet:",
    App_ErrorBoundary_Stack: "Veremkövetés:",
    App_ErrorBoundary_NoStack: "(nincs elérhető veremkövetés)",
    App_ErrorBoundary_ConsoleNote: "A teljes részletek a böngészőkonzolba is bekerültek.",
    App_DefaultQuestionTitle: "{number}. kérdés",
    App_Error_ListMissing: "Az űrlaphoz beállított lista már nem létezik. Válasszon másik listát a webrész beállításaiban.",
    App_Error_LoadConfig: "Hiba történt az űrlapkonfiguráció betöltésekor.",
    App_Error_Unable: "Az űrlap nem tölthető be.",
    App_Publish_ConflictNotice: "A(z) „{title}” kérdéshez már tartozik egy eltérő típusú ({type}) listaoszlop. Nevezze át a kérdést, hogy új oszlop jöhessen létre, vagy állítsa vissza a típusát.",
    App_Publish_ConflictUnnamedQuestion: "egy kérdés",
    App_Publish_ColumnsAddedOne: "{count} oszlop hozzáadva a(z) „{list}” listához.",
    App_Publish_ColumnsAddedOther: "{count} oszlop hozzáadva a(z) „{list}” listához.",
    App_Publish_TheList: "a lista",
    App_Publish_UpToDate: "A válaszlista már naprakész.",
    App_Publish_Error: "A listaoszlopokat nem sikerült létrehozni. Ez általában azt jelenti, hogy nincs Manage Lists jogosultsága a válaszlistán, de előfordulhat olyan webhelyeken is, ahol az egyéni parancsfájlok le vannak tiltva. A hiba okáért nézze meg a böngészőkonzolt, vagy próbálja újra.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Készítsen igényes űrlapot SharePoint-lista fölé — {count} kérdéstípus, elágazási logika, fájlfeltöltés, megosztható kitöltési hivatkozások és eredményirányítópult.",
    App_Placeholder_ChooseList: "Válasszon vagy hozzon létre listát",
    App_Placeholder_Hint: "A kezdéshez szerkessze az oldalt, és konfigurálja ezt a webrészt.",
    App_Loading: "Űrlap betöltése…",
    App_OpenSettings: "Beállítások megnyitása",
    App_Tab_Questions: "Kérdések",
    App_Tab_QuestionsWithCount: "Kérdések ({count})",
    App_Tab_Responses: "Válaszok",
    App_Tab_Responses_Title: "A válaszok a(z) „{list}” listába kerülnek",
    App_Templates_Start: "Indulás sablonból",
    App_Settings_Title: "Űrlapbeállítások — megjelenés, értesítések, hozzáférés",
    App_Settings_AriaLabel: "Űrlapbeállítások",
    App_Preview: "Előnézet",
    App_Preview_Close: "Előnézet bezárása",
    App_Preview_Hint: "Előnézet — az itt beküldött adatok nem kerülnek mentésre. Az érvényesítés és az elágazás pontosan úgy működik, mint a válaszadóknál.",
    App_Publish_GettingReady: "Előkészítés…",
    App_Publish_CollectResponses: "Válaszok gyűjtése",
    App_Publish_Share: "Megosztás",
    App_Retry: "Újra",
    App_SaveError_Banner: "Az utolsó módosítást nem sikerült menteni. Ellenőrizze a kapcsolatot, majd próbálja újra.",
    App_Preflight_BlockingTitle: "Javítsa ezeket a gyűjtés előtt",
    App_Preflight_WarningTitle: "Érdemes átnézni",
    App_Preflight_BlockingText: "Ezek megakadályoznák a közzétett űrlap megfelelő működését.",
    App_Preflight_WarningText: "Semmi sem hibás, de ezeket általában érdemes javítani a hivatkozás megosztása előtt.",
    App_Preflight_GoTo: "Ugrás ide",
    App_Preflight_CollectAnyway: "Gyűjtés mégis",
    App_Preflight_Back: "Vissza az űrlaphoz",
    App_Cancel: "Mégse",
    App_Done: "Kész",
    App_Share_Title: "Az űrlap készen áll a megosztásra",
    App_Share_SubText: "Küldje el ezt a hivatkozást mindenkinek, akinek ki kell töltenie az űrlapot.",
    App_Share_LinkAriaLabel: "Megosztási hivatkozás",
    App_Share_Copy: "Másolás",
    App_Share_Copied: "Másolva",
    App_Share_AddItemsEmphasis: "elemek hozzáadására",
    App_Share_PermissionNote: "A válaszadóknak jogosultságra van szükségük a(z) „{title}” listán {addItems}, valamint hozzáférésre ehhez az oldalhoz. Ha valaki hibát kap beküldéskor, szinte mindig ez az oka.",
    App_Share_PrefillNote: "A hivatkozásban előre megválaszolhat kérdéseket az oszlop nevének megadásával, például {example}.",
    App_Templates_ReplaceWarning: "A sablon kiválasztása lecseréli a jelenlegi kérdéseket.",
    App_Templates_PickStart: "Válasszon kiindulópontot — utána bármit módosíthat.",
    App_Templates_Empty: "Üres",
    App_Templates_QuestionCount: "{count} kérdés",
    App_SaveChip_SavingTitle: "A legutóbbi módosítás mentése folyamatban",
    App_SaveChip_Saving: "Mentés…",
    App_SaveChip_FailedTitle: "Az utolsó módosítást nem sikerült menteni. Ellenőrizze a kapcsolatot, és próbálja újra.",
    App_SaveChip_Failed: "A mentés sikertelen",
    App_SaveChip_SavedTitle: "Minden módosítás mentve",
    App_SaveChip_Saved: "Mentve",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Új válasz — {title}",
    Service_Email_NewResponseHeading: "Új válasz: {title}",
    Service_Email_NewResponseIntro: "Valaki most küldött be egy választ — {date}.",
    Service_Email_ReceiptSubject: "Az Ön válasza — {title}",
    Service_Email_ReceiptHeading: "Köszönjük a válaszát!",
    Service_Email_ReceiptIntro: "Itt van a(z) „{title}” űrlapon beküldött válaszainak másolata.",
    App_History_Title: "Verzióelőzmények",
    App_History_RestoredNotice: "A(z) {date} napon mentett verzió vissza lett állítva. Tekintse át, majd az új kérdések közzétételéhez használja a Válaszok gyűjtése lehetőséget.",
    App_History_Undo: "Visszaállítás visszavonása",
    App_Share_CopyManual: "A böngésző letiltotta a másolást. Jelölje ki a fenti hivatkozást, és másoláshoz nyomja meg a Ctrl+C billentyűkombinációt (Macen Cmd+C).",
    App_Share_TeamsNote: "Ön a Microsoft Teamsben van. Ez a hivatkozás közvetlenül a SharePoint-oldalt nyitja meg, ezért a címzetteknek hozzáférés kell a webhelyhez.",
    App_Share_PrefillNotSecure: "Az előre kitöltött válaszok csak kényelmi funkciók: a hivatkozással bárki módosíthatja őket, ezért soha ne tekintse biztonsági határnak.",
    Designer_Section_DropHere: "Húzza ide a kérdést",
    Designer_Section_DropEnd: "Ejtse ide, hogy a szakasz végére kerüljön",
    Designer_Rules_RemovedOne: "1 már nem illeszkedő elágazási szabály el lett távolítva.",
    Designer_Rules_RemovedOther: "{count} már nem illeszkedő elágazási szabály el lett távolítva.",
    Designer_Settings_AllowEdit: "A válaszadók szerkeszthetik a saját válaszukat",
    Designer_Settings_AllowEditHint: "A válaszadók újra megnyithatják és frissíthetik a beküldött válaszukat. Mindenki csak a saját válaszát szerkesztheti.",
    Designer_Settings_EnableApproval: "Jóváhagyási munkafolyamat engedélyezése",
    Designer_Settings_ApprovalNotify: "E-mail a válaszadónak döntés esetén",
    Designer_Settings_ApprovalHint: "A következő közzétételkor jóváhagyási oszlopok kerülnek a válaszlistába. A tulajdonosok a Válaszok lapon hagyhatják jóvá vagy utasíthatják el a válaszokat.",
    Designer_History_Title: "Verzióelőzmények",
    Designer_History_Intro: "Az űrlap kérdéseinek és beállításainak korábban mentett verziói. A visszaállítás betölti a verziót a tervezőbe; visszavonhatja, és új kérdések csak közzétételkor jönnek létre.",
    Designer_History_Loading: "Verziók betöltése...",
    Designer_History_Empty: "Nem található korábbi verzió. A verzióelőzményekhez be kell kapcsolni a verziókezelést a „Smart Forms Config” listán, és legalább egy mentett szerkesztésre van szükség.",
    Designer_History_Latest: "Legutóbbi",
    Designer_History_LatestTitle: "Ez a jelenleg használt verzió",
    Designer_History_By: "{name} által",
    Designer_History_UnknownAuthor: "Ismeretlen szerző",
    Designer_History_VersionLabel: "{label} verzió",
    Designer_History_Preview: "Előnézet",
    Designer_History_Restore: "Visszaállítás",
    Designer_History_QuestionsOne: "1 kérdés",
    Designer_History_QuestionsOther: "{count} kérdés",
    Designer_History_LoadFailed: "Ezt a verziót nem sikerült betölteni.",
    Designer_History_ConfirmTitle: "Visszaállítja ezt a verziót?",
    Designer_History_ConfirmText: "Az űrlap a(z) {date} napon mentett verzióra lesz cserélve ({count} kérdés). Ezt közvetlenül utána visszavonhatja."
  };
});
