define([], function () {
  return {
    Designer_Color_Blue: "Biru",
    Designer_Color_Teal: "Teal",
    Designer_Color_Green: "Hijau",
    Designer_Color_Purple: "Ungu",
    Designer_Color_Magenta: "Magenta",
    Designer_Color_Red: "Merah",
    Designer_Color_Orange: "Oranye",
    Designer_Color_Gray: "Abu-abu",
    Designer_Settings_LayoutSinglePage: "Semua pertanyaan dalam satu halaman",
    Designer_Settings_LayoutWizard: "Satu bagian per langkah (wizard)",
    Designer_Settings_Title: "Pengaturan formulir",
    Designer_Common_Apply: "Terapkan",
    Designer_Common_Cancel: "Batal",
    Designer_Settings_TabBasics: "Dasar",
    Designer_Settings_FormTitle: "Judul formulir",
    Designer_Settings_Description: "Deskripsi",
    Designer_Settings_Layout: "Tata letak",
    Designer_Settings_NumberQuestions: "Beri nomor pada pertanyaan",
    Designer_Settings_ShuffleQuestions: "Acak urutan pertanyaan untuk setiap responden",
    Designer_Settings_ShowProgressBar: "Tampilkan bilah kemajuan",
    Designer_Settings_TabAppearance: "Tampilan",
    Designer_Settings_AccentColor: "Warna aksen",
    Designer_Settings_CustomColorTitle: "Warna kustom",
    Designer_Settings_CustomColorAria: "Warna aksen kustom",
    Designer_Settings_AccentHint: "Warna aksen disesuaikan secara otomatis untuk kontras di situs gelap, sehingga formulir tetap terbaca apa pun tema yang digunakan halaman.",
    Designer_Settings_ShowHeader: "Tampilkan header formulir",
    Designer_Settings_HeaderIcon: "Ikon header",
    Designer_Settings_TabAfterSubmit: "Setelah dikirim",
    Designer_Settings_SubmitButtonText: "Teks tombol kirim",
    Designer_Settings_SubmitPlaceholder: "Kirim",
    Designer_Settings_ThankYouTitle: "Judul ucapan terima kasih",
    Designer_Settings_ThankYouPlaceholder: "Terima kasih!",
    Designer_Settings_ThankYouMessage: "Pesan ucapan terima kasih",
    Designer_Settings_ShowSubmitAnother: "Tampilkan tombol \"Kirim tanggapan lain\"",
    Designer_Settings_TabNotifications: "Notifikasi",
    Designer_Settings_EmailEachResponseTo: "Kirim setiap tanggapan melalui email ke",
    Designer_Settings_EmailPlaceholder: "nama@perusahaan.com; tim@perusahaan.com",
    Designer_Settings_EmailDescription: "Orang-orang di organisasi Anda menerima setiap tanggapan melalui email, beserta tautan ke item daftar",
    Designer_Settings_RespondentReceipt: "Kirim email salinan jawaban kepada responden",
    Designer_Settings_NotificationsInfo: "Notifikasi menggunakan layanan email bawaan SharePoint, sehingga penerima harus pengguna di organisasi Anda. Alamat eksternal akan dihapus tanpa pemberitahuan.",
    Designer_Settings_TabAccess: "Akses",
    Designer_Settings_OpenFrom: "Buka mulai",
    Designer_Settings_OpenImmediately: "Buka segera",
    Designer_Settings_CloseAfter: "Tutup setelah",
    Designer_Settings_NeverClose: "Jangan pernah tutup",
    Designer_Settings_ClearDates: "Hapus tanggal",
    Designer_Settings_DatesInverted: "Tanggal penutupan sama dengan atau sebelum tanggal pembukaan, sehingga formulir tidak akan pernah menerima tanggapan.",
    Designer_Settings_MaxResponses: "Berhenti setelah tanggapan sebanyak ini",
    Designer_Settings_NoLimit: "Tanpa batas",
    Designer_Settings_OneResponsePerPerson: "Hanya izinkan satu tanggapan per orang",
    Designer_Settings_AllowSaveDraft: "Izinkan responden menyimpan draf dan menyelesaikannya nanti",
    Designer_Settings_ClosedMessage: "Pesan yang ditampilkan saat formulir ditutup",
    Designer_Settings_ClosedMessagePlaceholder: "Formulir ini tidak lagi menerima tanggapan.",
    Designer_Settings_AccessInfo: "Batasan ini diberlakukan oleh formulir, bukan oleh SharePoint. Siapa pun yang memiliki izin untuk menambahkan item ke daftar tanggapan tetap dapat menambahkannya langsung melalui daftar.",
    Designer_Field_StyleInfo: "Info (aksen)",
    Designer_Field_StyleSuccess: "Berhasil (hijau)",
    Designer_Field_StyleWarning: "Peringatan (kuning tua)",
    Designer_Field_StylePlain: "Teks biasa",
    Designer_Field_StyleDivider: "Garis pemisah",
    Designer_Field_IconStars: "Bintang",
    Designer_Field_IconHearts: "Hati",
    Designer_Field_IconThumbs: "Jempol",
    Designer_Field_FormatPlain: "Angka biasa",
    Designer_Field_FormatCurrency: "Mata uang",
    Designer_Field_FormatPercent: "Persentase",
    Designer_Field_UntitledQuestion: "Pertanyaan tanpa judul",
    Designer_Field_DeletedQuestion: "pertanyaan yang dihapus",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} dan {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "ATAU",
    Designer_Rule_JoinAll: "DAN",
    Designer_Rule_Preview: "Ditampilkan saat {conditions}.",
    Designer_Field_Yes: "Ya",
    Designer_Field_No: "Tidak",
    Designer_Field_When: "Saat",
    Designer_Field_SelectValue: "Pilih nilai",
    Designer_Field_DateValuePlaceholder: "YYYY-MM-DD atau \"today\"",
    Designer_Field_ValuePlaceholder: "Nilai",
    Designer_Field_UpperBound: "Batas atas",
    Designer_Field_RemoveCondition: "Hapus kondisi ini",
    Designer_Field_FormulaInvalid: "Rumus ini tidak dapat dihitung. Periksa tanda kurung dan operatornya.",
    Designer_Field_FormulaMissing: "Pertanyaan berikut tidak ada: {names}.",
    Designer_Field_FormulaPreview: "Dengan setiap input bernilai 10, ini menampilkan {value}.",
    Designer_Field_HintYesNo: "Gunakan \"yes\" atau \"no\"",
    Designer_Field_HintMultiDefault: "Pisahkan beberapa nilai default dengan ;",
    Designer_Field_HintSingleDefault: "Harus cocok dengan salah satu opsi",
    Designer_Field_HintDate: "Gunakan \"today\", atau tanggal seperti 2026-03-01",
    Designer_Field_HintTime: "Gunakan \"now\", atau waktu seperti 09:30",
    Designer_Field_QuestionSettings: "Pengaturan pertanyaan",
    Designer_Field_Appearance: "Tampilan",
    Designer_Field_Style: "Gaya",
    Designer_Field_ImageUrl: "URL gambar (opsional)",
    Designer_Field_Content: "Konten",
    Designer_Field_BasicFormatting: "Pemformatan dasar diizinkan: tebal, miring, daftar, dan tautan.",
    Designer_Field_TabOptions: "Opsi",
    Designer_Field_TabBranching: "Percabangan",
    Designer_Field_BranchingNeedsQuestion: "Tambahkan pertanyaan lain terlebih dahulu — percabangan memerlukan sesuatu sebagai acuan.",
    Designer_Field_BranchingToggle: "Tampilkan pertanyaan ini hanya jika jawaban lain cocok",
    Designer_Field_Match: "Cocokkan",
    Designer_Field_MatchAll: "semua ini",
    Designer_Field_MatchAny: "salah satu ini",
    Designer_Field_AddCondition: "Tambah kondisi",
    Designer_Field_TabValidation: "Validasi",
    Designer_Field_HelpText: "Teks bantuan",
    Designer_Field_HelpTextPlaceholder: "Ditampilkan di bawah label pertanyaan",
    Designer_Field_CheckboxLabel: "Label kotak centang",
    Designer_Field_Placeholder: "Placeholder",
    Designer_Field_DefaultAnswer: "Jawaban default",
    Designer_Field_RequiredMessage: "Pesan wajib diisi kustom",
    Designer_Field_RequiredMessagePlaceholder: "{title} wajib diisi",
    Designer_Field_ThisQuestion: "Pertanyaan ini",
    Designer_Field_RequiredMessageDescription: "Ditampilkan sebagai pengganti pesan standar saat pertanyaan ini dikosongkan",
    Designer_Field_ReadOnly: "Hanya baca (jawaban hanya bisa berasal dari tautan yang telah diisi sebelumnya)",
    Designer_Field_ValidationRules: "Aturan validasi",
    Designer_Field_MaxLength: "Panjang maksimum",
    Designer_Field_Pattern: "Harus cocok dengan pola ini",
    Designer_Field_PatternDescription: "Ekspresi reguler. Biarkan kosong jika tidak perlu pemeriksaan pola.",
    Designer_Field_PatternMessage: "Pesan saat pola tidak cocok",
    Designer_Field_PatternMessagePlaceholder: "Jawaban ini tidak sesuai format yang diharapkan",
    Designer_Field_Format: "Format",
    Designer_Field_UnitSuffix: "Satuan yang ditampilkan setelah nilai",
    Designer_Field_UnitSuffixPlaceholder: "kg, jam, item…",
    Designer_Field_Minimum: "Minimum",
    Designer_Field_Maximum: "Maksimum",
    Designer_Field_Decimals: "Desimal",
    Designer_Field_Formula: "Rumus",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Rujuk pertanyaan lain dengan teksnya di dalam kurung kurawal. Mendukung + - * / ( ) serta round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Pertanyaan yang tersedia: {questions}",
    Designer_Field_NoneYet: "belum ada",
    Designer_Field_Step: "Langkah",
    Designer_Field_From: "Dari",
    Designer_Field_To: "Sampai",
    Designer_Field_LowLabel: "Label di ujung bawah",
    Designer_Field_LowLabelPlaceholder: "Sangat tidak mungkin",
    Designer_Field_HighLabel: "Label di ujung atas",
    Designer_Field_HighLabelPlaceholder: "Sangat mungkin",
    Designer_Field_SummarizeAs: "Ringkas sebagai",
    Designer_Field_SummarizeAverage: "Rata-rata dan distribusi",
    Designer_Field_SummarizeNps: "Net Promoter Score (memerlukan skala 0–10)",
    Designer_Field_NpsWarning: "Net Promoter Score hanya bermakna pada skala 0–10. Setel Dari ke 0 dan Sampai ke 10.",
    Designer_Field_NumberOfIcons: "Jumlah ikon",
    Designer_Field_Icon: "Ikon",
    Designer_Field_AllowHalf: "Izinkan nilai setengah",
    Designer_Field_ShowOptionsAs: "Tampilkan opsi sebagai",
    Designer_Field_DisplayButtons: "Tombol sebaris",
    Designer_Field_DisplayDropdown: "Dropdown",
    Designer_Field_DisplayAutomatic: "Otomatis (sebaris hingga 6 opsi)",
    Designer_Field_AllowOther: "Tambahkan opsi \"Lainnya\" yang dapat diisi sendiri",
    Designer_Field_OtherLabel: "Label untuk opsi \"Lainnya\"",
    Designer_Field_OtherPlaceholder: "Lainnya",
    Designer_Field_ShuffleOptions: "Acak urutan opsi untuk setiap responden",
    Designer_Field_MinSelections: "Pilihan minimum",
    Designer_Field_MaxSelections: "Pilihan maksimum",
    Designer_Field_SourceList: "Daftar sumber",
    Designer_Field_ChooseList: "Pilih daftar",
    Designer_Field_LookupColumn: "Kolom sumber opsi",
    Designer_Field_ChooseColumn: "Pilih kolom",
    Designer_Field_ChooseListFirst: "Pilih daftar terlebih dahulu",
    Designer_Field_LookupFilter: "Filter (opsional)",
    Designer_Field_LookupFilterDescription: "Filter OData yang mempersempit item sumber mana yang menjadi opsi",
    Designer_Field_LookupInfo: "Jawaban menyimpan teks opsi, bukan tautan ke item sumber, sehingga tanggapan tetap terbaca meskipun daftar sumber berubah di kemudian hari.",
    Designer_Field_ConsentText: "Ketentuan yang ditampilkan di atas kotak centang",
    Designer_Field_AllowMultiplePeople: "Izinkan beberapa orang",
    Designer_Field_AllowGroups: "Izinkan grup juga",
    Designer_Field_IncludeTime: "Sertakan waktu",
    Designer_Field_TimeStep: "Interval waktu (menit)",
    Designer_Field_MaxFiles: "Jumlah file maksimum",
    Designer_Field_MaxFileSize: "Ukuran maks. masing-masing (MB)",
    Designer_Field_AcceptedTypes: "Jenis file yang diterima",
    Designer_Field_AcceptedTypesDescription: "Ekstensi dipisahkan koma. Biarkan kosong untuk menerima semua yang diizinkan SharePoint.",
    Designer_Field_FilesInfo: "File disimpan sebagai lampiran pada item tanggapan. SharePoint memblokir beberapa ekstensi (seperti .exe) terlepas dari apa yang Anda izinkan di sini.",
    Designer_Field_Rows: "Baris",
    Designer_Field_ProvisionedNote: "Pertanyaan ini sudah memiliki kolom daftar ({name}). Pengaturan yang mengubah jenis kolom dikunci — duplikasi pertanyaan jika Anda memerlukan jenis yang berbeda.",
    Designer_Category_Text: "Teks",
    Designer_Category_Choice: "Pilihan",
    Designer_Category_Scales: "Skala",
    Designer_Category_Date: "Tanggal",
    Designer_Category_People: "Orang",
    Designer_Category_Advanced: "Lanjutan",
    Designer_Category_Layout: "Tata letak",
    Designer_Menu_CommonPresets: "Preset umum",
    Designer_Menu_AllTypes: "Semua jenis pertanyaan",
    Designer_Menu_ChangeType: "Ubah jenis",
    Designer_Menu_TypeLockedTitle: "Kolom daftar sudah ada, sehingga jenisnya dikunci. Duplikasi pertanyaan untuk mengubahnya.",
    Designer_Menu_MoreSettings: "Percabangan, validasi, dan lainnya",
    Designer_Menu_InsertBelow: "Sisipkan pertanyaan di bawah",
    Designer_Card_Duplicate: "Duplikasi",
    Designer_Card_DeleteQuestion: "Hapus pertanyaan",
    Designer_Outline_Aria: "Kerangka pertanyaan",
    Designer_Outline_QuestionCountOne: "{count} pertanyaan",
    Designer_Outline_QuestionCountOther: "{count} pertanyaan",
    Designer_Outline_IssuesTitle: "{count} masalah untuk ditinjau",
    Designer_Outline_Find: "Cari pertanyaan",
    Designer_Outline_Empty: "Belum ada pertanyaan.",
    Designer_Section_DefaultTitle: "Bagian {number}",
    Designer_Card_Question: "Pertanyaan",
    Designer_Card_BranchingTitle: "Pertanyaan ini hanya muncul saat aturan percabangan cocok",
    Designer_Card_BranchingChip: "Percabangan",
    Designer_Card_LiveTitle: "Kolom daftar sudah ada, sehingga jenisnya dikunci",
    Designer_Card_LiveChip: "Aktif",
    Designer_Card_CheckChip: "Periksa",
    Designer_Option_Placeholder: "Opsi {number}",
    Designer_Option_LabelAria: "Label opsi {number}",
    Designer_Option_ImageUrl: "URL gambar",
    Designer_Option_ImageUrlAria: "URL gambar opsi {number}",
    Designer_Option_Remove: "Hapus opsi",
    Designer_Option_RemoveAria: "Hapus opsi {number}",
    Designer_Option_Add: "Tambah opsi",
    Designer_Option_OtherHint: "Responden juga dapat menulis jawaban berlabel “{label}”.",
    Designer_Option_OtherFallback: "Lainnya",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Hapus",
    Designer_Grid_RemoveAria: "Hapus {label} {number}",
    Designer_Grid_Statements: "Pernyataan",
    Designer_Grid_Scale: "Skala",
    Designer_Grid_AddStatement: "Tambah pernyataan",
    Designer_Grid_AddScale: "Tambah skala",
    Designer_Width_Full: "Lebar penuh",
    Designer_Width_Half: "Setengah lebar",
    Designer_Width_Third: "Sepertiga lebar",
    Designer_Width_Aria: "Lebar pertanyaan",
    Designer_Card_BlockLabelPlaceholder: "Label blok (tidak ditampilkan kepada responden)",
    Designer_Card_QuestionText: "Teks pertanyaan",
    Designer_Card_MoveUp: "Pindah ke atas",
    Designer_Card_MoveQuestionUp: "Pindahkan pertanyaan ke atas",
    Designer_Card_MoveDown: "Pindah ke bawah",
    Designer_Card_MoveQuestionDown: "Pindahkan pertanyaan ke bawah",
    Designer_Card_DuplicateQuestion: "Duplikasi pertanyaan",
    Designer_Card_MultipleAnswers: "Beberapa jawaban",
    Designer_Card_Required: "Wajib diisi",
    Designer_Card_MoreOptions: "Opsi lainnya",
    Designer_Card_MoreOptionsAria: "Opsi lainnya untuk pertanyaan ini",
    Designer_Canvas_FormTitle: "Judul formulir",
    Designer_Canvas_DescriptionPlaceholder: "Tambahkan deskripsi (opsional)",
    Designer_Canvas_DescriptionAria: "Deskripsi formulir",
    Designer_Canvas_EmptyTitle: "Tambahkan pertanyaan pertama Anda",
    Designer_Canvas_EmptyBody: "Pilih jenis pertanyaan untuk memulai. Anda dapat mengurutkan ulang pertanyaan dengan menyeretnya, dan menambahkan percabangan agar orang hanya melihat yang relevan bagi mereka.",
    Designer_Section_Chip: "Bagian {number} dari {total}",
    Designer_Section_TitlePlaceholder: "Judul bagian",
    Designer_Section_TitleAria: "Judul bagian {number}",
    Designer_Section_DescriptionPlaceholder: "Deskripsi (opsional)",
    Designer_Section_DescriptionAria: "Deskripsi bagian {number}",
    Designer_Section_MoveUp: "Pindahkan bagian ke atas",
    Designer_Section_MoveDown: "Pindahkan bagian ke bawah",
    Designer_Section_Delete: "Hapus bagian",
    Designer_Card_DragToReorder: "Seret untuk mengurutkan ulang",
    Designer_Card_ReorderAria: "Urutkan ulang {title}",
    Designer_Card_ReorderFallback: "pertanyaan",
    Designer_Canvas_AddNew: "Tambah baru",
    Designer_Canvas_AddSection: "Tambah bagian",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Alamat jalan",
    Form_Address_Street2Placeholder: "Apartemen, suite, dll. (opsional)",
    Form_Address_CityPlaceholder: "Kota",
    Form_Address_StatePlaceholder: "Provinsi / kabupaten",
    Form_Address_PostalCodePlaceholder: "Kode pos",
    Form_Address_CountryPlaceholder: "Negara",
    Form_Address_StreetAria: "alamat jalan",
    Form_Address_Street2Aria: "baris alamat 2",
    Form_Address_CityAria: "kota",
    Form_Address_StateAria: "provinsi atau kabupaten",
    Form_Address_PostalCodeAria: "kode pos",
    Form_Address_CountryAria: "negara",
    Form_Consent_DefaultLabel: "Saya setuju",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered} dari {total} baris terjawab",
    Form_Lookup_LoadError: "Opsi untuk pertanyaan ini tidak dapat dimuat.",
    Form_Lookup_Loading: "Memuat opsi…",
    Form_Lookup_SelectOptionsPlaceholder: "Pilih opsi",
    Form_Lookup_SelectOptionPlaceholder: "Pilih satu opsi",
    Form_Person_Placeholder: "Mulai ketik nama…",
    Form_Person_SuggestedPeopleAndGroups: "Orang dan grup yang disarankan",
    Form_Person_SuggestedPeople: "Orang yang disarankan",
    Form_Person_NoPeopleOrGroups: "Tidak ada orang atau grup yang ditemukan",
    Form_Person_NoPeople: "Tidak ada orang yang ditemukan",
    Form_Person_Searching: "Mencari…",
    Form_Ranking_Moved: "{item} dipindahkan ke posisi {position} dari {total}",
    Form_Ranking_MoveUp: "Pindah ke atas",
    Form_Ranking_MoveDown: "Pindah ke bawah",
    Form_Ranking_MoveItemUpAria: "Pindahkan {item} ke atas",
    Form_Ranking_MoveItemDownAria: "Pindahkan {item} ke bawah",
    Form_Rating_ValueText: "{value} dari {max}",
    Form_Rating_NotRated: "Belum dinilai",
    Form_Rating_Clear: "Hapus penilaian",
    Form_RichText_Bold: "Tebal",
    Form_RichText_Italic: "Miring",
    Form_RichText_Underline: "Garis bawah",
    Form_RichText_BulletedList: "Daftar berpoin",
    Form_RichText_NumberedList: "Daftar bernomor",
    Form_RichText_ClearFormatting: "Hapus pemformatan",
    Form_RichText_ToolbarAria: "Pemformatan teks",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\" dilewati — batasnya adalah {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" bukan jenis yang diterima.",
    Form_File_TooLarge: "\"{name}\" lebih besar dari {size} MB.",
    Form_File_AlreadyAttached: "\"{name}\" sudah dilampirkan.",
    Form_File_ReadError: "Salah satu file tidak dapat dibaca. Coba lampirkan lagi.",
    Form_File_HintMaxSize: "hingga {size} MB masing-masing",
    Form_File_HintOneFile: "1 file",
    Form_File_HintMaxFiles: "maks. {count} file",
    Form_File_Reading: "Membaca file…",
    Form_File_DropPrompt: "Letakkan file di sini, atau klik untuk menelusuri",
    Form_File_Remove: "Hapus {name}",
    Form_Signature_Alt: "Tanda tangan",
    Form_Signature_AriaSigned: "{label} — sudah ditandatangani",
    Form_Signature_AriaEmpty: "{label} — kosong",
    Form_Signature_Clear: "Hapus",
    Form_Signature_Signed: "Sudah ditandatangani",
    Form_Signature_Prompt: "Tanda tangani di atas menggunakan mouse, pena, atau jari",
    Form_Time_Placeholder: "Pilih waktu",
    Form_Field_DatePlaceholder: "Pilih tanggal",
    Form_Field_TimeAriaWithLabel: "{label} — waktu",
    Form_Field_TimeAria: "Waktu",
    Form_Field_OtherDefault: "Lainnya",
    Form_Field_SelectOptionsPlaceholder: "Pilih opsi",
    Form_Field_PleaseSpecify: "Harap sebutkan",
    Form_Field_OtherSpecifyAria: "{label} — harap sebutkan",
    Form_Field_SelectOptionPlaceholder: "Pilih satu opsi",
    Form_Field_Yes: "Ya",
    Form_Field_No: "Tidak",
    Form_Field_SliderHint: "Seret penggeser untuk menjawab",
    Form_Field_WebAddressAriaWithLabel: "{label} — alamat web",
    Form_Field_WebAddressAria: "Alamat web",
    Form_Field_DisplayTextPlaceholder: "Teks tampilan (opsional)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — teks tampilan",
    Form_Field_DisplayTextAria: "Teks tampilan",
    Form_Field_ChooseBetween: "Pilih antara {min} dan {max}",
    Form_Field_ChooseAtLeast: "Pilih minimal {min}",
    Form_Field_ChooseUpTo: "Pilih hingga {max}",
    Form_Field_SelectedCount: "{count} dipilih",
    Form_Field_RequiredAria: "(wajib)",
    Form_Submit_SaveError: "Tanggapan Anda tidak dapat disimpan. Pastikan formulir telah dipublikasikan dari desainer dan Anda memiliki izin untuk menambahkan item ke daftar tanggapan.",
    Form_Empty_Message: "Formulir ini belum memiliki pertanyaan. Pemilik formulir dapat menambahkannya di tab Pertanyaan.",
    Form_Checking: "Memeriksa formulir…",
    Form_Closed_NotYetOpen: "Belum dibuka",
    Form_Closed_AlreadyAnswered: "Sudah dijawab",
    Form_Closed_Title: "Formulir ditutup",
    Form_Confirmation_PreviewNotice: "Ini hanya pratinjau — tidak ada yang disimpan ke daftar tanggapan.",
    Form_Confirmation_PreviewAgain: "Pratinjau lagi",
    Form_Confirmation_SubmitAnother: "Kirim tanggapan lain",
    Form_Wizard_StepFallback: "Langkah {step}",
    Form_Wizard_StepsAria: "Langkah formulir",
    Form_Wizard_StepOf: "Langkah {step} dari {total}",
    Form_ErrorSummary_Title: "Harap periksa {count} jawaban:",
    Form_ErrorSummary_UntitledQuestion: "Pertanyaan tanpa judul",
    Form_ErrorSummary_Question: "Pertanyaan",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Kembali",
    Form_Nav_Next: "Berikutnya",
    Form_Draft_Saving: "Menyimpan…",
    Form_Draft_Saved: "Draf disimpan",
    Form_Draft_SaveAndFinishLater: "Simpan dan selesaikan nanti",
    Form_Draft_NotSaved: "Draf tidak disimpan",
    Form_Submit_Preview: "Kirim (pratinjau)",
    Form_Submit_Button: "Kirim",
    Form_Response_NoAnswer: "Tidak ada jawaban",
    Form_Signature_TypeLabel: "Ketik nama lengkap Anda",
    Form_Signature_TypeInstead: "Ketik nama Anda saja",
    Form_Signature_DrawInstead: "Gambar saja",
    Form_Edit_Button: "Edit tanggapan Anda sebelumnya",
    Form_Edit_Available: "Anda sudah mengirim tanggapan. Anda dapat mengeditnya alih-alih mengirim yang baru.",
    Form_Edit_Banner: "Anda sedang mengedit tanggapan sebelumnya.",
    Form_Edit_Save: "Perbarui tanggapan",
    Form_Edit_UpdatedTitle: "Tanggapan diperbarui",
    Form_Edit_UpdatedMessage: "Perubahan Anda telah disimpan.",
    Form_Edit_LoadError: "Tanggapan Anda sebelumnya tidak dapat dimuat. Silakan coba lagi.",
    Form_Draft_MissingFiles: "Harap lampirkan ulang: {names}. File ini tidak dapat dipulihkan.",
    Form_Attachments_Failed: "Jawaban Anda telah disimpan, tetapi lampiran ini tidak dapat diunggah: {names}. Silakan coba lagi atau hubungi pemilik formulir.",
    Logic_ThisQuestion: "Pertanyaan ini",
    Logic_Required: "{label} wajib diisi",
    Logic_RequiredConsent: "Centang kotak untuk melanjutkan",
    Logic_RequiredFile: "Harap lampirkan setidaknya satu file",
    Logic_RequiredSignature: "Harap tambahkan tanda tangan Anda",
    Logic_RequiredLikert: "Harap jawab setiap baris",
    Logic_InvalidEmail: "Masukkan alamat email yang valid",
    Logic_InvalidPhone: "Masukkan nomor telepon yang valid",
    Logic_InvalidUrl: "Masukkan alamat web yang valid dan diawali http:// atau https://",
    Logic_MinValue: "Nilai minimal {value}",
    Logic_MaxValue: "Nilai maksimal {value}",
    Logic_MaxLength: "Panjang maksimal adalah {max} karakter",
    Logic_ChooseAtLeastOne: "Pilih setidaknya {count} opsi",
    Logic_ChooseAtLeastMany: "Pilih setidaknya {count} opsi",
    Logic_ChooseAtMostOne: "Pilih paling banyak {count} opsi",
    Logic_ChooseAtMostMany: "Pilih paling banyak {count} opsi",
    Logic_LikertRemaining: "Harap jawab setiap baris (sisa {count})",
    Logic_MaxFilesOne: "Lampirkan paling banyak {count} file",
    Logic_MaxFilesMany: "Lampirkan paling banyak {count} file",
    Logic_FileTooLarge: "\"{name}\" lebih besar dari {size} MB",
    Logic_FileTypeNotAccepted: "\"{name}\" bukan jenis file yang diterima ({types})",
    Logic_AddressRequired: "Masukkan setidaknya jalan dan kota",
    Logic_PatternDefault: "Jawaban ini tidak sesuai format yang diharapkan",
    Logic_Yes: "Ya",
    Logic_No: "Tidak",
    Logic_Agreed: "Setuju",
    Logic_NotAgreed: "Tidak setuju",
    Logic_Signed: "Ditandatangani",
    Logic_NoAnswer: "(tidak ada jawaban)",
    Logic_Unknown: "(tidak diketahui)",
    Logic_OtherSlice: "Lainnya ({count})",
    Logic_CsvResponseId: "ID tanggapan",
    Logic_CsvSubmitted: "Dikirim",
    Logic_CsvSubmittedBy: "Dikirim oleh",
    Logic_EmailQuestion: "Pertanyaan",
    Logic_EmailViewItem: "Lihat di Microsoft Lists",
    Logic_EmailFooter: "Dikirim otomatis oleh Smart Forms.",
    Logic_ClosedDefault: "Formulir ini tidak lagi menerima tanggapan.",
    Logic_NotYetOpen: "Formulir ini dibuka pada {date}.",
    Logic_AlreadyResponded: "Anda sudah menanggapi formulir ini. Terima kasih!",
    Logic_UntitledQuestion: "Pertanyaan tanpa judul",
    Logic_Issue_NoQuestions: "Tambahkan setidaknya satu pertanyaan sebelum mengumpulkan tanggapan.",
    Logic_Issue_NoTitle: "Ada pertanyaan tanpa teks — pertanyaan itu akan diberi nama otomatis saat Anda memublikasikan.",
    Logic_Issue_DuplicateTitle: "{label} memiliki teks yang sama dengan pertanyaan lain sehingga hasil lebih sulit dibaca.",
    Logic_Issue_NeedTwoOptions: "{label} memerlukan setidaknya dua opsi.",
    Logic_Issue_ImageNoImage: "{label} memiliki opsi tanpa gambar — opsi itu akan tampil sebagai kotak teks.",
    Logic_Issue_LikertNeedRow: "{label} memerlukan setidaknya satu baris.",
    Logic_Issue_LikertNeedColumns: "{label} memerlukan setidaknya dua kolom skala.",
    Logic_Issue_NoLookupList: "{label} belum memiliki daftar sumber yang dipilih.",
    Logic_Issue_NoFormula: "{label} tidak memiliki rumus.",
    Logic_Issue_BadFormula: "{label} memiliki rumus yang tidak dapat dihitung. Periksa tanda kurung dan operatornya.",
    Logic_Issue_MissingRefs: "{label} merujuk ke pertanyaan yang tidak ada: {names}.",
    Logic_Issue_BadPattern: "{label} memiliki pola validasi yang tidak valid.",
    Logic_Issue_BrokenRule: "{label} memiliki aturan percabangan yang mengarah ke pertanyaan yang telah dihapus.",
    Logic_Issue_SelfRule: "{label} memiliki aturan percabangan yang merujuk ke dirinya sendiri.",
    Logic_Issue_RuleMismatch: "{label} memiliki aturan percabangan yang tidak lagi sesuai dengan pertanyaan yang menjadi acuannya.",
    Logic_Issue_RequiredReadOnly: "{label} wajib diisi sekaligus hanya-baca, sehingga hanya dapat dijawab melalui tautan yang sudah terisi.",
    Logic_Issue_EmptySection: "Ada bagian tanpa pertanyaan dan akan dilewati.",
    Logic_Issue_CloseBeforeOpen: "Tanggal penutupan sama dengan atau sebelum tanggal pembukaan, sehingga formulir tidak akan pernah menerima tanggapan.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Email persetujuan diaktifkan tetapi langkah persetujuan dinonaktifkan.",
    Logic_Op_equals: "adalah",
    Logic_Op_notEquals: "bukan",
    Logic_Op_contains: "berisi",
    Logic_Op_notContains: "tidak berisi",
    Logic_Op_notEmpty: "dijawab",
    Logic_Op_empty: "tidak dijawab",
    Logic_Op_greaterThan: "lebih besar dari",
    Logic_Op_greaterOrEqual: "minimal",
    Logic_Op_lessThan: "kurang dari",
    Logic_Op_lessOrEqual: "maksimal",
    Logic_Op_between: "di antara",
    Logic_Op_before: "sebelum",
    Logic_Op_after: "setelah",
    Logic_Type_Text: "Jawaban singkat",
    Logic_TypeDesc_Text: "Satu baris teks",
    Logic_Category_Text: "Teks",
    Logic_Type_MultilineText: "Jawaban panjang",
    Logic_TypeDesc_MultilineText: "Beberapa baris teks biasa",
    Logic_Type_RichText: "Teks berformat",
    Logic_TypeDesc_RichText: "Tebal, daftar, dan tautan",
    Logic_Type_Choice: "Pilihan",
    Logic_TypeDesc_Choice: "Pilih dari daftar opsi",
    Logic_Category_Choice: "Pilihan",
    Logic_Type_ImageChoice: "Pilihan gambar",
    Logic_TypeDesc_ImageChoice: "Pilih dari kotak gambar",
    Logic_Type_Lookup: "Lookup dari daftar",
    Logic_TypeDesc_Lookup: "Opsi dibaca langsung dari daftar SharePoint lain",
    Logic_Type_YesNo: "Ya / Tidak",
    Logic_TypeDesc_YesNo: "Sakelar hidup/mati sederhana",
    Logic_Type_Consent: "Persetujuan",
    Logic_TypeDesc_Consent: "Kotak centang yang harus dicentang responden untuk melanjutkan",
    Logic_Type_Ranking: "Peringkat",
    Logic_TypeDesc_Ranking: "Seret opsi ke urutan preferensi",
    Logic_Type_Rating: "Rating",
    Logic_TypeDesc_Rating: "Bintang, hati, atau jempol",
    Logic_Category_Scales: "Skala",
    Logic_Type_Scale: "Skala opini",
    Logic_TypeDesc_Scale: "Skala bernomor dengan ujung berlabel",
    Logic_Type_Slider: "Penggeser",
    Logic_TypeDesc_Slider: "Nilai pada skala geser",
    Logic_Type_Likert: "Kisi Likert",
    Logic_TypeDesc_Likert: "Nilai beberapa pernyataan pada satu skala bersama",
    Logic_Type_Number: "Angka",
    Logic_TypeDesc_Number: "Biasa, mata uang, atau persentase",
    Logic_Category_Advanced: "Lanjutan",
    Logic_Type_Calculated: "Terhitung",
    Logic_TypeDesc_Calculated: "Total hanya-baca yang dihitung dari jawaban lain",
    Logic_Type_Date: "Tanggal",
    Logic_TypeDesc_Date: "Tanggal kalender, opsional dengan waktu",
    Logic_Category_Date: "Tanggal",
    Logic_Type_Time: "Waktu",
    Logic_TypeDesc_Time: "Hanya waktu dalam sehari",
    Logic_Type_Person: "Orang",
    Logic_TypeDesc_Person: "Pilih seseorang dari organisasi",
    Logic_Category_People: "Orang",
    Logic_Type_Email: "Email",
    Logic_TypeDesc_Email: "Alamat email yang divalidasi",
    Logic_Type_Phone: "Telepon",
    Logic_TypeDesc_Phone: "Nomor telepon yang divalidasi",
    Logic_Type_Address: "Alamat",
    Logic_TypeDesc_Address: "Jalan, kota, kode pos, dan negara",
    Logic_Type_Hyperlink: "Tautan",
    Logic_TypeDesc_Hyperlink: "Alamat web",
    Logic_Type_FileUpload: "Unggah file",
    Logic_TypeDesc_FileUpload: "Lampirkan satu file atau lebih pada tanggapan",
    Logic_Type_Signature: "Tanda tangan",
    Logic_TypeDesc_Signature: "Tanda tangan dengan mouse, pena, atau jari",
    Logic_Type_Content: "Blok teks",
    Logic_TypeDesc_Content: "Petunjuk atau gambar — tidak mengumpulkan jawaban",
    Logic_Category_Layout: "Tata letak",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Seberapa besar kemungkinan Anda merekomendasikan…",
    Logic_Preset_satisfaction: "Kepuasan (1–5)",
    Logic_PresetDesc_satisfaction: "Sangat tidak puas hingga sangat puas",
    Logic_Preset_currency: "Mata uang",
    Logic_PresetDesc_currency: "Jumlah uang",
    Logic_Preset_percent: "Persentase",
    Logic_PresetDesc_percent: "Nilai persentase",
    Logic_Template_blank_Name: "Formulir kosong",
    Logic_Template_blank_Description: "Mulai dari awal",
    Logic_Template_feedback_Name: "Umpan balik pelanggan",
    Logic_Template_feedback_Description: "NPS, rating, dan komentar terbuka",
    Logic_Template_event_Name: "Pendaftaran acara",
    Logic_Template_event_Description: "Detail peserta, sesi, dan kebutuhan diet",
    Logic_Template_itrequest_Name: "Permintaan layanan IT",
    Logic_Template_itrequest_Description: "Permintaan terkategori dengan prioritas dan lampiran",
    Logic_Template_expense_Name: "Klaim biaya",
    Logic_Template_expense_Description: "Item baris, kwitansi, dan total terhitung",
    Logic_Template_pulse_Name: "Survei denyut karyawan",
    Logic_Template_pulse_Description: "Kisi Likert, skala keterlibatan, dan catatan anonimitas",
    Logic_Template_safety_Name: "Inspeksi keselamatan",
    Logic_Template_safety_Description: "Daftar periksa, foto, dan tanda tangan",
    Logic_Template_booking_Name: "Pemesanan ruangan atau sumber daya",
    Logic_Template_booking_Description: "Pemilih sumber daya berbasis lookup dengan slot waktu",
    Charts_ColumnChartAria: "Diagram kolom dengan {count} kategori",
    Charts_DonutChartAria: "Diagram donat dari {count} kategori",
    Charts_NoAnswers: "Belum ada jawaban.",
    Charts_NoResponses: "Belum ada tanggapan.",
    Charts_Responses: "Tanggapan",
    Charts_ResponsesOverTime: "Tanggapan dari waktu ke waktu",
    Responses_Chart_Answer: "Jawaban",
    Responses_Chart_Average: "Rata-rata",
    Responses_Chart_AverageOf: "Rata-rata dari {count}",
    Responses_Chart_AveragePosition: "Posisi rata-rata",
    Responses_Chart_AverageRange: "Rata-rata (1–{max})",
    Responses_Chart_AvgValue: "rata-rata {value}",
    Responses_Chart_Detractors: "Detraktor (0–6)",
    Responses_Chart_Max: "Maks",
    Responses_Chart_Maximum: "Maksimum",
    Responses_Chart_Median: "Median",
    Responses_Chart_MentionOne: "{count} sebutan",
    Responses_Chart_MentionOther: "{count} sebutan",
    Responses_Chart_Min: "Min",
    Responses_Chart_Minimum: "Minimum",
    Responses_Chart_NoAnswers: "Belum ada jawaban.",
    Responses_Chart_NoNumeric: "Belum ada jawaban numerik.",
    Responses_Chart_NoRankings: "Belum ada peringkat.",
    Responses_Chart_NoScores: "Belum ada skor.",
    Responses_Chart_NotEnoughText: "Belum cukup teks untuk diringkas.",
    Responses_Chart_NpsScore: "Skor NPS",
    Responses_Chart_Option: "Opsi",
    Responses_Chart_Passives: "Pasif (7–8)",
    Responses_Chart_Promoters: "Promotor (9–10)",
    Responses_Chart_ResponseOne: "tanggapan",
    Responses_Chart_ResponseOther: "tanggapan",
    Responses_Chart_Responses: "Tanggapan",
    Responses_Chart_ShowingAnswers: "Menampilkan {shown} dari {total} jawaban.",
    Responses_Chart_Statement: "Pernyataan",
    Responses_Chart_Statistic: "Statistik",
    Responses_Chart_StdDev: "Simpangan baku",
    Responses_Chart_StdDeviation: "Simpangan baku",
    Responses_Chart_Total: "Total",
    Responses_Chart_Value: "Nilai",
    Responses_Dashboard_AllHidden: "Semua pertanyaan disembunyikan dari dasbor. Gunakan “Tampilkan pertanyaan tersembunyi” untuk memunculkannya kembali.",
    Responses_Dashboard_AnsweredOf: "{answered} dari {total} terjawab",
    Responses_Dashboard_AnsweredOfPinned: "{answered} dari {total} terjawab · disematkan",
    Responses_Dashboard_AveragedAcrossResponses: "Rata-rata dari semua tanggapan",
    Responses_Dashboard_ByDay: "Per hari",
    Responses_Dashboard_ByMonth: "Per bulan",
    Responses_Dashboard_ByWeek: "Per minggu",
    Responses_Dashboard_ChartAuto: "Otomatis",
    Responses_Dashboard_ChartBars: "Batang",
    Responses_Dashboard_ChartColumns: "Kolom",
    Responses_Dashboard_ChartDonut: "Donat",
    Responses_Dashboard_ChartGauge: "Pengukur",
    Responses_Dashboard_ChartHistogram: "Histogram",
    Responses_Dashboard_ChartOptions: "Opsi diagram",
    Responses_Dashboard_ChartOptionsFor: "Opsi diagram untuk {title}",
    Responses_Dashboard_ChartStatistics: "Statistik",
    Responses_Dashboard_ChartTable: "Tabel",
    Responses_Dashboard_ChartWordFrequency: "Frekuensi kata",
    Responses_Dashboard_EmptyBody: "Setelah orang mulai menjawab, dasbor ini terisi secara otomatis — angka utama, linimasa tanggapan, dan diagram untuk pertanyaan yang layak dipantau.",
    Responses_Dashboard_EmptyTitle: "Belum ada tanggapan",
    Responses_Dashboard_Hide: "Sembunyikan dari dasbor",
    Responses_Dashboard_Highlights: "Sorotan",
    Responses_Dashboard_Last7Days: "7 hari terakhir",
    Responses_Dashboard_LatestDate: "Terbaru {date}",
    Responses_Dashboard_MedianTimeToComplete: "Median waktu penyelesaian",
    Responses_Dashboard_NoPriorWeek: "Tidak ada minggu sebelumnya untuk dibandingkan",
    Responses_Dashboard_OneEach: "Masing-masing satu",
    Responses_Dashboard_Pin: "Sematkan ke dasbor",
    Responses_Dashboard_QuestionFallback: "pertanyaan",
    Responses_Dashboard_QuestionsAnswered: "Pertanyaan terjawab",
    Responses_Dashboard_RecordedOnSubmit: "Dicatat saat dikirim",
    Responses_Dashboard_RepeatResponses: "{count} tanggapan berulang",
    Responses_Dashboard_ResponsesOverTime: "Tanggapan dari waktu ke waktu",
    Responses_Dashboard_ShowHidden: "Tampilkan pertanyaan tersembunyi",
    Responses_Dashboard_SinceMidnight: "Sejak tengah malam",
    Responses_Dashboard_Today: "Hari ini",
    Responses_Dashboard_TotalResponses: "Total tanggapan",
    Responses_Dashboard_UniqueRespondents: "Responden unik",
    Responses_Dashboard_Unpin: "Lepas sematan dari dasbor",
    Responses_Dashboard_UntitledQuestion: "Pertanyaan tanpa judul",
    Responses_Dashboard_VsPrevious7Days: "dibandingkan 7 hari sebelumnya",
    Responses_Detail_Answers: "Jawaban",
    Responses_Detail_AsTheForm: "Seperti di formulir",
    Responses_Detail_Cancel: "Batal",
    Responses_Detail_Delete: "Hapus",
    Responses_Detail_DeleteBody: "Item daftar dipindahkan ke keranjang sampah situs, sehingga dapat dipulihkan dari sana.",
    Responses_Detail_DeleteTitle: "Hapus tanggapan ini?",
    Responses_Detail_Deleting: "Menghapus…",
    Responses_Detail_Draft: "Draf",
    Responses_Detail_Header: "Tanggapan {index} dari {total}",
    Responses_Detail_LoadingAttachments: "Memuat lampiran…",
    Responses_Detail_Next: "Tanggapan berikutnya",
    Responses_Detail_NoAnswer: "Tidak ada jawaban",
    Responses_Detail_Previous: "Tanggapan sebelumnya",
    Responses_Detail_Print: "Cetak",
    Responses_Detail_Signature: "Tanda tangan",
    Responses_Detail_Signed: "Sudah ditandatangani",
    Responses_Detail_Took: "memakan waktu {duration}",
    Responses_Summary_AnsweredOfType: "{answered} dari {total} terjawab · {type}",
    Responses_Summary_ByField: "Menurut {title}",
    Responses_Summary_CompareBy: "Bandingkan menurut…",
    Responses_Summary_EmptyBody: "Setiap pertanyaan akan mendapatkan ringkasannya sendiri di sini.",
    Responses_Summary_NoComparison: "Tanpa perbandingan",
    Responses_Summary_NothingToCompare: "Tidak ada tanggapan yang menjawab “{title}”, jadi tidak ada yang bisa dibandingkan.",
    Responses_Summary_OtherNote: "Diagram dengan lebih dari {max} kategori mengelompokkan yang terkecil ke dalam “Lainnya” — ubah kartu ke Tabel untuk melihat setiap nilai.",
    Responses_Summary_ResponseCountOne: "{count} tanggapan",
    Responses_Summary_ResponseCountOther: "{count} tanggapan",
    Responses_Summary_SeeAllAnswers: "Lihat semua jawaban di tabel",
    Responses_Summary_SegmentNote: "Menampilkan {groups} grup terbesar. Tanggapan yang memilih beberapa jawaban muncul di setiap grup yang cocok, sehingga total grup bisa melebihi {total}.",
    Responses_Summary_SplitBy: "Pisahkan menurut {title}",
    Responses_Summary_Untitled: "tanpa judul",
    Responses_Table_Apply: "Terapkan",
    Responses_Table_Cancel: "Batal",
    Responses_Table_ClearSelection: "Hapus pilihan",
    Responses_Table_ColumnOrder: "Urutan kolom",
    Responses_Table_ColumnsCount: "Kolom ({shown}/{total})",
    Responses_Table_Delete: "Hapus",
    Responses_Table_DeleteBody: "Item daftar dipindahkan ke keranjang sampah situs, sehingga dapat dipulihkan dari sana.",
    Responses_Table_DeleteSelected: "Hapus yang dipilih",
    Responses_Table_DeleteTitleOne: "Hapus {count} tanggapan?",
    Responses_Table_DeleteTitleOther: "Hapus {count} tanggapan?",
    Responses_Table_Deleting: "Menghapus…",
    Responses_Table_MoveDown: "Pindah ke bawah",
    Responses_Table_MoveDownFor: "Pindahkan {title} ke bawah",
    Responses_Table_MoveUp: "Pindah ke atas",
    Responses_Table_MoveUpFor: "Pindahkan {title} ke atas",
    Responses_Table_NoColumns: "Belum ada kolom pertanyaan yang terlihat.",
    Responses_Table_NoMatch: "Tidak ada tanggapan yang cocok dengan filter saat ini.",
    Responses_Table_NothingToShow: "Tidak ada yang ditampilkan",
    Responses_Table_OpenResponse: "Buka tanggapan ini",
    Responses_Table_OrderNote: "Dikirim dan Dikirim oleh selalu berada di urutan pertama. Urutan seret berlaku untuk kolom pertanyaan.",
    Responses_Table_Reorder: "Urutkan ulang",
    Responses_Table_ResetColumns: "Reset kolom",
    Responses_Table_SelectResponse: "Pilih tanggapan ini",
    Responses_Table_SelectedOne: "{count} tanggapan dipilih",
    Responses_Table_SelectedOther: "{count} tanggapan dipilih",
    Responses_Table_ShowAll: "Tampilkan semua",
    Responses_Table_ShowTheseQuestions: "Tampilkan pertanyaan ini",
    Responses_Table_Submitted: "Dikirim",
    Responses_Table_SubmittedBy: "Dikirim oleh",
    Responses_Table_ToggleSelection: "Alihkan pilihan",
    Responses_Table_Unknown: "Tidak diketahui",
    Responses_Table_Untitled: "Tanpa judul",
    Responses_View_AllTime: "Sepanjang waktu",
    Responses_View_AnyAnswer: "Jawaban apa pun",
    Responses_View_Clear: "Hapus",
    Responses_View_CopyShareLink: "Salin tautan berbagi",
    Responses_View_CountFiltered: "{shown} dari {total} tanggapan",
    Responses_View_CountOne: "{count} tanggapan",
    Responses_View_CountOther: "{count} tanggapan",
    Responses_View_Dashboard: "Dasbor",
    Responses_View_DateRange: "Rentang tanggal",
    Responses_View_EmptyBody: "Bagikan formulir untuk mulai mengumpulkan. Jawaban disimpan ke “{list}” dan langsung muncul di sini.",
    Responses_View_EmptyTitle: "Belum ada tanggapan",
    Responses_View_ExportCsv: "Ekspor CSV",
    Responses_View_FilterByAnswer: "Filter menurut jawaban",
    Responses_View_FilterByQuestion: "Filter menurut pertanyaan",
    Responses_View_FilterValue: "Nilai filter",
    Responses_View_Last30Days: "30 hari terakhir",
    Responses_View_Last7Days: "7 hari terakhir",
    Responses_View_Last90Days: "90 hari terakhir",
    Responses_View_LoadError: "Tanggapan tidak dapat dimuat. Publikasikan formulir sekali agar kolom daftar tersedia, lalu coba lagi.",
    Responses_View_Loading: "Memuat tanggapan…",
    Responses_View_MoreActions: "Tindakan tanggapan lainnya",
    Responses_View_PreviewForm: "Pratinjau formulir",
    Responses_View_Refresh: "Segarkan",
    Responses_View_ResponsesTab: "Tanggapan ({count})",
    Responses_View_SearchPlaceholder: "Cari di semua jawaban",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Pilih nilai",
    Responses_View_Summary: "Ringkasan",
    Responses_View_Today: "Hari ini",
    Responses_View_Truncated: "Daftar ini memiliki lebih banyak tanggapan daripada yang dapat dimuat Smart Forms sekaligus. {count} terbaru ditampilkan — buka daftar di Microsoft Lists untuk melihat seluruhnya.",
    Responses_View_TryAgain: "Coba lagi",
    Responses_View_Untitled: "Tanpa judul",
    Responses_Approval_Column: "Persetujuan",
    Responses_Approval_ReviewerColumn: "Ditinjau oleh",
    Responses_Approval_CommentColumn: "Komentar peninjau",
    Responses_Approval_Pending: "Menunggu",
    Responses_Approval_Approved: "Disetujui",
    Responses_Approval_Rejected: "Ditolak",
    Responses_Approval_AnyStatus: "Semua status persetujuan",
    Responses_Approval_FilterLabel: "Filter menurut status persetujuan",
    Responses_Approval_ApproveSelected: "Setujui yang dipilih",
    Responses_Approval_RejectSelected: "Tolak yang dipilih",
    Responses_Approval_BulkFailed: "{count} tanggapan tidak dapat diperbarui. Coba lagi.",
    Responses_Approval_Approve: "Setujui",
    Responses_Approval_Reject: "Tolak",
    Responses_Approval_Reset: "Setel ulang ke menunggu",
    Responses_Approval_CommentLabel: "Komentar (opsional)",
    Responses_Approval_ReviewedBy: "Ditinjau oleh {name}",
    Responses_Approval_Error: "Keputusan tidak dapat disimpan. Coba lagi.",
    Responses_Dashboard_ApprovalStatus: "Menunggu peninjauan",
    Responses_Dashboard_ApprovalBreakdown: "{pending} menunggu, {approved} disetujui, {rejected} ditolak",
    Responses_Dashboard_TimelineCoarsened: "Rentang tanggal panjang, sehingga linimasa dikelompokkan lebih kasar ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Rentang tanggal sangat panjang, sehingga hanya {count} periode terbaru yang ditampilkan.",
    Service_Item_DefaultTitle: "Tanggapan — {date}",
    Service_Email_ApprovalSubject: "Tanggapan Anda {status} — {title}",
    Service_Email_ApprovalHeading: "Tanggapan Anda {status}",
    Service_Email_ApprovalIntro: "Seorang peninjau menandai tanggapan Anda untuk \"{title}\" sebagai {status}.",
    Service_Email_ApprovalCommentLabel: "Komentar peninjau",
    Service_Approval_Approved: "disetujui",
    Service_Approval_Rejected: "ditolak",
    Service_Approval_Pending: "menunggu",
    Service_Lookup_InvalidFilter: "Filter lookup tidak valid.",
    Service_Edit_NotAllowed: "Formulir ini tidak mengizinkan pengeditan tanggapan yang sudah dikirim.",
    Service_Edit_NotYours: "Anda hanya dapat mengedit tanggapan Anda sendiri.",
    Service_Signature_AttachmentLabel: "Tanda tangan",
    PropertyPane_ListsLoadFailed: "Daftar di situs ini tidak dapat dimuat.",
    PropertyPane_EnterListName: "Masukkan nama untuk daftar baru terlebih dahulu.",
    PropertyPane_CreatingList: "Membuat \"{name}\"…",
    PropertyPane_ListCreated: "Daftar \"{title}\" dibuat dan dipilih.",
    PropertyPane_ListAlreadyExists: "Daftar bernama \"{name}\" sudah ada — pilih dari dropdown di atas.",
    PropertyPane_CreateListFailed: "Tidak dapat membuat daftar. Pastikan Anda memiliki izin untuk membuat daftar di situs ini.",
    PropertyPane_Description: "Pilih daftar SharePoint yang menyimpan tanggapan formulir, atau buat yang baru. Semua yang lain — pertanyaan, tampilan, notifikasi — diedit langsung di halaman.",
    PropertyPane_ResponseList_GroupName: "Daftar tanggapan",
    PropertyPane_ListDropdown_Label: "Simpan tanggapan ke daftar ini",
    PropertyPane_ResponsesGoTo: "Tanggapan disimpan ke \"{name}\".",
    PropertyPane_PickList: "Pilih daftar, atau buat di bawah.",
    PropertyPane_LoadingLists: "Memuat daftar…",
    PropertyPane_NewListName_Label: "Atau buat daftar baru",
    PropertyPane_NewListName_Placeholder: "Nama daftar baru",
    PropertyPane_CreateList_Button: "Buat daftar",
    PropertyPane_Tips_GroupName: "Tips",
    PropertyPane_Tip_AutoSave: "Pertanyaan dan pengaturan disimpan otomatis saat Anda mengeditnya — tidak perlu menyimpan atau memublikasikan halaman.",
    PropertyPane_Tip_Permissions: "Responden memerlukan izin untuk menambahkan item ke daftar tanggapan. Periksa izin daftar jika seseorang melaporkan kesalahan saat mengirim.",
    PropertyPane_Tip_Share: "Gunakan \"Kumpulkan tanggapan\" di halaman untuk membuat kolom daftar dan mendapatkan tautan pengisian yang dapat dibagikan.",
    App_ErrorBoundary_Title: "Smart Forms — Kesalahan Render",
    App_ErrorBoundary_Message: "Pesan:",
    App_ErrorBoundary_Stack: "Tumpukan:",
    App_ErrorBoundary_NoStack: "(tumpukan tidak tersedia)",
    App_ErrorBoundary_ConsoleNote: "Detail lengkap juga ditulis ke konsol browser.",
    App_DefaultQuestionTitle: "Pertanyaan {number}",
    App_Error_ListMissing: "Daftar yang dikonfigurasi untuk formulir ini sudah tidak ada. Pilih daftar lain di pengaturan web part.",
    App_Error_LoadConfig: "Terjadi kesalahan saat memuat konfigurasi formulir.",
    App_Error_Unable: "Tidak dapat memuat formulir.",
    App_Publish_ConflictNotice: "\"{title}\" sudah memiliki kolom daftar dengan jenis berbeda ({type}). Ganti nama pertanyaan agar kolom baru dapat dibuat, atau kembalikan jenisnya.",
    App_Publish_ConflictUnnamedQuestion: "sebuah pertanyaan",
    App_Publish_ColumnsAddedOne: "{count} kolom ditambahkan ke \"{list}\".",
    App_Publish_ColumnsAddedOther: "{count} kolom ditambahkan ke \"{list}\".",
    App_Publish_TheList: "daftar",
    App_Publish_UpToDate: "Daftar tanggapan sudah mutakhir.",
    App_Publish_Error: "Kolom daftar tidak dapat dibuat. Ini biasanya berarti Anda tidak memiliki izin Manage Lists pada daftar tanggapan, tetapi juga bisa terjadi di situs dengan skrip kustom dinonaktifkan. Periksa konsol browser untuk kesalahan yang mendasarinya, atau coba lagi.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Buat formulir yang menarik di atas daftar SharePoint — {count} jenis pertanyaan, logika percabangan, unggah file, tautan pengisian yang dapat dibagikan, dan dasbor hasil.",
    App_Placeholder_ChooseList: "Pilih atau buat daftar",
    App_Placeholder_Hint: "Edit halaman dan konfigurasikan web part ini untuk memulai.",
    App_Loading: "Memuat formulir…",
    App_OpenSettings: "Buka pengaturan",
    App_Tab_Questions: "Pertanyaan",
    App_Tab_QuestionsWithCount: "Pertanyaan ({count})",
    App_Tab_Responses: "Tanggapan",
    App_Tab_Responses_Title: "Tanggapan disimpan ke \"{list}\"",
    App_Templates_Start: "Mulai dari templat",
    App_Settings_Title: "Pengaturan formulir — tampilan, notifikasi, akses",
    App_Settings_AriaLabel: "Pengaturan formulir",
    App_Preview: "Pratinjau",
    App_Preview_Close: "Tutup pratinjau",
    App_Preview_Hint: "Pratinjau — apa pun yang Anda kirim di sini tidak disimpan. Validasi dan percabangan berperilaku persis seperti untuk responden.",
    App_Publish_GettingReady: "Menyiapkan…",
    App_Publish_CollectResponses: "Kumpulkan tanggapan",
    App_Publish_Share: "Bagikan",
    App_Retry: "Coba lagi",
    App_SaveError_Banner: "Perubahan terakhir Anda tidak dapat disimpan. Periksa koneksi Anda, lalu coba lagi.",
    App_Preflight_BlockingTitle: "Perbaiki ini sebelum mengumpulkan",
    App_Preflight_WarningTitle: "Layak diperiksa dahulu",
    App_Preflight_BlockingText: "Ini akan menghambat formulir yang dipublikasikan agar tidak berfungsi dengan baik.",
    App_Preflight_WarningText: "Tidak ada yang rusak, tetapi biasanya sebaiknya ini diperbaiki sebelum Anda membagikan tautan.",
    App_Preflight_GoTo: "Buka",
    App_Preflight_CollectAnyway: "Tetap kumpulkan tanggapan",
    App_Preflight_Back: "Kembali ke formulir",
    App_Cancel: "Batal",
    App_Done: "Selesai",
    App_Share_Title: "Formulir Anda siap dibagikan",
    App_Share_SubText: "Kirim tautan ini kepada siapa pun yang perlu mengisi formulir.",
    App_Share_LinkAriaLabel: "Tautan berbagi",
    App_Share_Copy: "Salin",
    App_Share_Copied: "Disalin",
    App_Share_AddItemsEmphasis: "menambahkan item",
    App_Share_PermissionNote: "Responden memerlukan izin untuk {addItems} ke “{title}”, serta akses ke halaman ini. Jika seseorang mendapat kesalahan saat mengirim, hampir selalu itu penyebabnya.",
    App_Share_PrefillNote: "Anda dapat menjawab pertanyaan lebih dulu di tautan dengan menambahkan nama kolom, misalnya {example}.",
    App_Templates_ReplaceWarning: "Memilih templat akan menggantikan pertanyaan yang ada saat ini.",
    App_Templates_PickStart: "Pilih titik awal — Anda dapat mengubah apa pun setelahnya.",
    App_Templates_Empty: "Kosong",
    App_Templates_QuestionCount: "{count} pertanyaan",
    App_SaveChip_SavingTitle: "Menyimpan hasil edit terbaru Anda",
    App_SaveChip_Saving: "Menyimpan…",
    App_SaveChip_FailedTitle: "Hasil edit terakhir Anda tidak dapat disimpan. Periksa koneksi Anda dan coba lagi.",
    App_SaveChip_Failed: "Gagal menyimpan",
    App_SaveChip_SavedTitle: "Semua perubahan tersimpan",
    App_SaveChip_Saved: "Tersimpan",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Tanggapan baru — {title}",
    Service_Email_NewResponseHeading: "Tanggapan baru: {title}",
    Service_Email_NewResponseIntro: "Seseorang baru saja mengirim tanggapan — {date}.",
    Service_Email_ReceiptSubject: "Tanggapan Anda — {title}",
    Service_Email_ReceiptHeading: "Terima kasih atas tanggapan Anda!",
    Service_Email_ReceiptIntro: "Berikut salinan yang Anda kirim ke \"{title}\".",
    App_History_Title: "Riwayat versi",
    App_History_RestoredNotice: "Versi yang disimpan pada {date} dipulihkan. Tinjau, lalu gunakan Kumpulkan tanggapan untuk memublikasikan pertanyaan baru.",
    App_History_Undo: "Urungkan pemulihan",
    App_Share_CopyManual: "Browser Anda memblokir penyalinan. Pilih tautan di atas lalu tekan Ctrl+C (Cmd+C di Mac) untuk menyalinnya.",
    App_Share_TeamsNote: "Anda berada di Microsoft Teams. Tautan ini langsung membuka halaman SharePoint, sehingga penerima memerlukan akses ke situs.",
    App_Share_PrefillNotSecure: "Jawaban yang sudah terisi hanyalah kemudahan: siapa pun yang memiliki tautan dapat mengubahnya, jadi jangan pernah menganggapnya sebagai batas keamanan.",
    Designer_Section_DropHere: "Letakkan pertanyaan di sini",
    Designer_Section_DropEnd: "Letakkan di sini untuk memindahkan ke akhir bagian ini",
    Designer_Rules_RemovedOne: "1 aturan percabangan yang tidak lagi sesuai telah dihapus.",
    Designer_Rules_RemovedOther: "{count} aturan percabangan yang tidak lagi sesuai telah dihapus.",
    Designer_Settings_AllowEdit: "Izinkan responden mengedit tanggapan mereka",
    Designer_Settings_AllowEditHint: "Responden dapat membuka kembali dan memperbarui apa yang telah dikirim. Setiap orang hanya dapat mengedit tanggapannya sendiri.",
    Designer_Settings_EnableApproval: "Aktifkan alur kerja persetujuan",
    Designer_Settings_ApprovalNotify: "Kirim email ke responden saat ada keputusan",
    Designer_Settings_ApprovalHint: "Menambahkan kolom persetujuan ke daftar tanggapan saat Anda memublikasikan berikutnya. Pemilik menyetujui atau menolak tanggapan dari tab Tanggapan.",
    Designer_History_Title: "Riwayat versi",
    Designer_History_Intro: "Versi tersimpan sebelumnya dari pertanyaan dan pengaturan formulir ini. Memulihkan akan memuat versi ke desainer; Anda dapat mengurungkannya, dan pertanyaan baru hanya dibuat saat Anda memublikasikan.",
    Designer_History_Loading: "Memuat versi...",
    Designer_History_Empty: "Tidak ada versi sebelumnya. Riwayat versi memerlukan pembuatan versi yang diaktifkan untuk daftar \"Smart Forms Config\" dan setidaknya satu suntingan tersimpan.",
    Designer_History_Latest: "Terbaru",
    Designer_History_LatestTitle: "Ini adalah versi yang sedang digunakan",
    Designer_History_By: "oleh {name}",
    Designer_History_UnknownAuthor: "Penulis tidak dikenal",
    Designer_History_VersionLabel: "versi {label}",
    Designer_History_Preview: "Pratinjau",
    Designer_History_Restore: "Pulihkan",
    Designer_History_QuestionsOne: "1 pertanyaan",
    Designer_History_QuestionsOther: "{count} pertanyaan",
    Designer_History_LoadFailed: "Versi ini tidak dapat dimuat.",
    Designer_History_ConfirmTitle: "Pulihkan versi ini?",
    Designer_History_ConfirmText: "Formulir akan diganti dengan versi yang disimpan pada {date} ({count} pertanyaan). Anda dapat mengurungkannya segera setelahnya."
  };
});
