define([], function () {
  return {
    Designer_Color_Blue: "Blu",
    Designer_Color_Teal: "Verde acqua",
    Designer_Color_Green: "Verde",
    Designer_Color_Purple: "Viola",
    Designer_Color_Magenta: "Magenta",
    Designer_Color_Red: "Rosso",
    Designer_Color_Orange: "Arancione",
    Designer_Color_Gray: "Grigio",
    Designer_Settings_LayoutSinglePage: "Tutte le domande in una pagina",
    Designer_Settings_LayoutWizard: "Una sezione per passaggio (procedura guidata)",
    Designer_Settings_Title: "Impostazioni modulo",
    Designer_Common_Apply: "Applica",
    Designer_Common_Cancel: "Annulla",
    Designer_Settings_TabBasics: "Generale",
    Designer_Settings_FormTitle: "Titolo del modulo",
    Designer_Settings_Description: "Descrizione",
    Designer_Settings_Layout: "Layout",
    Designer_Settings_NumberQuestions: "Numera le domande",
    Designer_Settings_ShuffleQuestions: "Mescola l'ordine delle domande per ogni partecipante",
    Designer_Settings_ShowProgressBar: "Mostra una barra di avanzamento",
    Designer_Settings_TabAppearance: "Aspetto",
    Designer_Settings_AccentColor: "Colore di risalto",
    Designer_Settings_CustomColorTitle: "Colore personalizzato",
    Designer_Settings_CustomColorAria: "Colore di risalto personalizzato",
    Designer_Settings_AccentHint: "I colori di risalto vengono regolati automaticamente per il contrasto nei siti scuri, così il modulo resta leggibile con qualsiasi tema della pagina.",
    Designer_Settings_ShowHeader: "Mostra l'intestazione del modulo",
    Designer_Settings_HeaderIcon: "Icona dell'intestazione",
    Designer_Settings_TabAfterSubmit: "Dopo l'invio",
    Designer_Settings_SubmitButtonText: "Testo del pulsante Invia",
    Designer_Settings_SubmitPlaceholder: "Invia",
    Designer_Settings_ThankYouTitle: "Titolo di ringraziamento",
    Designer_Settings_ThankYouPlaceholder: "Grazie!",
    Designer_Settings_ThankYouMessage: "Messaggio di ringraziamento",
    Designer_Settings_ShowSubmitAnother: "Mostra un pulsante \"Invia un'altra risposta\"",
    Designer_Settings_TabNotifications: "Notifiche",
    Designer_Settings_EmailEachResponseTo: "Invia ogni risposta via e-mail a",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "Le persone della tua organizzazione ricevono ogni risposta via e-mail, con un collegamento all'elemento dell'elenco",
    Designer_Settings_RespondentReceipt: "Invia ai partecipanti una copia delle loro risposte via e-mail",
    Designer_Settings_NotificationsInfo: "Le notifiche usano il servizio di posta di SharePoint, quindi i destinatari devono essere utenti della tua organizzazione. Gli indirizzi esterni vengono scartati senza avviso.",
    Designer_Settings_TabAccess: "Accesso",
    Designer_Settings_OpenFrom: "Apri da",
    Designer_Settings_OpenImmediately: "Apri subito",
    Designer_Settings_CloseAfter: "Chiudi dopo",
    Designer_Settings_NeverClose: "Non chiudere mai",
    Designer_Settings_ClearDates: "Cancella date",
    Designer_Settings_DatesInverted: "La data di chiusura coincide con o precede la data di apertura, quindi il modulo non accetterebbe mai risposte.",
    Designer_Settings_MaxResponses: "Interrompi dopo questo numero di risposte",
    Designer_Settings_NoLimit: "Nessun limite",
    Designer_Settings_OneResponsePerPerson: "Consenti una sola risposta per persona",
    Designer_Settings_AllowSaveDraft: "Consenti ai partecipanti di salvare una bozza e completare in seguito",
    Designer_Settings_ClosedMessage: "Messaggio mostrato quando il modulo è chiuso",
    Designer_Settings_ClosedMessagePlaceholder: "Questo modulo non accetta più risposte.",
    Designer_Settings_AccessInfo: "Questi limiti sono applicati dal modulo, non da SharePoint. Chiunque abbia l'autorizzazione ad aggiungere elementi all'elenco delle risposte potrebbe comunque aggiungerne uno direttamente dall'elenco.",
    Designer_Field_StyleInfo: "Informazione (risalto)",
    Designer_Field_StyleSuccess: "Operazione riuscita (verde)",
    Designer_Field_StyleWarning: "Avviso (ambra)",
    Designer_Field_StylePlain: "Testo normale",
    Designer_Field_StyleDivider: "Linea di separazione",
    Designer_Field_IconStars: "Stelle",
    Designer_Field_IconHearts: "Cuori",
    Designer_Field_IconThumbs: "Mi piace",
    Designer_Field_FormatPlain: "Numero semplice",
    Designer_Field_FormatCurrency: "Valuta",
    Designer_Field_FormatPercent: "Percentuale",
    Designer_Field_UntitledQuestion: "Domanda senza titolo",
    Designer_Field_DeletedQuestion: "una domanda eliminata",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} e {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "OPPURE",
    Designer_Rule_JoinAll: "E",
    Designer_Rule_Preview: "Mostrata quando {conditions}.",
    Designer_Field_Yes: "Sì",
    Designer_Field_No: "No",
    Designer_Field_When: "Quando",
    Designer_Field_SelectValue: "Seleziona un valore",
    Designer_Field_DateValuePlaceholder: "AAAA-MM-GG o \"today\"",
    Designer_Field_ValuePlaceholder: "Valore",
    Designer_Field_UpperBound: "Limite superiore",
    Designer_Field_RemoveCondition: "Rimuovi questa condizione",
    Designer_Field_FormulaInvalid: "Impossibile calcolare questa formula. Controlla le parentesi e gli operatori.",
    Designer_Field_FormulaMissing: "Queste domande non esistono: {names}.",
    Designer_Field_FormulaPreview: "Con ogni input pari a 10, viene mostrato {value}.",
    Designer_Field_HintYesNo: "Usa \"yes\" o \"no\"",
    Designer_Field_HintMultiDefault: "Separa più valori predefiniti con ;",
    Designer_Field_HintSingleDefault: "Deve corrispondere a una delle opzioni",
    Designer_Field_HintDate: "Usa \"today\" o una data come 2026-03-01",
    Designer_Field_HintTime: "Usa \"now\" o un'ora come 09:30",
    Designer_Field_QuestionSettings: "Impostazioni domanda",
    Designer_Field_Appearance: "Aspetto",
    Designer_Field_Style: "Stile",
    Designer_Field_ImageUrl: "URL immagine (facoltativo)",
    Designer_Field_Content: "Contenuto",
    Designer_Field_BasicFormatting: "È consentita la formattazione di base: grassetto, corsivo, elenchi e collegamenti.",
    Designer_Field_TabOptions: "Opzioni",
    Designer_Field_TabBranching: "Ramificazione",
    Designer_Field_BranchingNeedsQuestion: "Aggiungi prima un'altra domanda: la ramificazione richiede un elemento da cui dipendere.",
    Designer_Field_BranchingToggle: "Mostra questa domanda solo se le altre risposte corrispondono",
    Designer_Field_Match: "Corrispondenza con",
    Designer_Field_MatchAll: "tutte queste",
    Designer_Field_MatchAny: "almeno una di queste",
    Designer_Field_AddCondition: "Aggiungi condizione",
    Designer_Field_TabValidation: "Convalida",
    Designer_Field_HelpText: "Testo della Guida",
    Designer_Field_HelpTextPlaceholder: "Mostrato sotto l'etichetta della domanda",
    Designer_Field_CheckboxLabel: "Etichetta della casella di controllo",
    Designer_Field_Placeholder: "Segnaposto",
    Designer_Field_DefaultAnswer: "Risposta predefinita",
    Designer_Field_RequiredMessage: "Messaggio personalizzato per campo obbligatorio",
    Designer_Field_RequiredMessagePlaceholder: "{title} è obbligatorio",
    Designer_Field_ThisQuestion: "Questa domanda",
    Designer_Field_RequiredMessageDescription: "Mostrato al posto del messaggio standard quando questa domanda viene lasciata vuota",
    Designer_Field_ReadOnly: "Sola lettura (la risposta può provenire solo da un collegamento precompilato)",
    Designer_Field_ValidationRules: "Regole di convalida",
    Designer_Field_MaxLength: "Lunghezza massima",
    Designer_Field_Pattern: "Deve corrispondere a questo criterio",
    Designer_Field_PatternDescription: "Un'espressione regolare. Lascia vuoto per non controllare alcun criterio.",
    Designer_Field_PatternMessage: "Messaggio quando il criterio non corrisponde",
    Designer_Field_PatternMessagePlaceholder: "Questa risposta non è nel formato previsto",
    Designer_Field_Format: "Formato",
    Designer_Field_UnitSuffix: "Unità mostrata dopo il valore",
    Designer_Field_UnitSuffixPlaceholder: "kg, ore, elementi…",
    Designer_Field_Minimum: "Minimo",
    Designer_Field_Maximum: "Massimo",
    Designer_Field_Decimals: "Decimali",
    Designer_Field_Formula: "Formula",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Fai riferimento ad altre domande usando il loro testo tra parentesi graffe. Supporta + - * / ( ) e round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Domande disponibili: {questions}",
    Designer_Field_NoneYet: "nessuna al momento",
    Designer_Field_Step: "Incremento",
    Designer_Field_From: "Da",
    Designer_Field_To: "A",
    Designer_Field_LowLabel: "Etichetta per il valore minimo",
    Designer_Field_LowLabelPlaceholder: "Per niente probabile",
    Designer_Field_HighLabel: "Etichetta per il valore massimo",
    Designer_Field_HighLabelPlaceholder: "Estremamente probabile",
    Designer_Field_SummarizeAs: "Riepiloga come",
    Designer_Field_SummarizeAverage: "Media e distribuzione",
    Designer_Field_SummarizeNps: "Net Promoter Score (richiede una scala 0–10)",
    Designer_Field_NpsWarning: "Il Net Promoter Score ha senso solo su una scala 0–10. Imposta Da su 0 e A su 10.",
    Designer_Field_NumberOfIcons: "Numero di icone",
    Designer_Field_Icon: "Icona",
    Designer_Field_AllowHalf: "Consenti mezzi valori",
    Designer_Field_ShowOptionsAs: "Mostra le opzioni come",
    Designer_Field_DisplayButtons: "Pulsanti in linea",
    Designer_Field_DisplayDropdown: "Elenco a discesa",
    Designer_Field_DisplayAutomatic: "Automatico (in linea fino a 6 opzioni)",
    Designer_Field_AllowOther: "Aggiungi un'opzione \"Altro\" con testo libero",
    Designer_Field_OtherLabel: "Etichetta per l'opzione \"Altro\"",
    Designer_Field_OtherPlaceholder: "Altro",
    Designer_Field_ShuffleOptions: "Mescola l'ordine delle opzioni per ogni partecipante",
    Designer_Field_MinSelections: "Selezioni minime",
    Designer_Field_MaxSelections: "Selezioni massime",
    Designer_Field_SourceList: "Elenco di origine",
    Designer_Field_ChooseList: "Scegli un elenco",
    Designer_Field_LookupColumn: "Colonna da cui leggere le opzioni",
    Designer_Field_ChooseColumn: "Scegli una colonna",
    Designer_Field_ChooseListFirst: "Scegli prima un elenco",
    Designer_Field_LookupFilter: "Filtro (facoltativo)",
    Designer_Field_LookupFilterDescription: "Un filtro OData che limita quali elementi di origine diventano opzioni",
    Designer_Field_LookupInfo: "Le risposte memorizzano il testo dell'opzione, non un collegamento all'elemento di origine, quindi le risposte restano leggibili anche se l'elenco di origine cambia in seguito.",
    Designer_Field_ConsentText: "Termini mostrati sopra la casella di controllo",
    Designer_Field_AllowMultiplePeople: "Consenti più persone",
    Designer_Field_AllowGroups: "Consenti anche i gruppi",
    Designer_Field_IncludeTime: "Includi l'ora del giorno",
    Designer_Field_TimeStep: "Intervallo orario (minuti)",
    Designer_Field_MaxFiles: "Numero massimo di file",
    Designer_Field_MaxFileSize: "Dimensione massima per file (MB)",
    Designer_Field_AcceptedTypes: "Tipi di file accettati",
    Designer_Field_AcceptedTypesDescription: "Estensioni separate da virgole. Lascia vuoto per accettare tutto ciò che SharePoint consente.",
    Designer_Field_FilesInfo: "I file vengono salvati come allegati dell'elemento di risposta. SharePoint blocca alcune estensioni (ad esempio .exe) indipendentemente da ciò che consenti qui.",
    Designer_Field_Rows: "Righe",
    Designer_Field_ProvisionedNote: "Questa domanda ha già una colonna nell'elenco ({name}). Le impostazioni che modificano il tipo della colonna sono bloccate: duplica la domanda se ti serve un tipo diverso.",
    Designer_Category_Text: "Testo",
    Designer_Category_Choice: "Scelta",
    Designer_Category_Scales: "Scale",
    Designer_Category_Date: "Data",
    Designer_Category_People: "Persone",
    Designer_Category_Advanced: "Avanzate",
    Designer_Category_Layout: "Layout",
    Designer_Menu_CommonPresets: "Predefiniti comuni",
    Designer_Menu_AllTypes: "Tutti i tipi di domanda",
    Designer_Menu_ChangeType: "Cambia tipo",
    Designer_Menu_TypeLockedTitle: "La colonna dell'elenco esiste già, quindi il tipo è bloccato. Duplica la domanda per cambiarlo.",
    Designer_Menu_MoreSettings: "Ramificazione, convalida e altro",
    Designer_Menu_InsertBelow: "Inserisci domanda sotto",
    Designer_Card_Duplicate: "Duplica",
    Designer_Card_DeleteQuestion: "Elimina domanda",
    Designer_Outline_Aria: "Struttura delle domande",
    Designer_Outline_QuestionCountOne: "{count} domanda",
    Designer_Outline_QuestionCountOther: "{count} domande",
    Designer_Outline_IssuesTitle: "{count} problema/i da verificare",
    Designer_Outline_Find: "Trova una domanda",
    Designer_Outline_Empty: "Ancora nessuna domanda.",
    Designer_Section_DefaultTitle: "Sezione {number}",
    Designer_Card_Question: "Domanda",
    Designer_Card_BranchingTitle: "Questa domanda compare solo quando una regola di ramificazione corrisponde",
    Designer_Card_BranchingChip: "Ramificazione",
    Designer_Card_LiveTitle: "La colonna dell'elenco esiste, quindi il tipo è bloccato",
    Designer_Card_LiveChip: "Attiva",
    Designer_Card_CheckChip: "Verifica",
    Designer_Option_Placeholder: "Opzione {number}",
    Designer_Option_LabelAria: "Etichetta dell'opzione {number}",
    Designer_Option_ImageUrl: "URL immagine",
    Designer_Option_ImageUrlAria: "URL immagine dell'opzione {number}",
    Designer_Option_Remove: "Rimuovi opzione",
    Designer_Option_RemoveAria: "Rimuovi opzione {number}",
    Designer_Option_Add: "Aggiungi opzione",
    Designer_Option_OtherHint: "I partecipanti possono anche scrivere una risposta con l'etichetta “{label}”.",
    Designer_Option_OtherFallback: "Altro",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Rimuovi",
    Designer_Grid_RemoveAria: "Rimuovi {label} {number}",
    Designer_Grid_Statements: "Affermazioni",
    Designer_Grid_Scale: "Scala",
    Designer_Grid_AddStatement: "Aggiungi affermazione",
    Designer_Grid_AddScale: "Aggiungi scala",
    Designer_Width_Full: "Larghezza intera",
    Designer_Width_Half: "Metà larghezza",
    Designer_Width_Third: "Un terzo della larghezza",
    Designer_Width_Aria: "Larghezza della domanda",
    Designer_Card_BlockLabelPlaceholder: "Etichetta del blocco (non mostrata ai partecipanti)",
    Designer_Card_QuestionText: "Testo della domanda",
    Designer_Card_MoveUp: "Sposta su",
    Designer_Card_MoveQuestionUp: "Sposta la domanda su",
    Designer_Card_MoveDown: "Sposta giù",
    Designer_Card_MoveQuestionDown: "Sposta la domanda giù",
    Designer_Card_DuplicateQuestion: "Duplica domanda",
    Designer_Card_MultipleAnswers: "Risposte multiple",
    Designer_Card_Required: "Obbligatoria",
    Designer_Card_MoreOptions: "Altre opzioni",
    Designer_Card_MoreOptionsAria: "Altre opzioni per questa domanda",
    Designer_Canvas_FormTitle: "Titolo del modulo",
    Designer_Canvas_DescriptionPlaceholder: "Aggiungi una descrizione (facoltativo)",
    Designer_Canvas_DescriptionAria: "Descrizione del modulo",
    Designer_Canvas_EmptyTitle: "Aggiungi la prima domanda",
    Designer_Canvas_EmptyBody: "Scegli un tipo di domanda per iniziare. Puoi riordinare le domande trascinandole e aggiungere la ramificazione in modo che le persone vedano solo ciò che le riguarda.",
    Designer_Section_Chip: "Sezione {number} di {total}",
    Designer_Section_TitlePlaceholder: "Titolo della sezione",
    Designer_Section_TitleAria: "Titolo della sezione {number}",
    Designer_Section_DescriptionPlaceholder: "Descrizione (facoltativo)",
    Designer_Section_DescriptionAria: "Descrizione della sezione {number}",
    Designer_Section_MoveUp: "Sposta la sezione su",
    Designer_Section_MoveDown: "Sposta la sezione giù",
    Designer_Section_Delete: "Elimina sezione",
    Designer_Card_DragToReorder: "Trascina per riordinare",
    Designer_Card_ReorderAria: "Riordina {title}",
    Designer_Card_ReorderFallback: "domanda",
    Designer_Canvas_AddNew: "Aggiungi nuovo",
    Designer_Canvas_AddSection: "Aggiungi sezione",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Indirizzo",
    Form_Address_Street2Placeholder: "Interno, scala, ecc. (facoltativo)",
    Form_Address_CityPlaceholder: "Città",
    Form_Address_StatePlaceholder: "Provincia",
    Form_Address_PostalCodePlaceholder: "CAP",
    Form_Address_CountryPlaceholder: "Paese",
    Form_Address_StreetAria: "indirizzo",
    Form_Address_Street2Aria: "seconda riga dell'indirizzo",
    Form_Address_CityAria: "città",
    Form_Address_StateAria: "provincia",
    Form_Address_PostalCodeAria: "CAP",
    Form_Address_CountryAria: "paese",
    Form_Consent_DefaultLabel: "Accetto",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered} righe su {total} completate",
    Form_Lookup_LoadError: "Impossibile caricare le opzioni per questa domanda.",
    Form_Lookup_Loading: "Caricamento delle opzioni…",
    Form_Lookup_SelectOptionsPlaceholder: "Seleziona le opzioni",
    Form_Lookup_SelectOptionPlaceholder: "Seleziona un'opzione",
    Form_Person_Placeholder: "Inizia a digitare un nome…",
    Form_Person_SuggestedPeopleAndGroups: "Persone e gruppi suggeriti",
    Form_Person_SuggestedPeople: "Persone suggerite",
    Form_Person_NoPeopleOrGroups: "Nessuna persona o gruppo trovato",
    Form_Person_NoPeople: "Nessuna persona trovata",
    Form_Person_Searching: "Ricerca in corso…",
    Form_Ranking_Moved: "{item} spostato alla posizione {position} di {total}",
    Form_Ranking_MoveUp: "Sposta su",
    Form_Ranking_MoveDown: "Sposta giù",
    Form_Ranking_MoveItemUpAria: "Sposta {item} su",
    Form_Ranking_MoveItemDownAria: "Sposta {item} giù",
    Form_Rating_ValueText: "{value} su {max}",
    Form_Rating_NotRated: "Non valutato",
    Form_Rating_Clear: "Cancella valutazione",
    Form_RichText_Bold: "Grassetto",
    Form_RichText_Italic: "Corsivo",
    Form_RichText_Underline: "Sottolineato",
    Form_RichText_BulletedList: "Elenco puntato",
    Form_RichText_NumberedList: "Elenco numerato",
    Form_RichText_ClearFormatting: "Cancella formattazione",
    Form_RichText_ToolbarAria: "Formattazione del testo",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\" è stato ignorato: il limite è {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" non è un tipo accettato.",
    Form_File_TooLarge: "\"{name}\" supera {size} MB.",
    Form_File_AlreadyAttached: "\"{name}\" è già allegato.",
    Form_File_ReadError: "Impossibile leggere uno dei file. Prova ad allegarlo di nuovo.",
    Form_File_HintMaxSize: "fino a {size} MB ciascuno",
    Form_File_HintOneFile: "1 file",
    Form_File_HintMaxFiles: "massimo {count} file",
    Form_File_Reading: "Lettura dei file…",
    Form_File_DropPrompt: "Trascina qui i file oppure fai clic per sfogliare",
    Form_File_Remove: "Rimuovi {name}",
    Form_Signature_Alt: "Firma",
    Form_Signature_AriaSigned: "{label} — firmato",
    Form_Signature_AriaEmpty: "{label} — vuoto",
    Form_Signature_Clear: "Cancella",
    Form_Signature_Signed: "Firmato",
    Form_Signature_Prompt: "Firma qui sopra con il mouse, una penna o il dito",
    Form_Time_Placeholder: "Seleziona un'ora",
    Form_Field_DatePlaceholder: "Seleziona una data",
    Form_Field_TimeAriaWithLabel: "{label} — ora",
    Form_Field_TimeAria: "Ora",
    Form_Field_OtherDefault: "Altro",
    Form_Field_SelectOptionsPlaceholder: "Seleziona le opzioni",
    Form_Field_PleaseSpecify: "Specifica",
    Form_Field_OtherSpecifyAria: "{label} — specifica",
    Form_Field_SelectOptionPlaceholder: "Seleziona un'opzione",
    Form_Field_Yes: "Sì",
    Form_Field_No: "No",
    Form_Field_SliderHint: "Trascina il cursore per rispondere",
    Form_Field_WebAddressAriaWithLabel: "{label} — indirizzo Web",
    Form_Field_WebAddressAria: "Indirizzo Web",
    Form_Field_DisplayTextPlaceholder: "Testo visualizzato (facoltativo)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — testo visualizzato",
    Form_Field_DisplayTextAria: "Testo visualizzato",
    Form_Field_ChooseBetween: "Scegli da {min} a {max}",
    Form_Field_ChooseAtLeast: "Scegline almeno {min}",
    Form_Field_ChooseUpTo: "Scegline al massimo {max}",
    Form_Field_SelectedCount: "{count} selezionati",
    Form_Field_RequiredAria: "(obbligatorio)",
    Form_Submit_SaveError: "Impossibile salvare la risposta. Verifica che il modulo sia stato pubblicato dalla finestra di progettazione e di avere l'autorizzazione ad aggiungere elementi all'elenco delle risposte.",
    Form_Empty_Message: "Questo modulo non contiene ancora domande. Il proprietario del modulo può aggiungerle nella scheda Domande.",
    Form_Checking: "Verifica del modulo in corso…",
    Form_Closed_NotYetOpen: "Non ancora aperto",
    Form_Closed_AlreadyAnswered: "Hai già risposto",
    Form_Closed_Title: "Modulo chiuso",
    Form_Confirmation_PreviewNotice: "Questa era un'anteprima: non è stato salvato nulla nell'elenco delle risposte.",
    Form_Confirmation_PreviewAgain: "Anteprima di nuovo",
    Form_Confirmation_SubmitAnother: "Invia un'altra risposta",
    Form_Wizard_StepFallback: "Passaggio {step}",
    Form_Wizard_StepsAria: "Passaggi del modulo",
    Form_Wizard_StepOf: "Passaggio {step} di {total}",
    Form_ErrorSummary_Title: "Controlla {count} risposte:",
    Form_ErrorSummary_UntitledQuestion: "Domanda senza titolo",
    Form_ErrorSummary_Question: "Domanda",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Indietro",
    Form_Nav_Next: "Avanti",
    Form_Draft_Saving: "Salvataggio…",
    Form_Draft_Saved: "Bozza salvata",
    Form_Draft_SaveAndFinishLater: "Salva e completa più tardi",
    Form_Draft_NotSaved: "Bozza non salvata",
    Form_Submit_Preview: "Invia (anteprima)",
    Form_Submit_Button: "Invia",
    Form_Response_NoAnswer: "Nessuna risposta",
    Form_Signature_TypeLabel: "Digita il tuo nome completo",
    Form_Signature_TypeInstead: "Digita il nome",
    Form_Signature_DrawInstead: "Disegna",
    Form_Edit_Button: "Modifica la risposta precedente",
    Form_Edit_Available: "Hai già inviato una risposta. Puoi modificarla invece di inviarne una nuova.",
    Form_Edit_Banner: "Stai modificando la risposta precedente.",
    Form_Edit_Save: "Aggiorna risposta",
    Form_Edit_UpdatedTitle: "Risposta aggiornata",
    Form_Edit_UpdatedMessage: "Le modifiche sono state salvate.",
    Form_Edit_LoadError: "Impossibile caricare la risposta precedente. Riprova.",
    Form_Draft_MissingFiles: "Allega di nuovo: {names}. Impossibile ripristinare questi file.",
    Form_Attachments_Failed: "Le risposte sono state salvate, ma non è stato possibile caricare questi allegati: {names}. Riprova o contatta il proprietario del modulo.",
    Logic_ThisQuestion: "Questa domanda",
    Logic_Required: "{label} è obbligatorio",
    Logic_RequiredConsent: "Seleziona la casella per continuare",
    Logic_RequiredFile: "Allega almeno un file",
    Logic_RequiredSignature: "Aggiungi la tua firma",
    Logic_RequiredLikert: "Rispondi a ogni riga",
    Logic_InvalidEmail: "Inserisci un indirizzo e-mail valido",
    Logic_InvalidPhone: "Inserisci un numero di telefono valido",
    Logic_InvalidUrl: "Inserisci un indirizzo web valido che inizi con http:// o https://",
    Logic_MinValue: "Il valore deve essere almeno {value}",
    Logic_MaxValue: "Il valore deve essere al massimo {value}",
    Logic_MaxLength: "La lunghezza massima è {max} caratteri",
    Logic_ChooseAtLeastOne: "Scegli almeno {count} opzione",
    Logic_ChooseAtLeastMany: "Scegli almeno {count} opzioni",
    Logic_ChooseAtMostOne: "Scegli al massimo {count} opzione",
    Logic_ChooseAtMostMany: "Scegli al massimo {count} opzioni",
    Logic_LikertRemaining: "Rispondi a ogni riga (ne restano {count})",
    Logic_MaxFilesOne: "Allega al massimo {count} file",
    Logic_MaxFilesMany: "Allega al massimo {count} file",
    Logic_FileTooLarge: "\"{name}\" supera {size} MB",
    Logic_FileTypeNotAccepted: "\"{name}\" non è un tipo di file accettato ({types})",
    Logic_AddressRequired: "Inserisci almeno una via e una città",
    Logic_PatternDefault: "Questa risposta non è nel formato previsto",
    Logic_Yes: "Sì",
    Logic_No: "No",
    Logic_Agreed: "Accettato",
    Logic_NotAgreed: "Non accettato",
    Logic_Signed: "Firmato",
    Logic_NoAnswer: "(nessuna risposta)",
    Logic_Unknown: "(sconosciuto)",
    Logic_OtherSlice: "Altro ({count})",
    Logic_CsvResponseId: "ID risposta",
    Logic_CsvSubmitted: "Inviata",
    Logic_CsvSubmittedBy: "Inviata da",
    Logic_EmailQuestion: "Domanda",
    Logic_EmailViewItem: "Visualizza in Microsoft Lists",
    Logic_EmailFooter: "Inviato automaticamente da Smart Forms.",
    Logic_ClosedDefault: "Questo modulo non accetta più risposte.",
    Logic_NotYetOpen: "Questo modulo si apre il {date}.",
    Logic_AlreadyResponded: "Hai già risposto a questo modulo. Grazie!",
    Logic_UntitledQuestion: "Una domanda senza titolo",
    Logic_Issue_NoQuestions: "Aggiungi almeno una domanda prima di raccogliere risposte.",
    Logic_Issue_NoTitle: "Una domanda non ha testo: verrà denominata automaticamente alla pubblicazione.",
    Logic_Issue_DuplicateTitle: "{label} ha lo stesso testo di un'altra domanda, il che rende i risultati più difficili da leggere.",
    Logic_Issue_NeedTwoOptions: "{label} richiede almeno due opzioni.",
    Logic_Issue_ImageNoImage: "{label} ha opzioni senza immagine: verranno mostrate come riquadri di testo.",
    Logic_Issue_LikertNeedRow: "{label} richiede almeno una riga.",
    Logic_Issue_LikertNeedColumns: "{label} richiede almeno due colonne della scala.",
    Logic_Issue_NoLookupList: "{label} non ha un elenco di origine selezionato.",
    Logic_Issue_NoFormula: "{label} non ha una formula.",
    Logic_Issue_BadFormula: "{label} ha una formula che non può essere calcolata. Controlla le parentesi e gli operatori.",
    Logic_Issue_MissingRefs: "{label} fa riferimento a domande che non esistono: {names}.",
    Logic_Issue_BadPattern: "{label} ha un criterio di convalida non valido.",
    Logic_Issue_BrokenRule: "{label} ha una regola di ramificazione che punta a una domanda eliminata.",
    Logic_Issue_SelfRule: "{label} ha una regola di ramificazione che fa riferimento a se stessa.",
    Logic_Issue_RuleMismatch: "{label} ha una regola di ramificazione non più compatibile con la domanda da cui dipende.",
    Logic_Issue_RequiredReadOnly: "{label} è obbligatorio e di sola lettura, quindi può ricevere risposta solo tramite un collegamento precompilato.",
    Logic_Issue_EmptySection: "Una sezione non ha domande e verrà ignorata.",
    Logic_Issue_CloseBeforeOpen: "La data di chiusura coincide con o precede la data di apertura, quindi il modulo non accetterà mai risposte.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Le e-mail di approvazione sono attive ma il passaggio di approvazione è disattivato.",
    Logic_Op_equals: "è",
    Logic_Op_notEquals: "non è",
    Logic_Op_contains: "contiene",
    Logic_Op_notContains: "non contiene",
    Logic_Op_notEmpty: "ha una risposta",
    Logic_Op_empty: "non ha una risposta",
    Logic_Op_greaterThan: "è maggiore di",
    Logic_Op_greaterOrEqual: "è almeno",
    Logic_Op_lessThan: "è minore di",
    Logic_Op_lessOrEqual: "è al massimo",
    Logic_Op_between: "è compreso tra",
    Logic_Op_before: "è precedente a",
    Logic_Op_after: "è successivo a",
    Logic_Type_Text: "Risposta breve",
    Logic_TypeDesc_Text: "Una sola riga di testo",
    Logic_Category_Text: "Testo",
    Logic_Type_MultilineText: "Risposta lunga",
    Logic_TypeDesc_MultilineText: "Più righe di testo normale",
    Logic_Type_RichText: "Testo formattato",
    Logic_TypeDesc_RichText: "Grassetto, elenchi e collegamenti",
    Logic_Type_Choice: "Scelta",
    Logic_TypeDesc_Choice: "Scegli da un elenco di opzioni",
    Logic_Category_Choice: "Scelta",
    Logic_Type_ImageChoice: "Scelta con immagini",
    Logic_TypeDesc_ImageChoice: "Scegli tra riquadri con immagini",
    Logic_Type_Lookup: "Ricerca da un elenco",
    Logic_TypeDesc_Lookup: "Opzioni lette in tempo reale da un altro elenco SharePoint",
    Logic_Type_YesNo: "Sì / No",
    Logic_TypeDesc_YesNo: "Un semplice interruttore attivato/disattivato",
    Logic_Type_Consent: "Consenso",
    Logic_TypeDesc_Consent: "Una casella che il partecipante deve selezionare per continuare",
    Logic_Type_Ranking: "Classifica",
    Logic_TypeDesc_Ranking: "Trascina le opzioni in ordine di preferenza",
    Logic_Type_Rating: "Valutazione",
    Logic_TypeDesc_Rating: "Stelle, cuori o pollici",
    Logic_Category_Scales: "Scale",
    Logic_Type_Scale: "Scala di opinione",
    Logic_TypeDesc_Scale: "Una scala numerica con estremi etichettati",
    Logic_Type_Slider: "Cursore",
    Logic_TypeDesc_Slider: "Un valore su una scala scorrevole",
    Logic_Type_Likert: "Griglia Likert",
    Logic_TypeDesc_Likert: "Valuta più affermazioni su un'unica scala condivisa",
    Logic_Type_Number: "Numero",
    Logic_TypeDesc_Number: "Normale, valuta o percentuale",
    Logic_Category_Advanced: "Avanzate",
    Logic_Type_Calculated: "Calcolato",
    Logic_TypeDesc_Calculated: "Un totale di sola lettura calcolato dalle altre risposte",
    Logic_Type_Date: "Data",
    Logic_TypeDesc_Date: "Una data di calendario, facoltativamente con l'ora",
    Logic_Category_Date: "Data",
    Logic_Type_Time: "Ora",
    Logic_TypeDesc_Time: "Un'ora del giorno da sola",
    Logic_Type_Person: "Persona",
    Logic_TypeDesc_Person: "Scegli una persona dell'organizzazione",
    Logic_Category_People: "Persone",
    Logic_Type_Email: "E-mail",
    Logic_TypeDesc_Email: "Un indirizzo e-mail, convalidato",
    Logic_Type_Phone: "Telefono",
    Logic_TypeDesc_Phone: "Un numero di telefono, convalidato",
    Logic_Type_Address: "Indirizzo",
    Logic_TypeDesc_Address: "Via, città, CAP e paese",
    Logic_Type_Hyperlink: "Collegamento",
    Logic_TypeDesc_Hyperlink: "Un indirizzo web",
    Logic_Type_FileUpload: "Caricamento file",
    Logic_TypeDesc_FileUpload: "Allega uno o più file alla risposta",
    Logic_Type_Signature: "Firma",
    Logic_TypeDesc_Signature: "Firma con il mouse, la penna o il dito",
    Logic_Type_Content: "Blocco di testo",
    Logic_TypeDesc_Content: "Istruzioni o un'immagine: non raccoglie risposte",
    Logic_Category_Layout: "Layout",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Con quale probabilità consiglieresti…",
    Logic_Preset_satisfaction: "Soddisfazione (1–5)",
    Logic_PresetDesc_satisfaction: "Da molto insoddisfatto a molto soddisfatto",
    Logic_Preset_currency: "Valuta",
    Logic_PresetDesc_currency: "Un importo in denaro",
    Logic_Preset_percent: "Percentuale",
    Logic_PresetDesc_percent: "Un valore percentuale",
    Logic_Template_blank_Name: "Modulo vuoto",
    Logic_Template_blank_Description: "Parti da zero",
    Logic_Template_feedback_Name: "Feedback dei clienti",
    Logic_Template_feedback_Description: "NPS, valutazioni e commenti aperti",
    Logic_Template_event_Name: "Registrazione all'evento",
    Logic_Template_event_Description: "Dettagli dei partecipanti, sessioni ed esigenze alimentari",
    Logic_Template_itrequest_Name: "Richiesta di servizio IT",
    Logic_Template_itrequest_Description: "Richieste categorizzate con priorità e allegati",
    Logic_Template_expense_Name: "Nota spese",
    Logic_Template_expense_Description: "Voci di spesa, ricevute e totale calcolato",
    Logic_Template_pulse_Name: "Sondaggio di clima dei dipendenti",
    Logic_Template_pulse_Description: "Griglia Likert, scala di coinvolgimento e nota sull'anonimato",
    Logic_Template_safety_Name: "Ispezione di sicurezza",
    Logic_Template_safety_Description: "Checklist, foto e firma",
    Logic_Template_booking_Name: "Prenotazione di sale o risorse",
    Logic_Template_booking_Description: "Selettore di risorse basato su ricerca con fascia oraria",
    Charts_ColumnChartAria: "Grafico a colonne con {count} categorie",
    Charts_DonutChartAria: "Grafico ad anello di {count} categorie",
    Charts_NoAnswers: "Ancora nessuna risposta.",
    Charts_NoResponses: "Ancora nessuna risposta.",
    Charts_Responses: "Risposte",
    Charts_ResponsesOverTime: "Risposte nel tempo",
    Responses_Chart_Answer: "Risposta",
    Responses_Chart_Average: "Media",
    Responses_Chart_AverageOf: "Media di {count}",
    Responses_Chart_AveragePosition: "Posizione media",
    Responses_Chart_AverageRange: "Media (1–{max})",
    Responses_Chart_AvgValue: "media {value}",
    Responses_Chart_Detractors: "Detrattori (0–6)",
    Responses_Chart_Max: "Max",
    Responses_Chart_Maximum: "Massimo",
    Responses_Chart_Median: "Mediana",
    Responses_Chart_MentionOne: "{count} menzione",
    Responses_Chart_MentionOther: "{count} menzioni",
    Responses_Chart_Min: "Min",
    Responses_Chart_Minimum: "Minimo",
    Responses_Chart_NoAnswers: "Ancora nessuna risposta.",
    Responses_Chart_NoNumeric: "Ancora nessuna risposta numerica.",
    Responses_Chart_NoRankings: "Ancora nessuna classifica.",
    Responses_Chart_NoScores: "Ancora nessun punteggio.",
    Responses_Chart_NotEnoughText: "Testo insufficiente per un riepilogo.",
    Responses_Chart_NpsScore: "Punteggio NPS",
    Responses_Chart_Option: "Opzione",
    Responses_Chart_Passives: "Passivi (7–8)",
    Responses_Chart_Promoters: "Promotori (9–10)",
    Responses_Chart_ResponseOne: "risposta",
    Responses_Chart_ResponseOther: "risposte",
    Responses_Chart_Responses: "Risposte",
    Responses_Chart_ShowingAnswers: "Visualizzate {shown} risposte su {total}.",
    Responses_Chart_Statement: "Affermazione",
    Responses_Chart_Statistic: "Statistica",
    Responses_Chart_StdDev: "Dev. std",
    Responses_Chart_StdDeviation: "Deviazione standard",
    Responses_Chart_Total: "Totale",
    Responses_Chart_Value: "Valore",
    Responses_Dashboard_AllHidden: "Tutte le domande sono nascoste dal dashboard. Usa “Mostra domande nascoste” per ripristinarle.",
    Responses_Dashboard_AnsweredOf: "{answered} su {total} con risposta",
    Responses_Dashboard_AnsweredOfPinned: "{answered} su {total} con risposta · bloccata",
    Responses_Dashboard_AveragedAcrossResponses: "Media su tutte le risposte",
    Responses_Dashboard_ByDay: "Per giorno",
    Responses_Dashboard_ByMonth: "Per mese",
    Responses_Dashboard_ByWeek: "Per settimana",
    Responses_Dashboard_ChartAuto: "Automatico",
    Responses_Dashboard_ChartBars: "Barre",
    Responses_Dashboard_ChartColumns: "Colonne",
    Responses_Dashboard_ChartDonut: "Anello",
    Responses_Dashboard_ChartGauge: "Indicatore",
    Responses_Dashboard_ChartHistogram: "Istogramma",
    Responses_Dashboard_ChartOptions: "Opzioni del grafico",
    Responses_Dashboard_ChartOptionsFor: "Opzioni del grafico per {title}",
    Responses_Dashboard_ChartStatistics: "Statistiche",
    Responses_Dashboard_ChartTable: "Tabella",
    Responses_Dashboard_ChartWordFrequency: "Frequenza delle parole",
    Responses_Dashboard_EmptyBody: "Quando le persone iniziano a rispondere, questo dashboard si popola automaticamente: numeri principali, una cronologia delle risposte e un grafico per le domande da tenere d'occhio.",
    Responses_Dashboard_EmptyTitle: "Ancora nessuna risposta",
    Responses_Dashboard_Hide: "Nascondi dal dashboard",
    Responses_Dashboard_Highlights: "In evidenza",
    Responses_Dashboard_Last7Days: "Ultimi 7 giorni",
    Responses_Dashboard_LatestDate: "Ultima: {date}",
    Responses_Dashboard_MedianTimeToComplete: "Tempo mediano di completamento",
    Responses_Dashboard_NoPriorWeek: "Nessuna settimana precedente da confrontare",
    Responses_Dashboard_OneEach: "Una ciascuno",
    Responses_Dashboard_Pin: "Blocca nel dashboard",
    Responses_Dashboard_QuestionFallback: "domanda",
    Responses_Dashboard_QuestionsAnswered: "Domande con risposta",
    Responses_Dashboard_RecordedOnSubmit: "Registrato all'invio",
    Responses_Dashboard_RepeatResponses: "{count} risposte ripetute",
    Responses_Dashboard_ResponsesOverTime: "Risposte nel tempo",
    Responses_Dashboard_ShowHidden: "Mostra domande nascoste",
    Responses_Dashboard_SinceMidnight: "Da mezzanotte",
    Responses_Dashboard_Today: "Oggi",
    Responses_Dashboard_TotalResponses: "Risposte totali",
    Responses_Dashboard_UniqueRespondents: "Partecipanti univoci",
    Responses_Dashboard_Unpin: "Sblocca dal dashboard",
    Responses_Dashboard_UntitledQuestion: "Domanda senza titolo",
    Responses_Dashboard_VsPrevious7Days: "rispetto ai 7 giorni precedenti",
    Responses_Detail_Answers: "Risposte",
    Responses_Detail_AsTheForm: "Come nel modulo",
    Responses_Detail_Cancel: "Annulla",
    Responses_Detail_Delete: "Elimina",
    Responses_Detail_DeleteBody: "L'elemento dell'elenco viene spostato nel cestino del sito, da cui può essere ripristinato.",
    Responses_Detail_DeleteTitle: "Eliminare questa risposta?",
    Responses_Detail_Deleting: "Eliminazione…",
    Responses_Detail_Draft: "Bozza",
    Responses_Detail_Header: "Risposta {index} di {total}",
    Responses_Detail_LoadingAttachments: "Caricamento degli allegati…",
    Responses_Detail_Next: "Risposta successiva",
    Responses_Detail_NoAnswer: "Nessuna risposta",
    Responses_Detail_Previous: "Risposta precedente",
    Responses_Detail_Print: "Stampa",
    Responses_Detail_Signature: "Firma",
    Responses_Detail_Signed: "Firmato",
    Responses_Detail_Took: "durata: {duration}",
    Responses_Summary_AnsweredOfType: "{answered} su {total} con risposta · {type}",
    Responses_Summary_ByField: "Per {title}",
    Responses_Summary_CompareBy: "Confronta per…",
    Responses_Summary_EmptyBody: "Ogni domanda avrà qui il proprio riepilogo.",
    Responses_Summary_NoComparison: "Nessun confronto",
    Responses_Summary_NothingToCompare: "Nessuna risposta a “{title}”, quindi non c'è nulla da confrontare.",
    Responses_Summary_OtherNote: "I grafici con più di {max} categorie raggruppano le più piccole in “Altro”: passa una scheda a Tabella per vedere tutti i valori.",
    Responses_Summary_ResponseCountOne: "{count} risposta",
    Responses_Summary_ResponseCountOther: "{count} risposte",
    Responses_Summary_SeeAllAnswers: "Vedi tutte le risposte nella tabella",
    Responses_Summary_SegmentNote: "Visualizzati i {groups} gruppi più grandi. Una risposta che ha selezionato più opzioni compare in ogni gruppo corrispondente, quindi i totali dei gruppi possono superare {total}.",
    Responses_Summary_SplitBy: "Dividi per {title}",
    Responses_Summary_Untitled: "senza titolo",
    Responses_Table_Apply: "Applica",
    Responses_Table_Cancel: "Annulla",
    Responses_Table_ClearSelection: "Cancella selezione",
    Responses_Table_ColumnOrder: "Ordine delle colonne",
    Responses_Table_ColumnsCount: "Colonne ({shown}/{total})",
    Responses_Table_Delete: "Elimina",
    Responses_Table_DeleteBody: "Gli elementi dell'elenco vengono spostati nel cestino del sito, da cui possono essere ripristinati.",
    Responses_Table_DeleteSelected: "Elimina selezionate",
    Responses_Table_DeleteTitleOne: "Eliminare {count} risposta?",
    Responses_Table_DeleteTitleOther: "Eliminare {count} risposte?",
    Responses_Table_Deleting: "Eliminazione…",
    Responses_Table_MoveDown: "Sposta giù",
    Responses_Table_MoveDownFor: "Sposta {title} giù",
    Responses_Table_MoveUp: "Sposta su",
    Responses_Table_MoveUpFor: "Sposta {title} su",
    Responses_Table_NoColumns: "Non è ancora visibile nessuna colonna di domande.",
    Responses_Table_NoMatch: "Nessuna risposta corrisponde ai filtri correnti.",
    Responses_Table_NothingToShow: "Nessun elemento da mostrare",
    Responses_Table_OpenResponse: "Apri questa risposta",
    Responses_Table_OrderNote: "Inviato e Inviato da vengono sempre per primi. L'ordine trascinato si applica alle colonne delle domande.",
    Responses_Table_Reorder: "Riordina",
    Responses_Table_ResetColumns: "Reimposta colonne",
    Responses_Table_SelectResponse: "Seleziona questa risposta",
    Responses_Table_SelectedOne: "{count} risposta selezionata",
    Responses_Table_SelectedOther: "{count} risposte selezionate",
    Responses_Table_ShowAll: "Mostra tutto",
    Responses_Table_ShowTheseQuestions: "Mostra queste domande",
    Responses_Table_Submitted: "Inviato",
    Responses_Table_SubmittedBy: "Inviato da",
    Responses_Table_ToggleSelection: "Attiva/disattiva selezione",
    Responses_Table_Unknown: "Sconosciuto",
    Responses_Table_Untitled: "Senza titolo",
    Responses_View_AllTime: "Sempre",
    Responses_View_AnyAnswer: "Qualsiasi risposta",
    Responses_View_Clear: "Cancella",
    Responses_View_CopyShareLink: "Copia collegamento di condivisione",
    Responses_View_CountFiltered: "{shown} risposte su {total}",
    Responses_View_CountOne: "{count} risposta",
    Responses_View_CountOther: "{count} risposte",
    Responses_View_Dashboard: "Dashboard",
    Responses_View_DateRange: "Intervallo di date",
    Responses_View_EmptyBody: "Condividi il modulo per iniziare a raccogliere risposte. Le risposte vengono salvate in “{list}” e compaiono subito qui.",
    Responses_View_EmptyTitle: "Ancora nessuna risposta",
    Responses_View_ExportCsv: "Esporta CSV",
    Responses_View_FilterByAnswer: "Filtra per risposta",
    Responses_View_FilterByQuestion: "Filtra per domanda",
    Responses_View_FilterValue: "Valore del filtro",
    Responses_View_Last30Days: "Ultimi 30 giorni",
    Responses_View_Last7Days: "Ultimi 7 giorni",
    Responses_View_Last90Days: "Ultimi 90 giorni",
    Responses_View_LoadError: "Impossibile caricare le risposte. Pubblica il modulo una volta in modo che le colonne dell'elenco esistano, quindi riprova.",
    Responses_View_Loading: "Caricamento delle risposte…",
    Responses_View_MoreActions: "Altre azioni per le risposte",
    Responses_View_PreviewForm: "Anteprima del modulo",
    Responses_View_Refresh: "Aggiorna",
    Responses_View_ResponsesTab: "Risposte ({count})",
    Responses_View_SearchPlaceholder: "Cerca in tutte le risposte",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Seleziona un valore",
    Responses_View_Summary: "Riepilogo",
    Responses_View_Today: "Oggi",
    Responses_View_Truncated: "Questo elenco contiene più risposte di quante Smart Forms ne carichi contemporaneamente. Vengono mostrate le {count} più recenti: apri l'elenco in Microsoft Lists per vedere l'insieme completo.",
    Responses_View_TryAgain: "Riprova",
    Responses_View_Untitled: "Senza titolo",
    Responses_Approval_Column: "Approvazione",
    Responses_Approval_ReviewerColumn: "Rivisto da",
    Responses_Approval_CommentColumn: "Commento del revisore",
    Responses_Approval_Pending: "In sospeso",
    Responses_Approval_Approved: "Approvata",
    Responses_Approval_Rejected: "Rifiutata",
    Responses_Approval_AnyStatus: "Qualsiasi stato di approvazione",
    Responses_Approval_FilterLabel: "Filtra per stato di approvazione",
    Responses_Approval_ApproveSelected: "Approva selezionate",
    Responses_Approval_RejectSelected: "Rifiuta selezionate",
    Responses_Approval_BulkFailed: "Non è stato possibile aggiornare {count} risposte. Riprova.",
    Responses_Approval_Approve: "Approva",
    Responses_Approval_Reject: "Rifiuta",
    Responses_Approval_Reset: "Reimposta su in sospeso",
    Responses_Approval_CommentLabel: "Commento (facoltativo)",
    Responses_Approval_ReviewedBy: "Rivisto da {name}",
    Responses_Approval_Error: "Non è stato possibile salvare la decisione. Riprova.",
    Responses_Dashboard_ApprovalStatus: "In attesa di revisione",
    Responses_Dashboard_ApprovalBreakdown: "{pending} in sospeso, {approved} approvate, {rejected} rifiutate",
    Responses_Dashboard_TimelineCoarsened: "L'intervallo di date è lungo, quindi la sequenza temporale è stata raggruppata in modo più approssimativo ({grain}).",
    Responses_Dashboard_TimelineTruncated: "L'intervallo di date è molto lungo, quindi vengono mostrati solo gli ultimi {count} periodi.",
    Service_Item_DefaultTitle: "Risposta — {date}",
    Service_Email_ApprovalSubject: "La tua risposta è stata {status} — {title}",
    Service_Email_ApprovalHeading: "La tua risposta è stata {status}",
    Service_Email_ApprovalIntro: "Un revisore ha contrassegnato la tua risposta a \"{title}\" come {status}.",
    Service_Email_ApprovalCommentLabel: "Commento del revisore",
    Service_Approval_Approved: "approvata",
    Service_Approval_Rejected: "rifiutata",
    Service_Approval_Pending: "in sospeso",
    Service_Lookup_InvalidFilter: "Il filtro di ricerca non è valido.",
    Service_Edit_NotAllowed: "Questo modulo non consente di modificare una risposta inviata.",
    Service_Edit_NotYours: "Puoi modificare solo la tua risposta.",
    Service_Signature_AttachmentLabel: "Firma",
    PropertyPane_ListsLoadFailed: "Impossibile caricare gli elenchi di questo sito.",
    PropertyPane_EnterListName: "Immetti prima un nome per il nuovo elenco.",
    PropertyPane_CreatingList: "Creazione di \"{name}\"…",
    PropertyPane_ListCreated: "Elenco \"{title}\" creato e selezionato.",
    PropertyPane_ListAlreadyExists: "Esiste già un elenco denominato \"{name}\": selezionalo dall'elenco a discesa sopra.",
    PropertyPane_CreateListFailed: "Impossibile creare l'elenco. Verifica di avere l'autorizzazione a creare elenchi in questo sito.",
    PropertyPane_Description: "Scegli l'elenco SharePoint in cui archiviare le risposte del modulo oppure creane uno nuovo. Tutto il resto (domande, aspetto, notifiche) si modifica direttamente nella pagina.",
    PropertyPane_ResponseList_GroupName: "Elenco delle risposte",
    PropertyPane_ListDropdown_Label: "Salva le risposte in questo elenco",
    PropertyPane_ResponsesGoTo: "Le risposte vanno in \"{name}\".",
    PropertyPane_PickList: "Scegli un elenco oppure creane uno qui sotto.",
    PropertyPane_LoadingLists: "Caricamento degli elenchi…",
    PropertyPane_NewListName_Label: "Oppure crea un nuovo elenco",
    PropertyPane_NewListName_Placeholder: "Nome del nuovo elenco",
    PropertyPane_CreateList_Button: "Crea elenco",
    PropertyPane_Tips_GroupName: "Suggerimenti",
    PropertyPane_Tip_AutoSave: "Domande e impostazioni vengono salvate automaticamente durante la modifica: non è necessario salvare o pubblicare la pagina.",
    PropertyPane_Tip_Permissions: "I partecipanti devono avere l'autorizzazione ad aggiungere elementi all'elenco delle risposte. Controlla le autorizzazioni dell'elenco se qualcuno segnala un errore durante l'invio.",
    PropertyPane_Tip_Share: "Usa \"Raccogli risposte\" nella pagina per creare le colonne dell'elenco e ottenere un collegamento condivisibile per la compilazione.",
    App_ErrorBoundary_Title: "Smart Forms — Errore di rendering",
    App_ErrorBoundary_Message: "Messaggio:",
    App_ErrorBoundary_Stack: "Stack:",
    App_ErrorBoundary_NoStack: "(nessuno stack disponibile)",
    App_ErrorBoundary_ConsoleNote: "I dettagli completi sono stati scritti anche nella console del browser.",
    App_DefaultQuestionTitle: "Domanda {number}",
    App_Error_ListMissing: "L'elenco configurato per questo modulo non esiste più. Scegli un altro elenco nelle impostazioni della web part.",
    App_Error_LoadConfig: "Si è verificato un problema durante il caricamento della configurazione del modulo.",
    App_Error_Unable: "Impossibile caricare il modulo.",
    App_Publish_ConflictNotice: "\"{title}\" ha già una colonna dell'elenco di tipo diverso ({type}). Rinomina la domanda per consentire la creazione di una nuova colonna oppure ripristina il tipo precedente.",
    App_Publish_ConflictUnnamedQuestion: "una domanda",
    App_Publish_ColumnsAddedOne: "{count} colonna aggiunta a \"{list}\".",
    App_Publish_ColumnsAddedOther: "{count} colonne aggiunte a \"{list}\".",
    App_Publish_TheList: "l'elenco",
    App_Publish_UpToDate: "L'elenco delle risposte è già aggiornato.",
    App_Publish_Error: "Impossibile creare le colonne dell'elenco. In genere significa che non hai l'autorizzazione Gestisci elenchi sull'elenco delle risposte, ma può accadere anche nei siti con gli script personalizzati disabilitati. Controlla la console del browser per l'errore sottostante oppure riprova.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Crea un modulo curato basato su un elenco SharePoint: {count} tipi di domanda, logica di ramificazione, caricamento di file, collegamenti di compilazione condivisibili e un dashboard dei risultati.",
    App_Placeholder_ChooseList: "Scegli o crea un elenco",
    App_Placeholder_Hint: "Modifica la pagina e configura questa web part per iniziare.",
    App_Loading: "Caricamento del modulo…",
    App_OpenSettings: "Apri impostazioni",
    App_Tab_Questions: "Domande",
    App_Tab_QuestionsWithCount: "Domande ({count})",
    App_Tab_Responses: "Risposte",
    App_Tab_Responses_Title: "Le risposte vengono salvate in \"{list}\"",
    App_Templates_Start: "Inizia da un modello",
    App_Settings_Title: "Impostazioni modulo: aspetto, notifiche, accesso",
    App_Settings_AriaLabel: "Impostazioni modulo",
    App_Preview: "Anteprima",
    App_Preview_Close: "Chiudi anteprima",
    App_Preview_Hint: "Anteprima: nulla di ciò che invii qui viene salvato. La convalida e la ramificazione si comportano esattamente come per i partecipanti.",
    App_Publish_GettingReady: "Preparazione in corso…",
    App_Publish_CollectResponses: "Raccogli risposte",
    App_Publish_Share: "Condividi",
    App_Retry: "Riprova",
    App_SaveError_Banner: "Impossibile salvare l'ultima modifica. Controlla la connessione, quindi riprova.",
    App_Preflight_BlockingTitle: "Correggi questi problemi prima di raccogliere risposte",
    App_Preflight_WarningTitle: "Da controllare prima",
    App_Preflight_BlockingText: "Questi problemi impedirebbero il corretto funzionamento del modulo pubblicato.",
    App_Preflight_WarningText: "Non c'è nulla di rotto, ma in genere conviene correggere questi punti prima di condividere il collegamento.",
    App_Preflight_GoTo: "Vai a",
    App_Preflight_CollectAnyway: "Raccogli comunque le risposte",
    App_Preflight_Back: "Torna al modulo",
    App_Cancel: "Annulla",
    App_Done: "Fine",
    App_Share_Title: "Il modulo è pronto per essere condiviso",
    App_Share_SubText: "Invia questo collegamento a chiunque debba compilare il modulo.",
    App_Share_LinkAriaLabel: "Collegamento di condivisione",
    App_Share_Copy: "Copia",
    App_Share_Copied: "Copiato",
    App_Share_AddItemsEmphasis: "aggiungere elementi",
    App_Share_PermissionNote: "I partecipanti devono avere l'autorizzazione ad {addItems} a “{title}” e l'accesso a questa pagina. Se qualcuno riceve un errore durante l'invio, quasi sempre è per questo motivo.",
    App_Share_PrefillNote: "Puoi precompilare le risposte alle domande nel collegamento aggiungendo il nome della colonna, ad esempio {example}.",
    App_Templates_ReplaceWarning: "Scegliendo un modello, le domande attuali vengono sostituite.",
    App_Templates_PickStart: "Scegli un punto di partenza: potrai modificare tutto in seguito.",
    App_Templates_Empty: "Vuoto",
    App_Templates_QuestionCount: "{count} domande",
    App_SaveChip_SavingTitle: "Salvataggio dell'ultima modifica",
    App_SaveChip_Saving: "Salvataggio…",
    App_SaveChip_FailedTitle: "Impossibile salvare l'ultima modifica. Controlla la connessione e riprova.",
    App_SaveChip_Failed: "Salvataggio non riuscito",
    App_SaveChip_SavedTitle: "Tutte le modifiche sono state salvate",
    App_SaveChip_Saved: "Salvato",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Nuova risposta — {title}",
    Service_Email_NewResponseHeading: "Nuova risposta: {title}",
    Service_Email_NewResponseIntro: "Qualcuno ha appena inviato una risposta — {date}.",
    Service_Email_ReceiptSubject: "La tua risposta — {title}",
    Service_Email_ReceiptHeading: "Grazie per la tua risposta!",
    Service_Email_ReceiptIntro: "Ecco una copia di ciò che hai inviato a \"{title}\".",
    App_History_Title: "Cronologia versioni",
    App_History_RestoredNotice: "Ripristinata la versione salvata il {date}. Controllala, quindi usa Raccogli risposte per pubblicare le nuove domande.",
    App_History_Undo: "Annulla ripristino",
    App_Share_CopyManual: "Il browser ha bloccato la copia. Seleziona il collegamento qui sopra e premi Ctrl+C (Cmd+C su Mac) per copiarlo.",
    App_Share_TeamsNote: "Ti trovi in Microsoft Teams. Questo collegamento apre direttamente la pagina di SharePoint, quindi i destinatari devono avere accesso al sito.",
    App_Share_PrefillNotSecure: "Le risposte precompilate sono solo una comodità: chiunque abbia il collegamento può modificarle, quindi non considerarle mai un limite di sicurezza.",
    Designer_Section_DropHere: "Trascina qui una domanda",
    Designer_Section_DropEnd: "Rilascia qui per spostare alla fine di questa sezione",
    Designer_Rules_RemovedOne: "È stata rimossa 1 regola di ramificazione non più compatibile.",
    Designer_Rules_RemovedOther: "Sono state rimosse {count} regole di ramificazione non più compatibili.",
    Designer_Settings_AllowEdit: "Consenti ai partecipanti di modificare la propria risposta",
    Designer_Settings_AllowEditHint: "I partecipanti possono riaprire e aggiornare ciò che hanno inviato. Ogni persona può modificare solo la propria risposta.",
    Designer_Settings_EnableApproval: "Abilita il flusso di approvazione",
    Designer_Settings_ApprovalNotify: "Invia un'e-mail al partecipante con la decisione",
    Designer_Settings_ApprovalHint: "Aggiunge colonne di approvazione all'elenco delle risposte alla prossima pubblicazione. I proprietari approvano o rifiutano le risposte dalla scheda Risposte.",
    Designer_History_Title: "Cronologia versioni",
    Designer_History_Intro: "Versioni salvate in precedenza delle domande e delle impostazioni di questo modulo. Il ripristino carica una versione nella finestra di progettazione; puoi annullarlo e le nuove domande vengono create solo alla pubblicazione.",
    Designer_History_Loading: "Caricamento delle versioni...",
    Designer_History_Empty: "Non sono state trovate versioni precedenti. La cronologia versioni richiede che il controllo delle versioni sia attivo per l'elenco \"Smart Forms Config\" e almeno una modifica salvata.",
    Designer_History_Latest: "Più recente",
    Designer_History_LatestTitle: "Questa è la versione attualmente in uso",
    Designer_History_By: "di {name}",
    Designer_History_UnknownAuthor: "Autore sconosciuto",
    Designer_History_VersionLabel: "versione {label}",
    Designer_History_Preview: "Anteprima",
    Designer_History_Restore: "Ripristina",
    Designer_History_QuestionsOne: "1 domanda",
    Designer_History_QuestionsOther: "{count} domande",
    Designer_History_LoadFailed: "Impossibile caricare questa versione.",
    Designer_History_ConfirmTitle: "Ripristinare questa versione?",
    Designer_History_ConfirmText: "Il modulo verrà sostituito con la versione salvata il {date} ({count} domande). Potrai annullare subito dopo."
  };
});
