define([], function () {
  return {
    Designer_Color_Blue: "ブルー",
    Designer_Color_Teal: "ティール",
    Designer_Color_Green: "グリーン",
    Designer_Color_Purple: "パープル",
    Designer_Color_Magenta: "マゼンタ",
    Designer_Color_Red: "レッド",
    Designer_Color_Orange: "オレンジ",
    Designer_Color_Gray: "グレー",
    Designer_Settings_LayoutSinglePage: "すべての質問を 1 ページに表示",
    Designer_Settings_LayoutWizard: "1 ステップにつき 1 セクション (ウィザード)",
    Designer_Settings_Title: "フォームの設定",
    Designer_Common_Apply: "適用",
    Designer_Common_Cancel: "キャンセル",
    Designer_Settings_TabBasics: "基本",
    Designer_Settings_FormTitle: "フォームのタイトル",
    Designer_Settings_Description: "説明",
    Designer_Settings_Layout: "レイアウト",
    Designer_Settings_NumberQuestions: "質問に番号を付ける",
    Designer_Settings_ShuffleQuestions: "回答者ごとに質問の順序をシャッフルする",
    Designer_Settings_ShowProgressBar: "進行状況バーを表示する",
    Designer_Settings_TabAppearance: "外観",
    Designer_Settings_AccentColor: "アクセント カラー",
    Designer_Settings_CustomColorTitle: "ユーザー設定の色",
    Designer_Settings_CustomColorAria: "ユーザー設定のアクセント カラー",
    Designer_Settings_AccentHint: "アクセント カラーは、ダーク サイトでコントラストが保たれるよう自動的に調整されるため、ページのテーマに関係なくフォームが読みやすい状態を維持します。",
    Designer_Settings_ShowHeader: "フォームのヘッダーを表示する",
    Designer_Settings_HeaderIcon: "ヘッダー アイコン",
    Designer_Settings_TabAfterSubmit: "送信後",
    Designer_Settings_SubmitButtonText: "送信ボタンのテキスト",
    Designer_Settings_SubmitPlaceholder: "送信",
    Designer_Settings_ThankYouTitle: "お礼のタイトル",
    Designer_Settings_ThankYouPlaceholder: "ありがとうございました。",
    Designer_Settings_ThankYouMessage: "お礼のメッセージ",
    Designer_Settings_ShowSubmitAnother: "「別の回答を送信」ボタンを表示する",
    Designer_Settings_TabNotifications: "通知",
    Designer_Settings_EmailEachResponseTo: "各回答をメールで送信する宛先",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "組織内のユーザーは、リスト アイテムへのリンクが付いた各回答をメールで受け取ります",
    Designer_Settings_RespondentReceipt: "回答者に回答内容のコピーをメールで送信する",
    Designer_Settings_NotificationsInfo: "通知には SharePoint 独自のメール サービスが使用されるため、受信者は組織内のユーザーである必要があります。外部のアドレスは通知なく破棄されます。",
    Designer_Settings_TabAccess: "アクセス",
    Designer_Settings_OpenFrom: "公開開始",
    Designer_Settings_OpenImmediately: "すぐに公開",
    Designer_Settings_CloseAfter: "公開終了",
    Designer_Settings_NeverClose: "終了しない",
    Designer_Settings_ClearDates: "日付をクリア",
    Designer_Settings_DatesInverted: "終了日が開始日と同じか開始日より前のため、フォームは回答を受け付けません。",
    Designer_Settings_MaxResponses: "この件数の回答で受け付けを停止",
    Designer_Settings_NoLimit: "制限なし",
    Designer_Settings_OneResponsePerPerson: "1 人につき 1 回のみ回答を許可する",
    Designer_Settings_AllowSaveDraft: "回答者が下書きを保存して後で回答を完了できるようにする",
    Designer_Settings_ClosedMessage: "フォームが終了しているときに表示するメッセージ",
    Designer_Settings_ClosedMessagePlaceholder: "このフォームは現在、回答を受け付けていません。",
    Designer_Settings_AccessInfo: "これらの制限は SharePoint ではなくフォームによって適用されます。回答リストにアイテムを追加する権限を持つユーザーは、リストから直接アイテムを追加できます。",
    Designer_Field_StyleInfo: "情報 (アクセント)",
    Designer_Field_StyleSuccess: "成功 (緑)",
    Designer_Field_StyleWarning: "警告 (アンバー)",
    Designer_Field_StylePlain: "プレーン テキスト",
    Designer_Field_StyleDivider: "区切り線",
    Designer_Field_IconStars: "星",
    Designer_Field_IconHearts: "ハート",
    Designer_Field_IconThumbs: "いいね",
    Designer_Field_FormatPlain: "標準の数値",
    Designer_Field_FormatCurrency: "通貨",
    Designer_Field_FormatPercent: "パーセンテージ",
    Designer_Field_UntitledQuestion: "タイトルなしの質問",
    Designer_Field_DeletedQuestion: "削除された質問",
    Designer_Rule_Unary: "「{name}」 {operator}",
    Designer_Rule_Between: "「{name}」 {operator} {value} と {value2}",
    Designer_Rule_Binary: "「{name}」 {operator} 「{value}」",
    Designer_Rule_JoinAny: "または",
    Designer_Rule_JoinAll: "かつ",
    Designer_Rule_Preview: "{conditions} の場合に表示されます。",
    Designer_Field_Yes: "はい",
    Designer_Field_No: "いいえ",
    Designer_Field_When: "条件",
    Designer_Field_SelectValue: "値を選択",
    Designer_Field_DateValuePlaceholder: "YYYY-MM-DD または \"today\"",
    Designer_Field_ValuePlaceholder: "値",
    Designer_Field_UpperBound: "上限",
    Designer_Field_RemoveCondition: "この条件を削除",
    Designer_Field_FormulaInvalid: "この数式は計算できません。かっこと演算子を確認してください。",
    Designer_Field_FormulaMissing: "次の質問は存在しません: {names}。",
    Designer_Field_FormulaPreview: "すべての入力が 10 の場合、{value} と表示されます。",
    Designer_Field_HintYesNo: "\"yes\" または \"no\" を使用します",
    Designer_Field_HintMultiDefault: "複数の既定値は ; で区切ります",
    Designer_Field_HintSingleDefault: "選択肢のいずれかと一致する必要があります",
    Designer_Field_HintDate: "\"today\" または 2026-03-01 のような日付を使用します",
    Designer_Field_HintTime: "\"now\" または 09:30 のような時刻を使用します",
    Designer_Field_QuestionSettings: "質問の設定",
    Designer_Field_Appearance: "外観",
    Designer_Field_Style: "スタイル",
    Designer_Field_ImageUrl: "画像の URL (省略可)",
    Designer_Field_Content: "コンテンツ",
    Designer_Field_BasicFormatting: "基本的な書式 (太字、斜体、リスト、リンク) を使用できます。",
    Designer_Field_TabOptions: "オプション",
    Designer_Field_TabBranching: "分岐",
    Designer_Field_BranchingNeedsQuestion: "先に別の質問を追加してください。分岐には依存先が必要です。",
    Designer_Field_BranchingToggle: "他の回答が一致する場合にのみこの質問を表示する",
    Designer_Field_Match: "一致条件",
    Designer_Field_MatchAll: "次のすべて",
    Designer_Field_MatchAny: "次のいずれか",
    Designer_Field_AddCondition: "条件を追加",
    Designer_Field_TabValidation: "検証",
    Designer_Field_HelpText: "ヘルプ テキスト",
    Designer_Field_HelpTextPlaceholder: "質問ラベルの下に表示されます",
    Designer_Field_CheckboxLabel: "チェック ボックスのラベル",
    Designer_Field_Placeholder: "プレースホルダー",
    Designer_Field_DefaultAnswer: "既定の回答",
    Designer_Field_RequiredMessage: "カスタムの必須メッセージ",
    Designer_Field_RequiredMessagePlaceholder: "{title} は必須です",
    Designer_Field_ThisQuestion: "この質問",
    Designer_Field_RequiredMessageDescription: "この質問が空白の場合、標準のメッセージの代わりに表示されます",
    Designer_Field_ReadOnly: "読み取り専用 (回答は事前入力されたリンクからのみ設定可能)",
    Designer_Field_ValidationRules: "検証規則",
    Designer_Field_MaxLength: "最大長",
    Designer_Field_Pattern: "次のパターンと一致する必要があります",
    Designer_Field_PatternDescription: "正規表現。パターンを確認しない場合は空白のままにします。",
    Designer_Field_PatternMessage: "パターンが一致しない場合のメッセージ",
    Designer_Field_PatternMessagePlaceholder: "この回答は期待される形式ではありません",
    Designer_Field_Format: "形式",
    Designer_Field_UnitSuffix: "値の後ろに表示する単位",
    Designer_Field_UnitSuffixPlaceholder: "kg、時間、個…",
    Designer_Field_Minimum: "最小値",
    Designer_Field_Maximum: "最大値",
    Designer_Field_Decimals: "小数点以下の桁数",
    Designer_Field_Formula: "数式",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "他の質問は、その質問のテキストを中かっこで囲んで参照します。+ - * / ( ) と round、min、max、sum、avg をサポートします。",
    Designer_Field_AvailableQuestions: "使用可能な質問: {questions}",
    Designer_Field_NoneYet: "まだありません",
    Designer_Field_Step: "ステップ",
    Designer_Field_From: "開始",
    Designer_Field_To: "終了",
    Designer_Field_LowLabel: "下限のラベル",
    Designer_Field_LowLabelPlaceholder: "まったく可能性がない",
    Designer_Field_HighLabel: "上限のラベル",
    Designer_Field_HighLabelPlaceholder: "非常に可能性が高い",
    Designer_Field_SummarizeAs: "集計方法",
    Designer_Field_SummarizeAverage: "平均と分布",
    Designer_Field_SummarizeNps: "Net Promoter Score (0～10 の尺度が必要)",
    Designer_Field_NpsWarning: "Net Promoter Score は 0～10 の尺度でのみ有効です。開始を 0、終了を 10 に設定してください。",
    Designer_Field_NumberOfIcons: "アイコンの数",
    Designer_Field_Icon: "アイコン",
    Designer_Field_AllowHalf: "0.5 刻みの値を許可する",
    Designer_Field_ShowOptionsAs: "オプションの表示形式",
    Designer_Field_DisplayButtons: "インライン ボタン",
    Designer_Field_DisplayDropdown: "ドロップダウン",
    Designer_Field_DisplayAutomatic: "自動 (6 個までの選択肢はインライン表示)",
    Designer_Field_AllowOther: "自由入力の「その他」オプションを追加する",
    Designer_Field_OtherLabel: "「その他」オプションのラベル",
    Designer_Field_OtherPlaceholder: "その他",
    Designer_Field_ShuffleOptions: "回答者ごとに選択肢の順序をシャッフルする",
    Designer_Field_MinSelections: "最小選択数",
    Designer_Field_MaxSelections: "最大選択数",
    Designer_Field_SourceList: "ソース リスト",
    Designer_Field_ChooseList: "リストを選択",
    Designer_Field_LookupColumn: "オプションの取得元の列",
    Designer_Field_ChooseColumn: "列を選択",
    Designer_Field_ChooseListFirst: "先にリストを選択してください",
    Designer_Field_LookupFilter: "フィルター (省略可)",
    Designer_Field_LookupFilterDescription: "どのソース アイテムをオプションにするかを絞り込む OData フィルター",
    Designer_Field_LookupInfo: "回答にはソース アイテムへのリンクではなくオプションのテキストが保存されるため、ソース リストが後で変更されても回答は読み取り可能なままです。",
    Designer_Field_ConsentText: "チェック ボックスの上に表示する規約",
    Designer_Field_AllowMultiplePeople: "複数のユーザーを許可する",
    Designer_Field_AllowGroups: "グループも許可する",
    Designer_Field_IncludeTime: "時刻を含める",
    Designer_Field_TimeStep: "時刻の間隔 (分)",
    Designer_Field_MaxFiles: "最大ファイル数",
    Designer_Field_MaxFileSize: "1 ファイルあたりの最大サイズ (MB)",
    Designer_Field_AcceptedTypes: "許可するファイルの種類",
    Designer_Field_AcceptedTypesDescription: "拡張子をコンマで区切ります。SharePoint で許可されているものをすべて受け付ける場合は空白のままにします。",
    Designer_Field_FilesInfo: "ファイルは回答アイテムの添付ファイルとして保存されます。SharePoint では、ここでの許可設定に関係なく、一部の拡張子 (.exe など) がブロックされます。",
    Designer_Field_Rows: "行",
    Designer_Field_ProvisionedNote: "この質問にはすでにリスト列 ({name}) があります。列の種類を変更する設定はロックされています。別の種類が必要な場合は、質問を複製してください。",
    Designer_Category_Text: "テキスト",
    Designer_Category_Choice: "選択",
    Designer_Category_Scales: "尺度",
    Designer_Category_Date: "日付",
    Designer_Category_People: "ユーザー",
    Designer_Category_Advanced: "詳細",
    Designer_Category_Layout: "レイアウト",
    Designer_Menu_CommonPresets: "よく使うプリセット",
    Designer_Menu_AllTypes: "すべての質問の種類",
    Designer_Menu_ChangeType: "種類を変更",
    Designer_Menu_TypeLockedTitle: "リスト列がすでに存在するため、種類はロックされています。変更するには質問を複製してください。",
    Designer_Menu_MoreSettings: "分岐、検証など",
    Designer_Menu_InsertBelow: "下に質問を挿入",
    Designer_Card_Duplicate: "複製",
    Designer_Card_DeleteQuestion: "質問を削除",
    Designer_Outline_Aria: "質問のアウトライン",
    Designer_Outline_QuestionCountOne: "{count} 件の質問",
    Designer_Outline_QuestionCountOther: "{count} 件の質問",
    Designer_Outline_IssuesTitle: "確認が必要な問題 {count} 件",
    Designer_Outline_Find: "質問を検索",
    Designer_Outline_Empty: "質問はまだありません。",
    Designer_Section_DefaultTitle: "セクション {number}",
    Designer_Card_Question: "質問",
    Designer_Card_BranchingTitle: "この質問は、分岐ルールに一致した場合にのみ表示されます",
    Designer_Card_BranchingChip: "分岐",
    Designer_Card_LiveTitle: "リスト列が存在するため、種類はロックされています",
    Designer_Card_LiveChip: "公開中",
    Designer_Card_CheckChip: "要確認",
    Designer_Option_Placeholder: "オプション {number}",
    Designer_Option_LabelAria: "オプション {number} のラベル",
    Designer_Option_ImageUrl: "画像の URL",
    Designer_Option_ImageUrlAria: "オプション {number} の画像 URL",
    Designer_Option_Remove: "オプションを削除",
    Designer_Option_RemoveAria: "オプション {number} を削除",
    Designer_Option_Add: "オプションを追加",
    Designer_Option_OtherHint: "回答者は「{label}」というラベルの回答を自由に入力することもできます。",
    Designer_Option_OtherFallback: "その他",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "削除",
    Designer_Grid_RemoveAria: "{label} {number} を削除",
    Designer_Grid_Statements: "ステートメント",
    Designer_Grid_Scale: "尺度",
    Designer_Grid_AddStatement: "ステートメントを追加",
    Designer_Grid_AddScale: "尺度を追加",
    Designer_Width_Full: "全幅",
    Designer_Width_Half: "1/2 幅",
    Designer_Width_Third: "1/3 幅",
    Designer_Width_Aria: "質問の幅",
    Designer_Card_BlockLabelPlaceholder: "ブロックのラベル (回答者には表示されません)",
    Designer_Card_QuestionText: "質問のテキスト",
    Designer_Card_MoveUp: "上へ移動",
    Designer_Card_MoveQuestionUp: "質問を上へ移動",
    Designer_Card_MoveDown: "下へ移動",
    Designer_Card_MoveQuestionDown: "質問を下へ移動",
    Designer_Card_DuplicateQuestion: "質問を複製",
    Designer_Card_MultipleAnswers: "複数回答",
    Designer_Card_Required: "必須",
    Designer_Card_MoreOptions: "その他のオプション",
    Designer_Card_MoreOptionsAria: "この質問のその他のオプション",
    Designer_Canvas_FormTitle: "フォームのタイトル",
    Designer_Canvas_DescriptionPlaceholder: "説明を追加 (省略可)",
    Designer_Canvas_DescriptionAria: "フォームの説明",
    Designer_Canvas_EmptyTitle: "最初の質問を追加",
    Designer_Canvas_EmptyBody: "質問の種類を選んで始めましょう。質問はドラッグして並べ替えることができ、分岐を追加して、回答者に関係のある質問だけを表示することもできます。",
    Designer_Section_Chip: "セクション {number}/{total}",
    Designer_Section_TitlePlaceholder: "セクションのタイトル",
    Designer_Section_TitleAria: "セクション {number} のタイトル",
    Designer_Section_DescriptionPlaceholder: "説明 (省略可)",
    Designer_Section_DescriptionAria: "セクション {number} の説明",
    Designer_Section_MoveUp: "セクションを上へ移動",
    Designer_Section_MoveDown: "セクションを下へ移動",
    Designer_Section_Delete: "セクションを削除",
    Designer_Card_DragToReorder: "ドラッグして並べ替え",
    Designer_Card_ReorderAria: "{title} を並べ替え",
    Designer_Card_ReorderFallback: "質問",
    Designer_Canvas_AddNew: "新規追加",
    Designer_Canvas_AddSection: "セクションを追加",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "番地",
    Form_Address_Street2Placeholder: "建物名・部屋番号など (省略可)",
    Form_Address_CityPlaceholder: "市区町村",
    Form_Address_StatePlaceholder: "都道府県",
    Form_Address_PostalCodePlaceholder: "郵便番号",
    Form_Address_CountryPlaceholder: "国",
    Form_Address_StreetAria: "番地",
    Form_Address_Street2Aria: "住所の 2 行目",
    Form_Address_CityAria: "市区町村",
    Form_Address_StateAria: "都道府県",
    Form_Address_PostalCodeAria: "郵便番号",
    Form_Address_CountryAria: "国",
    Form_Consent_DefaultLabel: "同意します",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{total} 行中 {answered} 行に回答済み",
    Form_Lookup_LoadError: "この質問のオプションを読み込めませんでした。",
    Form_Lookup_Loading: "オプションを読み込んでいます…",
    Form_Lookup_SelectOptionsPlaceholder: "オプションを選択",
    Form_Lookup_SelectOptionPlaceholder: "オプションを選択",
    Form_Person_Placeholder: "名前を入力してください…",
    Form_Person_SuggestedPeopleAndGroups: "おすすめのユーザーとグループ",
    Form_Person_SuggestedPeople: "おすすめのユーザー",
    Form_Person_NoPeopleOrGroups: "ユーザーまたはグループが見つかりません",
    Form_Person_NoPeople: "ユーザーが見つかりません",
    Form_Person_Searching: "検索中…",
    Form_Ranking_Moved: "{item} を {total} 件中 {position} 番目に移動しました",
    Form_Ranking_MoveUp: "上へ移動",
    Form_Ranking_MoveDown: "下へ移動",
    Form_Ranking_MoveItemUpAria: "{item} を上へ移動",
    Form_Ranking_MoveItemDownAria: "{item} を下へ移動",
    Form_Rating_ValueText: "{value}/{max}",
    Form_Rating_NotRated: "未評価",
    Form_Rating_Clear: "評価をクリア",
    Form_RichText_Bold: "太字",
    Form_RichText_Italic: "斜体",
    Form_RichText_Underline: "下線",
    Form_RichText_BulletedList: "箇条書き",
    Form_RichText_NumberedList: "番号付きリスト",
    Form_RichText_ClearFormatting: "書式をクリア",
    Form_RichText_ToolbarAria: "テキストの書式設定",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "「{name}」はスキップされました。上限は {limit} です。",
    Form_File_TypeNotAccepted: "「{name}」は許可されていない種類です。",
    Form_File_TooLarge: "「{name}」は {size} MB を超えています。",
    Form_File_AlreadyAttached: "「{name}」はすでに添付されています。",
    Form_File_ReadError: "いずれかのファイルを読み取れませんでした。もう一度添付してください。",
    Form_File_HintMaxSize: "1 ファイルあたり最大 {size} MB",
    Form_File_HintOneFile: "1 ファイル",
    Form_File_HintMaxFiles: "最大 {count} ファイル",
    Form_File_Reading: "ファイルを読み取っています…",
    Form_File_DropPrompt: "ここにファイルをドロップするか、クリックして参照します",
    Form_File_Remove: "{name} を削除",
    Form_Signature_Alt: "署名",
    Form_Signature_AriaSigned: "{label} — 署名済み",
    Form_Signature_AriaEmpty: "{label} — 未入力",
    Form_Signature_Clear: "クリア",
    Form_Signature_Signed: "署名済み",
    Form_Signature_Prompt: "上の枠にマウス、ペン、または指で署名してください",
    Form_Time_Placeholder: "時刻を選択",
    Form_Field_DatePlaceholder: "日付を選択",
    Form_Field_TimeAriaWithLabel: "{label} — 時刻",
    Form_Field_TimeAria: "時刻",
    Form_Field_OtherDefault: "その他",
    Form_Field_SelectOptionsPlaceholder: "オプションを選択",
    Form_Field_PleaseSpecify: "具体的に入力してください",
    Form_Field_OtherSpecifyAria: "{label} — 具体的に入力してください",
    Form_Field_SelectOptionPlaceholder: "オプションを選択",
    Form_Field_Yes: "はい",
    Form_Field_No: "いいえ",
    Form_Field_SliderHint: "スライダーをドラッグして回答してください",
    Form_Field_WebAddressAriaWithLabel: "{label} — Web アドレス",
    Form_Field_WebAddressAria: "Web アドレス",
    Form_Field_DisplayTextPlaceholder: "表示テキスト (省略可)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — 表示テキスト",
    Form_Field_DisplayTextAria: "表示テキスト",
    Form_Field_ChooseBetween: "{min} ～ {max} 個を選択してください",
    Form_Field_ChooseAtLeast: "{min} 個以上選択してください",
    Form_Field_ChooseUpTo: "最大 {max} 個まで選択してください",
    Form_Field_SelectedCount: "{count} 個選択済み",
    Form_Field_RequiredAria: "(必須)",
    Form_Submit_SaveError: "回答を保存できませんでした。デザイナーからフォームが公開されていること、および回答リストにアイテムを追加する権限があることを確認してください。",
    Form_Empty_Message: "このフォームにはまだ質問がありません。フォームの所有者は [質問] タブで追加できます。",
    Form_Checking: "フォームを確認しています…",
    Form_Closed_NotYetOpen: "まだ公開されていません",
    Form_Closed_AlreadyAnswered: "回答済み",
    Form_Closed_Title: "フォームは終了しました",
    Form_Confirmation_PreviewNotice: "これはプレビューでした。回答リストには何も保存されていません。",
    Form_Confirmation_PreviewAgain: "もう一度プレビュー",
    Form_Confirmation_SubmitAnother: "別の回答を送信",
    Form_Wizard_StepFallback: "ステップ {step}",
    Form_Wizard_StepsAria: "フォームのステップ",
    Form_Wizard_StepOf: "ステップ {step}/{total}",
    Form_ErrorSummary_Title: "{count} 件の回答を確認してください:",
    Form_ErrorSummary_UntitledQuestion: "タイトルなしの質問",
    Form_ErrorSummary_Question: "質問",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "戻る",
    Form_Nav_Next: "次へ",
    Form_Draft_Saving: "保存中…",
    Form_Draft_Saved: "下書きを保存しました",
    Form_Draft_SaveAndFinishLater: "保存して後で完了",
    Form_Draft_NotSaved: "下書きは保存されていません",
    Form_Submit_Preview: "送信 (プレビュー)",
    Form_Submit_Button: "送信",
    Form_Response_NoAnswer: "回答なし",
    Form_Signature_TypeLabel: "氏名を入力してください",
    Form_Signature_TypeInstead: "代わりに名前を入力",
    Form_Signature_DrawInstead: "代わりに手書き",
    Form_Edit_Button: "前回の回答を編集",
    Form_Edit_Available: "すでに回答を送信済みです。新しく送信する代わりに、回答を編集できます。",
    Form_Edit_Banner: "前回の回答を編集しています。",
    Form_Edit_Save: "回答を更新",
    Form_Edit_UpdatedTitle: "回答を更新しました",
    Form_Edit_UpdatedMessage: "変更を保存しました。",
    Form_Edit_LoadError: "前回の回答を読み込めませんでした。もう一度お試しください。",
    Form_Draft_MissingFiles: "次のファイルを再度添付してください: {names}。これらのファイルは復元できませんでした。",
    Form_Attachments_Failed: "回答は保存されましたが、次の添付ファイルをアップロードできませんでした: {names}。もう一度お試しいただくか、フォームの所有者にお問い合わせください。",
    Logic_ThisQuestion: "この質問",
    Logic_Required: "{label} は必須です",
    Logic_RequiredConsent: "続行するにはチェック ボックスをオンにしてください",
    Logic_RequiredFile: "ファイルを 1 つ以上添付してください",
    Logic_RequiredSignature: "署名を追加してください",
    Logic_RequiredLikert: "すべての行に回答してください",
    Logic_InvalidEmail: "有効なメール アドレスを入力してください",
    Logic_InvalidPhone: "有効な電話番号を入力してください",
    Logic_InvalidUrl: "http:// または https:// で始まる有効な Web アドレスを入力してください",
    Logic_MinValue: "値は {value} 以上にしてください",
    Logic_MaxValue: "値は {value} 以下にしてください",
    Logic_MaxLength: "最大文字数は {max} 文字です",
    Logic_ChooseAtLeastOne: "{count} 個以上のオプションを選択してください",
    Logic_ChooseAtLeastMany: "{count} 個以上のオプションを選択してください",
    Logic_ChooseAtMostOne: "オプションの選択は {count} 個までです",
    Logic_ChooseAtMostMany: "オプションの選択は {count} 個までです",
    Logic_LikertRemaining: "すべての行に回答してください (残り {count} 行)",
    Logic_MaxFilesOne: "添付できるファイルは {count} 個までです",
    Logic_MaxFilesMany: "添付できるファイルは {count} 個までです",
    Logic_FileTooLarge: "\"{name}\" は {size} MB を超えています",
    Logic_FileTypeNotAccepted: "\"{name}\" は許可されていないファイルの種類です ({types})",
    Logic_AddressRequired: "少なくとも番地と市区町村を入力してください",
    Logic_PatternDefault: "この回答は想定された形式ではありません",
    Logic_Yes: "はい",
    Logic_No: "いいえ",
    Logic_Agreed: "同意済み",
    Logic_NotAgreed: "未同意",
    Logic_Signed: "署名済み",
    Logic_NoAnswer: "(回答なし)",
    Logic_Unknown: "(不明)",
    Logic_OtherSlice: "その他 ({count})",
    Logic_CsvResponseId: "回答 ID",
    Logic_CsvSubmitted: "送信日時",
    Logic_CsvSubmittedBy: "送信者",
    Logic_EmailQuestion: "質問",
    Logic_EmailViewItem: "Microsoft Lists で表示",
    Logic_EmailFooter: "Smart Forms から自動送信されました。",
    Logic_ClosedDefault: "このフォームは回答の受付を終了しました。",
    Logic_NotYetOpen: "このフォームは {date} に開始されます。",
    Logic_AlreadyResponded: "このフォームにはすでに回答済みです。ありがとうございました。",
    Logic_UntitledQuestion: "タイトルのない質問",
    Logic_Issue_NoQuestions: "回答を収集する前に、質問を 1 つ以上追加してください。",
    Logic_Issue_NoTitle: "テキストのない質問があります。発行時に自動的に名前が付けられます。",
    Logic_Issue_DuplicateTitle: "{label} は他の質問と同じテキストのため、結果が読みにくくなります。",
    Logic_Issue_NeedTwoOptions: "{label} には 2 つ以上のオプションが必要です。",
    Logic_Issue_ImageNoImage: "{label} には画像のないオプションがあり、テキスト タイルとして表示されます。",
    Logic_Issue_LikertNeedRow: "{label} には 1 つ以上の行が必要です。",
    Logic_Issue_LikertNeedColumns: "{label} には 2 つ以上のスケール列が必要です。",
    Logic_Issue_NoLookupList: "{label} にはソース リストが選択されていません。",
    Logic_Issue_NoFormula: "{label} には数式がありません。",
    Logic_Issue_BadFormula: "{label} の数式は計算できません。かっこと演算子を確認してください。",
    Logic_Issue_MissingRefs: "{label} は存在しない質問を参照しています: {names}。",
    Logic_Issue_BadPattern: "{label} の検証パターンが無効です。",
    Logic_Issue_BrokenRule: "{label} の分岐ルールが、削除された質問を指しています。",
    Logic_Issue_SelfRule: "{label} の分岐ルールが自分自身を参照しています。",
    Logic_Issue_RuleMismatch: "{label} の分岐ルールが、依存先の質問と一致しなくなりました。",
    Logic_Issue_RequiredReadOnly: "{label} は必須かつ読み取り専用のため、事前入力リンクからしか回答できません。",
    Logic_Issue_EmptySection: "質問のないセクションがあり、スキップされます。",
    Logic_Issue_CloseBeforeOpen: "終了日が開始日と同じかそれより前のため、このフォームは回答を受け付けません。",
    Logic_Issue_ApprovalNotifyWithoutApproval: "承認メールはオンですが、承認ステップがオフです。",
    Logic_Op_equals: "次と等しい",
    Logic_Op_notEquals: "次と等しくない",
    Logic_Op_contains: "次を含む",
    Logic_Op_notContains: "次を含まない",
    Logic_Op_notEmpty: "回答済み",
    Logic_Op_empty: "未回答",
    Logic_Op_greaterThan: "次より大きい",
    Logic_Op_greaterOrEqual: "次以上",
    Logic_Op_lessThan: "次より小さい",
    Logic_Op_lessOrEqual: "次以下",
    Logic_Op_between: "次の範囲内",
    Logic_Op_before: "次より前",
    Logic_Op_after: "次より後",
    Logic_Type_Text: "短い回答",
    Logic_TypeDesc_Text: "1 行のテキスト",
    Logic_Category_Text: "テキスト",
    Logic_Type_MultilineText: "長い回答",
    Logic_TypeDesc_MultilineText: "複数行のプレーン テキスト",
    Logic_Type_RichText: "書式付きテキスト",
    Logic_TypeDesc_RichText: "太字、リスト、リンク",
    Logic_Type_Choice: "選択肢",
    Logic_TypeDesc_Choice: "オプションの一覧から選択",
    Logic_Category_Choice: "選択肢",
    Logic_Type_ImageChoice: "画像の選択肢",
    Logic_TypeDesc_ImageChoice: "画像タイルから選択",
    Logic_Type_Lookup: "リストからの参照",
    Logic_TypeDesc_Lookup: "別の SharePoint リストからリアルタイムで読み取ったオプション",
    Logic_Type_YesNo: "はい / いいえ",
    Logic_TypeDesc_YesNo: "シンプルなオン/オフの切り替え",
    Logic_Type_Consent: "同意",
    Logic_TypeDesc_Consent: "続行するには回答者がオンにする必要があるチェック ボックス",
    Logic_Type_Ranking: "ランク付け",
    Logic_TypeDesc_Ranking: "オプションをドラッグして優先順に並べ替え",
    Logic_Type_Rating: "評価",
    Logic_TypeDesc_Rating: "星、ハート、親指",
    Logic_Category_Scales: "スケール",
    Logic_Type_Scale: "意見スケール",
    Logic_TypeDesc_Scale: "両端にラベルのある数値スケール",
    Logic_Type_Slider: "スライダー",
    Logic_TypeDesc_Slider: "スライド式スケール上の値",
    Logic_Type_Likert: "リッカート グリッド",
    Logic_TypeDesc_Likert: "複数の記述を 1 つの共通スケールで評価",
    Logic_Type_Number: "数値",
    Logic_TypeDesc_Number: "標準、通貨、パーセンテージ",
    Logic_Category_Advanced: "詳細",
    Logic_Type_Calculated: "計算",
    Logic_TypeDesc_Calculated: "他の回答から計算される読み取り専用の合計",
    Logic_Type_Date: "日付",
    Logic_TypeDesc_Date: "カレンダーの日付 (時刻を含めることも可能)",
    Logic_Category_Date: "日付",
    Logic_Type_Time: "時刻",
    Logic_TypeDesc_Time: "時刻のみ",
    Logic_Type_Person: "ユーザー",
    Logic_TypeDesc_Person: "組織内のユーザーを選択",
    Logic_Category_People: "ユーザー",
    Logic_Type_Email: "メール",
    Logic_TypeDesc_Email: "検証されるメール アドレス",
    Logic_Type_Phone: "電話",
    Logic_TypeDesc_Phone: "検証される電話番号",
    Logic_Type_Address: "住所",
    Logic_TypeDesc_Address: "番地、市区町村、郵便番号、国",
    Logic_Type_Hyperlink: "リンク",
    Logic_TypeDesc_Hyperlink: "Web アドレス",
    Logic_Type_FileUpload: "ファイルのアップロード",
    Logic_TypeDesc_FileUpload: "回答に 1 つ以上のファイルを添付",
    Logic_Type_Signature: "署名",
    Logic_TypeDesc_Signature: "マウス、ペン、指で署名",
    Logic_Type_Content: "テキスト ブロック",
    Logic_TypeDesc_Content: "手順または画像 (回答は収集されません)",
    Logic_Category_Layout: "レイアウト",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "どのくらい推奨したいと思いますか…",
    Logic_Preset_satisfaction: "満足度 (1–5)",
    Logic_PresetDesc_satisfaction: "非常に不満から非常に満足まで",
    Logic_Preset_currency: "通貨",
    Logic_PresetDesc_currency: "金額",
    Logic_Preset_percent: "パーセンテージ",
    Logic_PresetDesc_percent: "パーセンテージの値",
    Logic_Template_blank_Name: "空白のフォーム",
    Logic_Template_blank_Description: "最初から作成",
    Logic_Template_feedback_Name: "顧客フィードバック",
    Logic_Template_feedback_Description: "NPS、評価、自由記述コメント",
    Logic_Template_event_Name: "イベント登録",
    Logic_Template_event_Description: "参加者の詳細、セッション、食事の要件",
    Logic_Template_itrequest_Name: "IT サービス リクエスト",
    Logic_Template_itrequest_Description: "優先度と添付ファイル付きの分類済みリクエスト",
    Logic_Template_expense_Name: "経費精算",
    Logic_Template_expense_Description: "明細項目、領収書、計算された合計",
    Logic_Template_pulse_Name: "従業員パルス サーベイ",
    Logic_Template_pulse_Description: "リッカート グリッド、エンゲージメント スケール、匿名性に関する注記",
    Logic_Template_safety_Name: "安全点検",
    Logic_Template_safety_Description: "チェックリスト、写真、署名",
    Logic_Template_booking_Name: "会議室またはリソースの予約",
    Logic_Template_booking_Description: "時間枠付きの、参照ベースのリソース ピッカー",
    Charts_ColumnChartAria: "{count} 個のカテゴリを含む縦棒グラフ",
    Charts_DonutChartAria: "{count} 個のカテゴリのドーナツ グラフ",
    Charts_NoAnswers: "回答はまだありません。",
    Charts_NoResponses: "回答はまだありません。",
    Charts_Responses: "回答",
    Charts_ResponsesOverTime: "回答数の推移",
    Responses_Chart_Answer: "回答",
    Responses_Chart_Average: "平均",
    Responses_Chart_AverageOf: "{count} 件の平均",
    Responses_Chart_AveragePosition: "平均順位",
    Responses_Chart_AverageRange: "平均 (1～{max})",
    Responses_Chart_AvgValue: "平均 {value}",
    Responses_Chart_Detractors: "批判者 (0～6)",
    Responses_Chart_Max: "最大",
    Responses_Chart_Maximum: "最大値",
    Responses_Chart_Median: "中央値",
    Responses_Chart_MentionOne: "{count} 件の言及",
    Responses_Chart_MentionOther: "{count} 件の言及",
    Responses_Chart_Min: "最小",
    Responses_Chart_Minimum: "最小値",
    Responses_Chart_NoAnswers: "回答はまだありません。",
    Responses_Chart_NoNumeric: "数値の回答はまだありません。",
    Responses_Chart_NoRankings: "ランキングはまだありません。",
    Responses_Chart_NoScores: "スコアはまだありません。",
    Responses_Chart_NotEnoughText: "要約するにはテキストが足りません。",
    Responses_Chart_NpsScore: "NPS スコア",
    Responses_Chart_Option: "オプション",
    Responses_Chart_Passives: "中立者 (7～8)",
    Responses_Chart_Promoters: "推奨者 (9～10)",
    Responses_Chart_ResponseOne: "回答",
    Responses_Chart_ResponseOther: "回答",
    Responses_Chart_Responses: "回答",
    Responses_Chart_ShowingAnswers: "{total} 件中 {shown} 件の回答を表示しています。",
    Responses_Chart_Statement: "ステートメント",
    Responses_Chart_Statistic: "統計",
    Responses_Chart_StdDev: "標準偏差",
    Responses_Chart_StdDeviation: "標準偏差",
    Responses_Chart_Total: "合計",
    Responses_Chart_Value: "値",
    Responses_Dashboard_AllHidden: "すべての質問がダッシュボードで非表示になっています。「非表示の質問を表示」を使用すると元に戻せます。",
    Responses_Dashboard_AnsweredOf: "{total} 件中 {answered} 件が回答済み",
    Responses_Dashboard_AnsweredOfPinned: "{total} 件中 {answered} 件が回答済み · ピン留め済み",
    Responses_Dashboard_AveragedAcrossResponses: "全回答の平均",
    Responses_Dashboard_ByDay: "日別",
    Responses_Dashboard_ByMonth: "月別",
    Responses_Dashboard_ByWeek: "週別",
    Responses_Dashboard_ChartAuto: "自動",
    Responses_Dashboard_ChartBars: "横棒",
    Responses_Dashboard_ChartColumns: "縦棒",
    Responses_Dashboard_ChartDonut: "ドーナツ",
    Responses_Dashboard_ChartGauge: "ゲージ",
    Responses_Dashboard_ChartHistogram: "ヒストグラム",
    Responses_Dashboard_ChartOptions: "グラフのオプション",
    Responses_Dashboard_ChartOptionsFor: "{title} のグラフのオプション",
    Responses_Dashboard_ChartStatistics: "統計",
    Responses_Dashboard_ChartTable: "テーブル",
    Responses_Dashboard_ChartWordFrequency: "単語の出現頻度",
    Responses_Dashboard_EmptyBody: "回答が集まり始めると、このダッシュボードには主要な数値、回答のタイムライン、注目すべき質問のグラフが自動的に表示されます。",
    Responses_Dashboard_EmptyTitle: "回答はまだありません",
    Responses_Dashboard_Hide: "ダッシュボードから非表示",
    Responses_Dashboard_Highlights: "ハイライト",
    Responses_Dashboard_Last7Days: "過去 7 日間",
    Responses_Dashboard_LatestDate: "最新: {date}",
    Responses_Dashboard_MedianTimeToComplete: "回答完了までの所要時間 (中央値)",
    Responses_Dashboard_NoPriorWeek: "比較できる前の週がありません",
    Responses_Dashboard_OneEach: "各 1 件",
    Responses_Dashboard_Pin: "ダッシュボードにピン留め",
    Responses_Dashboard_QuestionFallback: "質問",
    Responses_Dashboard_QuestionsAnswered: "回答済みの質問",
    Responses_Dashboard_RecordedOnSubmit: "送信時に記録",
    Responses_Dashboard_RepeatResponses: "{count} 件の重複回答",
    Responses_Dashboard_ResponsesOverTime: "回答数の推移",
    Responses_Dashboard_ShowHidden: "非表示の質問を表示",
    Responses_Dashboard_SinceMidnight: "午前 0 時から",
    Responses_Dashboard_Today: "今日",
    Responses_Dashboard_TotalResponses: "回答の合計",
    Responses_Dashboard_UniqueRespondents: "回答者数 (重複なし)",
    Responses_Dashboard_Unpin: "ダッシュボードのピン留めを外す",
    Responses_Dashboard_UntitledQuestion: "タイトルなしの質問",
    Responses_Dashboard_VsPrevious7Days: "前の 7 日間との比較",
    Responses_Detail_Answers: "回答内容",
    Responses_Detail_AsTheForm: "フォームの表示形式",
    Responses_Detail_Cancel: "キャンセル",
    Responses_Detail_Delete: "削除",
    Responses_Detail_DeleteBody: "リスト アイテムはサイトのごみ箱に移動されるため、そこから復元できます。",
    Responses_Detail_DeleteTitle: "この回答を削除しますか?",
    Responses_Detail_Deleting: "削除中…",
    Responses_Detail_Draft: "下書き",
    Responses_Detail_Header: "回答 {index}/{total}",
    Responses_Detail_LoadingAttachments: "添付ファイルを読み込んでいます…",
    Responses_Detail_Next: "次の回答",
    Responses_Detail_NoAnswer: "回答なし",
    Responses_Detail_Previous: "前の回答",
    Responses_Detail_Print: "印刷",
    Responses_Detail_Signature: "署名",
    Responses_Detail_Signed: "署名済み",
    Responses_Detail_Took: "所要時間: {duration}",
    Responses_Summary_AnsweredOfType: "{total} 件中 {answered} 件が回答済み · {type}",
    Responses_Summary_ByField: "{title} 別",
    Responses_Summary_CompareBy: "比較の基準…",
    Responses_Summary_EmptyBody: "各質問の要約がここに表示されます。",
    Responses_Summary_NoComparison: "比較しない",
    Responses_Summary_NothingToCompare: "「{title}」に回答した人がいないため、比較するものがありません。",
    Responses_Summary_OtherNote: "カテゴリが {max} 個を超えるグラフでは、小さいものが「その他」にまとめられます。すべての値を表示するには、カードを [テーブル] に切り替えてください。",
    Responses_Summary_ResponseCountOne: "{count} 件の回答",
    Responses_Summary_ResponseCountOther: "{count} 件の回答",
    Responses_Summary_SeeAllAnswers: "すべての回答をテーブルで表示",
    Responses_Summary_SegmentNote: "最も大きい {groups} 個のグループを表示しています。複数の回答を選択した回答は該当するすべてのグループに表示されるため、グループの合計が {total} を超えることがあります。",
    Responses_Summary_SplitBy: "{title} で分割",
    Responses_Summary_Untitled: "タイトルなし",
    Responses_Table_Apply: "適用",
    Responses_Table_Cancel: "キャンセル",
    Responses_Table_ClearSelection: "選択を解除",
    Responses_Table_ColumnOrder: "列の順序",
    Responses_Table_ColumnsCount: "列 ({shown}/{total})",
    Responses_Table_Delete: "削除",
    Responses_Table_DeleteBody: "リスト アイテムはサイトのごみ箱に移動されるため、そこから復元できます。",
    Responses_Table_DeleteSelected: "選択したものを削除",
    Responses_Table_DeleteTitleOne: "{count} 件の回答を削除しますか?",
    Responses_Table_DeleteTitleOther: "{count} 件の回答を削除しますか?",
    Responses_Table_Deleting: "削除中…",
    Responses_Table_MoveDown: "下へ移動",
    Responses_Table_MoveDownFor: "{title} を下へ移動",
    Responses_Table_MoveUp: "上へ移動",
    Responses_Table_MoveUpFor: "{title} を上へ移動",
    Responses_Table_NoColumns: "表示されている質問の列はまだありません。",
    Responses_Table_NoMatch: "現在のフィルターに一致する回答はありません。",
    Responses_Table_NothingToShow: "表示するものがありません",
    Responses_Table_OpenResponse: "この回答を開く",
    Responses_Table_OrderNote: "「送信日時」と「送信者」は常に先頭に表示されます。ドラッグした順序は質問の列に適用されます。",
    Responses_Table_Reorder: "並べ替え",
    Responses_Table_ResetColumns: "列をリセット",
    Responses_Table_SelectResponse: "この回答を選択",
    Responses_Table_SelectedOne: "{count} 件の回答を選択中",
    Responses_Table_SelectedOther: "{count} 件の回答を選択中",
    Responses_Table_ShowAll: "すべて表示",
    Responses_Table_ShowTheseQuestions: "これらの質問を表示",
    Responses_Table_Submitted: "送信日時",
    Responses_Table_SubmittedBy: "送信者",
    Responses_Table_ToggleSelection: "選択の切り替え",
    Responses_Table_Unknown: "不明",
    Responses_Table_Untitled: "タイトルなし",
    Responses_View_AllTime: "全期間",
    Responses_View_AnyAnswer: "すべての回答",
    Responses_View_Clear: "クリア",
    Responses_View_CopyShareLink: "共有リンクをコピー",
    Responses_View_CountFiltered: "{total} 件中 {shown} 件の回答",
    Responses_View_CountOne: "{count} 件の回答",
    Responses_View_CountOther: "{count} 件の回答",
    Responses_View_Dashboard: "ダッシュボード",
    Responses_View_DateRange: "期間",
    Responses_View_EmptyBody: "フォームを共有して回答の収集を開始しましょう。回答は「{list}」に保存され、すぐにここに表示されます。",
    Responses_View_EmptyTitle: "回答はまだありません",
    Responses_View_ExportCsv: "CSV にエクスポート",
    Responses_View_FilterByAnswer: "回答で絞り込み",
    Responses_View_FilterByQuestion: "質問で絞り込み",
    Responses_View_FilterValue: "フィルター値",
    Responses_View_Last30Days: "過去 30 日間",
    Responses_View_Last7Days: "過去 7 日間",
    Responses_View_Last90Days: "過去 90 日間",
    Responses_View_LoadError: "回答を読み込めませんでした。リスト列が作成されるようにフォームを一度公開してから、もう一度お試しください。",
    Responses_View_Loading: "回答を読み込んでいます…",
    Responses_View_MoreActions: "回答のその他の操作",
    Responses_View_PreviewForm: "フォームをプレビュー",
    Responses_View_Refresh: "更新",
    Responses_View_ResponsesTab: "回答 ({count})",
    Responses_View_SearchPlaceholder: "すべての回答を検索",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "値を選択",
    Responses_View_Summary: "概要",
    Responses_View_Today: "今日",
    Responses_View_Truncated: "このリストには、Smart Forms が一度に読み込める数を超える回答があります。最新の {count} 件を表示しています。すべての回答を確認するには、Microsoft Lists でリストを開いてください。",
    Responses_View_TryAgain: "もう一度実行",
    Responses_View_Untitled: "タイトルなし",
    Responses_Approval_Column: "承認",
    Responses_Approval_ReviewerColumn: "レビュー担当者",
    Responses_Approval_CommentColumn: "レビュー担当者のコメント",
    Responses_Approval_Pending: "保留中",
    Responses_Approval_Approved: "承認済み",
    Responses_Approval_Rejected: "却下",
    Responses_Approval_AnyStatus: "すべての承認状態",
    Responses_Approval_FilterLabel: "承認状態で絞り込み",
    Responses_Approval_ApproveSelected: "選択項目を承認",
    Responses_Approval_RejectSelected: "選択項目を却下",
    Responses_Approval_BulkFailed: "{count} 件の回答を更新できませんでした。もう一度お試しください。",
    Responses_Approval_Approve: "承認",
    Responses_Approval_Reject: "却下",
    Responses_Approval_Reset: "保留中に戻す",
    Responses_Approval_CommentLabel: "コメント (省略可)",
    Responses_Approval_ReviewedBy: "レビュー担当者: {name}",
    Responses_Approval_Error: "決定を保存できませんでした。もう一度お試しください。",
    Responses_Dashboard_ApprovalStatus: "レビュー待ち",
    Responses_Dashboard_ApprovalBreakdown: "保留中 {pending} 件、承認済み {approved} 件、却下 {rejected} 件",
    Responses_Dashboard_TimelineCoarsened: "日付範囲が長いため、タイムラインはより大まかにグループ化されました ({grain})。",
    Responses_Dashboard_TimelineTruncated: "日付範囲が非常に長いため、直近の {count} 期間のみを表示しています。",
    Service_Item_DefaultTitle: "回答 — {date}",
    Service_Email_ApprovalSubject: "回答が{status} — {title}",
    Service_Email_ApprovalHeading: "回答が{status}",
    Service_Email_ApprovalIntro: "「{title}」への回答は、レビュー担当者により{status}。",
    Service_Email_ApprovalCommentLabel: "レビュー担当者のコメント",
    Service_Approval_Approved: "承認されました",
    Service_Approval_Rejected: "却下されました",
    Service_Approval_Pending: "保留中です",
    Service_Lookup_InvalidFilter: "参照フィルターが無効です。",
    Service_Edit_NotAllowed: "このフォームでは、送信済みの回答を編集できません。",
    Service_Edit_NotYours: "編集できるのは自分の回答のみです。",
    Service_Signature_AttachmentLabel: "署名",
    PropertyPane_ListsLoadFailed: "このサイトのリストを読み込めませんでした。",
    PropertyPane_EnterListName: "先に新しいリストの名前を入力してください。",
    PropertyPane_CreatingList: "「{name}」を作成しています…",
    PropertyPane_ListCreated: "リスト「{title}」を作成して選択しました。",
    PropertyPane_ListAlreadyExists: "「{name}」という名前のリストは既に存在します。上のドロップダウンから選択してください。",
    PropertyPane_CreateListFailed: "リストを作成できませんでした。このサイトでリストを作成する権限があることを確認してください。",
    PropertyPane_Description: "フォームの回答を保存する SharePoint リストを選択するか、新しく作成します。それ以外の項目 (質問、外観、通知) は、ページ上で直接編集します。",
    PropertyPane_ResponseList_GroupName: "回答リスト",
    PropertyPane_ListDropdown_Label: "回答をこのリストに保存",
    PropertyPane_ResponsesGoTo: "回答は「{name}」に保存されます。",
    PropertyPane_PickList: "リストを選択するか、下で作成してください。",
    PropertyPane_LoadingLists: "リストを読み込んでいます…",
    PropertyPane_NewListName_Label: "または新しいリストを作成",
    PropertyPane_NewListName_Placeholder: "新しいリスト名",
    PropertyPane_CreateList_Button: "リストを作成",
    PropertyPane_Tips_GroupName: "ヒント",
    PropertyPane_Tip_AutoSave: "質問と設定は編集するたびに自動的に保存されます。ページを保存または公開する必要はありません。",
    PropertyPane_Tip_Permissions: "回答者には、回答リストにアイテムを追加する権限が必要です。送信時にエラーが発生したという報告があった場合は、リストのアクセス許可を確認してください。",
    PropertyPane_Tip_Share: "ページの「回答を収集」を使用すると、リスト列が作成され、共有可能な回答用リンクを取得できます。",
    App_ErrorBoundary_Title: "Smart Forms — レンダリング エラー",
    App_ErrorBoundary_Message: "メッセージ:",
    App_ErrorBoundary_Stack: "スタック:",
    App_ErrorBoundary_NoStack: "(利用可能なスタックがありません)",
    App_ErrorBoundary_ConsoleNote: "完全な詳細はブラウザーのコンソールにも書き込まれました。",
    App_DefaultQuestionTitle: "質問 {number}",
    App_Error_ListMissing: "このフォームに構成されているリストは存在しなくなりました。Web パーツの設定で別のリストを選択してください。",
    App_Error_LoadConfig: "フォームの構成の読み込み中に問題が発生しました。",
    App_Error_Unable: "フォームを読み込めません。",
    App_Publish_ConflictNotice: "「{title}」には、種類が異なるリスト列 ({type}) が既にあります。新しい列を作成できるように質問の名前を変更するか、種類を元に戻してください。",
    App_Publish_ConflictUnnamedQuestion: "質問",
    App_Publish_ColumnsAddedOne: "「{list}」に {count} 個の列を追加しました。",
    App_Publish_ColumnsAddedOther: "「{list}」に {count} 個の列を追加しました。",
    App_Publish_TheList: "リスト",
    App_Publish_UpToDate: "回答リストは既に最新の状態です。",
    App_Publish_Error: "リスト列を作成できませんでした。通常は、回答リストに対する [リストの管理] 権限がないことが原因ですが、カスタム スクリプトが無効になっているサイトでも発生することがあります。ブラウザーのコンソールで根本的なエラーを確認するか、もう一度お試しください。",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "SharePoint リストを基盤にして、洗練されたフォームを作成できます。{count} 種類の質問、分岐ロジック、ファイル アップロード、共有可能な回答用リンク、結果ダッシュボードを備えています。",
    App_Placeholder_ChooseList: "リストを選択または作成",
    App_Placeholder_Hint: "開始するには、ページを編集してこの Web パーツを構成してください。",
    App_Loading: "フォームを読み込んでいます…",
    App_OpenSettings: "設定を開く",
    App_Tab_Questions: "質問",
    App_Tab_QuestionsWithCount: "質問 ({count})",
    App_Tab_Responses: "回答",
    App_Tab_Responses_Title: "回答は「{list}」に保存されます",
    App_Templates_Start: "テンプレートから開始",
    App_Settings_Title: "フォームの設定 — 外観、通知、アクセス",
    App_Settings_AriaLabel: "フォームの設定",
    App_Preview: "プレビュー",
    App_Preview_Close: "プレビューを閉じる",
    App_Preview_Hint: "プレビュー — ここで送信した内容は保存されません。検証と分岐は、回答者の場合とまったく同じように動作します。",
    App_Publish_GettingReady: "準備しています…",
    App_Publish_CollectResponses: "回答を収集",
    App_Publish_Share: "共有",
    App_Retry: "再試行",
    App_SaveError_Banner: "最後の変更を保存できませんでした。接続を確認して、もう一度お試しください。",
    App_Preflight_BlockingTitle: "回答の収集前に修正してください",
    App_Preflight_WarningTitle: "事前に確認したい項目",
    App_Preflight_BlockingText: "これらの問題があると、公開したフォームが正常に動作しません。",
    App_Preflight_WarningText: "問題はありませんが、リンクを共有する前に修正しておくことをお勧めします。",
    App_Preflight_GoTo: "移動",
    App_Preflight_CollectAnyway: "そのまま回答を収集",
    App_Preflight_Back: "フォームに戻る",
    App_Cancel: "キャンセル",
    App_Done: "完了",
    App_Share_Title: "フォームを共有する準備ができました",
    App_Share_SubText: "フォームに回答する人にこのリンクを送信してください。",
    App_Share_LinkAriaLabel: "共有リンク",
    App_Share_Copy: "コピー",
    App_Share_Copied: "コピーしました",
    App_Share_AddItemsEmphasis: "アイテムを追加",
    App_Share_PermissionNote: "回答者には、「{title}」に{addItems}する権限と、このページへのアクセス権が必要です。送信時にエラーが発生する場合は、ほとんどの場合これが原因です。",
    App_Share_PrefillNote: "列名を追加すると、リンク内で質問に事前に回答しておくことができます (例: {example})。",
    App_Templates_ReplaceWarning: "テンプレートを選択すると、現在の質問は置き換えられます。",
    App_Templates_PickStart: "開始点を選択してください。後からすべて変更できます。",
    App_Templates_Empty: "空白",
    App_Templates_QuestionCount: "{count} 件の質問",
    App_SaveChip_SavingTitle: "最新の編集を保存しています",
    App_SaveChip_Saving: "保存中…",
    App_SaveChip_FailedTitle: "最後の編集を保存できませんでした。接続を確認して、もう一度お試しください。",
    App_SaveChip_Failed: "保存に失敗",
    App_SaveChip_SavedTitle: "すべての変更が保存されました",
    App_SaveChip_Saved: "保存済み",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "新しい回答 — {title}",
    Service_Email_NewResponseHeading: "新しい回答: {title}",
    Service_Email_NewResponseIntro: "回答が送信されました — {date}。",
    Service_Email_ReceiptSubject: "回答の控え — {title}",
    Service_Email_ReceiptHeading: "ご回答ありがとうございます。",
    Service_Email_ReceiptIntro: "「{title}」に送信した内容のコピーです。",
    App_History_Title: "バージョン履歴",
    App_History_RestoredNotice: "{date} に保存されたバージョンを復元しました。内容を確認し、[回答を収集] を使用して新しい質問を発行してください。",
    App_History_Undo: "復元を元に戻す",
    App_Share_CopyManual: "ブラウザーによりコピーがブロックされました。上のリンクを選択し、Ctrl+C (Mac では Cmd+C) を押してコピーしてください。",
    App_Share_TeamsNote: "Microsoft Teams を使用しています。このリンクは SharePoint ページを直接開くため、受信者にはサイトへのアクセス権が必要です。",
    App_Share_PrefillNotSecure: "事前入力された回答は利便性のためだけのものです。リンクを知っていれば誰でも変更できるため、セキュリティ境界として扱わないでください。",
    Designer_Section_DropHere: "ここに質問をドロップ",
    Designer_Section_DropEnd: "ここにドロップしてこのセクションの末尾に移動",
    Designer_Rules_RemovedOne: "適合しなくなった分岐ルール 1 件を削除しました。",
    Designer_Rules_RemovedOther: "適合しなくなった分岐ルール {count} 件を削除しました。",
    Designer_Settings_AllowEdit: "回答者による回答の編集を許可する",
    Designer_Settings_AllowEditHint: "回答者は送信した内容を再度開いて更新できます。編集できるのは各自の回答のみです。",
    Designer_Settings_EnableApproval: "承認ワークフローを有効にする",
    Designer_Settings_ApprovalNotify: "決定時に回答者にメールを送信する",
    Designer_Settings_ApprovalHint: "次回の発行時に、回答リストに承認列が追加されます。所有者は [回答] タブから回答を承認または却下できます。",
    Designer_History_Title: "バージョン履歴",
    Designer_History_Intro: "このフォームの質問と設定の過去に保存されたバージョンです。復元するとバージョンがデザイナーに読み込まれます。元に戻すことができ、新しい質問は発行時にのみ作成されます。",
    Designer_History_Loading: "バージョンを読み込んでいます...",
    Designer_History_Empty: "以前のバージョンが見つかりませんでした。バージョン履歴を使用するには、\"Smart Forms Config\" リストでバージョン管理を有効にし、保存済みの編集が 1 回以上必要です。",
    Designer_History_Latest: "最新",
    Designer_History_LatestTitle: "これは現在使用中のバージョンです",
    Designer_History_By: "作成者: {name}",
    Designer_History_UnknownAuthor: "作成者不明",
    Designer_History_VersionLabel: "バージョン {label}",
    Designer_History_Preview: "プレビュー",
    Designer_History_Restore: "復元",
    Designer_History_QuestionsOne: "質問 1 件",
    Designer_History_QuestionsOther: "質問 {count} 件",
    Designer_History_LoadFailed: "このバージョンを読み込めませんでした。",
    Designer_History_ConfirmTitle: "このバージョンを復元しますか?",
    Designer_History_ConfirmText: "フォームは {date} に保存されたバージョン (質問 {count} 件) に置き換えられます。直後であれば元に戻せます。"
  };
});
