define([], function () {
  return {
    Designer_Color_Blue: "파랑",
    Designer_Color_Teal: "청록",
    Designer_Color_Green: "초록",
    Designer_Color_Purple: "보라",
    Designer_Color_Magenta: "마젠타",
    Designer_Color_Red: "빨강",
    Designer_Color_Orange: "주황",
    Designer_Color_Gray: "회색",
    Designer_Settings_LayoutSinglePage: "모든 질문을 한 페이지에 표시",
    Designer_Settings_LayoutWizard: "단계별로 섹션 하나씩(마법사)",
    Designer_Settings_Title: "양식 설정",
    Designer_Common_Apply: "적용",
    Designer_Common_Cancel: "취소",
    Designer_Settings_TabBasics: "기본",
    Designer_Settings_FormTitle: "양식 제목",
    Designer_Settings_Description: "설명",
    Designer_Settings_Layout: "레이아웃",
    Designer_Settings_NumberQuestions: "질문에 번호 매기기",
    Designer_Settings_ShuffleQuestions: "응답자마다 질문 순서 섞기",
    Designer_Settings_ShowProgressBar: "진행률 표시줄 표시",
    Designer_Settings_TabAppearance: "모양",
    Designer_Settings_AccentColor: "강조 색",
    Designer_Settings_CustomColorTitle: "사용자 지정 색",
    Designer_Settings_CustomColorAria: "사용자 지정 강조 색",
    Designer_Settings_AccentHint: "강조 색은 어두운 사이트에서 대비가 유지되도록 자동으로 조정되므로 페이지 테마와 관계없이 양식을 읽기 쉽게 유지합니다.",
    Designer_Settings_ShowHeader: "양식 머리글 표시",
    Designer_Settings_HeaderIcon: "머리글 아이콘",
    Designer_Settings_TabAfterSubmit: "제출 후",
    Designer_Settings_SubmitButtonText: "제출 단추 텍스트",
    Designer_Settings_SubmitPlaceholder: "제출",
    Designer_Settings_ThankYouTitle: "감사 제목",
    Designer_Settings_ThankYouPlaceholder: "감사합니다!",
    Designer_Settings_ThankYouMessage: "감사 메시지",
    Designer_Settings_ShowSubmitAnother: "\"다른 응답 제출\" 단추 표시",
    Designer_Settings_TabNotifications: "알림",
    Designer_Settings_EmailEachResponseTo: "각 응답을 이메일로 보낼 대상",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "조직의 사용자는 목록 항목에 대한 링크가 포함된 모든 응답을 이메일로 받습니다",
    Designer_Settings_RespondentReceipt: "응답자에게 답변 사본을 이메일로 보내기",
    Designer_Settings_NotificationsInfo: "알림은 SharePoint 자체 메일 서비스를 사용하므로 받는 사람은 조직의 사용자여야 합니다. 외부 주소는 알림 없이 삭제됩니다.",
    Designer_Settings_TabAccess: "액세스",
    Designer_Settings_OpenFrom: "시작 시간",
    Designer_Settings_OpenImmediately: "즉시 열기",
    Designer_Settings_CloseAfter: "종료 시간",
    Designer_Settings_NeverClose: "닫지 않음",
    Designer_Settings_ClearDates: "날짜 지우기",
    Designer_Settings_DatesInverted: "종료 날짜가 시작 날짜와 같거나 그 이전이므로 양식에서 응답을 받을 수 없습니다.",
    Designer_Settings_MaxResponses: "응답 수가 이 값에 도달하면 중지",
    Designer_Settings_NoLimit: "제한 없음",
    Designer_Settings_OneResponsePerPerson: "한 사람당 응답을 한 번만 허용",
    Designer_Settings_AllowSaveDraft: "응답자가 초안을 저장하고 나중에 완료할 수 있도록 허용",
    Designer_Settings_ClosedMessage: "양식이 닫혔을 때 표시할 메시지",
    Designer_Settings_ClosedMessagePlaceholder: "이 양식은 더 이상 응답을 받지 않습니다.",
    Designer_Settings_AccessInfo: "이러한 제한은 SharePoint가 아니라 양식에서 적용합니다. 응답 목록에 항목을 추가할 권한이 있는 사용자는 목록을 통해 직접 항목을 추가할 수 있습니다.",
    Designer_Field_StyleInfo: "정보(강조)",
    Designer_Field_StyleSuccess: "성공(초록)",
    Designer_Field_StyleWarning: "경고(황갈색)",
    Designer_Field_StylePlain: "일반 텍스트",
    Designer_Field_StyleDivider: "구분선",
    Designer_Field_IconStars: "별",
    Designer_Field_IconHearts: "하트",
    Designer_Field_IconThumbs: "좋아요",
    Designer_Field_FormatPlain: "일반 숫자",
    Designer_Field_FormatCurrency: "통화",
    Designer_Field_FormatPercent: "백분율",
    Designer_Field_UntitledQuestion: "제목 없는 질문",
    Designer_Field_DeletedQuestion: "삭제된 질문",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} 및 {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "또는",
    Designer_Rule_JoinAll: "및",
    Designer_Rule_Preview: "{conditions}일 때 표시됩니다.",
    Designer_Field_Yes: "예",
    Designer_Field_No: "아니요",
    Designer_Field_When: "조건",
    Designer_Field_SelectValue: "값 선택",
    Designer_Field_DateValuePlaceholder: "YYYY-MM-DD 또는 \"today\"",
    Designer_Field_ValuePlaceholder: "값",
    Designer_Field_UpperBound: "상한",
    Designer_Field_RemoveCondition: "이 조건 제거",
    Designer_Field_FormulaInvalid: "이 수식을 계산할 수 없습니다. 괄호와 연산자를 확인하세요.",
    Designer_Field_FormulaMissing: "다음 질문이 존재하지 않습니다: {names}.",
    Designer_Field_FormulaPreview: "모든 입력이 10이면 {value}이(가) 표시됩니다.",
    Designer_Field_HintYesNo: "\"yes\" 또는 \"no\" 사용",
    Designer_Field_HintMultiDefault: "여러 기본값은 ;로 구분",
    Designer_Field_HintSingleDefault: "옵션 중 하나와 일치해야 함",
    Designer_Field_HintDate: "\"today\" 또는 2026-03-01 같은 날짜 사용",
    Designer_Field_HintTime: "\"now\" 또는 09:30 같은 시간 사용",
    Designer_Field_QuestionSettings: "질문 설정",
    Designer_Field_Appearance: "모양",
    Designer_Field_Style: "스타일",
    Designer_Field_ImageUrl: "이미지 URL(선택 사항)",
    Designer_Field_Content: "콘텐츠",
    Designer_Field_BasicFormatting: "굵게, 기울임꼴, 목록, 링크 등 기본 서식을 사용할 수 있습니다.",
    Designer_Field_TabOptions: "옵션",
    Designer_Field_TabBranching: "분기",
    Designer_Field_BranchingNeedsQuestion: "먼저 다른 질문을 추가하세요. 분기에는 기준이 될 질문이 필요합니다.",
    Designer_Field_BranchingToggle: "다른 답변이 일치할 때만 이 질문 표시",
    Designer_Field_Match: "일치 조건",
    Designer_Field_MatchAll: "모두",
    Designer_Field_MatchAny: "하나 이상",
    Designer_Field_AddCondition: "조건 추가",
    Designer_Field_TabValidation: "유효성 검사",
    Designer_Field_HelpText: "도움말 텍스트",
    Designer_Field_HelpTextPlaceholder: "질문 레이블 아래에 표시됨",
    Designer_Field_CheckboxLabel: "확인란 레이블",
    Designer_Field_Placeholder: "자리 표시자",
    Designer_Field_DefaultAnswer: "기본 답변",
    Designer_Field_RequiredMessage: "사용자 지정 필수 메시지",
    Designer_Field_RequiredMessagePlaceholder: "{title}은(는) 필수입니다",
    Designer_Field_ThisQuestion: "이 질문",
    Designer_Field_RequiredMessageDescription: "이 질문이 비어 있을 때 표준 메시지 대신 표시됩니다",
    Designer_Field_ReadOnly: "읽기 전용(미리 채워진 링크로만 답변 가능)",
    Designer_Field_ValidationRules: "유효성 검사 규칙",
    Designer_Field_MaxLength: "최대 길이",
    Designer_Field_Pattern: "이 패턴과 일치해야 함",
    Designer_Field_PatternDescription: "정규식입니다. 패턴을 확인하지 않으려면 비워 두세요.",
    Designer_Field_PatternMessage: "패턴이 일치하지 않을 때의 메시지",
    Designer_Field_PatternMessagePlaceholder: "이 답변이 예상 형식이 아닙니다",
    Designer_Field_Format: "형식",
    Designer_Field_UnitSuffix: "값 뒤에 표시할 단위",
    Designer_Field_UnitSuffixPlaceholder: "kg, 시간, 개…",
    Designer_Field_Minimum: "최소값",
    Designer_Field_Maximum: "최대값",
    Designer_Field_Decimals: "소수 자릿수",
    Designer_Field_Formula: "수식",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "다른 질문은 질문 텍스트를 중괄호로 묶어 참조합니다. + - * / ( ) 및 round, min, max, sum, avg를 지원합니다.",
    Designer_Field_AvailableQuestions: "사용 가능한 질문: {questions}",
    Designer_Field_NoneYet: "아직 없음",
    Designer_Field_Step: "단계",
    Designer_Field_From: "시작",
    Designer_Field_To: "끝",
    Designer_Field_LowLabel: "낮은 쪽 레이블",
    Designer_Field_LowLabelPlaceholder: "전혀 그렇지 않음",
    Designer_Field_HighLabel: "높은 쪽 레이블",
    Designer_Field_HighLabelPlaceholder: "매우 그렇다",
    Designer_Field_SummarizeAs: "요약 방식",
    Designer_Field_SummarizeAverage: "평균 및 분포",
    Designer_Field_SummarizeNps: "Net Promoter Score(0–10 척도 필요)",
    Designer_Field_NpsWarning: "Net Promoter Score는 0–10 척도에서만 의미가 있습니다. 시작을 0으로, 끝을 10으로 설정하세요.",
    Designer_Field_NumberOfIcons: "아이콘 수",
    Designer_Field_Icon: "아이콘",
    Designer_Field_AllowHalf: "절반 값 허용",
    Designer_Field_ShowOptionsAs: "옵션 표시 방식",
    Designer_Field_DisplayButtons: "인라인 단추",
    Designer_Field_DisplayDropdown: "드롭다운",
    Designer_Field_DisplayAutomatic: "자동(옵션 6개까지 인라인)",
    Designer_Field_AllowOther: "직접 입력하는 \"기타\" 옵션 추가",
    Designer_Field_OtherLabel: "\"기타\" 옵션의 레이블",
    Designer_Field_OtherPlaceholder: "기타",
    Designer_Field_ShuffleOptions: "응답자마다 옵션 순서 섞기",
    Designer_Field_MinSelections: "최소 선택 수",
    Designer_Field_MaxSelections: "최대 선택 수",
    Designer_Field_SourceList: "원본 목록",
    Designer_Field_ChooseList: "목록 선택",
    Designer_Field_LookupColumn: "옵션을 읽어올 열",
    Designer_Field_ChooseColumn: "열 선택",
    Designer_Field_ChooseListFirst: "먼저 목록을 선택하세요",
    Designer_Field_LookupFilter: "필터(선택 사항)",
    Designer_Field_LookupFilterDescription: "옵션이 될 원본 항목을 좁히는 OData 필터",
    Designer_Field_LookupInfo: "답변에는 원본 항목에 대한 링크가 아니라 옵션 텍스트가 저장되므로 나중에 원본 목록이 변경되어도 응답을 계속 읽을 수 있습니다.",
    Designer_Field_ConsentText: "확인란 위에 표시할 약관",
    Designer_Field_AllowMultiplePeople: "여러 사용자 허용",
    Designer_Field_AllowGroups: "그룹도 허용",
    Designer_Field_IncludeTime: "시간 포함",
    Designer_Field_TimeStep: "시간 간격(분)",
    Designer_Field_MaxFiles: "최대 파일 수",
    Designer_Field_MaxFileSize: "파일당 최대 크기(MB)",
    Designer_Field_AcceptedTypes: "허용되는 파일 형식",
    Designer_Field_AcceptedTypesDescription: "확장명을 쉼표로 구분합니다. SharePoint에서 허용하는 모든 파일을 받으려면 비워 두세요.",
    Designer_Field_FilesInfo: "파일은 응답 항목의 첨부 파일로 저장됩니다. SharePoint는 여기서 허용한 내용과 관계없이 일부 확장명(예: .exe)을 차단합니다.",
    Designer_Field_Rows: "행",
    Designer_Field_ProvisionedNote: "이 질문에는 이미 목록 열({name})이 있습니다. 열 형식을 변경하는 설정은 잠겨 있습니다. 다른 형식이 필요하면 질문을 복제하세요.",
    Designer_Category_Text: "텍스트",
    Designer_Category_Choice: "선택",
    Designer_Category_Scales: "척도",
    Designer_Category_Date: "날짜",
    Designer_Category_People: "사용자",
    Designer_Category_Advanced: "고급",
    Designer_Category_Layout: "레이아웃",
    Designer_Menu_CommonPresets: "일반 사전 설정",
    Designer_Menu_AllTypes: "모든 질문 유형",
    Designer_Menu_ChangeType: "유형 변경",
    Designer_Menu_TypeLockedTitle: "목록 열이 이미 있으므로 유형이 잠겨 있습니다. 변경하려면 질문을 복제하세요.",
    Designer_Menu_MoreSettings: "분기, 유효성 검사 등",
    Designer_Menu_InsertBelow: "아래에 질문 삽입",
    Designer_Card_Duplicate: "복제",
    Designer_Card_DeleteQuestion: "질문 삭제",
    Designer_Outline_Aria: "질문 개요",
    Designer_Outline_QuestionCountOne: "질문 {count}개",
    Designer_Outline_QuestionCountOther: "질문 {count}개",
    Designer_Outline_IssuesTitle: "검토할 문제 {count}개",
    Designer_Outline_Find: "질문 찾기",
    Designer_Outline_Empty: "아직 질문이 없습니다.",
    Designer_Section_DefaultTitle: "섹션 {number}",
    Designer_Card_Question: "질문",
    Designer_Card_BranchingTitle: "이 질문은 분기 규칙이 일치할 때만 표시됩니다",
    Designer_Card_BranchingChip: "분기",
    Designer_Card_LiveTitle: "목록 열이 있으므로 유형이 잠겨 있습니다",
    Designer_Card_LiveChip: "사용 중",
    Designer_Card_CheckChip: "확인",
    Designer_Option_Placeholder: "옵션 {number}",
    Designer_Option_LabelAria: "옵션 {number} 레이블",
    Designer_Option_ImageUrl: "이미지 URL",
    Designer_Option_ImageUrlAria: "옵션 {number} 이미지 URL",
    Designer_Option_Remove: "옵션 제거",
    Designer_Option_RemoveAria: "옵션 {number} 제거",
    Designer_Option_Add: "옵션 추가",
    Designer_Option_OtherHint: "응답자는 \"{label}\" 레이블이 지정된 답변을 직접 입력할 수도 있습니다.",
    Designer_Option_OtherFallback: "기타",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "제거",
    Designer_Grid_RemoveAria: "{label} {number} 제거",
    Designer_Grid_Statements: "문항",
    Designer_Grid_Scale: "척도",
    Designer_Grid_AddStatement: "문항 추가",
    Designer_Grid_AddScale: "척도 추가",
    Designer_Width_Full: "전체 너비",
    Designer_Width_Half: "1/2 너비",
    Designer_Width_Third: "1/3 너비",
    Designer_Width_Aria: "질문 너비",
    Designer_Card_BlockLabelPlaceholder: "블록 레이블(응답자에게 표시되지 않음)",
    Designer_Card_QuestionText: "질문 텍스트",
    Designer_Card_MoveUp: "위로 이동",
    Designer_Card_MoveQuestionUp: "질문을 위로 이동",
    Designer_Card_MoveDown: "아래로 이동",
    Designer_Card_MoveQuestionDown: "질문을 아래로 이동",
    Designer_Card_DuplicateQuestion: "질문 복제",
    Designer_Card_MultipleAnswers: "여러 답변",
    Designer_Card_Required: "필수",
    Designer_Card_MoreOptions: "옵션 더 보기",
    Designer_Card_MoreOptionsAria: "이 질문의 추가 옵션",
    Designer_Canvas_FormTitle: "양식 제목",
    Designer_Canvas_DescriptionPlaceholder: "설명 추가(선택 사항)",
    Designer_Canvas_DescriptionAria: "양식 설명",
    Designer_Canvas_EmptyTitle: "첫 번째 질문 추가",
    Designer_Canvas_EmptyBody: "질문 유형을 선택하여 시작하세요. 질문을 끌어서 순서를 바꿀 수 있으며, 분기를 추가하여 응답자에게 해당하는 질문만 표시할 수 있습니다.",
    Designer_Section_Chip: "섹션 {number}/{total}",
    Designer_Section_TitlePlaceholder: "섹션 제목",
    Designer_Section_TitleAria: "섹션 {number} 제목",
    Designer_Section_DescriptionPlaceholder: "설명(선택 사항)",
    Designer_Section_DescriptionAria: "섹션 {number} 설명",
    Designer_Section_MoveUp: "섹션을 위로 이동",
    Designer_Section_MoveDown: "섹션을 아래로 이동",
    Designer_Section_Delete: "섹션 삭제",
    Designer_Card_DragToReorder: "끌어서 순서 변경",
    Designer_Card_ReorderAria: "{title} 순서 변경",
    Designer_Card_ReorderFallback: "질문",
    Designer_Canvas_AddNew: "새로 추가",
    Designer_Canvas_AddSection: "섹션 추가",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "도로명 주소",
    Form_Address_Street2Placeholder: "아파트, 동/호수 등(선택 사항)",
    Form_Address_CityPlaceholder: "시/군/구",
    Form_Address_StatePlaceholder: "시/도",
    Form_Address_PostalCodePlaceholder: "우편번호",
    Form_Address_CountryPlaceholder: "국가",
    Form_Address_StreetAria: "도로명 주소",
    Form_Address_Street2Aria: "주소 2행",
    Form_Address_CityAria: "시/군/구",
    Form_Address_StateAria: "시/도",
    Form_Address_PostalCodeAria: "우편번호",
    Form_Address_CountryAria: "국가",
    Form_Consent_DefaultLabel: "동의합니다",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{total}개 행 중 {answered}개 응답함",
    Form_Lookup_LoadError: "이 질문의 옵션을 불러올 수 없습니다.",
    Form_Lookup_Loading: "옵션을 불러오는 중…",
    Form_Lookup_SelectOptionsPlaceholder: "옵션 선택",
    Form_Lookup_SelectOptionPlaceholder: "옵션 선택",
    Form_Person_Placeholder: "이름을 입력하세요…",
    Form_Person_SuggestedPeopleAndGroups: "추천 사용자 및 그룹",
    Form_Person_SuggestedPeople: "추천 사용자",
    Form_Person_NoPeopleOrGroups: "사용자 또는 그룹을 찾을 수 없습니다",
    Form_Person_NoPeople: "사용자를 찾을 수 없습니다",
    Form_Person_Searching: "검색 중…",
    Form_Ranking_Moved: "{item}을(를) {total}개 중 {position}번째로 이동했습니다",
    Form_Ranking_MoveUp: "위로 이동",
    Form_Ranking_MoveDown: "아래로 이동",
    Form_Ranking_MoveItemUpAria: "{item}을(를) 위로 이동",
    Form_Ranking_MoveItemDownAria: "{item}을(를) 아래로 이동",
    Form_Rating_ValueText: "{value}/{max}",
    Form_Rating_NotRated: "평가 안 함",
    Form_Rating_Clear: "평가 지우기",
    Form_RichText_Bold: "굵게",
    Form_RichText_Italic: "기울임꼴",
    Form_RichText_Underline: "밑줄",
    Form_RichText_BulletedList: "글머리 기호 목록",
    Form_RichText_NumberedList: "번호 매기기 목록",
    Form_RichText_ClearFormatting: "서식 지우기",
    Form_RichText_ToolbarAria: "텍스트 서식",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\"을(를) 건너뛰었습니다. 제한은 {limit}개입니다.",
    Form_File_TypeNotAccepted: "\"{name}\"은(는) 허용되지 않는 형식입니다.",
    Form_File_TooLarge: "\"{name}\"은(는) {size}MB보다 큽니다.",
    Form_File_AlreadyAttached: "\"{name}\"은(는) 이미 첨부되었습니다.",
    Form_File_ReadError: "파일 중 하나를 읽을 수 없습니다. 다시 첨부해 보세요.",
    Form_File_HintMaxSize: "파일당 최대 {size}MB",
    Form_File_HintOneFile: "파일 1개",
    Form_File_HintMaxFiles: "최대 {count}개 파일",
    Form_File_Reading: "파일을 읽는 중…",
    Form_File_DropPrompt: "여기에 파일을 끌어다 놓거나 클릭하여 찾아보세요",
    Form_File_Remove: "{name} 제거",
    Form_Signature_Alt: "서명",
    Form_Signature_AriaSigned: "{label} — 서명됨",
    Form_Signature_AriaEmpty: "{label} — 비어 있음",
    Form_Signature_Clear: "지우기",
    Form_Signature_Signed: "서명됨",
    Form_Signature_Prompt: "위 영역에 마우스, 펜 또는 손가락으로 서명하세요",
    Form_Time_Placeholder: "시간 선택",
    Form_Field_DatePlaceholder: "날짜 선택",
    Form_Field_TimeAriaWithLabel: "{label} — 시간",
    Form_Field_TimeAria: "시간",
    Form_Field_OtherDefault: "기타",
    Form_Field_SelectOptionsPlaceholder: "옵션 선택",
    Form_Field_PleaseSpecify: "구체적으로 입력하세요",
    Form_Field_OtherSpecifyAria: "{label} — 구체적으로 입력하세요",
    Form_Field_SelectOptionPlaceholder: "옵션 선택",
    Form_Field_Yes: "예",
    Form_Field_No: "아니요",
    Form_Field_SliderHint: "슬라이더를 끌어 답하세요",
    Form_Field_WebAddressAriaWithLabel: "{label} — 웹 주소",
    Form_Field_WebAddressAria: "웹 주소",
    Form_Field_DisplayTextPlaceholder: "표시 텍스트(선택 사항)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — 표시 텍스트",
    Form_Field_DisplayTextAria: "표시 텍스트",
    Form_Field_ChooseBetween: "{min}개에서 {max}개 사이로 선택하세요",
    Form_Field_ChooseAtLeast: "{min}개 이상 선택하세요",
    Form_Field_ChooseUpTo: "최대 {max}개까지 선택하세요",
    Form_Field_SelectedCount: "{count}개 선택됨",
    Form_Field_RequiredAria: "(필수)",
    Form_Submit_SaveError: "응답을 저장할 수 없습니다. 디자이너에서 양식이 게시되었는지, 그리고 응답 목록에 항목을 추가할 권한이 있는지 확인하세요.",
    Form_Empty_Message: "이 양식에는 아직 질문이 없습니다. 양식 소유자는 [질문] 탭에서 질문을 추가할 수 있습니다.",
    Form_Checking: "양식을 확인하는 중…",
    Form_Closed_NotYetOpen: "아직 열리지 않음",
    Form_Closed_AlreadyAnswered: "이미 응답함",
    Form_Closed_Title: "양식이 닫힘",
    Form_Confirmation_PreviewNotice: "미리 보기였습니다. 응답 목록에는 아무것도 저장되지 않았습니다.",
    Form_Confirmation_PreviewAgain: "미리 보기 다시 실행",
    Form_Confirmation_SubmitAnother: "다른 응답 제출",
    Form_Wizard_StepFallback: "{step}단계",
    Form_Wizard_StepsAria: "양식 단계",
    Form_Wizard_StepOf: "{total}단계 중 {step}단계",
    Form_ErrorSummary_Title: "응답 {count}개를 확인하세요:",
    Form_ErrorSummary_UntitledQuestion: "제목 없는 질문",
    Form_ErrorSummary_Question: "질문",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "뒤로",
    Form_Nav_Next: "다음",
    Form_Draft_Saving: "저장 중…",
    Form_Draft_Saved: "초안 저장됨",
    Form_Draft_SaveAndFinishLater: "저장하고 나중에 완료",
    Form_Draft_NotSaved: "초안이 저장되지 않음",
    Form_Submit_Preview: "제출(미리 보기)",
    Form_Submit_Button: "제출",
    Form_Response_NoAnswer: "답변 없음",
    Form_Signature_TypeLabel: "전체 이름을 입력하세요",
    Form_Signature_TypeInstead: "이름 입력으로 전환",
    Form_Signature_DrawInstead: "그리기로 전환",
    Form_Edit_Button: "이전 응답 편집",
    Form_Edit_Available: "이미 응답을 제출했습니다. 새로 제출하는 대신 기존 응답을 편집할 수 있습니다.",
    Form_Edit_Banner: "이전 응답을 편집하고 있습니다.",
    Form_Edit_Save: "응답 업데이트",
    Form_Edit_UpdatedTitle: "응답이 업데이트되었습니다",
    Form_Edit_UpdatedMessage: "변경 내용이 저장되었습니다.",
    Form_Edit_LoadError: "이전 응답을 불러올 수 없습니다. 다시 시도하세요.",
    Form_Draft_MissingFiles: "다음 파일을 다시 첨부하세요: {names}. 이 파일을 복원할 수 없습니다.",
    Form_Attachments_Failed: "응답은 저장되었지만 다음 첨부 파일을 업로드할 수 없습니다: {names}. 다시 시도하거나 양식 소유자에게 문의하세요.",
    Logic_ThisQuestion: "이 질문",
    Logic_Required: "{label}은(는) 필수입니다",
    Logic_RequiredConsent: "계속하려면 확인란을 선택하세요",
    Logic_RequiredFile: "파일을 하나 이상 첨부하세요",
    Logic_RequiredSignature: "서명을 추가하세요",
    Logic_RequiredLikert: "모든 행에 응답하세요",
    Logic_InvalidEmail: "올바른 이메일 주소를 입력하세요",
    Logic_InvalidPhone: "올바른 전화번호를 입력하세요",
    Logic_InvalidUrl: "http:// 또는 https://로 시작하는 올바른 웹 주소를 입력하세요",
    Logic_MinValue: "값은 {value} 이상이어야 합니다",
    Logic_MaxValue: "값은 {value} 이하여야 합니다",
    Logic_MaxLength: "최대 길이는 {max}자입니다",
    Logic_ChooseAtLeastOne: "옵션을 {count}개 이상 선택하세요",
    Logic_ChooseAtLeastMany: "옵션을 {count}개 이상 선택하세요",
    Logic_ChooseAtMostOne: "옵션은 최대 {count}개까지 선택할 수 있습니다",
    Logic_ChooseAtMostMany: "옵션은 최대 {count}개까지 선택할 수 있습니다",
    Logic_LikertRemaining: "모든 행에 응답하세요({count}개 남음)",
    Logic_MaxFilesOne: "파일은 최대 {count}개까지 첨부할 수 있습니다",
    Logic_MaxFilesMany: "파일은 최대 {count}개까지 첨부할 수 있습니다",
    Logic_FileTooLarge: "\"{name}\" 파일이 {size}MB보다 큽니다",
    Logic_FileTypeNotAccepted: "\"{name}\"은(는) 허용되지 않는 파일 형식입니다({types})",
    Logic_AddressRequired: "최소한 도로명과 도시를 입력하세요",
    Logic_PatternDefault: "이 응답이 예상된 형식이 아닙니다",
    Logic_Yes: "예",
    Logic_No: "아니요",
    Logic_Agreed: "동의함",
    Logic_NotAgreed: "동의하지 않음",
    Logic_Signed: "서명됨",
    Logic_NoAnswer: "(응답 없음)",
    Logic_Unknown: "(알 수 없음)",
    Logic_OtherSlice: "기타({count})",
    Logic_CsvResponseId: "응답 ID",
    Logic_CsvSubmitted: "제출 시간",
    Logic_CsvSubmittedBy: "제출자",
    Logic_EmailQuestion: "질문",
    Logic_EmailViewItem: "Microsoft Lists에서 보기",
    Logic_EmailFooter: "Smart Forms에서 자동으로 보낸 메일입니다.",
    Logic_ClosedDefault: "이 양식은 더 이상 응답을 받지 않습니다.",
    Logic_NotYetOpen: "이 양식은 {date}에 열립니다.",
    Logic_AlreadyResponded: "이미 이 양식에 응답했습니다. 감사합니다!",
    Logic_UntitledQuestion: "제목 없는 질문",
    Logic_Issue_NoQuestions: "응답을 수집하기 전에 질문을 하나 이상 추가하세요.",
    Logic_Issue_NoTitle: "텍스트가 없는 질문이 있습니다. 게시할 때 이름이 자동으로 지정됩니다.",
    Logic_Issue_DuplicateTitle: "{label}이(가) 다른 질문과 텍스트가 같아 결과를 읽기 어려워집니다.",
    Logic_Issue_NeedTwoOptions: "{label}에는 옵션이 두 개 이상 필요합니다.",
    Logic_Issue_ImageNoImage: "{label}에 이미지가 없는 옵션이 있어 텍스트 타일로 표시됩니다.",
    Logic_Issue_LikertNeedRow: "{label}에는 행이 하나 이상 필요합니다.",
    Logic_Issue_LikertNeedColumns: "{label}에는 척도 열이 두 개 이상 필요합니다.",
    Logic_Issue_NoLookupList: "{label}에 원본 목록이 선택되지 않았습니다.",
    Logic_Issue_NoFormula: "{label}에 수식이 없습니다.",
    Logic_Issue_BadFormula: "{label}의 수식을 계산할 수 없습니다. 괄호와 연산자를 확인하세요.",
    Logic_Issue_MissingRefs: "{label}이(가) 존재하지 않는 질문을 참조합니다: {names}.",
    Logic_Issue_BadPattern: "{label}의 유효성 검사 패턴이 올바르지 않습니다.",
    Logic_Issue_BrokenRule: "{label}의 분기 규칙이 삭제된 질문을 가리킵니다.",
    Logic_Issue_SelfRule: "{label}의 분기 규칙이 자기 자신을 참조합니다.",
    Logic_Issue_RuleMismatch: "{label}의 분기 규칙이 더 이상 종속된 질문과 맞지 않습니다.",
    Logic_Issue_RequiredReadOnly: "{label}은(는) 필수이면서 읽기 전용이므로 미리 채운 링크를 통해서만 응답할 수 있습니다.",
    Logic_Issue_EmptySection: "질문이 없는 섹션이 있으며 건너뜁니다.",
    Logic_Issue_CloseBeforeOpen: "종료 날짜가 시작 날짜와 같거나 이전이므로 양식이 응답을 받지 않습니다.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "승인 이메일은 켜져 있지만 승인 단계가 꺼져 있습니다.",
    Logic_Op_equals: "같음",
    Logic_Op_notEquals: "같지 않음",
    Logic_Op_contains: "포함",
    Logic_Op_notContains: "포함하지 않음",
    Logic_Op_notEmpty: "응답함",
    Logic_Op_empty: "응답하지 않음",
    Logic_Op_greaterThan: "초과",
    Logic_Op_greaterOrEqual: "이상",
    Logic_Op_lessThan: "미만",
    Logic_Op_lessOrEqual: "이하",
    Logic_Op_between: "범위 내",
    Logic_Op_before: "이전",
    Logic_Op_after: "이후",
    Logic_Type_Text: "짧은 응답",
    Logic_TypeDesc_Text: "한 줄 텍스트",
    Logic_Category_Text: "텍스트",
    Logic_Type_MultilineText: "긴 응답",
    Logic_TypeDesc_MultilineText: "여러 줄의 일반 텍스트",
    Logic_Type_RichText: "서식 있는 텍스트",
    Logic_TypeDesc_RichText: "굵게, 목록, 링크",
    Logic_Type_Choice: "선택",
    Logic_TypeDesc_Choice: "옵션 목록에서 선택",
    Logic_Category_Choice: "선택",
    Logic_Type_ImageChoice: "이미지 선택",
    Logic_TypeDesc_ImageChoice: "이미지 타일에서 선택",
    Logic_Type_Lookup: "목록에서 조회",
    Logic_TypeDesc_Lookup: "다른 SharePoint 목록에서 실시간으로 읽어 온 옵션",
    Logic_Type_YesNo: "예 / 아니요",
    Logic_TypeDesc_YesNo: "간단한 켜기/끄기 토글",
    Logic_Type_Consent: "동의",
    Logic_TypeDesc_Consent: "계속하려면 응답자가 선택해야 하는 확인란",
    Logic_Type_Ranking: "순위",
    Logic_TypeDesc_Ranking: "옵션을 끌어 선호도 순으로 정렬",
    Logic_Type_Rating: "평가",
    Logic_TypeDesc_Rating: "별, 하트 또는 엄지",
    Logic_Category_Scales: "척도",
    Logic_Type_Scale: "의견 척도",
    Logic_TypeDesc_Scale: "양 끝에 레이블이 있는 숫자 척도",
    Logic_Type_Slider: "슬라이더",
    Logic_TypeDesc_Slider: "슬라이딩 척도의 값",
    Logic_Type_Likert: "리커트 그리드",
    Logic_TypeDesc_Likert: "하나의 공통 척도로 여러 문항 평가",
    Logic_Type_Number: "숫자",
    Logic_TypeDesc_Number: "일반, 통화 또는 백분율",
    Logic_Category_Advanced: "고급",
    Logic_Type_Calculated: "계산됨",
    Logic_TypeDesc_Calculated: "다른 응답에서 계산되는 읽기 전용 합계",
    Logic_Type_Date: "날짜",
    Logic_TypeDesc_Date: "달력 날짜(시간 포함 가능)",
    Logic_Category_Date: "날짜",
    Logic_Type_Time: "시간",
    Logic_TypeDesc_Time: "시간만 입력",
    Logic_Type_Person: "사용자",
    Logic_TypeDesc_Person: "조직의 사용자 선택",
    Logic_Category_People: "사용자",
    Logic_Type_Email: "이메일",
    Logic_TypeDesc_Email: "유효성이 검사되는 이메일 주소",
    Logic_Type_Phone: "전화",
    Logic_TypeDesc_Phone: "유효성이 검사되는 전화번호",
    Logic_Type_Address: "주소",
    Logic_TypeDesc_Address: "도로명, 도시, 우편번호, 국가",
    Logic_Type_Hyperlink: "링크",
    Logic_TypeDesc_Hyperlink: "웹 주소",
    Logic_Type_FileUpload: "파일 업로드",
    Logic_TypeDesc_FileUpload: "응답에 파일을 하나 이상 첨부",
    Logic_Type_Signature: "서명",
    Logic_TypeDesc_Signature: "마우스, 펜 또는 손가락으로 서명",
    Logic_Type_Content: "텍스트 블록",
    Logic_TypeDesc_Content: "지침 또는 이미지(응답을 수집하지 않음)",
    Logic_Category_Layout: "레이아웃",
    Logic_Preset_nps: "NPS(0–10)",
    Logic_PresetDesc_nps: "얼마나 추천하시겠습니까…",
    Logic_Preset_satisfaction: "만족도(1–5)",
    Logic_PresetDesc_satisfaction: "매우 불만족에서 매우 만족까지",
    Logic_Preset_currency: "통화",
    Logic_PresetDesc_currency: "금액",
    Logic_Preset_percent: "백분율",
    Logic_PresetDesc_percent: "백분율 값",
    Logic_Template_blank_Name: "빈 양식",
    Logic_Template_blank_Description: "처음부터 시작",
    Logic_Template_feedback_Name: "고객 피드백",
    Logic_Template_feedback_Description: "NPS, 평가 및 자유 의견",
    Logic_Template_event_Name: "이벤트 등록",
    Logic_Template_event_Description: "참석자 정보, 세션, 식이 요구 사항",
    Logic_Template_itrequest_Name: "IT 서비스 요청",
    Logic_Template_itrequest_Description: "우선순위와 첨부 파일이 포함된 분류된 요청",
    Logic_Template_expense_Name: "경비 청구",
    Logic_Template_expense_Description: "항목, 영수증 및 계산된 합계",
    Logic_Template_pulse_Name: "직원 펄스 설문 조사",
    Logic_Template_pulse_Description: "리커트 그리드, 참여도 척도 및 익명성 안내",
    Logic_Template_safety_Name: "안전 점검",
    Logic_Template_safety_Description: "체크리스트, 사진 및 서명",
    Logic_Template_booking_Name: "회의실 또는 리소스 예약",
    Logic_Template_booking_Description: "시간대가 있는 조회 기반 리소스 선택기",
    Charts_ColumnChartAria: "범주 {count}개가 있는 세로 막대형 차트",
    Charts_DonutChartAria: "범주 {count}개의 도넛형 차트",
    Charts_NoAnswers: "아직 답변이 없습니다.",
    Charts_NoResponses: "아직 응답이 없습니다.",
    Charts_Responses: "응답",
    Charts_ResponsesOverTime: "시간별 응답",
    Responses_Chart_Answer: "답변",
    Responses_Chart_Average: "평균",
    Responses_Chart_AverageOf: "{count}개의 평균",
    Responses_Chart_AveragePosition: "평균 순위",
    Responses_Chart_AverageRange: "평균(1–{max})",
    Responses_Chart_AvgValue: "평균 {value}",
    Responses_Chart_Detractors: "비추천자(0–6)",
    Responses_Chart_Max: "최대",
    Responses_Chart_Maximum: "최대값",
    Responses_Chart_Median: "중앙값",
    Responses_Chart_MentionOne: "언급 {count}회",
    Responses_Chart_MentionOther: "언급 {count}회",
    Responses_Chart_Min: "최소",
    Responses_Chart_Minimum: "최소값",
    Responses_Chart_NoAnswers: "아직 답변이 없습니다.",
    Responses_Chart_NoNumeric: "아직 숫자 답변이 없습니다.",
    Responses_Chart_NoRankings: "아직 순위가 없습니다.",
    Responses_Chart_NoScores: "아직 점수가 없습니다.",
    Responses_Chart_NotEnoughText: "요약하기에는 텍스트가 충분하지 않습니다.",
    Responses_Chart_NpsScore: "NPS 점수",
    Responses_Chart_Option: "옵션",
    Responses_Chart_Passives: "중립자(7–8)",
    Responses_Chart_Promoters: "추천자(9–10)",
    Responses_Chart_ResponseOne: "응답",
    Responses_Chart_ResponseOther: "응답",
    Responses_Chart_Responses: "응답",
    Responses_Chart_ShowingAnswers: "답변 {total}개 중 {shown}개를 표시하고 있습니다.",
    Responses_Chart_Statement: "문항",
    Responses_Chart_Statistic: "통계",
    Responses_Chart_StdDev: "표준 편차",
    Responses_Chart_StdDeviation: "표준 편차",
    Responses_Chart_Total: "합계",
    Responses_Chart_Value: "값",
    Responses_Dashboard_AllHidden: "모든 질문이 대시보드에서 숨겨져 있습니다. \"숨겨진 질문 표시\"를 사용하여 다시 표시하세요.",
    Responses_Dashboard_AnsweredOf: "{total}개 중 {answered}개 응답함",
    Responses_Dashboard_AnsweredOfPinned: "{total}개 중 {answered}개 응답함 · 고정됨",
    Responses_Dashboard_AveragedAcrossResponses: "모든 응답의 평균",
    Responses_Dashboard_ByDay: "일별",
    Responses_Dashboard_ByMonth: "월별",
    Responses_Dashboard_ByWeek: "주별",
    Responses_Dashboard_ChartAuto: "자동",
    Responses_Dashboard_ChartBars: "가로 막대",
    Responses_Dashboard_ChartColumns: "세로 막대",
    Responses_Dashboard_ChartDonut: "도넛형",
    Responses_Dashboard_ChartGauge: "게이지",
    Responses_Dashboard_ChartHistogram: "히스토그램",
    Responses_Dashboard_ChartOptions: "차트 옵션",
    Responses_Dashboard_ChartOptionsFor: "{title}의 차트 옵션",
    Responses_Dashboard_ChartStatistics: "통계",
    Responses_Dashboard_ChartTable: "표",
    Responses_Dashboard_ChartWordFrequency: "단어 빈도",
    Responses_Dashboard_EmptyBody: "사용자가 응답하기 시작하면 이 대시보드가 주요 수치, 응답 타임라인, 주목할 만한 질문의 차트로 자동으로 채워집니다.",
    Responses_Dashboard_EmptyTitle: "아직 응답이 없습니다",
    Responses_Dashboard_Hide: "대시보드에서 숨기기",
    Responses_Dashboard_Highlights: "주요 내용",
    Responses_Dashboard_Last7Days: "최근 7일",
    Responses_Dashboard_LatestDate: "최근: {date}",
    Responses_Dashboard_MedianTimeToComplete: "완료 소요 시간(중앙값)",
    Responses_Dashboard_NoPriorWeek: "비교할 이전 주가 없습니다",
    Responses_Dashboard_OneEach: "각 1회",
    Responses_Dashboard_Pin: "대시보드에 고정",
    Responses_Dashboard_QuestionFallback: "질문",
    Responses_Dashboard_QuestionsAnswered: "응답한 질문",
    Responses_Dashboard_RecordedOnSubmit: "제출 시 기록됨",
    Responses_Dashboard_RepeatResponses: "중복 응답 {count}개",
    Responses_Dashboard_ResponsesOverTime: "시간별 응답",
    Responses_Dashboard_ShowHidden: "숨겨진 질문 표시",
    Responses_Dashboard_SinceMidnight: "자정 이후",
    Responses_Dashboard_Today: "오늘",
    Responses_Dashboard_TotalResponses: "총 응답",
    Responses_Dashboard_UniqueRespondents: "고유 응답자",
    Responses_Dashboard_Unpin: "대시보드에서 고정 해제",
    Responses_Dashboard_UntitledQuestion: "제목 없는 질문",
    Responses_Dashboard_VsPrevious7Days: "이전 7일 대비",
    Responses_Detail_Answers: "답변",
    Responses_Detail_AsTheForm: "양식 보기",
    Responses_Detail_Cancel: "취소",
    Responses_Detail_Delete: "삭제",
    Responses_Detail_DeleteBody: "목록 항목은 사이트 휴지통으로 이동되므로 거기에서 복원할 수 있습니다.",
    Responses_Detail_DeleteTitle: "이 응답을 삭제하시겠습니까?",
    Responses_Detail_Deleting: "삭제 중…",
    Responses_Detail_Draft: "초안",
    Responses_Detail_Header: "응답 {index}/{total}",
    Responses_Detail_LoadingAttachments: "첨부 파일을 불러오는 중…",
    Responses_Detail_Next: "다음 응답",
    Responses_Detail_NoAnswer: "답변 없음",
    Responses_Detail_Previous: "이전 응답",
    Responses_Detail_Print: "인쇄",
    Responses_Detail_Signature: "서명",
    Responses_Detail_Signed: "서명됨",
    Responses_Detail_Took: "소요 시간: {duration}",
    Responses_Summary_AnsweredOfType: "{total}개 중 {answered}개 응답함 · {type}",
    Responses_Summary_ByField: "{title}별",
    Responses_Summary_CompareBy: "비교 기준…",
    Responses_Summary_EmptyBody: "각 질문의 요약이 여기에 표시됩니다.",
    Responses_Summary_NoComparison: "비교 안 함",
    Responses_Summary_NothingToCompare: "\"{title}\"에 응답한 사람이 없으므로 비교할 내용이 없습니다.",
    Responses_Summary_OtherNote: "범주가 {max}개를 초과하는 차트에서는 작은 범주가 \"기타\"로 묶입니다. 모든 값을 보려면 카드를 표로 전환하세요.",
    Responses_Summary_ResponseCountOne: "응답 {count}개",
    Responses_Summary_ResponseCountOther: "응답 {count}개",
    Responses_Summary_SeeAllAnswers: "표에서 모든 답변 보기",
    Responses_Summary_SegmentNote: "가장 큰 {groups}개 그룹을 표시하고 있습니다. 여러 답변을 선택한 응답은 해당하는 모든 그룹에 나타나므로 그룹 합계가 {total}보다 클 수 있습니다.",
    Responses_Summary_SplitBy: "{title}(으)로 나누기",
    Responses_Summary_Untitled: "제목 없음",
    Responses_Table_Apply: "적용",
    Responses_Table_Cancel: "취소",
    Responses_Table_ClearSelection: "선택 해제",
    Responses_Table_ColumnOrder: "열 순서",
    Responses_Table_ColumnsCount: "열({shown}/{total})",
    Responses_Table_Delete: "삭제",
    Responses_Table_DeleteBody: "목록 항목은 사이트 휴지통으로 이동되므로 거기에서 복원할 수 있습니다.",
    Responses_Table_DeleteSelected: "선택 항목 삭제",
    Responses_Table_DeleteTitleOne: "응답 {count}개를 삭제하시겠습니까?",
    Responses_Table_DeleteTitleOther: "응답 {count}개를 삭제하시겠습니까?",
    Responses_Table_Deleting: "삭제 중…",
    Responses_Table_MoveDown: "아래로 이동",
    Responses_Table_MoveDownFor: "{title}을(를) 아래로 이동",
    Responses_Table_MoveUp: "위로 이동",
    Responses_Table_MoveUpFor: "{title}을(를) 위로 이동",
    Responses_Table_NoColumns: "표시되는 질문 열이 아직 없습니다.",
    Responses_Table_NoMatch: "현재 필터와 일치하는 응답이 없습니다.",
    Responses_Table_NothingToShow: "표시할 항목 없음",
    Responses_Table_OpenResponse: "이 응답 열기",
    Responses_Table_OrderNote: "\"제출됨\"과 \"제출자\"는 항상 맨 앞에 옵니다. 끌어서 정한 순서는 질문 열에 적용됩니다.",
    Responses_Table_Reorder: "순서 변경",
    Responses_Table_ResetColumns: "열 다시 설정",
    Responses_Table_SelectResponse: "이 응답 선택",
    Responses_Table_SelectedOne: "응답 {count}개 선택됨",
    Responses_Table_SelectedOther: "응답 {count}개 선택됨",
    Responses_Table_ShowAll: "모두 표시",
    Responses_Table_ShowTheseQuestions: "이 질문 표시",
    Responses_Table_Submitted: "제출됨",
    Responses_Table_SubmittedBy: "제출자",
    Responses_Table_ToggleSelection: "선택 전환",
    Responses_Table_Unknown: "알 수 없음",
    Responses_Table_Untitled: "제목 없음",
    Responses_View_AllTime: "전체 기간",
    Responses_View_AnyAnswer: "모든 답변",
    Responses_View_Clear: "지우기",
    Responses_View_CopyShareLink: "공유 링크 복사",
    Responses_View_CountFiltered: "응답 {total}개 중 {shown}개",
    Responses_View_CountOne: "응답 {count}개",
    Responses_View_CountOther: "응답 {count}개",
    Responses_View_Dashboard: "대시보드",
    Responses_View_DateRange: "날짜 범위",
    Responses_View_EmptyBody: "양식을 공유하여 응답 수집을 시작하세요. 답변은 \"{list}\"에 저장되며 바로 여기에 표시됩니다.",
    Responses_View_EmptyTitle: "아직 응답이 없습니다",
    Responses_View_ExportCsv: "CSV 내보내기",
    Responses_View_FilterByAnswer: "답변으로 필터링",
    Responses_View_FilterByQuestion: "질문으로 필터링",
    Responses_View_FilterValue: "필터 값",
    Responses_View_Last30Days: "최근 30일",
    Responses_View_Last7Days: "최근 7일",
    Responses_View_Last90Days: "최근 90일",
    Responses_View_LoadError: "응답을 불러올 수 없습니다. 목록 열이 만들어지도록 양식을 한 번 게시한 후 다시 시도하세요.",
    Responses_View_Loading: "응답을 불러오는 중…",
    Responses_View_MoreActions: "응답 관련 추가 작업",
    Responses_View_PreviewForm: "양식 미리 보기",
    Responses_View_Refresh: "새로 고침",
    Responses_View_ResponsesTab: "응답({count})",
    Responses_View_SearchPlaceholder: "모든 답변 검색",
    Responses_View_SegmentOption: "{label}({count})",
    Responses_View_SelectValue: "값 선택",
    Responses_View_Summary: "요약",
    Responses_View_Today: "오늘",
    Responses_View_Truncated: "이 목록에는 Smart Forms에서 한 번에 불러올 수 있는 것보다 많은 응답이 있습니다. 최신 {count}개를 표시하고 있습니다. 전체 응답을 보려면 Microsoft Lists에서 목록을 여세요.",
    Responses_View_TryAgain: "다시 시도",
    Responses_View_Untitled: "제목 없음",
    Responses_Approval_Column: "승인",
    Responses_Approval_ReviewerColumn: "검토자",
    Responses_Approval_CommentColumn: "검토자 의견",
    Responses_Approval_Pending: "대기 중",
    Responses_Approval_Approved: "승인됨",
    Responses_Approval_Rejected: "거부됨",
    Responses_Approval_AnyStatus: "모든 승인 상태",
    Responses_Approval_FilterLabel: "승인 상태별 필터",
    Responses_Approval_ApproveSelected: "선택 항목 승인",
    Responses_Approval_RejectSelected: "선택 항목 거부",
    Responses_Approval_BulkFailed: "응답 {count}개를 업데이트할 수 없습니다. 다시 시도하세요.",
    Responses_Approval_Approve: "승인",
    Responses_Approval_Reject: "거부",
    Responses_Approval_Reset: "대기 중으로 재설정",
    Responses_Approval_CommentLabel: "의견(선택 사항)",
    Responses_Approval_ReviewedBy: "검토자: {name}",
    Responses_Approval_Error: "결정을 저장할 수 없습니다. 다시 시도하세요.",
    Responses_Dashboard_ApprovalStatus: "검토 대기 중",
    Responses_Dashboard_ApprovalBreakdown: "대기 중 {pending}개, 승인됨 {approved}개, 거부됨 {rejected}개",
    Responses_Dashboard_TimelineCoarsened: "날짜 범위가 길어 타임라인이 더 넓은 단위({grain})로 그룹화되었습니다.",
    Responses_Dashboard_TimelineTruncated: "날짜 범위가 매우 길어 가장 최근 {count}개 기간만 표시됩니다.",
    Service_Item_DefaultTitle: "응답 — {date}",
    Service_Email_ApprovalSubject: "응답이 {status} — {title}",
    Service_Email_ApprovalHeading: "응답이 {status}",
    Service_Email_ApprovalIntro: "검토자가 \"{title}\"에 대한 응답을 {status}.",
    Service_Email_ApprovalCommentLabel: "검토자 의견",
    Service_Approval_Approved: "승인되었습니다",
    Service_Approval_Rejected: "거부되었습니다",
    Service_Approval_Pending: "대기 중입니다",
    Service_Lookup_InvalidFilter: "조회 필터가 올바르지 않습니다.",
    Service_Edit_NotAllowed: "이 양식은 제출된 응답 편집을 허용하지 않습니다.",
    Service_Edit_NotYours: "본인의 응답만 편집할 수 있습니다.",
    Service_Signature_AttachmentLabel: "서명",
    PropertyPane_ListsLoadFailed: "이 사이트의 목록을 불러올 수 없습니다.",
    PropertyPane_EnterListName: "먼저 새 목록의 이름을 입력하세요.",
    PropertyPane_CreatingList: "\"{name}\"을(를) 만드는 중…",
    PropertyPane_ListCreated: "\"{title}\" 목록을 만들고 선택했습니다.",
    PropertyPane_ListAlreadyExists: "\"{name}\"(이)라는 목록이 이미 있습니다. 위의 드롭다운에서 선택하세요.",
    PropertyPane_CreateListFailed: "목록을 만들 수 없습니다. 이 사이트에서 목록을 만들 권한이 있는지 확인하세요.",
    PropertyPane_Description: "양식 응답을 저장할 SharePoint 목록을 선택하거나 새로 만드세요. 질문, 모양, 알림 등 나머지는 모두 페이지에서 직접 편집합니다.",
    PropertyPane_ResponseList_GroupName: "응답 목록",
    PropertyPane_ListDropdown_Label: "이 목록에 응답 저장",
    PropertyPane_ResponsesGoTo: "응답은 \"{name}\"에 저장됩니다.",
    PropertyPane_PickList: "목록을 선택하거나 아래에서 새로 만드세요.",
    PropertyPane_LoadingLists: "목록을 불러오는 중…",
    PropertyPane_NewListName_Label: "또는 새 목록 만들기",
    PropertyPane_NewListName_Placeholder: "새 목록 이름",
    PropertyPane_CreateList_Button: "목록 만들기",
    PropertyPane_Tips_GroupName: "팁",
    PropertyPane_Tip_AutoSave: "질문과 설정은 편집할 때 자동으로 저장되므로 페이지를 저장하거나 게시할 필요가 없습니다.",
    PropertyPane_Tip_Permissions: "응답자는 응답 목록에 항목을 추가할 권한이 있어야 합니다. 제출할 때 오류가 발생했다고 보고하는 사람이 있으면 목록 사용 권한을 확인하세요.",
    PropertyPane_Tip_Share: "페이지에서 \"응답 수집\"을 사용하면 목록 열이 만들어지고 공유 가능한 작성 링크를 받을 수 있습니다.",
    App_ErrorBoundary_Title: "Smart Forms — 렌더링 오류",
    App_ErrorBoundary_Message: "메시지:",
    App_ErrorBoundary_Stack: "스택:",
    App_ErrorBoundary_NoStack: "(사용 가능한 스택 없음)",
    App_ErrorBoundary_ConsoleNote: "전체 세부 정보도 브라우저 콘솔에 기록되었습니다.",
    App_DefaultQuestionTitle: "질문 {number}",
    App_Error_ListMissing: "이 양식에 구성된 목록이 더 이상 없습니다. 웹 파트 설정에서 다른 목록을 선택하세요.",
    App_Error_LoadConfig: "양식 구성을 불러오는 중 문제가 발생했습니다.",
    App_Error_Unable: "양식을 불러올 수 없습니다.",
    App_Publish_ConflictNotice: "\"{title}\"에는 다른 형식({type})의 목록 열이 이미 있습니다. 새 열을 만들 수 있도록 질문 이름을 바꾸거나 형식을 원래대로 되돌리세요.",
    App_Publish_ConflictUnnamedQuestion: "질문",
    App_Publish_ColumnsAddedOne: "\"{list}\"에 열 {count}개를 추가했습니다.",
    App_Publish_ColumnsAddedOther: "\"{list}\"에 열 {count}개를 추가했습니다.",
    App_Publish_TheList: "목록",
    App_Publish_UpToDate: "응답 목록이 이미 최신 상태입니다.",
    App_Publish_Error: "목록 열을 만들 수 없습니다. 일반적으로 응답 목록에 대한 목록 관리 권한이 없기 때문이지만, 사용자 지정 스크립트가 사용하지 않도록 설정된 사이트에서도 발생할 수 있습니다. 브라우저 콘솔에서 근본적인 오류를 확인하거나 다시 시도하세요.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "SharePoint 목록을 기반으로 세련된 양식을 만드세요. {count}가지 질문 유형, 분기 논리, 파일 업로드, 공유 가능한 작성 링크, 결과 대시보드를 제공합니다.",
    App_Placeholder_ChooseList: "목록 선택 또는 만들기",
    App_Placeholder_Hint: "시작하려면 페이지를 편집하고 이 웹 파트를 구성하세요.",
    App_Loading: "양식을 불러오는 중…",
    App_OpenSettings: "설정 열기",
    App_Tab_Questions: "질문",
    App_Tab_QuestionsWithCount: "질문({count})",
    App_Tab_Responses: "응답",
    App_Tab_Responses_Title: "응답은 \"{list}\"에 저장됩니다",
    App_Templates_Start: "템플릿으로 시작",
    App_Settings_Title: "양식 설정 — 모양, 알림, 액세스",
    App_Settings_AriaLabel: "양식 설정",
    App_Preview: "미리 보기",
    App_Preview_Close: "미리 보기 닫기",
    App_Preview_Hint: "미리 보기 — 여기서 제출한 내용은 저장되지 않습니다. 유효성 검사와 분기는 응답자에게와 똑같이 동작합니다.",
    App_Publish_GettingReady: "준비하는 중…",
    App_Publish_CollectResponses: "응답 수집",
    App_Publish_Share: "공유",
    App_Retry: "다시 시도",
    App_SaveError_Banner: "마지막 변경 내용을 저장할 수 없습니다. 연결을 확인한 후 다시 시도하세요.",
    App_Preflight_BlockingTitle: "응답을 수집하기 전에 수정하세요",
    App_Preflight_WarningTitle: "먼저 확인해 볼 항목",
    App_Preflight_BlockingText: "이 문제가 있으면 게시된 양식이 제대로 작동하지 않습니다.",
    App_Preflight_WarningText: "문제는 없지만 링크를 공유하기 전에 수정해 두는 것이 좋습니다.",
    App_Preflight_GoTo: "이동",
    App_Preflight_CollectAnyway: "그래도 응답 수집",
    App_Preflight_Back: "양식으로 돌아가기",
    App_Cancel: "취소",
    App_Done: "완료",
    App_Share_Title: "양식을 공유할 준비가 되었습니다",
    App_Share_SubText: "양식을 작성해야 하는 모든 사람에게 이 링크를 보내세요.",
    App_Share_LinkAriaLabel: "공유 링크",
    App_Share_Copy: "복사",
    App_Share_Copied: "복사됨",
    App_Share_AddItemsEmphasis: "항목을 추가",
    App_Share_PermissionNote: "응답자는 \"{title}\"에 {addItems}할 수 있는 권한과 이 페이지에 대한 액세스 권한이 있어야 합니다. 제출할 때 오류가 발생한다면 거의 항상 이것이 원인입니다.",
    App_Share_PrefillNote: "열 이름을 추가하면 링크에서 질문에 미리 답변할 수 있습니다(예: {example}).",
    App_Templates_ReplaceWarning: "템플릿을 선택하면 현재 질문이 바뀝니다.",
    App_Templates_PickStart: "시작점을 선택하세요. 나중에 무엇이든 변경할 수 있습니다.",
    App_Templates_Empty: "비어 있음",
    App_Templates_QuestionCount: "질문 {count}개",
    App_SaveChip_SavingTitle: "최근 편집 내용 저장 중",
    App_SaveChip_Saving: "저장 중…",
    App_SaveChip_FailedTitle: "마지막 편집 내용을 저장할 수 없습니다. 연결을 확인한 후 다시 시도하세요.",
    App_SaveChip_Failed: "저장 실패",
    App_SaveChip_SavedTitle: "모든 변경 내용이 저장되었습니다",
    App_SaveChip_Saved: "저장됨",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "새 응답 — {title}",
    Service_Email_NewResponseHeading: "새 응답: {title}",
    Service_Email_NewResponseIntro: "누군가 방금 응답을 제출했습니다 — {date}.",
    Service_Email_ReceiptSubject: "내 응답 — {title}",
    Service_Email_ReceiptHeading: "응답해 주셔서 감사합니다!",
    Service_Email_ReceiptIntro: "\"{title}\"에 제출한 내용의 사본입니다.",
    App_History_Title: "버전 기록",
    App_History_RestoredNotice: "{date}에 저장된 버전을 복원했습니다. 내용을 검토한 다음 '응답 수집'을 사용하여 새 질문을 게시하세요.",
    App_History_Undo: "복원 실행 취소",
    App_Share_CopyManual: "브라우저에서 복사를 차단했습니다. 위 링크를 선택하고 Ctrl+C(Mac에서는 Cmd+C)를 눌러 복사하세요.",
    App_Share_TeamsNote: "Microsoft Teams를 사용 중입니다. 이 링크는 SharePoint 페이지를 직접 열므로 받는 사람에게 사이트 액세스 권한이 있어야 합니다.",
    App_Share_PrefillNotSecure: "미리 채운 응답은 편의를 위한 기능일 뿐입니다. 링크가 있는 사람은 누구나 변경할 수 있으므로 보안 경계로 취급하지 마세요.",
    Designer_Section_DropHere: "여기에 질문 놓기",
    Designer_Section_DropEnd: "여기에 놓아 이 섹션의 끝으로 이동",
    Designer_Rules_RemovedOne: "더 이상 맞지 않는 분기 규칙 1개가 제거되었습니다.",
    Designer_Rules_RemovedOther: "더 이상 맞지 않는 분기 규칙 {count}개가 제거되었습니다.",
    Designer_Settings_AllowEdit: "응답자가 자신의 응답을 편집하도록 허용",
    Designer_Settings_AllowEditHint: "응답자가 제출한 내용을 다시 열어 업데이트할 수 있습니다. 각 사용자는 자신의 응답만 편집할 수 있습니다.",
    Designer_Settings_EnableApproval: "승인 워크플로 사용",
    Designer_Settings_ApprovalNotify: "결정 시 응답자에게 이메일 보내기",
    Designer_Settings_ApprovalHint: "다음에 게시할 때 응답 목록에 승인 열이 추가됩니다. 소유자는 응답 탭에서 응답을 승인하거나 거부할 수 있습니다.",
    Designer_History_Title: "버전 기록",
    Designer_History_Intro: "이 양식의 질문 및 설정에 대해 이전에 저장된 버전입니다. 복원하면 버전이 디자이너에 로드되며, 실행 취소할 수 있습니다. 새 질문은 게시할 때만 만들어집니다.",
    Designer_History_Loading: "버전을 불러오는 중...",
    Designer_History_Empty: "이전 버전을 찾을 수 없습니다. 버전 기록을 사용하려면 \"Smart Forms Config\" 목록에서 버전 관리를 켜야 하며 저장된 편집 내용이 하나 이상 있어야 합니다.",
    Designer_History_Latest: "최신",
    Designer_History_LatestTitle: "현재 사용 중인 버전입니다",
    Designer_History_By: "작성자: {name}",
    Designer_History_UnknownAuthor: "알 수 없는 작성자",
    Designer_History_VersionLabel: "버전 {label}",
    Designer_History_Preview: "미리 보기",
    Designer_History_Restore: "복원",
    Designer_History_QuestionsOne: "질문 1개",
    Designer_History_QuestionsOther: "질문 {count}개",
    Designer_History_LoadFailed: "이 버전을 불러올 수 없습니다.",
    Designer_History_ConfirmTitle: "이 버전을 복원하시겠습니까?",
    Designer_History_ConfirmText: "양식이 {date}에 저장된 버전(질문 {count}개)으로 대체됩니다. 바로 실행 취소할 수 있습니다."
  };
});
