define([], function () {
  return {
    Designer_Color_Blue: "Blå",
    Designer_Color_Teal: "Turkis",
    Designer_Color_Green: "Grønn",
    Designer_Color_Purple: "Lilla",
    Designer_Color_Magenta: "Magenta",
    Designer_Color_Red: "Rød",
    Designer_Color_Orange: "Oransje",
    Designer_Color_Gray: "Grå",
    Designer_Settings_LayoutSinglePage: "Alle spørsmål på én side",
    Designer_Settings_LayoutWizard: "Én seksjon per trinn (veiviser)",
    Designer_Settings_Title: "Skjemainnstillinger",
    Designer_Common_Apply: "Bruk",
    Designer_Common_Cancel: "Avbryt",
    Designer_Settings_TabBasics: "Grunnleggende",
    Designer_Settings_FormTitle: "Skjematittel",
    Designer_Settings_Description: "Beskrivelse",
    Designer_Settings_Layout: "Oppsett",
    Designer_Settings_NumberQuestions: "Nummerer spørsmålene",
    Designer_Settings_ShuffleQuestions: "Bland rekkefølgen på spørsmålene for hver respondent",
    Designer_Settings_ShowProgressBar: "Vis en fremdriftslinje",
    Designer_Settings_TabAppearance: "Utseende",
    Designer_Settings_AccentColor: "Aksentfarge",
    Designer_Settings_CustomColorTitle: "Egendefinert farge",
    Designer_Settings_CustomColorAria: "Egendefinert aksentfarge",
    Designer_Settings_AccentHint: "Aksentfarger justeres automatisk for kontrast på mørke områder, slik at skjemaet er lesbart uansett hvilket tema siden bruker.",
    Designer_Settings_ShowHeader: "Vis skjemaoverskriften",
    Designer_Settings_HeaderIcon: "Overskriftsikon",
    Designer_Settings_TabAfterSubmit: "Etter innsending",
    Designer_Settings_SubmitButtonText: "Tekst på Send-knappen",
    Designer_Settings_SubmitPlaceholder: "Send",
    Designer_Settings_ThankYouTitle: "Takketittel",
    Designer_Settings_ThankYouPlaceholder: "Takk!",
    Designer_Settings_ThankYouMessage: "Takkemelding",
    Designer_Settings_ShowSubmitAnother: "Vis en «Send inn et nytt svar»-knapp",
    Designer_Settings_TabNotifications: "Varsler",
    Designer_Settings_EmailEachResponseTo: "Send hvert svar på e-post til",
    Designer_Settings_EmailPlaceholder: "navn@firma.no; team@firma.no",
    Designer_Settings_EmailDescription: "Personer i organisasjonen din får hvert svar på e-post, med en kobling til listeelementet",
    Designer_Settings_RespondentReceipt: "Send respondentene en kopi av svarene deres på e-post",
    Designer_Settings_NotificationsInfo: "Varsler bruker SharePoints egen e-posttjeneste, så mottakerne må være brukere i organisasjonen din. Eksterne adresser fjernes uten varsel.",
    Designer_Settings_TabAccess: "Tilgang",
    Designer_Settings_OpenFrom: "Åpne fra",
    Designer_Settings_OpenImmediately: "Åpne umiddelbart",
    Designer_Settings_CloseAfter: "Lukk etter",
    Designer_Settings_NeverClose: "Lukk aldri",
    Designer_Settings_ClearDates: "Fjern datoer",
    Designer_Settings_DatesInverted: "Lukkedatoen er lik eller før åpningsdatoen, så skjemaet ville aldri akseptert svar.",
    Designer_Settings_MaxResponses: "Stopp etter dette antallet svar",
    Designer_Settings_NoLimit: "Ingen grense",
    Designer_Settings_OneResponsePerPerson: "Tillat bare ett svar per person",
    Designer_Settings_AllowSaveDraft: "La respondenter lagre et utkast og fullføre senere",
    Designer_Settings_ClosedMessage: "Melding som vises når skjemaet er lukket",
    Designer_Settings_ClosedMessagePlaceholder: "Dette skjemaet tar ikke lenger imot svar.",
    Designer_Settings_AccessInfo: "Disse grensene håndheves av skjemaet, ikke av SharePoint. Alle med tillatelse til å legge til elementer i svarlisten kan fortsatt legge til et svar direkte via listen.",
    Designer_Field_StyleInfo: "Info (aksent)",
    Designer_Field_StyleSuccess: "Vellykket (grønn)",
    Designer_Field_StyleWarning: "Advarsel (gul)",
    Designer_Field_StylePlain: "Ren tekst",
    Designer_Field_StyleDivider: "Skillelinje",
    Designer_Field_IconStars: "Stjerner",
    Designer_Field_IconHearts: "Hjerter",
    Designer_Field_IconThumbs: "Tommel opp",
    Designer_Field_FormatPlain: "Vanlig tall",
    Designer_Field_FormatCurrency: "Valuta",
    Designer_Field_FormatPercent: "Prosent",
    Designer_Field_UntitledQuestion: "Spørsmål uten tittel",
    Designer_Field_DeletedQuestion: "et slettet spørsmål",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} og {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "ELLER",
    Designer_Rule_JoinAll: "OG",
    Designer_Rule_Preview: "Vises når {conditions}.",
    Designer_Field_Yes: "Ja",
    Designer_Field_No: "Nei",
    Designer_Field_When: "Når",
    Designer_Field_SelectValue: "Velg en verdi",
    Designer_Field_DateValuePlaceholder: "ÅÅÅÅ-MM-DD eller «today»",
    Designer_Field_ValuePlaceholder: "Verdi",
    Designer_Field_UpperBound: "Øvre grense",
    Designer_Field_RemoveCondition: "Fjern denne betingelsen",
    Designer_Field_FormulaInvalid: "Denne formelen kan ikke beregnes. Kontroller parenteser og operatorer.",
    Designer_Field_FormulaMissing: "Disse spørsmålene finnes ikke: {names}.",
    Designer_Field_FormulaPreview: "Med alle inndata satt til 10 vises {value}.",
    Designer_Field_HintYesNo: "Bruk «yes» eller «no»",
    Designer_Field_HintMultiDefault: "Skill flere standardverdier med ;",
    Designer_Field_HintSingleDefault: "Må samsvare med ett av alternativene",
    Designer_Field_HintDate: "Bruk «today», eller en dato som 2026-03-01",
    Designer_Field_HintTime: "Bruk «now», eller et klokkeslett som 09:30",
    Designer_Field_QuestionSettings: "Spørsmålsinnstillinger",
    Designer_Field_Appearance: "Utseende",
    Designer_Field_Style: "Stil",
    Designer_Field_ImageUrl: "Bilde-URL (valgfritt)",
    Designer_Field_Content: "Innhold",
    Designer_Field_BasicFormatting: "Grunnleggende formatering er tillatt: fet, kursiv, lister og koblinger.",
    Designer_Field_TabOptions: "Alternativer",
    Designer_Field_TabBranching: "Forgrening",
    Designer_Field_BranchingNeedsQuestion: "Legg til et annet spørsmål først – forgrening trenger noe å basere seg på.",
    Designer_Field_BranchingToggle: "Vis bare dette spørsmålet når andre svar samsvarer",
    Designer_Field_Match: "Samsvar med",
    Designer_Field_MatchAll: "alle disse",
    Designer_Field_MatchAny: "noen av disse",
    Designer_Field_AddCondition: "Legg til betingelse",
    Designer_Field_TabValidation: "Validering",
    Designer_Field_HelpText: "Hjelpetekst",
    Designer_Field_HelpTextPlaceholder: "Vises under spørsmålsetiketten",
    Designer_Field_CheckboxLabel: "Etikett for avmerkingsboks",
    Designer_Field_Placeholder: "Plassholder",
    Designer_Field_DefaultAnswer: "Standardsvar",
    Designer_Field_RequiredMessage: "Egendefinert melding for obligatorisk",
    Designer_Field_RequiredMessagePlaceholder: "{title} er obligatorisk",
    Designer_Field_ThisQuestion: "Dette spørsmålet",
    Designer_Field_RequiredMessageDescription: "Vises i stedet for standardmeldingen når dette spørsmålet står tomt",
    Designer_Field_ReadOnly: "Skrivebeskyttet (svaret kan bare komme fra en forhåndsutfylt kobling)",
    Designer_Field_ValidationRules: "Valideringsregler",
    Designer_Field_MaxLength: "Maksimal lengde",
    Designer_Field_Pattern: "Må samsvare med dette mønsteret",
    Designer_Field_PatternDescription: "Et regulært uttrykk. La stå tomt for å hoppe over mønsterkontroll.",
    Designer_Field_PatternMessage: "Melding når mønsteret ikke samsvarer",
    Designer_Field_PatternMessagePlaceholder: "Dette svaret har ikke forventet format",
    Designer_Field_Format: "Format",
    Designer_Field_UnitSuffix: "Enhet som vises etter verdien",
    Designer_Field_UnitSuffixPlaceholder: "kg, timer, stk…",
    Designer_Field_Minimum: "Minimum",
    Designer_Field_Maximum: "Maksimum",
    Designer_Field_Decimals: "Desimaler",
    Designer_Field_Formula: "Formel",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Referer til andre spørsmål med teksten deres i klammeparenteser. Støtter + - * / ( ) samt round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Tilgjengelige spørsmål: {questions}",
    Designer_Field_NoneYet: "ingen ennå",
    Designer_Field_Step: "Trinn",
    Designer_Field_From: "Fra",
    Designer_Field_To: "Til",
    Designer_Field_LowLabel: "Etikett for den laveste enden",
    Designer_Field_LowLabelPlaceholder: "Ikke i det hele tatt sannsynlig",
    Designer_Field_HighLabel: "Etikett for den høyeste enden",
    Designer_Field_HighLabelPlaceholder: "Ekstremt sannsynlig",
    Designer_Field_SummarizeAs: "Oppsummer som",
    Designer_Field_SummarizeAverage: "Gjennomsnitt og fordeling",
    Designer_Field_SummarizeNps: "Net Promoter Score (krever en skala fra 0 til 10)",
    Designer_Field_NpsWarning: "Net Promoter Score gir bare mening på en skala fra 0 til 10. Sett Fra til 0 og Til til 10.",
    Designer_Field_NumberOfIcons: "Antall ikoner",
    Designer_Field_Icon: "Ikon",
    Designer_Field_AllowHalf: "Tillat halve verdier",
    Designer_Field_ShowOptionsAs: "Vis alternativer som",
    Designer_Field_DisplayButtons: "Innebygde knapper",
    Designer_Field_DisplayDropdown: "Nedtrekksliste",
    Designer_Field_DisplayAutomatic: "Automatisk (innebygd opptil 6 alternativer)",
    Designer_Field_AllowOther: "Legg til et «Annet»-alternativ med fritekst",
    Designer_Field_OtherLabel: "Etikett for «Annet»-alternativet",
    Designer_Field_OtherPlaceholder: "Annet",
    Designer_Field_ShuffleOptions: "Bland rekkefølgen på alternativene for hver respondent",
    Designer_Field_MinSelections: "Minimum antall valg",
    Designer_Field_MaxSelections: "Maksimum antall valg",
    Designer_Field_SourceList: "Kildeliste",
    Designer_Field_ChooseList: "Velg en liste",
    Designer_Field_LookupColumn: "Kolonne å lese alternativer fra",
    Designer_Field_ChooseColumn: "Velg en kolonne",
    Designer_Field_ChooseListFirst: "Velg en liste først",
    Designer_Field_LookupFilter: "Filter (valgfritt)",
    Designer_Field_LookupFilterDescription: "Et OData-filter som avgrenser hvilke kildeelementer som blir alternativer",
    Designer_Field_LookupInfo: "Svar lagrer alternativteksten, ikke en kobling til kildeelementet, slik at svarene forblir lesbare selv om kildelisten endres senere.",
    Designer_Field_ConsentText: "Vilkår som vises over avmerkingsboksen",
    Designer_Field_AllowMultiplePeople: "Tillat flere personer",
    Designer_Field_AllowGroups: "Tillat også grupper",
    Designer_Field_IncludeTime: "Ta med klokkeslett",
    Designer_Field_TimeStep: "Tidstrinn (minutter)",
    Designer_Field_MaxFiles: "Maksimalt antall filer",
    Designer_Field_MaxFileSize: "Maks. størrelse per fil (MB)",
    Designer_Field_AcceptedTypes: "Godkjente filtyper",
    Designer_Field_AcceptedTypesDescription: "Filtypenavn atskilt med komma. La stå tomt for å godta alt SharePoint tillater.",
    Designer_Field_FilesInfo: "Filer lagres som vedlegg på svarelementet. SharePoint blokkerer enkelte filtypenavn (for eksempel .exe) uansett hva du tillater her.",
    Designer_Field_Rows: "Rader",
    Designer_Field_ProvisionedNote: "Dette spørsmålet har allerede en listekolonne ({name}). Innstillinger som endrer kolonnetypen er låst – dupliser spørsmålet hvis du trenger en annen type.",
    Designer_Category_Text: "Tekst",
    Designer_Category_Choice: "Valg",
    Designer_Category_Scales: "Skalaer",
    Designer_Category_Date: "Dato",
    Designer_Category_People: "Personer",
    Designer_Category_Advanced: "Avansert",
    Designer_Category_Layout: "Oppsett",
    Designer_Menu_CommonPresets: "Vanlige forhåndsinnstillinger",
    Designer_Menu_AllTypes: "Alle spørsmålstyper",
    Designer_Menu_ChangeType: "Endre type",
    Designer_Menu_TypeLockedTitle: "Listekolonnen finnes allerede, så typen er låst. Dupliser spørsmålet for å endre den.",
    Designer_Menu_MoreSettings: "Forgrening, validering og mer",
    Designer_Menu_InsertBelow: "Sett inn spørsmål under",
    Designer_Card_Duplicate: "Dupliser",
    Designer_Card_DeleteQuestion: "Slett spørsmål",
    Designer_Outline_Aria: "Spørsmålsoversikt",
    Designer_Outline_QuestionCountOne: "{count} spørsmål",
    Designer_Outline_QuestionCountOther: "{count} spørsmål",
    Designer_Outline_IssuesTitle: "{count} problem(er) å gjennomgå",
    Designer_Outline_Find: "Finn et spørsmål",
    Designer_Outline_Empty: "Ingen spørsmål ennå.",
    Designer_Section_DefaultTitle: "Seksjon {number}",
    Designer_Card_Question: "Spørsmål",
    Designer_Card_BranchingTitle: "Dette spørsmålet vises bare når en forgreningsregel samsvarer",
    Designer_Card_BranchingChip: "Forgrening",
    Designer_Card_LiveTitle: "Listekolonnen finnes, så typen er låst",
    Designer_Card_LiveChip: "Aktiv",
    Designer_Card_CheckChip: "Kontroller",
    Designer_Option_Placeholder: "Alternativ {number}",
    Designer_Option_LabelAria: "Etikett for alternativ {number}",
    Designer_Option_ImageUrl: "Bilde-URL",
    Designer_Option_ImageUrlAria: "Bilde-URL for alternativ {number}",
    Designer_Option_Remove: "Fjern alternativ",
    Designer_Option_RemoveAria: "Fjern alternativ {number}",
    Designer_Option_Add: "Legg til alternativ",
    Designer_Option_OtherHint: "Respondenter kan også skrive inn et svar med etiketten «{label}».",
    Designer_Option_OtherFallback: "Annet",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Fjern",
    Designer_Grid_RemoveAria: "Fjern {label} {number}",
    Designer_Grid_Statements: "Utsagn",
    Designer_Grid_Scale: "Skala",
    Designer_Grid_AddStatement: "Legg til utsagn",
    Designer_Grid_AddScale: "Legg til skala",
    Designer_Width_Full: "Full bredde",
    Designer_Width_Half: "Halv bredde",
    Designer_Width_Third: "Én tredjedels bredde",
    Designer_Width_Aria: "Spørsmålsbredde",
    Designer_Card_BlockLabelPlaceholder: "Blokketikett (vises ikke for respondenter)",
    Designer_Card_QuestionText: "Spørsmålstekst",
    Designer_Card_MoveUp: "Flytt opp",
    Designer_Card_MoveQuestionUp: "Flytt spørsmålet opp",
    Designer_Card_MoveDown: "Flytt ned",
    Designer_Card_MoveQuestionDown: "Flytt spørsmålet ned",
    Designer_Card_DuplicateQuestion: "Dupliser spørsmål",
    Designer_Card_MultipleAnswers: "Flere svar",
    Designer_Card_Required: "Obligatorisk",
    Designer_Card_MoreOptions: "Flere alternativer",
    Designer_Card_MoreOptionsAria: "Flere alternativer for dette spørsmålet",
    Designer_Canvas_FormTitle: "Skjematittel",
    Designer_Canvas_DescriptionPlaceholder: "Legg til en beskrivelse (valgfritt)",
    Designer_Canvas_DescriptionAria: "Skjemabeskrivelse",
    Designer_Canvas_EmptyTitle: "Legg til ditt første spørsmål",
    Designer_Canvas_EmptyBody: "Velg en spørsmålstype for å komme i gang. Du kan endre rekkefølgen på spørsmålene ved å dra dem, og legge til forgrening slik at folk bare ser det som gjelder dem.",
    Designer_Section_Chip: "Seksjon {number} av {total}",
    Designer_Section_TitlePlaceholder: "Seksjonstittel",
    Designer_Section_TitleAria: "Tittel på seksjon {number}",
    Designer_Section_DescriptionPlaceholder: "Beskrivelse (valgfritt)",
    Designer_Section_DescriptionAria: "Beskrivelse av seksjon {number}",
    Designer_Section_MoveUp: "Flytt seksjonen opp",
    Designer_Section_MoveDown: "Flytt seksjonen ned",
    Designer_Section_Delete: "Slett seksjon",
    Designer_Card_DragToReorder: "Dra for å endre rekkefølge",
    Designer_Card_ReorderAria: "Endre rekkefølge på {title}",
    Designer_Card_ReorderFallback: "spørsmål",
    Designer_Canvas_AddNew: "Legg til ny",
    Designer_Canvas_AddSection: "Legg til seksjon",
    Form_Address_AriaWithLabel: "{label} – {part}",
    Form_Address_StreetPlaceholder: "Gateadresse",
    Form_Address_Street2Placeholder: "Leilighet, etasje osv. (valgfritt)",
    Form_Address_CityPlaceholder: "By",
    Form_Address_StatePlaceholder: "Fylke",
    Form_Address_PostalCodePlaceholder: "Postnummer",
    Form_Address_CountryPlaceholder: "Land",
    Form_Address_StreetAria: "gateadresse",
    Form_Address_Street2Aria: "adresselinje 2",
    Form_Address_CityAria: "by",
    Form_Address_StateAria: "fylke",
    Form_Address_PostalCodeAria: "postnummer",
    Form_Address_CountryAria: "land",
    Form_Consent_DefaultLabel: "Jeg samtykker",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered} av {total} rader besvart",
    Form_Lookup_LoadError: "Alternativene for dette spørsmålet kunne ikke lastes inn.",
    Form_Lookup_Loading: "Laster inn alternativer…",
    Form_Lookup_SelectOptionsPlaceholder: "Velg alternativer",
    Form_Lookup_SelectOptionPlaceholder: "Velg et alternativ",
    Form_Person_Placeholder: "Begynn å skrive et navn…",
    Form_Person_SuggestedPeopleAndGroups: "Foreslåtte personer og grupper",
    Form_Person_SuggestedPeople: "Foreslåtte personer",
    Form_Person_NoPeopleOrGroups: "Fant ingen personer eller grupper",
    Form_Person_NoPeople: "Fant ingen personer",
    Form_Person_Searching: "Søker…",
    Form_Ranking_Moved: "{item} flyttet til posisjon {position} av {total}",
    Form_Ranking_MoveUp: "Flytt opp",
    Form_Ranking_MoveDown: "Flytt ned",
    Form_Ranking_MoveItemUpAria: "Flytt {item} opp",
    Form_Ranking_MoveItemDownAria: "Flytt {item} ned",
    Form_Rating_ValueText: "{value} av {max}",
    Form_Rating_NotRated: "Ikke vurdert",
    Form_Rating_Clear: "Fjern vurdering",
    Form_RichText_Bold: "Fet",
    Form_RichText_Italic: "Kursiv",
    Form_RichText_Underline: "Understreket",
    Form_RichText_BulletedList: "Punktliste",
    Form_RichText_NumberedList: "Nummerert liste",
    Form_RichText_ClearFormatting: "Fjern formatering",
    Form_RichText_ToolbarAria: "Tekstformatering",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\" ble hoppet over – grensen er {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" er ikke en godkjent filtype.",
    Form_File_TooLarge: "\"{name}\" er større enn {size} MB.",
    Form_File_AlreadyAttached: "\"{name}\" er allerede vedlagt.",
    Form_File_ReadError: "En av filene kunne ikke leses. Prøv å legge den ved på nytt.",
    Form_File_HintMaxSize: "opptil {size} MB per fil",
    Form_File_HintOneFile: "1 fil",
    Form_File_HintMaxFiles: "maks. {count} filer",
    Form_File_Reading: "Leser filer…",
    Form_File_DropPrompt: "Slipp filer her, eller klikk for å bla",
    Form_File_Remove: "Fjern {name}",
    Form_Signature_Alt: "Signatur",
    Form_Signature_AriaSigned: "{label} – signert",
    Form_Signature_AriaEmpty: "{label} – tom",
    Form_Signature_Clear: "Fjern",
    Form_Signature_Signed: "Signert",
    Form_Signature_Prompt: "Signer ovenfor med mus, penn eller finger",
    Form_Time_Placeholder: "Velg et klokkeslett",
    Form_Field_DatePlaceholder: "Velg en dato",
    Form_Field_TimeAriaWithLabel: "{label} – klokkeslett",
    Form_Field_TimeAria: "Klokkeslett",
    Form_Field_OtherDefault: "Annet",
    Form_Field_SelectOptionsPlaceholder: "Velg alternativer",
    Form_Field_PleaseSpecify: "Vennligst spesifiser",
    Form_Field_OtherSpecifyAria: "{label} – vennligst spesifiser",
    Form_Field_SelectOptionPlaceholder: "Velg et alternativ",
    Form_Field_Yes: "Ja",
    Form_Field_No: "Nei",
    Form_Field_SliderHint: "Dra glidebryteren for å svare",
    Form_Field_WebAddressAriaWithLabel: "{label} – nettadresse",
    Form_Field_WebAddressAria: "Nettadresse",
    Form_Field_DisplayTextPlaceholder: "Visningstekst (valgfritt)",
    Form_Field_DisplayTextAriaWithLabel: "{label} – visningstekst",
    Form_Field_DisplayTextAria: "Visningstekst",
    Form_Field_ChooseBetween: "Velg mellom {min} og {max}",
    Form_Field_ChooseAtLeast: "Velg minst {min}",
    Form_Field_ChooseUpTo: "Velg opptil {max}",
    Form_Field_SelectedCount: "{count} valgt",
    Form_Field_RequiredAria: "(obligatorisk)",
    Form_Submit_SaveError: "Svaret ditt kunne ikke lagres. Kontroller at skjemaet er publisert fra designeren, og at du har tillatelse til å legge til elementer i svarlisten.",
    Form_Empty_Message: "Dette skjemaet har ingen spørsmål ennå. Skjemaeieren kan legge dem til i fanen Spørsmål.",
    Form_Checking: "Kontrollerer skjemaet…",
    Form_Closed_NotYetOpen: "Ikke åpent ennå",
    Form_Closed_AlreadyAnswered: "Allerede besvart",
    Form_Closed_Title: "Skjemaet er lukket",
    Form_Confirmation_PreviewNotice: "Dette var en forhåndsvisning – ingenting ble lagret i svarlisten.",
    Form_Confirmation_PreviewAgain: "Forhåndsvis på nytt",
    Form_Confirmation_SubmitAnother: "Send inn et nytt svar",
    Form_Wizard_StepFallback: "Trinn {step}",
    Form_Wizard_StepsAria: "Skjematrinn",
    Form_Wizard_StepOf: "Trinn {step} av {total}",
    Form_ErrorSummary_Title: "Kontroller {count} svar:",
    Form_ErrorSummary_UntitledQuestion: "Spørsmål uten tittel",
    Form_ErrorSummary_Question: "Spørsmål",
    Form_ErrorSummary_Detail: " – {message}",
    Form_Nav_Back: "Tilbake",
    Form_Nav_Next: "Neste",
    Form_Draft_Saving: "Lagrer…",
    Form_Draft_Saved: "Utkast lagret",
    Form_Draft_SaveAndFinishLater: "Lagre og fullfør senere",
    Form_Draft_NotSaved: "Utkastet ble ikke lagret",
    Form_Submit_Preview: "Send (forhåndsvisning)",
    Form_Submit_Button: "Send",
    Form_Response_NoAnswer: "Ikke besvart",
    Form_Signature_TypeLabel: "Skriv inn fullt navn",
    Form_Signature_TypeInstead: "Skriv inn navnet ditt i stedet",
    Form_Signature_DrawInstead: "Tegn i stedet",
    Form_Edit_Button: "Rediger forrige svar",
    Form_Edit_Available: "Du har allerede sendt inn et svar. Du kan redigere det i stedet for å sende inn et nytt.",
    Form_Edit_Banner: "Du redigerer forrige svar.",
    Form_Edit_Save: "Oppdater svar",
    Form_Edit_UpdatedTitle: "Svaret er oppdatert",
    Form_Edit_UpdatedMessage: "Endringene er lagret.",
    Form_Edit_LoadError: "Forrige svar kunne ikke lastes inn. Prøv igjen.",
    Form_Draft_MissingFiles: "Legg ved på nytt: {names}. Disse filene kunne ikke gjenopprettes.",
    Form_Attachments_Failed: "Svarene dine er lagret, men disse vedleggene kunne ikke lastes opp: {names}. Prøv igjen eller kontakt skjemaeieren.",
    Logic_ThisQuestion: "Dette spørsmålet",
    Logic_Required: "{label} er obligatorisk",
    Logic_RequiredConsent: "Merk av i boksen for å fortsette",
    Logic_RequiredFile: "Legg ved minst én fil",
    Logic_RequiredSignature: "Legg til signaturen din",
    Logic_RequiredLikert: "Svar på alle rader",
    Logic_InvalidEmail: "Angi en gyldig e-postadresse",
    Logic_InvalidPhone: "Angi et gyldig telefonnummer",
    Logic_InvalidUrl: "Angi en gyldig nettadresse som starter med http:// eller https://",
    Logic_MinValue: "Verdien må være minst {value}",
    Logic_MaxValue: "Verdien kan være høyst {value}",
    Logic_MaxLength: "Maksimal lengde er {max} tegn",
    Logic_ChooseAtLeastOne: "Velg minst {count} alternativ",
    Logic_ChooseAtLeastMany: "Velg minst {count} alternativer",
    Logic_ChooseAtMostOne: "Velg høyst {count} alternativ",
    Logic_ChooseAtMostMany: "Velg høyst {count} alternativer",
    Logic_LikertRemaining: "Svar på alle rader ({count} gjenstår)",
    Logic_MaxFilesOne: "Legg ved høyst {count} fil",
    Logic_MaxFilesMany: "Legg ved høyst {count} filer",
    Logic_FileTooLarge: "«{name}» er større enn {size} MB",
    Logic_FileTypeNotAccepted: "«{name}» er ikke en godkjent filtype ({types})",
    Logic_AddressRequired: "Angi minst gate og by",
    Logic_PatternDefault: "Svaret har ikke forventet format",
    Logic_Yes: "Ja",
    Logic_No: "Nei",
    Logic_Agreed: "Samtykket",
    Logic_NotAgreed: "Ikke samtykket",
    Logic_Signed: "Signert",
    Logic_NoAnswer: "(ingen svar)",
    Logic_Unknown: "(ukjent)",
    Logic_OtherSlice: "Andre ({count})",
    Logic_CsvResponseId: "Svar-ID",
    Logic_CsvSubmitted: "Sendt inn",
    Logic_CsvSubmittedBy: "Sendt inn av",
    Logic_EmailQuestion: "Spørsmål",
    Logic_EmailViewItem: "Vis i Microsoft Lists",
    Logic_EmailFooter: "Sendt automatisk av Smart Forms.",
    Logic_ClosedDefault: "Dette skjemaet tar ikke lenger imot svar.",
    Logic_NotYetOpen: "Dette skjemaet åpner {date}.",
    Logic_AlreadyResponded: "Du har allerede svart på dette skjemaet. Takk!",
    Logic_UntitledQuestion: "Et spørsmål uten tittel",
    Logic_Issue_NoQuestions: "Legg til minst ett spørsmål før du samler inn svar.",
    Logic_Issue_NoTitle: "Et spørsmål har ingen tekst – det får automatisk et navn når du publiserer.",
    Logic_Issue_DuplicateTitle: "{label} har samme tekst som et annet spørsmål, noe som gjør resultatene vanskeligere å lese.",
    Logic_Issue_NeedTwoOptions: "{label} trenger minst to alternativer.",
    Logic_Issue_ImageNoImage: "{label} har alternativer uten bilde – de vises som tekstfliser.",
    Logic_Issue_LikertNeedRow: "{label} trenger minst én rad.",
    Logic_Issue_LikertNeedColumns: "{label} trenger minst to skalakolonner.",
    Logic_Issue_NoLookupList: "{label} har ingen kildeliste valgt.",
    Logic_Issue_NoFormula: "{label} har ingen formel.",
    Logic_Issue_BadFormula: "{label} har en formel som ikke kan beregnes. Kontroller parenteser og operatorer.",
    Logic_Issue_MissingRefs: "{label} refererer til spørsmål som ikke finnes: {names}.",
    Logic_Issue_BadPattern: "{label} har et ugyldig valideringsmønster.",
    Logic_Issue_BrokenRule: "{label} har en forgreningsregel som peker på et slettet spørsmål.",
    Logic_Issue_SelfRule: "{label} har en forgreningsregel som refererer til seg selv.",
    Logic_Issue_RuleMismatch: "{label} har en forgreningsregel som ikke lenger passer til spørsmålet den avhenger av.",
    Logic_Issue_RequiredReadOnly: "{label} er både obligatorisk og skrivebeskyttet, så det kan bare besvares via en forhåndsutfylt kobling.",
    Logic_Issue_EmptySection: "En seksjon har ingen spørsmål og hoppes over.",
    Logic_Issue_CloseBeforeOpen: "Sluttdatoen er den samme som eller før startdatoen, så skjemaet vil aldri ta imot svar.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "E-post for godkjenning er slått på, men godkjenningstrinnet er slått av.",
    Logic_Op_equals: "er",
    Logic_Op_notEquals: "er ikke",
    Logic_Op_contains: "inneholder",
    Logic_Op_notContains: "inneholder ikke",
    Logic_Op_notEmpty: "er besvart",
    Logic_Op_empty: "er ikke besvart",
    Logic_Op_greaterThan: "er større enn",
    Logic_Op_greaterOrEqual: "er minst",
    Logic_Op_lessThan: "er mindre enn",
    Logic_Op_lessOrEqual: "er høyst",
    Logic_Op_between: "er mellom",
    Logic_Op_before: "er før",
    Logic_Op_after: "er etter",
    Logic_Type_Text: "Kort svar",
    Logic_TypeDesc_Text: "Én tekstlinje",
    Logic_Category_Text: "Tekst",
    Logic_Type_MultilineText: "Langt svar",
    Logic_TypeDesc_MultilineText: "Flere linjer med ren tekst",
    Logic_Type_RichText: "Formatert tekst",
    Logic_TypeDesc_RichText: "Fet skrift, lister og koblinger",
    Logic_Type_Choice: "Valg",
    Logic_TypeDesc_Choice: "Velg fra en liste med alternativer",
    Logic_Category_Choice: "Valg",
    Logic_Type_ImageChoice: "Bildevalg",
    Logic_TypeDesc_ImageChoice: "Velg fra bildefliser",
    Logic_Type_Lookup: "Oppslag fra en liste",
    Logic_TypeDesc_Lookup: "Alternativer hentes direkte fra en annen SharePoint-liste",
    Logic_Type_YesNo: "Ja / Nei",
    Logic_TypeDesc_YesNo: "En enkel av/på-bryter",
    Logic_Type_Consent: "Samtykke",
    Logic_TypeDesc_Consent: "En avmerkingsboks respondenten må krysse av for å fortsette",
    Logic_Type_Ranking: "Rangering",
    Logic_TypeDesc_Ranking: "Dra alternativene i prioritert rekkefølge",
    Logic_Type_Rating: "Vurdering",
    Logic_TypeDesc_Rating: "Stjerner, hjerter eller tommel opp",
    Logic_Category_Scales: "Skalaer",
    Logic_Type_Scale: "Meningsskala",
    Logic_TypeDesc_Scale: "En nummerert skala med etiketter i endene",
    Logic_Type_Slider: "Glidebryter",
    Logic_TypeDesc_Slider: "En verdi på en glidende skala",
    Logic_Type_Likert: "Likert-rutenett",
    Logic_TypeDesc_Likert: "Vurder flere utsagn på én felles skala",
    Logic_Type_Number: "Tall",
    Logic_TypeDesc_Number: "Vanlig tall, valuta eller prosent",
    Logic_Category_Advanced: "Avansert",
    Logic_Type_Calculated: "Beregnet",
    Logic_TypeDesc_Calculated: "En skrivebeskyttet sum beregnet fra andre svar",
    Logic_Type_Date: "Dato",
    Logic_TypeDesc_Date: "En kalenderdato, eventuelt med klokkeslett",
    Logic_Category_Date: "Dato",
    Logic_Type_Time: "Klokkeslett",
    Logic_TypeDesc_Time: "Et klokkeslett alene",
    Logic_Type_Person: "Person",
    Logic_TypeDesc_Person: "Velg noen i organisasjonen",
    Logic_Category_People: "Personer",
    Logic_Type_Email: "E-post",
    Logic_TypeDesc_Email: "En e-postadresse, validert",
    Logic_Type_Phone: "Telefon",
    Logic_TypeDesc_Phone: "Et telefonnummer, validert",
    Logic_Type_Address: "Adresse",
    Logic_TypeDesc_Address: "Gate, by, postnummer og land",
    Logic_Type_Hyperlink: "Kobling",
    Logic_TypeDesc_Hyperlink: "En nettadresse",
    Logic_Type_FileUpload: "Filopplasting",
    Logic_TypeDesc_FileUpload: "Legg ved én eller flere filer til svaret",
    Logic_Type_Signature: "Signatur",
    Logic_TypeDesc_Signature: "Signer med mus, penn eller finger",
    Logic_Type_Content: "Tekstblokk",
    Logic_TypeDesc_Content: "Instruksjoner eller et bilde – samler ikke inn svar",
    Logic_Category_Layout: "Oppsett",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Hvor sannsynlig er det at du anbefaler …",
    Logic_Preset_satisfaction: "Tilfredshet (1–5)",
    Logic_PresetDesc_satisfaction: "Svært utilfreds til svært fornøyd",
    Logic_Preset_currency: "Valuta",
    Logic_PresetDesc_currency: "Et pengebeløp",
    Logic_Preset_percent: "Prosent",
    Logic_PresetDesc_percent: "En prosentverdi",
    Logic_Template_blank_Name: "Tomt skjema",
    Logic_Template_blank_Description: "Start fra bunnen av",
    Logic_Template_feedback_Name: "Kundetilbakemelding",
    Logic_Template_feedback_Description: "NPS, vurderinger og åpne kommentarer",
    Logic_Template_event_Name: "Arrangementspåmelding",
    Logic_Template_event_Description: "Deltakerinformasjon, økter og kostbehov",
    Logic_Template_itrequest_Name: "IT-tjenesteforespørsel",
    Logic_Template_itrequest_Description: "Kategoriserte forespørsler med prioritet og vedlegg",
    Logic_Template_expense_Name: "Utgiftsrefusjon",
    Logic_Template_expense_Description: "Linjeposter, kvitteringer og en beregnet sum",
    Logic_Template_pulse_Name: "Medarbeiderundersøkelse (puls)",
    Logic_Template_pulse_Description: "Likert-rutenett, engasjementsskala og merknad om anonymitet",
    Logic_Template_safety_Name: "Sikkerhetsinspeksjon",
    Logic_Template_safety_Description: "Sjekkliste, bilder og en signatur",
    Logic_Template_booking_Name: "Booking av rom eller ressurs",
    Logic_Template_booking_Description: "Ressursvelger basert på oppslag, med tidsluke",
    Charts_ColumnChartAria: "Kolonnediagram med {count} kategorier",
    Charts_DonutChartAria: "Smultringdiagram med {count} kategorier",
    Charts_NoAnswers: "Ingen svar ennå.",
    Charts_NoResponses: "Ingen svar ennå.",
    Charts_Responses: "Svar",
    Charts_ResponsesOverTime: "Svar over tid",
    Responses_Chart_Answer: "Svar",
    Responses_Chart_Average: "Gjennomsnitt",
    Responses_Chart_AverageOf: "Gjennomsnitt av {count}",
    Responses_Chart_AveragePosition: "Gjennomsnittlig plassering",
    Responses_Chart_AverageRange: "Gjennomsnitt (1–{max})",
    Responses_Chart_AvgValue: "gj.snitt {value}",
    Responses_Chart_Detractors: "Kritikere (0–6)",
    Responses_Chart_Max: "Maks.",
    Responses_Chart_Maximum: "Maksimum",
    Responses_Chart_Median: "Median",
    Responses_Chart_MentionOne: "{count} omtale",
    Responses_Chart_MentionOther: "{count} omtaler",
    Responses_Chart_Min: "Min.",
    Responses_Chart_Minimum: "Minimum",
    Responses_Chart_NoAnswers: "Ingen svar ennå.",
    Responses_Chart_NoNumeric: "Ingen numeriske svar ennå.",
    Responses_Chart_NoRankings: "Ingen rangeringer ennå.",
    Responses_Chart_NoScores: "Ingen poengsummer ennå.",
    Responses_Chart_NotEnoughText: "Ikke nok tekst til å oppsummere ennå.",
    Responses_Chart_NpsScore: "NPS-score",
    Responses_Chart_Option: "Alternativ",
    Responses_Chart_Passives: "Nøytrale (7–8)",
    Responses_Chart_Promoters: "Tilhengere (9–10)",
    Responses_Chart_ResponseOne: "svar",
    Responses_Chart_ResponseOther: "svar",
    Responses_Chart_Responses: "Svar",
    Responses_Chart_ShowingAnswers: "Viser {shown} av {total} svar.",
    Responses_Chart_Statement: "Utsagn",
    Responses_Chart_Statistic: "Statistikk",
    Responses_Chart_StdDev: "Standardavvik",
    Responses_Chart_StdDeviation: "Standardavvik",
    Responses_Chart_Total: "Totalt",
    Responses_Chart_Value: "Verdi",
    Responses_Dashboard_AllHidden: "Alle spørsmål er skjult fra dashbordet. Bruk «Vis skjulte spørsmål» for å hente dem tilbake.",
    Responses_Dashboard_AnsweredOf: "{answered} av {total} besvart",
    Responses_Dashboard_AnsweredOfPinned: "{answered} av {total} besvart · festet",
    Responses_Dashboard_AveragedAcrossResponses: "Gjennomsnitt på tvers av svar",
    Responses_Dashboard_ByDay: "Per dag",
    Responses_Dashboard_ByMonth: "Per måned",
    Responses_Dashboard_ByWeek: "Per uke",
    Responses_Dashboard_ChartAuto: "Automatisk",
    Responses_Dashboard_ChartBars: "Stolper",
    Responses_Dashboard_ChartColumns: "Kolonner",
    Responses_Dashboard_ChartDonut: "Smultringdiagram",
    Responses_Dashboard_ChartGauge: "Måler",
    Responses_Dashboard_ChartHistogram: "Histogram",
    Responses_Dashboard_ChartOptions: "Diagramalternativer",
    Responses_Dashboard_ChartOptionsFor: "Diagramalternativer for {title}",
    Responses_Dashboard_ChartStatistics: "Statistikk",
    Responses_Dashboard_ChartTable: "Tabell",
    Responses_Dashboard_ChartWordFrequency: "Ordfrekvens",
    Responses_Dashboard_EmptyBody: "Når folk begynner å svare, fylles dette dashbordet ut automatisk – hovedtall, en tidslinje for svar og et diagram for spørsmålene som er verdt å følge med på.",
    Responses_Dashboard_EmptyTitle: "Ingen svar ennå",
    Responses_Dashboard_Hide: "Skjul fra dashbord",
    Responses_Dashboard_Highlights: "Høydepunkter",
    Responses_Dashboard_Last7Days: "Siste 7 dager",
    Responses_Dashboard_LatestDate: "Nyeste {date}",
    Responses_Dashboard_MedianTimeToComplete: "Median tid til fullføring",
    Responses_Dashboard_NoPriorWeek: "Ingen forrige uke å sammenligne med",
    Responses_Dashboard_OneEach: "Ett hver",
    Responses_Dashboard_Pin: "Fest til dashbord",
    Responses_Dashboard_QuestionFallback: "spørsmål",
    Responses_Dashboard_QuestionsAnswered: "Besvarte spørsmål",
    Responses_Dashboard_RecordedOnSubmit: "Registreres ved innsending",
    Responses_Dashboard_RepeatResponses: "{count} gjentatte svar",
    Responses_Dashboard_ResponsesOverTime: "Svar over tid",
    Responses_Dashboard_ShowHidden: "Vis skjulte spørsmål",
    Responses_Dashboard_SinceMidnight: "Siden midnatt",
    Responses_Dashboard_Today: "I dag",
    Responses_Dashboard_TotalResponses: "Totalt antall svar",
    Responses_Dashboard_UniqueRespondents: "Unike respondenter",
    Responses_Dashboard_Unpin: "Løsne fra dashbord",
    Responses_Dashboard_UntitledQuestion: "Spørsmål uten tittel",
    Responses_Dashboard_VsPrevious7Days: "mot forrige 7 dager",
    Responses_Detail_Answers: "Svar",
    Responses_Detail_AsTheForm: "Som skjemaet",
    Responses_Detail_Cancel: "Avbryt",
    Responses_Detail_Delete: "Slett",
    Responses_Detail_DeleteBody: "Listeelementet flyttes til områdets papirkurv, slik at det kan gjenopprettes derfra.",
    Responses_Detail_DeleteTitle: "Slette dette svaret?",
    Responses_Detail_Deleting: "Sletter…",
    Responses_Detail_Draft: "Utkast",
    Responses_Detail_Header: "Svar {index} av {total}",
    Responses_Detail_LoadingAttachments: "Laster inn vedlegg…",
    Responses_Detail_Next: "Neste svar",
    Responses_Detail_NoAnswer: "Ikke besvart",
    Responses_Detail_Previous: "Forrige svar",
    Responses_Detail_Print: "Skriv ut",
    Responses_Detail_Signature: "Signatur",
    Responses_Detail_Signed: "Signert",
    Responses_Detail_Took: "brukte {duration}",
    Responses_Summary_AnsweredOfType: "{answered} av {total} besvart · {type}",
    Responses_Summary_ByField: "Etter {title}",
    Responses_Summary_CompareBy: "Sammenlign etter…",
    Responses_Summary_EmptyBody: "Hvert spørsmål får sin egen oppsummering her.",
    Responses_Summary_NoComparison: "Ingen sammenligning",
    Responses_Summary_NothingToCompare: "Ingen svar besvarte «{title}», så det er ingenting å sammenligne.",
    Responses_Summary_OtherNote: "Diagrammer med mer enn {max} kategorier grupperer de minste i «Annet» – bytt et kort til Tabell for å se alle verdier.",
    Responses_Summary_ResponseCountOne: "{count} svar",
    Responses_Summary_ResponseCountOther: "{count} svar",
    Responses_Summary_SeeAllAnswers: "Se alle svar i tabellen",
    Responses_Summary_SegmentNote: "Viser de {groups} største gruppene. Et svar som valgte flere alternativer vises i hver samsvarende gruppe, så gruppetotalene kan bli høyere enn {total}.",
    Responses_Summary_SplitBy: "Del opp etter {title}",
    Responses_Summary_Untitled: "uten tittel",
    Responses_Table_Apply: "Bruk",
    Responses_Table_Cancel: "Avbryt",
    Responses_Table_ClearSelection: "Fjern utvalg",
    Responses_Table_ColumnOrder: "Kolonnerekkefølge",
    Responses_Table_ColumnsCount: "Kolonner ({shown}/{total})",
    Responses_Table_Delete: "Slett",
    Responses_Table_DeleteBody: "Listeelementene flyttes til områdets papirkurv, slik at de kan gjenopprettes derfra.",
    Responses_Table_DeleteSelected: "Slett valgte",
    Responses_Table_DeleteTitleOne: "Slette {count} svar?",
    Responses_Table_DeleteTitleOther: "Slette {count} svar?",
    Responses_Table_Deleting: "Sletter…",
    Responses_Table_MoveDown: "Flytt ned",
    Responses_Table_MoveDownFor: "Flytt {title} ned",
    Responses_Table_MoveUp: "Flytt opp",
    Responses_Table_MoveUpFor: "Flytt {title} opp",
    Responses_Table_NoColumns: "Ingen spørsmålskolonner er synlige ennå.",
    Responses_Table_NoMatch: "Ingen svar samsvarer med gjeldende filtre.",
    Responses_Table_NothingToShow: "Ingenting å vise",
    Responses_Table_OpenResponse: "Åpne dette svaret",
    Responses_Table_OrderNote: "Sendt inn og Sendt inn av kommer alltid først. Dra-rekkefølgen gjelder spørsmålskolonnene.",
    Responses_Table_Reorder: "Endre rekkefølge",
    Responses_Table_ResetColumns: "Tilbakestill kolonner",
    Responses_Table_SelectResponse: "Velg dette svaret",
    Responses_Table_SelectedOne: "{count} svar valgt",
    Responses_Table_SelectedOther: "{count} svar valgt",
    Responses_Table_ShowAll: "Vis alle",
    Responses_Table_ShowTheseQuestions: "Vis disse spørsmålene",
    Responses_Table_Submitted: "Sendt inn",
    Responses_Table_SubmittedBy: "Sendt inn av",
    Responses_Table_ToggleSelection: "Veksle utvalg",
    Responses_Table_Unknown: "Ukjent",
    Responses_Table_Untitled: "Uten tittel",
    Responses_View_AllTime: "Alle tider",
    Responses_View_AnyAnswer: "Alle svar",
    Responses_View_Clear: "Tøm",
    Responses_View_CopyShareLink: "Kopier delingskobling",
    Responses_View_CountFiltered: "{shown} av {total} svar",
    Responses_View_CountOne: "{count} svar",
    Responses_View_CountOther: "{count} svar",
    Responses_View_Dashboard: "Dashbord",
    Responses_View_DateRange: "Datoperiode",
    Responses_View_EmptyBody: "Del skjemaet for å begynne å samle inn svar. Svarene lagres i «{list}» og vises her med en gang.",
    Responses_View_EmptyTitle: "Ingen svar ennå",
    Responses_View_ExportCsv: "Eksporter CSV",
    Responses_View_FilterByAnswer: "Filtrer etter svar",
    Responses_View_FilterByQuestion: "Filtrer etter spørsmål",
    Responses_View_FilterValue: "Filterverdi",
    Responses_View_Last30Days: "Siste 30 dager",
    Responses_View_Last7Days: "Siste 7 dager",
    Responses_View_Last90Days: "Siste 90 dager",
    Responses_View_LoadError: "Svarene kunne ikke lastes inn. Publiser skjemaet én gang slik at listekolonnene finnes, og prøv deretter igjen.",
    Responses_View_Loading: "Laster inn svar…",
    Responses_View_MoreActions: "Flere svarhandlinger",
    Responses_View_PreviewForm: "Forhåndsvis skjemaet",
    Responses_View_Refresh: "Oppdater",
    Responses_View_ResponsesTab: "Svar ({count})",
    Responses_View_SearchPlaceholder: "Søk i alle svar",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Velg en verdi",
    Responses_View_Summary: "Oppsummering",
    Responses_View_Today: "I dag",
    Responses_View_Truncated: "Denne listen har flere svar enn Smart Forms laster inn samtidig. De nyeste {count} vises – åpne listen i Microsoft Lists for å se hele settet.",
    Responses_View_TryAgain: "Prøv igjen",
    Responses_View_Untitled: "Uten tittel",
    Responses_Approval_Column: "Godkjenning",
    Responses_Approval_ReviewerColumn: "Vurdert av",
    Responses_Approval_CommentColumn: "Kommentar fra vurderer",
    Responses_Approval_Pending: "Venter",
    Responses_Approval_Approved: "Godkjent",
    Responses_Approval_Rejected: "Avvist",
    Responses_Approval_AnyStatus: "Alle godkjenningsstatuser",
    Responses_Approval_FilterLabel: "Filtrer etter godkjenningsstatus",
    Responses_Approval_ApproveSelected: "Godkjenn valgte",
    Responses_Approval_RejectSelected: "Avvis valgte",
    Responses_Approval_BulkFailed: "{count} svar kunne ikke oppdateres. Prøv igjen.",
    Responses_Approval_Approve: "Godkjenn",
    Responses_Approval_Reject: "Avvis",
    Responses_Approval_Reset: "Tilbakestill til venter",
    Responses_Approval_CommentLabel: "Kommentar (valgfritt)",
    Responses_Approval_ReviewedBy: "Vurdert av {name}",
    Responses_Approval_Error: "Avgjørelsen kunne ikke lagres. Prøv igjen.",
    Responses_Dashboard_ApprovalStatus: "Venter på vurdering",
    Responses_Dashboard_ApprovalBreakdown: "{pending} venter, {approved} godkjent, {rejected} avvist",
    Responses_Dashboard_TimelineCoarsened: "Datoperioden er lang, så tidslinjen ble gruppert grovere ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Datoperioden er svært lang, så bare de siste {count} periodene vises.",
    Service_Item_DefaultTitle: "Svar – {date}",
    Service_Email_ApprovalSubject: "Svaret ditt er {status} – {title}",
    Service_Email_ApprovalHeading: "Svaret ditt er {status}",
    Service_Email_ApprovalIntro: "En vurderer har merket svaret ditt på «{title}» som {status}.",
    Service_Email_ApprovalCommentLabel: "Kommentar fra vurderer",
    Service_Approval_Approved: "godkjent",
    Service_Approval_Rejected: "avvist",
    Service_Approval_Pending: "venter",
    Service_Lookup_InvalidFilter: "Oppslagsfilteret er ikke gyldig.",
    Service_Edit_NotAllowed: "Dette skjemaet tillater ikke redigering av et innsendt svar.",
    Service_Edit_NotYours: "Du kan bare redigere ditt eget svar.",
    Service_Signature_AttachmentLabel: "Signatur",
    PropertyPane_ListsLoadFailed: "Listene på dette området kunne ikke lastes inn.",
    PropertyPane_EnterListName: "Skriv inn et navn for den nye listen først.",
    PropertyPane_CreatingList: "Oppretter \"{name}\"…",
    PropertyPane_ListCreated: "Listen \"{title}\" er opprettet og valgt.",
    PropertyPane_ListAlreadyExists: "En liste med navnet \"{name}\" finnes allerede – velg den fra nedtrekkslisten ovenfor.",
    PropertyPane_CreateListFailed: "Kunne ikke opprette listen. Kontroller at du har tillatelse til å opprette lister på dette området.",
    PropertyPane_Description: "Velg SharePoint-listen som lagrer skjemasvar, eller opprett en ny. Alt annet – spørsmål, utseende, varsler – redigeres direkte på siden.",
    PropertyPane_ResponseList_GroupName: "Svarliste",
    PropertyPane_ListDropdown_Label: "Lagre svar i denne listen",
    PropertyPane_ResponsesGoTo: "Svar sendes til \"{name}\".",
    PropertyPane_PickList: "Velg en liste, eller opprett en nedenfor.",
    PropertyPane_LoadingLists: "Laster inn lister…",
    PropertyPane_NewListName_Label: "Eller opprett en ny liste",
    PropertyPane_NewListName_Placeholder: "Navn på ny liste",
    PropertyPane_CreateList_Button: "Opprett liste",
    PropertyPane_Tips_GroupName: "Tips",
    PropertyPane_Tip_AutoSave: "Spørsmål og innstillinger lagres automatisk mens du redigerer – du trenger ikke lagre eller publisere siden.",
    PropertyPane_Tip_Permissions: "Respondenter trenger tillatelse til å legge til elementer i svarlisten. Kontroller listetillatelsene hvis noen melder om en feil ved innsending.",
    PropertyPane_Tip_Share: "Bruk «Samle inn svar» på siden for å opprette listekolonnene og få en delbar utfyllingskobling.",
    App_ErrorBoundary_Title: "Smart Forms – gjengivelsesfeil",
    App_ErrorBoundary_Message: "Melding:",
    App_ErrorBoundary_Stack: "Stakk:",
    App_ErrorBoundary_NoStack: "(ingen stakk tilgjengelig)",
    App_ErrorBoundary_ConsoleNote: "Alle detaljer ble også skrevet til nettleserkonsollen.",
    App_DefaultQuestionTitle: "Spørsmål {number}",
    App_Error_ListMissing: "Listen som er konfigurert for dette skjemaet finnes ikke lenger. Velg en annen liste i webdelinnstillingene.",
    App_Error_LoadConfig: "Noe gikk galt under lasting av skjemakonfigurasjonen.",
    App_Error_Unable: "Kan ikke laste inn skjemaet.",
    App_Publish_ConflictNotice: "\"{title}\" har allerede en listekolonne av en annen type ({type}). Gi spørsmålet et nytt navn slik at en ny kolonne kan opprettes, eller endre typen tilbake.",
    App_Publish_ConflictUnnamedQuestion: "et spørsmål",
    App_Publish_ColumnsAddedOne: "{count} kolonne ble lagt til i \"{list}\".",
    App_Publish_ColumnsAddedOther: "{count} kolonner ble lagt til i \"{list}\".",
    App_Publish_TheList: "listen",
    App_Publish_UpToDate: "Svarlisten er allerede oppdatert.",
    App_Publish_Error: "Listekolonnene kunne ikke opprettes. Dette betyr vanligvis at du ikke har tillatelsen Administrer lister for svarlisten, men det kan også skje på områder der egendefinerte skript er deaktivert. Sjekk nettleserkonsollen for den underliggende feilen, eller prøv igjen.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Bygg et polert skjema oppå en SharePoint-liste – {count} spørsmålstyper, forgreningslogikk, filopplasting, delbare utfyllingskoblinger og et resultatdashbord.",
    App_Placeholder_ChooseList: "Velg eller opprett en liste",
    App_Placeholder_Hint: "Rediger siden og konfigurer denne webdelen for å komme i gang.",
    App_Loading: "Laster inn skjema…",
    App_OpenSettings: "Åpne innstillinger",
    App_Tab_Questions: "Spørsmål",
    App_Tab_QuestionsWithCount: "Spørsmål ({count})",
    App_Tab_Responses: "Svar",
    App_Tab_Responses_Title: "Svarene lagres i \"{list}\"",
    App_Templates_Start: "Start fra en mal",
    App_Settings_Title: "Skjemainnstillinger – utseende, varsler, tilgang",
    App_Settings_AriaLabel: "Skjemainnstillinger",
    App_Preview: "Forhåndsvisning",
    App_Preview_Close: "Lukk forhåndsvisning",
    App_Preview_Hint: "Forhåndsvisning – ingenting du sender inn her, lagres. Validering og forgrening fungerer nøyaktig slik de vil gjøre for respondentene.",
    App_Publish_GettingReady: "Gjør klar…",
    App_Publish_CollectResponses: "Samle inn svar",
    App_Publish_Share: "Del",
    App_Retry: "Prøv igjen",
    App_SaveError_Banner: "Den siste endringen kunne ikke lagres. Kontroller tilkoblingen, og prøv deretter igjen.",
    App_Preflight_BlockingTitle: "Rett opp dette før du samler inn",
    App_Preflight_WarningTitle: "Verdt et blikk først",
    App_Preflight_BlockingText: "Disse vil hindre det publiserte skjemaet i å fungere som det skal.",
    App_Preflight_WarningText: "Ingenting er ødelagt, men disse bør vanligvis rettes før du deler koblingen.",
    App_Preflight_GoTo: "Gå til",
    App_Preflight_CollectAnyway: "Samle inn svar likevel",
    App_Preflight_Back: "Tilbake til skjemaet",
    App_Cancel: "Avbryt",
    App_Done: "Ferdig",
    App_Share_Title: "Skjemaet ditt er klart til deling",
    App_Share_SubText: "Send denne koblingen til alle som skal fylle ut skjemaet.",
    App_Share_LinkAriaLabel: "Delingskobling",
    App_Share_Copy: "Kopier",
    App_Share_Copied: "Kopiert",
    App_Share_AddItemsEmphasis: "legge til elementer",
    App_Share_PermissionNote: "Respondenter trenger tillatelse til å {addItems} i «{title}», og tilgang til denne siden. Hvis noen får en feil ved innsending, er dette nesten alltid årsaken.",
    App_Share_PrefillNote: "Du kan forhåndsutfylle svar på spørsmål i koblingen ved å legge til kolonnenavnet, for eksempel {example}.",
    App_Templates_ReplaceWarning: "Hvis du velger en mal, erstattes spørsmålene du har nå.",
    App_Templates_PickStart: "Velg et utgangspunkt – du kan endre alt etterpå.",
    App_Templates_Empty: "Tom",
    App_Templates_QuestionCount: "{count} spørsmål",
    App_SaveChip_SavingTitle: "Lagrer den siste redigeringen",
    App_SaveChip_Saving: "Lagrer…",
    App_SaveChip_FailedTitle: "Den siste redigeringen kunne ikke lagres. Kontroller tilkoblingen og prøv igjen.",
    App_SaveChip_Failed: "Lagring mislyktes",
    App_SaveChip_SavedTitle: "Alle endringer er lagret",
    App_SaveChip_Saved: "Lagret",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Nytt svar – {title}",
    Service_Email_NewResponseHeading: "Nytt svar: {title}",
    Service_Email_NewResponseIntro: "Noen har nettopp sendt inn et svar – {date}.",
    Service_Email_ReceiptSubject: "Svaret ditt – {title}",
    Service_Email_ReceiptHeading: "Takk for svaret ditt!",
    Service_Email_ReceiptIntro: "Her er en kopi av det du sendte inn til \"{title}\".",
    App_History_Title: "Versjonslogg",
    App_History_RestoredNotice: "Gjenopprettet versjonen som ble lagret {date}. Se gjennom den, og bruk deretter Samle inn svar for å publisere nye spørsmål.",
    App_History_Undo: "Angre gjenoppretting",
    App_Share_CopyManual: "Nettleseren blokkerte kopieringen. Merk koblingen ovenfor og trykk Ctrl+C (Cmd+C på Mac) for å kopiere den.",
    App_Share_TeamsNote: "Du er i Microsoft Teams. Denne koblingen åpner SharePoint-siden direkte, så mottakerne trenger tilgang til området.",
    App_Share_PrefillNotSecure: "Forhåndsutfylte svar er kun en bekvemmelighet: alle med koblingen kan endre dem, så bruk dem aldri som en sikkerhetsgrense.",
    Designer_Section_DropHere: "Slipp et spørsmål her",
    Designer_Section_DropEnd: "Slipp her for å flytte til slutten av denne seksjonen",
    Designer_Rules_RemovedOne: "1 forgreningsregel som ikke lenger passet ble fjernet.",
    Designer_Rules_RemovedOther: "{count} forgreningsregler som ikke lenger passet ble fjernet.",
    Designer_Settings_AllowEdit: "La respondenter redigere svaret sitt",
    Designer_Settings_AllowEditHint: "Respondenter kan åpne på nytt og oppdatere det de har sendt inn. Hver person kan bare redigere sitt eget svar.",
    Designer_Settings_EnableApproval: "Aktiver godkjenningsarbeidsflyt",
    Designer_Settings_ApprovalNotify: "Send e-post til respondenten ved avgjørelse",
    Designer_Settings_ApprovalHint: "Legger til godkjenningskolonner i svarlisten neste gang du publiserer. Eiere godkjenner eller avviser svar fra Svar-fanen.",
    Designer_History_Title: "Versjonslogg",
    Designer_History_Intro: "Tidligere lagrede versjoner av spørsmålene og innstillingene i dette skjemaet. Gjenoppretting laster en versjon inn i designeren. Du kan angre, og nye spørsmål opprettes først når du publiserer.",
    Designer_History_Loading: "Laster versjoner ...",
    Designer_History_Empty: "Ingen tidligere versjoner ble funnet. Versjonslogg krever at versjonering er slått på for listen «Smart Forms Config» og minst én lagret endring.",
    Designer_History_Latest: "Nyeste",
    Designer_History_LatestTitle: "Dette er versjonen som er i bruk nå",
    Designer_History_By: "av {name}",
    Designer_History_UnknownAuthor: "Ukjent forfatter",
    Designer_History_VersionLabel: "versjon {label}",
    Designer_History_Preview: "Forhåndsvis",
    Designer_History_Restore: "Gjenopprett",
    Designer_History_QuestionsOne: "1 spørsmål",
    Designer_History_QuestionsOther: "{count} spørsmål",
    Designer_History_LoadFailed: "Denne versjonen kunne ikke lastes inn.",
    Designer_History_ConfirmTitle: "Gjenopprette denne versjonen?",
    Designer_History_ConfirmText: "Skjemaet erstattes med versjonen som ble lagret {date} ({count} spørsmål). Du kan angre rett etterpå."
  };
});
