define([], function () {
  return {
    Designer_Color_Blue: "Blauw",
    Designer_Color_Teal: "Blauwgroen",
    Designer_Color_Green: "Groen",
    Designer_Color_Purple: "Paars",
    Designer_Color_Magenta: "Magenta",
    Designer_Color_Red: "Rood",
    Designer_Color_Orange: "Oranje",
    Designer_Color_Gray: "Grijs",
    Designer_Settings_LayoutSinglePage: "Alle vragen op één pagina",
    Designer_Settings_LayoutWizard: "Eén sectie per stap (wizard)",
    Designer_Settings_Title: "Formulierinstellingen",
    Designer_Common_Apply: "Toepassen",
    Designer_Common_Cancel: "Annuleren",
    Designer_Settings_TabBasics: "Algemeen",
    Designer_Settings_FormTitle: "Titel van het formulier",
    Designer_Settings_Description: "Beschrijving",
    Designer_Settings_Layout: "Indeling",
    Designer_Settings_NumberQuestions: "Vragen nummeren",
    Designer_Settings_ShuffleQuestions: "Volgorde van vragen voor elke respondent willekeurig maken",
    Designer_Settings_ShowProgressBar: "Een voortgangsbalk weergeven",
    Designer_Settings_TabAppearance: "Weergave",
    Designer_Settings_AccentColor: "Accentkleur",
    Designer_Settings_CustomColorTitle: "Aangepaste kleur",
    Designer_Settings_CustomColorAria: "Aangepaste accentkleur",
    Designer_Settings_AccentHint: "Accentkleuren worden automatisch aangepast voor contrast op donkere sites, zodat het formulier leesbaar blijft, welk thema de pagina ook gebruikt.",
    Designer_Settings_ShowHeader: "De kop van het formulier weergeven",
    Designer_Settings_HeaderIcon: "Kopafbeelding",
    Designer_Settings_TabAfterSubmit: "Na verzenden",
    Designer_Settings_SubmitButtonText: "Tekst van de verzendknop",
    Designer_Settings_SubmitPlaceholder: "Verzenden",
    Designer_Settings_ThankYouTitle: "Titel van de bedankpagina",
    Designer_Settings_ThankYouPlaceholder: "Bedankt!",
    Designer_Settings_ThankYouMessage: "Bedankbericht",
    Designer_Settings_ShowSubmitAnother: "Een knop 'Nog een antwoord verzenden' weergeven",
    Designer_Settings_TabNotifications: "Meldingen",
    Designer_Settings_EmailEachResponseTo: "Elk antwoord per e-mail verzenden naar",
    Designer_Settings_EmailPlaceholder: "naam@bedrijf.nl; team@bedrijf.nl",
    Designer_Settings_EmailDescription: "Personen in uw organisatie ontvangen elk antwoord per e-mail, met een koppeling naar het lijstitem",
    Designer_Settings_RespondentReceipt: "Respondenten een kopie van hun antwoorden per e-mail sturen",
    Designer_Settings_NotificationsInfo: "Meldingen gebruiken de eigen e-mailservice van SharePoint, dus ontvangers moeten gebruikers in uw organisatie zijn. Externe adressen worden zonder melding genegeerd.",
    Designer_Settings_TabAccess: "Toegang",
    Designer_Settings_OpenFrom: "Openen vanaf",
    Designer_Settings_OpenImmediately: "Direct openen",
    Designer_Settings_CloseAfter: "Sluiten na",
    Designer_Settings_NeverClose: "Nooit sluiten",
    Designer_Settings_ClearDates: "Datums wissen",
    Designer_Settings_DatesInverted: "De sluitingsdatum is gelijk aan of eerder dan de openingsdatum, waardoor het formulier nooit antwoorden zou accepteren.",
    Designer_Settings_MaxResponses: "Stoppen na dit aantal antwoorden",
    Designer_Settings_NoLimit: "Geen limiet",
    Designer_Settings_OneResponsePerPerson: "Slechts één antwoord per persoon toestaan",
    Designer_Settings_AllowSaveDraft: "Respondenten toestaan een concept op te slaan en later af te ronden",
    Designer_Settings_ClosedMessage: "Bericht dat wordt weergegeven wanneer het formulier is gesloten",
    Designer_Settings_ClosedMessagePlaceholder: "Dit formulier accepteert geen antwoorden meer.",
    Designer_Settings_AccessInfo: "Deze limieten worden afgedwongen door het formulier, niet door SharePoint. Iedereen met toestemming om items toe te voegen aan de antwoordlijst kan nog steeds rechtstreeks via de lijst een item toevoegen.",
    Designer_Field_StyleInfo: "Info (accent)",
    Designer_Field_StyleSuccess: "Geslaagd (groen)",
    Designer_Field_StyleWarning: "Waarschuwing (oranje)",
    Designer_Field_StylePlain: "Platte tekst",
    Designer_Field_StyleDivider: "Scheidingslijn",
    Designer_Field_IconStars: "Sterren",
    Designer_Field_IconHearts: "Hartjes",
    Designer_Field_IconThumbs: "Duim omhoog",
    Designer_Field_FormatPlain: "Gewoon getal",
    Designer_Field_FormatCurrency: "Valuta",
    Designer_Field_FormatPercent: "Percentage",
    Designer_Field_UntitledQuestion: "Vraag zonder titel",
    Designer_Field_DeletedQuestion: "een verwijderde vraag",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} en {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "OF",
    Designer_Rule_JoinAll: "EN",
    Designer_Rule_Preview: "Wordt weergegeven wanneer {conditions}.",
    Designer_Field_Yes: "Ja",
    Designer_Field_No: "Nee",
    Designer_Field_When: "Wanneer",
    Designer_Field_SelectValue: "Selecteer een waarde",
    Designer_Field_DateValuePlaceholder: "JJJJ-MM-DD of \"today\"",
    Designer_Field_ValuePlaceholder: "Waarde",
    Designer_Field_UpperBound: "Bovengrens",
    Designer_Field_RemoveCondition: "Deze voorwaarde verwijderen",
    Designer_Field_FormulaInvalid: "Deze formule kan niet worden berekend. Controleer de haakjes en operatoren.",
    Designer_Field_FormulaMissing: "Deze vragen bestaan niet: {names}.",
    Designer_Field_FormulaPreview: "Als elke invoer 10 is, wordt {value} weergegeven.",
    Designer_Field_HintYesNo: "Gebruik \"yes\" of \"no\"",
    Designer_Field_HintMultiDefault: "Scheid meerdere standaardwaarden met ;",
    Designer_Field_HintSingleDefault: "Moet overeenkomen met een van de opties",
    Designer_Field_HintDate: "Gebruik \"today\" of een datum zoals 2026-03-01",
    Designer_Field_HintTime: "Gebruik \"now\" of een tijd zoals 09:30",
    Designer_Field_QuestionSettings: "Vraaginstellingen",
    Designer_Field_Appearance: "Weergave",
    Designer_Field_Style: "Stijl",
    Designer_Field_ImageUrl: "Afbeeldings-URL (optioneel)",
    Designer_Field_Content: "Inhoud",
    Designer_Field_BasicFormatting: "Basisopmaak is toegestaan: vet, cursief, lijsten en koppelingen.",
    Designer_Field_TabOptions: "Opties",
    Designer_Field_TabBranching: "Vertakking",
    Designer_Field_BranchingNeedsQuestion: "Voeg eerst een andere vraag toe. Voor vertakking is iets nodig waarvan de vraag kan afhangen.",
    Designer_Field_BranchingToggle: "Deze vraag alleen weergeven wanneer andere antwoorden overeenkomen",
    Designer_Field_Match: "Overeenkomst",
    Designer_Field_MatchAll: "al deze",
    Designer_Field_MatchAny: "een van deze",
    Designer_Field_AddCondition: "Voorwaarde toevoegen",
    Designer_Field_TabValidation: "Validatie",
    Designer_Field_HelpText: "Helptekst",
    Designer_Field_HelpTextPlaceholder: "Wordt weergegeven onder het vraaglabel",
    Designer_Field_CheckboxLabel: "Label van selectievakje",
    Designer_Field_Placeholder: "Tijdelijke aanduiding",
    Designer_Field_DefaultAnswer: "Standaardantwoord",
    Designer_Field_RequiredMessage: "Aangepast bericht voor verplichte vraag",
    Designer_Field_RequiredMessagePlaceholder: "{title} is verplicht",
    Designer_Field_ThisQuestion: "Deze vraag",
    Designer_Field_RequiredMessageDescription: "Wordt weergegeven in plaats van het standaardbericht wanneer deze vraag leeg blijft",
    Designer_Field_ReadOnly: "Alleen-lezen (antwoord kan alleen afkomstig zijn van een vooraf ingevulde koppeling)",
    Designer_Field_ValidationRules: "Validatieregels",
    Designer_Field_MaxLength: "Maximale lengte",
    Designer_Field_Pattern: "Moet overeenkomen met dit patroon",
    Designer_Field_PatternDescription: "Een reguliere expressie. Laat leeg voor geen patroontest.",
    Designer_Field_PatternMessage: "Bericht wanneer het patroon niet overeenkomt",
    Designer_Field_PatternMessagePlaceholder: "Dit antwoord heeft niet de verwachte indeling",
    Designer_Field_Format: "Notatie",
    Designer_Field_UnitSuffix: "Eenheid die achter de waarde wordt weergegeven",
    Designer_Field_UnitSuffixPlaceholder: "kg, uur, stuks…",
    Designer_Field_Minimum: "Minimum",
    Designer_Field_Maximum: "Maximum",
    Designer_Field_Decimals: "Decimalen",
    Designer_Field_Formula: "Formule",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Verwijs naar andere vragen met hun tekst tussen accolades. Ondersteunt + - * / ( ) en round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Beschikbare vragen: {questions}",
    Designer_Field_NoneYet: "nog geen",
    Designer_Field_Step: "Stap",
    Designer_Field_From: "Van",
    Designer_Field_To: "Tot",
    Designer_Field_LowLabel: "Label aan de lage kant",
    Designer_Field_LowLabelPlaceholder: "Helemaal niet waarschijnlijk",
    Designer_Field_HighLabel: "Label aan de hoge kant",
    Designer_Field_HighLabelPlaceholder: "Zeer waarschijnlijk",
    Designer_Field_SummarizeAs: "Samenvatten als",
    Designer_Field_SummarizeAverage: "Gemiddelde en verdeling",
    Designer_Field_SummarizeNps: "Net Promoter Score (vereist een schaal van 0–10)",
    Designer_Field_NpsWarning: "Net Promoter Score is alleen zinvol op een schaal van 0–10. Stel Van in op 0 en Tot op 10.",
    Designer_Field_NumberOfIcons: "Aantal pictogrammen",
    Designer_Field_Icon: "Pictogram",
    Designer_Field_AllowHalf: "Halve waarden toestaan",
    Designer_Field_ShowOptionsAs: "Opties weergeven als",
    Designer_Field_DisplayButtons: "Inlineknoppen",
    Designer_Field_DisplayDropdown: "Vervolgkeuzelijst",
    Designer_Field_DisplayAutomatic: "Automatisch (inline tot 6 opties)",
    Designer_Field_AllowOther: "Een optie 'Anders' met vrije invoer toevoegen",
    Designer_Field_OtherLabel: "Label voor de optie 'Anders'",
    Designer_Field_OtherPlaceholder: "Anders",
    Designer_Field_ShuffleOptions: "Volgorde van opties voor elke respondent willekeurig maken",
    Designer_Field_MinSelections: "Minimum aantal selecties",
    Designer_Field_MaxSelections: "Maximum aantal selecties",
    Designer_Field_SourceList: "Bronlijst",
    Designer_Field_ChooseList: "Kies een lijst",
    Designer_Field_LookupColumn: "Kolom waaruit opties worden gelezen",
    Designer_Field_ChooseColumn: "Kies een kolom",
    Designer_Field_ChooseListFirst: "Kies eerst een lijst",
    Designer_Field_LookupFilter: "Filter (optioneel)",
    Designer_Field_LookupFilterDescription: "Een OData-filter dat bepaalt welke bronitems opties worden",
    Designer_Field_LookupInfo: "Antwoorden slaan de optietekst op, niet een koppeling naar het bronitem, zodat antwoorden leesbaar blijven, ook als de bronlijst later wijzigt.",
    Designer_Field_ConsentText: "Voorwaarden die boven het selectievakje worden weergegeven",
    Designer_Field_AllowMultiplePeople: "Meerdere personen toestaan",
    Designer_Field_AllowGroups: "Ook groepen toestaan",
    Designer_Field_IncludeTime: "Een tijdstip opnemen",
    Designer_Field_TimeStep: "Tijdstap (minuten)",
    Designer_Field_MaxFiles: "Maximum aantal bestanden",
    Designer_Field_MaxFileSize: "Max. grootte per bestand (MB)",
    Designer_Field_AcceptedTypes: "Toegestane bestandstypen",
    Designer_Field_AcceptedTypesDescription: "Door komma's gescheiden extensies. Laat leeg om alles te accepteren wat SharePoint toestaat.",
    Designer_Field_FilesInfo: "Bestanden worden opgeslagen als bijlagen bij het antwoorditem. SharePoint blokkeert sommige extensies (zoals .exe), ongeacht wat u hier toestaat.",
    Designer_Field_Rows: "Rijen",
    Designer_Field_ProvisionedNote: "Deze vraag heeft al een lijstkolom ({name}). Instellingen die het type van de kolom wijzigen, zijn vergrendeld. Dupliceer de vraag als u een ander type nodig hebt.",
    Designer_Category_Text: "Tekst",
    Designer_Category_Choice: "Keuze",
    Designer_Category_Scales: "Schalen",
    Designer_Category_Date: "Datum",
    Designer_Category_People: "Personen",
    Designer_Category_Advanced: "Geavanceerd",
    Designer_Category_Layout: "Indeling",
    Designer_Menu_CommonPresets: "Veelgebruikte voorinstellingen",
    Designer_Menu_AllTypes: "Alle vraagtypen",
    Designer_Menu_ChangeType: "Type wijzigen",
    Designer_Menu_TypeLockedTitle: "De lijstkolom bestaat al, dus het type is vergrendeld. Dupliceer de vraag om het te wijzigen.",
    Designer_Menu_MoreSettings: "Vertakking, validatie en meer",
    Designer_Menu_InsertBelow: "Vraag eronder invoegen",
    Designer_Card_Duplicate: "Dupliceren",
    Designer_Card_DeleteQuestion: "Vraag verwijderen",
    Designer_Outline_Aria: "Vraagoverzicht",
    Designer_Outline_QuestionCountOne: "{count} vraag",
    Designer_Outline_QuestionCountOther: "{count} vragen",
    Designer_Outline_IssuesTitle: "{count} probleem/problemen om te controleren",
    Designer_Outline_Find: "Een vraag zoeken",
    Designer_Outline_Empty: "Nog geen vragen.",
    Designer_Section_DefaultTitle: "Sectie {number}",
    Designer_Card_Question: "Vraag",
    Designer_Card_BranchingTitle: "Deze vraag wordt alleen weergegeven wanneer een vertakkingsregel overeenkomt",
    Designer_Card_BranchingChip: "Vertakking",
    Designer_Card_LiveTitle: "De lijstkolom bestaat, dus het type is vergrendeld",
    Designer_Card_LiveChip: "Live",
    Designer_Card_CheckChip: "Controleren",
    Designer_Option_Placeholder: "Optie {number}",
    Designer_Option_LabelAria: "Label van optie {number}",
    Designer_Option_ImageUrl: "Afbeeldings-URL",
    Designer_Option_ImageUrlAria: "Afbeeldings-URL van optie {number}",
    Designer_Option_Remove: "Optie verwijderen",
    Designer_Option_RemoveAria: "Optie {number} verwijderen",
    Designer_Option_Add: "Optie toevoegen",
    Designer_Option_OtherHint: "Respondenten kunnen ook een antwoord invullen met het label “{label}”.",
    Designer_Option_OtherFallback: "Anders",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Verwijderen",
    Designer_Grid_RemoveAria: "{label} {number} verwijderen",
    Designer_Grid_Statements: "Stellingen",
    Designer_Grid_Scale: "Schaal",
    Designer_Grid_AddStatement: "Stelling toevoegen",
    Designer_Grid_AddScale: "Schaal toevoegen",
    Designer_Width_Full: "Volledige breedte",
    Designer_Width_Half: "Halve breedte",
    Designer_Width_Third: "Een derde van de breedte",
    Designer_Width_Aria: "Breedte van vraag",
    Designer_Card_BlockLabelPlaceholder: "Bloklabel (niet zichtbaar voor respondenten)",
    Designer_Card_QuestionText: "Vraagtekst",
    Designer_Card_MoveUp: "Omhoog",
    Designer_Card_MoveQuestionUp: "Vraag omhoog verplaatsen",
    Designer_Card_MoveDown: "Omlaag",
    Designer_Card_MoveQuestionDown: "Vraag omlaag verplaatsen",
    Designer_Card_DuplicateQuestion: "Vraag dupliceren",
    Designer_Card_MultipleAnswers: "Meerdere antwoorden",
    Designer_Card_Required: "Verplicht",
    Designer_Card_MoreOptions: "Meer opties",
    Designer_Card_MoreOptionsAria: "Meer opties voor deze vraag",
    Designer_Canvas_FormTitle: "Titel van het formulier",
    Designer_Canvas_DescriptionPlaceholder: "Een beschrijving toevoegen (optioneel)",
    Designer_Canvas_DescriptionAria: "Beschrijving van het formulier",
    Designer_Canvas_EmptyTitle: "Voeg uw eerste vraag toe",
    Designer_Canvas_EmptyBody: "Kies een vraagtype om aan de slag te gaan. U kunt de volgorde van vragen wijzigen door ze te slepen en vertakking toevoegen zodat mensen alleen zien wat voor hen van toepassing is.",
    Designer_Section_Chip: "Sectie {number} van {total}",
    Designer_Section_TitlePlaceholder: "Sectietitel",
    Designer_Section_TitleAria: "Titel van sectie {number}",
    Designer_Section_DescriptionPlaceholder: "Beschrijving (optioneel)",
    Designer_Section_DescriptionAria: "Beschrijving van sectie {number}",
    Designer_Section_MoveUp: "Sectie omhoog verplaatsen",
    Designer_Section_MoveDown: "Sectie omlaag verplaatsen",
    Designer_Section_Delete: "Sectie verwijderen",
    Designer_Card_DragToReorder: "Slepen om de volgorde te wijzigen",
    Designer_Card_ReorderAria: "{title} opnieuw ordenen",
    Designer_Card_ReorderFallback: "vraag",
    Designer_Canvas_AddNew: "Nieuw toevoegen",
    Designer_Canvas_AddSection: "Sectie toevoegen",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Straat en huisnummer",
    Form_Address_Street2Placeholder: "Appartement, suite, enz. (optioneel)",
    Form_Address_CityPlaceholder: "Plaats",
    Form_Address_StatePlaceholder: "Provincie",
    Form_Address_PostalCodePlaceholder: "Postcode",
    Form_Address_CountryPlaceholder: "Land",
    Form_Address_StreetAria: "straat en huisnummer",
    Form_Address_Street2Aria: "adresregel 2",
    Form_Address_CityAria: "plaats",
    Form_Address_StateAria: "provincie",
    Form_Address_PostalCodeAria: "postcode",
    Form_Address_CountryAria: "land",
    Form_Consent_DefaultLabel: "Ik ga akkoord",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered} van {total} rijen beantwoord",
    Form_Lookup_LoadError: "De opties voor deze vraag konden niet worden geladen.",
    Form_Lookup_Loading: "Opties laden…",
    Form_Lookup_SelectOptionsPlaceholder: "Selecteer opties",
    Form_Lookup_SelectOptionPlaceholder: "Selecteer een optie",
    Form_Person_Placeholder: "Begin met het typen van een naam…",
    Form_Person_SuggestedPeopleAndGroups: "Voorgestelde personen en groepen",
    Form_Person_SuggestedPeople: "Voorgestelde personen",
    Form_Person_NoPeopleOrGroups: "Geen personen of groepen gevonden",
    Form_Person_NoPeople: "Geen personen gevonden",
    Form_Person_Searching: "Zoeken…",
    Form_Ranking_Moved: "{item} verplaatst naar positie {position} van {total}",
    Form_Ranking_MoveUp: "Omhoog",
    Form_Ranking_MoveDown: "Omlaag",
    Form_Ranking_MoveItemUpAria: "{item} omhoog verplaatsen",
    Form_Ranking_MoveItemDownAria: "{item} omlaag verplaatsen",
    Form_Rating_ValueText: "{value} van {max}",
    Form_Rating_NotRated: "Niet beoordeeld",
    Form_Rating_Clear: "Beoordeling wissen",
    Form_RichText_Bold: "Vet",
    Form_RichText_Italic: "Cursief",
    Form_RichText_Underline: "Onderstrepen",
    Form_RichText_BulletedList: "Lijst met opsommingstekens",
    Form_RichText_NumberedList: "Genummerde lijst",
    Form_RichText_ClearFormatting: "Opmaak wissen",
    Form_RichText_ToolbarAria: "Tekstopmaak",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\" is overgeslagen. De limiet is {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" is geen toegestaan type.",
    Form_File_TooLarge: "\"{name}\" is groter dan {size} MB.",
    Form_File_AlreadyAttached: "\"{name}\" is al bijgevoegd.",
    Form_File_ReadError: "Een van de bestanden kon niet worden gelezen. Probeer het opnieuw bij te voegen.",
    Form_File_HintMaxSize: "maximaal {size} MB per bestand",
    Form_File_HintOneFile: "1 bestand",
    Form_File_HintMaxFiles: "max. {count} bestanden",
    Form_File_Reading: "Bestanden lezen…",
    Form_File_DropPrompt: "Zet bestanden hier neer of klik om te bladeren",
    Form_File_Remove: "{name} verwijderen",
    Form_Signature_Alt: "Handtekening",
    Form_Signature_AriaSigned: "{label} — ondertekend",
    Form_Signature_AriaEmpty: "{label} — leeg",
    Form_Signature_Clear: "Wissen",
    Form_Signature_Signed: "Ondertekend",
    Form_Signature_Prompt: "Zet hierboven uw handtekening met een muis, pen of vinger",
    Form_Time_Placeholder: "Selecteer een tijd",
    Form_Field_DatePlaceholder: "Selecteer een datum",
    Form_Field_TimeAriaWithLabel: "{label} — tijd",
    Form_Field_TimeAria: "Tijd",
    Form_Field_OtherDefault: "Anders",
    Form_Field_SelectOptionsPlaceholder: "Selecteer opties",
    Form_Field_PleaseSpecify: "Geef een toelichting",
    Form_Field_OtherSpecifyAria: "{label} — geef een toelichting",
    Form_Field_SelectOptionPlaceholder: "Selecteer een optie",
    Form_Field_Yes: "Ja",
    Form_Field_No: "Nee",
    Form_Field_SliderHint: "Sleep de schuifregelaar om te antwoorden",
    Form_Field_WebAddressAriaWithLabel: "{label} — webadres",
    Form_Field_WebAddressAria: "Webadres",
    Form_Field_DisplayTextPlaceholder: "Weergavetekst (optioneel)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — weergavetekst",
    Form_Field_DisplayTextAria: "Weergavetekst",
    Form_Field_ChooseBetween: "Kies tussen {min} en {max}",
    Form_Field_ChooseAtLeast: "Kies minimaal {min}",
    Form_Field_ChooseUpTo: "Kies maximaal {max}",
    Form_Field_SelectedCount: "{count} geselecteerd",
    Form_Field_RequiredAria: "(verplicht)",
    Form_Submit_SaveError: "Uw antwoord kon niet worden opgeslagen. Controleer of het formulier is gepubliceerd vanuit de ontwerper en of u toestemming hebt om items toe te voegen aan de antwoordlijst.",
    Form_Empty_Message: "Dit formulier bevat nog geen vragen. De eigenaar van het formulier kan ze toevoegen op het tabblad Vragen.",
    Form_Checking: "Het formulier controleren…",
    Form_Closed_NotYetOpen: "Nog niet geopend",
    Form_Closed_AlreadyAnswered: "Al beantwoord",
    Form_Closed_Title: "Formulier gesloten",
    Form_Confirmation_PreviewNotice: "Dit was een voorbeeld. Er is niets opgeslagen in de antwoordlijst.",
    Form_Confirmation_PreviewAgain: "Opnieuw een voorbeeld bekijken",
    Form_Confirmation_SubmitAnother: "Nog een antwoord verzenden",
    Form_Wizard_StepFallback: "Stap {step}",
    Form_Wizard_StepsAria: "Formulierstappen",
    Form_Wizard_StepOf: "Stap {step} van {total}",
    Form_ErrorSummary_Title: "Controleer {count} antwoorden:",
    Form_ErrorSummary_UntitledQuestion: "Vraag zonder titel",
    Form_ErrorSummary_Question: "Vraag",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Vorige",
    Form_Nav_Next: "Volgende",
    Form_Draft_Saving: "Opslaan…",
    Form_Draft_Saved: "Concept opgeslagen",
    Form_Draft_SaveAndFinishLater: "Opslaan en later afronden",
    Form_Draft_NotSaved: "Concept niet opgeslagen",
    Form_Submit_Preview: "Verzenden (voorbeeld)",
    Form_Submit_Button: "Verzenden",
    Form_Response_NoAnswer: "Geen antwoord",
    Form_Signature_TypeLabel: "Typ je volledige naam",
    Form_Signature_TypeInstead: "Typ in plaats daarvan je naam",
    Form_Signature_DrawInstead: "In plaats daarvan tekenen",
    Form_Edit_Button: "Je vorige antwoord bewerken",
    Form_Edit_Available: "Je hebt al een antwoord ingediend. Je kunt dit bewerken in plaats van een nieuw antwoord in te dienen.",
    Form_Edit_Banner: "Je bewerkt je vorige antwoord.",
    Form_Edit_Save: "Antwoord bijwerken",
    Form_Edit_UpdatedTitle: "Antwoord bijgewerkt",
    Form_Edit_UpdatedMessage: "Je wijzigingen zijn opgeslagen.",
    Form_Edit_LoadError: "Je vorige antwoord kan niet worden geladen. Probeer het opnieuw.",
    Form_Draft_MissingFiles: "Voeg opnieuw toe: {names}. Deze bestanden konden niet worden hersteld.",
    Form_Attachments_Failed: "Je antwoorden zijn opgeslagen, maar deze bijlagen konden niet worden geüpload: {names}. Probeer het opnieuw of neem contact op met de formuliereigenaar.",
    Logic_ThisQuestion: "Deze vraag",
    Logic_Required: "{label} is verplicht",
    Logic_RequiredConsent: "Schakel het selectievakje in om door te gaan",
    Logic_RequiredFile: "Voeg ten minste één bestand toe",
    Logic_RequiredSignature: "Voeg je handtekening toe",
    Logic_RequiredLikert: "Beantwoord elke rij",
    Logic_InvalidEmail: "Voer een geldig e-mailadres in",
    Logic_InvalidPhone: "Voer een geldig telefoonnummer in",
    Logic_InvalidUrl: "Voer een geldig webadres in dat begint met http:// of https://",
    Logic_MinValue: "De waarde moet ten minste {value} zijn",
    Logic_MaxValue: "De waarde mag maximaal {value} zijn",
    Logic_MaxLength: "De maximale lengte is {max} tekens",
    Logic_ChooseAtLeastOne: "Kies ten minste {count} optie",
    Logic_ChooseAtLeastMany: "Kies ten minste {count} opties",
    Logic_ChooseAtMostOne: "Kies maximaal {count} optie",
    Logic_ChooseAtMostMany: "Kies maximaal {count} opties",
    Logic_LikertRemaining: "Beantwoord elke rij (nog {count})",
    Logic_MaxFilesOne: "Voeg maximaal {count} bestand toe",
    Logic_MaxFilesMany: "Voeg maximaal {count} bestanden toe",
    Logic_FileTooLarge: "\"{name}\" is groter dan {size} MB",
    Logic_FileTypeNotAccepted: "\"{name}\" is geen geaccepteerd bestandstype ({types})",
    Logic_AddressRequired: "Voer ten minste een straat en een plaats in",
    Logic_PatternDefault: "Dit antwoord heeft niet de verwachte notatie",
    Logic_Yes: "Ja",
    Logic_No: "Nee",
    Logic_Agreed: "Akkoord",
    Logic_NotAgreed: "Niet akkoord",
    Logic_Signed: "Ondertekend",
    Logic_NoAnswer: "(geen antwoord)",
    Logic_Unknown: "(onbekend)",
    Logic_OtherSlice: "Overig ({count})",
    Logic_CsvResponseId: "Antwoord-ID",
    Logic_CsvSubmitted: "Ingediend",
    Logic_CsvSubmittedBy: "Ingediend door",
    Logic_EmailQuestion: "Vraag",
    Logic_EmailViewItem: "Weergeven in Microsoft Lists",
    Logic_EmailFooter: "Automatisch verzonden door Smart Forms.",
    Logic_ClosedDefault: "Dit formulier accepteert geen antwoorden meer.",
    Logic_NotYetOpen: "Dit formulier wordt geopend op {date}.",
    Logic_AlreadyResponded: "Je hebt dit formulier al beantwoord. Bedankt!",
    Logic_UntitledQuestion: "Een vraag zonder titel",
    Logic_Issue_NoQuestions: "Voeg ten minste één vraag toe voordat je antwoorden verzamelt.",
    Logic_Issue_NoTitle: "Een vraag heeft geen tekst – deze krijgt automatisch een naam wanneer je publiceert.",
    Logic_Issue_DuplicateTitle: "{label} heeft dezelfde tekst als een andere vraag, waardoor de resultaten moeilijker te lezen zijn.",
    Logic_Issue_NeedTwoOptions: "{label} heeft ten minste twee opties nodig.",
    Logic_Issue_ImageNoImage: "{label} heeft opties zonder afbeelding – deze worden als teksttegels weergegeven.",
    Logic_Issue_LikertNeedRow: "{label} heeft ten minste één rij nodig.",
    Logic_Issue_LikertNeedColumns: "{label} heeft ten minste twee schaalkolommen nodig.",
    Logic_Issue_NoLookupList: "Voor {label} is geen bronlijst geselecteerd.",
    Logic_Issue_NoFormula: "{label} heeft geen formule.",
    Logic_Issue_BadFormula: "{label} heeft een formule die niet kan worden berekend. Controleer de haakjes en operatoren.",
    Logic_Issue_MissingRefs: "{label} verwijst naar vragen die niet bestaan: {names}.",
    Logic_Issue_BadPattern: "{label} heeft een ongeldig validatiepatroon.",
    Logic_Issue_BrokenRule: "{label} heeft een vertakkingsregel die naar een verwijderde vraag verwijst.",
    Logic_Issue_SelfRule: "{label} heeft een vertakkingsregel die naar zichzelf verwijst.",
    Logic_Issue_RuleMismatch: "{label} heeft een vertakkingsregel die niet meer past bij de vraag waarvan deze afhankelijk is.",
    Logic_Issue_RequiredReadOnly: "{label} is zowel verplicht als alleen-lezen en kan dus alleen worden beantwoord via een vooraf ingevulde koppeling.",
    Logic_Issue_EmptySection: "Een sectie bevat geen vragen en wordt overgeslagen.",
    Logic_Issue_CloseBeforeOpen: "De einddatum valt op of vóór de begindatum, dus het formulier accepteert nooit antwoorden.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "E-mails voor goedkeuring zijn ingeschakeld, maar de goedkeuringsstap is uitgeschakeld.",
    Logic_Op_equals: "is",
    Logic_Op_notEquals: "is niet",
    Logic_Op_contains: "bevat",
    Logic_Op_notContains: "bevat niet",
    Logic_Op_notEmpty: "is beantwoord",
    Logic_Op_empty: "is niet beantwoord",
    Logic_Op_greaterThan: "is groter dan",
    Logic_Op_greaterOrEqual: "is minimaal",
    Logic_Op_lessThan: "is kleiner dan",
    Logic_Op_lessOrEqual: "is maximaal",
    Logic_Op_between: "ligt tussen",
    Logic_Op_before: "is vóór",
    Logic_Op_after: "is na",
    Logic_Type_Text: "Kort antwoord",
    Logic_TypeDesc_Text: "Eén regel tekst",
    Logic_Category_Text: "Tekst",
    Logic_Type_MultilineText: "Lang antwoord",
    Logic_TypeDesc_MultilineText: "Meerdere regels platte tekst",
    Logic_Type_RichText: "Opgemaakte tekst",
    Logic_TypeDesc_RichText: "Vet, lijsten en koppelingen",
    Logic_Type_Choice: "Keuze",
    Logic_TypeDesc_Choice: "Kies uit een lijst met opties",
    Logic_Category_Choice: "Keuze",
    Logic_Type_ImageChoice: "Afbeeldingskeuze",
    Logic_TypeDesc_ImageChoice: "Kies uit afbeeldingstegels",
    Logic_Type_Lookup: "Opzoeken uit een lijst",
    Logic_TypeDesc_Lookup: "Opties worden live gelezen uit een andere SharePoint-lijst",
    Logic_Type_YesNo: "Ja / Nee",
    Logic_TypeDesc_YesNo: "Een eenvoudige aan/uit-schakelaar",
    Logic_Type_Consent: "Toestemming",
    Logic_TypeDesc_Consent: "Een selectievakje dat de respondent moet inschakelen om door te gaan",
    Logic_Type_Ranking: "Rangschikking",
    Logic_TypeDesc_Ranking: "Sleep opties in volgorde van voorkeur",
    Logic_Type_Rating: "Beoordeling",
    Logic_TypeDesc_Rating: "Sterren, hartjes of duimen",
    Logic_Category_Scales: "Schalen",
    Logic_Type_Scale: "Opinieschaal",
    Logic_TypeDesc_Scale: "Een genummerde schaal met gelabelde uiteinden",
    Logic_Type_Slider: "Schuifregelaar",
    Logic_TypeDesc_Slider: "Een waarde op een glijdende schaal",
    Logic_Type_Likert: "Likertraster",
    Logic_TypeDesc_Likert: "Beoordeel meerdere stellingen op één gedeelde schaal",
    Logic_Type_Number: "Getal",
    Logic_TypeDesc_Number: "Standaard, valuta of percentage",
    Logic_Category_Advanced: "Geavanceerd",
    Logic_Type_Calculated: "Berekend",
    Logic_TypeDesc_Calculated: "Een alleen-lezen totaal berekend op basis van andere antwoorden",
    Logic_Type_Date: "Datum",
    Logic_TypeDesc_Date: "Een kalenderdatum, optioneel met een tijd",
    Logic_Category_Date: "Datum",
    Logic_Type_Time: "Tijd",
    Logic_TypeDesc_Time: "Alleen een tijdstip",
    Logic_Type_Person: "Persoon",
    Logic_TypeDesc_Person: "Kies iemand uit de organisatie",
    Logic_Category_People: "Personen",
    Logic_Type_Email: "E-mail",
    Logic_TypeDesc_Email: "Een e-mailadres, gevalideerd",
    Logic_Type_Phone: "Telefoon",
    Logic_TypeDesc_Phone: "Een telefoonnummer, gevalideerd",
    Logic_Type_Address: "Adres",
    Logic_TypeDesc_Address: "Straat, plaats, postcode en land",
    Logic_Type_Hyperlink: "Koppeling",
    Logic_TypeDesc_Hyperlink: "Een webadres",
    Logic_Type_FileUpload: "Bestand uploaden",
    Logic_TypeDesc_FileUpload: "Voeg een of meer bestanden toe aan het antwoord",
    Logic_Type_Signature: "Handtekening",
    Logic_TypeDesc_Signature: "Onderteken met een muis, pen of vinger",
    Logic_Type_Content: "Tekstblok",
    Logic_TypeDesc_Content: "Instructies of een afbeelding – verzamelt geen antwoord",
    Logic_Category_Layout: "Indeling",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Hoe waarschijnlijk is het dat je … aanbeveelt",
    Logic_Preset_satisfaction: "Tevredenheid (1–5)",
    Logic_PresetDesc_satisfaction: "Zeer ontevreden tot zeer tevreden",
    Logic_Preset_currency: "Valuta",
    Logic_PresetDesc_currency: "Een geldbedrag",
    Logic_Preset_percent: "Percentage",
    Logic_PresetDesc_percent: "Een percentagewaarde",
    Logic_Template_blank_Name: "Leeg formulier",
    Logic_Template_blank_Description: "Begin helemaal opnieuw",
    Logic_Template_feedback_Name: "Klantfeedback",
    Logic_Template_feedback_Description: "NPS, beoordelingen en open opmerkingen",
    Logic_Template_event_Name: "Evenementregistratie",
    Logic_Template_event_Description: "Gegevens van deelnemers, sessies en dieetwensen",
    Logic_Template_itrequest_Name: "IT-serviceaanvraag",
    Logic_Template_itrequest_Description: "Gecategoriseerde aanvragen met prioriteit en bijlagen",
    Logic_Template_expense_Name: "Onkostendeclaratie",
    Logic_Template_expense_Description: "Regelitems, bonnetjes en een berekend totaal",
    Logic_Template_pulse_Name: "Pulsonderzoek onder medewerkers",
    Logic_Template_pulse_Description: "Likertraster, betrokkenheidsschaal en opmerking over anonimiteit",
    Logic_Template_safety_Name: "Veiligheidsinspectie",
    Logic_Template_safety_Description: "Checklist, foto's en een handtekening",
    Logic_Template_booking_Name: "Ruimte of resource reserveren",
    Logic_Template_booking_Description: "Op opzoeken gebaseerde resourcekiezer met een tijdslot",
    Charts_ColumnChartAria: "Kolomdiagram met {count} categorieën",
    Charts_DonutChartAria: "Ringdiagram van {count} categorieën",
    Charts_NoAnswers: "Nog geen antwoorden.",
    Charts_NoResponses: "Nog geen antwoorden.",
    Charts_Responses: "Antwoorden",
    Charts_ResponsesOverTime: "Antwoorden in de tijd",
    Responses_Chart_Answer: "Antwoord",
    Responses_Chart_Average: "Gemiddelde",
    Responses_Chart_AverageOf: "Gemiddelde van {count}",
    Responses_Chart_AveragePosition: "Gemiddelde positie",
    Responses_Chart_AverageRange: "Gemiddelde (1–{max})",
    Responses_Chart_AvgValue: "gem. {value}",
    Responses_Chart_Detractors: "Critici (0–6)",
    Responses_Chart_Max: "Max.",
    Responses_Chart_Maximum: "Maximum",
    Responses_Chart_Median: "Mediaan",
    Responses_Chart_MentionOne: "{count} vermelding",
    Responses_Chart_MentionOther: "{count} vermeldingen",
    Responses_Chart_Min: "Min.",
    Responses_Chart_Minimum: "Minimum",
    Responses_Chart_NoAnswers: "Nog geen antwoorden.",
    Responses_Chart_NoNumeric: "Nog geen numerieke antwoorden.",
    Responses_Chart_NoRankings: "Nog geen rangschikkingen.",
    Responses_Chart_NoScores: "Nog geen scores.",
    Responses_Chart_NotEnoughText: "Nog niet genoeg tekst om samen te vatten.",
    Responses_Chart_NpsScore: "NPS-score",
    Responses_Chart_Option: "Optie",
    Responses_Chart_Passives: "Passief (7–8)",
    Responses_Chart_Promoters: "Promoters (9–10)",
    Responses_Chart_ResponseOne: "antwoord",
    Responses_Chart_ResponseOther: "antwoorden",
    Responses_Chart_Responses: "Antwoorden",
    Responses_Chart_ShowingAnswers: "{shown} van {total} antwoorden weergegeven.",
    Responses_Chart_Statement: "Stelling",
    Responses_Chart_Statistic: "Statistiek",
    Responses_Chart_StdDev: "Std.afw.",
    Responses_Chart_StdDeviation: "Standaarddeviatie",
    Responses_Chart_Total: "Totaal",
    Responses_Chart_Value: "Waarde",
    Responses_Dashboard_AllHidden: "Alle vragen zijn verborgen in het dashboard. Gebruik 'Verborgen vragen weergeven' om ze terug te halen.",
    Responses_Dashboard_AnsweredOf: "{answered} van {total} beantwoord",
    Responses_Dashboard_AnsweredOfPinned: "{answered} van {total} beantwoord · vastgemaakt",
    Responses_Dashboard_AveragedAcrossResponses: "Gemiddeld over alle antwoorden",
    Responses_Dashboard_ByDay: "Per dag",
    Responses_Dashboard_ByMonth: "Per maand",
    Responses_Dashboard_ByWeek: "Per week",
    Responses_Dashboard_ChartAuto: "Automatisch",
    Responses_Dashboard_ChartBars: "Balken",
    Responses_Dashboard_ChartColumns: "Kolommen",
    Responses_Dashboard_ChartDonut: "Ring",
    Responses_Dashboard_ChartGauge: "Meter",
    Responses_Dashboard_ChartHistogram: "Histogram",
    Responses_Dashboard_ChartOptions: "Grafiekopties",
    Responses_Dashboard_ChartOptionsFor: "Grafiekopties voor {title}",
    Responses_Dashboard_ChartStatistics: "Statistieken",
    Responses_Dashboard_ChartTable: "Tabel",
    Responses_Dashboard_ChartWordFrequency: "Woordfrequentie",
    Responses_Dashboard_EmptyBody: "Zodra mensen antwoorden geven, wordt dit dashboard automatisch gevuld met kerncijfers, een tijdlijn van antwoorden en een grafiek voor de vragen die het volgen waard zijn.",
    Responses_Dashboard_EmptyTitle: "Nog geen antwoorden",
    Responses_Dashboard_Hide: "Verbergen in dashboard",
    Responses_Dashboard_Highlights: "Hoogtepunten",
    Responses_Dashboard_Last7Days: "Laatste 7 dagen",
    Responses_Dashboard_LatestDate: "Laatste {date}",
    Responses_Dashboard_MedianTimeToComplete: "Mediane tijd tot voltooiing",
    Responses_Dashboard_NoPriorWeek: "Geen vorige week om mee te vergelijken",
    Responses_Dashboard_OneEach: "Elk één",
    Responses_Dashboard_Pin: "Vastmaken aan dashboard",
    Responses_Dashboard_QuestionFallback: "vraag",
    Responses_Dashboard_QuestionsAnswered: "Beantwoorde vragen",
    Responses_Dashboard_RecordedOnSubmit: "Vastgelegd bij verzenden",
    Responses_Dashboard_RepeatResponses: "{count} herhaalde antwoorden",
    Responses_Dashboard_ResponsesOverTime: "Antwoorden in de tijd",
    Responses_Dashboard_ShowHidden: "Verborgen vragen weergeven",
    Responses_Dashboard_SinceMidnight: "Sinds middernacht",
    Responses_Dashboard_Today: "Vandaag",
    Responses_Dashboard_TotalResponses: "Totaal aantal antwoorden",
    Responses_Dashboard_UniqueRespondents: "Unieke respondenten",
    Responses_Dashboard_Unpin: "Losmaken van dashboard",
    Responses_Dashboard_UntitledQuestion: "Vraag zonder titel",
    Responses_Dashboard_VsPrevious7Days: "t.o.v. vorige 7 dagen",
    Responses_Detail_Answers: "Antwoorden",
    Responses_Detail_AsTheForm: "Zoals in het formulier",
    Responses_Detail_Cancel: "Annuleren",
    Responses_Detail_Delete: "Verwijderen",
    Responses_Detail_DeleteBody: "Het lijstitem wordt verplaatst naar de prullenbak van de site, zodat het daar kan worden hersteld.",
    Responses_Detail_DeleteTitle: "Dit antwoord verwijderen?",
    Responses_Detail_Deleting: "Verwijderen…",
    Responses_Detail_Draft: "Concept",
    Responses_Detail_Header: "Antwoord {index} van {total}",
    Responses_Detail_LoadingAttachments: "Bijlagen laden…",
    Responses_Detail_Next: "Volgend antwoord",
    Responses_Detail_NoAnswer: "Geen antwoord",
    Responses_Detail_Previous: "Vorig antwoord",
    Responses_Detail_Print: "Afdrukken",
    Responses_Detail_Signature: "Handtekening",
    Responses_Detail_Signed: "Ondertekend",
    Responses_Detail_Took: "duurde {duration}",
    Responses_Summary_AnsweredOfType: "{answered} van {total} beantwoord · {type}",
    Responses_Summary_ByField: "Op {title}",
    Responses_Summary_CompareBy: "Vergelijken op…",
    Responses_Summary_EmptyBody: "Elke vraag krijgt hier een eigen samenvatting.",
    Responses_Summary_NoComparison: "Geen vergelijking",
    Responses_Summary_NothingToCompare: "Niemand heeft “{title}” beantwoord, dus er valt niets te vergelijken.",
    Responses_Summary_OtherNote: "Grafieken met meer dan {max} categorieën voegen de kleinste samen onder 'Anders'. Schakel een kaart over naar Tabel om alle waarden te zien.",
    Responses_Summary_ResponseCountOne: "{count} antwoord",
    Responses_Summary_ResponseCountOther: "{count} antwoorden",
    Responses_Summary_SeeAllAnswers: "Alle antwoorden in de tabel bekijken",
    Responses_Summary_SegmentNote: "De {groups} grootste groepen worden weergegeven. Een antwoord waarin meerdere antwoorden zijn geselecteerd, verschijnt in elke bijbehorende groep, dus groepstotalen kunnen hoger uitkomen dan {total}.",
    Responses_Summary_SplitBy: "Splitsen op {title}",
    Responses_Summary_Untitled: "zonder titel",
    Responses_Table_Apply: "Toepassen",
    Responses_Table_Cancel: "Annuleren",
    Responses_Table_ClearSelection: "Selectie wissen",
    Responses_Table_ColumnOrder: "Kolomvolgorde",
    Responses_Table_ColumnsCount: "Kolommen ({shown}/{total})",
    Responses_Table_Delete: "Verwijderen",
    Responses_Table_DeleteBody: "De lijstitems worden verplaatst naar de prullenbak van de site, zodat ze daar kunnen worden hersteld.",
    Responses_Table_DeleteSelected: "Geselecteerde verwijderen",
    Responses_Table_DeleteTitleOne: "{count} antwoord verwijderen?",
    Responses_Table_DeleteTitleOther: "{count} antwoorden verwijderen?",
    Responses_Table_Deleting: "Verwijderen…",
    Responses_Table_MoveDown: "Omlaag",
    Responses_Table_MoveDownFor: "{title} omlaag verplaatsen",
    Responses_Table_MoveUp: "Omhoog",
    Responses_Table_MoveUpFor: "{title} omhoog verplaatsen",
    Responses_Table_NoColumns: "Er zijn nog geen vraagkolommen zichtbaar.",
    Responses_Table_NoMatch: "Geen antwoorden komen overeen met de huidige filters.",
    Responses_Table_NothingToShow: "Niets om weer te geven",
    Responses_Table_OpenResponse: "Dit antwoord openen",
    Responses_Table_OrderNote: "Verzonden en Verzonden door staan altijd vooraan. De sleepvolgorde geldt voor de vraagkolommen.",
    Responses_Table_Reorder: "Opnieuw ordenen",
    Responses_Table_ResetColumns: "Kolommen opnieuw instellen",
    Responses_Table_SelectResponse: "Dit antwoord selecteren",
    Responses_Table_SelectedOne: "{count} antwoord geselecteerd",
    Responses_Table_SelectedOther: "{count} antwoorden geselecteerd",
    Responses_Table_ShowAll: "Alles weergeven",
    Responses_Table_ShowTheseQuestions: "Deze vragen weergeven",
    Responses_Table_Submitted: "Verzonden",
    Responses_Table_SubmittedBy: "Verzonden door",
    Responses_Table_ToggleSelection: "Selectie in-/uitschakelen",
    Responses_Table_Unknown: "Onbekend",
    Responses_Table_Untitled: "Zonder titel",
    Responses_View_AllTime: "Altijd",
    Responses_View_AnyAnswer: "Elk antwoord",
    Responses_View_Clear: "Wissen",
    Responses_View_CopyShareLink: "Deelkoppeling kopiëren",
    Responses_View_CountFiltered: "{shown} van {total} antwoorden",
    Responses_View_CountOne: "{count} antwoord",
    Responses_View_CountOther: "{count} antwoorden",
    Responses_View_Dashboard: "Dashboard",
    Responses_View_DateRange: "Datumbereik",
    Responses_View_EmptyBody: "Deel het formulier om te beginnen met verzamelen. Antwoorden worden opgeslagen in “{list}” en verschijnen hier direct.",
    Responses_View_EmptyTitle: "Nog geen antwoorden",
    Responses_View_ExportCsv: "CSV exporteren",
    Responses_View_FilterByAnswer: "Filteren op antwoord",
    Responses_View_FilterByQuestion: "Filteren op vraag",
    Responses_View_FilterValue: "Filterwaarde",
    Responses_View_Last30Days: "Laatste 30 dagen",
    Responses_View_Last7Days: "Laatste 7 dagen",
    Responses_View_Last90Days: "Laatste 90 dagen",
    Responses_View_LoadError: "Antwoorden konden niet worden geladen. Publiceer het formulier eenmalig zodat de lijstkolommen bestaan en probeer het daarna opnieuw.",
    Responses_View_Loading: "Antwoorden laden…",
    Responses_View_MoreActions: "Meer acties voor antwoorden",
    Responses_View_PreviewForm: "Voorbeeld van het formulier bekijken",
    Responses_View_Refresh: "Vernieuwen",
    Responses_View_ResponsesTab: "Antwoorden ({count})",
    Responses_View_SearchPlaceholder: "Alle antwoorden doorzoeken",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Selecteer een waarde",
    Responses_View_Summary: "Samenvatting",
    Responses_View_Today: "Vandaag",
    Responses_View_Truncated: "Deze lijst bevat meer antwoorden dan Smart Forms in één keer laadt. De nieuwste {count} worden weergegeven. Open de lijst in Microsoft Lists voor de volledige set.",
    Responses_View_TryAgain: "Opnieuw proberen",
    Responses_View_Untitled: "Zonder titel",
    Responses_Approval_Column: "Goedkeuring",
    Responses_Approval_ReviewerColumn: "Beoordeeld door",
    Responses_Approval_CommentColumn: "Opmerking van beoordelaar",
    Responses_Approval_Pending: "In behandeling",
    Responses_Approval_Approved: "Goedgekeurd",
    Responses_Approval_Rejected: "Afgewezen",
    Responses_Approval_AnyStatus: "Elke goedkeuringsstatus",
    Responses_Approval_FilterLabel: "Filteren op goedkeuringsstatus",
    Responses_Approval_ApproveSelected: "Geselecteerde goedkeuren",
    Responses_Approval_RejectSelected: "Geselecteerde afwijzen",
    Responses_Approval_BulkFailed: "{count} antwoorden konden niet worden bijgewerkt. Probeer het opnieuw.",
    Responses_Approval_Approve: "Goedkeuren",
    Responses_Approval_Reject: "Afwijzen",
    Responses_Approval_Reset: "Terugzetten naar in behandeling",
    Responses_Approval_CommentLabel: "Opmerking (optioneel)",
    Responses_Approval_ReviewedBy: "Beoordeeld door {name}",
    Responses_Approval_Error: "De beslissing kan niet worden opgeslagen. Probeer het opnieuw.",
    Responses_Dashboard_ApprovalStatus: "Wacht op beoordeling",
    Responses_Dashboard_ApprovalBreakdown: "{pending} in behandeling, {approved} goedgekeurd, {rejected} afgewezen",
    Responses_Dashboard_TimelineCoarsened: "Het datumbereik is lang, daarom is de tijdlijn grover gegroepeerd ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Het datumbereik is erg lang, daarom worden alleen de meest recente {count} perioden weergegeven.",
    Service_Item_DefaultTitle: "Antwoord – {date}",
    Service_Email_ApprovalSubject: "Je antwoord is {status} – {title}",
    Service_Email_ApprovalHeading: "Je antwoord is {status}",
    Service_Email_ApprovalIntro: "Een beoordelaar heeft je antwoord op \"{title}\" gemarkeerd als {status}.",
    Service_Email_ApprovalCommentLabel: "Opmerking van beoordelaar",
    Service_Approval_Approved: "goedgekeurd",
    Service_Approval_Rejected: "afgewezen",
    Service_Approval_Pending: "in behandeling",
    Service_Lookup_InvalidFilter: "Het opzoekfilter is niet geldig.",
    Service_Edit_NotAllowed: "Dit formulier staat niet toe dat een ingediend antwoord wordt bewerkt.",
    Service_Edit_NotYours: "Je kunt alleen je eigen antwoord bewerken.",
    Service_Signature_AttachmentLabel: "Handtekening",
    PropertyPane_ListsLoadFailed: "De lijsten op deze site konden niet worden geladen.",
    PropertyPane_EnterListName: "Voer eerst een naam in voor de nieuwe lijst.",
    PropertyPane_CreatingList: "\"{name}\" maken…",
    PropertyPane_ListCreated: "Lijst \"{title}\" is gemaakt en geselecteerd.",
    PropertyPane_ListAlreadyExists: "Er bestaat al een lijst met de naam \"{name}\". Selecteer deze in de vervolgkeuzelijst hierboven.",
    PropertyPane_CreateListFailed: "De lijst kon niet worden gemaakt. Controleer of u toestemming hebt om lijsten te maken op deze site.",
    PropertyPane_Description: "Kies de SharePoint-lijst waarin formulierantwoorden worden opgeslagen, of maak een nieuwe. Al het overige (vragen, weergave, meldingen) wordt rechtstreeks op de pagina bewerkt.",
    PropertyPane_ResponseList_GroupName: "Antwoordlijst",
    PropertyPane_ListDropdown_Label: "Antwoorden opslaan in deze lijst",
    PropertyPane_ResponsesGoTo: "Antwoorden gaan naar \"{name}\".",
    PropertyPane_PickList: "Kies een lijst of maak hieronder een nieuwe.",
    PropertyPane_LoadingLists: "Lijsten laden…",
    PropertyPane_NewListName_Label: "Of maak een nieuwe lijst",
    PropertyPane_NewListName_Placeholder: "Naam van nieuwe lijst",
    PropertyPane_CreateList_Button: "Lijst maken",
    PropertyPane_Tips_GroupName: "Tips",
    PropertyPane_Tip_AutoSave: "Vragen en instellingen worden automatisch opgeslagen terwijl u ze bewerkt. U hoeft de pagina niet op te slaan of te publiceren.",
    PropertyPane_Tip_Permissions: "Respondenten hebben toestemming nodig om items toe te voegen aan de antwoordlijst. Controleer de lijstmachtigingen als iemand een fout meldt bij het verzenden.",
    PropertyPane_Tip_Share: "Gebruik 'Antwoorden verzamelen' op de pagina om de lijstkolommen te maken en een deelbare invullink te krijgen.",
    App_ErrorBoundary_Title: "Smart Forms — weergavefout",
    App_ErrorBoundary_Message: "Bericht:",
    App_ErrorBoundary_Stack: "Stack:",
    App_ErrorBoundary_NoStack: "(geen stack beschikbaar)",
    App_ErrorBoundary_ConsoleNote: "Alle details zijn ook naar de browserconsole geschreven.",
    App_DefaultQuestionTitle: "Vraag {number}",
    App_Error_ListMissing: "De lijst die voor dit formulier is geconfigureerd, bestaat niet meer. Kies een andere lijst in de webpartinstellingen.",
    App_Error_LoadConfig: "Er is iets misgegaan bij het laden van de formulierconfiguratie.",
    App_Error_Unable: "Het formulier kan niet worden geladen.",
    App_Publish_ConflictNotice: "\"{title}\" heeft al een lijstkolom van een ander type ({type}). Geef de vraag een andere naam zodat er een nieuwe kolom kan worden gemaakt, of wijzig het type terug.",
    App_Publish_ConflictUnnamedQuestion: "een vraag",
    App_Publish_ColumnsAddedOne: "{count} kolom is toegevoegd aan \"{list}\".",
    App_Publish_ColumnsAddedOther: "{count} kolommen zijn toegevoegd aan \"{list}\".",
    App_Publish_TheList: "de lijst",
    App_Publish_UpToDate: "De antwoordlijst is al up-to-date.",
    App_Publish_Error: "De lijstkolommen konden niet worden gemaakt. Meestal betekent dit dat u geen machtiging Lijsten beheren hebt voor de antwoordlijst, maar het kan ook gebeuren op sites waar aangepaste scripts zijn uitgeschakeld. Controleer de browserconsole op de onderliggende fout of probeer het opnieuw.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Bouw een verzorgd formulier op basis van een SharePoint-lijst, met {count} vraagtypen, vertakkingslogica, bestandsuploads, deelbare invullinks en een resultatendashboard.",
    App_Placeholder_ChooseList: "Kies of maak een lijst",
    App_Placeholder_Hint: "Bewerk de pagina en configureer deze webpart om aan de slag te gaan.",
    App_Loading: "Formulier laden…",
    App_OpenSettings: "Instellingen openen",
    App_Tab_Questions: "Vragen",
    App_Tab_QuestionsWithCount: "Vragen ({count})",
    App_Tab_Responses: "Antwoorden",
    App_Tab_Responses_Title: "Antwoorden worden opgeslagen in \"{list}\"",
    App_Templates_Start: "Beginnen met een sjabloon",
    App_Settings_Title: "Formulierinstellingen: weergave, meldingen, toegang",
    App_Settings_AriaLabel: "Formulierinstellingen",
    App_Preview: "Voorbeeld",
    App_Preview_Close: "Voorbeeld sluiten",
    App_Preview_Hint: "Voorbeeld: niets wat u hier verzendt, wordt opgeslagen. Validatie en vertakking werken precies zoals ze voor respondenten zullen werken.",
    App_Publish_GettingReady: "Voorbereiden…",
    App_Publish_CollectResponses: "Antwoorden verzamelen",
    App_Publish_Share: "Delen",
    App_Retry: "Opnieuw proberen",
    App_SaveError_Banner: "Uw laatste wijziging kon niet worden opgeslagen. Controleer uw verbinding en probeer het opnieuw.",
    App_Preflight_BlockingTitle: "Los deze problemen op voordat u gaat verzamelen",
    App_Preflight_WarningTitle: "Eerst even controleren",
    App_Preflight_BlockingText: "Deze problemen zouden ervoor zorgen dat het gepubliceerde formulier niet goed werkt.",
    App_Preflight_WarningText: "Er is niets kapot, maar deze punten zijn meestal de moeite waard om te verbeteren voordat u de koppeling deelt.",
    App_Preflight_GoTo: "Ga naar",
    App_Preflight_CollectAnyway: "Toch antwoorden verzamelen",
    App_Preflight_Back: "Terug naar het formulier",
    App_Cancel: "Annuleren",
    App_Done: "Gereed",
    App_Share_Title: "Uw formulier is klaar om te delen",
    App_Share_SubText: "Stuur deze koppeling naar iedereen die het formulier moet invullen.",
    App_Share_LinkAriaLabel: "Deelkoppeling",
    App_Share_Copy: "Kopiëren",
    App_Share_Copied: "Gekopieerd",
    App_Share_AddItemsEmphasis: "items toe te voegen",
    App_Share_PermissionNote: "Respondenten hebben toestemming nodig om {addItems} aan “{title}” en toegang tot deze pagina. Als iemand een fout krijgt bij het verzenden, is dat vrijwel altijd de oorzaak.",
    App_Share_PrefillNote: "U kunt vragen vooraf beantwoorden in de koppeling door de kolomnaam toe te voegen, bijvoorbeeld {example}.",
    App_Templates_ReplaceWarning: "Als u een sjabloon kiest, worden de huidige vragen vervangen.",
    App_Templates_PickStart: "Kies een uitgangspunt. Daarna kunt u alles nog wijzigen.",
    App_Templates_Empty: "Leeg",
    App_Templates_QuestionCount: "{count} vragen",
    App_SaveChip_SavingTitle: "Uw laatste bewerking wordt opgeslagen",
    App_SaveChip_Saving: "Opslaan…",
    App_SaveChip_FailedTitle: "Uw laatste bewerking kon niet worden opgeslagen. Controleer uw verbinding en probeer het opnieuw.",
    App_SaveChip_Failed: "Opslaan mislukt",
    App_SaveChip_SavedTitle: "Alle wijzigingen zijn opgeslagen",
    App_SaveChip_Saved: "Opgeslagen",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Nieuw antwoord — {title}",
    Service_Email_NewResponseHeading: "Nieuw antwoord: {title}",
    Service_Email_NewResponseIntro: "Iemand heeft zojuist een antwoord verzonden — {date}.",
    Service_Email_ReceiptSubject: "Uw antwoord — {title}",
    Service_Email_ReceiptHeading: "Bedankt voor uw antwoord!",
    Service_Email_ReceiptIntro: "Hier is een kopie van wat u hebt verzonden naar \"{title}\".",
    App_History_Title: "Versiegeschiedenis",
    App_History_RestoredNotice: "De versie die is opgeslagen op {date} is hersteld. Controleer deze en gebruik daarna Antwoorden verzamelen om nieuwe vragen te publiceren.",
    App_History_Undo: "Herstel ongedaan maken",
    App_Share_CopyManual: "Je browser heeft het kopiëren geblokkeerd. Selecteer de koppeling hierboven en druk op Ctrl+C (Cmd+C op een Mac) om deze te kopiëren.",
    App_Share_TeamsNote: "Je bent in Microsoft Teams. Deze koppeling opent de SharePoint-pagina rechtstreeks, dus ontvangers hebben toegang tot de site nodig.",
    App_Share_PrefillNotSecure: "Vooraf ingevulde antwoorden zijn alleen een gemak: iedereen met de koppeling kan ze wijzigen, dus beschouw ze nooit als een beveiligingsgrens.",
    Designer_Section_DropHere: "Sleep een vraag hierheen",
    Designer_Section_DropEnd: "Zet hier neer om naar het einde van deze sectie te verplaatsen",
    Designer_Rules_RemovedOne: "1 vertakkingsregel die niet meer paste, is verwijderd.",
    Designer_Rules_RemovedOther: "{count} vertakkingsregels die niet meer pasten, zijn verwijderd.",
    Designer_Settings_AllowEdit: "Respondenten toestaan hun antwoord te bewerken",
    Designer_Settings_AllowEditHint: "Respondenten kunnen hun ingediende antwoord opnieuw openen en bijwerken. Elke persoon kan alleen zijn of haar eigen antwoord bewerken.",
    Designer_Settings_EnableApproval: "Goedkeuringswerkstroom inschakelen",
    Designer_Settings_ApprovalNotify: "Respondent per e-mail op de hoogte stellen van de beslissing",
    Designer_Settings_ApprovalHint: "Voegt goedkeuringskolommen toe aan de antwoordenlijst wanneer je de volgende keer publiceert. Eigenaren keuren antwoorden goed of wijzen ze af op het tabblad Antwoorden.",
    Designer_History_Title: "Versiegeschiedenis",
    Designer_History_Intro: "Eerder opgeslagen versies van de vragen en instellingen van dit formulier. Bij herstellen wordt een versie in de ontwerper geladen; je kunt dit ongedaan maken en nieuwe vragen worden pas gemaakt wanneer je publiceert.",
    Designer_History_Loading: "Versies laden...",
    Designer_History_Empty: "Er zijn geen eerdere versies gevonden. Voor de versiegeschiedenis moet versiebeheer zijn ingeschakeld voor de lijst \"Smart Forms Config\" en moet er ten minste één bewerking zijn opgeslagen.",
    Designer_History_Latest: "Nieuwste",
    Designer_History_LatestTitle: "Dit is de versie die momenteel wordt gebruikt",
    Designer_History_By: "door {name}",
    Designer_History_UnknownAuthor: "Onbekende auteur",
    Designer_History_VersionLabel: "versie {label}",
    Designer_History_Preview: "Voorbeeld",
    Designer_History_Restore: "Herstellen",
    Designer_History_QuestionsOne: "1 vraag",
    Designer_History_QuestionsOther: "{count} vragen",
    Designer_History_LoadFailed: "Deze versie kan niet worden geladen.",
    Designer_History_ConfirmTitle: "Deze versie herstellen?",
    Designer_History_ConfirmText: "Het formulier wordt vervangen door de versie die is opgeslagen op {date} ({count} vragen). Je kunt dit direct daarna ongedaan maken."
  };
});
