define([], function () {
  return {
    Designer_Color_Blue: "Niebieski",
    Designer_Color_Teal: "Morski",
    Designer_Color_Green: "Zielony",
    Designer_Color_Purple: "Fioletowy",
    Designer_Color_Magenta: "Purpurowy",
    Designer_Color_Red: "Czerwony",
    Designer_Color_Orange: "Pomarańczowy",
    Designer_Color_Gray: "Szary",
    Designer_Settings_LayoutSinglePage: "Wszystkie pytania na jednej stronie",
    Designer_Settings_LayoutWizard: "Jedna sekcja na krok (kreator)",
    Designer_Settings_Title: "Ustawienia formularza",
    Designer_Common_Apply: "Zastosuj",
    Designer_Common_Cancel: "Anuluj",
    Designer_Settings_TabBasics: "Podstawowe",
    Designer_Settings_FormTitle: "Tytuł formularza",
    Designer_Settings_Description: "Opis",
    Designer_Settings_Layout: "Układ",
    Designer_Settings_NumberQuestions: "Numeruj pytania",
    Designer_Settings_ShuffleQuestions: "Losuj kolejność pytań dla każdego respondenta",
    Designer_Settings_ShowProgressBar: "Pokaż pasek postępu",
    Designer_Settings_TabAppearance: "Wygląd",
    Designer_Settings_AccentColor: "Kolor akcentu",
    Designer_Settings_CustomColorTitle: "Kolor niestandardowy",
    Designer_Settings_CustomColorAria: "Niestandardowy kolor akcentu",
    Designer_Settings_AccentHint: "Kolory akcentu są automatycznie dostosowywane pod kątem kontrastu w witrynach z ciemnym motywem, dzięki czemu formularz pozostaje czytelny niezależnie od motywu strony.",
    Designer_Settings_ShowHeader: "Pokaż nagłówek formularza",
    Designer_Settings_HeaderIcon: "Ikona nagłówka",
    Designer_Settings_TabAfterSubmit: "Po przesłaniu",
    Designer_Settings_SubmitButtonText: "Tekst przycisku przesyłania",
    Designer_Settings_SubmitPlaceholder: "Prześlij",
    Designer_Settings_ThankYouTitle: "Tytuł podziękowania",
    Designer_Settings_ThankYouPlaceholder: "Dziękujemy!",
    Designer_Settings_ThankYouMessage: "Komunikat z podziękowaniem",
    Designer_Settings_ShowSubmitAnother: "Pokaż przycisk „Prześlij kolejną odpowiedź”",
    Designer_Settings_TabNotifications: "Powiadomienia",
    Designer_Settings_EmailEachResponseTo: "Wysyłaj każdą odpowiedź e-mailem do",
    Designer_Settings_EmailPlaceholder: "imie@firma.pl; zespol@firma.pl",
    Designer_Settings_EmailDescription: "Osoby w Twojej organizacji otrzymują każdą odpowiedź e-mailem wraz z łączem do elementu listy",
    Designer_Settings_RespondentReceipt: "Wyślij respondentom e-mailem kopię ich odpowiedzi",
    Designer_Settings_NotificationsInfo: "Powiadomienia korzystają z własnej usługi poczty SharePoint, więc odbiorcy muszą być użytkownikami w Twojej organizacji. Adresy zewnętrzne są po cichu pomijane.",
    Designer_Settings_TabAccess: "Dostęp",
    Designer_Settings_OpenFrom: "Otwórz od",
    Designer_Settings_OpenImmediately: "Otwórz natychmiast",
    Designer_Settings_CloseAfter: "Zamknij po",
    Designer_Settings_NeverClose: "Nigdy nie zamykaj",
    Designer_Settings_ClearDates: "Wyczyść daty",
    Designer_Settings_DatesInverted: "Data zamknięcia jest taka sama jak data otwarcia lub wcześniejsza, więc formularz nigdy nie przyjmowałby odpowiedzi.",
    Designer_Settings_MaxResponses: "Zatrzymaj po tej liczbie odpowiedzi",
    Designer_Settings_NoLimit: "Bez limitu",
    Designer_Settings_OneResponsePerPerson: "Zezwalaj tylko na jedną odpowiedź na osobę",
    Designer_Settings_AllowSaveDraft: "Zezwalaj respondentom na zapisanie wersji roboczej i dokończenie później",
    Designer_Settings_ClosedMessage: "Komunikat wyświetlany po zamknięciu formularza",
    Designer_Settings_ClosedMessagePlaceholder: "Ten formularz nie przyjmuje już odpowiedzi.",
    Designer_Settings_AccessInfo: "Te limity są egzekwowane przez formularz, a nie przez SharePoint. Każdy, kto ma uprawnienia do dodawania elementów do listy odpowiedzi, nadal może dodać element bezpośrednio przez listę.",
    Designer_Field_StyleInfo: "Informacja (akcent)",
    Designer_Field_StyleSuccess: "Sukces (zielony)",
    Designer_Field_StyleWarning: "Ostrzeżenie (bursztynowy)",
    Designer_Field_StylePlain: "Zwykły tekst",
    Designer_Field_StyleDivider: "Linia podziału",
    Designer_Field_IconStars: "Gwiazdki",
    Designer_Field_IconHearts: "Serca",
    Designer_Field_IconThumbs: "Kciuk w górę",
    Designer_Field_FormatPlain: "Zwykła liczba",
    Designer_Field_FormatCurrency: "Waluta",
    Designer_Field_FormatPercent: "Procent",
    Designer_Field_UntitledQuestion: "Pytanie bez tytułu",
    Designer_Field_DeletedQuestion: "usunięte pytanie",
    Designer_Rule_Unary: "„{name}” {operator}",
    Designer_Rule_Between: "„{name}” {operator} {value} i {value2}",
    Designer_Rule_Binary: "„{name}” {operator} „{value}”",
    Designer_Rule_JoinAny: "LUB",
    Designer_Rule_JoinAll: "ORAZ",
    Designer_Rule_Preview: "Wyświetlane, gdy {conditions}.",
    Designer_Field_Yes: "Tak",
    Designer_Field_No: "Nie",
    Designer_Field_When: "Gdy",
    Designer_Field_SelectValue: "Wybierz wartość",
    Designer_Field_DateValuePlaceholder: "RRRR-MM-DD lub „today”",
    Designer_Field_ValuePlaceholder: "Wartość",
    Designer_Field_UpperBound: "Górna granica",
    Designer_Field_RemoveCondition: "Usuń ten warunek",
    Designer_Field_FormulaInvalid: "Nie można obliczyć tej formuły. Sprawdź nawiasy i operatory.",
    Designer_Field_FormulaMissing: "Te pytania nie istnieją: {names}.",
    Designer_Field_FormulaPreview: "Gdy każda wartość wejściowa wynosi 10, wyświetlana jest wartość {value}.",
    Designer_Field_HintYesNo: "Użyj „yes” lub „no”",
    Designer_Field_HintMultiDefault: "Oddziel wiele wartości domyślnych średnikiem ;",
    Designer_Field_HintSingleDefault: "Musi pasować do jednej z opcji",
    Designer_Field_HintDate: "Użyj „today” lub daty, np. 2026-03-01",
    Designer_Field_HintTime: "Użyj „now” lub godziny, np. 09:30",
    Designer_Field_QuestionSettings: "Ustawienia pytania",
    Designer_Field_Appearance: "Wygląd",
    Designer_Field_Style: "Styl",
    Designer_Field_ImageUrl: "Adres URL obrazu (opcjonalnie)",
    Designer_Field_Content: "Zawartość",
    Designer_Field_BasicFormatting: "Dozwolone jest podstawowe formatowanie: pogrubienie, kursywa, listy i łącza.",
    Designer_Field_TabOptions: "Opcje",
    Designer_Field_TabBranching: "Rozgałęzienia",
    Designer_Field_BranchingNeedsQuestion: "Najpierw dodaj inne pytanie — rozgałęzienie wymaga pytania, od którego może zależeć.",
    Designer_Field_BranchingToggle: "Pokaż to pytanie tylko wtedy, gdy inne odpowiedzi pasują",
    Designer_Field_Match: "Dopasuj",
    Designer_Field_MatchAll: "wszystkie z nich",
    Designer_Field_MatchAny: "dowolne z nich",
    Designer_Field_AddCondition: "Dodaj warunek",
    Designer_Field_TabValidation: "Walidacja",
    Designer_Field_HelpText: "Tekst pomocy",
    Designer_Field_HelpTextPlaceholder: "Wyświetlany pod etykietą pytania",
    Designer_Field_CheckboxLabel: "Etykieta pola wyboru",
    Designer_Field_Placeholder: "Tekst zastępczy",
    Designer_Field_DefaultAnswer: "Odpowiedź domyślna",
    Designer_Field_RequiredMessage: "Niestandardowy komunikat o wymaganej odpowiedzi",
    Designer_Field_RequiredMessagePlaceholder: "Pole „{title}” jest wymagane",
    Designer_Field_ThisQuestion: "To pytanie",
    Designer_Field_RequiredMessageDescription: "Wyświetlany zamiast komunikatu standardowego, gdy pytanie pozostanie bez odpowiedzi",
    Designer_Field_ReadOnly: "Tylko do odczytu (odpowiedź może pochodzić wyłącznie z wstępnie wypełnionego łącza)",
    Designer_Field_ValidationRules: "Reguły walidacji",
    Designer_Field_MaxLength: "Maksymalna długość",
    Designer_Field_Pattern: "Musi pasować do tego wzorca",
    Designer_Field_PatternDescription: "Wyrażenie regularne. Pozostaw puste, aby nie sprawdzać wzorca.",
    Designer_Field_PatternMessage: "Komunikat, gdy wzorzec nie pasuje",
    Designer_Field_PatternMessagePlaceholder: "Ta odpowiedź nie ma oczekiwanego formatu",
    Designer_Field_Format: "Format",
    Designer_Field_UnitSuffix: "Jednostka wyświetlana po wartości",
    Designer_Field_UnitSuffixPlaceholder: "kg, godz., szt.…",
    Designer_Field_Minimum: "Minimum",
    Designer_Field_Maximum: "Maksimum",
    Designer_Field_Decimals: "Miejsca dziesiętne",
    Designer_Field_Formula: "Formuła",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Odwołuj się do innych pytań, wpisując ich tekst w nawiasach klamrowych. Obsługiwane: + - * / ( ) oraz round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Dostępne pytania: {questions}",
    Designer_Field_NoneYet: "brak",
    Designer_Field_Step: "Krok",
    Designer_Field_From: "Od",
    Designer_Field_To: "Do",
    Designer_Field_LowLabel: "Etykieta na dolnym końcu",
    Designer_Field_LowLabelPlaceholder: "Zdecydowanie nie",
    Designer_Field_HighLabel: "Etykieta na górnym końcu",
    Designer_Field_HighLabelPlaceholder: "Zdecydowanie tak",
    Designer_Field_SummarizeAs: "Podsumuj jako",
    Designer_Field_SummarizeAverage: "Średnia i rozkład",
    Designer_Field_SummarizeNps: "Net Promoter Score (wymaga skali 0–10)",
    Designer_Field_NpsWarning: "Net Promoter Score ma sens tylko na skali 0–10. Ustaw pole Od na 0, a Do na 10.",
    Designer_Field_NumberOfIcons: "Liczba ikon",
    Designer_Field_Icon: "Ikona",
    Designer_Field_AllowHalf: "Zezwalaj na połowy wartości",
    Designer_Field_ShowOptionsAs: "Pokaż opcje jako",
    Designer_Field_DisplayButtons: "Przyciski w wierszu",
    Designer_Field_DisplayDropdown: "Lista rozwijana",
    Designer_Field_DisplayAutomatic: "Automatycznie (w wierszu do 6 opcji)",
    Designer_Field_AllowOther: "Dodaj opcję „Inne” z własną odpowiedzią",
    Designer_Field_OtherLabel: "Etykieta opcji „Inne”",
    Designer_Field_OtherPlaceholder: "Inne",
    Designer_Field_ShuffleOptions: "Losuj kolejność opcji dla każdego respondenta",
    Designer_Field_MinSelections: "Minimalna liczba wyborów",
    Designer_Field_MaxSelections: "Maksymalna liczba wyborów",
    Designer_Field_SourceList: "Lista źródłowa",
    Designer_Field_ChooseList: "Wybierz listę",
    Designer_Field_LookupColumn: "Kolumna, z której mają być odczytywane opcje",
    Designer_Field_ChooseColumn: "Wybierz kolumnę",
    Designer_Field_ChooseListFirst: "Najpierw wybierz listę",
    Designer_Field_LookupFilter: "Filtr (opcjonalnie)",
    Designer_Field_LookupFilterDescription: "Filtr OData ograniczający, które elementy źródłowe staną się opcjami",
    Designer_Field_LookupInfo: "Odpowiedzi zapisują tekst opcji, a nie łącze do elementu źródłowego, dzięki czemu pozostają czytelne, nawet jeśli lista źródłowa zmieni się później.",
    Designer_Field_ConsentText: "Warunki wyświetlane nad polem wyboru",
    Designer_Field_AllowMultiplePeople: "Zezwalaj na wiele osób",
    Designer_Field_AllowGroups: "Zezwalaj także na grupy",
    Designer_Field_IncludeTime: "Uwzględnij porę dnia",
    Designer_Field_TimeStep: "Krok czasu (minuty)",
    Designer_Field_MaxFiles: "Maksymalna liczba plików",
    Designer_Field_MaxFileSize: "Maks. rozmiar każdego (MB)",
    Designer_Field_AcceptedTypes: "Akceptowane typy plików",
    Designer_Field_AcceptedTypesDescription: "Rozszerzenia oddzielone przecinkami. Pozostaw puste, aby akceptować wszystko, na co zezwala SharePoint.",
    Designer_Field_FilesInfo: "Pliki są zapisywane jako załączniki elementu odpowiedzi. SharePoint blokuje niektóre rozszerzenia (np. .exe) niezależnie od tego, na co zezwolisz tutaj.",
    Designer_Field_Rows: "Wiersze",
    Designer_Field_ProvisionedNote: "To pytanie ma już kolumnę listy ({name}). Ustawienia zmieniające typ kolumny są zablokowane — jeśli potrzebujesz innego typu, zduplikuj pytanie.",
    Designer_Category_Text: "Tekst",
    Designer_Category_Choice: "Wybór",
    Designer_Category_Scales: "Skale",
    Designer_Category_Date: "Data",
    Designer_Category_People: "Osoby",
    Designer_Category_Advanced: "Zaawansowane",
    Designer_Category_Layout: "Układ",
    Designer_Menu_CommonPresets: "Typowe ustawienia wstępne",
    Designer_Menu_AllTypes: "Wszystkie typy pytań",
    Designer_Menu_ChangeType: "Zmień typ",
    Designer_Menu_TypeLockedTitle: "Kolumna listy już istnieje, więc typ jest zablokowany. Zduplikuj pytanie, aby go zmienić.",
    Designer_Menu_MoreSettings: "Rozgałęzienia, walidacja i więcej",
    Designer_Menu_InsertBelow: "Wstaw pytanie poniżej",
    Designer_Card_Duplicate: "Duplikuj",
    Designer_Card_DeleteQuestion: "Usuń pytanie",
    Designer_Outline_Aria: "Konspekt pytań",
    Designer_Outline_QuestionCountOne: "{count} pytanie",
    Designer_Outline_QuestionCountOther: "{count} pytań",
    Designer_Outline_IssuesTitle: "Liczba problemów do przejrzenia: {count}",
    Designer_Outline_Find: "Znajdź pytanie",
    Designer_Outline_Empty: "Brak pytań.",
    Designer_Section_DefaultTitle: "Sekcja {number}",
    Designer_Card_Question: "Pytanie",
    Designer_Card_BranchingTitle: "To pytanie jest wyświetlane tylko wtedy, gdy pasuje reguła rozgałęzienia",
    Designer_Card_BranchingChip: "Rozgałęzienie",
    Designer_Card_LiveTitle: "Kolumna listy istnieje, więc typ jest zablokowany",
    Designer_Card_LiveChip: "Aktywne",
    Designer_Card_CheckChip: "Sprawdź",
    Designer_Option_Placeholder: "Opcja {number}",
    Designer_Option_LabelAria: "Etykieta opcji {number}",
    Designer_Option_ImageUrl: "Adres URL obrazu",
    Designer_Option_ImageUrlAria: "Adres URL obrazu opcji {number}",
    Designer_Option_Remove: "Usuń opcję",
    Designer_Option_RemoveAria: "Usuń opcję {number}",
    Designer_Option_Add: "Dodaj opcję",
    Designer_Option_OtherHint: "Respondenci mogą też wpisać własną odpowiedź z etykietą „{label}”.",
    Designer_Option_OtherFallback: "Inne",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Usuń",
    Designer_Grid_RemoveAria: "Usuń: {label} {number}",
    Designer_Grid_Statements: "Stwierdzenia",
    Designer_Grid_Scale: "Skala",
    Designer_Grid_AddStatement: "Dodaj stwierdzenie",
    Designer_Grid_AddScale: "Dodaj skalę",
    Designer_Width_Full: "Pełna szerokość",
    Designer_Width_Half: "Połowa szerokości",
    Designer_Width_Third: "Jedna trzecia szerokości",
    Designer_Width_Aria: "Szerokość pytania",
    Designer_Card_BlockLabelPlaceholder: "Etykieta bloku (niewidoczna dla respondentów)",
    Designer_Card_QuestionText: "Tekst pytania",
    Designer_Card_MoveUp: "Przenieś w górę",
    Designer_Card_MoveQuestionUp: "Przenieś pytanie w górę",
    Designer_Card_MoveDown: "Przenieś w dół",
    Designer_Card_MoveQuestionDown: "Przenieś pytanie w dół",
    Designer_Card_DuplicateQuestion: "Duplikuj pytanie",
    Designer_Card_MultipleAnswers: "Wiele odpowiedzi",
    Designer_Card_Required: "Wymagane",
    Designer_Card_MoreOptions: "Więcej opcji",
    Designer_Card_MoreOptionsAria: "Więcej opcji dla tego pytania",
    Designer_Canvas_FormTitle: "Tytuł formularza",
    Designer_Canvas_DescriptionPlaceholder: "Dodaj opis (opcjonalnie)",
    Designer_Canvas_DescriptionAria: "Opis formularza",
    Designer_Canvas_EmptyTitle: "Dodaj pierwsze pytanie",
    Designer_Canvas_EmptyBody: "Wybierz typ pytania, aby rozpocząć. Kolejność pytań można zmieniać, przeciągając je, a dzięki rozgałęzieniom respondenci zobaczą tylko to, co ich dotyczy.",
    Designer_Section_Chip: "Sekcja {number} z {total}",
    Designer_Section_TitlePlaceholder: "Tytuł sekcji",
    Designer_Section_TitleAria: "Tytuł sekcji {number}",
    Designer_Section_DescriptionPlaceholder: "Opis (opcjonalnie)",
    Designer_Section_DescriptionAria: "Opis sekcji {number}",
    Designer_Section_MoveUp: "Przenieś sekcję w górę",
    Designer_Section_MoveDown: "Przenieś sekcję w dół",
    Designer_Section_Delete: "Usuń sekcję",
    Designer_Card_DragToReorder: "Przeciągnij, aby zmienić kolejność",
    Designer_Card_ReorderAria: "Zmień kolejność: {title}",
    Designer_Card_ReorderFallback: "pytanie",
    Designer_Canvas_AddNew: "Dodaj nowe",
    Designer_Canvas_AddSection: "Dodaj sekcję",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Ulica i numer",
    Form_Address_Street2Placeholder: "Mieszkanie, lokal itp. (opcjonalnie)",
    Form_Address_CityPlaceholder: "Miasto",
    Form_Address_StatePlaceholder: "Województwo",
    Form_Address_PostalCodePlaceholder: "Kod pocztowy",
    Form_Address_CountryPlaceholder: "Kraj",
    Form_Address_StreetAria: "ulica i numer",
    Form_Address_Street2Aria: "druga linia adresu",
    Form_Address_CityAria: "miasto",
    Form_Address_StateAria: "województwo",
    Form_Address_PostalCodeAria: "kod pocztowy",
    Form_Address_CountryAria: "kraj",
    Form_Consent_DefaultLabel: "Wyrażam zgodę",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "Odpowiedzi w wierszach: {answered} z {total}",
    Form_Lookup_LoadError: "Nie można załadować opcji dla tego pytania.",
    Form_Lookup_Loading: "Ładowanie opcji…",
    Form_Lookup_SelectOptionsPlaceholder: "Wybierz opcje",
    Form_Lookup_SelectOptionPlaceholder: "Wybierz opcję",
    Form_Person_Placeholder: "Zacznij wpisywać nazwę…",
    Form_Person_SuggestedPeopleAndGroups: "Sugerowane osoby i grupy",
    Form_Person_SuggestedPeople: "Sugerowane osoby",
    Form_Person_NoPeopleOrGroups: "Nie znaleziono osób ani grup",
    Form_Person_NoPeople: "Nie znaleziono osób",
    Form_Person_Searching: "Wyszukiwanie…",
    Form_Ranking_Moved: "Element {item} przeniesiono na pozycję {position} z {total}",
    Form_Ranking_MoveUp: "Przenieś w górę",
    Form_Ranking_MoveDown: "Przenieś w dół",
    Form_Ranking_MoveItemUpAria: "Przenieś element {item} w górę",
    Form_Ranking_MoveItemDownAria: "Przenieś element {item} w dół",
    Form_Rating_ValueText: "{value} z {max}",
    Form_Rating_NotRated: "Bez oceny",
    Form_Rating_Clear: "Wyczyść ocenę",
    Form_RichText_Bold: "Pogrubienie",
    Form_RichText_Italic: "Kursywa",
    Form_RichText_Underline: "Podkreślenie",
    Form_RichText_BulletedList: "Lista punktowana",
    Form_RichText_NumberedList: "Lista numerowana",
    Form_RichText_ClearFormatting: "Wyczyść formatowanie",
    Form_RichText_ToolbarAria: "Formatowanie tekstu",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "Plik „{name}” został pominięty — limit to {limit}.",
    Form_File_TypeNotAccepted: "Plik „{name}” nie jest akceptowanym typem.",
    Form_File_TooLarge: "Plik „{name}” jest większy niż {size} MB.",
    Form_File_AlreadyAttached: "Plik „{name}” jest już załączony.",
    Form_File_ReadError: "Nie można odczytać jednego z plików. Spróbuj załączyć go ponownie.",
    Form_File_HintMaxSize: "do {size} MB każdy",
    Form_File_HintOneFile: "1 plik",
    Form_File_HintMaxFiles: "maks. plików: {count}",
    Form_File_Reading: "Odczytywanie plików…",
    Form_File_DropPrompt: "Upuść pliki tutaj lub kliknij, aby przeglądać",
    Form_File_Remove: "Usuń: {name}",
    Form_Signature_Alt: "Podpis",
    Form_Signature_AriaSigned: "{label} — podpisano",
    Form_Signature_AriaEmpty: "{label} — puste",
    Form_Signature_Clear: "Wyczyść",
    Form_Signature_Signed: "Podpisano",
    Form_Signature_Prompt: "Podpisz powyżej za pomocą myszy, rysika lub palca",
    Form_Time_Placeholder: "Wybierz godzinę",
    Form_Field_DatePlaceholder: "Wybierz datę",
    Form_Field_TimeAriaWithLabel: "{label} — godzina",
    Form_Field_TimeAria: "Godzina",
    Form_Field_OtherDefault: "Inne",
    Form_Field_SelectOptionsPlaceholder: "Wybierz opcje",
    Form_Field_PleaseSpecify: "Podaj jakie",
    Form_Field_OtherSpecifyAria: "{label} — podaj jakie",
    Form_Field_SelectOptionPlaceholder: "Wybierz opcję",
    Form_Field_Yes: "Tak",
    Form_Field_No: "Nie",
    Form_Field_SliderHint: "Przeciągnij suwak, aby odpowiedzieć",
    Form_Field_WebAddressAriaWithLabel: "{label} — adres internetowy",
    Form_Field_WebAddressAria: "Adres internetowy",
    Form_Field_DisplayTextPlaceholder: "Tekst wyświetlany (opcjonalnie)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — tekst wyświetlany",
    Form_Field_DisplayTextAria: "Tekst wyświetlany",
    Form_Field_ChooseBetween: "Wybierz od {min} do {max}",
    Form_Field_ChooseAtLeast: "Wybierz co najmniej {min}",
    Form_Field_ChooseUpTo: "Wybierz maksymalnie {max}",
    Form_Field_SelectedCount: "Wybrano: {count}",
    Form_Field_RequiredAria: "(wymagane)",
    Form_Submit_SaveError: "Nie można zapisać odpowiedzi. Upewnij się, że formularz został opublikowany w projektancie i że masz uprawnienia do dodawania elementów do listy odpowiedzi.",
    Form_Empty_Message: "Ten formularz nie ma jeszcze żadnych pytań. Właściciel formularza może je dodać na karcie Pytania.",
    Form_Checking: "Sprawdzanie formularza…",
    Form_Closed_NotYetOpen: "Jeszcze nie otwarty",
    Form_Closed_AlreadyAnswered: "Już wypełniono",
    Form_Closed_Title: "Formularz zamknięty",
    Form_Confirmation_PreviewNotice: "To był podgląd — nic nie zostało zapisane na liście odpowiedzi.",
    Form_Confirmation_PreviewAgain: "Wyświetl podgląd ponownie",
    Form_Confirmation_SubmitAnother: "Prześlij kolejną odpowiedź",
    Form_Wizard_StepFallback: "Krok {step}",
    Form_Wizard_StepsAria: "Kroki formularza",
    Form_Wizard_StepOf: "Krok {step} z {total}",
    Form_ErrorSummary_Title: "Sprawdź odpowiedzi ({count}):",
    Form_ErrorSummary_UntitledQuestion: "Pytanie bez tytułu",
    Form_ErrorSummary_Question: "Pytanie",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Wstecz",
    Form_Nav_Next: "Dalej",
    Form_Draft_Saving: "Zapisywanie…",
    Form_Draft_Saved: "Wersja robocza zapisana",
    Form_Draft_SaveAndFinishLater: "Zapisz i dokończ później",
    Form_Draft_NotSaved: "Wersja robocza nie została zapisana",
    Form_Submit_Preview: "Prześlij (podgląd)",
    Form_Submit_Button: "Prześlij",
    Form_Response_NoAnswer: "Brak odpowiedzi",
    Form_Signature_TypeLabel: "Wpisz swoje imię i nazwisko",
    Form_Signature_TypeInstead: "Wpisz zamiast tego swoje imię i nazwisko",
    Form_Signature_DrawInstead: "Narysuj zamiast tego",
    Form_Edit_Button: "Edytuj poprzednią odpowiedź",
    Form_Edit_Available: "Odpowiedź została już przesłana. Możesz ją edytować zamiast przesyłać nową.",
    Form_Edit_Banner: "Edytujesz swoją poprzednią odpowiedź.",
    Form_Edit_Save: "Zaktualizuj odpowiedź",
    Form_Edit_UpdatedTitle: "Odpowiedź zaktualizowana",
    Form_Edit_UpdatedMessage: "Zmiany zostały zapisane.",
    Form_Edit_LoadError: "Nie można załadować poprzedniej odpowiedzi. Spróbuj ponownie.",
    Form_Draft_MissingFiles: "Dołącz ponownie: {names}. Nie można było przywrócić tych plików.",
    Form_Attachments_Failed: "Odpowiedzi zostały zapisane, ale nie można było przesłać tych załączników: {names}. Spróbuj ponownie lub skontaktuj się z właścicielem formularza.",
    Logic_ThisQuestion: "To pytanie",
    Logic_Required: "Pole {label} jest wymagane",
    Logic_RequiredConsent: "Zaznacz pole wyboru, aby kontynuować",
    Logic_RequiredFile: "Dołącz co najmniej jeden plik",
    Logic_RequiredSignature: "Dodaj swój podpis",
    Logic_RequiredLikert: "Odpowiedz w każdym wierszu",
    Logic_InvalidEmail: "Wprowadź prawidłowy adres e-mail",
    Logic_InvalidPhone: "Wprowadź prawidłowy numer telefonu",
    Logic_InvalidUrl: "Wprowadź prawidłowy adres internetowy zaczynający się od http:// lub https://",
    Logic_MinValue: "Wartość musi wynosić co najmniej {value}",
    Logic_MaxValue: "Wartość może wynosić co najwyżej {value}",
    Logic_MaxLength: "Maksymalna długość to {max} znaków",
    Logic_ChooseAtLeastOne: "Wybierz co najmniej {count} opcję",
    Logic_ChooseAtLeastMany: "Wybierz co najmniej {count} opcji",
    Logic_ChooseAtMostOne: "Wybierz maksymalnie {count} opcję",
    Logic_ChooseAtMostMany: "Wybierz maksymalnie {count} opcji",
    Logic_LikertRemaining: "Odpowiedz w każdym wierszu (pozostało: {count})",
    Logic_MaxFilesOne: "Dołącz maksymalnie {count} plik",
    Logic_MaxFilesMany: "Dołącz maksymalnie {count} plików",
    Logic_FileTooLarge: "Plik „{name}” jest większy niż {size} MB",
    Logic_FileTypeNotAccepted: "Plik „{name}” ma nieobsługiwany typ ({types})",
    Logic_AddressRequired: "Wprowadź co najmniej ulicę i miasto",
    Logic_PatternDefault: "Ta odpowiedź nie ma oczekiwanego formatu",
    Logic_Yes: "Tak",
    Logic_No: "Nie",
    Logic_Agreed: "Wyrażono zgodę",
    Logic_NotAgreed: "Nie wyrażono zgody",
    Logic_Signed: "Podpisano",
    Logic_NoAnswer: "(brak odpowiedzi)",
    Logic_Unknown: "(nieznane)",
    Logic_OtherSlice: "Inne ({count})",
    Logic_CsvResponseId: "Identyfikator odpowiedzi",
    Logic_CsvSubmitted: "Przesłano",
    Logic_CsvSubmittedBy: "Przesłał(a)",
    Logic_EmailQuestion: "Pytanie",
    Logic_EmailViewItem: "Wyświetl w aplikacji Microsoft Lists",
    Logic_EmailFooter: "Wysłano automatycznie przez Smart Forms.",
    Logic_ClosedDefault: "Ten formularz nie przyjmuje już odpowiedzi.",
    Logic_NotYetOpen: "Ten formularz zostanie otwarty {date}.",
    Logic_AlreadyResponded: "Odpowiedź na ten formularz została już przesłana. Dziękujemy!",
    Logic_UntitledQuestion: "Pytanie bez tytułu",
    Logic_Issue_NoQuestions: "Dodaj co najmniej jedno pytanie przed rozpoczęciem zbierania odpowiedzi.",
    Logic_Issue_NoTitle: "Pytanie nie ma treści – zostanie automatycznie nazwane podczas publikowania.",
    Logic_Issue_DuplicateTitle: "Pytanie {label} ma taką samą treść jak inne pytanie, co utrudnia odczytanie wyników.",
    Logic_Issue_NeedTwoOptions: "Pytanie {label} wymaga co najmniej dwóch opcji.",
    Logic_Issue_ImageNoImage: "Pytanie {label} zawiera opcje bez obrazu – zostaną wyświetlone jako kafelki tekstowe.",
    Logic_Issue_LikertNeedRow: "Pytanie {label} wymaga co najmniej jednego wiersza.",
    Logic_Issue_LikertNeedColumns: "Pytanie {label} wymaga co najmniej dwóch kolumn skali.",
    Logic_Issue_NoLookupList: "Dla pytania {label} nie wybrano listy źródłowej.",
    Logic_Issue_NoFormula: "Pytanie {label} nie ma formuły.",
    Logic_Issue_BadFormula: "Pytanie {label} ma formułę, której nie można obliczyć. Sprawdź nawiasy i operatory.",
    Logic_Issue_MissingRefs: "Pytanie {label} odwołuje się do nieistniejących pytań: {names}.",
    Logic_Issue_BadPattern: "Pytanie {label} ma nieprawidłowy wzorzec walidacji.",
    Logic_Issue_BrokenRule: "Pytanie {label} ma regułę rozgałęzienia wskazującą usunięte pytanie.",
    Logic_Issue_SelfRule: "Pytanie {label} ma regułę rozgałęzienia odwołującą się do samego siebie.",
    Logic_Issue_RuleMismatch: "Pytanie {label} ma regułę rozgałęzienia, która nie pasuje już do pytania, od którego zależy.",
    Logic_Issue_RequiredReadOnly: "Pytanie {label} jest jednocześnie wymagane i tylko do odczytu, więc można na nie odpowiedzieć tylko za pomocą wstępnie wypełnionego linku.",
    Logic_Issue_EmptySection: "Sekcja nie zawiera pytań i zostanie pominięta.",
    Logic_Issue_CloseBeforeOpen: "Data zamknięcia przypada w dniu otwarcia lub przed nim, więc formularz nigdy nie będzie przyjmował odpowiedzi.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Wiadomości e-mail dotyczące zatwierdzania są włączone, ale krok zatwierdzania jest wyłączony.",
    Logic_Op_equals: "jest równe",
    Logic_Op_notEquals: "jest inne niż",
    Logic_Op_contains: "zawiera",
    Logic_Op_notContains: "nie zawiera",
    Logic_Op_notEmpty: "ma odpowiedź",
    Logic_Op_empty: "nie ma odpowiedzi",
    Logic_Op_greaterThan: "jest większe niż",
    Logic_Op_greaterOrEqual: "wynosi co najmniej",
    Logic_Op_lessThan: "jest mniejsze niż",
    Logic_Op_lessOrEqual: "wynosi co najwyżej",
    Logic_Op_between: "mieści się między",
    Logic_Op_before: "jest przed",
    Logic_Op_after: "jest po",
    Logic_Type_Text: "Krótka odpowiedź",
    Logic_TypeDesc_Text: "Pojedynczy wiersz tekstu",
    Logic_Category_Text: "Tekst",
    Logic_Type_MultilineText: "Długa odpowiedź",
    Logic_TypeDesc_MultilineText: "Kilka wierszy zwykłego tekstu",
    Logic_Type_RichText: "Tekst sformatowany",
    Logic_TypeDesc_RichText: "Pogrubienie, listy i linki",
    Logic_Type_Choice: "Wybór",
    Logic_TypeDesc_Choice: "Wybierz z listy opcji",
    Logic_Category_Choice: "Wybór",
    Logic_Type_ImageChoice: "Wybór obrazu",
    Logic_TypeDesc_ImageChoice: "Wybierz z kafelków z obrazami",
    Logic_Type_Lookup: "Wyszukiwanie z listy",
    Logic_TypeDesc_Lookup: "Opcje odczytywane na żywo z innej listy programu SharePoint",
    Logic_Type_YesNo: "Tak / Nie",
    Logic_TypeDesc_YesNo: "Prosty przełącznik włącz/wyłącz",
    Logic_Type_Consent: "Zgoda",
    Logic_TypeDesc_Consent: "Pole wyboru, które respondent musi zaznaczyć, aby kontynuować",
    Logic_Type_Ranking: "Ranking",
    Logic_TypeDesc_Ranking: "Przeciągnij opcje, aby ustawić je w kolejności preferencji",
    Logic_Type_Rating: "Ocena",
    Logic_TypeDesc_Rating: "Gwiazdki, serca lub kciuki",
    Logic_Category_Scales: "Skale",
    Logic_Type_Scale: "Skala opinii",
    Logic_TypeDesc_Scale: "Skala numeryczna z opisanymi końcami",
    Logic_Type_Slider: "Suwak",
    Logic_TypeDesc_Slider: "Wartość na skali przesuwanej",
    Logic_Type_Likert: "Siatka Likerta",
    Logic_TypeDesc_Likert: "Oceń kilka stwierdzeń na jednej wspólnej skali",
    Logic_Type_Number: "Liczba",
    Logic_TypeDesc_Number: "Zwykła liczba, waluta lub wartość procentowa",
    Logic_Category_Advanced: "Zaawansowane",
    Logic_Type_Calculated: "Obliczane",
    Logic_TypeDesc_Calculated: "Suma tylko do odczytu obliczana na podstawie innych odpowiedzi",
    Logic_Type_Date: "Data",
    Logic_TypeDesc_Date: "Data kalendarzowa, opcjonalnie z godziną",
    Logic_Category_Date: "Data",
    Logic_Type_Time: "Godzina",
    Logic_TypeDesc_Time: "Sama godzina",
    Logic_Type_Person: "Osoba",
    Logic_TypeDesc_Person: "Wybierz osobę z organizacji",
    Logic_Category_People: "Osoby",
    Logic_Type_Email: "E-mail",
    Logic_TypeDesc_Email: "Adres e-mail, z walidacją",
    Logic_Type_Phone: "Telefon",
    Logic_TypeDesc_Phone: "Numer telefonu, z walidacją",
    Logic_Type_Address: "Adres",
    Logic_TypeDesc_Address: "Ulica, miasto, kod pocztowy i kraj",
    Logic_Type_Hyperlink: "Link",
    Logic_TypeDesc_Hyperlink: "Adres internetowy",
    Logic_Type_FileUpload: "Przesyłanie plików",
    Logic_TypeDesc_FileUpload: "Dołącz jeden lub więcej plików do odpowiedzi",
    Logic_Type_Signature: "Podpis",
    Logic_TypeDesc_Signature: "Podpisz myszą, piórem lub palcem",
    Logic_Type_Content: "Blok tekstu",
    Logic_TypeDesc_Content: "Instrukcje lub obraz – nie zbiera odpowiedzi",
    Logic_Category_Layout: "Układ",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Jak bardzo prawdopodobne jest, że polecisz…",
    Logic_Preset_satisfaction: "Zadowolenie (1–5)",
    Logic_PresetDesc_satisfaction: "Bardzo niezadowolony do bardzo zadowolony",
    Logic_Preset_currency: "Waluta",
    Logic_PresetDesc_currency: "Kwota pieniężna",
    Logic_Preset_percent: "Wartość procentowa",
    Logic_PresetDesc_percent: "Wartość procentowa",
    Logic_Template_blank_Name: "Pusty formularz",
    Logic_Template_blank_Description: "Zacznij od zera",
    Logic_Template_feedback_Name: "Opinie klientów",
    Logic_Template_feedback_Description: "NPS, oceny i otwarte komentarze",
    Logic_Template_event_Name: "Rejestracja na wydarzenie",
    Logic_Template_event_Description: "Dane uczestnika, sesje i wymagania żywieniowe",
    Logic_Template_itrequest_Name: "Zgłoszenie do działu IT",
    Logic_Template_itrequest_Description: "Skategoryzowane zgłoszenia z priorytetem i załącznikami",
    Logic_Template_expense_Name: "Rozliczenie wydatków",
    Logic_Template_expense_Description: "Pozycje, paragony i obliczana suma",
    Logic_Template_pulse_Name: "Krótka ankieta pracownicza",
    Logic_Template_pulse_Description: "Siatka Likerta, skala zaangażowania i informacja o anonimowości",
    Logic_Template_safety_Name: "Inspekcja bezpieczeństwa",
    Logic_Template_safety_Description: "Lista kontrolna, zdjęcia i podpis",
    Logic_Template_booking_Name: "Rezerwacja sali lub zasobu",
    Logic_Template_booking_Description: "Selektor zasobów oparty na wyszukiwaniu, z przedziałem czasowym",
    Charts_ColumnChartAria: "Wykres kolumnowy z kategoriami: {count}",
    Charts_DonutChartAria: "Wykres pierścieniowy z kategoriami: {count}",
    Charts_NoAnswers: "Brak odpowiedzi.",
    Charts_NoResponses: "Brak odpowiedzi.",
    Charts_Responses: "Odpowiedzi",
    Charts_ResponsesOverTime: "Odpowiedzi w czasie",
    Responses_Chart_Answer: "Odpowiedź",
    Responses_Chart_Average: "Średnia",
    Responses_Chart_AverageOf: "Średnia z {count}",
    Responses_Chart_AveragePosition: "Średnia pozycja",
    Responses_Chart_AverageRange: "Średnia (1–{max})",
    Responses_Chart_AvgValue: "śr. {value}",
    Responses_Chart_Detractors: "Krytycy (0–6)",
    Responses_Chart_Max: "Maks.",
    Responses_Chart_Maximum: "Maksimum",
    Responses_Chart_Median: "Mediana",
    Responses_Chart_MentionOne: "{count} wzmianka",
    Responses_Chart_MentionOther: "Wzmianki: {count}",
    Responses_Chart_Min: "Min.",
    Responses_Chart_Minimum: "Minimum",
    Responses_Chart_NoAnswers: "Brak odpowiedzi.",
    Responses_Chart_NoNumeric: "Brak odpowiedzi liczbowych.",
    Responses_Chart_NoRankings: "Brak rankingów.",
    Responses_Chart_NoScores: "Brak wyników.",
    Responses_Chart_NotEnoughText: "Za mało tekstu, aby go podsumować.",
    Responses_Chart_NpsScore: "Wynik NPS",
    Responses_Chart_Option: "Opcja",
    Responses_Chart_Passives: "Bierni (7–8)",
    Responses_Chart_Promoters: "Promotorzy (9–10)",
    Responses_Chart_ResponseOne: "odpowiedź",
    Responses_Chart_ResponseOther: "odpowiedzi",
    Responses_Chart_Responses: "Odpowiedzi",
    Responses_Chart_ShowingAnswers: "Wyświetlono {shown} z {total} odpowiedzi.",
    Responses_Chart_Statement: "Stwierdzenie",
    Responses_Chart_Statistic: "Statystyka",
    Responses_Chart_StdDev: "Odch. std.",
    Responses_Chart_StdDeviation: "Odchylenie standardowe",
    Responses_Chart_Total: "Razem",
    Responses_Chart_Value: "Wartość",
    Responses_Dashboard_AllHidden: "Wszystkie pytania są ukryte na pulpicie. Użyj opcji „Pokaż ukryte pytania”, aby je przywrócić.",
    Responses_Dashboard_AnsweredOf: "Odpowiedzi: {answered} z {total}",
    Responses_Dashboard_AnsweredOfPinned: "Odpowiedzi: {answered} z {total} · przypięto",
    Responses_Dashboard_AveragedAcrossResponses: "Średnia ze wszystkich odpowiedzi",
    Responses_Dashboard_ByDay: "Według dnia",
    Responses_Dashboard_ByMonth: "Według miesiąca",
    Responses_Dashboard_ByWeek: "Według tygodnia",
    Responses_Dashboard_ChartAuto: "Automatycznie",
    Responses_Dashboard_ChartBars: "Słupkowy",
    Responses_Dashboard_ChartColumns: "Kolumnowy",
    Responses_Dashboard_ChartDonut: "Pierścieniowy",
    Responses_Dashboard_ChartGauge: "Wskaźnik",
    Responses_Dashboard_ChartHistogram: "Histogram",
    Responses_Dashboard_ChartOptions: "Opcje wykresu",
    Responses_Dashboard_ChartOptionsFor: "Opcje wykresu: {title}",
    Responses_Dashboard_ChartStatistics: "Statystyki",
    Responses_Dashboard_ChartTable: "Tabela",
    Responses_Dashboard_ChartWordFrequency: "Częstotliwość słów",
    Responses_Dashboard_EmptyBody: "Gdy ludzie zaczną odpowiadać, ten pulpit wypełni się automatycznie — kluczowymi liczbami, osią czasu odpowiedzi i wykresem dla pytań wartych uwagi.",
    Responses_Dashboard_EmptyTitle: "Brak odpowiedzi",
    Responses_Dashboard_Hide: "Ukryj na pulpicie",
    Responses_Dashboard_Highlights: "Najważniejsze informacje",
    Responses_Dashboard_Last7Days: "Ostatnie 7 dni",
    Responses_Dashboard_LatestDate: "Ostatnia: {date}",
    Responses_Dashboard_MedianTimeToComplete: "Mediana czasu wypełnienia",
    Responses_Dashboard_NoPriorWeek: "Brak poprzedniego tygodnia do porównania",
    Responses_Dashboard_OneEach: "Po jednej",
    Responses_Dashboard_Pin: "Przypnij do pulpitu",
    Responses_Dashboard_QuestionFallback: "pytanie",
    Responses_Dashboard_QuestionsAnswered: "Pytania z odpowiedziami",
    Responses_Dashboard_RecordedOnSubmit: "Rejestrowane przy przesłaniu",
    Responses_Dashboard_RepeatResponses: "Powtórne odpowiedzi: {count}",
    Responses_Dashboard_ResponsesOverTime: "Odpowiedzi w czasie",
    Responses_Dashboard_ShowHidden: "Pokaż ukryte pytania",
    Responses_Dashboard_SinceMidnight: "Od północy",
    Responses_Dashboard_Today: "Dzisiaj",
    Responses_Dashboard_TotalResponses: "Łączna liczba odpowiedzi",
    Responses_Dashboard_UniqueRespondents: "Unikatowi respondenci",
    Responses_Dashboard_Unpin: "Odepnij od pulpitu",
    Responses_Dashboard_UntitledQuestion: "Pytanie bez tytułu",
    Responses_Dashboard_VsPrevious7Days: "w porównaniu z poprzednimi 7 dniami",
    Responses_Detail_Answers: "Odpowiedzi",
    Responses_Detail_AsTheForm: "Jak w formularzu",
    Responses_Detail_Cancel: "Anuluj",
    Responses_Detail_Delete: "Usuń",
    Responses_Detail_DeleteBody: "Element listy zostanie przeniesiony do kosza witryny, skąd można go przywrócić.",
    Responses_Detail_DeleteTitle: "Usunąć tę odpowiedź?",
    Responses_Detail_Deleting: "Usuwanie…",
    Responses_Detail_Draft: "Wersja robocza",
    Responses_Detail_Header: "Odpowiedź {index} z {total}",
    Responses_Detail_LoadingAttachments: "Ładowanie załączników…",
    Responses_Detail_Next: "Następna odpowiedź",
    Responses_Detail_NoAnswer: "Brak odpowiedzi",
    Responses_Detail_Previous: "Poprzednia odpowiedź",
    Responses_Detail_Print: "Drukuj",
    Responses_Detail_Signature: "Podpis",
    Responses_Detail_Signed: "Podpisano",
    Responses_Detail_Took: "czas: {duration}",
    Responses_Summary_AnsweredOfType: "Odpowiedzi: {answered} z {total} · {type}",
    Responses_Summary_ByField: "Według: {title}",
    Responses_Summary_CompareBy: "Porównaj według…",
    Responses_Summary_EmptyBody: "Każde pytanie otrzyma tutaj własne podsumowanie.",
    Responses_Summary_NoComparison: "Brak porównania",
    Responses_Summary_NothingToCompare: "Nikt nie odpowiedział na pytanie „{title}”, więc nie ma czego porównywać.",
    Responses_Summary_OtherNote: "Wykresy z liczbą kategorii większą niż {max} grupują najmniejsze w kategorii „Inne” — przełącz kartę na Tabelę, aby zobaczyć wszystkie wartości.",
    Responses_Summary_ResponseCountOne: "{count} odpowiedź",
    Responses_Summary_ResponseCountOther: "Odpowiedzi: {count}",
    Responses_Summary_SeeAllAnswers: "Zobacz wszystkie odpowiedzi w tabeli",
    Responses_Summary_SegmentNote: "Wyświetlono największe grupy: {groups}. Odpowiedź z wieloma wybranymi opcjami pojawia się w każdej pasującej grupie, więc sumy grup mogą przekraczać {total}.",
    Responses_Summary_SplitBy: "Podziel według: {title}",
    Responses_Summary_Untitled: "bez tytułu",
    Responses_Table_Apply: "Zastosuj",
    Responses_Table_Cancel: "Anuluj",
    Responses_Table_ClearSelection: "Wyczyść zaznaczenie",
    Responses_Table_ColumnOrder: "Kolejność kolumn",
    Responses_Table_ColumnsCount: "Kolumny ({shown}/{total})",
    Responses_Table_Delete: "Usuń",
    Responses_Table_DeleteBody: "Elementy listy zostaną przeniesione do kosza witryny, skąd można je przywrócić.",
    Responses_Table_DeleteSelected: "Usuń zaznaczone",
    Responses_Table_DeleteTitleOne: "Usunąć {count} odpowiedź?",
    Responses_Table_DeleteTitleOther: "Usunąć odpowiedzi ({count})?",
    Responses_Table_Deleting: "Usuwanie…",
    Responses_Table_MoveDown: "Przenieś w dół",
    Responses_Table_MoveDownFor: "Przenieś w dół: {title}",
    Responses_Table_MoveUp: "Przenieś w górę",
    Responses_Table_MoveUpFor: "Przenieś w górę: {title}",
    Responses_Table_NoColumns: "Żadne kolumny pytań nie są jeszcze widoczne.",
    Responses_Table_NoMatch: "Żadne odpowiedzi nie pasują do bieżących filtrów.",
    Responses_Table_NothingToShow: "Brak danych do wyświetlenia",
    Responses_Table_OpenResponse: "Otwórz tę odpowiedź",
    Responses_Table_OrderNote: "Kolumny Przesłano i Przesłał(a) zawsze są na początku. Kolejność przeciągania dotyczy kolumn pytań.",
    Responses_Table_Reorder: "Zmień kolejność",
    Responses_Table_ResetColumns: "Resetuj kolumny",
    Responses_Table_SelectResponse: "Zaznacz tę odpowiedź",
    Responses_Table_SelectedOne: "Zaznaczono {count} odpowiedź",
    Responses_Table_SelectedOther: "Zaznaczono odpowiedzi: {count}",
    Responses_Table_ShowAll: "Pokaż wszystko",
    Responses_Table_ShowTheseQuestions: "Pokaż te pytania",
    Responses_Table_Submitted: "Przesłano",
    Responses_Table_SubmittedBy: "Przesłał(a)",
    Responses_Table_ToggleSelection: "Przełącz zaznaczenie",
    Responses_Table_Unknown: "Nieznany",
    Responses_Table_Untitled: "Bez tytułu",
    Responses_View_AllTime: "Cały czas",
    Responses_View_AnyAnswer: "Dowolna odpowiedź",
    Responses_View_Clear: "Wyczyść",
    Responses_View_CopyShareLink: "Kopiuj łącze udostępniania",
    Responses_View_CountFiltered: "Odpowiedzi: {shown} z {total}",
    Responses_View_CountOne: "{count} odpowiedź",
    Responses_View_CountOther: "Odpowiedzi: {count}",
    Responses_View_Dashboard: "Pulpit",
    Responses_View_DateRange: "Zakres dat",
    Responses_View_EmptyBody: "Udostępnij formularz, aby rozpocząć zbieranie odpowiedzi. Odpowiedzi są zapisywane na liście „{list}” i od razu pojawiają się tutaj.",
    Responses_View_EmptyTitle: "Brak odpowiedzi",
    Responses_View_ExportCsv: "Eksportuj do CSV",
    Responses_View_FilterByAnswer: "Filtruj według odpowiedzi",
    Responses_View_FilterByQuestion: "Filtruj według pytania",
    Responses_View_FilterValue: "Wartość filtru",
    Responses_View_Last30Days: "Ostatnie 30 dni",
    Responses_View_Last7Days: "Ostatnie 7 dni",
    Responses_View_Last90Days: "Ostatnie 90 dni",
    Responses_View_LoadError: "Nie można załadować odpowiedzi. Opublikuj formularz raz, aby kolumny listy zostały utworzone, a następnie spróbuj ponownie.",
    Responses_View_Loading: "Ładowanie odpowiedzi…",
    Responses_View_MoreActions: "Więcej akcji dla odpowiedzi",
    Responses_View_PreviewForm: "Wyświetl podgląd formularza",
    Responses_View_Refresh: "Odśwież",
    Responses_View_ResponsesTab: "Odpowiedzi ({count})",
    Responses_View_SearchPlaceholder: "Przeszukaj wszystkie odpowiedzi",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Wybierz wartość",
    Responses_View_Summary: "Podsumowanie",
    Responses_View_Today: "Dzisiaj",
    Responses_View_Truncated: "Ta lista zawiera więcej odpowiedzi, niż Smart Forms ładuje jednorazowo. Wyświetlono {count} najnowszych — otwórz listę w Microsoft Lists, aby zobaczyć pełny zestaw.",
    Responses_View_TryAgain: "Spróbuj ponownie",
    Responses_View_Untitled: "Bez tytułu",
    Responses_Approval_Column: "Zatwierdzenie",
    Responses_Approval_ReviewerColumn: "Sprawdził(a)",
    Responses_Approval_CommentColumn: "Komentarz recenzenta",
    Responses_Approval_Pending: "Oczekuje",
    Responses_Approval_Approved: "Zatwierdzono",
    Responses_Approval_Rejected: "Odrzucono",
    Responses_Approval_AnyStatus: "Dowolny stan zatwierdzenia",
    Responses_Approval_FilterLabel: "Filtruj według stanu zatwierdzenia",
    Responses_Approval_ApproveSelected: "Zatwierdź zaznaczone",
    Responses_Approval_RejectSelected: "Odrzuć zaznaczone",
    Responses_Approval_BulkFailed: "Nie można zaktualizować odpowiedzi: {count}. Spróbuj ponownie.",
    Responses_Approval_Approve: "Zatwierdź",
    Responses_Approval_Reject: "Odrzuć",
    Responses_Approval_Reset: "Przywróć stan oczekiwania",
    Responses_Approval_CommentLabel: "Komentarz (opcjonalnie)",
    Responses_Approval_ReviewedBy: "Sprawdził(a): {name}",
    Responses_Approval_Error: "Nie można zapisać decyzji. Spróbuj ponownie.",
    Responses_Dashboard_ApprovalStatus: "Oczekuje na sprawdzenie",
    Responses_Dashboard_ApprovalBreakdown: "Oczekujące: {pending}, zatwierdzone: {approved}, odrzucone: {rejected}",
    Responses_Dashboard_TimelineCoarsened: "Zakres dat jest długi, dlatego oś czasu została pogrupowana mniej szczegółowo ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Zakres dat jest bardzo długi, dlatego wyświetlono tylko ostatnie okresy: {count}.",
    Service_Item_DefaultTitle: "Odpowiedź – {date}",
    Service_Email_ApprovalSubject: "Twoja odpowiedź: {status} – {title}",
    Service_Email_ApprovalHeading: "Twoja odpowiedź: {status}",
    Service_Email_ApprovalIntro: "Recenzent oznaczył Twoją odpowiedź na formularz „{title}” jako: {status}.",
    Service_Email_ApprovalCommentLabel: "Komentarz recenzenta",
    Service_Approval_Approved: "zatwierdzona",
    Service_Approval_Rejected: "odrzucona",
    Service_Approval_Pending: "oczekująca",
    Service_Lookup_InvalidFilter: "Filtr wyszukiwania jest nieprawidłowy.",
    Service_Edit_NotAllowed: "Ten formularz nie zezwala na edytowanie przesłanej odpowiedzi.",
    Service_Edit_NotYours: "Możesz edytować tylko własną odpowiedź.",
    Service_Signature_AttachmentLabel: "Podpis",
    PropertyPane_ListsLoadFailed: "Nie można załadować list w tej witrynie.",
    PropertyPane_EnterListName: "Najpierw wprowadź nazwę nowej listy.",
    PropertyPane_CreatingList: "Tworzenie listy „{name}”…",
    PropertyPane_ListCreated: "Lista „{title}” została utworzona i wybrana.",
    PropertyPane_ListAlreadyExists: "Lista o nazwie „{name}” już istnieje — wybierz ją z listy rozwijanej powyżej.",
    PropertyPane_CreateListFailed: "Nie można utworzyć listy. Sprawdź, czy masz uprawnienia do tworzenia list w tej witrynie.",
    PropertyPane_Description: "Wybierz listę SharePoint, na której będą przechowywane odpowiedzi z formularza, lub utwórz nową. Wszystko inne — pytania, wygląd, powiadomienia — edytuje się bezpośrednio na stronie.",
    PropertyPane_ResponseList_GroupName: "Lista odpowiedzi",
    PropertyPane_ListDropdown_Label: "Zapisuj odpowiedzi na tej liście",
    PropertyPane_ResponsesGoTo: "Odpowiedzi trafiają na listę „{name}”.",
    PropertyPane_PickList: "Wybierz listę lub utwórz nową poniżej.",
    PropertyPane_LoadingLists: "Ładowanie list…",
    PropertyPane_NewListName_Label: "Lub utwórz nową listę",
    PropertyPane_NewListName_Placeholder: "Nazwa nowej listy",
    PropertyPane_CreateList_Button: "Utwórz listę",
    PropertyPane_Tips_GroupName: "Wskazówki",
    PropertyPane_Tip_AutoSave: "Pytania i ustawienia są zapisywane automatycznie podczas edycji — nie trzeba zapisywać ani publikować strony.",
    PropertyPane_Tip_Permissions: "Respondenci potrzebują uprawnień do dodawania elementów do listy odpowiedzi. Jeśli ktoś zgłosi błąd podczas przesyłania, sprawdź uprawnienia listy.",
    PropertyPane_Tip_Share: "Użyj opcji „Zbieraj odpowiedzi” na stronie, aby utworzyć kolumny listy i uzyskać łącze do wypełnienia, które można udostępnić.",
    App_ErrorBoundary_Title: "Smart Forms — błąd renderowania",
    App_ErrorBoundary_Message: "Komunikat:",
    App_ErrorBoundary_Stack: "Stos:",
    App_ErrorBoundary_NoStack: "(brak dostępnego stosu)",
    App_ErrorBoundary_ConsoleNote: "Pełne szczegóły zapisano również w konsoli przeglądarki.",
    App_DefaultQuestionTitle: "Pytanie {number}",
    App_Error_ListMissing: "Lista skonfigurowana dla tego formularza już nie istnieje. Wybierz inną listę w ustawieniach składnika Web Part.",
    App_Error_LoadConfig: "Coś poszło nie tak podczas ładowania konfiguracji formularza.",
    App_Error_Unable: "Nie można załadować formularza.",
    App_Publish_ConflictNotice: "Pytanie „{title}” ma już kolumnę listy innego typu ({type}). Zmień nazwę pytania, aby można było utworzyć nową kolumnę, lub przywróć poprzedni typ.",
    App_Publish_ConflictUnnamedQuestion: "pytanie",
    App_Publish_ColumnsAddedOne: "Dodano {count} kolumnę do listy „{list}”.",
    App_Publish_ColumnsAddedOther: "Dodano kolumny ({count}) do listy „{list}”.",
    App_Publish_TheList: "lista",
    App_Publish_UpToDate: "Lista odpowiedzi jest już aktualna.",
    App_Publish_Error: "Nie można utworzyć kolumn listy. Zwykle oznacza to brak uprawnienia Zarządzanie listami na liście odpowiedzi, ale może się to zdarzyć także w witrynach z wyłączonymi skryptami niestandardowymi. Sprawdź konsolę przeglądarki, aby poznać przyczynę błędu, lub spróbuj ponownie.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Utwórz dopracowany formularz na bazie listy SharePoint — typy pytań: {count}, logika rozgałęzień, przesyłanie plików, łącza do wypełnienia, które można udostępnić, oraz pulpit wyników.",
    App_Placeholder_ChooseList: "Wybierz lub utwórz listę",
    App_Placeholder_Hint: "Edytuj stronę i skonfiguruj ten składnik Web Part, aby rozpocząć.",
    App_Loading: "Ładowanie formularza…",
    App_OpenSettings: "Otwórz ustawienia",
    App_Tab_Questions: "Pytania",
    App_Tab_QuestionsWithCount: "Pytania ({count})",
    App_Tab_Responses: "Odpowiedzi",
    App_Tab_Responses_Title: "Odpowiedzi są zapisywane na liście „{list}”",
    App_Templates_Start: "Zacznij od szablonu",
    App_Settings_Title: "Ustawienia formularza — wygląd, powiadomienia, dostęp",
    App_Settings_AriaLabel: "Ustawienia formularza",
    App_Preview: "Podgląd",
    App_Preview_Close: "Zamknij podgląd",
    App_Preview_Hint: "Podgląd — nic, co tu prześlesz, nie zostanie zapisane. Walidacja i rozgałęzienia działają dokładnie tak, jak będą działać dla respondentów.",
    App_Publish_GettingReady: "Przygotowywanie…",
    App_Publish_CollectResponses: "Zbieraj odpowiedzi",
    App_Publish_Share: "Udostępnij",
    App_Retry: "Ponów",
    App_SaveError_Banner: "Nie można zapisać ostatniej zmiany. Sprawdź połączenie i spróbuj ponownie.",
    App_Preflight_BlockingTitle: "Popraw to przed rozpoczęciem zbierania",
    App_Preflight_WarningTitle: "Warto najpierw sprawdzić",
    App_Preflight_BlockingText: "Te problemy uniemożliwiłyby prawidłowe działanie opublikowanego formularza.",
    App_Preflight_WarningText: "Nic nie jest zepsute, ale zwykle warto to poprawić przed udostępnieniem łącza.",
    App_Preflight_GoTo: "Przejdź do",
    App_Preflight_CollectAnyway: "Zbieraj odpowiedzi mimo to",
    App_Preflight_Back: "Wróć do formularza",
    App_Cancel: "Anuluj",
    App_Done: "Gotowe",
    App_Share_Title: "Formularz jest gotowy do udostępnienia",
    App_Share_SubText: "Wyślij to łącze każdemu, kto ma wypełnić formularz.",
    App_Share_LinkAriaLabel: "Łącze udostępniania",
    App_Share_Copy: "Kopiuj",
    App_Share_Copied: "Skopiowano",
    App_Share_AddItemsEmphasis: "dodawania elementów",
    App_Share_PermissionNote: "Respondenci potrzebują uprawnień do {addItems} na liście „{title}” oraz dostępu do tej strony. Jeśli ktoś otrzymuje błąd podczas przesyłania, prawie zawsze jest to przyczyną.",
    App_Share_PrefillNote: "Możesz wstępnie odpowiadać na pytania w łączu, dodając nazwę kolumny, na przykład {example}.",
    App_Templates_ReplaceWarning: "Wybranie szablonu zastępuje obecne pytania.",
    App_Templates_PickStart: "Wybierz punkt wyjścia — potem możesz zmienić wszystko.",
    App_Templates_Empty: "Pusty",
    App_Templates_QuestionCount: "Pytania: {count}",
    App_SaveChip_SavingTitle: "Zapisywanie ostatniej edycji",
    App_SaveChip_Saving: "Zapisywanie…",
    App_SaveChip_FailedTitle: "Nie można zapisać ostatniej edycji. Sprawdź połączenie i spróbuj ponownie.",
    App_SaveChip_Failed: "Zapis nie powiódł się",
    App_SaveChip_SavedTitle: "Wszystkie zmiany zostały zapisane",
    App_SaveChip_Saved: "Zapisano",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Nowa odpowiedź — {title}",
    Service_Email_NewResponseHeading: "Nowa odpowiedź: {title}",
    Service_Email_NewResponseIntro: "Ktoś właśnie przesłał odpowiedź — {date}.",
    Service_Email_ReceiptSubject: "Twoja odpowiedź — {title}",
    Service_Email_ReceiptHeading: "Dziękujemy za odpowiedź!",
    Service_Email_ReceiptIntro: "Oto kopia tego, co zostało przesłane do formularza „{title}”.",
    App_History_Title: "Historia wersji",
    App_History_RestoredNotice: "Przywrócono wersję zapisaną {date}. Przejrzyj ją, a następnie użyj opcji Zbieraj odpowiedzi, aby opublikować nowe pytania.",
    App_History_Undo: "Cofnij przywracanie",
    App_Share_CopyManual: "Przeglądarka zablokowała kopiowanie. Zaznacz powyższy link i naciśnij Ctrl+C (Cmd+C na komputerze Mac), aby go skopiować.",
    App_Share_TeamsNote: "Korzystasz z aplikacji Microsoft Teams. Ten link otwiera stronę programu SharePoint bezpośrednio, więc odbiorcy potrzebują dostępu do witryny.",
    App_Share_PrefillNotSecure: "Wstępnie wypełnione odpowiedzi to tylko udogodnienie: każdy, kto ma link, może je zmienić, więc nigdy nie traktuj ich jako zabezpieczenia.",
    Designer_Section_DropHere: "Upuść pytanie tutaj",
    Designer_Section_DropEnd: "Upuść tutaj, aby przenieść na koniec tej sekcji",
    Designer_Rules_RemovedOne: "Usunięto 1 regułę rozgałęzienia, która przestała pasować.",
    Designer_Rules_RemovedOther: "Usunięto reguły rozgałęzienia, które przestały pasować: {count}.",
    Designer_Settings_AllowEdit: "Zezwalaj respondentom na edytowanie odpowiedzi",
    Designer_Settings_AllowEditHint: "Respondenci mogą ponownie otworzyć i zaktualizować przesłane odpowiedzi. Każda osoba może edytować tylko własną odpowiedź.",
    Designer_Settings_EnableApproval: "Włącz przepływ pracy zatwierdzania",
    Designer_Settings_ApprovalNotify: "Wyślij e-mail do respondenta po podjęciu decyzji",
    Designer_Settings_ApprovalHint: "Dodaje kolumny zatwierdzania do listy odpowiedzi przy następnej publikacji. Właściciele zatwierdzają lub odrzucają odpowiedzi na karcie Odpowiedzi.",
    Designer_History_Title: "Historia wersji",
    Designer_History_Intro: "Wcześniej zapisane wersje pytań i ustawień tego formularza. Przywrócenie ładuje wersję do projektanta; możesz je cofnąć, a nowe pytania są tworzone dopiero po opublikowaniu.",
    Designer_History_Loading: "Ładowanie wersji...",
    Designer_History_Empty: "Nie znaleziono wcześniejszych wersji. Historia wersji wymaga włączenia przechowywania wersji dla listy „Smart Forms Config” oraz co najmniej jednej zapisanej edycji.",
    Designer_History_Latest: "Najnowsza",
    Designer_History_LatestTitle: "To jest wersja obecnie używana",
    Designer_History_By: "autor: {name}",
    Designer_History_UnknownAuthor: "Nieznany autor",
    Designer_History_VersionLabel: "wersja {label}",
    Designer_History_Preview: "Podgląd",
    Designer_History_Restore: "Przywróć",
    Designer_History_QuestionsOne: "1 pytanie",
    Designer_History_QuestionsOther: "Pytania: {count}",
    Designer_History_LoadFailed: "Nie można załadować tej wersji.",
    Designer_History_ConfirmTitle: "Przywrócić tę wersję?",
    Designer_History_ConfirmText: "Formularz zostanie zastąpiony wersją zapisaną {date} (pytania: {count}). Możesz to od razu cofnąć."
  };
});
