define([], function () {
  return {
    Designer_Color_Blue: "Azul",
    Designer_Color_Teal: "Verde-azulado",
    Designer_Color_Green: "Verde",
    Designer_Color_Purple: "Roxo",
    Designer_Color_Magenta: "Magenta",
    Designer_Color_Red: "Vermelho",
    Designer_Color_Orange: "Laranja",
    Designer_Color_Gray: "Cinza",
    Designer_Settings_LayoutSinglePage: "Todas as perguntas em uma página",
    Designer_Settings_LayoutWizard: "Uma seção por etapa (assistente)",
    Designer_Settings_Title: "Configurações do formulário",
    Designer_Common_Apply: "Aplicar",
    Designer_Common_Cancel: "Cancelar",
    Designer_Settings_TabBasics: "Básico",
    Designer_Settings_FormTitle: "Título do formulário",
    Designer_Settings_Description: "Descrição",
    Designer_Settings_Layout: "Layout",
    Designer_Settings_NumberQuestions: "Numerar as perguntas",
    Designer_Settings_ShuffleQuestions: "Embaralhar a ordem das perguntas para cada respondente",
    Designer_Settings_ShowProgressBar: "Mostrar uma barra de progresso",
    Designer_Settings_TabAppearance: "Aparência",
    Designer_Settings_AccentColor: "Cor de destaque",
    Designer_Settings_CustomColorTitle: "Cor personalizada",
    Designer_Settings_CustomColorAria: "Cor de destaque personalizada",
    Designer_Settings_AccentHint: "As cores de destaque são ajustadas automaticamente para contraste em sites escuros, para que o formulário continue legível em qualquer tema da página.",
    Designer_Settings_ShowHeader: "Mostrar o cabeçalho do formulário",
    Designer_Settings_HeaderIcon: "Ícone do cabeçalho",
    Designer_Settings_TabAfterSubmit: "Após o envio",
    Designer_Settings_SubmitButtonText: "Texto do botão Enviar",
    Designer_Settings_SubmitPlaceholder: "Enviar",
    Designer_Settings_ThankYouTitle: "Título de agradecimento",
    Designer_Settings_ThankYouPlaceholder: "Obrigado!",
    Designer_Settings_ThankYouMessage: "Mensagem de agradecimento",
    Designer_Settings_ShowSubmitAnother: "Mostrar um botão “Enviar outra resposta”",
    Designer_Settings_TabNotifications: "Notificações",
    Designer_Settings_EmailEachResponseTo: "Enviar cada resposta por email para",
    Designer_Settings_EmailPlaceholder: "nome@empresa.com; equipe@empresa.com",
    Designer_Settings_EmailDescription: "Pessoas da sua organização recebem cada resposta por email, com um link para o item da lista",
    Designer_Settings_RespondentReceipt: "Enviar aos respondentes uma cópia das respostas por email",
    Designer_Settings_NotificationsInfo: "As notificações usam o serviço de email do próprio SharePoint, portanto os destinatários precisam ser usuários da sua organização. Endereços externos são descartados silenciosamente.",
    Designer_Settings_TabAccess: "Acesso",
    Designer_Settings_OpenFrom: "Abrir em",
    Designer_Settings_OpenImmediately: "Abrir imediatamente",
    Designer_Settings_CloseAfter: "Fechar em",
    Designer_Settings_NeverClose: "Nunca fechar",
    Designer_Settings_ClearDates: "Limpar datas",
    Designer_Settings_DatesInverted: "A data de fechamento é igual ou anterior à data de abertura, então o formulário nunca aceitaria respostas.",
    Designer_Settings_MaxResponses: "Parar após este número de respostas",
    Designer_Settings_NoLimit: "Sem limite",
    Designer_Settings_OneResponsePerPerson: "Permitir apenas uma resposta por pessoa",
    Designer_Settings_AllowSaveDraft: "Permitir que os respondentes salvem um rascunho e concluam depois",
    Designer_Settings_ClosedMessage: "Mensagem exibida quando o formulário está fechado",
    Designer_Settings_ClosedMessagePlaceholder: "Este formulário não está mais aceitando respostas.",
    Designer_Settings_AccessInfo: "Esses limites são aplicados pelo formulário, não pelo SharePoint. Qualquer pessoa com permissão para adicionar itens à lista de respostas ainda poderia adicionar um diretamente pela lista.",
    Designer_Field_StyleInfo: "Informação (destaque)",
    Designer_Field_StyleSuccess: "Sucesso (verde)",
    Designer_Field_StyleWarning: "Aviso (âmbar)",
    Designer_Field_StylePlain: "Texto simples",
    Designer_Field_StyleDivider: "Linha divisória",
    Designer_Field_IconStars: "Estrelas",
    Designer_Field_IconHearts: "Corações",
    Designer_Field_IconThumbs: "Joinha",
    Designer_Field_FormatPlain: "Número simples",
    Designer_Field_FormatCurrency: "Moeda",
    Designer_Field_FormatPercent: "Porcentagem",
    Designer_Field_UntitledQuestion: "Pergunta sem título",
    Designer_Field_DeletedQuestion: "uma pergunta excluída",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} e {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "OU",
    Designer_Rule_JoinAll: "E",
    Designer_Rule_Preview: "Exibida quando {conditions}.",
    Designer_Field_Yes: "Sim",
    Designer_Field_No: "Não",
    Designer_Field_When: "Quando",
    Designer_Field_SelectValue: "Selecione um valor",
    Designer_Field_DateValuePlaceholder: "AAAA-MM-DD ou \"today\"",
    Designer_Field_ValuePlaceholder: "Valor",
    Designer_Field_UpperBound: "Limite superior",
    Designer_Field_RemoveCondition: "Remover esta condição",
    Designer_Field_FormulaInvalid: "Não foi possível calcular esta fórmula. Verifique os parênteses e os operadores.",
    Designer_Field_FormulaMissing: "Estas perguntas não existem: {names}.",
    Designer_Field_FormulaPreview: "Com todas as entradas em 10, isto mostra {value}.",
    Designer_Field_HintYesNo: "Use \"yes\" ou \"no\"",
    Designer_Field_HintMultiDefault: "Separe vários padrões com ;",
    Designer_Field_HintSingleDefault: "Deve corresponder a uma das opções",
    Designer_Field_HintDate: "Use \"today\" ou uma data como 2026-03-01",
    Designer_Field_HintTime: "Use \"now\" ou uma hora como 09:30",
    Designer_Field_QuestionSettings: "Configurações da pergunta",
    Designer_Field_Appearance: "Aparência",
    Designer_Field_Style: "Estilo",
    Designer_Field_ImageUrl: "URL da imagem (opcional)",
    Designer_Field_Content: "Conteúdo",
    Designer_Field_BasicFormatting: "Formatação básica permitida: negrito, itálico, listas e links.",
    Designer_Field_TabOptions: "Opções",
    Designer_Field_TabBranching: "Ramificação",
    Designer_Field_BranchingNeedsQuestion: "Adicione outra pergunta primeiro — a ramificação precisa de algo em que se basear.",
    Designer_Field_BranchingToggle: "Mostrar esta pergunta somente quando outras respostas corresponderem",
    Designer_Field_Match: "Corresponder a",
    Designer_Field_MatchAll: "todas estas",
    Designer_Field_MatchAny: "qualquer uma destas",
    Designer_Field_AddCondition: "Adicionar condição",
    Designer_Field_TabValidation: "Validação",
    Designer_Field_HelpText: "Texto de ajuda",
    Designer_Field_HelpTextPlaceholder: "Exibido abaixo do rótulo da pergunta",
    Designer_Field_CheckboxLabel: "Rótulo da caixa de seleção",
    Designer_Field_Placeholder: "Texto de exemplo",
    Designer_Field_DefaultAnswer: "Resposta padrão",
    Designer_Field_RequiredMessage: "Mensagem personalizada de obrigatório",
    Designer_Field_RequiredMessagePlaceholder: "{title} é obrigatório",
    Designer_Field_ThisQuestion: "Esta pergunta",
    Designer_Field_RequiredMessageDescription: "Exibida no lugar da mensagem padrão quando esta pergunta é deixada em branco",
    Designer_Field_ReadOnly: "Somente leitura (a resposta só pode vir de um link preenchido)",
    Designer_Field_ValidationRules: "Regras de validação",
    Designer_Field_MaxLength: "Comprimento máximo",
    Designer_Field_Pattern: "Deve corresponder a este padrão",
    Designer_Field_PatternDescription: "Uma expressão regular. Deixe em branco para não verificar padrão.",
    Designer_Field_PatternMessage: "Mensagem quando o padrão não corresponde",
    Designer_Field_PatternMessagePlaceholder: "Esta resposta não está no formato esperado",
    Designer_Field_Format: "Formato",
    Designer_Field_UnitSuffix: "Unidade exibida após o valor",
    Designer_Field_UnitSuffixPlaceholder: "kg, h, itens…",
    Designer_Field_Minimum: "Mínimo",
    Designer_Field_Maximum: "Máximo",
    Designer_Field_Decimals: "Casas decimais",
    Designer_Field_Formula: "Fórmula",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Consulte outras perguntas pelo texto delas entre chaves. Suporta + - * / ( ) e round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Perguntas disponíveis: {questions}",
    Designer_Field_NoneYet: "nenhuma ainda",
    Designer_Field_Step: "Passo",
    Designer_Field_From: "De",
    Designer_Field_To: "Até",
    Designer_Field_LowLabel: "Rótulo da extremidade inferior",
    Designer_Field_LowLabelPlaceholder: "Nada provável",
    Designer_Field_HighLabel: "Rótulo da extremidade superior",
    Designer_Field_HighLabelPlaceholder: "Extremamente provável",
    Designer_Field_SummarizeAs: "Resumir como",
    Designer_Field_SummarizeAverage: "Média e distribuição",
    Designer_Field_SummarizeNps: "Net Promoter Score (requer escala de 0 a 10)",
    Designer_Field_NpsWarning: "O Net Promoter Score só faz sentido em uma escala de 0 a 10. Defina De como 0 e Até como 10.",
    Designer_Field_NumberOfIcons: "Número de ícones",
    Designer_Field_Icon: "Ícone",
    Designer_Field_AllowHalf: "Permitir meio valor",
    Designer_Field_ShowOptionsAs: "Mostrar opções como",
    Designer_Field_DisplayButtons: "Botões em linha",
    Designer_Field_DisplayDropdown: "Lista suspensa",
    Designer_Field_DisplayAutomatic: "Automático (em linha até 6 opções)",
    Designer_Field_AllowOther: "Adicionar uma opção “Outro” de preenchimento livre",
    Designer_Field_OtherLabel: "Rótulo da opção “Outro”",
    Designer_Field_OtherPlaceholder: "Outro",
    Designer_Field_ShuffleOptions: "Embaralhar a ordem das opções para cada respondente",
    Designer_Field_MinSelections: "Mínimo de seleções",
    Designer_Field_MaxSelections: "Máximo de seleções",
    Designer_Field_SourceList: "Lista de origem",
    Designer_Field_ChooseList: "Escolha uma lista",
    Designer_Field_LookupColumn: "Coluna de onde ler as opções",
    Designer_Field_ChooseColumn: "Escolha uma coluna",
    Designer_Field_ChooseListFirst: "Escolha uma lista primeiro",
    Designer_Field_LookupFilter: "Filtro (opcional)",
    Designer_Field_LookupFilterDescription: "Um filtro OData que restringe quais itens de origem viram opções",
    Designer_Field_LookupInfo: "As respostas armazenam o texto da opção, não um link para o item de origem, então as respostas continuam legíveis mesmo que a lista de origem mude depois.",
    Designer_Field_ConsentText: "Termos exibidos acima da caixa de seleção",
    Designer_Field_AllowMultiplePeople: "Permitir várias pessoas",
    Designer_Field_AllowGroups: "Permitir também grupos",
    Designer_Field_IncludeTime: "Incluir uma hora do dia",
    Designer_Field_TimeStep: "Intervalo de tempo (minutos)",
    Designer_Field_MaxFiles: "Máximo de arquivos",
    Designer_Field_MaxFileSize: "Tamanho máx. de cada um (MB)",
    Designer_Field_AcceptedTypes: "Tipos de arquivo aceitos",
    Designer_Field_AcceptedTypesDescription: "Extensões separadas por vírgula. Deixe em branco para aceitar tudo o que o SharePoint permite.",
    Designer_Field_FilesInfo: "Os arquivos são salvos como anexos no item de resposta. O SharePoint bloqueia algumas extensões (como .exe) independentemente do que você permitir aqui.",
    Designer_Field_Rows: "Linhas",
    Designer_Field_ProvisionedNote: "Esta pergunta já tem uma coluna de lista ({name}). As configurações que alteram o tipo da coluna estão bloqueadas — duplique a pergunta se precisar de um tipo diferente.",
    Designer_Category_Text: "Texto",
    Designer_Category_Choice: "Escolha",
    Designer_Category_Scales: "Escalas",
    Designer_Category_Date: "Data",
    Designer_Category_People: "Pessoas",
    Designer_Category_Advanced: "Avançado",
    Designer_Category_Layout: "Layout",
    Designer_Menu_CommonPresets: "Predefinições comuns",
    Designer_Menu_AllTypes: "Todos os tipos de pergunta",
    Designer_Menu_ChangeType: "Alterar tipo",
    Designer_Menu_TypeLockedTitle: "A coluna da lista já existe, então o tipo está bloqueado. Duplique a pergunta para alterá-lo.",
    Designer_Menu_MoreSettings: "Ramificação, validação e mais",
    Designer_Menu_InsertBelow: "Inserir pergunta abaixo",
    Designer_Card_Duplicate: "Duplicar",
    Designer_Card_DeleteQuestion: "Excluir pergunta",
    Designer_Outline_Aria: "Estrutura de tópicos das perguntas",
    Designer_Outline_QuestionCountOne: "{count} pergunta",
    Designer_Outline_QuestionCountOther: "{count} perguntas",
    Designer_Outline_IssuesTitle: "{count} problema(s) para revisar",
    Designer_Outline_Find: "Localizar uma pergunta",
    Designer_Outline_Empty: "Nenhuma pergunta ainda.",
    Designer_Section_DefaultTitle: "Seção {number}",
    Designer_Card_Question: "Pergunta",
    Designer_Card_BranchingTitle: "Esta pergunta só aparece quando uma regra de ramificação é atendida",
    Designer_Card_BranchingChip: "Ramificação",
    Designer_Card_LiveTitle: "A coluna da lista existe, então o tipo está bloqueado",
    Designer_Card_LiveChip: "Ativa",
    Designer_Card_CheckChip: "Verificar",
    Designer_Option_Placeholder: "Opção {number}",
    Designer_Option_LabelAria: "Rótulo da opção {number}",
    Designer_Option_ImageUrl: "URL da imagem",
    Designer_Option_ImageUrlAria: "URL da imagem da opção {number}",
    Designer_Option_Remove: "Remover opção",
    Designer_Option_RemoveAria: "Remover opção {number}",
    Designer_Option_Add: "Adicionar opção",
    Designer_Option_OtherHint: "Os respondentes também podem escrever uma resposta rotulada como “{label}”.",
    Designer_Option_OtherFallback: "Outro",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Remover",
    Designer_Grid_RemoveAria: "Remover {label} {number}",
    Designer_Grid_Statements: "Afirmações",
    Designer_Grid_Scale: "Escala",
    Designer_Grid_AddStatement: "Adicionar afirmação",
    Designer_Grid_AddScale: "Adicionar escala",
    Designer_Width_Full: "Largura total",
    Designer_Width_Half: "Meia largura",
    Designer_Width_Third: "Um terço da largura",
    Designer_Width_Aria: "Largura da pergunta",
    Designer_Card_BlockLabelPlaceholder: "Rótulo do bloco (não exibido aos respondentes)",
    Designer_Card_QuestionText: "Texto da pergunta",
    Designer_Card_MoveUp: "Mover para cima",
    Designer_Card_MoveQuestionUp: "Mover pergunta para cima",
    Designer_Card_MoveDown: "Mover para baixo",
    Designer_Card_MoveQuestionDown: "Mover pergunta para baixo",
    Designer_Card_DuplicateQuestion: "Duplicar pergunta",
    Designer_Card_MultipleAnswers: "Várias respostas",
    Designer_Card_Required: "Obrigatória",
    Designer_Card_MoreOptions: "Mais opções",
    Designer_Card_MoreOptionsAria: "Mais opções para esta pergunta",
    Designer_Canvas_FormTitle: "Título do formulário",
    Designer_Canvas_DescriptionPlaceholder: "Adicione uma descrição (opcional)",
    Designer_Canvas_DescriptionAria: "Descrição do formulário",
    Designer_Canvas_EmptyTitle: "Adicione sua primeira pergunta",
    Designer_Canvas_EmptyBody: "Escolha um tipo de pergunta para começar. Você pode reordenar as perguntas arrastando-as e adicionar ramificação para que as pessoas vejam apenas o que se aplica a elas.",
    Designer_Section_Chip: "Seção {number} de {total}",
    Designer_Section_TitlePlaceholder: "Título da seção",
    Designer_Section_TitleAria: "Título da seção {number}",
    Designer_Section_DescriptionPlaceholder: "Descrição (opcional)",
    Designer_Section_DescriptionAria: "Descrição da seção {number}",
    Designer_Section_MoveUp: "Mover seção para cima",
    Designer_Section_MoveDown: "Mover seção para baixo",
    Designer_Section_Delete: "Excluir seção",
    Designer_Card_DragToReorder: "Arraste para reordenar",
    Designer_Card_ReorderAria: "Reordenar {title}",
    Designer_Card_ReorderFallback: "pergunta",
    Designer_Canvas_AddNew: "Adicionar novo",
    Designer_Canvas_AddSection: "Adicionar seção",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Endereço",
    Form_Address_Street2Placeholder: "Apartamento, sala etc. (opcional)",
    Form_Address_CityPlaceholder: "Cidade",
    Form_Address_StatePlaceholder: "Estado",
    Form_Address_PostalCodePlaceholder: "CEP",
    Form_Address_CountryPlaceholder: "País",
    Form_Address_StreetAria: "endereço",
    Form_Address_Street2Aria: "complemento do endereço",
    Form_Address_CityAria: "cidade",
    Form_Address_StateAria: "estado",
    Form_Address_PostalCodeAria: "CEP",
    Form_Address_CountryAria: "país",
    Form_Consent_DefaultLabel: "Eu concordo",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered} de {total} linhas respondidas",
    Form_Lookup_LoadError: "Não foi possível carregar as opções desta pergunta.",
    Form_Lookup_Loading: "Carregando opções…",
    Form_Lookup_SelectOptionsPlaceholder: "Selecione opções",
    Form_Lookup_SelectOptionPlaceholder: "Selecione uma opção",
    Form_Person_Placeholder: "Comece a digitar um nome…",
    Form_Person_SuggestedPeopleAndGroups: "Pessoas e grupos sugeridos",
    Form_Person_SuggestedPeople: "Pessoas sugeridas",
    Form_Person_NoPeopleOrGroups: "Nenhuma pessoa ou grupo encontrado",
    Form_Person_NoPeople: "Nenhuma pessoa encontrada",
    Form_Person_Searching: "Pesquisando…",
    Form_Ranking_Moved: "{item} movido para a posição {position} de {total}",
    Form_Ranking_MoveUp: "Mover para cima",
    Form_Ranking_MoveDown: "Mover para baixo",
    Form_Ranking_MoveItemUpAria: "Mover {item} para cima",
    Form_Ranking_MoveItemDownAria: "Mover {item} para baixo",
    Form_Rating_ValueText: "{value} de {max}",
    Form_Rating_NotRated: "Sem classificação",
    Form_Rating_Clear: "Limpar classificação",
    Form_RichText_Bold: "Negrito",
    Form_RichText_Italic: "Itálico",
    Form_RichText_Underline: "Sublinhado",
    Form_RichText_BulletedList: "Lista com marcadores",
    Form_RichText_NumberedList: "Lista numerada",
    Form_RichText_ClearFormatting: "Limpar formatação",
    Form_RichText_ToolbarAria: "Formatação de texto",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\" foi ignorado — o limite é {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" não é um tipo aceito.",
    Form_File_TooLarge: "\"{name}\" é maior que {size} MB.",
    Form_File_AlreadyAttached: "\"{name}\" já está anexado.",
    Form_File_ReadError: "Não foi possível ler um dos arquivos. Tente anexá-lo novamente.",
    Form_File_HintMaxSize: "até {size} MB cada",
    Form_File_HintOneFile: "1 arquivo",
    Form_File_HintMaxFiles: "máx. {count} arquivos",
    Form_File_Reading: "Lendo arquivos…",
    Form_File_DropPrompt: "Solte os arquivos aqui ou clique para procurar",
    Form_File_Remove: "Remover {name}",
    Form_Signature_Alt: "Assinatura",
    Form_Signature_AriaSigned: "{label} — assinado",
    Form_Signature_AriaEmpty: "{label} — vazio",
    Form_Signature_Clear: "Limpar",
    Form_Signature_Signed: "Assinado",
    Form_Signature_Prompt: "Assine acima usando um mouse, caneta ou o dedo",
    Form_Time_Placeholder: "Selecione uma hora",
    Form_Field_DatePlaceholder: "Selecione uma data",
    Form_Field_TimeAriaWithLabel: "{label} — hora",
    Form_Field_TimeAria: "Hora",
    Form_Field_OtherDefault: "Outro",
    Form_Field_SelectOptionsPlaceholder: "Selecione opções",
    Form_Field_PleaseSpecify: "Especifique",
    Form_Field_OtherSpecifyAria: "{label} — especifique",
    Form_Field_SelectOptionPlaceholder: "Selecione uma opção",
    Form_Field_Yes: "Sim",
    Form_Field_No: "Não",
    Form_Field_SliderHint: "Arraste o controle deslizante para responder",
    Form_Field_WebAddressAriaWithLabel: "{label} — endereço da Web",
    Form_Field_WebAddressAria: "Endereço da Web",
    Form_Field_DisplayTextPlaceholder: "Texto de exibição (opcional)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — texto de exibição",
    Form_Field_DisplayTextAria: "Texto de exibição",
    Form_Field_ChooseBetween: "Escolha entre {min} e {max}",
    Form_Field_ChooseAtLeast: "Escolha pelo menos {min}",
    Form_Field_ChooseUpTo: "Escolha até {max}",
    Form_Field_SelectedCount: "{count} selecionados",
    Form_Field_RequiredAria: "(obrigatório)",
    Form_Submit_SaveError: "Não foi possível salvar sua resposta. Verifique se o formulário foi publicado pelo designer e se você tem permissão para adicionar itens à lista de respostas.",
    Form_Empty_Message: "Este formulário ainda não tem perguntas. O proprietário do formulário pode adicioná-las na guia Perguntas.",
    Form_Checking: "Verificando o formulário…",
    Form_Closed_NotYetOpen: "Ainda não aberto",
    Form_Closed_AlreadyAnswered: "Já respondido",
    Form_Closed_Title: "Formulário fechado",
    Form_Confirmation_PreviewNotice: "Esta foi uma visualização — nada foi salvo na lista de respostas.",
    Form_Confirmation_PreviewAgain: "Visualizar novamente",
    Form_Confirmation_SubmitAnother: "Enviar outra resposta",
    Form_Wizard_StepFallback: "Etapa {step}",
    Form_Wizard_StepsAria: "Etapas do formulário",
    Form_Wizard_StepOf: "Etapa {step} de {total}",
    Form_ErrorSummary_Title: "Verifique {count} respostas:",
    Form_ErrorSummary_UntitledQuestion: "Pergunta sem título",
    Form_ErrorSummary_Question: "Pergunta",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Voltar",
    Form_Nav_Next: "Avançar",
    Form_Draft_Saving: "Salvando…",
    Form_Draft_Saved: "Rascunho salvo",
    Form_Draft_SaveAndFinishLater: "Salvar e concluir depois",
    Form_Draft_NotSaved: "Rascunho não salvo",
    Form_Submit_Preview: "Enviar (visualização)",
    Form_Submit_Button: "Enviar",
    Form_Response_NoAnswer: "Sem resposta",
    Form_Signature_TypeLabel: "Digite seu nome completo",
    Form_Signature_TypeInstead: "Digitar meu nome",
    Form_Signature_DrawInstead: "Desenhar",
    Form_Edit_Button: "Editar sua resposta anterior",
    Form_Edit_Available: "Você já enviou uma resposta. Você pode editá-la em vez de enviar uma nova.",
    Form_Edit_Banner: "Você está editando sua resposta anterior.",
    Form_Edit_Save: "Atualizar resposta",
    Form_Edit_UpdatedTitle: "Resposta atualizada",
    Form_Edit_UpdatedMessage: "Suas alterações foram salvas.",
    Form_Edit_LoadError: "Não foi possível carregar sua resposta anterior. Tente novamente.",
    Form_Draft_MissingFiles: "Anexe novamente: {names}. Não foi possível restaurar esses arquivos.",
    Form_Attachments_Failed: "Suas respostas foram salvas, mas não foi possível carregar estes anexos: {names}. Tente novamente ou entre em contato com o proprietário do formulário.",
    Logic_ThisQuestion: "Esta pergunta",
    Logic_Required: "{label} é obrigatório",
    Logic_RequiredConsent: "Marque a caixa para continuar",
    Logic_RequiredFile: "Anexe pelo menos um arquivo",
    Logic_RequiredSignature: "Adicione sua assinatura",
    Logic_RequiredLikert: "Responda a todas as linhas",
    Logic_InvalidEmail: "Insira um endereço de email válido",
    Logic_InvalidPhone: "Insira um número de telefone válido",
    Logic_InvalidUrl: "Insira um endereço da Web válido começando com http:// ou https://",
    Logic_MinValue: "O valor deve ser de no mínimo {value}",
    Logic_MaxValue: "O valor deve ser de no máximo {value}",
    Logic_MaxLength: "O comprimento máximo é de {max} caracteres",
    Logic_ChooseAtLeastOne: "Escolha pelo menos {count} opção",
    Logic_ChooseAtLeastMany: "Escolha pelo menos {count} opções",
    Logic_ChooseAtMostOne: "Escolha no máximo {count} opção",
    Logic_ChooseAtMostMany: "Escolha no máximo {count} opções",
    Logic_LikertRemaining: "Responda a todas as linhas (faltam {count})",
    Logic_MaxFilesOne: "Anexe no máximo {count} arquivo",
    Logic_MaxFilesMany: "Anexe no máximo {count} arquivos",
    Logic_FileTooLarge: "\"{name}\" é maior que {size} MB",
    Logic_FileTypeNotAccepted: "\"{name}\" não é um tipo de arquivo aceito ({types})",
    Logic_AddressRequired: "Insira pelo menos uma rua e uma cidade",
    Logic_PatternDefault: "Esta resposta não está no formato esperado",
    Logic_Yes: "Sim",
    Logic_No: "Não",
    Logic_Agreed: "Aceito",
    Logic_NotAgreed: "Não aceito",
    Logic_Signed: "Assinado",
    Logic_NoAnswer: "(sem resposta)",
    Logic_Unknown: "(desconhecido)",
    Logic_OtherSlice: "Outros ({count})",
    Logic_CsvResponseId: "ID da resposta",
    Logic_CsvSubmitted: "Enviado",
    Logic_CsvSubmittedBy: "Enviado por",
    Logic_EmailQuestion: "Pergunta",
    Logic_EmailViewItem: "Exibir no Microsoft Lists",
    Logic_EmailFooter: "Enviado automaticamente pelo Smart Forms.",
    Logic_ClosedDefault: "Este formulário não está mais aceitando respostas.",
    Logic_NotYetOpen: "Este formulário será aberto em {date}.",
    Logic_AlreadyResponded: "Você já respondeu a este formulário. Obrigado!",
    Logic_UntitledQuestion: "Uma pergunta sem título",
    Logic_Issue_NoQuestions: "Adicione pelo menos uma pergunta antes de coletar respostas.",
    Logic_Issue_NoTitle: "Uma pergunta não tem texto — ela será nomeada automaticamente ao publicar.",
    Logic_Issue_DuplicateTitle: "{label} tem o mesmo texto que outra pergunta, o que dificulta a leitura dos resultados.",
    Logic_Issue_NeedTwoOptions: "{label} precisa de pelo menos duas opções.",
    Logic_Issue_ImageNoImage: "{label} tem opções sem imagem — elas serão exibidas como blocos de texto.",
    Logic_Issue_LikertNeedRow: "{label} precisa de pelo menos uma linha.",
    Logic_Issue_LikertNeedColumns: "{label} precisa de pelo menos duas colunas de escala.",
    Logic_Issue_NoLookupList: "{label} não tem uma lista de origem selecionada.",
    Logic_Issue_NoFormula: "{label} não tem fórmula.",
    Logic_Issue_BadFormula: "{label} tem uma fórmula que não pode ser calculada. Verifique os parênteses e os operadores.",
    Logic_Issue_MissingRefs: "{label} faz referência a perguntas que não existem: {names}.",
    Logic_Issue_BadPattern: "{label} tem um padrão de validação inválido.",
    Logic_Issue_BrokenRule: "{label} tem uma regra de ramificação que aponta para uma pergunta excluída.",
    Logic_Issue_SelfRule: "{label} tem uma regra de ramificação que faz referência a ela mesma.",
    Logic_Issue_RuleMismatch: "{label} tem uma regra de ramificação que não corresponde mais à pergunta da qual depende.",
    Logic_Issue_RequiredReadOnly: "{label} é obrigatório e somente leitura, portanto só pode ser respondido por um link preenchido previamente.",
    Logic_Issue_EmptySection: "Uma seção não tem perguntas e será ignorada.",
    Logic_Issue_CloseBeforeOpen: "A data de fechamento é igual ou anterior à data de abertura, portanto o formulário nunca aceitará respostas.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Os emails de aprovação estão ativados, mas a etapa de aprovação está desativada.",
    Logic_Op_equals: "é",
    Logic_Op_notEquals: "não é",
    Logic_Op_contains: "contém",
    Logic_Op_notContains: "não contém",
    Logic_Op_notEmpty: "foi respondida",
    Logic_Op_empty: "não foi respondida",
    Logic_Op_greaterThan: "é maior que",
    Logic_Op_greaterOrEqual: "é no mínimo",
    Logic_Op_lessThan: "é menor que",
    Logic_Op_lessOrEqual: "é no máximo",
    Logic_Op_between: "está entre",
    Logic_Op_before: "é anterior a",
    Logic_Op_after: "é posterior a",
    Logic_Type_Text: "Resposta curta",
    Logic_TypeDesc_Text: "Uma única linha de texto",
    Logic_Category_Text: "Texto",
    Logic_Type_MultilineText: "Resposta longa",
    Logic_TypeDesc_MultilineText: "Várias linhas de texto simples",
    Logic_Type_RichText: "Texto formatado",
    Logic_TypeDesc_RichText: "Negrito, listas e links",
    Logic_Type_Choice: "Escolha",
    Logic_TypeDesc_Choice: "Escolha em uma lista de opções",
    Logic_Category_Choice: "Escolha",
    Logic_Type_ImageChoice: "Escolha de imagem",
    Logic_TypeDesc_ImageChoice: "Escolha entre blocos de imagem",
    Logic_Type_Lookup: "Pesquisa em uma lista",
    Logic_TypeDesc_Lookup: "Opções lidas em tempo real de outra lista do SharePoint",
    Logic_Type_YesNo: "Sim / Não",
    Logic_TypeDesc_YesNo: "Uma simples chave liga/desliga",
    Logic_Type_Consent: "Consentimento",
    Logic_TypeDesc_Consent: "Uma caixa de seleção que o respondente deve marcar para continuar",
    Logic_Type_Ranking: "Classificação",
    Logic_TypeDesc_Ranking: "Arraste as opções para a ordem de preferência",
    Logic_Type_Rating: "Avaliação",
    Logic_TypeDesc_Rating: "Estrelas, corações ou polegares",
    Logic_Category_Scales: "Escalas",
    Logic_Type_Scale: "Escala de opinião",
    Logic_TypeDesc_Scale: "Uma escala numerada com extremidades rotuladas",
    Logic_Type_Slider: "Controle deslizante",
    Logic_TypeDesc_Slider: "Um valor em uma escala deslizante",
    Logic_Type_Likert: "Grade Likert",
    Logic_TypeDesc_Likert: "Avalie várias afirmações em uma mesma escala",
    Logic_Type_Number: "Número",
    Logic_TypeDesc_Number: "Simples, moeda ou porcentagem",
    Logic_Category_Advanced: "Avançado",
    Logic_Type_Calculated: "Calculado",
    Logic_TypeDesc_Calculated: "Um total somente leitura calculado a partir de outras respostas",
    Logic_Type_Date: "Data",
    Logic_TypeDesc_Date: "Uma data do calendário, opcionalmente com horário",
    Logic_Category_Date: "Data",
    Logic_Type_Time: "Hora",
    Logic_TypeDesc_Time: "Um horário do dia isolado",
    Logic_Type_Person: "Pessoa",
    Logic_TypeDesc_Person: "Escolha alguém da organização",
    Logic_Category_People: "Pessoas",
    Logic_Type_Email: "Email",
    Logic_TypeDesc_Email: "Um endereço de email, validado",
    Logic_Type_Phone: "Telefone",
    Logic_TypeDesc_Phone: "Um número de telefone, validado",
    Logic_Type_Address: "Endereço",
    Logic_TypeDesc_Address: "Rua, cidade, CEP e país",
    Logic_Type_Hyperlink: "Link",
    Logic_TypeDesc_Hyperlink: "Um endereço da Web",
    Logic_Type_FileUpload: "Upload de arquivo",
    Logic_TypeDesc_FileUpload: "Anexe um ou mais arquivos à resposta",
    Logic_Type_Signature: "Assinatura",
    Logic_TypeDesc_Signature: "Assine com o mouse, a caneta ou o dedo",
    Logic_Type_Content: "Bloco de texto",
    Logic_TypeDesc_Content: "Instruções ou uma imagem — não coleta resposta",
    Logic_Category_Layout: "Layout",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Qual a probabilidade de você recomendar…",
    Logic_Preset_satisfaction: "Satisfação (1–5)",
    Logic_PresetDesc_satisfaction: "De muito insatisfeito a muito satisfeito",
    Logic_Preset_currency: "Moeda",
    Logic_PresetDesc_currency: "Um valor monetário",
    Logic_Preset_percent: "Porcentagem",
    Logic_PresetDesc_percent: "Um valor percentual",
    Logic_Template_blank_Name: "Formulário em branco",
    Logic_Template_blank_Description: "Comece do zero",
    Logic_Template_feedback_Name: "Feedback do cliente",
    Logic_Template_feedback_Description: "NPS, avaliações e comentários abertos",
    Logic_Template_event_Name: "Inscrição em evento",
    Logic_Template_event_Description: "Dados do participante, sessões e necessidades alimentares",
    Logic_Template_itrequest_Name: "Solicitação de serviço de TI",
    Logic_Template_itrequest_Description: "Solicitações categorizadas com prioridade e anexos",
    Logic_Template_expense_Name: "Pedido de reembolso de despesas",
    Logic_Template_expense_Description: "Itens de linha, recibos e um total calculado",
    Logic_Template_pulse_Name: "Pesquisa rápida com funcionários",
    Logic_Template_pulse_Description: "Grade Likert, escala de engajamento e nota de anonimato",
    Logic_Template_safety_Name: "Inspeção de segurança",
    Logic_Template_safety_Description: "Lista de verificação, fotos e uma assinatura",
    Logic_Template_booking_Name: "Reserva de sala ou recurso",
    Logic_Template_booking_Description: "Seletor de recursos baseado em pesquisa, com horário",
    Charts_ColumnChartAria: "Gráfico de colunas com {count} categorias",
    Charts_DonutChartAria: "Gráfico de rosca de {count} categorias",
    Charts_NoAnswers: "Nenhuma resposta ainda.",
    Charts_NoResponses: "Nenhuma resposta ainda.",
    Charts_Responses: "Respostas",
    Charts_ResponsesOverTime: "Respostas ao longo do tempo",
    Responses_Chart_Answer: "Resposta",
    Responses_Chart_Average: "Média",
    Responses_Chart_AverageOf: "Média de {count}",
    Responses_Chart_AveragePosition: "Posição média",
    Responses_Chart_AverageRange: "Média (1–{max})",
    Responses_Chart_AvgValue: "méd. {value}",
    Responses_Chart_Detractors: "Detratores (0–6)",
    Responses_Chart_Max: "Máx.",
    Responses_Chart_Maximum: "Máximo",
    Responses_Chart_Median: "Mediana",
    Responses_Chart_MentionOne: "{count} menção",
    Responses_Chart_MentionOther: "{count} menções",
    Responses_Chart_Min: "Mín.",
    Responses_Chart_Minimum: "Mínimo",
    Responses_Chart_NoAnswers: "Nenhuma resposta ainda.",
    Responses_Chart_NoNumeric: "Nenhuma resposta numérica ainda.",
    Responses_Chart_NoRankings: "Nenhum ranking ainda.",
    Responses_Chart_NoScores: "Nenhuma pontuação ainda.",
    Responses_Chart_NotEnoughText: "Ainda não há texto suficiente para resumir.",
    Responses_Chart_NpsScore: "Pontuação NPS",
    Responses_Chart_Option: "Opção",
    Responses_Chart_Passives: "Neutros (7–8)",
    Responses_Chart_Promoters: "Promotores (9–10)",
    Responses_Chart_ResponseOne: "resposta",
    Responses_Chart_ResponseOther: "respostas",
    Responses_Chart_Responses: "Respostas",
    Responses_Chart_ShowingAnswers: "Mostrando {shown} de {total} respostas.",
    Responses_Chart_Statement: "Afirmação",
    Responses_Chart_Statistic: "Estatística",
    Responses_Chart_StdDev: "Desvio pad.",
    Responses_Chart_StdDeviation: "Desvio padrão",
    Responses_Chart_Total: "Total",
    Responses_Chart_Value: "Valor",
    Responses_Dashboard_AllHidden: "Todas as perguntas estão ocultas no painel. Use “Mostrar perguntas ocultas” para trazê-las de volta.",
    Responses_Dashboard_AnsweredOf: "{answered} de {total} respondidas",
    Responses_Dashboard_AnsweredOfPinned: "{answered} de {total} respondidas · fixada",
    Responses_Dashboard_AveragedAcrossResponses: "Média entre as respostas",
    Responses_Dashboard_ByDay: "Por dia",
    Responses_Dashboard_ByMonth: "Por mês",
    Responses_Dashboard_ByWeek: "Por semana",
    Responses_Dashboard_ChartAuto: "Automático",
    Responses_Dashboard_ChartBars: "Barras",
    Responses_Dashboard_ChartColumns: "Colunas",
    Responses_Dashboard_ChartDonut: "Rosca",
    Responses_Dashboard_ChartGauge: "Medidor",
    Responses_Dashboard_ChartHistogram: "Histograma",
    Responses_Dashboard_ChartOptions: "Opções do gráfico",
    Responses_Dashboard_ChartOptionsFor: "Opções do gráfico para {title}",
    Responses_Dashboard_ChartStatistics: "Estatísticas",
    Responses_Dashboard_ChartTable: "Tabela",
    Responses_Dashboard_ChartWordFrequency: "Frequência de palavras",
    Responses_Dashboard_EmptyBody: "Assim que as pessoas começarem a responder, este painel é preenchido automaticamente — números principais, uma linha do tempo de respostas e um gráfico para as perguntas que vale acompanhar.",
    Responses_Dashboard_EmptyTitle: "Nenhuma resposta ainda",
    Responses_Dashboard_Hide: "Ocultar do painel",
    Responses_Dashboard_Highlights: "Destaques",
    Responses_Dashboard_Last7Days: "Últimos 7 dias",
    Responses_Dashboard_LatestDate: "Mais recente: {date}",
    Responses_Dashboard_MedianTimeToComplete: "Tempo mediano para concluir",
    Responses_Dashboard_NoPriorWeek: "Sem semana anterior para comparar",
    Responses_Dashboard_OneEach: "Uma cada",
    Responses_Dashboard_Pin: "Fixar no painel",
    Responses_Dashboard_QuestionFallback: "pergunta",
    Responses_Dashboard_QuestionsAnswered: "Perguntas respondidas",
    Responses_Dashboard_RecordedOnSubmit: "Registrado no envio",
    Responses_Dashboard_RepeatResponses: "{count} respostas repetidas",
    Responses_Dashboard_ResponsesOverTime: "Respostas ao longo do tempo",
    Responses_Dashboard_ShowHidden: "Mostrar perguntas ocultas",
    Responses_Dashboard_SinceMidnight: "Desde a meia-noite",
    Responses_Dashboard_Today: "Hoje",
    Responses_Dashboard_TotalResponses: "Total de respostas",
    Responses_Dashboard_UniqueRespondents: "Respondentes únicos",
    Responses_Dashboard_Unpin: "Desafixar do painel",
    Responses_Dashboard_UntitledQuestion: "Pergunta sem título",
    Responses_Dashboard_VsPrevious7Days: "vs. 7 dias anteriores",
    Responses_Detail_Answers: "Respostas",
    Responses_Detail_AsTheForm: "Como no formulário",
    Responses_Detail_Cancel: "Cancelar",
    Responses_Detail_Delete: "Excluir",
    Responses_Detail_DeleteBody: "O item da lista é movido para a lixeira do site e pode ser restaurado de lá.",
    Responses_Detail_DeleteTitle: "Excluir esta resposta?",
    Responses_Detail_Deleting: "Excluindo…",
    Responses_Detail_Draft: "Rascunho",
    Responses_Detail_Header: "Resposta {index} de {total}",
    Responses_Detail_LoadingAttachments: "Carregando anexos…",
    Responses_Detail_Next: "Próxima resposta",
    Responses_Detail_NoAnswer: "Sem resposta",
    Responses_Detail_Previous: "Resposta anterior",
    Responses_Detail_Print: "Imprimir",
    Responses_Detail_Signature: "Assinatura",
    Responses_Detail_Signed: "Assinado",
    Responses_Detail_Took: "levou {duration}",
    Responses_Summary_AnsweredOfType: "{answered} de {total} respondidas · {type}",
    Responses_Summary_ByField: "Por {title}",
    Responses_Summary_CompareBy: "Comparar por…",
    Responses_Summary_EmptyBody: "Cada pergunta terá seu próprio resumo aqui.",
    Responses_Summary_NoComparison: "Sem comparação",
    Responses_Summary_NothingToCompare: "Nenhuma resposta respondeu “{title}”, então não há nada para comparar.",
    Responses_Summary_OtherNote: "Gráficos com mais de {max} categorias agrupam as menores em “Outro” — mude um cartão para Tabela para ver todos os valores.",
    Responses_Summary_ResponseCountOne: "{count} resposta",
    Responses_Summary_ResponseCountOther: "{count} respostas",
    Responses_Summary_SeeAllAnswers: "Ver todas as respostas na tabela",
    Responses_Summary_SegmentNote: "Mostrando os {groups} maiores grupos. Uma resposta que selecionou várias opções aparece em todos os grupos correspondentes, então os totais dos grupos podem somar mais que {total}.",
    Responses_Summary_SplitBy: "Dividir por {title}",
    Responses_Summary_Untitled: "sem título",
    Responses_Table_Apply: "Aplicar",
    Responses_Table_Cancel: "Cancelar",
    Responses_Table_ClearSelection: "Limpar seleção",
    Responses_Table_ColumnOrder: "Ordem das colunas",
    Responses_Table_ColumnsCount: "Colunas ({shown}/{total})",
    Responses_Table_Delete: "Excluir",
    Responses_Table_DeleteBody: "Os itens da lista são movidos para a lixeira do site e podem ser restaurados de lá.",
    Responses_Table_DeleteSelected: "Excluir selecionadas",
    Responses_Table_DeleteTitleOne: "Excluir {count} resposta?",
    Responses_Table_DeleteTitleOther: "Excluir {count} respostas?",
    Responses_Table_Deleting: "Excluindo…",
    Responses_Table_MoveDown: "Mover para baixo",
    Responses_Table_MoveDownFor: "Mover {title} para baixo",
    Responses_Table_MoveUp: "Mover para cima",
    Responses_Table_MoveUpFor: "Mover {title} para cima",
    Responses_Table_NoColumns: "Nenhuma coluna de pergunta está visível ainda.",
    Responses_Table_NoMatch: "Nenhuma resposta corresponde aos filtros atuais.",
    Responses_Table_NothingToShow: "Nada para mostrar",
    Responses_Table_OpenResponse: "Abrir esta resposta",
    Responses_Table_OrderNote: "Enviado e Enviado por sempre vêm primeiro. A ordem de arrastar se aplica às colunas de perguntas.",
    Responses_Table_Reorder: "Reordenar",
    Responses_Table_ResetColumns: "Redefinir colunas",
    Responses_Table_SelectResponse: "Selecionar esta resposta",
    Responses_Table_SelectedOne: "{count} resposta selecionada",
    Responses_Table_SelectedOther: "{count} respostas selecionadas",
    Responses_Table_ShowAll: "Mostrar tudo",
    Responses_Table_ShowTheseQuestions: "Mostrar estas perguntas",
    Responses_Table_Submitted: "Enviado",
    Responses_Table_SubmittedBy: "Enviado por",
    Responses_Table_ToggleSelection: "Alternar seleção",
    Responses_Table_Unknown: "Desconhecido",
    Responses_Table_Untitled: "Sem título",
    Responses_View_AllTime: "Todo o período",
    Responses_View_AnyAnswer: "Qualquer resposta",
    Responses_View_Clear: "Limpar",
    Responses_View_CopyShareLink: "Copiar link de compartilhamento",
    Responses_View_CountFiltered: "{shown} de {total} respostas",
    Responses_View_CountOne: "{count} resposta",
    Responses_View_CountOther: "{count} respostas",
    Responses_View_Dashboard: "Painel",
    Responses_View_DateRange: "Intervalo de datas",
    Responses_View_EmptyBody: "Compartilhe o formulário para começar a coletar. As respostas são salvas em “{list}” e aparecem aqui imediatamente.",
    Responses_View_EmptyTitle: "Nenhuma resposta ainda",
    Responses_View_ExportCsv: "Exportar CSV",
    Responses_View_FilterByAnswer: "Filtrar por resposta",
    Responses_View_FilterByQuestion: "Filtrar por pergunta",
    Responses_View_FilterValue: "Valor do filtro",
    Responses_View_Last30Days: "Últimos 30 dias",
    Responses_View_Last7Days: "Últimos 7 dias",
    Responses_View_Last90Days: "Últimos 90 dias",
    Responses_View_LoadError: "Não foi possível carregar as respostas. Publique o formulário uma vez para que as colunas da lista existam e tente novamente.",
    Responses_View_Loading: "Carregando respostas…",
    Responses_View_MoreActions: "Mais ações de resposta",
    Responses_View_PreviewForm: "Visualizar o formulário",
    Responses_View_Refresh: "Atualizar",
    Responses_View_ResponsesTab: "Respostas ({count})",
    Responses_View_SearchPlaceholder: "Pesquisar em todas as respostas",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Selecione um valor",
    Responses_View_Summary: "Resumo",
    Responses_View_Today: "Hoje",
    Responses_View_Truncated: "Esta lista tem mais respostas do que o Smart Forms carrega de uma vez. As {count} mais recentes são mostradas — abra a lista no Microsoft Lists para ver o conjunto completo.",
    Responses_View_TryAgain: "Tentar novamente",
    Responses_View_Untitled: "Sem título",
    Responses_Approval_Column: "Aprovação",
    Responses_Approval_ReviewerColumn: "Revisado por",
    Responses_Approval_CommentColumn: "Comentário do revisor",
    Responses_Approval_Pending: "Pendente",
    Responses_Approval_Approved: "Aprovada",
    Responses_Approval_Rejected: "Rejeitada",
    Responses_Approval_AnyStatus: "Qualquer status de aprovação",
    Responses_Approval_FilterLabel: "Filtrar por status de aprovação",
    Responses_Approval_ApproveSelected: "Aprovar selecionadas",
    Responses_Approval_RejectSelected: "Rejeitar selecionadas",
    Responses_Approval_BulkFailed: "Não foi possível atualizar {count} respostas. Tente novamente.",
    Responses_Approval_Approve: "Aprovar",
    Responses_Approval_Reject: "Rejeitar",
    Responses_Approval_Reset: "Redefinir para pendente",
    Responses_Approval_CommentLabel: "Comentário (opcional)",
    Responses_Approval_ReviewedBy: "Revisado por {name}",
    Responses_Approval_Error: "Não foi possível salvar a decisão. Tente novamente.",
    Responses_Dashboard_ApprovalStatus: "Aguardando revisão",
    Responses_Dashboard_ApprovalBreakdown: "{pending} pendentes, {approved} aprovadas, {rejected} rejeitadas",
    Responses_Dashboard_TimelineCoarsened: "O intervalo de datas é longo, então a linha do tempo foi agrupada de forma mais ampla ({grain}).",
    Responses_Dashboard_TimelineTruncated: "O intervalo de datas é muito longo, então somente os {count} períodos mais recentes são mostrados.",
    Service_Item_DefaultTitle: "Resposta — {date}",
    Service_Email_ApprovalSubject: "Sua resposta foi {status} — {title}",
    Service_Email_ApprovalHeading: "Sua resposta foi {status}",
    Service_Email_ApprovalIntro: "Um revisor marcou sua resposta a \"{title}\" como {status}.",
    Service_Email_ApprovalCommentLabel: "Comentário do revisor",
    Service_Approval_Approved: "aprovada",
    Service_Approval_Rejected: "rejeitada",
    Service_Approval_Pending: "pendente",
    Service_Lookup_InvalidFilter: "O filtro de pesquisa não é válido.",
    Service_Edit_NotAllowed: "Este formulário não permite editar uma resposta enviada.",
    Service_Edit_NotYours: "Você só pode editar sua própria resposta.",
    Service_Signature_AttachmentLabel: "Assinatura",
    PropertyPane_ListsLoadFailed: "Não foi possível carregar as listas deste site.",
    PropertyPane_EnterListName: "Insira primeiro um nome para a nova lista.",
    PropertyPane_CreatingList: "Criando \"{name}\"…",
    PropertyPane_ListCreated: "Lista \"{title}\" criada e selecionada.",
    PropertyPane_ListAlreadyExists: "Já existe uma lista chamada \"{name}\" — selecione-a na lista suspensa acima.",
    PropertyPane_CreateListFailed: "Não foi possível criar a lista. Verifique se você tem permissão para criar listas neste site.",
    PropertyPane_Description: "Escolha a lista do SharePoint que armazena as respostas do formulário ou crie uma nova. Todo o resto — perguntas, aparência, notificações — é editado diretamente na página.",
    PropertyPane_ResponseList_GroupName: "Lista de respostas",
    PropertyPane_ListDropdown_Label: "Salvar respostas nesta lista",
    PropertyPane_ResponsesGoTo: "As respostas vão para \"{name}\".",
    PropertyPane_PickList: "Escolha uma lista ou crie uma abaixo.",
    PropertyPane_LoadingLists: "Carregando listas…",
    PropertyPane_NewListName_Label: "Ou crie uma nova lista",
    PropertyPane_NewListName_Placeholder: "Nome da nova lista",
    PropertyPane_CreateList_Button: "Criar lista",
    PropertyPane_Tips_GroupName: "Dicas",
    PropertyPane_Tip_AutoSave: "Perguntas e configurações são salvas automaticamente à medida que você as edita — não é preciso salvar nem publicar a página.",
    PropertyPane_Tip_Permissions: "Os respondentes precisam de permissão para adicionar itens à lista de respostas. Verifique as permissões da lista se alguém relatar um erro ao enviar.",
    PropertyPane_Tip_Share: "Use \"Coletar respostas\" na página para criar as colunas da lista e obter um link de preenchimento compartilhável.",
    App_ErrorBoundary_Title: "Smart Forms — Erro de renderização",
    App_ErrorBoundary_Message: "Mensagem:",
    App_ErrorBoundary_Stack: "Pilha:",
    App_ErrorBoundary_NoStack: "(nenhuma pilha disponível)",
    App_ErrorBoundary_ConsoleNote: "Os detalhes completos também foram gravados no console do navegador.",
    App_DefaultQuestionTitle: "Pergunta {number}",
    App_Error_ListMissing: "A lista configurada para este formulário não existe mais. Escolha outra lista nas configurações do web part.",
    App_Error_LoadConfig: "Algo deu errado ao carregar a configuração do formulário.",
    App_Error_Unable: "Não foi possível carregar o formulário.",
    App_Publish_ConflictNotice: "\"{title}\" já tem uma coluna de lista de outro tipo ({type}). Renomeie a pergunta para que uma nova coluna possa ser criada ou volte o tipo dela.",
    App_Publish_ConflictUnnamedQuestion: "uma pergunta",
    App_Publish_ColumnsAddedOne: "{count} coluna foi adicionada a \"{list}\".",
    App_Publish_ColumnsAddedOther: "{count} colunas foram adicionadas a \"{list}\".",
    App_Publish_TheList: "a lista",
    App_Publish_UpToDate: "A lista de respostas já está atualizada.",
    App_Publish_Error: "Não foi possível criar as colunas da lista. Isso geralmente significa que você não tem a permissão Gerenciar Listas na lista de respostas, mas também pode acontecer em sites com scripts personalizados desabilitados. Verifique o console do navegador para ver o erro subjacente ou tente novamente.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Crie um formulário elegante sobre uma lista do SharePoint — {count} tipos de pergunta, lógica de ramificação, upload de arquivos, links de preenchimento compartilháveis e um painel de resultados.",
    App_Placeholder_ChooseList: "Escolher ou criar uma lista",
    App_Placeholder_Hint: "Edite a página e configure este web part para começar.",
    App_Loading: "Carregando formulário…",
    App_OpenSettings: "Abrir configurações",
    App_Tab_Questions: "Perguntas",
    App_Tab_QuestionsWithCount: "Perguntas ({count})",
    App_Tab_Responses: "Respostas",
    App_Tab_Responses_Title: "As respostas são salvas em \"{list}\"",
    App_Templates_Start: "Começar de um modelo",
    App_Settings_Title: "Configurações do formulário — aparência, notificações, acesso",
    App_Settings_AriaLabel: "Configurações do formulário",
    App_Preview: "Visualizar",
    App_Preview_Close: "Fechar visualização",
    App_Preview_Hint: "Visualização — nada do que você enviar aqui é salvo. A validação e a ramificação se comportam exatamente como para os respondentes.",
    App_Publish_GettingReady: "Preparando…",
    App_Publish_CollectResponses: "Coletar respostas",
    App_Publish_Share: "Compartilhar",
    App_Retry: "Tentar novamente",
    App_SaveError_Banner: "Não foi possível salvar sua última alteração. Verifique sua conexão e tente novamente.",
    App_Preflight_BlockingTitle: "Corrija isto antes de coletar",
    App_Preflight_WarningTitle: "Vale a pena conferir antes",
    App_Preflight_BlockingText: "Isto impediria o formulário publicado de funcionar corretamente.",
    App_Preflight_WarningText: "Nada está quebrado, mas geralmente vale a pena corrigir isto antes de compartilhar o link.",
    App_Preflight_GoTo: "Ir para",
    App_Preflight_CollectAnyway: "Coletar respostas mesmo assim",
    App_Preflight_Back: "Voltar ao formulário",
    App_Cancel: "Cancelar",
    App_Done: "Concluído",
    App_Share_Title: "Seu formulário está pronto para compartilhar",
    App_Share_SubText: "Envie este link para quem deve preencher o formulário.",
    App_Share_LinkAriaLabel: "Link de compartilhamento",
    App_Share_Copy: "Copiar",
    App_Share_Copied: "Copiado",
    App_Share_AddItemsEmphasis: "adicionar itens",
    App_Share_PermissionNote: "Os respondentes precisam de permissão para {addItems} a “{title}” e de acesso a esta página. Se alguém receber um erro ao enviar, quase sempre é por isso.",
    App_Share_PrefillNote: "Você pode pré-responder perguntas no link adicionando o nome da coluna, por exemplo {example}.",
    App_Templates_ReplaceWarning: "Escolher um modelo substitui as perguntas atuais.",
    App_Templates_PickStart: "Escolha um ponto de partida — você pode alterar qualquer coisa depois.",
    App_Templates_Empty: "Vazio",
    App_Templates_QuestionCount: "{count} perguntas",
    App_SaveChip_SavingTitle: "Salvando sua última edição",
    App_SaveChip_Saving: "Salvando…",
    App_SaveChip_FailedTitle: "Não foi possível salvar sua última edição. Verifique sua conexão e tente novamente.",
    App_SaveChip_Failed: "Falha ao salvar",
    App_SaveChip_SavedTitle: "Todas as alterações foram salvas",
    App_SaveChip_Saved: "Salvo",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Nova resposta — {title}",
    Service_Email_NewResponseHeading: "Nova resposta: {title}",
    Service_Email_NewResponseIntro: "Alguém acabou de enviar uma resposta — {date}.",
    Service_Email_ReceiptSubject: "Sua resposta — {title}",
    Service_Email_ReceiptHeading: "Obrigado pela sua resposta!",
    Service_Email_ReceiptIntro: "Esta é uma cópia do que você enviou para \"{title}\".",
    App_History_Title: "Histórico de versões",
    App_History_RestoredNotice: "Versão salva em {date} restaurada. Revise-a e use Coletar respostas para publicar novas perguntas.",
    App_History_Undo: "Desfazer restauração",
    App_Share_CopyManual: "Seu navegador bloqueou a cópia. Selecione o link acima e pressione Ctrl+C (Cmd+C no Mac) para copiá-lo.",
    App_Share_TeamsNote: "Você está no Microsoft Teams. Este link abre a página do SharePoint diretamente, portanto os destinatários precisam de acesso ao site.",
    App_Share_PrefillNotSecure: "As respostas preenchidas previamente são apenas uma conveniência: qualquer pessoa com o link pode alterá-las, portanto nunca as trate como um limite de segurança.",
    Designer_Section_DropHere: "Solte uma pergunta aqui",
    Designer_Section_DropEnd: "Solte aqui para mover para o final desta seção",
    Designer_Rules_RemovedOne: "1 regra de ramificação que não se aplicava mais foi removida.",
    Designer_Rules_RemovedOther: "{count} regras de ramificação que não se aplicavam mais foram removidas.",
    Designer_Settings_AllowEdit: "Permitir que os respondentes editem sua resposta",
    Designer_Settings_AllowEditHint: "Os respondentes podem reabrir e atualizar o que enviaram. Cada pessoa pode editar somente a própria resposta.",
    Designer_Settings_EnableApproval: "Ativar fluxo de aprovação",
    Designer_Settings_ApprovalNotify: "Enviar email ao respondente sobre a decisão",
    Designer_Settings_ApprovalHint: "Adiciona colunas de aprovação à lista de respostas na próxima vez que você publicar. Os proprietários aprovam ou rejeitam as respostas na guia Respostas.",
    Designer_History_Title: "Histórico de versões",
    Designer_History_Intro: "Versões salvas anteriormente das perguntas e configurações deste formulário. Restaurar carrega uma versão no designer; você pode desfazer, e novas perguntas só são criadas quando você publica.",
    Designer_History_Loading: "Carregando versões...",
    Designer_History_Empty: "Nenhuma versão anterior encontrada. O histórico de versões requer que o controle de versão esteja ativado na lista \"Smart Forms Config\" e pelo menos uma edição salva.",
    Designer_History_Latest: "Mais recente",
    Designer_History_LatestTitle: "Esta é a versão em uso no momento",
    Designer_History_By: "por {name}",
    Designer_History_UnknownAuthor: "Autor desconhecido",
    Designer_History_VersionLabel: "versão {label}",
    Designer_History_Preview: "Visualizar",
    Designer_History_Restore: "Restaurar",
    Designer_History_QuestionsOne: "1 pergunta",
    Designer_History_QuestionsOther: "{count} perguntas",
    Designer_History_LoadFailed: "Não foi possível carregar esta versão.",
    Designer_History_ConfirmTitle: "Restaurar esta versão?",
    Designer_History_ConfirmText: "O formulário será substituído pela versão salva em {date} ({count} perguntas). Você pode desfazer logo em seguida."
  };
});
