define([], function () {
  return {
    Designer_Color_Blue: "Albastru",
    Designer_Color_Teal: "Turcoaz",
    Designer_Color_Green: "Verde",
    Designer_Color_Purple: "Violet",
    Designer_Color_Magenta: "Magenta",
    Designer_Color_Red: "Roșu",
    Designer_Color_Orange: "Portocaliu",
    Designer_Color_Gray: "Gri",
    Designer_Settings_LayoutSinglePage: "Toate întrebările pe o singură pagină",
    Designer_Settings_LayoutWizard: "O secțiune pe pas (expert)",
    Designer_Settings_Title: "Setări formular",
    Designer_Common_Apply: "Aplicare",
    Designer_Common_Cancel: "Anulare",
    Designer_Settings_TabBasics: "Noțiuni de bază",
    Designer_Settings_FormTitle: "Titlul formularului",
    Designer_Settings_Description: "Descriere",
    Designer_Settings_Layout: "Aspect",
    Designer_Settings_NumberQuestions: "Numerotează întrebările",
    Designer_Settings_ShuffleQuestions: "Amestecă ordinea întrebărilor pentru fiecare respondent",
    Designer_Settings_ShowProgressBar: "Afișează o bară de progres",
    Designer_Settings_TabAppearance: "Aspect vizual",
    Designer_Settings_AccentColor: "Culoare de accent",
    Designer_Settings_CustomColorTitle: "Culoare personalizată",
    Designer_Settings_CustomColorAria: "Culoare de accent personalizată",
    Designer_Settings_AccentHint: "Culorile de accent sunt ajustate automat pentru contrast pe site-urile întunecate, astfel încât formularul rămâne lizibil indiferent de tema paginii.",
    Designer_Settings_ShowHeader: "Afișează antetul formularului",
    Designer_Settings_HeaderIcon: "Pictogramă antet",
    Designer_Settings_TabAfterSubmit: "După trimitere",
    Designer_Settings_SubmitButtonText: "Textul butonului Trimitere",
    Designer_Settings_SubmitPlaceholder: "Trimitere",
    Designer_Settings_ThankYouTitle: "Titlu de mulțumire",
    Designer_Settings_ThankYouPlaceholder: "Vă mulțumim!",
    Designer_Settings_ThankYouMessage: "Mesaj de mulțumire",
    Designer_Settings_ShowSubmitAnother: "Afișează un buton „Trimite un alt răspuns”",
    Designer_Settings_TabNotifications: "Notificări",
    Designer_Settings_EmailEachResponseTo: "Trimite fiecare răspuns prin e-mail către",
    Designer_Settings_EmailPlaceholder: "nume@companie.com; echipa@companie.com",
    Designer_Settings_EmailDescription: "Persoanele din organizația dvs. primesc fiecare răspuns prin e-mail, cu un link către elementul din listă",
    Designer_Settings_RespondentReceipt: "Trimite respondenților prin e-mail o copie a răspunsurilor lor",
    Designer_Settings_NotificationsInfo: "Notificările folosesc serviciul de e-mail propriu al SharePoint, deci destinatarii trebuie să fie utilizatori din organizația dvs. Adresele externe sunt ignorate în tăcere.",
    Designer_Settings_TabAccess: "Acces",
    Designer_Settings_OpenFrom: "Deschide de la",
    Designer_Settings_OpenImmediately: "Deschide imediat",
    Designer_Settings_CloseAfter: "Închide după",
    Designer_Settings_NeverClose: "Nu se închide niciodată",
    Designer_Settings_ClearDates: "Șterge datele",
    Designer_Settings_DatesInverted: "Data de închidere este egală cu sau anterioară datei de deschidere, deci formularul nu ar accepta niciodată răspunsuri.",
    Designer_Settings_MaxResponses: "Oprește după acest număr de răspunsuri",
    Designer_Settings_NoLimit: "Fără limită",
    Designer_Settings_OneResponsePerPerson: "Permite un singur răspuns per persoană",
    Designer_Settings_AllowSaveDraft: "Permite respondenților să salveze o ciornă și să o finalizeze mai târziu",
    Designer_Settings_ClosedMessage: "Mesaj afișat când formularul este închis",
    Designer_Settings_ClosedMessagePlaceholder: "Acest formular nu mai acceptă răspunsuri.",
    Designer_Settings_AccessInfo: "Aceste limite sunt aplicate de formular, nu de SharePoint. Oricine are permisiunea de a adăuga elemente în lista de răspunsuri ar putea totuși să adauge unul direct prin listă.",
    Designer_Field_StyleInfo: "Informații (accent)",
    Designer_Field_StyleSuccess: "Succes (verde)",
    Designer_Field_StyleWarning: "Avertisment (chihlimbar)",
    Designer_Field_StylePlain: "Text simplu",
    Designer_Field_StyleDivider: "Linie de separare",
    Designer_Field_IconStars: "Stele",
    Designer_Field_IconHearts: "Inimi",
    Designer_Field_IconThumbs: "Degete mari în sus",
    Designer_Field_FormatPlain: "Număr simplu",
    Designer_Field_FormatCurrency: "Monedă",
    Designer_Field_FormatPercent: "Procent",
    Designer_Field_UntitledQuestion: "Întrebare fără titlu",
    Designer_Field_DeletedQuestion: "o întrebare ștearsă",
    Designer_Rule_Unary: "„{name}” {operator}",
    Designer_Rule_Between: "„{name}” {operator} {value} și {value2}",
    Designer_Rule_Binary: "„{name}” {operator} „{value}”",
    Designer_Rule_JoinAny: "SAU",
    Designer_Rule_JoinAll: "ȘI",
    Designer_Rule_Preview: "Afișată când {conditions}.",
    Designer_Field_Yes: "Da",
    Designer_Field_No: "Nu",
    Designer_Field_When: "Când",
    Designer_Field_SelectValue: "Selectați o valoare",
    Designer_Field_DateValuePlaceholder: "AAAA-LL-ZZ sau \"today\"",
    Designer_Field_ValuePlaceholder: "Valoare",
    Designer_Field_UpperBound: "Limită superioară",
    Designer_Field_RemoveCondition: "Elimină această condiție",
    Designer_Field_FormulaInvalid: "Această formulă nu poate fi calculată. Verificați parantezele și operatorii.",
    Designer_Field_FormulaMissing: "Aceste întrebări nu există: {names}.",
    Designer_Field_FormulaPreview: "Cu toate intrările egale cu 10, se afișează {value}.",
    Designer_Field_HintYesNo: "Folosiți \"yes\" sau \"no\"",
    Designer_Field_HintMultiDefault: "Separați mai multe valori implicite cu ;",
    Designer_Field_HintSingleDefault: "Trebuie să corespundă uneia dintre opțiuni",
    Designer_Field_HintDate: "Folosiți \"today\" sau o dată precum 2026-03-01",
    Designer_Field_HintTime: "Folosiți \"now\" sau o oră precum 09:30",
    Designer_Field_QuestionSettings: "Setări întrebare",
    Designer_Field_Appearance: "Aspect vizual",
    Designer_Field_Style: "Stil",
    Designer_Field_ImageUrl: "Adresă URL imagine (opțional)",
    Designer_Field_Content: "Conținut",
    Designer_Field_BasicFormatting: "Este permisă formatarea de bază: aldin, cursiv, liste și linkuri.",
    Designer_Field_TabOptions: "Opțiuni",
    Designer_Field_TabBranching: "Ramificare",
    Designer_Field_BranchingNeedsQuestion: "Adăugați mai întâi o altă întrebare — ramificarea are nevoie de ceva de care să depindă.",
    Designer_Field_BranchingToggle: "Afișează această întrebare doar când alte răspunsuri se potrivesc",
    Designer_Field_Match: "Potrivire",
    Designer_Field_MatchAll: "toate acestea",
    Designer_Field_MatchAny: "oricare dintre acestea",
    Designer_Field_AddCondition: "Adaugă condiție",
    Designer_Field_TabValidation: "Validare",
    Designer_Field_HelpText: "Text de ajutor",
    Designer_Field_HelpTextPlaceholder: "Afișat sub eticheta întrebării",
    Designer_Field_CheckboxLabel: "Eticheta casetei de selectare",
    Designer_Field_Placeholder: "Text substituent",
    Designer_Field_DefaultAnswer: "Răspuns implicit",
    Designer_Field_RequiredMessage: "Mesaj personalizat pentru câmp obligatoriu",
    Designer_Field_RequiredMessagePlaceholder: "{title} este obligatoriu",
    Designer_Field_ThisQuestion: "Această întrebare",
    Designer_Field_RequiredMessageDescription: "Afișat în locul mesajului standard când această întrebare este lăsată necompletată",
    Designer_Field_ReadOnly: "Numai în citire (răspunsul poate proveni doar dintr-un link precompletat)",
    Designer_Field_ValidationRules: "Reguli de validare",
    Designer_Field_MaxLength: "Lungime maximă",
    Designer_Field_Pattern: "Trebuie să corespundă acestui model",
    Designer_Field_PatternDescription: "O expresie regulată. Lăsați necompletat pentru a nu verifica modelul.",
    Designer_Field_PatternMessage: "Mesaj când modelul nu corespunde",
    Designer_Field_PatternMessagePlaceholder: "Acest răspuns nu are formatul așteptat",
    Designer_Field_Format: "Format",
    Designer_Field_UnitSuffix: "Unitate afișată după valoare",
    Designer_Field_UnitSuffixPlaceholder: "kg, ore, articole…",
    Designer_Field_Minimum: "Minim",
    Designer_Field_Maximum: "Maxim",
    Designer_Field_Decimals: "Zecimale",
    Designer_Field_Formula: "Formulă",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Faceți referire la alte întrebări prin textul lor între acolade. Acceptă + - * / ( ) și round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Întrebări disponibile: {questions}",
    Designer_Field_NoneYet: "încă niciuna",
    Designer_Field_Step: "Pas",
    Designer_Field_From: "De la",
    Designer_Field_To: "Până la",
    Designer_Field_LowLabel: "Etichetă pentru capătul inferior",
    Designer_Field_LowLabelPlaceholder: "Deloc probabil",
    Designer_Field_HighLabel: "Etichetă pentru capătul superior",
    Designer_Field_HighLabelPlaceholder: "Extrem de probabil",
    Designer_Field_SummarizeAs: "Rezumă ca",
    Designer_Field_SummarizeAverage: "Medie și distribuție",
    Designer_Field_SummarizeNps: "Net Promoter Score (necesită o scală 0–10)",
    Designer_Field_NpsWarning: "Net Promoter Score are sens doar pe o scală 0–10. Setați De la la 0 și Până la la 10.",
    Designer_Field_NumberOfIcons: "Număr de pictograme",
    Designer_Field_Icon: "Pictogramă",
    Designer_Field_AllowHalf: "Permite jumătăți de valoare",
    Designer_Field_ShowOptionsAs: "Afișează opțiunile ca",
    Designer_Field_DisplayButtons: "Butoane în linie",
    Designer_Field_DisplayDropdown: "Listă verticală",
    Designer_Field_DisplayAutomatic: "Automat (în linie până la 6 opțiuni)",
    Designer_Field_AllowOther: "Adaugă o opțiune „Altele” cu text liber",
    Designer_Field_OtherLabel: "Eticheta opțiunii „Altele”",
    Designer_Field_OtherPlaceholder: "Altele",
    Designer_Field_ShuffleOptions: "Amestecă ordinea opțiunilor pentru fiecare respondent",
    Designer_Field_MinSelections: "Selecții minime",
    Designer_Field_MaxSelections: "Selecții maxime",
    Designer_Field_SourceList: "Listă sursă",
    Designer_Field_ChooseList: "Alegeți o listă",
    Designer_Field_LookupColumn: "Coloana din care se citesc opțiunile",
    Designer_Field_ChooseColumn: "Alegeți o coloană",
    Designer_Field_ChooseListFirst: "Alegeți mai întâi o listă",
    Designer_Field_LookupFilter: "Filtru (opțional)",
    Designer_Field_LookupFilterDescription: "Un filtru OData care restrânge elementele sursă ce devin opțiuni",
    Designer_Field_LookupInfo: "Răspunsurile stochează textul opțiunii, nu un link către elementul sursă, astfel încât rămân lizibile chiar dacă lista sursă se modifică ulterior.",
    Designer_Field_ConsentText: "Termeni afișați deasupra casetei de selectare",
    Designer_Field_AllowMultiplePeople: "Permite mai multe persoane",
    Designer_Field_AllowGroups: "Permite și grupuri",
    Designer_Field_IncludeTime: "Include o oră din zi",
    Designer_Field_TimeStep: "Interval de timp (minute)",
    Designer_Field_MaxFiles: "Număr maxim de fișiere",
    Designer_Field_MaxFileSize: "Dimensiune maximă per fișier (MB)",
    Designer_Field_AcceptedTypes: "Tipuri de fișiere acceptate",
    Designer_Field_AcceptedTypesDescription: "Extensii separate prin virgulă. Lăsați necompletat pentru a accepta orice permite SharePoint.",
    Designer_Field_FilesInfo: "Fișierele sunt salvate ca atașamente la elementul de răspuns. SharePoint blochează unele extensii (precum .exe) indiferent de ce permiteți aici.",
    Designer_Field_Rows: "Rânduri",
    Designer_Field_ProvisionedNote: "Această întrebare are deja o coloană în listă ({name}). Setările care modifică tipul coloanei sunt blocate — duplicați întrebarea dacă aveți nevoie de un alt tip.",
    Designer_Category_Text: "Text",
    Designer_Category_Choice: "Alegere",
    Designer_Category_Scales: "Scale",
    Designer_Category_Date: "Dată",
    Designer_Category_People: "Persoane",
    Designer_Category_Advanced: "Avansat",
    Designer_Category_Layout: "Aspect",
    Designer_Menu_CommonPresets: "Presetări uzuale",
    Designer_Menu_AllTypes: "Toate tipurile de întrebări",
    Designer_Menu_ChangeType: "Schimbă tipul",
    Designer_Menu_TypeLockedTitle: "Coloana din listă există deja, deci tipul este blocat. Duplicați întrebarea pentru a-l schimba.",
    Designer_Menu_MoreSettings: "Ramificare, validare și altele",
    Designer_Menu_InsertBelow: "Inserează întrebare dedesubt",
    Designer_Card_Duplicate: "Duplică",
    Designer_Card_DeleteQuestion: "Șterge întrebarea",
    Designer_Outline_Aria: "Schița întrebărilor",
    Designer_Outline_QuestionCountOne: "{count} întrebare",
    Designer_Outline_QuestionCountOther: "{count} întrebări",
    Designer_Outline_IssuesTitle: "{count} problemă/probleme de revizuit",
    Designer_Outline_Find: "Găsiți o întrebare",
    Designer_Outline_Empty: "Nu există încă întrebări.",
    Designer_Section_DefaultTitle: "Secțiunea {number}",
    Designer_Card_Question: "Întrebare",
    Designer_Card_BranchingTitle: "Această întrebare apare doar când o regulă de ramificare este îndeplinită",
    Designer_Card_BranchingChip: "Ramificare",
    Designer_Card_LiveTitle: "Coloana din listă există, deci tipul este blocat",
    Designer_Card_LiveChip: "Activă",
    Designer_Card_CheckChip: "Verificare",
    Designer_Option_Placeholder: "Opțiunea {number}",
    Designer_Option_LabelAria: "Eticheta opțiunii {number}",
    Designer_Option_ImageUrl: "Adresă URL imagine",
    Designer_Option_ImageUrlAria: "Adresa URL a imaginii pentru opțiunea {number}",
    Designer_Option_Remove: "Elimină opțiunea",
    Designer_Option_RemoveAria: "Elimină opțiunea {number}",
    Designer_Option_Add: "Adaugă opțiune",
    Designer_Option_OtherHint: "Respondenții pot scrie și un răspuns cu eticheta „{label}”.",
    Designer_Option_OtherFallback: "Altele",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Elimină",
    Designer_Grid_RemoveAria: "Elimină {label} {number}",
    Designer_Grid_Statements: "Afirmații",
    Designer_Grid_Scale: "Scală",
    Designer_Grid_AddStatement: "Adaugă afirmație",
    Designer_Grid_AddScale: "Adaugă scală",
    Designer_Width_Full: "Lățime completă",
    Designer_Width_Half: "Jumătate de lățime",
    Designer_Width_Third: "O treime din lățime",
    Designer_Width_Aria: "Lățimea întrebării",
    Designer_Card_BlockLabelPlaceholder: "Eticheta blocului (nu se afișează respondenților)",
    Designer_Card_QuestionText: "Textul întrebării",
    Designer_Card_MoveUp: "Mută în sus",
    Designer_Card_MoveQuestionUp: "Mută întrebarea în sus",
    Designer_Card_MoveDown: "Mută în jos",
    Designer_Card_MoveQuestionDown: "Mută întrebarea în jos",
    Designer_Card_DuplicateQuestion: "Duplică întrebarea",
    Designer_Card_MultipleAnswers: "Răspunsuri multiple",
    Designer_Card_Required: "Obligatorie",
    Designer_Card_MoreOptions: "Mai multe opțiuni",
    Designer_Card_MoreOptionsAria: "Mai multe opțiuni pentru această întrebare",
    Designer_Canvas_FormTitle: "Titlul formularului",
    Designer_Canvas_DescriptionPlaceholder: "Adăugați o descriere (opțional)",
    Designer_Canvas_DescriptionAria: "Descrierea formularului",
    Designer_Canvas_EmptyTitle: "Adăugați prima întrebare",
    Designer_Canvas_EmptyBody: "Alegeți un tip de întrebare pentru a începe. Puteți reordona întrebările trăgându-le și puteți adăuga ramificări, astfel încât oamenii să vadă doar ce li se aplică.",
    Designer_Section_Chip: "Secțiunea {number} din {total}",
    Designer_Section_TitlePlaceholder: "Titlul secțiunii",
    Designer_Section_TitleAria: "Titlul secțiunii {number}",
    Designer_Section_DescriptionPlaceholder: "Descriere (opțional)",
    Designer_Section_DescriptionAria: "Descrierea secțiunii {number}",
    Designer_Section_MoveUp: "Mută secțiunea în sus",
    Designer_Section_MoveDown: "Mută secțiunea în jos",
    Designer_Section_Delete: "Șterge secțiunea",
    Designer_Card_DragToReorder: "Trageți pentru a reordona",
    Designer_Card_ReorderAria: "Reordonează {title}",
    Designer_Card_ReorderFallback: "întrebare",
    Designer_Canvas_AddNew: "Adaugă nou",
    Designer_Canvas_AddSection: "Adaugă secțiune",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Adresă (stradă și număr)",
    Form_Address_Street2Placeholder: "Apartament, bloc etc. (opțional)",
    Form_Address_CityPlaceholder: "Oraș",
    Form_Address_StatePlaceholder: "Județ / regiune",
    Form_Address_PostalCodePlaceholder: "Cod poștal",
    Form_Address_CountryPlaceholder: "Țară",
    Form_Address_StreetAria: "adresă (stradă și număr)",
    Form_Address_Street2Aria: "a doua linie a adresei",
    Form_Address_CityAria: "oraș",
    Form_Address_StateAria: "județ sau regiune",
    Form_Address_PostalCodeAria: "cod poștal",
    Form_Address_CountryAria: "țară",
    Form_Consent_DefaultLabel: "Sunt de acord",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered} din {total} rânduri completate",
    Form_Lookup_LoadError: "Opțiunile pentru această întrebare nu au putut fi încărcate.",
    Form_Lookup_Loading: "Se încarcă opțiunile…",
    Form_Lookup_SelectOptionsPlaceholder: "Selectați opțiuni",
    Form_Lookup_SelectOptionPlaceholder: "Selectați o opțiune",
    Form_Person_Placeholder: "Începeți să tastați un nume…",
    Form_Person_SuggestedPeopleAndGroups: "Persoane și grupuri sugerate",
    Form_Person_SuggestedPeople: "Persoane sugerate",
    Form_Person_NoPeopleOrGroups: "Nu s-au găsit persoane sau grupuri",
    Form_Person_NoPeople: "Nu s-au găsit persoane",
    Form_Person_Searching: "Se caută…",
    Form_Ranking_Moved: "{item} a fost mutat pe poziția {position} din {total}",
    Form_Ranking_MoveUp: "Mută în sus",
    Form_Ranking_MoveDown: "Mută în jos",
    Form_Ranking_MoveItemUpAria: "Mută {item} în sus",
    Form_Ranking_MoveItemDownAria: "Mută {item} în jos",
    Form_Rating_ValueText: "{value} din {max}",
    Form_Rating_NotRated: "Neevaluat",
    Form_Rating_Clear: "Șterge evaluarea",
    Form_RichText_Bold: "Aldin",
    Form_RichText_Italic: "Cursiv",
    Form_RichText_Underline: "Subliniat",
    Form_RichText_BulletedList: "Listă cu marcatori",
    Form_RichText_NumberedList: "Listă numerotată",
    Form_RichText_ClearFormatting: "Golește formatarea",
    Form_RichText_ToolbarAria: "Formatare text",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "„{name}” a fost omis — limita este {limit}.",
    Form_File_TypeNotAccepted: "„{name}” nu este un tip acceptat.",
    Form_File_TooLarge: "„{name}” este mai mare de {size} MB.",
    Form_File_AlreadyAttached: "„{name}” este deja atașat.",
    Form_File_ReadError: "Unul dintre fișiere nu a putut fi citit. Încercați să-l atașați din nou.",
    Form_File_HintMaxSize: "până la {size} MB fiecare",
    Form_File_HintOneFile: "1 fișier",
    Form_File_HintMaxFiles: "maximum {count} fișiere",
    Form_File_Reading: "Se citesc fișierele…",
    Form_File_DropPrompt: "Plasați fișierele aici sau faceți clic pentru a naviga",
    Form_File_Remove: "Elimină {name}",
    Form_Signature_Alt: "Semnătură",
    Form_Signature_AriaSigned: "{label} — semnat",
    Form_Signature_AriaEmpty: "{label} — gol",
    Form_Signature_Clear: "Golește",
    Form_Signature_Signed: "Semnat",
    Form_Signature_Prompt: "Semnați mai sus folosind mouse-ul, un stilou sau degetul",
    Form_Time_Placeholder: "Selectați o oră",
    Form_Field_DatePlaceholder: "Selectați o dată",
    Form_Field_TimeAriaWithLabel: "{label} — oră",
    Form_Field_TimeAria: "Oră",
    Form_Field_OtherDefault: "Altele",
    Form_Field_SelectOptionsPlaceholder: "Selectați opțiuni",
    Form_Field_PleaseSpecify: "Vă rugăm să specificați",
    Form_Field_OtherSpecifyAria: "{label} — vă rugăm să specificați",
    Form_Field_SelectOptionPlaceholder: "Selectați o opțiune",
    Form_Field_Yes: "Da",
    Form_Field_No: "Nu",
    Form_Field_SliderHint: "Trageți glisorul pentru a răspunde",
    Form_Field_WebAddressAriaWithLabel: "{label} — adresă web",
    Form_Field_WebAddressAria: "Adresă web",
    Form_Field_DisplayTextPlaceholder: "Text afișat (opțional)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — text afișat",
    Form_Field_DisplayTextAria: "Text afișat",
    Form_Field_ChooseBetween: "Alegeți între {min} și {max}",
    Form_Field_ChooseAtLeast: "Alegeți cel puțin {min}",
    Form_Field_ChooseUpTo: "Alegeți maximum {max}",
    Form_Field_SelectedCount: "{count} selectate",
    Form_Field_RequiredAria: "(obligatoriu)",
    Form_Submit_SaveError: "Răspunsul dvs. nu a putut fi salvat. Asigurați-vă că formularul a fost publicat din designer și că aveți permisiunea de a adăuga elemente în lista de răspunsuri.",
    Form_Empty_Message: "Acest formular nu are încă nicio întrebare. Proprietarul formularului le poate adăuga în fila Întrebări.",
    Form_Checking: "Se verifică formularul…",
    Form_Closed_NotYetOpen: "Încă nedeschis",
    Form_Closed_AlreadyAnswered: "Deja completat",
    Form_Closed_Title: "Formular închis",
    Form_Confirmation_PreviewNotice: "Aceasta a fost o previzualizare — nimic nu a fost salvat în lista de răspunsuri.",
    Form_Confirmation_PreviewAgain: "Previzualizează din nou",
    Form_Confirmation_SubmitAnother: "Trimite un alt răspuns",
    Form_Wizard_StepFallback: "Pasul {step}",
    Form_Wizard_StepsAria: "Pașii formularului",
    Form_Wizard_StepOf: "Pasul {step} din {total}",
    Form_ErrorSummary_Title: "Verificați {count} răspunsuri:",
    Form_ErrorSummary_UntitledQuestion: "Întrebare fără titlu",
    Form_ErrorSummary_Question: "Întrebare",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Înapoi",
    Form_Nav_Next: "Următorul",
    Form_Draft_Saving: "Se salvează…",
    Form_Draft_Saved: "Ciornă salvată",
    Form_Draft_SaveAndFinishLater: "Salvează și finalizează mai târziu",
    Form_Draft_NotSaved: "Ciorna nu a fost salvată",
    Form_Submit_Preview: "Trimitere (previzualizare)",
    Form_Submit_Button: "Trimitere",
    Form_Response_NoAnswer: "Fără răspuns",
    Form_Signature_TypeLabel: "Introduceți numele complet",
    Form_Signature_TypeInstead: "Introduceți numele",
    Form_Signature_DrawInstead: "Desenați",
    Form_Edit_Button: "Editați răspunsul anterior",
    Form_Edit_Available: "Ați trimis deja un răspuns. Îl puteți edita în loc să trimiteți unul nou.",
    Form_Edit_Banner: "Editați răspunsul anterior.",
    Form_Edit_Save: "Actualizare răspuns",
    Form_Edit_UpdatedTitle: "Răspuns actualizat",
    Form_Edit_UpdatedMessage: "Modificările au fost salvate.",
    Form_Edit_LoadError: "Răspunsul anterior nu a putut fi încărcat. Încercați din nou.",
    Form_Draft_MissingFiles: "Atașați din nou: {names}. Aceste fișiere nu au putut fi restaurate.",
    Form_Attachments_Failed: "Răspunsurile au fost salvate, dar aceste atașamente nu au putut fi încărcate: {names}. Încercați din nou sau contactați proprietarul formularului.",
    Logic_ThisQuestion: "Această întrebare",
    Logic_Required: "{label} este obligatoriu",
    Logic_RequiredConsent: "Bifați caseta pentru a continua",
    Logic_RequiredFile: "Atașați cel puțin un fișier",
    Logic_RequiredSignature: "Adăugați semnătura",
    Logic_RequiredLikert: "Răspundeți la toate rândurile",
    Logic_InvalidEmail: "Introduceți o adresă de e-mail validă",
    Logic_InvalidPhone: "Introduceți un număr de telefon valid",
    Logic_InvalidUrl: "Introduceți o adresă web validă care începe cu http:// sau https://",
    Logic_MinValue: "Valoarea trebuie să fie cel puțin {value}",
    Logic_MaxValue: "Valoarea trebuie să fie cel mult {value}",
    Logic_MaxLength: "Lungimea maximă este de {max} caractere",
    Logic_ChooseAtLeastOne: "Alegeți cel puțin {count} opțiune",
    Logic_ChooseAtLeastMany: "Alegeți cel puțin {count} opțiuni",
    Logic_ChooseAtMostOne: "Alegeți cel mult {count} opțiune",
    Logic_ChooseAtMostMany: "Alegeți cel mult {count} opțiuni",
    Logic_LikertRemaining: "Răspundeți la toate rândurile (mai rămân {count})",
    Logic_MaxFilesOne: "Atașați cel mult {count} fișier",
    Logic_MaxFilesMany: "Atașați cel mult {count} fișiere",
    Logic_FileTooLarge: "„{name}” este mai mare de {size} MB",
    Logic_FileTypeNotAccepted: "„{name}” nu este un tip de fișier acceptat ({types})",
    Logic_AddressRequired: "Introduceți cel puțin o stradă și un oraș",
    Logic_PatternDefault: "Acest răspuns nu are formatul așteptat",
    Logic_Yes: "Da",
    Logic_No: "Nu",
    Logic_Agreed: "Acceptat",
    Logic_NotAgreed: "Neacceptat",
    Logic_Signed: "Semnat",
    Logic_NoAnswer: "(fără răspuns)",
    Logic_Unknown: "(necunoscut)",
    Logic_OtherSlice: "Altele ({count})",
    Logic_CsvResponseId: "ID răspuns",
    Logic_CsvSubmitted: "Trimis",
    Logic_CsvSubmittedBy: "Trimis de",
    Logic_EmailQuestion: "Întrebare",
    Logic_EmailViewItem: "Vizualizare în Microsoft Lists",
    Logic_EmailFooter: "Trimis automat de Smart Forms.",
    Logic_ClosedDefault: "Acest formular nu mai acceptă răspunsuri.",
    Logic_NotYetOpen: "Acest formular se deschide la {date}.",
    Logic_AlreadyResponded: "Ați răspuns deja la acest formular. Vă mulțumim!",
    Logic_UntitledQuestion: "O întrebare fără titlu",
    Logic_Issue_NoQuestions: "Adăugați cel puțin o întrebare înainte de a colecta răspunsuri.",
    Logic_Issue_NoTitle: "O întrebare nu are text — va primi automat un nume la publicare.",
    Logic_Issue_DuplicateTitle: "{label} are același text ca o altă întrebare, ceea ce îngreunează citirea rezultatelor.",
    Logic_Issue_NeedTwoOptions: "{label} necesită cel puțin două opțiuni.",
    Logic_Issue_ImageNoImage: "{label} are opțiuni fără imagine — vor fi afișate ca dale de text.",
    Logic_Issue_LikertNeedRow: "{label} necesită cel puțin un rând.",
    Logic_Issue_LikertNeedColumns: "{label} necesită cel puțin două coloane de scală.",
    Logic_Issue_NoLookupList: "{label} nu are nicio listă sursă selectată.",
    Logic_Issue_NoFormula: "{label} nu are formulă.",
    Logic_Issue_BadFormula: "{label} are o formulă care nu poate fi calculată. Verificați parantezele și operatorii.",
    Logic_Issue_MissingRefs: "{label} face referire la întrebări care nu există: {names}.",
    Logic_Issue_BadPattern: "{label} are un model de validare nevalid.",
    Logic_Issue_BrokenRule: "{label} are o regulă de ramificare care indică o întrebare ștearsă.",
    Logic_Issue_SelfRule: "{label} are o regulă de ramificare care se referă la ea însăși.",
    Logic_Issue_RuleMismatch: "{label} are o regulă de ramificare care nu se mai potrivește cu întrebarea de care depinde.",
    Logic_Issue_RequiredReadOnly: "{label} este obligatoriu și numai în citire, deci poate primi răspuns doar printr-un link precompletat.",
    Logic_Issue_EmptySection: "O secțiune nu are întrebări și va fi omisă.",
    Logic_Issue_CloseBeforeOpen: "Data de închidere este egală sau anterioară datei de deschidere, deci formularul nu va accepta niciodată răspunsuri.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "E-mailurile de aprobare sunt activate, dar pasul de aprobare este dezactivat.",
    Logic_Op_equals: "este",
    Logic_Op_notEquals: "nu este",
    Logic_Op_contains: "conține",
    Logic_Op_notContains: "nu conține",
    Logic_Op_notEmpty: "are răspuns",
    Logic_Op_empty: "nu are răspuns",
    Logic_Op_greaterThan: "este mai mare decât",
    Logic_Op_greaterOrEqual: "este cel puțin",
    Logic_Op_lessThan: "este mai mic decât",
    Logic_Op_lessOrEqual: "este cel mult",
    Logic_Op_between: "este între",
    Logic_Op_before: "este înainte de",
    Logic_Op_after: "este după",
    Logic_Type_Text: "Răspuns scurt",
    Logic_TypeDesc_Text: "O singură linie de text",
    Logic_Category_Text: "Text",
    Logic_Type_MultilineText: "Răspuns lung",
    Logic_TypeDesc_MultilineText: "Mai multe linii de text simplu",
    Logic_Type_RichText: "Text formatat",
    Logic_TypeDesc_RichText: "Aldin, liste și linkuri",
    Logic_Type_Choice: "Alegere",
    Logic_TypeDesc_Choice: "Alegeți dintr-o listă de opțiuni",
    Logic_Category_Choice: "Alegere",
    Logic_Type_ImageChoice: "Alegere imagine",
    Logic_TypeDesc_ImageChoice: "Alegeți dintre dale cu imagini",
    Logic_Type_Lookup: "Căutare într-o listă",
    Logic_TypeDesc_Lookup: "Opțiuni citite în timp real dintr-o altă listă SharePoint",
    Logic_Type_YesNo: "Da / Nu",
    Logic_TypeDesc_YesNo: "Un simplu comutator activat/dezactivat",
    Logic_Type_Consent: "Consimțământ",
    Logic_TypeDesc_Consent: "O casetă de selectare pe care respondentul trebuie să o bifeze pentru a continua",
    Logic_Type_Ranking: "Clasament",
    Logic_TypeDesc_Ranking: "Trageți opțiunile în ordinea preferinței",
    Logic_Type_Rating: "Evaluare",
    Logic_TypeDesc_Rating: "Stele, inimi sau degete mari",
    Logic_Category_Scales: "Scale",
    Logic_Type_Scale: "Scală de opinie",
    Logic_TypeDesc_Scale: "O scală numerotată cu capete etichetate",
    Logic_Type_Slider: "Glisor",
    Logic_TypeDesc_Slider: "O valoare pe o scală glisantă",
    Logic_Type_Likert: "Grilă Likert",
    Logic_TypeDesc_Likert: "Evaluați mai multe afirmații pe aceeași scală",
    Logic_Type_Number: "Număr",
    Logic_TypeDesc_Number: "Simplu, monedă sau procent",
    Logic_Category_Advanced: "Avansat",
    Logic_Type_Calculated: "Calculat",
    Logic_TypeDesc_Calculated: "Un total numai în citire calculat din alte răspunsuri",
    Logic_Type_Date: "Dată",
    Logic_TypeDesc_Date: "O dată calendaristică, opțional cu oră",
    Logic_Category_Date: "Dată",
    Logic_Type_Time: "Oră",
    Logic_TypeDesc_Time: "O oră din zi, singură",
    Logic_Type_Person: "Persoană",
    Logic_TypeDesc_Person: "Alegeți o persoană din organizație",
    Logic_Category_People: "Persoane",
    Logic_Type_Email: "E-mail",
    Logic_TypeDesc_Email: "O adresă de e-mail, validată",
    Logic_Type_Phone: "Telefon",
    Logic_TypeDesc_Phone: "Un număr de telefon, validat",
    Logic_Type_Address: "Adresă",
    Logic_TypeDesc_Address: "Stradă, oraș, cod poștal și țară",
    Logic_Type_Hyperlink: "Link",
    Logic_TypeDesc_Hyperlink: "O adresă web",
    Logic_Type_FileUpload: "Încărcare fișier",
    Logic_TypeDesc_FileUpload: "Atașați unul sau mai multe fișiere la răspuns",
    Logic_Type_Signature: "Semnătură",
    Logic_TypeDesc_Signature: "Semnați cu mouse-ul, stiloul sau degetul",
    Logic_Type_Content: "Bloc de text",
    Logic_TypeDesc_Content: "Instrucțiuni sau o imagine — nu colectează răspunsuri",
    Logic_Category_Layout: "Aspect",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Cât de probabil este să recomandați…",
    Logic_Preset_satisfaction: "Satisfacție (1–5)",
    Logic_PresetDesc_satisfaction: "De la foarte nemulțumit la foarte mulțumit",
    Logic_Preset_currency: "Monedă",
    Logic_PresetDesc_currency: "O sumă de bani",
    Logic_Preset_percent: "Procent",
    Logic_PresetDesc_percent: "O valoare procentuală",
    Logic_Template_blank_Name: "Formular necompletat",
    Logic_Template_blank_Description: "Începeți de la zero",
    Logic_Template_feedback_Name: "Feedback client",
    Logic_Template_feedback_Description: "NPS, evaluări și comentarii libere",
    Logic_Template_event_Name: "Înscriere la eveniment",
    Logic_Template_event_Description: "Detalii participant, sesiuni și cerințe alimentare",
    Logic_Template_itrequest_Name: "Solicitare de servicii IT",
    Logic_Template_itrequest_Description: "Solicitări clasificate pe categorii, cu prioritate și atașamente",
    Logic_Template_expense_Name: "Decont de cheltuieli",
    Logic_Template_expense_Description: "Poziții, chitanțe și un total calculat",
    Logic_Template_pulse_Name: "Sondaj rapid pentru angajați",
    Logic_Template_pulse_Description: "Grilă Likert, scală de implicare și notă de anonimat",
    Logic_Template_safety_Name: "Inspecție de siguranță",
    Logic_Template_safety_Description: "Listă de verificare, fotografii și o semnătură",
    Logic_Template_booking_Name: "Rezervare de sală sau resursă",
    Logic_Template_booking_Description: "Selector de resurse bazat pe căutare, cu interval orar",
    Charts_ColumnChartAria: "Grafic cu coloane cu {count} categorii",
    Charts_DonutChartAria: "Grafic inel cu {count} categorii",
    Charts_NoAnswers: "Nu există încă răspunsuri.",
    Charts_NoResponses: "Nu există încă răspunsuri.",
    Charts_Responses: "Răspunsuri",
    Charts_ResponsesOverTime: "Răspunsuri în timp",
    Responses_Chart_Answer: "Răspuns",
    Responses_Chart_Average: "Medie",
    Responses_Chart_AverageOf: "Media din {count}",
    Responses_Chart_AveragePosition: "Poziția medie",
    Responses_Chart_AverageRange: "Medie (1–{max})",
    Responses_Chart_AvgValue: "medie {value}",
    Responses_Chart_Detractors: "Detractori (0–6)",
    Responses_Chart_Max: "Max.",
    Responses_Chart_Maximum: "Maxim",
    Responses_Chart_Median: "Mediană",
    Responses_Chart_MentionOne: "{count} mențiune",
    Responses_Chart_MentionOther: "{count} mențiuni",
    Responses_Chart_Min: "Min.",
    Responses_Chart_Minimum: "Minim",
    Responses_Chart_NoAnswers: "Nu există încă răspunsuri.",
    Responses_Chart_NoNumeric: "Nu există încă răspunsuri numerice.",
    Responses_Chart_NoRankings: "Nu există încă clasamente.",
    Responses_Chart_NoScores: "Nu există încă scoruri.",
    Responses_Chart_NotEnoughText: "Nu există încă suficient text pentru rezumat.",
    Responses_Chart_NpsScore: "Scor NPS",
    Responses_Chart_Option: "Opțiune",
    Responses_Chart_Passives: "Pasivi (7–8)",
    Responses_Chart_Promoters: "Promotori (9–10)",
    Responses_Chart_ResponseOne: "răspuns",
    Responses_Chart_ResponseOther: "răspunsuri",
    Responses_Chart_Responses: "Răspunsuri",
    Responses_Chart_ShowingAnswers: "Se afișează {shown} din {total} răspunsuri.",
    Responses_Chart_Statement: "Afirmație",
    Responses_Chart_Statistic: "Statistică",
    Responses_Chart_StdDev: "Abat. std.",
    Responses_Chart_StdDeviation: "Abatere standard",
    Responses_Chart_Total: "Total",
    Responses_Chart_Value: "Valoare",
    Responses_Dashboard_AllHidden: "Toate întrebările sunt ascunse din tabloul de bord. Folosiți „Afișează întrebările ascunse” pentru a le readuce.",
    Responses_Dashboard_AnsweredOf: "{answered} din {total} completate",
    Responses_Dashboard_AnsweredOfPinned: "{answered} din {total} completate · fixată",
    Responses_Dashboard_AveragedAcrossResponses: "Media răspunsurilor",
    Responses_Dashboard_ByDay: "După zi",
    Responses_Dashboard_ByMonth: "După lună",
    Responses_Dashboard_ByWeek: "După săptămână",
    Responses_Dashboard_ChartAuto: "Automat",
    Responses_Dashboard_ChartBars: "Bare",
    Responses_Dashboard_ChartColumns: "Coloane",
    Responses_Dashboard_ChartDonut: "Inel",
    Responses_Dashboard_ChartGauge: "Indicator",
    Responses_Dashboard_ChartHistogram: "Histogramă",
    Responses_Dashboard_ChartOptions: "Opțiuni grafic",
    Responses_Dashboard_ChartOptionsFor: "Opțiuni grafic pentru {title}",
    Responses_Dashboard_ChartStatistics: "Statistici",
    Responses_Dashboard_ChartTable: "Tabel",
    Responses_Dashboard_ChartWordFrequency: "Frecvența cuvintelor",
    Responses_Dashboard_EmptyBody: "Odată ce oamenii încep să răspundă, acest tablou de bord se completează automat — cifre principale, o cronologie a răspunsurilor și un grafic pentru întrebările care merită urmărite.",
    Responses_Dashboard_EmptyTitle: "Nu există încă răspunsuri",
    Responses_Dashboard_Hide: "Ascunde din tabloul de bord",
    Responses_Dashboard_Highlights: "Repere",
    Responses_Dashboard_Last7Days: "Ultimele 7 zile",
    Responses_Dashboard_LatestDate: "Ultimul: {date}",
    Responses_Dashboard_MedianTimeToComplete: "Timp median de completare",
    Responses_Dashboard_NoPriorWeek: "Nu există o săptămână anterioară pentru comparație",
    Responses_Dashboard_OneEach: "Câte unul",
    Responses_Dashboard_Pin: "Fixează în tabloul de bord",
    Responses_Dashboard_QuestionFallback: "întrebare",
    Responses_Dashboard_QuestionsAnswered: "Întrebări completate",
    Responses_Dashboard_RecordedOnSubmit: "Înregistrat la trimitere",
    Responses_Dashboard_RepeatResponses: "{count} răspunsuri repetate",
    Responses_Dashboard_ResponsesOverTime: "Răspunsuri în timp",
    Responses_Dashboard_ShowHidden: "Afișează întrebările ascunse",
    Responses_Dashboard_SinceMidnight: "De la miezul nopții",
    Responses_Dashboard_Today: "Astăzi",
    Responses_Dashboard_TotalResponses: "Total răspunsuri",
    Responses_Dashboard_UniqueRespondents: "Respondenți unici",
    Responses_Dashboard_Unpin: "Anulează fixarea din tabloul de bord",
    Responses_Dashboard_UntitledQuestion: "Întrebare fără titlu",
    Responses_Dashboard_VsPrevious7Days: "față de ultimele 7 zile anterioare",
    Responses_Detail_Answers: "Răspunsuri",
    Responses_Detail_AsTheForm: "Ca în formular",
    Responses_Detail_Cancel: "Anulare",
    Responses_Detail_Delete: "Ștergere",
    Responses_Detail_DeleteBody: "Elementul din listă este mutat în coșul de reciclare al site-ului, de unde poate fi restaurat.",
    Responses_Detail_DeleteTitle: "Ștergeți acest răspuns?",
    Responses_Detail_Deleting: "Se șterge…",
    Responses_Detail_Draft: "Ciornă",
    Responses_Detail_Header: "Răspunsul {index} din {total}",
    Responses_Detail_LoadingAttachments: "Se încarcă atașamentele…",
    Responses_Detail_Next: "Răspunsul următor",
    Responses_Detail_NoAnswer: "Fără răspuns",
    Responses_Detail_Previous: "Răspunsul anterior",
    Responses_Detail_Print: "Imprimare",
    Responses_Detail_Signature: "Semnătură",
    Responses_Detail_Signed: "Semnat",
    Responses_Detail_Took: "a durat {duration}",
    Responses_Summary_AnsweredOfType: "{answered} din {total} completate · {type}",
    Responses_Summary_ByField: "După {title}",
    Responses_Summary_CompareBy: "Compară după…",
    Responses_Summary_EmptyBody: "Fiecare întrebare va avea aici propriul rezumat.",
    Responses_Summary_NoComparison: "Fără comparație",
    Responses_Summary_NothingToCompare: "Niciun răspuns nu a completat „{title}”, deci nu există nimic de comparat.",
    Responses_Summary_OtherNote: "Graficele cu mai mult de {max} categorii grupează cele mai mici în „Altele” — comutați un card la Tabel pentru a vedea toate valorile.",
    Responses_Summary_ResponseCountOne: "{count} răspuns",
    Responses_Summary_ResponseCountOther: "{count} răspunsuri",
    Responses_Summary_SeeAllAnswers: "Vedeți toate răspunsurile în tabel",
    Responses_Summary_SegmentNote: "Se afișează cele mai mari {groups} grupuri. Un răspuns care a selectat mai multe variante apare în fiecare grup corespunzător, deci totalurile grupurilor pot însuma mai mult de {total}.",
    Responses_Summary_SplitBy: "Împarte după {title}",
    Responses_Summary_Untitled: "fără titlu",
    Responses_Table_Apply: "Aplicare",
    Responses_Table_Cancel: "Anulare",
    Responses_Table_ClearSelection: "Golește selecția",
    Responses_Table_ColumnOrder: "Ordinea coloanelor",
    Responses_Table_ColumnsCount: "Coloane ({shown}/{total})",
    Responses_Table_Delete: "Ștergere",
    Responses_Table_DeleteBody: "Elementele din listă sunt mutate în coșul de reciclare al site-ului, de unde pot fi restaurate.",
    Responses_Table_DeleteSelected: "Șterge selecția",
    Responses_Table_DeleteTitleOne: "Ștergeți {count} răspuns?",
    Responses_Table_DeleteTitleOther: "Ștergeți {count} răspunsuri?",
    Responses_Table_Deleting: "Se șterge…",
    Responses_Table_MoveDown: "Mută în jos",
    Responses_Table_MoveDownFor: "Mută {title} în jos",
    Responses_Table_MoveUp: "Mută în sus",
    Responses_Table_MoveUpFor: "Mută {title} în sus",
    Responses_Table_NoColumns: "Nu este încă vizibilă nicio coloană de întrebare.",
    Responses_Table_NoMatch: "Niciun răspuns nu corespunde filtrelor curente.",
    Responses_Table_NothingToShow: "Nimic de afișat",
    Responses_Table_OpenResponse: "Deschide acest răspuns",
    Responses_Table_OrderNote: "Trimis și Trimis de apar întotdeauna primele. Ordinea prin tragere se aplică coloanelor de întrebări.",
    Responses_Table_Reorder: "Reordonare",
    Responses_Table_ResetColumns: "Resetează coloanele",
    Responses_Table_SelectResponse: "Selectează acest răspuns",
    Responses_Table_SelectedOne: "{count} răspuns selectat",
    Responses_Table_SelectedOther: "{count} răspunsuri selectate",
    Responses_Table_ShowAll: "Afișează tot",
    Responses_Table_ShowTheseQuestions: "Afișează aceste întrebări",
    Responses_Table_Submitted: "Trimis",
    Responses_Table_SubmittedBy: "Trimis de",
    Responses_Table_ToggleSelection: "Comută selecția",
    Responses_Table_Unknown: "Necunoscut",
    Responses_Table_Untitled: "Fără titlu",
    Responses_View_AllTime: "Tot timpul",
    Responses_View_AnyAnswer: "Orice răspuns",
    Responses_View_Clear: "Golește",
    Responses_View_CopyShareLink: "Copiază linkul de partajare",
    Responses_View_CountFiltered: "{shown} din {total} răspunsuri",
    Responses_View_CountOne: "{count} răspuns",
    Responses_View_CountOther: "{count} răspunsuri",
    Responses_View_Dashboard: "Tablou de bord",
    Responses_View_DateRange: "Interval de date",
    Responses_View_EmptyBody: "Partajați formularul pentru a începe colectarea. Răspunsurile sunt salvate în „{list}” și apar aici imediat.",
    Responses_View_EmptyTitle: "Nu există încă răspunsuri",
    Responses_View_ExportCsv: "Exportă CSV",
    Responses_View_FilterByAnswer: "Filtrare după răspuns",
    Responses_View_FilterByQuestion: "Filtrare după întrebare",
    Responses_View_FilterValue: "Valoare filtru",
    Responses_View_Last30Days: "Ultimele 30 de zile",
    Responses_View_Last7Days: "Ultimele 7 zile",
    Responses_View_Last90Days: "Ultimele 90 de zile",
    Responses_View_LoadError: "Răspunsurile nu au putut fi încărcate. Publicați o dată formularul pentru ca coloanele listei să existe, apoi încercați din nou.",
    Responses_View_Loading: "Se încarcă răspunsurile…",
    Responses_View_MoreActions: "Mai multe acțiuni pentru răspunsuri",
    Responses_View_PreviewForm: "Previzualizează formularul",
    Responses_View_Refresh: "Reîmprospătare",
    Responses_View_ResponsesTab: "Răspunsuri ({count})",
    Responses_View_SearchPlaceholder: "Căutați în toate răspunsurile",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Selectați o valoare",
    Responses_View_Summary: "Rezumat",
    Responses_View_Today: "Astăzi",
    Responses_View_Truncated: "Această listă are mai multe răspunsuri decât încarcă Smart Forms simultan. Se afișează cele mai recente {count} — deschideți lista în Microsoft Lists pentru setul complet.",
    Responses_View_TryAgain: "Încercați din nou",
    Responses_View_Untitled: "Fără titlu",
    Responses_Approval_Column: "Aprobare",
    Responses_Approval_ReviewerColumn: "Revizuit de",
    Responses_Approval_CommentColumn: "Comentariu revizor",
    Responses_Approval_Pending: "În așteptare",
    Responses_Approval_Approved: "Aprobat",
    Responses_Approval_Rejected: "Respins",
    Responses_Approval_AnyStatus: "Orice stare de aprobare",
    Responses_Approval_FilterLabel: "Filtrare după starea de aprobare",
    Responses_Approval_ApproveSelected: "Aprobă selectate",
    Responses_Approval_RejectSelected: "Respinge selectate",
    Responses_Approval_BulkFailed: "{count} răspunsuri nu au putut fi actualizate. Încercați din nou.",
    Responses_Approval_Approve: "Aprobă",
    Responses_Approval_Reject: "Respinge",
    Responses_Approval_Reset: "Resetare la în așteptare",
    Responses_Approval_CommentLabel: "Comentariu (opțional)",
    Responses_Approval_ReviewedBy: "Revizuit de {name}",
    Responses_Approval_Error: "Decizia nu a putut fi salvată. Încercați din nou.",
    Responses_Dashboard_ApprovalStatus: "În așteptarea revizuirii",
    Responses_Dashboard_ApprovalBreakdown: "{pending} în așteptare, {approved} aprobate, {rejected} respinse",
    Responses_Dashboard_TimelineCoarsened: "Intervalul de date este lung, așa că cronologia a fost grupată mai grosier ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Intervalul de date este foarte lung, așa că sunt afișate doar cele mai recente {count} perioade.",
    Service_Item_DefaultTitle: "Răspuns — {date}",
    Service_Email_ApprovalSubject: "Răspunsul dvs. a fost {status} — {title}",
    Service_Email_ApprovalHeading: "Răspunsul dvs. a fost {status}",
    Service_Email_ApprovalIntro: "Un revizor a marcat răspunsul dvs. la „{title}” ca fiind {status}.",
    Service_Email_ApprovalCommentLabel: "Comentariu revizor",
    Service_Approval_Approved: "aprobat",
    Service_Approval_Rejected: "respins",
    Service_Approval_Pending: "în așteptare",
    Service_Lookup_InvalidFilter: "Filtrul de căutare nu este valid.",
    Service_Edit_NotAllowed: "Acest formular nu permite editarea unui răspuns trimis.",
    Service_Edit_NotYours: "Puteți edita doar propriul răspuns.",
    Service_Signature_AttachmentLabel: "Semnătură",
    PropertyPane_ListsLoadFailed: "Listele de pe acest site nu au putut fi încărcate.",
    PropertyPane_EnterListName: "Introduceți mai întâi un nume pentru lista nouă.",
    PropertyPane_CreatingList: "Se creează „{name}”…",
    PropertyPane_ListCreated: "Lista „{title}” a fost creată și selectată.",
    PropertyPane_ListAlreadyExists: "Există deja o listă numită „{name}” — selectați-o din lista verticală de mai sus.",
    PropertyPane_CreateListFailed: "Lista nu a putut fi creată. Verificați dacă aveți permisiunea de a crea liste pe acest site.",
    PropertyPane_Description: "Alegeți lista SharePoint care stochează răspunsurile formularului sau creați una nouă. Tot restul — întrebări, aspect, notificări — se editează direct pe pagină.",
    PropertyPane_ResponseList_GroupName: "Lista de răspunsuri",
    PropertyPane_ListDropdown_Label: "Salvează răspunsurile în această listă",
    PropertyPane_ResponsesGoTo: "Răspunsurile merg în „{name}”.",
    PropertyPane_PickList: "Alegeți o listă sau creați una mai jos.",
    PropertyPane_LoadingLists: "Se încarcă listele…",
    PropertyPane_NewListName_Label: "Sau creați o listă nouă",
    PropertyPane_NewListName_Placeholder: "Numele listei noi",
    PropertyPane_CreateList_Button: "Creează listă",
    PropertyPane_Tips_GroupName: "Sfaturi",
    PropertyPane_Tip_AutoSave: "Întrebările și setările se salvează automat pe măsură ce le editați — nu trebuie să salvați sau să publicați pagina.",
    PropertyPane_Tip_Permissions: "Respondenții au nevoie de permisiunea de a adăuga elemente în lista de răspunsuri. Verificați permisiunile listei dacă cineva raportează o eroare la trimitere.",
    PropertyPane_Tip_Share: "Folosiți „Colectează răspunsuri” pe pagină pentru a crea coloanele listei și a obține un link de completare care poate fi partajat.",
    App_ErrorBoundary_Title: "Smart Forms — Eroare de randare",
    App_ErrorBoundary_Message: "Mesaj:",
    App_ErrorBoundary_Stack: "Stivă:",
    App_ErrorBoundary_NoStack: "(nicio stivă disponibilă)",
    App_ErrorBoundary_ConsoleNote: "Detaliile complete au fost scrise și în consola browserului.",
    App_DefaultQuestionTitle: "Întrebarea {number}",
    App_Error_ListMissing: "Lista configurată pentru acest formular nu mai există. Alegeți altă listă în setările web part-ului.",
    App_Error_LoadConfig: "A apărut o problemă la încărcarea configurației formularului.",
    App_Error_Unable: "Formularul nu a putut fi încărcat.",
    App_Publish_ConflictNotice: "„{title}” are deja o coloană de listă de alt tip ({type}). Redenumiți întrebarea pentru a se putea crea o coloană nouă sau readuceți tipul.",
    App_Publish_ConflictUnnamedQuestion: "o întrebare",
    App_Publish_ColumnsAddedOne: "{count} coloană a fost adăugată în „{list}”.",
    App_Publish_ColumnsAddedOther: "{count} coloane au fost adăugate în „{list}”.",
    App_Publish_TheList: "lista",
    App_Publish_UpToDate: "Lista de răspunsuri este deja la zi.",
    App_Publish_Error: "Coloanele listei nu au putut fi create. De obicei, aceasta înseamnă că nu aveți permisiunea Gestionare liste pe lista de răspunsuri, dar se poate întâmpla și pe site-uri cu scripturile personalizate dezactivate. Verificați consola browserului pentru eroarea de bază sau încercați din nou.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Construiți un formular elegant pe baza unei liste SharePoint — {count} tipuri de întrebări, logică de ramificare, încărcări de fișiere, linkuri de completare partajabile și un tablou de bord cu rezultate.",
    App_Placeholder_ChooseList: "Alegeți sau creați o listă",
    App_Placeholder_Hint: "Editați pagina și configurați acest web part pentru a începe.",
    App_Loading: "Se încarcă formularul…",
    App_OpenSettings: "Deschide setările",
    App_Tab_Questions: "Întrebări",
    App_Tab_QuestionsWithCount: "Întrebări ({count})",
    App_Tab_Responses: "Răspunsuri",
    App_Tab_Responses_Title: "Răspunsurile sunt salvate în „{list}”",
    App_Templates_Start: "Începe dintr-un șablon",
    App_Settings_Title: "Setări formular — aspect, notificări, acces",
    App_Settings_AriaLabel: "Setări formular",
    App_Preview: "Previzualizare",
    App_Preview_Close: "Închide previzualizarea",
    App_Preview_Hint: "Previzualizare — nimic din ce trimiteți aici nu se salvează. Validarea și ramificarea se comportă exact ca pentru respondenți.",
    App_Publish_GettingReady: "Se pregătește…",
    App_Publish_CollectResponses: "Colectează răspunsuri",
    App_Publish_Share: "Partajare",
    App_Retry: "Reîncercare",
    App_SaveError_Banner: "Ultima modificare nu a putut fi salvată. Verificați conexiunea, apoi încercați din nou.",
    App_Preflight_BlockingTitle: "Remediați acestea înainte de colectare",
    App_Preflight_WarningTitle: "Merită verificate mai întâi",
    App_Preflight_BlockingText: "Acestea ar împiedica formularul publicat să funcționeze corect.",
    App_Preflight_WarningText: "Nimic nu este defect, dar de obicei merită remediate înainte de a partaja linkul.",
    App_Preflight_GoTo: "Salt la",
    App_Preflight_CollectAnyway: "Colectează răspunsuri oricum",
    App_Preflight_Back: "Înapoi la formular",
    App_Cancel: "Anulare",
    App_Done: "Terminat",
    App_Share_Title: "Formularul dvs. este gata de partajat",
    App_Share_SubText: "Trimiteți acest link oricui trebuie să completeze formularul.",
    App_Share_LinkAriaLabel: "Link de partajare",
    App_Share_Copy: "Copiere",
    App_Share_Copied: "Copiat",
    App_Share_AddItemsEmphasis: "adăuga elemente",
    App_Share_PermissionNote: "Respondenții au nevoie de permisiunea de a {addItems} în „{title}” și de acces la această pagină. Dacă cineva primește o eroare la trimitere, aproape întotdeauna acesta este motivul.",
    App_Share_PrefillNote: "Puteți precompleta răspunsuri în link adăugând numele coloanei, de exemplu {example}.",
    App_Templates_ReplaceWarning: "Alegerea unui șablon înlocuiește întrebările actuale.",
    App_Templates_PickStart: "Alegeți un punct de plecare — puteți modifica orice ulterior.",
    App_Templates_Empty: "Gol",
    App_Templates_QuestionCount: "{count} întrebări",
    App_SaveChip_SavingTitle: "Se salvează ultima modificare",
    App_SaveChip_Saving: "Se salvează…",
    App_SaveChip_FailedTitle: "Ultima modificare nu a putut fi salvată. Verificați conexiunea și încercați din nou.",
    App_SaveChip_Failed: "Salvarea a eșuat",
    App_SaveChip_SavedTitle: "Toate modificările sunt salvate",
    App_SaveChip_Saved: "Salvat",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Răspuns nou — {title}",
    Service_Email_NewResponseHeading: "Răspuns nou: {title}",
    Service_Email_NewResponseIntro: "Cineva tocmai a trimis un răspuns — {date}.",
    Service_Email_ReceiptSubject: "Răspunsul dvs. — {title}",
    Service_Email_ReceiptHeading: "Vă mulțumim pentru răspuns!",
    Service_Email_ReceiptIntro: "Iată o copie a ceea ce ați trimis către „{title}”.",
    App_History_Title: "Istoric versiuni",
    App_History_RestoredNotice: "Versiunea salvată la {date} a fost restaurată. Revizuiți-o, apoi utilizați Colectare răspunsuri pentru a publica întrebările noi.",
    App_History_Undo: "Anulare restaurare",
    App_Share_CopyManual: "Browserul a blocat copierea. Selectați linkul de mai sus și apăsați Ctrl+C (Cmd+C pe Mac) pentru a-l copia.",
    App_Share_TeamsNote: "Vă aflați în Microsoft Teams. Acest link deschide direct pagina SharePoint, deci destinatarii au nevoie de acces la site.",
    App_Share_PrefillNotSecure: "Răspunsurile precompletate sunt doar o facilitate: oricine are linkul le poate modifica, deci nu le considerați niciodată o limită de securitate.",
    Designer_Section_DropHere: "Plasați o întrebare aici",
    Designer_Section_DropEnd: "Plasați aici pentru a muta la sfârșitul acestei secțiuni",
    Designer_Rules_RemovedOne: "A fost eliminată 1 regulă de ramificare care nu se mai potrivea.",
    Designer_Rules_RemovedOther: "Au fost eliminate {count} reguli de ramificare care nu se mai potriveau.",
    Designer_Settings_AllowEdit: "Permite respondenților să-și editeze răspunsul",
    Designer_Settings_AllowEditHint: "Respondenții pot redeschide și actualiza ce au trimis. Fiecare persoană poate edita doar propriul răspuns.",
    Designer_Settings_EnableApproval: "Activare flux de aprobare",
    Designer_Settings_ApprovalNotify: "Trimite e-mail respondentului la decizie",
    Designer_Settings_ApprovalHint: "Adaugă coloane de aprobare la lista de răspunsuri la următoarea publicare. Proprietarii aprobă sau resping răspunsurile din fila Răspunsuri.",
    Designer_History_Title: "Istoric versiuni",
    Designer_History_Intro: "Versiuni salvate anterior ale întrebărilor și setărilor acestui formular. Restaurarea încarcă o versiune în designer; puteți anula acțiunea, iar întrebările noi se creează doar la publicare.",
    Designer_History_Loading: "Se încarcă versiunile...",
    Designer_History_Empty: "Nu s-au găsit versiuni anterioare. Istoricul versiunilor necesită activarea versionării pentru lista „Smart Forms Config” și cel puțin o modificare salvată.",
    Designer_History_Latest: "Cea mai recentă",
    Designer_History_LatestTitle: "Aceasta este versiunea utilizată în prezent",
    Designer_History_By: "de {name}",
    Designer_History_UnknownAuthor: "Autor necunoscut",
    Designer_History_VersionLabel: "versiunea {label}",
    Designer_History_Preview: "Previzualizare",
    Designer_History_Restore: "Restaurare",
    Designer_History_QuestionsOne: "1 întrebare",
    Designer_History_QuestionsOther: "{count} întrebări",
    Designer_History_LoadFailed: "Această versiune nu a putut fi încărcată.",
    Designer_History_ConfirmTitle: "Restaurați această versiune?",
    Designer_History_ConfirmText: "Formularul va fi înlocuit cu versiunea salvată la {date} ({count} întrebări). Puteți anula imediat după."
  };
});
