define([], function () {
  return {
    Designer_Color_Blue: "Синий",
    Designer_Color_Teal: "Бирюзовый",
    Designer_Color_Green: "Зеленый",
    Designer_Color_Purple: "Фиолетовый",
    Designer_Color_Magenta: "Пурпурный",
    Designer_Color_Red: "Красный",
    Designer_Color_Orange: "Оранжевый",
    Designer_Color_Gray: "Серый",
    Designer_Settings_LayoutSinglePage: "Все вопросы на одной странице",
    Designer_Settings_LayoutWizard: "Один раздел на шаг (мастер)",
    Designer_Settings_Title: "Параметры формы",
    Designer_Common_Apply: "Применить",
    Designer_Common_Cancel: "Отмена",
    Designer_Settings_TabBasics: "Основное",
    Designer_Settings_FormTitle: "Название формы",
    Designer_Settings_Description: "Описание",
    Designer_Settings_Layout: "Макет",
    Designer_Settings_NumberQuestions: "Нумеровать вопросы",
    Designer_Settings_ShuffleQuestions: "Перемешивать порядок вопросов для каждого респондента",
    Designer_Settings_ShowProgressBar: "Показывать индикатор выполнения",
    Designer_Settings_TabAppearance: "Оформление",
    Designer_Settings_AccentColor: "Цвет акцента",
    Designer_Settings_CustomColorTitle: "Пользовательский цвет",
    Designer_Settings_CustomColorAria: "Пользовательский цвет акцента",
    Designer_Settings_AccentHint: "Цвета акцента автоматически корректируются для контраста на темных сайтах, поэтому форма остается читаемой при любой теме страницы.",
    Designer_Settings_ShowHeader: "Показывать заголовок формы",
    Designer_Settings_HeaderIcon: "Значок заголовка",
    Designer_Settings_TabAfterSubmit: "После отправки",
    Designer_Settings_SubmitButtonText: "Текст кнопки отправки",
    Designer_Settings_SubmitPlaceholder: "Отправить",
    Designer_Settings_ThankYouTitle: "Заголовок благодарности",
    Designer_Settings_ThankYouPlaceholder: "Спасибо!",
    Designer_Settings_ThankYouMessage: "Сообщение с благодарностью",
    Designer_Settings_ShowSubmitAnother: "Показывать кнопку \"Отправить еще один ответ\"",
    Designer_Settings_TabNotifications: "Уведомления",
    Designer_Settings_EmailEachResponseTo: "Отправлять каждый ответ по эл. почте",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "Пользователи вашей организации получают каждый ответ по эл. почте со ссылкой на элемент списка",
    Designer_Settings_RespondentReceipt: "Отправлять респондентам копию их ответов по эл. почте",
    Designer_Settings_NotificationsInfo: "Уведомления используются через собственную почтовую службу SharePoint, поэтому получатели должны быть пользователями вашей организации. Внешние адреса автоматически отбрасываются.",
    Designer_Settings_TabAccess: "Доступ",
    Designer_Settings_OpenFrom: "Открыть с",
    Designer_Settings_OpenImmediately: "Открыть сразу",
    Designer_Settings_CloseAfter: "Закрыть после",
    Designer_Settings_NeverClose: "Никогда не закрывать",
    Designer_Settings_ClearDates: "Очистить даты",
    Designer_Settings_DatesInverted: "Дата закрытия совпадает с датой открытия или раньше нее, поэтому форма никогда не будет принимать ответы.",
    Designer_Settings_MaxResponses: "Остановить после такого количества ответов",
    Designer_Settings_NoLimit: "Без ограничений",
    Designer_Settings_OneResponsePerPerson: "Разрешить только один ответ от одного человека",
    Designer_Settings_AllowSaveDraft: "Разрешить респондентам сохранять черновик и завершать позже",
    Designer_Settings_ClosedMessage: "Сообщение, отображаемое при закрытии формы",
    Designer_Settings_ClosedMessagePlaceholder: "Эта форма больше не принимает ответы.",
    Designer_Settings_AccessInfo: "Эти ограничения применяются самой формой, а не SharePoint. Любой, кто имеет разрешение на добавление элементов в список ответов, все равно может добавить ответ напрямую через список.",
    Designer_Field_StyleInfo: "Информация (акцент)",
    Designer_Field_StyleSuccess: "Успех (зеленый)",
    Designer_Field_StyleWarning: "Предупреждение (желтый)",
    Designer_Field_StylePlain: "Обычный текст",
    Designer_Field_StyleDivider: "Разделительная линия",
    Designer_Field_IconStars: "Звезды",
    Designer_Field_IconHearts: "Сердца",
    Designer_Field_IconThumbs: "Палец вверх",
    Designer_Field_FormatPlain: "Обычное число",
    Designer_Field_FormatCurrency: "Денежный",
    Designer_Field_FormatPercent: "Процентный",
    Designer_Field_UntitledQuestion: "Вопрос без названия",
    Designer_Field_DeletedQuestion: "удаленный вопрос",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} и {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "ИЛИ",
    Designer_Rule_JoinAll: "И",
    Designer_Rule_Preview: "Отображается, когда {conditions}.",
    Designer_Field_Yes: "Да",
    Designer_Field_No: "Нет",
    Designer_Field_When: "Когда",
    Designer_Field_SelectValue: "Выберите значение",
    Designer_Field_DateValuePlaceholder: "ГГГГ-ММ-ДД или \"today\"",
    Designer_Field_ValuePlaceholder: "Значение",
    Designer_Field_UpperBound: "Верхняя граница",
    Designer_Field_RemoveCondition: "Удалить это условие",
    Designer_Field_FormulaInvalid: "Не удается вычислить эту формулу. Проверьте скобки и операторы.",
    Designer_Field_FormulaMissing: "Эти вопросы не существуют: {names}.",
    Designer_Field_FormulaPreview: "Если все входные значения равны 10, отображается {value}.",
    Designer_Field_HintYesNo: "Используйте \"yes\" или \"no\"",
    Designer_Field_HintMultiDefault: "Разделяйте несколько значений по умолчанию символом ;",
    Designer_Field_HintSingleDefault: "Должно совпадать с одним из вариантов",
    Designer_Field_HintDate: "Используйте \"today\" или дату вида 2026-03-01",
    Designer_Field_HintTime: "Используйте \"now\" или время вида 09:30",
    Designer_Field_QuestionSettings: "Параметры вопроса",
    Designer_Field_Appearance: "Оформление",
    Designer_Field_Style: "Стиль",
    Designer_Field_ImageUrl: "URL-адрес изображения (необязательно)",
    Designer_Field_Content: "Содержимое",
    Designer_Field_BasicFormatting: "Допускается базовое форматирование: полужирный, курсив, списки и ссылки.",
    Designer_Field_TabOptions: "Варианты",
    Designer_Field_TabBranching: "Ветвление",
    Designer_Field_BranchingNeedsQuestion: "Сначала добавьте другой вопрос: для ветвления нужен вопрос, от которого оно зависит.",
    Designer_Field_BranchingToggle: "Показывать этот вопрос, только если другие ответы совпадают",
    Designer_Field_Match: "Совпадение",
    Designer_Field_MatchAll: "все из этих",
    Designer_Field_MatchAny: "любое из этих",
    Designer_Field_AddCondition: "Добавить условие",
    Designer_Field_TabValidation: "Проверка",
    Designer_Field_HelpText: "Текст справки",
    Designer_Field_HelpTextPlaceholder: "Отображается под названием вопроса",
    Designer_Field_CheckboxLabel: "Подпись флажка",
    Designer_Field_Placeholder: "Заполнитель",
    Designer_Field_DefaultAnswer: "Ответ по умолчанию",
    Designer_Field_RequiredMessage: "Пользовательское сообщение об обязательном поле",
    Designer_Field_RequiredMessagePlaceholder: "{title}: обязательное поле",
    Designer_Field_ThisQuestion: "Этот вопрос",
    Designer_Field_RequiredMessageDescription: "Отображается вместо стандартного сообщения, если на этот вопрос не дан ответ",
    Designer_Field_ReadOnly: "Только для чтения (ответ можно получить только из предзаполненной ссылки)",
    Designer_Field_ValidationRules: "Правила проверки",
    Designer_Field_MaxLength: "Максимальная длина",
    Designer_Field_Pattern: "Должно соответствовать шаблону",
    Designer_Field_PatternDescription: "Регулярное выражение. Оставьте пустым, чтобы не проверять шаблон.",
    Designer_Field_PatternMessage: "Сообщение при несоответствии шаблону",
    Designer_Field_PatternMessagePlaceholder: "Этот ответ не соответствует ожидаемому формату",
    Designer_Field_Format: "Формат",
    Designer_Field_UnitSuffix: "Единица измерения после значения",
    Designer_Field_UnitSuffixPlaceholder: "кг, ч, шт…",
    Designer_Field_Minimum: "Минимум",
    Designer_Field_Maximum: "Максимум",
    Designer_Field_Decimals: "Десятичные знаки",
    Designer_Field_Formula: "Формула",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Ссылайтесь на другие вопросы по их тексту в фигурных скобках. Поддерживаются + - * / ( ) и round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Доступные вопросы: {questions}",
    Designer_Field_NoneYet: "пока нет",
    Designer_Field_Step: "Шаг",
    Designer_Field_From: "От",
    Designer_Field_To: "До",
    Designer_Field_LowLabel: "Подпись на нижнем конце",
    Designer_Field_LowLabelPlaceholder: "Совсем не вероятно",
    Designer_Field_HighLabel: "Подпись на верхнем конце",
    Designer_Field_HighLabelPlaceholder: "Чрезвычайно вероятно",
    Designer_Field_SummarizeAs: "Обобщать как",
    Designer_Field_SummarizeAverage: "Среднее и распределение",
    Designer_Field_SummarizeNps: "Индекс потребительской лояльности NPS (нужна шкала 0–10)",
    Designer_Field_NpsWarning: "Индекс потребительской лояльности NPS имеет смысл только для шкалы 0–10. Задайте значения От = 0 и До = 10.",
    Designer_Field_NumberOfIcons: "Количество значков",
    Designer_Field_Icon: "Значок",
    Designer_Field_AllowHalf: "Разрешить половинные значения",
    Designer_Field_ShowOptionsAs: "Показывать варианты как",
    Designer_Field_DisplayButtons: "Встроенные кнопки",
    Designer_Field_DisplayDropdown: "Раскрывающийся список",
    Designer_Field_DisplayAutomatic: "Автоматически (в строке до 6 вариантов)",
    Designer_Field_AllowOther: "Добавить вариант \"Другое\" для ввода",
    Designer_Field_OtherLabel: "Подпись для варианта \"Другое\"",
    Designer_Field_OtherPlaceholder: "Другое",
    Designer_Field_ShuffleOptions: "Перемешивать порядок вариантов для каждого респондента",
    Designer_Field_MinSelections: "Минимум выбранных вариантов",
    Designer_Field_MaxSelections: "Максимум выбранных вариантов",
    Designer_Field_SourceList: "Исходный список",
    Designer_Field_ChooseList: "Выберите список",
    Designer_Field_LookupColumn: "Столбец для чтения вариантов",
    Designer_Field_ChooseColumn: "Выберите столбец",
    Designer_Field_ChooseListFirst: "Сначала выберите список",
    Designer_Field_LookupFilter: "Фильтр (необязательно)",
    Designer_Field_LookupFilterDescription: "Фильтр OData, ограничивающий элементы источника, которые становятся вариантами",
    Designer_Field_LookupInfo: "В ответах сохраняется текст варианта, а не ссылка на исходный элемент, поэтому ответы остаются читаемыми, даже если исходный список позже изменится.",
    Designer_Field_ConsentText: "Условия, отображаемые над флажком",
    Designer_Field_AllowMultiplePeople: "Разрешить выбор нескольких людей",
    Designer_Field_AllowGroups: "Разрешить также группы",
    Designer_Field_IncludeTime: "Включить время суток",
    Designer_Field_TimeStep: "Шаг времени (минуты)",
    Designer_Field_MaxFiles: "Максимум файлов",
    Designer_Field_MaxFileSize: "Макс. размер каждого (МБ)",
    Designer_Field_AcceptedTypes: "Допустимые типы файлов",
    Designer_Field_AcceptedTypesDescription: "Расширения через запятую. Оставьте пустым, чтобы принимать все, что разрешает SharePoint.",
    Designer_Field_FilesInfo: "Файлы сохраняются как вложения элемента ответа. SharePoint блокирует некоторые расширения (например, .exe) независимо от того, что вы разрешите здесь.",
    Designer_Field_Rows: "Строки",
    Designer_Field_ProvisionedNote: "У этого вопроса уже есть столбец списка ({name}). Параметры, изменяющие тип столбца, заблокированы: дублируйте вопрос, если нужен другой тип.",
    Designer_Category_Text: "Текст",
    Designer_Category_Choice: "Выбор",
    Designer_Category_Scales: "Шкалы",
    Designer_Category_Date: "Дата",
    Designer_Category_People: "Люди",
    Designer_Category_Advanced: "Дополнительно",
    Designer_Category_Layout: "Макет",
    Designer_Menu_CommonPresets: "Часто используемые шаблоны",
    Designer_Menu_AllTypes: "Все типы вопросов",
    Designer_Menu_ChangeType: "Изменить тип",
    Designer_Menu_TypeLockedTitle: "Столбец списка уже существует, поэтому тип заблокирован. Дублируйте вопрос, чтобы изменить его.",
    Designer_Menu_MoreSettings: "Ветвление, проверка и другое",
    Designer_Menu_InsertBelow: "Вставить вопрос ниже",
    Designer_Card_Duplicate: "Дублировать",
    Designer_Card_DeleteQuestion: "Удалить вопрос",
    Designer_Outline_Aria: "Структура вопросов",
    Designer_Outline_QuestionCountOne: "{count} вопрос",
    Designer_Outline_QuestionCountOther: "{count} вопросов",
    Designer_Outline_IssuesTitle: "Проблем для проверки: {count}",
    Designer_Outline_Find: "Найти вопрос",
    Designer_Outline_Empty: "Вопросов пока нет.",
    Designer_Section_DefaultTitle: "Раздел {number}",
    Designer_Card_Question: "Вопрос",
    Designer_Card_BranchingTitle: "Этот вопрос отображается только при совпадении правила ветвления",
    Designer_Card_BranchingChip: "Ветвление",
    Designer_Card_LiveTitle: "Столбец списка существует, поэтому тип заблокирован",
    Designer_Card_LiveChip: "Активен",
    Designer_Card_CheckChip: "Проверить",
    Designer_Option_Placeholder: "Вариант {number}",
    Designer_Option_LabelAria: "Подпись варианта {number}",
    Designer_Option_ImageUrl: "URL-адрес изображения",
    Designer_Option_ImageUrlAria: "URL-адрес изображения варианта {number}",
    Designer_Option_Remove: "Удалить вариант",
    Designer_Option_RemoveAria: "Удалить вариант {number}",
    Designer_Option_Add: "Добавить вариант",
    Designer_Option_OtherHint: "Респонденты также могут ввести собственный ответ с подписью “{label}”.",
    Designer_Option_OtherFallback: "Другое",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Удалить",
    Designer_Grid_RemoveAria: "Удалить {label} {number}",
    Designer_Grid_Statements: "Утверждения",
    Designer_Grid_Scale: "Шкала",
    Designer_Grid_AddStatement: "Добавить утверждение",
    Designer_Grid_AddScale: "Добавить шкалу",
    Designer_Width_Full: "На всю ширину",
    Designer_Width_Half: "Половина ширины",
    Designer_Width_Third: "Треть ширины",
    Designer_Width_Aria: "Ширина вопроса",
    Designer_Card_BlockLabelPlaceholder: "Подпись блока (не отображается респондентам)",
    Designer_Card_QuestionText: "Текст вопроса",
    Designer_Card_MoveUp: "Переместить вверх",
    Designer_Card_MoveQuestionUp: "Переместить вопрос вверх",
    Designer_Card_MoveDown: "Переместить вниз",
    Designer_Card_MoveQuestionDown: "Переместить вопрос вниз",
    Designer_Card_DuplicateQuestion: "Дублировать вопрос",
    Designer_Card_MultipleAnswers: "Несколько ответов",
    Designer_Card_Required: "Обязательный",
    Designer_Card_MoreOptions: "Дополнительные параметры",
    Designer_Card_MoreOptionsAria: "Дополнительные параметры для этого вопроса",
    Designer_Canvas_FormTitle: "Название формы",
    Designer_Canvas_DescriptionPlaceholder: "Добавьте описание (необязательно)",
    Designer_Canvas_DescriptionAria: "Описание формы",
    Designer_Canvas_EmptyTitle: "Добавьте первый вопрос",
    Designer_Canvas_EmptyBody: "Выберите тип вопроса, чтобы начать. Вы можете менять порядок вопросов перетаскиванием и добавлять ветвление, чтобы люди видели только то, что к ним относится.",
    Designer_Section_Chip: "Раздел {number} из {total}",
    Designer_Section_TitlePlaceholder: "Название раздела",
    Designer_Section_TitleAria: "Название раздела {number}",
    Designer_Section_DescriptionPlaceholder: "Описание (необязательно)",
    Designer_Section_DescriptionAria: "Описание раздела {number}",
    Designer_Section_MoveUp: "Переместить раздел вверх",
    Designer_Section_MoveDown: "Переместить раздел вниз",
    Designer_Section_Delete: "Удалить раздел",
    Designer_Card_DragToReorder: "Перетащите для изменения порядка",
    Designer_Card_ReorderAria: "Изменить порядок: {title}",
    Designer_Card_ReorderFallback: "вопрос",
    Designer_Canvas_AddNew: "Добавить",
    Designer_Canvas_AddSection: "Добавить раздел",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Улица и дом",
    Form_Address_Street2Placeholder: "Квартира, офис и т. д. (необязательно)",
    Form_Address_CityPlaceholder: "Город",
    Form_Address_StatePlaceholder: "Область / регион",
    Form_Address_PostalCodePlaceholder: "Почтовый индекс",
    Form_Address_CountryPlaceholder: "Страна",
    Form_Address_StreetAria: "улица и дом",
    Form_Address_Street2Aria: "вторая строка адреса",
    Form_Address_CityAria: "город",
    Form_Address_StateAria: "область или регион",
    Form_Address_PostalCodeAria: "почтовый индекс",
    Form_Address_CountryAria: "страна",
    Form_Consent_DefaultLabel: "Я согласен",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "Отвечено строк: {answered} из {total}",
    Form_Lookup_LoadError: "Не удалось загрузить варианты для этого вопроса.",
    Form_Lookup_Loading: "Загрузка вариантов…",
    Form_Lookup_SelectOptionsPlaceholder: "Выберите варианты",
    Form_Lookup_SelectOptionPlaceholder: "Выберите вариант",
    Form_Person_Placeholder: "Начните вводить имя…",
    Form_Person_SuggestedPeopleAndGroups: "Рекомендуемые люди и группы",
    Form_Person_SuggestedPeople: "Рекомендуемые люди",
    Form_Person_NoPeopleOrGroups: "Люди или группы не найдены",
    Form_Person_NoPeople: "Люди не найдены",
    Form_Person_Searching: "Поиск…",
    Form_Ranking_Moved: "{item} перемещен на позицию {position} из {total}",
    Form_Ranking_MoveUp: "Переместить вверх",
    Form_Ranking_MoveDown: "Переместить вниз",
    Form_Ranking_MoveItemUpAria: "Переместить {item} вверх",
    Form_Ranking_MoveItemDownAria: "Переместить {item} вниз",
    Form_Rating_ValueText: "{value} из {max}",
    Form_Rating_NotRated: "Нет оценки",
    Form_Rating_Clear: "Очистить оценку",
    Form_RichText_Bold: "Полужирный",
    Form_RichText_Italic: "Курсив",
    Form_RichText_Underline: "Подчеркнутый",
    Form_RichText_BulletedList: "Маркированный список",
    Form_RichText_NumberedList: "Нумерованный список",
    Form_RichText_ClearFormatting: "Очистить форматирование",
    Form_RichText_ToolbarAria: "Форматирование текста",
    Form_File_SizeBytes: "{size} Б",
    Form_File_SizeKb: "{size} КБ",
    Form_File_SizeMb: "{size} МБ",
    Form_File_SkippedLimit: "Файл \"{name}\" пропущен: ограничение — {limit}.",
    Form_File_TypeNotAccepted: "Тип файла \"{name}\" не разрешен.",
    Form_File_TooLarge: "Файл \"{name}\" больше {size} МБ.",
    Form_File_AlreadyAttached: "Файл \"{name}\" уже вложен.",
    Form_File_ReadError: "Не удалось прочитать один из файлов. Попробуйте вложить его еще раз.",
    Form_File_HintMaxSize: "до {size} МБ каждый",
    Form_File_HintOneFile: "1 файл",
    Form_File_HintMaxFiles: "макс. файлов: {count}",
    Form_File_Reading: "Чтение файлов…",
    Form_File_DropPrompt: "Перетащите файлы сюда или щелкните для выбора",
    Form_File_Remove: "Удалить {name}",
    Form_Signature_Alt: "Подпись",
    Form_Signature_AriaSigned: "{label} — подписано",
    Form_Signature_AriaEmpty: "{label} — пусто",
    Form_Signature_Clear: "Очистить",
    Form_Signature_Signed: "Подписано",
    Form_Signature_Prompt: "Распишитесь выше мышью, пером или пальцем",
    Form_Time_Placeholder: "Выберите время",
    Form_Field_DatePlaceholder: "Выберите дату",
    Form_Field_TimeAriaWithLabel: "{label} — время",
    Form_Field_TimeAria: "Время",
    Form_Field_OtherDefault: "Другое",
    Form_Field_SelectOptionsPlaceholder: "Выберите варианты",
    Form_Field_PleaseSpecify: "Укажите, пожалуйста",
    Form_Field_OtherSpecifyAria: "{label} — укажите, пожалуйста",
    Form_Field_SelectOptionPlaceholder: "Выберите вариант",
    Form_Field_Yes: "Да",
    Form_Field_No: "Нет",
    Form_Field_SliderHint: "Перетащите ползунок, чтобы ответить",
    Form_Field_WebAddressAriaWithLabel: "{label} — веб-адрес",
    Form_Field_WebAddressAria: "Веб-адрес",
    Form_Field_DisplayTextPlaceholder: "Отображаемый текст (необязательно)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — отображаемый текст",
    Form_Field_DisplayTextAria: "Отображаемый текст",
    Form_Field_ChooseBetween: "Выберите от {min} до {max}",
    Form_Field_ChooseAtLeast: "Выберите не менее {min}",
    Form_Field_ChooseUpTo: "Выберите не более {max}",
    Form_Field_SelectedCount: "Выбрано: {count}",
    Form_Field_RequiredAria: "(обязательно)",
    Form_Submit_SaveError: "Не удалось сохранить ваш ответ. Убедитесь, что форма опубликована из конструктора и у вас есть разрешение на добавление элементов в список ответов.",
    Form_Empty_Message: "В этой форме пока нет вопросов. Владелец формы может добавить их на вкладке \"Вопросы\".",
    Form_Checking: "Проверка формы…",
    Form_Closed_NotYetOpen: "Еще не открыта",
    Form_Closed_AlreadyAnswered: "Ответ уже дан",
    Form_Closed_Title: "Форма закрыта",
    Form_Confirmation_PreviewNotice: "Это был предварительный просмотр: ничего не сохранено в списке ответов.",
    Form_Confirmation_PreviewAgain: "Просмотреть снова",
    Form_Confirmation_SubmitAnother: "Отправить еще один ответ",
    Form_Wizard_StepFallback: "Шаг {step}",
    Form_Wizard_StepsAria: "Шаги формы",
    Form_Wizard_StepOf: "Шаг {step} из {total}",
    Form_ErrorSummary_Title: "Проверьте ответы ({count}):",
    Form_ErrorSummary_UntitledQuestion: "Вопрос без названия",
    Form_ErrorSummary_Question: "Вопрос",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Назад",
    Form_Nav_Next: "Далее",
    Form_Draft_Saving: "Сохранение…",
    Form_Draft_Saved: "Черновик сохранен",
    Form_Draft_SaveAndFinishLater: "Сохранить и завершить позже",
    Form_Draft_NotSaved: "Черновик не сохранен",
    Form_Submit_Preview: "Отправить (просмотр)",
    Form_Submit_Button: "Отправить",
    Form_Response_NoAnswer: "Нет ответа",
    Form_Signature_TypeLabel: "Введите ваше полное имя",
    Form_Signature_TypeInstead: "Введите имя вместо подписи",
    Form_Signature_DrawInstead: "Нарисовать подпись",
    Form_Edit_Button: "Изменить предыдущий ответ",
    Form_Edit_Available: "Вы уже отправили ответ. Вы можете изменить его, вместо того чтобы отправлять новый.",
    Form_Edit_Banner: "Вы изменяете свой предыдущий ответ.",
    Form_Edit_Save: "Обновить ответ",
    Form_Edit_UpdatedTitle: "Ответ обновлен",
    Form_Edit_UpdatedMessage: "Ваши изменения сохранены.",
    Form_Edit_LoadError: "Не удалось загрузить ваш предыдущий ответ. Повторите попытку.",
    Form_Draft_MissingFiles: "Прикрепите повторно: {names}. Эти файлы не удалось восстановить.",
    Form_Attachments_Failed: "Ваши ответы сохранены, но не удалось отправить эти вложения: {names}. Повторите попытку или свяжитесь с владельцем формы.",
    Logic_ThisQuestion: "Этот вопрос",
    Logic_Required: "Поле \"{label}\" обязательно для заполнения",
    Logic_RequiredConsent: "Установите флажок, чтобы продолжить",
    Logic_RequiredFile: "Прикрепите хотя бы один файл",
    Logic_RequiredSignature: "Добавьте свою подпись",
    Logic_RequiredLikert: "Ответьте на каждую строку",
    Logic_InvalidEmail: "Введите допустимый адрес эл. почты",
    Logic_InvalidPhone: "Введите допустимый номер телефона",
    Logic_InvalidUrl: "Введите допустимый веб-адрес, начинающийся с http:// или https://",
    Logic_MinValue: "Значение должно быть не меньше {value}",
    Logic_MaxValue: "Значение должно быть не больше {value}",
    Logic_MaxLength: "Максимальная длина: {max} симв.",
    Logic_ChooseAtLeastOne: "Выберите не менее {count} варианта",
    Logic_ChooseAtLeastMany: "Выберите не менее {count} вариантов",
    Logic_ChooseAtMostOne: "Выберите не более {count} варианта",
    Logic_ChooseAtMostMany: "Выберите не более {count} вариантов",
    Logic_LikertRemaining: "Ответьте на каждую строку (осталось: {count})",
    Logic_MaxFilesOne: "Прикрепите не более {count} файла",
    Logic_MaxFilesMany: "Прикрепите не более {count} файлов",
    Logic_FileTooLarge: "Файл \"{name}\" больше {size} МБ",
    Logic_FileTypeNotAccepted: "Файл \"{name}\" имеет неподдерживаемый тип ({types})",
    Logic_AddressRequired: "Введите как минимум улицу и город",
    Logic_PatternDefault: "Ответ не соответствует ожидаемому формату",
    Logic_Yes: "Да",
    Logic_No: "Нет",
    Logic_Agreed: "Согласен",
    Logic_NotAgreed: "Не согласен",
    Logic_Signed: "Подписано",
    Logic_NoAnswer: "(нет ответа)",
    Logic_Unknown: "(неизвестно)",
    Logic_OtherSlice: "Другое ({count})",
    Logic_CsvResponseId: "Идентификатор ответа",
    Logic_CsvSubmitted: "Отправлено",
    Logic_CsvSubmittedBy: "Отправил",
    Logic_EmailQuestion: "Вопрос",
    Logic_EmailViewItem: "Открыть в Microsoft Lists",
    Logic_EmailFooter: "Отправлено автоматически приложением Smart Forms.",
    Logic_ClosedDefault: "Эта форма больше не принимает ответы.",
    Logic_NotYetOpen: "Эта форма откроется {date}.",
    Logic_AlreadyResponded: "Вы уже ответили на эту форму. Спасибо!",
    Logic_UntitledQuestion: "Вопрос без названия",
    Logic_Issue_NoQuestions: "Добавьте хотя бы один вопрос перед сбором ответов.",
    Logic_Issue_NoTitle: "У вопроса нет текста — при публикации ему будет автоматически присвоено имя.",
    Logic_Issue_DuplicateTitle: "Текст \"{label}\" совпадает с другим вопросом, из-за чего результаты труднее читать.",
    Logic_Issue_NeedTwoOptions: "Для \"{label}\" необходимо как минимум два варианта.",
    Logic_Issue_ImageNoImage: "У \"{label}\" есть варианты без изображения — они будут показаны как текстовые плитки.",
    Logic_Issue_LikertNeedRow: "Для \"{label}\" необходима хотя бы одна строка.",
    Logic_Issue_LikertNeedColumns: "Для \"{label}\" необходимо как минимум два столбца шкалы.",
    Logic_Issue_NoLookupList: "Для \"{label}\" не выбран список-источник.",
    Logic_Issue_NoFormula: "У \"{label}\" нет формулы.",
    Logic_Issue_BadFormula: "У \"{label}\" формула, которую невозможно вычислить. Проверьте скобки и операторы.",
    Logic_Issue_MissingRefs: "\"{label}\" ссылается на несуществующие вопросы: {names}.",
    Logic_Issue_BadPattern: "У \"{label}\" недопустимый шаблон проверки.",
    Logic_Issue_BrokenRule: "У \"{label}\" есть правило ветвления, указывающее на удаленный вопрос.",
    Logic_Issue_SelfRule: "У \"{label}\" есть правило ветвления, ссылающееся на сам вопрос.",
    Logic_Issue_RuleMismatch: "У \"{label}\" есть правило ветвления, которое больше не подходит вопросу, от которого оно зависит.",
    Logic_Issue_RequiredReadOnly: "\"{label}\" одновременно обязателен и доступен только для чтения, поэтому ответить на него можно только через ссылку с предзаполнением.",
    Logic_Issue_EmptySection: "В разделе нет вопросов, он будет пропущен.",
    Logic_Issue_CloseBeforeOpen: "Дата закрытия совпадает с датой открытия или предшествует ей, поэтому форма никогда не будет принимать ответы.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Письма об утверждении включены, но этап утверждения отключен.",
    Logic_Op_equals: "равно",
    Logic_Op_notEquals: "не равно",
    Logic_Op_contains: "содержит",
    Logic_Op_notContains: "не содержит",
    Logic_Op_notEmpty: "есть ответ",
    Logic_Op_empty: "нет ответа",
    Logic_Op_greaterThan: "больше",
    Logic_Op_greaterOrEqual: "не меньше",
    Logic_Op_lessThan: "меньше",
    Logic_Op_lessOrEqual: "не больше",
    Logic_Op_between: "между",
    Logic_Op_before: "раньше",
    Logic_Op_after: "позже",
    Logic_Type_Text: "Короткий ответ",
    Logic_TypeDesc_Text: "Одна строка текста",
    Logic_Category_Text: "Текст",
    Logic_Type_MultilineText: "Длинный ответ",
    Logic_TypeDesc_MultilineText: "Несколько строк обычного текста",
    Logic_Type_RichText: "Форматированный текст",
    Logic_TypeDesc_RichText: "Полужирный шрифт, списки и ссылки",
    Logic_Type_Choice: "Выбор",
    Logic_TypeDesc_Choice: "Выбор из списка вариантов",
    Logic_Category_Choice: "Выбор",
    Logic_Type_ImageChoice: "Выбор изображения",
    Logic_TypeDesc_ImageChoice: "Выбор из плиток с изображениями",
    Logic_Type_Lookup: "Подстановка из списка",
    Logic_TypeDesc_Lookup: "Варианты считываются из другого списка SharePoint в реальном времени",
    Logic_Type_YesNo: "Да / Нет",
    Logic_TypeDesc_YesNo: "Простой переключатель",
    Logic_Type_Consent: "Согласие",
    Logic_TypeDesc_Consent: "Флажок, который респондент должен установить, чтобы продолжить",
    Logic_Type_Ranking: "Ранжирование",
    Logic_TypeDesc_Ranking: "Перетащите варианты в порядке предпочтения",
    Logic_Type_Rating: "Оценка",
    Logic_TypeDesc_Rating: "Звезды, сердечки или \"нравится\"",
    Logic_Category_Scales: "Шкалы",
    Logic_Type_Scale: "Шкала мнений",
    Logic_TypeDesc_Scale: "Числовая шкала с подписанными краями",
    Logic_Type_Slider: "Ползунок",
    Logic_TypeDesc_Slider: "Значение на шкале с ползунком",
    Logic_Type_Likert: "Сетка Ликерта",
    Logic_TypeDesc_Likert: "Оценка нескольких утверждений по одной общей шкале",
    Logic_Type_Number: "Число",
    Logic_TypeDesc_Number: "Обычное, денежное или процентное",
    Logic_Category_Advanced: "Дополнительно",
    Logic_Type_Calculated: "Вычисляемое",
    Logic_TypeDesc_Calculated: "Итог только для чтения, вычисляемый на основе других ответов",
    Logic_Type_Date: "Дата",
    Logic_TypeDesc_Date: "Календарная дата, при необходимости со временем",
    Logic_Category_Date: "Дата",
    Logic_Type_Time: "Время",
    Logic_TypeDesc_Time: "Только время суток",
    Logic_Type_Person: "Пользователь",
    Logic_TypeDesc_Person: "Выбор пользователя из организации",
    Logic_Category_People: "Пользователи",
    Logic_Type_Email: "Эл. почта",
    Logic_TypeDesc_Email: "Адрес эл. почты с проверкой",
    Logic_Type_Phone: "Телефон",
    Logic_TypeDesc_Phone: "Номер телефона с проверкой",
    Logic_Type_Address: "Адрес",
    Logic_TypeDesc_Address: "Улица, город, почтовый индекс и страна",
    Logic_Type_Hyperlink: "Ссылка",
    Logic_TypeDesc_Hyperlink: "Веб-адрес",
    Logic_Type_FileUpload: "Отправка файла",
    Logic_TypeDesc_FileUpload: "Прикрепление одного или нескольких файлов к ответу",
    Logic_Type_Signature: "Подпись",
    Logic_TypeDesc_Signature: "Подпись мышью, пером или пальцем",
    Logic_Type_Content: "Текстовый блок",
    Logic_TypeDesc_Content: "Инструкции или изображение — ответ не собирается",
    Logic_Category_Layout: "Макет",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Насколько вероятно, что вы порекомендуете…",
    Logic_Preset_satisfaction: "Удовлетворенность (1–5)",
    Logic_PresetDesc_satisfaction: "От \"совсем не удовлетворен\" до \"полностью удовлетворен\"",
    Logic_Preset_currency: "Валюта",
    Logic_PresetDesc_currency: "Денежная сумма",
    Logic_Preset_percent: "Процент",
    Logic_PresetDesc_percent: "Процентное значение",
    Logic_Template_blank_Name: "Пустая форма",
    Logic_Template_blank_Description: "Начать с нуля",
    Logic_Template_feedback_Name: "Отзыв клиента",
    Logic_Template_feedback_Description: "NPS, оценки и открытые комментарии",
    Logic_Template_event_Name: "Регистрация на мероприятие",
    Logic_Template_event_Description: "Данные участников, сеансы и пищевые предпочтения",
    Logic_Template_itrequest_Name: "Запрос в ИТ-службу",
    Logic_Template_itrequest_Description: "Запросы по категориям с приоритетом и вложениями",
    Logic_Template_expense_Name: "Заявка на возмещение расходов",
    Logic_Template_expense_Description: "Позиции, квитанции и вычисляемый итог",
    Logic_Template_pulse_Name: "Пульс-опрос сотрудников",
    Logic_Template_pulse_Description: "Сетка Ликерта, шкала вовлеченности и примечание об анонимности",
    Logic_Template_safety_Name: "Проверка безопасности",
    Logic_Template_safety_Description: "Контрольный список, фотографии и подпись",
    Logic_Template_booking_Name: "Бронирование помещения или ресурса",
    Logic_Template_booking_Description: "Выбор ресурса из списка с временным интервалом",
    Charts_ColumnChartAria: "Столбчатая диаграмма, категорий: {count}",
    Charts_DonutChartAria: "Кольцевая диаграмма, категорий: {count}",
    Charts_NoAnswers: "Ответов пока нет.",
    Charts_NoResponses: "Ответов пока нет.",
    Charts_Responses: "Ответы",
    Charts_ResponsesOverTime: "Ответы за период",
    Responses_Chart_Answer: "Ответ",
    Responses_Chart_Average: "Среднее",
    Responses_Chart_AverageOf: "Среднее из {count}",
    Responses_Chart_AveragePosition: "Средняя позиция",
    Responses_Chart_AverageRange: "Среднее (1–{max})",
    Responses_Chart_AvgValue: "сред. {value}",
    Responses_Chart_Detractors: "Критики (0–6)",
    Responses_Chart_Max: "Макс.",
    Responses_Chart_Maximum: "Максимум",
    Responses_Chart_Median: "Медиана",
    Responses_Chart_MentionOne: "{count} упоминание",
    Responses_Chart_MentionOther: "{count} упоминаний",
    Responses_Chart_Min: "Мин.",
    Responses_Chart_Minimum: "Минимум",
    Responses_Chart_NoAnswers: "Ответов пока нет.",
    Responses_Chart_NoNumeric: "Числовых ответов пока нет.",
    Responses_Chart_NoRankings: "Рейтингов пока нет.",
    Responses_Chart_NoScores: "Оценок пока нет.",
    Responses_Chart_NotEnoughText: "Пока недостаточно текста для сводки.",
    Responses_Chart_NpsScore: "Оценка NPS",
    Responses_Chart_Option: "Вариант",
    Responses_Chart_Passives: "Нейтралы (7–8)",
    Responses_Chart_Promoters: "Промоутеры (9–10)",
    Responses_Chart_ResponseOne: "ответ",
    Responses_Chart_ResponseOther: "ответов",
    Responses_Chart_Responses: "Ответы",
    Responses_Chart_ShowingAnswers: "Показано ответов: {shown} из {total}.",
    Responses_Chart_Statement: "Утверждение",
    Responses_Chart_Statistic: "Статистический показатель",
    Responses_Chart_StdDev: "Станд. откл.",
    Responses_Chart_StdDeviation: "Стандартное отклонение",
    Responses_Chart_Total: "Итого",
    Responses_Chart_Value: "Значение",
    Responses_Dashboard_AllHidden: "Все вопросы скрыты на панели мониторинга. Используйте “Показать скрытые вопросы”, чтобы вернуть их.",
    Responses_Dashboard_AnsweredOf: "Отвечено: {answered} из {total}",
    Responses_Dashboard_AnsweredOfPinned: "Отвечено: {answered} из {total} · закреплено",
    Responses_Dashboard_AveragedAcrossResponses: "Среднее по ответам",
    Responses_Dashboard_ByDay: "По дням",
    Responses_Dashboard_ByMonth: "По месяцам",
    Responses_Dashboard_ByWeek: "По неделям",
    Responses_Dashboard_ChartAuto: "Автоматически",
    Responses_Dashboard_ChartBars: "Полосы",
    Responses_Dashboard_ChartColumns: "Столбцы",
    Responses_Dashboard_ChartDonut: "Кольцевая",
    Responses_Dashboard_ChartGauge: "Шкала",
    Responses_Dashboard_ChartHistogram: "Гистограмма",
    Responses_Dashboard_ChartOptions: "Параметры диаграммы",
    Responses_Dashboard_ChartOptionsFor: "Параметры диаграммы: {title}",
    Responses_Dashboard_ChartStatistics: "Статистика",
    Responses_Dashboard_ChartTable: "Таблица",
    Responses_Dashboard_ChartWordFrequency: "Частота слов",
    Responses_Dashboard_EmptyBody: "Когда люди начнут отвечать, эта панель заполнится автоматически: ключевые показатели, временная шкала ответов и диаграммы для важных вопросов.",
    Responses_Dashboard_EmptyTitle: "Ответов пока нет",
    Responses_Dashboard_Hide: "Скрыть с панели мониторинга",
    Responses_Dashboard_Highlights: "Основное",
    Responses_Dashboard_Last7Days: "Последние 7 дней",
    Responses_Dashboard_LatestDate: "Последний: {date}",
    Responses_Dashboard_MedianTimeToComplete: "Медианное время заполнения",
    Responses_Dashboard_NoPriorWeek: "Нет предыдущей недели для сравнения",
    Responses_Dashboard_OneEach: "По одному",
    Responses_Dashboard_Pin: "Закрепить на панели мониторинга",
    Responses_Dashboard_QuestionFallback: "вопрос",
    Responses_Dashboard_QuestionsAnswered: "Отвечено вопросов",
    Responses_Dashboard_RecordedOnSubmit: "Записывается при отправке",
    Responses_Dashboard_RepeatResponses: "Повторных ответов: {count}",
    Responses_Dashboard_ResponsesOverTime: "Ответы за период",
    Responses_Dashboard_ShowHidden: "Показать скрытые вопросы",
    Responses_Dashboard_SinceMidnight: "С полуночи",
    Responses_Dashboard_Today: "Сегодня",
    Responses_Dashboard_TotalResponses: "Всего ответов",
    Responses_Dashboard_UniqueRespondents: "Уникальные респонденты",
    Responses_Dashboard_Unpin: "Открепить от панели мониторинга",
    Responses_Dashboard_UntitledQuestion: "Вопрос без названия",
    Responses_Dashboard_VsPrevious7Days: "по сравнению с предыдущими 7 днями",
    Responses_Detail_Answers: "Ответы",
    Responses_Detail_AsTheForm: "Как в форме",
    Responses_Detail_Cancel: "Отмена",
    Responses_Detail_Delete: "Удалить",
    Responses_Detail_DeleteBody: "Элемент списка перемещается в корзину сайта, поэтому его можно восстановить оттуда.",
    Responses_Detail_DeleteTitle: "Удалить этот ответ?",
    Responses_Detail_Deleting: "Удаление…",
    Responses_Detail_Draft: "Черновик",
    Responses_Detail_Header: "Ответ {index} из {total}",
    Responses_Detail_LoadingAttachments: "Загрузка вложений…",
    Responses_Detail_Next: "Следующий ответ",
    Responses_Detail_NoAnswer: "Нет ответа",
    Responses_Detail_Previous: "Предыдущий ответ",
    Responses_Detail_Print: "Печать",
    Responses_Detail_Signature: "Подпись",
    Responses_Detail_Signed: "Подписано",
    Responses_Detail_Took: "время заполнения: {duration}",
    Responses_Summary_AnsweredOfType: "Отвечено: {answered} из {total} · {type}",
    Responses_Summary_ByField: "По: {title}",
    Responses_Summary_CompareBy: "Сравнить по…",
    Responses_Summary_EmptyBody: "В каждом вопросе здесь будет своя сводка.",
    Responses_Summary_NoComparison: "Без сравнения",
    Responses_Summary_NothingToCompare: "Никто не ответил на вопрос “{title}”, поэтому сравнивать нечего.",
    Responses_Summary_OtherNote: "В диаграммах с числом категорий более {max} самые малые объединяются в “Другое”. Переключите карточку на таблицу, чтобы увидеть все значения.",
    Responses_Summary_ResponseCountOne: "{count} ответ",
    Responses_Summary_ResponseCountOther: "{count} ответов",
    Responses_Summary_SeeAllAnswers: "Показать все ответы в таблице",
    Responses_Summary_SegmentNote: "Показаны самые большие группы ({groups}). Ответ, в котором выбрано несколько вариантов, попадает в каждую подходящую группу, поэтому сумма по группам может превышать {total}.",
    Responses_Summary_SplitBy: "Разделить по: {title}",
    Responses_Summary_Untitled: "без названия",
    Responses_Table_Apply: "Применить",
    Responses_Table_Cancel: "Отмена",
    Responses_Table_ClearSelection: "Снять выделение",
    Responses_Table_ColumnOrder: "Порядок столбцов",
    Responses_Table_ColumnsCount: "Столбцы ({shown}/{total})",
    Responses_Table_Delete: "Удалить",
    Responses_Table_DeleteBody: "Элементы списка перемещаются в корзину сайта, поэтому их можно восстановить оттуда.",
    Responses_Table_DeleteSelected: "Удалить выбранные",
    Responses_Table_DeleteTitleOne: "Удалить {count} ответ?",
    Responses_Table_DeleteTitleOther: "Удалить ответы ({count})?",
    Responses_Table_Deleting: "Удаление…",
    Responses_Table_MoveDown: "Переместить вниз",
    Responses_Table_MoveDownFor: "Переместить {title} вниз",
    Responses_Table_MoveUp: "Переместить вверх",
    Responses_Table_MoveUpFor: "Переместить {title} вверх",
    Responses_Table_NoColumns: "Столбцы вопросов пока не отображаются.",
    Responses_Table_NoMatch: "Нет ответов, соответствующих текущим фильтрам.",
    Responses_Table_NothingToShow: "Нечего показывать",
    Responses_Table_OpenResponse: "Открыть этот ответ",
    Responses_Table_OrderNote: "Столбцы \"Отправлено\" и \"Отправил\" всегда идут первыми. Порядок перетаскивания применяется к столбцам вопросов.",
    Responses_Table_Reorder: "Изменить порядок",
    Responses_Table_ResetColumns: "Сбросить столбцы",
    Responses_Table_SelectResponse: "Выбрать этот ответ",
    Responses_Table_SelectedOne: "Выбран {count} ответ",
    Responses_Table_SelectedOther: "Выбрано ответов: {count}",
    Responses_Table_ShowAll: "Показать все",
    Responses_Table_ShowTheseQuestions: "Показать эти вопросы",
    Responses_Table_Submitted: "Отправлено",
    Responses_Table_SubmittedBy: "Отправил",
    Responses_Table_ToggleSelection: "Переключить выделение",
    Responses_Table_Unknown: "Неизвестно",
    Responses_Table_Untitled: "Без названия",
    Responses_View_AllTime: "За все время",
    Responses_View_AnyAnswer: "Любой ответ",
    Responses_View_Clear: "Очистить",
    Responses_View_CopyShareLink: "Копировать ссылку для общего доступа",
    Responses_View_CountFiltered: "Ответов: {shown} из {total}",
    Responses_View_CountOne: "{count} ответ",
    Responses_View_CountOther: "{count} ответов",
    Responses_View_Dashboard: "Панель мониторинга",
    Responses_View_DateRange: "Диапазон дат",
    Responses_View_EmptyBody: "Поделитесь формой, чтобы начать сбор. Ответы сохраняются в “{list}” и сразу отображаются здесь.",
    Responses_View_EmptyTitle: "Ответов пока нет",
    Responses_View_ExportCsv: "Экспорт в CSV",
    Responses_View_FilterByAnswer: "Фильтровать по ответу",
    Responses_View_FilterByQuestion: "Фильтровать по вопросу",
    Responses_View_FilterValue: "Значение фильтра",
    Responses_View_Last30Days: "Последние 30 дней",
    Responses_View_Last7Days: "Последние 7 дней",
    Responses_View_Last90Days: "Последние 90 дней",
    Responses_View_LoadError: "Не удалось загрузить ответы. Опубликуйте форму один раз, чтобы создать столбцы списка, и повторите попытку.",
    Responses_View_Loading: "Загрузка ответов…",
    Responses_View_MoreActions: "Дополнительные действия с ответами",
    Responses_View_PreviewForm: "Предварительный просмотр формы",
    Responses_View_Refresh: "Обновить",
    Responses_View_ResponsesTab: "Ответы ({count})",
    Responses_View_SearchPlaceholder: "Поиск по всем ответам",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Выберите значение",
    Responses_View_Summary: "Сводка",
    Responses_View_Today: "Сегодня",
    Responses_View_Truncated: "В этом списке больше ответов, чем Smart Forms загружает за один раз. Показаны новейшие ответы ({count}); чтобы увидеть полный набор, откройте список в Microsoft Lists.",
    Responses_View_TryAgain: "Повторить",
    Responses_View_Untitled: "Без названия",
    Responses_Approval_Column: "Утверждение",
    Responses_Approval_ReviewerColumn: "Проверил",
    Responses_Approval_CommentColumn: "Комментарий проверяющего",
    Responses_Approval_Pending: "На рассмотрении",
    Responses_Approval_Approved: "Утверждено",
    Responses_Approval_Rejected: "Отклонено",
    Responses_Approval_AnyStatus: "Любой статус утверждения",
    Responses_Approval_FilterLabel: "Фильтр по статусу утверждения",
    Responses_Approval_ApproveSelected: "Утвердить выбранные",
    Responses_Approval_RejectSelected: "Отклонить выбранные",
    Responses_Approval_BulkFailed: "Не удалось обновить ответы: {count}. Повторите попытку.",
    Responses_Approval_Approve: "Утвердить",
    Responses_Approval_Reject: "Отклонить",
    Responses_Approval_Reset: "Сбросить в \"На рассмотрении\"",
    Responses_Approval_CommentLabel: "Комментарий (необязательно)",
    Responses_Approval_ReviewedBy: "Проверил: {name}",
    Responses_Approval_Error: "Не удалось сохранить решение. Повторите попытку.",
    Responses_Dashboard_ApprovalStatus: "Ожидают проверки",
    Responses_Dashboard_ApprovalBreakdown: "На рассмотрении: {pending}, утверждено: {approved}, отклонено: {rejected}",
    Responses_Dashboard_TimelineCoarsened: "Диапазон дат большой, поэтому временная шкала сгруппирована крупнее ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Диапазон дат очень большой, поэтому показаны только последние периоды: {count}.",
    Service_Item_DefaultTitle: "Ответ — {date}",
    Service_Email_ApprovalSubject: "Ваш ответ: {status} — {title}",
    Service_Email_ApprovalHeading: "Ваш ответ: {status}",
    Service_Email_ApprovalIntro: "Проверяющий отметил ваш ответ на \"{title}\" как {status}.",
    Service_Email_ApprovalCommentLabel: "Комментарий проверяющего",
    Service_Approval_Approved: "утвержден",
    Service_Approval_Rejected: "отклонен",
    Service_Approval_Pending: "на рассмотрении",
    Service_Lookup_InvalidFilter: "Недопустимый фильтр подстановки.",
    Service_Edit_NotAllowed: "Эта форма не позволяет изменять отправленный ответ.",
    Service_Edit_NotYours: "Вы можете изменять только свой ответ.",
    Service_Signature_AttachmentLabel: "Подпись",
    PropertyPane_ListsLoadFailed: "Не удалось загрузить списки на этом сайте.",
    PropertyPane_EnterListName: "Сначала введите имя нового списка.",
    PropertyPane_CreatingList: "Создание \"{name}\"…",
    PropertyPane_ListCreated: "Список \"{title}\" создан и выбран.",
    PropertyPane_ListAlreadyExists: "Список с именем \"{name}\" уже существует: выберите его в раскрывающемся списке выше.",
    PropertyPane_CreateListFailed: "Не удалось создать список. Убедитесь, что у вас есть разрешение на создание списков на этом сайте.",
    PropertyPane_Description: "Выберите список SharePoint, в котором хранятся ответы формы, или создайте новый. Все остальное — вопросы, оформление, уведомления — редактируется прямо на странице.",
    PropertyPane_ResponseList_GroupName: "Список ответов",
    PropertyPane_ListDropdown_Label: "Сохранять ответы в этот список",
    PropertyPane_ResponsesGoTo: "Ответы отправляются в \"{name}\".",
    PropertyPane_PickList: "Выберите список или создайте новый ниже.",
    PropertyPane_LoadingLists: "Загрузка списков…",
    PropertyPane_NewListName_Label: "Или создайте новый список",
    PropertyPane_NewListName_Placeholder: "Имя нового списка",
    PropertyPane_CreateList_Button: "Создать список",
    PropertyPane_Tips_GroupName: "Советы",
    PropertyPane_Tip_AutoSave: "Вопросы и параметры сохраняются автоматически при редактировании: сохранять или публиковать страницу не нужно.",
    PropertyPane_Tip_Permissions: "Респондентам нужно разрешение на добавление элементов в список ответов. Проверьте разрешения списка, если кто-то сообщает об ошибке при отправке.",
    PropertyPane_Tip_Share: "Используйте \"Собирать ответы\" на странице, чтобы создать столбцы списка и получить ссылку для заполнения.",
    App_ErrorBoundary_Title: "Smart Forms — ошибка отрисовки",
    App_ErrorBoundary_Message: "Сообщение:",
    App_ErrorBoundary_Stack: "Стек:",
    App_ErrorBoundary_NoStack: "(стек недоступен)",
    App_ErrorBoundary_ConsoleNote: "Полные сведения также записаны в консоль браузера.",
    App_DefaultQuestionTitle: "Вопрос {number}",
    App_Error_ListMissing: "Список, настроенный для этой формы, больше не существует. Выберите другой список в параметрах веб-части.",
    App_Error_LoadConfig: "Произошла ошибка при загрузке конфигурации формы.",
    App_Error_Unable: "Не удалось загрузить форму.",
    App_Publish_ConflictNotice: "Для \"{title}\" уже существует столбец списка другого типа ({type}). Переименуйте вопрос, чтобы можно было создать новый столбец, или верните прежний тип.",
    App_Publish_ConflictUnnamedQuestion: "вопрос",
    App_Publish_ColumnsAddedOne: "В \"{list}\" добавлен {count} столбец.",
    App_Publish_ColumnsAddedOther: "В \"{list}\" добавлено столбцов: {count}.",
    App_Publish_TheList: "список",
    App_Publish_UpToDate: "Список ответов уже обновлен.",
    App_Publish_Error: "Не удалось создать столбцы списка. Обычно это означает, что у вас нет разрешения на управление списками для списка ответов, но это также может происходить на сайтах с отключенными пользовательскими сценариями. Проверьте консоль браузера на наличие исходной ошибки или повторите попытку.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Создайте стильную форму на основе списка SharePoint: типов вопросов — {count}, логика ветвления, отправка файлов, ссылки для заполнения и панель результатов.",
    App_Placeholder_ChooseList: "Выберите или создайте список",
    App_Placeholder_Hint: "Измените страницу и настройте эту веб-часть, чтобы начать работу.",
    App_Loading: "Загрузка формы…",
    App_OpenSettings: "Открыть параметры",
    App_Tab_Questions: "Вопросы",
    App_Tab_QuestionsWithCount: "Вопросы ({count})",
    App_Tab_Responses: "Ответы",
    App_Tab_Responses_Title: "Ответы сохраняются в \"{list}\"",
    App_Templates_Start: "Начать с шаблона",
    App_Settings_Title: "Параметры формы: оформление, уведомления, доступ",
    App_Settings_AriaLabel: "Параметры формы",
    App_Preview: "Просмотр",
    App_Preview_Close: "Закрыть просмотр",
    App_Preview_Hint: "Просмотр: ничто из отправленного здесь не сохраняется. Проверка и ветвление работают точно так же, как для респондентов.",
    App_Publish_GettingReady: "Подготовка…",
    App_Publish_CollectResponses: "Собирать ответы",
    App_Publish_Share: "Поделиться",
    App_Retry: "Повторить",
    App_SaveError_Banner: "Не удалось сохранить последнее изменение. Проверьте подключение и повторите попытку.",
    App_Preflight_BlockingTitle: "Исправьте это перед сбором ответов",
    App_Preflight_WarningTitle: "Стоит проверить сначала",
    App_Preflight_BlockingText: "Из-за этого опубликованная форма не сможет работать должным образом.",
    App_Preflight_WarningText: "Ничего не сломано, но обычно это стоит исправить, прежде чем делиться ссылкой.",
    App_Preflight_GoTo: "Перейти к",
    App_Preflight_CollectAnyway: "Все равно собирать ответы",
    App_Preflight_Back: "Вернуться к форме",
    App_Cancel: "Отмена",
    App_Done: "Готово",
    App_Share_Title: "Ваша форма готова к отправке",
    App_Share_SubText: "Отправьте эту ссылку всем, кто должен заполнить форму.",
    App_Share_LinkAriaLabel: "Ссылка для общего доступа",
    App_Share_Copy: "Копировать",
    App_Share_Copied: "Скопировано",
    App_Share_AddItemsEmphasis: "добавление элементов",
    App_Share_PermissionNote: "Респондентам нужно разрешение на {addItems} в “{title}” и доступ к этой странице. Если при отправке возникает ошибка, почти всегда причина в этом.",
    App_Share_PrefillNote: "Вы можете заранее ответить на вопросы в ссылке, добавив имя столбца, например {example}.",
    App_Templates_ReplaceWarning: "При выборе шаблона текущие вопросы заменяются.",
    App_Templates_PickStart: "Выберите отправную точку: потом можно изменить что угодно.",
    App_Templates_Empty: "Пустая",
    App_Templates_QuestionCount: "Вопросов: {count}",
    App_SaveChip_SavingTitle: "Сохранение последнего изменения",
    App_SaveChip_Saving: "Сохранение…",
    App_SaveChip_FailedTitle: "Не удалось сохранить последнее изменение. Проверьте подключение и повторите попытку.",
    App_SaveChip_Failed: "Сбой сохранения",
    App_SaveChip_SavedTitle: "Все изменения сохранены",
    App_SaveChip_Saved: "Сохранено",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Новый ответ — {title}",
    Service_Email_NewResponseHeading: "Новый ответ: {title}",
    Service_Email_NewResponseIntro: "Кто-то только что отправил ответ — {date}.",
    Service_Email_ReceiptSubject: "Ваш ответ — {title}",
    Service_Email_ReceiptHeading: "Спасибо за ваш ответ!",
    Service_Email_ReceiptIntro: "Вот копия того, что вы отправили в \"{title}\".",
    App_History_Title: "История версий",
    App_History_RestoredNotice: "Восстановлена версия, сохраненная {date}. Проверьте ее, затем используйте \"Собрать ответы\", чтобы опубликовать новые вопросы.",
    App_History_Undo: "Отменить восстановление",
    App_Share_CopyManual: "Браузер заблокировал копирование. Выделите ссылку выше и нажмите Ctrl+C (Cmd+C на Mac), чтобы скопировать ее.",
    App_Share_TeamsNote: "Вы находитесь в Microsoft Teams. Эта ссылка открывает страницу SharePoint напрямую, поэтому получателям нужен доступ к сайту.",
    App_Share_PrefillNotSecure: "Предзаполненные ответы удобны, но не защищены: любой, у кого есть ссылка, может их изменить, поэтому не используйте их как средство защиты.",
    Designer_Section_DropHere: "Перетащите вопрос сюда",
    Designer_Section_DropEnd: "Отпустите, чтобы переместить в конец этого раздела",
    Designer_Rules_RemovedOne: "1 правило ветвления, которое больше не подходило, удалено.",
    Designer_Rules_RemovedOther: "Правил ветвления, которые больше не подходили, удалено: {count}.",
    Designer_Settings_AllowEdit: "Разрешить респондентам изменять свои ответы",
    Designer_Settings_AllowEditHint: "Респонденты могут повторно открыть и обновить отправленные данные. Каждый пользователь может изменять только свой ответ.",
    Designer_Settings_EnableApproval: "Включить процесс утверждения",
    Designer_Settings_ApprovalNotify: "Уведомлять респондента по эл. почте о решении",
    Designer_Settings_ApprovalHint: "При следующей публикации в список ответов будут добавлены столбцы утверждения. Владельцы утверждают или отклоняют ответы на вкладке \"Ответы\".",
    Designer_History_Title: "История версий",
    Designer_History_Intro: "Ранее сохраненные версии вопросов и параметров этой формы. При восстановлении версия загружается в конструктор; это можно отменить, а новые вопросы создаются только при публикации.",
    Designer_History_Loading: "Загрузка версий...",
    Designer_History_Empty: "Более ранние версии не найдены. Для истории версий необходимо включить управление версиями для списка \"Smart Forms Config\" и иметь хотя бы одно сохраненное изменение.",
    Designer_History_Latest: "Последняя",
    Designer_History_LatestTitle: "Это версия, используемая в данный момент",
    Designer_History_By: "{name}",
    Designer_History_UnknownAuthor: "Неизвестный автор",
    Designer_History_VersionLabel: "версия {label}",
    Designer_History_Preview: "Просмотр",
    Designer_History_Restore: "Восстановить",
    Designer_History_QuestionsOne: "1 вопрос",
    Designer_History_QuestionsOther: "Вопросов: {count}",
    Designer_History_LoadFailed: "Не удалось загрузить эту версию.",
    Designer_History_ConfirmTitle: "Восстановить эту версию?",
    Designer_History_ConfirmText: "Форма будет заменена версией, сохраненной {date} (вопросов: {count}). Сразу после этого можно отменить действие."
  };
});
