define([], function () {
  return {
    Designer_Color_Blue: "Blå",
    Designer_Color_Teal: "Blågrön",
    Designer_Color_Green: "Grön",
    Designer_Color_Purple: "Lila",
    Designer_Color_Magenta: "Magenta",
    Designer_Color_Red: "Röd",
    Designer_Color_Orange: "Orange",
    Designer_Color_Gray: "Grå",
    Designer_Settings_LayoutSinglePage: "Alla frågor på en sida",
    Designer_Settings_LayoutWizard: "Ett avsnitt per steg (guide)",
    Designer_Settings_Title: "Formulärinställningar",
    Designer_Common_Apply: "Använd",
    Designer_Common_Cancel: "Avbryt",
    Designer_Settings_TabBasics: "Grundläggande",
    Designer_Settings_FormTitle: "Formulärtitel",
    Designer_Settings_Description: "Beskrivning",
    Designer_Settings_Layout: "Layout",
    Designer_Settings_NumberQuestions: "Numrera frågorna",
    Designer_Settings_ShuffleQuestions: "Slumpa frågornas ordning för varje svarande",
    Designer_Settings_ShowProgressBar: "Visa en förloppsindikator",
    Designer_Settings_TabAppearance: "Utseende",
    Designer_Settings_AccentColor: "Accentfärg",
    Designer_Settings_CustomColorTitle: "Anpassad färg",
    Designer_Settings_CustomColorAria: "Anpassad accentfärg",
    Designer_Settings_AccentHint: "Accentfärger justeras automatiskt för kontrast på mörka webbplatser, så att formuläret förblir läsbart oavsett vilket tema sidan använder.",
    Designer_Settings_ShowHeader: "Visa formulärhuvudet",
    Designer_Settings_HeaderIcon: "Huvudikon",
    Designer_Settings_TabAfterSubmit: "Efter inskickning",
    Designer_Settings_SubmitButtonText: "Text på skicka-knappen",
    Designer_Settings_SubmitPlaceholder: "Skicka",
    Designer_Settings_ThankYouTitle: "Tacktitel",
    Designer_Settings_ThankYouPlaceholder: "Tack!",
    Designer_Settings_ThankYouMessage: "Tackmeddelande",
    Designer_Settings_ShowSubmitAnother: "Visa en knapp för \"Skicka ett svar till\"",
    Designer_Settings_TabNotifications: "Aviseringar",
    Designer_Settings_EmailEachResponseTo: "Skicka varje svar via e-post till",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "Personer i din organisation får varje svar via e-post, med en länk till listobjektet",
    Designer_Settings_RespondentReceipt: "Skicka en kopia av svaren till de svarande via e-post",
    Designer_Settings_NotificationsInfo: "Aviseringar använder SharePoints egen e-posttjänst, så mottagarna måste vara användare i din organisation. Externa adresser tas bort utan meddelande.",
    Designer_Settings_TabAccess: "Åtkomst",
    Designer_Settings_OpenFrom: "Öppna från",
    Designer_Settings_OpenImmediately: "Öppna direkt",
    Designer_Settings_CloseAfter: "Stäng efter",
    Designer_Settings_NeverClose: "Stäng aldrig",
    Designer_Settings_ClearDates: "Rensa datum",
    Designer_Settings_DatesInverted: "Stängningsdatumet är samma som eller före öppningsdatumet, så formuläret skulle aldrig ta emot några svar.",
    Designer_Settings_MaxResponses: "Sluta efter så här många svar",
    Designer_Settings_NoLimit: "Ingen gräns",
    Designer_Settings_OneResponsePerPerson: "Tillåt bara ett svar per person",
    Designer_Settings_AllowSaveDraft: "Låt svarande spara ett utkast och slutföra senare",
    Designer_Settings_ClosedMessage: "Meddelande som visas när formuläret är stängt",
    Designer_Settings_ClosedMessagePlaceholder: "Det här formuläret tar inte längre emot svar.",
    Designer_Settings_AccessInfo: "Dessa gränser tillämpas av formuläret, inte av SharePoint. Den som har behörighet att lägga till objekt i svarslistan kan fortfarande lägga till ett direkt via listan.",
    Designer_Field_StyleInfo: "Information (accent)",
    Designer_Field_StyleSuccess: "Lyckades (grön)",
    Designer_Field_StyleWarning: "Varning (gul)",
    Designer_Field_StylePlain: "Oformaterad text",
    Designer_Field_StyleDivider: "Avdelarlinje",
    Designer_Field_IconStars: "Stjärnor",
    Designer_Field_IconHearts: "Hjärtan",
    Designer_Field_IconThumbs: "Tummen upp",
    Designer_Field_FormatPlain: "Vanligt tal",
    Designer_Field_FormatCurrency: "Valuta",
    Designer_Field_FormatPercent: "Procent",
    Designer_Field_UntitledQuestion: "Fråga utan titel",
    Designer_Field_DeletedQuestion: "en borttagen fråga",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} och {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "ELLER",
    Designer_Rule_JoinAll: "OCH",
    Designer_Rule_Preview: "Visas när {conditions}.",
    Designer_Field_Yes: "Ja",
    Designer_Field_No: "Nej",
    Designer_Field_When: "När",
    Designer_Field_SelectValue: "Välj ett värde",
    Designer_Field_DateValuePlaceholder: "ÅÅÅÅ-MM-DD eller \"today\"",
    Designer_Field_ValuePlaceholder: "Värde",
    Designer_Field_UpperBound: "Övre gräns",
    Designer_Field_RemoveCondition: "Ta bort det här villkoret",
    Designer_Field_FormulaInvalid: "Formeln kan inte beräknas. Kontrollera parenteser och operatorer.",
    Designer_Field_FormulaMissing: "Följande frågor finns inte: {names}.",
    Designer_Field_FormulaPreview: "Med alla indata satta till 10 visas {value}.",
    Designer_Field_HintYesNo: "Använd \"yes\" eller \"no\"",
    Designer_Field_HintMultiDefault: "Avgränsa flera standardvärden med ;",
    Designer_Field_HintSingleDefault: "Måste matcha ett av alternativen",
    Designer_Field_HintDate: "Använd \"today\" eller ett datum som 2026-03-01",
    Designer_Field_HintTime: "Använd \"now\" eller en tid som 09:30",
    Designer_Field_QuestionSettings: "Frågeinställningar",
    Designer_Field_Appearance: "Utseende",
    Designer_Field_Style: "Format",
    Designer_Field_ImageUrl: "Bild-URL (valfritt)",
    Designer_Field_Content: "Innehåll",
    Designer_Field_BasicFormatting: "Grundläggande formatering tillåts: fet, kursiv, listor och länkar.",
    Designer_Field_TabOptions: "Alternativ",
    Designer_Field_TabBranching: "Förgrening",
    Designer_Field_BranchingNeedsQuestion: "Lägg först till en annan fråga – förgrening kräver något att utgå från.",
    Designer_Field_BranchingToggle: "Visa bara den här frågan när andra svar matchar",
    Designer_Field_Match: "Matcha",
    Designer_Field_MatchAll: "alla dessa",
    Designer_Field_MatchAny: "någon av dessa",
    Designer_Field_AddCondition: "Lägg till villkor",
    Designer_Field_TabValidation: "Validering",
    Designer_Field_HelpText: "Hjälptext",
    Designer_Field_HelpTextPlaceholder: "Visas under frågeetiketten",
    Designer_Field_CheckboxLabel: "Etikett för kryssruta",
    Designer_Field_Placeholder: "Platshållare",
    Designer_Field_DefaultAnswer: "Standardsvar",
    Designer_Field_RequiredMessage: "Anpassat meddelande för obligatoriskt fält",
    Designer_Field_RequiredMessagePlaceholder: "{title} är obligatoriskt",
    Designer_Field_ThisQuestion: "Den här frågan",
    Designer_Field_RequiredMessageDescription: "Visas i stället för standardmeddelandet när frågan lämnas tom",
    Designer_Field_ReadOnly: "Skrivskyddad (svaret kan bara komma från en förifylld länk)",
    Designer_Field_ValidationRules: "Valideringsregler",
    Designer_Field_MaxLength: "Maximal längd",
    Designer_Field_Pattern: "Måste matcha det här mönstret",
    Designer_Field_PatternDescription: "Ett reguljärt uttryck. Lämna tomt om du inte vill kontrollera något mönster.",
    Designer_Field_PatternMessage: "Meddelande när mönstret inte matchar",
    Designer_Field_PatternMessagePlaceholder: "Det här svaret har inte det förväntade formatet",
    Designer_Field_Format: "Format",
    Designer_Field_UnitSuffix: "Enhet som visas efter värdet",
    Designer_Field_UnitSuffixPlaceholder: "kg, tim, st…",
    Designer_Field_Minimum: "Minimum",
    Designer_Field_Maximum: "Maximum",
    Designer_Field_Decimals: "Decimaler",
    Designer_Field_Formula: "Formel",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Referera till andra frågor med deras text inom klammerparenteser. Stöder + - * / ( ) samt round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Tillgängliga frågor: {questions}",
    Designer_Field_NoneYet: "inga ännu",
    Designer_Field_Step: "Steg",
    Designer_Field_From: "Från",
    Designer_Field_To: "Till",
    Designer_Field_LowLabel: "Etikett i den låga änden",
    Designer_Field_LowLabelPlaceholder: "Inte alls troligt",
    Designer_Field_HighLabel: "Etikett i den höga änden",
    Designer_Field_HighLabelPlaceholder: "Extremt troligt",
    Designer_Field_SummarizeAs: "Sammanfatta som",
    Designer_Field_SummarizeAverage: "Medelvärde och fördelning",
    Designer_Field_SummarizeNps: "Net Promoter Score (kräver en skala på 0–10)",
    Designer_Field_NpsWarning: "Net Promoter Score är bara meningsfullt på en skala på 0–10. Ange Från till 0 och Till till 10.",
    Designer_Field_NumberOfIcons: "Antal ikoner",
    Designer_Field_Icon: "Ikon",
    Designer_Field_AllowHalf: "Tillåt halva värden",
    Designer_Field_ShowOptionsAs: "Visa alternativ som",
    Designer_Field_DisplayButtons: "Knappar på samma rad",
    Designer_Field_DisplayDropdown: "Listruta",
    Designer_Field_DisplayAutomatic: "Automatiskt (på samma rad upp till 6 alternativ)",
    Designer_Field_AllowOther: "Lägg till ett fritt alternativ \"Annat\"",
    Designer_Field_OtherLabel: "Etikett för alternativet \"Annat\"",
    Designer_Field_OtherPlaceholder: "Annat",
    Designer_Field_ShuffleOptions: "Slumpa alternativens ordning för varje svarande",
    Designer_Field_MinSelections: "Minsta antal val",
    Designer_Field_MaxSelections: "Högsta antal val",
    Designer_Field_SourceList: "Källista",
    Designer_Field_ChooseList: "Välj en lista",
    Designer_Field_LookupColumn: "Kolumn att läsa alternativ från",
    Designer_Field_ChooseColumn: "Välj en kolumn",
    Designer_Field_ChooseListFirst: "Välj först en lista",
    Designer_Field_LookupFilter: "Filter (valfritt)",
    Designer_Field_LookupFilterDescription: "Ett OData-filter som begränsar vilka källobjekt som blir alternativ",
    Designer_Field_LookupInfo: "Svaren lagrar alternativets text, inte en länk till källobjektet, så svaren förblir läsbara även om källistan ändras senare.",
    Designer_Field_ConsentText: "Villkor som visas ovanför kryssrutan",
    Designer_Field_AllowMultiplePeople: "Tillåt flera personer",
    Designer_Field_AllowGroups: "Tillåt även grupper",
    Designer_Field_IncludeTime: "Inkludera klockslag",
    Designer_Field_TimeStep: "Tidssteg (minuter)",
    Designer_Field_MaxFiles: "Maximalt antal filer",
    Designer_Field_MaxFileSize: "Maxstorlek per fil (MB)",
    Designer_Field_AcceptedTypes: "Godkända filtyper",
    Designer_Field_AcceptedTypesDescription: "Kommaseparerade filnamnstillägg. Lämna tomt för att godta allt som SharePoint tillåter.",
    Designer_Field_FilesInfo: "Filer sparas som bilagor på svarsobjektet. SharePoint blockerar vissa filnamnstillägg (till exempel .exe) oavsett vad du tillåter här.",
    Designer_Field_Rows: "Rader",
    Designer_Field_ProvisionedNote: "Den här frågan har redan en listkolumn ({name}). Inställningar som ändrar kolumnens typ är låsta – duplicera frågan om du behöver en annan typ.",
    Designer_Category_Text: "Text",
    Designer_Category_Choice: "Val",
    Designer_Category_Scales: "Skalor",
    Designer_Category_Date: "Datum",
    Designer_Category_People: "Personer",
    Designer_Category_Advanced: "Avancerat",
    Designer_Category_Layout: "Layout",
    Designer_Menu_CommonPresets: "Vanliga förval",
    Designer_Menu_AllTypes: "Alla frågetyper",
    Designer_Menu_ChangeType: "Ändra typ",
    Designer_Menu_TypeLockedTitle: "Listkolumnen finns redan, så typen är låst. Duplicera frågan för att ändra den.",
    Designer_Menu_MoreSettings: "Förgrening, validering med mera",
    Designer_Menu_InsertBelow: "Infoga fråga nedanför",
    Designer_Card_Duplicate: "Duplicera",
    Designer_Card_DeleteQuestion: "Ta bort fråga",
    Designer_Outline_Aria: "Frågeöversikt",
    Designer_Outline_QuestionCountOne: "{count} fråga",
    Designer_Outline_QuestionCountOther: "{count} frågor",
    Designer_Outline_IssuesTitle: "{count} problem att granska",
    Designer_Outline_Find: "Sök efter en fråga",
    Designer_Outline_Empty: "Inga frågor ännu.",
    Designer_Section_DefaultTitle: "Avsnitt {number}",
    Designer_Card_Question: "Fråga",
    Designer_Card_BranchingTitle: "Den här frågan visas bara när en förgreningsregel matchar",
    Designer_Card_BranchingChip: "Förgrening",
    Designer_Card_LiveTitle: "Listkolumnen finns, så typen är låst",
    Designer_Card_LiveChip: "Aktiv",
    Designer_Card_CheckChip: "Kontrollera",
    Designer_Option_Placeholder: "Alternativ {number}",
    Designer_Option_LabelAria: "Etikett för alternativ {number}",
    Designer_Option_ImageUrl: "Bild-URL",
    Designer_Option_ImageUrlAria: "Bild-URL för alternativ {number}",
    Designer_Option_Remove: "Ta bort alternativ",
    Designer_Option_RemoveAria: "Ta bort alternativ {number}",
    Designer_Option_Add: "Lägg till alternativ",
    Designer_Option_OtherHint: "Svarande kan också skriva ett eget svar med etiketten “{label}”.",
    Designer_Option_OtherFallback: "Annat",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Ta bort",
    Designer_Grid_RemoveAria: "Ta bort {label} {number}",
    Designer_Grid_Statements: "Påståenden",
    Designer_Grid_Scale: "Skala",
    Designer_Grid_AddStatement: "Lägg till påstående",
    Designer_Grid_AddScale: "Lägg till skala",
    Designer_Width_Full: "Full bredd",
    Designer_Width_Half: "Halv bredd",
    Designer_Width_Third: "En tredjedels bredd",
    Designer_Width_Aria: "Frågans bredd",
    Designer_Card_BlockLabelPlaceholder: "Blocketikett (visas inte för svarande)",
    Designer_Card_QuestionText: "Frågetext",
    Designer_Card_MoveUp: "Flytta upp",
    Designer_Card_MoveQuestionUp: "Flytta upp frågan",
    Designer_Card_MoveDown: "Flytta ned",
    Designer_Card_MoveQuestionDown: "Flytta ned frågan",
    Designer_Card_DuplicateQuestion: "Duplicera fråga",
    Designer_Card_MultipleAnswers: "Flera svar",
    Designer_Card_Required: "Obligatorisk",
    Designer_Card_MoreOptions: "Fler alternativ",
    Designer_Card_MoreOptionsAria: "Fler alternativ för den här frågan",
    Designer_Canvas_FormTitle: "Formulärtitel",
    Designer_Canvas_DescriptionPlaceholder: "Lägg till en beskrivning (valfritt)",
    Designer_Canvas_DescriptionAria: "Formulärbeskrivning",
    Designer_Canvas_EmptyTitle: "Lägg till din första fråga",
    Designer_Canvas_EmptyBody: "Välj en frågetyp för att komma igång. Du kan ändra ordning på frågorna genom att dra dem och lägga till förgrening så att människor bara ser det som gäller dem.",
    Designer_Section_Chip: "Avsnitt {number} av {total}",
    Designer_Section_TitlePlaceholder: "Avsnittstitel",
    Designer_Section_TitleAria: "Titel för avsnitt {number}",
    Designer_Section_DescriptionPlaceholder: "Beskrivning (valfritt)",
    Designer_Section_DescriptionAria: "Beskrivning för avsnitt {number}",
    Designer_Section_MoveUp: "Flytta upp avsnittet",
    Designer_Section_MoveDown: "Flytta ned avsnittet",
    Designer_Section_Delete: "Ta bort avsnitt",
    Designer_Card_DragToReorder: "Dra för att ändra ordning",
    Designer_Card_ReorderAria: "Ändra ordning på {title}",
    Designer_Card_ReorderFallback: "fråga",
    Designer_Canvas_AddNew: "Lägg till ny",
    Designer_Canvas_AddSection: "Lägg till avsnitt",
    Form_Address_AriaWithLabel: "{label} – {part}",
    Form_Address_StreetPlaceholder: "Gatuadress",
    Form_Address_Street2Placeholder: "Lägenhet, ingång osv. (valfritt)",
    Form_Address_CityPlaceholder: "Ort",
    Form_Address_StatePlaceholder: "Län / region",
    Form_Address_PostalCodePlaceholder: "Postnummer",
    Form_Address_CountryPlaceholder: "Land",
    Form_Address_StreetAria: "gatuadress",
    Form_Address_Street2Aria: "adressrad 2",
    Form_Address_CityAria: "ort",
    Form_Address_StateAria: "län eller region",
    Form_Address_PostalCodeAria: "postnummer",
    Form_Address_CountryAria: "land",
    Form_Consent_DefaultLabel: "Jag godkänner",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{answered} av {total} rader besvarade",
    Form_Lookup_LoadError: "Alternativen för den här frågan kunde inte läsas in.",
    Form_Lookup_Loading: "Läser in alternativ…",
    Form_Lookup_SelectOptionsPlaceholder: "Välj alternativ",
    Form_Lookup_SelectOptionPlaceholder: "Välj ett alternativ",
    Form_Person_Placeholder: "Börja skriva ett namn…",
    Form_Person_SuggestedPeopleAndGroups: "Föreslagna personer och grupper",
    Form_Person_SuggestedPeople: "Föreslagna personer",
    Form_Person_NoPeopleOrGroups: "Inga personer eller grupper hittades",
    Form_Person_NoPeople: "Inga personer hittades",
    Form_Person_Searching: "Söker…",
    Form_Ranking_Moved: "{item} flyttades till plats {position} av {total}",
    Form_Ranking_MoveUp: "Flytta upp",
    Form_Ranking_MoveDown: "Flytta ned",
    Form_Ranking_MoveItemUpAria: "Flytta upp {item}",
    Form_Ranking_MoveItemDownAria: "Flytta ned {item}",
    Form_Rating_ValueText: "{value} av {max}",
    Form_Rating_NotRated: "Inte betygsatt",
    Form_Rating_Clear: "Rensa betyg",
    Form_RichText_Bold: "Fet",
    Form_RichText_Italic: "Kursiv",
    Form_RichText_Underline: "Understruken",
    Form_RichText_BulletedList: "Punktlista",
    Form_RichText_NumberedList: "Numrerad lista",
    Form_RichText_ClearFormatting: "Rensa formatering",
    Form_RichText_ToolbarAria: "Textformatering",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} kB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\" hoppades över – gränsen är {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" är inte en godkänd filtyp.",
    Form_File_TooLarge: "\"{name}\" är större än {size} MB.",
    Form_File_AlreadyAttached: "\"{name}\" är redan bifogad.",
    Form_File_ReadError: "Det gick inte att läsa en av filerna. Försök bifoga den igen.",
    Form_File_HintMaxSize: "upp till {size} MB per fil",
    Form_File_HintOneFile: "1 fil",
    Form_File_HintMaxFiles: "högst {count} filer",
    Form_File_Reading: "Läser filer…",
    Form_File_DropPrompt: "Släpp filer här eller klicka för att bläddra",
    Form_File_Remove: "Ta bort {name}",
    Form_Signature_Alt: "Signatur",
    Form_Signature_AriaSigned: "{label} – signerad",
    Form_Signature_AriaEmpty: "{label} – tom",
    Form_Signature_Clear: "Rensa",
    Form_Signature_Signed: "Signerad",
    Form_Signature_Prompt: "Signera ovan med mus, penna eller finger",
    Form_Time_Placeholder: "Välj en tid",
    Form_Field_DatePlaceholder: "Välj ett datum",
    Form_Field_TimeAriaWithLabel: "{label} – tid",
    Form_Field_TimeAria: "Tid",
    Form_Field_OtherDefault: "Annat",
    Form_Field_SelectOptionsPlaceholder: "Välj alternativ",
    Form_Field_PleaseSpecify: "Ange vilket",
    Form_Field_OtherSpecifyAria: "{label} – ange vilket",
    Form_Field_SelectOptionPlaceholder: "Välj ett alternativ",
    Form_Field_Yes: "Ja",
    Form_Field_No: "Nej",
    Form_Field_SliderHint: "Dra i reglaget för att svara",
    Form_Field_WebAddressAriaWithLabel: "{label} – webbadress",
    Form_Field_WebAddressAria: "Webbadress",
    Form_Field_DisplayTextPlaceholder: "Visningstext (valfritt)",
    Form_Field_DisplayTextAriaWithLabel: "{label} – visningstext",
    Form_Field_DisplayTextAria: "Visningstext",
    Form_Field_ChooseBetween: "Välj mellan {min} och {max}",
    Form_Field_ChooseAtLeast: "Välj minst {min}",
    Form_Field_ChooseUpTo: "Välj upp till {max}",
    Form_Field_SelectedCount: "{count} valda",
    Form_Field_RequiredAria: "(obligatoriskt)",
    Form_Submit_SaveError: "Ditt svar kunde inte sparas. Kontrollera att formuläret har publicerats från designern och att du har behörighet att lägga till objekt i svarslistan.",
    Form_Empty_Message: "Det här formuläret har inga frågor ännu. Formulärets ägare kan lägga till dem på fliken Frågor.",
    Form_Checking: "Kontrollerar formuläret…",
    Form_Closed_NotYetOpen: "Inte öppet ännu",
    Form_Closed_AlreadyAnswered: "Redan besvarat",
    Form_Closed_Title: "Formuläret är stängt",
    Form_Confirmation_PreviewNotice: "Det här var en förhandsgranskning – ingenting sparades i svarslistan.",
    Form_Confirmation_PreviewAgain: "Förhandsgranska igen",
    Form_Confirmation_SubmitAnother: "Skicka ett svar till",
    Form_Wizard_StepFallback: "Steg {step}",
    Form_Wizard_StepsAria: "Formulärsteg",
    Form_Wizard_StepOf: "Steg {step} av {total}",
    Form_ErrorSummary_Title: "Kontrollera {count} svar:",
    Form_ErrorSummary_UntitledQuestion: "Fråga utan titel",
    Form_ErrorSummary_Question: "Fråga",
    Form_ErrorSummary_Detail: " – {message}",
    Form_Nav_Back: "Tillbaka",
    Form_Nav_Next: "Nästa",
    Form_Draft_Saving: "Sparar…",
    Form_Draft_Saved: "Utkastet har sparats",
    Form_Draft_SaveAndFinishLater: "Spara och slutför senare",
    Form_Draft_NotSaved: "Utkastet sparades inte",
    Form_Submit_Preview: "Skicka (förhandsgranskning)",
    Form_Submit_Button: "Skicka",
    Form_Response_NoAnswer: "Inget svar",
    Form_Signature_TypeLabel: "Skriv ditt fullständiga namn",
    Form_Signature_TypeInstead: "Skriv ditt namn i stället",
    Form_Signature_DrawInstead: "Rita i stället",
    Form_Edit_Button: "Redigera ditt tidigare svar",
    Form_Edit_Available: "Du har redan skickat ett svar. Du kan redigera det i stället för att skicka ett nytt.",
    Form_Edit_Banner: "Du redigerar ditt tidigare svar.",
    Form_Edit_Save: "Uppdatera svar",
    Form_Edit_UpdatedTitle: "Svaret har uppdaterats",
    Form_Edit_UpdatedMessage: "Dina ändringar har sparats.",
    Form_Edit_LoadError: "Ditt tidigare svar kunde inte läsas in. Försök igen.",
    Form_Draft_MissingFiles: "Bifoga på nytt: {names}. Filerna kunde inte återställas.",
    Form_Attachments_Failed: "Dina svar sparades, men de här bilagorna kunde inte laddas upp: {names}. Försök igen eller kontakta formulärets ägare.",
    Logic_ThisQuestion: "Den här frågan",
    Logic_Required: "{label} är obligatoriskt",
    Logic_RequiredConsent: "Markera rutan för att fortsätta",
    Logic_RequiredFile: "Bifoga minst en fil",
    Logic_RequiredSignature: "Lägg till din signatur",
    Logic_RequiredLikert: "Svara på varje rad",
    Logic_InvalidEmail: "Ange en giltig e-postadress",
    Logic_InvalidPhone: "Ange ett giltigt telefonnummer",
    Logic_InvalidUrl: "Ange en giltig webbadress som börjar med http:// eller https://",
    Logic_MinValue: "Värdet måste vara minst {value}",
    Logic_MaxValue: "Värdet får vara högst {value}",
    Logic_MaxLength: "Maximal längd är {max} tecken",
    Logic_ChooseAtLeastOne: "Välj minst {count} alternativ",
    Logic_ChooseAtLeastMany: "Välj minst {count} alternativ",
    Logic_ChooseAtMostOne: "Välj högst {count} alternativ",
    Logic_ChooseAtMostMany: "Välj högst {count} alternativ",
    Logic_LikertRemaining: "Svara på varje rad ({count} kvar)",
    Logic_MaxFilesOne: "Bifoga högst {count} fil",
    Logic_MaxFilesMany: "Bifoga högst {count} filer",
    Logic_FileTooLarge: "\"{name}\" är större än {size} MB",
    Logic_FileTypeNotAccepted: "\"{name}\" är inte en godkänd filtyp ({types})",
    Logic_AddressRequired: "Ange minst gata och ort",
    Logic_PatternDefault: "Svaret har inte det förväntade formatet",
    Logic_Yes: "Ja",
    Logic_No: "Nej",
    Logic_Agreed: "Godkänt",
    Logic_NotAgreed: "Inte godkänt",
    Logic_Signed: "Signerat",
    Logic_NoAnswer: "(inget svar)",
    Logic_Unknown: "(okänd)",
    Logic_OtherSlice: "Övrigt ({count})",
    Logic_CsvResponseId: "Svars-ID",
    Logic_CsvSubmitted: "Skickat",
    Logic_CsvSubmittedBy: "Skickat av",
    Logic_EmailQuestion: "Fråga",
    Logic_EmailViewItem: "Visa i Microsoft Lists",
    Logic_EmailFooter: "Skickas automatiskt av Smart Forms.",
    Logic_ClosedDefault: "Det här formuläret tar inte längre emot svar.",
    Logic_NotYetOpen: "Det här formuläret öppnas den {date}.",
    Logic_AlreadyResponded: "Du har redan svarat på det här formuläret. Tack!",
    Logic_UntitledQuestion: "En fråga utan titel",
    Logic_Issue_NoQuestions: "Lägg till minst en fråga innan du samlar in svar.",
    Logic_Issue_NoTitle: "En fråga saknar text – den får ett namn automatiskt när du publicerar.",
    Logic_Issue_DuplicateTitle: "{label} har samma text som en annan fråga, vilket gör resultaten svårare att läsa.",
    Logic_Issue_NeedTwoOptions: "{label} behöver minst två alternativ.",
    Logic_Issue_ImageNoImage: "{label} har alternativ utan bild – de visas som textrutor.",
    Logic_Issue_LikertNeedRow: "{label} behöver minst en rad.",
    Logic_Issue_LikertNeedColumns: "{label} behöver minst två skalkolumner.",
    Logic_Issue_NoLookupList: "{label} har ingen källista vald.",
    Logic_Issue_NoFormula: "{label} har ingen formel.",
    Logic_Issue_BadFormula: "{label} har en formel som inte kan beräknas. Kontrollera parenteser och operatorer.",
    Logic_Issue_MissingRefs: "{label} refererar till frågor som inte finns: {names}.",
    Logic_Issue_BadPattern: "{label} har ett ogiltigt valideringsmönster.",
    Logic_Issue_BrokenRule: "{label} har en förgreningsregel som pekar på en borttagen fråga.",
    Logic_Issue_SelfRule: "{label} har en förgreningsregel som refererar till sig själv.",
    Logic_Issue_RuleMismatch: "{label} har en förgreningsregel som inte längre passar frågan den beror på.",
    Logic_Issue_RequiredReadOnly: "{label} är både obligatoriskt och skrivskyddat, så det kan bara besvaras via en länk med förifyllda svar.",
    Logic_Issue_EmptySection: "Ett avsnitt har inga frågor och hoppas över.",
    Logic_Issue_CloseBeforeOpen: "Stängningsdatumet är samma som eller före öppningsdatumet, så formuläret kommer aldrig att ta emot svar.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "E-post om godkännande är aktiverad men godkännandesteget är avstängt.",
    Logic_Op_equals: "är",
    Logic_Op_notEquals: "är inte",
    Logic_Op_contains: "innehåller",
    Logic_Op_notContains: "innehåller inte",
    Logic_Op_notEmpty: "är besvarad",
    Logic_Op_empty: "är inte besvarad",
    Logic_Op_greaterThan: "är större än",
    Logic_Op_greaterOrEqual: "är minst",
    Logic_Op_lessThan: "är mindre än",
    Logic_Op_lessOrEqual: "är högst",
    Logic_Op_between: "är mellan",
    Logic_Op_before: "är före",
    Logic_Op_after: "är efter",
    Logic_Type_Text: "Kort svar",
    Logic_TypeDesc_Text: "En enda textrad",
    Logic_Category_Text: "Text",
    Logic_Type_MultilineText: "Långt svar",
    Logic_TypeDesc_MultilineText: "Flera rader oformaterad text",
    Logic_Type_RichText: "Formaterad text",
    Logic_TypeDesc_RichText: "Fetstil, listor och länkar",
    Logic_Type_Choice: "Val",
    Logic_TypeDesc_Choice: "Välj bland en lista med alternativ",
    Logic_Category_Choice: "Val",
    Logic_Type_ImageChoice: "Bildval",
    Logic_TypeDesc_ImageChoice: "Välj bland bildrutor",
    Logic_Type_Lookup: "Uppslag från en lista",
    Logic_TypeDesc_Lookup: "Alternativ som läses live från en annan SharePoint-lista",
    Logic_Type_YesNo: "Ja / Nej",
    Logic_TypeDesc_YesNo: "En enkel av/på-växel",
    Logic_Type_Consent: "Samtycke",
    Logic_TypeDesc_Consent: "En kryssruta som den svarande måste markera för att fortsätta",
    Logic_Type_Ranking: "Rangordning",
    Logic_TypeDesc_Ranking: "Dra alternativen i önskad ordning",
    Logic_Type_Rating: "Betyg",
    Logic_TypeDesc_Rating: "Stjärnor, hjärtan eller tummar",
    Logic_Category_Scales: "Skalor",
    Logic_Type_Scale: "Åsiktsskala",
    Logic_TypeDesc_Scale: "En numrerad skala med namngivna ändpunkter",
    Logic_Type_Slider: "Reglage",
    Logic_TypeDesc_Slider: "Ett värde på en glidande skala",
    Logic_Type_Likert: "Likert-rutnät",
    Logic_TypeDesc_Likert: "Bedöm flera påståenden på en gemensam skala",
    Logic_Type_Number: "Tal",
    Logic_TypeDesc_Number: "Vanligt tal, valuta eller procent",
    Logic_Category_Advanced: "Avancerat",
    Logic_Type_Calculated: "Beräknat",
    Logic_TypeDesc_Calculated: "En skrivskyddad summa som beräknas från andra svar",
    Logic_Type_Date: "Datum",
    Logic_TypeDesc_Date: "Ett kalenderdatum, eventuellt med klockslag",
    Logic_Category_Date: "Datum",
    Logic_Type_Time: "Tid",
    Logic_TypeDesc_Time: "Enbart ett klockslag",
    Logic_Type_Person: "Person",
    Logic_TypeDesc_Person: "Välj någon i organisationen",
    Logic_Category_People: "Personer",
    Logic_Type_Email: "E-post",
    Logic_TypeDesc_Email: "En e-postadress, validerad",
    Logic_Type_Phone: "Telefon",
    Logic_TypeDesc_Phone: "Ett telefonnummer, validerat",
    Logic_Type_Address: "Adress",
    Logic_TypeDesc_Address: "Gata, ort, postnummer och land",
    Logic_Type_Hyperlink: "Länk",
    Logic_TypeDesc_Hyperlink: "En webbadress",
    Logic_Type_FileUpload: "Filuppladdning",
    Logic_TypeDesc_FileUpload: "Bifoga en eller flera filer till svaret",
    Logic_Type_Signature: "Signatur",
    Logic_TypeDesc_Signature: "Signera med mus, penna eller finger",
    Logic_Type_Content: "Textblock",
    Logic_TypeDesc_Content: "Instruktioner eller en bild – samlar inte in något svar",
    Logic_Category_Layout: "Layout",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Hur troligt är det att du rekommenderar…",
    Logic_Preset_satisfaction: "Nöjdhet (1–5)",
    Logic_PresetDesc_satisfaction: "Mycket missnöjd till mycket nöjd",
    Logic_Preset_currency: "Valuta",
    Logic_PresetDesc_currency: "Ett penningbelopp",
    Logic_Preset_percent: "Procent",
    Logic_PresetDesc_percent: "Ett procentvärde",
    Logic_Template_blank_Name: "Tomt formulär",
    Logic_Template_blank_Description: "Börja från början",
    Logic_Template_feedback_Name: "Kundfeedback",
    Logic_Template_feedback_Description: "NPS, betyg och öppna kommentarer",
    Logic_Template_event_Name: "Evenemangsanmälan",
    Logic_Template_event_Description: "Deltagaruppgifter, sessioner och kostbehov",
    Logic_Template_itrequest_Name: "IT-serviceförfrågan",
    Logic_Template_itrequest_Description: "Kategoriserade förfrågningar med prioritet och bilagor",
    Logic_Template_expense_Name: "Utläggsrapport",
    Logic_Template_expense_Description: "Rader, kvitton och en beräknad summa",
    Logic_Template_pulse_Name: "Medarbetarpuls",
    Logic_Template_pulse_Description: "Likert-rutnät, engagemangsskala och anonymitetsmeddelande",
    Logic_Template_safety_Name: "Säkerhetsinspektion",
    Logic_Template_safety_Description: "Checklista, foton och en signatur",
    Logic_Template_booking_Name: "Bokning av rum eller resurs",
    Logic_Template_booking_Description: "Resursval via uppslag med en tidslucka",
    Charts_ColumnChartAria: "Kolumndiagram med {count} kategorier",
    Charts_DonutChartAria: "Cirkeldiagram över {count} kategorier",
    Charts_NoAnswers: "Inga svar ännu.",
    Charts_NoResponses: "Inga svar ännu.",
    Charts_Responses: "Svar",
    Charts_ResponsesOverTime: "Svar över tid",
    Responses_Chart_Answer: "Svar",
    Responses_Chart_Average: "Medelvärde",
    Responses_Chart_AverageOf: "Medelvärde av {count}",
    Responses_Chart_AveragePosition: "Genomsnittlig placering",
    Responses_Chart_AverageRange: "Medelvärde (1–{max})",
    Responses_Chart_AvgValue: "medel {value}",
    Responses_Chart_Detractors: "Belackare (0–6)",
    Responses_Chart_Max: "Max",
    Responses_Chart_Maximum: "Maximum",
    Responses_Chart_Median: "Median",
    Responses_Chart_MentionOne: "{count} omnämnande",
    Responses_Chart_MentionOther: "{count} omnämnanden",
    Responses_Chart_Min: "Min",
    Responses_Chart_Minimum: "Minimum",
    Responses_Chart_NoAnswers: "Inga svar ännu.",
    Responses_Chart_NoNumeric: "Inga numeriska svar ännu.",
    Responses_Chart_NoRankings: "Inga rangordningar ännu.",
    Responses_Chart_NoScores: "Inga poäng ännu.",
    Responses_Chart_NotEnoughText: "Inte tillräckligt med text att sammanfatta ännu.",
    Responses_Chart_NpsScore: "NPS-poäng",
    Responses_Chart_Option: "Alternativ",
    Responses_Chart_Passives: "Passiva (7–8)",
    Responses_Chart_Promoters: "Ambassadörer (9–10)",
    Responses_Chart_ResponseOne: "svar",
    Responses_Chart_ResponseOther: "svar",
    Responses_Chart_Responses: "Svar",
    Responses_Chart_ShowingAnswers: "Visar {shown} av {total} svar.",
    Responses_Chart_Statement: "Påstående",
    Responses_Chart_Statistic: "Statistik",
    Responses_Chart_StdDev: "Standardavv.",
    Responses_Chart_StdDeviation: "Standardavvikelse",
    Responses_Chart_Total: "Totalt",
    Responses_Chart_Value: "Värde",
    Responses_Dashboard_AllHidden: "Alla frågor är dolda från instrumentpanelen. Använd “Visa dolda frågor” för att få tillbaka dem.",
    Responses_Dashboard_AnsweredOf: "{answered} av {total} besvarade",
    Responses_Dashboard_AnsweredOfPinned: "{answered} av {total} besvarade · fäst",
    Responses_Dashboard_AveragedAcrossResponses: "Medelvärde över svaren",
    Responses_Dashboard_ByDay: "Per dag",
    Responses_Dashboard_ByMonth: "Per månad",
    Responses_Dashboard_ByWeek: "Per vecka",
    Responses_Dashboard_ChartAuto: "Automatiskt",
    Responses_Dashboard_ChartBars: "Staplar",
    Responses_Dashboard_ChartColumns: "Kolumner",
    Responses_Dashboard_ChartDonut: "Ringdiagram",
    Responses_Dashboard_ChartGauge: "Mätare",
    Responses_Dashboard_ChartHistogram: "Histogram",
    Responses_Dashboard_ChartOptions: "Diagramalternativ",
    Responses_Dashboard_ChartOptionsFor: "Diagramalternativ för {title}",
    Responses_Dashboard_ChartStatistics: "Statistik",
    Responses_Dashboard_ChartTable: "Tabell",
    Responses_Dashboard_ChartWordFrequency: "Ordfrekvens",
    Responses_Dashboard_EmptyBody: "När folk börjar svara fylls den här instrumentpanelen i automatiskt – nyckeltal, en tidslinje över svaren och diagram för de frågor som är värda att följa.",
    Responses_Dashboard_EmptyTitle: "Inga svar ännu",
    Responses_Dashboard_Hide: "Dölj från instrumentpanelen",
    Responses_Dashboard_Highlights: "Höjdpunkter",
    Responses_Dashboard_Last7Days: "Senaste 7 dagarna",
    Responses_Dashboard_LatestDate: "Senaste: {date}",
    Responses_Dashboard_MedianTimeToComplete: "Mediantid för att slutföra",
    Responses_Dashboard_NoPriorWeek: "Ingen föregående vecka att jämföra med",
    Responses_Dashboard_OneEach: "En vardera",
    Responses_Dashboard_Pin: "Fäst på instrumentpanelen",
    Responses_Dashboard_QuestionFallback: "fråga",
    Responses_Dashboard_QuestionsAnswered: "Besvarade frågor",
    Responses_Dashboard_RecordedOnSubmit: "Registreras vid inskickning",
    Responses_Dashboard_RepeatResponses: "{count} upprepade svar",
    Responses_Dashboard_ResponsesOverTime: "Svar över tid",
    Responses_Dashboard_ShowHidden: "Visa dolda frågor",
    Responses_Dashboard_SinceMidnight: "Sedan midnatt",
    Responses_Dashboard_Today: "Idag",
    Responses_Dashboard_TotalResponses: "Totalt antal svar",
    Responses_Dashboard_UniqueRespondents: "Unika svarande",
    Responses_Dashboard_Unpin: "Lossa från instrumentpanelen",
    Responses_Dashboard_UntitledQuestion: "Fråga utan titel",
    Responses_Dashboard_VsPrevious7Days: "jämfört med föregående 7 dagar",
    Responses_Detail_Answers: "Svar",
    Responses_Detail_AsTheForm: "Som i formuläret",
    Responses_Detail_Cancel: "Avbryt",
    Responses_Detail_Delete: "Ta bort",
    Responses_Detail_DeleteBody: "Listobjektet flyttas till webbplatsens papperskorg, så det kan återställas därifrån.",
    Responses_Detail_DeleteTitle: "Ta bort det här svaret?",
    Responses_Detail_Deleting: "Tar bort…",
    Responses_Detail_Draft: "Utkast",
    Responses_Detail_Header: "Svar {index} av {total}",
    Responses_Detail_LoadingAttachments: "Läser in bilagor…",
    Responses_Detail_Next: "Nästa svar",
    Responses_Detail_NoAnswer: "Inget svar",
    Responses_Detail_Previous: "Föregående svar",
    Responses_Detail_Print: "Skriv ut",
    Responses_Detail_Signature: "Signatur",
    Responses_Detail_Signed: "Signerad",
    Responses_Detail_Took: "tog {duration}",
    Responses_Summary_AnsweredOfType: "{answered} av {total} besvarade · {type}",
    Responses_Summary_ByField: "Efter {title}",
    Responses_Summary_CompareBy: "Jämför efter…",
    Responses_Summary_EmptyBody: "Varje fråga får sin egen sammanfattning här.",
    Responses_Summary_NoComparison: "Ingen jämförelse",
    Responses_Summary_NothingToCompare: "Ingen har svarat på “{title}”, så det finns inget att jämföra.",
    Responses_Summary_OtherNote: "Diagram med fler än {max} kategorier grupperar de minsta under “Annat” – växla ett kort till Tabell för att se alla värden.",
    Responses_Summary_ResponseCountOne: "{count} svar",
    Responses_Summary_ResponseCountOther: "{count} svar",
    Responses_Summary_SeeAllAnswers: "Se alla svar i tabellen",
    Responses_Summary_SegmentNote: "Visar de {groups} största grupperna. Ett svar med flera valda alternativ visas i varje matchande grupp, så gruppsummorna kan bli större än {total}.",
    Responses_Summary_SplitBy: "Dela upp efter {title}",
    Responses_Summary_Untitled: "utan titel",
    Responses_Table_Apply: "Använd",
    Responses_Table_Cancel: "Avbryt",
    Responses_Table_ClearSelection: "Rensa markering",
    Responses_Table_ColumnOrder: "Kolumnordning",
    Responses_Table_ColumnsCount: "Kolumner ({shown}/{total})",
    Responses_Table_Delete: "Ta bort",
    Responses_Table_DeleteBody: "Listobjekten flyttas till webbplatsens papperskorg, så de kan återställas därifrån.",
    Responses_Table_DeleteSelected: "Ta bort markerade",
    Responses_Table_DeleteTitleOne: "Ta bort {count} svar?",
    Responses_Table_DeleteTitleOther: "Ta bort {count} svar?",
    Responses_Table_Deleting: "Tar bort…",
    Responses_Table_MoveDown: "Flytta ned",
    Responses_Table_MoveDownFor: "Flytta ned {title}",
    Responses_Table_MoveUp: "Flytta upp",
    Responses_Table_MoveUpFor: "Flytta upp {title}",
    Responses_Table_NoColumns: "Inga frågekolumner är synliga ännu.",
    Responses_Table_NoMatch: "Inga svar matchar de aktuella filtren.",
    Responses_Table_NothingToShow: "Inget att visa",
    Responses_Table_OpenResponse: "Öppna det här svaret",
    Responses_Table_OrderNote: "Skickades och Skickades av kommer alltid först. Dragordningen gäller frågekolumnerna.",
    Responses_Table_Reorder: "Ändra ordning",
    Responses_Table_ResetColumns: "Återställ kolumner",
    Responses_Table_SelectResponse: "Markera det här svaret",
    Responses_Table_SelectedOne: "{count} svar markerat",
    Responses_Table_SelectedOther: "{count} svar markerade",
    Responses_Table_ShowAll: "Visa alla",
    Responses_Table_ShowTheseQuestions: "Visa de här frågorna",
    Responses_Table_Submitted: "Skickades",
    Responses_Table_SubmittedBy: "Skickades av",
    Responses_Table_ToggleSelection: "Växla markering",
    Responses_Table_Unknown: "Okänd",
    Responses_Table_Untitled: "Utan titel",
    Responses_View_AllTime: "Alla tider",
    Responses_View_AnyAnswer: "Valfritt svar",
    Responses_View_Clear: "Rensa",
    Responses_View_CopyShareLink: "Kopiera delningslänk",
    Responses_View_CountFiltered: "{shown} av {total} svar",
    Responses_View_CountOne: "{count} svar",
    Responses_View_CountOther: "{count} svar",
    Responses_View_Dashboard: "Instrumentpanel",
    Responses_View_DateRange: "Datumintervall",
    Responses_View_EmptyBody: "Dela formuläret för att börja samla in svar. Svaren sparas i “{list}” och visas här direkt.",
    Responses_View_EmptyTitle: "Inga svar ännu",
    Responses_View_ExportCsv: "Exportera CSV",
    Responses_View_FilterByAnswer: "Filtrera efter svar",
    Responses_View_FilterByQuestion: "Filtrera efter fråga",
    Responses_View_FilterValue: "Filtervärde",
    Responses_View_Last30Days: "Senaste 30 dagarna",
    Responses_View_Last7Days: "Senaste 7 dagarna",
    Responses_View_Last90Days: "Senaste 90 dagarna",
    Responses_View_LoadError: "Svaren kunde inte läsas in. Publicera formuläret en gång så att listkolumnerna finns och försök sedan igen.",
    Responses_View_Loading: "Läser in svar…",
    Responses_View_MoreActions: "Fler åtgärder för svar",
    Responses_View_PreviewForm: "Förhandsgranska formuläret",
    Responses_View_Refresh: "Uppdatera",
    Responses_View_ResponsesTab: "Svar ({count})",
    Responses_View_SearchPlaceholder: "Sök i alla svar",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Välj ett värde",
    Responses_View_Summary: "Sammanfattning",
    Responses_View_Today: "Idag",
    Responses_View_Truncated: "Den här listan har fler svar än Smart Forms läser in på en gång. De senaste {count} visas – öppna listan i Microsoft Lists för att se hela uppsättningen.",
    Responses_View_TryAgain: "Försök igen",
    Responses_View_Untitled: "Utan titel",
    Responses_Approval_Column: "Godkännande",
    Responses_Approval_ReviewerColumn: "Granskad av",
    Responses_Approval_CommentColumn: "Granskarens kommentar",
    Responses_Approval_Pending: "Väntar",
    Responses_Approval_Approved: "Godkänd",
    Responses_Approval_Rejected: "Avslagen",
    Responses_Approval_AnyStatus: "Valfri godkännandestatus",
    Responses_Approval_FilterLabel: "Filtrera efter godkännandestatus",
    Responses_Approval_ApproveSelected: "Godkänn markerade",
    Responses_Approval_RejectSelected: "Avslå markerade",
    Responses_Approval_BulkFailed: "{count} svar kunde inte uppdateras. Försök igen.",
    Responses_Approval_Approve: "Godkänn",
    Responses_Approval_Reject: "Avslå",
    Responses_Approval_Reset: "Återställ till väntar",
    Responses_Approval_CommentLabel: "Kommentar (valfritt)",
    Responses_Approval_ReviewedBy: "Granskad av {name}",
    Responses_Approval_Error: "Beslutet kunde inte sparas. Försök igen.",
    Responses_Dashboard_ApprovalStatus: "Väntar på granskning",
    Responses_Dashboard_ApprovalBreakdown: "{pending} väntar, {approved} godkända, {rejected} avslagna",
    Responses_Dashboard_TimelineCoarsened: "Datumintervallet är långt, så tidslinjen grupperades grövre ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Datumintervallet är mycket långt, så endast de senaste {count} perioderna visas.",
    Service_Item_DefaultTitle: "Svar – {date}",
    Service_Email_ApprovalSubject: "Ditt svar blev {status} – {title}",
    Service_Email_ApprovalHeading: "Ditt svar blev {status}",
    Service_Email_ApprovalIntro: "En granskare markerade ditt svar på \"{title}\" som {status}.",
    Service_Email_ApprovalCommentLabel: "Granskarens kommentar",
    Service_Approval_Approved: "godkänt",
    Service_Approval_Rejected: "avslaget",
    Service_Approval_Pending: "väntande",
    Service_Lookup_InvalidFilter: "Uppslagsfiltret är inte giltigt.",
    Service_Edit_NotAllowed: "Det här formuläret tillåter inte redigering av ett skickat svar.",
    Service_Edit_NotYours: "Du kan bara redigera ditt eget svar.",
    Service_Signature_AttachmentLabel: "Signatur",
    PropertyPane_ListsLoadFailed: "Listorna på den här webbplatsen kunde inte läsas in.",
    PropertyPane_EnterListName: "Ange först ett namn för den nya listan.",
    PropertyPane_CreatingList: "Skapar \"{name}\"…",
    PropertyPane_ListCreated: "Listan \"{title}\" har skapats och valts.",
    PropertyPane_ListAlreadyExists: "En lista med namnet \"{name}\" finns redan – välj den i listrutan ovan.",
    PropertyPane_CreateListFailed: "Det gick inte att skapa listan. Kontrollera att du har behörighet att skapa listor på den här webbplatsen.",
    PropertyPane_Description: "Välj den SharePoint-lista som lagrar formulärsvaren, eller skapa en ny. Allt annat – frågor, utseende, aviseringar – redigeras direkt på sidan.",
    PropertyPane_ResponseList_GroupName: "Svarslista",
    PropertyPane_ListDropdown_Label: "Spara svar i den här listan",
    PropertyPane_ResponsesGoTo: "Svar skickas till \"{name}\".",
    PropertyPane_PickList: "Välj en lista eller skapa en nedan.",
    PropertyPane_LoadingLists: "Läser in listor…",
    PropertyPane_NewListName_Label: "Eller skapa en ny lista",
    PropertyPane_NewListName_Placeholder: "Namn på ny lista",
    PropertyPane_CreateList_Button: "Skapa lista",
    PropertyPane_Tips_GroupName: "Tips",
    PropertyPane_Tip_AutoSave: "Frågor och inställningar sparas automatiskt när du redigerar – du behöver inte spara eller publicera sidan.",
    PropertyPane_Tip_Permissions: "Svarande behöver behörighet att lägga till objekt i svarslistan. Kontrollera listans behörigheter om någon rapporterar ett fel vid inskickning.",
    PropertyPane_Tip_Share: "Använd \"Samla in svar\" på sidan för att skapa listkolumnerna och få en delbar länk för ifyllning.",
    App_ErrorBoundary_Title: "Smart Forms – renderingsfel",
    App_ErrorBoundary_Message: "Meddelande:",
    App_ErrorBoundary_Stack: "Stack:",
    App_ErrorBoundary_NoStack: "(ingen stack tillgänglig)",
    App_ErrorBoundary_ConsoleNote: "Fullständig information skrevs också till webbläsarens konsol.",
    App_DefaultQuestionTitle: "Fråga {number}",
    App_Error_ListMissing: "Listan som är konfigurerad för det här formuläret finns inte längre. Välj en annan lista i webbdelens inställningar.",
    App_Error_LoadConfig: "Något gick fel när formulärkonfigurationen lästes in.",
    App_Error_Unable: "Det gick inte att läsa in formuläret.",
    App_Publish_ConflictNotice: "\"{title}\" har redan en listkolumn av en annan typ ({type}). Byt namn på frågan så att en ny kolumn kan skapas, eller ändra tillbaka typen.",
    App_Publish_ConflictUnnamedQuestion: "en fråga",
    App_Publish_ColumnsAddedOne: "{count} kolumn lades till i \"{list}\".",
    App_Publish_ColumnsAddedOther: "{count} kolumner lades till i \"{list}\".",
    App_Publish_TheList: "listan",
    App_Publish_UpToDate: "Svarslistan är redan uppdaterad.",
    App_Publish_Error: "Listkolumnerna kunde inte skapas. Det betyder vanligtvis att du inte har behörigheten Hantera listor för svarslistan, men det kan också hända på webbplatser där anpassade skript är inaktiverade. Kontrollera webbläsarkonsolen för det underliggande felet eller försök igen.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Bygg ett snyggt formulär ovanpå en SharePoint-lista – {count} frågetyper, förgreningslogik, filuppladdningar, delbara ifyllningslänkar och en resultatinstrumentpanel.",
    App_Placeholder_ChooseList: "Välj eller skapa en lista",
    App_Placeholder_Hint: "Redigera sidan och konfigurera den här webbdelen för att komma igång.",
    App_Loading: "Läser in formulär…",
    App_OpenSettings: "Öppna inställningar",
    App_Tab_Questions: "Frågor",
    App_Tab_QuestionsWithCount: "Frågor ({count})",
    App_Tab_Responses: "Svar",
    App_Tab_Responses_Title: "Svar sparas i \"{list}\"",
    App_Templates_Start: "Börja från en mall",
    App_Settings_Title: "Formulärinställningar – utseende, aviseringar, åtkomst",
    App_Settings_AriaLabel: "Formulärinställningar",
    App_Preview: "Förhandsgranska",
    App_Preview_Close: "Stäng förhandsgranskningen",
    App_Preview_Hint: "Förhandsgranskning – ingenting du skickar in här sparas. Validering och förgrening beter sig precis som för de svarande.",
    App_Publish_GettingReady: "Gör klart…",
    App_Publish_CollectResponses: "Samla in svar",
    App_Publish_Share: "Dela",
    App_Retry: "Försök igen",
    App_SaveError_Banner: "Din senaste ändring kunde inte sparas. Kontrollera anslutningen och försök igen.",
    App_Preflight_BlockingTitle: "Åtgärda detta innan du samlar in svar",
    App_Preflight_WarningTitle: "Värt att titta på först",
    App_Preflight_BlockingText: "Det här skulle hindra det publicerade formuläret från att fungera som det ska.",
    App_Preflight_WarningText: "Inget är trasigt, men det här är oftast värt att åtgärda innan du delar länken.",
    App_Preflight_GoTo: "Gå till",
    App_Preflight_CollectAnyway: "Samla in svar ändå",
    App_Preflight_Back: "Tillbaka till formuläret",
    App_Cancel: "Avbryt",
    App_Done: "Klar",
    App_Share_Title: "Ditt formulär är redo att delas",
    App_Share_SubText: "Skicka den här länken till alla som ska fylla i formuläret.",
    App_Share_LinkAriaLabel: "Delningslänk",
    App_Share_Copy: "Kopiera",
    App_Share_Copied: "Kopierad",
    App_Share_AddItemsEmphasis: "lägga till objekt",
    App_Share_PermissionNote: "Svarande behöver behörighet att {addItems} i “{title}” och åtkomst till den här sidan. Om någon får ett fel vid inskickning är det nästan alltid därför.",
    App_Share_PrefillNote: "Du kan förifylla svar på frågor i länken genom att lägga till kolumnnamnet, till exempel {example}.",
    App_Templates_ReplaceWarning: "Om du väljer en mall ersätts de frågor du har nu.",
    App_Templates_PickStart: "Välj en utgångspunkt – du kan ändra allt efteråt.",
    App_Templates_Empty: "Tomt",
    App_Templates_QuestionCount: "{count} frågor",
    App_SaveChip_SavingTitle: "Sparar din senaste ändring",
    App_SaveChip_Saving: "Sparar…",
    App_SaveChip_FailedTitle: "Din senaste ändring kunde inte sparas. Kontrollera anslutningen och försök igen.",
    App_SaveChip_Failed: "Det gick inte att spara",
    App_SaveChip_SavedTitle: "Alla ändringar är sparade",
    App_SaveChip_Saved: "Sparat",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Nytt svar – {title}",
    Service_Email_NewResponseHeading: "Nytt svar: {title}",
    Service_Email_NewResponseIntro: "Någon har just skickat in ett svar – {date}.",
    Service_Email_ReceiptSubject: "Ditt svar – {title}",
    Service_Email_ReceiptHeading: "Tack för ditt svar!",
    Service_Email_ReceiptIntro: "Här är en kopia av det du skickade till \"{title}\".",
    App_History_Title: "Versionshistorik",
    App_History_RestoredNotice: "Versionen som sparades {date} har återställts. Granska den och använd sedan Samla in svar för att publicera nya frågor.",
    App_History_Undo: "Ångra återställning",
    App_Share_CopyManual: "Webbläsaren blockerade kopiering. Markera länken ovan och tryck på Ctrl+C (Cmd+C på Mac) för att kopiera den.",
    App_Share_TeamsNote: "Du är i Microsoft Teams. Länken öppnar SharePoint-sidan direkt, så mottagarna behöver åtkomst till webbplatsen.",
    App_Share_PrefillNotSecure: "Förifyllda svar är bara en bekvämlighet: alla med länken kan ändra dem, så behandla dem aldrig som en säkerhetsgräns.",
    Designer_Section_DropHere: "Släpp en fråga här",
    Designer_Section_DropEnd: "Släpp här för att flytta till slutet av det här avsnittet",
    Designer_Rules_RemovedOne: "1 förgreningsregel som inte längre passade har tagits bort.",
    Designer_Rules_RemovedOther: "{count} förgreningsregler som inte längre passade har tagits bort.",
    Designer_Settings_AllowEdit: "Tillåt svarande att redigera sitt svar",
    Designer_Settings_AllowEditHint: "Svarande kan öppna och uppdatera det de har skickat. Var och en kan bara redigera sitt eget svar.",
    Designer_Settings_EnableApproval: "Aktivera godkännandeflöde",
    Designer_Settings_ApprovalNotify: "Skicka e-post till svarande vid beslut",
    Designer_Settings_ApprovalHint: "Lägger till godkännandekolumner i svarslistan nästa gång du publicerar. Ägare godkänner eller avslår svar på fliken Svar.",
    Designer_History_Title: "Versionshistorik",
    Designer_History_Intro: "Tidigare sparade versioner av formulärets frågor och inställningar. Vid återställning läses en version in i designern; du kan ångra det, och nya frågor skapas först när du publicerar.",
    Designer_History_Loading: "Läser in versioner...",
    Designer_History_Empty: "Inga tidigare versioner hittades. Versionshistorik kräver att versionshantering är aktiverad för listan \"Smart Forms Config\" och minst en sparad ändring.",
    Designer_History_Latest: "Senaste",
    Designer_History_LatestTitle: "Det här är den version som används just nu",
    Designer_History_By: "av {name}",
    Designer_History_UnknownAuthor: "Okänd författare",
    Designer_History_VersionLabel: "version {label}",
    Designer_History_Preview: "Förhandsgranska",
    Designer_History_Restore: "Återställ",
    Designer_History_QuestionsOne: "1 fråga",
    Designer_History_QuestionsOther: "{count} frågor",
    Designer_History_LoadFailed: "Den här versionen kunde inte läsas in.",
    Designer_History_ConfirmTitle: "Återställa den här versionen?",
    Designer_History_ConfirmText: "Formuläret ersätts med versionen som sparades {date} ({count} frågor). Du kan ångra det direkt efteråt."
  };
});
