define([], function () {
  return {
    Designer_Color_Blue: "น้ำเงิน",
    Designer_Color_Teal: "เขียวน้ำเงิน",
    Designer_Color_Green: "เขียว",
    Designer_Color_Purple: "ม่วง",
    Designer_Color_Magenta: "บานเย็น",
    Designer_Color_Red: "แดง",
    Designer_Color_Orange: "ส้ม",
    Designer_Color_Gray: "เทา",
    Designer_Settings_LayoutSinglePage: "คำถามทั้งหมดในหน้าเดียว",
    Designer_Settings_LayoutWizard: "หนึ่งส่วนต่อขั้นตอน (ตัวช่วยสร้าง)",
    Designer_Settings_Title: "การตั้งค่าฟอร์ม",
    Designer_Common_Apply: "นำไปใช้",
    Designer_Common_Cancel: "ยกเลิก",
    Designer_Settings_TabBasics: "พื้นฐาน",
    Designer_Settings_FormTitle: "ชื่อฟอร์ม",
    Designer_Settings_Description: "คำอธิบาย",
    Designer_Settings_Layout: "เค้าโครง",
    Designer_Settings_NumberQuestions: "ใส่หมายเลขคำถาม",
    Designer_Settings_ShuffleQuestions: "สลับลำดับคำถามสำหรับผู้ตอบแต่ละคน",
    Designer_Settings_ShowProgressBar: "แสดงแถบความคืบหน้า",
    Designer_Settings_TabAppearance: "รูปลักษณ์",
    Designer_Settings_AccentColor: "สีเน้น",
    Designer_Settings_CustomColorTitle: "สีที่กำหนดเอง",
    Designer_Settings_CustomColorAria: "สีเน้นที่กำหนดเอง",
    Designer_Settings_AccentHint: "สีเน้นจะได้รับการปรับอัตโนมัติเพื่อความคมชัดบนไซต์โทนมืด ฟอร์มจึงอ่านง่ายไม่ว่าหน้าจะใช้ชุดรูปแบบใด",
    Designer_Settings_ShowHeader: "แสดงส่วนหัวของฟอร์ม",
    Designer_Settings_HeaderIcon: "ไอคอนส่วนหัว",
    Designer_Settings_TabAfterSubmit: "หลังจากส่ง",
    Designer_Settings_SubmitButtonText: "ข้อความบนปุ่มส่ง",
    Designer_Settings_SubmitPlaceholder: "ส่ง",
    Designer_Settings_ThankYouTitle: "หัวข้อขอบคุณ",
    Designer_Settings_ThankYouPlaceholder: "ขอบคุณ!",
    Designer_Settings_ThankYouMessage: "ข้อความขอบคุณ",
    Designer_Settings_ShowSubmitAnother: "แสดงปุ่ม \"ส่งการตอบกลับอีกครั้ง\"",
    Designer_Settings_TabNotifications: "การแจ้งเตือน",
    Designer_Settings_EmailEachResponseTo: "ส่งอีเมลการตอบกลับแต่ละรายการไปยัง",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "ผู้ใช้ในองค์กรของคุณจะได้รับการตอบกลับทุกรายการทางอีเมลพร้อมลิงก์ไปยังรายการในรายการ",
    Designer_Settings_RespondentReceipt: "ส่งอีเมลสำเนาคำตอบให้ผู้ตอบ",
    Designer_Settings_NotificationsInfo: "การแจ้งเตือนใช้บริการอีเมลของ SharePoint เอง ผู้รับจึงต้องเป็นผู้ใช้ในองค์กรของคุณ ที่อยู่ภายนอกจะถูกละทิ้งโดยไม่มีการแจ้งเตือน",
    Designer_Settings_TabAccess: "การเข้าถึง",
    Designer_Settings_OpenFrom: "เปิดตั้งแต่",
    Designer_Settings_OpenImmediately: "เปิดทันที",
    Designer_Settings_CloseAfter: "ปิดหลังจาก",
    Designer_Settings_NeverClose: "ไม่ปิดเลย",
    Designer_Settings_ClearDates: "ล้างวันที่",
    Designer_Settings_DatesInverted: "วันที่ปิดตรงกับหรือก่อนวันที่เปิด ฟอร์มจึงจะไม่รับการตอบกลับเลย",
    Designer_Settings_MaxResponses: "หยุดหลังจากมีการตอบกลับตามจำนวนนี้",
    Designer_Settings_NoLimit: "ไม่จำกัด",
    Designer_Settings_OneResponsePerPerson: "อนุญาตเพียงหนึ่งการตอบกลับต่อคน",
    Designer_Settings_AllowSaveDraft: "ให้ผู้ตอบบันทึกแบบร่างและกลับมาทำต่อภายหลัง",
    Designer_Settings_ClosedMessage: "ข้อความที่แสดงเมื่อฟอร์มปิด",
    Designer_Settings_ClosedMessagePlaceholder: "ฟอร์มนี้ไม่รับการตอบกลับอีกต่อไป",
    Designer_Settings_AccessInfo: "ฟอร์มเป็นผู้บังคับใช้ขีดจำกัดเหล่านี้ ไม่ใช่ SharePoint ผู้ที่มีสิทธิ์เพิ่มรายการลงในรายการการตอบกลับยังคงเพิ่มรายการโดยตรงผ่านรายการได้",
    Designer_Field_StyleInfo: "ข้อมูล (สีเน้น)",
    Designer_Field_StyleSuccess: "สำเร็จ (สีเขียว)",
    Designer_Field_StyleWarning: "คำเตือน (สีเหลืองอำพัน)",
    Designer_Field_StylePlain: "ข้อความธรรมดา",
    Designer_Field_StyleDivider: "เส้นแบ่ง",
    Designer_Field_IconStars: "ดาว",
    Designer_Field_IconHearts: "หัวใจ",
    Designer_Field_IconThumbs: "ยกนิ้ว",
    Designer_Field_FormatPlain: "ตัวเลขธรรมดา",
    Designer_Field_FormatCurrency: "สกุลเงิน",
    Designer_Field_FormatPercent: "เปอร์เซ็นต์",
    Designer_Field_UntitledQuestion: "คำถามที่ไม่มีชื่อ",
    Designer_Field_DeletedQuestion: "คำถามที่ถูกลบ",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} และ {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "หรือ",
    Designer_Rule_JoinAll: "และ",
    Designer_Rule_Preview: "แสดงเมื่อ {conditions}",
    Designer_Field_Yes: "ใช่",
    Designer_Field_No: "ไม่ใช่",
    Designer_Field_When: "เมื่อ",
    Designer_Field_SelectValue: "เลือกค่า",
    Designer_Field_DateValuePlaceholder: "YYYY-MM-DD หรือ \"today\"",
    Designer_Field_ValuePlaceholder: "ค่า",
    Designer_Field_UpperBound: "ขอบเขตบน",
    Designer_Field_RemoveCondition: "ลบเงื่อนไขนี้",
    Designer_Field_FormulaInvalid: "ไม่สามารถคำนวณสูตรนี้ได้ ตรวจสอบวงเล็บและตัวดำเนินการ",
    Designer_Field_FormulaMissing: "ไม่มีคำถามเหล่านี้: {names}",
    Designer_Field_FormulaPreview: "เมื่อค่าอินพุตทั้งหมดเป็น 10 จะแสดง {value}",
    Designer_Field_HintYesNo: "ใช้ \"yes\" หรือ \"no\"",
    Designer_Field_HintMultiDefault: "คั่นค่าเริ่มต้นหลายค่าด้วย ;",
    Designer_Field_HintSingleDefault: "ต้องตรงกับหนึ่งในตัวเลือก",
    Designer_Field_HintDate: "ใช้ \"today\" หรือวันที่ เช่น 2026-03-01",
    Designer_Field_HintTime: "ใช้ \"now\" หรือเวลา เช่น 09:30",
    Designer_Field_QuestionSettings: "การตั้งค่าคำถาม",
    Designer_Field_Appearance: "รูปลักษณ์",
    Designer_Field_Style: "สไตล์",
    Designer_Field_ImageUrl: "URL รูปภาพ (ไม่บังคับ)",
    Designer_Field_Content: "เนื้อหา",
    Designer_Field_BasicFormatting: "อนุญาตการจัดรูปแบบพื้นฐาน: ตัวหนา ตัวเอียง รายการ และลิงก์",
    Designer_Field_TabOptions: "ตัวเลือก",
    Designer_Field_TabBranching: "การแตกสาขา",
    Designer_Field_BranchingNeedsQuestion: "เพิ่มคำถามอื่นก่อน เพราะการแตกสาขาต้องมีสิ่งที่ใช้อ้างอิง",
    Designer_Field_BranchingToggle: "แสดงคำถามนี้เฉพาะเมื่อคำตอบอื่นตรงตามเงื่อนไข",
    Designer_Field_Match: "ตรงกัน",
    Designer_Field_MatchAll: "ทั้งหมดนี้",
    Designer_Field_MatchAny: "อย่างใดอย่างหนึ่งนี้",
    Designer_Field_AddCondition: "เพิ่มเงื่อนไข",
    Designer_Field_TabValidation: "การตรวจสอบ",
    Designer_Field_HelpText: "ข้อความช่วยเหลือ",
    Designer_Field_HelpTextPlaceholder: "แสดงใต้ป้ายชื่อคำถาม",
    Designer_Field_CheckboxLabel: "ป้ายชื่อช่องทำเครื่องหมาย",
    Designer_Field_Placeholder: "ตัวยึดตำแหน่ง",
    Designer_Field_DefaultAnswer: "คำตอบเริ่มต้น",
    Designer_Field_RequiredMessage: "ข้อความแจ้งว่าจำเป็นต้องกรอกแบบกำหนดเอง",
    Designer_Field_RequiredMessagePlaceholder: "ต้องกรอก {title}",
    Designer_Field_ThisQuestion: "คำถามนี้",
    Designer_Field_RequiredMessageDescription: "แสดงแทนข้อความมาตรฐานเมื่อไม่ได้ตอบคำถามนี้",
    Designer_Field_ReadOnly: "อ่านอย่างเดียว (คำตอบมาจากลิงก์ที่กรอกไว้ล่วงหน้าเท่านั้น)",
    Designer_Field_ValidationRules: "กฎการตรวจสอบ",
    Designer_Field_MaxLength: "ความยาวสูงสุด",
    Designer_Field_Pattern: "ต้องตรงกับรูปแบบนี้",
    Designer_Field_PatternDescription: "นิพจน์ทั่วไป เว้นว่างไว้หากไม่ต้องการตรวจสอบรูปแบบ",
    Designer_Field_PatternMessage: "ข้อความเมื่อไม่ตรงกับรูปแบบ",
    Designer_Field_PatternMessagePlaceholder: "คำตอบนี้ไม่อยู่ในรูปแบบที่คาดไว้",
    Designer_Field_Format: "รูปแบบ",
    Designer_Field_UnitSuffix: "หน่วยที่แสดงหลังค่า",
    Designer_Field_UnitSuffixPlaceholder: "กก., ชม., รายการ…",
    Designer_Field_Minimum: "ต่ำสุด",
    Designer_Field_Maximum: "สูงสุด",
    Designer_Field_Decimals: "ทศนิยม",
    Designer_Field_Formula: "สูตร",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "อ้างอิงคำถามอื่นด้วยข้อความของคำถามในวงเล็บปีกกา รองรับ + - * / ( ) และ round, min, max, sum, avg",
    Designer_Field_AvailableQuestions: "คำถามที่ใช้ได้: {questions}",
    Designer_Field_NoneYet: "ยังไม่มี",
    Designer_Field_Step: "ช่วงห่าง",
    Designer_Field_From: "จาก",
    Designer_Field_To: "ถึง",
    Designer_Field_LowLabel: "ป้ายชื่อที่ปลายด้านต่ำ",
    Designer_Field_LowLabelPlaceholder: "ไม่มีโอกาสเลย",
    Designer_Field_HighLabel: "ป้ายชื่อที่ปลายด้านสูง",
    Designer_Field_HighLabelPlaceholder: "มีโอกาสอย่างยิ่ง",
    Designer_Field_SummarizeAs: "สรุปเป็น",
    Designer_Field_SummarizeAverage: "ค่าเฉลี่ยและการแจกแจง",
    Designer_Field_SummarizeNps: "Net Promoter Score (ต้องใช้มาตราส่วน 0–10)",
    Designer_Field_NpsWarning: "Net Promoter Score มีความหมายเฉพาะบนมาตราส่วน 0–10 ตั้งค่า จาก เป็น 0 และ ถึง เป็น 10",
    Designer_Field_NumberOfIcons: "จำนวนไอคอน",
    Designer_Field_Icon: "ไอคอน",
    Designer_Field_AllowHalf: "อนุญาตค่าครึ่งหนึ่ง",
    Designer_Field_ShowOptionsAs: "แสดงตัวเลือกเป็น",
    Designer_Field_DisplayButtons: "ปุ่มแบบอินไลน์",
    Designer_Field_DisplayDropdown: "รายการแบบเลื่อนลง",
    Designer_Field_DisplayAutomatic: "อัตโนมัติ (แบบอินไลน์ไม่เกิน 6 ตัวเลือก)",
    Designer_Field_AllowOther: "เพิ่มตัวเลือก \"อื่นๆ\" ให้พิมพ์เอง",
    Designer_Field_OtherLabel: "ป้ายชื่อสำหรับตัวเลือก \"อื่นๆ\"",
    Designer_Field_OtherPlaceholder: "อื่นๆ",
    Designer_Field_ShuffleOptions: "สลับลำดับตัวเลือกสำหรับผู้ตอบแต่ละคน",
    Designer_Field_MinSelections: "จำนวนที่เลือกขั้นต่ำ",
    Designer_Field_MaxSelections: "จำนวนที่เลือกสูงสุด",
    Designer_Field_SourceList: "รายการต้นทาง",
    Designer_Field_ChooseList: "เลือกรายการ",
    Designer_Field_LookupColumn: "คอลัมน์ที่ใช้อ่านตัวเลือก",
    Designer_Field_ChooseColumn: "เลือกคอลัมน์",
    Designer_Field_ChooseListFirst: "เลือกรายการก่อน",
    Designer_Field_LookupFilter: "ตัวกรอง (ไม่บังคับ)",
    Designer_Field_LookupFilterDescription: "ตัวกรอง OData ที่จำกัดว่ารายการต้นทางใดจะกลายเป็นตัวเลือก",
    Designer_Field_LookupInfo: "คำตอบจะเก็บข้อความของตัวเลือก ไม่ใช่ลิงก์ไปยังรายการต้นทาง คำตอบจึงยังอ่านได้แม้รายการต้นทางเปลี่ยนแปลงในภายหลัง",
    Designer_Field_ConsentText: "ข้อกำหนดที่แสดงเหนือช่องทำเครื่องหมาย",
    Designer_Field_AllowMultiplePeople: "อนุญาตหลายคน",
    Designer_Field_AllowGroups: "อนุญาตกลุ่มด้วย",
    Designer_Field_IncludeTime: "รวมเวลาของวัน",
    Designer_Field_TimeStep: "ช่วงเวลา (นาที)",
    Designer_Field_MaxFiles: "จำนวนไฟล์สูงสุด",
    Designer_Field_MaxFileSize: "ขนาดสูงสุดต่อไฟล์ (MB)",
    Designer_Field_AcceptedTypes: "ประเภทไฟล์ที่ยอมรับ",
    Designer_Field_AcceptedTypesDescription: "นามสกุลไฟล์คั่นด้วยเครื่องหมายจุลภาค เว้นว่างไว้เพื่อยอมรับทุกอย่างที่ SharePoint อนุญาต",
    Designer_Field_FilesInfo: "ไฟล์จะถูกบันทึกเป็นไฟล์แนบของรายการตอบกลับ SharePoint บล็อกบางนามสกุล (เช่น .exe) ไม่ว่าคุณจะอนุญาตไว้ที่นี่หรือไม่",
    Designer_Field_Rows: "แถว",
    Designer_Field_ProvisionedNote: "คำถามนี้มีคอลัมน์รายการอยู่แล้ว ({name}) การตั้งค่าที่เปลี่ยนประเภทของคอลัมน์ถูกล็อก ให้ทำสำเนาคำถามหากต้องการประเภทอื่น",
    Designer_Category_Text: "ข้อความ",
    Designer_Category_Choice: "ตัวเลือก",
    Designer_Category_Scales: "มาตราส่วน",
    Designer_Category_Date: "วันที่",
    Designer_Category_People: "บุคคล",
    Designer_Category_Advanced: "ขั้นสูง",
    Designer_Category_Layout: "เค้าโครง",
    Designer_Menu_CommonPresets: "ค่าที่ตั้งไว้ล่วงหน้าที่ใช้บ่อย",
    Designer_Menu_AllTypes: "ประเภทคำถามทั้งหมด",
    Designer_Menu_ChangeType: "เปลี่ยนประเภท",
    Designer_Menu_TypeLockedTitle: "คอลัมน์รายการมีอยู่แล้ว ประเภทจึงถูกล็อก ให้ทำสำเนาคำถามเพื่อเปลี่ยนประเภท",
    Designer_Menu_MoreSettings: "การแตกสาขา การตรวจสอบ และอื่นๆ",
    Designer_Menu_InsertBelow: "แทรกคำถามด้านล่าง",
    Designer_Card_Duplicate: "ทำสำเนา",
    Designer_Card_DeleteQuestion: "ลบคำถาม",
    Designer_Outline_Aria: "โครงร่างคำถาม",
    Designer_Outline_QuestionCountOne: "{count} คำถาม",
    Designer_Outline_QuestionCountOther: "{count} คำถาม",
    Designer_Outline_IssuesTitle: "มี {count} ปัญหาที่ต้องตรวจสอบ",
    Designer_Outline_Find: "ค้นหาคำถาม",
    Designer_Outline_Empty: "ยังไม่มีคำถาม",
    Designer_Section_DefaultTitle: "ส่วนที่ {number}",
    Designer_Card_Question: "คำถาม",
    Designer_Card_BranchingTitle: "คำถามนี้จะแสดงเมื่อตรงตามกฎการแตกสาขาเท่านั้น",
    Designer_Card_BranchingChip: "การแตกสาขา",
    Designer_Card_LiveTitle: "คอลัมน์รายการมีอยู่แล้ว ประเภทจึงถูกล็อก",
    Designer_Card_LiveChip: "ใช้งานจริง",
    Designer_Card_CheckChip: "ตรวจสอบ",
    Designer_Option_Placeholder: "ตัวเลือก {number}",
    Designer_Option_LabelAria: "ป้ายชื่อตัวเลือก {number}",
    Designer_Option_ImageUrl: "URL รูปภาพ",
    Designer_Option_ImageUrlAria: "URL รูปภาพของตัวเลือก {number}",
    Designer_Option_Remove: "ลบตัวเลือก",
    Designer_Option_RemoveAria: "ลบตัวเลือก {number}",
    Designer_Option_Add: "เพิ่มตัวเลือก",
    Designer_Option_OtherHint: "ผู้ตอบสามารถพิมพ์คำตอบเองที่มีป้ายชื่อ “{label}” ได้ด้วย",
    Designer_Option_OtherFallback: "อื่นๆ",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "ลบ",
    Designer_Grid_RemoveAria: "ลบ {label} {number}",
    Designer_Grid_Statements: "ข้อความ",
    Designer_Grid_Scale: "มาตราส่วน",
    Designer_Grid_AddStatement: "เพิ่มข้อความ",
    Designer_Grid_AddScale: "เพิ่มมาตราส่วน",
    Designer_Width_Full: "เต็มความกว้าง",
    Designer_Width_Half: "ครึ่งความกว้าง",
    Designer_Width_Third: "หนึ่งในสามของความกว้าง",
    Designer_Width_Aria: "ความกว้างของคำถาม",
    Designer_Card_BlockLabelPlaceholder: "ป้ายชื่อบล็อก (ไม่แสดงให้ผู้ตอบเห็น)",
    Designer_Card_QuestionText: "ข้อความคำถาม",
    Designer_Card_MoveUp: "เลื่อนขึ้น",
    Designer_Card_MoveQuestionUp: "เลื่อนคำถามขึ้น",
    Designer_Card_MoveDown: "เลื่อนลง",
    Designer_Card_MoveQuestionDown: "เลื่อนคำถามลง",
    Designer_Card_DuplicateQuestion: "ทำสำเนาคำถาม",
    Designer_Card_MultipleAnswers: "หลายคำตอบ",
    Designer_Card_Required: "จำเป็น",
    Designer_Card_MoreOptions: "ตัวเลือกเพิ่มเติม",
    Designer_Card_MoreOptionsAria: "ตัวเลือกเพิ่มเติมสำหรับคำถามนี้",
    Designer_Canvas_FormTitle: "ชื่อฟอร์ม",
    Designer_Canvas_DescriptionPlaceholder: "เพิ่มคำอธิบาย (ไม่บังคับ)",
    Designer_Canvas_DescriptionAria: "คำอธิบายฟอร์ม",
    Designer_Canvas_EmptyTitle: "เพิ่มคำถามแรกของคุณ",
    Designer_Canvas_EmptyBody: "เลือกประเภทคำถามเพื่อเริ่มต้น คุณสามารถจัดลำดับคำถามใหม่โดยลากได้ และเพิ่มการแตกสาขาเพื่อให้ผู้ตอบเห็นเฉพาะสิ่งที่เกี่ยวข้องกับตน",
    Designer_Section_Chip: "ส่วนที่ {number} จาก {total}",
    Designer_Section_TitlePlaceholder: "ชื่อส่วน",
    Designer_Section_TitleAria: "ชื่อส่วนที่ {number}",
    Designer_Section_DescriptionPlaceholder: "คำอธิบาย (ไม่บังคับ)",
    Designer_Section_DescriptionAria: "คำอธิบายส่วนที่ {number}",
    Designer_Section_MoveUp: "เลื่อนส่วนขึ้น",
    Designer_Section_MoveDown: "เลื่อนส่วนลง",
    Designer_Section_Delete: "ลบส่วน",
    Designer_Card_DragToReorder: "ลากเพื่อจัดลำดับใหม่",
    Designer_Card_ReorderAria: "จัดลำดับ {title} ใหม่",
    Designer_Card_ReorderFallback: "คำถาม",
    Designer_Canvas_AddNew: "เพิ่มใหม่",
    Designer_Canvas_AddSection: "เพิ่มส่วน",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "ที่อยู่",
    Form_Address_Street2Placeholder: "อพาร์ตเมนต์ ห้อง ฯลฯ (ไม่บังคับ)",
    Form_Address_CityPlaceholder: "เมือง",
    Form_Address_StatePlaceholder: "จังหวัด / รัฐ",
    Form_Address_PostalCodePlaceholder: "รหัสไปรษณีย์",
    Form_Address_CountryPlaceholder: "ประเทศ",
    Form_Address_StreetAria: "ที่อยู่",
    Form_Address_Street2Aria: "บรรทัดที่อยู่ 2",
    Form_Address_CityAria: "เมือง",
    Form_Address_StateAria: "จังหวัดหรือรัฐ",
    Form_Address_PostalCodeAria: "รหัสไปรษณีย์",
    Form_Address_CountryAria: "ประเทศ",
    Form_Consent_DefaultLabel: "ฉันยอมรับ",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "ตอบแล้ว {answered} จาก {total} แถว",
    Form_Lookup_LoadError: "ไม่สามารถโหลดตัวเลือกสำหรับคำถามนี้ได้",
    Form_Lookup_Loading: "กำลังโหลดตัวเลือก…",
    Form_Lookup_SelectOptionsPlaceholder: "เลือกตัวเลือก",
    Form_Lookup_SelectOptionPlaceholder: "เลือกตัวเลือก",
    Form_Person_Placeholder: "เริ่มพิมพ์ชื่อ…",
    Form_Person_SuggestedPeopleAndGroups: "บุคคลและกลุ่มที่แนะนำ",
    Form_Person_SuggestedPeople: "บุคคลที่แนะนำ",
    Form_Person_NoPeopleOrGroups: "ไม่พบบุคคลหรือกลุ่ม",
    Form_Person_NoPeople: "ไม่พบบุคคล",
    Form_Person_Searching: "กำลังค้นหา…",
    Form_Ranking_Moved: "ย้าย {item} ไปยังตำแหน่งที่ {position} จาก {total} แล้ว",
    Form_Ranking_MoveUp: "เลื่อนขึ้น",
    Form_Ranking_MoveDown: "เลื่อนลง",
    Form_Ranking_MoveItemUpAria: "เลื่อน {item} ขึ้น",
    Form_Ranking_MoveItemDownAria: "เลื่อน {item} ลง",
    Form_Rating_ValueText: "{value} จาก {max}",
    Form_Rating_NotRated: "ยังไม่ได้ให้คะแนน",
    Form_Rating_Clear: "ล้างคะแนน",
    Form_RichText_Bold: "ตัวหนา",
    Form_RichText_Italic: "ตัวเอียง",
    Form_RichText_Underline: "ขีดเส้นใต้",
    Form_RichText_BulletedList: "รายการแบบสัญลักษณ์แสดงหัวข้อย่อย",
    Form_RichText_NumberedList: "รายการแบบลำดับเลข",
    Form_RichText_ClearFormatting: "ล้างการจัดรูปแบบ",
    Form_RichText_ToolbarAria: "การจัดรูปแบบข้อความ",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "ข้าม \"{name}\" แล้ว — ขีดจำกัดคือ {limit}",
    Form_File_TypeNotAccepted: "\"{name}\" ไม่ใช่ประเภทที่ยอมรับ",
    Form_File_TooLarge: "\"{name}\" มีขนาดใหญ่กว่า {size} MB",
    Form_File_AlreadyAttached: "\"{name}\" ถูกแนบไว้แล้ว",
    Form_File_ReadError: "ไม่สามารถอ่านไฟล์หนึ่งไฟล์ได้ ลองแนบอีกครั้ง",
    Form_File_HintMaxSize: "สูงสุด {size} MB ต่อไฟล์",
    Form_File_HintOneFile: "1 ไฟล์",
    Form_File_HintMaxFiles: "สูงสุด {count} ไฟล์",
    Form_File_Reading: "กำลังอ่านไฟล์…",
    Form_File_DropPrompt: "วางไฟล์ที่นี่ หรือคลิกเพื่อเรียกดู",
    Form_File_Remove: "ลบ {name}",
    Form_Signature_Alt: "ลายเซ็น",
    Form_Signature_AriaSigned: "{label} — ลงนามแล้ว",
    Form_Signature_AriaEmpty: "{label} — ว่างเปล่า",
    Form_Signature_Clear: "ล้าง",
    Form_Signature_Signed: "ลงนามแล้ว",
    Form_Signature_Prompt: "ลงนามด้านบนโดยใช้เมาส์ ปากกา หรือนิ้ว",
    Form_Time_Placeholder: "เลือกเวลา",
    Form_Field_DatePlaceholder: "เลือกวันที่",
    Form_Field_TimeAriaWithLabel: "{label} — เวลา",
    Form_Field_TimeAria: "เวลา",
    Form_Field_OtherDefault: "อื่นๆ",
    Form_Field_SelectOptionsPlaceholder: "เลือกตัวเลือก",
    Form_Field_PleaseSpecify: "โปรดระบุ",
    Form_Field_OtherSpecifyAria: "{label} — โปรดระบุ",
    Form_Field_SelectOptionPlaceholder: "เลือกตัวเลือก",
    Form_Field_Yes: "ใช่",
    Form_Field_No: "ไม่ใช่",
    Form_Field_SliderHint: "ลากแถบเลื่อนเพื่อตอบ",
    Form_Field_WebAddressAriaWithLabel: "{label} — ที่อยู่เว็บ",
    Form_Field_WebAddressAria: "ที่อยู่เว็บ",
    Form_Field_DisplayTextPlaceholder: "ข้อความที่แสดง (ไม่บังคับ)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — ข้อความที่แสดง",
    Form_Field_DisplayTextAria: "ข้อความที่แสดง",
    Form_Field_ChooseBetween: "เลือกระหว่าง {min} ถึง {max}",
    Form_Field_ChooseAtLeast: "เลือกอย่างน้อย {min}",
    Form_Field_ChooseUpTo: "เลือกได้สูงสุด {max}",
    Form_Field_SelectedCount: "เลือกแล้ว {count}",
    Form_Field_RequiredAria: "(จำเป็น)",
    Form_Submit_SaveError: "ไม่สามารถบันทึกการตอบกลับของคุณได้ ตรวจสอบว่าฟอร์มได้รับการเผยแพร่จากตัวออกแบบแล้ว และคุณมีสิทธิ์เพิ่มรายการลงในรายการการตอบกลับ",
    Form_Empty_Message: "ฟอร์มนี้ยังไม่มีคำถาม เจ้าของฟอร์มสามารถเพิ่มได้ในแท็บคำถาม",
    Form_Checking: "กำลังตรวจสอบฟอร์ม…",
    Form_Closed_NotYetOpen: "ยังไม่เปิด",
    Form_Closed_AlreadyAnswered: "ตอบแล้ว",
    Form_Closed_Title: "ฟอร์มปิดแล้ว",
    Form_Confirmation_PreviewNotice: "นี่เป็นเพียงตัวอย่าง — ไม่มีการบันทึกสิ่งใดลงในรายการการตอบกลับ",
    Form_Confirmation_PreviewAgain: "ดูตัวอย่างอีกครั้ง",
    Form_Confirmation_SubmitAnother: "ส่งการตอบกลับอีกครั้ง",
    Form_Wizard_StepFallback: "ขั้นตอนที่ {step}",
    Form_Wizard_StepsAria: "ขั้นตอนของฟอร์ม",
    Form_Wizard_StepOf: "ขั้นตอนที่ {step} จาก {total}",
    Form_ErrorSummary_Title: "โปรดตรวจสอบ {count} คำตอบ:",
    Form_ErrorSummary_UntitledQuestion: "คำถามที่ไม่มีชื่อ",
    Form_ErrorSummary_Question: "คำถาม",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "ย้อนกลับ",
    Form_Nav_Next: "ถัดไป",
    Form_Draft_Saving: "กำลังบันทึก…",
    Form_Draft_Saved: "บันทึกแบบร่างแล้ว",
    Form_Draft_SaveAndFinishLater: "บันทึกและกลับมาทำต่อภายหลัง",
    Form_Draft_NotSaved: "ไม่ได้บันทึกแบบร่าง",
    Form_Submit_Preview: "ส่ง (ตัวอย่าง)",
    Form_Submit_Button: "ส่ง",
    Form_Response_NoAnswer: "ไม่มีคำตอบ",
    Form_Signature_TypeLabel: "พิมพ์ชื่อเต็มของคุณ",
    Form_Signature_TypeInstead: "พิมพ์ชื่อของคุณแทน",
    Form_Signature_DrawInstead: "วาดแทน",
    Form_Edit_Button: "แก้ไขการตอบกลับก่อนหน้าของคุณ",
    Form_Edit_Available: "คุณส่งการตอบกลับไปแล้ว คุณสามารถแก้ไขแทนการส่งใหม่ได้",
    Form_Edit_Banner: "คุณกำลังแก้ไขการตอบกลับก่อนหน้าของคุณ",
    Form_Edit_Save: "อัปเดตการตอบกลับ",
    Form_Edit_UpdatedTitle: "อัปเดตการตอบกลับแล้ว",
    Form_Edit_UpdatedMessage: "บันทึกการเปลี่ยนแปลงของคุณแล้ว",
    Form_Edit_LoadError: "ไม่สามารถโหลดการตอบกลับก่อนหน้าของคุณได้ โปรดลองอีกครั้ง",
    Form_Draft_MissingFiles: "โปรดแนบใหม่: {names} ไม่สามารถกู้คืนไฟล์เหล่านี้ได้",
    Form_Attachments_Failed: "บันทึกคำตอบของคุณแล้ว แต่ไม่สามารถอัปโหลดไฟล์แนบเหล่านี้ได้: {names} โปรดลองอีกครั้งหรือติดต่อเจ้าของฟอร์ม",
    Logic_ThisQuestion: "คำถามนี้",
    Logic_Required: "ต้องระบุ {label}",
    Logic_RequiredConsent: "โปรดทำเครื่องหมายในช่องเพื่อดำเนินการต่อ",
    Logic_RequiredFile: "โปรดแนบไฟล์อย่างน้อยหนึ่งไฟล์",
    Logic_RequiredSignature: "โปรดเพิ่มลายเซ็นของคุณ",
    Logic_RequiredLikert: "โปรดตอบทุกแถว",
    Logic_InvalidEmail: "ป้อนที่อยู่อีเมลที่ถูกต้อง",
    Logic_InvalidPhone: "ป้อนหมายเลขโทรศัพท์ที่ถูกต้อง",
    Logic_InvalidUrl: "ป้อนที่อยู่เว็บที่ถูกต้องซึ่งขึ้นต้นด้วย http:// หรือ https://",
    Logic_MinValue: "ค่าต้องไม่น้อยกว่า {value}",
    Logic_MaxValue: "ค่าต้องไม่เกิน {value}",
    Logic_MaxLength: "ความยาวสูงสุดคือ {max} อักขระ",
    Logic_ChooseAtLeastOne: "เลือกอย่างน้อย {count} ตัวเลือก",
    Logic_ChooseAtLeastMany: "เลือกอย่างน้อย {count} ตัวเลือก",
    Logic_ChooseAtMostOne: "เลือกไม่เกิน {count} ตัวเลือก",
    Logic_ChooseAtMostMany: "เลือกไม่เกิน {count} ตัวเลือก",
    Logic_LikertRemaining: "โปรดตอบทุกแถว (เหลืออีก {count})",
    Logic_MaxFilesOne: "แนบไฟล์ไม่เกิน {count} ไฟล์",
    Logic_MaxFilesMany: "แนบไฟล์ไม่เกิน {count} ไฟล์",
    Logic_FileTooLarge: "\"{name}\" มีขนาดใหญ่กว่า {size} MB",
    Logic_FileTypeNotAccepted: "\"{name}\" ไม่ใช่ชนิดไฟล์ที่ยอมรับ ({types})",
    Logic_AddressRequired: "ป้อนอย่างน้อยถนนและเมือง",
    Logic_PatternDefault: "คำตอบนี้ไม่อยู่ในรูปแบบที่คาดไว้",
    Logic_Yes: "ใช่",
    Logic_No: "ไม่ใช่",
    Logic_Agreed: "ยอมรับ",
    Logic_NotAgreed: "ไม่ยอมรับ",
    Logic_Signed: "ลงนามแล้ว",
    Logic_NoAnswer: "(ไม่มีคำตอบ)",
    Logic_Unknown: "(ไม่ทราบ)",
    Logic_OtherSlice: "อื่นๆ ({count})",
    Logic_CsvResponseId: "รหัสการตอบกลับ",
    Logic_CsvSubmitted: "ส่งเมื่อ",
    Logic_CsvSubmittedBy: "ส่งโดย",
    Logic_EmailQuestion: "คำถาม",
    Logic_EmailViewItem: "ดูใน Microsoft Lists",
    Logic_EmailFooter: "ส่งโดยอัตโนมัติจาก Smart Forms",
    Logic_ClosedDefault: "ฟอร์มนี้ไม่รับการตอบกลับอีกต่อไป",
    Logic_NotYetOpen: "ฟอร์มนี้จะเปิดในวันที่ {date}",
    Logic_AlreadyResponded: "คุณตอบฟอร์มนี้แล้ว ขอบคุณ",
    Logic_UntitledQuestion: "คำถามที่ไม่มีชื่อ",
    Logic_Issue_NoQuestions: "เพิ่มคำถามอย่างน้อยหนึ่งข้อก่อนเก็บการตอบกลับ",
    Logic_Issue_NoTitle: "มีคำถามที่ไม่มีข้อความ ระบบจะตั้งชื่อให้อัตโนมัติเมื่อคุณเผยแพร่",
    Logic_Issue_DuplicateTitle: "{label} มีข้อความซ้ำกับคำถามอื่น ทำให้อ่านผลลัพธ์ได้ยากขึ้น",
    Logic_Issue_NeedTwoOptions: "{label} ต้องมีอย่างน้อยสองตัวเลือก",
    Logic_Issue_ImageNoImage: "{label} มีตัวเลือกที่ไม่มีรูปภาพ จึงจะแสดงเป็นไทล์ข้อความ",
    Logic_Issue_LikertNeedRow: "{label} ต้องมีอย่างน้อยหนึ่งแถว",
    Logic_Issue_LikertNeedColumns: "{label} ต้องมีคอลัมน์มาตราส่วนอย่างน้อยสองคอลัมน์",
    Logic_Issue_NoLookupList: "{label} ยังไม่ได้เลือกรายการต้นทาง",
    Logic_Issue_NoFormula: "{label} ไม่มีสูตร",
    Logic_Issue_BadFormula: "{label} มีสูตรที่ไม่สามารถคำนวณได้ ตรวจสอบวงเล็บและตัวดำเนินการ",
    Logic_Issue_MissingRefs: "{label} อ้างอิงถึงคำถามที่ไม่มีอยู่: {names}",
    Logic_Issue_BadPattern: "{label} มีรูปแบบการตรวจสอบที่ไม่ถูกต้อง",
    Logic_Issue_BrokenRule: "{label} มีกฎการแตกแขนงที่ชี้ไปยังคำถามที่ถูกลบ",
    Logic_Issue_SelfRule: "{label} มีกฎการแตกแขนงที่อ้างอิงถึงตัวมันเอง",
    Logic_Issue_RuleMismatch: "{label} มีกฎการแตกแขนงที่ไม่เหมาะกับคำถามที่อ้างอิงอีกต่อไป",
    Logic_Issue_RequiredReadOnly: "{label} ต้องระบุและเป็นแบบอ่านอย่างเดียวพร้อมกัน จึงตอบได้ผ่านลิงก์ที่กรอกไว้ล่วงหน้าเท่านั้น",
    Logic_Issue_EmptySection: "มีส่วนที่ไม่มีคำถามและจะถูกข้าม",
    Logic_Issue_CloseBeforeOpen: "วันที่ปิดตรงกับหรืออยู่ก่อนวันที่เปิด ฟอร์มจึงจะไม่รับการตอบกลับเลย",
    Logic_Issue_ApprovalNotifyWithoutApproval: "เปิดใช้อีเมลการอนุมัติแล้ว แต่ปิดขั้นตอนการอนุมัติอยู่",
    Logic_Op_equals: "เท่ากับ",
    Logic_Op_notEquals: "ไม่เท่ากับ",
    Logic_Op_contains: "มี",
    Logic_Op_notContains: "ไม่มี",
    Logic_Op_notEmpty: "มีคำตอบ",
    Logic_Op_empty: "ไม่มีคำตอบ",
    Logic_Op_greaterThan: "มากกว่า",
    Logic_Op_greaterOrEqual: "อย่างน้อย",
    Logic_Op_lessThan: "น้อยกว่า",
    Logic_Op_lessOrEqual: "ไม่เกิน",
    Logic_Op_between: "อยู่ระหว่าง",
    Logic_Op_before: "ก่อน",
    Logic_Op_after: "หลัง",
    Logic_Type_Text: "คำตอบสั้น",
    Logic_TypeDesc_Text: "ข้อความหนึ่งบรรทัด",
    Logic_Category_Text: "ข้อความ",
    Logic_Type_MultilineText: "คำตอบยาว",
    Logic_TypeDesc_MultilineText: "ข้อความธรรมดาหลายบรรทัด",
    Logic_Type_RichText: "ข้อความที่มีการจัดรูปแบบ",
    Logic_TypeDesc_RichText: "ตัวหนา รายการ และลิงก์",
    Logic_Type_Choice: "ตัวเลือก",
    Logic_TypeDesc_Choice: "เลือกจากรายการตัวเลือก",
    Logic_Category_Choice: "ตัวเลือก",
    Logic_Type_ImageChoice: "ตัวเลือกรูปภาพ",
    Logic_TypeDesc_ImageChoice: "เลือกจากไทล์รูปภาพ",
    Logic_Type_Lookup: "การค้นหาจากรายการ",
    Logic_TypeDesc_Lookup: "ตัวเลือกที่อ่านสดจากรายการ SharePoint อื่น",
    Logic_Type_YesNo: "ใช่ / ไม่ใช่",
    Logic_TypeDesc_YesNo: "สวิตช์เปิด/ปิดแบบง่าย",
    Logic_Type_Consent: "ความยินยอม",
    Logic_TypeDesc_Consent: "ช่องทำเครื่องหมายที่ผู้ตอบต้องเลือกเพื่อดำเนินการต่อ",
    Logic_Type_Ranking: "การจัดอันดับ",
    Logic_TypeDesc_Ranking: "ลากตัวเลือกเรียงตามความชอบ",
    Logic_Type_Rating: "การให้คะแนน",
    Logic_TypeDesc_Rating: "ดาว หัวใจ หรือยกนิ้ว",
    Logic_Category_Scales: "มาตราส่วน",
    Logic_Type_Scale: "มาตราส่วนความคิดเห็น",
    Logic_TypeDesc_Scale: "มาตราส่วนที่มีตัวเลขและป้ายกำกับที่ปลายทั้งสอง",
    Logic_Type_Slider: "แถบเลื่อน",
    Logic_TypeDesc_Slider: "ค่าบนมาตราส่วนแบบเลื่อน",
    Logic_Type_Likert: "ตาราง Likert",
    Logic_TypeDesc_Likert: "ให้คะแนนหลายข้อความบนมาตราส่วนเดียวกัน",
    Logic_Type_Number: "ตัวเลข",
    Logic_TypeDesc_Number: "ธรรมดา สกุลเงิน หรือเปอร์เซ็นต์",
    Logic_Category_Advanced: "ขั้นสูง",
    Logic_Type_Calculated: "คำนวณ",
    Logic_TypeDesc_Calculated: "ผลรวมแบบอ่านอย่างเดียวที่คำนวณจากคำตอบอื่น",
    Logic_Type_Date: "วันที่",
    Logic_TypeDesc_Date: "วันที่ในปฏิทิน พร้อมเวลาได้ตามต้องการ",
    Logic_Category_Date: "วันที่",
    Logic_Type_Time: "เวลา",
    Logic_TypeDesc_Time: "เวลาของวันเพียงอย่างเดียว",
    Logic_Type_Person: "บุคคล",
    Logic_TypeDesc_Person: "เลือกบุคคลจากองค์กร",
    Logic_Category_People: "บุคคล",
    Logic_Type_Email: "อีเมล",
    Logic_TypeDesc_Email: "ที่อยู่อีเมล พร้อมการตรวจสอบ",
    Logic_Type_Phone: "โทรศัพท์",
    Logic_TypeDesc_Phone: "หมายเลขโทรศัพท์ พร้อมการตรวจสอบ",
    Logic_Type_Address: "ที่อยู่",
    Logic_TypeDesc_Address: "ถนน เมือง รหัสไปรษณีย์ และประเทศ",
    Logic_Type_Hyperlink: "ลิงก์",
    Logic_TypeDesc_Hyperlink: "ที่อยู่เว็บ",
    Logic_Type_FileUpload: "อัปโหลดไฟล์",
    Logic_TypeDesc_FileUpload: "แนบไฟล์หนึ่งไฟล์ขึ้นไปกับการตอบกลับ",
    Logic_Type_Signature: "ลายเซ็น",
    Logic_TypeDesc_Signature: "ลงนามด้วยเมาส์ ปากกา หรือนิ้ว",
    Logic_Type_Content: "บล็อกข้อความ",
    Logic_TypeDesc_Content: "คำแนะนำหรือรูปภาพ ไม่เก็บคำตอบ",
    Logic_Category_Layout: "เค้าโครง",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "คุณมีแนวโน้มที่จะแนะนำมากน้อยเพียงใด…",
    Logic_Preset_satisfaction: "ความพึงพอใจ (1–5)",
    Logic_PresetDesc_satisfaction: "ไม่พอใจมากถึงพอใจมาก",
    Logic_Preset_currency: "สกุลเงิน",
    Logic_PresetDesc_currency: "จำนวนเงิน",
    Logic_Preset_percent: "เปอร์เซ็นต์",
    Logic_PresetDesc_percent: "ค่าเปอร์เซ็นต์",
    Logic_Template_blank_Name: "ฟอร์มเปล่า",
    Logic_Template_blank_Description: "เริ่มจากศูนย์",
    Logic_Template_feedback_Name: "ความคิดเห็นของลูกค้า",
    Logic_Template_feedback_Description: "NPS การให้คะแนน และความคิดเห็นแบบเปิด",
    Logic_Template_event_Name: "การลงทะเบียนเข้าร่วมงาน",
    Logic_Template_event_Description: "รายละเอียดผู้เข้าร่วม ช่วงเซสชัน และความต้องการด้านอาหาร",
    Logic_Template_itrequest_Name: "คำขอบริการไอที",
    Logic_Template_itrequest_Description: "คำขอที่จัดหมวดหมู่พร้อมลำดับความสำคัญและไฟล์แนบ",
    Logic_Template_expense_Name: "ใบเบิกค่าใช้จ่าย",
    Logic_Template_expense_Description: "รายการ ใบเสร็จ และยอดรวมที่คำนวณให้",
    Logic_Template_pulse_Name: "แบบสำรวจความรู้สึกพนักงาน",
    Logic_Template_pulse_Description: "ตาราง Likert มาตราส่วนความผูกพัน และหมายเหตุการไม่ระบุตัวตน",
    Logic_Template_safety_Name: "การตรวจสอบความปลอดภัย",
    Logic_Template_safety_Description: "รายการตรวจสอบ รูปถ่าย และลายเซ็น",
    Logic_Template_booking_Name: "การจองห้องหรือทรัพยากร",
    Logic_Template_booking_Description: "ตัวเลือกทรัพยากรจากการค้นหาพร้อมช่วงเวลา",
    Charts_ColumnChartAria: "แผนภูมิคอลัมน์ที่มี {count} หมวดหมู่",
    Charts_DonutChartAria: "แผนภูมิโดนัทของ {count} หมวดหมู่",
    Charts_NoAnswers: "ยังไม่มีคำตอบ",
    Charts_NoResponses: "ยังไม่มีการตอบกลับ",
    Charts_Responses: "การตอบกลับ",
    Charts_ResponsesOverTime: "การตอบกลับตามช่วงเวลา",
    Responses_Chart_Answer: "คำตอบ",
    Responses_Chart_Average: "ค่าเฉลี่ย",
    Responses_Chart_AverageOf: "ค่าเฉลี่ยของ {count}",
    Responses_Chart_AveragePosition: "ตำแหน่งเฉลี่ย",
    Responses_Chart_AverageRange: "ค่าเฉลี่ย (1–{max})",
    Responses_Chart_AvgValue: "เฉลี่ย {value}",
    Responses_Chart_Detractors: "ผู้วิจารณ์ (0–6)",
    Responses_Chart_Max: "สูงสุด",
    Responses_Chart_Maximum: "สูงสุด",
    Responses_Chart_Median: "ค่ามัธยฐาน",
    Responses_Chart_MentionOne: "{count} การกล่าวถึง",
    Responses_Chart_MentionOther: "{count} การกล่าวถึง",
    Responses_Chart_Min: "ต่ำสุด",
    Responses_Chart_Minimum: "ต่ำสุด",
    Responses_Chart_NoAnswers: "ยังไม่มีคำตอบ",
    Responses_Chart_NoNumeric: "ยังไม่มีคำตอบที่เป็นตัวเลข",
    Responses_Chart_NoRankings: "ยังไม่มีการจัดอันดับ",
    Responses_Chart_NoScores: "ยังไม่มีคะแนน",
    Responses_Chart_NotEnoughText: "ยังมีข้อความไม่เพียงพอที่จะสรุป",
    Responses_Chart_NpsScore: "คะแนน NPS",
    Responses_Chart_Option: "ตัวเลือก",
    Responses_Chart_Passives: "ผู้เป็นกลาง (7–8)",
    Responses_Chart_Promoters: "ผู้สนับสนุน (9–10)",
    Responses_Chart_ResponseOne: "การตอบกลับ",
    Responses_Chart_ResponseOther: "การตอบกลับ",
    Responses_Chart_Responses: "การตอบกลับ",
    Responses_Chart_ShowingAnswers: "แสดง {shown} จาก {total} คำตอบ",
    Responses_Chart_Statement: "ข้อความ",
    Responses_Chart_Statistic: "สถิติ",
    Responses_Chart_StdDev: "ส่วนเบี่ยงเบนมาตรฐาน",
    Responses_Chart_StdDeviation: "ส่วนเบี่ยงเบนมาตรฐาน",
    Responses_Chart_Total: "รวม",
    Responses_Chart_Value: "ค่า",
    Responses_Dashboard_AllHidden: "คำถามทั้งหมดถูกซ่อนจากแดชบอร์ด ใช้ “แสดงคำถามที่ซ่อน” เพื่อนำกลับมา",
    Responses_Dashboard_AnsweredOf: "ตอบแล้ว {answered} จาก {total}",
    Responses_Dashboard_AnsweredOfPinned: "ตอบแล้ว {answered} จาก {total} · ปักหมุดแล้ว",
    Responses_Dashboard_AveragedAcrossResponses: "ค่าเฉลี่ยจากทุกการตอบกลับ",
    Responses_Dashboard_ByDay: "รายวัน",
    Responses_Dashboard_ByMonth: "รายเดือน",
    Responses_Dashboard_ByWeek: "รายสัปดาห์",
    Responses_Dashboard_ChartAuto: "อัตโนมัติ",
    Responses_Dashboard_ChartBars: "แถบ",
    Responses_Dashboard_ChartColumns: "คอลัมน์",
    Responses_Dashboard_ChartDonut: "โดนัท",
    Responses_Dashboard_ChartGauge: "มาตรวัด",
    Responses_Dashboard_ChartHistogram: "ฮิสโตแกรม",
    Responses_Dashboard_ChartOptions: "ตัวเลือกแผนภูมิ",
    Responses_Dashboard_ChartOptionsFor: "ตัวเลือกแผนภูมิสำหรับ {title}",
    Responses_Dashboard_ChartStatistics: "สถิติ",
    Responses_Dashboard_ChartTable: "ตาราง",
    Responses_Dashboard_ChartWordFrequency: "ความถี่ของคำ",
    Responses_Dashboard_EmptyBody: "เมื่อมีคนเริ่มตอบ แดชบอร์ดนี้จะเติมข้อมูลอัตโนมัติ ทั้งตัวเลขสำคัญ ไทม์ไลน์การตอบกลับ และแผนภูมิสำหรับคำถามที่น่าติดตาม",
    Responses_Dashboard_EmptyTitle: "ยังไม่มีการตอบกลับ",
    Responses_Dashboard_Hide: "ซ่อนจากแดชบอร์ด",
    Responses_Dashboard_Highlights: "ไฮไลต์",
    Responses_Dashboard_Last7Days: "7 วันที่ผ่านมา",
    Responses_Dashboard_LatestDate: "ล่าสุด {date}",
    Responses_Dashboard_MedianTimeToComplete: "เวลามัธยฐานที่ใช้ทำให้เสร็จ",
    Responses_Dashboard_NoPriorWeek: "ไม่มีสัปดาห์ก่อนหน้าให้เปรียบเทียบ",
    Responses_Dashboard_OneEach: "อย่างละหนึ่ง",
    Responses_Dashboard_Pin: "ปักหมุดไว้ที่แดชบอร์ด",
    Responses_Dashboard_QuestionFallback: "คำถาม",
    Responses_Dashboard_QuestionsAnswered: "คำถามที่ตอบแล้ว",
    Responses_Dashboard_RecordedOnSubmit: "บันทึกเมื่อส่ง",
    Responses_Dashboard_RepeatResponses: "การตอบกลับซ้ำ {count} รายการ",
    Responses_Dashboard_ResponsesOverTime: "การตอบกลับตามช่วงเวลา",
    Responses_Dashboard_ShowHidden: "แสดงคำถามที่ซ่อน",
    Responses_Dashboard_SinceMidnight: "ตั้งแต่เที่ยงคืน",
    Responses_Dashboard_Today: "วันนี้",
    Responses_Dashboard_TotalResponses: "การตอบกลับทั้งหมด",
    Responses_Dashboard_UniqueRespondents: "ผู้ตอบที่ไม่ซ้ำกัน",
    Responses_Dashboard_Unpin: "เลิกปักหมุดจากแดชบอร์ด",
    Responses_Dashboard_UntitledQuestion: "คำถามที่ไม่มีชื่อ",
    Responses_Dashboard_VsPrevious7Days: "เทียบกับ 7 วันก่อนหน้า",
    Responses_Detail_Answers: "คำตอบ",
    Responses_Detail_AsTheForm: "ตามแบบฟอร์ม",
    Responses_Detail_Cancel: "ยกเลิก",
    Responses_Detail_Delete: "ลบ",
    Responses_Detail_DeleteBody: "รายการในรายการจะถูกย้ายไปที่ถังรีไซเคิลของไซต์ จึงสามารถกู้คืนได้จากที่นั่น",
    Responses_Detail_DeleteTitle: "ลบการตอบกลับนี้หรือไม่",
    Responses_Detail_Deleting: "กำลังลบ…",
    Responses_Detail_Draft: "แบบร่าง",
    Responses_Detail_Header: "การตอบกลับที่ {index} จาก {total}",
    Responses_Detail_LoadingAttachments: "กำลังโหลดไฟล์แนบ…",
    Responses_Detail_Next: "การตอบกลับถัดไป",
    Responses_Detail_NoAnswer: "ไม่มีคำตอบ",
    Responses_Detail_Previous: "การตอบกลับก่อนหน้า",
    Responses_Detail_Print: "พิมพ์",
    Responses_Detail_Signature: "ลายเซ็น",
    Responses_Detail_Signed: "ลงนามแล้ว",
    Responses_Detail_Took: "ใช้เวลา {duration}",
    Responses_Summary_AnsweredOfType: "ตอบแล้ว {answered} จาก {total} · {type}",
    Responses_Summary_ByField: "ตาม {title}",
    Responses_Summary_CompareBy: "เปรียบเทียบตาม…",
    Responses_Summary_EmptyBody: "ทุกคำถามจะมีบทสรุปของตนเองที่นี่",
    Responses_Summary_NoComparison: "ไม่เปรียบเทียบ",
    Responses_Summary_NothingToCompare: "ไม่มีการตอบกลับที่ตอบ “{title}” จึงไม่มีอะไรให้เปรียบเทียบ",
    Responses_Summary_OtherNote: "แผนภูมิที่มีมากกว่า {max} หมวดหมู่จะรวมหมวดหมู่ที่เล็กที่สุดไว้ใน “อื่นๆ” — สลับการ์ดเป็นตารางเพื่อดูทุกค่า",
    Responses_Summary_ResponseCountOne: "{count} การตอบกลับ",
    Responses_Summary_ResponseCountOther: "{count} การตอบกลับ",
    Responses_Summary_SeeAllAnswers: "ดูคำตอบทั้งหมดในตาราง",
    Responses_Summary_SegmentNote: "แสดง {groups} กลุ่มที่ใหญ่ที่สุด การตอบกลับที่เลือกหลายคำตอบจะปรากฏในทุกกลุ่มที่ตรงกัน ดังนั้นยอดรวมของกลุ่มอาจเกิน {total}",
    Responses_Summary_SplitBy: "แยกตาม {title}",
    Responses_Summary_Untitled: "ไม่มีชื่อ",
    Responses_Table_Apply: "นำไปใช้",
    Responses_Table_Cancel: "ยกเลิก",
    Responses_Table_ClearSelection: "ล้างการเลือก",
    Responses_Table_ColumnOrder: "ลำดับคอลัมน์",
    Responses_Table_ColumnsCount: "คอลัมน์ ({shown}/{total})",
    Responses_Table_Delete: "ลบ",
    Responses_Table_DeleteBody: "รายการในรายการจะถูกย้ายไปที่ถังรีไซเคิลของไซต์ จึงสามารถกู้คืนได้จากที่นั่น",
    Responses_Table_DeleteSelected: "ลบที่เลือก",
    Responses_Table_DeleteTitleOne: "ลบ {count} การตอบกลับหรือไม่",
    Responses_Table_DeleteTitleOther: "ลบ {count} การตอบกลับหรือไม่",
    Responses_Table_Deleting: "กำลังลบ…",
    Responses_Table_MoveDown: "เลื่อนลง",
    Responses_Table_MoveDownFor: "เลื่อน {title} ลง",
    Responses_Table_MoveUp: "เลื่อนขึ้น",
    Responses_Table_MoveUpFor: "เลื่อน {title} ขึ้น",
    Responses_Table_NoColumns: "ยังไม่มีคอลัมน์คำถามที่มองเห็นได้",
    Responses_Table_NoMatch: "ไม่มีการตอบกลับที่ตรงกับตัวกรองปัจจุบัน",
    Responses_Table_NothingToShow: "ไม่มีอะไรให้แสดง",
    Responses_Table_OpenResponse: "เปิดการตอบกลับนี้",
    Responses_Table_OrderNote: "ส่งเมื่อ และ ส่งโดย จะอยู่ก่อนเสมอ ลำดับการลากใช้กับคอลัมน์คำถาม",
    Responses_Table_Reorder: "จัดลำดับใหม่",
    Responses_Table_ResetColumns: "รีเซ็ตคอลัมน์",
    Responses_Table_SelectResponse: "เลือกการตอบกลับนี้",
    Responses_Table_SelectedOne: "เลือกการตอบกลับแล้ว {count} รายการ",
    Responses_Table_SelectedOther: "เลือกการตอบกลับแล้ว {count} รายการ",
    Responses_Table_ShowAll: "แสดงทั้งหมด",
    Responses_Table_ShowTheseQuestions: "แสดงคำถามเหล่านี้",
    Responses_Table_Submitted: "ส่งเมื่อ",
    Responses_Table_SubmittedBy: "ส่งโดย",
    Responses_Table_ToggleSelection: "สลับการเลือก",
    Responses_Table_Unknown: "ไม่ทราบ",
    Responses_Table_Untitled: "ไม่มีชื่อ",
    Responses_View_AllTime: "ตลอดเวลา",
    Responses_View_AnyAnswer: "คำตอบใดก็ได้",
    Responses_View_Clear: "ล้าง",
    Responses_View_CopyShareLink: "คัดลอกลิงก์แชร์",
    Responses_View_CountFiltered: "{shown} จาก {total} การตอบกลับ",
    Responses_View_CountOne: "{count} การตอบกลับ",
    Responses_View_CountOther: "{count} การตอบกลับ",
    Responses_View_Dashboard: "แดชบอร์ด",
    Responses_View_DateRange: "ช่วงวันที่",
    Responses_View_EmptyBody: "แชร์ฟอร์มเพื่อเริ่มรวบรวมคำตอบ คำตอบจะถูกบันทึกลงใน “{list}” และแสดงที่นี่ทันที",
    Responses_View_EmptyTitle: "ยังไม่มีการตอบกลับ",
    Responses_View_ExportCsv: "ส่งออก CSV",
    Responses_View_FilterByAnswer: "กรองตามคำตอบ",
    Responses_View_FilterByQuestion: "กรองตามคำถาม",
    Responses_View_FilterValue: "ค่าตัวกรอง",
    Responses_View_Last30Days: "30 วันที่ผ่านมา",
    Responses_View_Last7Days: "7 วันที่ผ่านมา",
    Responses_View_Last90Days: "90 วันที่ผ่านมา",
    Responses_View_LoadError: "ไม่สามารถโหลดการตอบกลับได้ เผยแพร่ฟอร์มหนึ่งครั้งเพื่อให้มีคอลัมน์รายการ แล้วลองอีกครั้ง",
    Responses_View_Loading: "กำลังโหลดการตอบกลับ…",
    Responses_View_MoreActions: "การดำเนินการเพิ่มเติมสำหรับการตอบกลับ",
    Responses_View_PreviewForm: "ดูตัวอย่างฟอร์ม",
    Responses_View_Refresh: "รีเฟรช",
    Responses_View_ResponsesTab: "การตอบกลับ ({count})",
    Responses_View_SearchPlaceholder: "ค้นหาคำตอบทั้งหมด",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "เลือกค่า",
    Responses_View_Summary: "สรุป",
    Responses_View_Today: "วันนี้",
    Responses_View_Truncated: "รายการนี้มีการตอบกลับมากกว่าที่ Smart Forms โหลดในครั้งเดียว แสดง {count} รายการล่าสุด — เปิดรายการใน Microsoft Lists เพื่อดูชุดข้อมูลทั้งหมด",
    Responses_View_TryAgain: "ลองอีกครั้ง",
    Responses_View_Untitled: "ไม่มีชื่อ",
    Responses_Approval_Column: "การอนุมัติ",
    Responses_Approval_ReviewerColumn: "ตรวจสอบโดย",
    Responses_Approval_CommentColumn: "ความคิดเห็นของผู้ตรวจสอบ",
    Responses_Approval_Pending: "รอดำเนินการ",
    Responses_Approval_Approved: "อนุมัติแล้ว",
    Responses_Approval_Rejected: "ปฏิเสธแล้ว",
    Responses_Approval_AnyStatus: "สถานะการอนุมัติใดก็ได้",
    Responses_Approval_FilterLabel: "กรองตามสถานะการอนุมัติ",
    Responses_Approval_ApproveSelected: "อนุมัติที่เลือก",
    Responses_Approval_RejectSelected: "ปฏิเสธที่เลือก",
    Responses_Approval_BulkFailed: "ไม่สามารถอัปเดตการตอบกลับ {count} รายการ โปรดลองอีกครั้ง",
    Responses_Approval_Approve: "อนุมัติ",
    Responses_Approval_Reject: "ปฏิเสธ",
    Responses_Approval_Reset: "รีเซ็ตเป็นรอดำเนินการ",
    Responses_Approval_CommentLabel: "ความคิดเห็น (ไม่บังคับ)",
    Responses_Approval_ReviewedBy: "ตรวจสอบโดย {name}",
    Responses_Approval_Error: "ไม่สามารถบันทึกการตัดสินใจได้ โปรดลองอีกครั้ง",
    Responses_Dashboard_ApprovalStatus: "รอการตรวจสอบ",
    Responses_Dashboard_ApprovalBreakdown: "รอดำเนินการ {pending} อนุมัติแล้ว {approved} ปฏิเสธแล้ว {rejected}",
    Responses_Dashboard_TimelineCoarsened: "ช่วงวันที่ยาว ไทม์ไลน์จึงถูกจัดกลุ่มแบบหยาบขึ้น ({grain})",
    Responses_Dashboard_TimelineTruncated: "ช่วงวันที่ยาวมาก จึงแสดงเฉพาะ {count} ช่วงล่าสุด",
    Service_Item_DefaultTitle: "การตอบกลับ — {date}",
    Service_Email_ApprovalSubject: "การตอบกลับของคุณ{status} — {title}",
    Service_Email_ApprovalHeading: "การตอบกลับของคุณ{status}",
    Service_Email_ApprovalIntro: "ผู้ตรวจสอบทำเครื่องหมายการตอบกลับของคุณสำหรับ \"{title}\" ว่า{status}",
    Service_Email_ApprovalCommentLabel: "ความคิดเห็นของผู้ตรวจสอบ",
    Service_Approval_Approved: "ได้รับการอนุมัติ",
    Service_Approval_Rejected: "ถูกปฏิเสธ",
    Service_Approval_Pending: "อยู่ระหว่างรอดำเนินการ",
    Service_Lookup_InvalidFilter: "ตัวกรองการค้นหาไม่ถูกต้อง",
    Service_Edit_NotAllowed: "ฟอร์มนี้ไม่อนุญาตให้แก้ไขการตอบกลับที่ส่งแล้ว",
    Service_Edit_NotYours: "คุณแก้ไขได้เฉพาะการตอบกลับของคุณเอง",
    Service_Signature_AttachmentLabel: "ลายเซ็น",
    PropertyPane_ListsLoadFailed: "ไม่สามารถโหลดรายการในไซต์นี้ได้",
    PropertyPane_EnterListName: "ป้อนชื่อสำหรับรายการใหม่ก่อน",
    PropertyPane_CreatingList: "กำลังสร้าง \"{name}\"…",
    PropertyPane_ListCreated: "สร้างและเลือกรายการ \"{title}\" แล้ว",
    PropertyPane_ListAlreadyExists: "มีรายการชื่อ \"{name}\" อยู่แล้ว — เลือกจากรายการแบบเลื่อนลงด้านบน",
    PropertyPane_CreateListFailed: "ไม่สามารถสร้างรายการได้ ตรวจสอบว่าคุณมีสิทธิ์สร้างรายการในไซต์นี้",
    PropertyPane_Description: "เลือกรายการ SharePoint ที่เก็บการตอบกลับของฟอร์ม หรือสร้างรายการใหม่ ส่วนอื่นทั้งหมด ไม่ว่าจะเป็นคำถาม รูปลักษณ์ หรือการแจ้งเตือน แก้ไขได้โดยตรงบนหน้า",
    PropertyPane_ResponseList_GroupName: "รายการการตอบกลับ",
    PropertyPane_ListDropdown_Label: "บันทึกการตอบกลับลงในรายการนี้",
    PropertyPane_ResponsesGoTo: "การตอบกลับจะไปที่ \"{name}\"",
    PropertyPane_PickList: "เลือกรายการ หรือสร้างรายการด้านล่าง",
    PropertyPane_LoadingLists: "กำลังโหลดรายการ…",
    PropertyPane_NewListName_Label: "หรือสร้างรายการใหม่",
    PropertyPane_NewListName_Placeholder: "ชื่อรายการใหม่",
    PropertyPane_CreateList_Button: "สร้างรายการ",
    PropertyPane_Tips_GroupName: "เคล็ดลับ",
    PropertyPane_Tip_AutoSave: "คำถามและการตั้งค่าจะบันทึกอัตโนมัติขณะที่คุณแก้ไข ไม่ต้องบันทึกหรือเผยแพร่หน้า",
    PropertyPane_Tip_Permissions: "ผู้ตอบต้องมีสิทธิ์เพิ่มรายการลงในรายการการตอบกลับ ตรวจสอบสิทธิ์ของรายการหากมีผู้รายงานข้อผิดพลาดตอนส่ง",
    PropertyPane_Tip_Share: "ใช้ \"รวบรวมการตอบกลับ\" บนหน้าเพื่อสร้างคอลัมน์รายการและรับลิงก์สำหรับกรอกที่แชร์ได้",
    App_ErrorBoundary_Title: "Smart Forms — ข้อผิดพลาดในการแสดงผล",
    App_ErrorBoundary_Message: "ข้อความ:",
    App_ErrorBoundary_Stack: "สแตก:",
    App_ErrorBoundary_NoStack: "(ไม่มีสแตก)",
    App_ErrorBoundary_ConsoleNote: "รายละเอียดทั้งหมดถูกเขียนลงในคอนโซลของเบราว์เซอร์ด้วย",
    App_DefaultQuestionTitle: "คำถามที่ {number}",
    App_Error_ListMissing: "รายการที่กำหนดค่าไว้สำหรับฟอร์มนี้ไม่มีอยู่แล้ว เลือกรายการอื่นในการตั้งค่าเว็บพาร์ต",
    App_Error_LoadConfig: "เกิดข้อผิดพลาดขณะโหลดการกำหนดค่าฟอร์ม",
    App_Error_Unable: "ไม่สามารถโหลดฟอร์มได้",
    App_Publish_ConflictNotice: "\"{title}\" มีคอลัมน์รายการที่เป็นประเภทอื่นอยู่แล้ว ({type}) เปลี่ยนชื่อคำถามเพื่อให้สร้างคอลัมน์ใหม่ได้ หรือเปลี่ยนประเภทกลับ",
    App_Publish_ConflictUnnamedQuestion: "คำถาม",
    App_Publish_ColumnsAddedOne: "เพิ่ม {count} คอลัมน์ใน \"{list}\" แล้ว",
    App_Publish_ColumnsAddedOther: "เพิ่ม {count} คอลัมน์ใน \"{list}\" แล้ว",
    App_Publish_TheList: "รายการ",
    App_Publish_UpToDate: "รายการการตอบกลับเป็นปัจจุบันอยู่แล้ว",
    App_Publish_Error: "ไม่สามารถสร้างคอลัมน์รายการได้ โดยปกติหมายความว่าคุณไม่มีสิทธิ์จัดการรายการในรายการการตอบกลับ แต่ก็อาจเกิดขึ้นในไซต์ที่ปิดใช้งานสคริปต์แบบกำหนดเองได้เช่นกัน ตรวจสอบคอนโซลของเบราว์เซอร์เพื่อดูข้อผิดพลาดที่แท้จริง หรือลองอีกครั้ง",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "สร้างฟอร์มที่สวยงามบนรายการ SharePoint — คำถามได้ {count} ประเภท ตรรกะการแตกสาขา การอัปโหลดไฟล์ ลิงก์สำหรับกรอกที่แชร์ได้ และแดชบอร์ดผลลัพธ์",
    App_Placeholder_ChooseList: "เลือกหรือสร้างรายการ",
    App_Placeholder_Hint: "แก้ไขหน้าและกำหนดค่าเว็บพาร์ตนี้เพื่อเริ่มต้น",
    App_Loading: "กำลังโหลดฟอร์ม…",
    App_OpenSettings: "เปิดการตั้งค่า",
    App_Tab_Questions: "คำถาม",
    App_Tab_QuestionsWithCount: "คำถาม ({count})",
    App_Tab_Responses: "การตอบกลับ",
    App_Tab_Responses_Title: "การตอบกลับจะถูกบันทึกลงใน \"{list}\"",
    App_Templates_Start: "เริ่มจากเทมเพลต",
    App_Settings_Title: "การตั้งค่าฟอร์ม — รูปลักษณ์ การแจ้งเตือน การเข้าถึง",
    App_Settings_AriaLabel: "การตั้งค่าฟอร์ม",
    App_Preview: "ตัวอย่าง",
    App_Preview_Close: "ปิดตัวอย่าง",
    App_Preview_Hint: "ตัวอย่าง — ไม่มีการบันทึกสิ่งที่คุณส่งที่นี่ การตรวจสอบและการแตกสาขาทำงานเหมือนกับที่ผู้ตอบจะพบทุกประการ",
    App_Publish_GettingReady: "กำลังเตรียม…",
    App_Publish_CollectResponses: "รวบรวมการตอบกลับ",
    App_Publish_Share: "แชร์",
    App_Retry: "ลองใหม่",
    App_SaveError_Banner: "ไม่สามารถบันทึกการเปลี่ยนแปลงล่าสุดของคุณได้ ตรวจสอบการเชื่อมต่อแล้วลองอีกครั้ง",
    App_Preflight_BlockingTitle: "แก้ไขสิ่งเหล่านี้ก่อนรวบรวมการตอบกลับ",
    App_Preflight_WarningTitle: "ควรตรวจสอบก่อน",
    App_Preflight_BlockingText: "สิ่งเหล่านี้จะทำให้ฟอร์มที่เผยแพร่ทำงานไม่ถูกต้อง",
    App_Preflight_WarningText: "ไม่มีสิ่งใดเสีย แต่โดยทั่วไปควรแก้ไขสิ่งเหล่านี้ก่อนแชร์ลิงก์",
    App_Preflight_GoTo: "ไปที่",
    App_Preflight_CollectAnyway: "รวบรวมการตอบกลับต่อไป",
    App_Preflight_Back: "กลับไปที่ฟอร์ม",
    App_Cancel: "ยกเลิก",
    App_Done: "เสร็จสิ้น",
    App_Share_Title: "ฟอร์มของคุณพร้อมแชร์แล้ว",
    App_Share_SubText: "ส่งลิงก์นี้ให้ทุกคนที่ควรกรอกฟอร์ม",
    App_Share_LinkAriaLabel: "ลิงก์แชร์",
    App_Share_Copy: "คัดลอก",
    App_Share_Copied: "คัดลอกแล้ว",
    App_Share_AddItemsEmphasis: "เพิ่มรายการ",
    App_Share_PermissionNote: "ผู้ตอบต้องมีสิทธิ์ใน{addItems}ลงใน “{title}” และมีสิทธิ์เข้าถึงหน้านี้ หากมีผู้พบข้อผิดพลาดตอนส่ง แทบทุกครั้งเป็นเพราะสาเหตุนี้",
    App_Share_PrefillNote: "คุณสามารถตอบคำถามล่วงหน้าในลิงก์ได้โดยเพิ่มชื่อคอลัมน์ เช่น {example}",
    App_Templates_ReplaceWarning: "การเลือกเทมเพลตจะแทนที่คำถามที่คุณมีอยู่ตอนนี้",
    App_Templates_PickStart: "เลือกจุดเริ่มต้น — คุณเปลี่ยนแปลงได้ทุกอย่างในภายหลัง",
    App_Templates_Empty: "ว่างเปล่า",
    App_Templates_QuestionCount: "{count} คำถาม",
    App_SaveChip_SavingTitle: "กำลังบันทึกการแก้ไขล่าสุดของคุณ",
    App_SaveChip_Saving: "กำลังบันทึก…",
    App_SaveChip_FailedTitle: "ไม่สามารถบันทึกการแก้ไขล่าสุดของคุณได้ ตรวจสอบการเชื่อมต่อแล้วลองอีกครั้ง",
    App_SaveChip_Failed: "บันทึกไม่สำเร็จ",
    App_SaveChip_SavedTitle: "บันทึกการเปลี่ยนแปลงทั้งหมดแล้ว",
    App_SaveChip_Saved: "บันทึกแล้ว",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "การตอบกลับใหม่ — {title}",
    Service_Email_NewResponseHeading: "การตอบกลับใหม่: {title}",
    Service_Email_NewResponseIntro: "มีคนเพิ่งส่งการตอบกลับ — {date}",
    Service_Email_ReceiptSubject: "การตอบกลับของคุณ — {title}",
    Service_Email_ReceiptHeading: "ขอบคุณสำหรับการตอบกลับ!",
    Service_Email_ReceiptIntro: "นี่คือสำเนาของสิ่งที่คุณส่งไปยัง \"{title}\"",
    App_History_Title: "ประวัติเวอร์ชัน",
    App_History_RestoredNotice: "กู้คืนเวอร์ชันที่บันทึกเมื่อ {date} แล้ว ตรวจสอบ จากนั้นใช้ เก็บการตอบกลับ เพื่อเผยแพร่คำถามใหม่",
    App_History_Undo: "เลิกทำการกู้คืน",
    App_Share_CopyManual: "เบราว์เซอร์บล็อกการคัดลอก เลือกลิงก์ด้านบนแล้วกด Ctrl+C (Cmd+C บน Mac) เพื่อคัดลอก",
    App_Share_TeamsNote: "คุณอยู่ใน Microsoft Teams ลิงก์นี้เปิดหน้า SharePoint โดยตรง ผู้รับจึงต้องมีสิทธิ์เข้าถึงไซต์",
    App_Share_PrefillNotSecure: "คำตอบที่กรอกไว้ล่วงหน้าเป็นเพียงความสะดวก ทุกคนที่มีลิงก์สามารถเปลี่ยนได้ จึงอย่าถือว่าเป็นขอบเขตความปลอดภัย",
    Designer_Section_DropHere: "วางคำถามที่นี่",
    Designer_Section_DropEnd: "วางที่นี่เพื่อย้ายไปท้ายส่วนนี้",
    Designer_Rules_RemovedOne: "ลบกฎการแตกแขนงที่ไม่เหมาะสมอีกต่อไปแล้ว 1 กฎ",
    Designer_Rules_RemovedOther: "ลบกฎการแตกแขนงที่ไม่เหมาะสมอีกต่อไปแล้ว {count} กฎ",
    Designer_Settings_AllowEdit: "อนุญาตให้ผู้ตอบแก้ไขการตอบกลับของตน",
    Designer_Settings_AllowEditHint: "ผู้ตอบสามารถเปิดและอัปเดตสิ่งที่ส่งไปแล้วได้ แต่ละคนแก้ไขได้เฉพาะการตอบกลับของตนเอง",
    Designer_Settings_EnableApproval: "เปิดใช้เวิร์กโฟลว์การอนุมัติ",
    Designer_Settings_ApprovalNotify: "ส่งอีเมลถึงผู้ตอบเมื่อมีการตัดสินใจ",
    Designer_Settings_ApprovalHint: "เพิ่มคอลัมน์การอนุมัติในรายการการตอบกลับเมื่อคุณเผยแพร่ครั้งถัดไป เจ้าของอนุมัติหรือปฏิเสธการตอบกลับได้จากแท็บการตอบกลับ",
    Designer_History_Title: "ประวัติเวอร์ชัน",
    Designer_History_Intro: "เวอร์ชันที่บันทึกไว้ก่อนหน้านี้ของคำถามและการตั้งค่าของฟอร์มนี้ การกู้คืนจะโหลดเวอร์ชันเข้าตัวออกแบบ คุณเลิกทำได้ และคำถามใหม่จะถูกสร้างเมื่อเผยแพร่เท่านั้น",
    Designer_History_Loading: "กำลังโหลดเวอร์ชัน...",
    Designer_History_Empty: "ไม่พบเวอร์ชันก่อนหน้า ประวัติเวอร์ชันต้องเปิดใช้การกำหนดเวอร์ชันสำหรับรายการ \"Smart Forms Config\" และมีการแก้ไขที่บันทึกไว้อย่างน้อยหนึ่งครั้ง",
    Designer_History_Latest: "ล่าสุด",
    Designer_History_LatestTitle: "นี่คือเวอร์ชันที่ใช้งานอยู่ในขณะนี้",
    Designer_History_By: "โดย {name}",
    Designer_History_UnknownAuthor: "ไม่ทราบผู้เขียน",
    Designer_History_VersionLabel: "เวอร์ชัน {label}",
    Designer_History_Preview: "ดูตัวอย่าง",
    Designer_History_Restore: "กู้คืน",
    Designer_History_QuestionsOne: "1 คำถาม",
    Designer_History_QuestionsOther: "{count} คำถาม",
    Designer_History_LoadFailed: "ไม่สามารถโหลดเวอร์ชันนี้ได้",
    Designer_History_ConfirmTitle: "กู้คืนเวอร์ชันนี้หรือไม่",
    Designer_History_ConfirmText: "ฟอร์มจะถูกแทนที่ด้วยเวอร์ชันที่บันทึกเมื่อ {date} ({count} คำถาม) คุณเลิกทำได้ทันทีหลังจากนั้น"
  };
});
