define([], function () {
  return {
    Designer_Color_Blue: "Mavi",
    Designer_Color_Teal: "Deniz mavisi",
    Designer_Color_Green: "Yeşil",
    Designer_Color_Purple: "Mor",
    Designer_Color_Magenta: "Eflatun",
    Designer_Color_Red: "Kırmızı",
    Designer_Color_Orange: "Turuncu",
    Designer_Color_Gray: "Gri",
    Designer_Settings_LayoutSinglePage: "Tüm sorular tek sayfada",
    Designer_Settings_LayoutWizard: "Adım başına bir bölüm (sihirbaz)",
    Designer_Settings_Title: "Form ayarları",
    Designer_Common_Apply: "Uygula",
    Designer_Common_Cancel: "İptal",
    Designer_Settings_TabBasics: "Temel bilgiler",
    Designer_Settings_FormTitle: "Form başlığı",
    Designer_Settings_Description: "Açıklama",
    Designer_Settings_Layout: "Düzen",
    Designer_Settings_NumberQuestions: "Soruları numaralandır",
    Designer_Settings_ShuffleQuestions: "Soru sırasını her yanıtlayan için karıştır",
    Designer_Settings_ShowProgressBar: "İlerleme çubuğu göster",
    Designer_Settings_TabAppearance: "Görünüm",
    Designer_Settings_AccentColor: "Vurgu rengi",
    Designer_Settings_CustomColorTitle: "Özel renk",
    Designer_Settings_CustomColorAria: "Özel vurgu rengi",
    Designer_Settings_AccentHint: "Vurgu renkleri koyu sitelerde kontrast için otomatik olarak ayarlanır; böylece sayfa hangi temayı kullanırsa kullansın form okunaklı kalır.",
    Designer_Settings_ShowHeader: "Form üst bilgisini göster",
    Designer_Settings_HeaderIcon: "Üst bilgi simgesi",
    Designer_Settings_TabAfterSubmit: "Gönderdikten sonra",
    Designer_Settings_SubmitButtonText: "Gönder düğmesi metni",
    Designer_Settings_SubmitPlaceholder: "Gönder",
    Designer_Settings_ThankYouTitle: "Teşekkür başlığı",
    Designer_Settings_ThankYouPlaceholder: "Teşekkürler!",
    Designer_Settings_ThankYouMessage: "Teşekkür iletisi",
    Designer_Settings_ShowSubmitAnother: "\"Başka bir yanıt gönder\" düğmesini göster",
    Designer_Settings_TabNotifications: "Bildirimler",
    Designer_Settings_EmailEachResponseTo: "Her yanıtı şuraya e-postayla gönder",
    Designer_Settings_EmailPlaceholder: "ad@sirket.com; ekip@sirket.com",
    Designer_Settings_EmailDescription: "Kuruluşunuzdaki kişiler her yanıtı, liste öğesine bağlantıyla birlikte e-postayla alır",
    Designer_Settings_RespondentReceipt: "Yanıtlayanlara yanıtlarının bir kopyasını e-postayla gönder",
    Designer_Settings_NotificationsInfo: "Bildirimler SharePoint'in kendi posta hizmetini kullanır; bu nedenle alıcılar kuruluşunuzdaki kullanıcılar olmalıdır. Harici adresler sessizce yok sayılır.",
    Designer_Settings_TabAccess: "Erişim",
    Designer_Settings_OpenFrom: "Açılış tarihi",
    Designer_Settings_OpenImmediately: "Hemen aç",
    Designer_Settings_CloseAfter: "Kapanış tarihi",
    Designer_Settings_NeverClose: "Hiç kapanmasın",
    Designer_Settings_ClearDates: "Tarihleri temizle",
    Designer_Settings_DatesInverted: "Kapanış tarihi açılış tarihinden önce veya aynı gün olduğundan form hiçbir zaman yanıt kabul etmez.",
    Designer_Settings_MaxResponses: "Şu kadar yanıttan sonra durdur",
    Designer_Settings_NoLimit: "Sınır yok",
    Designer_Settings_OneResponsePerPerson: "Kişi başına yalnızca bir yanıta izin ver",
    Designer_Settings_AllowSaveDraft: "Yanıtlayanların taslak kaydedip daha sonra bitirmesine izin ver",
    Designer_Settings_ClosedMessage: "Form kapalıyken gösterilecek ileti",
    Designer_Settings_ClosedMessagePlaceholder: "Bu form artık yanıt kabul etmiyor.",
    Designer_Settings_AccessInfo: "Bu sınırları SharePoint değil, form uygular. Yanıt listesine öğe ekleme izni olan herkes yine de doğrudan listeden bir öğe ekleyebilir.",
    Designer_Field_StyleInfo: "Bilgi (vurgu)",
    Designer_Field_StyleSuccess: "Başarılı (yeşil)",
    Designer_Field_StyleWarning: "Uyarı (kehribar)",
    Designer_Field_StylePlain: "Düz metin",
    Designer_Field_StyleDivider: "Ayırıcı çizgi",
    Designer_Field_IconStars: "Yıldızlar",
    Designer_Field_IconHearts: "Kalpler",
    Designer_Field_IconThumbs: "Başparmak yukarı",
    Designer_Field_FormatPlain: "Düz sayı",
    Designer_Field_FormatCurrency: "Para birimi",
    Designer_Field_FormatPercent: "Yüzde",
    Designer_Field_UntitledQuestion: "Başlıksız soru",
    Designer_Field_DeletedQuestion: "silinmiş bir soru",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} ve {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "VEYA",
    Designer_Rule_JoinAll: "VE",
    Designer_Rule_Preview: "{conditions} olduğunda gösterilir.",
    Designer_Field_Yes: "Evet",
    Designer_Field_No: "Hayır",
    Designer_Field_When: "Koşul",
    Designer_Field_SelectValue: "Bir değer seçin",
    Designer_Field_DateValuePlaceholder: "YYYY-AA-GG veya \"today\"",
    Designer_Field_ValuePlaceholder: "Değer",
    Designer_Field_UpperBound: "Üst sınır",
    Designer_Field_RemoveCondition: "Bu koşulu kaldır",
    Designer_Field_FormulaInvalid: "Bu formül hesaplanamıyor. Parantezleri ve işleçleri kontrol edin.",
    Designer_Field_FormulaMissing: "Bu sorular mevcut değil: {names}.",
    Designer_Field_FormulaPreview: "Tüm girdiler 10 olduğunda bu {value} gösterir.",
    Designer_Field_HintYesNo: "\"yes\" veya \"no\" kullanın",
    Designer_Field_HintMultiDefault: "Birden çok varsayılan değeri ; ile ayırın",
    Designer_Field_HintSingleDefault: "Seçeneklerden biriyle eşleşmelidir",
    Designer_Field_HintDate: "\"today\" veya 2026-03-01 gibi bir tarih kullanın",
    Designer_Field_HintTime: "\"now\" veya 09:30 gibi bir saat kullanın",
    Designer_Field_QuestionSettings: "Soru ayarları",
    Designer_Field_Appearance: "Görünüm",
    Designer_Field_Style: "Stil",
    Designer_Field_ImageUrl: "Görsel URL'si (isteğe bağlı)",
    Designer_Field_Content: "İçerik",
    Designer_Field_BasicFormatting: "Temel biçimlendirmeye izin verilir: kalın, italik, listeler ve bağlantılar.",
    Designer_Field_TabOptions: "Seçenekler",
    Designer_Field_TabBranching: "Dallanma",
    Designer_Field_BranchingNeedsQuestion: "Önce başka bir soru ekleyin; dallanmanın dayanacağı bir şey olmalı.",
    Designer_Field_BranchingToggle: "Bu soruyu yalnızca diğer yanıtlar eşleştiğinde göster",
    Designer_Field_Match: "Eşleşme",
    Designer_Field_MatchAll: "bunların tümü",
    Designer_Field_MatchAny: "bunlardan herhangi biri",
    Designer_Field_AddCondition: "Koşul ekle",
    Designer_Field_TabValidation: "Doğrulama",
    Designer_Field_HelpText: "Yardım metni",
    Designer_Field_HelpTextPlaceholder: "Soru etiketinin altında gösterilir",
    Designer_Field_CheckboxLabel: "Onay kutusu etiketi",
    Designer_Field_Placeholder: "Yer tutucu",
    Designer_Field_DefaultAnswer: "Varsayılan yanıt",
    Designer_Field_RequiredMessage: "Özel zorunlu alan iletisi",
    Designer_Field_RequiredMessagePlaceholder: "{title} zorunludur",
    Designer_Field_ThisQuestion: "Bu soru",
    Designer_Field_RequiredMessageDescription: "Bu soru boş bırakıldığında standart ileti yerine gösterilir",
    Designer_Field_ReadOnly: "Salt okunur (yanıt yalnızca önceden doldurulmuş bir bağlantıdan gelebilir)",
    Designer_Field_ValidationRules: "Doğrulama kuralları",
    Designer_Field_MaxLength: "Maksimum uzunluk",
    Designer_Field_Pattern: "Bu desenle eşleşmelidir",
    Designer_Field_PatternDescription: "Bir normal ifade. Desen denetimi istemiyorsanız boş bırakın.",
    Designer_Field_PatternMessage: "Desen eşleşmediğinde gösterilecek ileti",
    Designer_Field_PatternMessagePlaceholder: "Bu yanıt beklenen biçimde değil",
    Designer_Field_Format: "Biçim",
    Designer_Field_UnitSuffix: "Değerden sonra gösterilen birim",
    Designer_Field_UnitSuffixPlaceholder: "kg, saat, adet…",
    Designer_Field_Minimum: "Minimum",
    Designer_Field_Maximum: "Maksimum",
    Designer_Field_Decimals: "Ondalık basamak",
    Designer_Field_Formula: "Formül",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Diğer sorulara metinleriyle, süslü parantez içinde başvurun. + - * / ( ) ile round, min, max, sum, avg desteklenir.",
    Designer_Field_AvailableQuestions: "Kullanılabilir sorular: {questions}",
    Designer_Field_NoneYet: "henüz yok",
    Designer_Field_Step: "Adım",
    Designer_Field_From: "Başlangıç",
    Designer_Field_To: "Bitiş",
    Designer_Field_LowLabel: "Alt uçtaki etiket",
    Designer_Field_LowLabelPlaceholder: "Hiç olası değil",
    Designer_Field_HighLabel: "Üst uçtaki etiket",
    Designer_Field_HighLabelPlaceholder: "Son derece olası",
    Designer_Field_SummarizeAs: "Özet biçimi",
    Designer_Field_SummarizeAverage: "Ortalama ve dağılım",
    Designer_Field_SummarizeNps: "Net Tavsiye Skoru (0–10 ölçeği gerekir)",
    Designer_Field_NpsWarning: "Net Tavsiye Skoru yalnızca 0–10 ölçeğinde anlamlıdır. Başlangıcı 0, bitişi 10 yapın.",
    Designer_Field_NumberOfIcons: "Simge sayısı",
    Designer_Field_Icon: "Simge",
    Designer_Field_AllowHalf: "Yarım değerlere izin ver",
    Designer_Field_ShowOptionsAs: "Seçenekleri şöyle göster",
    Designer_Field_DisplayButtons: "Satır içi düğmeler",
    Designer_Field_DisplayDropdown: "Açılır liste",
    Designer_Field_DisplayAutomatic: "Otomatik (en fazla 6 seçenekte satır içi)",
    Designer_Field_AllowOther: "Elle girilen bir \"Diğer\" seçeneği ekle",
    Designer_Field_OtherLabel: "\"Diğer\" seçeneğinin etiketi",
    Designer_Field_OtherPlaceholder: "Diğer",
    Designer_Field_ShuffleOptions: "Seçenek sırasını her yanıtlayan için karıştır",
    Designer_Field_MinSelections: "Minimum seçim sayısı",
    Designer_Field_MaxSelections: "Maksimum seçim sayısı",
    Designer_Field_SourceList: "Kaynak liste",
    Designer_Field_ChooseList: "Bir liste seçin",
    Designer_Field_LookupColumn: "Seçeneklerin okunacağı sütun",
    Designer_Field_ChooseColumn: "Bir sütun seçin",
    Designer_Field_ChooseListFirst: "Önce bir liste seçin",
    Designer_Field_LookupFilter: "Filtre (isteğe bağlı)",
    Designer_Field_LookupFilterDescription: "Hangi kaynak öğelerinin seçenek olacağını daraltan bir OData filtresi",
    Designer_Field_LookupInfo: "Yanıtlar, kaynak öğeye bağlantı değil seçenek metnini saklar; böylece kaynak liste sonradan değişse bile yanıtlar okunabilir kalır.",
    Designer_Field_ConsentText: "Onay kutusunun üstünde gösterilen koşullar",
    Designer_Field_AllowMultiplePeople: "Birden çok kişiye izin ver",
    Designer_Field_AllowGroups: "Gruplara da izin ver",
    Designer_Field_IncludeTime: "Saat bilgisi ekle",
    Designer_Field_TimeStep: "Saat adımı (dakika)",
    Designer_Field_MaxFiles: "Maksimum dosya sayısı",
    Designer_Field_MaxFileSize: "Dosya başına maks. boyut (MB)",
    Designer_Field_AcceptedTypes: "Kabul edilen dosya türleri",
    Designer_Field_AcceptedTypesDescription: "Virgülle ayrılmış uzantılar. SharePoint'in izin verdiği her şeyi kabul etmek için boş bırakın.",
    Designer_Field_FilesInfo: "Dosyalar, yanıt öğesine ek olarak kaydedilir. SharePoint, burada ne izin verdiğinizden bağımsız olarak bazı uzantıları (.exe gibi) engeller.",
    Designer_Field_Rows: "Satır",
    Designer_Field_ProvisionedNote: "Bu sorunun zaten bir liste sütunu var ({name}). Sütunun türünü değiştiren ayarlar kilitlidir; farklı bir tür gerekiyorsa soruyu çoğaltın.",
    Designer_Category_Text: "Metin",
    Designer_Category_Choice: "Seçim",
    Designer_Category_Scales: "Ölçekler",
    Designer_Category_Date: "Tarih",
    Designer_Category_People: "Kişiler",
    Designer_Category_Advanced: "Gelişmiş",
    Designer_Category_Layout: "Düzen",
    Designer_Menu_CommonPresets: "Yaygın hazır ayarlar",
    Designer_Menu_AllTypes: "Tüm soru türleri",
    Designer_Menu_ChangeType: "Türü değiştir",
    Designer_Menu_TypeLockedTitle: "Liste sütunu zaten var, bu nedenle tür kilitli. Değiştirmek için soruyu çoğaltın.",
    Designer_Menu_MoreSettings: "Dallanma, doğrulama ve daha fazlası",
    Designer_Menu_InsertBelow: "Aşağıya soru ekle",
    Designer_Card_Duplicate: "Çoğalt",
    Designer_Card_DeleteQuestion: "Soruyu sil",
    Designer_Outline_Aria: "Soru ana hatları",
    Designer_Outline_QuestionCountOne: "{count} soru",
    Designer_Outline_QuestionCountOther: "{count} soru",
    Designer_Outline_IssuesTitle: "İncelenecek {count} sorun",
    Designer_Outline_Find: "Soru bul",
    Designer_Outline_Empty: "Henüz soru yok.",
    Designer_Section_DefaultTitle: "Bölüm {number}",
    Designer_Card_Question: "Soru",
    Designer_Card_BranchingTitle: "Bu soru yalnızca bir dallanma kuralı eşleştiğinde görünür",
    Designer_Card_BranchingChip: "Dallanma",
    Designer_Card_LiveTitle: "Liste sütunu var, bu nedenle tür kilitli",
    Designer_Card_LiveChip: "Canlı",
    Designer_Card_CheckChip: "Kontrol et",
    Designer_Option_Placeholder: "Seçenek {number}",
    Designer_Option_LabelAria: "Seçenek {number} etiketi",
    Designer_Option_ImageUrl: "Görsel URL'si",
    Designer_Option_ImageUrlAria: "Seçenek {number} görsel URL'si",
    Designer_Option_Remove: "Seçeneği kaldır",
    Designer_Option_RemoveAria: "Seçenek {number} öğesini kaldır",
    Designer_Option_Add: "Seçenek ekle",
    Designer_Option_OtherHint: "Yanıtlayanlar “{label}” etiketli bir yanıtı elle de girebilir.",
    Designer_Option_OtherFallback: "Diğer",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Kaldır",
    Designer_Grid_RemoveAria: "{label} {number} öğesini kaldır",
    Designer_Grid_Statements: "İfadeler",
    Designer_Grid_Scale: "Ölçek",
    Designer_Grid_AddStatement: "İfade ekle",
    Designer_Grid_AddScale: "Ölçek ekle",
    Designer_Width_Full: "Tam genişlik",
    Designer_Width_Half: "Yarım genişlik",
    Designer_Width_Third: "Üçte bir genişlik",
    Designer_Width_Aria: "Soru genişliği",
    Designer_Card_BlockLabelPlaceholder: "Blok etiketi (yanıtlayanlara gösterilmez)",
    Designer_Card_QuestionText: "Soru metni",
    Designer_Card_MoveUp: "Yukarı taşı",
    Designer_Card_MoveQuestionUp: "Soruyu yukarı taşı",
    Designer_Card_MoveDown: "Aşağı taşı",
    Designer_Card_MoveQuestionDown: "Soruyu aşağı taşı",
    Designer_Card_DuplicateQuestion: "Soruyu çoğalt",
    Designer_Card_MultipleAnswers: "Birden çok yanıt",
    Designer_Card_Required: "Zorunlu",
    Designer_Card_MoreOptions: "Diğer seçenekler",
    Designer_Card_MoreOptionsAria: "Bu soru için diğer seçenekler",
    Designer_Canvas_FormTitle: "Form başlığı",
    Designer_Canvas_DescriptionPlaceholder: "Açıklama ekleyin (isteğe bağlı)",
    Designer_Canvas_DescriptionAria: "Form açıklaması",
    Designer_Canvas_EmptyTitle: "İlk sorunuzu ekleyin",
    Designer_Canvas_EmptyBody: "Başlamak için bir soru türü seçin. Soruları sürükleyerek yeniden sıralayabilir ve dallanma ekleyerek kişilerin yalnızca kendileri için geçerli olanı görmesini sağlayabilirsiniz.",
    Designer_Section_Chip: "Bölüm {number} / {total}",
    Designer_Section_TitlePlaceholder: "Bölüm başlığı",
    Designer_Section_TitleAria: "Bölüm {number} başlığı",
    Designer_Section_DescriptionPlaceholder: "Açıklama (isteğe bağlı)",
    Designer_Section_DescriptionAria: "Bölüm {number} açıklaması",
    Designer_Section_MoveUp: "Bölümü yukarı taşı",
    Designer_Section_MoveDown: "Bölümü aşağı taşı",
    Designer_Section_Delete: "Bölümü sil",
    Designer_Card_DragToReorder: "Yeniden sıralamak için sürükleyin",
    Designer_Card_ReorderAria: "{title} öğesini yeniden sırala",
    Designer_Card_ReorderFallback: "soru",
    Designer_Canvas_AddNew: "Yeni ekle",
    Designer_Canvas_AddSection: "Bölüm ekle",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Sokak adresi",
    Form_Address_Street2Placeholder: "Daire, kat vb. (isteğe bağlı)",
    Form_Address_CityPlaceholder: "Şehir",
    Form_Address_StatePlaceholder: "Eyalet / ilçe",
    Form_Address_PostalCodePlaceholder: "Posta kodu",
    Form_Address_CountryPlaceholder: "Ülke",
    Form_Address_StreetAria: "sokak adresi",
    Form_Address_Street2Aria: "adres satırı 2",
    Form_Address_CityAria: "şehir",
    Form_Address_StateAria: "eyalet veya ilçe",
    Form_Address_PostalCodeAria: "posta kodu",
    Form_Address_CountryAria: "ülke",
    Form_Consent_DefaultLabel: "Kabul ediyorum",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "{total} satırdan {answered} tanesi yanıtlandı",
    Form_Lookup_LoadError: "Bu sorunun seçenekleri yüklenemedi.",
    Form_Lookup_Loading: "Seçenekler yükleniyor…",
    Form_Lookup_SelectOptionsPlaceholder: "Seçenekleri belirleyin",
    Form_Lookup_SelectOptionPlaceholder: "Bir seçenek belirleyin",
    Form_Person_Placeholder: "Bir ad yazmaya başlayın…",
    Form_Person_SuggestedPeopleAndGroups: "Önerilen kişiler ve gruplar",
    Form_Person_SuggestedPeople: "Önerilen kişiler",
    Form_Person_NoPeopleOrGroups: "Kişi veya grup bulunamadı",
    Form_Person_NoPeople: "Kişi bulunamadı",
    Form_Person_Searching: "Aranıyor…",
    Form_Ranking_Moved: "{item}, {total} içinde {position}. konuma taşındı",
    Form_Ranking_MoveUp: "Yukarı taşı",
    Form_Ranking_MoveDown: "Aşağı taşı",
    Form_Ranking_MoveItemUpAria: "{item} öğesini yukarı taşı",
    Form_Ranking_MoveItemDownAria: "{item} öğesini aşağı taşı",
    Form_Rating_ValueText: "{value} / {max}",
    Form_Rating_NotRated: "Derecelendirilmedi",
    Form_Rating_Clear: "Derecelendirmeyi temizle",
    Form_RichText_Bold: "Kalın",
    Form_RichText_Italic: "İtalik",
    Form_RichText_Underline: "Altı çizili",
    Form_RichText_BulletedList: "Madde işaretli liste",
    Form_RichText_NumberedList: "Numaralı liste",
    Form_RichText_ClearFormatting: "Biçimlendirmeyi temizle",
    Form_RichText_ToolbarAria: "Metin biçimlendirme",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\" atlandı; sınır {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" kabul edilen bir tür değil.",
    Form_File_TooLarge: "\"{name}\", {size} MB'tan büyük.",
    Form_File_AlreadyAttached: "\"{name}\" zaten ekli.",
    Form_File_ReadError: "Dosyalardan biri okunamadı. Yeniden eklemeyi deneyin.",
    Form_File_HintMaxSize: "her biri en fazla {size} MB",
    Form_File_HintOneFile: "1 dosya",
    Form_File_HintMaxFiles: "en fazla {count} dosya",
    Form_File_Reading: "Dosyalar okunuyor…",
    Form_File_DropPrompt: "Dosyaları buraya bırakın veya göz atmak için tıklayın",
    Form_File_Remove: "{name} öğesini kaldır",
    Form_Signature_Alt: "İmza",
    Form_Signature_AriaSigned: "{label} — imzalandı",
    Form_Signature_AriaEmpty: "{label} — boş",
    Form_Signature_Clear: "Temizle",
    Form_Signature_Signed: "İmzalandı",
    Form_Signature_Prompt: "Yukarıya fare, kalem veya parmağınızla imza atın",
    Form_Time_Placeholder: "Bir saat seçin",
    Form_Field_DatePlaceholder: "Bir tarih seçin",
    Form_Field_TimeAriaWithLabel: "{label} — saat",
    Form_Field_TimeAria: "Saat",
    Form_Field_OtherDefault: "Diğer",
    Form_Field_SelectOptionsPlaceholder: "Seçenekleri belirleyin",
    Form_Field_PleaseSpecify: "Lütfen belirtin",
    Form_Field_OtherSpecifyAria: "{label} — lütfen belirtin",
    Form_Field_SelectOptionPlaceholder: "Bir seçenek belirleyin",
    Form_Field_Yes: "Evet",
    Form_Field_No: "Hayır",
    Form_Field_SliderHint: "Yanıtlamak için kaydırıcıyı sürükleyin",
    Form_Field_WebAddressAriaWithLabel: "{label} — web adresi",
    Form_Field_WebAddressAria: "Web adresi",
    Form_Field_DisplayTextPlaceholder: "Görünen metin (isteğe bağlı)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — görünen metin",
    Form_Field_DisplayTextAria: "Görünen metin",
    Form_Field_ChooseBetween: "{min} ile {max} arasında seçim yapın",
    Form_Field_ChooseAtLeast: "En az {min} seçin",
    Form_Field_ChooseUpTo: "En fazla {max} seçin",
    Form_Field_SelectedCount: "{count} seçildi",
    Form_Field_RequiredAria: "(zorunlu)",
    Form_Submit_SaveError: "Yanıtınız kaydedilemedi. Formun tasarımcıdan yayımlandığından ve yanıt listesine öğe ekleme izninizin olduğundan emin olun.",
    Form_Empty_Message: "Bu formda henüz soru yok. Form sahibi bunları Sorular sekmesinden ekleyebilir.",
    Form_Checking: "Form denetleniyor…",
    Form_Closed_NotYetOpen: "Henüz açılmadı",
    Form_Closed_AlreadyAnswered: "Zaten yanıtlandı",
    Form_Closed_Title: "Form kapatıldı",
    Form_Confirmation_PreviewNotice: "Bu bir önizlemeydi; yanıt listesine hiçbir şey kaydedilmedi.",
    Form_Confirmation_PreviewAgain: "Yeniden önizle",
    Form_Confirmation_SubmitAnother: "Başka bir yanıt gönder",
    Form_Wizard_StepFallback: "Adım {step}",
    Form_Wizard_StepsAria: "Form adımları",
    Form_Wizard_StepOf: "Adım {step} / {total}",
    Form_ErrorSummary_Title: "Lütfen {count} yanıtı kontrol edin:",
    Form_ErrorSummary_UntitledQuestion: "Başlıksız soru",
    Form_ErrorSummary_Question: "Soru",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Geri",
    Form_Nav_Next: "İleri",
    Form_Draft_Saving: "Kaydediliyor…",
    Form_Draft_Saved: "Taslak kaydedildi",
    Form_Draft_SaveAndFinishLater: "Kaydet ve daha sonra bitir",
    Form_Draft_NotSaved: "Taslak kaydedilmedi",
    Form_Submit_Preview: "Gönder (önizleme)",
    Form_Submit_Button: "Gönder",
    Form_Response_NoAnswer: "Yanıt yok",
    Form_Signature_TypeLabel: "Ad ve soyadınızı yazın",
    Form_Signature_TypeInstead: "Bunun yerine adımı yaz",
    Form_Signature_DrawInstead: "Bunun yerine çiz",
    Form_Edit_Button: "Önceki yanıtınızı düzenleyin",
    Form_Edit_Available: "Zaten bir yanıt gönderdiniz. Yeni yanıt göndermek yerine mevcut yanıtı düzenleyebilirsiniz.",
    Form_Edit_Banner: "Önceki yanıtınızı düzenliyorsunuz.",
    Form_Edit_Save: "Yanıtı güncelle",
    Form_Edit_UpdatedTitle: "Yanıt güncellendi",
    Form_Edit_UpdatedMessage: "Değişiklikleriniz kaydedildi.",
    Form_Edit_LoadError: "Önceki yanıtınız yüklenemedi. Lütfen tekrar deneyin.",
    Form_Draft_MissingFiles: "Lütfen yeniden ekleyin: {names}. Bu dosyalar geri yüklenemedi.",
    Form_Attachments_Failed: "Yanıtlarınız kaydedildi ancak şu ekler karşıya yüklenemedi: {names}. Lütfen tekrar deneyin veya form sahibiyle iletişime geçin.",
    Logic_ThisQuestion: "Bu soru",
    Logic_Required: "{label} gereklidir",
    Logic_RequiredConsent: "Devam etmek için kutuyu işaretleyin",
    Logic_RequiredFile: "Lütfen en az bir dosya ekleyin",
    Logic_RequiredSignature: "Lütfen imzanızı ekleyin",
    Logic_RequiredLikert: "Lütfen her satırı yanıtlayın",
    Logic_InvalidEmail: "Geçerli bir e-posta adresi girin",
    Logic_InvalidPhone: "Geçerli bir telefon numarası girin",
    Logic_InvalidUrl: "http:// veya https:// ile başlayan geçerli bir web adresi girin",
    Logic_MinValue: "Değer en az {value} olmalıdır",
    Logic_MaxValue: "Değer en fazla {value} olmalıdır",
    Logic_MaxLength: "Azami uzunluk {max} karakterdir",
    Logic_ChooseAtLeastOne: "En az {count} seçenek belirleyin",
    Logic_ChooseAtLeastMany: "En az {count} seçenek belirleyin",
    Logic_ChooseAtMostOne: "En fazla {count} seçenek belirleyin",
    Logic_ChooseAtMostMany: "En fazla {count} seçenek belirleyin",
    Logic_LikertRemaining: "Lütfen her satırı yanıtlayın ({count} kaldı)",
    Logic_MaxFilesOne: "En fazla {count} dosya ekleyin",
    Logic_MaxFilesMany: "En fazla {count} dosya ekleyin",
    Logic_FileTooLarge: "\"{name}\" dosyası {size} MB'tan büyük",
    Logic_FileTypeNotAccepted: "\"{name}\" kabul edilen bir dosya türü değil ({types})",
    Logic_AddressRequired: "En azından bir sokak ve şehir girin",
    Logic_PatternDefault: "Bu yanıt beklenen biçimde değil",
    Logic_Yes: "Evet",
    Logic_No: "Hayır",
    Logic_Agreed: "Kabul edildi",
    Logic_NotAgreed: "Kabul edilmedi",
    Logic_Signed: "İmzalandı",
    Logic_NoAnswer: "(yanıt yok)",
    Logic_Unknown: "(bilinmiyor)",
    Logic_OtherSlice: "Diğer ({count})",
    Logic_CsvResponseId: "Yanıt Kimliği",
    Logic_CsvSubmitted: "Gönderildi",
    Logic_CsvSubmittedBy: "Gönderen",
    Logic_EmailQuestion: "Soru",
    Logic_EmailViewItem: "Microsoft Lists'te görüntüle",
    Logic_EmailFooter: "Smart Forms tarafından otomatik olarak gönderildi.",
    Logic_ClosedDefault: "Bu form artık yanıt kabul etmiyor.",
    Logic_NotYetOpen: "Bu form {date} tarihinde açılacak.",
    Logic_AlreadyResponded: "Bu formu zaten yanıtladınız. Teşekkürler!",
    Logic_UntitledQuestion: "Başlıksız bir soru",
    Logic_Issue_NoQuestions: "Yanıt toplamadan önce en az bir soru ekleyin.",
    Logic_Issue_NoTitle: "Bir sorunun metni yok; yayımladığınızda otomatik olarak adlandırılacak.",
    Logic_Issue_DuplicateTitle: "{label} metnini başka bir soruyla paylaşıyor; bu, sonuçların okunmasını zorlaştırır.",
    Logic_Issue_NeedTwoOptions: "{label} için en az iki seçenek gerekir.",
    Logic_Issue_ImageNoImage: "{label} içinde görseli olmayan seçenekler var; metin kutucukları olarak gösterilecekler.",
    Logic_Issue_LikertNeedRow: "{label} için en az bir satır gerekir.",
    Logic_Issue_LikertNeedColumns: "{label} için en az iki ölçek sütunu gerekir.",
    Logic_Issue_NoLookupList: "{label} için kaynak liste seçilmedi.",
    Logic_Issue_NoFormula: "{label} için formül yok.",
    Logic_Issue_BadFormula: "{label} hesaplanamayan bir formül içeriyor. Parantezleri ve işleçleri denetleyin.",
    Logic_Issue_MissingRefs: "{label} var olmayan sorulara başvuruyor: {names}.",
    Logic_Issue_BadPattern: "{label} için doğrulama deseni geçersiz.",
    Logic_Issue_BrokenRule: "{label} için silinmiş bir soruyu gösteren bir dallanma kuralı var.",
    Logic_Issue_SelfRule: "{label} için kendine başvuran bir dallanma kuralı var.",
    Logic_Issue_RuleMismatch: "{label} için bağlı olduğu soruya artık uymayan bir dallanma kuralı var.",
    Logic_Issue_RequiredReadOnly: "{label} hem zorunlu hem salt okunur olduğundan yalnızca önceden doldurulmuş bir bağlantıyla yanıtlanabilir.",
    Logic_Issue_EmptySection: "Bir bölümde soru yok ve atlanacak.",
    Logic_Issue_CloseBeforeOpen: "Kapanış tarihi açılış tarihinde veya öncesinde olduğundan form hiçbir zaman yanıt kabul etmeyecek.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Onay e-postaları açık ancak onay adımı kapalı.",
    Logic_Op_equals: "şuna eşit",
    Logic_Op_notEquals: "şuna eşit değil",
    Logic_Op_contains: "içerir",
    Logic_Op_notContains: "içermez",
    Logic_Op_notEmpty: "yanıtlanmış",
    Logic_Op_empty: "yanıtlanmamış",
    Logic_Op_greaterThan: "şundan büyük",
    Logic_Op_greaterOrEqual: "en az",
    Logic_Op_lessThan: "şundan küçük",
    Logic_Op_lessOrEqual: "en fazla",
    Logic_Op_between: "arasında",
    Logic_Op_before: "şundan önce",
    Logic_Op_after: "şundan sonra",
    Logic_Type_Text: "Kısa yanıt",
    Logic_TypeDesc_Text: "Tek satırlık metin",
    Logic_Category_Text: "Metin",
    Logic_Type_MultilineText: "Uzun yanıt",
    Logic_TypeDesc_MultilineText: "Birkaç satırlık düz metin",
    Logic_Type_RichText: "Biçimlendirilmiş metin",
    Logic_TypeDesc_RichText: "Kalın, listeler ve bağlantılar",
    Logic_Type_Choice: "Seçim",
    Logic_TypeDesc_Choice: "Seçenek listesinden seçin",
    Logic_Category_Choice: "Seçim",
    Logic_Type_ImageChoice: "Görsel seçimi",
    Logic_TypeDesc_ImageChoice: "Resim kutucuklarından seçin",
    Logic_Type_Lookup: "Listeden arama",
    Logic_TypeDesc_Lookup: "Seçenekler başka bir SharePoint listesinden canlı okunur",
    Logic_Type_YesNo: "Evet / Hayır",
    Logic_TypeDesc_YesNo: "Basit bir açma/kapama anahtarı",
    Logic_Type_Consent: "Onay",
    Logic_TypeDesc_Consent: "Yanıtlayanın devam etmek için işaretlemesi gereken bir onay kutusu",
    Logic_Type_Ranking: "Sıralama",
    Logic_TypeDesc_Ranking: "Seçenekleri tercih sırasına sürükleyin",
    Logic_Type_Rating: "Derecelendirme",
    Logic_TypeDesc_Rating: "Yıldızlar, kalpler veya başparmaklar",
    Logic_Category_Scales: "Ölçekler",
    Logic_Type_Scale: "Görüş ölçeği",
    Logic_TypeDesc_Scale: "Uçları etiketli numaralı bir ölçek",
    Logic_Type_Slider: "Kaydırıcı",
    Logic_TypeDesc_Slider: "Kayan bir ölçek üzerinde bir değer",
    Logic_Type_Likert: "Likert tablosu",
    Logic_TypeDesc_Likert: "Birkaç ifadeyi ortak bir ölçekte derecelendirin",
    Logic_Type_Number: "Sayı",
    Logic_TypeDesc_Number: "Düz, para birimi veya yüzde",
    Logic_Category_Advanced: "Gelişmiş",
    Logic_Type_Calculated: "Hesaplanan",
    Logic_TypeDesc_Calculated: "Diğer yanıtlardan hesaplanan salt okunur bir toplam",
    Logic_Type_Date: "Tarih",
    Logic_TypeDesc_Date: "Takvim tarihi, isteğe bağlı olarak saatle birlikte",
    Logic_Category_Date: "Tarih",
    Logic_Type_Time: "Saat",
    Logic_TypeDesc_Time: "Yalnızca günün saati",
    Logic_Type_Person: "Kişi",
    Logic_TypeDesc_Person: "Kuruluştan bir kişi seçin",
    Logic_Category_People: "Kişiler",
    Logic_Type_Email: "E-posta",
    Logic_TypeDesc_Email: "Doğrulanan bir e-posta adresi",
    Logic_Type_Phone: "Telefon",
    Logic_TypeDesc_Phone: "Doğrulanan bir telefon numarası",
    Logic_Type_Address: "Adres",
    Logic_TypeDesc_Address: "Sokak, şehir, posta kodu ve ülke",
    Logic_Type_Hyperlink: "Bağlantı",
    Logic_TypeDesc_Hyperlink: "Bir web adresi",
    Logic_Type_FileUpload: "Dosya yükleme",
    Logic_TypeDesc_FileUpload: "Yanıta bir veya daha fazla dosya ekleyin",
    Logic_Type_Signature: "İmza",
    Logic_TypeDesc_Signature: "Fare, kalem veya parmakla imzalayın",
    Logic_Type_Content: "Metin bloğu",
    Logic_TypeDesc_Content: "Yönergeler veya görsel — yanıt toplamaz",
    Logic_Category_Layout: "Düzen",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Tavsiye etme olasılığınız nedir…",
    Logic_Preset_satisfaction: "Memnuniyet (1–5)",
    Logic_PresetDesc_satisfaction: "Çok memnuniyetsizden çok memnuna",
    Logic_Preset_currency: "Para birimi",
    Logic_PresetDesc_currency: "Bir para tutarı",
    Logic_Preset_percent: "Yüzde",
    Logic_PresetDesc_percent: "Bir yüzde değeri",
    Logic_Template_blank_Name: "Boş form",
    Logic_Template_blank_Description: "Sıfırdan başlayın",
    Logic_Template_feedback_Name: "Müşteri geri bildirimi",
    Logic_Template_feedback_Description: "NPS, derecelendirmeler ve açık yorumlar",
    Logic_Template_event_Name: "Etkinlik kaydı",
    Logic_Template_event_Description: "Katılımcı bilgileri, oturumlar ve beslenme ihtiyaçları",
    Logic_Template_itrequest_Name: "BT hizmet talebi",
    Logic_Template_itrequest_Description: "Öncelik ve eklerle kategorilere ayrılmış talepler",
    Logic_Template_expense_Name: "Masraf talebi",
    Logic_Template_expense_Description: "Kalemler, makbuzlar ve hesaplanan toplam",
    Logic_Template_pulse_Name: "Çalışan nabız anketi",
    Logic_Template_pulse_Description: "Likert tablosu, bağlılık ölçeği ve anonimlik notu",
    Logic_Template_safety_Name: "Güvenlik denetimi",
    Logic_Template_safety_Description: "Kontrol listesi, fotoğraflar ve imza",
    Logic_Template_booking_Name: "Oda veya kaynak rezervasyonu",
    Logic_Template_booking_Description: "Zaman aralıklı, aramaya dayalı kaynak seçici",
    Charts_ColumnChartAria: "{count} kategorili sütun grafiği",
    Charts_DonutChartAria: "{count} kategorili halka grafik",
    Charts_NoAnswers: "Henüz yanıt yok.",
    Charts_NoResponses: "Henüz yanıt yok.",
    Charts_Responses: "Yanıtlar",
    Charts_ResponsesOverTime: "Zaman içinde yanıtlar",
    Responses_Chart_Answer: "Yanıt",
    Responses_Chart_Average: "Ortalama",
    Responses_Chart_AverageOf: "{count} ortalaması",
    Responses_Chart_AveragePosition: "Ortalama konum",
    Responses_Chart_AverageRange: "Ortalama (1–{max})",
    Responses_Chart_AvgValue: "ort. {value}",
    Responses_Chart_Detractors: "Eleştirenler (0–6)",
    Responses_Chart_Max: "Maks",
    Responses_Chart_Maximum: "Maksimum",
    Responses_Chart_Median: "Medyan",
    Responses_Chart_MentionOne: "{count} bahsedilme",
    Responses_Chart_MentionOther: "{count} bahsedilme",
    Responses_Chart_Min: "Min",
    Responses_Chart_Minimum: "Minimum",
    Responses_Chart_NoAnswers: "Henüz yanıt yok.",
    Responses_Chart_NoNumeric: "Henüz sayısal yanıt yok.",
    Responses_Chart_NoRankings: "Henüz sıralama yok.",
    Responses_Chart_NoScores: "Henüz puan yok.",
    Responses_Chart_NotEnoughText: "Özetlemek için henüz yeterli metin yok.",
    Responses_Chart_NpsScore: "NPS skoru",
    Responses_Chart_Option: "Seçenek",
    Responses_Chart_Passives: "Pasifler (7–8)",
    Responses_Chart_Promoters: "Destekleyenler (9–10)",
    Responses_Chart_ResponseOne: "yanıt",
    Responses_Chart_ResponseOther: "yanıt",
    Responses_Chart_Responses: "Yanıtlar",
    Responses_Chart_ShowingAnswers: "{total} yanıttan {shown} tanesi gösteriliyor.",
    Responses_Chart_Statement: "İfade",
    Responses_Chart_Statistic: "İstatistik",
    Responses_Chart_StdDev: "Std. sapma",
    Responses_Chart_StdDeviation: "Standart sapma",
    Responses_Chart_Total: "Toplam",
    Responses_Chart_Value: "Değer",
    Responses_Dashboard_AllHidden: "Her soru panodan gizlenmiş. Geri getirmek için “Gizli soruları göster” seçeneğini kullanın.",
    Responses_Dashboard_AnsweredOf: "{total} sorudan {answered} tanesi yanıtlandı",
    Responses_Dashboard_AnsweredOfPinned: "{total} sorudan {answered} tanesi yanıtlandı · sabitlendi",
    Responses_Dashboard_AveragedAcrossResponses: "Yanıtların ortalaması alındı",
    Responses_Dashboard_ByDay: "Güne göre",
    Responses_Dashboard_ByMonth: "Aya göre",
    Responses_Dashboard_ByWeek: "Haftaya göre",
    Responses_Dashboard_ChartAuto: "Otomatik",
    Responses_Dashboard_ChartBars: "Çubuklar",
    Responses_Dashboard_ChartColumns: "Sütunlar",
    Responses_Dashboard_ChartDonut: "Halka",
    Responses_Dashboard_ChartGauge: "Gösterge",
    Responses_Dashboard_ChartHistogram: "Histogram",
    Responses_Dashboard_ChartOptions: "Grafik seçenekleri",
    Responses_Dashboard_ChartOptionsFor: "{title} için grafik seçenekleri",
    Responses_Dashboard_ChartStatistics: "İstatistikler",
    Responses_Dashboard_ChartTable: "Tablo",
    Responses_Dashboard_ChartWordFrequency: "Sözcük sıklığı",
    Responses_Dashboard_EmptyBody: "İnsanlar yanıtlamaya başladığında bu pano otomatik olarak dolar: öne çıkan sayılar, yanıt zaman çizelgesi ve izlemeye değer sorular için bir grafik.",
    Responses_Dashboard_EmptyTitle: "Henüz yanıt yok",
    Responses_Dashboard_Hide: "Panodan gizle",
    Responses_Dashboard_Highlights: "Öne çıkanlar",
    Responses_Dashboard_Last7Days: "Son 7 gün",
    Responses_Dashboard_LatestDate: "Son: {date}",
    Responses_Dashboard_MedianTimeToComplete: "Ortalama tamamlama süresi",
    Responses_Dashboard_NoPriorWeek: "Karşılaştırılacak önceki hafta yok",
    Responses_Dashboard_OneEach: "Her birinden bir",
    Responses_Dashboard_Pin: "Panoya sabitle",
    Responses_Dashboard_QuestionFallback: "soru",
    Responses_Dashboard_QuestionsAnswered: "Yanıtlanan sorular",
    Responses_Dashboard_RecordedOnSubmit: "Gönderim sırasında kaydedilir",
    Responses_Dashboard_RepeatResponses: "{count} tekrarlanan yanıt",
    Responses_Dashboard_ResponsesOverTime: "Zaman içinde yanıtlar",
    Responses_Dashboard_ShowHidden: "Gizli soruları göster",
    Responses_Dashboard_SinceMidnight: "Gece yarısından beri",
    Responses_Dashboard_Today: "Bugün",
    Responses_Dashboard_TotalResponses: "Toplam yanıt",
    Responses_Dashboard_UniqueRespondents: "Benzersiz yanıtlayan",
    Responses_Dashboard_Unpin: "Panodan sabitlemeyi kaldır",
    Responses_Dashboard_UntitledQuestion: "Başlıksız soru",
    Responses_Dashboard_VsPrevious7Days: "önceki 7 güne göre",
    Responses_Detail_Answers: "Yanıtlar",
    Responses_Detail_AsTheForm: "Form olarak",
    Responses_Detail_Cancel: "İptal",
    Responses_Detail_Delete: "Sil",
    Responses_Detail_DeleteBody: "Liste öğesi sitenin geri dönüşüm kutusuna taşınır; oradan geri yüklenebilir.",
    Responses_Detail_DeleteTitle: "Bu yanıt silinsin mi?",
    Responses_Detail_Deleting: "Siliniyor…",
    Responses_Detail_Draft: "Taslak",
    Responses_Detail_Header: "Yanıt {index} / {total}",
    Responses_Detail_LoadingAttachments: "Ekler yükleniyor…",
    Responses_Detail_Next: "Sonraki yanıt",
    Responses_Detail_NoAnswer: "Yanıt yok",
    Responses_Detail_Previous: "Önceki yanıt",
    Responses_Detail_Print: "Yazdır",
    Responses_Detail_Signature: "İmza",
    Responses_Detail_Signed: "İmzalandı",
    Responses_Detail_Took: "{duration} sürdü",
    Responses_Summary_AnsweredOfType: "{total} sorudan {answered} tanesi yanıtlandı · {type}",
    Responses_Summary_ByField: "{title} bazında",
    Responses_Summary_CompareBy: "Şuna göre karşılaştır…",
    Responses_Summary_EmptyBody: "Her sorunun kendi özeti burada yer alacak.",
    Responses_Summary_NoComparison: "Karşılaştırma yok",
    Responses_Summary_NothingToCompare: "“{title}” sorusunu yanıtlayan olmadığından karşılaştırılacak bir şey yok.",
    Responses_Summary_OtherNote: "{max} kategoriden fazlası olan grafiklerde en küçükler “Diğer” altında gruplanır; her değeri görmek için bir kartı Tablo görünümüne geçirin.",
    Responses_Summary_ResponseCountOne: "{count} yanıt",
    Responses_Summary_ResponseCountOther: "{count} yanıt",
    Responses_Summary_SeeAllAnswers: "Tüm yanıtları tabloda gör",
    Responses_Summary_SegmentNote: "En büyük {groups} grup gösteriliyor. Birden çok yanıt seçen bir yanıt eşleşen her grupta görüneceğinden grup toplamları {total} değerinden fazla olabilir.",
    Responses_Summary_SplitBy: "{title} bazında böl",
    Responses_Summary_Untitled: "başlıksız",
    Responses_Table_Apply: "Uygula",
    Responses_Table_Cancel: "İptal",
    Responses_Table_ClearSelection: "Seçimi temizle",
    Responses_Table_ColumnOrder: "Sütun sırası",
    Responses_Table_ColumnsCount: "Sütunlar ({shown}/{total})",
    Responses_Table_Delete: "Sil",
    Responses_Table_DeleteBody: "Liste öğeleri sitenin geri dönüşüm kutusuna taşınır; oradan geri yüklenebilir.",
    Responses_Table_DeleteSelected: "Seçilenleri sil",
    Responses_Table_DeleteTitleOne: "{count} yanıt silinsin mi?",
    Responses_Table_DeleteTitleOther: "{count} yanıt silinsin mi?",
    Responses_Table_Deleting: "Siliniyor…",
    Responses_Table_MoveDown: "Aşağı taşı",
    Responses_Table_MoveDownFor: "{title} öğesini aşağı taşı",
    Responses_Table_MoveUp: "Yukarı taşı",
    Responses_Table_MoveUpFor: "{title} öğesini yukarı taşı",
    Responses_Table_NoColumns: "Henüz görünür soru sütunu yok.",
    Responses_Table_NoMatch: "Geçerli filtrelerle eşleşen yanıt yok.",
    Responses_Table_NothingToShow: "Gösterilecek bir şey yok",
    Responses_Table_OpenResponse: "Bu yanıtı aç",
    Responses_Table_OrderNote: "Gönderilme tarihi ve Gönderen her zaman ilk sırada gelir. Sürükleme sırası soru sütunlarına uygulanır.",
    Responses_Table_Reorder: "Yeniden sırala",
    Responses_Table_ResetColumns: "Sütunları sıfırla",
    Responses_Table_SelectResponse: "Bu yanıtı seç",
    Responses_Table_SelectedOne: "{count} yanıt seçildi",
    Responses_Table_SelectedOther: "{count} yanıt seçildi",
    Responses_Table_ShowAll: "Tümünü göster",
    Responses_Table_ShowTheseQuestions: "Bu soruları göster",
    Responses_Table_Submitted: "Gönderilme tarihi",
    Responses_Table_SubmittedBy: "Gönderen",
    Responses_Table_ToggleSelection: "Seçimi değiştir",
    Responses_Table_Unknown: "Bilinmiyor",
    Responses_Table_Untitled: "Başlıksız",
    Responses_View_AllTime: "Tüm zamanlar",
    Responses_View_AnyAnswer: "Herhangi bir yanıt",
    Responses_View_Clear: "Temizle",
    Responses_View_CopyShareLink: "Paylaşım bağlantısını kopyala",
    Responses_View_CountFiltered: "{total} yanıttan {shown} tanesi",
    Responses_View_CountOne: "{count} yanıt",
    Responses_View_CountOther: "{count} yanıt",
    Responses_View_Dashboard: "Pano",
    Responses_View_DateRange: "Tarih aralığı",
    Responses_View_EmptyBody: "Toplamaya başlamak için formu paylaşın. Yanıtlar “{list}” listesine kaydedilir ve hemen burada görünür.",
    Responses_View_EmptyTitle: "Henüz yanıt yok",
    Responses_View_ExportCsv: "CSV olarak dışa aktar",
    Responses_View_FilterByAnswer: "Yanıta göre filtrele",
    Responses_View_FilterByQuestion: "Soruya göre filtrele",
    Responses_View_FilterValue: "Filtre değeri",
    Responses_View_Last30Days: "Son 30 gün",
    Responses_View_Last7Days: "Son 7 gün",
    Responses_View_Last90Days: "Son 90 gün",
    Responses_View_LoadError: "Yanıtlar yüklenemedi. Liste sütunlarının oluşması için formu bir kez yayımlayın, sonra yeniden deneyin.",
    Responses_View_Loading: "Yanıtlar yükleniyor…",
    Responses_View_MoreActions: "Diğer yanıt eylemleri",
    Responses_View_PreviewForm: "Formu önizle",
    Responses_View_Refresh: "Yenile",
    Responses_View_ResponsesTab: "Yanıtlar ({count})",
    Responses_View_SearchPlaceholder: "Tüm yanıtlarda ara",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Bir değer seçin",
    Responses_View_Summary: "Özet",
    Responses_View_Today: "Bugün",
    Responses_View_Truncated: "Bu listede Smart Forms'un bir seferde yüklediğinden fazla yanıt var. En yeni {count} yanıt gösteriliyor; tamamı için listeyi Microsoft Lists'te açın.",
    Responses_View_TryAgain: "Yeniden dene",
    Responses_View_Untitled: "Başlıksız",
    Responses_Approval_Column: "Onay",
    Responses_Approval_ReviewerColumn: "İnceleyen",
    Responses_Approval_CommentColumn: "İnceleyen yorumu",
    Responses_Approval_Pending: "Beklemede",
    Responses_Approval_Approved: "Onaylandı",
    Responses_Approval_Rejected: "Reddedildi",
    Responses_Approval_AnyStatus: "Herhangi bir onay durumu",
    Responses_Approval_FilterLabel: "Onay durumuna göre filtrele",
    Responses_Approval_ApproveSelected: "Seçilenleri onayla",
    Responses_Approval_RejectSelected: "Seçilenleri reddet",
    Responses_Approval_BulkFailed: "{count} yanıt güncellenemedi. Tekrar deneyin.",
    Responses_Approval_Approve: "Onayla",
    Responses_Approval_Reject: "Reddet",
    Responses_Approval_Reset: "Beklemeye sıfırla",
    Responses_Approval_CommentLabel: "Yorum (isteğe bağlı)",
    Responses_Approval_ReviewedBy: "İnceleyen: {name}",
    Responses_Approval_Error: "Karar kaydedilemedi. Tekrar deneyin.",
    Responses_Dashboard_ApprovalStatus: "İnceleme bekliyor",
    Responses_Dashboard_ApprovalBreakdown: "{pending} beklemede, {approved} onaylandı, {rejected} reddedildi",
    Responses_Dashboard_TimelineCoarsened: "Tarih aralığı uzun olduğundan zaman çizelgesi daha geniş gruplandı ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Tarih aralığı çok uzun olduğundan yalnızca en son {count} dönem gösteriliyor.",
    Service_Item_DefaultTitle: "Yanıt — {date}",
    Service_Email_ApprovalSubject: "Yanıtınız {status} — {title}",
    Service_Email_ApprovalHeading: "Yanıtınız {status}",
    Service_Email_ApprovalIntro: "Bir inceleyen, \"{title}\" yanıtınızı {status} olarak işaretledi.",
    Service_Email_ApprovalCommentLabel: "İnceleyen yorumu",
    Service_Approval_Approved: "onaylandı",
    Service_Approval_Rejected: "reddedildi",
    Service_Approval_Pending: "beklemede",
    Service_Lookup_InvalidFilter: "Arama filtresi geçerli değil.",
    Service_Edit_NotAllowed: "Bu form, gönderilmiş bir yanıtın düzenlenmesine izin vermiyor.",
    Service_Edit_NotYours: "Yalnızca kendi yanıtınızı düzenleyebilirsiniz.",
    Service_Signature_AttachmentLabel: "İmza",
    PropertyPane_ListsLoadFailed: "Bu sitedeki listeler yüklenemedi.",
    PropertyPane_EnterListName: "Önce yeni liste için bir ad girin.",
    PropertyPane_CreatingList: "\"{name}\" oluşturuluyor…",
    PropertyPane_ListCreated: "\"{title}\" listesi oluşturuldu ve seçildi.",
    PropertyPane_ListAlreadyExists: "\"{name}\" adlı bir liste zaten var; yukarıdaki açılır listeden seçin.",
    PropertyPane_CreateListFailed: "Liste oluşturulamadı. Bu sitede liste oluşturma izniniz olduğunu denetleyin.",
    PropertyPane_Description: "Form yanıtlarını depolayan SharePoint listesini seçin veya yeni bir liste oluşturun. Diğer her şey (sorular, görünüm, bildirimler) doğrudan sayfada düzenlenir.",
    PropertyPane_ResponseList_GroupName: "Yanıt listesi",
    PropertyPane_ListDropdown_Label: "Yanıtları bu listeye kaydet",
    PropertyPane_ResponsesGoTo: "Yanıtlar \"{name}\" listesine gider.",
    PropertyPane_PickList: "Bir liste seçin veya aşağıdan yeni bir tane oluşturun.",
    PropertyPane_LoadingLists: "Listeler yükleniyor…",
    PropertyPane_NewListName_Label: "Veya yeni bir liste oluşturun",
    PropertyPane_NewListName_Placeholder: "Yeni liste adı",
    PropertyPane_CreateList_Button: "Liste oluştur",
    PropertyPane_Tips_GroupName: "İpuçları",
    PropertyPane_Tip_AutoSave: "Sorular ve ayarlar düzenlerken otomatik olarak kaydedilir; sayfayı kaydetmeniz veya yayımlamanız gerekmez.",
    PropertyPane_Tip_Permissions: "Yanıtlayanların yanıt listesine öğe ekleme izni olmalıdır. Biri gönderirken hata bildirirse liste izinlerini kontrol edin.",
    PropertyPane_Tip_Share: "Liste sütunlarını oluşturmak ve paylaşılabilir bir doldurma bağlantısı almak için sayfadaki \"Yanıt topla\" düğmesini kullanın.",
    App_ErrorBoundary_Title: "Smart Forms — Oluşturma hatası",
    App_ErrorBoundary_Message: "İleti:",
    App_ErrorBoundary_Stack: "Yığın:",
    App_ErrorBoundary_NoStack: "(yığın kullanılamıyor)",
    App_ErrorBoundary_ConsoleNote: "Tüm ayrıntılar tarayıcı konsoluna da yazıldı.",
    App_DefaultQuestionTitle: "Soru {number}",
    App_Error_ListMissing: "Bu form için yapılandırılan liste artık yok. Web bölümü ayarlarından başka bir liste seçin.",
    App_Error_LoadConfig: "Form yapılandırması yüklenirken bir sorun oluştu.",
    App_Error_Unable: "Form yüklenemiyor.",
    App_Publish_ConflictNotice: "\"{title}\" için farklı türde bir liste sütunu zaten var ({type}). Yeni bir sütun oluşturulabilmesi için soruyu yeniden adlandırın veya türünü eski haline getirin.",
    App_Publish_ConflictUnnamedQuestion: "bir soru",
    App_Publish_ColumnsAddedOne: "\"{list}\" listesine {count} sütun eklendi.",
    App_Publish_ColumnsAddedOther: "\"{list}\" listesine {count} sütun eklendi.",
    App_Publish_TheList: "liste",
    App_Publish_UpToDate: "Yanıt listesi zaten güncel.",
    App_Publish_Error: "Liste sütunları oluşturulamadı. Bu genellikle yanıt listesinde Listeleri Yönetme izniniz olmadığı anlamına gelir, ancak özel komut dosyasının devre dışı olduğu sitelerde de olabilir. Asıl hata için tarayıcı konsoluna bakın veya yeniden deneyin.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "SharePoint listesi üzerine gelişmiş bir form oluşturun: {count} soru türü, dallanma mantığı, dosya yüklemeleri, paylaşılabilir doldurma bağlantıları ve sonuç panosu.",
    App_Placeholder_ChooseList: "Liste seçin veya oluşturun",
    App_Placeholder_Hint: "Başlamak için sayfayı düzenleyin ve bu web bölümünü yapılandırın.",
    App_Loading: "Form yükleniyor…",
    App_OpenSettings: "Ayarları aç",
    App_Tab_Questions: "Sorular",
    App_Tab_QuestionsWithCount: "Sorular ({count})",
    App_Tab_Responses: "Yanıtlar",
    App_Tab_Responses_Title: "Yanıtlar \"{list}\" listesine kaydedilir",
    App_Templates_Start: "Şablondan başla",
    App_Settings_Title: "Form ayarları: görünüm, bildirimler, erişim",
    App_Settings_AriaLabel: "Form ayarları",
    App_Preview: "Önizleme",
    App_Preview_Close: "Önizlemeyi kapat",
    App_Preview_Hint: "Önizleme: burada gönderdiğiniz hiçbir şey kaydedilmez. Doğrulama ve dallanma, yanıtlayanlar için tam olarak böyle davranır.",
    App_Publish_GettingReady: "Hazırlanıyor…",
    App_Publish_CollectResponses: "Yanıt topla",
    App_Publish_Share: "Paylaş",
    App_Retry: "Yeniden dene",
    App_SaveError_Banner: "Son değişikliğiniz kaydedilemedi. Bağlantınızı kontrol edip yeniden deneyin.",
    App_Preflight_BlockingTitle: "Toplamadan önce bunları düzeltin",
    App_Preflight_WarningTitle: "Önce göz atmaya değer",
    App_Preflight_BlockingText: "Bunlar yayımlanan formun düzgün çalışmasını engeller.",
    App_Preflight_WarningText: "Bozuk bir şey yok, ancak bağlantıyı paylaşmadan önce bunları düzeltmek genellikle faydalıdır.",
    App_Preflight_GoTo: "Git",
    App_Preflight_CollectAnyway: "Yine de yanıt topla",
    App_Preflight_Back: "Forma geri dön",
    App_Cancel: "İptal",
    App_Done: "Bitti",
    App_Share_Title: "Formunuz paylaşıma hazır",
    App_Share_SubText: "Bu bağlantıyı formu doldurması gereken herkese gönderin.",
    App_Share_LinkAriaLabel: "Paylaşım bağlantısı",
    App_Share_Copy: "Kopyala",
    App_Share_Copied: "Kopyalandı",
    App_Share_AddItemsEmphasis: "öğe eklemek",
    App_Share_PermissionNote: "Yanıtlayanların “{title}” listesine {addItems} için izne ve bu sayfaya erişimlerinin olması gerekir. Biri göndermede hata alıyorsa neredeyse her zaman nedeni budur.",
    App_Share_PrefillNote: "Bağlantıya sütun adını ekleyerek soruları önceden yanıtlayabilirsiniz, örneğin {example}.",
    App_Templates_ReplaceWarning: "Bir şablon seçmek, şu anki soruların yerine geçer.",
    App_Templates_PickStart: "Bir başlangıç noktası seçin; sonrasında her şeyi değiştirebilirsiniz.",
    App_Templates_Empty: "Boş",
    App_Templates_QuestionCount: "{count} soru",
    App_SaveChip_SavingTitle: "Son düzenlemeniz kaydediliyor",
    App_SaveChip_Saving: "Kaydediliyor…",
    App_SaveChip_FailedTitle: "Son düzenlemeniz kaydedilemedi. Bağlantınızı kontrol edip yeniden deneyin.",
    App_SaveChip_Failed: "Kaydedilemedi",
    App_SaveChip_SavedTitle: "Tüm değişiklikler kaydedildi",
    App_SaveChip_Saved: "Kaydedildi",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Yeni yanıt — {title}",
    Service_Email_NewResponseHeading: "Yeni yanıt: {title}",
    Service_Email_NewResponseIntro: "Biri az önce bir yanıt gönderdi — {date}.",
    Service_Email_ReceiptSubject: "Yanıtınız — {title}",
    Service_Email_ReceiptHeading: "Yanıtınız için teşekkürler!",
    Service_Email_ReceiptIntro: "\"{title}\" formuna gönderdiğiniz yanıtın bir kopyası aşağıdadır.",
    App_History_Title: "Sürüm geçmişi",
    App_History_RestoredNotice: "{date} tarihinde kaydedilen sürüm geri yüklendi. İnceleyin, ardından yeni soruları yayımlamak için Yanıt topla'yı kullanın.",
    App_History_Undo: "Geri yüklemeyi geri al",
    App_Share_CopyManual: "Tarayıcınız kopyalamayı engelledi. Yukarıdaki bağlantıyı seçin ve kopyalamak için Ctrl+C (Mac'te Cmd+C) tuşlarına basın.",
    App_Share_TeamsNote: "Microsoft Teams'desiniz. Bu bağlantı SharePoint sayfasını doğrudan açar, bu nedenle alıcıların siteye erişimi olmalıdır.",
    App_Share_PrefillNotSecure: "Önceden doldurulmuş yanıtlar yalnızca kolaylık içindir: bağlantıya sahip herkes bunları değiştirebilir, bu yüzden asla bir güvenlik sınırı olarak görmeyin.",
    Designer_Section_DropHere: "Bir soruyu buraya bırakın",
    Designer_Section_DropEnd: "Bu bölümün sonuna taşımak için buraya bırakın",
    Designer_Rules_RemovedOne: "Artık uymayan 1 dallanma kuralı kaldırıldı.",
    Designer_Rules_RemovedOther: "Artık uymayan {count} dallanma kuralı kaldırıldı.",
    Designer_Settings_AllowEdit: "Yanıtlayanların yanıtlarını düzenlemesine izin ver",
    Designer_Settings_AllowEditHint: "Yanıtlayanlar gönderdiklerini yeniden açıp güncelleyebilir. Her kişi yalnızca kendi yanıtını düzenleyebilir.",
    Designer_Settings_EnableApproval: "Onay iş akışını etkinleştir",
    Designer_Settings_ApprovalNotify: "Karar verildiğinde yanıtlayana e-posta gönder",
    Designer_Settings_ApprovalHint: "Bir sonraki yayımlayışınızda yanıt listesine onay sütunları ekler. Sahipler yanıtları Yanıtlar sekmesinden onaylar veya reddeder.",
    Designer_History_Title: "Sürüm geçmişi",
    Designer_History_Intro: "Bu formun soru ve ayarlarının daha önce kaydedilmiş sürümleri. Geri yükleme, bir sürümü tasarımcıya yükler; geri alabilirsiniz ve yeni sorular yalnızca yayımladığınızda oluşturulur.",
    Designer_History_Loading: "Sürümler yükleniyor...",
    Designer_History_Empty: "Daha önceki sürüm bulunamadı. Sürüm geçmişi için \"Smart Forms Config\" listesinde sürüm oluşturmanın açık olması ve en az bir kayıtlı düzenleme gerekir.",
    Designer_History_Latest: "En son",
    Designer_History_LatestTitle: "Şu anda kullanılan sürüm budur",
    Designer_History_By: "{name} tarafından",
    Designer_History_UnknownAuthor: "Bilinmeyen yazar",
    Designer_History_VersionLabel: "sürüm {label}",
    Designer_History_Preview: "Önizleme",
    Designer_History_Restore: "Geri yükle",
    Designer_History_QuestionsOne: "1 soru",
    Designer_History_QuestionsOther: "{count} soru",
    Designer_History_LoadFailed: "Bu sürüm yüklenemedi.",
    Designer_History_ConfirmTitle: "Bu sürüm geri yüklensin mi?",
    Designer_History_ConfirmText: "Form, {date} tarihinde kaydedilen sürümle ({count} soru) değiştirilecek. Hemen ardından geri alabilirsiniz."
  };
});
