define([], function () {
  return {
    Designer_Color_Blue: "Синій",
    Designer_Color_Teal: "Бірюзовий",
    Designer_Color_Green: "Зелений",
    Designer_Color_Purple: "Фіолетовий",
    Designer_Color_Magenta: "Пурпуровий",
    Designer_Color_Red: "Червоний",
    Designer_Color_Orange: "Помаранчевий",
    Designer_Color_Gray: "Сірий",
    Designer_Settings_LayoutSinglePage: "Усі запитання на одній сторінці",
    Designer_Settings_LayoutWizard: "Один розділ на крок (майстер)",
    Designer_Settings_Title: "Параметри форми",
    Designer_Common_Apply: "Застосувати",
    Designer_Common_Cancel: "Скасувати",
    Designer_Settings_TabBasics: "Основне",
    Designer_Settings_FormTitle: "Назва форми",
    Designer_Settings_Description: "Опис",
    Designer_Settings_Layout: "Макет",
    Designer_Settings_NumberQuestions: "Нумерувати запитання",
    Designer_Settings_ShuffleQuestions: "Змішувати порядок запитань для кожного респондента",
    Designer_Settings_ShowProgressBar: "Показувати індикатор виконання",
    Designer_Settings_TabAppearance: "Вигляд",
    Designer_Settings_AccentColor: "Акцентний колір",
    Designer_Settings_CustomColorTitle: "Власний колір",
    Designer_Settings_CustomColorAria: "Власний акцентний колір",
    Designer_Settings_AccentHint: "Акцентні кольори автоматично коригуються для контрасту на темних сайтах, тому форма залишається читабельною за будь-якої теми сторінки.",
    Designer_Settings_ShowHeader: "Показувати заголовок форми",
    Designer_Settings_HeaderIcon: "Піктограма заголовка",
    Designer_Settings_TabAfterSubmit: "Після надсилання",
    Designer_Settings_SubmitButtonText: "Текст кнопки надсилання",
    Designer_Settings_SubmitPlaceholder: "Надіслати",
    Designer_Settings_ThankYouTitle: "Заголовок подяки",
    Designer_Settings_ThankYouPlaceholder: "Дякуємо!",
    Designer_Settings_ThankYouMessage: "Повідомлення подяки",
    Designer_Settings_ShowSubmitAnother: "Показувати кнопку «Надіслати ще одну відповідь»",
    Designer_Settings_TabNotifications: "Сповіщення",
    Designer_Settings_EmailEachResponseTo: "Надсилати кожну відповідь електронною поштою на адресу",
    Designer_Settings_EmailPlaceholder: "ім’я@компанія.com; команда@компанія.com",
    Designer_Settings_EmailDescription: "Користувачі вашої організації отримуватимуть кожну відповідь електронною поштою з посиланням на елемент списку",
    Designer_Settings_RespondentReceipt: "Надсилати респондентам копію їхніх відповідей електронною поштою",
    Designer_Settings_NotificationsInfo: "Сповіщення використовують власну поштову службу SharePoint, тому одержувачі мають бути користувачами вашої організації. Зовнішні адреси мовчки відкидаються.",
    Designer_Settings_TabAccess: "Доступ",
    Designer_Settings_OpenFrom: "Відкрити з",
    Designer_Settings_OpenImmediately: "Відкрити одразу",
    Designer_Settings_CloseAfter: "Закрити після",
    Designer_Settings_NeverClose: "Ніколи не закривати",
    Designer_Settings_ClearDates: "Очистити дати",
    Designer_Settings_DatesInverted: "Дата закриття збігається з датою відкриття або передує їй, тому форма ніколи не прийматиме відповіді.",
    Designer_Settings_MaxResponses: "Зупинити після такої кількості відповідей",
    Designer_Settings_NoLimit: "Без обмежень",
    Designer_Settings_OneResponsePerPerson: "Дозволити лише одну відповідь від особи",
    Designer_Settings_AllowSaveDraft: "Дозволити респондентам зберігати чернетку й завершувати пізніше",
    Designer_Settings_ClosedMessage: "Повідомлення, що відображається, коли форму закрито",
    Designer_Settings_ClosedMessagePlaceholder: "Ця форма більше не приймає відповіді.",
    Designer_Settings_AccessInfo: "Ці обмеження забезпечує форма, а не SharePoint. Будь-хто з дозволом додавати елементи до списку відповідей однаково може додати елемент безпосередньо через список.",
    Designer_Field_StyleInfo: "Інформація (акцент)",
    Designer_Field_StyleSuccess: "Успіх (зелений)",
    Designer_Field_StyleWarning: "Попередження (бурштиновий)",
    Designer_Field_StylePlain: "Звичайний текст",
    Designer_Field_StyleDivider: "Роздільна лінія",
    Designer_Field_IconStars: "Зірки",
    Designer_Field_IconHearts: "Серця",
    Designer_Field_IconThumbs: "Великий палець угору",
    Designer_Field_FormatPlain: "Звичайне число",
    Designer_Field_FormatCurrency: "Валюта",
    Designer_Field_FormatPercent: "Відсоток",
    Designer_Field_UntitledQuestion: "Запитання без назви",
    Designer_Field_DeletedQuestion: "видалене запитання",
    Designer_Rule_Unary: "«{name}» {operator}",
    Designer_Rule_Between: "«{name}» {operator} {value} і {value2}",
    Designer_Rule_Binary: "«{name}» {operator} «{value}»",
    Designer_Rule_JoinAny: "АБО",
    Designer_Rule_JoinAll: "І",
    Designer_Rule_Preview: "Відображається, коли {conditions}.",
    Designer_Field_Yes: "Так",
    Designer_Field_No: "Ні",
    Designer_Field_When: "Коли",
    Designer_Field_SelectValue: "Виберіть значення",
    Designer_Field_DateValuePlaceholder: "РРРР-ММ-ДД або \"today\"",
    Designer_Field_ValuePlaceholder: "Значення",
    Designer_Field_UpperBound: "Верхня межа",
    Designer_Field_RemoveCondition: "Видалити цю умову",
    Designer_Field_FormulaInvalid: "Цю формулу неможливо обчислити. Перевірте дужки та оператори.",
    Designer_Field_FormulaMissing: "Ці запитання не існують: {names}.",
    Designer_Field_FormulaPreview: "Якщо всі вхідні значення дорівнюють 10, відображається {value}.",
    Designer_Field_HintYesNo: "Використовуйте \"yes\" або \"no\"",
    Designer_Field_HintMultiDefault: "Розділяйте кілька типових значень символом ;",
    Designer_Field_HintSingleDefault: "Має збігатися з одним із варіантів",
    Designer_Field_HintDate: "Використовуйте \"today\" або дату, наприклад 2026-03-01",
    Designer_Field_HintTime: "Використовуйте \"now\" або час, наприклад 09:30",
    Designer_Field_QuestionSettings: "Параметри запитання",
    Designer_Field_Appearance: "Вигляд",
    Designer_Field_Style: "Стиль",
    Designer_Field_ImageUrl: "URL-адреса зображення (необов’язково)",
    Designer_Field_Content: "Вміст",
    Designer_Field_BasicFormatting: "Дозволено базове форматування: напівжирний, курсив, списки та посилання.",
    Designer_Field_TabOptions: "Варіанти",
    Designer_Field_TabBranching: "Розгалуження",
    Designer_Field_BranchingNeedsQuestion: "Спершу додайте ще одне запитання: для розгалуження потрібна залежність.",
    Designer_Field_BranchingToggle: "Показувати це запитання, лише коли збігаються інші відповіді",
    Designer_Field_Match: "Збіг",
    Designer_Field_MatchAll: "усіх цих",
    Designer_Field_MatchAny: "будь-якої з цих",
    Designer_Field_AddCondition: "Додати умову",
    Designer_Field_TabValidation: "Перевірка",
    Designer_Field_HelpText: "Довідковий текст",
    Designer_Field_HelpTextPlaceholder: "Відображається під підписом запитання",
    Designer_Field_CheckboxLabel: "Підпис прапорця",
    Designer_Field_Placeholder: "Заповнювач",
    Designer_Field_DefaultAnswer: "Типова відповідь",
    Designer_Field_RequiredMessage: "Власне повідомлення про обов’язкове поле",
    Designer_Field_RequiredMessagePlaceholder: "Поле «{title}» обов’язкове",
    Designer_Field_ThisQuestion: "Це запитання",
    Designer_Field_RequiredMessageDescription: "Відображається замість стандартного повідомлення, якщо на це запитання не відповіли",
    Designer_Field_ReadOnly: "Лише читання (відповідь може надходити лише з попередньо заповненого посилання)",
    Designer_Field_ValidationRules: "Правила перевірки",
    Designer_Field_MaxLength: "Максимальна довжина",
    Designer_Field_Pattern: "Має відповідати цьому шаблону",
    Designer_Field_PatternDescription: "Регулярний вираз. Залиште порожнім, щоб не перевіряти шаблон.",
    Designer_Field_PatternMessage: "Повідомлення, якщо шаблон не збігається",
    Designer_Field_PatternMessagePlaceholder: "Ця відповідь має неочікуваний формат",
    Designer_Field_Format: "Формат",
    Designer_Field_UnitSuffix: "Одиниця, що відображається після значення",
    Designer_Field_UnitSuffixPlaceholder: "кг, год, шт…",
    Designer_Field_Minimum: "Мінімум",
    Designer_Field_Maximum: "Максимум",
    Designer_Field_Decimals: "Десяткові знаки",
    Designer_Field_Formula: "Формула",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Посилайтеся на інші запитання за їхнім текстом у фігурних дужках. Підтримуються + - * / ( ) і round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Доступні запитання: {questions}",
    Designer_Field_NoneYet: "поки немає",
    Designer_Field_Step: "Крок",
    Designer_Field_From: "Від",
    Designer_Field_To: "До",
    Designer_Field_LowLabel: "Підпис на нижньому краї",
    Designer_Field_LowLabelPlaceholder: "Зовсім неймовірно",
    Designer_Field_HighLabel: "Підпис на верхньому краї",
    Designer_Field_HighLabelPlaceholder: "Надзвичайно ймовірно",
    Designer_Field_SummarizeAs: "Підсумувати як",
    Designer_Field_SummarizeAverage: "Середнє значення й розподіл",
    Designer_Field_SummarizeNps: "Індекс споживчої лояльності NPS (потрібна шкала 0–10)",
    Designer_Field_NpsWarning: "Індекс NPS має сенс лише на шкалі 0–10. Установіть «Від» 0, а «До» 10.",
    Designer_Field_NumberOfIcons: "Кількість піктограм",
    Designer_Field_Icon: "Піктограма",
    Designer_Field_AllowHalf: "Дозволити половинні значення",
    Designer_Field_ShowOptionsAs: "Показувати варіанти як",
    Designer_Field_DisplayButtons: "Вбудовані кнопки",
    Designer_Field_DisplayDropdown: "Спадний список",
    Designer_Field_DisplayAutomatic: "Автоматично (вбудовано до 6 варіантів)",
    Designer_Field_AllowOther: "Додати варіант «Інше» з можливістю введення",
    Designer_Field_OtherLabel: "Підпис варіанта «Інше»",
    Designer_Field_OtherPlaceholder: "Інше",
    Designer_Field_ShuffleOptions: "Змішувати порядок варіантів для кожного респондента",
    Designer_Field_MinSelections: "Мінімум виборів",
    Designer_Field_MaxSelections: "Максимум виборів",
    Designer_Field_SourceList: "Вихідний список",
    Designer_Field_ChooseList: "Виберіть список",
    Designer_Field_LookupColumn: "Стовпець, з якого читати варіанти",
    Designer_Field_ChooseColumn: "Виберіть стовпець",
    Designer_Field_ChooseListFirst: "Спершу виберіть список",
    Designer_Field_LookupFilter: "Фільтр (необов’язково)",
    Designer_Field_LookupFilterDescription: "Фільтр OData, що обмежує, які елементи джерела стають варіантами",
    Designer_Field_LookupInfo: "Відповіді зберігають текст варіанта, а не посилання на вихідний елемент, тому вони залишаються читабельними, навіть якщо вихідний список пізніше зміниться.",
    Designer_Field_ConsentText: "Умови, що відображаються над прапорцем",
    Designer_Field_AllowMultiplePeople: "Дозволити кількох осіб",
    Designer_Field_AllowGroups: "Дозволити також групи",
    Designer_Field_IncludeTime: "Додати час доби",
    Designer_Field_TimeStep: "Крок часу (хвилини)",
    Designer_Field_MaxFiles: "Максимум файлів",
    Designer_Field_MaxFileSize: "Макс. розмір кожного (МБ)",
    Designer_Field_AcceptedTypes: "Допустимі типи файлів",
    Designer_Field_AcceptedTypesDescription: "Розширення через кому. Залиште порожнім, щоб приймати все, що дозволяє SharePoint.",
    Designer_Field_FilesInfo: "Файли зберігаються як вкладення елемента відповіді. SharePoint блокує деякі розширення (наприклад, .exe) незалежно від того, що ви дозволите тут.",
    Designer_Field_Rows: "Рядки",
    Designer_Field_ProvisionedNote: "Це запитання вже має стовпець списку ({name}). Параметри, що змінюють тип стовпця, заблоковано; якщо потрібен інший тип, дублюйте запитання.",
    Designer_Category_Text: "Текст",
    Designer_Category_Choice: "Вибір",
    Designer_Category_Scales: "Шкали",
    Designer_Category_Date: "Дата",
    Designer_Category_People: "Люди",
    Designer_Category_Advanced: "Додатково",
    Designer_Category_Layout: "Макет",
    Designer_Menu_CommonPresets: "Поширені шаблони",
    Designer_Menu_AllTypes: "Усі типи запитань",
    Designer_Menu_ChangeType: "Змінити тип",
    Designer_Menu_TypeLockedTitle: "Стовпець списку вже існує, тому тип заблоковано. Щоб змінити його, дублюйте запитання.",
    Designer_Menu_MoreSettings: "Розгалуження, перевірка тощо",
    Designer_Menu_InsertBelow: "Вставити запитання нижче",
    Designer_Card_Duplicate: "Дублювати",
    Designer_Card_DeleteQuestion: "Видалити запитання",
    Designer_Outline_Aria: "Структура запитань",
    Designer_Outline_QuestionCountOne: "{count} запитання",
    Designer_Outline_QuestionCountOther: "{count} запитань",
    Designer_Outline_IssuesTitle: "Питань для перегляду: {count}",
    Designer_Outline_Find: "Знайти запитання",
    Designer_Outline_Empty: "Запитань поки немає.",
    Designer_Section_DefaultTitle: "Розділ {number}",
    Designer_Card_Question: "Запитання",
    Designer_Card_BranchingTitle: "Це запитання відображається, лише коли спрацьовує правило розгалуження",
    Designer_Card_BranchingChip: "Розгалуження",
    Designer_Card_LiveTitle: "Стовпець списку існує, тому тип заблоковано",
    Designer_Card_LiveChip: "Активне",
    Designer_Card_CheckChip: "Перевірити",
    Designer_Option_Placeholder: "Варіант {number}",
    Designer_Option_LabelAria: "Підпис варіанта {number}",
    Designer_Option_ImageUrl: "URL-адреса зображення",
    Designer_Option_ImageUrlAria: "URL-адреса зображення варіанта {number}",
    Designer_Option_Remove: "Видалити варіант",
    Designer_Option_RemoveAria: "Видалити варіант {number}",
    Designer_Option_Add: "Додати варіант",
    Designer_Option_OtherHint: "Респонденти також можуть ввести власну відповідь із підписом «{label}».",
    Designer_Option_OtherFallback: "Інше",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Видалити",
    Designer_Grid_RemoveAria: "Видалити: {label} {number}",
    Designer_Grid_Statements: "Твердження",
    Designer_Grid_Scale: "Шкала",
    Designer_Grid_AddStatement: "Додати твердження",
    Designer_Grid_AddScale: "Додати шкалу",
    Designer_Width_Full: "Повна ширина",
    Designer_Width_Half: "Половина ширини",
    Designer_Width_Third: "Одна третина ширини",
    Designer_Width_Aria: "Ширина запитання",
    Designer_Card_BlockLabelPlaceholder: "Підпис блока (респондентам не відображається)",
    Designer_Card_QuestionText: "Текст запитання",
    Designer_Card_MoveUp: "Перемістити вгору",
    Designer_Card_MoveQuestionUp: "Перемістити запитання вгору",
    Designer_Card_MoveDown: "Перемістити вниз",
    Designer_Card_MoveQuestionDown: "Перемістити запитання вниз",
    Designer_Card_DuplicateQuestion: "Дублювати запитання",
    Designer_Card_MultipleAnswers: "Кілька відповідей",
    Designer_Card_Required: "Обов’язкове",
    Designer_Card_MoreOptions: "Додаткові параметри",
    Designer_Card_MoreOptionsAria: "Додаткові параметри для цього запитання",
    Designer_Canvas_FormTitle: "Назва форми",
    Designer_Canvas_DescriptionPlaceholder: "Додайте опис (необов’язково)",
    Designer_Canvas_DescriptionAria: "Опис форми",
    Designer_Canvas_EmptyTitle: "Додайте перше запитання",
    Designer_Canvas_EmptyBody: "Виберіть тип запитання, щоб почати. Ви можете змінювати порядок запитань перетягуванням і додавати розгалуження, щоб користувачі бачили лише те, що їх стосується.",
    Designer_Section_Chip: "Розділ {number} із {total}",
    Designer_Section_TitlePlaceholder: "Назва розділу",
    Designer_Section_TitleAria: "Назва розділу {number}",
    Designer_Section_DescriptionPlaceholder: "Опис (необов’язково)",
    Designer_Section_DescriptionAria: "Опис розділу {number}",
    Designer_Section_MoveUp: "Перемістити розділ угору",
    Designer_Section_MoveDown: "Перемістити розділ униз",
    Designer_Section_Delete: "Видалити розділ",
    Designer_Card_DragToReorder: "Перетягніть, щоб змінити порядок",
    Designer_Card_ReorderAria: "Змінити порядок: {title}",
    Designer_Card_ReorderFallback: "запитання",
    Designer_Canvas_AddNew: "Додати",
    Designer_Canvas_AddSection: "Додати розділ",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Вулиця, будинок",
    Form_Address_Street2Placeholder: "Квартира, офіс тощо (необов’язково)",
    Form_Address_CityPlaceholder: "Місто",
    Form_Address_StatePlaceholder: "Область / район",
    Form_Address_PostalCodePlaceholder: "Поштовий індекс",
    Form_Address_CountryPlaceholder: "Країна",
    Form_Address_StreetAria: "вулиця, будинок",
    Form_Address_Street2Aria: "адресний рядок 2",
    Form_Address_CityAria: "місто",
    Form_Address_StateAria: "область або район",
    Form_Address_PostalCodeAria: "поштовий індекс",
    Form_Address_CountryAria: "країна",
    Form_Consent_DefaultLabel: "Я погоджуюся",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "Відповіді в рядках: {answered} із {total}",
    Form_Lookup_LoadError: "Не вдалося завантажити варіанти для цього запитання.",
    Form_Lookup_Loading: "Завантаження варіантів…",
    Form_Lookup_SelectOptionsPlaceholder: "Виберіть варіанти",
    Form_Lookup_SelectOptionPlaceholder: "Виберіть варіант",
    Form_Person_Placeholder: "Почніть вводити ім’я…",
    Form_Person_SuggestedPeopleAndGroups: "Запропоновані люди та групи",
    Form_Person_SuggestedPeople: "Запропоновані люди",
    Form_Person_NoPeopleOrGroups: "Людей або груп не знайдено",
    Form_Person_NoPeople: "Людей не знайдено",
    Form_Person_Searching: "Пошук…",
    Form_Ranking_Moved: "Елемент «{item}» переміщено на позицію {position} із {total}",
    Form_Ranking_MoveUp: "Перемістити вгору",
    Form_Ranking_MoveDown: "Перемістити вниз",
    Form_Ranking_MoveItemUpAria: "Перемістити «{item}» вгору",
    Form_Ranking_MoveItemDownAria: "Перемістити «{item}» вниз",
    Form_Rating_ValueText: "{value} із {max}",
    Form_Rating_NotRated: "Без оцінки",
    Form_Rating_Clear: "Скинути оцінку",
    Form_RichText_Bold: "Напівжирний",
    Form_RichText_Italic: "Курсив",
    Form_RichText_Underline: "Підкреслений",
    Form_RichText_BulletedList: "Маркований список",
    Form_RichText_NumberedList: "Нумерований список",
    Form_RichText_ClearFormatting: "Очистити форматування",
    Form_RichText_ToolbarAria: "Форматування тексту",
    Form_File_SizeBytes: "{size} Б",
    Form_File_SizeKb: "{size} КБ",
    Form_File_SizeMb: "{size} МБ",
    Form_File_SkippedLimit: "Файл «{name}» пропущено: ліміт становить {limit}.",
    Form_File_TypeNotAccepted: "Файл «{name}» має недопустимий тип.",
    Form_File_TooLarge: "Файл «{name}» більший за {size} МБ.",
    Form_File_AlreadyAttached: "Файл «{name}» уже прикріплено.",
    Form_File_ReadError: "Не вдалося прочитати один із файлів. Спробуйте прикріпити його ще раз.",
    Form_File_HintMaxSize: "до {size} МБ кожен",
    Form_File_HintOneFile: "1 файл",
    Form_File_HintMaxFiles: "макс. файлів: {count}",
    Form_File_Reading: "Читання файлів…",
    Form_File_DropPrompt: "Перетягніть файли сюди або натисніть, щоб вибрати",
    Form_File_Remove: "Видалити {name}",
    Form_Signature_Alt: "Підпис",
    Form_Signature_AriaSigned: "{label} — підписано",
    Form_Signature_AriaEmpty: "{label} — порожньо",
    Form_Signature_Clear: "Очистити",
    Form_Signature_Signed: "Підписано",
    Form_Signature_Prompt: "Розпишіться вище мишею, пером або пальцем",
    Form_Time_Placeholder: "Виберіть час",
    Form_Field_DatePlaceholder: "Виберіть дату",
    Form_Field_TimeAriaWithLabel: "{label} — час",
    Form_Field_TimeAria: "Час",
    Form_Field_OtherDefault: "Інше",
    Form_Field_SelectOptionsPlaceholder: "Виберіть варіанти",
    Form_Field_PleaseSpecify: "Уточніть",
    Form_Field_OtherSpecifyAria: "{label} — уточніть",
    Form_Field_SelectOptionPlaceholder: "Виберіть варіант",
    Form_Field_Yes: "Так",
    Form_Field_No: "Ні",
    Form_Field_SliderHint: "Щоб відповісти, перетягніть повзунок",
    Form_Field_WebAddressAriaWithLabel: "{label} — вебадреса",
    Form_Field_WebAddressAria: "Вебадреса",
    Form_Field_DisplayTextPlaceholder: "Текст для відображення (необов’язково)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — текст для відображення",
    Form_Field_DisplayTextAria: "Текст для відображення",
    Form_Field_ChooseBetween: "Виберіть від {min} до {max}",
    Form_Field_ChooseAtLeast: "Виберіть щонайменше {min}",
    Form_Field_ChooseUpTo: "Виберіть не більше {max}",
    Form_Field_SelectedCount: "Вибрано: {count}",
    Form_Field_RequiredAria: "(обов’язково)",
    Form_Submit_SaveError: "Не вдалося зберегти вашу відповідь. Переконайтеся, що форму опубліковано з конструктора та що у вас є дозвіл додавати елементи до списку відповідей.",
    Form_Empty_Message: "У цій формі поки немає запитань. Власник форми може додати їх на вкладці «Запитання».",
    Form_Checking: "Перевірка форми…",
    Form_Closed_NotYetOpen: "Ще не відкрито",
    Form_Closed_AlreadyAnswered: "Уже відповіли",
    Form_Closed_Title: "Форму закрито",
    Form_Confirmation_PreviewNotice: "Це був попередній перегляд: у список відповідей нічого не збережено.",
    Form_Confirmation_PreviewAgain: "Переглянути ще раз",
    Form_Confirmation_SubmitAnother: "Надіслати ще одну відповідь",
    Form_Wizard_StepFallback: "Крок {step}",
    Form_Wizard_StepsAria: "Кроки форми",
    Form_Wizard_StepOf: "Крок {step} із {total}",
    Form_ErrorSummary_Title: "Перевірте відповіді (кількість: {count}):",
    Form_ErrorSummary_UntitledQuestion: "Запитання без назви",
    Form_ErrorSummary_Question: "Запитання",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Назад",
    Form_Nav_Next: "Далі",
    Form_Draft_Saving: "Збереження…",
    Form_Draft_Saved: "Чернетку збережено",
    Form_Draft_SaveAndFinishLater: "Зберегти й завершити пізніше",
    Form_Draft_NotSaved: "Чернетку не збережено",
    Form_Submit_Preview: "Надіслати (перегляд)",
    Form_Submit_Button: "Надіслати",
    Form_Response_NoAnswer: "Немає відповіді",
    Form_Signature_TypeLabel: "Введіть своє повне ім’я",
    Form_Signature_TypeInstead: "Ввести ім’я замість цього",
    Form_Signature_DrawInstead: "Намалювати замість цього",
    Form_Edit_Button: "Редагувати попередню відповідь",
    Form_Edit_Available: "Ви вже надіслали відповідь. Можна відредагувати її замість надсилання нової.",
    Form_Edit_Banner: "Ви редагуєте свою попередню відповідь.",
    Form_Edit_Save: "Оновити відповідь",
    Form_Edit_UpdatedTitle: "Відповідь оновлено",
    Form_Edit_UpdatedMessage: "Ваші зміни збережено.",
    Form_Edit_LoadError: "Не вдалося завантажити вашу попередню відповідь. Повторіть спробу.",
    Form_Draft_MissingFiles: "Приєднайте повторно: {names}. Ці файли не вдалося відновити.",
    Form_Attachments_Failed: "Ваші відповіді збережено, але ці вкладення не вдалося передати: {names}. Повторіть спробу або зверніться до власника форми.",
    Logic_ThisQuestion: "Це запитання",
    Logic_Required: "Поле «{label}» обов’язкове",
    Logic_RequiredConsent: "Установіть прапорець, щоб продовжити",
    Logic_RequiredFile: "Приєднайте принаймні один файл",
    Logic_RequiredSignature: "Додайте свій підпис",
    Logic_RequiredLikert: "Дайте відповідь у кожному рядку",
    Logic_InvalidEmail: "Введіть припустиму адресу електронної пошти",
    Logic_InvalidPhone: "Введіть припустимий номер телефону",
    Logic_InvalidUrl: "Введіть припустиму веб-адресу, що починається з http:// або https://",
    Logic_MinValue: "Значення має бути не менше {value}",
    Logic_MaxValue: "Значення має бути не більше {value}",
    Logic_MaxLength: "Максимальна довжина — {max} символів",
    Logic_ChooseAtLeastOne: "Виберіть принаймні {count} варіант",
    Logic_ChooseAtLeastMany: "Виберіть принаймні варіантів: {count}",
    Logic_ChooseAtMostOne: "Виберіть не більше {count} варіанта",
    Logic_ChooseAtMostMany: "Виберіть не більше варіантів: {count}",
    Logic_LikertRemaining: "Дайте відповідь у кожному рядку (залишилось: {count})",
    Logic_MaxFilesOne: "Приєднайте не більше {count} файлу",
    Logic_MaxFilesMany: "Приєднайте не більше файлів: {count}",
    Logic_FileTooLarge: "Файл «{name}» більший за {size} МБ",
    Logic_FileTypeNotAccepted: "Файл «{name}» має неприйнятний тип ({types})",
    Logic_AddressRequired: "Введіть принаймні вулицю та місто",
    Logic_PatternDefault: "Відповідь має неочікуваний формат",
    Logic_Yes: "Так",
    Logic_No: "Ні",
    Logic_Agreed: "Погоджено",
    Logic_NotAgreed: "Не погоджено",
    Logic_Signed: "Підписано",
    Logic_NoAnswer: "(немає відповіді)",
    Logic_Unknown: "(невідомо)",
    Logic_OtherSlice: "Інше ({count})",
    Logic_CsvResponseId: "Ідентифікатор відповіді",
    Logic_CsvSubmitted: "Надіслано",
    Logic_CsvSubmittedBy: "Надіслав(-ла)",
    Logic_EmailQuestion: "Запитання",
    Logic_EmailViewItem: "Переглянути в Microsoft Lists",
    Logic_EmailFooter: "Автоматично надіслано Smart Forms.",
    Logic_ClosedDefault: "Ця форма більше не приймає відповідей.",
    Logic_NotYetOpen: "Ця форма відкриється {date}.",
    Logic_AlreadyResponded: "Ви вже відповіли на цю форму. Дякуємо!",
    Logic_UntitledQuestion: "Запитання без назви",
    Logic_Issue_NoQuestions: "Додайте принаймні одне запитання, перш ніж збирати відповіді.",
    Logic_Issue_NoTitle: "Запитання не має тексту — після публікації йому буде автоматично надано назву.",
    Logic_Issue_DuplicateTitle: "Текст «{label}» збігається з іншим запитанням, через що результати важче читати.",
    Logic_Issue_NeedTwoOptions: "«{label}» потребує принаймні двох варіантів.",
    Logic_Issue_ImageNoImage: "У «{label}» є варіанти без зображення — вони відображатимуться як текстові плитки.",
    Logic_Issue_LikertNeedRow: "«{label}» потребує принаймні одного рядка.",
    Logic_Issue_LikertNeedColumns: "«{label}» потребує принаймні двох стовпців шкали.",
    Logic_Issue_NoLookupList: "Для «{label}» не вибрано список-джерело.",
    Logic_Issue_NoFormula: "«{label}» не має формули.",
    Logic_Issue_BadFormula: "«{label}» має формулу, яку неможливо обчислити. Перевірте дужки та оператори.",
    Logic_Issue_MissingRefs: "«{label}» посилається на неіснуючі запитання: {names}.",
    Logic_Issue_BadPattern: "«{label}» має недійсний шаблон перевірки.",
    Logic_Issue_BrokenRule: "«{label}» має правило розгалуження, що вказує на видалене запитання.",
    Logic_Issue_SelfRule: "«{label}» має правило розгалуження, що посилається на нього самого.",
    Logic_Issue_RuleMismatch: "«{label}» має правило розгалуження, яке більше не відповідає запитанню, від якого залежить.",
    Logic_Issue_RequiredReadOnly: "«{label}» одночасно обов’язкове й лише для читання, тому відповісти можна лише за попередньо заповненим посиланням.",
    Logic_Issue_EmptySection: "Розділ не містить запитань і буде пропущений.",
    Logic_Issue_CloseBeforeOpen: "Дата закриття збігається з датою відкриття або передує їй, тому форма ніколи не прийматиме відповідей.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Електронні листи про затвердження ввімкнено, але крок затвердження вимкнено.",
    Logic_Op_equals: "дорівнює",
    Logic_Op_notEquals: "не дорівнює",
    Logic_Op_contains: "містить",
    Logic_Op_notContains: "не містить",
    Logic_Op_notEmpty: "має відповідь",
    Logic_Op_empty: "не має відповіді",
    Logic_Op_greaterThan: "більше за",
    Logic_Op_greaterOrEqual: "щонайменше",
    Logic_Op_lessThan: "менше за",
    Logic_Op_lessOrEqual: "щонайбільше",
    Logic_Op_between: "між",
    Logic_Op_before: "раніше за",
    Logic_Op_after: "пізніше за",
    Logic_Type_Text: "Коротка відповідь",
    Logic_TypeDesc_Text: "Один рядок тексту",
    Logic_Category_Text: "Текст",
    Logic_Type_MultilineText: "Розгорнута відповідь",
    Logic_TypeDesc_MultilineText: "Кілька рядків звичайного тексту",
    Logic_Type_RichText: "Форматований текст",
    Logic_TypeDesc_RichText: "Напівжирний шрифт, списки та посилання",
    Logic_Type_Choice: "Вибір",
    Logic_TypeDesc_Choice: "Виберіть зі списку варіантів",
    Logic_Category_Choice: "Вибір",
    Logic_Type_ImageChoice: "Вибір зображення",
    Logic_TypeDesc_ImageChoice: "Виберіть серед плиток із зображеннями",
    Logic_Type_Lookup: "Підстановка зі списку",
    Logic_TypeDesc_Lookup: "Варіанти зчитуються наживо з іншого списку SharePoint",
    Logic_Type_YesNo: "Так / Ні",
    Logic_TypeDesc_YesNo: "Простий перемикач увімкнено/вимкнено",
    Logic_Type_Consent: "Згода",
    Logic_TypeDesc_Consent: "Прапорець, який респондент має встановити, щоб продовжити",
    Logic_Type_Ranking: "Ранжування",
    Logic_TypeDesc_Ranking: "Перетягніть варіанти в порядку переваги",
    Logic_Type_Rating: "Оцінка",
    Logic_TypeDesc_Rating: "Зірки, серця або великі пальці",
    Logic_Category_Scales: "Шкали",
    Logic_Type_Scale: "Шкала думок",
    Logic_TypeDesc_Scale: "Нумерована шкала з підписаними краями",
    Logic_Type_Slider: "Повзунок",
    Logic_TypeDesc_Slider: "Значення на шкалі з повзунком",
    Logic_Type_Likert: "Таблиця Лайкерта",
    Logic_TypeDesc_Likert: "Оцініть кілька тверджень за однією спільною шкалою",
    Logic_Type_Number: "Число",
    Logic_TypeDesc_Number: "Звичайне, грошове або відсоток",
    Logic_Category_Advanced: "Додатково",
    Logic_Type_Calculated: "Обчислюване",
    Logic_TypeDesc_Calculated: "Сума лише для читання, обчислена з інших відповідей",
    Logic_Type_Date: "Дата",
    Logic_TypeDesc_Date: "Календарна дата, за потреби з часом",
    Logic_Category_Date: "Дата",
    Logic_Type_Time: "Час",
    Logic_TypeDesc_Time: "Лише час доби",
    Logic_Type_Person: "Особа",
    Logic_TypeDesc_Person: "Виберіть особу з організації",
    Logic_Category_People: "Люди",
    Logic_Type_Email: "Електронна пошта",
    Logic_TypeDesc_Email: "Адреса електронної пошти з перевіркою",
    Logic_Type_Phone: "Телефон",
    Logic_TypeDesc_Phone: "Номер телефону з перевіркою",
    Logic_Type_Address: "Адреса",
    Logic_TypeDesc_Address: "Вулиця, місто, поштовий індекс і країна",
    Logic_Type_Hyperlink: "Посилання",
    Logic_TypeDesc_Hyperlink: "Веб-адреса",
    Logic_Type_FileUpload: "Передавання файлу",
    Logic_TypeDesc_FileUpload: "Приєднайте до відповіді один або кілька файлів",
    Logic_Type_Signature: "Підпис",
    Logic_TypeDesc_Signature: "Підпишіться мишею, пером або пальцем",
    Logic_Type_Content: "Текстовий блок",
    Logic_TypeDesc_Content: "Інструкції або зображення — відповідей не збирає",
    Logic_Category_Layout: "Макет",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Наскільки ймовірно, що ви порекомендуєте…",
    Logic_Preset_satisfaction: "Задоволеність (1–5)",
    Logic_PresetDesc_satisfaction: "Від дуже незадоволений до дуже задоволений",
    Logic_Preset_currency: "Грошова сума",
    Logic_PresetDesc_currency: "Сума грошей",
    Logic_Preset_percent: "Відсоток",
    Logic_PresetDesc_percent: "Значення у відсотках",
    Logic_Template_blank_Name: "Порожня форма",
    Logic_Template_blank_Description: "Почати з нуля",
    Logic_Template_feedback_Name: "Відгуки клієнтів",
    Logic_Template_feedback_Description: "NPS, оцінки та відкриті коментарі",
    Logic_Template_event_Name: "Реєстрація на захід",
    Logic_Template_event_Description: "Дані учасників, сесії та дієтичні потреби",
    Logic_Template_itrequest_Name: "Запит на ІТ-послугу",
    Logic_Template_itrequest_Description: "Запити за категоріями з пріоритетом і вкладеннями",
    Logic_Template_expense_Name: "Звіт про витрати",
    Logic_Template_expense_Description: "Позиції, квитанції та обчислювана сума",
    Logic_Template_pulse_Name: "Опитування настрою працівників",
    Logic_Template_pulse_Description: "Таблиця Лайкерта, шкала залученості та примітка про анонімність",
    Logic_Template_safety_Name: "Перевірка безпеки",
    Logic_Template_safety_Description: "Контрольний список, фото та підпис",
    Logic_Template_booking_Name: "Бронювання кімнати або ресурсу",
    Logic_Template_booking_Description: "Вибір ресурсу через підстановку з часовим інтервалом",
    Charts_ColumnChartAria: "Стовпчаста діаграма з категоріями: {count}",
    Charts_DonutChartAria: "Кільцева діаграма з категоріями: {count}",
    Charts_NoAnswers: "Відповідей поки немає.",
    Charts_NoResponses: "Відповідей поки немає.",
    Charts_Responses: "Відповіді",
    Charts_ResponsesOverTime: "Відповіді за часом",
    Responses_Chart_Answer: "Відповідь",
    Responses_Chart_Average: "Середнє",
    Responses_Chart_AverageOf: "Середнє з {count}",
    Responses_Chart_AveragePosition: "Середня позиція",
    Responses_Chart_AverageRange: "Середнє (1–{max})",
    Responses_Chart_AvgValue: "сер. {value}",
    Responses_Chart_Detractors: "Критики (0–6)",
    Responses_Chart_Max: "Макс.",
    Responses_Chart_Maximum: "Максимум",
    Responses_Chart_Median: "Медіана",
    Responses_Chart_MentionOne: "{count} згадка",
    Responses_Chart_MentionOther: "{count} згадок",
    Responses_Chart_Min: "Мін.",
    Responses_Chart_Minimum: "Мінімум",
    Responses_Chart_NoAnswers: "Відповідей поки немає.",
    Responses_Chart_NoNumeric: "Числових відповідей поки немає.",
    Responses_Chart_NoRankings: "Рейтингів поки немає.",
    Responses_Chart_NoScores: "Балів поки немає.",
    Responses_Chart_NotEnoughText: "Поки недостатньо тексту для підсумку.",
    Responses_Chart_NpsScore: "Індекс NPS",
    Responses_Chart_Option: "Варіант",
    Responses_Chart_Passives: "Пасивні (7–8)",
    Responses_Chart_Promoters: "Промоутери (9–10)",
    Responses_Chart_ResponseOne: "відповідь",
    Responses_Chart_ResponseOther: "відповідей",
    Responses_Chart_Responses: "Відповіді",
    Responses_Chart_ShowingAnswers: "Показано {shown} із {total} відповідей.",
    Responses_Chart_Statement: "Твердження",
    Responses_Chart_Statistic: "Показник",
    Responses_Chart_StdDev: "Станд. відх.",
    Responses_Chart_StdDeviation: "Стандартне відхилення",
    Responses_Chart_Total: "Разом",
    Responses_Chart_Value: "Значення",
    Responses_Dashboard_AllHidden: "Усі запитання приховано з панелі. Скористайтеся пунктом «Показати приховані запитання», щоб повернути їх.",
    Responses_Dashboard_AnsweredOf: "Відповіли на {answered} із {total}",
    Responses_Dashboard_AnsweredOfPinned: "Відповіли на {answered} із {total} · закріплено",
    Responses_Dashboard_AveragedAcrossResponses: "Усереднено за відповідями",
    Responses_Dashboard_ByDay: "За днями",
    Responses_Dashboard_ByMonth: "За місяцями",
    Responses_Dashboard_ByWeek: "За тижнями",
    Responses_Dashboard_ChartAuto: "Автоматично",
    Responses_Dashboard_ChartBars: "Смуги",
    Responses_Dashboard_ChartColumns: "Стовпці",
    Responses_Dashboard_ChartDonut: "Кільцева",
    Responses_Dashboard_ChartGauge: "Шкала",
    Responses_Dashboard_ChartHistogram: "Гістограма",
    Responses_Dashboard_ChartOptions: "Параметри діаграми",
    Responses_Dashboard_ChartOptionsFor: "Параметри діаграми: {title}",
    Responses_Dashboard_ChartStatistics: "Статистика",
    Responses_Dashboard_ChartTable: "Таблиця",
    Responses_Dashboard_ChartWordFrequency: "Частота слів",
    Responses_Dashboard_EmptyBody: "Щойно люди почнуть відповідати, ця панель заповниться автоматично: ключові показники, хронологія відповідей і діаграма для запитань, за якими варто стежити.",
    Responses_Dashboard_EmptyTitle: "Відповідей поки немає",
    Responses_Dashboard_Hide: "Приховати з панелі",
    Responses_Dashboard_Highlights: "Основне",
    Responses_Dashboard_Last7Days: "Останні 7 днів",
    Responses_Dashboard_LatestDate: "Остання: {date}",
    Responses_Dashboard_MedianTimeToComplete: "Медіанний час заповнення",
    Responses_Dashboard_NoPriorWeek: "Немає попереднього тижня для порівняння",
    Responses_Dashboard_OneEach: "По одній",
    Responses_Dashboard_Pin: "Закріпити на панелі",
    Responses_Dashboard_QuestionFallback: "запитання",
    Responses_Dashboard_QuestionsAnswered: "Запитань із відповідями",
    Responses_Dashboard_RecordedOnSubmit: "Записується під час надсилання",
    Responses_Dashboard_RepeatResponses: "Повторних відповідей: {count}",
    Responses_Dashboard_ResponsesOverTime: "Відповіді за часом",
    Responses_Dashboard_ShowHidden: "Показати приховані запитання",
    Responses_Dashboard_SinceMidnight: "Від опівночі",
    Responses_Dashboard_Today: "Сьогодні",
    Responses_Dashboard_TotalResponses: "Усього відповідей",
    Responses_Dashboard_UniqueRespondents: "Унікальні респонденти",
    Responses_Dashboard_Unpin: "Відкріпити від панелі",
    Responses_Dashboard_UntitledQuestion: "Запитання без назви",
    Responses_Dashboard_VsPrevious7Days: "порівняно з попередніми 7 днями",
    Responses_Detail_Answers: "Відповіді",
    Responses_Detail_AsTheForm: "Як у формі",
    Responses_Detail_Cancel: "Скасувати",
    Responses_Detail_Delete: "Видалити",
    Responses_Detail_DeleteBody: "Елемент списку переміститься до кошика сайту, тож його можна буде відновити звідти.",
    Responses_Detail_DeleteTitle: "Видалити цю відповідь?",
    Responses_Detail_Deleting: "Видалення…",
    Responses_Detail_Draft: "Чернетка",
    Responses_Detail_Header: "Відповідь {index} із {total}",
    Responses_Detail_LoadingAttachments: "Завантаження вкладень…",
    Responses_Detail_Next: "Наступна відповідь",
    Responses_Detail_NoAnswer: "Немає відповіді",
    Responses_Detail_Previous: "Попередня відповідь",
    Responses_Detail_Print: "Друк",
    Responses_Detail_Signature: "Підпис",
    Responses_Detail_Signed: "Підписано",
    Responses_Detail_Took: "тривалість: {duration}",
    Responses_Summary_AnsweredOfType: "Відповіли на {answered} із {total} · {type}",
    Responses_Summary_ByField: "За полем «{title}»",
    Responses_Summary_CompareBy: "Порівняти за…",
    Responses_Summary_EmptyBody: "Для кожного запитання тут буде окремий підсумок.",
    Responses_Summary_NoComparison: "Без порівняння",
    Responses_Summary_NothingToCompare: "Ніхто не відповів на запитання «{title}», тому порівнювати нічого.",
    Responses_Summary_OtherNote: "У діаграмах із понад {max} категоріями найменші групуються в «Інше»; щоб побачити кожне значення, перемкніть картку на «Таблиця».",
    Responses_Summary_ResponseCountOne: "{count} відповідь",
    Responses_Summary_ResponseCountOther: "{count} відповідей",
    Responses_Summary_SeeAllAnswers: "Переглянути всі відповіді в таблиці",
    Responses_Summary_SegmentNote: "Показано найбільші групи (кількість: {groups}). Відповідь із кількома вибраними варіантами з’являється в кожній відповідній групі, тому сума за групами може перевищувати {total}.",
    Responses_Summary_SplitBy: "Розділити за полем «{title}»",
    Responses_Summary_Untitled: "без назви",
    Responses_Table_Apply: "Застосувати",
    Responses_Table_Cancel: "Скасувати",
    Responses_Table_ClearSelection: "Скасувати вибір",
    Responses_Table_ColumnOrder: "Порядок стовпців",
    Responses_Table_ColumnsCount: "Стовпці ({shown}/{total})",
    Responses_Table_Delete: "Видалити",
    Responses_Table_DeleteBody: "Елементи списку перемістяться до кошика сайту, тож їх можна буде відновити звідти.",
    Responses_Table_DeleteSelected: "Видалити вибране",
    Responses_Table_DeleteTitleOne: "Видалити {count} відповідь?",
    Responses_Table_DeleteTitleOther: "Видалити відповіді ({count})?",
    Responses_Table_Deleting: "Видалення…",
    Responses_Table_MoveDown: "Перемістити вниз",
    Responses_Table_MoveDownFor: "Перемістити «{title}» вниз",
    Responses_Table_MoveUp: "Перемістити вгору",
    Responses_Table_MoveUpFor: "Перемістити «{title}» вгору",
    Responses_Table_NoColumns: "Видимих стовпців із запитаннями поки немає.",
    Responses_Table_NoMatch: "Немає відповідей, що відповідають поточним фільтрам.",
    Responses_Table_NothingToShow: "Нічого показувати",
    Responses_Table_OpenResponse: "Відкрити цю відповідь",
    Responses_Table_OrderNote: "Стовпці «Надіслано» та «Автор надсилання» завжди йдуть першими. Порядок перетягування стосується стовпців із запитаннями.",
    Responses_Table_Reorder: "Змінити порядок",
    Responses_Table_ResetColumns: "Скинути стовпці",
    Responses_Table_SelectResponse: "Вибрати цю відповідь",
    Responses_Table_SelectedOne: "Вибрано {count} відповідь",
    Responses_Table_SelectedOther: "Вибрано відповідей: {count}",
    Responses_Table_ShowAll: "Показати все",
    Responses_Table_ShowTheseQuestions: "Показати ці запитання",
    Responses_Table_Submitted: "Надіслано",
    Responses_Table_SubmittedBy: "Автор надсилання",
    Responses_Table_ToggleSelection: "Перемкнути вибір",
    Responses_Table_Unknown: "Невідомо",
    Responses_Table_Untitled: "Без назви",
    Responses_View_AllTime: "За весь час",
    Responses_View_AnyAnswer: "Будь-яка відповідь",
    Responses_View_Clear: "Очистити",
    Responses_View_CopyShareLink: "Копіювати посилання для спільного доступу",
    Responses_View_CountFiltered: "{shown} із {total} відповідей",
    Responses_View_CountOne: "{count} відповідь",
    Responses_View_CountOther: "{count} відповідей",
    Responses_View_Dashboard: "Панель",
    Responses_View_DateRange: "Діапазон дат",
    Responses_View_EmptyBody: "Поділіться формою, щоб почати збирання. Відповіді зберігаються в списку «{list}» і відображаються тут одразу.",
    Responses_View_EmptyTitle: "Відповідей поки немає",
    Responses_View_ExportCsv: "Експортувати в CSV",
    Responses_View_FilterByAnswer: "Фільтрувати за відповіддю",
    Responses_View_FilterByQuestion: "Фільтрувати за запитанням",
    Responses_View_FilterValue: "Значення фільтра",
    Responses_View_Last30Days: "Останні 30 днів",
    Responses_View_Last7Days: "Останні 7 днів",
    Responses_View_Last90Days: "Останні 90 днів",
    Responses_View_LoadError: "Не вдалося завантажити відповіді. Опублікуйте форму один раз, щоб створити стовпці списку, і повторіть спробу.",
    Responses_View_Loading: "Завантаження відповідей…",
    Responses_View_MoreActions: "Інші дії з відповідями",
    Responses_View_PreviewForm: "Переглянути форму",
    Responses_View_Refresh: "Оновити",
    Responses_View_ResponsesTab: "Відповіді ({count})",
    Responses_View_SearchPlaceholder: "Пошук в усіх відповідях",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Виберіть значення",
    Responses_View_Summary: "Підсумок",
    Responses_View_Today: "Сьогодні",
    Responses_View_Truncated: "У цьому списку більше відповідей, ніж Smart Forms завантажує за раз. Показано {count} найновіших; щоб побачити всі, відкрийте список у Microsoft Lists.",
    Responses_View_TryAgain: "Повторити",
    Responses_View_Untitled: "Без назви",
    Responses_Approval_Column: "Затвердження",
    Responses_Approval_ReviewerColumn: "Перевірив(-ла)",
    Responses_Approval_CommentColumn: "Коментар рецензента",
    Responses_Approval_Pending: "Очікує",
    Responses_Approval_Approved: "Затверджено",
    Responses_Approval_Rejected: "Відхилено",
    Responses_Approval_AnyStatus: "Будь-який стан затвердження",
    Responses_Approval_FilterLabel: "Фільтрувати за станом затвердження",
    Responses_Approval_ApproveSelected: "Затвердити вибрані",
    Responses_Approval_RejectSelected: "Відхилити вибрані",
    Responses_Approval_BulkFailed: "Не вдалося оновити відповіді: {count}. Повторіть спробу.",
    Responses_Approval_Approve: "Затвердити",
    Responses_Approval_Reject: "Відхилити",
    Responses_Approval_Reset: "Скинути до очікування",
    Responses_Approval_CommentLabel: "Коментар (необов’язково)",
    Responses_Approval_ReviewedBy: "Перевірив(-ла): {name}",
    Responses_Approval_Error: "Не вдалося зберегти рішення. Повторіть спробу.",
    Responses_Dashboard_ApprovalStatus: "Очікують перевірки",
    Responses_Dashboard_ApprovalBreakdown: "очікують: {pending}, затверджено: {approved}, відхилено: {rejected}",
    Responses_Dashboard_TimelineCoarsened: "Діапазон дат довгий, тому часову шкалу згруповано крупніше ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Діапазон дат дуже довгий, тому показано лише останні періоди: {count}.",
    Service_Item_DefaultTitle: "Відповідь — {date}",
    Service_Email_ApprovalSubject: "Вашу відповідь {status} — {title}",
    Service_Email_ApprovalHeading: "Вашу відповідь {status}",
    Service_Email_ApprovalIntro: "Рецензент позначив вашу відповідь на «{title}» так: {status}.",
    Service_Email_ApprovalCommentLabel: "Коментар рецензента",
    Service_Approval_Approved: "затверджено",
    Service_Approval_Rejected: "відхилено",
    Service_Approval_Pending: "очікує",
    Service_Lookup_InvalidFilter: "Фільтр підстановки недійсний.",
    Service_Edit_NotAllowed: "Ця форма не дозволяє редагувати надіслану відповідь.",
    Service_Edit_NotYours: "Редагувати можна лише власну відповідь.",
    Service_Signature_AttachmentLabel: "Підпис",
    PropertyPane_ListsLoadFailed: "Не вдалося завантажити списки на цьому сайті.",
    PropertyPane_EnterListName: "Спершу введіть назву нового списку.",
    PropertyPane_CreatingList: "Створення «{name}»…",
    PropertyPane_ListCreated: "Список «{title}» створено й вибрано.",
    PropertyPane_ListAlreadyExists: "Список «{name}» уже існує — виберіть його у спадному списку вище.",
    PropertyPane_CreateListFailed: "Не вдалося створити список. Переконайтеся, що у вас є дозвіл створювати списки на цьому сайті.",
    PropertyPane_Description: "Виберіть список SharePoint, у якому зберігатимуться відповіді на форму, або створіть новий. Усе інше — запитання, вигляд, сповіщення — редагується безпосередньо на сторінці.",
    PropertyPane_ResponseList_GroupName: "Список відповідей",
    PropertyPane_ListDropdown_Label: "Зберігати відповіді в цьому списку",
    PropertyPane_ResponsesGoTo: "Відповіді надходять до списку «{name}».",
    PropertyPane_PickList: "Виберіть список або створіть його нижче.",
    PropertyPane_LoadingLists: "Завантаження списків…",
    PropertyPane_NewListName_Label: "Або створіть новий список",
    PropertyPane_NewListName_Placeholder: "Назва нового списку",
    PropertyPane_CreateList_Button: "Створити список",
    PropertyPane_Tips_GroupName: "Поради",
    PropertyPane_Tip_AutoSave: "Запитання й параметри зберігаються автоматично під час редагування — зберігати чи публікувати сторінку не потрібно.",
    PropertyPane_Tip_Permissions: "Респондентам потрібен дозвіл додавати елементи до списку відповідей. Якщо хтось повідомляє про помилку під час надсилання, перевірте дозволи для списку.",
    PropertyPane_Tip_Share: "Скористайтеся кнопкою «Зібрати відповіді» на сторінці, щоб створити стовпці списку й отримати посилання для заповнення.",
    App_ErrorBoundary_Title: "Smart Forms — помилка відтворення",
    App_ErrorBoundary_Message: "Повідомлення:",
    App_ErrorBoundary_Stack: "Стек:",
    App_ErrorBoundary_NoStack: "(стек недоступний)",
    App_ErrorBoundary_ConsoleNote: "Повні відомості також записано в консоль браузера.",
    App_DefaultQuestionTitle: "Запитання {number}",
    App_Error_ListMissing: "Список, налаштований для цієї форми, більше не існує. Виберіть інший список у параметрах вебчастини.",
    App_Error_LoadConfig: "Під час завантаження конфігурації форми сталася помилка.",
    App_Error_Unable: "Не вдалося завантажити форму.",
    App_Publish_ConflictNotice: "«{title}» уже має стовпець списку іншого типу ({type}). Перейменуйте запитання, щоб можна було створити новий стовпець, або поверніть його тип.",
    App_Publish_ConflictUnnamedQuestion: "запитання",
    App_Publish_ColumnsAddedOne: "До списку «{list}» додано {count} стовпець.",
    App_Publish_ColumnsAddedOther: "До списку «{list}» додано стовпців: {count}.",
    App_Publish_TheList: "список",
    App_Publish_UpToDate: "Список відповідей уже актуальний.",
    App_Publish_Error: "Не вдалося створити стовпці списку. Зазвичай це означає, що у вас немає дозволу «Керування списками» для списку відповідей, але таке може бути й на сайтах із вимкненими власними скриптами. Перегляньте консоль браузера, щоб побачити вихідну помилку, або повторіть спробу.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Створюйте вишукані форми на основі списку SharePoint: типів запитань — {count}, логіка розгалуження, передавання файлів, посилання для заповнення та панель результатів.",
    App_Placeholder_ChooseList: "Виберіть або створіть список",
    App_Placeholder_Hint: "Щоб почати, відредагуйте сторінку й налаштуйте цю вебчастину.",
    App_Loading: "Завантаження форми…",
    App_OpenSettings: "Відкрити параметри",
    App_Tab_Questions: "Запитання",
    App_Tab_QuestionsWithCount: "Запитання ({count})",
    App_Tab_Responses: "Відповіді",
    App_Tab_Responses_Title: "Відповіді зберігаються в списку «{list}»",
    App_Templates_Start: "Почати із шаблону",
    App_Settings_Title: "Параметри форми: вигляд, сповіщення, доступ",
    App_Settings_AriaLabel: "Параметри форми",
    App_Preview: "Перегляд",
    App_Preview_Close: "Закрити перегляд",
    App_Preview_Hint: "Перегляд: усе, що ви тут надішлете, не зберігається. Перевірка й розгалуження працюють так само, як для респондентів.",
    App_Publish_GettingReady: "Підготовка…",
    App_Publish_CollectResponses: "Зібрати відповіді",
    App_Publish_Share: "Поділитися",
    App_Retry: "Повторити",
    App_SaveError_Banner: "Вашу останню зміну не вдалося зберегти. Перевірте підключення й повторіть спробу.",
    App_Preflight_BlockingTitle: "Виправте це перед збиранням",
    App_Preflight_WarningTitle: "Варто переглянути спершу",
    App_Preflight_BlockingText: "Через це опублікована форма не працюватиме належним чином.",
    App_Preflight_WarningText: "Нічого не зламано, але зазвичай варто виправити це, перш ніж ділитися посиланням.",
    App_Preflight_GoTo: "Перейти",
    App_Preflight_CollectAnyway: "Усе одно зібрати відповіді",
    App_Preflight_Back: "Назад до форми",
    App_Cancel: "Скасувати",
    App_Done: "Готово",
    App_Share_Title: "Вашу форму готово до спільного доступу",
    App_Share_SubText: "Надішліть це посилання кожному, хто має заповнити форму.",
    App_Share_LinkAriaLabel: "Посилання для спільного доступу",
    App_Share_Copy: "Копіювати",
    App_Share_Copied: "Скопійовано",
    App_Share_AddItemsEmphasis: "додавати елементи",
    App_Share_PermissionNote: "Респондентам потрібен дозвіл {addItems} до списку «{title}» і доступ до цієї сторінки. Якщо хтось отримує помилку під час надсилання, майже завжди причина в цьому.",
    App_Share_PrefillNote: "Ви можете заздалегідь відповісти на запитання в посиланні, додавши назву стовпця, наприклад {example}.",
    App_Templates_ReplaceWarning: "Вибір шаблону замінить наявні запитання.",
    App_Templates_PickStart: "Виберіть відправну точку — потім можна змінити що завгодно.",
    App_Templates_Empty: "Порожня",
    App_Templates_QuestionCount: "Запитань: {count}",
    App_SaveChip_SavingTitle: "Зберігається ваша остання правка",
    App_SaveChip_Saving: "Збереження…",
    App_SaveChip_FailedTitle: "Вашу останню правку не вдалося зберегти. Перевірте підключення й повторіть спробу.",
    App_SaveChip_Failed: "Не збережено",
    App_SaveChip_SavedTitle: "Усі зміни збережено",
    App_SaveChip_Saved: "Збережено",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Нова відповідь — {title}",
    Service_Email_NewResponseHeading: "Нова відповідь: {title}",
    Service_Email_NewResponseIntro: "Хтось щойно надіслав відповідь — {date}.",
    Service_Email_ReceiptSubject: "Ваша відповідь — {title}",
    Service_Email_ReceiptHeading: "Дякуємо за вашу відповідь!",
    Service_Email_ReceiptIntro: "Ось копія того, що ви надіслали до форми «{title}».",
    App_History_Title: "Історія версій",
    App_History_RestoredNotice: "Відновлено версію, збережену {date}. Перегляньте її, а потім скористайтеся пунктом «Збирати відповіді», щоб опублікувати нові запитання.",
    App_History_Undo: "Скасувати відновлення",
    App_Share_CopyManual: "Ваш браузер заблокував копіювання. Виділіть посилання вище й натисніть Ctrl+C (Cmd+C на Mac), щоб скопіювати його.",
    App_Share_TeamsNote: "Ви працюєте в Microsoft Teams. Це посилання відкриває сторінку SharePoint напряму, тому отримувачам потрібен доступ до сайту.",
    App_Share_PrefillNotSecure: "Попередньо заповнені відповіді — лише зручність: будь-хто з посиланням може їх змінити, тому ніколи не вважайте їх межею безпеки.",
    Designer_Section_DropHere: "Перетягніть запитання сюди",
    Designer_Section_DropEnd: "Відпустіть тут, щоб перемістити в кінець цього розділу",
    Designer_Rules_RemovedOne: "Видалено 1 правило розгалуження, що більше не підходило.",
    Designer_Rules_RemovedOther: "Видалено правил розгалуження, що більше не підходили: {count}.",
    Designer_Settings_AllowEdit: "Дозволити респондентам редагувати свою відповідь",
    Designer_Settings_AllowEditHint: "Респонденти можуть знову відкрити й оновити надіслане. Кожен може редагувати лише власну відповідь.",
    Designer_Settings_EnableApproval: "Увімкнути робочий процес затвердження",
    Designer_Settings_ApprovalNotify: "Надсилати респонденту лист про рішення",
    Designer_Settings_ApprovalHint: "Додає стовпці затвердження до списку відповідей під час наступної публікації. Власники затверджують або відхиляють відповіді на вкладці «Відповіді».",
    Designer_History_Title: "Історія версій",
    Designer_History_Intro: "Раніше збережені версії запитань і параметрів цієї форми. Відновлення завантажує версію в конструктор; це можна скасувати, а нові запитання створюються лише після публікації.",
    Designer_History_Loading: "Завантаження версій...",
    Designer_History_Empty: "Попередніх версій не знайдено. Для історії версій потрібно ввімкнути керування версіями для списку «Smart Forms Config» і мати принаймні одне збережене редагування.",
    Designer_History_Latest: "Остання",
    Designer_History_LatestTitle: "Це версія, яка зараз використовується",
    Designer_History_By: "автор: {name}",
    Designer_History_UnknownAuthor: "Невідомий автор",
    Designer_History_VersionLabel: "версія {label}",
    Designer_History_Preview: "Попередній перегляд",
    Designer_History_Restore: "Відновити",
    Designer_History_QuestionsOne: "1 запитання",
    Designer_History_QuestionsOther: "Запитань: {count}",
    Designer_History_LoadFailed: "Не вдалося завантажити цю версію.",
    Designer_History_ConfirmTitle: "Відновити цю версію?",
    Designer_History_ConfirmText: "Форму буде замінено версією, збереженою {date} (запитань: {count}). Одразу після цього можна скасувати дію."
  };
});
