define([], function () {
  return {
    Designer_Color_Blue: "Xanh dương",
    Designer_Color_Teal: "Xanh mòng két",
    Designer_Color_Green: "Xanh lục",
    Designer_Color_Purple: "Tím",
    Designer_Color_Magenta: "Đỏ tươi",
    Designer_Color_Red: "Đỏ",
    Designer_Color_Orange: "Cam",
    Designer_Color_Gray: "Xám",
    Designer_Settings_LayoutSinglePage: "Tất cả câu hỏi trên một trang",
    Designer_Settings_LayoutWizard: "Mỗi bước một phần (trình hướng dẫn)",
    Designer_Settings_Title: "Cài đặt biểu mẫu",
    Designer_Common_Apply: "Áp dụng",
    Designer_Common_Cancel: "Hủy",
    Designer_Settings_TabBasics: "Cơ bản",
    Designer_Settings_FormTitle: "Tiêu đề biểu mẫu",
    Designer_Settings_Description: "Mô tả",
    Designer_Settings_Layout: "Bố cục",
    Designer_Settings_NumberQuestions: "Đánh số câu hỏi",
    Designer_Settings_ShuffleQuestions: "Xáo trộn thứ tự câu hỏi cho mỗi người trả lời",
    Designer_Settings_ShowProgressBar: "Hiển thị thanh tiến trình",
    Designer_Settings_TabAppearance: "Giao diện",
    Designer_Settings_AccentColor: "Màu nhấn",
    Designer_Settings_CustomColorTitle: "Màu tùy chỉnh",
    Designer_Settings_CustomColorAria: "Màu nhấn tùy chỉnh",
    Designer_Settings_AccentHint: "Màu nhấn được tự động điều chỉnh để có độ tương phản trên các site tối, nhờ đó biểu mẫu luôn dễ đọc dù trang dùng giao diện nào.",
    Designer_Settings_ShowHeader: "Hiển thị tiêu đề biểu mẫu",
    Designer_Settings_HeaderIcon: "Biểu tượng tiêu đề",
    Designer_Settings_TabAfterSubmit: "Sau khi gửi",
    Designer_Settings_SubmitButtonText: "Văn bản nút gửi",
    Designer_Settings_SubmitPlaceholder: "Gửi",
    Designer_Settings_ThankYouTitle: "Tiêu đề lời cảm ơn",
    Designer_Settings_ThankYouPlaceholder: "Cảm ơn bạn!",
    Designer_Settings_ThankYouMessage: "Thông điệp cảm ơn",
    Designer_Settings_ShowSubmitAnother: "Hiển thị nút \"Gửi phản hồi khác\"",
    Designer_Settings_TabNotifications: "Thông báo",
    Designer_Settings_EmailEachResponseTo: "Gửi email từng phản hồi tới",
    Designer_Settings_EmailPlaceholder: "ten@congty.com; nhom@congty.com",
    Designer_Settings_EmailDescription: "Người trong tổ chức của bạn sẽ nhận mọi phản hồi qua email, kèm liên kết đến mục trong danh sách",
    Designer_Settings_RespondentReceipt: "Gửi email cho người trả lời một bản sao câu trả lời của họ",
    Designer_Settings_NotificationsInfo: "Thông báo dùng dịch vụ thư của chính SharePoint, vì vậy người nhận phải là người dùng trong tổ chức của bạn. Địa chỉ bên ngoài sẽ bị bỏ qua mà không có thông báo.",
    Designer_Settings_TabAccess: "Truy cập",
    Designer_Settings_OpenFrom: "Mở từ",
    Designer_Settings_OpenImmediately: "Mở ngay",
    Designer_Settings_CloseAfter: "Đóng sau",
    Designer_Settings_NeverClose: "Không bao giờ đóng",
    Designer_Settings_ClearDates: "Xóa ngày",
    Designer_Settings_DatesInverted: "Ngày đóng trùng hoặc trước ngày mở, nên biểu mẫu sẽ không bao giờ nhận phản hồi.",
    Designer_Settings_MaxResponses: "Dừng sau số phản hồi này",
    Designer_Settings_NoLimit: "Không giới hạn",
    Designer_Settings_OneResponsePerPerson: "Chỉ cho phép một phản hồi cho mỗi người",
    Designer_Settings_AllowSaveDraft: "Cho phép người trả lời lưu bản nháp và hoàn tất sau",
    Designer_Settings_ClosedMessage: "Thông báo hiển thị khi biểu mẫu đã đóng",
    Designer_Settings_ClosedMessagePlaceholder: "Biểu mẫu này không còn nhận phản hồi.",
    Designer_Settings_AccessInfo: "Các giới hạn này do biểu mẫu thực thi, không phải SharePoint. Bất kỳ ai có quyền thêm mục vào danh sách phản hồi vẫn có thể thêm trực tiếp qua danh sách.",
    Designer_Field_StyleInfo: "Thông tin (màu nhấn)",
    Designer_Field_StyleSuccess: "Thành công (xanh lục)",
    Designer_Field_StyleWarning: "Cảnh báo (hổ phách)",
    Designer_Field_StylePlain: "Văn bản thuần",
    Designer_Field_StyleDivider: "Đường phân cách",
    Designer_Field_IconStars: "Ngôi sao",
    Designer_Field_IconHearts: "Trái tim",
    Designer_Field_IconThumbs: "Thích",
    Designer_Field_FormatPlain: "Số thuần",
    Designer_Field_FormatCurrency: "Tiền tệ",
    Designer_Field_FormatPercent: "Phần trăm",
    Designer_Field_UntitledQuestion: "Câu hỏi chưa có tiêu đề",
    Designer_Field_DeletedQuestion: "một câu hỏi đã xóa",
    Designer_Rule_Unary: "\"{name}\" {operator}",
    Designer_Rule_Between: "\"{name}\" {operator} {value} và {value2}",
    Designer_Rule_Binary: "\"{name}\" {operator} \"{value}\"",
    Designer_Rule_JoinAny: "HOẶC",
    Designer_Rule_JoinAll: "VÀ",
    Designer_Rule_Preview: "Hiển thị khi {conditions}.",
    Designer_Field_Yes: "Có",
    Designer_Field_No: "Không",
    Designer_Field_When: "Khi",
    Designer_Field_SelectValue: "Chọn một giá trị",
    Designer_Field_DateValuePlaceholder: "YYYY-MM-DD hoặc \"today\"",
    Designer_Field_ValuePlaceholder: "Giá trị",
    Designer_Field_UpperBound: "Giới hạn trên",
    Designer_Field_RemoveCondition: "Xóa điều kiện này",
    Designer_Field_FormulaInvalid: "Không thể tính công thức này. Hãy kiểm tra dấu ngoặc và toán tử.",
    Designer_Field_FormulaMissing: "Các câu hỏi này không tồn tại: {names}.",
    Designer_Field_FormulaPreview: "Khi mọi đầu vào đều bằng 10, giá trị hiển thị là {value}.",
    Designer_Field_HintYesNo: "Dùng \"yes\" hoặc \"no\"",
    Designer_Field_HintMultiDefault: "Phân tách nhiều giá trị mặc định bằng ;",
    Designer_Field_HintSingleDefault: "Phải khớp với một trong các lựa chọn",
    Designer_Field_HintDate: "Dùng \"today\" hoặc một ngày như 2026-03-01",
    Designer_Field_HintTime: "Dùng \"now\" hoặc một giờ như 09:30",
    Designer_Field_QuestionSettings: "Cài đặt câu hỏi",
    Designer_Field_Appearance: "Giao diện",
    Designer_Field_Style: "Kiểu",
    Designer_Field_ImageUrl: "URL hình ảnh (tùy chọn)",
    Designer_Field_Content: "Nội dung",
    Designer_Field_BasicFormatting: "Cho phép định dạng cơ bản: đậm, nghiêng, danh sách và liên kết.",
    Designer_Field_TabOptions: "Lựa chọn",
    Designer_Field_TabBranching: "Phân nhánh",
    Designer_Field_BranchingNeedsQuestion: "Hãy thêm một câu hỏi khác trước — phân nhánh cần có câu hỏi để phụ thuộc vào.",
    Designer_Field_BranchingToggle: "Chỉ hiển thị câu hỏi này khi các câu trả lời khác khớp",
    Designer_Field_Match: "Khớp",
    Designer_Field_MatchAll: "tất cả các điều kiện này",
    Designer_Field_MatchAny: "bất kỳ điều kiện nào trong số này",
    Designer_Field_AddCondition: "Thêm điều kiện",
    Designer_Field_TabValidation: "Xác thực",
    Designer_Field_HelpText: "Văn bản trợ giúp",
    Designer_Field_HelpTextPlaceholder: "Hiển thị bên dưới nhãn câu hỏi",
    Designer_Field_CheckboxLabel: "Nhãn hộp kiểm",
    Designer_Field_Placeholder: "Văn bản gợi ý",
    Designer_Field_DefaultAnswer: "Câu trả lời mặc định",
    Designer_Field_RequiredMessage: "Thông báo bắt buộc tùy chỉnh",
    Designer_Field_RequiredMessagePlaceholder: "{title} là bắt buộc",
    Designer_Field_ThisQuestion: "Câu hỏi này",
    Designer_Field_RequiredMessageDescription: "Hiển thị thay cho thông báo chuẩn khi câu hỏi này bị bỏ trống",
    Designer_Field_ReadOnly: "Chỉ đọc (câu trả lời chỉ có thể đến từ liên kết điền sẵn)",
    Designer_Field_ValidationRules: "Quy tắc xác thực",
    Designer_Field_MaxLength: "Độ dài tối đa",
    Designer_Field_Pattern: "Phải khớp với mẫu này",
    Designer_Field_PatternDescription: "Một biểu thức chính quy. Để trống nếu không cần kiểm tra mẫu.",
    Designer_Field_PatternMessage: "Thông báo khi mẫu không khớp",
    Designer_Field_PatternMessagePlaceholder: "Câu trả lời này không đúng định dạng mong đợi",
    Designer_Field_Format: "Định dạng",
    Designer_Field_UnitSuffix: "Đơn vị hiển thị sau giá trị",
    Designer_Field_UnitSuffixPlaceholder: "kg, giờ, mục…",
    Designer_Field_Minimum: "Tối thiểu",
    Designer_Field_Maximum: "Tối đa",
    Designer_Field_Decimals: "Số thập phân",
    Designer_Field_Formula: "Công thức",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "Tham chiếu các câu hỏi khác bằng văn bản của chúng trong dấu ngoặc nhọn. Hỗ trợ + - * / ( ) và round, min, max, sum, avg.",
    Designer_Field_AvailableQuestions: "Các câu hỏi khả dụng: {questions}",
    Designer_Field_NoneYet: "chưa có",
    Designer_Field_Step: "Bước nhảy",
    Designer_Field_From: "Từ",
    Designer_Field_To: "Đến",
    Designer_Field_LowLabel: "Nhãn ở đầu thấp",
    Designer_Field_LowLabelPlaceholder: "Hoàn toàn không có khả năng",
    Designer_Field_HighLabel: "Nhãn ở đầu cao",
    Designer_Field_HighLabelPlaceholder: "Cực kỳ có khả năng",
    Designer_Field_SummarizeAs: "Tóm tắt dưới dạng",
    Designer_Field_SummarizeAverage: "Trung bình và phân bố",
    Designer_Field_SummarizeNps: "Net Promoter Score (cần thang điểm 0–10)",
    Designer_Field_NpsWarning: "Net Promoter Score chỉ có ý nghĩa trên thang điểm 0–10. Đặt Từ là 0 và Đến là 10.",
    Designer_Field_NumberOfIcons: "Số biểu tượng",
    Designer_Field_Icon: "Biểu tượng",
    Designer_Field_AllowHalf: "Cho phép giá trị nửa điểm",
    Designer_Field_ShowOptionsAs: "Hiển thị lựa chọn dưới dạng",
    Designer_Field_DisplayButtons: "Nút cùng dòng",
    Designer_Field_DisplayDropdown: "Danh sách thả xuống",
    Designer_Field_DisplayAutomatic: "Tự động (cùng dòng tối đa 6 lựa chọn)",
    Designer_Field_AllowOther: "Thêm lựa chọn \"Khác\" cho phép nhập tự do",
    Designer_Field_OtherLabel: "Nhãn cho lựa chọn \"Khác\"",
    Designer_Field_OtherPlaceholder: "Khác",
    Designer_Field_ShuffleOptions: "Xáo trộn thứ tự lựa chọn cho mỗi người trả lời",
    Designer_Field_MinSelections: "Số lựa chọn tối thiểu",
    Designer_Field_MaxSelections: "Số lựa chọn tối đa",
    Designer_Field_SourceList: "Danh sách nguồn",
    Designer_Field_ChooseList: "Chọn một danh sách",
    Designer_Field_LookupColumn: "Cột để đọc các lựa chọn",
    Designer_Field_ChooseColumn: "Chọn một cột",
    Designer_Field_ChooseListFirst: "Hãy chọn danh sách trước",
    Designer_Field_LookupFilter: "Bộ lọc (tùy chọn)",
    Designer_Field_LookupFilterDescription: "Bộ lọc OData thu hẹp những mục nguồn nào trở thành lựa chọn",
    Designer_Field_LookupInfo: "Câu trả lời lưu văn bản lựa chọn, không phải liên kết đến mục nguồn, nên phản hồi vẫn dễ đọc ngay cả khi danh sách nguồn thay đổi sau này.",
    Designer_Field_ConsentText: "Điều khoản hiển thị phía trên hộp kiểm",
    Designer_Field_AllowMultiplePeople: "Cho phép nhiều người",
    Designer_Field_AllowGroups: "Cho phép cả nhóm",
    Designer_Field_IncludeTime: "Bao gồm giờ trong ngày",
    Designer_Field_TimeStep: "Bước thời gian (phút)",
    Designer_Field_MaxFiles: "Số tệp tối đa",
    Designer_Field_MaxFileSize: "Kích thước tối đa mỗi tệp (MB)",
    Designer_Field_AcceptedTypes: "Loại tệp được chấp nhận",
    Designer_Field_AcceptedTypesDescription: "Các phần mở rộng phân tách bằng dấu phẩy. Để trống để chấp nhận mọi thứ SharePoint cho phép.",
    Designer_Field_FilesInfo: "Tệp được lưu dưới dạng tệp đính kèm trên mục phản hồi. SharePoint chặn một số phần mở rộng (như .exe) bất kể bạn cho phép gì ở đây.",
    Designer_Field_Rows: "Hàng",
    Designer_Field_ProvisionedNote: "Câu hỏi này đã có một cột danh sách ({name}). Các cài đặt thay đổi kiểu của cột bị khóa — hãy nhân bản câu hỏi nếu bạn cần kiểu khác.",
    Designer_Category_Text: "Văn bản",
    Designer_Category_Choice: "Lựa chọn",
    Designer_Category_Scales: "Thang đo",
    Designer_Category_Date: "Ngày",
    Designer_Category_People: "Người",
    Designer_Category_Advanced: "Nâng cao",
    Designer_Category_Layout: "Bố cục",
    Designer_Menu_CommonPresets: "Mẫu thường dùng",
    Designer_Menu_AllTypes: "Tất cả loại câu hỏi",
    Designer_Menu_ChangeType: "Đổi loại",
    Designer_Menu_TypeLockedTitle: "Cột danh sách đã tồn tại nên loại bị khóa. Hãy nhân bản câu hỏi để thay đổi.",
    Designer_Menu_MoreSettings: "Phân nhánh, xác thực và hơn thế nữa",
    Designer_Menu_InsertBelow: "Chèn câu hỏi bên dưới",
    Designer_Card_Duplicate: "Nhân bản",
    Designer_Card_DeleteQuestion: "Xóa câu hỏi",
    Designer_Outline_Aria: "Dàn ý câu hỏi",
    Designer_Outline_QuestionCountOne: "{count} câu hỏi",
    Designer_Outline_QuestionCountOther: "{count} câu hỏi",
    Designer_Outline_IssuesTitle: "{count} vấn đề cần xem xét",
    Designer_Outline_Find: "Tìm câu hỏi",
    Designer_Outline_Empty: "Chưa có câu hỏi nào.",
    Designer_Section_DefaultTitle: "Phần {number}",
    Designer_Card_Question: "Câu hỏi",
    Designer_Card_BranchingTitle: "Câu hỏi này chỉ xuất hiện khi một quy tắc phân nhánh khớp",
    Designer_Card_BranchingChip: "Phân nhánh",
    Designer_Card_LiveTitle: "Cột danh sách đã tồn tại nên loại bị khóa",
    Designer_Card_LiveChip: "Đang hoạt động",
    Designer_Card_CheckChip: "Kiểm tra",
    Designer_Option_Placeholder: "Lựa chọn {number}",
    Designer_Option_LabelAria: "Nhãn lựa chọn {number}",
    Designer_Option_ImageUrl: "URL hình ảnh",
    Designer_Option_ImageUrlAria: "URL hình ảnh của lựa chọn {number}",
    Designer_Option_Remove: "Xóa lựa chọn",
    Designer_Option_RemoveAria: "Xóa lựa chọn {number}",
    Designer_Option_Add: "Thêm lựa chọn",
    Designer_Option_OtherHint: "Người trả lời cũng có thể tự nhập một câu trả lời có nhãn “{label}”.",
    Designer_Option_OtherFallback: "Khác",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "Xóa",
    Designer_Grid_RemoveAria: "Xóa {label} {number}",
    Designer_Grid_Statements: "Phát biểu",
    Designer_Grid_Scale: "Thang đo",
    Designer_Grid_AddStatement: "Thêm phát biểu",
    Designer_Grid_AddScale: "Thêm thang đo",
    Designer_Width_Full: "Chiều rộng đầy đủ",
    Designer_Width_Half: "Nửa chiều rộng",
    Designer_Width_Third: "Một phần ba chiều rộng",
    Designer_Width_Aria: "Chiều rộng câu hỏi",
    Designer_Card_BlockLabelPlaceholder: "Nhãn khối (không hiển thị cho người trả lời)",
    Designer_Card_QuestionText: "Nội dung câu hỏi",
    Designer_Card_MoveUp: "Di chuyển lên",
    Designer_Card_MoveQuestionUp: "Di chuyển câu hỏi lên",
    Designer_Card_MoveDown: "Di chuyển xuống",
    Designer_Card_MoveQuestionDown: "Di chuyển câu hỏi xuống",
    Designer_Card_DuplicateQuestion: "Nhân bản câu hỏi",
    Designer_Card_MultipleAnswers: "Nhiều câu trả lời",
    Designer_Card_Required: "Bắt buộc",
    Designer_Card_MoreOptions: "Tùy chọn khác",
    Designer_Card_MoreOptionsAria: "Tùy chọn khác cho câu hỏi này",
    Designer_Canvas_FormTitle: "Tiêu đề biểu mẫu",
    Designer_Canvas_DescriptionPlaceholder: "Thêm mô tả (tùy chọn)",
    Designer_Canvas_DescriptionAria: "Mô tả biểu mẫu",
    Designer_Canvas_EmptyTitle: "Thêm câu hỏi đầu tiên của bạn",
    Designer_Canvas_EmptyBody: "Chọn một loại câu hỏi để bắt đầu. Bạn có thể sắp xếp lại câu hỏi bằng cách kéo, và thêm phân nhánh để mọi người chỉ thấy những gì phù hợp với họ.",
    Designer_Section_Chip: "Phần {number} trên {total}",
    Designer_Section_TitlePlaceholder: "Tiêu đề phần",
    Designer_Section_TitleAria: "Tiêu đề phần {number}",
    Designer_Section_DescriptionPlaceholder: "Mô tả (tùy chọn)",
    Designer_Section_DescriptionAria: "Mô tả phần {number}",
    Designer_Section_MoveUp: "Di chuyển phần lên",
    Designer_Section_MoveDown: "Di chuyển phần xuống",
    Designer_Section_Delete: "Xóa phần",
    Designer_Card_DragToReorder: "Kéo để sắp xếp lại",
    Designer_Card_ReorderAria: "Sắp xếp lại {title}",
    Designer_Card_ReorderFallback: "câu hỏi",
    Designer_Canvas_AddNew: "Thêm mới",
    Designer_Canvas_AddSection: "Thêm phần",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "Địa chỉ đường phố",
    Form_Address_Street2Placeholder: "Căn hộ, phòng, v.v. (tùy chọn)",
    Form_Address_CityPlaceholder: "Thành phố",
    Form_Address_StatePlaceholder: "Tiểu bang / quận",
    Form_Address_PostalCodePlaceholder: "Mã bưu chính",
    Form_Address_CountryPlaceholder: "Quốc gia",
    Form_Address_StreetAria: "địa chỉ đường phố",
    Form_Address_Street2Aria: "dòng địa chỉ 2",
    Form_Address_CityAria: "thành phố",
    Form_Address_StateAria: "tiểu bang hoặc quận",
    Form_Address_PostalCodeAria: "mã bưu chính",
    Form_Address_CountryAria: "quốc gia",
    Form_Consent_DefaultLabel: "Tôi đồng ý",
    Form_Likert_RadioAria: "{row}: {column}",
    Form_Likert_RowsAnswered: "Đã trả lời {answered} trên {total} hàng",
    Form_Lookup_LoadError: "Không thể tải các lựa chọn cho câu hỏi này.",
    Form_Lookup_Loading: "Đang tải lựa chọn…",
    Form_Lookup_SelectOptionsPlaceholder: "Chọn các lựa chọn",
    Form_Lookup_SelectOptionPlaceholder: "Chọn một lựa chọn",
    Form_Person_Placeholder: "Bắt đầu nhập tên…",
    Form_Person_SuggestedPeopleAndGroups: "Người và nhóm được đề xuất",
    Form_Person_SuggestedPeople: "Người được đề xuất",
    Form_Person_NoPeopleOrGroups: "Không tìm thấy người hoặc nhóm nào",
    Form_Person_NoPeople: "Không tìm thấy người nào",
    Form_Person_Searching: "Đang tìm kiếm…",
    Form_Ranking_Moved: "{item} đã được chuyển đến vị trí {position} trên {total}",
    Form_Ranking_MoveUp: "Di chuyển lên",
    Form_Ranking_MoveDown: "Di chuyển xuống",
    Form_Ranking_MoveItemUpAria: "Di chuyển {item} lên",
    Form_Ranking_MoveItemDownAria: "Di chuyển {item} xuống",
    Form_Rating_ValueText: "{value} trên {max}",
    Form_Rating_NotRated: "Chưa đánh giá",
    Form_Rating_Clear: "Xóa đánh giá",
    Form_RichText_Bold: "Đậm",
    Form_RichText_Italic: "Nghiêng",
    Form_RichText_Underline: "Gạch chân",
    Form_RichText_BulletedList: "Danh sách dấu đầu dòng",
    Form_RichText_NumberedList: "Danh sách đánh số",
    Form_RichText_ClearFormatting: "Xóa định dạng",
    Form_RichText_ToolbarAria: "Định dạng văn bản",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "\"{name}\" đã bị bỏ qua — giới hạn là {limit}.",
    Form_File_TypeNotAccepted: "\"{name}\" không phải loại tệp được chấp nhận.",
    Form_File_TooLarge: "\"{name}\" lớn hơn {size} MB.",
    Form_File_AlreadyAttached: "\"{name}\" đã được đính kèm.",
    Form_File_ReadError: "Không thể đọc một trong các tệp. Hãy thử đính kèm lại.",
    Form_File_HintMaxSize: "tối đa {size} MB mỗi tệp",
    Form_File_HintOneFile: "1 tệp",
    Form_File_HintMaxFiles: "tối đa {count} tệp",
    Form_File_Reading: "Đang đọc tệp…",
    Form_File_DropPrompt: "Thả tệp vào đây hoặc bấm để duyệt",
    Form_File_Remove: "Xóa {name}",
    Form_Signature_Alt: "Chữ ký",
    Form_Signature_AriaSigned: "{label} — đã ký",
    Form_Signature_AriaEmpty: "{label} — trống",
    Form_Signature_Clear: "Xóa",
    Form_Signature_Signed: "Đã ký",
    Form_Signature_Prompt: "Ký ở trên bằng chuột, bút hoặc ngón tay",
    Form_Time_Placeholder: "Chọn giờ",
    Form_Field_DatePlaceholder: "Chọn ngày",
    Form_Field_TimeAriaWithLabel: "{label} — giờ",
    Form_Field_TimeAria: "Giờ",
    Form_Field_OtherDefault: "Khác",
    Form_Field_SelectOptionsPlaceholder: "Chọn các lựa chọn",
    Form_Field_PleaseSpecify: "Vui lòng nêu rõ",
    Form_Field_OtherSpecifyAria: "{label} — vui lòng nêu rõ",
    Form_Field_SelectOptionPlaceholder: "Chọn một lựa chọn",
    Form_Field_Yes: "Có",
    Form_Field_No: "Không",
    Form_Field_SliderHint: "Kéo thanh trượt để trả lời",
    Form_Field_WebAddressAriaWithLabel: "{label} — địa chỉ web",
    Form_Field_WebAddressAria: "Địa chỉ web",
    Form_Field_DisplayTextPlaceholder: "Văn bản hiển thị (tùy chọn)",
    Form_Field_DisplayTextAriaWithLabel: "{label} — văn bản hiển thị",
    Form_Field_DisplayTextAria: "Văn bản hiển thị",
    Form_Field_ChooseBetween: "Chọn từ {min} đến {max}",
    Form_Field_ChooseAtLeast: "Chọn ít nhất {min}",
    Form_Field_ChooseUpTo: "Chọn tối đa {max}",
    Form_Field_SelectedCount: "Đã chọn {count}",
    Form_Field_RequiredAria: "(bắt buộc)",
    Form_Submit_SaveError: "Không thể lưu phản hồi của bạn. Hãy đảm bảo biểu mẫu đã được xuất bản từ trình thiết kế và bạn có quyền thêm mục vào danh sách phản hồi.",
    Form_Empty_Message: "Biểu mẫu này chưa có câu hỏi nào. Chủ sở hữu biểu mẫu có thể thêm câu hỏi trong tab Câu hỏi.",
    Form_Checking: "Đang kiểm tra biểu mẫu…",
    Form_Closed_NotYetOpen: "Chưa mở",
    Form_Closed_AlreadyAnswered: "Đã trả lời",
    Form_Closed_Title: "Biểu mẫu đã đóng",
    Form_Confirmation_PreviewNotice: "Đây là bản xem trước — không có gì được lưu vào danh sách phản hồi.",
    Form_Confirmation_PreviewAgain: "Xem trước lại",
    Form_Confirmation_SubmitAnother: "Gửi phản hồi khác",
    Form_Wizard_StepFallback: "Bước {step}",
    Form_Wizard_StepsAria: "Các bước của biểu mẫu",
    Form_Wizard_StepOf: "Bước {step} trên {total}",
    Form_ErrorSummary_Title: "Vui lòng kiểm tra {count} câu trả lời:",
    Form_ErrorSummary_UntitledQuestion: "Câu hỏi chưa có tiêu đề",
    Form_ErrorSummary_Question: "Câu hỏi",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "Quay lại",
    Form_Nav_Next: "Tiếp theo",
    Form_Draft_Saving: "Đang lưu…",
    Form_Draft_Saved: "Đã lưu bản nháp",
    Form_Draft_SaveAndFinishLater: "Lưu và hoàn tất sau",
    Form_Draft_NotSaved: "Chưa lưu bản nháp",
    Form_Submit_Preview: "Gửi (xem trước)",
    Form_Submit_Button: "Gửi",
    Form_Response_NoAnswer: "Chưa trả lời",
    Form_Signature_TypeLabel: "Nhập họ và tên đầy đủ của bạn",
    Form_Signature_TypeInstead: "Nhập tên thay thế",
    Form_Signature_DrawInstead: "Vẽ thay thế",
    Form_Edit_Button: "Chỉnh sửa phản hồi trước đó của bạn",
    Form_Edit_Available: "Bạn đã gửi phản hồi. Bạn có thể chỉnh sửa phản hồi đó thay vì gửi phản hồi mới.",
    Form_Edit_Banner: "Bạn đang chỉnh sửa phản hồi trước đó của mình.",
    Form_Edit_Save: "Cập nhật phản hồi",
    Form_Edit_UpdatedTitle: "Đã cập nhật phản hồi",
    Form_Edit_UpdatedMessage: "Các thay đổi của bạn đã được lưu.",
    Form_Edit_LoadError: "Không thể tải phản hồi trước đó của bạn. Vui lòng thử lại.",
    Form_Draft_MissingFiles: "Vui lòng đính kèm lại: {names}. Không thể khôi phục các tệp này.",
    Form_Attachments_Failed: "Câu trả lời của bạn đã được lưu, nhưng không thể tải lên các tệp đính kèm sau: {names}. Vui lòng thử lại hoặc liên hệ chủ sở hữu biểu mẫu.",
    Logic_ThisQuestion: "Câu hỏi này",
    Logic_Required: "{label} là bắt buộc",
    Logic_RequiredConsent: "Vui lòng chọn hộp kiểm để tiếp tục",
    Logic_RequiredFile: "Vui lòng đính kèm ít nhất một tệp",
    Logic_RequiredSignature: "Vui lòng thêm chữ ký của bạn",
    Logic_RequiredLikert: "Vui lòng trả lời mọi hàng",
    Logic_InvalidEmail: "Nhập địa chỉ email hợp lệ",
    Logic_InvalidPhone: "Nhập số điện thoại hợp lệ",
    Logic_InvalidUrl: "Nhập địa chỉ web hợp lệ bắt đầu bằng http:// hoặc https://",
    Logic_MinValue: "Giá trị phải tối thiểu là {value}",
    Logic_MaxValue: "Giá trị phải tối đa là {value}",
    Logic_MaxLength: "Độ dài tối đa là {max} ký tự",
    Logic_ChooseAtLeastOne: "Chọn ít nhất {count} tùy chọn",
    Logic_ChooseAtLeastMany: "Chọn ít nhất {count} tùy chọn",
    Logic_ChooseAtMostOne: "Chọn tối đa {count} tùy chọn",
    Logic_ChooseAtMostMany: "Chọn tối đa {count} tùy chọn",
    Logic_LikertRemaining: "Vui lòng trả lời mọi hàng (còn {count})",
    Logic_MaxFilesOne: "Đính kèm tối đa {count} tệp",
    Logic_MaxFilesMany: "Đính kèm tối đa {count} tệp",
    Logic_FileTooLarge: "\"{name}\" lớn hơn {size} MB",
    Logic_FileTypeNotAccepted: "\"{name}\" không phải loại tệp được chấp nhận ({types})",
    Logic_AddressRequired: "Nhập ít nhất đường và thành phố",
    Logic_PatternDefault: "Câu trả lời này không đúng định dạng mong đợi",
    Logic_Yes: "Có",
    Logic_No: "Không",
    Logic_Agreed: "Đã đồng ý",
    Logic_NotAgreed: "Chưa đồng ý",
    Logic_Signed: "Đã ký",
    Logic_NoAnswer: "(không có câu trả lời)",
    Logic_Unknown: "(không xác định)",
    Logic_OtherSlice: "Khác ({count})",
    Logic_CsvResponseId: "ID phản hồi",
    Logic_CsvSubmitted: "Đã gửi",
    Logic_CsvSubmittedBy: "Người gửi",
    Logic_EmailQuestion: "Câu hỏi",
    Logic_EmailViewItem: "Xem trong Microsoft Lists",
    Logic_EmailFooter: "Được Smart Forms tự động gửi.",
    Logic_ClosedDefault: "Biểu mẫu này không còn nhận phản hồi.",
    Logic_NotYetOpen: "Biểu mẫu này sẽ mở vào {date}.",
    Logic_AlreadyResponded: "Bạn đã phản hồi biểu mẫu này. Cảm ơn bạn!",
    Logic_UntitledQuestion: "Câu hỏi chưa có tiêu đề",
    Logic_Issue_NoQuestions: "Thêm ít nhất một câu hỏi trước khi thu thập phản hồi.",
    Logic_Issue_NoTitle: "Có một câu hỏi chưa có nội dung — câu hỏi sẽ được tự động đặt tên khi bạn xuất bản.",
    Logic_Issue_DuplicateTitle: "{label} có nội dung trùng với câu hỏi khác, khiến kết quả khó đọc hơn.",
    Logic_Issue_NeedTwoOptions: "{label} cần ít nhất hai tùy chọn.",
    Logic_Issue_ImageNoImage: "{label} có các tùy chọn không có hình ảnh — chúng sẽ hiển thị dưới dạng ô văn bản.",
    Logic_Issue_LikertNeedRow: "{label} cần ít nhất một hàng.",
    Logic_Issue_LikertNeedColumns: "{label} cần ít nhất hai cột thang đo.",
    Logic_Issue_NoLookupList: "{label} chưa chọn danh sách nguồn.",
    Logic_Issue_NoFormula: "{label} chưa có công thức.",
    Logic_Issue_BadFormula: "{label} có công thức không thể tính toán. Hãy kiểm tra dấu ngoặc và toán tử.",
    Logic_Issue_MissingRefs: "{label} tham chiếu đến các câu hỏi không tồn tại: {names}.",
    Logic_Issue_BadPattern: "{label} có mẫu xác thực không hợp lệ.",
    Logic_Issue_BrokenRule: "{label} có quy tắc rẽ nhánh trỏ đến câu hỏi đã bị xóa.",
    Logic_Issue_SelfRule: "{label} có quy tắc rẽ nhánh tham chiếu đến chính nó.",
    Logic_Issue_RuleMismatch: "{label} có quy tắc rẽ nhánh không còn phù hợp với câu hỏi mà nó phụ thuộc.",
    Logic_Issue_RequiredReadOnly: "{label} vừa bắt buộc vừa chỉ đọc, nên chỉ có thể trả lời qua liên kết điền sẵn.",
    Logic_Issue_EmptySection: "Một phần không có câu hỏi nào và sẽ bị bỏ qua.",
    Logic_Issue_CloseBeforeOpen: "Ngày đóng trùng hoặc trước ngày mở, nên biểu mẫu sẽ không bao giờ nhận phản hồi.",
    Logic_Issue_ApprovalNotifyWithoutApproval: "Email phê duyệt đã bật nhưng bước phê duyệt đang tắt.",
    Logic_Op_equals: "là",
    Logic_Op_notEquals: "không phải là",
    Logic_Op_contains: "chứa",
    Logic_Op_notContains: "không chứa",
    Logic_Op_notEmpty: "đã được trả lời",
    Logic_Op_empty: "chưa được trả lời",
    Logic_Op_greaterThan: "lớn hơn",
    Logic_Op_greaterOrEqual: "tối thiểu là",
    Logic_Op_lessThan: "nhỏ hơn",
    Logic_Op_lessOrEqual: "tối đa là",
    Logic_Op_between: "nằm giữa",
    Logic_Op_before: "trước",
    Logic_Op_after: "sau",
    Logic_Type_Text: "Câu trả lời ngắn",
    Logic_TypeDesc_Text: "Một dòng văn bản",
    Logic_Category_Text: "Văn bản",
    Logic_Type_MultilineText: "Câu trả lời dài",
    Logic_TypeDesc_MultilineText: "Nhiều dòng văn bản thuần",
    Logic_Type_RichText: "Văn bản có định dạng",
    Logic_TypeDesc_RichText: "In đậm, danh sách và liên kết",
    Logic_Type_Choice: "Lựa chọn",
    Logic_TypeDesc_Choice: "Chọn từ danh sách tùy chọn",
    Logic_Category_Choice: "Lựa chọn",
    Logic_Type_ImageChoice: "Lựa chọn hình ảnh",
    Logic_TypeDesc_ImageChoice: "Chọn từ các ô hình ảnh",
    Logic_Type_Lookup: "Tra cứu từ danh sách",
    Logic_TypeDesc_Lookup: "Các tùy chọn được đọc trực tiếp từ một danh sách SharePoint khác",
    Logic_Type_YesNo: "Có / Không",
    Logic_TypeDesc_YesNo: "Công tắc bật/tắt đơn giản",
    Logic_Type_Consent: "Đồng ý",
    Logic_TypeDesc_Consent: "Hộp kiểm mà người trả lời phải chọn để tiếp tục",
    Logic_Type_Ranking: "Xếp hạng",
    Logic_TypeDesc_Ranking: "Kéo các tùy chọn theo thứ tự ưu tiên",
    Logic_Type_Rating: "Đánh giá",
    Logic_TypeDesc_Rating: "Sao, trái tim hoặc ngón cái",
    Logic_Category_Scales: "Thang đo",
    Logic_Type_Scale: "Thang ý kiến",
    Logic_TypeDesc_Scale: "Thang đánh số có nhãn ở hai đầu",
    Logic_Type_Slider: "Thanh trượt",
    Logic_TypeDesc_Slider: "Một giá trị trên thang trượt",
    Logic_Type_Likert: "Bảng Likert",
    Logic_TypeDesc_Likert: "Đánh giá nhiều phát biểu trên cùng một thang đo",
    Logic_Type_Number: "Số",
    Logic_TypeDesc_Number: "Số thường, tiền tệ hoặc phần trăm",
    Logic_Category_Advanced: "Nâng cao",
    Logic_Type_Calculated: "Được tính toán",
    Logic_TypeDesc_Calculated: "Tổng chỉ đọc được tính từ các câu trả lời khác",
    Logic_Type_Date: "Ngày",
    Logic_TypeDesc_Date: "Một ngày trên lịch, có thể kèm giờ",
    Logic_Category_Date: "Ngày",
    Logic_Type_Time: "Giờ",
    Logic_TypeDesc_Time: "Chỉ giờ trong ngày",
    Logic_Type_Person: "Người",
    Logic_TypeDesc_Person: "Chọn một người trong tổ chức",
    Logic_Category_People: "Mọi người",
    Logic_Type_Email: "Email",
    Logic_TypeDesc_Email: "Địa chỉ email có xác thực",
    Logic_Type_Phone: "Điện thoại",
    Logic_TypeDesc_Phone: "Số điện thoại có xác thực",
    Logic_Type_Address: "Địa chỉ",
    Logic_TypeDesc_Address: "Đường, thành phố, mã bưu chính và quốc gia",
    Logic_Type_Hyperlink: "Liên kết",
    Logic_TypeDesc_Hyperlink: "Một địa chỉ web",
    Logic_Type_FileUpload: "Tải tệp lên",
    Logic_TypeDesc_FileUpload: "Đính kèm một hoặc nhiều tệp vào phản hồi",
    Logic_Type_Signature: "Chữ ký",
    Logic_TypeDesc_Signature: "Ký bằng chuột, bút hoặc ngón tay",
    Logic_Type_Content: "Khối văn bản",
    Logic_TypeDesc_Content: "Hướng dẫn hoặc hình ảnh — không thu thập câu trả lời",
    Logic_Category_Layout: "Bố cục",
    Logic_Preset_nps: "NPS (0–10)",
    Logic_PresetDesc_nps: "Bạn có khả năng giới thiệu đến mức nào…",
    Logic_Preset_satisfaction: "Mức hài lòng (1–5)",
    Logic_PresetDesc_satisfaction: "Từ rất không hài lòng đến rất hài lòng",
    Logic_Preset_currency: "Tiền tệ",
    Logic_PresetDesc_currency: "Một số tiền",
    Logic_Preset_percent: "Phần trăm",
    Logic_PresetDesc_percent: "Một giá trị phần trăm",
    Logic_Template_blank_Name: "Biểu mẫu trống",
    Logic_Template_blank_Description: "Bắt đầu từ đầu",
    Logic_Template_feedback_Name: "Phản hồi của khách hàng",
    Logic_Template_feedback_Description: "NPS, xếp hạng và nhận xét mở",
    Logic_Template_event_Name: "Đăng ký sự kiện",
    Logic_Template_event_Description: "Thông tin người tham dự, phiên và nhu cầu ăn uống",
    Logic_Template_itrequest_Name: "Yêu cầu dịch vụ CNTT",
    Logic_Template_itrequest_Description: "Yêu cầu được phân loại kèm mức ưu tiên và tệp đính kèm",
    Logic_Template_expense_Name: "Yêu cầu hoàn chi phí",
    Logic_Template_expense_Description: "Các khoản mục, biên lai và tổng được tính toán",
    Logic_Template_pulse_Name: "Khảo sát nhanh nhân viên",
    Logic_Template_pulse_Description: "Bảng Likert, thang mức độ gắn kết và ghi chú ẩn danh",
    Logic_Template_safety_Name: "Kiểm tra an toàn",
    Logic_Template_safety_Description: "Danh sách kiểm tra, ảnh và chữ ký",
    Logic_Template_booking_Name: "Đặt phòng hoặc tài nguyên",
    Logic_Template_booking_Description: "Bộ chọn tài nguyên dựa trên tra cứu với khung giờ",
    Charts_ColumnChartAria: "Biểu đồ cột với {count} danh mục",
    Charts_DonutChartAria: "Biểu đồ vành khuyên gồm {count} danh mục",
    Charts_NoAnswers: "Chưa có câu trả lời.",
    Charts_NoResponses: "Chưa có phản hồi.",
    Charts_Responses: "Phản hồi",
    Charts_ResponsesOverTime: "Phản hồi theo thời gian",
    Responses_Chart_Answer: "Câu trả lời",
    Responses_Chart_Average: "Trung bình",
    Responses_Chart_AverageOf: "Trung bình của {count}",
    Responses_Chart_AveragePosition: "Vị trí trung bình",
    Responses_Chart_AverageRange: "Trung bình (1–{max})",
    Responses_Chart_AvgValue: "TB {value}",
    Responses_Chart_Detractors: "Người phản đối (0–6)",
    Responses_Chart_Max: "Tối đa",
    Responses_Chart_Maximum: "Tối đa",
    Responses_Chart_Median: "Trung vị",
    Responses_Chart_MentionOne: "{count} lượt đề cập",
    Responses_Chart_MentionOther: "{count} lượt đề cập",
    Responses_Chart_Min: "Tối thiểu",
    Responses_Chart_Minimum: "Tối thiểu",
    Responses_Chart_NoAnswers: "Chưa có câu trả lời.",
    Responses_Chart_NoNumeric: "Chưa có câu trả lời dạng số.",
    Responses_Chart_NoRankings: "Chưa có xếp hạng.",
    Responses_Chart_NoScores: "Chưa có điểm.",
    Responses_Chart_NotEnoughText: "Chưa đủ văn bản để tóm tắt.",
    Responses_Chart_NpsScore: "Điểm NPS",
    Responses_Chart_Option: "Lựa chọn",
    Responses_Chart_Passives: "Người trung lập (7–8)",
    Responses_Chart_Promoters: "Người ủng hộ (9–10)",
    Responses_Chart_ResponseOne: "phản hồi",
    Responses_Chart_ResponseOther: "phản hồi",
    Responses_Chart_Responses: "Phản hồi",
    Responses_Chart_ShowingAnswers: "Hiển thị {shown} trên {total} câu trả lời.",
    Responses_Chart_Statement: "Phát biểu",
    Responses_Chart_Statistic: "Thống kê",
    Responses_Chart_StdDev: "Độ lệch chuẩn",
    Responses_Chart_StdDeviation: "Độ lệch chuẩn",
    Responses_Chart_Total: "Tổng",
    Responses_Chart_Value: "Giá trị",
    Responses_Dashboard_AllHidden: "Mọi câu hỏi đều bị ẩn khỏi bảng thông tin. Dùng “Hiện câu hỏi đã ẩn” để hiển thị lại.",
    Responses_Dashboard_AnsweredOf: "Đã trả lời {answered} trên {total}",
    Responses_Dashboard_AnsweredOfPinned: "Đã trả lời {answered} trên {total} · đã ghim",
    Responses_Dashboard_AveragedAcrossResponses: "Trung bình trên các phản hồi",
    Responses_Dashboard_ByDay: "Theo ngày",
    Responses_Dashboard_ByMonth: "Theo tháng",
    Responses_Dashboard_ByWeek: "Theo tuần",
    Responses_Dashboard_ChartAuto: "Tự động",
    Responses_Dashboard_ChartBars: "Thanh",
    Responses_Dashboard_ChartColumns: "Cột",
    Responses_Dashboard_ChartDonut: "Vành khuyên",
    Responses_Dashboard_ChartGauge: "Đồng hồ đo",
    Responses_Dashboard_ChartHistogram: "Biểu đồ tần suất",
    Responses_Dashboard_ChartOptions: "Tùy chọn biểu đồ",
    Responses_Dashboard_ChartOptionsFor: "Tùy chọn biểu đồ cho {title}",
    Responses_Dashboard_ChartStatistics: "Thống kê",
    Responses_Dashboard_ChartTable: "Bảng",
    Responses_Dashboard_ChartWordFrequency: "Tần suất từ",
    Responses_Dashboard_EmptyBody: "Khi mọi người bắt đầu trả lời, bảng thông tin này sẽ tự động được điền — các con số nổi bật, dòng thời gian phản hồi và biểu đồ cho những câu hỏi đáng theo dõi.",
    Responses_Dashboard_EmptyTitle: "Chưa có phản hồi",
    Responses_Dashboard_Hide: "Ẩn khỏi bảng thông tin",
    Responses_Dashboard_Highlights: "Điểm nổi bật",
    Responses_Dashboard_Last7Days: "7 ngày qua",
    Responses_Dashboard_LatestDate: "Mới nhất {date}",
    Responses_Dashboard_MedianTimeToComplete: "Thời gian hoàn thành trung vị",
    Responses_Dashboard_NoPriorWeek: "Không có tuần trước để so sánh",
    Responses_Dashboard_OneEach: "Mỗi loại một",
    Responses_Dashboard_Pin: "Ghim vào bảng thông tin",
    Responses_Dashboard_QuestionFallback: "câu hỏi",
    Responses_Dashboard_QuestionsAnswered: "Câu hỏi đã trả lời",
    Responses_Dashboard_RecordedOnSubmit: "Được ghi khi gửi",
    Responses_Dashboard_RepeatResponses: "{count} phản hồi lặp lại",
    Responses_Dashboard_ResponsesOverTime: "Phản hồi theo thời gian",
    Responses_Dashboard_ShowHidden: "Hiện câu hỏi đã ẩn",
    Responses_Dashboard_SinceMidnight: "Từ nửa đêm",
    Responses_Dashboard_Today: "Hôm nay",
    Responses_Dashboard_TotalResponses: "Tổng số phản hồi",
    Responses_Dashboard_UniqueRespondents: "Người trả lời duy nhất",
    Responses_Dashboard_Unpin: "Bỏ ghim khỏi bảng thông tin",
    Responses_Dashboard_UntitledQuestion: "Câu hỏi chưa có tiêu đề",
    Responses_Dashboard_VsPrevious7Days: "so với 7 ngày trước",
    Responses_Detail_Answers: "Câu trả lời",
    Responses_Detail_AsTheForm: "Như biểu mẫu",
    Responses_Detail_Cancel: "Hủy",
    Responses_Detail_Delete: "Xóa",
    Responses_Detail_DeleteBody: "Mục danh sách được chuyển vào thùng rác của site nên có thể khôi phục từ đó.",
    Responses_Detail_DeleteTitle: "Xóa phản hồi này?",
    Responses_Detail_Deleting: "Đang xóa…",
    Responses_Detail_Draft: "Bản nháp",
    Responses_Detail_Header: "Phản hồi {index} trên {total}",
    Responses_Detail_LoadingAttachments: "Đang tải tệp đính kèm…",
    Responses_Detail_Next: "Phản hồi tiếp theo",
    Responses_Detail_NoAnswer: "Chưa trả lời",
    Responses_Detail_Previous: "Phản hồi trước",
    Responses_Detail_Print: "In",
    Responses_Detail_Signature: "Chữ ký",
    Responses_Detail_Signed: "Đã ký",
    Responses_Detail_Took: "mất {duration}",
    Responses_Summary_AnsweredOfType: "Đã trả lời {answered} trên {total} · {type}",
    Responses_Summary_ByField: "Theo {title}",
    Responses_Summary_CompareBy: "So sánh theo…",
    Responses_Summary_EmptyBody: "Mỗi câu hỏi sẽ có phần tóm tắt riêng tại đây.",
    Responses_Summary_NoComparison: "Không so sánh",
    Responses_Summary_NothingToCompare: "Không có phản hồi nào trả lời “{title}”, nên không có gì để so sánh.",
    Responses_Summary_OtherNote: "Biểu đồ có hơn {max} danh mục sẽ gộp các mục nhỏ nhất vào “Khác” — chuyển thẻ sang Bảng để xem mọi giá trị.",
    Responses_Summary_ResponseCountOne: "{count} phản hồi",
    Responses_Summary_ResponseCountOther: "{count} phản hồi",
    Responses_Summary_SeeAllAnswers: "Xem tất cả câu trả lời trong bảng",
    Responses_Summary_SegmentNote: "Hiển thị {groups} nhóm lớn nhất. Một phản hồi chọn nhiều câu trả lời sẽ xuất hiện trong mọi nhóm khớp, nên tổng các nhóm có thể lớn hơn {total}.",
    Responses_Summary_SplitBy: "Chia theo {title}",
    Responses_Summary_Untitled: "chưa có tiêu đề",
    Responses_Table_Apply: "Áp dụng",
    Responses_Table_Cancel: "Hủy",
    Responses_Table_ClearSelection: "Xóa lựa chọn",
    Responses_Table_ColumnOrder: "Thứ tự cột",
    Responses_Table_ColumnsCount: "Cột ({shown}/{total})",
    Responses_Table_Delete: "Xóa",
    Responses_Table_DeleteBody: "Các mục danh sách được chuyển vào thùng rác của site nên có thể khôi phục từ đó.",
    Responses_Table_DeleteSelected: "Xóa mục đã chọn",
    Responses_Table_DeleteTitleOne: "Xóa {count} phản hồi?",
    Responses_Table_DeleteTitleOther: "Xóa {count} phản hồi?",
    Responses_Table_Deleting: "Đang xóa…",
    Responses_Table_MoveDown: "Di chuyển xuống",
    Responses_Table_MoveDownFor: "Di chuyển {title} xuống",
    Responses_Table_MoveUp: "Di chuyển lên",
    Responses_Table_MoveUpFor: "Di chuyển {title} lên",
    Responses_Table_NoColumns: "Chưa có cột câu hỏi nào hiển thị.",
    Responses_Table_NoMatch: "Không có phản hồi nào khớp với bộ lọc hiện tại.",
    Responses_Table_NothingToShow: "Không có gì để hiển thị",
    Responses_Table_OpenResponse: "Mở phản hồi này",
    Responses_Table_OrderNote: "Cột Đã gửi và Người gửi luôn ở đầu. Thứ tự kéo áp dụng cho các cột câu hỏi.",
    Responses_Table_Reorder: "Sắp xếp lại",
    Responses_Table_ResetColumns: "Đặt lại cột",
    Responses_Table_SelectResponse: "Chọn phản hồi này",
    Responses_Table_SelectedOne: "Đã chọn {count} phản hồi",
    Responses_Table_SelectedOther: "Đã chọn {count} phản hồi",
    Responses_Table_ShowAll: "Hiện tất cả",
    Responses_Table_ShowTheseQuestions: "Hiện các câu hỏi này",
    Responses_Table_Submitted: "Đã gửi",
    Responses_Table_SubmittedBy: "Người gửi",
    Responses_Table_ToggleSelection: "Bật/tắt lựa chọn",
    Responses_Table_Unknown: "Không xác định",
    Responses_Table_Untitled: "Chưa có tiêu đề",
    Responses_View_AllTime: "Mọi lúc",
    Responses_View_AnyAnswer: "Bất kỳ câu trả lời",
    Responses_View_Clear: "Xóa",
    Responses_View_CopyShareLink: "Sao chép liên kết chia sẻ",
    Responses_View_CountFiltered: "{shown} trên {total} phản hồi",
    Responses_View_CountOne: "{count} phản hồi",
    Responses_View_CountOther: "{count} phản hồi",
    Responses_View_Dashboard: "Bảng thông tin",
    Responses_View_DateRange: "Khoảng ngày",
    Responses_View_EmptyBody: "Hãy chia sẻ biểu mẫu để bắt đầu thu thập. Câu trả lời được lưu vào “{list}” và xuất hiện ở đây ngay lập tức.",
    Responses_View_EmptyTitle: "Chưa có phản hồi",
    Responses_View_ExportCsv: "Xuất CSV",
    Responses_View_FilterByAnswer: "Lọc theo câu trả lời",
    Responses_View_FilterByQuestion: "Lọc theo câu hỏi",
    Responses_View_FilterValue: "Giá trị bộ lọc",
    Responses_View_Last30Days: "30 ngày qua",
    Responses_View_Last7Days: "7 ngày qua",
    Responses_View_Last90Days: "90 ngày qua",
    Responses_View_LoadError: "Không thể tải phản hồi. Hãy xuất bản biểu mẫu một lần để các cột danh sách được tạo, sau đó thử lại.",
    Responses_View_Loading: "Đang tải phản hồi…",
    Responses_View_MoreActions: "Thao tác khác với phản hồi",
    Responses_View_PreviewForm: "Xem trước biểu mẫu",
    Responses_View_Refresh: "Làm mới",
    Responses_View_ResponsesTab: "Phản hồi ({count})",
    Responses_View_SearchPlaceholder: "Tìm trong tất cả câu trả lời",
    Responses_View_SegmentOption: "{label} ({count})",
    Responses_View_SelectValue: "Chọn một giá trị",
    Responses_View_Summary: "Tóm tắt",
    Responses_View_Today: "Hôm nay",
    Responses_View_Truncated: "Danh sách này có nhiều phản hồi hơn mức Smart Forms tải cùng lúc. {count} phản hồi mới nhất được hiển thị — hãy mở danh sách trong Microsoft Lists để xem đầy đủ.",
    Responses_View_TryAgain: "Thử lại",
    Responses_View_Untitled: "Chưa có tiêu đề",
    Responses_Approval_Column: "Phê duyệt",
    Responses_Approval_ReviewerColumn: "Người xem xét",
    Responses_Approval_CommentColumn: "Nhận xét của người xem xét",
    Responses_Approval_Pending: "Đang chờ",
    Responses_Approval_Approved: "Đã phê duyệt",
    Responses_Approval_Rejected: "Đã từ chối",
    Responses_Approval_AnyStatus: "Mọi trạng thái phê duyệt",
    Responses_Approval_FilterLabel: "Lọc theo trạng thái phê duyệt",
    Responses_Approval_ApproveSelected: "Phê duyệt mục đã chọn",
    Responses_Approval_RejectSelected: "Từ chối mục đã chọn",
    Responses_Approval_BulkFailed: "Không thể cập nhật {count} phản hồi. Hãy thử lại.",
    Responses_Approval_Approve: "Phê duyệt",
    Responses_Approval_Reject: "Từ chối",
    Responses_Approval_Reset: "Đặt lại về đang chờ",
    Responses_Approval_CommentLabel: "Nhận xét (tùy chọn)",
    Responses_Approval_ReviewedBy: "Được xem xét bởi {name}",
    Responses_Approval_Error: "Không thể lưu quyết định. Hãy thử lại.",
    Responses_Dashboard_ApprovalStatus: "Đang chờ xem xét",
    Responses_Dashboard_ApprovalBreakdown: "{pending} đang chờ, {approved} đã phê duyệt, {rejected} đã từ chối",
    Responses_Dashboard_TimelineCoarsened: "Phạm vi ngày dài nên dòng thời gian được nhóm thô hơn ({grain}).",
    Responses_Dashboard_TimelineTruncated: "Phạm vi ngày rất dài nên chỉ hiển thị {count} giai đoạn gần nhất.",
    Service_Item_DefaultTitle: "Phản hồi — {date}",
    Service_Email_ApprovalSubject: "Phản hồi của bạn đã được {status} — {title}",
    Service_Email_ApprovalHeading: "Phản hồi của bạn đã được {status}",
    Service_Email_ApprovalIntro: "Người xem xét đã đánh dấu phản hồi của bạn cho \"{title}\" là {status}.",
    Service_Email_ApprovalCommentLabel: "Nhận xét của người xem xét",
    Service_Approval_Approved: "phê duyệt",
    Service_Approval_Rejected: "từ chối",
    Service_Approval_Pending: "chờ xử lý",
    Service_Lookup_InvalidFilter: "Bộ lọc tra cứu không hợp lệ.",
    Service_Edit_NotAllowed: "Biểu mẫu này không cho phép chỉnh sửa phản hồi đã gửi.",
    Service_Edit_NotYours: "Bạn chỉ có thể chỉnh sửa phản hồi của chính mình.",
    Service_Signature_AttachmentLabel: "Chữ ký",
    PropertyPane_ListsLoadFailed: "Không thể tải các danh sách trên site này.",
    PropertyPane_EnterListName: "Hãy nhập tên cho danh sách mới trước.",
    PropertyPane_CreatingList: "Đang tạo \"{name}\"…",
    PropertyPane_ListCreated: "Đã tạo và chọn danh sách \"{title}\".",
    PropertyPane_ListAlreadyExists: "Đã có danh sách tên \"{name}\" — hãy chọn danh sách đó từ menu thả xuống ở trên.",
    PropertyPane_CreateListFailed: "Không thể tạo danh sách. Hãy kiểm tra bạn có quyền tạo danh sách trên site này.",
    PropertyPane_Description: "Chọn danh sách SharePoint lưu các phản hồi biểu mẫu, hoặc tạo danh sách mới. Mọi thứ khác — câu hỏi, giao diện, thông báo — được chỉnh sửa trực tiếp trên trang.",
    PropertyPane_ResponseList_GroupName: "Danh sách phản hồi",
    PropertyPane_ListDropdown_Label: "Lưu phản hồi vào danh sách này",
    PropertyPane_ResponsesGoTo: "Phản hồi được gửi đến \"{name}\".",
    PropertyPane_PickList: "Chọn một danh sách, hoặc tạo danh sách bên dưới.",
    PropertyPane_LoadingLists: "Đang tải danh sách…",
    PropertyPane_NewListName_Label: "Hoặc tạo danh sách mới",
    PropertyPane_NewListName_Placeholder: "Tên danh sách mới",
    PropertyPane_CreateList_Button: "Tạo danh sách",
    PropertyPane_Tips_GroupName: "Mẹo",
    PropertyPane_Tip_AutoSave: "Câu hỏi và cài đặt được lưu tự động khi bạn chỉnh sửa — không cần lưu hay xuất bản trang.",
    PropertyPane_Tip_Permissions: "Người trả lời cần có quyền thêm mục vào danh sách phản hồi. Hãy kiểm tra quyền của danh sách nếu ai đó báo lỗi khi gửi.",
    PropertyPane_Tip_Share: "Dùng \"Thu thập phản hồi\" trên trang để tạo các cột danh sách và nhận liên kết điền biểu mẫu có thể chia sẻ.",
    App_ErrorBoundary_Title: "Smart Forms — Lỗi hiển thị",
    App_ErrorBoundary_Message: "Thông báo:",
    App_ErrorBoundary_Stack: "Ngăn xếp:",
    App_ErrorBoundary_NoStack: "(không có ngăn xếp)",
    App_ErrorBoundary_ConsoleNote: "Chi tiết đầy đủ cũng đã được ghi vào bảng điều khiển của trình duyệt.",
    App_DefaultQuestionTitle: "Câu hỏi {number}",
    App_Error_ListMissing: "Danh sách được cấu hình cho biểu mẫu này không còn tồn tại. Hãy chọn danh sách khác trong cài đặt web part.",
    App_Error_LoadConfig: "Đã xảy ra lỗi khi tải cấu hình biểu mẫu.",
    App_Error_Unable: "Không thể tải biểu mẫu.",
    App_Publish_ConflictNotice: "\"{title}\" đã có một cột danh sách thuộc kiểu khác ({type}). Hãy đổi tên câu hỏi để có thể tạo cột mới, hoặc đổi lại kiểu của nó.",
    App_Publish_ConflictUnnamedQuestion: "một câu hỏi",
    App_Publish_ColumnsAddedOne: "Đã thêm {count} cột vào \"{list}\".",
    App_Publish_ColumnsAddedOther: "Đã thêm {count} cột vào \"{list}\".",
    App_Publish_TheList: "danh sách",
    App_Publish_UpToDate: "Danh sách phản hồi đã được cập nhật.",
    App_Publish_Error: "Không thể tạo các cột danh sách. Điều này thường có nghĩa là bạn không có quyền Quản lý danh sách trên danh sách phản hồi, nhưng cũng có thể xảy ra trên các site đã tắt tập lệnh tùy chỉnh. Hãy xem bảng điều khiển của trình duyệt để biết lỗi gốc, hoặc thử lại.",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "Xây dựng biểu mẫu chỉn chu trên nền danh sách SharePoint — {count} loại câu hỏi, logic phân nhánh, tải tệp lên, liên kết điền biểu mẫu có thể chia sẻ và bảng thông tin kết quả.",
    App_Placeholder_ChooseList: "Chọn hoặc tạo danh sách",
    App_Placeholder_Hint: "Chỉnh sửa trang và cấu hình web part này để bắt đầu.",
    App_Loading: "Đang tải biểu mẫu…",
    App_OpenSettings: "Mở cài đặt",
    App_Tab_Questions: "Câu hỏi",
    App_Tab_QuestionsWithCount: "Câu hỏi ({count})",
    App_Tab_Responses: "Phản hồi",
    App_Tab_Responses_Title: "Phản hồi được lưu vào \"{list}\"",
    App_Templates_Start: "Bắt đầu từ mẫu",
    App_Settings_Title: "Cài đặt biểu mẫu — giao diện, thông báo, truy cập",
    App_Settings_AriaLabel: "Cài đặt biểu mẫu",
    App_Preview: "Xem trước",
    App_Preview_Close: "Đóng bản xem trước",
    App_Preview_Hint: "Xem trước — mọi thứ bạn gửi ở đây sẽ không được lưu. Xác thực và phân nhánh hoạt động chính xác như với người trả lời.",
    App_Publish_GettingReady: "Đang chuẩn bị…",
    App_Publish_CollectResponses: "Thu thập phản hồi",
    App_Publish_Share: "Chia sẻ",
    App_Retry: "Thử lại",
    App_SaveError_Banner: "Không thể lưu thay đổi gần nhất của bạn. Hãy kiểm tra kết nối rồi thử lại.",
    App_Preflight_BlockingTitle: "Sửa các mục này trước khi thu thập",
    App_Preflight_WarningTitle: "Nên xem qua trước",
    App_Preflight_BlockingText: "Những mục này sẽ khiến biểu mẫu đã xuất bản không hoạt động đúng.",
    App_Preflight_WarningText: "Không có gì hỏng, nhưng thường nên sửa các mục này trước khi chia sẻ liên kết.",
    App_Preflight_GoTo: "Đi tới",
    App_Preflight_CollectAnyway: "Vẫn thu thập phản hồi",
    App_Preflight_Back: "Quay lại biểu mẫu",
    App_Cancel: "Hủy",
    App_Done: "Xong",
    App_Share_Title: "Biểu mẫu của bạn đã sẵn sàng để chia sẻ",
    App_Share_SubText: "Gửi liên kết này cho bất kỳ ai cần điền biểu mẫu.",
    App_Share_LinkAriaLabel: "Liên kết chia sẻ",
    App_Share_Copy: "Sao chép",
    App_Share_Copied: "Đã sao chép",
    App_Share_AddItemsEmphasis: "thêm mục",
    App_Share_PermissionNote: "Người trả lời cần có quyền {addItems} vào “{title}” và quyền truy cập trang này. Nếu ai đó gặp lỗi khi gửi, hầu như luôn là vì lý do này.",
    App_Share_PrefillNote: "Bạn có thể trả lời trước các câu hỏi trong liên kết bằng cách thêm tên cột, ví dụ {example}.",
    App_Templates_ReplaceWarning: "Chọn một mẫu sẽ thay thế các câu hỏi hiện có của bạn.",
    App_Templates_PickStart: "Chọn điểm khởi đầu — bạn có thể thay đổi mọi thứ sau đó.",
    App_Templates_Empty: "Trống",
    App_Templates_QuestionCount: "{count} câu hỏi",
    App_SaveChip_SavingTitle: "Đang lưu chỉnh sửa mới nhất của bạn",
    App_SaveChip_Saving: "Đang lưu…",
    App_SaveChip_FailedTitle: "Không thể lưu chỉnh sửa gần nhất của bạn. Hãy kiểm tra kết nối rồi thử lại.",
    App_SaveChip_Failed: "Lưu không thành công",
    App_SaveChip_SavedTitle: "Tất cả thay đổi đã được lưu",
    App_SaveChip_Saved: "Đã lưu",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "Phản hồi mới — {title}",
    Service_Email_NewResponseHeading: "Phản hồi mới: {title}",
    Service_Email_NewResponseIntro: "Có người vừa gửi một phản hồi — {date}.",
    Service_Email_ReceiptSubject: "Phản hồi của bạn — {title}",
    Service_Email_ReceiptHeading: "Cảm ơn bạn đã phản hồi!",
    Service_Email_ReceiptIntro: "Đây là bản sao nội dung bạn đã gửi tới \"{title}\".",
    App_History_Title: "Lịch sử phiên bản",
    App_History_RestoredNotice: "Đã khôi phục phiên bản được lưu vào {date}. Hãy xem lại, sau đó dùng Thu thập phản hồi để xuất bản các câu hỏi mới.",
    App_History_Undo: "Hoàn tác khôi phục",
    App_Share_CopyManual: "Trình duyệt của bạn đã chặn việc sao chép. Chọn liên kết ở trên và nhấn Ctrl+C (Cmd+C trên máy Mac) để sao chép.",
    App_Share_TeamsNote: "Bạn đang ở trong Microsoft Teams. Liên kết này mở trực tiếp trang SharePoint, vì vậy người nhận cần có quyền truy cập vào site.",
    App_Share_PrefillNotSecure: "Câu trả lời điền sẵn chỉ mang tính tiện lợi: bất kỳ ai có liên kết đều có thể thay đổi, vì vậy đừng bao giờ coi đó là ranh giới bảo mật.",
    Designer_Section_DropHere: "Thả câu hỏi vào đây",
    Designer_Section_DropEnd: "Thả vào đây để chuyển đến cuối phần này",
    Designer_Rules_RemovedOne: "Đã xóa 1 quy tắc rẽ nhánh không còn phù hợp.",
    Designer_Rules_RemovedOther: "Đã xóa {count} quy tắc rẽ nhánh không còn phù hợp.",
    Designer_Settings_AllowEdit: "Cho phép người trả lời chỉnh sửa phản hồi của họ",
    Designer_Settings_AllowEditHint: "Người trả lời có thể mở lại và cập nhật nội dung đã gửi. Mỗi người chỉ có thể chỉnh sửa phản hồi của chính mình.",
    Designer_Settings_EnableApproval: "Bật quy trình phê duyệt",
    Designer_Settings_ApprovalNotify: "Gửi email cho người trả lời khi có quyết định",
    Designer_Settings_ApprovalHint: "Thêm các cột phê duyệt vào danh sách phản hồi vào lần xuất bản tiếp theo. Chủ sở hữu phê duyệt hoặc từ chối phản hồi từ tab Phản hồi.",
    Designer_History_Title: "Lịch sử phiên bản",
    Designer_History_Intro: "Các phiên bản đã lưu trước đó của câu hỏi và cài đặt của biểu mẫu này. Khôi phục sẽ tải một phiên bản vào trình thiết kế; bạn có thể hoàn tác, và câu hỏi mới chỉ được tạo khi bạn xuất bản.",
    Designer_History_Loading: "Đang tải các phiên bản...",
    Designer_History_Empty: "Không tìm thấy phiên bản trước đó. Lịch sử phiên bản cần bật tính năng tạo phiên bản cho danh sách \"Smart Forms Config\" và có ít nhất một lần chỉnh sửa đã lưu.",
    Designer_History_Latest: "Mới nhất",
    Designer_History_LatestTitle: "Đây là phiên bản đang được sử dụng",
    Designer_History_By: "bởi {name}",
    Designer_History_UnknownAuthor: "Tác giả không xác định",
    Designer_History_VersionLabel: "phiên bản {label}",
    Designer_History_Preview: "Xem trước",
    Designer_History_Restore: "Khôi phục",
    Designer_History_QuestionsOne: "1 câu hỏi",
    Designer_History_QuestionsOther: "{count} câu hỏi",
    Designer_History_LoadFailed: "Không thể tải phiên bản này.",
    Designer_History_ConfirmTitle: "Khôi phục phiên bản này?",
    Designer_History_ConfirmText: "Biểu mẫu sẽ được thay bằng phiên bản đã lưu vào {date} ({count} câu hỏi). Bạn có thể hoàn tác ngay sau đó."
  };
});
