define([], function () {
  return {
    Designer_Color_Blue: "蓝色",
    Designer_Color_Teal: "青色",
    Designer_Color_Green: "绿色",
    Designer_Color_Purple: "紫色",
    Designer_Color_Magenta: "洋红色",
    Designer_Color_Red: "红色",
    Designer_Color_Orange: "橙色",
    Designer_Color_Gray: "灰色",
    Designer_Settings_LayoutSinglePage: "所有问题在同一页",
    Designer_Settings_LayoutWizard: "每步一个部分（向导）",
    Designer_Settings_Title: "表单设置",
    Designer_Common_Apply: "应用",
    Designer_Common_Cancel: "取消",
    Designer_Settings_TabBasics: "基本",
    Designer_Settings_FormTitle: "表单标题",
    Designer_Settings_Description: "说明",
    Designer_Settings_Layout: "布局",
    Designer_Settings_NumberQuestions: "为问题编号",
    Designer_Settings_ShuffleQuestions: "为每位答题者随机排列问题顺序",
    Designer_Settings_ShowProgressBar: "显示进度条",
    Designer_Settings_TabAppearance: "外观",
    Designer_Settings_AccentColor: "强调色",
    Designer_Settings_CustomColorTitle: "自定义颜色",
    Designer_Settings_CustomColorAria: "自定义强调色",
    Designer_Settings_AccentHint: "强调色会在深色站点上自动调整对比度，因此无论页面使用哪种主题，表单都保持清晰易读。",
    Designer_Settings_ShowHeader: "显示表单标题栏",
    Designer_Settings_HeaderIcon: "标题栏图标",
    Designer_Settings_TabAfterSubmit: "提交后",
    Designer_Settings_SubmitButtonText: "提交按钮文本",
    Designer_Settings_SubmitPlaceholder: "提交",
    Designer_Settings_ThankYouTitle: "感谢标题",
    Designer_Settings_ThankYouPlaceholder: "谢谢！",
    Designer_Settings_ThankYouMessage: "感谢消息",
    Designer_Settings_ShowSubmitAnother: "显示“再次提交响应”按钮",
    Designer_Settings_TabNotifications: "通知",
    Designer_Settings_EmailEachResponseTo: "将每个响应通过电子邮件发送给",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "组织中的人员将通过电子邮件收到每个响应，并附有列表项的链接",
    Designer_Settings_RespondentReceipt: "通过电子邮件向答题者发送其答案的副本",
    Designer_Settings_NotificationsInfo: "通知使用 SharePoint 自带的邮件服务，因此收件人必须是组织中的用户。外部地址会被静默丢弃。",
    Designer_Settings_TabAccess: "访问",
    Designer_Settings_OpenFrom: "开放时间起",
    Designer_Settings_OpenImmediately: "立即开放",
    Designer_Settings_CloseAfter: "关闭时间",
    Designer_Settings_NeverClose: "永不关闭",
    Designer_Settings_ClearDates: "清除日期",
    Designer_Settings_DatesInverted: "关闭日期等于或早于开放日期，因此表单将永远不会接受响应。",
    Designer_Settings_MaxResponses: "达到此响应数后停止",
    Designer_Settings_NoLimit: "无限制",
    Designer_Settings_OneResponsePerPerson: "每人仅允许一个响应",
    Designer_Settings_AllowSaveDraft: "允许答题者保存草稿并稍后完成",
    Designer_Settings_ClosedMessage: "表单关闭时显示的消息",
    Designer_Settings_ClosedMessagePlaceholder: "此表单不再接受响应。",
    Designer_Settings_AccessInfo: "这些限制由表单强制执行，而非 SharePoint。任何有权向响应列表添加项的人仍可直接通过列表添加。",
    Designer_Field_StyleInfo: "信息（强调色）",
    Designer_Field_StyleSuccess: "成功（绿色）",
    Designer_Field_StyleWarning: "警告（琥珀色）",
    Designer_Field_StylePlain: "纯文本",
    Designer_Field_StyleDivider: "分隔线",
    Designer_Field_IconStars: "星形",
    Designer_Field_IconHearts: "心形",
    Designer_Field_IconThumbs: "点赞",
    Designer_Field_FormatPlain: "纯数字",
    Designer_Field_FormatCurrency: "货币",
    Designer_Field_FormatPercent: "百分比",
    Designer_Field_UntitledQuestion: "无标题问题",
    Designer_Field_DeletedQuestion: "已删除的问题",
    Designer_Rule_Unary: "“{name}”{operator}",
    Designer_Rule_Between: "“{name}”{operator} {value} 和 {value2}",
    Designer_Rule_Binary: "“{name}”{operator}“{value}”",
    Designer_Rule_JoinAny: "或",
    Designer_Rule_JoinAll: "且",
    Designer_Rule_Preview: "当{conditions}时显示。",
    Designer_Field_Yes: "是",
    Designer_Field_No: "否",
    Designer_Field_When: "当",
    Designer_Field_SelectValue: "选择值",
    Designer_Field_DateValuePlaceholder: "YYYY-MM-DD 或 \"today\"",
    Designer_Field_ValuePlaceholder: "值",
    Designer_Field_UpperBound: "上限",
    Designer_Field_RemoveCondition: "删除此条件",
    Designer_Field_FormulaInvalid: "无法计算此公式。请检查括号和运算符。",
    Designer_Field_FormulaMissing: "这些问题不存在：{names}。",
    Designer_Field_FormulaPreview: "当每个输入均为 10 时，此处显示 {value}。",
    Designer_Field_HintYesNo: "使用 \"yes\" 或 \"no\"",
    Designer_Field_HintMultiDefault: "用 ; 分隔多个默认值",
    Designer_Field_HintSingleDefault: "必须与其中一个选项匹配",
    Designer_Field_HintDate: "使用 \"today\",或类似 2026-03-01 的日期",
    Designer_Field_HintTime: "使用 \"now\",或类似 09:30 的时间",
    Designer_Field_QuestionSettings: "问题设置",
    Designer_Field_Appearance: "外观",
    Designer_Field_Style: "样式",
    Designer_Field_ImageUrl: "图像 URL（可选）",
    Designer_Field_Content: "内容",
    Designer_Field_BasicFormatting: "允许基本格式：粗体、斜体、列表和链接。",
    Designer_Field_TabOptions: "选项",
    Designer_Field_TabBranching: "分支",
    Designer_Field_BranchingNeedsQuestion: "请先添加另一个问题 — 分支需要有可依赖的内容。",
    Designer_Field_BranchingToggle: "仅当其他答案匹配时才显示此问题",
    Designer_Field_Match: "匹配",
    Designer_Field_MatchAll: "所有条件",
    Designer_Field_MatchAny: "任一条件",
    Designer_Field_AddCondition: "添加条件",
    Designer_Field_TabValidation: "验证",
    Designer_Field_HelpText: "帮助文本",
    Designer_Field_HelpTextPlaceholder: "显示在问题标签下方",
    Designer_Field_CheckboxLabel: "复选框标签",
    Designer_Field_Placeholder: "占位符",
    Designer_Field_DefaultAnswer: "默认答案",
    Designer_Field_RequiredMessage: "自定义必填消息",
    Designer_Field_RequiredMessagePlaceholder: "{title}为必填项",
    Designer_Field_ThisQuestion: "此问题",
    Designer_Field_RequiredMessageDescription: "此问题留空时显示，以替代标准消息",
    Designer_Field_ReadOnly: "只读（答案只能来自预填充链接）",
    Designer_Field_ValidationRules: "验证规则",
    Designer_Field_MaxLength: "最大长度",
    Designer_Field_Pattern: "必须匹配此模式",
    Designer_Field_PatternDescription: "正则表达式。留空则不检查模式。",
    Designer_Field_PatternMessage: "模式不匹配时的消息",
    Designer_Field_PatternMessagePlaceholder: "此答案的格式不符合要求",
    Designer_Field_Format: "格式",
    Designer_Field_UnitSuffix: "显示在值之后的单位",
    Designer_Field_UnitSuffixPlaceholder: "kg、小时、件…",
    Designer_Field_Minimum: "最小值",
    Designer_Field_Maximum: "最大值",
    Designer_Field_Decimals: "小数位数",
    Designer_Field_Formula: "公式",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "通过花括号中的问题文本引用其他问题。支持 + - * / ( ) 以及 round、min、max、sum、avg。",
    Designer_Field_AvailableQuestions: "可用问题：{questions}",
    Designer_Field_NoneYet: "暂无",
    Designer_Field_Step: "步长",
    Designer_Field_From: "从",
    Designer_Field_To: "到",
    Designer_Field_LowLabel: "低端标签",
    Designer_Field_LowLabelPlaceholder: "完全不可能",
    Designer_Field_HighLabel: "高端标签",
    Designer_Field_HighLabelPlaceholder: "极有可能",
    Designer_Field_SummarizeAs: "汇总方式",
    Designer_Field_SummarizeAverage: "平均值和分布",
    Designer_Field_SummarizeNps: "净推荐值（需要 0–10 量表）",
    Designer_Field_NpsWarning: "净推荐值仅在 0–10 量表上才有意义。请将“从”设为 0,“到”设为 10。",
    Designer_Field_NumberOfIcons: "图标数量",
    Designer_Field_Icon: "图标",
    Designer_Field_AllowHalf: "允许半值",
    Designer_Field_ShowOptionsAs: "选项显示为",
    Designer_Field_DisplayButtons: "内联按钮",
    Designer_Field_DisplayDropdown: "下拉列表",
    Designer_Field_DisplayAutomatic: "自动（最多 6 个选项时内联）",
    Designer_Field_AllowOther: "添加可手动填写的“其他”选项",
    Designer_Field_OtherLabel: "“其他”选项的标签",
    Designer_Field_OtherPlaceholder: "其他",
    Designer_Field_ShuffleOptions: "为每位答题者随机排列选项顺序",
    Designer_Field_MinSelections: "最少选择数",
    Designer_Field_MaxSelections: "最多选择数",
    Designer_Field_SourceList: "源列表",
    Designer_Field_ChooseList: "选择列表",
    Designer_Field_LookupColumn: "用于读取选项的列",
    Designer_Field_ChooseColumn: "选择列",
    Designer_Field_ChooseListFirst: "请先选择列表",
    Designer_Field_LookupFilter: "筛选器（可选）",
    Designer_Field_LookupFilterDescription: "用于缩小哪些源项成为选项的 OData 筛选器",
    Designer_Field_LookupInfo: "答案存储的是选项文本，而非指向源项的链接，因此即使源列表日后发生变化，响应仍然可读。",
    Designer_Field_ConsentText: "复选框上方显示的条款",
    Designer_Field_AllowMultiplePeople: "允许多人",
    Designer_Field_AllowGroups: "同时允许组",
    Designer_Field_IncludeTime: "包含具体时间",
    Designer_Field_TimeStep: "时间步长（分钟）",
    Designer_Field_MaxFiles: "最大文件数",
    Designer_Field_MaxFileSize: "每个文件最大大小（MB）",
    Designer_Field_AcceptedTypes: "接受的文件类型",
    Designer_Field_AcceptedTypesDescription: "以逗号分隔的扩展名。留空则接受 SharePoint 允许的所有类型。",
    Designer_Field_FilesInfo: "文件将作为附件保存在响应项上。无论您在此处允许什么，SharePoint 都会阻止某些扩展名（如 .exe）。",
    Designer_Field_Rows: "行",
    Designer_Field_ProvisionedNote: "此问题已有列表列（{name}）。更改列类型的设置已锁定 — 如需其他类型，请复制该问题。",
    Designer_Category_Text: "文本",
    Designer_Category_Choice: "选择",
    Designer_Category_Scales: "量表",
    Designer_Category_Date: "日期",
    Designer_Category_People: "人员",
    Designer_Category_Advanced: "高级",
    Designer_Category_Layout: "布局",
    Designer_Menu_CommonPresets: "常用预设",
    Designer_Menu_AllTypes: "所有问题类型",
    Designer_Menu_ChangeType: "更改类型",
    Designer_Menu_TypeLockedTitle: "列表列已存在，因此类型已锁定。请复制该问题以更改类型。",
    Designer_Menu_MoreSettings: "分支、验证及更多",
    Designer_Menu_InsertBelow: "在下方插入问题",
    Designer_Card_Duplicate: "复制",
    Designer_Card_DeleteQuestion: "删除问题",
    Designer_Outline_Aria: "问题大纲",
    Designer_Outline_QuestionCountOne: "{count} 个问题",
    Designer_Outline_QuestionCountOther: "{count} 个问题",
    Designer_Outline_IssuesTitle: "{count} 个待检查的问题",
    Designer_Outline_Find: "查找问题",
    Designer_Outline_Empty: "暂无问题。",
    Designer_Section_DefaultTitle: "第 {number} 部分",
    Designer_Card_Question: "问题",
    Designer_Card_BranchingTitle: "此问题仅在分支规则匹配时才会显示",
    Designer_Card_BranchingChip: "分支",
    Designer_Card_LiveTitle: "列表列已存在，因此类型已锁定",
    Designer_Card_LiveChip: "已上线",
    Designer_Card_CheckChip: "检查",
    Designer_Option_Placeholder: "选项 {number}",
    Designer_Option_LabelAria: "选项 {number} 标签",
    Designer_Option_ImageUrl: "图像 URL",
    Designer_Option_ImageUrlAria: "选项 {number} 图像 URL",
    Designer_Option_Remove: "删除选项",
    Designer_Option_RemoveAria: "删除选项 {number}",
    Designer_Option_Add: "添加选项",
    Designer_Option_OtherHint: "答题者还可以手动填写标为“{label}”的答案。",
    Designer_Option_OtherFallback: "其他",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "删除",
    Designer_Grid_RemoveAria: "删除 {label} {number}",
    Designer_Grid_Statements: "陈述",
    Designer_Grid_Scale: "量表",
    Designer_Grid_AddStatement: "添加陈述",
    Designer_Grid_AddScale: "添加量表",
    Designer_Width_Full: "全宽",
    Designer_Width_Half: "半宽",
    Designer_Width_Third: "三分之一宽",
    Designer_Width_Aria: "问题宽度",
    Designer_Card_BlockLabelPlaceholder: "块标签（不向答题者显示）",
    Designer_Card_QuestionText: "问题文本",
    Designer_Card_MoveUp: "上移",
    Designer_Card_MoveQuestionUp: "上移问题",
    Designer_Card_MoveDown: "下移",
    Designer_Card_MoveQuestionDown: "下移问题",
    Designer_Card_DuplicateQuestion: "复制问题",
    Designer_Card_MultipleAnswers: "多个答案",
    Designer_Card_Required: "必填",
    Designer_Card_MoreOptions: "更多选项",
    Designer_Card_MoreOptionsAria: "此问题的更多选项",
    Designer_Canvas_FormTitle: "表单标题",
    Designer_Canvas_DescriptionPlaceholder: "添加说明（可选）",
    Designer_Canvas_DescriptionAria: "表单说明",
    Designer_Canvas_EmptyTitle: "添加第一个问题",
    Designer_Canvas_EmptyBody: "选择问题类型即可开始。您可以通过拖动来重新排序问题，还可以添加分支，让人们只看到与自己相关的内容。",
    Designer_Section_Chip: "第 {number} 部分，共 {total} 部分",
    Designer_Section_TitlePlaceholder: "部分标题",
    Designer_Section_TitleAria: "第 {number} 部分标题",
    Designer_Section_DescriptionPlaceholder: "说明（可选）",
    Designer_Section_DescriptionAria: "第 {number} 部分说明",
    Designer_Section_MoveUp: "上移部分",
    Designer_Section_MoveDown: "下移部分",
    Designer_Section_Delete: "删除部分",
    Designer_Card_DragToReorder: "拖动以重新排序",
    Designer_Card_ReorderAria: "重新排序{title}",
    Designer_Card_ReorderFallback: "问题",
    Designer_Canvas_AddNew: "新增",
    Designer_Canvas_AddSection: "添加部分",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "街道地址",
    Form_Address_Street2Placeholder: "公寓、套房等（可选）",
    Form_Address_CityPlaceholder: "城市",
    Form_Address_StatePlaceholder: "省/自治区/直辖市",
    Form_Address_PostalCodePlaceholder: "邮政编码",
    Form_Address_CountryPlaceholder: "国家/地区",
    Form_Address_StreetAria: "街道地址",
    Form_Address_Street2Aria: "地址第 2 行",
    Form_Address_CityAria: "城市",
    Form_Address_StateAria: "省/自治区/直辖市",
    Form_Address_PostalCodeAria: "邮政编码",
    Form_Address_CountryAria: "国家/地区",
    Form_Consent_DefaultLabel: "我同意",
    Form_Likert_RadioAria: "{row}:{column}",
    Form_Likert_RowsAnswered: "已回答 {answered}/{total} 行",
    Form_Lookup_LoadError: "无法加载此问题的选项。",
    Form_Lookup_Loading: "正在加载选项…",
    Form_Lookup_SelectOptionsPlaceholder: "选择选项",
    Form_Lookup_SelectOptionPlaceholder: "选择一个选项",
    Form_Person_Placeholder: "开始键入姓名…",
    Form_Person_SuggestedPeopleAndGroups: "建议的人员和组",
    Form_Person_SuggestedPeople: "建议的人员",
    Form_Person_NoPeopleOrGroups: "未找到人员或组",
    Form_Person_NoPeople: "未找到人员",
    Form_Person_Searching: "正在搜索…",
    Form_Ranking_Moved: "{item} 已移至第 {position} 位（共 {total} 位）",
    Form_Ranking_MoveUp: "上移",
    Form_Ranking_MoveDown: "下移",
    Form_Ranking_MoveItemUpAria: "上移 {item}",
    Form_Ranking_MoveItemDownAria: "下移 {item}",
    Form_Rating_ValueText: "{value}/{max}",
    Form_Rating_NotRated: "未评分",
    Form_Rating_Clear: "清除评分",
    Form_RichText_Bold: "粗体",
    Form_RichText_Italic: "斜体",
    Form_RichText_Underline: "下划线",
    Form_RichText_BulletedList: "项目符号列表",
    Form_RichText_NumberedList: "编号列表",
    Form_RichText_ClearFormatting: "清除格式",
    Form_RichText_ToolbarAria: "文本格式",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "已跳过“{name}” — 上限为 {limit}。",
    Form_File_TypeNotAccepted: "“{name}”不是可接受的类型。",
    Form_File_TooLarge: "“{name}”大于 {size} MB。",
    Form_File_AlreadyAttached: "“{name}”已附加。",
    Form_File_ReadError: "无法读取其中一个文件。请尝试重新附加。",
    Form_File_HintMaxSize: "每个最大 {size} MB",
    Form_File_HintOneFile: "1 个文件",
    Form_File_HintMaxFiles: "最多 {count} 个文件",
    Form_File_Reading: "正在读取文件…",
    Form_File_DropPrompt: "将文件拖放到此处，或单击浏览",
    Form_File_Remove: "删除 {name}",
    Form_Signature_Alt: "签名",
    Form_Signature_AriaSigned: "{label} — 已签名",
    Form_Signature_AriaEmpty: "{label} — 空",
    Form_Signature_Clear: "清除",
    Form_Signature_Signed: "已签名",
    Form_Signature_Prompt: "使用鼠标、手写笔或手指在上方签名",
    Form_Time_Placeholder: "选择时间",
    Form_Field_DatePlaceholder: "选择日期",
    Form_Field_TimeAriaWithLabel: "{label} — 时间",
    Form_Field_TimeAria: "时间",
    Form_Field_OtherDefault: "其他",
    Form_Field_SelectOptionsPlaceholder: "选择选项",
    Form_Field_PleaseSpecify: "请说明",
    Form_Field_OtherSpecifyAria: "{label} — 请说明",
    Form_Field_SelectOptionPlaceholder: "选择一个选项",
    Form_Field_Yes: "是",
    Form_Field_No: "否",
    Form_Field_SliderHint: "拖动滑块进行回答",
    Form_Field_WebAddressAriaWithLabel: "{label} — 网址",
    Form_Field_WebAddressAria: "网址",
    Form_Field_DisplayTextPlaceholder: "显示文本（可选）",
    Form_Field_DisplayTextAriaWithLabel: "{label} — 显示文本",
    Form_Field_DisplayTextAria: "显示文本",
    Form_Field_ChooseBetween: "请选择 {min} 到 {max} 项",
    Form_Field_ChooseAtLeast: "请至少选择 {min} 项",
    Form_Field_ChooseUpTo: "最多选择 {max} 项",
    Form_Field_SelectedCount: "已选择 {count} 项",
    Form_Field_RequiredAria: "（必填）",
    Form_Submit_SaveError: "无法保存您的响应。请确保已从设计器发布表单，并且您有权向响应列表添加项。",
    Form_Empty_Message: "此表单尚无任何问题。表单所有者可以在“问题”选项卡中添加。",
    Form_Checking: "正在检查表单…",
    Form_Closed_NotYetOpen: "尚未开放",
    Form_Closed_AlreadyAnswered: "已回答",
    Form_Closed_Title: "表单已关闭",
    Form_Confirmation_PreviewNotice: "这是预览 — 未向响应列表保存任何内容。",
    Form_Confirmation_PreviewAgain: "再次预览",
    Form_Confirmation_SubmitAnother: "再次提交响应",
    Form_Wizard_StepFallback: "步骤 {step}",
    Form_Wizard_StepsAria: "表单步骤",
    Form_Wizard_StepOf: "第 {step} 步，共 {total} 步",
    Form_ErrorSummary_Title: "请检查 {count} 个答案：",
    Form_ErrorSummary_UntitledQuestion: "无标题问题",
    Form_ErrorSummary_Question: "问题",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "上一步",
    Form_Nav_Next: "下一步",
    Form_Draft_Saving: "正在保存…",
    Form_Draft_Saved: "草稿已保存",
    Form_Draft_SaveAndFinishLater: "保存并稍后完成",
    Form_Draft_NotSaved: "草稿未保存",
    Form_Submit_Preview: "提交（预览）",
    Form_Submit_Button: "提交",
    Form_Response_NoAnswer: "无答案",
    Form_Signature_TypeLabel: "输入您的全名",
    Form_Signature_TypeInstead: "改为输入姓名",
    Form_Signature_DrawInstead: "改为手绘",
    Form_Edit_Button: "编辑您之前的响应",
    Form_Edit_Available: "您已提交过响应。可以编辑该响应，而无需提交新响应。",
    Form_Edit_Banner: "您正在编辑之前的响应。",
    Form_Edit_Save: "更新响应",
    Form_Edit_UpdatedTitle: "响应已更新",
    Form_Edit_UpdatedMessage: "您的更改已保存。",
    Form_Edit_LoadError: "无法加载您之前的响应。请重试。",
    Form_Draft_MissingFiles: "请重新附加：{names}。这些文件无法恢复。",
    Form_Attachments_Failed: "您的答案已保存，但以下附件无法上传：{names}。请重试或联系表单所有者。",
    Logic_ThisQuestion: "此问题",
    Logic_Required: "{label}为必填项",
    Logic_RequiredConsent: "请选中复选框以继续",
    Logic_RequiredFile: "请至少附加一个文件",
    Logic_RequiredSignature: "请添加您的签名",
    Logic_RequiredLikert: "请回答每一行",
    Logic_InvalidEmail: "请输入有效的电子邮件地址",
    Logic_InvalidPhone: "请输入有效的电话号码",
    Logic_InvalidUrl: "请输入以 http:// 或 https:// 开头的有效网址",
    Logic_MinValue: "值不能小于 {value}",
    Logic_MaxValue: "值不能大于 {value}",
    Logic_MaxLength: "最大长度为 {max} 个字符",
    Logic_ChooseAtLeastOne: "至少选择 {count} 个选项",
    Logic_ChooseAtLeastMany: "至少选择 {count} 个选项",
    Logic_ChooseAtMostOne: "最多选择 {count} 个选项",
    Logic_ChooseAtMostMany: "最多选择 {count} 个选项",
    Logic_LikertRemaining: "请回答每一行（还剩 {count} 行）",
    Logic_MaxFilesOne: "最多附加 {count} 个文件",
    Logic_MaxFilesMany: "最多附加 {count} 个文件",
    Logic_FileTooLarge: "“{name}”大于 {size} MB",
    Logic_FileTypeNotAccepted: "“{name}”不是可接受的文件类型（{types}）",
    Logic_AddressRequired: "请至少输入街道和城市",
    Logic_PatternDefault: "此答案格式不符合要求",
    Logic_Yes: "是",
    Logic_No: "否",
    Logic_Agreed: "已同意",
    Logic_NotAgreed: "未同意",
    Logic_Signed: "已签名",
    Logic_NoAnswer: "（无答案）",
    Logic_Unknown: "（未知）",
    Logic_OtherSlice: "其他（{count}）",
    Logic_CsvResponseId: "响应 ID",
    Logic_CsvSubmitted: "提交时间",
    Logic_CsvSubmittedBy: "提交者",
    Logic_EmailQuestion: "问题",
    Logic_EmailViewItem: "在 Microsoft Lists 中查看",
    Logic_EmailFooter: "由 Smart Forms 自动发送。",
    Logic_ClosedDefault: "此表单不再接受响应。",
    Logic_NotYetOpen: "此表单将于 {date} 开放。",
    Logic_AlreadyResponded: "您已响应过此表单。谢谢！",
    Logic_UntitledQuestion: "无标题问题",
    Logic_Issue_NoQuestions: "收集响应之前，请至少添加一个问题。",
    Logic_Issue_NoTitle: "有一个问题没有文本，发布时将自动为其命名。",
    Logic_Issue_DuplicateTitle: "{label}与另一个问题的文本相同，这会使结果更难阅读。",
    Logic_Issue_NeedTwoOptions: "{label}至少需要两个选项。",
    Logic_Issue_ImageNoImage: "{label}中有选项没有图片，它们将显示为文本磁贴。",
    Logic_Issue_LikertNeedRow: "{label}至少需要一行。",
    Logic_Issue_LikertNeedColumns: "{label}至少需要两个量表列。",
    Logic_Issue_NoLookupList: "{label}未选择源列表。",
    Logic_Issue_NoFormula: "{label}没有公式。",
    Logic_Issue_BadFormula: "{label}的公式无法计算。请检查括号和运算符。",
    Logic_Issue_MissingRefs: "{label}引用了不存在的问题：{names}。",
    Logic_Issue_BadPattern: "{label}的验证模式无效。",
    Logic_Issue_BrokenRule: "{label}有一条分支规则指向已删除的问题。",
    Logic_Issue_SelfRule: "{label}有一条引用自身的分支规则。",
    Logic_Issue_RuleMismatch: "{label}有一条分支规则与其所依赖的问题不再匹配。",
    Logic_Issue_RequiredReadOnly: "{label}既为必填又为只读，因此只能通过预填链接作答。",
    Logic_Issue_EmptySection: "有一个部分没有问题，将被跳过。",
    Logic_Issue_CloseBeforeOpen: "关闭日期等于或早于开放日期，因此表单将永远不会接受响应。",
    Logic_Issue_ApprovalNotifyWithoutApproval: "审批电子邮件已开启，但审批步骤已关闭。",
    Logic_Op_equals: "等于",
    Logic_Op_notEquals: "不等于",
    Logic_Op_contains: "包含",
    Logic_Op_notContains: "不包含",
    Logic_Op_notEmpty: "已回答",
    Logic_Op_empty: "未回答",
    Logic_Op_greaterThan: "大于",
    Logic_Op_greaterOrEqual: "至少为",
    Logic_Op_lessThan: "小于",
    Logic_Op_lessOrEqual: "至多为",
    Logic_Op_between: "介于",
    Logic_Op_before: "早于",
    Logic_Op_after: "晚于",
    Logic_Type_Text: "简答",
    Logic_TypeDesc_Text: "单行文本",
    Logic_Category_Text: "文本",
    Logic_Type_MultilineText: "长答",
    Logic_TypeDesc_MultilineText: "多行纯文本",
    Logic_Type_RichText: "格式化文本",
    Logic_TypeDesc_RichText: "粗体、列表和链接",
    Logic_Type_Choice: "选择",
    Logic_TypeDesc_Choice: "从选项列表中选取",
    Logic_Category_Choice: "选择",
    Logic_Type_ImageChoice: "图片选择",
    Logic_TypeDesc_ImageChoice: "从图片磁贴中选取",
    Logic_Type_Lookup: "列表查阅",
    Logic_TypeDesc_Lookup: "实时读取另一个 SharePoint 列表中的选项",
    Logic_Type_YesNo: "是 / 否",
    Logic_TypeDesc_YesNo: "简单的开关切换",
    Logic_Type_Consent: "同意",
    Logic_TypeDesc_Consent: "答题者必须选中才能继续的复选框",
    Logic_Type_Ranking: "排名",
    Logic_TypeDesc_Ranking: "将选项拖动到偏好顺序",
    Logic_Type_Rating: "评分",
    Logic_TypeDesc_Rating: "星形、心形或拇指",
    Logic_Category_Scales: "量表",
    Logic_Type_Scale: "意见量表",
    Logic_TypeDesc_Scale: "两端带标签的数字量表",
    Logic_Type_Slider: "滑块",
    Logic_TypeDesc_Slider: "滑动量表上的值",
    Logic_Type_Likert: "李克特网格",
    Logic_TypeDesc_Likert: "在同一量表上对多个陈述评分",
    Logic_Type_Number: "数字",
    Logic_TypeDesc_Number: "纯数字、货币或百分比",
    Logic_Category_Advanced: "高级",
    Logic_Type_Calculated: "计算",
    Logic_TypeDesc_Calculated: "根据其他答案得出的只读合计",
    Logic_Type_Date: "日期",
    Logic_TypeDesc_Date: "日历日期，可选包含时间",
    Logic_Category_Date: "日期",
    Logic_Type_Time: "时间",
    Logic_TypeDesc_Time: "单独的一天中的时间",
    Logic_Type_Person: "人员",
    Logic_TypeDesc_Person: "从组织中选取某人",
    Logic_Category_People: "人员",
    Logic_Type_Email: "电子邮件",
    Logic_TypeDesc_Email: "电子邮件地址，经过验证",
    Logic_Type_Phone: "电话",
    Logic_TypeDesc_Phone: "电话号码，经过验证",
    Logic_Type_Address: "地址",
    Logic_TypeDesc_Address: "街道、城市、邮政编码和国家/地区",
    Logic_Type_Hyperlink: "链接",
    Logic_TypeDesc_Hyperlink: "网址",
    Logic_Type_FileUpload: "文件上传",
    Logic_TypeDesc_FileUpload: "将一个或多个文件附加到响应",
    Logic_Type_Signature: "签名",
    Logic_TypeDesc_Signature: "用鼠标、笔或手指签名",
    Logic_Type_Content: "文本块",
    Logic_TypeDesc_Content: "说明或图片，不收集答案",
    Logic_Category_Layout: "布局",
    Logic_Preset_nps: "NPS（0–10）",
    Logic_PresetDesc_nps: "您有多大可能推荐……",
    Logic_Preset_satisfaction: "满意度（1–5）",
    Logic_PresetDesc_satisfaction: "从非常不满意到非常满意",
    Logic_Preset_currency: "货币",
    Logic_PresetDesc_currency: "金额",
    Logic_Preset_percent: "百分比",
    Logic_PresetDesc_percent: "百分比值",
    Logic_Template_blank_Name: "空白表单",
    Logic_Template_blank_Description: "从零开始",
    Logic_Template_feedback_Name: "客户反馈",
    Logic_Template_feedback_Description: "NPS、评分和开放式评论",
    Logic_Template_event_Name: "活动注册",
    Logic_Template_event_Description: "与会者详细信息、会议和饮食需求",
    Logic_Template_itrequest_Name: "IT 服务请求",
    Logic_Template_itrequest_Description: "带优先级和附件的分类请求",
    Logic_Template_expense_Name: "费用报销",
    Logic_Template_expense_Description: "明细项目、收据和计算得出的合计",
    Logic_Template_pulse_Name: "员工脉搏调查",
    Logic_Template_pulse_Description: "李克特网格、敬业度量表和匿名说明",
    Logic_Template_safety_Name: "安全检查",
    Logic_Template_safety_Description: "检查清单、照片和签名",
    Logic_Template_booking_Name: "会议室或资源预订",
    Logic_Template_booking_Description: "基于查阅的资源选取器，带时间段",
    Charts_ColumnChartAria: "包含 {count} 个类别的柱形图",
    Charts_DonutChartAria: "包含 {count} 个类别的圆环图",
    Charts_NoAnswers: "暂无答案。",
    Charts_NoResponses: "暂无响应。",
    Charts_Responses: "响应",
    Charts_ResponsesOverTime: "响应随时间变化",
    Responses_Chart_Answer: "答案",
    Responses_Chart_Average: "平均值",
    Responses_Chart_AverageOf: "{count} 项的平均值",
    Responses_Chart_AveragePosition: "平均位置",
    Responses_Chart_AverageRange: "平均值（1–{max}）",
    Responses_Chart_AvgValue: "平均 {value}",
    Responses_Chart_Detractors: "贬损者（0–6）",
    Responses_Chart_Max: "最大",
    Responses_Chart_Maximum: "最大值",
    Responses_Chart_Median: "中位数",
    Responses_Chart_MentionOne: "{count} 次提及",
    Responses_Chart_MentionOther: "{count} 次提及",
    Responses_Chart_Min: "最小",
    Responses_Chart_Minimum: "最小值",
    Responses_Chart_NoAnswers: "暂无答案。",
    Responses_Chart_NoNumeric: "暂无数值答案。",
    Responses_Chart_NoRankings: "暂无排名。",
    Responses_Chart_NoScores: "暂无分数。",
    Responses_Chart_NotEnoughText: "文本不足，暂无法汇总。",
    Responses_Chart_NpsScore: "NPS 得分",
    Responses_Chart_Option: "选项",
    Responses_Chart_Passives: "被动者（7–8）",
    Responses_Chart_Promoters: "推荐者（9–10）",
    Responses_Chart_ResponseOne: "个响应",
    Responses_Chart_ResponseOther: "个响应",
    Responses_Chart_Responses: "响应",
    Responses_Chart_ShowingAnswers: "显示 {shown}/{total} 个答案。",
    Responses_Chart_Statement: "陈述",
    Responses_Chart_Statistic: "统计",
    Responses_Chart_StdDev: "标准差",
    Responses_Chart_StdDeviation: "标准差",
    Responses_Chart_Total: "总计",
    Responses_Chart_Value: "值",
    Responses_Dashboard_AllHidden: "所有问题均已从仪表板隐藏。使用“显示隐藏的问题”可将其恢复。",
    Responses_Dashboard_AnsweredOf: "已回答 {answered}/{total}",
    Responses_Dashboard_AnsweredOfPinned: "已回答 {answered}/{total} · 已固定",
    Responses_Dashboard_AveragedAcrossResponses: "所有响应的平均值",
    Responses_Dashboard_ByDay: "按天",
    Responses_Dashboard_ByMonth: "按月",
    Responses_Dashboard_ByWeek: "按周",
    Responses_Dashboard_ChartAuto: "自动",
    Responses_Dashboard_ChartBars: "条形图",
    Responses_Dashboard_ChartColumns: "柱形图",
    Responses_Dashboard_ChartDonut: "圆环图",
    Responses_Dashboard_ChartGauge: "仪表图",
    Responses_Dashboard_ChartHistogram: "直方图",
    Responses_Dashboard_ChartOptions: "图表选项",
    Responses_Dashboard_ChartOptionsFor: "{title}的图表选项",
    Responses_Dashboard_ChartStatistics: "统计",
    Responses_Dashboard_ChartTable: "表格",
    Responses_Dashboard_ChartWordFrequency: "词频",
    Responses_Dashboard_EmptyBody: "人们开始作答后，此仪表板会自动填充 — 包括关键数字、响应时间线，以及值得关注的问题图表。",
    Responses_Dashboard_EmptyTitle: "暂无响应",
    Responses_Dashboard_Hide: "从仪表板隐藏",
    Responses_Dashboard_Highlights: "要点",
    Responses_Dashboard_Last7Days: "过去 7 天",
    Responses_Dashboard_LatestDate: "最近 {date}",
    Responses_Dashboard_MedianTimeToComplete: "完成时间中位数",
    Responses_Dashboard_NoPriorWeek: "没有可比较的上一周",
    Responses_Dashboard_OneEach: "各一次",
    Responses_Dashboard_Pin: "固定到仪表板",
    Responses_Dashboard_QuestionFallback: "问题",
    Responses_Dashboard_QuestionsAnswered: "已回答的问题",
    Responses_Dashboard_RecordedOnSubmit: "提交时记录",
    Responses_Dashboard_RepeatResponses: "{count} 个重复响应",
    Responses_Dashboard_ResponsesOverTime: "响应随时间变化",
    Responses_Dashboard_ShowHidden: "显示隐藏的问题",
    Responses_Dashboard_SinceMidnight: "自午夜起",
    Responses_Dashboard_Today: "今天",
    Responses_Dashboard_TotalResponses: "响应总数",
    Responses_Dashboard_UniqueRespondents: "唯一答题者",
    Responses_Dashboard_Unpin: "从仪表板取消固定",
    Responses_Dashboard_UntitledQuestion: "无标题问题",
    Responses_Dashboard_VsPrevious7Days: "对比前 7 天",
    Responses_Detail_Answers: "答案",
    Responses_Detail_AsTheForm: "按表单显示",
    Responses_Detail_Cancel: "取消",
    Responses_Detail_Delete: "删除",
    Responses_Detail_DeleteBody: "列表项将移至站点回收站，因此可以从中还原。",
    Responses_Detail_DeleteTitle: "删除此响应？",
    Responses_Detail_Deleting: "正在删除…",
    Responses_Detail_Draft: "草稿",
    Responses_Detail_Header: "第 {index} 个响应，共 {total} 个",
    Responses_Detail_LoadingAttachments: "正在加载附件…",
    Responses_Detail_Next: "下一个响应",
    Responses_Detail_NoAnswer: "无答案",
    Responses_Detail_Previous: "上一个响应",
    Responses_Detail_Print: "打印",
    Responses_Detail_Signature: "签名",
    Responses_Detail_Signed: "已签名",
    Responses_Detail_Took: "用时 {duration}",
    Responses_Summary_AnsweredOfType: "已回答 {answered}/{total} · {type}",
    Responses_Summary_ByField: "按{title}",
    Responses_Summary_CompareBy: "比较依据…",
    Responses_Summary_EmptyBody: "每个问题都将在此处有自己的摘要。",
    Responses_Summary_NoComparison: "不比较",
    Responses_Summary_NothingToCompare: "没有响应回答“{title}”,因此无可比较内容。",
    Responses_Summary_OtherNote: "类别超过 {max} 个的图表会将最小的几个归入“其他” — 将卡片切换为表格可查看每个值。",
    Responses_Summary_ResponseCountOne: "{count} 个响应",
    Responses_Summary_ResponseCountOther: "{count} 个响应",
    Responses_Summary_SeeAllAnswers: "在表格中查看所有答案",
    Responses_Summary_SegmentNote: "显示最大的 {groups} 个组。选择了多个答案的响应会出现在每个匹配的组中，因此各组总数之和可能超过 {total}。",
    Responses_Summary_SplitBy: "按{title}拆分",
    Responses_Summary_Untitled: "无标题",
    Responses_Table_Apply: "应用",
    Responses_Table_Cancel: "取消",
    Responses_Table_ClearSelection: "清除选择",
    Responses_Table_ColumnOrder: "列顺序",
    Responses_Table_ColumnsCount: "列（{shown}/{total}）",
    Responses_Table_Delete: "删除",
    Responses_Table_DeleteBody: "列表项将移至站点回收站，因此可以从中还原。",
    Responses_Table_DeleteSelected: "删除所选项",
    Responses_Table_DeleteTitleOne: "删除 {count} 个响应？",
    Responses_Table_DeleteTitleOther: "删除 {count} 个响应？",
    Responses_Table_Deleting: "正在删除…",
    Responses_Table_MoveDown: "下移",
    Responses_Table_MoveDownFor: "下移{title}",
    Responses_Table_MoveUp: "上移",
    Responses_Table_MoveUpFor: "上移{title}",
    Responses_Table_NoColumns: "暂无可见的问题列。",
    Responses_Table_NoMatch: "没有与当前筛选器匹配的响应。",
    Responses_Table_NothingToShow: "无可显示内容",
    Responses_Table_OpenResponse: "打开此响应",
    Responses_Table_OrderNote: "“提交时间”和“提交者”始终排在最前。拖动顺序适用于问题列。",
    Responses_Table_Reorder: "重新排序",
    Responses_Table_ResetColumns: "重置列",
    Responses_Table_SelectResponse: "选择此响应",
    Responses_Table_SelectedOne: "已选择 {count} 个响应",
    Responses_Table_SelectedOther: "已选择 {count} 个响应",
    Responses_Table_ShowAll: "全部显示",
    Responses_Table_ShowTheseQuestions: "显示这些问题",
    Responses_Table_Submitted: "提交时间",
    Responses_Table_SubmittedBy: "提交者",
    Responses_Table_ToggleSelection: "切换选择",
    Responses_Table_Unknown: "未知",
    Responses_Table_Untitled: "无标题",
    Responses_View_AllTime: "所有时间",
    Responses_View_AnyAnswer: "任意答案",
    Responses_View_Clear: "清除",
    Responses_View_CopyShareLink: "复制共享链接",
    Responses_View_CountFiltered: "{shown}/{total} 个响应",
    Responses_View_CountOne: "{count} 个响应",
    Responses_View_CountOther: "{count} 个响应",
    Responses_View_Dashboard: "仪表板",
    Responses_View_DateRange: "日期范围",
    Responses_View_EmptyBody: "共享表单即可开始收集。答案将保存到“{list}”,并立即显示在此处。",
    Responses_View_EmptyTitle: "暂无响应",
    Responses_View_ExportCsv: "导出 CSV",
    Responses_View_FilterByAnswer: "按答案筛选",
    Responses_View_FilterByQuestion: "按问题筛选",
    Responses_View_FilterValue: "筛选值",
    Responses_View_Last30Days: "过去 30 天",
    Responses_View_Last7Days: "过去 7 天",
    Responses_View_Last90Days: "过去 90 天",
    Responses_View_LoadError: "无法加载响应。请先发布一次表单以创建列表列，然后重试。",
    Responses_View_Loading: "正在加载响应…",
    Responses_View_MoreActions: "更多响应操作",
    Responses_View_PreviewForm: "预览表单",
    Responses_View_Refresh: "刷新",
    Responses_View_ResponsesTab: "响应（{count}）",
    Responses_View_SearchPlaceholder: "搜索所有答案",
    Responses_View_SegmentOption: "{label}({count})",
    Responses_View_SelectValue: "选择值",
    Responses_View_Summary: "摘要",
    Responses_View_Today: "今天",
    Responses_View_Truncated: "此列表的响应数超过 Smart Forms 一次可加载的数量。仅显示最新的 {count} 个 — 请在 Microsoft Lists 中打开该列表以查看完整内容。",
    Responses_View_TryAgain: "重试",
    Responses_View_Untitled: "无标题",
    Responses_Approval_Column: "审批",
    Responses_Approval_ReviewerColumn: "审阅者",
    Responses_Approval_CommentColumn: "审阅者评论",
    Responses_Approval_Pending: "待审批",
    Responses_Approval_Approved: "已批准",
    Responses_Approval_Rejected: "已拒绝",
    Responses_Approval_AnyStatus: "任何审批状态",
    Responses_Approval_FilterLabel: "按审批状态筛选",
    Responses_Approval_ApproveSelected: "批准所选项",
    Responses_Approval_RejectSelected: "拒绝所选项",
    Responses_Approval_BulkFailed: "有 {count} 个响应无法更新。请重试。",
    Responses_Approval_Approve: "批准",
    Responses_Approval_Reject: "拒绝",
    Responses_Approval_Reset: "重置为待审批",
    Responses_Approval_CommentLabel: "评论（可选）",
    Responses_Approval_ReviewedBy: "审阅者：{name}",
    Responses_Approval_Error: "无法保存该决定。请重试。",
    Responses_Dashboard_ApprovalStatus: "等待审阅",
    Responses_Dashboard_ApprovalBreakdown: "{pending} 个待审批，{approved} 个已批准，{rejected} 个已拒绝",
    Responses_Dashboard_TimelineCoarsened: "日期范围较长，因此时间线已按更粗的粒度分组（{grain}）。",
    Responses_Dashboard_TimelineTruncated: "日期范围非常长，因此仅显示最近的 {count} 个时间段。",
    Service_Item_DefaultTitle: "响应 — {date}",
    Service_Email_ApprovalSubject: "您的响应{status} — {title}",
    Service_Email_ApprovalHeading: "您的响应{status}",
    Service_Email_ApprovalIntro: "审阅者已将您对“{title}”的响应标记为{status}。",
    Service_Email_ApprovalCommentLabel: "审阅者评论",
    Service_Approval_Approved: "已批准",
    Service_Approval_Rejected: "已拒绝",
    Service_Approval_Pending: "待审批",
    Service_Lookup_InvalidFilter: "查阅筛选器无效。",
    Service_Edit_NotAllowed: "此表单不允许编辑已提交的响应。",
    Service_Edit_NotYours: "您只能编辑自己的响应。",
    Service_Signature_AttachmentLabel: "签名",
    PropertyPane_ListsLoadFailed: "无法加载此站点上的列表。",
    PropertyPane_EnterListName: "请先输入新列表的名称。",
    PropertyPane_CreatingList: "正在创建“{name}”…",
    PropertyPane_ListCreated: "已创建并选择列表“{title}”。",
    PropertyPane_ListAlreadyExists: "名为“{name}”的列表已存在 — 请从上方下拉列表中选择它。",
    PropertyPane_CreateListFailed: "无法创建列表。请检查您是否有权在此站点上创建列表。",
    PropertyPane_Description: "选择用于存储表单响应的 SharePoint 列表，或创建新列表。其他所有内容（问题、外观、通知）均可直接在页面上编辑。",
    PropertyPane_ResponseList_GroupName: "响应列表",
    PropertyPane_ListDropdown_Label: "将响应保存到此列表",
    PropertyPane_ResponsesGoTo: "响应将保存到“{name}”。",
    PropertyPane_PickList: "请选择一个列表，或在下方创建。",
    PropertyPane_LoadingLists: "正在加载列表…",
    PropertyPane_NewListName_Label: "或创建新列表",
    PropertyPane_NewListName_Placeholder: "新列表名称",
    PropertyPane_CreateList_Button: "创建列表",
    PropertyPane_Tips_GroupName: "提示",
    PropertyPane_Tip_AutoSave: "问题和设置会在您编辑时自动保存 — 无需保存或发布页面。",
    PropertyPane_Tip_Permissions: "答题者需要有权向响应列表添加项。如果有人报告提交时出错，请检查列表权限。",
    PropertyPane_Tip_Share: "使用页面上的“收集响应”可创建列表列并获取可共享的填写链接。",
    App_ErrorBoundary_Title: "Smart Forms — 呈现错误",
    App_ErrorBoundary_Message: "消息：",
    App_ErrorBoundary_Stack: "堆栈：",
    App_ErrorBoundary_NoStack: "（无可用堆栈）",
    App_ErrorBoundary_ConsoleNote: "完整详细信息也已写入浏览器控制台。",
    App_DefaultQuestionTitle: "问题 {number}",
    App_Error_ListMissing: "为此表单配置的列表已不存在。请在 Web 部件设置中选择其他列表。",
    App_Error_LoadConfig: "加载表单配置时出错。",
    App_Error_Unable: "无法加载表单。",
    App_Publish_ConflictNotice: "“{title}”已有不同类型（{type}）的列表列。请重命名该问题以便创建新列，或将其类型改回。",
    App_Publish_ConflictUnnamedQuestion: "某个问题",
    App_Publish_ColumnsAddedOne: "已向“{list}”添加 {count} 列。",
    App_Publish_ColumnsAddedOther: "已向“{list}”添加 {count} 列。",
    App_Publish_TheList: "该列表",
    App_Publish_UpToDate: "响应列表已是最新。",
    App_Publish_Error: "无法创建列表列。这通常意味着您对响应列表没有“管理列表”权限，但在禁用自定义脚本的站点上也可能发生。请查看浏览器控制台中的底层错误，或重试。",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "在 SharePoint 列表之上构建精美的表单 — {count} 种问题类型、分支逻辑、文件上传、可共享的填写链接以及结果仪表板。",
    App_Placeholder_ChooseList: "选择或创建列表",
    App_Placeholder_Hint: "编辑页面并配置此 Web 部件以开始使用。",
    App_Loading: "正在加载表单…",
    App_OpenSettings: "打开设置",
    App_Tab_Questions: "问题",
    App_Tab_QuestionsWithCount: "问题（{count}）",
    App_Tab_Responses: "响应",
    App_Tab_Responses_Title: "响应将保存到“{list}”",
    App_Templates_Start: "从模板开始",
    App_Settings_Title: "表单设置 — 外观、通知、访问",
    App_Settings_AriaLabel: "表单设置",
    App_Preview: "预览",
    App_Preview_Close: "关闭预览",
    App_Preview_Hint: "预览 — 您在此处提交的任何内容都不会保存。验证和分支的行为与答题者看到的完全一致。",
    App_Publish_GettingReady: "正在准备…",
    App_Publish_CollectResponses: "收集响应",
    App_Publish_Share: "共享",
    App_Retry: "重试",
    App_SaveError_Banner: "无法保存您的上次更改。请检查网络连接，然后重试。",
    App_Preflight_BlockingTitle: "收集前请先修复以下问题",
    App_Preflight_WarningTitle: "建议先检查",
    App_Preflight_BlockingText: "这些问题会导致已发布的表单无法正常工作。",
    App_Preflight_WarningText: "没有任何故障，但通常建议在共享链接之前先修复这些问题。",
    App_Preflight_GoTo: "转到",
    App_Preflight_CollectAnyway: "仍然收集响应",
    App_Preflight_Back: "返回表单",
    App_Cancel: "取消",
    App_Done: "完成",
    App_Share_Title: "您的表单已可共享",
    App_Share_SubText: "将此链接发送给需要填写表单的任何人。",
    App_Share_LinkAriaLabel: "共享链接",
    App_Share_Copy: "复制",
    App_Share_Copied: "已复制",
    App_Share_AddItemsEmphasis: "添加项",
    App_Share_PermissionNote: "答题者需要有权向“{title}”{addItems},并有权访问此页面。如果有人在提交时遇到错误，几乎总是这个原因。",
    App_Share_PrefillNote: "您可以通过在链接中添加列名来预先回答问题，例如 {example}。",
    App_Templates_ReplaceWarning: "选择模板将替换您当前的问题。",
    App_Templates_PickStart: "选择一个起点 — 之后可以更改任何内容。",
    App_Templates_Empty: "空白",
    App_Templates_QuestionCount: "{count} 个问题",
    App_SaveChip_SavingTitle: "正在保存您的最新编辑",
    App_SaveChip_Saving: "正在保存…",
    App_SaveChip_FailedTitle: "无法保存您的上次编辑。请检查网络连接并重试。",
    App_SaveChip_Failed: "保存失败",
    App_SaveChip_SavedTitle: "所有更改均已保存",
    App_SaveChip_Saved: "已保存",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "新响应 — {title}",
    Service_Email_NewResponseHeading: "新响应：{title}",
    Service_Email_NewResponseIntro: "有人刚刚提交了响应 — {date}。",
    Service_Email_ReceiptSubject: "您的响应 — {title}",
    Service_Email_ReceiptHeading: "感谢您的响应！",
    Service_Email_ReceiptIntro: "这是您提交到“{title}”的内容副本。",
    App_History_Title: "版本历史记录",
    App_History_RestoredNotice: "已还原 {date} 保存的版本。请查看，然后使用“收集响应”发布任何新问题。",
    App_History_Undo: "撤消还原",
    App_Share_CopyManual: "您的浏览器阻止了复制。请选择上方的链接，然后按 Ctrl+C（Mac 上为 Cmd+C）进行复制。",
    App_Share_TeamsNote: "您正在 Microsoft Teams 中。此链接会直接打开 SharePoint 页面，因此收件人需要有该网站的访问权限。",
    App_Share_PrefillNotSecure: "预填答案仅为方便之用：任何拥有链接的人都可以更改，因此切勿将其视为安全边界。",
    Designer_Section_DropHere: "将问题拖放到此处",
    Designer_Section_DropEnd: "拖放到此处以移至此部分末尾",
    Designer_Rules_RemovedOne: "已删除 1 条不再适用的分支规则。",
    Designer_Rules_RemovedOther: "已删除 {count} 条不再适用的分支规则。",
    Designer_Settings_AllowEdit: "允许答题者编辑其响应",
    Designer_Settings_AllowEditHint: "答题者可以重新打开并更新其提交的内容。每个人只能编辑自己的响应。",
    Designer_Settings_EnableApproval: "启用审批工作流",
    Designer_Settings_ApprovalNotify: "决定后向答题者发送电子邮件",
    Designer_Settings_ApprovalHint: "下次发布时，将向响应列表添加审批列。所有者可在“响应”选项卡中批准或拒绝响应。",
    Designer_History_Title: "版本历史记录",
    Designer_History_Intro: "此表单问题和设置的早期已保存版本。还原会将某个版本加载到设计器中；您可以撤消，只有在发布时才会创建新问题。",
    Designer_History_Loading: "正在加载版本...",
    Designer_History_Empty: "未找到早期版本。版本历史记录需要为“Smart Forms Config”列表启用版本控制，并且至少有一次已保存的编辑。",
    Designer_History_Latest: "最新",
    Designer_History_LatestTitle: "这是当前正在使用的版本",
    Designer_History_By: "作者：{name}",
    Designer_History_UnknownAuthor: "未知作者",
    Designer_History_VersionLabel: "版本 {label}",
    Designer_History_Preview: "预览",
    Designer_History_Restore: "还原",
    Designer_History_QuestionsOne: "1 个问题",
    Designer_History_QuestionsOther: "{count} 个问题",
    Designer_History_LoadFailed: "无法加载此版本。",
    Designer_History_ConfirmTitle: "还原此版本？",
    Designer_History_ConfirmText: "表单将替换为 {date} 保存的版本（{count} 个问题）。还原后可立即撤消。"
  };
});
