define([], function () {
  return {
    Designer_Color_Blue: "藍色",
    Designer_Color_Teal: "青色",
    Designer_Color_Green: "綠色",
    Designer_Color_Purple: "紫色",
    Designer_Color_Magenta: "洋紅色",
    Designer_Color_Red: "紅色",
    Designer_Color_Orange: "橙色",
    Designer_Color_Gray: "灰色",
    Designer_Settings_LayoutSinglePage: "所有問題在同一頁",
    Designer_Settings_LayoutWizard: "每步一個區段（精靈）",
    Designer_Settings_Title: "表單設定",
    Designer_Common_Apply: "套用",
    Designer_Common_Cancel: "取消",
    Designer_Settings_TabBasics: "基本",
    Designer_Settings_FormTitle: "表單標題",
    Designer_Settings_Description: "描述",
    Designer_Settings_Layout: "版面配置",
    Designer_Settings_NumberQuestions: "為問題編號",
    Designer_Settings_ShuffleQuestions: "為每位填答者隨機排列問題順序",
    Designer_Settings_ShowProgressBar: "顯示進度列",
    Designer_Settings_TabAppearance: "外觀",
    Designer_Settings_AccentColor: "輔色",
    Designer_Settings_CustomColorTitle: "自訂色彩",
    Designer_Settings_CustomColorAria: "自訂輔色",
    Designer_Settings_AccentHint: "輔色會在深色網站上自動調整對比，因此無論頁面使用哪種佈景主題，表單都能保持清晰易讀。",
    Designer_Settings_ShowHeader: "顯示表單標頭",
    Designer_Settings_HeaderIcon: "標頭圖示",
    Designer_Settings_TabAfterSubmit: "提交後",
    Designer_Settings_SubmitButtonText: "提交按鈕文字",
    Designer_Settings_SubmitPlaceholder: "提交",
    Designer_Settings_ThankYouTitle: "感謝標題",
    Designer_Settings_ThankYouPlaceholder: "謝謝您！",
    Designer_Settings_ThankYouMessage: "感謝訊息",
    Designer_Settings_ShowSubmitAnother: "顯示「再提交一份回應」按鈕",
    Designer_Settings_TabNotifications: "通知",
    Designer_Settings_EmailEachResponseTo: "將每份回應以電子郵件寄給",
    Designer_Settings_EmailPlaceholder: "name@company.com; team@company.com",
    Designer_Settings_EmailDescription: "組織中的人員會透過電子郵件收到每份回應，並附有清單項目的連結",
    Designer_Settings_RespondentReceipt: "以電子郵件將答案副本寄給填答者",
    Designer_Settings_NotificationsInfo: "通知使用 SharePoint 內建的郵件服務，因此收件者必須是組織中的使用者。外部地址會被靜默捨棄。",
    Designer_Settings_TabAccess: "存取",
    Designer_Settings_OpenFrom: "開放時間從",
    Designer_Settings_OpenImmediately: "立即開放",
    Designer_Settings_CloseAfter: "關閉時間",
    Designer_Settings_NeverClose: "永不關閉",
    Designer_Settings_ClearDates: "清除日期",
    Designer_Settings_DatesInverted: "關閉日期等於或早於開放日期，因此表單將永遠不會接受回應。",
    Designer_Settings_MaxResponses: "達到此回應數後停止",
    Designer_Settings_NoLimit: "無限制",
    Designer_Settings_OneResponsePerPerson: "每人僅允許一份回應",
    Designer_Settings_AllowSaveDraft: "允許填答者儲存草稿並稍後完成",
    Designer_Settings_ClosedMessage: "表單關閉時顯示的訊息",
    Designer_Settings_ClosedMessagePlaceholder: "此表單已不再接受回應。",
    Designer_Settings_AccessInfo: "這些限制由表單強制執行，而非 SharePoint。任何有權限將項目新增至回應清單的人，仍可直接透過清單新增。",
    Designer_Field_StyleInfo: "資訊（輔色）",
    Designer_Field_StyleSuccess: "成功（綠色）",
    Designer_Field_StyleWarning: "警告（琥珀色）",
    Designer_Field_StylePlain: "純文字",
    Designer_Field_StyleDivider: "分隔線",
    Designer_Field_IconStars: "星星",
    Designer_Field_IconHearts: "愛心",
    Designer_Field_IconThumbs: "讚",
    Designer_Field_FormatPlain: "純數字",
    Designer_Field_FormatCurrency: "貨幣",
    Designer_Field_FormatPercent: "百分比",
    Designer_Field_UntitledQuestion: "未命名問題",
    Designer_Field_DeletedQuestion: "已刪除的問題",
    Designer_Rule_Unary: "「{name}」{operator}",
    Designer_Rule_Between: "「{name}」{operator} {value} 和 {value2}",
    Designer_Rule_Binary: "「{name}」{operator}「{value}」",
    Designer_Rule_JoinAny: "或",
    Designer_Rule_JoinAll: "且",
    Designer_Rule_Preview: "當{conditions}時顯示。",
    Designer_Field_Yes: "是",
    Designer_Field_No: "否",
    Designer_Field_When: "當",
    Designer_Field_SelectValue: "選取值",
    Designer_Field_DateValuePlaceholder: "YYYY-MM-DD 或 \"today\"",
    Designer_Field_ValuePlaceholder: "值",
    Designer_Field_UpperBound: "上限",
    Designer_Field_RemoveCondition: "移除此條件",
    Designer_Field_FormulaInvalid: "無法計算此公式。請檢查括號和運算子。",
    Designer_Field_FormulaMissing: "這些問題不存在：{names}。",
    Designer_Field_FormulaPreview: "當每個輸入均為 10 時，此處顯示 {value}。",
    Designer_Field_HintYesNo: "使用 \"yes\" 或 \"no\"",
    Designer_Field_HintMultiDefault: "以 ; 分隔多個預設值",
    Designer_Field_HintSingleDefault: "必須符合其中一個選項",
    Designer_Field_HintDate: "使用 \"today\",或類似 2026-03-01 的日期",
    Designer_Field_HintTime: "使用 \"now\",或類似 09:30 的時間",
    Designer_Field_QuestionSettings: "問題設定",
    Designer_Field_Appearance: "外觀",
    Designer_Field_Style: "樣式",
    Designer_Field_ImageUrl: "影像 URL（選填）",
    Designer_Field_Content: "內容",
    Designer_Field_BasicFormatting: "允許基本格式：粗體、斜體、清單和連結。",
    Designer_Field_TabOptions: "選項",
    Designer_Field_TabBranching: "分支",
    Designer_Field_BranchingNeedsQuestion: "請先新增另一個問題 — 分支需要有可依賴的內容。",
    Designer_Field_BranchingToggle: "僅在其他答案符合時才顯示此問題",
    Designer_Field_Match: "符合",
    Designer_Field_MatchAll: "所有條件",
    Designer_Field_MatchAny: "任一條件",
    Designer_Field_AddCondition: "新增條件",
    Designer_Field_TabValidation: "驗證",
    Designer_Field_HelpText: "說明文字",
    Designer_Field_HelpTextPlaceholder: "顯示在問題標籤下方",
    Designer_Field_CheckboxLabel: "核取方塊標籤",
    Designer_Field_Placeholder: "預留位置",
    Designer_Field_DefaultAnswer: "預設答案",
    Designer_Field_RequiredMessage: "自訂必填訊息",
    Designer_Field_RequiredMessagePlaceholder: "{title}為必填",
    Designer_Field_ThisQuestion: "此問題",
    Designer_Field_RequiredMessageDescription: "此問題留空時顯示，以取代標準訊息",
    Designer_Field_ReadOnly: "唯讀（答案只能來自預先填入的連結）",
    Designer_Field_ValidationRules: "驗證規則",
    Designer_Field_MaxLength: "最大長度",
    Designer_Field_Pattern: "必須符合此模式",
    Designer_Field_PatternDescription: "規則運算式。留空則不檢查模式。",
    Designer_Field_PatternMessage: "模式不符時的訊息",
    Designer_Field_PatternMessagePlaceholder: "此答案的格式不符合要求",
    Designer_Field_Format: "格式",
    Designer_Field_UnitSuffix: "顯示在值之後的單位",
    Designer_Field_UnitSuffixPlaceholder: "kg、小時、件…",
    Designer_Field_Minimum: "最小值",
    Designer_Field_Maximum: "最大值",
    Designer_Field_Decimals: "小數位數",
    Designer_Field_Formula: "公式",
    Designer_Field_FormulaPlaceholder: "{Quantity} * {Unit price}",
    Designer_Field_FormulaDescription: "以大括號中的問題文字參照其他問題。支援 + - * / ( ) 以及 round、min、max、sum、avg。",
    Designer_Field_AvailableQuestions: "可用問題：{questions}",
    Designer_Field_NoneYet: "尚無",
    Designer_Field_Step: "間隔",
    Designer_Field_From: "從",
    Designer_Field_To: "到",
    Designer_Field_LowLabel: "低端標籤",
    Designer_Field_LowLabelPlaceholder: "完全不可能",
    Designer_Field_HighLabel: "高端標籤",
    Designer_Field_HighLabelPlaceholder: "極有可能",
    Designer_Field_SummarizeAs: "摘要方式",
    Designer_Field_SummarizeAverage: "平均值和分佈",
    Designer_Field_SummarizeNps: "淨推薦值（需要 0–10 量表）",
    Designer_Field_NpsWarning: "淨推薦值僅在 0–10 量表上才有意義。請將「從」設為 0,「到」設為 10。",
    Designer_Field_NumberOfIcons: "圖示數量",
    Designer_Field_Icon: "圖示",
    Designer_Field_AllowHalf: "允許半值",
    Designer_Field_ShowOptionsAs: "選項顯示為",
    Designer_Field_DisplayButtons: "內嵌按鈕",
    Designer_Field_DisplayDropdown: "下拉式清單",
    Designer_Field_DisplayAutomatic: "自動（最多 6 個選項時內嵌）",
    Designer_Field_AllowOther: "新增可自行填寫的「其他」選項",
    Designer_Field_OtherLabel: "「其他」選項的標籤",
    Designer_Field_OtherPlaceholder: "其他",
    Designer_Field_ShuffleOptions: "為每位填答者隨機排列選項順序",
    Designer_Field_MinSelections: "最少選取數",
    Designer_Field_MaxSelections: "最多選取數",
    Designer_Field_SourceList: "來源清單",
    Designer_Field_ChooseList: "選擇清單",
    Designer_Field_LookupColumn: "用於讀取選項的欄",
    Designer_Field_ChooseColumn: "選擇欄",
    Designer_Field_ChooseListFirst: "請先選擇清單",
    Designer_Field_LookupFilter: "篩選（選填）",
    Designer_Field_LookupFilterDescription: "用於縮小哪些來源項目成為選項的 OData 篩選",
    Designer_Field_LookupInfo: "答案儲存的是選項文字，而非指向來源項目的連結，因此即使來源清單日後變更，回應仍然可讀。",
    Designer_Field_ConsentText: "核取方塊上方顯示的條款",
    Designer_Field_AllowMultiplePeople: "允許多人",
    Designer_Field_AllowGroups: "同時允許群組",
    Designer_Field_IncludeTime: "包含具體時間",
    Designer_Field_TimeStep: "時間間隔（分鐘）",
    Designer_Field_MaxFiles: "最大檔案數",
    Designer_Field_MaxFileSize: "每個檔案大小上限（MB）",
    Designer_Field_AcceptedTypes: "接受的檔案類型",
    Designer_Field_AcceptedTypesDescription: "以逗號分隔的副檔名。留空則接受 SharePoint 允許的所有類型。",
    Designer_Field_FilesInfo: "檔案會以附件形式儲存在回應項目上。無論您在此允許什麼，SharePoint 都會封鎖某些副檔名（例如 .exe）。",
    Designer_Field_Rows: "列",
    Designer_Field_ProvisionedNote: "此問題已有清單欄（{name}）。變更欄類型的設定已鎖定 — 如需其他類型，請複製該問題。",
    Designer_Category_Text: "文字",
    Designer_Category_Choice: "選擇",
    Designer_Category_Scales: "量表",
    Designer_Category_Date: "日期",
    Designer_Category_People: "人員",
    Designer_Category_Advanced: "進階",
    Designer_Category_Layout: "版面配置",
    Designer_Menu_CommonPresets: "常用預設",
    Designer_Menu_AllTypes: "所有問題類型",
    Designer_Menu_ChangeType: "變更類型",
    Designer_Menu_TypeLockedTitle: "清單欄已存在，因此類型已鎖定。請複製該問題以變更類型。",
    Designer_Menu_MoreSettings: "分支、驗證及更多",
    Designer_Menu_InsertBelow: "在下方插入問題",
    Designer_Card_Duplicate: "複製",
    Designer_Card_DeleteQuestion: "刪除問題",
    Designer_Outline_Aria: "問題大綱",
    Designer_Outline_QuestionCountOne: "{count} 個問題",
    Designer_Outline_QuestionCountOther: "{count} 個問題",
    Designer_Outline_IssuesTitle: "{count} 個待檢查的問題",
    Designer_Outline_Find: "尋找問題",
    Designer_Outline_Empty: "尚無問題。",
    Designer_Section_DefaultTitle: "第 {number} 區段",
    Designer_Card_Question: "問題",
    Designer_Card_BranchingTitle: "此問題僅在分支規則符合時才會出現",
    Designer_Card_BranchingChip: "分支",
    Designer_Card_LiveTitle: "清單欄已存在，因此類型已鎖定",
    Designer_Card_LiveChip: "已上線",
    Designer_Card_CheckChip: "檢查",
    Designer_Option_Placeholder: "選項 {number}",
    Designer_Option_LabelAria: "選項 {number} 標籤",
    Designer_Option_ImageUrl: "影像 URL",
    Designer_Option_ImageUrlAria: "選項 {number} 影像 URL",
    Designer_Option_Remove: "移除選項",
    Designer_Option_RemoveAria: "移除選項 {number}",
    Designer_Option_Add: "新增選項",
    Designer_Option_OtherHint: "填答者還可以自行填寫標為「{label}」的答案。",
    Designer_Option_OtherFallback: "其他",
    Designer_Grid_ItemPlaceholder: "{label} {number}",
    Designer_Grid_Remove: "移除",
    Designer_Grid_RemoveAria: "移除 {label} {number}",
    Designer_Grid_Statements: "陳述",
    Designer_Grid_Scale: "量表",
    Designer_Grid_AddStatement: "新增陳述",
    Designer_Grid_AddScale: "新增量表",
    Designer_Width_Full: "全寬",
    Designer_Width_Half: "半寬",
    Designer_Width_Third: "三分之一寬",
    Designer_Width_Aria: "問題寬度",
    Designer_Card_BlockLabelPlaceholder: "區塊標籤（不顯示給填答者）",
    Designer_Card_QuestionText: "問題文字",
    Designer_Card_MoveUp: "上移",
    Designer_Card_MoveQuestionUp: "上移問題",
    Designer_Card_MoveDown: "下移",
    Designer_Card_MoveQuestionDown: "下移問題",
    Designer_Card_DuplicateQuestion: "複製問題",
    Designer_Card_MultipleAnswers: "多個答案",
    Designer_Card_Required: "必填",
    Designer_Card_MoreOptions: "更多選項",
    Designer_Card_MoreOptionsAria: "此問題的更多選項",
    Designer_Canvas_FormTitle: "表單標題",
    Designer_Canvas_DescriptionPlaceholder: "新增描述（選填）",
    Designer_Canvas_DescriptionAria: "表單描述",
    Designer_Canvas_EmptyTitle: "新增第一個問題",
    Designer_Canvas_EmptyBody: "選擇問題類型即可開始。您可以透過拖曳來重新排列問題，還可以新增分支，讓人們只看到與自己相關的內容。",
    Designer_Section_Chip: "第 {number} 區段，共 {total} 區段",
    Designer_Section_TitlePlaceholder: "區段標題",
    Designer_Section_TitleAria: "第 {number} 區段標題",
    Designer_Section_DescriptionPlaceholder: "描述（選填）",
    Designer_Section_DescriptionAria: "第 {number} 區段描述",
    Designer_Section_MoveUp: "上移區段",
    Designer_Section_MoveDown: "下移區段",
    Designer_Section_Delete: "刪除區段",
    Designer_Card_DragToReorder: "拖曳以重新排序",
    Designer_Card_ReorderAria: "重新排序{title}",
    Designer_Card_ReorderFallback: "問題",
    Designer_Canvas_AddNew: "新增",
    Designer_Canvas_AddSection: "新增區段",
    Form_Address_AriaWithLabel: "{label} — {part}",
    Form_Address_StreetPlaceholder: "街道地址",
    Form_Address_Street2Placeholder: "公寓、套房等（選填）",
    Form_Address_CityPlaceholder: "城市",
    Form_Address_StatePlaceholder: "州/縣市",
    Form_Address_PostalCodePlaceholder: "郵遞區號",
    Form_Address_CountryPlaceholder: "國家/地區",
    Form_Address_StreetAria: "街道地址",
    Form_Address_Street2Aria: "地址第 2 行",
    Form_Address_CityAria: "城市",
    Form_Address_StateAria: "州或縣市",
    Form_Address_PostalCodeAria: "郵遞區號",
    Form_Address_CountryAria: "國家/地區",
    Form_Consent_DefaultLabel: "我同意",
    Form_Likert_RadioAria: "{row}:{column}",
    Form_Likert_RowsAnswered: "已回答 {answered}/{total} 列",
    Form_Lookup_LoadError: "無法載入此問題的選項。",
    Form_Lookup_Loading: "正在載入選項…",
    Form_Lookup_SelectOptionsPlaceholder: "選取選項",
    Form_Lookup_SelectOptionPlaceholder: "選取一個選項",
    Form_Person_Placeholder: "開始輸入姓名…",
    Form_Person_SuggestedPeopleAndGroups: "建議的人員和群組",
    Form_Person_SuggestedPeople: "建議的人員",
    Form_Person_NoPeopleOrGroups: "找不到人員或群組",
    Form_Person_NoPeople: "找不到人員",
    Form_Person_Searching: "正在搜尋…",
    Form_Ranking_Moved: "{item} 已移至第 {position} 位（共 {total} 位）",
    Form_Ranking_MoveUp: "上移",
    Form_Ranking_MoveDown: "下移",
    Form_Ranking_MoveItemUpAria: "上移 {item}",
    Form_Ranking_MoveItemDownAria: "下移 {item}",
    Form_Rating_ValueText: "{value}/{max}",
    Form_Rating_NotRated: "未評分",
    Form_Rating_Clear: "清除評分",
    Form_RichText_Bold: "粗體",
    Form_RichText_Italic: "斜體",
    Form_RichText_Underline: "底線",
    Form_RichText_BulletedList: "項目符號清單",
    Form_RichText_NumberedList: "編號清單",
    Form_RichText_ClearFormatting: "清除格式",
    Form_RichText_ToolbarAria: "文字格式",
    Form_File_SizeBytes: "{size} B",
    Form_File_SizeKb: "{size} KB",
    Form_File_SizeMb: "{size} MB",
    Form_File_SkippedLimit: "已略過「{name}」 — 上限為 {limit}。",
    Form_File_TypeNotAccepted: "「{name}」不是可接受的類型。",
    Form_File_TooLarge: "「{name}」大於 {size} MB。",
    Form_File_AlreadyAttached: "「{name}」已附加。",
    Form_File_ReadError: "無法讀取其中一個檔案。請嘗試重新附加。",
    Form_File_HintMaxSize: "每個最大 {size} MB",
    Form_File_HintOneFile: "1 個檔案",
    Form_File_HintMaxFiles: "最多 {count} 個檔案",
    Form_File_Reading: "正在讀取檔案…",
    Form_File_DropPrompt: "將檔案拖放到此處，或按一下瀏覽",
    Form_File_Remove: "移除 {name}",
    Form_Signature_Alt: "簽名",
    Form_Signature_AriaSigned: "{label} — 已簽名",
    Form_Signature_AriaEmpty: "{label} — 空白",
    Form_Signature_Clear: "清除",
    Form_Signature_Signed: "已簽名",
    Form_Signature_Prompt: "使用滑鼠、手寫筆或手指在上方簽名",
    Form_Time_Placeholder: "選取時間",
    Form_Field_DatePlaceholder: "選取日期",
    Form_Field_TimeAriaWithLabel: "{label} — 時間",
    Form_Field_TimeAria: "時間",
    Form_Field_OtherDefault: "其他",
    Form_Field_SelectOptionsPlaceholder: "選取選項",
    Form_Field_PleaseSpecify: "請說明",
    Form_Field_OtherSpecifyAria: "{label} — 請說明",
    Form_Field_SelectOptionPlaceholder: "選取一個選項",
    Form_Field_Yes: "是",
    Form_Field_No: "否",
    Form_Field_SliderHint: "拖曳滑桿以回答",
    Form_Field_WebAddressAriaWithLabel: "{label} — 網址",
    Form_Field_WebAddressAria: "網址",
    Form_Field_DisplayTextPlaceholder: "顯示文字（選填）",
    Form_Field_DisplayTextAriaWithLabel: "{label} — 顯示文字",
    Form_Field_DisplayTextAria: "顯示文字",
    Form_Field_ChooseBetween: "請選擇 {min} 到 {max} 項",
    Form_Field_ChooseAtLeast: "請至少選擇 {min} 項",
    Form_Field_ChooseUpTo: "最多選擇 {max} 項",
    Form_Field_SelectedCount: "已選取 {count} 項",
    Form_Field_RequiredAria: "（必填）",
    Form_Submit_SaveError: "無法儲存您的回應。請確定已從設計工具發佈表單，且您有權限將項目新增至回應清單。",
    Form_Empty_Message: "此表單尚無任何問題。表單擁有者可以在「問題」索引標籤中新增。",
    Form_Checking: "正在檢查表單…",
    Form_Closed_NotYetOpen: "尚未開放",
    Form_Closed_AlreadyAnswered: "已回答",
    Form_Closed_Title: "表單已關閉",
    Form_Confirmation_PreviewNotice: "這是預覽 — 未將任何內容儲存至回應清單。",
    Form_Confirmation_PreviewAgain: "再次預覽",
    Form_Confirmation_SubmitAnother: "再提交一份回應",
    Form_Wizard_StepFallback: "步驟 {step}",
    Form_Wizard_StepsAria: "表單步驟",
    Form_Wizard_StepOf: "第 {step} 步，共 {total} 步",
    Form_ErrorSummary_Title: "請檢查 {count} 個答案：",
    Form_ErrorSummary_UntitledQuestion: "未命名問題",
    Form_ErrorSummary_Question: "問題",
    Form_ErrorSummary_Detail: " — {message}",
    Form_Nav_Back: "上一步",
    Form_Nav_Next: "下一步",
    Form_Draft_Saving: "正在儲存…",
    Form_Draft_Saved: "草稿已儲存",
    Form_Draft_SaveAndFinishLater: "儲存並稍後完成",
    Form_Draft_NotSaved: "草稿未儲存",
    Form_Submit_Preview: "提交（預覽）",
    Form_Submit_Button: "提交",
    Form_Response_NoAnswer: "無答案",
    Form_Signature_TypeLabel: "輸入您的全名",
    Form_Signature_TypeInstead: "改為輸入姓名",
    Form_Signature_DrawInstead: "改為手繪",
    Form_Edit_Button: "編輯您先前的回應",
    Form_Edit_Available: "您已提交過回應。可以編輯該回應，而不必提交新的回應。",
    Form_Edit_Banner: "您正在編輯先前的回應。",
    Form_Edit_Save: "更新回應",
    Form_Edit_UpdatedTitle: "回應已更新",
    Form_Edit_UpdatedMessage: "您的變更已儲存。",
    Form_Edit_LoadError: "無法載入您先前的回應。請再試一次。",
    Form_Draft_MissingFiles: "請重新附加：{names}。這些檔案無法還原。",
    Form_Attachments_Failed: "您的答案已儲存，但下列附件無法上傳：{names}。請再試一次或聯絡表單擁有者。",
    Logic_ThisQuestion: "此問題",
    Logic_Required: "{label}為必填",
    Logic_RequiredConsent: "請勾選核取方塊以繼續",
    Logic_RequiredFile: "請至少附加一個檔案",
    Logic_RequiredSignature: "請新增您的簽名",
    Logic_RequiredLikert: "請回答每一列",
    Logic_InvalidEmail: "請輸入有效的電子郵件地址",
    Logic_InvalidPhone: "請輸入有效的電話號碼",
    Logic_InvalidUrl: "請輸入以 http:// 或 https:// 開頭的有效網址",
    Logic_MinValue: "值不可小於 {value}",
    Logic_MaxValue: "值不可大於 {value}",
    Logic_MaxLength: "長度上限為 {max} 個字元",
    Logic_ChooseAtLeastOne: "至少選擇 {count} 個選項",
    Logic_ChooseAtLeastMany: "至少選擇 {count} 個選項",
    Logic_ChooseAtMostOne: "最多選擇 {count} 個選項",
    Logic_ChooseAtMostMany: "最多選擇 {count} 個選項",
    Logic_LikertRemaining: "請回答每一列（還剩 {count} 列）",
    Logic_MaxFilesOne: "最多附加 {count} 個檔案",
    Logic_MaxFilesMany: "最多附加 {count} 個檔案",
    Logic_FileTooLarge: "「{name}」大於 {size} MB",
    Logic_FileTypeNotAccepted: "「{name}」不是可接受的檔案類型（{types}）",
    Logic_AddressRequired: "請至少輸入街道和城市",
    Logic_PatternDefault: "此答案格式不符合要求",
    Logic_Yes: "是",
    Logic_No: "否",
    Logic_Agreed: "已同意",
    Logic_NotAgreed: "未同意",
    Logic_Signed: "已簽名",
    Logic_NoAnswer: "（無答案）",
    Logic_Unknown: "（未知）",
    Logic_OtherSlice: "其他（{count}）",
    Logic_CsvResponseId: "回應 ID",
    Logic_CsvSubmitted: "提交時間",
    Logic_CsvSubmittedBy: "提交者",
    Logic_EmailQuestion: "問題",
    Logic_EmailViewItem: "在 Microsoft Lists 中檢視",
    Logic_EmailFooter: "由 Smart Forms 自動傳送。",
    Logic_ClosedDefault: "此表單不再接受回應。",
    Logic_NotYetOpen: "此表單將於 {date} 開放。",
    Logic_AlreadyResponded: "您已回應過此表單。謝謝！",
    Logic_UntitledQuestion: "未命名的問題",
    Logic_Issue_NoQuestions: "收集回應之前，請至少新增一個問題。",
    Logic_Issue_NoTitle: "有一個問題沒有文字，發佈時將自動為其命名。",
    Logic_Issue_DuplicateTitle: "{label}與另一個問題的文字相同，這會讓結果更難閱讀。",
    Logic_Issue_NeedTwoOptions: "{label}至少需要兩個選項。",
    Logic_Issue_ImageNoImage: "{label}中有選項沒有圖片，它們將顯示為文字磚。",
    Logic_Issue_LikertNeedRow: "{label}至少需要一列。",
    Logic_Issue_LikertNeedColumns: "{label}至少需要兩個量表欄。",
    Logic_Issue_NoLookupList: "{label}未選取來源清單。",
    Logic_Issue_NoFormula: "{label}沒有公式。",
    Logic_Issue_BadFormula: "{label}的公式無法計算。請檢查括號和運算子。",
    Logic_Issue_MissingRefs: "{label}參照了不存在的問題：{names}。",
    Logic_Issue_BadPattern: "{label}的驗證模式無效。",
    Logic_Issue_BrokenRule: "{label}有一項分支規則指向已刪除的問題。",
    Logic_Issue_SelfRule: "{label}有一項參照自身的分支規則。",
    Logic_Issue_RuleMismatch: "{label}有一項分支規則與其所依賴的問題不再相符。",
    Logic_Issue_RequiredReadOnly: "{label}既為必填又為唯讀，因此只能透過預先填入的連結作答。",
    Logic_Issue_EmptySection: "有一個區段沒有問題，將被略過。",
    Logic_Issue_CloseBeforeOpen: "關閉日期等於或早於開放日期，因此表單將永遠不會接受回應。",
    Logic_Issue_ApprovalNotifyWithoutApproval: "核准電子郵件已開啟，但核准步驟已關閉。",
    Logic_Op_equals: "等於",
    Logic_Op_notEquals: "不等於",
    Logic_Op_contains: "包含",
    Logic_Op_notContains: "不包含",
    Logic_Op_notEmpty: "已回答",
    Logic_Op_empty: "未回答",
    Logic_Op_greaterThan: "大於",
    Logic_Op_greaterOrEqual: "至少為",
    Logic_Op_lessThan: "小於",
    Logic_Op_lessOrEqual: "至多為",
    Logic_Op_between: "介於",
    Logic_Op_before: "早於",
    Logic_Op_after: "晚於",
    Logic_Type_Text: "簡答",
    Logic_TypeDesc_Text: "單行文字",
    Logic_Category_Text: "文字",
    Logic_Type_MultilineText: "詳答",
    Logic_TypeDesc_MultilineText: "多行純文字",
    Logic_Type_RichText: "格式化文字",
    Logic_TypeDesc_RichText: "粗體、清單和連結",
    Logic_Type_Choice: "選擇",
    Logic_TypeDesc_Choice: "從選項清單中挑選",
    Logic_Category_Choice: "選擇",
    Logic_Type_ImageChoice: "圖片選擇",
    Logic_TypeDesc_ImageChoice: "從圖片磚中挑選",
    Logic_Type_Lookup: "清單查閱",
    Logic_TypeDesc_Lookup: "即時讀取另一個 SharePoint 清單中的選項",
    Logic_Type_YesNo: "是 / 否",
    Logic_TypeDesc_YesNo: "簡單的開關切換",
    Logic_Type_Consent: "同意",
    Logic_TypeDesc_Consent: "填答者必須勾選才能繼續的核取方塊",
    Logic_Type_Ranking: "排名",
    Logic_TypeDesc_Ranking: "將選項拖曳成偏好順序",
    Logic_Type_Rating: "評等",
    Logic_TypeDesc_Rating: "星形、心形或大拇指",
    Logic_Category_Scales: "量表",
    Logic_Type_Scale: "意見量表",
    Logic_TypeDesc_Scale: "兩端有標籤的數字量表",
    Logic_Type_Slider: "滑桿",
    Logic_TypeDesc_Slider: "滑動量表上的值",
    Logic_Type_Likert: "李克特方格",
    Logic_TypeDesc_Likert: "在同一量表上為多個陳述評分",
    Logic_Type_Number: "數字",
    Logic_TypeDesc_Number: "純數字、貨幣或百分比",
    Logic_Category_Advanced: "進階",
    Logic_Type_Calculated: "計算",
    Logic_TypeDesc_Calculated: "根據其他答案算出的唯讀總計",
    Logic_Type_Date: "日期",
    Logic_TypeDesc_Date: "行事曆日期，可選擇包含時間",
    Logic_Category_Date: "日期",
    Logic_Type_Time: "時間",
    Logic_TypeDesc_Time: "單獨的一天中的時間",
    Logic_Type_Person: "人員",
    Logic_TypeDesc_Person: "從組織中挑選某人",
    Logic_Category_People: "人員",
    Logic_Type_Email: "電子郵件",
    Logic_TypeDesc_Email: "電子郵件地址，經過驗證",
    Logic_Type_Phone: "電話",
    Logic_TypeDesc_Phone: "電話號碼，經過驗證",
    Logic_Type_Address: "地址",
    Logic_TypeDesc_Address: "街道、城市、郵遞區號和國家/地區",
    Logic_Type_Hyperlink: "連結",
    Logic_TypeDesc_Hyperlink: "網址",
    Logic_Type_FileUpload: "檔案上傳",
    Logic_TypeDesc_FileUpload: "將一個或多個檔案附加到回應",
    Logic_Type_Signature: "簽名",
    Logic_TypeDesc_Signature: "用滑鼠、手寫筆或手指簽名",
    Logic_Type_Content: "文字區塊",
    Logic_TypeDesc_Content: "說明或圖片，不收集答案",
    Logic_Category_Layout: "版面配置",
    Logic_Preset_nps: "NPS（0–10）",
    Logic_PresetDesc_nps: "您有多大可能推薦……",
    Logic_Preset_satisfaction: "滿意度（1–5）",
    Logic_PresetDesc_satisfaction: "從非常不滿意到非常滿意",
    Logic_Preset_currency: "貨幣",
    Logic_PresetDesc_currency: "金額",
    Logic_Preset_percent: "百分比",
    Logic_PresetDesc_percent: "百分比值",
    Logic_Template_blank_Name: "空白表單",
    Logic_Template_blank_Description: "從零開始",
    Logic_Template_feedback_Name: "客戶意見反應",
    Logic_Template_feedback_Description: "NPS、評等和開放式意見",
    Logic_Template_event_Name: "活動報名",
    Logic_Template_event_Description: "與會者詳細資料、議程和飲食需求",
    Logic_Template_itrequest_Name: "IT 服務要求",
    Logic_Template_itrequest_Description: "附有優先順序和附件的分類要求",
    Logic_Template_expense_Name: "費用報銷",
    Logic_Template_expense_Description: "明細項目、收據和計算出的總計",
    Logic_Template_pulse_Name: "員工脈動調查",
    Logic_Template_pulse_Description: "李克特方格、敬業度量表和匿名說明",
    Logic_Template_safety_Name: "安全檢查",
    Logic_Template_safety_Description: "檢查清單、照片和簽名",
    Logic_Template_booking_Name: "會議室或資源預訂",
    Logic_Template_booking_Description: "以查閱為基礎的資源選擇器，含時段",
    Charts_ColumnChartAria: "包含 {count} 個類別的直條圖",
    Charts_DonutChartAria: "包含 {count} 個類別的環圈圖",
    Charts_NoAnswers: "尚無答案。",
    Charts_NoResponses: "尚無回應。",
    Charts_Responses: "回應",
    Charts_ResponsesOverTime: "回應隨時間變化",
    Responses_Chart_Answer: "答案",
    Responses_Chart_Average: "平均值",
    Responses_Chart_AverageOf: "{count} 項的平均值",
    Responses_Chart_AveragePosition: "平均位置",
    Responses_Chart_AverageRange: "平均值（1–{max}）",
    Responses_Chart_AvgValue: "平均 {value}",
    Responses_Chart_Detractors: "貶損者（0–6）",
    Responses_Chart_Max: "最大",
    Responses_Chart_Maximum: "最大值",
    Responses_Chart_Median: "中位數",
    Responses_Chart_MentionOne: "{count} 次提及",
    Responses_Chart_MentionOther: "{count} 次提及",
    Responses_Chart_Min: "最小",
    Responses_Chart_Minimum: "最小值",
    Responses_Chart_NoAnswers: "尚無答案。",
    Responses_Chart_NoNumeric: "尚無數值答案。",
    Responses_Chart_NoRankings: "尚無排名。",
    Responses_Chart_NoScores: "尚無分數。",
    Responses_Chart_NotEnoughText: "文字不足，暫時無法摘要。",
    Responses_Chart_NpsScore: "NPS 分數",
    Responses_Chart_Option: "選項",
    Responses_Chart_Passives: "被動者（7–8）",
    Responses_Chart_Promoters: "推薦者（9–10）",
    Responses_Chart_ResponseOne: "份回應",
    Responses_Chart_ResponseOther: "份回應",
    Responses_Chart_Responses: "回應",
    Responses_Chart_ShowingAnswers: "顯示 {shown}/{total} 個答案。",
    Responses_Chart_Statement: "陳述",
    Responses_Chart_Statistic: "統計",
    Responses_Chart_StdDev: "標準差",
    Responses_Chart_StdDeviation: "標準差",
    Responses_Chart_Total: "總計",
    Responses_Chart_Value: "值",
    Responses_Dashboard_AllHidden: "所有問題均已從儀表板隱藏。使用「顯示隱藏的問題」即可將其還原。",
    Responses_Dashboard_AnsweredOf: "已回答 {answered}/{total}",
    Responses_Dashboard_AnsweredOfPinned: "已回答 {answered}/{total} · 已釘選",
    Responses_Dashboard_AveragedAcrossResponses: "所有回應的平均值",
    Responses_Dashboard_ByDay: "依日",
    Responses_Dashboard_ByMonth: "依月",
    Responses_Dashboard_ByWeek: "依週",
    Responses_Dashboard_ChartAuto: "自動",
    Responses_Dashboard_ChartBars: "橫條圖",
    Responses_Dashboard_ChartColumns: "直條圖",
    Responses_Dashboard_ChartDonut: "環圈圖",
    Responses_Dashboard_ChartGauge: "量表圖",
    Responses_Dashboard_ChartHistogram: "直方圖",
    Responses_Dashboard_ChartOptions: "圖表選項",
    Responses_Dashboard_ChartOptionsFor: "{title}的圖表選項",
    Responses_Dashboard_ChartStatistics: "統計",
    Responses_Dashboard_ChartTable: "表格",
    Responses_Dashboard_ChartWordFrequency: "詞頻",
    Responses_Dashboard_EmptyBody: "人們開始作答後，此儀表板會自動填入 — 包括重點數字、回應時間軸，以及值得關注的問題圖表。",
    Responses_Dashboard_EmptyTitle: "尚無回應",
    Responses_Dashboard_Hide: "從儀表板隱藏",
    Responses_Dashboard_Highlights: "重點",
    Responses_Dashboard_Last7Days: "過去 7 天",
    Responses_Dashboard_LatestDate: "最近 {date}",
    Responses_Dashboard_MedianTimeToComplete: "完成時間中位數",
    Responses_Dashboard_NoPriorWeek: "沒有可比較的上一週",
    Responses_Dashboard_OneEach: "各一次",
    Responses_Dashboard_Pin: "釘選到儀表板",
    Responses_Dashboard_QuestionFallback: "問題",
    Responses_Dashboard_QuestionsAnswered: "已回答的問題",
    Responses_Dashboard_RecordedOnSubmit: "提交時記錄",
    Responses_Dashboard_RepeatResponses: "{count} 份重複回應",
    Responses_Dashboard_ResponsesOverTime: "回應隨時間變化",
    Responses_Dashboard_ShowHidden: "顯示隱藏的問題",
    Responses_Dashboard_SinceMidnight: "自午夜起",
    Responses_Dashboard_Today: "今天",
    Responses_Dashboard_TotalResponses: "回應總數",
    Responses_Dashboard_UniqueRespondents: "不重複填答者",
    Responses_Dashboard_Unpin: "從儀表板取消釘選",
    Responses_Dashboard_UntitledQuestion: "未命名問題",
    Responses_Dashboard_VsPrevious7Days: "與前 7 天相比",
    Responses_Detail_Answers: "答案",
    Responses_Detail_AsTheForm: "依表單顯示",
    Responses_Detail_Cancel: "取消",
    Responses_Detail_Delete: "刪除",
    Responses_Detail_DeleteBody: "清單項目會移至網站資源回收筒，因此可以從中還原。",
    Responses_Detail_DeleteTitle: "要刪除此回應嗎？",
    Responses_Detail_Deleting: "正在刪除…",
    Responses_Detail_Draft: "草稿",
    Responses_Detail_Header: "第 {index} 份回應，共 {total} 份",
    Responses_Detail_LoadingAttachments: "正在載入附件…",
    Responses_Detail_Next: "下一份回應",
    Responses_Detail_NoAnswer: "無答案",
    Responses_Detail_Previous: "上一份回應",
    Responses_Detail_Print: "列印",
    Responses_Detail_Signature: "簽名",
    Responses_Detail_Signed: "已簽名",
    Responses_Detail_Took: "耗時 {duration}",
    Responses_Summary_AnsweredOfType: "已回答 {answered}/{total} · {type}",
    Responses_Summary_ByField: "依{title}",
    Responses_Summary_CompareBy: "比較依據…",
    Responses_Summary_EmptyBody: "每個問題都會在此處有自己的摘要。",
    Responses_Summary_NoComparison: "不比較",
    Responses_Summary_NothingToCompare: "沒有回應回答「{title}」,因此無可比較內容。",
    Responses_Summary_OtherNote: "類別超過 {max} 個的圖表會將最小的幾個歸入「其他」 — 將卡片切換為表格即可檢視每個值。",
    Responses_Summary_ResponseCountOne: "{count} 份回應",
    Responses_Summary_ResponseCountOther: "{count} 份回應",
    Responses_Summary_SeeAllAnswers: "在表格中檢視所有答案",
    Responses_Summary_SegmentNote: "顯示最大的 {groups} 個群組。選取多個答案的回應會出現在每個符合的群組中，因此各群組總數之和可能超過 {total}。",
    Responses_Summary_SplitBy: "依{title}分割",
    Responses_Summary_Untitled: "未命名",
    Responses_Table_Apply: "套用",
    Responses_Table_Cancel: "取消",
    Responses_Table_ClearSelection: "清除選取",
    Responses_Table_ColumnOrder: "欄順序",
    Responses_Table_ColumnsCount: "欄（{shown}/{total}）",
    Responses_Table_Delete: "刪除",
    Responses_Table_DeleteBody: "清單項目會移至網站資源回收筒，因此可以從中還原。",
    Responses_Table_DeleteSelected: "刪除選取項目",
    Responses_Table_DeleteTitleOne: "要刪除 {count} 份回應嗎？",
    Responses_Table_DeleteTitleOther: "要刪除 {count} 份回應嗎？",
    Responses_Table_Deleting: "正在刪除…",
    Responses_Table_MoveDown: "下移",
    Responses_Table_MoveDownFor: "下移{title}",
    Responses_Table_MoveUp: "上移",
    Responses_Table_MoveUpFor: "上移{title}",
    Responses_Table_NoColumns: "尚無可見的問題欄。",
    Responses_Table_NoMatch: "沒有符合目前篩選的回應。",
    Responses_Table_NothingToShow: "沒有可顯示的內容",
    Responses_Table_OpenResponse: "開啟此回應",
    Responses_Table_OrderNote: "「提交時間」和「提交者」一律排在最前。拖曳順序適用於問題欄。",
    Responses_Table_Reorder: "重新排序",
    Responses_Table_ResetColumns: "重設欄",
    Responses_Table_SelectResponse: "選取此回應",
    Responses_Table_SelectedOne: "已選取 {count} 份回應",
    Responses_Table_SelectedOther: "已選取 {count} 份回應",
    Responses_Table_ShowAll: "全部顯示",
    Responses_Table_ShowTheseQuestions: "顯示這些問題",
    Responses_Table_Submitted: "提交時間",
    Responses_Table_SubmittedBy: "提交者",
    Responses_Table_ToggleSelection: "切換選取",
    Responses_Table_Unknown: "未知",
    Responses_Table_Untitled: "未命名",
    Responses_View_AllTime: "所有時間",
    Responses_View_AnyAnswer: "任何答案",
    Responses_View_Clear: "清除",
    Responses_View_CopyShareLink: "複製共用連結",
    Responses_View_CountFiltered: "{shown}/{total} 份回應",
    Responses_View_CountOne: "{count} 份回應",
    Responses_View_CountOther: "{count} 份回應",
    Responses_View_Dashboard: "儀表板",
    Responses_View_DateRange: "日期範圍",
    Responses_View_EmptyBody: "共用表單即可開始收集。答案會儲存至「{list}」,並立即顯示在此處。",
    Responses_View_EmptyTitle: "尚無回應",
    Responses_View_ExportCsv: "匯出 CSV",
    Responses_View_FilterByAnswer: "依答案篩選",
    Responses_View_FilterByQuestion: "依問題篩選",
    Responses_View_FilterValue: "篩選值",
    Responses_View_Last30Days: "過去 30 天",
    Responses_View_Last7Days: "過去 7 天",
    Responses_View_Last90Days: "過去 90 天",
    Responses_View_LoadError: "無法載入回應。請先發佈一次表單以建立清單欄，然後再試一次。",
    Responses_View_Loading: "正在載入回應…",
    Responses_View_MoreActions: "更多回應動作",
    Responses_View_PreviewForm: "預覽表單",
    Responses_View_Refresh: "重新整理",
    Responses_View_ResponsesTab: "回應（{count}）",
    Responses_View_SearchPlaceholder: "搜尋所有答案",
    Responses_View_SegmentOption: "{label}({count})",
    Responses_View_SelectValue: "選取值",
    Responses_View_Summary: "摘要",
    Responses_View_Today: "今天",
    Responses_View_Truncated: "此清單的回應數超過 Smart Forms 一次可載入的數量。僅顯示最新的 {count} 份 — 請在 Microsoft Lists 中開啟該清單以檢視完整內容。",
    Responses_View_TryAgain: "再試一次",
    Responses_View_Untitled: "未命名",
    Responses_Approval_Column: "核准",
    Responses_Approval_ReviewerColumn: "審核者",
    Responses_Approval_CommentColumn: "審核者註解",
    Responses_Approval_Pending: "待核准",
    Responses_Approval_Approved: "已核准",
    Responses_Approval_Rejected: "已拒絕",
    Responses_Approval_AnyStatus: "任何核准狀態",
    Responses_Approval_FilterLabel: "依核准狀態篩選",
    Responses_Approval_ApproveSelected: "核准所選項目",
    Responses_Approval_RejectSelected: "拒絕所選項目",
    Responses_Approval_BulkFailed: "有 {count} 份回應無法更新。請再試一次。",
    Responses_Approval_Approve: "核准",
    Responses_Approval_Reject: "拒絕",
    Responses_Approval_Reset: "重設為待核准",
    Responses_Approval_CommentLabel: "註解（選填）",
    Responses_Approval_ReviewedBy: "審核者：{name}",
    Responses_Approval_Error: "無法儲存該決定。請再試一次。",
    Responses_Dashboard_ApprovalStatus: "等待審核",
    Responses_Dashboard_ApprovalBreakdown: "{pending} 份待核准，{approved} 份已核准，{rejected} 份已拒絕",
    Responses_Dashboard_TimelineCoarsened: "日期範圍較長，因此時間軸已依較粗的粒度分組（{grain}）。",
    Responses_Dashboard_TimelineTruncated: "日期範圍非常長，因此僅顯示最近的 {count} 個期間。",
    Service_Item_DefaultTitle: "回應 — {date}",
    Service_Email_ApprovalSubject: "您的回應{status} — {title}",
    Service_Email_ApprovalHeading: "您的回應{status}",
    Service_Email_ApprovalIntro: "審核者已將您對「{title}」的回應標記為{status}。",
    Service_Email_ApprovalCommentLabel: "審核者註解",
    Service_Approval_Approved: "已核准",
    Service_Approval_Rejected: "已拒絕",
    Service_Approval_Pending: "待核准",
    Service_Lookup_InvalidFilter: "查閱篩選條件無效。",
    Service_Edit_NotAllowed: "此表單不允許編輯已提交的回應。",
    Service_Edit_NotYours: "您只能編輯自己的回應。",
    Service_Signature_AttachmentLabel: "簽名",
    PropertyPane_ListsLoadFailed: "無法載入此網站上的清單。",
    PropertyPane_EnterListName: "請先輸入新清單的名稱。",
    PropertyPane_CreatingList: "正在建立「{name}」…",
    PropertyPane_ListCreated: "已建立並選取清單「{title}」。",
    PropertyPane_ListAlreadyExists: "名為「{name}」的清單已存在 — 請從上方下拉式清單中選取。",
    PropertyPane_CreateListFailed: "無法建立清單。請檢查您是否有權限在此網站上建立清單。",
    PropertyPane_Description: "選擇用於儲存表單回應的 SharePoint 清單，或建立新清單。其他所有內容（問題、外觀、通知）均可直接在頁面上編輯。",
    PropertyPane_ResponseList_GroupName: "回應清單",
    PropertyPane_ListDropdown_Label: "將回應儲存至此清單",
    PropertyPane_ResponsesGoTo: "回應將儲存至「{name}」。",
    PropertyPane_PickList: "請選擇一個清單，或在下方建立。",
    PropertyPane_LoadingLists: "正在載入清單…",
    PropertyPane_NewListName_Label: "或建立新清單",
    PropertyPane_NewListName_Placeholder: "新清單名稱",
    PropertyPane_CreateList_Button: "建立清單",
    PropertyPane_Tips_GroupName: "提示",
    PropertyPane_Tip_AutoSave: "問題和設定會在您編輯時自動儲存 — 無需儲存或發佈頁面。",
    PropertyPane_Tip_Permissions: "填答者需要有權限將項目新增至回應清單。如果有人回報提交時發生錯誤，請檢查清單權限。",
    PropertyPane_Tip_Share: "使用頁面上的「收集回應」可建立清單欄並取得可共用的填寫連結。",
    App_ErrorBoundary_Title: "Smart Forms — 轉譯錯誤",
    App_ErrorBoundary_Message: "訊息：",
    App_ErrorBoundary_Stack: "堆疊：",
    App_ErrorBoundary_NoStack: "（無可用堆疊）",
    App_ErrorBoundary_ConsoleNote: "完整詳細資料也已寫入瀏覽器主控台。",
    App_DefaultQuestionTitle: "問題 {number}",
    App_Error_ListMissing: "為此表單設定的清單已不存在。請在 Web 組件設定中選擇其他清單。",
    App_Error_LoadConfig: "載入表單設定時發生錯誤。",
    App_Error_Unable: "無法載入表單。",
    App_Publish_ConflictNotice: "「{title}」已有不同類型（{type}）的清單欄。請重新命名該問題以便建立新欄，或將其類型改回。",
    App_Publish_ConflictUnnamedQuestion: "某個問題",
    App_Publish_ColumnsAddedOne: "已將 {count} 欄新增至「{list}」。",
    App_Publish_ColumnsAddedOther: "已將 {count} 欄新增至「{list}」。",
    App_Publish_TheList: "該清單",
    App_Publish_UpToDate: "回應清單已是最新。",
    App_Publish_Error: "無法建立清單欄。這通常表示您對回應清單沒有「管理清單」權限，但在停用自訂指令碼的網站上也可能發生。請查看瀏覽器主控台中的底層錯誤，或再試一次。",
    App_Placeholder_Title: "Smart Forms",
    App_Placeholder_Description: "在 SharePoint 清單之上建立精美的表單 — {count} 種問題類型、分支邏輯、檔案上傳、可共用的填寫連結以及結果儀表板。",
    App_Placeholder_ChooseList: "選擇或建立清單",
    App_Placeholder_Hint: "編輯頁面並設定此 Web 組件即可開始使用。",
    App_Loading: "正在載入表單…",
    App_OpenSettings: "開啟設定",
    App_Tab_Questions: "問題",
    App_Tab_QuestionsWithCount: "問題（{count}）",
    App_Tab_Responses: "回應",
    App_Tab_Responses_Title: "回應會儲存至「{list}」",
    App_Templates_Start: "從範本開始",
    App_Settings_Title: "表單設定 — 外觀、通知、存取",
    App_Settings_AriaLabel: "表單設定",
    App_Preview: "預覽",
    App_Preview_Close: "關閉預覽",
    App_Preview_Hint: "預覽 — 您在此提交的任何內容都不會儲存。驗證和分支的行為與填答者看到的完全一致。",
    App_Publish_GettingReady: "正在準備…",
    App_Publish_CollectResponses: "收集回應",
    App_Publish_Share: "共用",
    App_Retry: "重試",
    App_SaveError_Banner: "無法儲存您的上次變更。請檢查網路連線，然後再試一次。",
    App_Preflight_BlockingTitle: "收集前請先修正以下問題",
    App_Preflight_WarningTitle: "建議先檢查",
    App_Preflight_BlockingText: "這些問題會導致已發佈的表單無法正常運作。",
    App_Preflight_WarningText: "沒有任何故障，但通常建議在共用連結之前先修正這些問題。",
    App_Preflight_GoTo: "前往",
    App_Preflight_CollectAnyway: "仍要收集回應",
    App_Preflight_Back: "返回表單",
    App_Cancel: "取消",
    App_Done: "完成",
    App_Share_Title: "您的表單已可共用",
    App_Share_SubText: "將此連結傳送給需要填寫表單的任何人。",
    App_Share_LinkAriaLabel: "共用連結",
    App_Share_Copy: "複製",
    App_Share_Copied: "已複製",
    App_Share_AddItemsEmphasis: "新增項目",
    App_Share_PermissionNote: "填答者需要有權限向「{title}」{addItems},並有權存取此頁面。如果有人在提交時遇到錯誤，幾乎總是這個原因。",
    App_Share_PrefillNote: "您可以在連結中加入欄名稱來預先回答問題，例如 {example}。",
    App_Templates_ReplaceWarning: "選擇範本將取代您目前的問題。",
    App_Templates_PickStart: "選擇一個起點 — 之後可以變更任何內容。",
    App_Templates_Empty: "空白",
    App_Templates_QuestionCount: "{count} 個問題",
    App_SaveChip_SavingTitle: "正在儲存您的最新編輯",
    App_SaveChip_Saving: "正在儲存…",
    App_SaveChip_FailedTitle: "無法儲存您的上次編輯。請檢查網路連線並再試一次。",
    App_SaveChip_Failed: "儲存失敗",
    App_SaveChip_SavedTitle: "所有變更均已儲存",
    App_SaveChip_Saved: "已儲存",
    Service_DefaultFormTitle: "Smart Forms",
    Service_Email_NewResponseSubject: "新回應 — {title}",
    Service_Email_NewResponseHeading: "新回應：{title}",
    Service_Email_NewResponseIntro: "有人剛剛提交了回應 — {date}。",
    Service_Email_ReceiptSubject: "您的回應 — {title}",
    Service_Email_ReceiptHeading: "感謝您的回應！",
    Service_Email_ReceiptIntro: "這是您提交至「{title}」的內容副本。",
    App_History_Title: "版本歷程記錄",
    App_History_RestoredNotice: "已還原 {date} 儲存的版本。請檢閱，然後使用「收集回應」發佈任何新問題。",
    App_History_Undo: "復原還原",
    App_Share_CopyManual: "您的瀏覽器封鎖了複製。請選取上方的連結，然後按 Ctrl+C（Mac 上為 Cmd+C）進行複製。",
    App_Share_TeamsNote: "您正在 Microsoft Teams 中。此連結會直接開啟 SharePoint 頁面，因此收件者需要有該網站的存取權。",
    App_Share_PrefillNotSecure: "預先填入的答案僅為方便之用：任何擁有連結的人都可以變更，因此切勿將其視為安全邊界。",
    Designer_Section_DropHere: "將問題拖放到此處",
    Designer_Section_DropEnd: "拖放到此處以移至此區段末尾",
    Designer_Rules_RemovedOne: "已移除 1 項不再適用的分支規則。",
    Designer_Rules_RemovedOther: "已移除 {count} 項不再適用的分支規則。",
    Designer_Settings_AllowEdit: "允許填答者編輯其回應",
    Designer_Settings_AllowEditHint: "填答者可以重新開啟並更新其提交的內容。每個人只能編輯自己的回應。",
    Designer_Settings_EnableApproval: "啟用核准工作流程",
    Designer_Settings_ApprovalNotify: "決定後以電子郵件通知填答者",
    Designer_Settings_ApprovalHint: "下次發佈時，將在回應清單中新增核准欄。擁有者可在「回應」索引標籤中核准或拒絕回應。",
    Designer_History_Title: "版本歷程記錄",
    Designer_History_Intro: "此表單問題和設定的先前已儲存版本。還原會將某個版本載入設計工具中；您可以復原，只有在發佈時才會建立新問題。",
    Designer_History_Loading: "正在載入版本...",
    Designer_History_Empty: "找不到先前的版本。版本歷程記錄需要為「Smart Forms Config」清單啟用版本設定，且至少有一次已儲存的編輯。",
    Designer_History_Latest: "最新",
    Designer_History_LatestTitle: "這是目前使用中的版本",
    Designer_History_By: "作者：{name}",
    Designer_History_UnknownAuthor: "未知作者",
    Designer_History_VersionLabel: "版本 {label}",
    Designer_History_Preview: "預覽",
    Designer_History_Restore: "還原",
    Designer_History_QuestionsOne: "1 個問題",
    Designer_History_QuestionsOther: "{count} 個問題",
    Designer_History_LoadFailed: "無法載入此版本。",
    Designer_History_ConfirmTitle: "還原此版本？",
    Designer_History_ConfirmText: "表單將被取代為 {date} 儲存的版本（{count} 個問題）。還原後可立即復原。"
  };
});
